CREATE OR REPLACE TRANSIENT TABLE REPORTING.SXF.SEGMENT_PRODUCT (
    SESSION_START_DATE DATE,
    SESSION_START_HOUR TIMESTAMP_NTZ(9),
    PRODUCT_ID VARCHAR(16777216),
    IS_BUNDLE VARCHAR(16777216),
    BUNDLE_PRODUCT_ID VARCHAR(16777216),
    IS_ACTIVATING VARCHAR(16777216),
    MEMBERSHIP_STATUS VARCHAR(16777216),
    LIST_VIEW_TOTAL NUMBER(38,0),
    PDP_VIEW_TOTAL NUMBER(38,0),
    PA_TOTAL NUMBER(38,0),
    OC_TOTAL FLOAT,
    SS_PDP_VIEW NUMBER(38,0),
    SS_PRODUCT_ADDED NUMBER(38,0),
    SS_PRODUCT_ORDERED FLOAT,
    REFRESH_DATETIME TIMESTAMP_LTZ(9)
);
