CREATE OR REPLACE VIEW LAKE_CONSOLIDATED_VIEW.ULTRA_MERCHANT.CREDITCARD  (
    data_source_id,
    meta_company_id,
    creditcard_id,
    customer_id,
    address_id,
    cnh,
    tokenized_card_num,
    card_type,
    exp_month,
    exp_year,
    name_on_card,
    last_four_digits,
    method,
    datetime_added,
    datetime_last_used,
    statuscode,
    datetime_modified,
    meta_original_creditcard_id,
    hvr_is_deleted,
    meta_create_datetime,
    meta_update_datetime
) AS
SELECT
    data_source_id,
    meta_company_id,
    creditcard_id,
    customer_id,
    address_id,
    cnh,
    card_num as tokenized_card_num,
    card_type,
    exp_month,
    exp_year,
    name_on_card,
    last_four_digits,
    method,
    datetime_added,
    datetime_last_used,
    statuscode,
    datetime_modified,
    meta_original_creditcard_id,
    hvr_is_deleted,
    meta_create_datetime,
    meta_update_datetime
FROM LAKE_CONSOLIDATED.ULTRA_MERCHANT.CREDITCARD;
