from snowflake.snowpark.types import (
    StructType,
    StructField,
    IntegerType,
    StringType,
    ArrayType,
    BooleanType,
    MapType,
    LongType,
    DoubleType,
)

javascript_sx_schema = StructType(
    [
        StructField(
            "_metadata",
            StructType(
                [
                    StructField("bundled", ArrayType(StringType()), True),
                    StructField("bundledConfigIds", ArrayType(StringType()), True),
                    StructField("bundledIds", ArrayType(StringType()), True),
                    StructField("unbundled", ArrayType(StringType()), True),
                    StructField("unbundledConfigIds", ArrayType(StringType()), True),
                ]
            ),
        ),
        StructField("anonymousId", StringType(), True),
        StructField("category", StringType(), True),
        StructField("channel", StringType(), True),
        StructField(
            "context",
            StructType(
                [
                    StructField(
                        "campaign",
                        StructType(
                            [
                                StructField("amp;utm_campaign", StringType(), True),
                                StructField("amp;utm_medium", StringType(), True),
                                StructField("amp;utm_source", StringType(), True),
                                StructField("amp;utm_term", StringType(), True),
                                StructField("content", StringType(), True),
                                StructField("id", StringType(), True),
                                StructField("keyword", StringType(), True),
                                StructField("medium", StringType(), True),
                                StructField("name", StringType(), True),
                                StructField("source", StringType(), True),
                                StructField("term", StringType(), True),
                                StructField("tm_medium", StringType(), True),
                                StructField("utm_campaign", StringType(), True),
                                StructField("utm_content", StringType(), True),
                                StructField("utm_medium", StringType(), True),
                                StructField("utm_source", StringType(), True),
                                StructField("utm_term", StringType(), True),
                            ]
                        ),
                    ),
                    StructField("ip", StringType(), True),
                    StructField(
                        "library",
                        StructType(
                            [
                                StructField("name", StringType(), True),
                                StructField("version", StringType(), True),
                            ]
                        ),
                    ),
                    StructField("locale", StringType(), True),
                    StructField(
                        "page",
                        StructType(
                            [
                                StructField("path", StringType(), True),
                                StructField("referrer", StringType(), True),
                                StructField("search", StringType(), True),
                                StructField("title", StringType(), True),
                                StructField("url", StringType(), True),
                            ]
                        ),
                    ),
                    StructField(
                        "protocols",
                        StructType(
                            [
                                StructField("sourceId", StringType(), True),
                                StructField(
                                    "violations",
                                    ArrayType(
                                        StructType(
                                            [
                                                StructField(
                                                    "description", StringType(), True
                                                ),
                                                StructField(
                                                    "field", StringType(), True
                                                ),
                                                StructField("type", StringType(), True),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    StructField("userAgent", StringType(), True),
                ]
            ),
        ),
        StructField("event", StringType(), True),
        StructField("integrations", StringType(), True),
        StructField("messageId", StringType(), True),
        StructField("name", StringType(), True),
        StructField("originalTimestamp", StringType(), True),
        StructField("projectId", StringType(), True),
        StructField(
            "properties",
            StructType(
                [
                    StructField(
                        "promos",
                        StructType(
                            [
                                StructField("promo_code", StringType(), True),
                                StructField("promo_price", DoubleType(), True),
                                StructField("display_on_pdp", LongType(), True),
                                StructField("promo_type_id", StringType(), True),
                                StructField("promo_label", StringType(), True),
                            ]
                        ),
                    ),
                    StructField("list_category", StringType(), True),
                    StructField("bundle_price", DoubleType(), True),
                    StructField("subcategory", StringType(), True),
                    StructField("store_id", StringType(), True),
                    StructField("availableTokenQuantity", LongType(), True),
                    StructField("tests_active", StringType(), True),
                    StructField("email", StringType(), True),
                    StructField("user_id", StringType(), True),
                    StructField("angle", StringType(), True),
                    StructField("asset_id", StringType(), True),
                    StructField("automated_test", BooleanType(), True),
                    StructField("avg_recommended", DoubleType(), True),
                    StructField("avg_star_rating", DoubleType(), True),
                    StructField("brand", StringType(), True),
                    StructField("bundle_alias", StringType(), True),
                    StructField("bundle_index", LongType(), True),
                    StructField("bundle_name", StringType(), True),
                    StructField("bundle_product_id", StringType(), True),
                    StructField("bundle_product_id_hit", StringType(), True),
                    StructField("bundle_quantity", LongType(), True),
                    StructField("bundle_retail_price", DoubleType(), True),
                    StructField("bundle_sale_price", DoubleType(), True),
                    StructField("bundle_url", StringType(), True),
                    StructField("bundle_vip_price", DoubleType(), True),
                    StructField("cart_id", StringType(), True),
                    StructField("category", StringType(), True),
                    StructField("clickable", BooleanType(), True),
                    StructField("clickable_url", StringType(), True),
                    StructField("content_asset_id", LongType(), True),
                    StructField("coupon", StringType(), True),
                    StructField("creative", StringType(), True),
                    StructField(
                        "custom_vars",
                        StructType(
                            [
                                StructField("altText", StringType(), True),
                                StructField("autoplay", StringType(), True),
                                StructField("backgroundSize", StringType(), True),
                                StructField("bodyText", StringType(), True),
                                StructField("bottomMarginDesktop", StringType(), True),
                                StructField("bottomMarginMobile", StringType(), True),
                                StructField("caption", StringType(), True),
                                StructField("carouselAlignment", StringType(), True),
                                StructField("cellsTall", StringType(), True),
                                StructField("cellsWide", StringType(), True),
                                StructField("ctaColor", StringType(), True),
                                StructField("ctaText", StringType(), True),
                                StructField("ctaTheme", StringType(), True),
                                StructField("ctaUrl", StringType(), True),
                                StructField("flags", StringType(), True),
                                StructField("fplId", StringType(), True),
                                StructField("gridPosition", StringType(), True),
                                StructField("horizontalFocus", StringType(), True),
                                StructField("imagePosition", StringType(), True),
                                StructField("isVertical", StringType(), True),
                                StructField("marginBottomDesktop", StringType(), True),
                                StructField("marginBottomMobile", StringType(), True),
                                StructField("maxColumns", StringType(), True),
                                StructField("minColumns", StringType(), True),
                                StructField("numPerOrder", StringType(), True),
                                StructField("numProducts", StringType(), True),
                                StructField("order", StringType(), True),
                                StructField("promoText", StringType(), True),
                                StructField("slotCount", StringType(), True),
                                StructField("textColor", StringType(), True),
                                StructField("textPosition", StringType(), True),
                                StructField("textUnderCarousel", StringType(), True),
                                StructField("title", StringType(), True),
                                StructField("type", StringType(), True),
                                StructField("verticalFocus", StringType(), True),
                                StructField("videoUrl", StringType(), True),
                            ]
                        ),
                    ),
                    StructField("customer_bucket_group", StringType(), True),
                    StructField("customer_id", StringType(), True),
                    StructField("dmg_code", StringType(), True),
                    StructField("error_details", StringType(), True),
                    StructField("error_message", StringType(), True),
                    StructField("error_status_code", StringType(), True),
                    StructField("feature", StringType(), True),
                    StructField(
                        "filter",
                        ArrayType(
                            StructType(
                                [
                                    StructField("type", StringType(), True),
                                    StructField("value", StringType(), True),
                                ]
                            )
                        ),
                    ),
                    StructField(
                        "filters",
                        ArrayType(
                            StructType(
                                [
                                    StructField("type", StringType(), True),
                                    StructField("value", StringType(), True),
                                ]
                            )
                        ),
                    ),
                    StructField("fpl_id", StringType(), True),
                    StructField("gateway", BooleanType(), True),
                    StructField("grid_label", StringType(), True),
                    StructField("has_member_models", BooleanType(), True),
                    StructField("has_reviews", BooleanType(), True),
                    StructField("has_video", BooleanType(), True),
                    StructField("image_id", StringType(), True),
                    StructField("image_url", StringType(), True),
                    StructField("inventory_availability", LongType(), True),
                    StructField("is_bundle", BooleanType(), True),
                    StructField("is_default_model", BooleanType(), True),
                    StructField("is_member_model", BooleanType(), True),
                    StructField("is_plus_size", BooleanType(), True),
                    StructField("is_preorder", BooleanType(), True),
                    StructField("label", StringType(), True),
                    StructField("list", StringType(), True),
                    StructField("list_id", StringType(), True),
                    StructField("location", StringType(), True),
                    StructField("logged_in_status", BooleanType(), True),
                    StructField("loggedin_status", BooleanType(), True),
                    StructField("membership_status", StringType(), True),
                    StructField("model_height", StringType(), True),
                    StructField("model_id", StringType(), True),
                    StructField("model_name", StringType(), True),
                    StructField("name", StringType(), True),
                    StructField("new_color", StringType(), True),
                    StructField("new_product_id", LongType(), True),
                    StructField("new_value", StringType(), True),
                    StructField("p_source", StringType(), True),
                    StructField("page_name", StringType(), True),
                    StructField("path", StringType(), True),
                    StructField("position", StringType(), True),
                    StructField("previous_color", StringType(), True),
                    StructField("previous_product_id", LongType(), True),
                    StructField("previous_value", StringType(), True),
                    StructField("price", DoubleType(), True),
                    StructField("product_id", StringType(), True),
                    StructField("product_id_hit", StringType(), True),
                    StructField(
                        "products",
                        ArrayType(
                            StructType(
                                [
                                    StructField("review_rating", DoubleType(), True),
                                    StructField("subcategory", StringType(), True),
                                    StructField(
                                        "inventory_availability", LongType(), True
                                    ),
                                    StructField("grid_position", LongType(), True),
                                    StructField("bundle_alias", StringType(), True),
                                    StructField("bundle_name", StringType(), True),
                                    StructField(
                                        "bundle_product_id", StringType(), True
                                    ),
                                    StructField("bundle_quantity", StringType(), True),
                                    StructField(
                                        "bundle_retail_price", StringType(), True
                                    ),
                                    StructField(
                                        "bundle_sale_price", StringType(), True
                                    ),
                                    StructField("bundle_url", StringType(), True),
                                    StructField("bundle_vip_price", StringType(), True),
                                    StructField("category", StringType(), True),
                                    StructField("coupon", StringType(), True),
                                    StructField("grid_label", StringType(), True),
                                    StructField("is_bundle", BooleanType(), True),
                                    StructField("name", StringType(), True),
                                    StructField("position", LongType(), True),
                                    StructField("price", DoubleType(), True),
                                    StructField("product_id", StringType(), True),
                                    StructField("quantity", LongType(), True),
                                    StructField("retail_price", DoubleType(), True),
                                    StructField("sale_price", DoubleType(), True),
                                    StructField("size", StringType(), True),
                                    StructField("sized_product_id", LongType(), True),
                                    StructField("sized_sku", StringType(), True),
                                    StructField("sku", StringType(), True),
                                    StructField("url", StringType(), True),
                                    StructField("variant", StringType(), True),
                                    StructField("is_preorder", BooleanType(), True),
                                    StructField("review_num", LongType(), True),
                                    StructField("has_reviews", BooleanType(), True),
                                    StructField("avg_start_rating", LongType(), True),
                                    StructField("vip_price", DoubleType(), True),
                                ]
                            )
                        ),
                    ),
                    StructField("avg_start_rating", LongType(), True),
                    StructField("quantity", LongType(), True),
                    StructField("query", StringType(), True),
                    StructField("referrer", StringType(), True),
                    StructField("referring_page_module", StringType(), True),
                    StructField("retail_price", DoubleType(), True),
                    StructField("review_num", LongType(), True),
                    StructField("review_rating", DoubleType(), True),
                    StructField("sale_price", DoubleType(), True),
                    StructField("search", StringType(), True),
                    StructField("session_id", StringType(), True),
                    StructField("show_id", StringType(), True),
                    StructField("size", StringType(), True),
                    StructField("sized_product_id", StringType(), True),
                    StructField("sized_sku", StringType(), True),
                    StructField("sku", StringType(), True),
                    StructField("sort", StringType(), True),
                    StructField("sort_label", StringType(), True),
                    StructField("source", StringType(), True),
                    StructField("storeGroupId", LongType(), True),
                    StructField("store_group_id", StringType(), True),
                    StructField("title", StringType(), True),
                    StructField("total_length", LongType(), True),
                    StructField("url", StringType(), True),
                    StructField("user_status_initial", StringType(), True),
                    StructField("variant", StringType(), True),
                    StructField("vip_price", DoubleType(), True),
                ]
            ),
        ),
        StructField("receivedAt", StringType(), True),
        StructField("sentAt", StringType(), True),
        StructField("timestamp", StringType(), True),
        StructField(
            "traits",
            StructType(
                [
                    StructField("is_interested_in_sport", BooleanType(), True),
                    StructField("color_brights", BooleanType(), True),
                    StructField("vibe_extra", BooleanType(), True),
                    StructField("color_jewel_tones", BooleanType(), True),
                    StructField("vibe_cute", BooleanType(), True),
                    StructField("color_blacks", BooleanType(), True),
                    StructField("color_patterns", BooleanType(), True),
                    StructField("color_pastels", BooleanType(), True),
                    StructField("vibe_sexy", BooleanType(), True),
                    StructField("color_neutrals", BooleanType(), True),
                    StructField("vibe_chill", BooleanType(), True),
                    StructField("is_interested_in_lounge", BooleanType(), True),
                    StructField("birth_day", StringType(), True),
                    StructField("birth_month", StringType(), True),
                    StructField("birth_year", StringType(), True),
                    StructField("birthday", StringType(), True),
                    StructField("blind_date_style_preference", StringType(), True),
                    StructField("bottom-size", StringType(), True),
                    StructField("bra-size", StringType(), True),
                    StructField("bra_size", StringType(), True),
                    StructField("bralette-size", StringType(), True),
                    StructField("bralette_size", StringType(), True),
                    StructField("color1", BooleanType(), True),
                    StructField("color2", BooleanType(), True),
                    StructField("color3", BooleanType(), True),
                    StructField("color4", BooleanType(), True),
                    StructField("color5", BooleanType(), True),
                    StructField("color6", BooleanType(), True),
                    StructField("color_preference", StringType(), True),
                    StructField("confident_style_preference", StringType(), True),
                    StructField("createdAt", StringType(), True),
                    StructField("customer_referrer_id", StringType(), True),
                    StructField("email", StringType(), True),
                    StructField("everyday_mood", StringType(), True),
                    StructField("flirting_style", StringType(), True),
                    StructField("going_out_showing_out", StringType(), True),
                    StructField("is_interested_in_boxers", BooleanType(), True),
                    StructField("is_interested_in_bralettes", BooleanType(), True),
                    StructField("is_interested_in_bras", BooleanType(), True),
                    StructField("is_interested_in_lingerie", BooleanType(), True),
                    StructField("is_interested_in_sleepwear", BooleanType(), True),
                    StructField("is_interested_in_undies", BooleanType(), True),
                    StructField("lingerie-sleep-size", StringType(), True),
                    StructField("lingerie_shop_preference", StringType(), True),
                    StructField("lingerie_sleep_size", StringType(), True),
                    StructField("lingerie_style_preference", StringType(), True),
                    StructField("membership_id", StringType(), True),
                    StructField("membership_status", StringType(), True),
                    StructField("potential_male_customer", BooleanType(), True),
                    StructField("shipping_zip", StringType(), True),
                    StructField("style1", BooleanType(), True),
                    StructField("style2", BooleanType(), True),
                    StructField("style3", BooleanType(), True),
                    StructField("style4", BooleanType(), True),
                    StructField("underwear_size", StringType(), True),
                    StructField("user_id", StringType(), True),
                    StructField("username", StringType(), True),
                    StructField("zip_code", StringType(), True),
                ]
            ),
        ),
        StructField("type", StringType(), True),
        StructField("userId", StringType(), True),
        StructField("version", LongType(), True),
    ]
)
