CREATE OR REPLACE TABLE fabletics.gc_historical_customer_request
(
    customer_segment                                      VARCHAR(250),
    brand                                                 VARCHAR(20),
    vip_cohort                                            DATE,
    payment_date                                          DATE,
    billing_type                                          VARCHAR(30),
    store_region                                          VARCHAR(32),
    customer_count                                        INT,
    cash_gross_revenue                                    NUMBER(38, 10),
    cash_net_rev                                          NUMBER(38, 10),
    cash_margin_pre_return                                NUMBER(38, 10),
    cash_gross_profit                                     NUMBER(38, 12),
    product_order_cash_refund_amount                      NUMBER(38, 10),
    product_order_cash_chargeback_amount                  NUMBER(38, 10),
    billing_cash_refund_amount                            NUMBER(38, 10),
    billing_cash_chargeback_amount                        NUMBER(38, 10),
    product_order_landed_product_cost_amount              NUMBER(38, 10),
    product_order_exchange_product_cost_amount            NUMBER(38, 10),
    product_order_reship_product_cost_amount              NUMBER(38, 10),
    product_order_shipping_cost_amount                    NUMBER(38, 12),
    product_order_reship_shipping_cost_amount             NUMBER(38, 12),
    product_order_exchange_shipping_cost_amount           NUMBER(38, 12),
    product_order_return_shipping_cost_amount             NUMBER(38, 10),
    product_order_shipping_supplies_cost_amount           NUMBER(38, 12),
    product_order_exchange_shipping_supplies_cost_amount  NUMBER(38, 12),
    product_order_reship_shipping_supplies_cost_amount    NUMBER(38, 12),
    product_order_misc_cogs_amount                        NUMBER(38, 12),
    product_order_cost_product_returned_resaleable_amount NUMBER(38, 12),
    product_order_variable_gms_cost_amount                NUMBER(38, 12),
    billing_variable_gms_cost_amount                      NUMBER(38, 12),
    product_order_payment_processing_cost_amount          NUMBER(38, 12),
    billing_payment_processing_cost_amount                NUMBER(38, 12),
    product_order_variable_warehouse_cost_amount          NUMBER(38, 12),
    selling_expenses                                      NUMBER(38, 12),
    gfc_fixed                                             NUMBER(38, 12),
    gfc_back_office                                       NUMBER(38, 12),
    gms_fixed                                             NUMBER(38, 12),
    gms_back_office                                       NUMBER(38, 12),
    meta_create_datetime                                  TIMESTAMP_LTZ(9)
);
