CREATE TRANSIENT TABLE IF NOT EXISTS gms.bos_boss_forecast(
    billing_month DATE,
    storefront VARCHAR(55),
    m1_new_vips NUMBER(38,0),
    first_successful_new_vips NUMBER(38,6),
    m1_grace_vips NUMBER(38,0),
    first_successful_grace_vips NUMBER(38,6),
    first_successful_billed_credit_rate NUMBER(15,2),
    first_successful_billed_credit_rate_trailing NUMBER(15,2),
    retry_rate NUMBER(15,2),
    retry_rate_trailing_6_months NUMBER(15,2),
    m2_tenure_vips NUMBER(38,10),
    m2_plus_vips NUMBER(38,10),
    fpa_m2_credit_billings NUMBER(38,10),
    fpa_m2_plus_credit_billings NUMBER(38,10),
    m2_billing_credit_rate_fpa NUMBER(38,12),
    m2_plus_billing_rate NUMBER(38,25),
    total_billing_fpa_forecast NUMBER(38,10),
    meta_row_hash NUMBER(38,0),
    meta_create_datetime TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    meta_update_datetime TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
