CREATE OR REPLACE TABLE GMS.GMS_TRUSTPILOT_AND_CONSUMERAFFAIRS_LIST (
	STORE_ID NUMBER(38,0),
	BUSINESS_UNIT VARCHAR(8000),
	CUSTOMER_ID NUMBER(38,0),
	FIRSTNAME VARCHAR(250),
	LASTNAME VARCHAR(250),
	EMAIL VARCHAR(250),
	PHONE VARCHAR(250),
	CAMPAIGN_NAME VARCHAR(250),
	DATETIME_ADDED TIMESTAMP_NTZ(3),
	CITY VARCHAR(250),
	STATE VARCHAR(10),
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(3),
	META_UPDATE_DATETIME TIMESTAMP_LTZ(3)
);
