CREATE TRANSIENT TABLE IF NOT EXISTS gms.genesys_segment (
    conversation_id STRING,
    participant_id STRING,
    session_id STRING,
    segment_start TIMESTAMP_LTZ(3),
    segment_end TIMESTAMP_LTZ(3),
    queue_id STRING,
    wrapup_code STRING,
    wrapup_note TEXT,
    error_code STRING,
    disconnect_type STRING,
    segment_type STRING,
    requested_language_id STRING,
    source_conversation_id STRING,
    destination_conversation_id STRING,
    source_session_id STRING,
    destination_session_id STRING,
    conference BOOLEAN,
    group_id STRING,
    subject STRING,
    audio_muted BOOLEAN,
    video_muted BOOLEAN,
    meta_row_hash NUMBER(38, 0),
    meta_create_datetime TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
    meta_update_datetime TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP
);
