CREATE TRANSIENT TABLE IF NOT EXISTS gms.genesys_conversation (
    conversation_id STRING,
    conversation_start TIMESTAMP_LTZ(3),
    conversation_end TIMESTAMP_LTZ(3),
    media_stats_min_conversation_mos NUMBER(38, 16),
    media_stats_min_conversation_rfactor NUMBER(38, 16),
    originating_direction STRING,
    participant_id STRING,
    participant_name STRING,
    user_id STRING,
    purpose STRING,
    external_contact_id STRING,
    external_organization_id STRING,
    external_tag STRING,
    flagged_reason STRING,
    media_type STRING,
    session_id STRING,
    address_other STRING,
    address_self STRING,
    address_from STRING,
    address_to STRING,
    message_type STRING,
    ani STRING,
    direction STRING,
    dnis STRING,
    session_dnis STRING,
    outbound_campaign_id STRING,
    outbound_contact_id STRING,
    outbound_contact_list_id STRING,
    disposition_analyzer STRING,
    disposition_name STRING,
    edge_id STRING,
    remote_name_displayable STRING,
    room_id STRING,
    monitored_session_id STRING,
    monitored_participant_id STRING,
    script_id STRING,
    peer_id STRING,
    skip_enabled BOOLEAN,
    time_out_seconds TEXT,
    co_browse_role STRING,
    co_browse_roomid STRING,
    media_bridge_id STRING,
    screen_share_address_self STRING,
    sharing_screen BOOLEAN,
    screen_share_roomid STRING,
    video_roomid STRING,
    video_address_self STRING,
    recording BOOLEAN,
    journey_customer_id STRING,
    journey_customer_id_type STRING,
    journey_customer_session_id STRING,
    journey_customer_session_id_type STRING,
    journey_action_id STRING,
    journey_action_map_id STRING,
    journey_action_map_version STRING,
    protocol_call_id STRING,
    t_acd NUMBER(38, 0),
    t_answered NUMBER(38, 0),
    t_flowout NUMBER(38, 0),
    t_talk NUMBER(38, 0),
    t_talk_complete NUMBER(38, 0),
    t_handle NUMBER(38, 0),
    t_dialing NUMBER(38, 0),
    t_contacting NUMBER(38, 0),
    t_held NUMBER(38, 0),
    t_held_complete NUMBER(38, 0),
    o_interacting NUMBER(38, 0),
    o_waiting NUMBER(38, 0),
    n_transferred NUMBER(38, 0),
    n_error NUMBER(38, 0),
    n_state_transition_error NUMBER(38, 0),
    t_alert NUMBER(38, 0),
    t_not_responding NUMBER(38, 0),
    o_service_level NUMBER(38, 0),
    o_service_target NUMBER(38, 0),
    n_over_sla NUMBER(38, 0),
    t_wait NUMBER(38, 0),
    t_ivr NUMBER(38, 0),
    t_abandon NUMBER(38, 0),
    t_voicemail NUMBER(38, 0),
    t_acw NUMBER(38, 0),
    n_outbound_attempted NUMBER(38, 0),
    n_outbound_connected NUMBER(38, 0),
    n_outbound_abandoned NUMBER(38, 0),
    n_outbound NUMBER(38, 0),
    t_user_response_time NUMBER(38, 0),
    t_agent_response_time NUMBER(38, 0),
    conversation_start_hq TIMESTAMP_NTZ(9),
    meta_row_hash NUMBER(38, 0),
    meta_create_datetime TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
    meta_update_datetime TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP,
    n_consult NUMBER(38,0)
);
