create or replace TABLE GMS.GMS_OPERATIONAL_BILLING_HISTORY (
	MONTH DATE,
	STORE_NAME VARCHAR(55),
	M1_NEW_VIPS NUMBER(38,0),
	FIRST_SUCCESSFUL_NEW_VIPS NUMBER(38,0),
	M1_GRACE_VIPS NUMBER(38,0),
	FIRST_SUCCESSFUL_GRACE_VIPS NUMBER(38,0),
	BILLED_CREDIT NUMBER(15,2),
	FIRST_SUCCESSFUL_BILLED_CREDIT_RATE_TRAILING_6_MONTHS NUMBER(15,2),
	RETRY_RATE NUMBER(15,2),
	RETRY_RATE_TRAILING_6_MONTHS NUMBER(15,2),
	META_CREATE_DATETIME TIMESTAMP_LTZ(3),
	META_UPDATE_DATETIME TIMESTAMP_LTZ(3)
);
