create or replace TABLE REPORTING_PROD.RETAIL.RETAIL_DRIVE_TIME (
    GRAIN VARCHAR(5),
	SHEET VARCHAR(6),
	DATE DATE,
	STORE_NAME VARCHAR(101),
	REGION VARCHAR(32),
	COUNTRY VARCHAR(50),
	DISTRICT VARCHAR(50),
	DRIVING_TIME FLOAT,
	DISTANCE FLOAT,
	SHOPPED_IN_RETAIL NUMBER(1,0),
	IS_BOP_VIP NUMBER(1,0),
	IS_ACTIVATED NUMBER(1,0),
	DISTANCE_RANK NUMBER(1,0),
	DISTINCT_CUSTOMER_CNT NUMBER(18,0)
);
