CREATE OR REPLACE TABLE REPORTING_PROD.SHARED.BREAKAGE_BY_STATE_ACTUALS (
	BRAND VARCHAR(155),
	COUNTRY VARCHAR(155),
	STATE VARCHAR(155),
	ORIGINAL_ISSUED_MONTH DATE,
	ORIGINAL_CREDIT_TYPE VARCHAR(155),
	ACTIVITY_MONTH DATE,
	ISSUED_TO_DATE NUMBER(32,4),
	REDEEMED_TO_DATE NUMBER(32,4),
	CANCELLED_TO_DATE NUMBER(32,4),
	UNREDEEMED_TO_DATE NUMBER(32,4)
);
