CREATE TABLE IF NOT EXISTS sxf.retail_attribution
(
    DATE_VIEW                                                     VARCHAR(10),
    METRIC_TYPE                                                   VARCHAR(23),
    METRIC_METHOD                                                 VARCHAR(9),
    DATE                                                          DATE,
    WEEKOFYEAR                                                    NUMBER,
    YEAROFWEEK                                                    NUMBER,
    START_DATE                                                    DATE,
    END_DATE                                                      DATE,
    STORE_ID                                                      NUMBER,
    STORE_NAME                                                    VARCHAR(50),
    REGION                                                        VARCHAR(32),
    LONGITUDE                                                     DOUBLE,
    LATITUDE                                                      DOUBLE,
    STORE_ZIP                                                     VARCHAR(10),
    STORE_CITY                                                    VARCHAR(50),
    STORE_STATE                                                   VARCHAR(50),
    STORE_OPENING_DATE                                            DATE,
    SQ_FOOTAGE                                                    NUMBER,
    STORE_NUMBER                                                  NUMBER,
    STORE_RETAIL_TYPE                                             VARCHAR(10),
    STORE_TYPE                                                    VARCHAR(10),
    COMP_NEW                                                      VARCHAR(4),
    IS_RETAIL_SHIP_ONLY_ORDER                                     VARCHAR(24),
    ORDERS                                                        NUMBER,
    ORDERS_LY                                                     NUMBER,
    FIRST_GUEST_ORDERS                                            NUMBER,
    FIRST_GUEST_ORDERS_LY                                         NUMBER,
    REPEAT_GUEST_ORDERS                                           NUMBER,
    REPEAT_GUEST_ORDERS_LY                                        NUMBER,
    ACT_VIP_ORDERS                                                NUMBER,
    ACT_VIP_ORDERS_LY                                             NUMBER,
    REPEAT_VIP_ORDERS                                             NUMBER,
    REPEAT_VIP_ORDERS_LY                                          NUMBER,
    UNITS                                                         NUMBER,
    UNITS_LY                                                      NUMBER,
    FIRST_GUEST_UNITS                                             NUMBER,
    FIRST_GUEST_UNITS_LY                                          NUMBER,
    REPEAT_GUEST_UNITS                                            NUMBER,
    REPEAT_GUEST_UNITS_LY                                         NUMBER,
    ACT_VIP_UNITS                                                 NUMBER,
    ACT_VIP_UNITS_LY                                              NUMBER,
    REPEAT_VIP_UNITS                                              NUMBER,
    REPEAT_VIP_UNITS_LY                                           NUMBER,
    GIFT_CARD_ORDERS                                              NUMBER,
    GIFT_CARD_ORDERS_LY                                           NUMBER,
    ORDERS_WITH_CREDIT_REDEMPTION                                 NUMBER,
    ORDERS_WITH_CREDIT_REDEMPTION_LY                              NUMBER,
    FIRST_GUEST_ORDERS_WITH_CREDIT_REDEMPTION                     NUMBER,
    FIRST_GUEST_ORDERS_WITH_CREDIT_REDEMPTION_LY                  NUMBER,
    REPEAT_GUEST_ORDERS_WITH_CREDIT_REDEMPTION                    NUMBER,
    REPEAT_GUEST_ORDERS_WITH_CREDIT_REDEMPTION_LY                 NUMBER,
    ACT_VIP_ORDERS_WITH_CREDIT_REDEMPTION                         NUMBER,
    ACT_VIP_ORDERS_WITH_CREDIT_REDEMPTION_LY                      NUMBER,
    REPEAT_VIP_ORDERS_WITH_CREDIT_REDEMPTION                      NUMBER,
    REPEAT_VIP_ORDERS_WITH_CREDIT_REDEMPTION_LY                   NUMBER,
    PRODUCT_GROSS_REVENUE                                         NUMBER(38, 10),
    PRODUCT_GROSS_REVENUE_LY                                      NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_GROSS_REVENUE                             NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_GROSS_REVENUE_LY                          NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_GROSS_REVENUE                            NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_GROSS_REVENUE_LY                         NUMBER(38, 10),
    ACT_VIP_PRODUCT_GROSS_REVENUE                                 NUMBER(38, 10),
    ACT_VIP_PRODUCT_GROSS_REVENUE_LY                              NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_GROSS_REVENUE                              NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_GROSS_REVENUE_LY                           NUMBER(38, 10),
    CASH_GROSS_REVENUE                                            NUMBER(38, 10),
    CASH_GROSS_REVENUE_LY                                         NUMBER(38, 10),
    PRODUCT_NET_REVENUE                                           NUMBER(38, 10),
    PRODUCT_NET_REVENUE_LY                                        NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_NET_REVENUE                               NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_NET_REVENUE_LY                            NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_NET_REVENUE                              NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_NET_REVENUE_LY                           NUMBER(38, 10),
    ACT_VIP_PRODUCT_NET_REVENUE                                   NUMBER(38, 10),
    ACT_VIP_PRODUCT_NET_REVENUE_LY                                NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_NET_REVENUE                                NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_NET_REVENUE_LY                             NUMBER(38, 10),
    CASH_NET_REVENUE                                              NUMBER(38, 10),
    CASH_NET_REVENUE_LY                                           NUMBER(38, 10),
    PRODUCT_GROSS_PROFIT                                          NUMBER(38, 12),
    PRODUCT_GROSS_PROFIT_LY                                       NUMBER(38, 12),
    FIRST_GUEST_PRODUCT_GROSS_PROFIT                              NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_GROSS_PROFIT_LY                           NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_GROSS_PROFIT                             NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_GROSS_PROFIT_LY                          NUMBER(38, 10),
    ACT_VIP_PRODUCT_GROSS_PROFIT                                  NUMBER(38, 10),
    ACT_VIP_PRODUCT_GROSS_PROFIT_LY                               NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_GROSS_PROFIT                               NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_GROSS_PROFIT_LY                            NUMBER(38, 10),
    CASH_GROSS_PROFIT                                             NUMBER(38, 12),
    CASH_GROSS_PROFIT_LY                                          NUMBER(38, 12),
    SHIPPING_REVENUE                                              NUMBER(38, 10),
    SHIPPING_REVENUE_LY                                           NUMBER(38, 10),
    SHIPPING_COST                                                 NUMBER(38, 12),
    SHIPPING_COST_LY                                              NUMBER(38, 12),
    DISCOUNT                                                      NUMBER(38, 10),
    DISCOUNT_LY                                                   NUMBER(38, 10),
    FIRST_GUEST_DISCOUNT                                          NUMBER(38, 10),
    FIRST_GUEST_DISCOUNT_LY                                       NUMBER(38, 10),
    REPEAT_GUEST_DISCOUNT                                         NUMBER(38, 10),
    REPEAT_GUEST_DISCOUNT_LY                                      NUMBER(38, 10),
    ACT_VIP_DISCOUNT                                              NUMBER(38, 10),
    ACT_VIP_DISCOUNT_LY                                           NUMBER(38, 10),
    REPEAT_VIP_DISCOUNT                                           NUMBER(38, 10),
    REPEAT_VIP_DISCOUNT_LY                                        NUMBER(38, 10),
    INITIAL_RETAIL_PRICE_EXCL_VAT                                 NUMBER(38, 10),
    INITIAL_RETAIL_PRICE_EXCL_VAT_LY                              NUMBER(38, 10),
    FIRST_GUEST_INITIAL_RETAIL_PRICE_EXCL_VAT                     NUMBER(38, 10),
    FIRST_GUEST_INITIAL_RETAIL_PRICE_EXCL_VAT_LY                  NUMBER(38, 10),
    REPEAT_GUEST_INITIAL_RETAIL_PRICE_EXCL_VAT                    NUMBER(38, 10),
    REPEAT_GUEST_INITIAL_RETAIL_PRICE_EXCL_VAT_LY                 NUMBER(38, 10),
    ACT_VIP_INITIAL_RETAIL_PRICE_EXCL_VAT                         NUMBER(38, 10),
    ACT_VIP_INITIAL_RETAIL_PRICE_EXCL_VAT_LY                      NUMBER(38, 10),
    REPEAT_VIP_INITIAL_RETAIL_PRICE_EXCL_VAT                      NUMBER(38, 10),
    REPEAT_VIP_INITIAL_RETAIL_PRICE_EXCL_VAT_LY                   NUMBER(38, 10),
    SUBTOTAL_AMOUNT_EXCL_TARIFF                                   NUMBER(38, 10),
    SUBTOTAL_AMOUNT_EXCL_TARIFF_LY                                NUMBER(38, 10),
    FIRST_GUEST_SUBTOTAL_AMOUNT_EXCL_TARIFF                       NUMBER(38, 10),
    FIRST_GUEST_SUBTOTAL_AMOUNT_EXCL_TARIFF_LY                    NUMBER(38, 10),
    REPEAT_GUEST_SUBTOTAL_AMOUNT_EXCL_TARIFF                      NUMBER(38, 10),
    REPEAT_GUEST_SUBTOTAL_AMOUNT_EXCL_TARIFF_LY                   NUMBER(38, 10),
    ACT_VIP_SUBTOTAL_AMOUNT_EXCL_TARIFF                           NUMBER(38, 10),
    ACT_VIP_SUBTOTAL_AMOUNT_EXCL_TARIFF_LY                        NUMBER(38, 10),
    REPEAT_VIP_SUBTOTAL_AMOUNT_EXCL_TARIFF                        NUMBER(38, 10),
    REPEAT_VIP_SUBTOTAL_AMOUNT_EXCL_TARIFF_LY                     NUMBER(38, 10),
    PRODUCT_DISCOUNT_AMOUNT                                       NUMBER(38, 10),
    PRODUCT_DISCOUNT_AMOUNT_LY                                    NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_DISCOUNT_AMOUNT                           NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_DISCOUNT_AMOUNT_LY                        NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_DISCOUNT_AMOUNT                          NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_DISCOUNT_AMOUNT_LY                       NUMBER(38, 10),
    ACT_VIP_PRODUCT_DISCOUNT_AMOUNT                               NUMBER(38, 10),
    ACT_VIP_PRODUCT_DISCOUNT_AMOUNT_LY                            NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_DISCOUNT_AMOUNT                            NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_DISCOUNT_AMOUNT_LY                         NUMBER(38, 10),
    PRODUCT_COST_AMOUNT                                           NUMBER(38, 10),
    PRODUCT_COST_AMOUNT_LY                                        NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_COST_AMOUNT                               NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_COST_AMOUNT_LY                            NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_COST_AMOUNT                              NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_COST_AMOUNT_LY                           NUMBER(38, 10),
    ACT_VIP_PRODUCT_COST_AMOUNT                                   NUMBER(38, 10),
    ACT_VIP_PRODUCT_COST_AMOUNT_LY                                NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_COST_AMOUNT                                NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_COST_AMOUNT_LY                             NUMBER(38, 10),
    PRODUCT_SUBTOTAL_AMOUNT                                       NUMBER(38, 10),
    PRODUCT_SUBTOTAL_AMOUNT_LY                                    NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_SUBTOTAL_AMOUNT                           NUMBER(38, 10),
    FIRST_GUEST_PRODUCT_SUBTOTAL_AMOUNT_LY                        NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_SUBTOTAL_AMOUNT                          NUMBER(38, 10),
    REPEAT_GUEST_PRODUCT_SUBTOTAL_AMOUNT_LY                       NUMBER(38, 10),
    ACT_VIP_PRODUCT_SUBTOTAL_AMOUNT                               NUMBER(38, 10),
    ACT_VIP_PRODUCT_SUBTOTAL_AMOUNT_LY                            NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_SUBTOTAL_AMOUNT                            NUMBER(38, 10),
    REPEAT_VIP_PRODUCT_SUBTOTAL_AMOUNT_LY                         NUMBER(38, 10),
    NON_CASH_CREDIT_AMOUNT                                        NUMBER(38, 10),
    NON_CASH_CREDIT_AMOUNT_LY                                     NUMBER(38, 10),
    FIRST_GUEST_NON_CASH_CREDIT_AMOUNT                            NUMBER(38, 10),
    FIRST_GUEST_NON_CASH_CREDIT_AMOUNT_LY                         NUMBER(38, 10),
    REPEAT_GUEST_NON_CASH_CREDIT_AMOUNT                           NUMBER(38, 10),
    REPEAT_GUEST_NON_CASH_CREDIT_AMOUNT_LY                        NUMBER(38, 10),
    ACT_VIP_NON_CASH_CREDIT_AMOUNT                                NUMBER(38, 10),
    ACT_VIP_NON_CASH_CREDIT_AMOUNT_LY                             NUMBER(38, 10),
    REPEAT_VIP_NON_CASH_CREDIT_AMOUNT                             NUMBER(38, 10),
    REPEAT_VIP_NON_CASH_CREDIT_AMOUNT_LY                          NUMBER(38, 10),
    CREDIT_REDEMPTION_AMOUNT                                      NUMBER(38, 10),
    CREDIT_REDEMPTION_AMOUNT_LY                                   NUMBER(38, 6),
    CREDIT_REDEMPTION_COUNT                                       NUMBER(38, 10),
    CREDIT_REDEMPTION_COUNT_LY                                    NUMBER(38, 6),
    GIFT_CARD_ISSUANCE_AMOUNT                                     NUMBER(38, 12),
    GIFT_CARD_ISSUANCE_AMOUNT_LY                                  NUMBER(38, 12),
    CREDIT_ISSUANCE_AMOUNT                                        NUMBER(38, 10),
    CREDIT_ISSUANCE_AMOUNT_LY                                     NUMBER(38, 10),
    CREDIT_ISSUANCE_COUNT                                         NUMBER(38, 6),
    CREDIT_ISSUANCE_COUNT_LY                                      NUMBER(38, 6),
    GIFT_CARD_REDEMPTION_AMOUNT                                   NUMBER(38, 10),
    GIFT_CARD_REDEMPTION_AMOUNT_LY                                NUMBER(38, 10),
    CONVERSION_ELIGIBLE_ORDERS                                    NUMBER,
    CONVERSION_ELIGIBLE_ORDERS_LY                                 NUMBER,
    PAYGO_ACTIVATIONS                                             NUMBER(37),
    PAYGO_ACTIVATIONS_LY                                          NUMBER(37),
    PRODUCT_ORDER_CASH_REFUND_AMOUNT                              NUMBER(38, 10),
    PRODUCT_ORDER_CASH_REFUND_AMOUNT_LY                           NUMBER(38, 10),
    PRODUCT_ORDER_CASH_CREDIT_REFUND_AMOUNT                       NUMBER(38, 10),
    PRODUCT_ORDER_CASH_CREDIT_REFUND_AMOUNT_LY                    NUMBER(38, 10),
    BILLING_CASH_REFUND_AMOUNT                                    NUMBER(38, 10),
    BILLING_CASH_REFUND_AMOUNT_LY                                 NUMBER(38, 10),
    BILLING_CASH_CHARGEBACK_AMOUNT                                NUMBER(38, 10),
    BILLING_CASH_CHARGEBACK_AMOUNT_LY                             NUMBER(38, 10),
    PRODUCT_ORDER_CASH_CHARGEBACK_AMOUNT                          NUMBER(38, 10),
    PRODUCT_ORDER_CASH_CHARGEBACK_AMOUNT_LY                       NUMBER(38, 10),
    RESHIP_ORDERS                                                 NUMBER,
    RESHIP_ORDERS_LY                                              NUMBER,
    RESHIP_UNITS                                                  NUMBER,
    RESHIP_UNITS_LY                                               NUMBER,
    RESHIP_PRODUCT_COST                                           NUMBER(38, 10),
    RESHIP_PRODUCT_COST_LY                                        NUMBER(38, 10),
    EXCHANGE_ORDERS                                               NUMBER,
    EXCHANGE_ORDERS_LY                                            NUMBER,
    EXCHANGE_UNITS                                                NUMBER,
    EXCHANGE_UNITS_LY                                             NUMBER,
    EXCHANGE_PRODUCT_COST                                         NUMBER(38, 10),
    EXCHANGE_PRODUCT_COST_LY                                      NUMBER(38, 10),
    RETURN_PRODUCT_COST                                           NUMBER(38, 10),
    RETURN_PRODUCT_COST_LY                                        NUMBER(38, 10),
    RETURN_SHIPPING_COST                                          NUMBER(38, 10),
    RETURN_SHIPPING_COST_LY                                       NUMBER(38, 10),
    ONLINE_PURCHASE_RETAIL_RETURNS                                NUMBER,
    ONLINE_PURCHASE_RETAIL_RETURNS_LY                             NUMBER,
    RETAIL_PURCHASE_RETAIL_RETURNS                                NUMBER,
    RETAIL_PURCHASE_RETAIL_RETURNS_LY                             NUMBER,
    RETAIL_PURCHASE_ONLINE_RETURNS                                NUMBER,
    RETAIL_PURCHASE_ONLINE_RETURNS_LY                             NUMBER,
    TOTAL_EXCHANGES                                               NUMBER,
    TOTAL_EXCHANGES_LY                                            NUMBER,
    EXCHANGES_AFTER_ONLINE_RETURN                                 NUMBER,
    EXCHANGES_AFTER_ONLINE_RETURN_LY                              NUMBER,
    EXCHANGES_AFTER_IN_STORE_RETURN                               NUMBER,
    EXCHANGES_AFTER_IN_STORE_RETURN_LY                            NUMBER,
    EXCHANGES_AFTER_IN_STORE_RETURN_FROM_ONLINE_PURCHASE          NUMBER,
    EXCHANGES_AFTER_IN_STORE_RETURN_FROM_ONLINE_PURCHASE_LY       NUMBER,
    TOTAL_EXCHANGES_VALUE                                         NUMBER(38, 10),
    TOTAL_EXCHANGES_VALUE_LY                                      NUMBER(38, 10),
    EXCHANGES_VALUE_AFTER_ONLINE_RETURN                           NUMBER(38, 10),
    EXCHANGES_VALUE_AFTER_ONLINE_RETURN_LY                        NUMBER(38, 10),
    EXCHANGES_VALUE_AFTER_IN_STORE_RETURN                         NUMBER(38, 10),
    EXCHANGES_VALUE_AFTER_IN_STORE_RETURN_LY                      NUMBER(38, 10),
    EXCHANGES_VALUE_AFTER_IN_STORE_RETURN_FROM_ONLINE_PURCHASE    NUMBER(38, 10),
    EXCHANGES_VALUE_AFTER_IN_STORE_RETURN_FROM_ONLINE_PURCHASE_LY NUMBER(38, 10),
    INCOMING_VISITOR_TRAFFIC                                      NUMBER,
    INCOMING_VISITOR_TRAFFIC_LY                                   NUMBER,
    META_CREATE_DATETIME                                          TIMESTAMPLTZ(3),
    META_UPDATE_DATETIME                                          TIMESTAMPLTZ(3),
    ONLINE_PURCHASE_RETAIL_RETURN_ORDERS                          NUMBER,
    ONLINE_PURCHASE_RETAIL_RETURN_ORDERS_LY                       NUMBER,
    RETAIL_PURCHASE_RETAIL_RETURN_ORDERS                          NUMBER,
    RETAIL_PURCHASE_RETAIL_RETURN_ORDERS_LY                       NUMBER,
    RETAIL_PURCHASE_ONLINE_RETURN_ORDERS                          NUMBER,
    RETAIL_PURCHASE_ONLINE_RETURN_ORDERS_LY                       NUMBER,
    EXITING_VISITOR_TRAFFIC                                       NUMBER,
    EXITING_VISITOR_TRAFFIC_LY                                    NUMBER
);

