CREATE TABLE IF NOT EXISTS sxf.style_master
(
    COLOR_SKU_PO                      VARCHAR(93),
    STYLE_NUMBER_PO                   VARCHAR(450),
    STYLE_NAME                        VARCHAR(900),
    SITE_NAME                         VARCHAR(900),
    PO_COLOR                          VARCHAR(450),
    SITE_COLOR                        VARCHAR(1800),
    IMAGE_URL                         VARCHAR,
    COLOR_FAMILY                      VARCHAR,
    CATEGORY                          VARCHAR(450),
    SUBCATEGORY                       VARCHAR(450),
    CATEGORY_TYPE                     VARCHAR(450),
    SIZE_SCALE                        VARCHAR,
    SIZE_SCALE_PRODUCTION             VARCHAR(150),
    GSHEET_SIZE_RANGE                 VARCHAR,
    SIZE_RANGE                        VARCHAR(20),
    BUY_RANK                          VARCHAR,
    CORE_FASHION                      VARCHAR(12),
    NEW_CORE_FASHION                  VARCHAR,
    FABRIC                            VARCHAR,
    PERSONA                           VARCHAR,
    COLLECTION                        VARCHAR,
    GENDER                            VARCHAR,
    VIP_PRICE                         NUMBER(20, 4),
    EURO_VIP                          NUMBER(20, 4),
    GBP_VIP                           NUMBER(20, 4),
    MSRP                              NUMBER(20, 4),
    EURO_MSRP                         NUMBER(20, 4),
    GBP_MSRP                          NUMBER(20, 4),
    FIRST_SHOWROOM                    DATE,
    LATEST_SHOWROOM                   DATE,
    SAVAGE_SHOWROOM                   DATE,
    FIRST_VENDOR                      VARCHAR(195),
    LATEST_VENDOR                     VARCHAR(195),
    FIRST_EST_LANDED_COST             NUMBER(12, 2),
    LATEST_EST_LANDED_COST            NUMBER(12, 2),
    LATEST_QTY                        NUMBER,
    ACTIVE_BUNDLE_PROGRAMS            VARCHAR(150),
    BUNDLE_RETAIL                     VARCHAR,
    ACTIVE_SETS                       VARCHAR,
    VIP_BOX                           VARCHAR,
    FIRST_SALES_DATE                  TIMESTAMP_NTZ,
    FIRST_RECEIVED_DATE               TIMESTAMP_NTZ,
    LAST_RECEIVED_DATE                TIMESTAMP_NTZ,
    FIRST_INVENTORY_READY_DATE        TIMESTAMP_NTZ,
    FIRST_INVENTORY_OCCURRENCE_DATE   TIMESTAMP_NTZ,
    FIRST_OCCURRENCE_DATE             TIMESTAMP_NTZ,
    INV_AGED_DAYS                     NUMBER(9),
    INV_AGED_MONTHS                   NUMBER(9),
    INV_AGED_STATUS                   VARCHAR(7),
    PLANNED_SITE_RELEASE_DATE         TIMESTAMP_NTZ,
    INV_AGED_RANK                     NUMBER(1),
    RANK                              NUMBER(18),
    SALE_SECTION_PRICE_CURRENT        NUMBER(19, 4),
    SALE_SECTION_DATE_ADDED_FIRST     TIMESTAMP_NTZ(3),
    SR_WEIGHTED_EST_FREIGHT_US        NUMBER(10, 2),
    SR_WEIGHTED_EST_DUTY_US           NUMBER(10, 2),
    SR_WEIGHTED_EST_CMT_US            NUMBER(10, 2),
    SR_WEIGHTED_EST_COST_US           NUMBER(10, 2),
    SR_WEIGHTED_EST_PRIMARY_TARIFF_US NUMBER(10, 3),
    SR_WEIGHTED_EST_UK_TARIFF_US      NUMBER(10, 3),
    SR_WEIGHTED_EST_US_TARIFF_US      NUMBER(10, 3),
    SR_WEIGHTED_EST_LANDED_COST_US    NUMBER(10, 2),
    SR_WEIGHTED_EST_FREIGHT_EU        NUMBER(10, 2),
    SR_WEIGHTED_EST_DUTY_EU           NUMBER(10, 2),
    SR_WEIGHTED_EST_CMT_EU            NUMBER(10, 2),
    SR_WEIGHTED_EST_COST_EU           NUMBER(10, 2),
    SR_WEIGHTED_EST_PRIMARY_TARIFF_EU NUMBER(10, 3),
    SR_WEIGHTED_EST_UK_TARIFF_EU      NUMBER(10, 3),
    SR_WEIGHTED_EST_US_TARIFF_EU      NUMBER(10, 3),
    SR_WEIGHTED_EST_LANDED_COST_EU    NUMBER(10, 2),
    ESTIMATED_LANDED_COST             NUMBER(38, 12),
    LOAD_DATETIME                     TIMESTAMP_LTZ(3),
    BRIGHT                            VARCHAR,
    HEAT                              VARCHAR,
    COLOR_ROLL_UP                     VARCHAR,
    COLOR_VALUE                       VARCHAR,
    COLOR_TONE                        VARCHAR,
    COVERAGE                          VARCHAR,
    FABRIC_GROUPING                   VARCHAR,
    OPACITY                           VARCHAR,
    PATTERN                           VARCHAR,
    PREORDER_EXPIRES_DATE             TIMESTAMP_NTZ(3),
    DEPARTMENT                        VARCHAR,
    SUB_DEPARTMENT                    VARCHAR,
    LAUNCH_COLLECTION                 VARCHAR,
    IS_CENTRIC                        VARCHAR(5),
    PLANNING_RESERVE_TYPE_NA          VARCHAR(25),
    CURRENT_VIP_PRICE_ON_SITE_NA      NUMBER(19, 4),
    CURRENT_RETAIL_PRICE_ON_SITE_NA   NUMBER(19, 4),
    LATEST_BRAND_SHOWROOM             DATE,
    REPORTING_LANDED_COST             NUMBER(38, 12)
)
