CREATE OR REPLACE VIEW UTIL.PUBLIC.ACCESS_HISTORY AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.ACCESS_HISTORY;

GRANT OWNERSHIP ON VIEW UTIL.PUBLIC.ACCESS_HISTORY TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;
