CREATE OR REPLACE VIEW UTIL.PUBLIC.USAGE_IN_CURRENCY_DAILY AS
SELECT *
FROM SNOWFLAKE.ORGANIZATION_USAGE.USAGE_IN_CURRENCY_DAILY;

GRANT OWNERSHIP ON VIEW UTIL.PUBLIC.USAGE_IN_CURRENCY_DAILY TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;
