CREATE OR REPLACE VIEW UTIL.PUBLIC.GRANTS_TO_USERS
AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_USERS;

GRANT OWNERSHIP ON VIEW UTIL.PUBLIC.GRANTS_TO_USERS TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;
