CREATE OR REPLACE VIEW UTIL.PUBLIC.TASK_HISTORY
AS
SELECT
    *,
    TIMESTAMPDIFF('MILLISECOND', QUERY_START_TIME, COMPLETED_TIME) AS DURATION,
    RANK() OVER(PARTITION BY NAME, schema_name, database_name ORDER BY run_id DESC) AS rnk
FROM snowflake.account_usage.task_history;

GRANT OWNERSHIP ON VIEW UTIL.PUBLIC.TASK_HISTORY TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;
