CREATE OR REPLACE VIEW UTIL.PUBLIC.DATABASE_STORAGE_USAGE_HISTORY AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.DATABASE_STORAGE_USAGE_HISTORY;

GRANT OWNERSHIP ON VIEW UTIL.PUBLIC.DATABASE_STORAGE_USAGE_HISTORY TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;
