CREATE OR REPLACE VIEW UTIL.PUBLIC.USERS AS
SELECT
    USER_ID,
	NAME,
	CREATED_ON,
	DELETED_ON,
	LOGIN_NAME,
	DISPLAY_NAME,
	FIRST_NAME,
	LAST_NAME,
	EMAIL,
	MUST_CHANGE_PASSWORD,
	HAS_PASSWORD,
	COMMENT,
	DISABLED,
	SNOWFLAKE_LOCK,
	DEFAULT_WAREHOUSE,
	DEFAULT_NAMESPACE,
	DEFAULT_ROLE,
	EXT_AUTHN_DUO,
	EXT_AUTHN_UID,
	HAS_MFA,
	BYPASS_MFA_UNTIL,
	LAST_SUCCESS_LOGIN,
	EXPIRES_AT,
	LOCKED_UNTIL_TIME,
	HAS_RSA_PUBLIC_KEY,
	PASSWORD_LAST_SET_TIME,
	OWNER,
	DEFAULT_SECONDARY_ROLE,
	TYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS;

GRANT OWNERSHIP ON VIEW UTIL.PUBLIC.USERS TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;
