CREATE OR REPLACE VIEW UTIL.PUBLIC.WAREHOUSE_METERING_HISTORY AS
SELECT *
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY;

GRANT OWNERSHIP ON VIEW UTIL.PUBLIC.WAREHOUSE_METERING_HISTORY TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;
