SET watermark = (
    SELECT COALESCE(MAX(CUSTOMER_BI_UPDATED_DATETIME), '1970-01-01') AS CUSTOMER_BI_UPDATED_DATETIME
    FROM lake.crm.bi_data_history
    );

INSERT INTO lake.crm.bi_data_history (
    CUSTOMER_ID,
    STORE,
    STORE_GROUP,
    PROMO_GROUP,
    LEAD_REGISTRATION_DATETIME,
    ACTIVATION_LOCAL_DATE,
    CANCEL_LOCAL_DATE,
    REGISTRATION_SOURCE_MEDIUM_CHANNEL,
    ACTIVATION_SOURCE_MEDIUM_CHANNEL,
    IS_ACTIVATED_ON_MOBILE_APP,
    TIMEZONE,
    VIP_LIFETIME_SAVING,
    AVG_DAYS_BETWEEN_PURCHASE,
    LAST_PLACED_DATE,
    IS_RETAIL_SHOPPER,
    IS_ONLINE_SHOPPER,
    IS_MOBILE_APP_SHOPPER,
    IS_FEMALE_PRODUCT_SHOPPER,
    IS_MALE_PRODUCT_SHOPPER,
    IS_UNISEX_PRODUCT_SHOPPER,
    IS_MALE_PRODUCT_ONLY_SHOPPER,
    LAST_RETAIL_PURCHASE_DATE,
    LAST_MOBILE_APP_PURCHASE_DATE,
    LAST_ONLINE_PURCHASE_DATE,
    LAST_PRODUCT_ORDER_PURCHASE_DATE,
    NEAREST_RETAIL_STORE,
    RETAIL_STORE_DISTANCE,
    RETAIL_STORE_DRIVE_TIME,
    NEAREST_RETAIL_STORE_ADDRESS1,
    NEAREST_RETAIL_STORE_ADDRESS2,
    NEAREST_RETAIL_STORE_CITY,
    NEAREST_RETAIL_STORE_STATE,
    NEAREST_RETAIL_STORE_ZIP,
    NEAREST_RETAIL_STORE_COUNTRY_CODE,
    NEAREST_RETAIL_STORE_GOOGLE_MAPS_LINK,
    NEAREST_RETAIL_STORE_LOCATION_IN_MALL,
    SKIP_REASON,
    IS_IN_GRACE_PERIOD,
    ACTIVATING_UPT,
    PURCHASE_MENS_ONLY_ACTIVATING_ORDER,
    PRE_PASSIVE_CANCEL_2M_CHECK,
    CURRENT_CASH_MARGIN_DECILE,
    CURRENT_PRODUCT_MARGIN_DECILE,
    LTV_ORDER_REVENUE,
    LTV_TOTAL_REVENUE,
    PRODUCT_ORDERS,
    CREDIT_BILLINGS,
    LTV_CASH_GROSS_MARGIN,
    LTV_GROSS_MARGIN_PCT,
    AVG_AOV,
    RECENT_CUSTOMER_ACTION,
    RECENT_BILL_ME_NOW_DATE,
    PREVIOUS_DECILE,
    MEMBERSHIP_AMOUNT_SAVED_TO_DATE,
    IS_REPEAT_FAILED_BILLING,
    CONSECUTIVE_FAILED_BILLING_MONTHS,
    IS_EMP_ENROLLED,
    IS_BRAND_APP_DOWNLOADED,
    IS_FITNESS_APP_DOWNLOADED,
    IS_HYDROW_PURCHASED,
    SX_UNIQUE_TOP_SIZE,
    SX_UNIQUE_BOTTOM_SIZE,
    HOW_DID_YOU_HEAR,
    MEMBERSHIP_2995USD_CREDITS,
    MEMBERSHIP_3995USD_CREDITS,
    MOST_RECENT_SUCCESSFUL_CREDIT_BILLING,
    REDEEMED_DOWNGRADED_PROMO,
    SCRUBS_INTEREST_RESPONSE,
    SXF_LIFETIME_SUB_DEPARTMENT,
    SXF_ACTIVATING_SUB_DEPARTMENT,
    SXF_LIFETIME_SUB_DEPARTMENT_WITHOUT_GENDER,
    SXF_ACTIVATING_SUB_DEPARTMENT_WITHOUT_GENDER,
    SXF_CONSECUTIVE_FAILED_BILLING_MONTHS,
    SXF_IS_FAILED_BILLING,
    SXF_ON_TRACK_PASSIVE_CANCEL_CRITERIA_MONTHS,
    SXF_TOTAL_FAILED_BILLING_MONTHS_INPASTYEAR,
    SXF_IS_FIRST_TIME_FAILED_BILLING,
    SXF_VIP_GAMER,
    CUSTOMER_BI_UPDATED_DATETIME,
    CURRENT_STATUS,
    EXCLUSION_REASON,
    is_new_TCs_opt_in,
    IS_EMP_OPTIN,
    FAILED_BILLER_SEGMENT,
    SKIPPER_SEGMENT,
    CANCELLED_VIP_SEGMENT,
    IS_BIRTH_MONTH,
    BIRTH_DAY,
    IS_ANNIVERSARY_TODAY,
    IS_ANNIVERSARY_MONTH,
    SXF_NMP_FIFTH_BILLING_PERK_FLAG,
    FIRST_MOST_RECENT_FAVORITED_ITEM_SITE_NAME,
    FIRST_MOST_RECENT_FAVORITED_ITEM_IMAGE_URL,
    SECOND_MOST_RECENT_FAVORITED_ITEM_SITE_NAME,
    SECOND_MOST_RECENT_FAVORITED_ITEM_IMAGE_URL,
    SXF_NMP_FIFTH_BILLING_PERK_COUNTER,
    /* History Columns */
    IS_CURRENT,
    EFFECTIVE_START_DATETIME,
    EFFECTIVE_END_DATETIME,
    META_UPDATE_DATETIME
    )
SELECT
    CUSTOMER_ID,
    STORE,
    STORE_GROUP,
    PROMO_GROUP,
    LEAD_REGISTRATION_DATETIME,
    ACTIVATION_LOCAL_DATE,
    CANCEL_LOCAL_DATE,
    REGISTRATION_SOURCE_MEDIUM_CHANNEL,
    ACTIVATION_SOURCE_MEDIUM_CHANNEL,
    IS_ACTIVATED_ON_MOBILE_APP,
    TIMEZONE,
    VIP_LIFETIME_SAVING,
    AVG_DAYS_BETWEEN_PURCHASE,
    LAST_PLACED_DATE,
    IS_RETAIL_SHOPPER,
    IS_ONLINE_SHOPPER,
    IS_MOBILE_APP_SHOPPER,
    IS_FEMALE_PRODUCT_SHOPPER,
    IS_MALE_PRODUCT_SHOPPER,
    IS_UNISEX_PRODUCT_SHOPPER,
    IS_MALE_PRODUCT_ONLY_SHOPPER,
    LAST_RETAIL_PURCHASE_DATE,
    LAST_MOBILE_APP_PURCHASE_DATE,
    LAST_ONLINE_PURCHASE_DATE,
    LAST_PRODUCT_ORDER_PURCHASE_DATE,
    NEAREST_RETAIL_STORE,
    RETAIL_STORE_DISTANCE,
    RETAIL_STORE_DRIVE_TIME,
    NEAREST_RETAIL_STORE_ADDRESS1,
    NEAREST_RETAIL_STORE_ADDRESS2,
    NEAREST_RETAIL_STORE_CITY,
    NEAREST_RETAIL_STORE_STATE,
    NEAREST_RETAIL_STORE_ZIP,
    NEAREST_RETAIL_STORE_COUNTRY_CODE,
    NEAREST_RETAIL_STORE_GOOGLE_MAPS_LINK,
    NEAREST_RETAIL_STORE_LOCATION_IN_MALL,
    SKIP_REASON,
    IS_IN_GRACE_PERIOD,
    ACTIVATING_UPT,
    PURCHASE_MENS_ONLY_ACTIVATING_ORDER,
    PRE_PASSIVE_CANCEL_2M_CHECK,
    CURRENT_CASH_MARGIN_DECILE,
    CURRENT_PRODUCT_MARGIN_DECILE,
    LTV_ORDER_REVENUE,
    LTV_TOTAL_REVENUE,
    PRODUCT_ORDERS,
    CREDIT_BILLINGS,
    LTV_CASH_GROSS_MARGIN,
    LTV_GROSS_MARGIN_PCT,
    AVG_AOV,
    RECENT_CUSTOMER_ACTION,
    RECENT_BILL_ME_NOW_DATE,
    PREVIOUS_DECILE,
    MEMBERSHIP_AMOUNT_SAVED_TO_DATE,
    IS_REPEAT_FAILED_BILLING,
    CONSECUTIVE_FAILED_BILLING_MONTHS,
    IS_EMP_ENROLLED,
    IS_BRAND_APP_DOWNLOADED,
    IS_FITNESS_APP_DOWNLOADED,
    IS_HYDROW_PURCHASED,
    SX_UNIQUE_TOP_SIZE,
    SX_UNIQUE_BOTTOM_SIZE,
    HOW_DID_YOU_HEAR,
    MEMBERSHIP_2995USD_CREDITS,
    MEMBERSHIP_3995USD_CREDITS,
    MOST_RECENT_SUCCESSFUL_CREDIT_BILLING,
    REDEEMED_DOWNGRADED_PROMO,
    SCRUBS_INTEREST_RESPONSE,
    SXF_LIFETIME_SUB_DEPARTMENT,
    SXF_ACTIVATING_SUB_DEPARTMENT,
    SXF_LIFETIME_SUB_DEPARTMENT_WITHOUT_GENDER,
    SXF_ACTIVATING_SUB_DEPARTMENT_WITHOUT_GENDER,
    SXF_CONSECUTIVE_FAILED_BILLING_MONTHS,
    SXF_IS_FAILED_BILLING,
    SXF_ON_TRACK_PASSIVE_CANCEL_CRITERIA_MONTHS,
    SXF_TOTAL_FAILED_BILLING_MONTHS_INPASTYEAR,
    SXF_IS_FIRST_TIME_FAILED_BILLING,
    SXF_VIP_GAMER,
    CUSTOMER_BI_UPDATED_DATETIME,
    CURRENT_STATUS,
    EXCLUSION_REASON,
    is_new_TCs_opt_in,
    IS_EMP_OPTIN,
    FAILED_BILLER_SEGMENT,
    SKIPPER_SEGMENT,
    CANCELLED_VIP_SEGMENT,
    IS_BIRTH_MONTH,
    BIRTH_DAY,
    IS_ANNIVERSARY_TODAY,
    IS_ANNIVERSARY_MONTH,
    SXF_NMP_FIFTH_BILLING_PERK_FLAG,
    FIRST_MOST_RECENT_FAVORITED_ITEM_SITE_NAME,
    FIRST_MOST_RECENT_FAVORITED_ITEM_IMAGE_URL,
    SECOND_MOST_RECENT_FAVORITED_ITEM_SITE_NAME,
    SECOND_MOST_RECENT_FAVORITED_ITEM_IMAGE_URL,
    SXF_NMP_FIFTH_BILLING_PERK_COUNTER,
    /* History Columns */
    TRUE AS IS_CURRENT,
    CUSTOMER_BI_UPDATED_DATETIME AS EFFECTIVE_START_DATETIME,
    NULL AS EFFECTIVE_END_DATETIME,
    CURRENT_TIMESTAMP() AS META_UPDATE_DATETIME
FROM lake.crm.bi_data AS A
WHERE CUSTOMER_BI_UPDATED_DATETIME >= DATEADD(MINUTE, -5, $watermark)
    AND NOT EXISTS (
    SELECT DISTINCT
        X.customer_id,
        X.customer_bi_updated_datetime
    FROM lake.crm.bi_data_history AS X
    WHERE X.CUSTOMER_BI_UPDATED_DATETIME >= DATEADD(MINUTE, -5, $watermark)
        AND A.customer_id = X.customer_id
        AND A.customer_bi_updated_datetime = X.customer_bi_updated_datetime
    )
;

CREATE OR REPLACE TEMPORARY TABLE _rows AS
WITH _fix AS (
SELECT
    customer_id,
    customer_bi_updated_datetime,
    effective_start_datetime,
    effective_end_datetime,
    ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY effective_start_datetime ASC) AS rnk
FROM lake.crm.bi_data_history AS H
)

SELECT
   A.customer_id,
   A.customer_bi_updated_datetime,
   A.effective_start_datetime,
   COALESCE(dateadd(MILLISECOND, -1, B.effective_start_datetime), '9999-12-31 00:00:00.000 -0800'
       ) AS new_effective_end_datetime
FROM _fix AS A
    LEFT JOIN _fix AS B
    ON A.customer_id = B.customer_id
    AND A.rnk = B.rnk - 1
;

/* Update effective timestamps */
UPDATE lake.crm.bi_data_history AS A
SET A.effective_end_datetime = B.new_effective_end_datetime,
    META_UPDATE_DATETIME = current_timestamp
FROM _rows AS B
WHERE A.customer_id = B.customer_id
    AND A.customer_bi_updated_datetime = B.customer_bi_updated_datetime
    AND (A.effective_end_datetime <> B.new_effective_end_datetime
    	OR A.effective_end_datetime IS NULL);

/* Update IS_CURRENT */
UPDATE lake.crm.bi_data_history
SET
    IS_CURRENT = CASE WHEN effective_end_datetime = '9999-12-31' THEN TRUE ELSE FALSE END,
    META_UPDATE_DATETIME = current_timestamp
WHERE customer_id IN (SELECT DISTINCT customer_id FROM _rows WHERE customer_id IS NOT NULL)
    AND IS_CURRENT <> CASE WHEN effective_end_datetime = '9999-12-31' THEN TRUE ELSE FALSE END
;
