set wm_cucb_exception_report_by_date = (SELECT MAX(meta_update_datetime) FROM lake.excel.cucb_exception_report_by_date);
set wm_jf_exception_by_rule = (SELECT MAX(meta_update_datetime) FROM lake.excel.jf_exception_by_rule);

INSERT INTO lake.excel.waived_po_data(
    ref_type,
    ref_num,
    po,
    item,
    excep_detail,
    status,
    create_by_user_name,
    create_time,
    last_update_time,
    last_update_from,
    division_name,
    last_reply,
    po_number,
    po_origin,
    customer_code,
    customer_name,
    category,
    vendor,
    po_vendor_standard_name,
    handle_option,
    reply_option,
    reply_notes,
    exception_name,
    ref_type_number,
    approve_not_approve_date,
    exception_date,
    created_by,
    notes,
    event_notes_oid,
    business_type,
    transport_mode,
    pod_eta,
    traffic_mode,
    container,
    postadvice,
    size_type,
    so,
    por,
    pol,
    carrier,
    pol_etd,
    pod,
    exception_subject,
    meta_create_datetime,
    meta_update_datetime)
SELECT a.ref_type,
    a.ref_num,
    a.po,
    a.item,
    a.excep_detail,
    a.status,
    a.create_by_user_name,
    a.create_time,
    a.last_update_time,
    a.last_update_from,
    a.division_name,
    a.last_reply,
    b.po_number,
    b.po_origin,
    b.customer_code,
    b.customer_name,
    b.category,
    b.vendor,
    b.po_vendor_standard_name,
    b.handle_option,
    b.reply_option,
    b.reply_notes,
    b.exception_name,
    b.ref_type_number,
    to_date(b.approve_not_approve_date) AS approve_not_approve_date,
    to_date(b.exception_date) AS exception_date,
    b.created_by,
    b.notes,
    b.event_notes_oid,
    b.business_type,
    b.transport_mode,
    to_date(b.pod_eta) AS pod_eta,
    b.traffic_mode,
    b.container,
    b.postadvice,
    b.size_type,
    b.so,
    b.por,
    b.pol,
    b.carrier,
    to_date(b.pol_etd) AS pol_etd,
    b.pod,
    b.exception_subject,
    CURRENT_TIMESTAMP() AS meta_create_datetime,
    CURRENT_TIMESTAMP() AS meta_update_datetime
FROM lake.excel.cucb_exception_report_by_date a
LEFT JOIN lake.excel.jf_exception_by_rule b ON b.ref_type_number = CONCAT(a.ref_type, ' ', a.ref_num)
    AND b.exception_name ILIKE 'Light box'
    AND b.meta_update_datetime >= $wm_jf_exception_by_rule
WHERE a.meta_update_datetime >= $wm_cucb_exception_report_by_date;
