from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    linked_server='bluecherry',
    database='datafbpr',
    schema='dbo',
    table='tfg_style_master',
    watermark_column='datetime_transaction',
    schema_version_prefix='v4',
    column_list=[
        Column("style_key", "INT", source_name="styleKey", uniqueness=True),
        Column("style_color_key", "INT", source_name="styleColorKey", uniqueness=True),
        Column("size_bucket", "VARCHAR(2)", source_name="sizebucket"),
        Column("upc", "VARCHAR(12)", uniqueness=True),
        Column("ean", "VARCHAR(14)"),
        Column("nrf_color", "VARCHAR(50)"),
        Column("nrf_size", "VARCHAR(50)"),
        Column("sku", "VARCHAR(50)"),
        Column("basesku", "VARCHAR(31)"),
        Column("sku_description", "VARCHAR(136)"),
        Column("division", "VARCHAR(30)"),
        Column("business_unit", "VARCHAR(30)"),
        Column("uom", "VARCHAR(4)"),
        Column("item_status", "VARCHAR(12)"),
        Column("style_code", "VARCHAR(50)"),
        Column("hts_code", "VARCHAR(12)"),
        Column("dimension", "VARCHAR(50)"),
        Column("packing_dimension", "INT"),
        Column("packing_weight", "INT"),
        Column("brand", "VARCHAR(30)"),
        Column("master_class", "VARCHAR(30)"),
        Column("class", "VARCHAR(30)"),
        Column("sub_class", "VARCHAR(30)"),
        Column("product_category", "VARCHAR(50)"),
        Column("department", "VARCHAR(30)"),
        Column("sub_department", "VARCHAR(30)"),
        Column("gender", "VARCHAR(30)"),
        Column("sc_cat", "VARCHAR(30)"),
        Column("show_room", "VARCHAR(7)"),
        Column("original_retail_price", "NUMERIC(9,2)"),
        Column("current_retail_price", "NUMERIC(9,2)"),
        Column("member_price", "NUMERIC(14,5)"),
        Column("non_member_price", "NUMERIC(14,5)"),
        Column("msrp_usd", "NUMERIC(14,5)"),
        Column("msrp_eur", "NUMERIC(14,5)"),
        Column("msrp_gbp", "NUMERIC(14,5)"),
        Column("style", "VARCHAR(50)"),
        Column("color", "VARCHAR(30)"),
        Column("size", "VARCHAR(10)"),
        Column("launch_date", "TIMESTAMP_NTZ(3)"),
        Column("style_name", "VARCHAR(60)"),
        Column("datetime_local_transaction", "TIMESTAMP_NTZ(3)"),
        Column("datetime_transaction", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("carryover", "VARCHAR(10)"),
        Column("buyer", "VARCHAR(128)"),
        Column("graphic", "VARCHAR(10)"),
        Column("po_size_range", "VARCHAR(128)"),
        Column("style_comp", "VARCHAR(128)"),
        Column("performance", "VARCHAR(10)"),
        Column("plussize", "VARCHAR(10)"),
        Column("curvy", "VARCHAR(10)"),
        Column("collection", "VARCHAR(128)"),
        Column("colorway_comp", "VARCHAR(128)"),
        Column("colorfamily", "VARCHAR(128)"),
        Column("hts_eu", "VARCHAR(128)"),
        Column("hts_ca", "VARCHAR(128)"),
        Column("hts_uk", "VARCHAR(128)"),
        Column("colorway_carryover", "VARCHAR(10)"),
        Column("blank_sku", "VARCHAR(128)"),
        Column("centric_url", "VARCHAR(20)"),
        Column("case_size", "NUMERIC(8,2)"),
        Column("datetime_local_transaction_upd", "TIMESTAMP_NTZ(3)"),
    ],
)
