from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    linked_server="bluecherry",
    database="datafbpr",
    schema="dbo",
    table="tfg_po_dtl_full",
    watermark_column="po_dtl_mod",
    schema_version_prefix="v7",
    column_list=[
        Column("po_number", "VARCHAR(60)"),
        Column("open_seq", "INT"),
        Column("po_line_number", "INT", uniqueness=True),
        Column("factory_address1", "VARCHAR(254)"),
        Column("factory_address2", "VARCHAR(254)"),
        Column("factory_address3", "VARCHAR(254)"),
        Column("factory_address4", "VARCHAR(254)"),
        Column("factory_city", "VARCHAR(254)"),
        Column("factory_state", "VARCHAR(3)"),
        Column("factory_zip_code", "VARCHAR(10)"),
        Column("factory_country", "VARCHAR(3)"),
        Column("official_factory_name", "VARCHAR(254)"),
        Column("po_id", "INT"),
        Column("division_id", "VARCHAR(3)"),
        Column("division_name", "VARCHAR(30)"),
        Column("division_name_bc", "VARCHAR(30)"),
        Column("show_room", "VARCHAR(7)"),
        Column("date_launch", "TIMESTAMP_NTZ(3)"),
        Column("approved_date", "TIMESTAMP_NTZ(3)"),
        Column("payment_term", "VARCHAR(30)"),
        Column("currency_code", "VARCHAR(3)"),
        Column("xfd", "TIMESTAMP_NTZ(3)"),
        Column("start_date", "TIMESTAMP_NTZ(3)"),
        Column("inco_term", "VARCHAR(10)"),
        Column("date_create", "TIMESTAMP_NTZ(3)"),
        Column("date_update", "TIMESTAMP_NTZ(3)"),
        Column("brand", "VARCHAR(30)"),
        Column("country_origin", "VARCHAR(3)"),
        Column("po_type", "VARCHAR(128)"),
        Column("is_retail", "INT"),
        Column("fc_delivery", "TIMESTAMP_NTZ(3)"),
        Column("delivery", "INT"),
        Column("region_id", "VARCHAR(25)"),
        Column("freight_method", "VARCHAR(30)"),
        Column("shipping_port", "VARCHAR(82)"),
        Column("shipping_port_country", "VARCHAR(30)"),
        Column("shipping_port_city", "VARCHAR(50)"),
        Column("warehouse_id", "VARCHAR(6)"),
        Column("warehouse_name", "VARCHAR(254)"),
        Column("warehouse_id_origin", "VARCHAR(10)"),
        Column("warehouse_name_origin", "VARCHAR(254)"),
        Column("vendor_id", "VARCHAR(6)"),
        Column("vend_name", "VARCHAR(254)"),
        Column("vendor_address1", "VARCHAR(254)"),
        Column("vendor_address2", "VARCHAR(254)"),
        Column("vendor_address3", "VARCHAR(254)"),
        Column("vendor_address4", "VARCHAR(254)"),
        Column("vendor_city", "VARCHAR(254)"),
        Column("vendor_state", "VARCHAR(3)"),
        Column("vendor_zip_code", "VARCHAR(10)"),
        Column("vendor_country", "VARCHAR(3)"),
        Column("agent_id", "VARCHAR(6)"),
        Column("agent_name", "VARCHAR(254)"),
        Column("plan_qty", "INT"),
        Column("issue_qty", "INT"),
        Column("qty", "INT"),
        Column("intran_qty", "INT"),
        Column("recv_qty", "INT"),
        Column("cancelled_qty", "INT"),
        Column("is_cancelled", "INT"),
        Column("freight_shipping", "NUMERIC(12,5)"),
        Column("freight_drayage", "NUMERIC(12,5)"),
        Column("freight_transload", "NUMERIC(12,5)"),
        Column("duty", "NUMERIC(25,12)"),
        Column("misc_cost", "NUMERIC(14,5)"),
        Column("cost", "NUMERIC(17,8)"),
        Column("line_status", "VARCHAR(7)"),
        Column("hts_code", "VARCHAR(12)"),
        Column("duty_percentage", "NUMERIC(12,7)"),
        Column("tariff_pct", "NUMERIC(6,2)"),
        Column("tariff", "NUMERIC(19,7)"),
        Column("commission", "NUMERIC(12,5)"),
        Column("commission_pct", "NUMERIC(12,5)"),
        Column("inspection", "NUMERIC(12,5)"),
        Column("cmt", "NUMERIC(12,5)"),
        Column("wholesaler_id", "VARCHAR(7)"),
        Column("wholesaler_name", "VARCHAR(254)"),
        Column("sku", "VARCHAR(50)"),
        Column("basesku", "VARCHAR(31)"),
        Column("upc", "VARCHAR(12)"),
        Column("ean", "VARCHAR(14)"),
        Column("dimension", "VARCHAR(50)"),
        Column("size_name", "VARCHAR(10)"),
        Column("color", "VARCHAR(30)"),
        Column("style", "VARCHAR(50)"),
        Column("style_name", "VARCHAR(60)"),
        Column("department", "VARCHAR(30)"),
        Column("sub_department", "VARCHAR(30)"),
        Column("class", "VARCHAR(30)"),
        Column("subclass", "VARCHAR(30)"),
        Column("gender", "VARCHAR(30)"),
        Column("sc_cat", "VARCHAR(30)"),
        Column("description", "VARCHAR(136)"),
        Column("carryover", "VARCHAR(10)"),
        Column("buyer", "VARCHAR(128)"),
        Column("graphic", "VARCHAR(10)"),
        Column("blank_sku", "VARCHAR(128)"),
        Column("po_size_range", "VARCHAR(128)"),
        Column("composition", "VARCHAR(128)"),
        Column("performance", "VARCHAR(10)"),
        Column("plussize", "VARCHAR(10)"),
        Column("curvy", "VARCHAR(10)"),
        Column("collection", "VARCHAR(128)"),
        Column("colorfamily", "VARCHAR(128)"),
        Column("hts_ca", "VARCHAR(128)"),
        Column("hts_eu", "VARCHAR(128)"),
        Column("hts_uk", "VARCHAR(128)"),
        Column("sizebucket", "VARCHAR(2)"),
        Column("uom", "VARCHAR(4)"),
        Column("case_size", "INT"),
        Column("num_case_pack", "INT"),
        Column("retail_price", "NUMERIC(9,2)"),
        Column("member_price", "NUMERIC(14,5)"),
        Column("non_member_price", "NUMERIC(14,5)"),
        Column("msrp_usd", "NUMERIC(14,5)"),
        Column("msrp_eur", "NUMERIC(14,5)"),
        Column("msrp_gbp", "NUMERIC(14,5)"),
        Column("centric_url", "VARCHAR(20)"),
        Column("po_dtl_mod", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("po_num_merlin", "VARCHAR(60)"),
        Column("po_num_bc", "INT", uniqueness=True),
        Column("inter_id", "VARCHAR(4)"),
        Column("first_cost", "NUMERIC(12,5)"),
        Column("production_type", "VARCHAR(30)"),
        Column("po_status", "VARCHAR(9)"),
        Column("po_dtl_id_merlin", "INT"),
        Column("color_code", "VARCHAR(50)"),
        Column("label_code", "VARCHAR(50)"),
        Column("us_compound_rate", "NUMERIC(12,5)"),
        Column("gs1_prefix", "VARCHAR(80)"),
        Column("is_prepack", "INT"),
        Column("prepack_sku", "VARCHAR(80)"),
        Column("prepack_po_line_number", "INT"),
    ],
)
