
SET NOCOUNT ON;

SELECT
    CONCAT(hvr.db_name, '.dbo.', hvr.table_name) AS SOURCE_TABLE
FROM (
    SELECT
        db_name,
        table_name
    FROM (VALUES
        /* GDPR */
        ('gdpr', 'request'),
        ('gdpr', 'request_comment'),
        ('gdpr', 'request_type'),
        ('gdpr', 'statuscode'),
        /* ULTRA_CMS */
        ('ultracms', 'statuscode'),
        ('ultracms', 'test_framework'),
        ('ultracms', 'test_framework_data'),
        ('ultracms', 'test_framework_group'),
        ('ultracms', 'test_framework_xfa'),
        ('ultracms', 'ui_promo_management_promos'),
        ('ultracms', 'ui_promo_management_promos_membership_promo_type'),
        /* ULTRA_CART */
        ('ultracart', 'cart'),
        ('ultracart', 'cart_source_type'),
        ('ultracart', 'statuscode'),
        ('ultracart', 'statuscode_category'),
        /* ULTRA_MERCHANT */
        ('ultramerchant', 'address'),
        ('ultramerchant', 'address_blacklist'),
        ('ultramerchant', 'address_validation_request_log'),
        ('ultramerchant', 'administrator'),
        ('ultramerchant', 'administrator_administrator_group'),
        ('ultramerchant', 'administrator_group'),
        ('ultramerchant', 'administrator_session'),
        ('ultramerchant', 'administrator_session_log'),
        ('ultramerchant', 'administrator_store_group'),
        ('ultramerchant', 'administrator_survey'),
        ('ultramerchant', 'administrator_survey_question_answer'),
        ('ultramerchant', 'administrator_warehouse'),
        ('ultramerchant', 'asset'),
        ('ultramerchant', 'billing_alternate_payment'),
        ('ultramerchant', 'billing_alternate_payment_log'),
        ('ultramerchant', 'billing_retry_schedule_queue'),
        ('ultramerchant', 'billing_retry_schedule_queue_log'),
        ('ultramerchant', 'bond_user_action'),
        ('ultramerchant', 'bond_user_action_parameter'),
        ('ultramerchant', 'bond_user_action_type'),
        ('ultramerchant', 'bounceback_endowment'),
        ('ultramerchant', 'bounceback_type'),
        ('ultramerchant', 'box'),
        ('ultramerchant', 'box_completion'),
        ('ultramerchant', 'brand'),
        ('ultramerchant', 'carrier_service_uw'),
        ('ultramerchant', 'carrier_uw'),
        ('ultramerchant', 'cart'),
        ('ultramerchant', 'cart_dressing_room'),
        ('ultramerchant', 'cart_dressing_room_product'),
        ('ultramerchant', 'cart_line'),
        ('ultramerchant', 'cart_product_source'),
        ('ultramerchant', 'cart_warehouse'),
        ('ultramerchant', 'case'),
        ('ultramerchant', 'case_action'),
        ('ultramerchant', 'case_classification'),
        ('ultramerchant', 'case_comment'),
        ('ultramerchant', 'case_customer'),
        ('ultramerchant', 'case_flag'),
        ('ultramerchant', 'case_flag_disposition'),
        ('ultramerchant', 'case_flag_disposition_case_flag_type'),
        ('ultramerchant', 'case_flag_type'),
        ('ultramerchant', 'case_intent'),
        ('ultramerchant', 'case_log'),
        ('ultramerchant', 'case_qa'),
        ('ultramerchant', 'case_source'),
        ('ultramerchant', 'case_source_location'),
        ('ultramerchant', 'cash_deposit'),
        ('ultramerchant', 'cash_drawer'),
        ('ultramerchant', 'cash_register'),
        ('ultramerchant', 'cash_register_eod'),
        ('ultramerchant', 'cash_register_log'),
        ('ultramerchant', 'cash_transaction'),
        ('ultramerchant', 'cdr_incontact'),
        ('ultramerchant', 'cdr_smartaction'),
        ('ultramerchant', 'chargeback_import_batch'),
        ('ultramerchant', 'chargeback_import_batch_detail'),
        ('ultramerchant', 'chargeback_import_transaction'),
        ('ultramerchant', 'chargeback_import_transaction_log'),
        ('ultramerchant', 'credit_transfer_queue'),
        ('ultramerchant', 'credit_transfer_transaction'),
        ('ultramerchant', 'credit_transfer_transaction_type'),
        ('ultramerchant', 'creditcard'),
        ('ultramerchant', 'creditcard_blacklist'),
        ('ultramerchant', 'creditcard_update_batch'),
        ('ultramerchant', 'creditcard_update_transaction'),
        ('ultramerchant', 'customer'),
        ('ultramerchant', 'customer_address'),
        ('ultramerchant', 'customer_blacklist'),
        ('ultramerchant', 'customer_blacklist_reason'),
        ('ultramerchant', 'customer_compensation'),
        ('ultramerchant', 'customer_compensation_type'),
        ('ultramerchant', 'customer_compensation_vip_reason'),
        ('ultramerchant', 'customer_customer_compensation'),
        ('ultramerchant', 'customer_detail'),
        ('ultramerchant', 'customer_fitmatch'),
        ('ultramerchant', 'customer_fitmatch_product'),
        ('ultramerchant', 'customer_last_event'),
        ('ultramerchant', 'customer_lead_map'),
        ('ultramerchant', 'customer_link'),
        ('ultramerchant', 'customer_log'),
        ('ultramerchant', 'customer_order_verification'),
        ('ultramerchant', 'customer_phone'),
        ('ultramerchant', 'customer_quiz'),
        ('ultramerchant', 'customer_quiz_detail'),
        ('ultramerchant', 'customer_quiz_question_answer'),
        ('ultramerchant', 'customer_referrer'),
        ('ultramerchant', 'customer_referrer_type'),
        ('ultramerchant', 'customer_search'),
        ('ultramerchant', 'customer_search_detail'),
        ('ultramerchant', 'customer_solicitation_permission'),
        ('ultramerchant', 'customer_solicitation_permission_option'),
        ('ultramerchant', 'customer_survey'),
        ('ultramerchant', 'customer_survey_question_answer'),
        ('ultramerchant', 'customer_tag'),
        ('ultramerchant', 'customer_type'),
        ('ultramerchant', 'discount'),
        ('ultramerchant', 'discount_type'),
        ('ultramerchant', 'dm_gateway'),
        ('ultramerchant', 'dm_gateway_sub_type'),
        ('ultramerchant', 'dm_gateway_test'),
        ('ultramerchant', 'dm_gateway_test_site'),
        ('ultramerchant', 'dm_gateway_test_site_class'),
        ('ultramerchant', 'dm_gateway_test_site_location'),
        ('ultramerchant', 'dm_gateway_test_site_type'),
        ('ultramerchant', 'dm_gateway_type'),
        ('ultramerchant', 'dm_site'),
        ('ultramerchant', 'dm_site_type'),
        ('ultramerchant', 'dressing_room'),
        ('ultramerchant', 'ds_algo_membership_suggestion'),
        ('ultramerchant', 'ds_algo_membership_suggestion_features'),
        ('ultramerchant', 'ds_algo_membership_suggestion_product'),
        ('ultramerchant', 'ds_algo_membership_suggestion_product_type'),
        ('ultramerchant', 'ds_algo_registry'),
        ('ultramerchant', 'ds_algo_registry_group'),
        ('ultramerchant', 'ds_algo_registry_version'),
        ('ultramerchant', 'exchange'),
        ('ultramerchant', 'exchange_line'),
        ('ultramerchant', 'exclude_state_surcharge'),
        ('ultramerchant', 'featured_product'),
        ('ultramerchant', 'featured_product_location'),
        ('ultramerchant', 'featured_product_location_reward_tier'),
        ('ultramerchant', 'featured_product_location_type'),
        ('ultramerchant', 'fraud_address'),
        ('ultramerchant', 'fraud_customer'),
        ('ultramerchant', 'fraud_customer_reason'),
        ('ultramerchant', 'fraud_quarantine_queue'),
        ('ultramerchant', 'fraud_quarantine_queue_detail'),
        ('ultramerchant', 'fraud_quarantine_queue_detail_rule'),
        ('ultramerchant', 'fraud_rule'),
        ('ultramerchant', 'fulfillment_partner'),
        ('ultramerchant', 'gaming_prevention_log'),
        ('ultramerchant', 'gaming_prevention_log_detail'),
        ('ultramerchant', 'gateway_account'),
        ('ultramerchant', 'gift_certificate'),
        ('ultramerchant', 'gift_certificate_batch'),
        ('ultramerchant', 'gift_certificate_store_credit'),
        ('ultramerchant', 'gift_certificate_transaction_reason'),
        ('ultramerchant', 'gift_certificate_transaction_type'),
        ('ultramerchant', 'gift_certificate_type'),
        ('ultramerchant', 'gift_order'),
        ('ultramerchant', 'happy_returns_item_log'),
        ('ultramerchant', 'hdyh_global_list'),
        ('ultramerchant', 'hdyh_global_list_referrer'),
        ('ultramerchant', 'item'),
        ('ultramerchant', 'item_preallocation'),
        ('ultramerchant', 'language'),
        ('ultramerchant', 'managed_gift_certificate'),
        ('ultramerchant', 'managed_gift_certificate_redemption'),
        ('ultramerchant', 'managed_gift_certificate_redemption_queue'),
        ('ultramerchant', 'marin_tracking'),
        ('ultramerchant', 'media_code'),
        ('ultramerchant', 'media_code_type'),
        ('ultramerchant', 'media_publisher'),
        ('ultramerchant', 'media_type'),
        ('ultramerchant', 'membership'),
        ('ultramerchant', 'membership_billing'),
        ('ultramerchant', 'membership_billing_cohort'),
        ('ultramerchant', 'membership_billing_cohort_billing_date'),
        ('ultramerchant', 'membership_billing_credit_threshold'),
        ('ultramerchant', 'membership_billing_source'),
        ('ultramerchant', 'membership_brand'),
        ('ultramerchant', 'membership_brand_activation'),
        ('ultramerchant', 'membership_brand_signup'),
        ('ultramerchant', 'membership_cancel'),
        ('ultramerchant', 'membership_cancel_reason'),
        ('ultramerchant', 'membership_completion_method'),
        ('ultramerchant', 'membership_credit_billing_stats_log'),
        ('ultramerchant', 'membership_detail'),
        ('ultramerchant', 'membership_downgrade'),
        ('ultramerchant', 'membership_downgrade_reason'),
        ('ultramerchant', 'membership_invitation'),
        ('ultramerchant', 'membership_invitation_link'),
        ('ultramerchant', 'membership_level'),
        ('ultramerchant', 'membership_level_group'),
        ('ultramerchant', 'membership_level_group_modification_log'),
        ('ultramerchant', 'membership_order'),
        ('ultramerchant', 'membership_passive_cancels'),
        ('ultramerchant', 'membership_period'),
        ('ultramerchant', 'membership_plan'),
        ('ultramerchant', 'membership_plan_membership_brand'),
        ('ultramerchant', 'membership_plan_membership_type'),
        ('ultramerchant', 'membership_product'),
        ('ultramerchant', 'membership_product_type'),
        ('ultramerchant', 'membership_product_wait_list'),
        ('ultramerchant', 'membership_product_wait_list_component'),
        ('ultramerchant', 'membership_product_wait_list_order_log'),
        ('ultramerchant', 'membership_product_wait_list_type'),
        ('ultramerchant', 'membership_promo'),
        ('ultramerchant', 'membership_promo_type'),
        ('ultramerchant', 'membership_reward_plan'),
        ('ultramerchant', 'membership_reward_plan_transaction_type'),
        ('ultramerchant', 'membership_reward_signal'),
        ('ultramerchant', 'membership_reward_tier'),
        ('ultramerchant', 'membership_reward_transaction'),
        ('ultramerchant', 'membership_reward_transaction_type'),
        ('ultramerchant', 'membership_settings'),
        ('ultramerchant', 'membership_signup'),
        ('ultramerchant', 'membership_skip'),
        ('ultramerchant', 'membership_skip_reason'),
        ('ultramerchant', 'membership_snooze'),
        ('ultramerchant', 'membership_snooze_period'),
        ('ultramerchant', 'membership_store_credit'),
        ('ultramerchant', 'membership_suggestion'),
        ('ultramerchant', 'membership_suggestion_product'),
        ('ultramerchant', 'membership_suggestion_product_purchase'),
        ('ultramerchant', 'membership_token'),
        ('ultramerchant', 'membership_token_billing_stats_log'),
        ('ultramerchant', 'membership_token_credit_conversion'),
        ('ultramerchant', 'membership_token_credit_conversion_log'),
        ('ultramerchant', 'membership_token_reason'),
        ('ultramerchant', 'membership_token_transaction'),
        ('ultramerchant', 'membership_token_transaction_reason'),
        ('ultramerchant', 'membership_token_transaction_type'),
        ('ultramerchant', 'membership_trial'),
        ('ultramerchant', 'membership_type'),
        ('ultramerchant', 'meta_data'),
        ('ultramerchant', 'ml_gms_export_customer_save_data_sel'),
        ('ultramerchant', 'modification_log'),
        ('ultramerchant', 'offer_category'),
        ('ultramerchant', 'order'),
        ('ultramerchant', 'order_cancel'),
        ('ultramerchant', 'order_cancel_reason'),
        ('ultramerchant', 'order_chargeback'),
        ('ultramerchant', 'order_chargeback_log'),
        ('ultramerchant', 'order_classification'),
        ('ultramerchant', 'order_comment'),
        ('ultramerchant', 'order_credit'),
        ('ultramerchant', 'order_detail'),
        ('ultramerchant', 'order_discount'),
        ('ultramerchant', 'order_fulfillment'),
        ('ultramerchant', 'order_gift_certificate'),
        ('ultramerchant', 'order_line'),
        ('ultramerchant', 'order_line_customization'),
        ('ultramerchant', 'order_line_customization_option'),
        ('ultramerchant', 'order_line_discount'),
        ('ultramerchant', 'order_line_split_map'),
        ('ultramerchant', 'order_line_token'),
        ('ultramerchant', 'order_line_warehouse_mapping_log'),
        ('ultramerchant', 'order_line_warehouse_mapping_log_detail'),
        ('ultramerchant', 'order_product_source'),
        ('ultramerchant', 'order_shipment'),
        ('ultramerchant', 'order_shipment_line'),
        ('ultramerchant', 'order_shipping'),
        ('ultramerchant', 'order_surcharge'),
        ('ultramerchant', 'order_tax'),
        ('ultramerchant', 'order_tracking_detail'),
        ('ultramerchant', 'order_type'),
        ('ultramerchant', 'order_vat'),
        ('ultramerchant', 'partner'),
        ('ultramerchant', 'partner_campaign'),
        ('ultramerchant', 'partner_post'),
        ('ultramerchant', 'partner_post_detail'),
        ('ultramerchant', 'payment'),
        ('ultramerchant', 'payment_transaction_cash'),
        ('ultramerchant', 'payment_transaction_creditcard'),
        ('ultramerchant', 'payment_transaction_creditcard_data'),
        ('ultramerchant', 'payment_transaction_psp'),
        ('ultramerchant', 'period'),
        ('ultramerchant', 'pricing_option'),
        ('ultramerchant', 'product'),
        ('ultramerchant', 'product_bundle_component'),
        ('ultramerchant', 'product_category'),
        ('ultramerchant', 'product_endowment'),
        ('ultramerchant', 'product_endowment_delete_log'),
        ('ultramerchant', 'product_feedback'),
        ('ultramerchant', 'product_lily_metadata'),
        ('ultramerchant', 'product_preorder'),
        ('ultramerchant', 'product_product_category'),
        ('ultramerchant', 'product_product_feedback'),
        ('ultramerchant', 'product_property'),
        ('ultramerchant', 'product_property_type'),
        ('ultramerchant', 'product_tag'),
        ('ultramerchant', 'product_type'),
        ('ultramerchant', 'product_wait_list'),
        ('ultramerchant', 'product_wait_list_type'),
        ('ultramerchant', 'promo'),
        ('ultramerchant', 'promo_classification'),
        ('ultramerchant', 'promo_membership_access'),
        ('ultramerchant', 'promo_promo_classfication'),
        ('ultramerchant', 'promo_type'),
        ('ultramerchant', 'psp'),
        ('ultramerchant', 'psp_chargeback_log'),
        ('ultramerchant', 'psp_notification_log'),
        ('ultramerchant', 'quiz'),
        ('ultramerchant','quiz_answer_algo_test_definition'),
        ('ultramerchant','quiz_answer_algo_test_definition_field'),
        ('ultramerchant', 'quiz_question'),
        ('ultramerchant', 'quiz_question_answer'),
        ('ultramerchant', 'quiz_question_answer_product'),
        ('ultramerchant', 'quiz_question_category'),
        ('ultramerchant', 'quiz_question_map_type'),
        ('ultramerchant', 'quiz_question_type'),
        ('ultramerchant', 'quiz_quiz_question'),
        ('ultramerchant', 'quiz_type'),
        ('ultramerchant', 'refund'),
        ('ultramerchant', 'refund_detail'),
        ('ultramerchant', 'refund_line'),
        ('ultramerchant', 'refund_membership_token'),
        ('ultramerchant', 'refund_reason'),
        ('ultramerchant', 'refund_store_credit'),
        ('ultramerchant', 'refunded_membership_token'),
        ('ultramerchant', 'reship'),
        ('ultramerchant', 'retail_location'),
        ('ultramerchant', 'retail_return'),
        ('ultramerchant', 'retail_return_detail'),
        ('ultramerchant', 'retail_store_address'),
        ('ultramerchant', 'return'),
        ('ultramerchant', 'return_action'),
        ('ultramerchant', 'return_batch'),
        ('ultramerchant', 'return_category'),
        ('ultramerchant', 'return_condition'),
        ('ultramerchant', 'return_disposition'),
        ('ultramerchant', 'return_line'),
        ('ultramerchant', 'return_product'),
        ('ultramerchant', 'return_product_return_disposition'),
        ('ultramerchant', 'return_reason'),
        ('ultramerchant', 'review'),
        ('ultramerchant', 'review_field_answer'),
        ('ultramerchant', 'review_template'),
        ('ultramerchant', 'review_template_field'),
        ('ultramerchant', 'review_template_field_answer'),
        ('ultramerchant', 'review_template_field_group'),
        ('ultramerchant', 'review_template_field_type'),
        ('ultramerchant', 'rma'),
        ('ultramerchant', 'rma_label'),
        ('ultramerchant', 'rma_line'),
        ('ultramerchant', 'rma_product'),
        ('ultramerchant', 'rma_refund'),
        ('ultramerchant', 'rma_source'),
        ('ultramerchant', 'session'),
        ('ultramerchant', 'session_action'),
        ('ultramerchant', 'session_data'),
        ('ultramerchant', 'session_detail'),
        ('ultramerchant', 'session_log'),
        ('ultramerchant', 'session_media_data'),
        ('ultramerchant', 'session_migration_log'),
        ('ultramerchant', 'session_migration_log_detail'),
        ('ultramerchant', 'session_tracking'),
        ('ultramerchant', 'session_tracking_detail'),
        ('ultramerchant', 'session_uri'),
        ('ultramerchant', 'shipping_option'),
        ('ultramerchant', 'stage_tracking'),
        ('ultramerchant', 'stage_tracking_log'),
        ('ultramerchant', 'statuscode'),
        ('ultramerchant', 'statuscode_category'),
        ('ultramerchant', 'statuscode_modification_log'),
        ('ultramerchant', 'store'),
        ('ultramerchant', 'store_classification'),
        ('ultramerchant', 'store_credit'),
        ('ultramerchant', 'store_credit_conversion'),
        ('ultramerchant', 'store_credit_reason'),
        ('ultramerchant', 'store_credit_token_conversion'),
        ('ultramerchant', 'store_credit_transaction'),
        ('ultramerchant', 'store_credit_transaction_reason'),
        ('ultramerchant', 'store_credit_transaction_type'),
        ('ultramerchant', 'store_domain'),
        ('ultramerchant', 'store_gateway_account'),
        ('ultramerchant', 'store_group'),
        ('ultramerchant', 'store_group_return_reason'),
        ('ultramerchant', 'store_language'),
        ('ultramerchant', 'store_surcharge'),
        ('ultramerchant', 'store_type'),
        ('ultramerchant', 'store_warehouse_map'),
        ('ultramerchant', 'stylist'),
        ('ultramerchant', 'suggested_product'),
        ('ultramerchant', 'survey'),
        ('ultramerchant', 'survey_question'),
        ('ultramerchant', 'survey_question_answer'),
        ('ultramerchant', 'survey_survey_question'),
        ('ultramerchant', 'tag'),
        ('ultramerchant', 'tag_archive'),
        ('ultramerchant', 'tag_category'),
        ('ultramerchant', 'test_metadata'),
        ('ultramerchant', 'test_winner'),
        ('ultramerchant', 'ui_promo_management_userlist_promo'),
        ('ultramerchant', 'ui_promo_management_userlist_users'),
        ('ultramerchant', 'url_rewrite'),
        ('ultramerchant', 'variant_pricing'),
        ('ultramerchant', 'vat_rate'),
        ('ultramerchant', 'visitor'),
        ('ultramerchant', 'visitor_session'),
        ('ultramerchant', 'zip_city_state'),
        /* ULTRA_ROLLUP */
        ('ultrarollup', 'product_image_request_test'),
        ('ultrarollup', 'product_image_test_config_history'),
        ('ultrarollup', 'products_in_stock'),
        ('ultrarollup', 'products_in_stock_master'),
        ('ultrarollup', 'products_in_stock_product_feed')
        ) AS hvr_tables(db_name, table_name)
    ) AS HVR
    LEFT JOIN (
    SELECT
        sp.name,
        'gdpr' AS db_name,
        sa.name as table_name
    FROM gdpr.dbo.sysarticles AS sa with(nolock)
    JOIN gdpr.dbo.syspublications AS sp with(nolock)
    ON sa.pubid = sp.pubid
    WHERE sp.name LIKE '%HVR%'
        AND sa.status % 2 = 1
    UNION ALL
    SELECT
        sp.name,
        'ultracart' AS db_name,
        sa.name as table_name
    FROM ultracart.dbo.sysarticles AS sa with(nolock)
    JOIN ultracart.dbo.syspublications AS sp with(nolock)
    ON sa.pubid = sp.pubid
    WHERE sp.name LIKE '%HVR%'
        AND sa.status % 2 = 1
    UNION ALL
    SELECT
        sp.name,
        'ultracms' AS db_name,
        sa.name as table_name
    FROM ultracms.dbo.sysarticles AS sa with(nolock)
    JOIN ultracms.dbo.syspublications AS sp with(nolock)
    ON sa.pubid = sp.pubid
    WHERE sp.name LIKE '%HVR%'
        AND sa.status % 2 = 1
    UNION ALL
    SELECT
        sp.name,
        'ultramerchant' AS db_name,
        sa.name as table_name
    FROM ultramerchant.dbo.sysarticles AS sa with(nolock)
    JOIN ultramerchant.dbo.syspublications AS sp with(nolock)
    ON sa.pubid = sp.pubid
    WHERE sp.name LIKE '%HVR%'
        AND sa.status % 2 = 1
    UNION ALL
    SELECT
        sp.name,
        'ultrarollup' AS db_name,
        sa.name as table_name
    FROM ultrarollup.dbo.sysarticles AS sa with(nolock)
    JOIN ultrarollup.dbo.syspublications AS sp with(nolock)
    ON sa.pubid = sp.pubid
    WHERE sp.name LIKE '%HVR%'
        AND sa.status % 2 = 1
    ) AS A
    ON A.db_name = HVR.db_name
    AND A.table_name = HVR.table_name
WHERE
    A.table_name IS NULL
    OR hvr.table_name IS NULL
ORDER BY SOURCE_TABLE ASC;
