SELECT
    LH.EVENT_TIMESTAMP,
    LH.USER_NAME,
    LH.CLIENT_IP,
    LH.ERROR_MESSAGE
FROM SNOWFLAKE.ACCOUNT_USAGE.LOGIN_HISTORY AS LH
JOIN SNOWFLAKE.ACCOUNT_USAGE.USERS AS U
    ON U.NAME = LH.USER_NAME
WHERE
    LH.EVENT_TIMESTAMP
        BETWEEN DATE_TRUNC(HOUR, DATEADD(hour, -6, CURRENT_TIMESTAMP()))
        AND DATE_TRUNC(HOUR, CURRENT_TIMESTAMP())
    AND LH.IS_SUCCESS = 'NO'
    AND LH.ERROR_MESSAGE NOT IN (
        'ID_TOKEN_INVALID'
        )
    AND U.DISABLED = FALSE
    AND U.DELETED_ON IS NULL
ORDER BY
    CASE WHEN LH.USER_NAME ILIKE ANY ('SVC%', 'VENDOR%') THEN 1 ELSE 2 END ASC,
    LH.EVENT_TIMESTAMP ASC
;