SELECT DISTINCT
    UPPER(U.EMAIL) AS EMAIL,
    CASE
        WHEN AAD.ACCOUNT_ENABLED <> 'TRUE' THEN 'Disabled in Azure AD'
        WHEN A.TERMINATION_DATE IS NOT NULL OR A.EMAIL IS NULL THEN 'Workday Termination?'
        ELSE NULL END
    AS REASON,
    AAD.ACCOUNT_ENABLED AS AAD_ENABLED,
    A.TERMINATION_DATE AS WORKDAY_TERMINATION_DATE,
    CAST(U.LAST_ACTIVE_DATE AS DATE) AS LAST_ACTIVITY_DATE_IN_SNOWFLAKE,
    A.EMPLOYEE_ID AS WORKDAY_EMPLOYEE_ID
FROM (
        SELECT
            UPPER(U.EMAIL) AS EMAIL,
            UPPER(U.FIRST_NAME) AS FIRST_NAME,
            UPPER(U.LAST_NAME) AS LAST_NAME,
            CAST(COALESCE(U.LAST_SUCCESS_LOGIN, U.CREATED_ON) AS DATE) AS LAST_ACTIVE_DATE,
            U.DISABLED,
            U.DELETED_ON,
            ROW_NUMBER() OVER(PARTITION BY UPPER(U.Email) ORDER BY U.CREATED_ON DESC) AS RNK
        FROM SNOWFLAKE.ACCOUNT_USAGE.USERS AS U
        WHERE NAME LIKE '%@%'
    ) AS U
    /* Find Users by Email */
    LEFT JOIN (
        SELECT
            EMAIL,
            TERMINATION_DATE,
            EMPLOYEE_ID,
            ROW_NUMBER() OVER(PARTITION BY EMPLOYEE_ID ORDER BY START_DATE DESC) AS RNK
        FROM lake.workday.employees
        WHERE EMAIL LIKE '%@%'
            AND EMAIL NOT LIKE '0%'
            AND EMPLOYEE_ID NOT IN ('019365', '023928') /* Excluded employee_ids due to Email Duplication */
   ) AS A
    ON UPPER(U.EMAIL) = UPPER(A.EMAIL)
    LEFT JOIN (
        SELECT DISTINCT
            MAIL,
            COALESCE(ACCOUNT_ENABLED, 'FALSE') AS ACCOUNT_ENABLED
        FROM LAKE.AZURE.USER_DETAILS
    ) AS AAD
        ON UPPER(AAD.MAIL) = UPPER(U.EMAIL)
WHERE U.RNK = 1
    AND ((A.RNK = 1 AND A.TERMINATION_DATE IS NOT NULL)
        OR AAD.ACCOUNT_ENABLED <> 'TRUE')
    AND U.DISABLED = 'false'
    AND U.DELETED_ON IS NULL
    AND U.EMAIL IS NOT NULL
ORDER BY COALESCE(WORKDAY_TERMINATION_DATE, '1900-01-01') DESC, UPPER(U.EMAIL) ASC;
