SELECT
    CONCAT(T.TABLE_CATALOG, '.', T.TABLE_SCHEMA, '.', T.TABLE_NAME) AS FQ_TABLE_NAME
    , TSM.FAILSAFE_MB
FROM SNOWFLAKE.ACCOUNT_USAGE.TABLES AS T
INNER JOIN (
    SELECT
        TABLE_CATALOG,
        TABLE_SCHEMA,
        TABLE_NAME,
        ROUND(SUM(FAILSAFE_BYTES)/1024.0/1024.0,1) AS FAILSAFE_MB
    FROM SNOWFLAKE.ACCOUNT_USAGE.TABLE_STORAGE_METRICS
    WHERE CATALOG_DROPPED IS NULL
        AND SCHEMA_DROPPED IS NULL
        AND TABLE_DROPPED IS NULL
        AND IS_TRANSIENT = 'NO'
        AND (
                (
                TABLE_CATALOG IN ('LAKE_FL', 'LAKE_JFB', 'LAKE_SXF')
                AND TABLE_SCHEMA NOT ILIKE 'HVR_INTERNAL%'
                AND TABLE_SCHEMA NOT ILIKE '%HISTORY'
                AND TABLE_SCHEMA NOT IN ('SEGMENT')
                )
            OR (
                TABLE_CATALOG = 'LAKE'
                AND TABLE_SCHEMA = 'ULTRA_WAREHOUSE'
                )
            )
    GROUP BY TABLE_CATALOG,
        TABLE_SCHEMA,
        TABLE_NAME
    ) AS TSM
ON TSM.TABLE_CATALOG = T.TABLE_CATALOG
    AND TSM.TABLE_SCHEMA = T.TABLE_SCHEMA
    AND TSM.TABLE_NAME = T.TABLE_NAME
WHERE T.IS_TRANSIENT = 'NO'
    AND T.DELETED IS NULL
    AND T.TABLE_TYPE = 'BASE TABLE'
    AND (
            (
            T.TABLE_CATALOG IN ('LAKE_FL', 'LAKE_JFB', 'LAKE_SXF')
            AND T.TABLE_SCHEMA NOT ILIKE 'HVR_INTERNAL%'
            AND T.TABLE_SCHEMA NOT ILIKE '%HISTORY'
            AND T.TABLE_SCHEMA NOT IN ('SEGMENT')
            )
        OR (
            T.TABLE_CATALOG = 'LAKE'
            AND T.TABLE_SCHEMA = 'ULTRA_WAREHOUSE'
            )
        )
ORDER BY FQ_TABLE_NAME ASC;