WITH _table_columns AS (
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    IS_NULLABLE,
    CASE
        WHEN DATA_TYPE = 'NUMBER'
        THEN CONCAT(DATA_TYPE, '(',NUMERIC_PRECISION, ',',NUMERIC_SCALE,')')
        WHEN DATA_TYPE = 'TEXT'
        THEN CONCAT(DATA_TYPE, '(',CHARACTER_MAXIMUM_LENGTH,')')
        WHEN DATA_TYPE ILIKE 'TIME%'
        THEN CONCAT(DATA_TYPE, '(',DATETIME_PRECISION,')')
    ELSE DATA_TYPE END AS COMBINED_DATATYPE
FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMNS AS C
WHERE
    DELETED IS NULL
    AND TABLE_CATALOG IN (
    'LAKE_CONSOLIDATED',
    'LAKE_FL',
    'LAKE_JFB',
    'LAKE_SXF'
    )
    AND TABLE_SCHEMA IN (
        'GDPR',
        'ULTRA_CART',
        'ULTRA_CMS',
        'ULTRA_CMS_HISTORY',
        'ULTRA_MERCHANT',
        'ULTRA_MERCHANT_HISTORY',
        'ULTRA_ROLLUP'
    )
    AND NOT COLUMN_NAME ILIKE ANY ('METADATA$%', 'META_ROW_SOURCE')
),
_view_columns AS (
SELECT
        TABLE_CATALOG,
        TABLE_SCHEMA,
        TABLE_NAME,
        COLUMN_NAME,
        IS_NULLABLE,
        CASE
            WHEN DATA_TYPE = 'NUMBER'
            THEN CONCAT(DATA_TYPE, '(',NUMERIC_PRECISION, ',',NUMERIC_SCALE,')')
            WHEN DATA_TYPE = 'TEXT'
            THEN CONCAT(DATA_TYPE, '(',CHARACTER_MAXIMUM_LENGTH,')')
            WHEN DATA_TYPE ILIKE 'TIME%'
            THEN CONCAT(DATA_TYPE, '(',DATETIME_PRECISION,')')
        ELSE DATA_TYPE END AS COMBINED_DATATYPE
    FROM SNOWFLAKE.ACCOUNT_USAGE.COLUMNS
    WHERE
        DELETED IS NULL
        AND TABLE_CATALOG IN (
        'LAKE_CONSOLIDATED_VIEW',
        'LAKE_FL_VIEW',
        'LAKE_JFB_VIEW',
        'LAKE_SXF_VIEW'
        )
        AND TABLE_SCHEMA IN (
            'GDPR',
            'ULTRA_CART',
            'ULTRA_CMS',
            'ULTRA_CMS_HISTORY',
            'ULTRA_MERCHANT',
            'ULTRA_MERCHANT_HISTORY',
            'ULTRA_ROLLUP'
        )
),
_objects_in_both AS (
SELECT DISTINCT
    T.TABLE_CATALOG,
    T.TABLE_SCHEMA,
    T.TABLE_NAME
FROM _table_columns AS T
    JOIN _view_columns AS V
        ON CONCAT(T.TABLE_CATALOG, '_VIEW') = V.TABLE_CATALOG
        AND T.TABLE_SCHEMA = V.TABLE_SCHEMA
        AND T.TABLE_NAME = V.TABLE_NAME
)

SELECT
    CONCAT(C.TABLE_CATALOG, '.', C.TABLE_SCHEMA, '.', C.TABLE_NAME) AS TABLE_NAME,
    C.COLUMN_NAME,
    C.COMBINED_DATATYPE AS TABLE_DATATYPE,
    COALESCE(V.COMBINED_DATATYPE, '') AS COLUMN_DATATYPE,
    CASE
        WHEN V.COLUMN_NAME IS NULL
        THEN 'Column is missing from View'
        WHEN C.COMBINED_DATATYPE <> V.COMBINED_DATATYPE
        THEN 'Datatype mismatch'
        END
    AS REASON
FROM _table_columns AS C
JOIN _objects_in_both AS X
    ON C.TABLE_CATALOG = X.TABLE_CATALOG
    AND C.TABLE_SCHEMA = X.TABLE_SCHEMA
    AND C.TABLE_NAME = X.TABLE_NAME
LEFT JOIN _view_columns AS V
    ON CONCAT(C.TABLE_CATALOG, '_VIEW') = V.TABLE_CATALOG
    AND C.TABLE_SCHEMA = V.TABLE_SCHEMA
    AND C.TABLE_NAME = V.TABLE_NAME
    AND UPPER(C.COLUMN_NAME) = UPPER(V.COLUMN_NAME)
WHERE
    C.COMBINED_DATATYPE <> COALESCE(V.COMBINED_DATATYPE, '')
ORDER BY
    TABLE_NAME ASC,
    C.COLUMN_NAME ASC
;
