SELECT DISTINCT
    NAME AS USER_NAME,
    COALESCE(U.LAST_SUCCESS_LOGIN, U.CREATED_ON) AS LAST_ACTIVE,
    DATEDIFF(DAY, COALESCE(U.LAST_SUCCESS_LOGIN, U.CREATED_ON), CURRENT_DATE) AS DAYS_INACTIVE,
    CONCAT('DROP USER IF EXISTS "', NAME, '";') AS QUERY_TO_RUN
FROM UTIL.PUBLIC.USERS AS U
WHERE U.DISABLED ILIKE 'true'
    AND U.DELETED_ON IS NULL
    AND COALESCE(U.LAST_SUCCESS_LOGIN, U.CREATED_ON) <= DATEADD(DAY, -180, CURRENT_DATE())
ORDER BY LAST_ACTIVE ASC;
