SELECT
    NAME,
    DATEDIFF(DAY, PASSWORD_LAST_SET_TIME, CURRENT_DATE()) AS DAYS_SINCE_LAST_PW_RESET
FROM UTIL.PUBLIC.USERS
WHERE NAME NOT ILIKE '%@%'
    AND DELETED_ON IS NULL
    AND DISABLED NOT ILIKE 'true'
    AND HAS_PASSWORD = 'TRUE'
    AND DATEDIFF(DAY, PASSWORD_LAST_SET_TIME, CURRENT_DATE()) >= 60
ORDER BY DAYS_SINCE_LAST_PW_RESET DESC, NAME ASC
;
