WITH _raw_columns AS (
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME
FROM LAKE_FL.INFORMATION_SCHEMA.COLUMNS AS LC
WHERE TABLE_SCHEMA IN (
    'GDPR', 'ULTRA_CART', 'ULTRA_CMS', 'ULTRA_CMS_HISTORY', 'ULTRA_MERCHANT', 'ULTRA_MERCHANT_HISTORY', 'ULTRA_ROLLUP'
    )
UNION ALL
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME
FROM LAKE_JFB.INFORMATION_SCHEMA.COLUMNS AS LC
WHERE TABLE_SCHEMA IN (
    'GDPR', 'ULTRA_CART', 'ULTRA_CMS', 'ULTRA_CMS_HISTORY', 'ULTRA_MERCHANT', 'ULTRA_MERCHANT_HISTORY', 'ULTRA_ROLLUP'
    )
UNION ALL
SELECT
    TABLE_CATALOG,
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME
FROM LAKE_SXF.INFORMATION_SCHEMA.COLUMNS AS LC
WHERE TABLE_SCHEMA IN (
    'GDPR', 'ULTRA_CART', 'ULTRA_CMS', 'ULTRA_CMS_HISTORY', 'ULTRA_MERCHANT', 'ULTRA_MERCHANT_HISTORY', 'ULTRA_ROLLUP'
    )
),
_combined_columns AS (
SELECT
    TABLE_SCHEMA,
    TABLE_NAME,
    COLUMN_NAME,
    COUNT(DISTINCT TABLE_CATALOG) AS DB_CNT
FROM _raw_columns AS U
    GROUP BY TABLE_SCHEMA,
        TABLE_NAME,
        COLUMN_NAME
),
_tables_in_both AS (
/* Not all Tables need to be in LAKE_CONSOLIDATED */
SELECT DISTINCT
    U.TABLE_SCHEMA,
    U.TABLE_NAME
FROM _combined_columns AS U
    JOIN LAKE_CONSOLIDATED.INFORMATION_SCHEMA.COLUMNS AS LC
        ON U.TABLE_SCHEMA = LC.TABLE_SCHEMA
        AND U.TABLE_NAME = LC.TABLE_NAME
    WHERE LC.TABLE_SCHEMA IN (
    'GDPR', 'ULTRA_CART', 'ULTRA_CMS', 'ULTRA_CMS_HISTORY', 'ULTRA_MERCHANT', 'ULTRA_MERCHANT_HISTORY', 'ULTRA_ROLLUP'
    )
)

SELECT
    C.TABLE_SCHEMA,
    C.TABLE_NAME,
    C.COLUMN_NAME
FROM _combined_columns AS C
JOIN _tables_in_both AS X
    ON C.TABLE_SCHEMA = X.TABLE_SCHEMA
    AND C.TABLE_NAME = X.TABLE_NAME
LEFT JOIN LAKE_CONSOLIDATED.INFORMATION_SCHEMA.COLUMNS AS LC
    ON C.TABLE_SCHEMA = LC.TABLE_SCHEMA
    AND C.TABLE_NAME = LC.TABLE_NAME
    AND C.COLUMN_NAME = LC.COLUMN_NAME
WHERE LC.COLUMN_NAME IS NULL
    /* Ignore HVR system columns that we don't want in LAKE_CONSOLIDATED */
    AND C.COLUMN_NAME NOT IN (
    'HVR_CHANGE_SEQUENCE', 'HVR_CHANGE_TIME',
    'META_ROW_SOURCE', 'META_SOURCE_CHANGE_DATETIME'
    )
    /* Only include Columns in all LAKE databases */
    AND DB_CNT = 3
ORDER BY TABLE_SCHEMA ASC, TABLE_NAME ASC, COLUMN_NAME ASC
;
