SELECT DISTINCT NAME AS USER_NAME
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS AS U
WHERE U.DISABLED = 'false'
    AND U.DELETED_ON IS NULL
    AND U.NAME LIKE '%@%'
    AND COALESCE(U.LAST_SUCCESS_LOGIN, U.CREATED_ON) <= DATEADD(DAY, -75, CURRENT_DATE())
ORDER BY USER_NAME ASC;
