CREATE TRANSIENT TABLE IF NOT EXISTS breakage.fabletics_token_breakage_report (
	brand VARCHAR(16777216),
	region VARCHAR(16777216),
	country VARCHAR(16777216),
	currency VARCHAR(15),
	original_credit_tender VARCHAR(16777216),
	original_credit_reason VARCHAR(16777216),
	original_credit_type VARCHAR(16777216),
	original_issued_amount FLOAT,
	original_issued_month DATE,
	activity_month DATE,
	credit_tenure NUMBER(38,0),
	issued_to_date FLOAT,
	redeemed_to_date FLOAT,
	cancelled_to_date FLOAT,
	expired_to_date FLOAT,
	unredeemed_to_date FLOAT,
	redeemed_rate_to_date FLOAT,
	expected_redeemed_rate FLOAT,
	expected_unredeemed_rate FLOAT,
	actual_redeemed_rate_vs_expected FLOAT,
	expected_breakage_to_record FLOAT,
	breakage_recorded FLOAT,
	expected_redeemed_rate_max FLOAT,
	expected_additional_redeemed FLOAT,
	expected_additional_cancelled FLOAT,
	expected_additional_activity_amount_m14to19 FLOAT
);
