CREATE TRANSIENT TABLE IF NOT EXISTS month_end.emp_token (
	membership_token_id NUMBER(38,0),
	membership_id NUMBER(38,0),
	store_id NUMBER(38,0),
	customer_id NUMBER(38,0),
	datetime_activated TIMESTAMP_NTZ(3),
	membership_statuscode NUMBER(38,0),
	membership_token_reason_id NUMBER(38,0),
	token_reason_label VARCHAR(50),
	credit_tender VARCHAR(7),
	country_code VARCHAR(5),
	store_group_id NUMBER(38,0),
	purchase_price NUMBER(19,4),
	currency_code VARCHAR(3),
	statuscode NUMBER(38,0),
	datetime_added TIMESTAMP_NTZ(3),
	datetime_optin TIMESTAMP_NTZ(3),
	date_migrated_vip DATE,
	date_migrated_payg DATE,
	extension_months NUMBER(38,0),
	scenario VARCHAR(77),
	date_expires DATE,
	adjusted_datetime_optin TIMESTAMP_TZ(3)
);
