CREATE TRANSIENT TABLE IF NOT EXISTS month_end.fin012_giftco_rollforward_snapshot (
	membership_store_brand VARCHAR(255),
	store_brand VARCHAR(20),
	store_country VARCHAR(50),
	store_region VARCHAR(32),
	purchase_location VARCHAR(6),
	original_credit_id NUMBER(38,0),
	merchant_id NUMBER(38,0),
	legal_entity VARCHAR(4),
	store_credit_id NUMBER(38,0),
	transfer_in_id NUMBER(38,0),
	transfer_in_id_type VARCHAR(16777216),
	transfer_out_id NUMBER(38,0),
	transfer_out_id_type VARCHAR(16777216),
	original_issued_month DATE,
	original_credit_tender VARCHAR(7),
	original_credit_type VARCHAR(16),
	original_credit_reason VARCHAR(50),
	new_credit_type VARCHAR(16),
	new_credit_reason VARCHAR(50),
	credit_activity_type VARCHAR(16777216),
	activity_month DATE,
	activity_amount NUMBER(20,4),
	giftco_type VARCHAR(45),
	snapshot_datetime TIMESTAMP_LTZ(9)
);
