CREATE TRANSIENT TABLE IF NOT EXISTS month_end.retail_orders (
	store_id NUMBER(38,0),
	store_brand VARCHAR(20),
	store_country VARCHAR(50),
	mapped_store_id NUMBER(38,5),
	order_id NUMBER(38,0),
	order_classification VARCHAR(50),
	activating VARCHAR(14),
	units NUMBER(38,0),
	subtotal NUMBER(19,4),
	discount NUMBER(19,4),
	shipping NUMBER(19,4),
	tax NUMBER(19,4),
	estimated_cost_product_usd NUMBER(37,10),
	cost_shipping NUMBER(26,11),
	credit NUMBER(19,4),
	creditcard NUMBER(19,4),
	cash NUMBER(19,4),
	payment_method VARCHAR(55),
	customer_id NUMBER(38,0),
	ecom NUMBER(1,0),
	vip_activation NUMBER(1,0),
	order_segment VARCHAR(11),
	customer_datetime_added DATE,
	order_datetime_added TIMESTAMP_TZ(9),
	tbl_datetime_added TIMESTAMP_LTZ(9)
);
