CREATE TRANSIENT TABLE IF NOT EXISTS month_end.gaap_refund_waterfalls_full (
	membership_store_id NUMBER(38,0),
	membership_store VARCHAR(101),
	order_type VARCHAR(34),
	date_shipped DATE,
	order_id NUMBER(38,0),
	rate NUMBER(19,6),
	gross_rev_after_discount NUMBER(32,10),
	total_cash_and_cash_credit NUMBER(33,10),
	refund_type VARCHAR(20),
	refund_id NUMBER(38,0),
	refund_total NUMBER(20,6),
	monthoffset NUMBER(10,0),
	refund_month DATE,
	payment_method VARCHAR(25),
	order_count NUMBER(1,0),
	order_total NUMBER(33,10),
	refund_group NUMBER(32,6),
	order_total_group NUMBER(38,10),
	order_count_group NUMBER(18,0),
	refund_percentage NUMBER(38,12)
);
