CREATE TRANSIENT TABLE IF NOT EXISTS month_end.fin012_giftco_rollforward (
	membership_store_brand VARCHAR(155),
	store_brand VARCHAR(155),
	store_country VARCHAR(155),
	store_region VARCHAR(155),
	purchase_location VARCHAR(155),
	event_store_id NUMBER(38,0),
	membership_store_id NUMBER(38,0),
	original_credit_id NUMBER(38,0),
	merchant_id NUMBER(38,0),
	legal_entity VARCHAR(155),
	store_credit_id NUMBER(38,0),
	transfer_in_id NUMBER(38,0),
	transfer_in_id_type VARCHAR(155),
	transfer_out_id NUMBER(38,0),
	transfer_out_id_type VARCHAR(155),
	original_issued_month DATE,
	original_credit_tender VARCHAR(155),
	original_credit_type VARCHAR(155),
	original_credit_reason VARCHAR(155),
	new_credit_type VARCHAR(155),
	new_credit_reason VARCHAR(155),
	credit_activity_type VARCHAR(155),
	activity_month DATE,
	activity_amount NUMBER(20,4),
	giftco_type VARCHAR(155),
	data_refresh_datetime TIMESTAMP_NTZ(9)
);
