from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_dim import SnowflakeMartDimOperator


def get_mart_operator():
    return SnowflakeMartDimOperator(
        table='dim_universal_product',
        use_surrogate_key=True,
        initial_load_value='1900-01-01',
        transform_proc_list=['stg.transform_dim_universal_product.sql'],
        column_list=[
            Column('sku', 'VARCHAR(350)', uniqueness=True),
            Column('centric_color_id', 'NUMBER(38, 0)'),
            Column('centric_style_id', 'NUMBER(38, 0)'),
            Column('centric_size_id', 'NUMBER(38, 0)'),
            Column('last_showroom', 'TIMESTAMP_TZ'),
            Column('season', 'VARCHAR(350)'),
            Column('upm_tier', 'NUMBER(38, 0)'),
            Column('brand', 'VARCHAR(350)'),
            Column('style_sku', 'VARCHAR(350)'),
            Column('style_number_po', 'VARCHAR(350)'),
            Column('tfg_gender', 'VARCHAR(350)'),
            Column('tfg_core_fashion', 'VARCHAR(350)'),
            Column('tfg_rank', 'VARCHAR(350)'),
            Column('tfg_coverage', 'VARCHAR(350)'),
            Column('color_sku', 'VARCHAR(350)'),
            Column('colorway_sku', 'VARCHAR(350)'),
            Column('color_name', 'VARCHAR(350)'),
            Column('site_color_name', 'VARCHAR(350)'),
            Column('size_sku', 'VARCHAR(350)'),
            Column('size', 'VARCHAR(350)'),
            Column('category', 'VARCHAR(350)'),
            Column('subcategory', 'VARCHAR(350)'),
            Column('department', 'VARCHAR(350)'),
            Column('subdepartment', 'VARCHAR(350)'),
            Column('class', 'VARCHAR(350)'),
            Column('subclass', 'VARCHAR(350)'),
            Column('centric_material_id', 'VARCHAR(350)'),
            Column('material_name', 'VARCHAR(350)'),
            Column('tfg_fabric_category', 'VARCHAR(350)'),
            Column('tfg_material_opacity', 'VARCHAR(350)'),
            Column('description', 'VARCHAR(350)'),
            Column('direct_non_direct', 'VARCHAR(350)'),
            Column('heel_height', 'VARCHAR(350)'),
            Column('latest_launch_date', 'TIMESTAMP_TZ'),
            Column('avg_landing_cost', 'VARCHAR(350)'),
            Column('reorder_status', 'VARCHAR(350)'),
            Column('shared', 'VARCHAR(350)'),
            Column('size_13_15', 'VARCHAR(350)'),
            Column('ww_wc', 'VARCHAR(350)'),
            Column('factory', 'VARCHAR(350)'),
            Column('buy_timing', 'VARCHAR(350)'),
            Column('is_chase', 'VARCHAR(350)'),
            Column('ca_blended_ldp', 'VARCHAR(350)'),
            Column('solid_print_colorblocked', 'VARCHAR(350)'),
            Column('eco_system', 'VARCHAR(350)'),
            Column('is_editorial', 'VARCHAR(350)'),
            Column('fabric_shop', 'VARCHAR(350)'),
            Column('block_fit', 'VARCHAR(350)'),
            Column('inseam_length', 'VARCHAR(350)'),
            Column('sku_status', 'VARCHAR(350)'),
            Column('style_status', 'VARCHAR(350)'),
            Column('ca_product_tag_id', 'VARCHAR(350)'),
            Column('us_product_tag_id', 'VARCHAR(350)'),
            Column('us_product_id', 'VARCHAR(350)'),
            Column('us_blended_ldp', 'VARCHAR(350)'),
            Column('go_live_date', 'TIMESTAMP_TZ'),
            Column('style_name', 'VARCHAR(350)'),
            Column('size_scale', 'VARCHAR(350)'),
            Column('bright', 'VARCHAR(350)'),
            Column('bundle_retail', 'VARCHAR(350)'),
            Column('category_type', 'VARCHAR(350)'),
            Column('color_roll_up', 'VARCHAR(350)'),
            Column('color_tone', 'VARCHAR(350)'),
            Column('first_showroom', 'VARCHAR(350)'),
            Column('first_vendor', 'VARCHAR(350)'),
            Column('heat', 'VARCHAR(350)'),
            Column('inv_aged_days', 'NUMBER(38, 0)'),
            Column('inv_aged_months', 'NUMBER(38, 0)'),
            Column('inv_aged_status', 'VARCHAR(350)'),
            Column('last_received_date', 'TIMESTAMP_TZ'),
            Column('latest_qty', 'NUMBER(38, 0)'),
            Column('persona', 'VARCHAR(350)'),
            Column('site_name', 'VARCHAR(350)'),
            Column('msrp', 'NUMBER(38, 2)'),
            Column('vip_price', 'NUMBER(38, 2)'),
            Column('landed_cost', 'NUMBER(38, 2)'),
            Column('regular_vendor_price', 'NUMBER(38, 2)'),
            Column('plus_vendor_price', 'NUMBER(38, 2)'),
        ],
        watermark_tables=[
            'lake_view.centric.ed_colorway',
            'lake_view.centric.ed_sku',
        ],
    )
