from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_dim import SnowflakeMartDimOperator


def get_mart_operator():
    return SnowflakeMartDimOperator(
        table='dim_customer',
        initial_load_value='1900-01-01',
        transform_proc_list=['stg.transform_dim_customer.sql'],
        use_surrogate_key=False,
        column_list=[
            Column('customer_id', 'INT', uniqueness=True),
            Column('meta_original_customer_id', 'INT'),
            Column('first_name', 'VARCHAR(25)'),
            Column('last_name', 'VARCHAR(25)'),
            Column('email', 'VARCHAR(75)'),
            Column('store_id', 'INT'),
            Column('primary_registration_store_id', 'INT'),
            Column('secondary_registration_store_id', 'INT'),
            Column('is_secondary_registration_after_vip', 'BOOLEAN'),
            Column('default_address_id', 'INT'),
            Column('default_address1', 'VARCHAR(100)'),
            Column('default_address2', 'VARCHAR(100)'),
            Column('default_city', 'VARCHAR(100)'),
            Column('default_state_province', 'VARCHAR(25)'),
            Column('default_postal_code', 'VARCHAR(25)'),
            Column('default_country_code', 'VARCHAR(20)'),
            Column('detail_country_code', 'VARCHAR(20)'),
            Column('specialty_country_code', 'VARCHAR(20)'),
            Column('finance_specialty_store', 'VARCHAR(20)'),
            Column('birth_day', 'INT'),
            Column('birth_year', 'INT'),
            Column('birth_month', 'INT'),
            Column('quiz_zip', 'VARCHAR(50)'),
            Column('top_size', 'VARCHAR(50)'),
            Column('bottom_size', 'VARCHAR(50)'),
            Column('bra_size', 'VARCHAR(50)'),
            Column('onepiece_size', 'VARCHAR(50)'),
            Column('denim_size', 'VARCHAR(20)'),
            Column('dress_size', 'VARCHAR(20)'),
            Column('shoe_size', 'VARCHAR(20)'),
            Column('gender', 'VARCHAR(10)'),
            Column('first_gender', 'VARCHAR(10)'),
            Column('is_friend_referral', 'BOOLEAN'),
            Column('membership_level', 'VARCHAR(50)'),
            Column('how_did_you_hear', 'VARCHAR(50)'),
            Column('how_did_you_hear_parent', 'VARCHAR(50)'),
            Column('registration_local_datetime', 'TIMESTAMP_TZ'),
            Column('secondary_registration_local_datetime', 'TIMESTAMP_TZ'),
            Column('is_blacklisted', 'BOOLEAN'),
            Column('blacklist_reason', 'VARCHAR(50)'),
            Column('is_free_trial', 'BOOLEAN'),
            Column('is_free_trial_promo', 'BOOLEAN'),
            Column('is_free_trial_gift_order', 'BOOLEAN'),
            Column('is_cross_promo', 'BOOLEAN'),
            Column('is_metanav', 'BOOLEAN'),
            Column('is_scrubs_customer', 'BOOLEAN'),
            Column('is_test_customer', 'BOOLEAN'),
            Column('is_opt_out', 'BOOLEAN'),
            Column('sms_opt_in_datetime', 'TIMESTAMP_TZ'),
            Column('email_opt_in_datetime', 'TIMESTAMP_TZ'),
            Column('bralette_size', 'VARCHAR(50)'),
            Column('undie_size', 'VARCHAR(50)'),
            Column('lingerie_sleep_size', 'VARCHAR(50)'),
            Column('emp_optin_datetime', 'TIMESTAMP_TZ'),
            Column('first_mobile_app_session_local_datetime', 'TIMESTAMP_TZ'),
            Column('first_mobile_app_session_id', 'INT'),
            Column('first_mobile_app_order_local_datetime', 'TIMESTAMP_TZ'),
            Column('first_mobile_app_order_id', 'INT'),
            Column('mobile_app_cohort_month_date', 'DATE'),
            Column('mobile_app_cohort_os', 'VARCHAR(25)'),
            Column('onetrust_consent_strictlynecessary', 'Boolean'),
            Column('onetrust_consent_performance', 'Boolean'),
            Column('onetrust_consent_functional', 'Boolean'),
            Column('onetrust_consent_targeting', 'Boolean'),
            Column('onetrust_consent_social', 'Boolean'),
            Column('onetrust_update_datetime', 'TIMESTAMP_NTZ(3)'),
            Column('registration_type', 'VARCHAR'),
            Column('current_membership_type', 'VARCHAR(50)'),
            Column('membership_price', 'NUMBER(19,4)'),
            Column('membership_plan_id', 'INT'),
            Column('customer_bucket_group', 'INT'),
            Column('membership_state', 'VARCHAR(50)'),
            Column('is_deleted', 'Boolean'),
        ],
        watermark_tables=[
            'lake_consolidated.ultra_merchant.customer',
            'lake_consolidated.ultra_merchant.fraud_customer',
            'lake_consolidated.ultra_merchant."ORDER"',
            'lake_consolidated.ultra_merchant.order_classification',
            'lake_consolidated.ultra_merchant.order_discount',
            'lake_consolidated.ultra_merchant.membership',
            'lake_consolidated.ultra_merchant.membership_level',
            'lake_consolidated.ultra_merchant.customer_detail',
            'lake_consolidated.ultra_merchant.session',
            'lake_consolidated.ultra_merchant.membership_signup',
            'lake_consolidated.ultra_merchant.membership_brand_signup',
            'lake_consolidated.ultra_merchant.membership_plan_membership_brand',
            'lake_consolidated.ultra_merchant_history.customer',
            'lake_consolidated.ultra_merchant.membership_trial',
            'lake_consolidated.ultra_merchant.gift_order',
            'lake_consolidated.ultra_merchant.customer_referrer',
            'lake_consolidated.ultra_merchant.hdyh_global_list_referrer',
            'lake_consolidated.ultra_merchant.hdyh_global_list',
            'reporting_base_prod.staging.site_visit_metrics',
            'reporting_base_prod.shared.mobile_app_session_os_updated',
            'edw_prod.stg.lkp_membership_state',
            'edw_prod.stg.dim_address',
            'edw_prod.stg.dim_customer_detail_history',
            'edw_prod.reference.test_customer',
            'lake.builder.hdyh_flattened',
            'lake.emarsys.email_subscribes',
            'lake.media.attentive_attentive_sms_legacy',
            'edw_prod.stg.dim_customer_sailthru_history',
            'edw_prod.stg.lkp_order_classification',
        ],
    )
