from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_scd import SnowflakeMartSCDOperator


def get_mart_operator():
    return SnowflakeMartSCDOperator(
        table='dim_promo_history',
        initial_load_value='1900-01-01',
        transform_proc_list=['stg.transform_dim_promo_history.sql'],
        use_surrogate_key=True,
        column_list=[
            Column('promo_id', 'INT', uniqueness=True, type_2=True),
            Column('meta_original_promo_id', 'INT', type_2=True),
            Column('promo_name', 'VARCHAR(50)', type_2=True),
            Column('first_promo_code', 'VARCHAR(255)', type_2=True),
            Column('promo_code', 'VARCHAR(255)', type_2=True),
            Column('promo_description', 'VARCHAR(255)', type_2=True),
            Column('promo_type', 'VARCHAR(100)', type_2=True),
            Column('promo_cms_type', 'VARCHAR(50)', type_2=True),
            Column('promo_cms_description', 'VARCHAR(500)', type_2=True),
            Column('promo_classification', 'VARCHAR(50)', type_2=True),
            Column('discount_method', 'VARCHAR(25)', type_2=True),
            Column('subtotal_discount', 'VARCHAR(50)', type_2=True),
            Column('shipping_discount', 'VARCHAR(50)', type_2=True),
            Column('promo_status_code', 'INT', type_2=True),
            Column('promo_status', 'VARCHAR(50)', type_2=True),
            Column('promo_start_datetime', 'TIMESTAMP_TZ(3)', type_2=True),
            Column('promo_end_datetime', 'TIMESTAMP_TZ(3)', type_2=True),
            Column('is_deleted', 'BOOLEAN', type_2=True),
            Column('promo_store_applied', 'VARCHAR', type_2=True),
            Column('required_product_quantity', 'INT', type_2=True),
            Column('min_product_quantity', 'INT', type_2=True),
            Column('fpl_included', 'VARCHAR', type_2=True),
            Column('fpl_excluded', 'VARCHAR', type_2=True),
            Column('fpl_required', 'VARCHAR', type_2=True),
            Column('category_included', 'VARCHAR', type_2=True),
            Column('category_excluded', 'VARCHAR', type_2=True),
            Column('category_required', 'VARCHAR', type_2=True),
            Column('promo_name_cms', 'VARCHAR', type_2=True),
            Column('membership_choice', 'VARCHAR', type_2=True),
            Column('registration_date_option', 'VARCHAR', type_2=True),
            Column('registration_exact_date', 'DATETIME', type_2=True),
            Column('registration_start_date', 'DATETIME', type_2=True),
            Column('registration_end_date', 'DATETIME', type_2=True),
            Column('registration_day', 'VARCHAR', type_2=True),
            Column('registration_day_start', 'VARCHAR', type_2=True),
            Column('registration_day_end', 'VARCHAR', type_2=True),
            Column('gender_selected', 'VARCHAR', type_2=True),
            Column('membership_reward_multiplier', 'VARCHAR', type_2=True),
        ],
        watermark_tables=[
            'lake_consolidated.ultra_merchant_history.promo',
            'lake_consolidated.ultra_merchant.promo_promo_classfication',
            'lake_consolidated.ultra_merchant.promo_classification',
            'lake_consolidated.ultra_merchant.promo_type',
            'lake_consolidated.ultra_merchant_history.discount',
            'lake_consolidated.ultra_cms_history.ui_promo_management_promos',
            'lake_consolidated.ultra_merchant.featured_product_location',
            'lake_consolidated.ultra_merchant.product_category',
        ],
    )
