from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_dim import SnowflakeMartDimOperator


def get_mart_operator():
    return SnowflakeMartDimOperator(
        table="dim_product",
        use_surrogate_key=False,
        initial_load_value="1900-01-01",
        transform_proc_list=["stg.transform_dim_product.sql"],
        column_list=[
            Column("product_id", "INT", uniqueness=True),
            Column("master_product_id", "INT"),
            Column("meta_original_product_id", "INT"),
            Column("meta_original_master_product_id", "INT"),
            Column("store_id", "INT"),
            Column("sku", "VARCHAR(30)"),
            Column("product_sku", "VARCHAR(30)"),
            Column("base_sku", "VARCHAR(30)"),
            Column("product_name", "VARCHAR(100)"),
            Column("product_alias", "VARCHAR(100)"),
            Column("product_type", "VARCHAR(50)"),
            Column("brand", "VARCHAR(100)"),
            Column("manufacturer", "VARCHAR(255)"),
            Column("current_showroom_date", "DATE"),
            Column("product_category_id", "INT"),
            Column("product_category", "VARCHAR(200)"),
            Column("department", "VARCHAR(100)"),
            Column("category", "VARCHAR(3000)"),
            Column("subcategory", "VARCHAR(3000)"),
            Column("class", "VARCHAR(3000)"),
            Column("color", "VARCHAR(200)"),
            Column("size", "VARCHAR(200)"),
            Column("material", "VARCHAR(200)"),
            Column("heel_height", "VARCHAR(200)"),
            Column("occasion", "VARCHAR(200)"),
            Column("vip_unit_price", "NUMBER(19,4)"),
            Column("retail_unit_price", "NUMBER(19,4)"),
            Column("sale_price", "NUMBER(19,4)"),
            Column("short_description", "VARCHAR(1000)"),
            Column("medium_description", "VARCHAR(2000)"),
            Column("long_description", "VARCHAR(4000)"),
            Column("is_active", "BOOLEAN"),
            Column("is_free", "BOOLEAN"),
            Column("image_url", "VARCHAR(200)"),
            Column("product_status_code", "VARCHAR(20)"),
            Column("product_status", "VARCHAR(50)"),
            Column("wms_class", "VARCHAR(50)"),
            Column("group_code", "VARCHAR"),
            Column("product_id_object_type", "VARCHAR"),
            Column("master_product_last_update_datetime", "TIMESTAMP_LTZ(3)"),
            Column("membership_brand_id", "INT"),
            Column("is_endowment_eligible", "BOOLEAN"),
            Column("is_warehouse_product", "BOOLEAN"),
            Column("warehouse_unit_price", "NUMBER(19,4)"),
        ],
        watermark_tables=[
            "lake_consolidated.ultra_merchant.product",
            "lake_consolidated.ultra_rollup.products_in_stock_product_feed",
            "lake_consolidated.ultra_merchant.product_tag",
            "lake_consolidated.ultra_merchant.item",
            "edw_prod.stg.dim_sku",
            "lake_consolidated.ultra_merchant.pricing_option",
            "lake_consolidated.ultra_merchant.product_endowment",
        ],
    )
