from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_dim import SnowflakeMartDimOperator


def get_mart_operator():
    return SnowflakeMartDimOperator(
        table="dim_credit",
        use_surrogate_key=False,
        initial_load_value="1900-01-01",
        transform_proc_list=["stg.transform_dim_credit.sql"],
        column_list=[
            Column("credit_key", "NUMBER(38,0)"),
            Column("credit_id", "NUMBER(38,0)", uniqueness=True),
            Column("meta_original_credit_id", "NUMBER(38,0)", uniqueness=True),
            Column("store_id", "NUMBER(38,0)", uniqueness=True),
            Column("customer_id", "NUMBER(38,0)"),
            Column("administrator_id", "NUMBER(38,0)"),
            Column("credit_order_id", "NUMBER(38,0)"),
            Column("source_credit_id_type", "VARCHAR(50)"),
            Column("credit_report_mapping", "VARCHAR(50)"),
            Column("credit_report_sub_mapping", "VARCHAR(50)"),
            Column(
                "credit_type",
                "VARCHAR(50)",
            ),
            Column("credit_tender", "VARCHAR(50)"),
            Column("credit_reason", "VARCHAR(50)"),
            Column("credit_issuance_reason", "VARCHAR(50)"),
            Column("credit_issued_hq_datetime", "TIMESTAMP_TZ(9)", uniqueness=True),
            Column("credit_issued_local_datetime", "TIMESTAMP_TZ(9)"),
            Column("credit_expiration_local_datetime", "TIMESTAMP_TZ(9)"),
            Column("original_credit_key", " NUMBER(38,0)"),
            Column("original_credit_tender", "VARCHAR(25)"),
            Column("original_credit_type", "VARCHAR(25)"),
            Column("original_credit_issued_local_datetime", "TIMESTAMP_TZ(9)"),
            Column("original_credit_expiration_local_datetime", "TIMESTAMP_TZ(9)"),
            Column("original_credit_reason", "VARCHAR(50)"),
            Column("original_credit_match_reason", "VARCHAR(50)"),
            Column("deferred_recognition_label_token", "VARCHAR(55)"),
            Column("credit_country_code", "VARCHAR(30)"),
            Column("credit_issued_usd_conversion_rate", "NUMBER(18,6)"),
            Column("credit_issued_local_gross_vat_amount", "NUMBER(19,4)"),
            Column("credit_issued_equivalent_count", "NUMBER(19,4)"),
            Column("credit_issued_local_amount", "NUMBER(19,4)"),
            Column("is_cancelled_before_token_conversion", "BOOLEAN"),
            Column("is_test_customer", "BOOLEAN"),
            Column("is_bill_me_now_online", "BOOLEAN"),
            Column("is_bill_me_now_gms", "BOOLEAN"),
        ],
        watermark_tables=[
            "lake_consolidated.ultra_merchant.order_credit",
            "lake_consolidated.ultra_merchant_history.customer",
            "lake_consolidated.ultra_merchant_history.membership",
            "lake_consolidated.ultra_merchant.store_credit",
            "lake_consolidated.ultra_merchant.store_credit_reason",
            "lake_consolidated.ultra_merchant.customer",
            "lake_consolidated.ultra_merchant.refund",
            "lake_consolidated.ultra_merchant.refund_store_credit",
            "lake_consolidated.ultra_merchant.gift_certificate",
            "lake_consolidated.ultra_merchant.gift_certificate_store_credit",
            "lake_consolidated.ultra_merchant.store_credit_conversion",
            "lake_consolidated.ultra_merchant.credit_transfer_transaction",
            "lake_consolidated.ultra_merchant.address",
            "lake_consolidated.ultra_merchant.membership_token",
            "lake_consolidated.ultra_merchant.membership_token_reason",
            "lake_consolidated.ultra_merchant.membership_store_credit",
            "lake_consolidated.ultra_merchant.credit_transfer_transaction",
            'lake_consolidated.ultra_merchant."ORDER"',
            "lake_consolidated.ultra_merchant.membership_billing",
            "lake_consolidated.ultra_merchant.bounceback_endowment",
            "edw_prod.reference.currency_exchange_rate",
            "edw_prod.reference.test_customer",
            "lake_consolidated.ultra_merchant.membership_token_credit_conversion",
        ],
    )
