from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_fact import SnowflakeMartFactOperator


def get_mart_operator():
    return SnowflakeMartFactOperator(
        table='fact_registration',
        use_surrogate_key=True,
        transform_proc_list=['stg.transform_fact_registration.sql'],
        column_list=[
            Column('membership_event_key', 'NUMBER(38,0)'),
            Column('store_id', 'NUMBER(38,0)', uniqueness=True),
            Column('customer_id', 'NUMBER(38,0)', uniqueness=True),
            Column('meta_original_customer_id', 'NUMBER(38,0)'),
            Column('registration_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('session_id', 'NUMBER(38,0)'),
            Column('registration_channel_type', 'VARCHAR(255)'),
            Column('registration_channel', 'VARCHAR(255)'),
            Column('registration_subchannel', 'VARCHAR(255)'),
            Column('is_reactivated_lead_raw', 'BOOLEAN'),
            Column('uri', 'STRING'),
            Column('hdyh_values_shown', 'VARCHAR(255)'),
            Column('cdetail_lead_type', 'VARCHAR(255)'),
            Column('cdetail_origin', 'VARCHAR(255)'),
            Column('cdetail_initial_medium', 'VARCHAR(255)'),
            Column('how_did_you_hear', 'STRING'),
            Column('how_did_you_hear_parent', 'VARCHAR(50)'),
            Column('dm_gateway_id', 'VARCHAR(50)'),
            Column('dm_site_id', 'VARCHAR(50)'),
            Column('utm_medium', 'STRING'),
            Column('utm_source', 'STRING'),
            Column('utm_campaign', 'STRING'),
            Column('utm_content', 'STRING'),
            Column('utm_term', 'STRING'),
            Column('ccode', 'STRING'),
            Column('pcode', 'STRING'),
            Column('scode', 'STRING'),
            Column('acode', 'STRING'),
            Column('master_product_id', 'VARCHAR(200)'),
            Column('device', 'STRING'),
            Column('browser', 'STRING'),
            Column('uri_utm_medium', 'STRING'),
            Column('uri_utm_source', 'STRING'),
            Column('uri_utm_campaign', 'STRING'),
            Column('uri_utm_content', 'STRING'),
            Column('uri_utm_term', 'STRING'),
            Column('uri_device', 'STRING'),
            Column('uri_browser', 'STRING'),
            Column('rpt_utm_medium', 'STRING'),
            Column('rpt_utm_source', 'STRING'),
            Column('rpt_utm_campaign', 'STRING'),
            Column('rpt_utm_content', 'STRING'),
            Column('rpt_utm_term', 'STRING'),
            Column('rpt_device', 'STRING'),
            Column('rpt_browser', 'STRING'),
            Column('operating_system', 'STRING'),
            Column('is_secondary_registration', 'BOOLEAN'),
            Column('is_secondary_registration_after_vip', 'BOOLEAN'),
            Column('has_membership_password', 'BOOLEAN'),
            Column('has_membership_password_first_value', 'BOOLEAN'),
            Column('is_fake_retail_registration', 'BOOLEAN'),
            Column('is_retail_registration', 'BOOLEAN'),
            Column('retail_location', 'NUMBER(38,0)'),
            Column('is_test_customer', 'BOOLEAN'),
            Column('is_deleted', 'BOOLEAN'),
            Column('is_reactivated_lead', 'BOOLEAN'),
        ],
        watermark_tables=[
            'edw_prod.stg.fact_membership_event',
            'edw_prod.stg.dim_membership_event_type',
            'edw_prod.stg.dim_customer',
            'lake_consolidated.ultra_merchant.customer_detail',
            'lake_consolidated.ultra_merchant.customer_link',
            'lake_consolidated.ultra_merchant.session',
            'lake_consolidated.ultra_merchant.session_uri',
            'lake_consolidated.ultra_merchant.session_media_data',
            'lake_consolidated.ultra_merchant.media_code',
            'reporting_base_prod.shared.media_source_channel_mapping',
            'reporting_base_prod.shared.session',
            'edw_prod.reference.fake_retail_leads_with_activations',
        ],
    )
