from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_fact import SnowflakeMartFactOperator
from include.utils.snowflake import ForeignKey


def get_mart_operator():
    return SnowflakeMartFactOperator(
        table="fact_order_line_product_cost",
        use_surrogate_key=False,
        initial_load_value="1900-01-01",
        transform_proc_list=["stg.transform_fact_order_line_product_cost.sql"],
        column_list=[
            Column("order_line_id", "INT", uniqueness=True),
            Column("meta_original_order_line_id", "INT"),
            Column("order_id", "INT", foreign_key=ForeignKey("fact_order")),
            Column("store_id", "INT", foreign_key=ForeignKey("dim_store")),
            Column("brand", "VARCHAR"),
            Column("sku", "VARCHAR"),
            Column("style_color", "VARCHAR"),
            Column("product_category", "VARCHAR"),
            Column("department", "VARCHAR"),
            Column("category", "VARCHAR"),
            Column("subcategory", "VARCHAR"),
            Column("class", "VARCHAR"),
            Column("calculation_type", "VARCHAR"),
            Column("shipped_local_datetime", "TIMESTAMP_TZ(3)"),
            Column("order_completion_local_datetime", "TIMESTAMP_TZ(3)"),
            Column("receipt_po", "VARCHAR"),
            Column("receipt_po_line_number", "NUMBER(38, 0)"),
            Column("receipt_year_month", "DATE"),
            Column("alternate_po", "VARCHAR"),
            Column("alternate_po_line_number", "NUMBER(38, 0)"),
            Column("alternate_year_month", "DATE"),
            Column("receipt_datetime", "TIMESTAMP_NTZ(3)"),
            Column("alternate_receipt_datetime", "TIMESTAMP_NTZ(3)"),
            Column("is_lpn_found", "BOOLEAN"),
            Column("is_po_receipt_found", "BOOLEAN"),
            Column("is_fully_landed", "BOOLEAN"),
            Column("reporting_landed_cost_local_amount", "NUMBER(38, 6)"),
            Column("is_actual_landed_cost", "BOOLEAN"),
            Column("fully_landed_conversion_date", "TIMESTAMP_LTZ(3)"),
            Column("is_deleted", "BOOLEAN"),
            Column("currency_key", "INT"),
            Column("estimated_landed_cost_local_amount", "NUMBER(38, 6)"),
            Column("actual_landed_cost_local_amount", "NUMBER(38, 6)"),
            Column("actual_po_cost_local_amount", "NUMBER(38, 6)"),
            Column("actual_cmt_cost_local_amount", "NUMBER(38, 6)"),
            Column("actual_tariff_duty_cost_local_amount", "NUMBER(38, 6)"),
            Column("actual_freight_cost_local_amount", "NUMBER(38, 6)"),
            Column("actual_other_cost_local_amount", "NUMBER(38, 6)"),
        ],
        watermark_tables=[
            "edw_prod.stg.fact_order_line",
            "edw_prod.stg.dim_product",
            "edw_prod.stg.dim_lpn",
            "lake.ultra_warehouse.receipt",
            "edw_prod.reference.gsc_landed_cost",
            "lake_consolidated.ultra_merchant.order_line_split_map",
            "edw_prod.reference.gfc_po_sku_line_lpn_mapping",
        ],
    )
