from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_fact import SnowflakeMartFactOperator


def get_mart_operator():
    return SnowflakeMartFactOperator(
        table="fact_credit_event",
        use_surrogate_key=True,
        initial_load_value="1900-01-01",
        transform_proc_list=["stg.transform_fact_credit_event.sql"],
        column_list=[
            Column("credit_key", "NUMBER(38,0)"),
            Column("credit_id", "NUMBER(38,0)", uniqueness=True),
            Column("source_credit_id", "NUMBER(38, 0)", uniqueness=True),
            Column("activation_key", "NUMBER(38,0)"),
            Column("first_activation_key", "NUMBER(38,0)"),
            Column("is_bop_vip", "NUMBER(38,0)"),
            Column("customer_id", "NUMBER(38,0)"),
            Column("administrator_id", "NUMBER(38,0)"),
            Column("credit_activity_type", "VARCHAR(60)", uniqueness=True),
            Column("original_credit_activity_type_action", "VARCHAR(60)"),
            Column("credit_activity_type_reason", "VARCHAR(60)"),
            Column(
                "credit_activity_local_datetime", "TIMESTAMP_TZ(3)", uniqueness=True
            ),
            Column("credit_activity_source", "VARCHAR(155)", uniqueness=True),
            Column("credit_activity_source_reason", "VARCHAR(155)"),
            Column("credit_store_id", "NUMBER(38,0)", uniqueness=True),
            Column("redemption_order_id", "NUMBER(38,0)"),
            Column("source_redemption_order_id", "NUMBER(38,0)", uniqueness=True),
            Column("redemption_store_id", "NUMBER(38,0)"),
            Column("vat_rate_ship_to_country", "VARCHAR(50)"),
            Column("credit_activity_vat_rate", "NUMBER(18,6)"),
            Column("credit_activity_usd_conversion_rate", "NUMBER(18,6)"),
            Column("credit_activity_equivalent_count", "NUMBER(38,10)"),
            Column("credit_activity_gross_vat_local_amount", "NUMBER(31,4)"),
            Column("credit_activity_local_amount", "NUMBER(38,10)"),
            Column("activity_amount_local_amount_issuance_date", "NUMBER(38,10)"),
            Column("is_deleted", "BOOLEAN"),
            Column("is_test_customer", "BOOLEAN"),
            Column("credit_issued_hq_datetime", "TIMESTAMP_TZ(9)", uniqueness=True),
            Column("is_current", "BOOLEAN"),
        ],
        watermark_tables=[
            "edw_prod.stg.dim_credit",
            "edw_prod.stg.fact_activation",
            "edw_prod.stg.fact_order",
            "edw_prod.reference.credit_historical_activity",
            "edw_prod.reference.currency_exchange_rate",
            "lake_consolidated.ultra_merchant.membership_token",
            "lake_consolidated.ultra_merchant.membership_token_transaction",
            "lake_consolidated.ultra_merchant.store_credit",
            "lake_consolidated.ultra_merchant.store_credit_transaction",
            "lake_consolidated.ultra_merchant.order_credit",
            "lake_consolidated.ultra_merchant.order_tracking_detail",
            'lake_consolidated.ultra_merchant."ORDER"',
            "lake_consolidated.ultra_merchant.address",
            "lake_consolidated.ultra_merchant.customer",
            "lake_consolidated.ultra_merchant.bounceback_endowment",
            "lake_consolidated.ultra_merchant.gift_certificate",
            "lake_consolidated.ultra_merchant.gift_certificate_transaction",
            "lake_consolidated.ultra_merchant_history.membership",
            "lake_consolidated.ultra_merchant.credit_transfer_transaction",
            "lake_consolidated.ultra_merchant.managed_gift_certificate",
            "lake_consolidated.ultra_merchant.gift_certificate_store_credit",
        ],
    )
