from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_fact import SnowflakeMartFactOperator
from include.utils.snowflake import ForeignKey


def get_mart_operator():
    return SnowflakeMartFactOperator(
        table="fact_return_line",
        initial_load_value="1900-01-01",
        transform_proc_list=["stg.transform_fact_return_line.sql"],
        use_surrogate_key=False,
        column_list=[
            Column("return_line_id", "INT", uniqueness=True),
            Column("rma_product_id", "INT", uniqueness=True),
            Column("meta_original_return_line_id", "INT"),
            Column("meta_original_rma_product_id", "INT"),
            Column("return_id", "INT", foreign_key=ForeignKey("fact_refund")),
            Column("order_line_id", "INT", foreign_key=ForeignKey("fact_order_line")),
            Column("order_id", "INT", foreign_key=ForeignKey("fact_order")),
            Column("customer_id", "INT", foreign_key=ForeignKey("dim_customer")),
            Column("activation_key", "NUMBER(38,0)"),
            Column("first_activation_key", "NUMBER(38,0)"),
            Column("product_id", "INT", foreign_key=ForeignKey("dim_product")),
            Column("store_id", "INT", foreign_key=ForeignKey("dim_store")),
            Column("item_price_key", "INT"),
            Column("rma_id", "INT"),
            Column("administrator_id", "INT"),
            Column("return_category_id", "INT"),
            Column("return_carrier", "VARCHAR(50)"),
            Column("return_source_id", "INT"),
            Column("retail_return_store_id", "INT"),
            Column("warehouse_id", "INT", foreign_key=ForeignKey("dim_warehouse")),
            Column("return_status_key", "INT"),
            Column("return_condition_key", "INT"),
            Column("return_reason_id", "INT"),
            Column("is_exchange", "BOOLEAN"),
            Column("return_item_quantity", "INT"),
            Column("return_product_cost_local_amount", "NUMBER(19,4)"),
            Column("estimated_return_shipping_cost_local_amount", "NUMBER(19,4)"),
            Column("return_restocking_fee_local_amount", "NUMBER(19,4)"),
            Column("return_receipt_date_eur_conversion_rate", "NUMBER(18,6)"),
            Column("return_receipt_date_usd_conversion_rate", "NUMBER(18,6)"),
            Column("return_request_local_datetime", "TIMESTAMP_TZ"),
            Column("return_receipt_local_datetime", "TIMESTAMP_TZ"),
            Column("return_completion_local_datetime", "TIMESTAMP_TZ"),
            Column("rma_resolution_local_datetime", "TIMESTAMP_TZ"),
            Column("rma_transit_local_datetime", "TIMESTAMP_TZ"),
            Column("effective_vat_rate", "NUMBER(18,6)"),
            Column("return_tax_local_amount", "NUMBER(19,4)"),
            Column("return_subtotal_local_amount", "NUMBER(19,4)"),
            Column("return_cash_credit_local_amount", "NUMBER(19,4)"),
            Column("return_discount_local_amount", "NUMBER(19,4)"),
            Column("return_non_cash_credit_local_amount", "NUMBER(19,4)"),
            Column("estimated_returned_product_cost_local_amount", "NUMBER(19,4)"),
            Column("estimated_returned_product_resaleable_pct", "NUMBER(19,4)"),
            Column("return_line_ratio_of_total", "DECIMAL(18,6)"),
            Column("is_test_customer", "BOOLEAN"),
            Column("is_deleted", "BOOLEAN"),
            Column("source_order_line_id", "INT"),
            Column("source_order_id", "INT"),
        ],
        watermark_tables=[
            "edw_prod.stg.dim_customer",
            "edw_prod.stg.fact_activation",
            "edw_prod.stg.fact_order",
            "edw_prod.stg.fact_order_line",
            "lake_consolidated.ultra_merchant.return",
            "lake_consolidated.ultra_merchant.order_line",
            'lake_consolidated.ultra_merchant."ORDER"',
            "lake_consolidated.ultra_merchant.order_line_discount",
            "lake_consolidated.ultra_merchant.order_credit",
            "lake_consolidated.ultra_merchant.return_line",
            "lake_consolidated.ultra_merchant.return_product",
            "lake_consolidated.ultra_merchant.rma_product",
            "lake_consolidated.ultra_merchant.rma_line",
            "lake_consolidated.ultra_merchant.rma",
            "lake.ultra_warehouse.lpn",
            "lake.ultra_warehouse.warehouse",
            "lake_consolidated.ultra_merchant.order_classification",
            "lake_consolidated.ultra_merchant.order_detail",
            "lake_consolidated.ultra_merchant.retail_return",
            "lake_consolidated.ultra_merchant.retail_return_detail",
            "lake_consolidated.ultra_merchant.exchange",
            "lake_consolidated.ultra_merchant.exchange_line",
            "lake_consolidated.ultra_merchant.gift_order",
            "lake_consolidated.ultra_merchant.reship",
            "lake_consolidated.ultra_merchant.order_line_split_map",
            "lake_consolidated.ultra_merchant.statuscode_modification_log",
            "edw_prod.reference.finance_assumption",
        ],
    )
