from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_fact import SnowflakeMartFactOperator
from include.utils.snowflake import ForeignKey


def get_mart_operator():
    return SnowflakeMartFactOperator(
        table='fact_activation',
        use_surrogate_key=True,
        transform_proc_list=['stg.transform_fact_activation.sql'],
        column_list=[
            Column('membership_event_key', 'NUMBER(38,0)'),
            Column('store_id', 'NUMBER(38,0)', foreign_key=ForeignKey('dim_store')),
            Column(
                'customer_id',
                'NUMBER(38,0)',
                uniqueness=True,
                foreign_key=ForeignKey('dim_customer'),
            ),
            Column('meta_original_customer_id', 'NUMBER(38,0)'),
            Column('is_test_customer', 'BOOLEAN'),
            Column('activation_local_datetime', 'TIMESTAMP_TZ(3)', uniqueness=True),
            Column('next_activation_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('source_activation_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('source_next_activation_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('cancellation_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('is_reactivated_vip', 'BOOLEAN'),
            Column('order_id', 'NUMBER(38,0)', foreign_key=ForeignKey('fact_order')),
            Column('session_id', 'NUMBER(38,0)'),
            Column('activation_channel_type', 'VARCHAR(255)'),
            Column('activation_channel', 'VARCHAR(255)'),
            Column('activation_subchannel', 'VARCHAR(255)'),
            Column('vip_cohort_month_date', 'DATE'),
            Column('source_vip_cohort_month_date', 'DATE'),
            Column('membership_event_type', 'VARCHAR(60)'),
            Column('membership_type', 'VARCHAR(255)'),
            Column('is_vip_activation_from_reactivated_lead', 'BOOLEAN'),
            Column('dm_gateway_id', 'NUMBER(38,0)'),
            Column('device', 'STRING'),
            Column('browser', 'STRING'),
            Column('operating_system', 'STRING'),
            Column('utm_medium', 'STRING'),
            Column('utm_source', 'STRING'),
            Column('utm_campaign', 'STRING'),
            Column('utm_content', 'STRING'),
            Column('utm_term', 'STRING'),
            Column('pcode', 'STRING'),
            Column('ccode', 'STRING'),
            Column('acode', 'STRING'),
            Column('scode', 'STRING'),
            # Column('order_detail_retail_store_id', 'NUMBER(38,0)'),
            Column('sub_store_id', 'NUMBER(38,0)'),
            # Column('is_varsity_vip', 'BOOLEAN'),
            Column('is_legging_bar_vip', 'BOOLEAN'),
            Column('is_kiosk_vip', 'BOOLEAN'),
            Column('is_scrubs_vip', 'BOOLEAN'),
            Column('order_discount_percent', 'NUMBER(19,4)'),
            Column('is_current', 'BOOLEAN'),
            Column('is_deleted', 'BOOLEAN'),
            Column('cancel_type', 'VARCHAR (50)'),
            Column('cancel_method', 'VARCHAR'),
            Column('cancel_reason', 'VARCHAR'),
            Column('activation_sequence_number', 'NUMBER(38,0)'),
        ],
        watermark_tables=[
            'edw_prod.stg.fact_membership_event',
            'lake_consolidated.ultra_merchant.session',
            'lake_consolidated.ultra_merchant.session_uri',
            'lake_consolidated.ultra_merchant.store',
            'lake_consolidated.ultra_merchant."ORDER"',
            'lake_consolidated.ultra_merchant.customer_link',
            'lake_consolidated.ultra_merchant.membership',
            'lake_consolidated.ultra_merchant.membership_type',
            'reporting_base_prod.shared.media_source_channel_mapping',
            'reporting_base_prod.shared.session',
            'edw_prod.reference.test_customer',
            'edw_prod.stg.lkp_membership_cancel_method',
        ],
    )
