from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_fact import SnowflakeMartFactOperator
from include.utils.snowflake import ForeignKey


def get_mart_operator():
    return SnowflakeMartFactOperator(
        table="fact_order_line",
        use_surrogate_key=False,
        initial_load_value="1900-01-01",
        transform_proc_list=["stg.transform_fact_order_line.sql"],
        column_list=[
            Column("order_line_id", "INT", uniqueness=True),
            Column("meta_original_order_line_id", "INT"),
            Column("order_id", "INT", foreign_key=ForeignKey("fact_order")),
            Column("store_id", "INT", foreign_key=ForeignKey("dim_store")),
            Column("customer_id", "INT", foreign_key=ForeignKey("dim_customer")),
            Column("product_id", "INT", foreign_key=ForeignKey("dim_product")),
            Column("master_product_id", "INT", foreign_key=ForeignKey("dim_product")),
            Column("bundle_product_id", "INT", foreign_key=ForeignKey("dim_product")),
            Column(
                "bundle_component_product_id",
                "INT",
                foreign_key=ForeignKey("dim_product"),
            ),
            Column("group_code", "VARCHAR(50)"),
            Column("bundle_component_history_key", "INT"),
            Column("product_type_key", "INT"),
            Column("bundle_order_line_id", "INT"),
            Column("order_membership_classification_key", "INT"),
            Column("order_sales_channel_key", "INT"),
            Column("order_line_status_key", "INT"),
            Column("order_status_key", "INT"),
            Column("order_product_source_key", "INT"),
            Column("currency_key", "INT"),
            Column("warehouse_id", "INT", foreign_key=ForeignKey("dim_warehouse")),
            Column("shipping_address_id", "INT", foreign_key=ForeignKey("dim_address")),
            Column("billing_address_id", "INT", foreign_key=ForeignKey("dim_address")),
            Column("is_deleted", "BOOLEAN"),
            Column("cost_source_id", "INT"),
            Column("cost_source", "VARCHAR"),
            Column("order_local_datetime", "TIMESTAMP_TZ(3)"),
            Column("payment_transaction_local_datetime", "TIMESTAMP_TZ(3)"),
            Column("shipped_local_datetime", "TIMESTAMP_TZ(3)"),
            Column("order_completion_local_datetime", "TIMESTAMP_TZ(3)"),
            Column("order_date_usd_conversion_rate", "NUMBER(18,6)"),
            Column("order_date_eur_conversion_rate", "NUMBER(18,6)"),
            Column("payment_transaction_date_usd_conversion_rate", "NUMBER(18,6)"),
            Column("payment_transaction_date_eur_conversion_rate", "NUMBER(18,6)"),
            Column("shipped_date_usd_conversion_rate", "NUMBER(18,6)"),
            Column("shipped_date_eur_conversion_rate", "NUMBER(18,6)"),
            Column("reporting_usd_conversion_rate", "NUMBER(18,6)"),
            Column("reporting_eur_conversion_rate", "NUMBER(18,6)"),
            Column("effective_vat_rate", "NUMBER(18,6)"),
            Column("item_quantity", "INT"),
            Column("payment_transaction_local_amount", "NUMBER(19,4)"),
            Column("subtotal_excl_tariff_local_amount", "NUMBER(19,4)"),
            Column("tax_local_amount", "NUMBER(19,4)"),
            Column("tax_cash_local_amount", "NUMBER(19,4)"),
            Column("tax_credit_local_amount", "NUMBER(19,4)"),
            Column("delivery_fee_local_amount", "NUMBER(19,4)"),
            Column("product_discount_local_amount", "NUMBER(19,4)"),
            Column("shipping_discount_local_amount", "NUMBER(19,4)"),
            Column("shipping_revenue_before_discount_local_amount", "NUMBER(19,4)"),
            Column("shipping_revenue_cash_local_amount", "NUMBER(19,4)"),
            Column("shipping_revenue_credit_local_amount", "NUMBER(19,4)"),
            Column("cash_credit_local_amount", "NUMBER(19,4)"),
            Column("cash_membership_credit_local_amount", "NUMBER(19,4)"),
            Column("cash_refund_credit_local_amount", "NUMBER(19,4)"),
            Column("cash_giftco_credit_local_amount", "NUMBER(19,4)"),
            Column("cash_giftcard_credit_local_amount", "NUMBER(19,4)"),
            Column("token_local_amount", "NUMBER(19,4)"),
            Column("token_count", "NUMBER(19,4)"),
            Column("cash_token_local_amount", "NUMBER(19,4)"),
            Column("cash_token_count", "NUMBER(19,4)"),
            Column("non_cash_token_local_amount", "NUMBER(19,4)"),
            Column("non_cash_token_count", "NUMBER(19,4)"),
            Column("non_cash_credit_local_amount", "NUMBER(19,4)"),
            Column("estimated_landed_cost_local_amount", "NUMBER(19,4)"),
            Column("oracle_cost_local_amount", "NUMBER(19,4)"),
            Column("lpn_po_cost_local_amount", "NUMBER(19,4)"),
            Column("po_cost_local_amount", "NUMBER(19,4)"),
            Column("misc_cogs_local_amount", "NUMBER(19,4)"),
            Column("estimated_shipping_supplies_cost_local_amount", "NUMBER(19,4)"),
            Column("estimated_shipping_cost_local_amount", "NUMBER(19,4)"),
            Column("estimated_variable_gms_cost_local_amount", "NUMBER(19,4)"),
            Column("estimated_variable_warehouse_cost_local_amount", "NUMBER(19,4)"),
            Column(
                "estimated_variable_payment_processing_pct_cash_revenue", "NUMBER(19,4)"
            ),
            Column("tariff_revenue_local_amount", "NUMBER(19,4)"),
            Column("price_offered_local_amount", "NUMBER(19,4)"),
            Column("air_vip_price", "NUMBER(19,4)"),
            Column("retail_unit_price", "NUMBER(19,4)"),
            Column("bundle_price_offered_local_amount", "NUMBER(19,4)"),
            Column("product_price_history_key", "INT"),
            Column("bundle_product_price_history_key", "INT"),
            Column("item_price_key", "INT"),
            Column("administrator_id", "INT"),
            Column("is_test_customer", "BOOLEAN"),
            Column("group_key", "VARCHAR"),
            Column("sub_group_key", "VARCHAR"),
            Column("lpn_code", "VARCHAR(255)"),
            Column("custom_printed_text", "VARCHAR(100)"),
            Column("shipping_cost_local_amount", "NUMBER(19,4)"),
            Column("bounceback_endowment_id", "INT"),
            Column("bounceback_endowment_local_amount", "NUMBER(19,4)"),
            Column("vip_endowment_local_amount", "NUMBER(19,4)"),
        ],
        watermark_tables=[
            "edw_prod.stg.fact_order",
            "edw_prod.stg.dim_item_price",
            "edw_prod.stg.dim_product",
            "edw_prod.stg.dim_product_price_history",
            "edw_prod.stg.dim_related_product",
            "edw_prod.stg.dim_bundle_component_history",
            "lake_consolidated.ultra_merchant.bounceback_endowment",
            'lake_consolidated.ultra_merchant."ORDER"',
            "lake_consolidated.ultra_merchant.order_line",
            "lake_consolidated.ultra_merchant.order_line_discount",
            "lake_consolidated.ultra_merchant.order_line_token",
            "lake_consolidated.ultra_merchant.order_product_source",
            "lake_consolidated.ultra_merchant.product",
            "lake_consolidated.ultra_merchant.product_type",
            "lake.ultra_warehouse.fulfillment",
            "lake.ultra_warehouse.fulfillment_item",
            "lake.ultra_warehouse.invoice",
            "lake.ultra_warehouse.invoice_item",
            "lake.oracle_ebs.landed_cost",
            "lake_consolidated.ultra_merchant.order_tax",
            "edw_prod.reference.po_sku_cost",
            "edw_prod.reference.gfc_po_sku_line_lpn_mapping",
            "edw_prod.reference.miracle_miles_landed_cost",
            "lake.centric.ed_sku",
            "lake.centric.ed_style",
            "lake.centric.ed_colorway",
            "lake_consolidated.ultra_merchant.order_line_split_map",
        ],
    )
