from include.airflow.operators.snowflake_mart_base import Column
from include.airflow.operators.snowflake_mart_fact import SnowflakeMartFactOperator
from include.utils.snowflake import ForeignKey


def get_mart_operator():
    return SnowflakeMartFactOperator(
        table='fact_order',
        initial_load_value='1900-01-01',
        transform_proc_list=['stg.transform_fact_order.sql'],
        use_surrogate_key=False,
        column_list=[
            Column('order_id', 'NUMBER(38,0)', uniqueness=True),
            Column('meta_original_order_id', 'NUMBER(38,0)'),
            Column('membership_event_key', 'NUMBER(38,0)'),
            Column('activation_key', 'NUMBER(38,0)'),
            Column('first_activation_key', 'NUMBER(38,0)'),
            Column('currency_key', 'NUMBER(38,0)'),
            Column('customer_id', 'NUMBER(38,0)', foreign_key=ForeignKey('dim_customer')),
            Column('store_id', 'NUMBER(38,0)', foreign_key=ForeignKey('dim_store')),
            Column('cart_store_id', 'NUMBER(38,0)'),
            Column('membership_brand_id', 'NUMBER(38,0)'),
            Column('master_order_id', 'NUMBER(38,0)'),
            Column('order_payment_status_key', 'NUMBER(38,0)'),
            Column('order_processing_status_key', 'NUMBER(38,0)'),
            Column('order_membership_classification_key', 'NUMBER(38,0)'),
            Column('is_cash', 'BOOLEAN'),
            Column('is_credit_billing_on_retry', 'BOOLEAN'),
            Column('shipping_address_id', 'NUMBER(38,0)', foreign_key=ForeignKey('dim_address')),
            Column('billing_address_id', 'NUMBER(38,0)', foreign_key=ForeignKey('dim_address')),
            Column('order_status_key', 'NUMBER(38,0)'),
            Column('order_sales_channel_key', 'NUMBER(38,0)'),
            Column('payment_key', 'NUMBER(38,0)'),
            Column('session_id', 'NUMBER(38,0)'),
            Column('order_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('payment_transaction_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('shipped_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('order_completion_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('unit_count', 'NUMBER(38,0)'),
            Column('loyalty_unit_count', 'NUMBER(38,0)'),
            Column('third_party_unit_count', 'NUMBER(38,0)'),
            Column('order_date_usd_conversion_rate', 'NUMBER(18,6)'),
            Column('order_date_eur_conversion_rate', 'NUMBER(18,6)'),
            Column('payment_transaction_date_usd_conversion_rate', 'NUMBER(18,6)'),
            Column('payment_transaction_date_eur_conversion_rate', 'NUMBER(18,6)'),
            Column('shipped_date_usd_conversion_rate', 'NUMBER(18,6)'),
            Column('shipped_date_eur_conversion_rate', 'NUMBER(18,6)'),
            Column('reporting_usd_conversion_rate', 'NUMBER(18,6)'),
            Column('reporting_eur_conversion_rate', 'NUMBER(18,6)'),
            Column('payment_transaction_local_amount', 'NUMBER(19,4)'),
            Column('subtotal_excl_tariff_local_amount', 'NUMBER(19,4)'),
            Column('effective_vat_rate', 'NUMBER(18,6)'),
            Column('tax_local_amount', 'NUMBER(19,4)'),
            Column('tax_cash_local_amount', 'NUMBER(19,4)'),
            Column('tax_credit_local_amount', 'NUMBER(19,4)'),
            Column('cash_credit_local_amount', 'NUMBER(19,4)'),
            Column('cash_credit_count', 'NUMBER(38,0)'),
            Column('cash_membership_credit_local_amount', 'NUMBER(19,4)'),
            Column('cash_membership_credit_count', 'NUMBER(38,0)'),
            Column('cash_refund_credit_local_amount', 'NUMBER(19,4)'),
            Column('cash_refund_credit_count', 'NUMBER(38,0)'),
            Column('cash_giftco_credit_local_amount', 'NUMBER(19,4)'),
            Column('cash_giftco_credit_count', 'NUMBER(38,0)'),
            Column('cash_giftcard_credit_local_amount', 'NUMBER(19,4)'),
            Column('cash_giftcard_credit_count', 'NUMBER(38,0)'),
            Column('token_local_amount', 'NUMBER(19,4)'),
            Column('token_count', 'NUMBER(38,0)'),
            Column('cash_token_local_amount', 'NUMBER(19,4)'),
            Column('cash_token_count', 'NUMBER(38,0)'),
            Column('non_cash_token_local_amount', 'NUMBER(19,4)'),
            Column('non_cash_token_count', 'NUMBER(38,0)'),
            Column('non_cash_credit_local_amount', 'NUMBER(19,4)'),
            Column('non_cash_credit_count', 'NUMBER(38,0)'),
            Column('shipping_revenue_before_discount_local_amount', 'NUMBER(19,4)'),
            Column('shipping_revenue_cash_local_amount', 'NUMBER(19,4)'),
            Column('shipping_revenue_credit_local_amount', 'NUMBER(19,4)'),
            Column('shipping_cost_local_amount', 'NUMBER(19,4)'),
            Column('product_discount_local_amount', 'NUMBER(19,4)'),
            Column('shipping_discount_local_amount', 'NUMBER(19,4)'),
            Column('tariff_revenue_local_amount', 'NUMBER(19,4)'),
            Column('delivery_fee_local_amount', 'NUMBER(19,4)'),
            Column('estimated_variable_gms_cost_local_amount', 'NUMBER(19,4)'),
            Column('estimated_variable_warehouse_cost_local_amount', 'NUMBER(19,4)'),
            Column('estimated_variable_payment_processing_pct_cash_revenue', 'NUMBER(19,4)'),
            Column('estimated_shipping_cost_local_amount', 'NUMBER(19,4)'),
            Column('estimated_shipping_supplies_cost_local_amount', 'NUMBER(19,4)'),
            Column('is_deleted', 'BOOLEAN'),
            Column('estimated_landed_cost_local_amount', 'NUMBER(19,4)'),
            Column('reporting_landed_cost_local_amount', 'NUMBER(38, 6)'),
            Column('is_actual_landed_cost', 'BOOLEAN'),
            Column('misc_cogs_local_amount', 'NUMBER(19,4)'),
            Column('administrator_id', 'INT'),
            Column('is_test_customer', 'BOOLEAN'),
            Column('bops_store_id', 'INT'),
            Column('bops_pickup_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('order_customer_selected_shipping_key', 'NUMBER(38,0)'),
            Column('order_placed_local_datetime', 'TIMESTAMP_TZ(3)'),
            Column('bounceback_endowment_local_amount', 'NUMBER(19,4)'),
            Column('vip_endowment_local_amount', 'NUMBER(19,4)'),
        ],
        watermark_tables=[
            'lake_consolidated.ultra_merchant."ORDER"',
            'edw_prod.stg.dim_customer',
            'edw_prod.stg.fact_membership_event',
            'edw_prod.stg.fact_activation',
            'lake_consolidated.ultra_merchant.order_line',
            'lake_consolidated.ultra_merchant.order_classification',
            'lake_consolidated.ultra_merchant.order_cancel',
            'lake_consolidated.ultra_merchant.order_credit',
            'lake_consolidated.ultra_merchant.credit_transfer_transaction',
            'lake_consolidated.ultra_merchant.gift_certificate',
            'lake_consolidated.ultra_merchant.gift_certificate_store_credit',
            'lake_consolidated.ultra_merchant.store_credit',
            'lake_consolidated.ultra_merchant.store_credit_reason',
            'lake_consolidated.ultra_merchant.membership_plan_membership_brand',
            'lake_consolidated.ultra_merchant.membership_token',
            'lake_consolidated.ultra_merchant.membership_token_reason',
            'lake_consolidated.ultra_merchant.order_discount',
            'lake_consolidated.ultra_merchant.order_surcharge',
            'lake_consolidated.ultra_merchant.payment_transaction_creditcard',
            'lake_consolidated.ultra_merchant.payment_transaction_psp',
            'lake_consolidated.ultra_merchant.payment_transaction_cash',
            'lake_consolidated.ultra_merchant.billing_retry_schedule_queue',
            'lake_consolidated.ultra_merchant.box',
            'lake_consolidated.ultra_merchant.box_completion',
            'lake_consolidated.ultra_merchant.order_shipment',
            'lake_consolidated.ultra_merchant.carrier_uw',
            'lake_consolidated.ultra_merchant.creditcard',
            'lake_consolidated.ultra_merchant.payment_transaction_creditcard_data',
            'lake_consolidated.ultra_merchant.psp',
            'lake_consolidated.ultra_merchant.product_type',
            'lake_consolidated.ultra_merchant.address',
            'lake_consolidated.ultra_merchant.order_tracking_detail',
            'edw_prod.stg.lkp_order_classification',
            'lake_consolidated.ultra_merchant.exchange',
            'lake_consolidated.ultra_merchant.order_detail',
            'lake_consolidated.ultra_merchant.order_shipping',
            'lake_consolidated.ultra_merchant.order_tax',
            'lake_consolidated.ultra_merchant.address',
            'lake_consolidated.ultra_merchant.gift_order',
            'lake_consolidated.ultra_merchant.reship',
            'edw_prod.reference.test_customer',
            'edw_prod.reference.finance_assumption',
            'lake_consolidated.ultra_merchant.bounceback_endowment',
        ],
    )
