CREATE OR REPLACE VIEW lake_view.amazon_ads.campaign_level_report
AS
SELECT campaign_id,
       DATE,
       impressions,
       clicks,
       cost,
       cost_per_click,
       campaign_bidding_strategy,
       click_through_rate,
       spend,
       purchases_1_d,
       purchases_7_d,
       purchases_14_d,
       purchases_30_d,
       purchases_same_sku_1_d,
       purchases_same_sku_7_d,
       purchases_same_sku_14_d,
       purchases_same_sku_30_d,
       units_sold_clicks_1_d,
       units_sold_clicks_7_d,
       units_sold_clicks_14_d,
       units_sold_clicks_30_d,
       sales_1_d,
       sales_7_d,
       sales_14_d,
       sales_30_d,
       attributed_sales_same_sku_1_d,
       attributed_sales_same_sku_7_d,
       attributed_sales_same_sku_14_d,
       attributed_sales_same_sku_30_d,
       units_sold_same_sku_1_d,
       units_sold_same_sku_7_d,
       units_sold_same_sku_14_d,
       units_sold_same_sku_30_d,
       kindle_edition_normalized_pages_read_14_d,
       kindle_edition_normalized_pages_royalties_14_d,
       campaign_budget_amount,
       campaign_budget_type,
       campaign_rule_based_budget_amount,
       campaign_applicable_budget_rule_id,
       campaign_applicable_budget_rule_name,
       campaign_budget_currency_code,
       Convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
FROM lake_fivetran.central_amazon_ads_v1.campaign_level_report;
