SET target_table = 'analytics_base.customer_lifetime_value_ltd';
SET execution_start_time = CURRENT_TIMESTAMP::TIMESTAMP_LTZ(3);
SET is_full_refresh = TRUE; /* Because this transformation uses aggregation across large groups of data, a full refresh is performed every time */
ALTER SESSION SET QUERY_TAG = $target_table;

SET initial_warehouse = CURRENT_WAREHOUSE();
USE WAREHOUSE IDENTIFIER ('da_wh_adhoc_large'); /* Always use Large Warehouse for this transform */

-- SELECT CURRENT_WAREHOUSE();
-- USE WAREHOUSE IDENTIFIER ('da_wh_adhoc_large'); -- Large Warehouse
-- USE WAREHOUSE IDENTIFIER ('da_wh_edw'); -- Normal Warehouse used by System (Low Concurrent Usage)
-- USE WAREHOUSE IDENTIFIER ('da_wh_etl'); -- Normal Warehouse used by System (High Concurrent Usage)
-- USE WAREHOUSE IDENTIFIER ('da_wh_analytics'); -- Normal Warehouse used by Individuals

CREATE OR REPLACE TEMP TABLE _customer_lifetime_value_ltd__ltv AS
SELECT
    c.customer_id,
    c.meta_original_customer_id,
    c.store_id,
    c.vip_store_id,
    c.vip_cohort_month_date,
    c.guest_cohort_month_date,
    c.activation_key,
    c.first_activation_key,
    c.is_reactivated_vip,
    c.membership_type,
    c.gender,
    c.is_scrubs_customer,
    SUM(c.product_order_count)                                           AS product_order_count,
    SUM(c.online_product_order_count)                                    AS online_product_order_count,
    SUM(c.retail_product_order_count)                                    AS retail_product_order_count,
    SUM(c.mobile_app_product_order_count)                                AS mobile_app_product_order_count,
    SUM(c.product_order_unit_count)                                      AS product_order_unit_count,
    SUM(c.online_product_order_unit_count)                               AS online_product_order_unit_count,
    SUM(c.retail_product_order_unit_count)                               AS retail_product_order_unit_count,
    SUM(c.mobile_app_product_order_unit_count)                           AS mobile_app_product_order_unit_count,
    SUM(c.product_order_subtotal_excl_tariff_amount)                     AS product_order_subtotal_excl_tariff_amount,
    SUM(c.online_product_order_subtotal_excl_tariff_amount)              AS online_product_order_subtotal_excl_tariff_amount,
    SUM(c.retail_product_order_subtotal_excl_tariff_amount)              AS retail_product_order_subtotal_excl_tariff_amount,
    SUM(c.mobile_app_product_order_subtotal_excl_tariff_amount)          AS mobile_app_product_order_subtotal_excl_tariff_amount,
    SUM(c.product_order_product_discount_amount)                         AS product_order_product_discount_amount,
    SUM(c.online_product_order_product_discount_amount)                  AS online_product_order_product_discount_amount,
    SUM(c.retail_product_order_product_discount_amount)                  AS retail_product_order_product_discount_amount,
    SUM(c.mobile_app_product_order_product_discount_amount)              AS mobile_app_product_order_product_discount_amount,
    SUM(c.product_order_shipping_revenue_amount)                         AS product_order_shipping_revenue_amount,
    SUM(c.online_product_order_shipping_revenue_amount)                  AS online_product_order_shipping_revenue_amount,
    SUM(c.retail_product_order_shipping_revenue_amount)                  AS retail_product_order_shipping_revenue_amount,
    SUM(c.mobile_app_product_order_shipping_revenue_amount)              AS mobile_app_product_order_shipping_revenue_amount,
    SUM(c.product_order_direct_cogs_amount)                              AS product_order_direct_cogs_amount,
    SUM(c.online_product_order_direct_cogs_amount)                       AS online_product_order_direct_cogs_amount,
    SUM(c.retail_product_order_direct_cogs_amount)                       AS retail_product_order_direct_cogs_amount,
    SUM(c.mobile_app_product_order_direct_cogs_amount)                   AS mobile_app_product_order_direct_cogs_amount,
    SUM(c.product_order_selling_expenses_amount)                         AS product_order_selling_expenses_amount,
    SUM(c.online_product_order_selling_expenses_amount)                  AS online_product_order_selling_expenses_amount,
    SUM(c.retail_product_order_selling_expenses_amount)                  AS retail_product_order_selling_expenses_amount,
    SUM(c.mobile_app_product_order_selling_expenses_amount)              AS mobile_app_product_order_selling_expenses_amount,
    SUM(c.product_order_cash_refund_amount_and_chargeback_amount)        AS product_order_cash_refund_amount_and_chargeback_amount,
    SUM(c.online_product_order_cash_refund_chargeback_amount)            AS online_product_order_cash_refund_chargeback_amount,
    SUM(c.retail_product_order_cash_refund_chargeback_amount)            AS retail_product_order_cash_refund_chargeback_amount,
    SUM(c.mobile_app_product_order_cash_refund_chargeback_amount)        AS mobile_app_product_order_cash_refund_chargeback_amount,
    SUM(c.product_order_cash_credit_refund_amount)                       AS product_order_cash_credit_refund_amount,
    SUM(c.online_product_order_cash_credit_refund_amount)                AS online_product_order_cash_credit_refund_amount,
    SUM(c.retail_product_order_cash_credit_refund_amount)                AS retail_product_order_cash_credit_refund_amount,
    SUM(c.mobile_app_product_order_cash_credit_refund_amount)            AS mobile_app_product_order_cash_credit_refund_amount,
    SUM(c.product_order_reship_exchange_order_count)                     AS product_order_reship_exchange_order_count,
    SUM(c.online_product_order_reship_exchange_order_count)              AS online_product_order_reship_exchange_order_count,
    SUM(c.retail_product_order_reship_exchange_order_count)              AS retail_product_order_reship_exchange_order_count,
    SUM(c.mobile_app_product_order_reship_exchange_order_count)          AS mobile_app_product_order_reship_exchange_order_count,
    SUM(c.product_order_reship_exchange_unit_count)                      AS product_order_reship_exchange_unit_count,
    SUM(c.online_product_order_reship_exchange_unit_count)               AS online_product_order_reship_exchange_unit_count,
    SUM(c.retail_product_order_reship_exchange_unit_count)               AS retail_product_order_reship_exchange_unit_count,
    SUM(c.mobile_app_product_order_reship_exchange_unit_count)           AS mobile_app_product_order_reship_exchange_unit_count,
    SUM(c.product_order_reship_exchange_direct_cogs_amount)              AS product_order_reship_exchange_direct_cogs_amount,
    SUM(c.online_product_order_reship_exchange_direct_cogs_amount)       AS online_product_order_reship_exchange_direct_cogs_amount,
    SUM(c.retail_product_order_reship_exchange_direct_cogs_amount)       AS retail_product_order_reship_exchange_direct_cogs_amount,
    SUM(c.mobile_app_product_order_reship_exchange_direct_cogs_amount)   AS mobile_app_product_order_reship_exchange_direct_cogs_amount,
    SUM(c.product_order_return_cogs_amount)                              AS product_order_return_cogs_amount,
    SUM(c.online_product_order_return_cogs_amount)                       AS online_product_order_return_cogs_amount,
    SUM(c.retail_product_order_return_cogs_amount)                       AS retail_product_order_return_cogs_amount,
    SUM(c.mobile_app_product_order_return_cogs_amount)                   AS mobile_app_product_order_return_cogs_amount,
    SUM(c.product_order_return_unit_count)                               AS product_order_return_unit_count,
    SUM(c.online_product_order_return_unit_count)                        AS online_product_order_return_unit_count,
    SUM(c.retail_product_order_return_unit_count)                        AS retail_product_order_return_unit_count,
    SUM(c.mobile_app_product_order_return_unit_count)                    AS mobile_app_product_order_return_unit_count,
    SUM(c.product_order_amount_to_pay)                                   AS product_order_amount_to_pay,
    SUM(c.online_product_order_amount_to_pay)                            AS online_product_order_amount_to_pay,
    SUM(c.retail_product_order_amount_to_pay)                            AS retail_product_order_amount_to_pay,
    SUM(c.mobile_app_product_order_amount_to_pay)                        AS mobile_app_product_order_amount_to_pay,
    SUM(c.product_gross_revenue_excl_shipping)                           AS product_gross_revenue_excl_shipping,
    SUM(c.online_product_gross_revenue_excl_shipping)                    AS online_product_gross_revenue_excl_shipping,
    SUM(c.retail_product_gross_revenue_excl_shipping)                    AS retail_product_gross_revenue_excl_shipping,
    SUM(c.mobile_app_product_gross_revenue_excl_shipping)                AS mobile_app_product_gross_revenue_excl_shipping,
    SUM(c.product_gross_revenue)                                         AS product_gross_revenue,
    SUM(c.online_product_gross_revenue)                                  AS online_product_gross_revenue,
    SUM(c.retail_product_gross_revenue)                                  AS retail_product_gross_revenue,
    SUM(c.mobile_app_product_gross_revenue)                              AS mobile_app_product_gross_revenue,
    SUM(c.product_net_revenue)                                           AS product_net_revenue,
    SUM(c.online_product_net_revenue)                                    AS online_product_net_revenue,
    SUM(c.retail_product_net_revenue)                                    AS retail_product_net_revenue,
    SUM(c.mobile_app_product_net_revenue)                                AS mobile_app_product_net_revenue,
    SUM(c.product_margin_pre_return)                                     AS product_margin_pre_return,
    SUM(c.online_product_margin_pre_return)                              AS online_product_margin_pre_return,
    SUM(c.retail_product_margin_pre_return)                              AS retail_product_margin_pre_return,
    SUM(c.mobile_app_product_margin_pre_return)                          AS mobile_app_product_margin_pre_return,
    SUM(c.product_margin_pre_return_excl_shipping)                       AS product_margin_pre_return_excl_shipping,
    SUM(c.online_product_margin_pre_return_excl_shipping)                AS online_product_margin_pre_return_excl_shipping,
    SUM(c.retail_product_margin_pre_return_excl_shipping)                AS retail_product_margin_pre_return_excl_shipping,
    SUM(c.mobile_app_product_margin_pre_return_excl_shipping)            AS mobile_app_product_margin_pre_return_excl_shipping,
    SUM(c.product_gross_profit)                                          AS product_gross_profit,
    SUM(c.online_product_gross_profit)                                   AS online_product_gross_profit,
    SUM(c.retail_product_gross_profit)                                   AS retail_product_gross_profit,
    SUM(c.mobile_app_product_gross_profit)                               AS mobile_app_product_gross_profit,
    SUM(c.product_variable_contribution_profit)                          AS product_variable_contribution_profit,
    SUM(c.online_product_variable_contribution_profit)                   AS online_product_variable_contribution_profit,
    SUM(c.retail_product_variable_contribution_profit)                   AS retail_product_variable_contribution_profit,
    SUM(c.mobile_app_product_variable_contribution_profit)               AS mobile_app_product_variable_contribution_profit,
    SUM(c.product_order_cash_gross_revenue_amount)                       AS product_order_cash_gross_revenue_amount,
    SUM(c.online_product_order_cash_gross_revenue_amount)                AS online_product_order_cash_gross_revenue_amount,
    SUM(c.retail_product_order_cash_gross_revenue_amount)                AS retail_product_order_cash_gross_revenue_amount,
    SUM(c.mobile_app_product_order_cash_gross_revenue_amount)            AS mobile_app_product_order_cash_gross_revenue_amount,
    SUM(c.product_order_cash_net_revenue)                                AS product_order_cash_net_revenue,
    SUM(c.online_product_order_cash_net_revenue)                         AS online_product_order_cash_net_revenue,
    SUM(c.retail_product_order_cash_net_revenue)                         AS retail_product_order_cash_net_revenue,
    SUM(c.mobile_app_product_order_cash_net_revenue)                     AS mobile_app_product_order_cash_net_revenue,
    SUM(c.billing_cash_gross_revenue)                                    AS billing_cash_gross_revenue,
    SUM(c.billing_cash_net_revenue)                                      AS billing_cash_net_revenue,
    SUM(c.cash_gross_revenue)                                            AS cash_gross_revenue,
    SUM(c.cash_net_revenue)                                              AS cash_net_revenue,
    SUM(c.cash_gross_profit)                                             AS cash_gross_profit,
    SUM(c.cash_variable_contribution_profit)                             AS cash_variable_contribution_profit,
    SUM(c.monthly_billed_credit_cash_transaction_amount)                 AS monthly_billed_credit_cash_transaction_amount,
    SUM(c.membership_fee_cash_transaction_amount)                        AS membership_fee_cash_transaction_amount,
    SUM(c.gift_card_transaction_amount)                                  AS gift_card_transaction_amount,
    SUM(c.legacy_credit_cash_transaction_amount)                         AS legacy_credit_cash_transaction_amount,
    SUM(c.monthly_billed_credit_cash_refund_chargeback_amount)           AS monthly_billed_credit_cash_refund_chargeback_amount,
    SUM(c.membership_fee_cash_refund_chargeback_amount)                  AS membership_fee_cash_refund_chargeback_amount,
    SUM(c.gift_card_cash_refund_chargeback_amount)                       AS gift_card_cash_refund_chargeback_amount,
    SUM(c.legacy_credit_cash_refund_chargeback_amount)                   AS legacy_credit_cash_refund_chargeback_amount,
    SUM(c.billed_cash_credit_issued_amount)                              AS billed_cash_credit_issued_amount,
    SUM(c.billed_cash_credit_redeemed_amount)                            AS billed_cash_credit_redeemed_amount,
    SUM(c.online_billed_cash_credit_redeemed_amount)                     AS online_billed_cash_credit_redeemed_amount,
    SUM(c.retail_billed_cash_credit_redeemed_amount)                     AS retail_billed_cash_credit_redeemed_amount,
    SUM(c.mobile_billed_cash_credit_redeemed_amount)                     AS mobile_billed_cash_credit_redeemed_amount,
    SUM(c.billed_cash_credit_cancelled_amount)                           AS billed_cash_credit_cancelled_amount,
    SUM(c.billed_cash_credit_expired_amount)                             AS billed_cash_credit_expired_amount,
    SUM(c.billed_cash_credit_issued_equivalent_count)                    AS billed_cash_credit_issued_equivalent_count,
    SUM(c.billed_cash_credit_redeemed_same_month_amount)                 AS billed_cash_credit_redeemed_same_month_amount,
    SUM(c.billed_cash_credit_redeemed_equivalent_count)                  AS billed_cash_credit_redeemed_equivalent_count,
    SUM(c.billed_cash_credit_cancelled_equivalent_count)                 AS billed_cash_credit_cancelled_equivalent_count,
    SUM(c.billed_cash_credit_expired_equivalent_count)                   AS billed_cash_credit_expired_equivalent_count,
    SUM(c.refund_cash_credit_issued_amount)                              AS refund_cash_credit_issued_amount,
    SUM(c.refund_cash_credit_redeemed_amount)                            AS refund_cash_credit_redeemed_amount,
    SUM(c.refund_cash_credit_cancelled_amount)                           AS refund_cash_credit_cancelled_amount,
    SUM(c.refund_cash_credit_expired_amount)                             AS refund_cash_credit_expired_amount,
    SUM(c.other_cash_credit_issued_amount)                               AS other_cash_credit_issued_amount,
    SUM(c.other_cash_credit_redeemed_amount)                             AS other_cash_credit_redeemed_amount,
    SUM(c.other_cash_credit_cancelled_amount)                            AS other_cash_credit_cancelled_amount,
    SUM(c.other_cash_credit_expired_amount)                              AS other_cash_credit_expired_amount,
    SUM(c.noncash_credit_issued_amount)                                  AS noncash_credit_issued_amount,
    SUM(c.noncash_credit_cancelled_amount)                               AS noncash_credit_cancelled_amount,
    SUM(c.noncash_credit_expired_amount)                                 AS noncash_credit_expired_amount,
    SUM(c.first_guest_product_margin_pre_return)                         AS first_guest_product_margin_pre_return,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 3 THEN c.cumulative_cash_gross_profit ELSE 0 END) AS m3_cumulative_cash_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 3 THEN c.cumulative_product_gross_profit ELSE 0 END) AS m3_cumulative_product_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 6 THEN c.cumulative_cash_gross_profit ELSE 0 END) AS m6_cumulative_cash_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 6 THEN c.cumulative_product_gross_profit ELSE 0 END) AS m6_cumulative_product_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 9 THEN c.cumulative_cash_gross_profit ELSE 0 END) AS m9_cumulative_cash_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 9 THEN c.cumulative_product_gross_profit ELSE 0 END) AS m9_cumulative_product_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 12 THEN c.cumulative_cash_gross_profit ELSE 0 END) AS m12_cumulative_cash_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 12 THEN c.cumulative_product_gross_profit ELSE 0 END) AS m12_cumulative_product_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 18 THEN c.cumulative_cash_gross_profit ELSE 0 END) AS m18_cumulative_cash_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 18 THEN c.cumulative_product_gross_profit ELSE 0 END) AS m18_cumulative_product_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 24 THEN c.cumulative_cash_gross_profit ELSE 0 END) AS m24_cumulative_cash_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 24 THEN c.cumulative_product_gross_profit ELSE 0 END) AS m24_cumulative_product_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 36 THEN c.cumulative_cash_gross_profit ELSE 0 END) AS m36_cumulative_cash_gross_profit,
    SUM(CASE WHEN DATEDIFF(MONTH, c.vip_cohort_month_date, c.month_date) + 1 = 36 THEN c.cumulative_product_gross_profit ELSE 0 END) AS m36_cumulative_product_gross_profit
FROM analytics_base.customer_lifetime_value_monthly AS c
GROUP BY
    c.customer_id,
    c.meta_original_customer_id,
    c.store_id,
    c.vip_store_id,
    c.vip_cohort_month_date,
    c.guest_cohort_month_date,
    c.activation_key,
    c.first_activation_key,
    c.is_reactivated_vip,
    c.membership_type,
    c.gender,
    c.is_scrubs_customer;
-- SELECT * FROM _customer_lifetime_value_ltd__ltv;

CREATE OR REPLACE TEMP TABLE _customer_lifetime_value_ltd__activating AS
SELECT fso.customer_id,
       fso.activation_key,
       SUM(fso.product_order_subtotal_excl_tariff_amount)                       AS activating_product_order_subtotal_excl_tariff_amount,
       SUM(fso.product_order_tariff_amount)                                     AS activating_product_order_tariff_amount,
       SUM(fso.product_order_product_subtotal_amount)                           AS activating_product_order_product_subtotal_amount,
       SUM(fso.product_order_product_discount_amount)                           AS activating_product_order_product_discount_amount,
       SUM(fso.product_order_shipping_discount_amount)                          AS activating_product_order_shipping_discount_amount,
       SUM(fso.product_order_shipping_revenue_before_discount_amount)           AS activating_product_order_shipping_revenue_before_discount_amount,
       SUM(fso.product_order_shipping_revenue_amount)                           AS activating_product_order_shipping_revenue_amount,
       SUM(fso.product_order_tax_amount)                                        AS activating_product_order_tax_amount,
       SUM(fso.product_order_cash_transaction_amount)                           AS activating_product_order_cash_transaction_amount,
       SUM(fso.product_order_count)                                             AS activating_product_order_count,
       SUM(IFF(LOWER(store_type) = 'online', fso.product_order_count, 0))       AS online_activating_product_order_count,
       SUM(IFF(LOWER(store_type) = 'retail', fso.product_order_count, 0))       AS retail_activating_product_order_count,
       SUM(IFF(LOWER(store_type) = 'mobile app', fso.product_order_count, 0))   AS mobile_app_activating_product_order_count,
       SUM(fso.product_order_unit_count)                                        AS activating_product_order_unit_count,
       SUM(fso.product_order_outfit_component_unit_count)                       AS activating_product_order_outfit_component_unit_count,
       SUM(fso.product_order_outfit_count)                                      AS activating_product_order_outfit_count,
       SUM(fso.product_order_discounted_unit_count)                             AS activating_product_order_discounted_unit_count,
       SUM(fso.product_order_zero_revenue_unit_count)                           AS activating_product_order_zero_revenue_unit_count,
       SUM(fso.product_order_landed_product_cost_amount)                        AS activating_product_order_landed_product_cost_amount,
       SUM(fso.product_order_shipping_cost_amount)                              AS activating_product_order_shipping_cost_amount,
       SUM(fso.product_order_shipping_supplies_cost_amount)                     AS activating_product_order_shipping_supplies_cost_amount,
       SUM(fso.product_order_misc_cogs_amount)                                  AS activating_product_order_misc_cogs_amount,
       SUM(fso.product_order_direct_cogs_amount)                                AS activating_product_order_direct_cogs_amount,
       SUM(fso.product_order_payment_processing_cost_amount)                    AS activating_product_order_payment_processing_cost_amount,
       SUM(fso.product_order_variable_gms_cost_amount)                          AS activating_product_order_variable_gms_cost_amount,
       SUM(fso.product_order_variable_warehouse_cost_amount)                    AS activating_product_order_variable_warehouse_cost_amount,
       SUM(fso.product_order_amount_to_pay)                                     AS activating_product_order_amount_to_pay,
       SUM(fso.product_gross_revenue_excl_shipping)                             AS activating_product_gross_revenue_excl_shipping,
       SUM(fso.product_gross_revenue)                                           AS activating_product_gross_revenue,
       SUM(IFF(LOWER(store_type) = 'online', fso.product_gross_revenue, 0))     AS online_activating_product_gross_revenue,
       SUM(IFF(LOWER(store_type) = 'retail', fso.product_gross_revenue, 0))     AS retail_activating_product_gross_revenue,
       SUM(IFF(LOWER(store_type) = 'mobile app', fso.product_gross_revenue, 0)) AS mobile_app_activating_product_gross_revenue,
       SUM(fso.product_margin_pre_return)                                       AS activating_product_margin_pre_return,
       SUM(fso.product_margin_pre_return_excl_shipping)                         AS activating_product_margin_pre_return_excl_shipping
FROM analytics_base.finance_sales_ops AS fso
         JOIN data_model.dim_order_membership_classification AS domc
              ON domc.order_membership_classification_key = fso.order_membership_classification_key
                  AND domc.membership_order_type_l3 = 'Activating VIP'
         JOIN data_model.dim_store ds
              ON ds.store_id = fso.store_id
WHERE fso.date_object = 'placed'
  AND fso.currency_object = 'usd'
  AND fso.date < CURRENT_DATE
GROUP BY fso.customer_id,
         fso.activation_key;
-- SELECT * FROM _customer_lifetime_value_ltd__activating;

SET max_month_date = (SELECT MAX(month_date) FROM analytics_base.customer_lifetime_value_monthly_cust);

CREATE OR REPLACE TEMP TABLE _customer_lifetime_value_ltd__decile AS
SELECT DISTINCT
    mc.customer_id,
    mc.activation_key,
    mc.cumulative_cash_gross_profit_decile,
    mc.cumulative_product_gross_profit_decile
FROM analytics_base.customer_lifetime_value_monthly_cust AS mc
WHERE mc.month_date = $max_month_date
    AND mc.activation_key != -1;
-- SELECT * FROM _customer_lifetime_value_ltd__decile;

CREATE OR REPLACE TEMP TABLE _customer_lifetime_value_ltd__cross_promo AS
SELECT customer_id
FROM data_model.dim_customer
WHERE is_cross_promo;
-- SELECT * FROM _customer_lifetime_value_ltd__cross_promo;

CREATE OR REPLACE TEMP TABLE _customer_lifetime_value_ltd__media_spend_denominator AS
SELECT
    m.store_id,
    m.vip_cohort_month_date,
    IFF(m.gender = 'M', TRUE, FALSE)::BOOLEAN AS is_mens_flag,
    COUNT(1) AS media_spend_denom
FROM analytics_base.customer_lifetime_value_monthly_cust AS m
    LEFT JOIN _customer_lifetime_value_ltd__cross_promo AS c
        ON c.customer_id = m.customer_id
WHERE m.activation_key != -1
    AND m.vip_cohort_month_date = m.month_date
    AND c.customer_id IS NULL
GROUP BY
    m.store_id,
    m.vip_cohort_month_date,
    IFF(m.gender = 'M', TRUE, FALSE)::BOOLEAN;
-- SELECT * FROM _customer_lifetime_value_ltd__media_spend_denominator;

CREATE OR REPLACE TEMP TABLE _customer_lifetime_value_ltd__media_spend AS
SELECT
    fmc.store_id,
    DATE_TRUNC(MONTH, fmc.media_cost_date) AS vip_cohort_month_date,
    fmc.is_mens_flag::BOOLEAN AS is_mens_flag,
    SUM(fmc.cost * fmc.spend_date_usd_conv_rate) AS media_spend
FROM reporting_media_prod.dbo.vw_fact_media_cost AS fmc
WHERE LOWER(fmc.targeting) NOT IN ('vip retargeting', 'purchase retargeting', 'free alpha')
GROUP BY
    fmc.store_id,
    DATE_TRUNC(MONTH, fmc.media_cost_date),
    fmc.is_mens_flag::BOOLEAN;
-- SELECT * FROM _customer_lifetime_value_ltd__media_spend;

CREATE OR REPLACE TEMP TABLE _customer_lifetime_value_ltd__stg AS
SELECT
    ltv.customer_id,
    ltv.meta_original_customer_id,
    ltv.store_id,
    ltv.vip_store_id,
    ltv.vip_cohort_month_date,
    ltv.guest_cohort_month_date,
    ltv.activation_key,
    ltv.first_activation_key,
    ltv.is_reactivated_vip,
    ltv.membership_type,
    ltv.gender,
    ltv.is_scrubs_customer,
    COALESCE(ltv.product_order_count, 0) AS product_order_count,
    COALESCE(ltv.online_product_order_count, 0) AS online_product_order_count,
    COALESCE(ltv.retail_product_order_count, 0) AS retail_product_order_count,
    COALESCE(ltv.mobile_app_product_order_count, 0) AS mobile_app_product_order_count,
    COALESCE(ltv.product_order_unit_count, 0) AS product_order_unit_count,
    COALESCE(ltv.online_product_order_unit_count, 0) AS online_product_order_unit_count,
    COALESCE(ltv.retail_product_order_unit_count, 0) AS retail_product_order_unit_count,
    COALESCE(ltv.mobile_app_product_order_unit_count, 0) AS mobile_app_product_order_unit_count,
    COALESCE(ltv.product_order_subtotal_excl_tariff_amount, 0) AS product_order_subtotal_excl_tariff_amount,
    COALESCE(ltv.online_product_order_subtotal_excl_tariff_amount, 0) AS online_product_order_subtotal_excl_tariff_amount,
    COALESCE(ltv.retail_product_order_subtotal_excl_tariff_amount, 0) AS retail_product_order_subtotal_excl_tariff_amount,
    COALESCE(ltv.mobile_app_product_order_subtotal_excl_tariff_amount, 0) AS mobile_app_product_order_subtotal_excl_tariff_amount,
    COALESCE(ltv.product_order_product_discount_amount, 0) AS product_order_product_discount_amount,
    COALESCE(ltv.online_product_order_product_discount_amount, 0) AS online_product_order_product_discount_amount,
    COALESCE(ltv.retail_product_order_product_discount_amount, 0) AS retail_product_order_product_discount_amount,
    COALESCE(ltv.mobile_app_product_order_product_discount_amount, 0) AS mobile_app_product_order_product_discount_amount,
    COALESCE(ltv.product_order_shipping_revenue_amount, 0) AS product_order_shipping_revenue_amount,
    COALESCE(ltv.online_product_order_shipping_revenue_amount, 0) AS online_product_order_shipping_revenue_amount,
    COALESCE(ltv.retail_product_order_shipping_revenue_amount, 0) AS retail_product_order_shipping_revenue_amount,
    COALESCE(ltv.mobile_app_product_order_shipping_revenue_amount, 0) AS mobile_app_product_order_shipping_revenue_amount,
    COALESCE(ltv.product_order_direct_cogs_amount, 0) AS product_order_direct_cogs_amount,
    COALESCE(ltv.online_product_order_direct_cogs_amount, 0) AS online_product_order_direct_cogs_amount,
    COALESCE(ltv.retail_product_order_direct_cogs_amount, 0) AS retail_product_order_direct_cogs_amount,
    COALESCE(ltv.mobile_app_product_order_direct_cogs_amount, 0) AS mobile_app_product_order_direct_cogs_amount,
    COALESCE(ltv.product_order_selling_expenses_amount, 0) AS product_order_selling_expenses_amount,
    COALESCE(ltv.online_product_order_selling_expenses_amount, 0) AS online_product_order_selling_expenses_amount,
    COALESCE(ltv.retail_product_order_selling_expenses_amount, 0) AS retail_product_order_selling_expenses_amount,
    COALESCE(ltv.mobile_app_product_order_selling_expenses_amount, 0) AS mobile_app_product_order_selling_expenses_amount,
    COALESCE(ltv.product_order_cash_refund_amount_and_chargeback_amount, 0) AS product_order_cash_refund_amount_and_chargeback_amount,
    COALESCE(ltv.online_product_order_cash_refund_chargeback_amount, 0) AS online_product_order_cash_refund_chargeback_amount,
    COALESCE(ltv.retail_product_order_cash_refund_chargeback_amount, 0) AS retail_product_order_cash_refund_chargeback_amount,
    COALESCE(ltv.mobile_app_product_order_cash_refund_chargeback_amount, 0) AS mobile_app_product_order_cash_refund_chargeback_amount,
    COALESCE(ltv.product_order_cash_credit_refund_amount, 0) AS product_order_cash_credit_refund_amount,
    COALESCE(ltv.online_product_order_cash_credit_refund_amount, 0) AS online_product_order_cash_credit_refund_amount,
    COALESCE(ltv.retail_product_order_cash_credit_refund_amount, 0) AS retail_product_order_cash_credit_refund_amount,
    COALESCE(ltv.mobile_app_product_order_cash_credit_refund_amount, 0) AS mobile_app_product_order_cash_credit_refund_amount,
    COALESCE(ltv.product_order_reship_exchange_order_count, 0) AS product_order_reship_exchange_order_count,
    COALESCE(ltv.online_product_order_reship_exchange_order_count, 0) AS online_product_order_reship_exchange_order_count,
    COALESCE(ltv.retail_product_order_reship_exchange_order_count, 0) AS retail_product_order_reship_exchange_order_count,
    COALESCE(ltv.mobile_app_product_order_reship_exchange_order_count, 0) AS mobile_app_product_order_reship_exchange_order_count,
    COALESCE(ltv.product_order_reship_exchange_unit_count, 0) AS product_order_reship_exchange_unit_count,
    COALESCE(ltv.online_product_order_reship_exchange_unit_count, 0) AS online_product_order_reship_exchange_unit_count,
    COALESCE(ltv.retail_product_order_reship_exchange_unit_count, 0) AS retail_product_order_reship_exchange_unit_count,
    COALESCE(ltv.mobile_app_product_order_reship_exchange_unit_count, 0) AS mobile_app_product_order_reship_exchange_unit_count,
    COALESCE(ltv.product_order_reship_exchange_direct_cogs_amount, 0) AS product_order_reship_exchange_direct_cogs_amount,
    COALESCE(ltv.online_product_order_reship_exchange_direct_cogs_amount, 0) AS online_product_order_reship_exchange_direct_cogs_amount,
    COALESCE(ltv.retail_product_order_reship_exchange_direct_cogs_amount, 0) AS retail_product_order_reship_exchange_direct_cogs_amount,
    COALESCE(ltv.mobile_app_product_order_reship_exchange_direct_cogs_amount, 0) AS mobile_app_product_order_reship_exchange_direct_cogs_amount,
    COALESCE(ltv.product_order_return_cogs_amount, 0) AS product_order_return_cogs_amount,
    COALESCE(ltv.online_product_order_return_cogs_amount, 0) AS online_product_order_return_cogs_amount,
    COALESCE(ltv.retail_product_order_return_cogs_amount, 0) AS retail_product_order_return_cogs_amount,
    COALESCE(ltv.mobile_app_product_order_return_cogs_amount, 0) AS mobile_app_product_order_return_cogs_amount,
    COALESCE(ltv.product_order_return_unit_count, 0) AS product_order_return_unit_count,
    COALESCE(ltv.online_product_order_return_unit_count, 0) AS online_product_order_return_unit_count,
    COALESCE(ltv.retail_product_order_return_unit_count, 0) AS retail_product_order_return_unit_count,
    COALESCE(ltv.mobile_app_product_order_return_unit_count, 0) AS mobile_app_product_order_return_unit_count,
    COALESCE(ltv.product_order_amount_to_pay, 0) AS product_order_amount_to_pay,
    COALESCE(ltv.online_product_order_amount_to_pay, 0) AS online_product_order_amount_to_pay,
    COALESCE(ltv.retail_product_order_amount_to_pay, 0) AS retail_product_order_amount_to_pay,
    COALESCE(ltv.mobile_app_product_order_amount_to_pay, 0) AS mobile_app_product_order_amount_to_pay,
    COALESCE(ltv.product_gross_revenue_excl_shipping, 0) AS product_gross_revenue_excl_shipping,
    COALESCE(ltv.online_product_gross_revenue_excl_shipping, 0) AS online_product_gross_revenue_excl_shipping,
    COALESCE(ltv.retail_product_gross_revenue_excl_shipping, 0) AS retail_product_gross_revenue_excl_shipping,
    COALESCE(ltv.mobile_app_product_gross_revenue_excl_shipping, 0) AS mobile_app_product_gross_revenue_excl_shipping,
    COALESCE(ltv.product_gross_revenue, 0) AS product_gross_revenue,
    COALESCE(ltv.online_product_gross_revenue, 0) AS online_product_gross_revenue,
    COALESCE(ltv.retail_product_gross_revenue, 0) AS retail_product_gross_revenue,
    COALESCE(ltv.mobile_app_product_gross_revenue, 0) AS mobile_app_product_gross_revenue,
    COALESCE(ltv.product_net_revenue, 0) AS product_net_revenue,
    COALESCE(ltv.online_product_net_revenue, 0) AS online_product_net_revenue,
    COALESCE(ltv.retail_product_net_revenue, 0) AS retail_product_net_revenue,
    COALESCE(ltv.mobile_app_product_net_revenue, 0) AS mobile_app_product_net_revenue,
    COALESCE(ltv.product_margin_pre_return, 0) AS product_margin_pre_return,
    COALESCE(ltv.first_guest_product_margin_pre_return, 0) AS first_guest_product_margin_pre_return,
    COALESCE(ltv.online_product_margin_pre_return, 0) AS online_product_margin_pre_return,
    COALESCE(ltv.retail_product_margin_pre_return, 0) AS retail_product_margin_pre_return,
    COALESCE(ltv.mobile_app_product_margin_pre_return, 0) AS mobile_app_product_margin_pre_return,
    COALESCE(ltv.product_margin_pre_return_excl_shipping, 0) AS product_margin_pre_return_excl_shipping,
    COALESCE(ltv.online_product_margin_pre_return_excl_shipping, 0) AS online_product_margin_pre_return_excl_shipping,
    COALESCE(ltv.retail_product_margin_pre_return_excl_shipping, 0) AS retail_product_margin_pre_return_excl_shipping,
    COALESCE(ltv.mobile_app_product_margin_pre_return_excl_shipping, 0) AS mobile_app_product_margin_pre_return_excl_shipping,
    COALESCE(ltv.product_gross_profit, 0) AS product_gross_profit,
    COALESCE(ltv.online_product_gross_profit, 0) AS online_product_gross_profit,
    COALESCE(ltv.retail_product_gross_profit, 0) AS retail_product_gross_profit,
    COALESCE(ltv.mobile_app_product_gross_profit, 0) AS mobile_app_product_gross_profit,
    COALESCE(ltv.product_variable_contribution_profit, 0) AS product_variable_contribution_profit,
    COALESCE(ltv.online_product_variable_contribution_profit, 0) AS online_product_variable_contribution_profit,
    COALESCE(ltv.retail_product_variable_contribution_profit, 0) AS retail_product_variable_contribution_profit,
    COALESCE(ltv.mobile_app_product_variable_contribution_profit, 0) AS mobile_app_product_variable_contribution_profit,
    COALESCE(ltv.product_order_cash_gross_revenue_amount, 0) AS product_order_cash_gross_revenue_amount,
    COALESCE(ltv.online_product_order_cash_gross_revenue_amount, 0) AS online_product_order_cash_gross_revenue_amount,
    COALESCE(ltv.retail_product_order_cash_gross_revenue_amount, 0) AS retail_product_order_cash_gross_revenue_amount,
    COALESCE(ltv.mobile_app_product_order_cash_gross_revenue_amount, 0) AS mobile_app_product_order_cash_gross_revenue_amount,
    COALESCE(ltv.product_order_cash_net_revenue, 0) AS product_order_cash_net_revenue,
    COALESCE(ltv.online_product_order_cash_net_revenue, 0) AS online_product_order_cash_net_revenue,
    COALESCE(ltv.retail_product_order_cash_net_revenue, 0) AS retail_product_order_cash_net_revenue,
    COALESCE(ltv.mobile_app_product_order_cash_net_revenue, 0) AS mobile_app_product_order_cash_net_revenue,
    COALESCE(ltv.billing_cash_gross_revenue, 0) AS billing_cash_gross_revenue,
    COALESCE(ltv.billing_cash_net_revenue, 0) AS billing_cash_net_revenue,
    COALESCE(ltv.cash_gross_revenue, 0) AS cash_gross_revenue,
    COALESCE(ltv.cash_net_revenue, 0) AS cash_net_revenue,
    COALESCE(ltv.cash_gross_profit, 0) AS cash_gross_profit,
    COALESCE(ltv.cash_variable_contribution_profit, 0) AS cash_variable_contribution_profit,
    COALESCE(ltv.monthly_billed_credit_cash_transaction_amount, 0) AS monthly_billed_credit_cash_transaction_amount,
    COALESCE(ltv.membership_fee_cash_transaction_amount, 0) AS membership_fee_cash_transaction_amount,
    COALESCE(ltv.gift_card_transaction_amount, 0) AS gift_card_transaction_amount,
    COALESCE(ltv.legacy_credit_cash_transaction_amount, 0) AS legacy_credit_cash_transaction_amount,
    COALESCE(ltv.monthly_billed_credit_cash_refund_chargeback_amount, 0) AS monthly_billed_credit_cash_refund_chargeback_amount,
    COALESCE(ltv.membership_fee_cash_refund_chargeback_amount, 0) AS membership_fee_cash_refund_chargeback_amount,
    COALESCE(ltv.gift_card_cash_refund_chargeback_amount, 0) AS gift_card_cash_refund_chargeback_amount,
    COALESCE(ltv.legacy_credit_cash_refund_chargeback_amount, 0) AS legacy_credit_cash_refund_chargeback_amount,
    COALESCE(ltv.billed_cash_credit_issued_amount, 0) AS billed_cash_credit_issued_amount,
    COALESCE(ltv.billed_cash_credit_redeemed_amount, 0) AS billed_cash_credit_redeemed_amount,
    COALESCE(ltv.online_billed_cash_credit_redeemed_amount, 0) AS online_billed_cash_credit_redeemed_amount,
    COALESCE(ltv.retail_billed_cash_credit_redeemed_amount, 0) AS retail_billed_cash_credit_redeemed_amount,
    COALESCE(ltv.mobile_billed_cash_credit_redeemed_amount, 0) AS mobile_billed_cash_credit_redeemed_amount,
    COALESCE(ltv.billed_cash_credit_cancelled_amount, 0) AS billed_cash_credit_cancelled_amount,
    COALESCE(ltv.billed_cash_credit_expired_amount, 0) AS billed_cash_credit_expired_amount,
    COALESCE(ltv.billed_cash_credit_issued_equivalent_count, 0) AS billed_cash_credit_issued_equivalent_count,
    COALESCE(ltv.billed_cash_credit_redeemed_same_month_amount, 0) AS billed_cash_credit_redeemed_same_month_amount,
    COALESCE(ltv.billed_cash_credit_redeemed_equivalent_count, 0) AS billed_cash_credit_redeemed_equivalent_count,
    COALESCE(ltv.billed_cash_credit_cancelled_equivalent_count, 0) AS billed_cash_credit_cancelled_equivalent_count,
    COALESCE(ltv.billed_cash_credit_expired_equivalent_count, 0) AS billed_cash_credit_expired_equivalent_count,
    COALESCE(ltv.refund_cash_credit_issued_amount, 0) AS refund_cash_credit_issued_amount,
    COALESCE(ltv.refund_cash_credit_redeemed_amount, 0) AS refund_cash_credit_redeemed_amount,
    COALESCE(ltv.refund_cash_credit_cancelled_amount, 0) AS refund_cash_credit_cancelled_amount,
    COALESCE(ltv.refund_cash_credit_expired_amount, 0) AS refund_cash_credit_expired_amount,
    COALESCE(ltv.other_cash_credit_issued_amount, 0) AS other_cash_credit_issued_amount,
    COALESCE(ltv.other_cash_credit_redeemed_amount, 0) AS other_cash_credit_redeemed_amount,
    COALESCE(ltv.other_cash_credit_cancelled_amount, 0) AS other_cash_credit_cancelled_amount,
    COALESCE(ltv.other_cash_credit_expired_amount, 0) AS other_cash_credit_expired_amount,
    COALESCE(ltv.noncash_credit_issued_amount, 0) AS noncash_credit_issued_amount,
    COALESCE(ltv.noncash_credit_cancelled_amount, 0) AS noncash_credit_cancelled_amount,
    COALESCE(ltv.noncash_credit_expired_amount, 0) AS noncash_credit_expired_amount,
    COALESCE(d.cumulative_cash_gross_profit_decile, 0) AS cumulative_cash_gross_profit_decile,
    COALESCE(d.cumulative_product_gross_profit_decile, 0) AS cumulative_product_gross_profit_decile,
    COALESCE(a.activating_product_order_subtotal_excl_tariff_amount, 0) AS activating_product_order_subtotal_excl_tariff_amount,
    COALESCE(a.activating_product_order_tariff_amount, 0) AS activating_product_order_tariff_amount,
    COALESCE(a.activating_product_order_product_subtotal_amount, 0) AS activating_product_order_product_subtotal_amount,
    COALESCE(a.activating_product_order_product_discount_amount, 0) AS activating_product_order_product_discount_amount,
    COALESCE(a.activating_product_order_shipping_discount_amount, 0) AS activating_product_order_shipping_discount_amount,
    COALESCE(a.activating_product_order_shipping_revenue_before_discount_amount, 0) AS activating_product_order_shipping_revenue_before_discount_amount,
    COALESCE(a.activating_product_order_shipping_revenue_amount, 0) AS activating_product_order_shipping_revenue_amount,
    COALESCE(a.activating_product_order_tax_amount, 0) AS activating_product_order_tax_amount,
    COALESCE(a.activating_product_order_cash_transaction_amount, 0) AS activating_product_order_cash_transaction_amount,
    COALESCE(a.activating_product_order_count, 0) AS activating_product_order_count,
    COALESCE(a.online_activating_product_order_count, 0) AS online_activating_product_order_count,
    COALESCE(a.retail_activating_product_order_count, 0) AS retail_activating_product_order_count,
    COALESCE(a.mobile_app_activating_product_order_count, 0) AS mobile_app_activating_product_order_count,
    COALESCE(a.activating_product_order_unit_count, 0) AS activating_product_order_unit_count,
    COALESCE(a.activating_product_order_outfit_component_unit_count, 0) AS activating_product_order_outfit_component_unit_count,
    COALESCE(a.activating_product_order_outfit_count, 0) AS activating_product_order_outfit_count,
    COALESCE(a.activating_product_order_discounted_unit_count, 0) AS activating_product_order_discounted_unit_count,
    COALESCE(a.activating_product_order_zero_revenue_unit_count, 0) AS activating_product_order_zero_revenue_unit_count,
    COALESCE(a.activating_product_order_landed_product_cost_amount, 0) AS activating_product_order_landed_product_cost_amount,
    COALESCE(a.activating_product_order_shipping_cost_amount, 0) AS activating_product_order_shipping_cost_amount,
    COALESCE(a.activating_product_order_shipping_supplies_cost_amount, 0) AS activating_product_order_shipping_supplies_cost_amount,
    COALESCE(a.activating_product_order_misc_cogs_amount, 0) AS activating_product_order_misc_cogs_amount,
    COALESCE(a.activating_product_order_direct_cogs_amount, 0) AS activating_product_order_direct_cogs_amount,
    COALESCE(a.activating_product_order_payment_processing_cost_amount, 0) AS activating_product_order_payment_processing_cost_amount,
    COALESCE(a.activating_product_order_variable_gms_cost_amount, 0) AS activating_product_order_variable_gms_cost_amount,
    COALESCE(a.activating_product_order_variable_warehouse_cost_amount, 0) AS activating_product_order_variable_warehouse_cost_amount,
    COALESCE(a.activating_product_order_amount_to_pay, 0) AS activating_product_order_amount_to_pay,
    COALESCE(a.activating_product_gross_revenue_excl_shipping, 0) AS activating_product_gross_revenue_excl_shipping,
    COALESCE(a.activating_product_gross_revenue, 0) AS activating_product_gross_revenue,
    COALESCE(a.online_activating_product_gross_revenue, 0) AS online_activating_product_gross_revenue,
    COALESCE(a.retail_activating_product_gross_revenue, 0) AS retail_activating_product_gross_revenue,
    COALESCE(a.mobile_app_activating_product_gross_revenue, 0) AS mobile_app_activating_product_gross_revenue,
    COALESCE(a.activating_product_margin_pre_return, 0) AS activating_product_margin_pre_return,
    COALESCE(a.activating_product_margin_pre_return_excl_shipping, 0) AS activating_product_margin_pre_return_excl_shipping,
    COALESCE(ltv.m3_cumulative_cash_gross_profit, 0) AS m3_cumulative_cash_gross_profit,
    COALESCE(ltv.m3_cumulative_product_gross_profit, 0) AS m3_cumulative_product_gross_profit,
    COALESCE(ltv.m6_cumulative_cash_gross_profit, 0) AS m6_cumulative_cash_gross_profit,
    COALESCE(ltv.m6_cumulative_product_gross_profit, 0) AS m6_cumulative_product_gross_profit,
    COALESCE(ltv.m9_cumulative_cash_gross_profit, 0) AS m9_cumulative_cash_gross_profit,
    COALESCE(ltv.m9_cumulative_product_gross_profit, 0) AS m9_cumulative_product_gross_profit,
    COALESCE(ltv.m12_cumulative_cash_gross_profit, 0) AS m12_cumulative_cash_gross_profit,
    COALESCE(ltv.m12_cumulative_product_gross_profit, 0) AS m12_cumulative_product_gross_profit,
    COALESCE(ltv.m18_cumulative_cash_gross_profit, 0) AS m18_cumulative_cash_gross_profit,
    COALESCE(ltv.m18_cumulative_product_gross_profit, 0) AS m18_cumulative_product_gross_profit,
    COALESCE(ltv.m24_cumulative_cash_gross_profit, 0) AS m24_cumulative_cash_gross_profit,
    COALESCE(ltv.m24_cumulative_product_gross_profit, 0) AS m24_cumulative_product_gross_profit,
    COALESCE(ltv.m36_cumulative_cash_gross_profit, 0) AS m36_cumulative_cash_gross_profit,
    COALESCE(ltv.m36_cumulative_product_gross_profit, 0) AS m36_cumulative_product_gross_profit,
    COALESCE(ms.media_spend / NULLIF(msd.media_spend_denom, 0), 0) AS customer_acquisition_cost,
    COALESCE((IFNULL(ms.media_spend, 0) - IFNULL(ltv.first_guest_product_margin_pre_return, 0)) / NULLIF(msd.media_spend_denom, 0), 0) AS x_customer_acquisition_cost
FROM _customer_lifetime_value_ltd__ltv AS ltv
    LEFT JOIN _customer_lifetime_value_ltd__decile AS d
        ON d.customer_id = ltv.customer_id
        AND d.activation_key = ltv.activation_key
    LEFT JOIN _customer_lifetime_value_ltd__activating AS a
        ON a.customer_id = ltv.customer_id
        AND a.activation_key = ltv.activation_key
    LEFT JOIN _customer_lifetime_value_ltd__cross_promo AS cp
        ON cp.customer_id = ltv.customer_id
    LEFT JOIN _customer_lifetime_value_ltd__media_spend AS ms
        ON ms.store_id = ltv.store_id
        AND ms.is_mens_flag = IFF(ltv.gender = 'M', TRUE, FALSE)::BOOLEAN
        AND ms.vip_cohort_month_date = ltv.vip_cohort_month_date
        AND cp.customer_id IS NULL
    LEFT JOIN _customer_lifetime_value_ltd__media_spend_denominator AS msd
        ON msd.store_id = ltv.store_id
        AND msd.is_mens_flag = IFF(ltv.gender = 'M', TRUE, FALSE)::BOOLEAN
        AND msd.vip_cohort_month_date = ltv.vip_cohort_month_date
        AND cp.customer_id IS NULL;
-- SELECT * FROM _customer_lifetime_value_ltd__stg;

/* Since this transform always performs a full refresh, we will overwrite the analytics_base.customer_lifetime_value_ltd table */
INSERT OVERWRITE INTO analytics_base.customer_lifetime_value_ltd (
    customer_id,
    meta_original_customer_id,
    store_id,
    vip_store_id,
    vip_cohort_month_date,
    guest_cohort_month_date,
    activation_key,
    first_activation_key,
    is_reactivated_vip,
    membership_type,
    gender,
    is_scrubs_customer,
    product_order_count,
    online_product_order_count,
    retail_product_order_count,
    mobile_app_product_order_count,
    product_order_unit_count,
    online_product_order_unit_count,
    retail_product_order_unit_count,
    mobile_app_product_order_unit_count,
    product_order_subtotal_excl_tariff_amount,
    online_product_order_subtotal_excl_tariff_amount,
    retail_product_order_subtotal_excl_tariff_amount,
    mobile_app_product_order_subtotal_excl_tariff_amount,
    product_order_product_discount_amount,
    online_product_order_product_discount_amount,
    retail_product_order_product_discount_amount,
    mobile_app_product_order_product_discount_amount,
    product_order_shipping_revenue_amount,
    online_product_order_shipping_revenue_amount,
    retail_product_order_shipping_revenue_amount,
    mobile_app_product_order_shipping_revenue_amount,
    product_order_direct_cogs_amount,
    online_product_order_direct_cogs_amount,
    retail_product_order_direct_cogs_amount,
    mobile_app_product_order_direct_cogs_amount,
    product_order_selling_expenses_amount,
    online_product_order_selling_expenses_amount,
    retail_product_order_selling_expenses_amount,
    mobile_app_product_order_selling_expenses_amount,
    product_order_cash_refund_amount_and_chargeback_amount,
    online_product_order_cash_refund_chargeback_amount,
    retail_product_order_cash_refund_chargeback_amount,
    mobile_app_product_order_cash_refund_chargeback_amount,
    product_order_cash_credit_refund_amount,
    online_product_order_cash_credit_refund_amount,
    retail_product_order_cash_credit_refund_amount,
    mobile_app_product_order_cash_credit_refund_amount,
    product_order_reship_exchange_order_count,
    online_product_order_reship_exchange_order_count,
    retail_product_order_reship_exchange_order_count,
    mobile_app_product_order_reship_exchange_order_count,
    product_order_reship_exchange_unit_count,
    online_product_order_reship_exchange_unit_count,
    retail_product_order_reship_exchange_unit_count,
    mobile_app_product_order_reship_exchange_unit_count,
    product_order_reship_exchange_direct_cogs_amount,
    online_product_order_reship_exchange_direct_cogs_amount,
    retail_product_order_reship_exchange_direct_cogs_amount,
    mobile_app_product_order_reship_exchange_direct_cogs_amount,
    product_order_return_cogs_amount,
    online_product_order_return_cogs_amount,
    retail_product_order_return_cogs_amount,
    mobile_app_product_order_return_cogs_amount,
    product_order_return_unit_count,
    online_product_order_return_unit_count,
    retail_product_order_return_unit_count,
    mobile_app_product_order_return_unit_count,
    product_order_amount_to_pay,
    online_product_order_amount_to_pay,
    retail_product_order_amount_to_pay,
    mobile_app_product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    online_product_gross_revenue_excl_shipping,
    retail_product_gross_revenue_excl_shipping,
    mobile_app_product_gross_revenue_excl_shipping,
    product_gross_revenue,
    online_product_gross_revenue,
    retail_product_gross_revenue,
    mobile_app_product_gross_revenue,
    product_net_revenue,
    online_product_net_revenue,
    retail_product_net_revenue,
    mobile_app_product_net_revenue,
    product_margin_pre_return,
    first_guest_product_margin_pre_return,
    online_product_margin_pre_return,
    retail_product_margin_pre_return,
    mobile_app_product_margin_pre_return,
    product_margin_pre_return_excl_shipping,
    online_product_margin_pre_return_excl_shipping,
    retail_product_margin_pre_return_excl_shipping,
    mobile_app_product_margin_pre_return_excl_shipping,
    product_gross_profit,
    online_product_gross_profit,
    retail_product_gross_profit,
    mobile_app_product_gross_profit,
    product_variable_contribution_profit,
    online_product_variable_contribution_profit,
    retail_product_variable_contribution_profit,
    mobile_app_product_variable_contribution_profit,
    product_order_cash_gross_revenue_amount,
    online_product_order_cash_gross_revenue_amount,
    retail_product_order_cash_gross_revenue_amount,
    mobile_app_product_order_cash_gross_revenue_amount,
    product_order_cash_net_revenue,
    online_product_order_cash_net_revenue,
    retail_product_order_cash_net_revenue,
    mobile_app_product_order_cash_net_revenue,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    cash_variable_contribution_profit,
    monthly_billed_credit_cash_transaction_amount,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    monthly_billed_credit_cash_refund_chargeback_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_redeemed_amount,
    online_billed_cash_credit_redeemed_amount,
    retail_billed_cash_credit_redeemed_amount,
    mobile_billed_cash_credit_redeemed_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_same_month_amount,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount,
    cumulative_cash_gross_profit_decile,
    cumulative_product_gross_profit_decile,
    activating_product_order_subtotal_excl_tariff_amount,
    activating_product_order_tariff_amount,
    activating_product_order_product_subtotal_amount,
    activating_product_order_product_discount_amount,
    activating_product_order_shipping_discount_amount,
    activating_product_order_shipping_revenue_before_discount_amount,
    activating_product_order_shipping_revenue_amount,
    activating_product_order_tax_amount,
    activating_product_order_cash_transaction_amount,
    activating_product_order_count,
    online_activating_product_order_count,
    retail_activating_product_order_count,
    mobile_app_activating_product_order_count,
    activating_product_order_unit_count,
    activating_product_order_outfit_component_unit_count,
    activating_product_order_outfit_count,
    activating_product_order_discounted_unit_count,
    activating_product_order_zero_revenue_unit_count,
    activating_product_order_landed_product_cost_amount,
    activating_product_order_shipping_cost_amount,
    activating_product_order_shipping_supplies_cost_amount,
    activating_product_order_misc_cogs_amount,
    activating_product_order_direct_cogs_amount,
    activating_product_order_payment_processing_cost_amount,
    activating_product_order_variable_gms_cost_amount,
    activating_product_order_variable_warehouse_cost_amount,
    activating_product_order_amount_to_pay,
    activating_product_gross_revenue_excl_shipping,
    activating_product_gross_revenue,
    online_activating_product_gross_revenue,
    retail_activating_product_gross_revenue,
    mobile_app_activating_product_gross_revenue,
    activating_product_margin_pre_return,
    activating_product_margin_pre_return_excl_shipping,
    m3_cumulative_cash_gross_profit,
    m3_cumulative_product_gross_profit,
    m6_cumulative_cash_gross_profit,
    m6_cumulative_product_gross_profit,
    m9_cumulative_cash_gross_profit,
    m9_cumulative_product_gross_profit,
    m12_cumulative_cash_gross_profit,
    m12_cumulative_product_gross_profit,
    m18_cumulative_cash_gross_profit,
    m18_cumulative_product_gross_profit,
    m24_cumulative_cash_gross_profit,
    m24_cumulative_product_gross_profit,
    m36_cumulative_cash_gross_profit,
    m36_cumulative_product_gross_profit,
    customer_acquisition_cost,
    x_customer_acquisition_cost,
    meta_row_hash,
    meta_create_datetime,
    meta_update_datetime
    )
SELECT
    customer_id,
    meta_original_customer_id,
    store_id,
    vip_store_id,
    vip_cohort_month_date,
    guest_cohort_month_date,
    activation_key,
    first_activation_key,
    is_reactivated_vip,
    membership_type,
    gender,
    is_scrubs_customer,
    product_order_count,
    online_product_order_count,
    retail_product_order_count,
    mobile_app_product_order_count,
    product_order_unit_count,
    online_product_order_unit_count,
    retail_product_order_unit_count,
    mobile_app_product_order_unit_count,
    product_order_subtotal_excl_tariff_amount,
    online_product_order_subtotal_excl_tariff_amount,
    retail_product_order_subtotal_excl_tariff_amount,
    mobile_app_product_order_subtotal_excl_tariff_amount,
    product_order_product_discount_amount,
    online_product_order_product_discount_amount,
    retail_product_order_product_discount_amount,
    mobile_app_product_order_product_discount_amount,
    product_order_shipping_revenue_amount,
    online_product_order_shipping_revenue_amount,
    retail_product_order_shipping_revenue_amount,
    mobile_app_product_order_shipping_revenue_amount,
    product_order_direct_cogs_amount,
    online_product_order_direct_cogs_amount,
    retail_product_order_direct_cogs_amount,
    mobile_app_product_order_direct_cogs_amount,
    product_order_selling_expenses_amount,
    online_product_order_selling_expenses_amount,
    retail_product_order_selling_expenses_amount,
    mobile_app_product_order_selling_expenses_amount,
    product_order_cash_refund_amount_and_chargeback_amount,
    online_product_order_cash_refund_chargeback_amount,
    retail_product_order_cash_refund_chargeback_amount,
    mobile_app_product_order_cash_refund_chargeback_amount,
    product_order_cash_credit_refund_amount,
    online_product_order_cash_credit_refund_amount,
    retail_product_order_cash_credit_refund_amount,
    mobile_app_product_order_cash_credit_refund_amount,
    product_order_reship_exchange_order_count,
    online_product_order_reship_exchange_order_count,
    retail_product_order_reship_exchange_order_count,
    mobile_app_product_order_reship_exchange_order_count,
    product_order_reship_exchange_unit_count,
    online_product_order_reship_exchange_unit_count,
    retail_product_order_reship_exchange_unit_count,
    mobile_app_product_order_reship_exchange_unit_count,
    product_order_reship_exchange_direct_cogs_amount,
    online_product_order_reship_exchange_direct_cogs_amount,
    retail_product_order_reship_exchange_direct_cogs_amount,
    mobile_app_product_order_reship_exchange_direct_cogs_amount,
    product_order_return_cogs_amount,
    online_product_order_return_cogs_amount,
    retail_product_order_return_cogs_amount,
    mobile_app_product_order_return_cogs_amount,
    product_order_return_unit_count,
    online_product_order_return_unit_count,
    retail_product_order_return_unit_count,
    mobile_app_product_order_return_unit_count,
    product_order_amount_to_pay,
    online_product_order_amount_to_pay,
    retail_product_order_amount_to_pay,
    mobile_app_product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    online_product_gross_revenue_excl_shipping,
    retail_product_gross_revenue_excl_shipping,
    mobile_app_product_gross_revenue_excl_shipping,
    product_gross_revenue,
    online_product_gross_revenue,
    retail_product_gross_revenue,
    mobile_app_product_gross_revenue,
    product_net_revenue,
    online_product_net_revenue,
    retail_product_net_revenue,
    mobile_app_product_net_revenue,
    product_margin_pre_return,
    first_guest_product_margin_pre_return,
    online_product_margin_pre_return,
    retail_product_margin_pre_return,
    mobile_app_product_margin_pre_return,
    product_margin_pre_return_excl_shipping,
    online_product_margin_pre_return_excl_shipping,
    retail_product_margin_pre_return_excl_shipping,
    mobile_app_product_margin_pre_return_excl_shipping,
    product_gross_profit,
    online_product_gross_profit,
    retail_product_gross_profit,
    mobile_app_product_gross_profit,
    product_variable_contribution_profit,
    online_product_variable_contribution_profit,
    retail_product_variable_contribution_profit,
    mobile_app_product_variable_contribution_profit,
    product_order_cash_gross_revenue_amount,
    online_product_order_cash_gross_revenue_amount,
    retail_product_order_cash_gross_revenue_amount,
    mobile_app_product_order_cash_gross_revenue_amount,
    product_order_cash_net_revenue,
    online_product_order_cash_net_revenue,
    retail_product_order_cash_net_revenue,
    mobile_app_product_order_cash_net_revenue,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    cash_variable_contribution_profit,
    monthly_billed_credit_cash_transaction_amount,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    monthly_billed_credit_cash_refund_chargeback_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_redeemed_amount,
    online_billed_cash_credit_redeemed_amount,
    retail_billed_cash_credit_redeemed_amount,
    mobile_billed_cash_credit_redeemed_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_same_month_amount,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount,
    cumulative_cash_gross_profit_decile,
    cumulative_product_gross_profit_decile,
    activating_product_order_subtotal_excl_tariff_amount,
    activating_product_order_tariff_amount,
    activating_product_order_product_subtotal_amount,
    activating_product_order_product_discount_amount,
    activating_product_order_shipping_discount_amount,
    activating_product_order_shipping_revenue_before_discount_amount,
    activating_product_order_shipping_revenue_amount,
    activating_product_order_tax_amount,
    activating_product_order_cash_transaction_amount,
    activating_product_order_count,
    online_activating_product_order_count,
    retail_activating_product_order_count,
    mobile_app_activating_product_order_count,
    activating_product_order_unit_count,
    activating_product_order_outfit_component_unit_count,
    activating_product_order_outfit_count,
    activating_product_order_discounted_unit_count,
    activating_product_order_zero_revenue_unit_count,
    activating_product_order_landed_product_cost_amount,
    activating_product_order_shipping_cost_amount,
    activating_product_order_shipping_supplies_cost_amount,
    activating_product_order_misc_cogs_amount,
    activating_product_order_direct_cogs_amount,
    activating_product_order_payment_processing_cost_amount,
    activating_product_order_variable_gms_cost_amount,
    activating_product_order_variable_warehouse_cost_amount,
    activating_product_order_amount_to_pay,
    activating_product_gross_revenue_excl_shipping,
    activating_product_gross_revenue,
    online_activating_product_gross_revenue,
    retail_activating_product_gross_revenue,
    mobile_app_activating_product_gross_revenue,
    activating_product_margin_pre_return,
    activating_product_margin_pre_return_excl_shipping,
    m3_cumulative_cash_gross_profit,
    m3_cumulative_product_gross_profit,
    m6_cumulative_cash_gross_profit,
    m6_cumulative_product_gross_profit,
    m9_cumulative_cash_gross_profit,
    m9_cumulative_product_gross_profit,
    m12_cumulative_cash_gross_profit,
    m12_cumulative_product_gross_profit,
    m18_cumulative_cash_gross_profit,
    m18_cumulative_product_gross_profit,
    m24_cumulative_cash_gross_profit,
    m24_cumulative_product_gross_profit,
    m36_cumulative_cash_gross_profit,
    m36_cumulative_product_gross_profit,
    customer_acquisition_cost,
    x_customer_acquisition_cost,
    HASH(
        customer_id,
        meta_original_customer_id,
        store_id,
        vip_store_id,
        vip_cohort_month_date,
        guest_cohort_month_date,
        activation_key,
        first_activation_key,
        is_reactivated_vip,
        membership_type,
        gender,
        is_scrubs_customer,
        product_order_count,
        online_product_order_count,
        retail_product_order_count,
        mobile_app_product_order_count,
        product_order_unit_count,
        online_product_order_unit_count,
        retail_product_order_unit_count,
        mobile_app_product_order_unit_count,
        product_order_subtotal_excl_tariff_amount,
        online_product_order_subtotal_excl_tariff_amount,
        retail_product_order_subtotal_excl_tariff_amount,
        mobile_app_product_order_subtotal_excl_tariff_amount,
        product_order_product_discount_amount,
        online_product_order_product_discount_amount,
        retail_product_order_product_discount_amount,
        mobile_app_product_order_product_discount_amount,
        product_order_shipping_revenue_amount,
        online_product_order_shipping_revenue_amount,
        retail_product_order_shipping_revenue_amount,
        mobile_app_product_order_shipping_revenue_amount,
        product_order_direct_cogs_amount,
        online_product_order_direct_cogs_amount,
        retail_product_order_direct_cogs_amount,
        mobile_app_product_order_direct_cogs_amount,
        product_order_selling_expenses_amount,
        online_product_order_selling_expenses_amount,
        retail_product_order_selling_expenses_amount,
        mobile_app_product_order_selling_expenses_amount,
        product_order_cash_refund_amount_and_chargeback_amount,
        online_product_order_cash_refund_chargeback_amount,
        retail_product_order_cash_refund_chargeback_amount,
        mobile_app_product_order_cash_refund_chargeback_amount,
        product_order_cash_credit_refund_amount,
        online_product_order_cash_credit_refund_amount,
        retail_product_order_cash_credit_refund_amount,
        mobile_app_product_order_cash_credit_refund_amount,
        product_order_reship_exchange_order_count,
        online_product_order_reship_exchange_order_count,
        retail_product_order_reship_exchange_order_count,
        mobile_app_product_order_reship_exchange_order_count,
        product_order_reship_exchange_unit_count,
        online_product_order_reship_exchange_unit_count,
        retail_product_order_reship_exchange_unit_count,
        mobile_app_product_order_reship_exchange_unit_count,
        product_order_reship_exchange_direct_cogs_amount,
        online_product_order_reship_exchange_direct_cogs_amount,
        retail_product_order_reship_exchange_direct_cogs_amount,
        mobile_app_product_order_reship_exchange_direct_cogs_amount,
        product_order_return_cogs_amount,
        online_product_order_return_cogs_amount,
        retail_product_order_return_cogs_amount,
        mobile_app_product_order_return_cogs_amount,
        product_order_return_unit_count,
        online_product_order_return_unit_count,
        retail_product_order_return_unit_count,
        mobile_app_product_order_return_unit_count,
        product_order_amount_to_pay,
        online_product_order_amount_to_pay,
        retail_product_order_amount_to_pay,
        mobile_app_product_order_amount_to_pay,
        product_gross_revenue_excl_shipping,
        online_product_gross_revenue_excl_shipping,
        retail_product_gross_revenue_excl_shipping,
        mobile_app_product_gross_revenue_excl_shipping,
        product_gross_revenue,
        online_product_gross_revenue,
        retail_product_gross_revenue,
        mobile_app_product_gross_revenue,
        product_net_revenue,
        online_product_net_revenue,
        retail_product_net_revenue,
        mobile_app_product_net_revenue,
        product_margin_pre_return,
        first_guest_product_margin_pre_return,
        online_product_margin_pre_return,
        retail_product_margin_pre_return,
        mobile_app_product_margin_pre_return,
        product_margin_pre_return_excl_shipping,
        online_product_margin_pre_return_excl_shipping,
        retail_product_margin_pre_return_excl_shipping,
        mobile_app_product_margin_pre_return_excl_shipping,
        product_gross_profit,
        online_product_gross_profit,
        retail_product_gross_profit,
        mobile_app_product_gross_profit,
        product_variable_contribution_profit,
        online_product_variable_contribution_profit,
        retail_product_variable_contribution_profit,
        mobile_app_product_variable_contribution_profit,
        product_order_cash_gross_revenue_amount,
        online_product_order_cash_gross_revenue_amount,
        retail_product_order_cash_gross_revenue_amount,
        mobile_app_product_order_cash_gross_revenue_amount,
        product_order_cash_net_revenue,
        online_product_order_cash_net_revenue,
        retail_product_order_cash_net_revenue,
        mobile_app_product_order_cash_net_revenue,
        billing_cash_gross_revenue,
        billing_cash_net_revenue,
        cash_gross_revenue,
        cash_net_revenue,
        cash_gross_profit,
        cash_variable_contribution_profit,
        monthly_billed_credit_cash_transaction_amount,
        membership_fee_cash_transaction_amount,
        gift_card_transaction_amount,
        legacy_credit_cash_transaction_amount,
        monthly_billed_credit_cash_refund_chargeback_amount,
        membership_fee_cash_refund_chargeback_amount,
        gift_card_cash_refund_chargeback_amount,
        legacy_credit_cash_refund_chargeback_amount,
        billed_cash_credit_issued_amount,
        billed_cash_credit_redeemed_amount,
        online_billed_cash_credit_redeemed_amount,
        retail_billed_cash_credit_redeemed_amount,
        mobile_billed_cash_credit_redeemed_amount,
        billed_cash_credit_cancelled_amount,
        billed_cash_credit_expired_amount,
        billed_cash_credit_issued_equivalent_count,
        billed_cash_credit_redeemed_same_month_amount,
        billed_cash_credit_redeemed_equivalent_count,
        billed_cash_credit_cancelled_equivalent_count,
        billed_cash_credit_expired_equivalent_count,
        refund_cash_credit_issued_amount,
        refund_cash_credit_redeemed_amount,
        refund_cash_credit_cancelled_amount,
        refund_cash_credit_expired_amount,
        other_cash_credit_issued_amount,
        other_cash_credit_redeemed_amount,
        other_cash_credit_cancelled_amount,
        other_cash_credit_expired_amount,
        noncash_credit_issued_amount,
        noncash_credit_cancelled_amount,
        noncash_credit_expired_amount,
        cumulative_cash_gross_profit_decile,
        cumulative_product_gross_profit_decile,
        activating_product_order_subtotal_excl_tariff_amount,
        activating_product_order_tariff_amount,
        activating_product_order_product_subtotal_amount,
        activating_product_order_product_discount_amount,
        activating_product_order_shipping_discount_amount,
        activating_product_order_shipping_revenue_before_discount_amount,
        activating_product_order_shipping_revenue_amount,
        activating_product_order_tax_amount,
        activating_product_order_cash_transaction_amount,
        activating_product_order_count,
        online_activating_product_order_count,
        retail_activating_product_order_count,
        mobile_app_activating_product_order_count,
        activating_product_order_unit_count,
        activating_product_order_outfit_component_unit_count,
        activating_product_order_outfit_count,
        activating_product_order_discounted_unit_count,
        activating_product_order_zero_revenue_unit_count,
        activating_product_order_landed_product_cost_amount,
        activating_product_order_shipping_cost_amount,
        activating_product_order_shipping_supplies_cost_amount,
        activating_product_order_misc_cogs_amount,
        activating_product_order_direct_cogs_amount,
        activating_product_order_payment_processing_cost_amount,
        activating_product_order_variable_gms_cost_amount,
        activating_product_order_variable_warehouse_cost_amount,
        activating_product_order_amount_to_pay,
        activating_product_gross_revenue_excl_shipping,
        activating_product_gross_revenue,
        online_activating_product_gross_revenue,
        retail_activating_product_gross_revenue,
        mobile_app_activating_product_gross_revenue,
        activating_product_margin_pre_return,
        activating_product_margin_pre_return_excl_shipping,
        m3_cumulative_cash_gross_profit,
        m3_cumulative_product_gross_profit,
        m6_cumulative_cash_gross_profit,
        m6_cumulative_product_gross_profit,
        m9_cumulative_cash_gross_profit,
        m9_cumulative_product_gross_profit,
        m12_cumulative_cash_gross_profit,
        m12_cumulative_product_gross_profit,
        m18_cumulative_cash_gross_profit,
        m18_cumulative_product_gross_profit,
        m24_cumulative_cash_gross_profit,
        m24_cumulative_product_gross_profit,
        m36_cumulative_cash_gross_profit,
        m36_cumulative_product_gross_profit,
        customer_acquisition_cost,
        x_customer_acquisition_cost
        ) AS meta_row_hash,
    $execution_start_time AS meta_create_datetime,
    $execution_start_time AS meta_update_datetime
FROM _customer_lifetime_value_ltd__stg
ORDER BY
    customer_id,
    activation_key;
