SET execution_start_time = CURRENT_TIMESTAMP :: TIMESTAMP_LTZ(3);
SET target_table = 'analytics_base.acquisition_media_spend_daily_agg';
ALTER SESSION SET QUERY_TAG = $target_table;

CREATE OR REPLACE TEMPORARY TABLE _leads AS
SELECT CASE
           WHEN st.store_brand = 'Fabletics' AND st.store_type = 'Retail' THEN 52
           ELSE st.store_id END                                 AS event_store_id,
       -1                                                       AS vip_store_id,
       cast(0 AS BOOLEAN)                                       AS is_retail_vip,
       IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') AS customer_gender,
       dc.is_cross_promo                                        AS is_cross_promo,
       dc.finance_specialty_store                               AS finance_specialty_store,
       l.is_retail_registration                                 AS is_retail_registration,
       IFF(st.store_brand = 'Fabletics' AND dc.is_scrubs_customer = TRUE, TRUE, FALSE) AS is_scrubs_customer,
       IFNULL(l.registration_channel,'unclassified')            AS registration_channel,
       IFF(l.registration_subchannel = '' or l.registration_subchannel is null,'unclassified',l.registration_subchannel) AS registration_subchannel,
       IFNULL(l.how_did_you_hear,'Unknown')                     AS how_did_you_hear,
       IFNULL(l.how_did_you_hear_parent,'Unknown')              AS how_did_you_hear_parent,
       l.registration_local_datetime::DATE                      AS date,
       COUNT(IFF(is_reactivated_lead = TRUE and l.is_secondary_registration=FALSE, l.customer_id, NULL)) AS reactivated_leads,
       COUNT(DISTINCT l.customer_id)                            AS leads,
       COUNT(DISTINCT iff(l.is_secondary_registration= FALSE,l.customer_id,null)) AS primary_leads,
       COUNT(DISTINCT iff(l.is_secondary_registration= TRUE,l.customer_id,null)) AS secondary_leads
FROM edw_prod.data_model_jfb.fact_registration l
         JOIN edw_prod.data_model_jfb.dim_customer dc ON dc.customer_id = l.customer_id
         JOIN edw_prod.data_model_jfb.dim_store st ON st.store_id = l.store_id
WHERE IFNULL(l.is_fake_retail_registration, FALSE) = FALSE
GROUP BY event_store_id,
         vip_store_id,
         is_retail_vip,
         customer_gender,
         is_cross_promo,
         finance_specialty_store,
         is_retail_registration,
         IFF(st.store_brand = 'Fabletics' AND dc.is_scrubs_customer = TRUE, TRUE, FALSE),
         IFNULL(l.registration_channel,'unclassified'),
         IFF(l.registration_subchannel = '' or l.registration_subchannel is null,'unclassified',l.registration_subchannel),
         IFNULL(l.how_did_you_hear,'Unknown'),
         IFNULL(l.how_did_you_hear_parent,'Unknown'),
         l.registration_local_datetime::DATE ;


CREATE OR REPLACE TEMPORARY TABLE _acquisition_media_stg AS
SELECT dc.customer_id,
       IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') AS gender,
       dc.is_cross_promo,
       dc.finance_specialty_store,
       fr.registration_local_datetime,
       fr.is_retail_registration,
       IFF(st.store_brand = 'Fabletics' AND dc.is_scrubs_customer = TRUE, TRUE, FALSE) AS is_scrubs_customer,
       IFNULL(fr.registration_channel,'unclassified')                                  AS registration_channel,
       IFF(fr.registration_subchannel = '' or fr.registration_subchannel is null,'unclassified',fr.registration_subchannel) AS registration_subchannel,
       IFNULL(fr.how_did_you_hear,'Unknown')                                           AS how_did_you_hear,
       IFNULL(fr.how_did_you_hear_parent,'Unknown')                                    AS how_did_you_hear_parent,
       fr.is_reactivated_lead,
       fr.store_id as registration_store_id,
       fa.activation_local_datetime,
       fa.cancellation_local_datetime,
       fa.cancel_type,
       fa.sub_store_id,
       fa.is_retail_vip,
       fa.is_reactivated_vip,
       fa.is_retail_varsity_vip,
       fa.store_id AS activation_store_id
FROM edw_prod.data_model_jfb.fact_activation fa
         JOIN edw_prod.data_model_jfb.fact_registration fr
              ON fa.customer_id = fr.customer_id
                  AND IFNULL(fr.is_secondary_registration, FALSE) = FALSE
                  AND IFNULL(fr.is_fake_retail_registration, FALSE) = FALSE
         JOIN edw_prod.data_model_jfb.dim_customer dc ON dc.customer_id = fa.customer_id
         JOIN edw_prod.data_model_jfb.dim_store st ON st.store_id = fa.sub_store_id;


CREATE OR REPLACE TEMPORARY TABLE _vips_from_leads AS
SELECT sub_store_id                                                              AS event_store_id,
       sub_store_id                                                              AS vip_store_id,
       is_retail_vip                                                             AS is_retail_vip,
       gender                                                                    AS customer_gender,
       is_cross_promo                                                            AS is_cross_promo,
       finance_specialty_store,
       is_retail_registration                                                    AS is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       CAST(registration_local_datetime AS DATE)                                 AS date,
       COUNT(IFF(DATEDIFF(MIN, registration_local_datetime, activation_local_datetime) < 30,
                 customer_id, NULL))                                             AS vip_from_leads_30min,
       COUNT(IFF(DATEDIFF(HOUR, registration_local_datetime, activation_local_datetime) < 2,
                 customer_id, NULL))                                             AS vip_from_leads_2h,
       COUNT(IFF(DATEDIFF(HOUR, registration_local_datetime, activation_local_datetime) < 24,
                 customer_id, NULL))                                             AS vip_from_leads_24h,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MIN, registration_local_datetime, activation_local_datetime) < 30,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_30min,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(HOUR, registration_local_datetime, activation_local_datetime) < 2,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_2h,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(HOUR, registration_local_datetime, activation_local_datetime) < 24,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_24h,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 0,
                 customer_id, NULL))                                             AS vip_from_leads_d1,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 0,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d1,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 1,
                 customer_id, NULL))                                             AS vip_from_leads_d2,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 1,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d2,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 2,
                 customer_id, NULL))                                             AS vip_from_leads_d3,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 2,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d3,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 3,
                 customer_id, NULL))                                             AS vip_from_leads_d4,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 3,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d4,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 4,
                 customer_id, NULL))                                             AS vip_from_leads_d5,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 4,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d5,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 5,
                 customer_id, NULL))                                             AS vip_from_leads_d6,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 5,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d6,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 6,
                 customer_id, NULL))                                             AS vip_from_leads_d7,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 6,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d7,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 7 AND 29,
                 customer_id, NULL))                                             AS vip_from_leads_d8_d30,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 7 AND 29,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_d8_d30,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 0, customer_id,
                 NULL))                                                          AS vip_from_leads_m1,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 0,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m1,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 1, customer_id,
                 NULL))                                                          AS vip_from_leads_m2,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 1,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m2,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 2, customer_id,
                 NULL))                                                          AS vip_from_leads_m3,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 2,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m3,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 3, customer_id,
                 NULL))                                                          AS vip_from_leads_m4,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 3,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m4,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 4, customer_id,
                 NULL))                                                          AS vip_from_leads_m5,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 4,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m5,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 5, customer_id,
                 NULL))                                                          AS vip_from_leads_m6,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 5,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m6,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 6, customer_id,
                 NULL))                                                          AS vip_from_leads_m7,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 6,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m7,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 7, customer_id,
                 NULL))                                                          AS vip_from_leads_m8,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 7,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m8,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 8, customer_id,
                 NULL))                                                          AS vip_from_leads_m9,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 8,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m9,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 9, customer_id,
                 NULL))                                                          AS vip_from_leads_m10,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 9,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m10,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 10, customer_id,
                 NULL))                                                          AS vip_from_leads_m11,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 10,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m11,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 11, customer_id,
                 NULL))                                                          AS vip_from_leads_m12,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 11,
                 customer_id, NULL))                                             AS vip_from_reactivated_leads_m12
FROM _acquisition_media_stg
WHERE activation_store_id = registration_store_id
AND is_reactivated_vip='FALSE'
GROUP BY event_store_id,
         vip_store_id,
         is_retail_vip,
         customer_gender,
         is_cross_promo,
         finance_specialty_store,
         is_retail_registration,
         is_scrubs_customer,
         registration_channel,
         registration_subchannel,
         how_did_you_hear,
         how_did_you_hear_parent,
         CAST(registration_local_datetime AS DATE);


CREATE OR REPLACE TEMPORARY TABLE _vips AS
SELECT sub_store_id                                                              AS event_store_id,
       sub_store_id                                                              AS vip_store_id,
       is_retail_vip                                                             AS is_retail_vip,
       gender                                                                    AS customer_gender,
       is_cross_promo                                                            AS is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       CAST(activation_local_datetime AS DATE)                                   AS date,
       COUNT(*)                                                                  AS new_vips,
       COUNT(IFF(is_reactivated_lead = 'TRUE', customer_id,
                 NULL))                                                          AS vips_from_reactivated_leads,
       COUNT(IFF(is_reactivated_lead = 'TRUE' AND
                 DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 0, customer_id,
                 NULL))                                                          AS vips_from_reactivated_leads_m1,
       COUNT(IFF(is_reactivated_vip = 'TRUE', 1, NULL))                               AS reactivated_vips,
       COUNT(IFF(is_retail_vip = 'TRUE', 1, NULL))                                    AS retail_vips,
       COUNT(IFF(is_retail_varsity_vip = 'TRUE', 1, NULL))                            AS varsity_vips,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 0 AND is_reactivated_vip='FALSE',
                customer_id, NULL))                                              AS new_vips_m1,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 0 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_m1_reactivated_leads,
       COUNT(IFF(is_cross_promo = 'FALSE' AND is_retail_vip = 'FALSE' AND DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 0,
                 customer_id, NULL))                                             AS paid_vips_m1,
       -- fk classifies their cross promo vips as unpaid & not cross promo as paid
       -- fl classifies their retail vips as unpaid & not cross promo as paid
       COUNT(
               IFF(is_cross_promo = 'FALSE' AND is_retail_vip = 'FALSE', customer_id, NULL)) AS paid_vips,  -- new change, FL wanted to include non-retail-vips in paid
       COUNT(
               IFF(is_cross_promo = 'TRUE' OR is_retail_vip = 'TRUE', customer_id, NULL))  AS unpaid_vips, -- new change, FL wanted to include retail vips as unpaid
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 0 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d1,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 0 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d1_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 1 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d2,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 1 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d2_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 2 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d3,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 2 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d3_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 3 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d4,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 3 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d4_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 4 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d5,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 4 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d5_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 5 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d6,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 5 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d6_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 6 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d7,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) = 6 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d7_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 1 AND 6 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d2_d7,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 1 AND 6 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d2_d7_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 0 AND 6 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d1_d7,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 0 AND 6 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d1_d7_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 7 AND 29 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d8_d30,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 7 AND 29 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d8_d30_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 30 AND 88 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d31_d89,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 30 AND 88 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d31_d89_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 7 AND 89 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d8_d90,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) BETWEEN 7 AND 89 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d8_d90_reactivated_leads,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) >= 89 AND is_reactivated_vip='FALSE',
                 customer_id, NULL))                                             AS new_vips_d90plus,
       COUNT(IFF(DATEDIFF(DAY, registration_local_datetime, activation_local_datetime) >= 89 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE',
                 customer_id, NULL))                                             AS new_vips_d90plus_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 1 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m2,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 1 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m2_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 2 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m3,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 2 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m3_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 3 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m4,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 3 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m4_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 4 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m5,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 4 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m5_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 5 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m6,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 5 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m6_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 6 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m7,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 6 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m7_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 7 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m8,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 7 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m8_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 8 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m9,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 8 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m9_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 9 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m10,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 9 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m10_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 10 , customer_id,
                 NULL))                                                             AS new_vips_m11,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 10 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m11_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 11 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m12,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) = 11 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m12_reactivated_leads,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) >= 12 AND is_reactivated_vip='FALSE', customer_id,
                 NULL))                                                             AS new_vips_m13plus,
       COUNT(IFF(DATEDIFF(MONTH, registration_local_datetime, activation_local_datetime) >= 12 AND is_reactivated_vip='FALSE' AND is_reactivated_lead='TRUE', customer_id,
                 NULL))                                                             AS new_vips_m13plus_reactivated_leads
FROM _acquisition_media_stg
GROUP BY event_store_id,
         vip_store_id,
         is_retail_vip,
         customer_gender,
         is_cross_promo,
         finance_specialty_store,
         is_retail_registration,
         is_scrubs_customer,
         registration_channel,
         registration_subchannel,
         how_did_you_hear,
         how_did_you_hear_parent,
         CAST(activation_local_datetime AS DATE);


CREATE OR REPLACE TEMPORARY TABLE _cancels AS
SELECT sub_store_id                              AS event_store_id,
       sub_store_id                              AS vip_store_id,
       is_retail_vip                             AS is_retail_vip,
       gender                                    AS customer_gender,
       is_cross_promo                            AS is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       CAST(cancellation_local_datetime AS DATE) AS date,
       COUNT(*)                                     AS cancels,
       COUNT(IFF(DATEDIFF(MONTH, activation_local_datetime, cancellation_local_datetime) = 0, 1,
                 NULL))                             AS m1_cancels,
       COUNT(IFF(cancel_type = 'Passive', 1,
                 NULL))  as passive_cancel,
       COUNT(IFF(DATEDIFF(DAY, activation_local_datetime, cancellation_local_datetime) = 0, 1,
                 NULL))                             AS d1_cancels,

       COUNT(IFF(DATEDIFF(MONTH, activation_local_datetime, cancellation_local_datetime) = 1, 1,
                 NULL))                             AS m2_cancels,
       COUNT(IFF(DATEDIFF(MONTH, activation_local_datetime, cancellation_local_datetime) = 2, 1,
                 NULL))                             AS m3_cancels,
       COUNT(IFF(DATEDIFF(MONTH, activation_local_datetime, cancellation_local_datetime) between 3 and 11, 1,
                 NULL))                             AS m4_m12_cancels,
       COUNT(IFF(DATEDIFF(MONTH, activation_local_datetime, cancellation_local_datetime) >= 12, 1,
                 NULL))                             AS m13plus_cancels
FROM _acquisition_media_stg
WHERE CAST(cancellation_local_datetime AS DATE) NOT IN ('9999-12-31','1900-01-01')
GROUP BY event_store_id,
         vip_store_id,
         is_retail_vip,
         customer_gender,
         is_cross_promo,
         finance_specialty_store,
         is_retail_registration,
         is_scrubs_customer,
         registration_channel,
         registration_subchannel,
         how_did_you_hear,
         how_did_you_hear_parent,
         CAST(cancellation_local_datetime AS DATE);



CREATE OR REPLACE TEMPORARY TABLE _date AS
SELECT DISTINCT full_date
FROM edw_prod.data_model_jfb.dim_date
WHERE full_date <= CURRENT_TIMESTAMP()
  AND full_date >=
      (SELECT CAST(LEAST(MIN(cancellation_local_datetime), MIN(activation_local_datetime),
                         MIN(registration_local_datetime)) AS DATE)
       FROM _acquisition_media_stg);


CREATE OR REPLACE TEMPORARY TABLE _bop_vips AS
SELECT sub_store_id   AS event_store_id,
       sub_store_id   AS vip_store_id,
       is_retail_vip  AS is_retail_vip,
       gender         AS customer_gender,
       is_cross_promo AS is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       d.full_date       AS date,
       COUNT(*)          AS bop_vips
FROM _date d
         JOIN _acquisition_media_stg stg ON CAST(stg.activation_local_datetime AS DATE) < d.full_date
    AND CAST(stg.cancellation_local_datetime AS DATE) >= d.full_date
GROUP BY event_store_id,
         vip_store_id,
         is_retail_vip,
         customer_gender,
         is_cross_promo,
         finance_specialty_store,
         is_retail_registration,
         is_scrubs_customer,
         registration_channel,
         registration_subchannel,
         how_did_you_hear,
         how_did_you_hear_parent,
         d.full_date;



CREATE OR REPLACE TEMPORARY TABLE _total_spend AS
SELECT IFF(st2.store_id = 41, 26, st2.store_id)                              AS event_store_id,
       CASE
           WHEN st2.store_id = 52 AND LOWER(fmc.channel) = 'physical partnerships' THEN 9999
           ELSE IFF(st2.store_id = 41, 26, st2.store_id) END                 AS vip_store_id,
       IFF(LOWER(fmc.channel) = 'physical partnerships', 1, 0)               AS is_retail_vip,
       IFF(st2.store_brand = 'Fabletics' AND fmc.is_mens_flag = 1, 'M', 'F') AS customer_gender,
       0                                                                     AS is_cross_promo,
       CASE
           WHEN st2.store_full_name = 'Fabletics AU' THEN 'AU'
           WHEN st2.store_full_name = 'JustFab BE' THEN 'BE'
           WHEN st2.store_full_name = 'Fabletics AT' THEN 'AT'
           WHEN st2.store_full_name = 'JustFab AT' THEN 'AT'
           WHEN st2.store_full_name = 'ShoeDazzle CA' THEN 'CA'
           WHEN st2.store_full_name = 'FabKids CA' THEN 'CA'
           WHEN st2.store_full_name = 'JustFab CA' THEN 'CA'
           ELSE 'None'
           END                                                               AS finance_specialty_store,
       0                                                                     AS is_retail_registration,
       fmc.is_scrubs_flag                                                    AS is_scrubs_customer,
       'unclassified'                                                        AS registration_channel,
       'unclassified'                                                        AS registration_subchannel,
       'Unknown'                                                             AS how_did_you_hear,
       'Unknown'                                                             AS how_did_you_hear_parent,
       CAST(media_cost_date AS DATE)                                         AS date,
       SUM(fmc.cost * fmc.spend_date_usd_conv_rate)                          AS media_spend_usd,
       SUM(fmc.cost * fmc.local_store_conv_rate)                             AS media_spend_local
FROM reporting_media_prod.dbo.vw_fact_media_cost fmc
         JOIN edw_prod.data_model_jfb.dim_store st2 ON st2.store_id = fmc.store_id -- will ensure we get no specialty stores
WHERE LOWER(fmc.targeting) NOT IN ('vip retargeting', 'purchase retargeting', 'free alpha')
AND  CAST(fmc.media_cost_date AS DATE) < DATEADD(DAY, 1, current_date())
GROUP BY event_store_id,
         vip_store_id,
         is_retail_vip,
         customer_gender,
         is_cross_promo,
         finance_specialty_store,
         is_retail_registration,
         fmc.is_scrubs_flag,
         'unclassified',
         'unclassified',
         'Unknown',
         'Unknown',
         CAST(media_cost_date AS DATE);


CREATE OR REPLACE TEMPORARY TABLE _scaffold AS
SELECT date,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent
FROM _leads
UNION
SELECT date,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent
FROM _vips_from_leads
UNION
SELECT date,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent
FROM _vips
UNION
SELECT date,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent
FROM _cancels
UNION
SELECT date,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent
FROM _bop_vips
UNION
SELECT date,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent
FROM _total_spend;



------------------------------------------------------------------------
-- consolidate
CREATE OR REPLACE TEMPORARY TABLE _final_output AS
SELECT s.event_store_id,
       s.vip_store_id,
       s.is_retail_vip,
       s.customer_gender,
       s.is_cross_promo,
       s.finance_specialty_store,
       s.is_retail_registration,
       s.is_scrubs_customer,
       s.registration_channel,
       s.registration_subchannel,
       s.how_did_you_hear,
       s.how_did_you_hear_parent,
       s.date,
       COALESCE(l.leads, 0)                             AS leads,
       COALESCE(l.reactivated_leads, 0)                 AS reactivated_leads,
       COALESCE(l.primary_leads, 0)                     AS primary_leads,
       COALESCE(l.secondary_leads, 0)                   AS secondary_leads,
       COALESCE(vl.vip_from_leads_30min, 0)             AS vip_from_leads_30min,
       COALESCE(vl.vip_from_leads_2h, 0)                AS vip_from_leads_2h,
       COALESCE(vl.vip_from_leads_24h, 0)               AS vip_from_leads_24h,
       COALESCE(vl.vip_from_reactivated_leads_30min, 0) AS vip_from_reactivated_leads_30min,
       COALESCE(vl.vip_from_reactivated_leads_2h, 0)    AS vip_from_reactivated_leads_2h,
       COALESCE(vl.vip_from_reactivated_leads_24h, 0)   AS vip_from_reactivated_leads_24h,
       COALESCE(vl.vip_from_leads_d1, 0)                AS vip_from_leads_d1,
       COALESCE(vl.vip_from_reactivated_leads_d1, 0)    AS vip_from_reactivated_leads_d1,
       COALESCE(vl.vip_from_leads_d2, 0)                AS vip_from_leads_d2,
       COALESCE(vl.vip_from_reactivated_leads_d2, 0)    AS vip_from_reactivated_leads_d2,
       COALESCE(vl.vip_from_leads_d3, 0)                AS vip_from_leads_d3,
       COALESCE(vl.vip_from_reactivated_leads_d3, 0)    AS vip_from_reactivated_leads_d3,
       COALESCE(vl.vip_from_leads_d4, 0)                AS vip_from_leads_d4,
       COALESCE(vl.vip_from_reactivated_leads_d4, 0)    AS vip_from_reactivated_leads_d4,
       COALESCE(vl.vip_from_leads_d5, 0)                AS vip_from_leads_d5,
       COALESCE(vl.vip_from_reactivated_leads_d5, 0)    AS vip_from_reactivated_leads_d5,
       COALESCE(vl.vip_from_leads_d6, 0)                AS vip_from_leads_d6,
       COALESCE(vl.vip_from_reactivated_leads_d6, 0)    AS vip_from_reactivated_leads_d6,
       COALESCE(vl.vip_from_leads_d7, 0)                AS vip_from_leads_d7,
       COALESCE(vl.vip_from_reactivated_leads_d7, 0)    AS vip_from_reactivated_leads_d7,
       COALESCE(vl.vip_from_leads_d8_d30, 0)            AS vip_from_leads_d8_d30,
       COALESCE(vl.vip_from_reactivated_leads_d8_d30, 0) AS vip_from_reactivated_leads_d8_d30,
       COALESCE(vl.vip_from_leads_m1, 0)                AS vip_from_leads_m1,
       COALESCE(vl.vip_from_reactivated_leads_m1, 0)    AS vip_from_reactivated_leads_m1,
       COALESCE(vl.vip_from_leads_m2, 0)                AS vip_from_leads_m2,
       COALESCE(vl.vip_from_reactivated_leads_m2, 0)    AS vip_from_reactivated_leads_m2,
       COALESCE(vl.vip_from_leads_m3, 0)                AS vip_from_leads_m3,
       COALESCE(vl.vip_from_reactivated_leads_m3, 0)    AS vip_from_reactivated_leads_m3,
       COALESCE(vl.vip_from_leads_m4, 0)                AS vip_from_leads_m4,
       COALESCE(vl.vip_from_reactivated_leads_m4, 0)    AS vip_from_reactivated_leads_m4,
       COALESCE(vl.vip_from_leads_m5, 0)                AS vip_from_leads_m5,
       COALESCE(vl.vip_from_reactivated_leads_m5, 0)    AS vip_from_reactivated_leads_m5,
       COALESCE(vl.vip_from_leads_m6, 0)                AS vip_from_leads_m6,
       COALESCE(vl.vip_from_reactivated_leads_m6, 0)    AS vip_from_reactivated_leads_m6,
       COALESCE(vl.vip_from_leads_m7, 0)                AS vip_from_leads_m7,
       COALESCE(vl.vip_from_reactivated_leads_m7, 0)    AS vip_from_reactivated_leads_m7,
       COALESCE(vl.vip_from_leads_m8, 0)                AS vip_from_leads_m8,
       COALESCE(vl.vip_from_reactivated_leads_m8, 0)    AS vip_from_reactivated_leads_m8,
       COALESCE(vl.vip_from_leads_m9, 0)                AS vip_from_leads_m9,
       COALESCE(vl.vip_from_reactivated_leads_m9, 0)    AS vip_from_reactivated_leads_m9,
       COALESCE(vl.vip_from_leads_m10, 0)               AS vip_from_leads_m10,
       COALESCE(vl.vip_from_reactivated_leads_m10, 0)    AS vip_from_reactivated_leads_m10,
       COALESCE(vl.vip_from_leads_m11, 0)               AS vip_from_leads_m11,
       COALESCE(vl.vip_from_reactivated_leads_m11, 0)    AS vip_from_reactivated_leads_m11,
       COALESCE(vl.vip_from_leads_m12, 0)               AS vip_from_leads_m12,
       COALESCE(vl.vip_from_reactivated_leads_m12, 0)    AS vip_from_reactivated_leads_m12,
       COALESCE(v.new_vips, 0)                          AS new_vips,
       COALESCE(v.reactivated_vips, 0)                  AS reactivated_vips,
       COALESCE(v.retail_vips, 0)                       AS retail_vips,
       COALESCE(v.varsity_vips, 0)                      AS varsity_vips,
       COALESCE(v.vips_from_reactivated_leads, 0)       AS vips_from_reactivated_leads,
       COALESCE(v.vips_from_reactivated_leads_m1, 0)    AS vips_from_reactivated_leads_m1,
       COALESCE(v.paid_vips, 0)                         AS paid_vips,
       COALESCE(v.unpaid_vips, 0)                       AS unpaid_vips,
       COALESCE(v.new_vips_m1, 0)                       AS new_vips_m1,
       COALESCE(v.new_vips_m1_reactivated_leads, 0)     AS new_vips_m1_reactivated_leads,
       COALESCE(v.paid_vips_m1, 0)                      AS paid_vips_m1,
       COALESCE(v.new_vips_d1, 0)                       AS new_vips_d1,
       COALESCE(v.new_vips_d1_reactivated_leads, 0)     AS new_vips_d1_reactivated_leads,
       COALESCE(v.new_vips_d2, 0)                       AS new_vips_d2,
       COALESCE(v.new_vips_d2_reactivated_leads, 0)     AS new_vips_d2_reactivated_leads,
       COALESCE(v.new_vips_d3, 0)                       AS new_vips_d3,
       COALESCE(v.new_vips_d3_reactivated_leads, 0)     AS new_vips_d3_reactivated_leads,
       COALESCE(v.new_vips_d4, 0)                       AS new_vips_d4,
       COALESCE(v.new_vips_d4_reactivated_leads, 0)     AS new_vips_d4_reactivated_leads,
       COALESCE(v.new_vips_d5, 0)                       AS new_vips_d5,
       COALESCE(v.new_vips_d5_reactivated_leads, 0)     AS new_vips_d5_reactivated_leads,
       COALESCE(v.new_vips_d6, 0)                       AS new_vips_d6,
       COALESCE(v.new_vips_d6_reactivated_leads, 0)     AS new_vips_d6_reactivated_leads,
       COALESCE(v.new_vips_d7, 0)                       AS new_vips_d7,
       COALESCE(v.new_vips_d7_reactivated_leads, 0)     AS new_vips_d7_reactivated_leads,
       COALESCE(v.new_vips_d2_d7, 0)                    AS new_vips_d2_d7,
       COALESCE(v.new_vips_d2_d7_reactivated_leads, 0)  AS new_vips_d2_d7_reactivated_leads,
       COALESCE(v.new_vips_d1_d7, 0)                    AS new_vips_d1_d7,
       COALESCE(v.new_vips_d1_d7_reactivated_leads, 0)  AS new_vips_d1_d7_reactivated_leads,
       COALESCE(v.new_vips_d8_d30, 0)                   AS new_vips_d8_d30,
       COALESCE(v.new_vips_d8_d30_reactivated_leads, 0) AS new_vips_d8_d30_reactivated_leads,
       COALESCE(v.new_vips_d31_d89, 0)                  AS new_vips_d31_d89,
       COALESCE(v.new_vips_d31_d89_reactivated_leads, 0) AS new_vips_d31_d89_reactivated_leads,
       COALESCE(v.new_vips_d8_d90, 0)                   AS new_vips_d8_d90,
       COALESCE(v.new_vips_d8_d90_reactivated_leads, 0) AS new_vips_d8_d90_reactivated_leads,
       COALESCE(v.new_vips_d90plus, 0)                  AS new_vips_d90plus,
       COALESCE(v.new_vips_d90plus_reactivated_leads, 0) AS new_vips_d90plus_reactivated_leads,
       COALESCE(v.new_vips_m2, 0)                       AS new_vips_m2,
       COALESCE(v.new_vips_m2_reactivated_leads, 0)     AS new_vips_m2_reactivated_leads,
       COALESCE(v.new_vips_m3, 0)                       AS new_vips_m3,
       COALESCE(v.new_vips_m3_reactivated_leads, 0)     AS new_vips_m3_reactivated_leads,
       COALESCE(v.new_vips_m4, 0)                       AS new_vips_m4,
       COALESCE(v.new_vips_m4_reactivated_leads, 0)     AS new_vips_m4_reactivated_leads,
       COALESCE(v.new_vips_m5, 0)                       AS new_vips_m5,
       COALESCE(v.new_vips_m5_reactivated_leads, 0)     AS new_vips_m5_reactivated_leads,
       COALESCE(v.new_vips_m6, 0)                       AS new_vips_m6,
       COALESCE(v.new_vips_m6_reactivated_leads, 0)     AS new_vips_m6_reactivated_leads,
       COALESCE(v.new_vips_m7, 0)                       AS new_vips_m7,
       COALESCE(v.new_vips_m7_reactivated_leads, 0)     AS new_vips_m7_reactivated_leads,
       COALESCE(v.new_vips_m8, 0)                       AS new_vips_m8,
       COALESCE(v.new_vips_m8_reactivated_leads, 0)     AS new_vips_m8_reactivated_leads,
       COALESCE(v.new_vips_m9, 0)                       AS new_vips_m9,
       COALESCE(v.new_vips_m9_reactivated_leads, 0)     AS new_vips_m9_reactivated_leads,
       COALESCE(v.new_vips_m10, 0)                      AS new_vips_m10,
       COALESCE(v.new_vips_m10_reactivated_leads, 0)    AS new_vips_m10_reactivated_leads,
       COALESCE(v.new_vips_m11, 0)                      AS new_vips_m11,
       COALESCE(v.new_vips_m11_reactivated_leads, 0)    AS new_vips_m11_reactivated_leads,
       COALESCE(v.new_vips_m12, 0)                      AS new_vips_m12,
       COALESCE(v.new_vips_m12_reactivated_leads, 0)    AS new_vips_m12_reactivated_leads,
       COALESCE(v.new_vips_m13plus, 0)                  AS new_vips_m13plus,
       COALESCE(v.new_vips_m13plus_reactivated_leads, 0) AS new_vips_m13plus_reactivated_leads,
       COALESCE(c.cancels, 0)                           AS cancels,
       COALESCE(c.m1_cancels, 0)                        AS m1_cancels,
       COALESCE(c.passive_cancel, 0)                    AS passive_cancel,
       COALESCE(c.d1_cancels, 0)                        AS d1_cancels,
       COALESCE(c.m2_cancels, 0)                        AS m2_cancels,
       COALESCE(c.m3_cancels, 0)                        AS m3_cancels,
       COALESCE(c.m4_m12_cancels, 0)                    AS m4_m12_cancels,
       COALESCE(c.m13plus_cancels, 0)                   AS m13plus_cancels,
       COALESCE(bop.bop_vips, 0)                        AS bop_vips,
       COALESCE(ts.media_spend_usd, 0)                  AS media_spend,
       COALESCE(ts.media_spend_local, 0)                AS media_spend_local
FROM _scaffold s
         LEFT JOIN _leads l ON l.event_store_id = s.event_store_id
    AND s.vip_store_id = l.vip_store_id
    AND l.is_retail_vip = s.is_retail_vip
    AND l.customer_gender = s.customer_gender
    AND l.is_cross_promo = s.is_cross_promo
    AND l.finance_specialty_store = s.finance_specialty_store
    AND l.is_retail_registration = s.is_retail_registration
    AND l.is_scrubs_customer = s.is_scrubs_customer
    AND l.registration_channel = s.registration_channel
    AND l.registration_subchannel = s.registration_subchannel
    AND l.how_did_you_hear = s.how_did_you_hear
    AND l.how_did_you_hear_parent = s.how_did_you_hear_parent
    AND l.date = s.date
         LEFT JOIN _vips_from_leads vl ON vl.event_store_id = s.event_store_id
    AND s.vip_store_id = vl.vip_store_id
    AND vl.is_retail_vip = s.is_retail_vip
    AND vl.customer_gender = s.customer_gender
    AND vl.is_cross_promo = s.is_cross_promo
    AND vl.finance_specialty_store = s.finance_specialty_store
    AND vl.is_retail_registration = s.is_retail_registration
    AND vl.is_scrubs_customer = s.is_scrubs_customer
    AND vl.registration_channel = s.registration_channel
    AND vl.registration_subchannel = s.registration_subchannel
    AND vl.how_did_you_hear = s.how_did_you_hear
    AND vl.how_did_you_hear_parent = s.how_did_you_hear_parent
    AND vl.date = s.date
         LEFT JOIN _vips v ON v.event_store_id = s.event_store_id
    AND s.vip_store_id = v.vip_store_id
    AND v.is_retail_vip = s.is_retail_vip
    AND v.customer_gender = s.customer_gender
    AND v.is_cross_promo = s.is_cross_promo
    AND v.finance_specialty_store = s.finance_specialty_store
    AND v.is_retail_registration = s.is_retail_registration
    AND v.is_scrubs_customer = s.is_scrubs_customer
    AND v.registration_channel = s.registration_channel
    AND v.registration_subchannel = s.registration_subchannel
    AND v.how_did_you_hear = s.how_did_you_hear
    AND v.how_did_you_hear_parent = s.how_did_you_hear_parent
    AND v.date = s.date
         LEFT JOIN _cancels c ON c.event_store_id = s.event_store_id
    AND s.vip_store_id = c.vip_store_id
    AND c.is_retail_vip = s.is_retail_vip
    AND c.customer_gender = s.customer_gender
    AND c.is_cross_promo = s.is_cross_promo
    AND c.finance_specialty_store = s.finance_specialty_store
    AND c.is_retail_registration = s.is_retail_registration
    AND c.is_scrubs_customer = s.is_scrubs_customer
    AND c.registration_channel = s.registration_channel
    AND c.registration_subchannel = s.registration_subchannel
    AND c.how_did_you_hear = s.how_did_you_hear
    AND c.how_did_you_hear_parent = s.how_did_you_hear_parent
    AND c.date = s.date
         LEFT JOIN _bop_vips bop ON bop.event_store_id = s.event_store_id
    AND s.vip_store_id = bop.vip_store_id
    AND bop.is_retail_vip = s.is_retail_vip
    AND bop.customer_gender = s.customer_gender
    AND bop.is_cross_promo = s.is_cross_promo
    AND bop.finance_specialty_store = s.finance_specialty_store
    AND bop.is_retail_registration = s.is_retail_registration
    AND bop.is_scrubs_customer = s.is_scrubs_customer
    AND bop.registration_channel = s.registration_channel
    AND bop.registration_subchannel = s.registration_subchannel
    AND bop.how_did_you_hear = s.how_did_you_hear
    AND bop.how_did_you_hear_parent = s.how_did_you_hear_parent
    AND bop.date = s.date
         LEFT JOIN _total_spend ts ON ts.event_store_id = s.event_store_id
    AND ts.vip_store_id = s.vip_store_id
    AND ts.is_retail_vip = s.is_retail_vip
    AND ts.customer_gender = s.customer_gender
    AND ts.is_cross_promo = s.is_cross_promo
    AND ts.finance_specialty_store = s.finance_specialty_store
    AND ts.is_retail_registration = s.is_retail_registration
    AND ts.is_scrubs_customer = s.is_scrubs_customer
    AND ts.registration_channel = s.registration_channel
    AND ts.registration_subchannel = s.registration_subchannel
    AND ts.how_did_you_hear = s.how_did_you_hear
    AND ts.how_did_you_hear_parent = s.how_did_you_hear_parent
    AND ts.date = s.date;


------------------------------------------------------------------------

CREATE OR REPLACE TEMPORARY TABLE _combine_currencies AS
SELECT 'placed'               AS date_object,
       date,
       cast('usd' AS VARCHAR) AS currency_object,
       cast('USD' AS VARCHAR) AS currency_type,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       'Activating VIP'       AS membership_order_type_l1,
       'Activating VIP'       AS membership_order_type_l2,
       'Activating VIP'       AS membership_order_type_l3,
       leads,
       reactivated_leads,
       primary_leads,
       secondary_leads,
       vip_from_leads_30min,
       vip_from_leads_2h,
       vip_from_leads_24h,
       vip_from_reactivated_leads_30min,
       vip_from_reactivated_leads_2h,
       vip_from_reactivated_leads_24h,
       vip_from_leads_d1,
       vip_from_reactivated_leads_d1,
       vip_from_leads_d2,
       vip_from_reactivated_leads_d2,
       vip_from_leads_d3,
       vip_from_reactivated_leads_d3,
       vip_from_leads_d4,
       vip_from_reactivated_leads_d4,
       vip_from_leads_d5,
       vip_from_reactivated_leads_d5,
       vip_from_leads_d6,
       vip_from_reactivated_leads_d6,
       vip_from_leads_d7,
       vip_from_reactivated_leads_d7,
       vip_from_leads_d8_d30,
       vip_from_reactivated_leads_d8_d30,
       vip_from_leads_m1,
       vip_from_reactivated_leads_m1,
       vip_from_leads_m2,
       vip_from_reactivated_leads_m2,
       vip_from_leads_m3,
       vip_from_reactivated_leads_m3,
       vip_from_leads_m4,
       vip_from_reactivated_leads_m4,
       vip_from_leads_m5,
       vip_from_reactivated_leads_m5,
       vip_from_leads_m6,
       vip_from_reactivated_leads_m6,
       vip_from_leads_m7,
       vip_from_reactivated_leads_m7,
       vip_from_leads_m8,
       vip_from_reactivated_leads_m8,
       vip_from_leads_m9,
       vip_from_reactivated_leads_m9,
       vip_from_leads_m10,
       vip_from_reactivated_leads_m10,
       vip_from_leads_m11,
       vip_from_reactivated_leads_m11,
       vip_from_leads_m12,
       vip_from_reactivated_leads_m12,
       new_vips,
       reactivated_vips,
       retail_vips,
       varsity_vips,
       vips_from_reactivated_leads,
       vips_from_reactivated_leads_m1,
       paid_vips,
       unpaid_vips,
       new_vips_m1,
       new_vips_m1_reactivated_leads,
       paid_vips_m1,
       new_vips_d1,
       new_vips_d1_reactivated_leads,
       new_vips_d2,
       new_vips_d2_reactivated_leads,
       new_vips_d3,
       new_vips_d3_reactivated_leads,
       new_vips_d4,
       new_vips_d4_reactivated_leads,
       new_vips_d5,
       new_vips_d5_reactivated_leads,
       new_vips_d6,
       new_vips_d6_reactivated_leads,
       new_vips_d7,
       new_vips_d7_reactivated_leads,
       new_vips_d2_d7,
       new_vips_d2_d7_reactivated_leads,
       new_vips_d1_d7,
       new_vips_d1_d7_reactivated_leads,
       new_vips_d8_d30,
       new_vips_d8_d30_reactivated_leads,
       new_vips_d31_d89,
       new_vips_d31_d89_reactivated_leads,
       new_vips_d8_d90,
       new_vips_d8_d90_reactivated_leads,
       new_vips_d90plus,
       new_vips_d90plus_reactivated_leads,
       new_vips_m2,
       new_vips_m2_reactivated_leads,
       new_vips_m3,
       new_vips_m3_reactivated_leads,
       new_vips_m4,
       new_vips_m4_reactivated_leads,
       new_vips_m5,
       new_vips_m5_reactivated_leads,
       new_vips_m6,
       new_vips_m6_reactivated_leads,
       new_vips_m7,
       new_vips_m7_reactivated_leads,
       new_vips_m8,
       new_vips_m8_reactivated_leads,
       new_vips_m9,
       new_vips_m9_reactivated_leads,
       new_vips_m10,
       new_vips_m10_reactivated_leads,
       new_vips_m11,
       new_vips_m11_reactivated_leads,
       new_vips_m12,
       new_vips_m12_reactivated_leads,
       new_vips_m13plus,
       new_vips_m13plus_reactivated_leads,
       cancels,
       m1_cancels,
       passive_cancel,
       d1_cancels,
       m2_cancels,
       m3_cancels,
       m4_m12_cancels,
       m13plus_cancels,
       bop_vips,
       media_spend
FROM _final_output;

INSERT INTO _combine_currencies
SELECT 'placed'           AS date_object,
       date,
       'local'            AS currency_object,
       CASE
           WHEN store_country = 'SE' THEN 'SEK'
           WHEN store_country = 'DK' THEN 'DKK'
           WHEN store_country = 'UK' THEN 'GBP'
           ELSE 'EUR' END AS currency_type,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       'Activating VIP'   AS membership_order_type_l1,
       'Activating VIP'   AS membership_order_type_l2,
       'Activating VIP'   AS membership_order_type_l3,
       leads,
       reactivated_leads,
       primary_leads,
       secondary_leads,
       vip_from_leads_30min,
       vip_from_leads_2h,
       vip_from_leads_24h,
       vip_from_reactivated_leads_30min,
       vip_from_reactivated_leads_2h,
       vip_from_reactivated_leads_24h,
       vip_from_leads_d1,
       vip_from_reactivated_leads_d1,
       vip_from_leads_d2,
       vip_from_reactivated_leads_d2,
       vip_from_leads_d3,
       vip_from_reactivated_leads_d3,
       vip_from_leads_d4,
       vip_from_reactivated_leads_d4,
       vip_from_leads_d5,
       vip_from_reactivated_leads_d5,
       vip_from_leads_d6,
       vip_from_reactivated_leads_d6,
       vip_from_leads_d7,
       vip_from_reactivated_leads_d7,
       vip_from_leads_d8_d30,
       vip_from_reactivated_leads_d8_d30,
       vip_from_leads_m1,
       vip_from_reactivated_leads_m1,
       vip_from_leads_m2,
       vip_from_reactivated_leads_m2,
       vip_from_leads_m3,
       vip_from_reactivated_leads_m3,
       vip_from_leads_m4,
       vip_from_reactivated_leads_m4,
       vip_from_leads_m5,
       vip_from_reactivated_leads_m5,
       vip_from_leads_m6,
       vip_from_reactivated_leads_m6,
       vip_from_leads_m7,
       vip_from_reactivated_leads_m7,
       vip_from_leads_m8,
       vip_from_reactivated_leads_m8,
       vip_from_leads_m9,
       vip_from_reactivated_leads_m9,
       vip_from_leads_m10,
       vip_from_reactivated_leads_m10,
       vip_from_leads_m11,
       vip_from_reactivated_leads_m11,
       vip_from_leads_m12,
       vip_from_reactivated_leads_m12,
       new_vips,
       reactivated_vips,
       retail_vips,
       varsity_vips,
       vips_from_reactivated_leads,
       vips_from_reactivated_leads_m1,
       paid_vips,
       unpaid_vips,
       new_vips_m1,
       new_vips_m1_reactivated_leads,
       paid_vips_m1,
       new_vips_d1,
       new_vips_d1_reactivated_leads,
       new_vips_d2,
       new_vips_d2_reactivated_leads,
       new_vips_d3,
       new_vips_d3_reactivated_leads,
       new_vips_d4,
       new_vips_d4_reactivated_leads,
       new_vips_d5,
       new_vips_d5_reactivated_leads,
       new_vips_d6,
       new_vips_d6_reactivated_leads,
       new_vips_d7,
       new_vips_d7_reactivated_leads,
       new_vips_d2_d7,
       new_vips_d2_d7_reactivated_leads,
       new_vips_d1_d7,
       new_vips_d1_d7_reactivated_leads,
       new_vips_d8_d30,
       new_vips_d8_d30_reactivated_leads,
       new_vips_d31_d89,
       new_vips_d31_d89_reactivated_leads,
       new_vips_d8_d90,
       new_vips_d8_d90_reactivated_leads,
       new_vips_d90plus,
       new_vips_d90plus_reactivated_leads,
       new_vips_m2,
       new_vips_m2_reactivated_leads,
       new_vips_m3,
       new_vips_m3_reactivated_leads,
       new_vips_m4,
       new_vips_m4_reactivated_leads,
       new_vips_m5,
       new_vips_m5_reactivated_leads,
       new_vips_m6,
       new_vips_m6_reactivated_leads,
       new_vips_m7,
       new_vips_m7_reactivated_leads,
       new_vips_m8,
       new_vips_m8_reactivated_leads,
       new_vips_m9,
       new_vips_m9_reactivated_leads,
       new_vips_m10,
       new_vips_m10_reactivated_leads,
       new_vips_m11,
       new_vips_m11_reactivated_leads,
       new_vips_m12,
       new_vips_m12_reactivated_leads,
       new_vips_m13plus,
       new_vips_m13plus_reactivated_leads,
       cancels,
       m1_cancels,
       passive_cancel,
       d1_cancels,
       m2_cancels,
       m3_cancels,
       m4_m12_cancels,
       m13plus_cancels,
       bop_vips,
       media_spend
FROM _final_output fo
         JOIN edw_prod.data_model_jfb.dim_store st ON st.store_id = fo.event_store_id
WHERE st.store_region = 'EU';

-- add in currencies for hyperion
INSERT INTO _combine_currencies
SELECT 'placed'         AS date_object,
       date,
       'hyperion'       AS currency_object,
       CASE WHEN st.store_country IN ('SE', 'DK') THEN 'GBP'
           WHEN st.store_country = 'UK' THEN 'EUR' END AS currency_type,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       'Activating VIP' AS membership_order_type_l1,
       'Activating VIP' AS membership_order_type_l2,
       'Activating VIP' AS membership_order_type_l3,
       leads,
       reactivated_leads,
       primary_leads,
       secondary_leads,
       vip_from_leads_30min,
       vip_from_leads_2h,
       vip_from_leads_24h,
       vip_from_reactivated_leads_30min,
       vip_from_reactivated_leads_2h,
       vip_from_reactivated_leads_24h,
       vip_from_leads_d1,
       vip_from_reactivated_leads_d1,
       vip_from_leads_d2,
       vip_from_reactivated_leads_d2,
       vip_from_leads_d3,
       vip_from_reactivated_leads_d3,
       vip_from_leads_d4,
       vip_from_reactivated_leads_d4,
       vip_from_leads_d5,
       vip_from_reactivated_leads_d5,
       vip_from_leads_d6,
       vip_from_reactivated_leads_d6,
       vip_from_leads_d7,
       vip_from_reactivated_leads_d7,
       vip_from_leads_d8_d30,
       vip_from_reactivated_leads_d8_d30,
       vip_from_leads_m1,
       vip_from_reactivated_leads_m1,
       vip_from_leads_m2,
       vip_from_reactivated_leads_m2,
       vip_from_leads_m3,
       vip_from_reactivated_leads_m3,
       vip_from_leads_m4,
       vip_from_reactivated_leads_m4,
       vip_from_leads_m5,
       vip_from_reactivated_leads_m5,
       vip_from_leads_m6,
       vip_from_reactivated_leads_m6,
       vip_from_leads_m7,
       vip_from_reactivated_leads_m7,
       vip_from_leads_m8,
       vip_from_reactivated_leads_m8,
       vip_from_leads_m9,
       vip_from_reactivated_leads_m9,
       vip_from_leads_m10,
       vip_from_reactivated_leads_m10,
       vip_from_leads_m11,
       vip_from_reactivated_leads_m11,
       vip_from_leads_m12,
       vip_from_reactivated_leads_m12,
       new_vips,
       reactivated_vips,
       retail_vips,
       varsity_vips,
       vips_from_reactivated_leads,
       vips_from_reactivated_leads_m1,
       paid_vips,
       unpaid_vips,
       new_vips_m1,
       new_vips_m1_reactivated_leads,
       paid_vips_m1,
       new_vips_d1,
       new_vips_d1_reactivated_leads,
       new_vips_d2,
       new_vips_d2_reactivated_leads,
       new_vips_d3,
       new_vips_d3_reactivated_leads,
       new_vips_d4,
       new_vips_d4_reactivated_leads,
       new_vips_d5,
       new_vips_d5_reactivated_leads,
       new_vips_d6,
       new_vips_d6_reactivated_leads,
       new_vips_d7,
       new_vips_d7_reactivated_leads,
       new_vips_d2_d7,
       new_vips_d2_d7_reactivated_leads,
       new_vips_d1_d7,
       new_vips_d1_d7_reactivated_leads,
       new_vips_d8_d30,
       new_vips_d8_d30_reactivated_leads,
       new_vips_d31_d89,
       new_vips_d31_d89_reactivated_leads,
       new_vips_d8_d90,
       new_vips_d8_d90_reactivated_leads,
       new_vips_d90plus,
       new_vips_d90plus_reactivated_leads,
       new_vips_m2,
       new_vips_m2_reactivated_leads,
       new_vips_m3,
       new_vips_m3_reactivated_leads,
       new_vips_m4,
       new_vips_m4_reactivated_leads,
       new_vips_m5,
       new_vips_m5_reactivated_leads,
       new_vips_m6,
       new_vips_m6_reactivated_leads,
       new_vips_m7,
       new_vips_m7_reactivated_leads,
       new_vips_m8,
       new_vips_m8_reactivated_leads,
       new_vips_m9,
       new_vips_m9_reactivated_leads,
       new_vips_m10,
       new_vips_m10_reactivated_leads,
       new_vips_m11,
       new_vips_m11_reactivated_leads,
       new_vips_m12,
       new_vips_m12_reactivated_leads,
       new_vips_m13plus,
       new_vips_m13plus_reactivated_leads,
       cancels,
       m1_cancels,
       passive_cancel,
       d1_cancels,
       m2_cancels,
       m3_cancels,
       m4_m12_cancels,
       m13plus_cancels,
       bop_vips,
       0                AS media_spend
FROM _final_output fo
         JOIN edw_prod.data_model_jfb.dim_store st ON st.store_id = fo.event_store_id
WHERE (st.store_country IN ('SE', 'DK')
  AND store_brand IN ('Fabletics', 'JustFab'))
OR (st.store_brand = 'Savage X'
  AND store_country = 'UK');

BEGIN TRANSACTION;

TRUNCATE TABLE edw_prod.analytics_base.acquisition_media_spend_daily_agg;

INSERT INTO edw_prod.analytics_base.acquisition_media_spend_daily_agg
(date_object,
 date,
 currency_object,
 currency_type,
 event_store_id,
 vip_store_id,
 is_retail_vip,
 customer_gender,
 is_cross_promo,
 finance_specialty_store,
 is_retail_registration,
 is_scrubs_customer,
 registration_channel,
 registration_subchannel,
 how_did_you_hear,
 how_did_you_hear_parent,
 membership_order_type_l1,
 membership_order_type_l2,
 membership_order_type_l3,
 leads,
 reactivated_leads,
 primary_leads,
 secondary_leads,
 vip_from_leads_30min,
 vip_from_leads_2h,
 vip_from_leads_24h,
 vip_from_reactivated_leads_30min,
 vip_from_reactivated_leads_2h,
 vip_from_reactivated_leads_24h,
 vip_from_leads_d1,
 vip_from_reactivated_leads_d1,
 vip_from_leads_d2,
 vip_from_reactivated_leads_d2,
 vip_from_leads_d3,
 vip_from_reactivated_leads_d3,
 vip_from_leads_d4,
 vip_from_reactivated_leads_d4,
 vip_from_leads_d5,
 vip_from_reactivated_leads_d5,
 vip_from_leads_d6,
 vip_from_reactivated_leads_d6,
 vip_from_leads_d7,
 vip_from_reactivated_leads_d7,
 vip_from_leads_d8_d30,
 vip_from_reactivated_leads_d8_d30,
 vip_from_leads_m1,
 vip_from_reactivated_leads_m1,
 vip_from_leads_m2,
 vip_from_reactivated_leads_m2,
 vip_from_leads_m3,
 vip_from_reactivated_leads_m3,
 vip_from_leads_m4,
 vip_from_reactivated_leads_m4,
 vip_from_leads_m5,
 vip_from_reactivated_leads_m5,
 vip_from_leads_m6,
 vip_from_reactivated_leads_m6,
 vip_from_leads_m7,
 vip_from_reactivated_leads_m7,
 vip_from_leads_m8,
 vip_from_reactivated_leads_m8,
 vip_from_leads_m9,
 vip_from_reactivated_leads_m9,
 vip_from_leads_m10,
 vip_from_reactivated_leads_m10,
 vip_from_leads_m11,
 vip_from_reactivated_leads_m11,
 vip_from_leads_m12,
 vip_from_reactivated_leads_m12,
 new_vips,
 reactivated_vips,
 retail_vips,
 varsity_vips,
 vips_from_reactivated_leads,
 vips_from_reactivated_leads_m1,
 paid_vips,
 unpaid_vips,
 new_vips_m1,
 new_vips_m1_reactivated_leads,
 paid_vips_m1,
 new_vips_d1,
 new_vips_d1_reactivated_leads,
 new_vips_d2,
 new_vips_d2_reactivated_leads,
 new_vips_d3,
 new_vips_d3_reactivated_leads,
 new_vips_d4,
 new_vips_d4_reactivated_leads,
 new_vips_d5,
 new_vips_d5_reactivated_leads,
 new_vips_d6,
 new_vips_d6_reactivated_leads,
 new_vips_d7,
 new_vips_d7_reactivated_leads,
 new_vips_d2_d7,
 new_vips_d2_d7_reactivated_leads,
 new_vips_d1_d7,
 new_vips_d1_d7_reactivated_leads,
 new_vips_d8_d30,
 new_vips_d8_d30_reactivated_leads,
 new_vips_d31_d89,
 new_vips_d31_d89_reactivated_leads,
 new_vips_d8_d90,
 new_vips_d8_d90_reactivated_leads,
 new_vips_d90plus,
 new_vips_d90plus_reactivated_leads,
 new_vips_m2,
 new_vips_m2_reactivated_leads,
 new_vips_m3,
 new_vips_m3_reactivated_leads,
 new_vips_m4,
 new_vips_m4_reactivated_leads,
 new_vips_m5,
 new_vips_m5_reactivated_leads,
 new_vips_m6,
 new_vips_m6_reactivated_leads,
 new_vips_m7,
 new_vips_m7_reactivated_leads,
 new_vips_m8,
 new_vips_m8_reactivated_leads,
 new_vips_m9,
 new_vips_m9_reactivated_leads,
 new_vips_m10,
 new_vips_m10_reactivated_leads,
 new_vips_m11,
 new_vips_m11_reactivated_leads,
 new_vips_m12,
 new_vips_m12_reactivated_leads,
 new_vips_m13plus,
 new_vips_m13plus_reactivated_leads,
 cancels,
 m1_cancels,
 passive_cancel,
 d1_cancels,
 m2_cancels,
 m3_cancels,
 m4_m12_cancels,
 m13plus_cancels,
 bop_vips,
 media_spend,
 meta_create_datetime,
 meta_update_datetime)
SELECT date_object,
       date,
       currency_object,
       currency_type,
       event_store_id,
       vip_store_id,
       is_retail_vip,
       customer_gender,
       is_cross_promo,
       finance_specialty_store,
       is_retail_registration,
       is_scrubs_customer,
       registration_channel,
       registration_subchannel,
       how_did_you_hear,
       how_did_you_hear_parent,
       membership_order_type_l1,
       membership_order_type_l2,
       membership_order_type_l3,
       leads,
       reactivated_leads,
       primary_leads,
       secondary_leads,
       vip_from_leads_30min,
       vip_from_leads_2h,
       vip_from_leads_24h,
       vip_from_reactivated_leads_30min,
       vip_from_reactivated_leads_2h,
       vip_from_reactivated_leads_24h,
       vip_from_leads_d1,
       vip_from_reactivated_leads_d1,
       vip_from_leads_d2,
       vip_from_reactivated_leads_d2,
       vip_from_leads_d3,
       vip_from_reactivated_leads_d3,
       vip_from_leads_d4,
       vip_from_reactivated_leads_d4,
       vip_from_leads_d5,
       vip_from_reactivated_leads_d5,
       vip_from_leads_d6,
       vip_from_reactivated_leads_d6,
       vip_from_leads_d7,
       vip_from_reactivated_leads_d7,
       vip_from_leads_d8_d30,
       vip_from_reactivated_leads_d8_d30,
       vip_from_leads_m1,
       vip_from_reactivated_leads_m1,
       vip_from_leads_m2,
       vip_from_reactivated_leads_m2,
       vip_from_leads_m3,
       vip_from_reactivated_leads_m3,
       vip_from_leads_m4,
       vip_from_reactivated_leads_m4,
       vip_from_leads_m5,
       vip_from_reactivated_leads_m5,
       vip_from_leads_m6,
       vip_from_reactivated_leads_m6,
       vip_from_leads_m7,
       vip_from_reactivated_leads_m7,
       vip_from_leads_m8,
       vip_from_reactivated_leads_m8,
       vip_from_leads_m9,
       vip_from_reactivated_leads_m9,
       vip_from_leads_m10,
       vip_from_reactivated_leads_m10,
       vip_from_leads_m11,
       vip_from_reactivated_leads_m11,
       vip_from_leads_m12,
       vip_from_reactivated_leads_m12,
       new_vips,
       reactivated_vips,
       retail_vips,
       varsity_vips,
       vips_from_reactivated_leads,
       vips_from_reactivated_leads_m1,
       paid_vips,
       unpaid_vips,
       new_vips_m1,
       new_vips_m1_reactivated_leads,
       paid_vips_m1,
       new_vips_d1,
       new_vips_d1_reactivated_leads,
       new_vips_d2,
       new_vips_d2_reactivated_leads,
       new_vips_d3,
       new_vips_d3_reactivated_leads,
       new_vips_d4,
       new_vips_d4_reactivated_leads,
       new_vips_d5,
       new_vips_d5_reactivated_leads,
       new_vips_d6,
       new_vips_d6_reactivated_leads,
       new_vips_d7,
       new_vips_d7_reactivated_leads,
       new_vips_d2_d7,
       new_vips_d2_d7_reactivated_leads,
       new_vips_d1_d7,
       new_vips_d1_d7_reactivated_leads,
       new_vips_d8_d30,
       new_vips_d8_d30_reactivated_leads,
       new_vips_d31_d89,
       new_vips_d31_d89_reactivated_leads,
       new_vips_d8_d90,
       new_vips_d8_d90_reactivated_leads,
       new_vips_d90plus,
       new_vips_d90plus_reactivated_leads,
       new_vips_m2,
       new_vips_m2_reactivated_leads,
       new_vips_m3,
       new_vips_m3_reactivated_leads,
       new_vips_m4,
       new_vips_m4_reactivated_leads,
       new_vips_m5,
       new_vips_m5_reactivated_leads,
       new_vips_m6,
       new_vips_m6_reactivated_leads,
       new_vips_m7,
       new_vips_m7_reactivated_leads,
       new_vips_m8,
       new_vips_m8_reactivated_leads,
       new_vips_m9,
       new_vips_m9_reactivated_leads,
       new_vips_m10,
       new_vips_m10_reactivated_leads,
       new_vips_m11,
       new_vips_m11_reactivated_leads,
       new_vips_m12,
       new_vips_m12_reactivated_leads,
       new_vips_m13plus,
       new_vips_m13plus_reactivated_leads,
       cancels,
       m1_cancels,
       passive_cancel,
       d1_cancels,
       m2_cancels,
       m3_cancels,
       m4_m12_cancels,
       m13plus_cancels,
       bop_vips,
       media_spend,
       $execution_start_time AS meta_create_datetime,
       $execution_start_time AS meta_update_datetime
FROM _combine_currencies
ORDER BY date;

COMMIT;
