SET execution_start_time = CURRENT_TIMESTAMP::TIMESTAMP_LTZ(3);

CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_currency AS
SELECT DISTINCT fa.bu,
                c.local_currency,
                c.target_currency,
                c.budgeted_fx_rate,
                c.effective_date_from,
                c.effective_date_to
FROM reference.finance_bu_mapping fa
         JOIN reference.finance_currency_conversion c
              ON c.local_currency = fa.local_currency;

-- avg budget rates for USDCurrFX
CREATE OR REPLACE TEMPORARY TABLE _avg_budget_rates AS
SELECT src_currency,
       dest_currency,
       DATE_TRUNC(MONTH, rate_date_pst) AS budget_month,
       AVG(exchange_rate)               AS avg_exchange_rate
FROM reference.currency_exchange_rate_by_date
WHERE dest_currency = 'USD'
  AND DATE_TRUNC(MONTH, rate_date_pst) < DATE_TRUNC(MONTH, CURRENT_DATE)
GROUP BY src_currency, dest_currency, DATE_TRUNC(MONTH, rate_date_pst);


SET max_avg_date = (SELECT max(budget_month)
                    FROM _avg_budget_rates);

-- latest available version of budgets and forecasts
CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_base AS
SELECT *
FROM (
         SELECT *,
                RANK() OVER (PARTITION BY bu, financial_date, version ORDER BY version_date DESC ) AS rn
         FROM reference.finance_monthly_budget_forecast_actual
         WHERE version ILIKE '%budget%'
            OR version ILIKE '%forecast%'
            OR version ='CapRaise') AS a
WHERE rn = 1;


-- datasets for region level BUs
CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_region_base AS
SELECT b.*,
       IFNULL(f.store_brand, '')         AS store_brand,
       IFNULL(f.region_type, '')         AS region_type,
       IFNULL(f.region_type_mapping, '') AS store_region
FROM _budget_forecast_base b
         JOIN reference.finance_bu_mapping f
              ON b.bu = f.bu AND
                 b.financial_date BETWEEN f.start_date AND f.end_date;


-- raw data in reference.finance_monthly_budget_forecast_actual is USD
-- USDBTFX = the budgeted rates in USD as is with no conversion
CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_region_usdbtfx AS
SELECT version,
       version_date,
       financial_date     AS financial_date,
       bu,
       ''        AS hyperion_store_id,
       store_brand,
       region_type,
       store_region,
       FALSE     AS is_retail_revenue,
       'USDBTFX' AS currency_type,
       'USD'     AS currency,
       1.000000  AS budgeted_fx_rate,
       membership_credits_charged_count,
       membership_credits_redeemed_count,
       membership_credits_cancelled_count,
       first_msrp_revenue,
       first_discounts,
       repeat_msrp_revenue,
       repeat_discounts,
       leads,
       gross_cash_revenue,
       cash_refunds,
       chargebacks,
       net_cash_revenue_total,
       refunds_and_chargebacks_as_percent_of_gross_cash,
       cash_gross_margin,
       cash_gross_margin_percent_total,
       media_spend,
       cash_contribution_after_media,
       cpl,
       vip_cpa,
       m1_lead_to_vip,
       m1_vips,
       aged_lead_conversions,
       total_new_vips,
       cancels,
       net_change_in_vips,
       ending_vips,
       vip_growth_percent,
       activating_gaap_gross_revenue,
       activating_gaap_net_revenue,
       activating_order_count,
       activating_aov_incl_shipping_rev,
       activating_units_per_transaction,
       activating_discount_percent,
       activating_gross_margin_$,
       activating_gross_margin_percent,
       repeat_gaap_gross_revenue,
       repeat_gaap_net_revenue,
       repeat_order_count,
       repeat_aov_incl_shipping_rev,
       repeat_units_per_transaction,
       repeat_discount_percent,
       repeat_gaap_gross_margin_$,
       repeat_gaap_gross_margin_percent,
       repeat_net_unredeemed_credit_billings,
       repeat_refund_credits,
       repeat_other_ad_rev_div_adaptive_adj,
       repeat_net_cash_revenue,
       repeat_cash_gross_margin,
       repeat_cash_gross_margin_percent,
       membership_credits_charged,
       membership_credits_redeemed,
       membership_credits_refunded_plus_chargebacks,
       net_unredeemed_credit_billings,
       net_unredeemed_credit_billings_as_percent_of_net_cash_revenue,
       refunded_as_credit,
       refund_credit_redeemed,
       net_unredeemed_refund_credit,
       deferred_revenue,
       bom_vips,
       credit_billed_percent,
       credit_redeemed_percent,
       credit_canceled_percent,
       total_units_shipped,
       repeat_cash_purchasers,
       cash_purchase_rate,
       o_div_vip,
       ebitda_minus_cash,
       repeatplusbizdev,
       activating_units,
       repeat_units,
       repeat_product_revenue_incl_shipping,
       product_cost_calc,
       inventory_writedown,
       total_cogs_minus_cash,
       merchant_fees,
       gms_variable,
       fc_variable,
       freight_revenue,
       freight_out_cost,
       outbound_shipping_supplies,
       returns_shipping_cost,
       product_cost_markdown,
       repeat_shipped_order_cash_collected,
       acquisition_margin_$,
       acquisition_margin_percent,
       acquisition_margin_$__div__order,
       product_cost_cust_returns_calc,
       reship_exch_orders_shipped,
       reship_exch_units_shipped,
       cash_net_revenue,
       activating_product_gross_revenue,
       repeat_product_gross_revenue,
       cash_gross_margin_percent,
       repeat_units_shipped,
       repeat_orders_shipped,
       advertising_expenses,
       merchant_fee,
       selling_expenses,
       marketing_expenses,
       direct_general_and_administrative,
       total_opex,
       product_revenue,
       product_gross_margin,
       cash_gross_profit,
       retail_redemption_revenue,
       global_finance_organization,
       global_ops_office_admin_and_facilities,
       tfg_administration,
       global_people_team,
       legal,
       executive,
       non_allocable_corporate,
       eu_media_buying,
       eu_creative_and_marketing,
       total_backoffice_step1,
       net_revenue_cash,
       selling_expense,
       global_member_services_fixed,
       fulfillment_centers_fixed
FROM _budget_forecast_region_base;

-- Local = take budget targets in USD convert back to Local using the Budgeted FX Rates
CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_region_local AS
SELECT version,
       version_date,
       financial_date                                                                 AS financial_date,
       b.bu,
       ''                                                                    AS hyperion_store_id,
       store_brand,
       region_type,
       store_region,
       FALSE                                                                 AS is_retail_revenue,
       'Local'                                                               AS currency_type,
       c.local_currency                                                      AS currency,
       1.0000 / c.budgeted_fx_rate                                           AS budgeted_fx_rate,
       membership_credits_charged_count                                      AS membership_credits_charged_count,
       membership_credits_redeemed_count                                     AS membership_credits_redeemed_count,
       membership_credits_cancelled_count                                    AS membership_credits_cancelled_count,
       c.budgeted_fx_rate * first_msrp_revenue / c.budgeted_fx_rate          AS first_msrp_revenue,
       first_discounts / c.budgeted_fx_rate                                  AS first_discounts,
       repeat_msrp_revenue / c.budgeted_fx_rate                              AS repeat_msrp_revenue,
       repeat_discounts / c.budgeted_fx_rate                                 AS repeat_discounts,
       leads                                                                 AS leads,
       gross_cash_revenue / c.budgeted_fx_rate                               AS gross_cash_revenue,
       cash_refunds / c.budgeted_fx_rate                                     AS cash_refunds,
       chargebacks / c.budgeted_fx_rate                                      AS chargebacks,
       net_cash_revenue_total / c.budgeted_fx_rate                           AS net_cash_revenue_total,
       refunds_and_chargebacks_as_percent_of_gross_cash / c.budgeted_fx_rate AS refunds_and_chargebacks_as_percent_of_gross_cash,
       cash_gross_margin / c.budgeted_fx_rate                                AS cash_gross_margin,
       cash_gross_margin_percent_total                                       AS cash_gross_margin_percent_total,
       media_spend / c.budgeted_fx_rate                                      AS media_spend,
       cash_contribution_after_media / c.budgeted_fx_rate                    AS cash_contribution_after_media,
       cpl / c.budgeted_fx_rate                                              AS cpl,
       vip_cpa / c.budgeted_fx_rate                                          AS vip_cpa,
       m1_lead_to_vip                                                        AS m1_lead_to_vip,
       m1_vips                                                               AS m1_vips,
       aged_lead_conversions                                                 AS aged_lead_conversions,
       total_new_vips                                                        AS total_new_vips,
       cancels                                                               AS cancels,
       net_change_in_vips                                                    AS net_change_in_vips,
       ending_vips                                                           AS ending_vips,
       vip_growth_percent                                                    AS vip_growth_percent,
       activating_gaap_gross_revenue / c.budgeted_fx_rate                    AS activating_gaap_gross_revenue,
       activating_gaap_net_revenue / c.budgeted_fx_rate                      AS activating_gaap_net_revenue,
       activating_order_count                                                AS activating_order_count,
       activating_aov_incl_shipping_rev                                      AS activating_aov_incl_shipping_rev,
       activating_units_per_transaction                                      AS activating_units_per_transaction,
       activating_discount_percent                                           AS activating_discount_percent,
       activating_gross_margin_$ / c.budgeted_fx_rate                        AS activating_gross_margin_$,
       activating_gross_margin_percent                                       AS activating_gross_margin_percent,
       repeat_gaap_gross_revenue / c.budgeted_fx_rate                        AS repeat_gaap_gross_revenue,
       repeat_gaap_net_revenue / c.budgeted_fx_rate                          AS repeat_gaap_net_revenue,
       repeat_order_count                                                    AS repeat_order_count,
       repeat_aov_incl_shipping_rev / c.budgeted_fx_rate                     AS repeat_aov_incl_shipping_rev,
       repeat_units_per_transaction                                          AS repeat_units_per_transaction,
       repeat_discount_percent                                               AS repeat_discount_percent,
       repeat_gaap_gross_margin_$ / c.budgeted_fx_rate                       AS repeat_gaap_gross_margin_$,
       repeat_gaap_gross_margin_percent                                      AS repeat_gaap_gross_margin_percent,
       repeat_net_unredeemed_credit_billings / c.budgeted_fx_rate            AS repeat_net_unredeemed_credit_billings,
       repeat_refund_credits / c.budgeted_fx_rate                            AS repeat_refund_credits,
       repeat_other_ad_rev_div_adaptive_adj                                  AS repeat_other_ad_rev_div_adaptive_adj,
       repeat_net_cash_revenue / c.budgeted_fx_rate                          AS repeat_net_cash_revenue,
       repeat_cash_gross_margin                                              AS repeat_cash_gross_margin,
       repeat_cash_gross_margin_percent                                      AS repeat_cash_gross_margin_percent,
       membership_credits_charged / c.budgeted_fx_rate                       AS membership_credits_charged,
       membership_credits_redeemed / c.budgeted_fx_rate                      AS membership_credits_redeemed,
       membership_credits_refunded_plus_chargebacks / c.budgeted_fx_rate     AS membership_credits_refunded_plus_chargebacks,
       net_unredeemed_credit_billings / c.budgeted_fx_rate                   AS net_unredeemed_credit_billings,
       net_unredeemed_credit_billings_as_percent_of_net_cash_revenue /
       c.budgeted_fx_rate                                                    AS net_unredeemed_credit_billings_as_percent_of_net_cash_revenue,
       refunded_as_credit / c.budgeted_fx_rate                               AS refunded_as_credit,
       refund_credit_redeemed / c.budgeted_fx_rate                           AS refund_credit_redeemed,
       net_unredeemed_refund_credit / c.budgeted_fx_rate                     AS net_unredeemed_refund_credit,
       deferred_revenue / c.budgeted_fx_rate                                 AS deferred_revenue,
       bom_vips                                                              AS bom_vips,
       credit_billed_percent                                                 AS credit_billed_percent,
       credit_redeemed_percent                                               AS credit_redeemed_percent,
       credit_canceled_percent                                               AS credit_canceled_percent,
       total_units_shipped                                                   AS total_units_shipped,
       repeat_cash_purchasers                                                AS repeat_cash_purchasers,
       cash_purchase_rate                                                    AS cash_purchase_rate,
       o_div_vip                                                             AS o_div_vip,
       ebitda_minus_cash / c.budgeted_fx_rate                                AS ebitda_minus_cash,
       repeatplusbizdev / c.budgeted_fx_rate                                 AS repeatplusbizdev,
       activating_units                                                      AS activating_units,
       repeat_units                                                          AS repeat_units,
       repeat_product_revenue_incl_shipping / c.budgeted_fx_rate             AS repeat_product_revenue_incl_shipping,
       product_cost_calc / c.budgeted_fx_rate                                AS product_cost_calc,
       inventory_writedown / c.budgeted_fx_rate                              AS inventory_writedown,
       total_cogs_minus_cash / c.budgeted_fx_rate                            AS total_cogs_minus_cash,
       merchant_fees / c.budgeted_fx_rate                                    AS merchant_fees,
       gms_variable / c.budgeted_fx_rate                                     AS gms_variable,
       fc_variable / c.budgeted_fx_rate                                      AS fc_variable,
       freight_revenue / c.budgeted_fx_rate                                  AS freight_revenue,
       freight_out_cost / c.budgeted_fx_rate                                 AS freight_out_cost,
       outbound_shipping_supplies / c.budgeted_fx_rate                       AS outbound_shipping_supplies,
       returns_shipping_cost / c.budgeted_fx_rate                            AS returns_shipping_cost,
       product_cost_markdown / c.budgeted_fx_rate                            AS product_cost_markdown,
       repeat_shipped_order_cash_collected / c.budgeted_fx_rate              AS repeat_shipped_order_cash_collected,
       acquisition_margin_$ / c.budgeted_fx_rate                             AS acquisition_margin_$,
       acquisition_margin_percent                                            AS acquisition_margin_percent,
       acquisition_margin_$__div__order                                      AS acquisition_margin_$__div__order,
       product_cost_cust_returns_calc / c.budgeted_fx_rate                   AS product_cost_cust_returns_calc,
       reship_exch_orders_shipped                                            AS reship_exch_orders_shipped,
       reship_exch_units_shipped                                             AS reship_exch_units_shipped,
       cash_net_revenue / c.budgeted_fx_rate                                 AS cash_net_revenue,
       activating_product_gross_revenue / c.budgeted_fx_rate                 AS activating_product_gross_revenue,
       repeat_product_gross_revenue / c.budgeted_fx_rate                     AS repeat_product_gross_revenue,
       cash_gross_margin_percent                                             AS cash_gross_margin_percent,
       repeat_units_shipped                                                  AS repeat_units_shipped,
       repeat_orders_shipped                                                 AS repeat_orders_shipped,
       advertising_expenses / c.budgeted_fx_rate                             AS advertising_expenses,
       merchant_fee / c.budgeted_fx_rate                                     AS merchant_fee,
       selling_expenses / c.budgeted_fx_rate                                 AS selling_expenses,
       marketing_expenses / c.budgeted_fx_rate                               AS marketing_expenses,
       direct_general_and_administrative / c.budgeted_fx_rate                AS direct_general_and_administrative,
       total_opex / c.budgeted_fx_rate                                       AS total_opex,
       product_revenue / c.budgeted_fx_rate                                  AS product_revenue,
       product_gross_margin / c.budgeted_fx_rate                             AS product_gross_margin,
       cash_gross_profit / c.budgeted_fx_rate                                AS cash_gross_profit,
       retail_redemption_revenue / c.budgeted_fx_rate                        AS retail_redemption_revenue,
       global_finance_organization / c.budgeted_fx_rate                      AS global_finance_organization,
       global_ops_office_admin_and_facilities / c.budgeted_fx_rate           AS global_ops_office_admin_and_facilities,
       tfg_administration / c.budgeted_fx_rate                               AS tfg_administration,
       global_people_team / c.budgeted_fx_rate                               AS global_people_team,
       legal / c.budgeted_fx_rate                                            AS legal,
       executive / c.budgeted_fx_rate                                        AS executive,
       non_allocable_corporate / c.budgeted_fx_rate                          AS non_allocable_corporate,
       eu_media_buying / c.budgeted_fx_rate                                  AS eu_media_buying,
       eu_creative_and_marketing / c.budgeted_fx_rate                        AS eu_creative_and_marketing,
       total_backoffice_step1 / c.budgeted_fx_rate                           AS total_backoffice_step1,
       net_revenue_cash / c.budgeted_fx_rate                                 AS net_revenue_cash,
       selling_expense / c.budgeted_fx_rate                                  AS selling_expense,
       global_member_services_fixed / c.budgeted_fx_rate                     AS global_member_services_fixed,
       fulfillment_centers_fixed / c.budgeted_fx_rate                        AS fulfillment_centers_fixed
FROM _budget_forecast_region_base b
         LEFT JOIN _budget_forecast_currency c
                   ON c.bu = b.bu
                       AND b.financial_date >= c.effective_date_from
                       AND b.financial_date < c.effective_date_to;

/* USDCurrFX = take budget targets in USD convert back to Local using the Budgeted FX Rates ( done in _budget_forecast_region_local)
   then convert to current fx using the prior month average FX rate.
   For future months that haven't happened, use the most recent prior months FX rate.
 */
CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_region_usdcurrfx AS
SELECT version,
       version_date,
       financial_date,
       b.bu,
       ''                                                                 AS hyperion_store_id,
       store_brand,
       region_type,
       store_region,
       FALSE                                                              AS is_retail_revenue,
       'USDCurrFX'                                                        AS currency_type,
       a.dest_currency                                                    AS currency,
       a.avg_exchange_rate                                                AS budgeted_fx_rate,
       membership_credits_charged_count                                   AS membership_credits_charged_count,
       membership_credits_redeemed_count                                  AS membership_credits_redeemed_count,
       membership_credits_cancelled_count                                 AS membership_credits_cancelled_count,
       a.avg_exchange_rate * first_msrp_revenue                           AS first_msrp_revenue,
       a.avg_exchange_rate * first_discounts                              AS first_discounts,
       a.avg_exchange_rate * repeat_msrp_revenue                          AS repeat_msrp_revenue,
       a.avg_exchange_rate * repeat_discounts                             AS repeat_discounts,
       leads                                                              AS leads,
       a.avg_exchange_rate * gross_cash_revenue                           AS gross_cash_revenue,
       a.avg_exchange_rate * cash_refunds                                 AS cash_refunds,
       a.avg_exchange_rate * chargebacks                                  AS chargebacks,
       a.avg_exchange_rate * net_cash_revenue_total                       AS net_cash_revenue_total,
       refunds_and_chargebacks_as_percent_of_gross_cash                   AS refunds_and_chargebacks_as_percent_of_gross_cash,
       a.avg_exchange_rate * cash_gross_margin                            AS cash_gross_margin,
       cash_gross_margin_percent_total                                    AS cash_gross_margin_percent_total,
       a.avg_exchange_rate * media_spend                                  AS media_spend,
       a.avg_exchange_rate * cash_contribution_after_media                AS cash_contribution_after_media,
       a.avg_exchange_rate * cpl                                          AS cpl,
       a.avg_exchange_rate * vip_cpa                                      AS vip_cpa,
       m1_lead_to_vip                                                     AS m1_lead_to_vip,
       m1_vips                                                            AS m1_vips,
       aged_lead_conversions                                              AS aged_lead_conversions,
       total_new_vips                                                     AS total_new_vips,
       cancels                                                            AS cancels,
       net_change_in_vips                                                 AS net_change_in_vips,
       ending_vips                                                        AS ending_vips,
       vip_growth_percent                                                 AS vip_growth_percent,
       a.avg_exchange_rate * activating_gaap_gross_revenue                AS activating_gaap_gross_revenue,
       a.avg_exchange_rate * activating_gaap_net_revenue                  AS activating_gaap_net_revenue,
       activating_order_count                                             AS activating_order_count,
       activating_aov_incl_shipping_rev                                   AS activating_aov_incl_shipping_rev,
       activating_units_per_transaction                                   AS activating_units_per_transaction,
       activating_discount_percent                                        AS activating_discount_percent,
       a.avg_exchange_rate * activating_gross_margin_$                    AS activating_gross_margin_$,
       activating_gross_margin_percent                                    AS activating_gross_margin_percent,
       a.avg_exchange_rate * repeat_gaap_gross_revenue                    AS repeat_gaap_gross_revenue,
       a.avg_exchange_rate * repeat_gaap_net_revenue                      AS repeat_gaap_net_revenue,
       repeat_order_count                                                 AS repeat_order_count,
       a.avg_exchange_rate * repeat_aov_incl_shipping_rev                 AS repeat_aov_incl_shipping_rev,
       repeat_units_per_transaction                                       AS repeat_units_per_transaction,
       repeat_discount_percent                                            AS repeat_discount_percent,
       a.avg_exchange_rate * repeat_gaap_gross_margin_$                   AS repeat_gaap_gross_margin_$,
       repeat_gaap_gross_margin_percent                                   AS repeat_gaap_gross_margin_percent,
       a.avg_exchange_rate * repeat_net_unredeemed_credit_billings        AS repeat_net_unredeemed_credit_billings,
       a.avg_exchange_rate * repeat_refund_credits                        AS repeat_refund_credits,
       repeat_other_ad_rev_div_adaptive_adj                               AS repeat_other_ad_rev_div_adaptive_adj,
       a.avg_exchange_rate * repeat_net_cash_revenue                      AS repeat_net_cash_revenue,
       repeat_cash_gross_margin                                           AS repeat_cash_gross_margin,
       repeat_cash_gross_margin_percent                                   AS repeat_cash_gross_margin_percent,
       a.avg_exchange_rate * membership_credits_charged                   AS membership_credits_charged,
       a.avg_exchange_rate * membership_credits_redeemed                  AS membership_credits_redeemed,
       a.avg_exchange_rate * membership_credits_refunded_plus_chargebacks AS membership_credits_refunded_plus_chargebacks,
       a.avg_exchange_rate * net_unredeemed_credit_billings               AS net_unredeemed_credit_billings,
       net_unredeemed_credit_billings_as_percent_of_net_cash_revenue      AS net_unredeemed_credit_billings_as_percent_of_net_cash_revenue,
       a.avg_exchange_rate * refunded_as_credit                           AS refunded_as_credit,
       a.avg_exchange_rate * refund_credit_redeemed                       AS refund_credit_redeemed,
       a.avg_exchange_rate * net_unredeemed_refund_credit                 AS net_unredeemed_refund_credit,
       a.avg_exchange_rate * deferred_revenue                             AS deferred_revenue,
       bom_vips                                                           AS bom_vips,
       credit_billed_percent                                              AS credit_billed_percent,
       credit_redeemed_percent                                            AS credit_redeemed_percent,
       credit_canceled_percent                                            AS credit_canceled_percent,
       total_units_shipped                                                AS total_units_shipped,
       repeat_cash_purchasers                                             AS repeat_cash_purchasers,
       cash_purchase_rate                                                 AS cash_purchase_rate,
       o_div_vip                                                          AS o_div_vip,
       a.avg_exchange_rate * ebitda_minus_cash                            AS ebitda_minus_cash,
       a.avg_exchange_rate * repeatplusbizdev                             AS repeatplusbizdev,
       activating_units                                                   AS activating_units,
       repeat_units                                                       AS repeat_units,
       a.avg_exchange_rate * repeat_product_revenue_incl_shipping         AS repeat_product_revenue_incl_shipping,
       a.avg_exchange_rate * product_cost_calc                            AS product_cost_calc,
       a.avg_exchange_rate * inventory_writedown                          AS inventory_writedown,
       a.avg_exchange_rate * total_cogs_minus_cash                        AS total_cogs_minus_cash,
       a.avg_exchange_rate * merchant_fees                                AS merchant_fees,
       a.avg_exchange_rate * gms_variable                                 AS gms_variable,
       a.avg_exchange_rate * fc_variable                                  AS fc_variable,
       a.avg_exchange_rate * freight_revenue                              AS freight_revenue,
       a.avg_exchange_rate * freight_out_cost                             AS freight_out_cost,
       a.avg_exchange_rate * outbound_shipping_supplies                   AS outbound_shipping_supplies,
       a.avg_exchange_rate * returns_shipping_cost                        AS returns_shipping_cost,
       a.avg_exchange_rate * product_cost_markdown                        AS product_cost_markdown,
       a.avg_exchange_rate * repeat_shipped_order_cash_collected          AS repeat_shipped_order_cash_collected,
       a.avg_exchange_rate * acquisition_margin_$                         AS acquisition_margin_$,
       acquisition_margin_percent                                         AS acquisition_margin_percent,
       acquisition_margin_$__div__order                                   AS acquisition_margin_$__div__order,
       a.avg_exchange_rate * product_cost_cust_returns_calc               AS product_cost_cust_returns_calc,
       reship_exch_orders_shipped                                         AS reship_exch_orders_shipped,
       reship_exch_units_shipped                                          AS reship_exch_units_shipped,
       a.avg_exchange_rate * cash_net_revenue                             AS cash_net_revenue,
       a.avg_exchange_rate * activating_product_gross_revenue             AS activating_product_gross_revenue,
       a.avg_exchange_rate * repeat_product_gross_revenue                 AS repeat_product_gross_revenue,
       cash_gross_margin_percent                                          AS cash_gross_margin_percent,
       repeat_units_shipped                                               AS repeat_units_shipped,
       repeat_orders_shipped                                              AS repeat_orders_shipped,
       a.avg_exchange_rate * advertising_expenses                         AS advertising_expenses,
       a.avg_exchange_rate * merchant_fee                                 AS merchant_fee,
       a.avg_exchange_rate * selling_expenses                             AS selling_expenses,
       a.avg_exchange_rate * marketing_expenses                           AS marketing_expenses,
       a.avg_exchange_rate * direct_general_and_administrative            AS direct_general_and_administrative,
       a.avg_exchange_rate * total_opex                                   AS total_opex,
       a.avg_exchange_rate * product_revenue                              AS product_revenue,
       a.avg_exchange_rate * product_gross_margin                         AS product_gross_margin,
       a.avg_exchange_rate * cash_gross_profit                            AS cash_gross_profit,
       a.avg_exchange_rate * retail_redemption_revenue                    AS retail_redemption_revenue,
       a.avg_exchange_rate * global_finance_organization                  AS global_finance_organization,
       a.avg_exchange_rate * global_ops_office_admin_and_facilities       AS global_ops_office_admin_and_facilities,
       a.avg_exchange_rate * tfg_administration                           AS tfg_administration,
       a.avg_exchange_rate * global_people_team                           AS global_people_team,
       a.avg_exchange_rate * legal                                        AS legal,
       a.avg_exchange_rate * executive                                    AS executive,
       a.avg_exchange_rate * non_allocable_corporate                      AS non_allocable_corporate,
       a.avg_exchange_rate * eu_media_buying                              AS eu_media_buying,
       a.avg_exchange_rate * eu_creative_and_marketing                    AS eu_creative_and_marketing,
       a.avg_exchange_rate * total_backoffice_step1                       AS total_backoffice_step1,
       a.avg_exchange_rate * net_revenue_cash                             AS net_revenue_cash,
       a.avg_exchange_rate * selling_expense                              AS selling_expense,
       a.avg_exchange_rate * global_member_services_fixed                 AS global_member_services_fixed,
       a.avg_exchange_rate * fulfillment_centers_fixed                    AS fulfillment_centers_fixed
FROM _budget_forecast_region_local b
         LEFT JOIN _avg_budget_rates a
                   ON b.currency = a.src_currency AND
                      CASE
                          WHEN b.financial_date > $max_avg_date THEN $max_avg_date
                          ELSE b.financial_date END = a.budget_month;

-- datasets for retail stores
CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_retail_base AS
SELECT b.*,
       fsm.store_id,
       IFNULL(ds.store_brand, '')                                      AS store_brand,
       IFNULL(ds.store_region, '')                                     AS store_region,
       CASE WHEN ds.store_region IS NOT NULL THEN 'Region' ELSE '' END AS region_type
FROM _budget_forecast_base b
         LEFT JOIN reference.finance_store_mapping_tsos fsm
                   ON b.hyperion_store_rg = fsm.hyperion_store_id
         LEFT JOIN stg.dim_store ds
                   ON ds.store_id = fsm.store_id
WHERE b.bu NOT IN (SELECT bu FROM _budget_forecast_region_base);


CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_retail_usdbtfx AS
SELECT version,
       version_date,
       financial_date             AS financial_date,
       bu,
       hyperion_store_rg AS hyperion_store_id,
       store_brand,
       region_type,
       store_region,
       TRUE              AS is_retail_revenue,
       'USDBTFX'         AS currency_type,
       'USD'             AS currency,
       1.000000          AS budgeted_fx_rate,
       membership_credits_charged_count,
       membership_credits_redeemed_count,
       membership_credits_cancelled_count,
       first_msrp_revenue,
       first_discounts,
       repeat_msrp_revenue,
       repeat_discounts,
       leads,
       gross_cash_revenue,
       cash_refunds,
       chargebacks,
       net_cash_revenue_total,
       refunds_and_chargebacks_as_percent_of_gross_cash,
       cash_gross_margin,
       cash_gross_margin_percent_total,
       media_spend,
       cash_contribution_after_media,
       cpl,
       vip_cpa,
       m1_lead_to_vip,
       m1_vips,
       aged_lead_conversions,
       total_new_vips,
       cancels,
       net_change_in_vips,
       ending_vips,
       vip_growth_percent,
       activating_gaap_gross_revenue,
       activating_gaap_net_revenue,
       activating_order_count,
       activating_aov_incl_shipping_rev,
       activating_units_per_transaction,
       activating_discount_percent,
       activating_gross_margin_$,
       activating_gross_margin_percent,
       repeat_gaap_gross_revenue,
       repeat_gaap_net_revenue,
       repeat_order_count,
       repeat_aov_incl_shipping_rev,
       repeat_units_per_transaction,
       repeat_discount_percent,
       repeat_gaap_gross_margin_$,
       repeat_gaap_gross_margin_percent,
       repeat_net_unredeemed_credit_billings,
       repeat_refund_credits,
       repeat_other_ad_rev_div_adaptive_adj,
       repeat_net_cash_revenue,
       repeat_cash_gross_margin,
       repeat_cash_gross_margin_percent,
       membership_credits_charged,
       membership_credits_redeemed,
       membership_credits_refunded_plus_chargebacks,
       net_unredeemed_credit_billings,
       net_unredeemed_credit_billings_as_percent_of_net_cash_revenue,
       refunded_as_credit,
       refund_credit_redeemed,
       net_unredeemed_refund_credit,
       deferred_revenue,
       bom_vips,
       credit_billed_percent,
       credit_redeemed_percent,
       credit_canceled_percent,
       total_units_shipped,
       repeat_cash_purchasers,
       cash_purchase_rate,
       o_div_vip,
       ebitda_minus_cash,
       repeatplusbizdev,
       activating_units,
       repeat_units,
       repeat_product_revenue_incl_shipping,
       product_cost_calc,
       inventory_writedown,
       total_cogs_minus_cash,
       merchant_fees,
       gms_variable,
       fc_variable,
       freight_revenue,
       freight_out_cost,
       outbound_shipping_supplies,
       returns_shipping_cost,
       product_cost_markdown,
       repeat_shipped_order_cash_collected,
       acquisition_margin_$,
       acquisition_margin_percent,
       acquisition_margin_$__div__order,
       product_cost_cust_returns_calc,
       reship_exch_orders_shipped,
       reship_exch_units_shipped,
       cash_net_revenue,
       activating_product_gross_revenue,
       repeat_product_gross_revenue,
       cash_gross_margin_percent,
       repeat_units_shipped,
       repeat_orders_shipped,
       advertising_expenses,
       merchant_fee,
       selling_expenses,
       marketing_expenses,
       direct_general_and_administrative,
       total_opex,
       product_revenue,
       product_gross_margin,
       cash_gross_profit,
       retail_redemption_revenue,
       global_finance_organization,
       global_ops_office_admin_and_facilities,
       tfg_administration,
       global_people_team,
       legal,
       executive,
       non_allocable_corporate,
       eu_media_buying,
       eu_creative_and_marketing,
       total_backoffice_step1,
       net_revenue_cash,
       selling_expense,
       global_member_services_fixed,
       fulfillment_centers_fixed
FROM _budget_forecast_retail_base;


-- all of our retail stores are currently in USA, meaning there is no need to have Local and USDCurrFx versions.
-- however, the script still produces these versions in case there is a retail store in foreign currency in the future.
-- it also creates consistency with region level data
CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_retail_local AS
SELECT rb.version,
       rb.version_date,
       rb.financial_date                                                               AS financial_date,
       rb.bu,
       rb.hyperion_store_rg                                                   AS hyperion_store_id,
       rb.store_brand,
       rb.region_type,
       rb.store_region,
       TRUE                                                                   AS is_retail_revenue,
       'Local'                                                                AS currency_type,
       'USD'                                                                  AS currency,
       IFNULL(c.budgeted_fx_rate, 1.0000)                                     AS budgeted_fx_rate,
       membership_credits_charged_count                                       AS membership_credits_charged_count,
       membership_credits_redeemed_count                                      AS membership_credits_redeemed_count,
       membership_credits_cancelled_count                                     AS membership_credits_cancelled_count,
       IFNULL(c.budgeted_fx_rate, 1.0000) * first_msrp_revenue                AS first_msrp_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * first_discounts                   AS first_discounts,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_msrp_revenue               AS repeat_msrp_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_discounts                  AS repeat_discounts,
       leads                                                                  AS leads,
       IFNULL(c.budgeted_fx_rate, 1.0000) * gross_cash_revenue                AS gross_cash_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * cash_refunds                      AS cash_refunds,
       IFNULL(c.budgeted_fx_rate, 1.0000) * chargebacks                       AS chargebacks,
       IFNULL(c.budgeted_fx_rate, 1.0000) * net_cash_revenue_total            AS net_cash_revenue_total,
       refunds_and_chargebacks_as_percent_of_gross_cash                       AS refunds_and_chargebacks_as_percent_of_gross_cash,
       IFNULL(c.budgeted_fx_rate, 1.0000) * cash_gross_margin                 AS cash_gross_margin,
       cash_gross_margin_percent_total                                        AS cash_gross_margin_percent_total,
       IFNULL(c.budgeted_fx_rate, 1.0000) * media_spend                       AS media_spend,
       IFNULL(c.budgeted_fx_rate, 1.0000) * cash_contribution_after_media     AS cash_contribution_after_media,
       IFNULL(c.budgeted_fx_rate, 1.0000) * cpl                               AS cpl,
       IFNULL(c.budgeted_fx_rate, 1.0000) * vip_cpa                           AS vip_cpa,
       m1_lead_to_vip                                                         AS m1_lead_to_vip,
       m1_vips                                                                AS m1_vips,
       aged_lead_conversions                                                  AS aged_lead_conversions,
       total_new_vips                                                         AS total_new_vips,
       cancels                                                                AS cancels,
       net_change_in_vips                                                     AS net_change_in_vips,
       ending_vips                                                            AS ending_vips,
       vip_growth_percent                                                     AS vip_growth_percent,
       IFNULL(c.budgeted_fx_rate, 1.0000) * activating_gaap_gross_revenue     AS activating_gaap_gross_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * activating_gaap_net_revenue       AS activating_gaap_net_revenue,
       activating_order_count                                                 AS activating_order_count,
       activating_aov_incl_shipping_rev                                       AS activating_aov_incl_shipping_rev,
       activating_units_per_transaction                                       AS activating_units_per_transaction,
       activating_discount_percent                                            AS activating_discount_percent,
       IFNULL(c.budgeted_fx_rate, 1.0000) * activating_gross_margin_$         AS activating_gross_margin_$,
       activating_gross_margin_percent                                        AS activating_gross_margin_percent,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_gaap_gross_revenue         AS repeat_gaap_gross_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_gaap_net_revenue           AS repeat_gaap_net_revenue,
       repeat_order_count                                                     AS repeat_order_count,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_aov_incl_shipping_rev      AS repeat_aov_incl_shipping_rev,
       repeat_units_per_transaction                                           AS repeat_units_per_transaction,
       repeat_discount_percent                                                AS repeat_discount_percent,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_gaap_gross_margin_$        AS repeat_gaap_gross_margin_$,
       repeat_gaap_gross_margin_percent                                       AS repeat_gaap_gross_margin_percent,
       IFNULL(c.budgeted_fx_rate, 1.0000) *
       repeat_net_unredeemed_credit_billings                                  AS repeat_net_unredeemed_credit_billings,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_refund_credits             AS repeat_refund_credits,
       repeat_other_ad_rev_div_adaptive_adj                                   AS repeat_other_ad_rev_div_adaptive_adj,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_net_cash_revenue           AS repeat_net_cash_revenue,
       repeat_cash_gross_margin                                               AS repeat_cash_gross_margin,
       repeat_cash_gross_margin_percent                                       AS repeat_cash_gross_margin_percent,
       IFNULL(c.budgeted_fx_rate, 1.0000) * membership_credits_charged        AS membership_credits_charged,
       IFNULL(c.budgeted_fx_rate, 1.0000) * membership_credits_redeemed       AS membership_credits_redeemed,
       IFNULL(c.budgeted_fx_rate, 1.0000) *
       membership_credits_refunded_plus_chargebacks                           AS membership_credits_refunded_plus_chargebacks,
       IFNULL(c.budgeted_fx_rate, 1.0000) * net_unredeemed_credit_billings    AS net_unredeemed_credit_billings,
       net_unredeemed_credit_billings_as_percent_of_net_cash_revenue          AS net_unredeemed_credit_billings_as_percent_of_net_cash_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * refunded_as_credit                AS refunded_as_credit,
       IFNULL(c.budgeted_fx_rate, 1.0000) * refund_credit_redeemed            AS refund_credit_redeemed,
       IFNULL(c.budgeted_fx_rate, 1.0000) * net_unredeemed_refund_credit      AS net_unredeemed_refund_credit,
       IFNULL(c.budgeted_fx_rate, 1.0000) * deferred_revenue                  AS deferred_revenue,
       bom_vips                                                               AS bom_vips,
       credit_billed_percent                                                  AS credit_billed_percent,
       credit_redeemed_percent                                                AS credit_redeemed_percent,
       credit_canceled_percent                                                AS credit_canceled_percent,
       total_units_shipped                                                    AS total_units_shipped,
       repeat_cash_purchasers                                                 AS repeat_cash_purchasers,
       cash_purchase_rate                                                     AS cash_purchase_rate,
       o_div_vip                                                              AS o_div_vip,
       IFNULL(c.budgeted_fx_rate, 1.0000) * ebitda_minus_cash                 AS ebitda_minus_cash,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeatplusbizdev                  AS repeatplusbizdev,
       activating_units                                                       AS activating_units,
       repeat_units                                                           AS repeat_units,
       IFNULL(c.budgeted_fx_rate, 1.0000) *
       repeat_product_revenue_incl_shipping                                   AS repeat_product_revenue_incl_shipping,
       IFNULL(c.budgeted_fx_rate, 1.0000) * product_cost_calc                 AS product_cost_calc,
       IFNULL(c.budgeted_fx_rate, 1.0000) * inventory_writedown               AS inventory_writedown,
       IFNULL(c.budgeted_fx_rate, 1.0000) * total_cogs_minus_cash             AS total_cogs_minus_cash,
       IFNULL(c.budgeted_fx_rate, 1.0000) * merchant_fees                     AS merchant_fees,
       IFNULL(c.budgeted_fx_rate, 1.0000) * gms_variable                      AS gms_variable,
       IFNULL(c.budgeted_fx_rate, 1.0000) * fc_variable                       AS fc_variable,
       IFNULL(c.budgeted_fx_rate, 1.0000) * freight_revenue                   AS freight_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * freight_out_cost                  AS freight_out_cost,
       IFNULL(c.budgeted_fx_rate, 1.0000) * outbound_shipping_supplies        AS outbound_shipping_supplies,
       IFNULL(c.budgeted_fx_rate, 1.0000) * returns_shipping_cost             AS returns_shipping_cost,
       IFNULL(c.budgeted_fx_rate, 1.0000) * product_cost_markdown             AS product_cost_markdown,
       IFNULL(c.budgeted_fx_rate, 1.0000) *
       repeat_shipped_order_cash_collected                                    AS repeat_shipped_order_cash_collected,
       IFNULL(c.budgeted_fx_rate, 1.0000) * acquisition_margin_$              AS acquisition_margin_$,
       acquisition_margin_percent                                             AS acquisition_margin_percent,
       acquisition_margin_$__div__order                                       AS acquisition_margin_$__div__order,
       IFNULL(c.budgeted_fx_rate, 1.0000) * product_cost_cust_returns_calc    AS product_cost_cust_returns_calc,
       reship_exch_orders_shipped                                             AS reship_exch_orders_shipped,
       reship_exch_units_shipped                                              AS reship_exch_units_shipped,
       IFNULL(c.budgeted_fx_rate, 1.0000) * cash_net_revenue                  AS cash_net_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * activating_product_gross_revenue  AS activating_product_gross_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * repeat_product_gross_revenue      AS repeat_product_gross_revenue,
       cash_gross_margin_percent                                              AS cash_gross_margin_percent,
       repeat_units_shipped                                                   AS repeat_units_shipped,
       repeat_orders_shipped                                                  AS repeat_orders_shipped,
       IFNULL(c.budgeted_fx_rate, 1.0000) * advertising_expenses              AS advertising_expenses,
       IFNULL(c.budgeted_fx_rate, 1.0000) * merchant_fee                      AS merchant_fee,
       IFNULL(c.budgeted_fx_rate, 1.0000) * selling_expenses                  AS selling_expenses,
       IFNULL(c.budgeted_fx_rate, 1.0000) * marketing_expenses                AS marketing_expenses,
       IFNULL(c.budgeted_fx_rate, 1.0000) * direct_general_and_administrative AS direct_general_and_administrative,
       IFNULL(c.budgeted_fx_rate, 1.0000) * total_opex                        AS total_opex,
       IFNULL(c.budgeted_fx_rate, 1.0000) * product_revenue                   AS product_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * product_gross_margin              AS product_gross_margin,
       IFNULL(c.budgeted_fx_rate, 1.0000) * cash_gross_profit                 AS cash_gross_profit,
       IFNULL(c.budgeted_fx_rate, 1.0000) * retail_redemption_revenue         AS retail_redemption_revenue,
       IFNULL(c.budgeted_fx_rate, 1.0000) * global_finance_organization         AS global_finance_organization,
       IFNULL(c.budgeted_fx_rate, 1.0000) * global_ops_office_admin_and_facilities AS global_ops_office_admin_and_facilities,
       IFNULL(c.budgeted_fx_rate, 1.0000) * tfg_administration                    AS tfg_administration,
       IFNULL(c.budgeted_fx_rate, 1.0000) * global_people_team                    AS global_people_team,
       IFNULL(c.budgeted_fx_rate, 1.0000) * legal                                 AS legal,
       IFNULL(c.budgeted_fx_rate, 1.0000) * executive                             AS executive,
       IFNULL(c.budgeted_fx_rate, 1.0000) * non_allocable_corporate               AS non_allocable_corporate,
       IFNULL(c.budgeted_fx_rate, 1.0000) * eu_media_buying                       AS eu_media_buying,
       IFNULL(c.budgeted_fx_rate, 1.0000) * eu_creative_and_marketing             AS eu_creative_and_marketing,
       IFNULL(c.budgeted_fx_rate, 1.0000) * total_backoffice_step1                AS total_backoffice_step1,
       IFNULL(c.budgeted_fx_rate, 1.0000) * net_revenue_cash                      AS net_revenue_cash,
       IFNULL(c.budgeted_fx_rate, 1.0000) * selling_expense                       AS selling_expense,
       IFNULL(c.budgeted_fx_rate, 1.0000) * global_member_services_fixed          AS global_member_services_fixed,
       IFNULL(c.budgeted_fx_rate, 1.0000) * fulfillment_centers_fixed             AS fulfillment_centers_fixed
FROM _budget_forecast_retail_base rb
         LEFT JOIN reference.store_currency sc
                   ON rb.store_id = sc.store_id
         LEFT JOIN reference.finance_currency_conversion c
                   ON c.local_currency = sc.currency_code
                       AND rb.financial_date >= c.effective_date_from
                       AND rb.financial_date < c.effective_date_to;



CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_retail_usdcurrfx AS
SELECT rl.version,
       rl.version_date,
       rl.financial_date,
       rl.bu,
       rl.hyperion_store_id,
       rl.store_brand,
       rl.region_type,
       rl.store_region,
       TRUE                                                                   AS is_retail_revenue,
       'USDCurrFX'                                                            AS currency_type,
       IFNULL(a.dest_currency, 'USD')                                         AS currency,
       IFNULL(a.avg_exchange_rate, 1.0000)                                    AS budgeted_fx_rate,
       membership_credits_charged_count                                       AS membership_credits_charged_count,
       membership_credits_redeemed_count                                      AS membership_credits_redeemed_count,
       membership_credits_cancelled_count                                     AS membership_credits_cancelled_count,
       IFNULL(a.avg_exchange_rate, 1.0000) * first_msrp_revenue               AS first_msrp_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * first_discounts                  AS first_discounts,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_msrp_revenue              AS repeat_msrp_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_discounts                 AS repeat_discounts,
       leads                                                                  AS leads,
       IFNULL(a.avg_exchange_rate, 1.0000) * gross_cash_revenue               AS gross_cash_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * cash_refunds                     AS cash_refunds,
       IFNULL(a.avg_exchange_rate, 1.0000) * chargebacks                      AS chargebacks,
       IFNULL(a.avg_exchange_rate, 1.0000) * net_cash_revenue_total           AS net_cash_revenue_total,
       refunds_and_chargebacks_as_percent_of_gross_cash                       AS refunds_and_chargebacks_as_percent_of_gross_cash,
       IFNULL(a.avg_exchange_rate, 1.0000) * cash_gross_margin                AS cash_gross_margin,
       cash_gross_margin_percent_total                                        AS cash_gross_margin_percent_total,
       IFNULL(a.avg_exchange_rate, 1.0000) * media_spend                      AS media_spend,
       IFNULL(a.avg_exchange_rate, 1.0000) * cash_contribution_after_media    AS cash_contribution_after_media,
       IFNULL(a.avg_exchange_rate, 1.0000) * cpl                              AS cpl,
       IFNULL(a.avg_exchange_rate, 1.0000) * vip_cpa                          AS vip_cpa,
       m1_lead_to_vip                                                         AS m1_lead_to_vip,
       m1_vips                                                                AS m1_vips,
       aged_lead_conversions                                                  AS aged_lead_conversions,
       total_new_vips                                                         AS total_new_vips,
       cancels                                                                AS cancels,
       net_change_in_vips                                                     AS net_change_in_vips,
       ending_vips                                                            AS ending_vips,
       vip_growth_percent                                                     AS vip_growth_percent,
       IFNULL(a.avg_exchange_rate, 1.0000) * activating_gaap_gross_revenue    AS activating_gaap_gross_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * activating_gaap_net_revenue      AS activating_gaap_net_revenue,
       activating_order_count                                                 AS activating_order_count,
       activating_aov_incl_shipping_rev                                       AS activating_aov_incl_shipping_rev,
       activating_units_per_transaction                                       AS activating_units_per_transaction,
       activating_discount_percent                                            AS activating_discount_percent,
       IFNULL(a.avg_exchange_rate, 1.0000) * activating_gross_margin_$        AS activating_gross_margin_$,
       activating_gross_margin_percent                                        AS activating_gross_margin_percent,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_gaap_gross_revenue        AS repeat_gaap_gross_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_gaap_net_revenue          AS repeat_gaap_net_revenue,
       repeat_order_count                                                     AS repeat_order_count,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_aov_incl_shipping_rev     AS repeat_aov_incl_shipping_rev,
       repeat_units_per_transaction                                           AS repeat_units_per_transaction,
       repeat_discount_percent                                                AS repeat_discount_percent,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_gaap_gross_margin_$       AS repeat_gaap_gross_margin_$,
       repeat_gaap_gross_margin_percent                                       AS repeat_gaap_gross_margin_percent,
       IFNULL(a.avg_exchange_rate, 1.0000) *
       repeat_net_unredeemed_credit_billings                                  AS repeat_net_unredeemed_credit_billings,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_refund_credits            AS repeat_refund_credits,
       repeat_other_ad_rev_div_adaptive_adj                                   AS repeat_other_ad_rev_div_adaptive_adj,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_net_cash_revenue          AS repeat_net_cash_revenue,
       repeat_cash_gross_margin                                               AS repeat_cash_gross_margin,
       repeat_cash_gross_margin_percent                                       AS repeat_cash_gross_margin_percent,
       IFNULL(a.avg_exchange_rate, 1.0000) * membership_credits_charged       AS membership_credits_charged,
       IFNULL(a.avg_exchange_rate, 1.0000) * membership_credits_redeemed      AS membership_credits_redeemed,
       IFNULL(a.avg_exchange_rate, 1.0000) *
       membership_credits_refunded_plus_chargebacks                           AS membership_credits_refunded_plus_chargebacks,
       IFNULL(a.avg_exchange_rate, 1.0000) * net_unredeemed_credit_billings   AS net_unredeemed_credit_billings,
       net_unredeemed_credit_billings_as_percent_of_net_cash_revenue          AS net_unredeemed_credit_billings_as_percent_of_net_cash_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * refunded_as_credit               AS refunded_as_credit,
       IFNULL(a.avg_exchange_rate, 1.0000) * refund_credit_redeemed           AS refund_credit_redeemed,
       IFNULL(a.avg_exchange_rate, 1.0000) * net_unredeemed_refund_credit     AS net_unredeemed_refund_credit,
       IFNULL(a.avg_exchange_rate, 1.0000) * deferred_revenue                 AS deferred_revenue,
       bom_vips                                                               AS bom_vips,
       credit_billed_percent                                                  AS credit_billed_percent,
       credit_redeemed_percent                                                AS credit_redeemed_percent,
       credit_canceled_percent                                                AS credit_canceled_percent,
       total_units_shipped                                                    AS total_units_shipped,
       repeat_cash_purchasers                                                 AS repeat_cash_purchasers,
       cash_purchase_rate                                                     AS cash_purchase_rate,
       o_div_vip                                                              AS o_div_vip,
       IFNULL(a.avg_exchange_rate, 1.0000) * ebitda_minus_cash                AS ebitda_minus_cash,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeatplusbizdev                 AS repeatplusbizdev,
       activating_units                                                       AS activating_units,
       repeat_units                                                           AS repeat_units,
       IFNULL(a.avg_exchange_rate, 1.0000) *
       repeat_product_revenue_incl_shipping                                   AS repeat_product_revenue_incl_shipping,
       IFNULL(a.avg_exchange_rate, 1.0000) * product_cost_calc                AS product_cost_calc,
       IFNULL(a.avg_exchange_rate, 1.0000) * inventory_writedown              AS inventory_writedown,
       IFNULL(a.avg_exchange_rate, 1.0000) * total_cogs_minus_cash            AS total_cogs_minus_cash,
       IFNULL(a.avg_exchange_rate, 1.0000) * merchant_fees                    AS merchant_fees,
       IFNULL(a.avg_exchange_rate, 1.0000) * gms_variable                     AS gms_variable,
       IFNULL(a.avg_exchange_rate, 1.0000) * fc_variable                      AS fc_variable,
       IFNULL(a.avg_exchange_rate, 1.0000) * freight_revenue                  AS freight_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * freight_out_cost                 AS freight_out_cost,
       IFNULL(a.avg_exchange_rate, 1.0000) * outbound_shipping_supplies       AS outbound_shipping_supplies,
       IFNULL(a.avg_exchange_rate, 1.0000) * returns_shipping_cost            AS returns_shipping_cost,
       IFNULL(a.avg_exchange_rate, 1.0000) * product_cost_markdown            AS product_cost_markdown,
       IFNULL(a.avg_exchange_rate, 1.0000) *
       repeat_shipped_order_cash_collected                                    AS repeat_shipped_order_cash_collected,
       IFNULL(a.avg_exchange_rate, 1.0000) * acquisition_margin_$             AS acquisition_margin_$,
       acquisition_margin_percent                                             AS acquisition_margin_percent,
       acquisition_margin_$__div__order                                       AS acquisition_margin_$__div__order,
       IFNULL(a.avg_exchange_rate, 1.0000) * product_cost_cust_returns_calc   AS product_cost_cust_returns_calc,
       reship_exch_orders_shipped                                             AS reship_exch_orders_shipped,
       reship_exch_units_shipped                                              AS reship_exch_units_shipped,
       IFNULL(a.avg_exchange_rate, 1.0000) * cash_net_revenue                 AS cash_net_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * activating_product_gross_revenue AS activating_product_gross_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * repeat_product_gross_revenue     AS repeat_product_gross_revenue,
       cash_gross_margin_percent                                              AS cash_gross_margin_percent,
       repeat_units_shipped                                                   AS repeat_units_shipped,
       repeat_orders_shipped                                                  AS repeat_orders_shipped,
       IFNULL(a.avg_exchange_rate, 1.0000) * advertising_expenses             AS advertising_expenses,
       IFNULL(a.avg_exchange_rate, 1.0000) * merchant_fee                     AS merchant_fee,
       IFNULL(a.avg_exchange_rate, 1.0000) * selling_expenses                 AS selling_expenses,
       IFNULL(a.avg_exchange_rate, 1.0000) * marketing_expenses               AS marketing_expenses,
       IFNULL(a.avg_exchange_rate, 1.0000) *
       direct_general_and_administrative                                      AS direct_general_and_administrative,
       IFNULL(a.avg_exchange_rate, 1.0000) * total_opex                       AS total_opex,
       IFNULL(a.avg_exchange_rate, 1.0000) * product_revenue                  AS product_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * product_gross_margin             AS product_gross_margin,
       IFNULL(a.avg_exchange_rate, 1.0000) * cash_gross_profit                AS cash_gross_profit,
       IFNULL(a.avg_exchange_rate, 1.0000) * retail_redemption_revenue        AS retail_redemption_revenue,
       IFNULL(a.avg_exchange_rate, 1.0000) * global_finance_organization         AS global_finance_organization,
       IFNULL(a.avg_exchange_rate, 1.0000) * global_ops_office_admin_and_facilities AS global_ops_office_admin_and_facilities,
       IFNULL(a.avg_exchange_rate, 1.0000) * tfg_administration                    AS tfg_administration,
       IFNULL(a.avg_exchange_rate, 1.0000) * global_people_team                    AS global_people_team,
       IFNULL(a.avg_exchange_rate, 1.0000) * legal                                 AS legal,
       IFNULL(a.avg_exchange_rate, 1.0000) * executive                             AS executive,
       IFNULL(a.avg_exchange_rate, 1.0000) * non_allocable_corporate               AS non_allocable_corporate,
       IFNULL(a.avg_exchange_rate, 1.0000) * eu_media_buying                       AS eu_media_buying,
       IFNULL(a.avg_exchange_rate, 1.0000) * eu_creative_and_marketing             AS eu_creative_and_marketing,
       IFNULL(a.avg_exchange_rate, 1.0000) * total_backoffice_step1                AS total_backoffice_step1,
       IFNULL(a.avg_exchange_rate, 1.0000) * net_revenue_cash                      AS net_revenue_cash,
       IFNULL(a.avg_exchange_rate, 1.0000) * selling_expense                       AS selling_expense,
       IFNULL(a.avg_exchange_rate, 1.0000) * global_member_services_fixed          AS global_member_services_fixed,
       IFNULL(a.avg_exchange_rate, 1.0000) * fulfillment_centers_fixed             AS fulfillment_centers_fixed
FROM _budget_forecast_retail_local rl
         LEFT JOIN reference.finance_store_mapping fsm
                   ON rl.hyperion_store_id = fsm.hyperion_store_id
         LEFT JOIN reference.store_currency sc
                   ON fsm.store_id = sc.store_id
         LEFT JOIN _avg_budget_rates a
                   ON sc.currency_code = a.src_currency AND
                      CASE
                          WHEN rl.financial_date > $max_avg_date THEN $max_avg_date
                          ELSE rl.financial_date END = a.budget_month;


CREATE OR REPLACE TEMPORARY TABLE _budget_forecast_comb AS
SELECT *
FROM _budget_forecast_retail_usdbtfx
UNION
SELECT *
FROM _budget_forecast_retail_local
UNION
SELECT *
FROM _budget_forecast_retail_usdcurrfx
UNION
SELECT *
FROM _budget_forecast_region_usdbtfx
UNION
SELECT *
FROM _budget_forecast_region_usdcurrfx
UNION
SELECT *
FROM _budget_forecast_region_local;


CREATE OR REPLACE TABLE reference.finance_budget_forecast AS
SELECT version,
       version_date,
       financial_date,
       bu,
       hyperion_store_id,
       store_brand,
       region_type,
       store_region,
       is_retail_revenue,
       currency_type,
       currency,
       budgeted_fx_rate,
       membership_credits_charged_count,
       membership_credits_redeemed_count,
       membership_credits_cancelled_count,
       first_msrp_revenue,
       first_discounts,
       repeat_msrp_revenue,
       repeat_discounts,
       leads,
       gross_cash_revenue,
       cash_refunds,
       chargebacks,
       net_cash_revenue_total,
       refunds_and_chargebacks_as_percent_of_gross_cash,
       cash_gross_margin,
       cash_gross_margin_percent_total,
       media_spend,
       cash_contribution_after_media,
       cpl,
       vip_cpa,
       m1_lead_to_vip,
       m1_vips,
       aged_lead_conversions,
       total_new_vips,
       cancels,
       net_change_in_vips,
       ending_vips,
       vip_growth_percent,
       activating_gaap_gross_revenue,
       activating_gaap_net_revenue,
       activating_order_count,
       activating_aov_incl_shipping_rev,
       activating_units_per_transaction,
       activating_discount_percent,
       activating_gross_margin_$,
       activating_gross_margin_percent,
       repeat_gaap_gross_revenue,
       repeat_gaap_net_revenue,
       repeat_order_count,
       repeat_aov_incl_shipping_rev,
       repeat_units_per_transaction,
       repeat_discount_percent,
       repeat_gaap_gross_margin_$,
       repeat_gaap_gross_margin_percent,
       repeat_net_unredeemed_credit_billings,
       repeat_refund_credits,
       repeat_other_ad_rev_div_adaptive_adj,
       repeat_net_cash_revenue,
       repeat_cash_gross_margin,
       repeat_cash_gross_margin_percent,
       membership_credits_charged,
       membership_credits_redeemed,
       membership_credits_refunded_plus_chargebacks,
       net_unredeemed_credit_billings,
       net_unredeemed_credit_billings_as_percent_of_net_cash_revenue,
       refunded_as_credit,
       refund_credit_redeemed,
       net_unredeemed_refund_credit,
       deferred_revenue,
       bom_vips,
       credit_billed_percent,
       credit_redeemed_percent,
       credit_canceled_percent,
       total_units_shipped,
       repeat_cash_purchasers,
       cash_purchase_rate,
       o_div_vip,
       ebitda_minus_cash,
       repeatplusbizdev,
       activating_units,
       repeat_units,
       repeat_product_revenue_incl_shipping,
       product_cost_calc,
       inventory_writedown,
       total_cogs_minus_cash,
       merchant_fees,
       gms_variable,
       fc_variable,
       freight_revenue,
       freight_out_cost,
       outbound_shipping_supplies,
       returns_shipping_cost,
       product_cost_markdown,
       repeat_shipped_order_cash_collected,
       acquisition_margin_$,
       acquisition_margin_percent,
       acquisition_margin_$__div__order,
       product_cost_cust_returns_calc,
       reship_exch_orders_shipped,
       reship_exch_units_shipped,
       cash_net_revenue,
       activating_product_gross_revenue,
       repeat_product_gross_revenue,
       cash_gross_margin_percent,
       repeat_units_shipped,
       repeat_orders_shipped,
       advertising_expenses,
       merchant_fee,
       selling_expenses,
       marketing_expenses,
       direct_general_and_administrative,
       total_opex,
       product_revenue,
       product_gross_margin,
       cash_gross_profit,
       retail_redemption_revenue,
       global_finance_organization,
       global_ops_office_admin_and_facilities,
       tfg_administration,
       global_people_team,
       legal,
       executive,
       non_allocable_corporate,
       eu_media_buying,
       eu_creative_and_marketing,
       total_backoffice_step1,
       net_revenue_cash,
       selling_expense,
       global_member_services_fixed,
       fulfillment_centers_fixed,
       $execution_start_time AS meta_create_datetime,
       $execution_start_time AS meta_update_datetime
FROM _budget_forecast_comb;
