TRUNCATE TABLE reporting.merch_planning_outfit_final_output;

INSERT INTO reporting.merch_planning_outfit_final_output (
    date,
    period,
    date_type,
    store_id,
    store_name,
    store_full_name,
    store_brand,
    product_brand,
    store_type,
    country,
    finance_specialty_store,
    region,
    is_retail,
    bundle_name,
    bundle_alias,
    ty_total_bundle_count,
    ty_bundle_count_activating,
    ty_bundle_count_nonactivating,
    ty_bundle_count_repeat,
    ty_bundle_count_guest,
    ty_total_product_subtotal,
    ty_product_subtotal_activating,
    ty_product_subtotal_nonactivating,
    ty_product_subtotal_repeat,
    ty_product_subtotal_guest,
    ty_total_product_discount,
    ty_product_discount_activating,
    ty_product_discount_nonactivating,
    ty_product_discount_repeat,
    ty_product_discount_guest,
    ty_total_product_gross_revenue_excl_shipping,
    ty_product_gross_revenue_excl_shipping_activating,
    ty_product_gross_revenue_excl_shipping_nonactivating,
    ty_product_gross_revenue_excl_shipping_repeat,
    ty_product_gross_revenue_excl_shipping_guest,
    ty_total_product_margin_pre_return_excl_shipping,
    ty_product_margin_pre_return_excl_shipping_activating,
    ty_product_margin_pre_return_excl_shipping_nonactivating,
    ty_product_margin_pre_return_excl_shipping_repeat,
    ty_product_margin_pre_return_excl_shipping_guest,
    ty_total_product_cost,
    ty_product_cost_activating,
    ty_product_cost_nonactivating,
    ty_product_cost_repeat,
    ty_product_cost_guest,
    ty_total_product_cost_c,
    ty_product_cost_activating_c,
    ty_product_cost_nonactivating_c,
    ty_product_cost_repeat_c,
    ty_product_cost_guest_c,
    ty_total_non_reduced_vip_price,
    ty_non_reduced_vip_price_activating,
    ty_non_reduced_vip_price_nonactivating,
    ty_non_reduced_vip_price_repeat,
    ty_non_reduced_vip_price_guest,
    ltd_total_bundle_count,
    ltd_bundle_count_activating,
    ltd_bundle_count_nonactivating,
    ltd_bundle_count_repeat,
    ltd_bundle_count_guest,
    mtd_total_bundle_count,
    mtd_bundle_count_activating,
    mtd_bundle_count_nonactivating,
    mtd_bundle_count_repeat,
    mtd_bundle_count_guest,
    mtd_total_product_subtotal,
    mtd_product_subtotal_activating,
    mtd_product_subtotal_nonactivating,
    mtd_product_subtotal_repeat,
    mtd_product_subtotal_guest,
    mtd_total_product_discount,
    mtd_product_discount_activating,
    mtd_product_discount_nonactivating,
    mtd_product_discount_repeat,
    mtd_product_discount_guest,
    mtd_total_product_gross_revenue_excl_shipping,
    mtd_product_gross_revenue_excl_shipping_activating,
    mtd_product_gross_revenue_excl_shipping_nonactivating,
    mtd_product_gross_revenue_excl_shipping_repeat,
    mtd_product_gross_revenue_excl_shipping_guest,
    mtd_total_product_margin_pre_return_excl_shipping,
    mtd_product_margin_pre_return_excl_shipping_activating,
    mtd_product_margin_pre_return_excl_shipping_nonactivating,
    mtd_product_margin_pre_return_excl_shipping_repeat,
    mtd_product_margin_pre_return_excl_shipping_guest,
    mtd_total_product_cost,
    mtd_product_cost_activating,
    mtd_product_cost_nonactivating,
    mtd_product_cost_repeat,
    mtd_product_cost_guest,
    mtd_total_product_cost_c,
    mtd_product_cost_activating_c,
    mtd_product_cost_nonactivating_c,
    mtd_product_cost_repeat_c,
    mtd_product_cost_guest_c,
    mtd_total_non_reduced_vip_price,
    mtd_non_reduced_vip_price_activating,
    mtd_non_reduced_vip_price_nonactivating,
    mtd_non_reduced_vip_price_repeat,
    mtd_non_reduced_vip_price_guest,
    ly_total_bundle_count,
    ly_bundle_count_activating,
    ly_bundle_count_nonactivating,
    ly_bundle_count_repeat,
    ly_bundle_count_guest,
    ly_total_product_subtotal,
    ly_product_subtotal_activating,
    ly_product_subtotal_nonactivating,
    ly_product_subtotal_repeat,
    ly_product_subtotal_guest,
    ly_total_product_discount,
    ly_product_discount_activating,
    ly_product_discount_nonactivating,
    ly_product_discount_repeat,
    ly_product_discount_guest,
    ly_total_product_gross_revenue_excl_shipping,
    ly_product_gross_revenue_excl_shipping_activating,
    ly_product_gross_revenue_excl_shipping_nonactivating,
    ly_product_gross_revenue_excl_shipping_repeat,
    ly_product_gross_revenue_excl_shipping_guest,
    ly_total_product_margin_pre_return_excl_shipping,
    ly_product_margin_pre_return_excl_shipping_activating,
    ly_product_margin_pre_return_excl_shipping_nonactivating,
    ly_product_margin_pre_return_excl_shipping_repeat,
    ly_product_margin_pre_return_excl_shipping_guest,
    ly_total_product_cost,
    ly_product_cost_activating,
    ly_product_cost_nonactivating,
    ly_product_cost_repeat,
    ly_product_cost_guest,
    ly_total_product_cost_c,
    ly_product_cost_activating_c,
    ly_product_cost_nonactivating_c,
    ly_product_cost_repeat_c,
    ly_product_cost_guest_c,
    ly_total_non_reduced_vip_price,
    ly_non_reduced_vip_price_activating,
    ly_non_reduced_vip_price_nonactivating,
    ly_non_reduced_vip_price_repeat,
    ly_non_reduced_vip_price_guest,
    lymtd_total_bundle_count,
    lymtd_bundle_count_activating,
    lymtd_bundle_count_nonactivating,
    lymtd_bundle_count_repeat,
    lymtd_bundle_count_guest,
    lymtd_total_product_subtotal,
    lymtd_product_subtotal_activating,
    lymtd_product_subtotal_nonactivating,
    lymtd_product_subtotal_repeat,
    lymtd_product_subtotal_guest,
    lymtd_total_product_discount,
    lymtd_product_discount_activating,
    lymtd_product_discount_nonactivating,
    lymtd_product_discount_repeat,
    lymtd_product_discount_guest,
    lymtd_total_product_gross_revenue_excl_shipping,
    lymtd_product_gross_revenue_excl_shipping_activating,
    lymtd_product_gross_revenue_excl_shipping_nonactivating,
    lymtd_product_gross_revenue_excl_shipping_repeat,
    lymtd_product_gross_revenue_excl_shipping_guest,
    lymtd_total_product_margin_pre_return_excl_shipping,
    lymtd_product_margin_pre_return_excl_shipping_activating,
    lymtd_product_margin_pre_return_excl_shipping_nonactivating,
    lymtd_product_margin_pre_return_excl_shipping_repeat,
    lymtd_product_margin_pre_return_excl_shipping_guest,
    lymtd_total_product_cost,
    lymtd_product_cost_activating,
    lymtd_product_cost_nonactivating,
    lymtd_product_cost_repeat,
    lymtd_product_cost_guest,
    lymtd_total_product_cost_c,
    lymtd_product_cost_activating_c,
    lymtd_product_cost_nonactivating_c,
    lymtd_product_cost_repeat_c,
    lymtd_product_cost_guest_c,
    lymtd_total_non_reduced_vip_price,
    lymtd_non_reduced_vip_price_activating,
    lymtd_non_reduced_vip_price_nonactivating,
    lymtd_non_reduced_vip_price_repeat,
    lymtd_non_reduced_vip_price_guest,
    meta_create_datetime,
    meta_update_datetime
)
WITH _dim_date_week AS (
    SELECT date_key,
        full_date,
        week_of_year
    FROM data_model.dim_date
    WHERE day_of_week = 1
),
_dim_date_base AS (
    SELECT date_key,
        full_date,
        week_of_year,
        LEAD(full_date, 1) OVER(ORDER BY full_date) AS next_week
    FROM _dim_date_week
),
_period AS (
    SELECT 'Weekly' AS source,
        dd.full_date,
        ddo.full_date AS start_date,
        DATEADD(DAY, -1, ddo.next_week) AS end_date
    FROM data_model.dim_date dd
    JOIN _dim_date_base ddo ON dd.full_date >= ddo.full_date
        AND dd.full_date < ddo.next_week
    WHERE dd.full_date >= '2019-01-01'
        AND dd.full_date < CURRENT_DATE()

    UNION ALL

    SELECT 'Monthly' AS source,
        full_date,
        month_date AS start_date,
        IFF(DATEADD('day', -1, DATEADD('month', 1, month_date)) > CURRENT_DATE() - 1, CURRENT_DATE() - 1, DATEADD('day', -1, DATEADD('month', 1, month_date))) AS end_date
    FROM data_model.dim_date
    WHERE full_date >= '2019-01-01'
        AND full_date < CURRENT_DATE()

    UNION ALL

    SELECT 'Quarterly' AS source, full_date, DATE_TRUNC('quarter', full_date) AS start_date,
        IFF(DATEADD('day', -1, DATEADD('quarter', 1, start_date)) > CURRENT_DATE() - 1, CURRENT_DATE() - 1, DATEADD('day', -1, DATEADD('quarter', 1, start_date))) AS end_date
    FROM data_model.dim_date
    WHERE full_date >= '2019-01-01'
        AND full_date < CURRENT_DATE()

    UNION ALL

    SELECT 'Yearly' AS source,
        full_date,
        DATE_TRUNC('year', full_date) AS start_date,
        IFF(DATEADD('day', -1, DATEADD('year', 1, start_date)) > CURRENT_DATE() - 1, CURRENT_DATE() - 1, DATEADD('day', -1, DATEADD('year', 1, start_date))) AS end_date
    FROM data_model.dim_date
    WHERE full_date >= '2019-01-01'
        AND full_date < CURRENT_DATE()
)
SELECT p.start_date AS date,
    p.source AS period,
    date_type,
    store_id,
    store_name,
    store_full_name,
    store_brand,
    product_brand,
    store_type,
    country,
    finance_specialty_store,
    region,
    is_retail,
    bundle_name,
    bundle_alias,
    SUM(ty_total_bundle_count) AS ty_total_bundle_count,
    SUM(ty_bundle_count_activating) AS ty_bundle_count_activating,
    SUM(ty_bundle_count_nonactivating) AS ty_bundle_count_nonactivating,
    SUM(ty_bundle_count_repeat) AS ty_bundle_count_repeat,
    SUM(ty_bundle_count_guest) AS ty_bundle_count_guest,
    SUM(ty_total_product_subtotal) AS ty_total_product_subtotal,
    SUM(ty_product_subtotal_activating) AS ty_product_subtotal_activating,
    SUM(ty_product_subtotal_nonactivating) AS ty_product_subtotal_nonactivating,
    SUM(ty_product_subtotal_repeat) AS ty_product_subtotal_repeat,
    SUM(ty_product_subtotal_guest) AS ty_product_subtotal_guest,
    SUM(ty_total_product_discount) AS ty_total_product_discount,
    SUM(ty_product_discount_activating) AS ty_product_discount_activating,
    SUM(ty_product_discount_nonactivating) AS ty_product_discount_nonactivating,
    SUM(ty_product_discount_repeat) AS ty_product_discount_repeat,
    SUM(ty_product_discount_guest) AS ty_product_discount_guest,
    SUM(ty_total_product_gross_revenue_excl_shipping) AS ty_total_product_gross_revenue_excl_shipping,
    SUM(ty_product_gross_revenue_excl_shipping_activating) AS ty_product_gross_revenue_excl_shipping_activating,
    SUM(ty_product_gross_revenue_excl_shipping_nonactivating) AS ty_product_gross_revenue_excl_shipping_nonactivating,
    SUM(ty_product_gross_revenue_excl_shipping_repeat) AS ty_product_gross_revenue_excl_shipping_repeat,
    SUM(ty_product_gross_revenue_excl_shipping_guest) AS ty_product_gross_revenue_excl_shipping_guest,
    SUM(ty_total_product_margin_pre_return_excl_shipping) AS ty_total_product_margin_pre_return_excl_shipping,
    SUM(ty_product_margin_pre_return_excl_shipping_activating) AS ty_product_margin_pre_return_excl_shipping_activating,
    SUM(ty_product_margin_pre_return_excl_shipping_nonactivating) AS ty_product_margin_pre_return_excl_shipping_nonactivating,
    SUM(ty_product_margin_pre_return_excl_shipping_repeat) AS ty_product_margin_pre_return_excl_shipping_repeat,
    SUM(ty_product_margin_pre_return_excl_shipping_guest) AS ty_product_margin_pre_return_excl_shipping_guest,
    SUM(ty_total_product_cost) AS ty_total_product_cost,
    SUM(ty_product_cost_activating) AS ty_product_cost_activating,
    SUM(ty_product_cost_nonactivating) AS ty_product_cost_nonactivating,
    SUM(ty_product_cost_repeat) AS ty_product_cost_repeat,
    SUM(ty_product_cost_guest) AS ty_product_cost_guest,

    SUM(ty_total_product_cost_c) AS ty_total_product_cost_c,
    SUM(ty_product_cost_activating_c) AS ty_product_cost_activating_c,
    SUM(ty_product_cost_nonactivating_c) AS ty_product_cost_nonactivating_c,
    SUM(ty_product_cost_repeat_c) AS ty_product_cost_repeat_c,
    SUM(ty_product_cost_guest_c) AS ty_product_cost_guest_c,

    SUM(ty_total_non_reduced_vip_price) AS ty_total_non_reduced_vip_price,
    SUM(ty_non_reduced_vip_price_activating) AS ty_non_reduced_vip_price_activating,
    SUM(ty_non_reduced_vip_price_nonactivating) AS ty_non_reduced_vip_price_nonactivating,
    SUM(ty_non_reduced_vip_price_repeat) AS ty_non_reduced_vip_price_repeat,
    SUM(ty_non_reduced_vip_price_guest) AS ty_non_reduced_vip_price_guest,
    SUM(IFF(ops.date = p.end_date, ltd_total_bundle_count, 0)) AS ltd_total_bundle_count,
    SUM(IFF(ops.date = p.end_date, ltd_bundle_count_activating, 0)) AS ltd_bundle_count_activating,
    SUM(IFF(ops.date = p.end_date, ltd_bundle_count_nonactivating, 0)) AS ltd_bundle_count_nonactivating,
    SUM(IFF(ops.date = p.end_date, ltd_bundle_count_repeat, 0)) AS ltd_bundle_count_repeat,
    SUM(IFF(ops.date = p.end_date, ltd_bundle_count_guest, 0)) AS ltd_bundle_count_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_bundle_count, 0)) AS mtd_total_bundle_count,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_bundle_count_activating, 0)) AS mtd_bundle_count_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_bundle_count_nonactivating, 0)) AS mtd_bundle_count_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_bundle_count_repeat, 0)) AS mtd_bundle_count_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_bundle_count_guest, 0)) AS mtd_bundle_count_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_product_subtotal, 0)) AS mtd_total_product_subtotal,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_subtotal_activating, 0)) AS mtd_product_subtotal_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_subtotal_nonactivating, 0)) AS mtd_product_subtotal_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_subtotal_repeat, 0)) AS mtd_product_subtotal_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_subtotal_guest, 0)) AS mtd_product_subtotal_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_product_discount, 0)) AS mtd_total_product_discount,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_discount_activating, 0)) AS mtd_product_discount_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_discount_nonactivating, 0)) AS mtd_product_discount_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_discount_repeat, 0)) AS mtd_product_discount_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_discount_guest, 0)) AS mtd_product_discount_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_product_gross_revenue_excl_shipping, 0)) AS mtd_total_product_gross_revenue_excl_shipping,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_gross_revenue_excl_shipping_activating, 0)) AS mtd_product_gross_revenue_excl_shipping_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_gross_revenue_excl_shipping_nonactivating, 0)) AS mtd_product_gross_revenue_excl_shipping_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_gross_revenue_excl_shipping_repeat, 0)) AS mtd_product_gross_revenue_excl_shipping_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_gross_revenue_excl_shipping_guest, 0)) AS mtd_product_gross_revenue_excl_shipping_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_product_margin_pre_return_excl_shipping, 0)) AS mtd_total_product_margin_pre_return_excl_shipping,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_margin_pre_return_excl_shipping_activating, 0)) AS mtd_product_margin_pre_return_excl_shipping_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_margin_pre_return_excl_shipping_nonactivating, 0)) AS mtd_product_margin_pre_return_excl_shipping_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_margin_pre_return_excl_shipping_repeat, 0)) AS mtd_product_margin_pre_return_excl_shipping_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_margin_pre_return_excl_shipping_guest, 0)) AS mtd_product_margin_pre_return_excl_shipping_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_product_cost, 0)) AS mtd_total_product_cost,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_activating, 0)) AS mtd_product_cost_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_nonactivating, 0)) AS mtd_product_cost_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_repeat, 0)) AS mtd_product_cost_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_guest, 0)) AS mtd_product_cost_guest,

    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_product_cost_c, 0)) AS mtd_total_product_cost_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_activating_c, 0)) AS mtd_product_cost_activating_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_nonactivating_c, 0)) AS mtd_product_cost_nonactivating_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_repeat_c, 0)) AS mtd_product_cost_repeat_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_product_cost_guest_c, 0)) AS mtd_product_cost_guest_c,

    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_total_non_reduced_vip_price, 0)) AS mtd_total_non_reduced_vip_price,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_non_reduced_vip_price_activating, 0)) AS mtd_non_reduced_vip_price_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_non_reduced_vip_price_nonactivating, 0)) AS mtd_non_reduced_vip_price_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_non_reduced_vip_price_repeat, 0)) AS mtd_non_reduced_vip_price_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', mtd_non_reduced_vip_price_guest, 0)) AS mtd_non_reduced_vip_price_guest,
    SUM(IFF(p.source = 'Weekly', ly_day_total_bundle_count, ly_date_total_bundle_count)) AS ly_total_bundle_count,
    SUM(IFF(p.source = 'Weekly', ly_day_bundle_count_activating, ly_date_bundle_count_activating)) AS ly_bundle_count_activating,
    SUM(IFF(p.source = 'Weekly', ly_day_bundle_count_nonactivating, ly_date_bundle_count_nonactivating)) AS ly_bundle_count_nonactivating,
    SUM(IFF(p.source = 'Weekly', ly_day_bundle_count_repeat, ly_date_bundle_count_repeat)) AS ly_bundle_count_repeat,
    SUM(IFF(p.source = 'Weekly', ly_day_bundle_count_guest, ly_date_bundle_count_guest)) AS ly_bundle_count_guest,
    SUM(IFF(p.source = 'Weekly', ly_day_total_product_subtotal, ly_date_total_product_subtotal)) AS ly_total_product_subtotal,
    SUM(IFF(p.source = 'Weekly', ly_day_product_subtotal_activating, ly_date_product_subtotal_activating)) AS ly_product_subtotal_activating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_subtotal_nonactivating, ly_date_product_subtotal_nonactivating)) AS ly_product_subtotal_nonactivating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_subtotal_repeat, ly_date_product_subtotal_repeat)) AS ly_product_subtotal_repeat,
    SUM(IFF(p.source = 'Weekly', ly_day_product_subtotal_guest, ly_date_product_subtotal_guest)) AS ly_product_subtotal_guest,
    SUM(IFF(p.source = 'Weekly', ly_day_total_product_discount, ly_date_total_product_discount)) AS ly_total_product_discount,
    SUM(IFF(p.source = 'Weekly', ly_day_product_discount_activating, ly_date_product_discount_activating)) AS ly_product_discount_activating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_discount_nonactivating, ly_date_product_discount_nonactivating)) AS ly_product_discount_nonactivating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_discount_repeat, ly_date_product_discount_repeat)) AS ly_product_discount_repeat,
    SUM(IFF(p.source = 'Weekly', ly_day_product_discount_guest, ly_date_product_discount_guest)) AS ly_product_discount_guest,
    SUM(IFF(p.source = 'Weekly', ly_day_total_product_gross_revenue_excl_shipping, ly_date_total_product_gross_revenue_excl_shipping)) AS ly_total_product_gross_revenue_excl_shipping,
    SUM(IFF(p.source = 'Weekly', ly_day_product_gross_revenue_excl_shipping_activating, ly_date_product_gross_revenue_excl_shipping_activating)) AS ly_product_gross_revenue_excl_shipping_activating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_gross_revenue_excl_shipping_nonactivating, ly_date_product_gross_revenue_excl_shipping_nonactivating)) AS ly_product_gross_revenue_excl_shipping_nonactivating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_gross_revenue_excl_shipping_repeat, ly_date_product_gross_revenue_excl_shipping_repeat)) AS ly_product_gross_revenue_excl_shipping_repeat,
    SUM(IFF(p.source = 'Weekly', ly_day_product_gross_revenue_excl_shipping_guest, ly_date_product_gross_revenue_excl_shipping_guest)) AS ly_product_gross_revenue_excl_shipping_guest,
    SUM(IFF(p.source = 'Weekly', ly_day_total_product_margin_pre_return_excl_shipping, ly_date_total_product_margin_pre_return_excl_shipping)) AS ly_total_product_margin_pre_return_excl_shipping,
    SUM(IFF(p.source = 'Weekly', ly_day_product_margin_pre_return_excl_shipping_activating, ly_date_product_margin_pre_return_excl_shipping_activating)) AS ly_product_margin_pre_return_excl_shipping_activating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_margin_pre_return_excl_shipping_nonactivating, ly_date_product_margin_pre_return_excl_shipping_nonactivating)) AS ly_product_margin_pre_return_excl_shipping_nonactivating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_margin_pre_return_excl_shipping_repeat, ly_date_product_margin_pre_return_excl_shipping_repeat)) AS ly_product_margin_pre_return_excl_shipping_repeat,
    SUM(IFF(p.source = 'Weekly', ly_day_product_margin_pre_return_excl_shipping_guest, ly_date_product_margin_pre_return_excl_shipping_guest)) AS ly_product_margin_pre_return_excl_shipping_guest,
    SUM(IFF(p.source = 'Weekly', ly_day_total_product_cost, ly_date_total_product_cost)) AS ly_total_product_cost,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_activating, ly_date_product_cost_activating)) AS ly_product_cost_activating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_nonactivating, ly_date_product_cost_nonactivating)) AS ly_product_cost_nonactivating,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_repeat, ly_date_product_cost_repeat)) AS ly_product_cost_repeat,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_guest, ly_date_product_cost_guest)) AS ly_product_cost_guest,

    SUM(IFF(p.source = 'Weekly', ly_day_total_product_cost_c, ly_date_total_product_cost_c)) AS ly_total_product_cost_c,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_activating_c, ly_date_product_cost_activating_c)) AS ly_product_cost_activating_c,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_nonactivating_c, ly_date_product_cost_nonactivating_c)) AS ly_product_cost_nonactivating_c,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_repeat_c, ly_date_product_cost_repeat_c)) AS ly_product_cost_repeat_c,
    SUM(IFF(p.source = 'Weekly', ly_day_product_cost_guest_c, ly_date_product_cost_guest_c)) AS ly_product_cost_guest_c,

    SUM(IFF(p.source = 'Weekly', ly_day_total_non_reduced_vip_price, ly_date_total_non_reduced_vip_price)) AS ly_total_non_reduced_vip_price,
    SUM(IFF(p.source = 'Weekly', ly_day_non_reduced_vip_price_activating, ly_date_non_reduced_vip_price_activating)) AS ly_non_reduced_vip_price_activating,
    SUM(IFF(p.source = 'Weekly', ly_day_non_reduced_vip_price_nonactivating, ly_date_non_reduced_vip_price_nonactivating)) AS ly_non_reduced_vip_price_nonactivating,
    SUM(IFF(p.source = 'Weekly', ly_day_non_reduced_vip_price_repeat, ly_date_non_reduced_vip_price_repeat)) AS ly_non_reduced_vip_price_repeat,
    SUM(IFF(p.source = 'Weekly', ly_day_non_reduced_vip_price_guest, ly_date_non_reduced_vip_price_guest)) AS ly_non_reduced_vip_price_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_bundle_count, 0)) AS lymtd_total_bundle_count,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_bundle_count_activating, 0)) AS lymtd_bundle_count_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_bundle_count_nonactivating, 0)) AS lymtd_bundle_count_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_bundle_count_repeat, 0)) AS lymtd_bundle_count_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_bundle_count_guest, 0)) AS lymtd_bundle_count_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_product_subtotal, 0)) AS lymtd_total_product_subtotal,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_subtotal_activating, 0)) AS lymtd_product_subtotal_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_subtotal_nonactivating, 0)) AS lymtd_product_subtotal_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_subtotal_repeat, 0)) AS lymtd_product_subtotal_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_subtotal_guest, 0)) AS lymtd_product_subtotal_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_product_discount, 0)) AS lymtd_total_product_discount,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_discount_activating, 0)) AS lymtd_product_discount_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_discount_nonactivating, 0)) AS lymtd_product_discount_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_discount_repeat, 0)) AS lymtd_product_discount_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_discount_guest, 0)) AS lymtd_product_discount_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_product_gross_revenue_excl_shipping, 0)) AS lymtd_total_product_gross_revenue_excl_shipping,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_gross_revenue_excl_shipping_activating, 0)) AS lymtd_product_gross_revenue_excl_shipping_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_gross_revenue_excl_shipping_nonactivating, 0)) AS lymtd_product_gross_revenue_excl_shipping_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_gross_revenue_excl_shipping_repeat, 0)) AS lymtd_product_gross_revenue_excl_shipping_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_gross_revenue_excl_shipping_guest, 0)) AS lymtd_product_gross_revenue_excl_shipping_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_product_margin_pre_return_excl_shipping, 0)) AS lymtd_total_product_margin_pre_return_excl_shipping,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_margin_pre_return_excl_shipping_activating, 0)) AS lymtd_product_margin_pre_return_excl_shipping_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_margin_pre_return_excl_shipping_nonactivating, 0)) AS lymtd_product_margin_pre_return_excl_shipping_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_margin_pre_return_excl_shipping_repeat, 0)) AS lymtd_product_margin_pre_return_excl_shipping_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_margin_pre_return_excl_shipping_guest, 0)) AS lymtd_product_margin_pre_return_excl_shipping_guest,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_product_cost, 0)) AS lymtd_total_product_cost,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_activating, 0)) AS lymtd_product_cost_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_nonactivating, 0)) AS lymtd_product_cost_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_repeat, 0)) AS lymtd_product_cost_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_guest, 0)) AS lymtd_product_cost_guest,

    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_product_cost_c, 0)) AS lymtd_total_product_cost_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_activating_c, 0)) AS lymtd_product_cost_activating_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_nonactivating_c, 0)) AS lymtd_product_cost_nonactivating_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_repeat_c, 0)) AS lymtd_product_cost_repeat_c,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_product_cost_guest_c, 0)) AS lymtd_product_cost_guest_c,

    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_total_non_reduced_vip_price, 0)) AS lymtd_total_non_reduced_vip_price,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_non_reduced_vip_price_activating, 0)) AS lymtd_non_reduced_vip_price_activating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_non_reduced_vip_price_nonactivating, 0)) AS lymtd_non_reduced_vip_price_nonactivating,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_non_reduced_vip_price_repeat, 0)) AS lymtd_non_reduced_vip_price_repeat,
    SUM(IFF(ops.date = p.end_date AND p.source = 'Weekly', lymtd_day_non_reduced_vip_price_guest, 0)) AS lymtd_non_reduced_vip_price_guest,
    MAX(meta_create_datetime) AS meta_create_datetime,
    MAX(meta_update_datetime) AS meta_update_datetime
FROM reporting.merch_planning_outfit ops
JOIN _period p ON p.full_date = ops.date
WHERE store_brand IN ('FABLETICS', 'SAVAGE X', 'YITTY')
GROUP BY p.start_date,
    p.source,
    date_type,
    store_id,
    store_name,
    store_full_name,
    store_brand,
    product_brand,
    store_type,
    country,
    finance_specialty_store,
    region,
    is_retail,
    bundle_name,
    bundle_alias;
