ALTER SESSION SET QUERY_TAG ='finance_sales_ops_snapshot_process';

SET execution_start_time = CURRENT_TIMESTAMP::TIMESTAMP_LTZ(3);

CREATE OR REPLACE TEMP TABLE _aggregated_fso AS
SELECT ds.store_brand,
       ds.store_country,
       ds.store_region,
       ds.store_type,
       fso.gender,
       fso.is_retail_vip,
       fso.is_cross_promo,
       fso.finance_specialty_store,
       domc.membership_order_type_l3,
       fso.date,
       fso.date_object,
       fso.currency_object,
       fso.currency_type,
       SUM(product_order_subtotal_excl_tariff_amount)                AS product_order_subtotal_excl_tariff_amount,
       SUM(product_order_tariff_amount)                              AS product_order_tariff_amount,
       SUM(product_order_product_subtotal_amount)                    AS product_order_product_subtotal_amount,
       SUM(product_order_product_discount_amount)                    AS product_order_product_discount_amount,
       SUM(product_order_shipping_discount_amount)                   AS product_order_shipping_discount_amount,
       SUM(product_order_shipping_revenue_before_discount_amount)    AS product_order_shipping_revenue_before_discount_amount,
       SUM(product_order_shipping_revenue_amount)                    AS product_order_shipping_revenue_amount,
       SUM(product_order_tax_amount)                                 AS product_order_tax_amount,
       SUM(product_order_cash_transaction_amount)                    AS product_order_cash_transaction_amount,
       SUM(product_order_cash_credit_redeemed_amount)                AS product_order_cash_credit_redeemed_amount,
       SUM(product_order_noncash_credit_redeemed_amount)             AS product_order_noncash_credit_redeemed_amount,
       SUM(product_order_count)                                      AS product_order_count,
       SUM(product_order_count_excl_seeding)                         AS product_order_count_excl_seeding,
       SUM(product_order_unit_count)                                 AS product_order_unit_count,
       SUM(product_order_loyalty_unit_count)                         AS product_order_loyalty_unit_count,
       SUM(product_order_outfit_component_unit_count)                AS product_order_outfit_component_unit_count,
       SUM(product_order_outfit_count)                               AS product_order_outfit_count,
       SUM(product_order_discounted_unit_count)                      AS product_order_discounted_unit_count,
       SUM(product_order_zero_revenue_unit_count)                    AS product_order_zero_revenue_unit_count,
       SUM(product_order_landed_product_cost_amount)                 AS product_order_landed_product_cost_amount,
       SUM(product_order_shipping_cost_amount)                       AS product_order_shipping_cost_amount,
       SUM(product_order_shipping_supplies_cost_amount)              AS product_order_shipping_supplies_cost_amount,
       SUM(product_order_misc_cogs_amount)                           AS product_order_misc_cogs_amount,
       SUM(product_order_direct_cogs_amount)                         AS product_order_direct_cogs_amount,
       SUM(product_order_cash_refund_amount)                         AS product_order_cash_refund_amount,
       SUM(product_order_cash_credit_refund_amount)                  AS product_order_cash_credit_refund_amount,
       SUM(product_order_noncash_credit_refund_amount)               AS product_order_noncash_credit_refund_amount,
       SUM(product_order_cash_chargeback_amount)                     AS product_order_cash_chargeback_amount,
       SUM(product_order_cost_product_returned_resaleable_amount)    AS product_order_cost_product_returned_resaleable_amount,
       SUM(product_order_cost_product_returned_damaged_amount)       AS product_order_cost_product_returned_damaged_amount,
       SUM(product_order_return_shipping_cost_amount)                AS product_order_return_shipping_cost_amount,
       SUM(product_order_return_unit_count)                          AS product_order_return_unit_count,
       SUM(product_order_reship_order_count)                         AS product_order_reship_order_count,
       SUM(product_order_reship_unit_count)                          AS product_order_reship_unit_count,
       SUM(product_order_reship_direct_cogs_amount)                  AS product_order_reship_direct_cogs_amount,
       SUM(product_order_reship_product_cost_amount)                 AS product_order_reship_product_cost_amount,
       SUM(product_order_reship_shipping_cost_amount)                AS product_order_reship_shipping_cost_amount,
       SUM(product_order_reship_shipping_supplies_cost_amount)       AS product_order_reship_shipping_supplies_cost_amount,
       SUM(product_order_exchange_order_count)                       AS product_order_exchange_order_count,
       SUM(product_order_exchange_unit_count)                        AS product_order_exchange_unit_count,
       SUM(product_order_exchange_direct_cogs_amount)                AS product_order_exchange_direct_cogs_amount,
       SUM(product_order_exchange_product_cost_amount)               AS product_order_exchange_product_cost_amount,
       SUM(product_order_exchange_shipping_cost_amount)              AS product_order_exchange_shipping_cost_amount,
       SUM(product_order_exchange_shipping_supplies_cost_amount)     AS product_order_exchange_shipping_supplies_cost_amount,
       SUM(product_order_selling_expenses_amount)                    AS product_order_selling_expenses_amount,
       SUM(product_order_payment_processing_cost_amount)             AS product_order_payment_processing_cost_amount,
       SUM(product_order_variable_gms_cost_amount)                   AS product_order_variable_gms_cost_amount,
       SUM(product_order_variable_warehouse_cost_amount)             AS product_order_variable_warehouse_cost_amount,
       SUM(billing_selling_expenses_amount)                          AS billing_selling_expenses_amount,
       SUM(billing_payment_processing_cost_amount)                   AS billing_payment_processing_cost_amount,
       SUM(billing_variable_gms_cost_amount)                         AS billing_variable_gms_cost_amount,
       SUM(product_order_amount_to_pay)                              AS product_order_amount_to_pay,
       SUM(product_gross_revenue_excl_shipping)                      AS product_gross_revenue_excl_shipping,
       SUM(product_gross_revenue)                                    AS product_gross_revenue,
       SUM(product_net_revenue)                                      AS product_net_revenue,
       SUM(product_margin_pre_return)                                AS product_margin_pre_return,
       SUM(product_margin_pre_return_excl_seeding)                   AS product_margin_pre_return_excl_seeding,
       SUM(product_margin_pre_return_excl_shipping)                  AS product_margin_pre_return_excl_shipping,
       SUM(product_gross_profit)                                     AS product_gross_profit,
       SUM(product_variable_contribution_profit)                     AS product_variable_contribution_profit,
       SUM(product_order_cash_gross_revenue_amount)                  AS product_order_cash_gross_revenue_amount,
       SUM(product_order_cash_net_revenue)                           AS product_order_cash_net_revenue,
       SUM(product_order_cash_margin_pre_return)                     AS product_order_cash_margin_pre_return,
       SUM(product_order_cash_gross_profit)                          AS product_order_cash_gross_profit,
       SUM(billing_cash_gross_revenue)                               AS billing_cash_gross_revenue,
       SUM(billing_cash_net_revenue)                                 AS billing_cash_net_revenue,
       SUM(cash_gross_revenue)                                       AS cash_gross_revenue,
       SUM(cash_net_revenue)                                         AS cash_net_revenue,
       SUM(cash_gross_profit)                                        AS cash_gross_profit,
       SUM(cash_variable_contribution_profit)                        AS cash_variable_contribution_profit,
       SUM(billing_order_transaction_count)                          AS billing_order_transaction_count,
       SUM(billed_credit_cash_transaction_count)                     AS billed_credit_cash_transaction_count,
       SUM(on_retry_billed_credit_cash_transaction_count)            AS on_retry_billed_credit_cash_transaction_count,
       SUM(billing_cash_refund_amount)                               AS billing_cash_refund_amount,
       SUM(billing_cash_chargeback_amount)                           AS billing_cash_chargeback_amount,
       SUM(billed_credit_cash_transaction_amount)                    AS billed_credit_cash_transaction_amount,
       SUM(membership_fee_cash_transaction_amount)                   AS membership_fee_cash_transaction_amount,
       SUM(gift_card_transaction_amount)                             AS gift_card_transaction_amount,
       SUM(legacy_credit_cash_transaction_amount)                    AS legacy_credit_cash_transaction_amount,
       SUM(billed_credit_cash_refund_count)                          AS billed_credit_cash_refund_count,
       SUM(billed_credit_cash_refund_chargeback_amount)              AS billed_credit_cash_refund_chargeback_amount,
       SUM(membership_fee_cash_refund_chargeback_amount)             AS membership_fee_cash_refund_chargeback_amount,
       SUM(gift_card_cash_refund_chargeback_amount)                  AS gift_card_cash_refund_chargeback_amount,
       SUM(legacy_credit_cash_refund_chargeback_amount)              AS legacy_credit_cash_refund_chargeback_amount,
       SUM(billed_cash_credit_issued_amount)                         AS billed_cash_credit_issued_amount,
       SUM(billed_cash_credit_redeemed_amount)                       AS billed_cash_credit_redeemed_amount,
       SUM(billed_cash_credit_cancelled_amount)                      AS billed_cash_credit_cancelled_amount,
       SUM(billed_cash_credit_expired_amount)                        AS billed_cash_credit_expired_amount,
       SUM(billed_cash_credit_issued_equivalent_count)               AS billed_cash_credit_issued_equivalent_count,
       SUM(billed_cash_credit_redeemed_same_month_amount)            AS billed_cash_credit_redeemed_same_month_amount,
       SUM(billed_cash_credit_redeemed_equivalent_count)             AS billed_cash_credit_redeemed_equivalent_count,
       SUM(billed_cash_credit_cancelled_equivalent_count)            AS billed_cash_credit_cancelled_equivalent_count,
       SUM(billed_cash_credit_expired_equivalent_count)              AS billed_cash_credit_expired_equivalent_count,
       SUM(refund_cash_credit_issued_amount)                         AS refund_cash_credit_issued_amount,
       SUM(refund_cash_credit_redeemed_amount)                       AS refund_cash_credit_redeemed_amount,
       SUM(refund_cash_credit_cancelled_amount)                      AS refund_cash_credit_cancelled_amount,
       SUM(refund_cash_credit_expired_amount)                        AS refund_cash_credit_expired_amount,
       SUM(other_cash_credit_issued_amount)                          AS other_cash_credit_issued_amount,
       SUM(other_cash_credit_redeemed_amount)                        AS other_cash_credit_redeemed_amount,
       SUM(other_cash_credit_cancelled_amount)                       AS other_cash_credit_cancelled_amount,
       SUM(other_cash_credit_expired_amount)                         AS other_cash_credit_expired_amount,
       SUM(noncash_credit_issued_amount)                             AS noncash_credit_issued_amount,
       SUM(noncash_credit_cancelled_amount)                          AS noncash_credit_cancelled_amount,
       SUM(noncash_credit_expired_amount)                            AS noncash_credit_expired_amount,
       SUM(retail_ship_only_product_order_count)                     AS retail_ship_only_product_order_count,
       SUM(retail_ship_only_product_order_unit_count)                AS retail_ship_only_product_order_unit_count,
       SUM(retail_ship_only_product_gross_revenue)                   AS retail_ship_only_product_gross_revenue,
       SUM(retail_ship_only_product_gross_revenue_excl_shipping)     AS retail_ship_only_product_gross_revenue_excl_shipping,
       SUM(retail_ship_only_product_margin_pre_return)               AS retail_ship_only_product_margin_pre_return,
       SUM(retail_ship_only_product_margin_pre_return_excl_shipping) AS retail_ship_only_product_margin_pre_return_excl_shipping,
       SUM(retail_ship_only_product_order_cash_margin_pre_return)    AS retail_ship_only_product_order_cash_margin_pre_return,
       SUM(retail_ship_only_product_order_cash_gross_revenue)        AS retail_ship_only_product_order_cash_gross_revenue,
       SUM(retail_ship_only_product_net_revenue)                     AS retail_ship_only_product_net_revenue,
       SUM(retail_ship_only_product_gross_profit)                    AS retail_ship_only_product_gross_profit,
       SUM(retail_ship_only_product_order_cash_net_revenue)          AS retail_ship_only_product_order_cash_net_revenue,
       SUM(retail_ship_only_product_order_cash_gross_profit)         AS retail_ship_only_product_order_cash_gross_profit,
       SUM(product_order_reship_exchange_cash_gross_revenue)         AS product_order_reship_exchange_cash_gross_revenue,
       SUM(cash_gift_card_redeemed_amount)                           AS cash_gift_card_redeemed_amount
FROM analytics_base.finance_sales_ops fso
         JOIN stg.dim_store ds
                    ON fso.store_id = ds.store_id
         JOIN stg.dim_order_membership_classification domc
                    ON fso.order_membership_classification_key = domc.order_membership_classification_key
GROUP BY ds.store_brand,
         ds.store_country,
         ds.store_region,
         ds.store_type,
         fso.gender,
         fso.is_retail_vip,
         fso.is_cross_promo,
         fso.finance_specialty_store,
         domc.membership_order_type_l3,
         fso.date,
         fso.date_object,
         fso.currency_object,
         fso.currency_type;

INSERT INTO snapshot.finance_sales_ops(
       store_brand,
       store_country,
       store_region,
       store_type,
       gender,
       is_retail_vip,
       is_cross_promo,
       finance_specialty_store,
       membership_order_type_l3,
       date,
       date_object,
       currency_object,
       currency_type,
       product_order_subtotal_excl_tariff_amount,
       product_order_tariff_amount,
       product_order_product_subtotal_amount,
       product_order_product_discount_amount,
       product_order_shipping_discount_amount,
       product_order_shipping_revenue_before_discount_amount,
       product_order_shipping_revenue_amount,
       product_order_tax_amount,
       product_order_cash_transaction_amount,
       product_order_cash_credit_redeemed_amount,
       product_order_noncash_credit_redeemed_amount,
       product_order_count,
       product_order_count_excl_seeding,
       product_order_unit_count,
       product_order_loyalty_unit_count,
       product_order_outfit_component_unit_count,
       product_order_outfit_count,
       product_order_discounted_unit_count,
       product_order_zero_revenue_unit_count,
       product_order_landed_product_cost_amount,
       product_order_shipping_cost_amount,
       product_order_shipping_supplies_cost_amount,
       product_order_misc_cogs_amount,
       product_order_direct_cogs_amount,
       product_order_cash_refund_amount,
       product_order_cash_credit_refund_amount,
       product_order_noncash_credit_refund_amount,
       product_order_cash_chargeback_amount,
       product_order_cost_product_returned_resaleable_amount,
       product_order_cost_product_returned_damaged_amount,
       product_order_return_shipping_cost_amount,
       product_order_return_unit_count,
       product_order_reship_order_count,
       product_order_reship_unit_count,
       product_order_reship_direct_cogs_amount,
       product_order_reship_product_cost_amount,
       product_order_reship_shipping_cost_amount,
       product_order_reship_shipping_supplies_cost_amount,
       product_order_exchange_order_count,
       product_order_exchange_unit_count,
       product_order_exchange_direct_cogs_amount,
       product_order_exchange_product_cost_amount,
       product_order_exchange_shipping_cost_amount,
       product_order_exchange_shipping_supplies_cost_amount,
       product_order_selling_expenses_amount,
       product_order_payment_processing_cost_amount,
       product_order_variable_gms_cost_amount,
       product_order_variable_warehouse_cost_amount,
       billing_selling_expenses_amount,
       billing_payment_processing_cost_amount,
       billing_variable_gms_cost_amount,
       product_order_amount_to_pay,
       product_gross_revenue_excl_shipping,
       product_gross_revenue,
       product_net_revenue,
       product_margin_pre_return,
       product_margin_pre_return_excl_seeding,
       product_margin_pre_return_excl_shipping,
       product_gross_profit,
       product_variable_contribution_profit,
       product_order_cash_gross_revenue_amount,
       product_order_cash_net_revenue,
       product_order_cash_margin_pre_return,
       product_order_cash_gross_profit,
       billing_cash_gross_revenue,
       billing_cash_net_revenue,
       cash_gross_revenue,
       cash_net_revenue,
       cash_gross_profit,
       cash_variable_contribution_profit,
       billing_order_transaction_count,
       billed_credit_cash_transaction_count,
       on_retry_billed_credit_cash_transaction_count,
       billing_cash_refund_amount,
       billing_cash_chargeback_amount,
       billed_credit_cash_transaction_amount,
       membership_fee_cash_transaction_amount,
       gift_card_transaction_amount,
       legacy_credit_cash_transaction_amount,
       billed_credit_cash_refund_count,
       billed_credit_cash_refund_chargeback_amount,
       membership_fee_cash_refund_chargeback_amount,
       gift_card_cash_refund_chargeback_amount,
       legacy_credit_cash_refund_chargeback_amount,
       billed_cash_credit_issued_amount,
       billed_cash_credit_redeemed_amount,
       billed_cash_credit_cancelled_amount,
       billed_cash_credit_expired_amount,
       billed_cash_credit_issued_equivalent_count,
       billed_cash_credit_redeemed_same_month_amount,
       billed_cash_credit_redeemed_equivalent_count,
       billed_cash_credit_cancelled_equivalent_count,
       billed_cash_credit_expired_equivalent_count,
       refund_cash_credit_issued_amount,
       refund_cash_credit_redeemed_amount,
       refund_cash_credit_cancelled_amount,
       refund_cash_credit_expired_amount,
       other_cash_credit_issued_amount,
       other_cash_credit_redeemed_amount,
       other_cash_credit_cancelled_amount,
       other_cash_credit_expired_amount,
       noncash_credit_issued_amount,
       noncash_credit_cancelled_amount,
       noncash_credit_expired_amount,
       retail_ship_only_product_order_count,
       retail_ship_only_product_order_unit_count,
       retail_ship_only_product_gross_revenue,
       retail_ship_only_product_gross_revenue_excl_shipping,
       retail_ship_only_product_margin_pre_return,
       retail_ship_only_product_margin_pre_return_excl_shipping,
       retail_ship_only_product_order_cash_margin_pre_return,
       retail_ship_only_product_order_cash_gross_revenue,
       retail_ship_only_product_net_revenue,
       retail_ship_only_product_gross_profit,
       retail_ship_only_product_order_cash_net_revenue,
       retail_ship_only_product_order_cash_gross_profit,
       product_order_reship_exchange_cash_gross_revenue,
       cash_gift_card_redeemed_amount,
       snapshot_datetime)
SELECT store_brand,
       store_country,
       store_region,
       store_type,
       gender,
       is_retail_vip,
       is_cross_promo,
       finance_specialty_store,
       membership_order_type_l3,
       date,
       date_object,
       currency_object,
       currency_type,
       product_order_subtotal_excl_tariff_amount,
       product_order_tariff_amount,
       product_order_product_subtotal_amount,
       product_order_product_discount_amount,
       product_order_shipping_discount_amount,
       product_order_shipping_revenue_before_discount_amount,
       product_order_shipping_revenue_amount,
       product_order_tax_amount,
       product_order_cash_transaction_amount,
       product_order_cash_credit_redeemed_amount,
       product_order_noncash_credit_redeemed_amount,
       product_order_count,
       product_order_count_excl_seeding,
       product_order_unit_count,
       product_order_loyalty_unit_count,
       product_order_outfit_component_unit_count,
       product_order_outfit_count,
       product_order_discounted_unit_count,
       product_order_zero_revenue_unit_count,
       product_order_landed_product_cost_amount,
       product_order_shipping_cost_amount,
       product_order_shipping_supplies_cost_amount,
       product_order_misc_cogs_amount,
       product_order_direct_cogs_amount,
       product_order_cash_refund_amount,
       product_order_cash_credit_refund_amount,
       product_order_noncash_credit_refund_amount,
       product_order_cash_chargeback_amount,
       product_order_cost_product_returned_resaleable_amount,
       product_order_cost_product_returned_damaged_amount,
       product_order_return_shipping_cost_amount,
       product_order_return_unit_count,
       product_order_reship_order_count,
       product_order_reship_unit_count,
       product_order_reship_direct_cogs_amount,
       product_order_reship_product_cost_amount,
       product_order_reship_shipping_cost_amount,
       product_order_reship_shipping_supplies_cost_amount,
       product_order_exchange_order_count,
       product_order_exchange_unit_count,
       product_order_exchange_direct_cogs_amount,
       product_order_exchange_product_cost_amount,
       product_order_exchange_shipping_cost_amount,
       product_order_exchange_shipping_supplies_cost_amount,
       product_order_selling_expenses_amount,
       product_order_payment_processing_cost_amount,
       product_order_variable_gms_cost_amount,
       product_order_variable_warehouse_cost_amount,
       billing_selling_expenses_amount,
       billing_payment_processing_cost_amount,
       billing_variable_gms_cost_amount,
       product_order_amount_to_pay,
       product_gross_revenue_excl_shipping,
       product_gross_revenue,
       product_net_revenue,
       product_margin_pre_return,
       product_margin_pre_return_excl_seeding,
       product_margin_pre_return_excl_shipping,
       product_gross_profit,
       product_variable_contribution_profit,
       product_order_cash_gross_revenue_amount,
       product_order_cash_net_revenue,
       product_order_cash_margin_pre_return,
       product_order_cash_gross_profit,
       billing_cash_gross_revenue,
       billing_cash_net_revenue,
       cash_gross_revenue,
       cash_net_revenue,
       cash_gross_profit,
       cash_variable_contribution_profit,
       billing_order_transaction_count,
       billed_credit_cash_transaction_count,
       on_retry_billed_credit_cash_transaction_count,
       billing_cash_refund_amount,
       billing_cash_chargeback_amount,
       billed_credit_cash_transaction_amount,
       membership_fee_cash_transaction_amount,
       gift_card_transaction_amount,
       legacy_credit_cash_transaction_amount,
       billed_credit_cash_refund_count,
       billed_credit_cash_refund_chargeback_amount,
       membership_fee_cash_refund_chargeback_amount,
       gift_card_cash_refund_chargeback_amount,
       legacy_credit_cash_refund_chargeback_amount,
       billed_cash_credit_issued_amount,
       billed_cash_credit_redeemed_amount,
       billed_cash_credit_cancelled_amount,
       billed_cash_credit_expired_amount,
       billed_cash_credit_issued_equivalent_count,
       billed_cash_credit_redeemed_same_month_amount,
       billed_cash_credit_redeemed_equivalent_count,
       billed_cash_credit_cancelled_equivalent_count,
       billed_cash_credit_expired_equivalent_count,
       refund_cash_credit_issued_amount,
       refund_cash_credit_redeemed_amount,
       refund_cash_credit_cancelled_amount,
       refund_cash_credit_expired_amount,
       other_cash_credit_issued_amount,
       other_cash_credit_redeemed_amount,
       other_cash_credit_cancelled_amount,
       other_cash_credit_expired_amount,
       noncash_credit_issued_amount,
       noncash_credit_cancelled_amount,
       noncash_credit_expired_amount,
       retail_ship_only_product_order_count,
       retail_ship_only_product_order_unit_count,
       retail_ship_only_product_gross_revenue,
       retail_ship_only_product_gross_revenue_excl_shipping,
       retail_ship_only_product_margin_pre_return,
       retail_ship_only_product_margin_pre_return_excl_shipping,
       retail_ship_only_product_order_cash_margin_pre_return,
       retail_ship_only_product_order_cash_gross_revenue,
       retail_ship_only_product_net_revenue,
       retail_ship_only_product_gross_profit,
       retail_ship_only_product_order_cash_net_revenue,
       retail_ship_only_product_order_cash_gross_profit,
       product_order_reship_exchange_cash_gross_revenue,
       cash_gift_card_redeemed_amount,
       $execution_start_time AS snapshot_datetime
FROM _aggregated_fso;
