ALTER SESSION SET QUERY_TAG = 'customer_lifetime_value_monthly_snapshot';
SET execution_start_time = CURRENT_TIMESTAMP::TIMESTAMP_LTZ(3);

CREATE OR REPLACE TEMP TABLE _aggregated_cltv AS
SELECT ds.store_brand,
       ds.store_country,
       ds.store_region,
       ds.store_type,
       clvm.gender,
       clvm.vip_cohort_month_date,
       clvm.month_date,
       clvm.is_retail_vip,
       clvm.is_cross_promo,
       clvm.finance_specialty_store,
       SUM(product_order_count)                                          AS product_order_count,
       SUM(online_product_order_count)                                   AS online_product_order_count,
       SUM(retail_product_order_count)                                   AS retail_product_order_count,
       SUM(mobile_app_product_order_count)                               AS mobile_app_product_order_count,
       SUM(product_order_unit_count)                                     AS product_order_unit_count,
       SUM(online_product_order_unit_count)                              AS online_product_order_unit_count,
       SUM(retail_product_order_unit_count)                              AS retail_product_order_unit_count,
       SUM(mobile_app_product_order_unit_count)                          AS mobile_app_product_order_unit_count,
       SUM(product_order_subtotal_excl_tariff_amount)                    AS product_order_subtotal_excl_tariff_amount,
       SUM(online_product_order_subtotal_excl_tariff_amount)             AS online_product_order_subtotal_excl_tariff_amount,
       SUM(retail_product_order_subtotal_excl_tariff_amount)             AS retail_product_order_subtotal_excl_tariff_amount,
       SUM(mobile_app_product_order_subtotal_excl_tariff_amount)         AS mobile_app_product_order_subtotal_excl_tariff_amount,
       SUM(product_order_product_discount_amount)                        AS product_order_product_discount_amount,
       SUM(online_product_order_product_discount_amount)                 AS online_product_order_product_discount_amount,
       SUM(retail_product_order_product_discount_amount)                 AS retail_product_order_product_discount_amount,
       SUM(mobile_app_product_order_product_discount_amount)             AS mobile_app_product_order_product_discount_amount,
       SUM(product_order_shipping_revenue_amount)                        AS product_order_shipping_revenue_amount,
       SUM(online_product_order_shipping_revenue_amount)                 AS online_product_order_shipping_revenue_amount,
       SUM(retail_product_order_shipping_revenue_amount)                 AS retail_product_order_shipping_revenue_amount,
       SUM(mobile_app_product_order_shipping_revenue_amount)             AS mobile_app_product_order_shipping_revenue_amount,
       SUM(product_order_direct_cogs_amount)                             AS product_order_direct_cogs_amount,
       SUM(online_product_order_direct_cogs_amount)                      AS online_product_order_direct_cogs_amount,
       SUM(retail_product_order_direct_cogs_amount)                      AS retail_product_order_direct_cogs_amount,
       SUM(mobile_app_product_order_direct_cogs_amount)                  AS mobile_app_product_order_direct_cogs_amount,
       SUM(product_order_selling_expenses_amount)                        AS product_order_selling_expenses_amount,
       SUM(online_product_order_selling_expenses_amount)                 AS online_product_order_selling_expenses_amount,
       SUM(retail_product_order_selling_expenses_amount)                 AS retail_product_order_selling_expenses_amount,
       SUM(mobile_app_product_order_selling_expenses_amount)             AS mobile_app_product_order_selling_expenses_amount,
       SUM(product_order_cash_refund_amount_and_chargeback_amount)       AS product_order_cash_refund_amount_and_chargeback_amount,
       SUM(online_product_order_cash_refund_chargeback_amount)           AS online_product_order_cash_refund_chargeback_amount,
       SUM(retail_product_order_cash_refund_chargeback_amount)           AS retail_product_order_cash_refund_chargeback_amount,
       SUM(mobile_app_product_order_cash_refund_chargeback_amount)       AS mobile_app_product_order_cash_refund_chargeback_amount,
       SUM(product_order_cash_credit_refund_amount)                      AS product_order_cash_credit_refund_amount,
       SUM(online_product_order_cash_credit_refund_amount)               AS online_product_order_cash_credit_refund_amount,
       SUM(retail_product_order_cash_credit_refund_amount)               AS retail_product_order_cash_credit_refund_amount,
       SUM(mobile_app_product_order_cash_credit_refund_amount)           AS mobile_app_product_order_cash_credit_refund_amount,
       SUM(product_order_reship_exchange_order_count)                    AS product_order_reship_exchange_order_count,
       SUM(online_product_order_reship_exchange_order_count)             AS online_product_order_reship_exchange_order_count,
       SUM(retail_product_order_reship_exchange_order_count)             AS retail_product_order_reship_exchange_order_count,
       SUM(mobile_app_product_order_reship_exchange_order_count)         AS mobile_app_product_order_reship_exchange_order_count,
       SUM(product_order_reship_exchange_unit_count)                     AS product_order_reship_exchange_unit_count,
       SUM(online_product_order_reship_exchange_unit_count)              AS online_product_order_reship_exchange_unit_count,
       SUM(retail_product_order_reship_exchange_unit_count)              AS retail_product_order_reship_exchange_unit_count,
       SUM(mobile_app_product_order_reship_exchange_unit_count)          AS mobile_app_product_order_reship_exchange_unit_count,
       SUM(product_order_reship_exchange_direct_cogs_amount)             AS product_order_reship_exchange_direct_cogs_amount,
       SUM(online_product_order_reship_exchange_direct_cogs_amount)      AS online_product_order_reship_exchange_direct_cogs_amount,
       SUM(retail_product_order_reship_exchange_direct_cogs_amount)      AS retail_product_order_reship_exchange_direct_cogs_amount,
       SUM(mobile_app_product_order_reship_exchange_direct_cogs_amount)  AS mobile_app_product_order_reship_exchange_direct_cogs_amount,
       SUM(product_order_return_cogs_amount)                             AS product_order_return_cogs_amount,
       SUM(online_product_order_return_cogs_amount)                      AS online_product_order_return_cogs_amount,
       SUM(retail_product_order_return_cogs_amount)                      AS retail_product_order_return_cogs_amount,
       SUM(mobile_app_product_order_return_cogs_amount)                  AS mobile_app_product_order_return_cogs_amount,
       SUM(product_order_return_unit_count)                              AS product_order_return_unit_count,
       SUM(online_product_order_return_unit_count)                       AS online_product_order_return_unit_count,
       SUM(retail_product_order_return_unit_count)                       AS retail_product_order_return_unit_count,
       SUM(mobile_app_product_order_return_unit_count)                   AS mobile_app_product_order_return_unit_count,
       SUM(product_order_amount_to_pay)                                  AS product_order_amount_to_pay,
       SUM(online_product_order_amount_to_pay)                           AS online_product_order_amount_to_pay,
       SUM(retail_product_order_amount_to_pay)                           AS retail_product_order_amount_to_pay,
       SUM(mobile_app_product_order_amount_to_pay)                       AS mobile_app_product_order_amount_to_pay,
       SUM(product_gross_revenue_excl_shipping)                          AS product_gross_revenue_excl_shipping,
       SUM(online_product_gross_revenue_excl_shipping)                   AS online_product_gross_revenue_excl_shipping,
       SUM(retail_product_gross_revenue_excl_shipping)                   AS retail_product_gross_revenue_excl_shipping,
       SUM(mobile_app_product_gross_revenue_excl_shipping)               AS mobile_app_product_gross_revenue_excl_shipping,
       SUM(product_gross_revenue)                                        AS product_gross_revenue,
       SUM(online_product_gross_revenue)                                 AS online_product_gross_revenue,
       SUM(retail_product_gross_revenue)                                 AS retail_product_gross_revenue,
       SUM(mobile_app_product_gross_revenue)                             AS mobile_app_product_gross_revenue,
       SUM(product_net_revenue)                                          AS product_net_revenue,
       SUM(online_product_net_revenue)                                   AS online_product_net_revenue,
       SUM(retail_product_net_revenue)                                   AS retail_product_net_revenue,
       SUM(mobile_app_product_net_revenue)                               AS mobile_app_product_net_revenue,
       SUM(product_margin_pre_return)                                    AS product_margin_pre_return,
       SUM(online_product_margin_pre_return)                             AS online_product_margin_pre_return,
       SUM(retail_product_margin_pre_return)                             AS retail_product_margin_pre_return,
       SUM(mobile_app_product_margin_pre_return)                         AS mobile_app_product_margin_pre_return,
       SUM(product_margin_pre_return_excl_shipping)                      AS product_margin_pre_return_excl_shipping,
       SUM(online_product_margin_pre_return_excl_shipping)               AS online_product_margin_pre_return_excl_shipping,
       SUM(retail_product_margin_pre_return_excl_shipping)               AS retail_product_margin_pre_return_excl_shipping,
       SUM(mobile_app_product_margin_pre_return_excl_shipping)           AS mobile_app_product_margin_pre_return_excl_shipping,
       SUM(product_gross_profit)                                         AS product_gross_profit,
       SUM(online_product_gross_profit)                                  AS online_product_gross_profit,
       SUM(retail_product_gross_profit)                                  AS retail_product_gross_profit,
       SUM(mobile_app_product_gross_profit)                              AS mobile_app_product_gross_profit,
       SUM(product_variable_contribution_profit)                         AS product_variable_contribution_profit,
       SUM(online_product_variable_contribution_profit)                  AS online_product_variable_contribution_profit,
       SUM(retail_product_variable_contribution_profit)                  AS retail_product_variable_contribution_profit,
       SUM(mobile_app_product_variable_contribution_profit)              AS mobile_app_product_variable_contribution_profit,
       SUM(product_order_cash_gross_revenue_amount)                      AS product_order_cash_gross_revenue_amount,
       SUM(online_product_order_cash_gross_revenue_amount)               AS online_product_order_cash_gross_revenue_amount,
       SUM(retail_product_order_cash_gross_revenue_amount)               AS retail_product_order_cash_gross_revenue_amount,
       SUM(mobile_app_product_order_cash_gross_revenue_amount)           AS mobile_app_product_order_cash_gross_revenue_amount,
       SUM(product_order_cash_net_revenue)                               AS product_order_cash_net_revenue,
       SUM(online_product_order_cash_net_revenue)                        AS online_product_order_cash_net_revenue,
       SUM(retail_product_order_cash_net_revenue)                        AS retail_product_order_cash_net_revenue,
       SUM(mobile_app_product_order_cash_net_revenue)                    AS mobile_app_product_order_cash_net_revenue,
       SUM(product_order_landed_product_cost_amount)                     AS product_order_landed_product_cost_amount,
       SUM(online_product_order_landed_product_cost_amount)              AS online_product_order_landed_product_cost_amount,
       SUM(retail_product_order_landed_product_cost_amount)              AS retail_product_order_landed_product_cost_amount,
       SUM(mobile_app_product_order_landed_product_cost_amount)          AS mobile_app_product_order_landed_product_cost_amount,
       SUM(product_order_cash_margin_pre_return)                         AS product_order_cash_margin_pre_return,
       SUM(online_product_order_cash_margin_pre_return)                  AS online_product_order_cash_margin_pre_return,
       SUM(retail_product_order_cash_margin_pre_return)                  AS retail_product_order_cash_margin_pre_return,
       SUM(mobile_app_product_order_cash_margin_pre_return)              AS mobile_app_product_order_cash_margin_pre_return,
       SUM(product_order_cash_gross_profit)                              AS product_order_cash_gross_profit,
       SUM(online_product_order_cash_gross_profit)                       AS online_product_order_cash_gross_profit,
       SUM(retail_product_order_cash_gross_profit)                       AS retail_product_order_cash_gross_profit,
       SUM(mobile_app_product_order_cash_gross_profit)                   AS mobile_app_product_order_cash_gross_profit,
       SUM(billing_cash_gross_revenue)                                   AS billing_cash_gross_revenue,
       SUM(billing_cash_net_revenue)                                     AS billing_cash_net_revenue,
       SUM(cash_gross_revenue)                                           AS cash_gross_revenue,
       SUM(cash_net_revenue)                                             AS cash_net_revenue,
       SUM(cash_gross_profit)                                            AS cash_gross_profit,
       SUM(cash_variable_contribution_profit)                            AS cash_variable_contribution_profit,
       SUM(monthly_billed_credit_cash_transaction_amount)                AS monthly_billed_credit_cash_transaction_amount,
       SUM(membership_fee_cash_transaction_amount)                       AS membership_fee_cash_transaction_amount,
       SUM(gift_card_transaction_amount)                                 AS gift_card_transaction_amount,
       SUM(legacy_credit_cash_transaction_amount)                        AS legacy_credit_cash_transaction_amount,
       SUM(monthly_billed_credit_cash_refund_count)                      AS monthly_billed_credit_cash_refund_count,
       SUM(monthly_billed_credit_cash_refund_chargeback_amount)          AS monthly_billed_credit_cash_refund_chargeback_amount,
       SUM(membership_fee_cash_refund_chargeback_amount)                 AS membership_fee_cash_refund_chargeback_amount,
       SUM(gift_card_cash_refund_chargeback_amount)                      AS gift_card_cash_refund_chargeback_amount,
       SUM(legacy_credit_cash_refund_chargeback_amount)                  AS legacy_credit_cash_refund_chargeback_amount,
       SUM(billed_cash_credit_issued_amount)                             AS billed_cash_credit_issued_amount,
       SUM(billed_cash_credit_redeemed_amount)                           AS billed_cash_credit_redeemed_amount,
       SUM(online_billed_cash_credit_redeemed_amount)                    AS online_billed_cash_credit_redeemed_amount,
       SUM(retail_billed_cash_credit_redeemed_amount)                    AS retail_billed_cash_credit_redeemed_amount,
       SUM(mobile_billed_cash_credit_redeemed_amount)                    AS mobile_billed_cash_credit_redeemed_amount,
       SUM(billed_cash_credit_cancelled_amount)                          AS billed_cash_credit_cancelled_amount,
       SUM(billed_cash_credit_expired_amount)                            AS billed_cash_credit_expired_amount,
       SUM(billed_cash_credit_issued_equivalent_count)                   AS billed_cash_credit_issued_equivalent_count,
       SUM(billed_cash_credit_redeemed_same_month_amount)                AS billed_cash_credit_redeemed_same_month_amount,
       SUM(billed_cash_credit_redeemed_equivalent_count)                 AS billed_cash_credit_redeemed_equivalent_count,
       SUM(billed_cash_credit_cancelled_equivalent_count)                AS billed_cash_credit_cancelled_equivalent_count,
       SUM(billed_cash_credit_expired_equivalent_count)                  AS billed_cash_credit_expired_equivalent_count,
       SUM(refund_cash_credit_issued_amount)                             AS refund_cash_credit_issued_amount,
       SUM(refund_cash_credit_redeemed_amount)                           AS refund_cash_credit_redeemed_amount,
       SUM(refund_cash_credit_cancelled_amount)                          AS refund_cash_credit_cancelled_amount,
       SUM(refund_cash_credit_expired_amount)                            AS refund_cash_credit_expired_amount,
       SUM(other_cash_credit_issued_amount)                              AS other_cash_credit_issued_amount,
       SUM(other_cash_credit_redeemed_amount)                            AS other_cash_credit_redeemed_amount,
       SUM(other_cash_credit_cancelled_amount)                           AS other_cash_credit_cancelled_amount,
       SUM(other_cash_credit_expired_amount)                             AS other_cash_credit_expired_amount,
       SUM(noncash_credit_issued_amount)                                 AS noncash_credit_issued_amount,
       SUM(noncash_credit_cancelled_amount)                              AS noncash_credit_cancelled_amount,
       SUM(noncash_credit_expired_amount)                                AS noncash_credit_expired_amount,
       SUM(first_guest_product_margin_pre_return)                        AS first_guest_product_margin_pre_return
FROM analytics_base.customer_lifetime_value_monthly clvm
         JOIN stg.dim_store ds
              ON clvm.store_id = ds.store_id
GROUP BY ds.store_brand,
         ds.store_country,
         ds.store_region,
         ds.store_type,
         clvm.gender,
         clvm.vip_cohort_month_date,
         clvm.month_date,
         clvm.is_retail_vip,
         clvm.is_cross_promo,
         clvm.finance_specialty_store;

INSERT INTO snapshot.customer_lifetime_value_monthly (
      store_brand,
      store_country,
      store_region,
      store_type,
      gender,
      vip_cohort_month_date,
      month_date,
      is_retail_vip,
      is_cross_promo,
      finance_specialty_store,
      product_order_count,
      online_product_order_count,
      retail_product_order_count,
      mobile_app_product_order_count,
      product_order_unit_count,
      online_product_order_unit_count,
      retail_product_order_unit_count,
      mobile_app_product_order_unit_count,
      product_order_subtotal_excl_tariff_amount,
      online_product_order_subtotal_excl_tariff_amount,
      retail_product_order_subtotal_excl_tariff_amount,
      mobile_app_product_order_subtotal_excl_tariff_amount,
      product_order_product_discount_amount,
      online_product_order_product_discount_amount,
      retail_product_order_product_discount_amount,
      mobile_app_product_order_product_discount_amount,
      product_order_shipping_revenue_amount,
      online_product_order_shipping_revenue_amount,
      retail_product_order_shipping_revenue_amount,
      mobile_app_product_order_shipping_revenue_amount,
      product_order_direct_cogs_amount,
      online_product_order_direct_cogs_amount,
      retail_product_order_direct_cogs_amount,
      mobile_app_product_order_direct_cogs_amount,
      product_order_selling_expenses_amount,
      online_product_order_selling_expenses_amount,
      retail_product_order_selling_expenses_amount,
      mobile_app_product_order_selling_expenses_amount,
      product_order_cash_refund_amount_and_chargeback_amount,
      online_product_order_cash_refund_chargeback_amount,
      retail_product_order_cash_refund_chargeback_amount,
      mobile_app_product_order_cash_refund_chargeback_amount,
      product_order_cash_credit_refund_amount,
      online_product_order_cash_credit_refund_amount,
      retail_product_order_cash_credit_refund_amount,
      mobile_app_product_order_cash_credit_refund_amount,
      product_order_reship_exchange_order_count,
      online_product_order_reship_exchange_order_count,
      retail_product_order_reship_exchange_order_count,
      mobile_app_product_order_reship_exchange_order_count,
      product_order_reship_exchange_unit_count,
      online_product_order_reship_exchange_unit_count,
      retail_product_order_reship_exchange_unit_count,
      mobile_app_product_order_reship_exchange_unit_count,
      product_order_reship_exchange_direct_cogs_amount,
      online_product_order_reship_exchange_direct_cogs_amount,
      retail_product_order_reship_exchange_direct_cogs_amount,
      mobile_app_product_order_reship_exchange_direct_cogs_amount,
      product_order_return_cogs_amount,
      online_product_order_return_cogs_amount,
      retail_product_order_return_cogs_amount,
      mobile_app_product_order_return_cogs_amount,
      product_order_return_unit_count,
      online_product_order_return_unit_count,
      retail_product_order_return_unit_count,
      mobile_app_product_order_return_unit_count,
      product_order_amount_to_pay,
      online_product_order_amount_to_pay,
      retail_product_order_amount_to_pay,
      mobile_app_product_order_amount_to_pay,
      product_gross_revenue_excl_shipping,
      online_product_gross_revenue_excl_shipping,
      retail_product_gross_revenue_excl_shipping,
      mobile_app_product_gross_revenue_excl_shipping,
      product_gross_revenue,
      online_product_gross_revenue,
      retail_product_gross_revenue,
      mobile_app_product_gross_revenue,
      product_net_revenue,
      online_product_net_revenue,
      retail_product_net_revenue,
      mobile_app_product_net_revenue,
      product_margin_pre_return,
      online_product_margin_pre_return,
      retail_product_margin_pre_return,
      mobile_app_product_margin_pre_return,
      product_margin_pre_return_excl_shipping,
      online_product_margin_pre_return_excl_shipping,
      retail_product_margin_pre_return_excl_shipping,
      mobile_app_product_margin_pre_return_excl_shipping,
      product_gross_profit,
      online_product_gross_profit,
      retail_product_gross_profit,
      mobile_app_product_gross_profit,
      product_variable_contribution_profit,
      online_product_variable_contribution_profit,
      retail_product_variable_contribution_profit,
      mobile_app_product_variable_contribution_profit,
      product_order_cash_gross_revenue_amount,
      online_product_order_cash_gross_revenue_amount,
      retail_product_order_cash_gross_revenue_amount,
      mobile_app_product_order_cash_gross_revenue_amount,
      product_order_cash_net_revenue,
      online_product_order_cash_net_revenue,
      retail_product_order_cash_net_revenue,
      mobile_app_product_order_cash_net_revenue,
      product_order_landed_product_cost_amount,
      online_product_order_landed_product_cost_amount,
      retail_product_order_landed_product_cost_amount,
      mobile_app_product_order_landed_product_cost_amount,
      product_order_cash_margin_pre_return,
      online_product_order_cash_margin_pre_return,
      retail_product_order_cash_margin_pre_return,
      mobile_app_product_order_cash_margin_pre_return,
      product_order_cash_gross_profit,
      online_product_order_cash_gross_profit,
      retail_product_order_cash_gross_profit,
      mobile_app_product_order_cash_gross_profit,
      billing_cash_gross_revenue,
      billing_cash_net_revenue,
      cash_gross_revenue,
      cash_net_revenue,
      cash_gross_profit,
      cash_variable_contribution_profit,
      monthly_billed_credit_cash_transaction_amount,
      membership_fee_cash_transaction_amount,
      gift_card_transaction_amount,
      legacy_credit_cash_transaction_amount,
      monthly_billed_credit_cash_refund_count,
      monthly_billed_credit_cash_refund_chargeback_amount,
      membership_fee_cash_refund_chargeback_amount,
      gift_card_cash_refund_chargeback_amount,
      legacy_credit_cash_refund_chargeback_amount,
      billed_cash_credit_issued_amount,
      billed_cash_credit_redeemed_amount,
      online_billed_cash_credit_redeemed_amount,
      retail_billed_cash_credit_redeemed_amount,
      mobile_billed_cash_credit_redeemed_amount,
      billed_cash_credit_cancelled_amount,
      billed_cash_credit_expired_amount,
      billed_cash_credit_issued_equivalent_count,
      billed_cash_credit_redeemed_same_month_amount,
      billed_cash_credit_redeemed_equivalent_count,
      billed_cash_credit_cancelled_equivalent_count,
      billed_cash_credit_expired_equivalent_count,
      refund_cash_credit_issued_amount,
      refund_cash_credit_redeemed_amount,
      refund_cash_credit_cancelled_amount,
      refund_cash_credit_expired_amount,
      other_cash_credit_issued_amount,
      other_cash_credit_redeemed_amount,
      other_cash_credit_cancelled_amount,
      other_cash_credit_expired_amount,
      noncash_credit_issued_amount,
      noncash_credit_cancelled_amount,
      noncash_credit_expired_amount,
      first_guest_product_margin_pre_return,
      snapshot_datetime
      )
SELECT store_brand,
       store_country,
       store_region,
       store_type,
       gender,
       vip_cohort_month_date,
       month_date,
       is_retail_vip,
       is_cross_promo,
       finance_specialty_store,
       product_order_count,
       online_product_order_count,
       retail_product_order_count,
       mobile_app_product_order_count,
       product_order_unit_count,
       online_product_order_unit_count,
       retail_product_order_unit_count,
       mobile_app_product_order_unit_count,
       product_order_subtotal_excl_tariff_amount,
       online_product_order_subtotal_excl_tariff_amount,
       retail_product_order_subtotal_excl_tariff_amount,
       mobile_app_product_order_subtotal_excl_tariff_amount,
       product_order_product_discount_amount,
       online_product_order_product_discount_amount,
       retail_product_order_product_discount_amount,
       mobile_app_product_order_product_discount_amount,
       product_order_shipping_revenue_amount,
       online_product_order_shipping_revenue_amount,
       retail_product_order_shipping_revenue_amount,
       mobile_app_product_order_shipping_revenue_amount,
       product_order_direct_cogs_amount,
       online_product_order_direct_cogs_amount,
       retail_product_order_direct_cogs_amount,
       mobile_app_product_order_direct_cogs_amount,
       product_order_selling_expenses_amount,
       online_product_order_selling_expenses_amount,
       retail_product_order_selling_expenses_amount,
       mobile_app_product_order_selling_expenses_amount,
       product_order_cash_refund_amount_and_chargeback_amount,
       online_product_order_cash_refund_chargeback_amount,
       retail_product_order_cash_refund_chargeback_amount,
       mobile_app_product_order_cash_refund_chargeback_amount,
       product_order_cash_credit_refund_amount,
       online_product_order_cash_credit_refund_amount,
       retail_product_order_cash_credit_refund_amount,
       mobile_app_product_order_cash_credit_refund_amount,
       product_order_reship_exchange_order_count,
       online_product_order_reship_exchange_order_count,
       retail_product_order_reship_exchange_order_count,
       mobile_app_product_order_reship_exchange_order_count,
       product_order_reship_exchange_unit_count,
       online_product_order_reship_exchange_unit_count,
       retail_product_order_reship_exchange_unit_count,
       mobile_app_product_order_reship_exchange_unit_count,
       product_order_reship_exchange_direct_cogs_amount,
       online_product_order_reship_exchange_direct_cogs_amount,
       retail_product_order_reship_exchange_direct_cogs_amount,
       mobile_app_product_order_reship_exchange_direct_cogs_amount,
       product_order_return_cogs_amount,
       online_product_order_return_cogs_amount,
       retail_product_order_return_cogs_amount,
       mobile_app_product_order_return_cogs_amount,
       product_order_return_unit_count,
       online_product_order_return_unit_count,
       retail_product_order_return_unit_count,
       mobile_app_product_order_return_unit_count,
       product_order_amount_to_pay,
       online_product_order_amount_to_pay,
       retail_product_order_amount_to_pay,
       mobile_app_product_order_amount_to_pay,
       product_gross_revenue_excl_shipping,
       online_product_gross_revenue_excl_shipping,
       retail_product_gross_revenue_excl_shipping,
       mobile_app_product_gross_revenue_excl_shipping,
       product_gross_revenue,
       online_product_gross_revenue,
       retail_product_gross_revenue,
       mobile_app_product_gross_revenue,
       product_net_revenue,
       online_product_net_revenue,
       retail_product_net_revenue,
       mobile_app_product_net_revenue,
       product_margin_pre_return,
       online_product_margin_pre_return,
       retail_product_margin_pre_return,
       mobile_app_product_margin_pre_return,
       product_margin_pre_return_excl_shipping,
       online_product_margin_pre_return_excl_shipping,
       retail_product_margin_pre_return_excl_shipping,
       mobile_app_product_margin_pre_return_excl_shipping,
       product_gross_profit,
       online_product_gross_profit,
       retail_product_gross_profit,
       mobile_app_product_gross_profit,
       product_variable_contribution_profit,
       online_product_variable_contribution_profit,
       retail_product_variable_contribution_profit,
       mobile_app_product_variable_contribution_profit,
       product_order_cash_gross_revenue_amount,
       online_product_order_cash_gross_revenue_amount,
       retail_product_order_cash_gross_revenue_amount,
       mobile_app_product_order_cash_gross_revenue_amount,
       product_order_cash_net_revenue,
       online_product_order_cash_net_revenue,
       retail_product_order_cash_net_revenue,
       mobile_app_product_order_cash_net_revenue,
       product_order_landed_product_cost_amount,
       online_product_order_landed_product_cost_amount,
       retail_product_order_landed_product_cost_amount,
       mobile_app_product_order_landed_product_cost_amount,
       product_order_cash_margin_pre_return,
       online_product_order_cash_margin_pre_return,
       retail_product_order_cash_margin_pre_return,
       mobile_app_product_order_cash_margin_pre_return,
       product_order_cash_gross_profit,
       online_product_order_cash_gross_profit,
       retail_product_order_cash_gross_profit,
       mobile_app_product_order_cash_gross_profit,
       billing_cash_gross_revenue,
       billing_cash_net_revenue,
       cash_gross_revenue,
       cash_net_revenue,
       cash_gross_profit,
       cash_variable_contribution_profit,
       monthly_billed_credit_cash_transaction_amount,
       membership_fee_cash_transaction_amount,
       gift_card_transaction_amount,
       legacy_credit_cash_transaction_amount,
       monthly_billed_credit_cash_refund_count,
       monthly_billed_credit_cash_refund_chargeback_amount,
       membership_fee_cash_refund_chargeback_amount,
       gift_card_cash_refund_chargeback_amount,
       legacy_credit_cash_refund_chargeback_amount,
       billed_cash_credit_issued_amount,
       billed_cash_credit_redeemed_amount,
       online_billed_cash_credit_redeemed_amount,
       retail_billed_cash_credit_redeemed_amount,
       mobile_billed_cash_credit_redeemed_amount,
       billed_cash_credit_cancelled_amount,
       billed_cash_credit_expired_amount,
       billed_cash_credit_issued_equivalent_count,
       billed_cash_credit_redeemed_same_month_amount,
       billed_cash_credit_redeemed_equivalent_count,
       billed_cash_credit_cancelled_equivalent_count,
       billed_cash_credit_expired_equivalent_count,
       refund_cash_credit_issued_amount,
       refund_cash_credit_redeemed_amount,
       refund_cash_credit_cancelled_amount,
       refund_cash_credit_expired_amount,
       other_cash_credit_issued_amount,
       other_cash_credit_redeemed_amount,
       other_cash_credit_cancelled_amount,
       other_cash_credit_expired_amount,
       noncash_credit_issued_amount,
       noncash_credit_cancelled_amount,
       noncash_credit_expired_amount,
       first_guest_product_margin_pre_return,
       $execution_start_time AS snapshot_datetime
FROM _aggregated_cltv;
