SET execution_start_time = CURRENT_TIMESTAMP::TIMESTAMP_LTZ(3);

INSERT INTO snapshot.finance_sales_ops_weekly (
    customer_id,
    date,
    currency_object,
    date_object,
    store_id,
    vip_cohort_month_date,
    gender,
    is_scrubs_customer,
    cash_gross_revenue,
    cash_net_revenue,
    product_order_cash_margin_pre_return,
    billing_cash_gross_revenue,
    cash_gross_profit,
    product_order_cash_refund_amount,
    product_order_cash_chargeback_amount,
    billing_cash_refund_amount,
    billing_cash_chargeback_amount,
    product_order_landed_product_cost_amount,
    product_order_exchange_product_cost_amount,
    product_order_reship_product_cost_amount,
    product_order_shipping_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_return_shipping_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    product_order_misc_cogs_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_variable_gms_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_payment_processing_cost_amount,
    billing_payment_processing_cost_amount,
    product_order_variable_warehouse_cost_amount,
    activation_key,
    first_activation_key,
    associate_id,
    order_membership_classification_key,
    is_bop_vip,
    currency_type,
    is_deleted,
    vip_store_id,
    is_cross_promo,
    is_retail_vip,
    is_reactivated_vip,
    activation_local_datetime,
    cancellation_local_datetime,
    first_activation_local_datetime,
    first_vip_cohort_month_date,
    first_cancellation_local_datetime,
    finance_specialty_store,
    snapshot_datetime
)
SELECT
    fso.customer_id,
    fso.date,
    fso.currency_object,
    fso.date_object,
    st.store_id,
    fso.vip_cohort_month_date,
    fso.gender,
    fso.is_scrubs_customer,
    fso.cash_gross_revenue,
    fso.cash_net_revenue,
    fso.product_order_cash_margin_pre_return,
    fso.billing_cash_gross_revenue,
    fso.cash_gross_profit,
    fso.product_order_cash_refund_amount,
    fso.product_order_cash_chargeback_amount,
    fso.billing_cash_refund_amount,
    fso.billing_cash_chargeback_amount,
    fso.product_order_landed_product_cost_amount,
    fso.product_order_exchange_product_cost_amount,
    fso.product_order_reship_product_cost_amount,
    fso.product_order_shipping_cost_amount,
    fso.product_order_reship_shipping_cost_amount,
    fso.product_order_exchange_shipping_cost_amount,
    fso.product_order_return_shipping_cost_amount,
    fso.product_order_shipping_supplies_cost_amount,
    fso.product_order_exchange_shipping_supplies_cost_amount,
    fso.product_order_reship_shipping_supplies_cost_amount,
    fso.product_order_misc_cogs_amount,
    fso.product_order_cost_product_returned_resaleable_amount,
    fso.product_order_variable_gms_cost_amount,
    fso.billing_variable_gms_cost_amount,
    fso.product_order_payment_processing_cost_amount,
    fso.billing_payment_processing_cost_amount,
    fso.product_order_variable_warehouse_cost_amount,
    fso.activation_key,
    fso.first_activation_key,
    fso.associate_id,
    fso.order_membership_classification_key,
    fso.is_bop_vip,
    fso.currency_type,
    fso.is_deleted,
    fso.vip_store_id,
    fso.is_cross_promo,
    fso.is_retail_vip,
    fso.is_reactivated_vip,
    fso.activation_local_datetime,
    fso.cancellation_local_datetime,
    fso.first_activation_local_datetime,
    fso.first_vip_cohort_month_date,
    fso.first_cancellation_local_datetime,
    fso.finance_specialty_store,
    $execution_start_time AS snapshot_datetime
FROM analytics_base.finance_sales_ops_stg fso
JOIN stg.dim_store st ON st.store_id = fso.store_id
WHERE currency_object = 'usd'
  AND date_object IN ('shipped', 'placed')
  AND store_region IN ('EU', 'NA')
  AND store_brand IN ('Fabletics', 'Yitty')
  AND vip_cohort_month_date >= '2019-01-01';
