ALTER SESSION SET QUERY_TAG ='finance_sales_ops_historical_snapshot_comparison';

SET execution_start_time = CURRENT_TIMESTAMP :: TIMESTAMP_LTZ(3);
CREATE OR REPLACE TEMP TABLE _snapshot_order AS
SELECT snapshot_datetime, row_number()OVER(ORDER BY snapshot_datetime DESC) AS row_num
FROM (
         SELECT max(snapshot_datetime) AS snapshot_datetime
         FROM snapshot.finance_sales_ops
         WHERE to_time(snapshot_datetime) < '13:00:00'
         GROUP BY cast(snapshot_datetime AS DATE)
         ORDER BY cast(snapshot_datetime AS DATE) DESC
) QUALIFY row_num <= 2;

SET max_snapshot_datetime = (SELECT snapshot_datetime FROM _snapshot_order WHERE row_num = 1);
SET previous_snapshot_datetime = (SELECT snapshot_datetime FROM _snapshot_order WHERE row_num = 2);

/* creating table to make all metrics have same data type so we can unpivot*/
CREATE OR REPLACE TEMP TABLE _snapshot_aggregate (
    SNAPSHOT_DATETIME TIMESTAMP_LTZ(3),
	STORE_BRAND VARCHAR(20),
	STORE_COUNTRY VARCHAR(50),
	STORE_REGION VARCHAR(32),
	STORE_TYPE VARCHAR(20),
	GENDER VARCHAR(10),
	IS_RETAIL_VIP BOOLEAN,
	IS_CROSS_PROMO BOOLEAN,
	FINANCE_SPECIALTY_STORE VARCHAR(20),
	MEMBERSHIP_ORDER_TYPE_L3 VARCHAR(50),
	MONTH_DATE DATE,
	PRODUCT_ORDER_SUBTOTAL_EXCL_TARIFF_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_TARIFF_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_PRODUCT_SUBTOTAL_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_PRODUCT_DISCOUNT_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_SHIPPING_DISCOUNT_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_SHIPPING_REVENUE_BEFORE_DISCOUNT_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_SHIPPING_REVENUE_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_TAX_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_CASH_TRANSACTION_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_CASH_CREDIT_REDEEMED_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_NONCASH_CREDIT_REDEEMED_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_COUNT NUMBER(38,10),
	PRODUCT_ORDER_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_LOYALTY_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_OUTFIT_COMPONENT_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_OUTFIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_DISCOUNTED_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_ZERO_REVENUE_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_LANDED_PRODUCT_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_SHIPPING_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_SHIPPING_SUPPLIES_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_MISC_COGS_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_DIRECT_COGS_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_CASH_REFUND_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_CASH_CREDIT_REFUND_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_NONCASH_CREDIT_REFUND_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_CASH_CHARGEBACK_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_COST_PRODUCT_RETURNED_RESALEABLE_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_COST_PRODUCT_RETURNED_DAMAGED_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_RETURN_SHIPPING_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_RETURN_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_RESHIP_ORDER_COUNT NUMBER(38,10),
	PRODUCT_ORDER_RESHIP_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_RESHIP_DIRECT_COGS_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_RESHIP_PRODUCT_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_RESHIP_SHIPPING_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_RESHIP_SHIPPING_SUPPLIES_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_EXCHANGE_ORDER_COUNT NUMBER(38,10),
	PRODUCT_ORDER_EXCHANGE_UNIT_COUNT NUMBER(38,10),
	PRODUCT_ORDER_EXCHANGE_DIRECT_COGS_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_EXCHANGE_PRODUCT_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_EXCHANGE_SHIPPING_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_EXCHANGE_SHIPPING_SUPPLIES_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_SELLING_EXPENSES_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_PAYMENT_PROCESSING_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_VARIABLE_GMS_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_VARIABLE_WAREHOUSE_COST_AMOUNT NUMBER(38,10),
	BILLING_SELLING_EXPENSES_AMOUNT NUMBER(38,10),
	BILLING_PAYMENT_PROCESSING_COST_AMOUNT NUMBER(38,10),
	BILLING_VARIABLE_GMS_COST_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_AMOUNT_TO_PAY NUMBER(38,10),
	PRODUCT_GROSS_REVENUE_EXCL_SHIPPING NUMBER(38,10),
	PRODUCT_GROSS_REVENUE NUMBER(38,10),
	PRODUCT_NET_REVENUE NUMBER(38,10),
	PRODUCT_MARGIN_PRE_RETURN NUMBER(38,10),
	PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING NUMBER(38,10),
	PRODUCT_GROSS_PROFIT NUMBER(38,10),
	PRODUCT_VARIABLE_CONTRIBUTION_PROFIT NUMBER(38,10),
	PRODUCT_ORDER_CASH_GROSS_REVENUE_AMOUNT NUMBER(38,10),
	PRODUCT_ORDER_CASH_NET_REVENUE NUMBER(38,10),
	PRODUCT_ORDER_CASH_MARGIN_PRE_RETURN NUMBER(38,10),
	PRODUCT_ORDER_CASH_GROSS_PROFIT NUMBER(38,10),
	BILLING_CASH_GROSS_REVENUE NUMBER(38,10),
	BILLING_CASH_NET_REVENUE NUMBER(38,10),
	CASH_GROSS_REVENUE NUMBER(38,10),
	CASH_NET_REVENUE NUMBER(38,10),
	CASH_GROSS_PROFIT NUMBER(38,10),
	CASH_VARIABLE_CONTRIBUTION_PROFIT NUMBER(38,10),
	BILLING_ORDER_TRANSACTION_COUNT NUMBER(38,10),
	BILLED_CREDIT_CASH_TRANSACTION_COUNT NUMBER(38,10),
	ON_RETRY_BILLED_CREDIT_CASH_TRANSACTION_COUNT NUMBER(38,10),
	BILLING_CASH_REFUND_AMOUNT NUMBER(38,10),
	BILLING_CASH_CHARGEBACK_AMOUNT NUMBER(38,10),
	BILLED_CREDIT_CASH_TRANSACTION_AMOUNT NUMBER(38,10),
	MEMBERSHIP_FEE_CASH_TRANSACTION_AMOUNT NUMBER(38,10),
	GIFT_CARD_TRANSACTION_AMOUNT NUMBER(38,10),
	LEGACY_CREDIT_CASH_TRANSACTION_AMOUNT NUMBER(38,10),
	BILLED_CREDIT_CASH_REFUND_COUNT NUMBER(38,10),
	BILLED_CREDIT_CASH_REFUND_CHARGEBACK_AMOUNT NUMBER(38,10),
	MEMBERSHIP_FEE_CASH_REFUND_CHARGEBACK_AMOUNT NUMBER(38,10),
	GIFT_CARD_CASH_REFUND_CHARGEBACK_AMOUNT NUMBER(38,10),
	LEGACY_CREDIT_CASH_REFUND_CHARGEBACK_AMOUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_ISSUED_AMOUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_REDEEMED_AMOUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_CANCELLED_AMOUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_EXPIRED_AMOUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_ISSUED_EQUIVALENT_COUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_REDEEMED_SAME_MONTH_AMOUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_REDEEMED_EQUIVALENT_COUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_CANCELLED_EQUIVALENT_COUNT NUMBER(38,10),
	BILLED_CASH_CREDIT_EXPIRED_EQUIVALENT_COUNT NUMBER(38,10),
	REFUND_CASH_CREDIT_ISSUED_AMOUNT NUMBER(38,10),
	REFUND_CASH_CREDIT_REDEEMED_AMOUNT NUMBER(38,10),
	REFUND_CASH_CREDIT_CANCELLED_AMOUNT NUMBER(38,10),
	REFUND_CASH_CREDIT_EXPIRED_AMOUNT NUMBER(38,10),
	OTHER_CASH_CREDIT_ISSUED_AMOUNT NUMBER(38,10),
	OTHER_CASH_CREDIT_REDEEMED_AMOUNT NUMBER(38,10),
	OTHER_CASH_CREDIT_CANCELLED_AMOUNT NUMBER(38,10),
	OTHER_CASH_CREDIT_EXPIRED_AMOUNT NUMBER(38,10),
	NONCASH_CREDIT_ISSUED_AMOUNT NUMBER(38,10),
	NONCASH_CREDIT_CANCELLED_AMOUNT NUMBER(38,10),
	NONCASH_CREDIT_EXPIRED_AMOUNT NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_ORDER_COUNT NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_ORDER_UNIT_COUNT NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_GROSS_REVENUE NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_GROSS_REVENUE_EXCL_SHIPPING NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_MARGIN_PRE_RETURN NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_ORDER_CASH_MARGIN_PRE_RETURN NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_ORDER_CASH_GROSS_REVENUE NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_NET_REVENUE NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_GROSS_PROFIT NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_ORDER_CASH_NET_REVENUE NUMBER(38,10),
	RETAIL_SHIP_ONLY_PRODUCT_ORDER_CASH_GROSS_PROFIT NUMBER(38,10),
	PRODUCT_ORDER_RESHIP_EXCHANGE_CASH_GROSS_REVENUE NUMBER(38,10)
);

INSERT INTO _snapshot_aggregate
(
snapshot_datetime,
store_brand,
store_country,
store_region,
store_type,
gender,
is_retail_vip,
is_cross_promo,
finance_specialty_store,
membership_order_type_l3,
month_date,
product_order_subtotal_excl_tariff_amount,
product_order_tariff_amount,
product_order_product_subtotal_amount,
product_order_product_discount_amount,
product_order_shipping_discount_amount,
product_order_shipping_revenue_before_discount_amount,
product_order_shipping_revenue_amount,
product_order_tax_amount,
product_order_cash_transaction_amount,
product_order_cash_credit_redeemed_amount,
product_order_noncash_credit_redeemed_amount,
product_order_count, product_order_unit_count,
product_order_loyalty_unit_count,
product_order_outfit_component_unit_count,
product_order_outfit_count,
product_order_discounted_unit_count,
product_order_zero_revenue_unit_count,
product_order_landed_product_cost_amount,
product_order_shipping_cost_amount,
product_order_shipping_supplies_cost_amount,
product_order_misc_cogs_amount,
product_order_direct_cogs_amount,
product_order_cash_refund_amount,
product_order_cash_credit_refund_amount,
product_order_noncash_credit_refund_amount,
product_order_cash_chargeback_amount,
product_order_cost_product_returned_resaleable_amount,
product_order_cost_product_returned_damaged_amount,
product_order_return_shipping_cost_amount,
product_order_return_unit_count,
product_order_reship_order_count,
product_order_reship_unit_count,
product_order_reship_direct_cogs_amount,
product_order_reship_product_cost_amount,
product_order_reship_shipping_cost_amount,
product_order_reship_shipping_supplies_cost_amount,
product_order_exchange_order_count,
product_order_exchange_unit_count,
product_order_exchange_direct_cogs_amount,
product_order_exchange_product_cost_amount,
product_order_exchange_shipping_cost_amount,
product_order_exchange_shipping_supplies_cost_amount,
product_order_selling_expenses_amount,
product_order_payment_processing_cost_amount,
product_order_variable_gms_cost_amount,
product_order_variable_warehouse_cost_amount,
billing_selling_expenses_amount,
billing_payment_processing_cost_amount,
billing_variable_gms_cost_amount,
product_order_amount_to_pay,
product_gross_revenue_excl_shipping,
product_gross_revenue, product_net_revenue,
product_margin_pre_return,
product_margin_pre_return_excl_shipping,
product_gross_profit,
product_variable_contribution_profit,
product_order_cash_gross_revenue_amount,
product_order_cash_net_revenue,
product_order_cash_margin_pre_return,
product_order_cash_gross_profit,
billing_cash_gross_revenue,
billing_cash_net_revenue,
cash_gross_revenue,
cash_net_revenue,
cash_gross_profit,
cash_variable_contribution_profit,
billing_order_transaction_count,
billed_credit_cash_transaction_count,
on_retry_billed_credit_cash_transaction_count,
billing_cash_refund_amount,
billing_cash_chargeback_amount,
billed_credit_cash_transaction_amount,
membership_fee_cash_transaction_amount,
gift_card_transaction_amount,
legacy_credit_cash_transaction_amount,
billed_credit_cash_refund_count,
billed_credit_cash_refund_chargeback_amount,
membership_fee_cash_refund_chargeback_amount,
gift_card_cash_refund_chargeback_amount,
legacy_credit_cash_refund_chargeback_amount,
billed_cash_credit_issued_amount,
billed_cash_credit_redeemed_amount,
billed_cash_credit_cancelled_amount,
billed_cash_credit_expired_amount,
billed_cash_credit_issued_equivalent_count,
billed_cash_credit_redeemed_same_month_amount,
billed_cash_credit_redeemed_equivalent_count,
billed_cash_credit_cancelled_equivalent_count,
billed_cash_credit_expired_equivalent_count,
refund_cash_credit_issued_amount,
refund_cash_credit_redeemed_amount,
refund_cash_credit_cancelled_amount,
refund_cash_credit_expired_amount,
other_cash_credit_issued_amount,
other_cash_credit_redeemed_amount,
other_cash_credit_cancelled_amount,
other_cash_credit_expired_amount,
noncash_credit_issued_amount,
noncash_credit_cancelled_amount,
noncash_credit_expired_amount,
retail_ship_only_product_order_count,
retail_ship_only_product_order_unit_count,
retail_ship_only_product_gross_revenue,
retail_ship_only_product_gross_revenue_excl_shipping,
retail_ship_only_product_margin_pre_return,
retail_ship_only_product_margin_pre_return_excl_shipping,
retail_ship_only_product_order_cash_margin_pre_return,
retail_ship_only_product_order_cash_gross_revenue,
retail_ship_only_product_net_revenue,
retail_ship_only_product_gross_profit,
retail_ship_only_product_order_cash_net_revenue,
retail_ship_only_product_order_cash_gross_profit,
product_order_reship_exchange_cash_gross_revenue
)

SELECT
    snapshot_datetime,
    store_brand,
    store_country,
    store_region,
    store_type,
    gender,
    is_retail_vip,
    COALESCE(is_cross_promo,FALSE) AS is_cross_promo,
    COALESCE(finance_specialty_store,'NULL') AS finance_specialty_store,
    membership_order_type_l3,
    DATE_TRUNC(month,date) AS month_date,
    SUM(product_order_subtotal_excl_tariff_amount) AS product_order_subtotal_excl_tariff_amount,
    SUM(product_order_tariff_amount) AS product_order_tariff_amount,
    SUM(product_order_product_subtotal_amount) AS product_order_product_subtotal_amount,
    SUM(product_order_product_discount_amount) AS product_order_product_discount_amount,
    SUM(product_order_shipping_discount_amount) AS product_order_shipping_discount_amount,
    SUM(product_order_shipping_revenue_before_discount_amount) AS product_order_shipping_revenue_before_discount_amount,
    SUM(product_order_shipping_revenue_amount) AS product_order_shipping_revenue_amount,
    SUM(product_order_tax_amount) AS product_order_tax_amount,
    SUM(product_order_cash_transaction_amount) AS product_order_cash_transaction_amount,
    SUM(product_order_cash_credit_redeemed_amount) AS product_order_cash_credit_redeemed_amount,
    SUM(product_order_noncash_credit_redeemed_amount) AS product_order_noncash_credit_redeemed_amount,
    SUM(product_order_count) AS product_order_count,
    SUM(product_order_unit_count) AS product_order_unit_count,
    SUM(product_order_loyalty_unit_count) AS product_order_loyalty_unit_count,
    SUM(product_order_outfit_component_unit_count) AS product_order_outfit_component_unit_count,
    SUM(product_order_outfit_count) AS product_order_outfit_count,
    SUM(product_order_discounted_unit_count) AS product_order_discounted_unit_count,
    SUM(product_order_zero_revenue_unit_count) AS product_order_zero_revenue_unit_count,
    SUM(product_order_landed_product_cost_amount) AS product_order_landed_product_cost_amount,
    SUM(product_order_shipping_cost_amount) AS product_order_shipping_cost_amount,
    SUM(product_order_shipping_supplies_cost_amount) AS product_order_shipping_supplies_cost_amount,
    SUM(product_order_misc_cogs_amount) AS product_order_misc_cogs_amount,
    SUM(product_order_direct_cogs_amount) AS product_order_direct_cogs_amount,
    SUM(product_order_cash_refund_amount) AS product_order_cash_refund_amount,
    SUM(product_order_cash_credit_refund_amount) AS product_order_cash_credit_refund_amount,
    SUM(product_order_noncash_credit_refund_amount) AS product_order_noncash_credit_refund_amount,
    SUM(product_order_cash_chargeback_amount) AS product_order_cash_chargeback_amount,
    SUM(product_order_cost_product_returned_resaleable_amount) AS product_order_cost_product_returned_resaleable_amount,
    SUM(product_order_cost_product_returned_damaged_amount) AS product_order_cost_product_returned_damaged_amount,
    SUM(product_order_return_shipping_cost_amount) AS product_order_return_shipping_cost_amount,
    SUM(product_order_return_unit_count) AS product_order_return_unit_count,
    SUM(product_order_reship_order_count) AS product_order_reship_order_count,
    SUM(product_order_reship_unit_count) AS product_order_reship_unit_count,
    SUM(product_order_reship_direct_cogs_amount) AS product_order_reship_direct_cogs_amount,
    SUM(product_order_reship_product_cost_amount) AS product_order_reship_product_cost_amount,
    SUM(product_order_reship_shipping_cost_amount) AS product_order_reship_shipping_cost_amount,
    SUM(product_order_reship_shipping_supplies_cost_amount) AS product_order_reship_shipping_supplies_cost_amount,
    SUM(product_order_exchange_order_count) AS product_order_exchange_order_count,
    SUM(product_order_exchange_unit_count) AS product_order_exchange_unit_count,
    SUM(product_order_exchange_direct_cogs_amount) AS product_order_exchange_direct_cogs_amount,
    SUM(product_order_exchange_product_cost_amount) AS product_order_exchange_product_cost_amount,
    SUM(product_order_exchange_shipping_cost_amount) AS product_order_exchange_shipping_cost_amount,
    SUM(product_order_exchange_shipping_supplies_cost_amount) AS product_order_exchange_shipping_supplies_cost_amount,
    SUM(product_order_selling_expenses_amount) AS product_order_selling_expenses_amount,
    SUM(product_order_payment_processing_cost_amount) AS product_order_payment_processing_cost_amount,
    SUM(product_order_variable_gms_cost_amount) AS product_order_variable_gms_cost_amount,
    SUM(product_order_variable_warehouse_cost_amount) AS product_order_variable_warehouse_cost_amount,
    SUM(billing_selling_expenses_amount) AS billing_selling_expenses_amount,
    SUM(billing_payment_processing_cost_amount) AS billing_payment_processing_cost_amount,
    SUM(billing_variable_gms_cost_amount) AS billing_variable_gms_cost_amount,
    SUM(product_order_amount_to_pay) AS product_order_amount_to_pay,
    SUM(product_gross_revenue_excl_shipping) AS product_gross_revenue_excl_shipping,
    SUM(product_gross_revenue) AS product_gross_revenue,
    SUM(product_net_revenue) AS product_net_revenue,
    SUM(product_margin_pre_return) AS product_margin_pre_return,
    SUM(product_margin_pre_return_excl_shipping) AS product_margin_pre_return_excl_shipping,
    SUM(product_gross_profit) AS product_gross_profit,
    SUM(product_variable_contribution_profit) AS product_variable_contribution_profit,
    SUM(product_order_cash_gross_revenue_amount) AS product_order_cash_gross_revenue_amount,
    SUM(product_order_cash_net_revenue) AS product_order_cash_net_revenue,
    SUM(product_order_cash_margin_pre_return) AS product_order_cash_margin_pre_return,
    SUM(product_order_cash_gross_profit) AS product_order_cash_gross_profit,
    SUM(billing_cash_gross_revenue) AS billing_cash_gross_revenue,
    SUM(billing_cash_net_revenue) AS billing_cash_net_revenue,
    SUM(cash_gross_revenue) AS cash_gross_revenue,
    SUM(cash_net_revenue) AS cash_net_revenue,
    SUM(cash_gross_profit) AS cash_gross_profit,
    SUM(cash_variable_contribution_profit) AS cash_variable_contribution_profit,
    SUM(billing_order_transaction_count) AS billing_order_transaction_count,
    SUM(billed_credit_cash_transaction_count) AS billed_credit_cash_transaction_count,
    SUM(on_retry_billed_credit_cash_transaction_count) AS on_retry_billed_credit_cash_transaction_count,
    SUM(billing_cash_refund_amount) AS billing_cash_refund_amount,
    SUM(billing_cash_chargeback_amount) AS billing_cash_chargeback_amount,
    SUM(billed_credit_cash_transaction_amount) AS billed_credit_cash_transaction_amount,
    SUM(membership_fee_cash_transaction_amount) AS membership_fee_cash_transaction_amount,
    SUM(gift_card_transaction_amount) AS gift_card_transaction_amount,
    SUM(legacy_credit_cash_transaction_amount) AS legacy_credit_cash_transaction_amount,
    SUM(billed_credit_cash_refund_count) AS billed_credit_cash_refund_count,
    SUM(billed_credit_cash_refund_chargeback_amount) AS billed_credit_cash_refund_chargeback_amount,
    SUM(membership_fee_cash_refund_chargeback_amount) AS membership_fee_cash_refund_chargeback_amount,
    SUM(gift_card_cash_refund_chargeback_amount) AS gift_card_cash_refund_chargeback_amount,
    SUM(legacy_credit_cash_refund_chargeback_amount) AS legacy_credit_cash_refund_chargeback_amount,
    SUM(billed_cash_credit_issued_amount) AS billed_cash_credit_issued_amount,
    SUM(billed_cash_credit_redeemed_amount) AS billed_cash_credit_redeemed_amount,
    SUM(billed_cash_credit_cancelled_amount) AS billed_cash_credit_cancelled_amount,
    SUM(billed_cash_credit_expired_amount) AS billed_cash_credit_expired_amount,
    SUM(billed_cash_credit_issued_equivalent_count) AS billed_cash_credit_issued_equivalent_count,
    SUM(billed_cash_credit_redeemed_same_month_amount) AS billed_cash_credit_redeemed_same_month_amount,
    SUM(billed_cash_credit_redeemed_equivalent_count) AS billed_cash_credit_redeemed_equivalent_count,
    SUM(billed_cash_credit_cancelled_equivalent_count) AS billed_cash_credit_cancelled_equivalent_count,
    SUM(billed_cash_credit_expired_equivalent_count) AS billed_cash_credit_expired_equivalent_count,
    SUM(refund_cash_credit_issued_amount) AS refund_cash_credit_issued_amount,
    SUM(refund_cash_credit_redeemed_amount) AS refund_cash_credit_redeemed_amount,
    SUM(refund_cash_credit_cancelled_amount) AS refund_cash_credit_cancelled_amount,
    SUM(refund_cash_credit_expired_amount) AS refund_cash_credit_expired_amount,
    SUM(other_cash_credit_issued_amount) AS other_cash_credit_issued_amount,
    SUM(other_cash_credit_redeemed_amount) AS other_cash_credit_redeemed_amount,
    SUM(other_cash_credit_cancelled_amount) AS other_cash_credit_cancelled_amount,
    SUM(other_cash_credit_expired_amount) AS other_cash_credit_expired_amount,
    SUM(noncash_credit_issued_amount) AS noncash_credit_issued_amount,
    SUM(noncash_credit_cancelled_amount) AS noncash_credit_cancelled_amount,
    SUM(noncash_credit_expired_amount) AS noncash_credit_expired_amount,
    SUM(retail_ship_only_product_order_count) AS retail_ship_only_product_order_count,
    SUM(retail_ship_only_product_order_unit_count) AS retail_ship_only_product_order_unit_count,
    SUM(retail_ship_only_product_gross_revenue) AS retail_ship_only_product_gross_revenue,
    SUM(retail_ship_only_product_gross_revenue_excl_shipping) AS retail_ship_only_product_gross_revenue_excl_shipping,
    SUM(retail_ship_only_product_margin_pre_return) AS retail_ship_only_product_margin_pre_return,
    SUM(retail_ship_only_product_margin_pre_return_excl_shipping) AS retail_ship_only_product_margin_pre_return_excl_shipping,
    SUM(retail_ship_only_product_order_cash_margin_pre_return) AS retail_ship_only_product_order_cash_margin_pre_return,
    SUM(retail_ship_only_product_order_cash_gross_revenue) AS retail_ship_only_product_order_cash_gross_revenue,
    SUM(retail_ship_only_product_net_revenue) AS retail_ship_only_product_net_revenue,
    SUM(retail_ship_only_product_gross_profit) AS retail_ship_only_product_gross_profit,
    SUM(retail_ship_only_product_order_cash_net_revenue) AS retail_ship_only_product_order_cash_net_revenue,
    SUM(retail_ship_only_product_order_cash_gross_profit) AS retail_ship_only_product_order_cash_gross_profit,
    SUM(product_order_reship_exchange_cash_gross_revenue) AS product_order_reship_exchange_cash_gross_revenue
FROM snapshot.finance_sales_ops AS fso
WHERE
    date_object = 'shipped'
    AND currency_object = 'usd'
    AND snapshot_datetime IN ($previous_snapshot_datetime,$max_snapshot_datetime)
    AND date < $previous_snapshot_datetime::date -- to have current month consider the same amount of days;
 GROUP BY
    snapshot_datetime,
    store_brand,
    store_country,
    store_region,
    store_type,
    gender,
    is_retail_vip,
    COALESCE(is_cross_promo,FALSE),
    COALESCE(finance_specialty_store,'NULL'),
    membership_order_type_l3,
    month_date;

CREATE OR REPLACE TEMP TABLE _snapshot_aggregate_pivot AS
SELECT * FROM _snapshot_aggregate
    UNPIVOT ( value FOR metric IN (
    product_order_subtotal_excl_tariff_amount,
    product_order_tariff_amount,
    product_order_product_subtotal_amount,
    product_order_product_discount_amount,
    product_order_shipping_discount_amount,
    product_order_shipping_revenue_before_discount_amount,
    product_order_shipping_revenue_amount,
    product_order_tax_amount,
    product_order_cash_transaction_amount,
    product_order_cash_credit_redeemed_amount,
    product_order_noncash_credit_redeemed_amount,
    product_order_count,
    product_order_unit_count,
    product_order_loyalty_unit_count,
    product_order_outfit_component_unit_count,
    product_order_outfit_count,
    product_order_discounted_unit_count,
    product_order_zero_revenue_unit_count,
    product_order_landed_product_cost_amount,
    product_order_shipping_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_misc_cogs_amount,
    product_order_direct_cogs_amount,
    product_order_cash_refund_amount,
    product_order_cash_credit_refund_amount,
    product_order_noncash_credit_refund_amount,
    product_order_cash_chargeback_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_cost_product_returned_damaged_amount,
    product_order_return_shipping_cost_amount,
    product_order_return_unit_count,
    product_order_reship_order_count,
    product_order_reship_unit_count,
    product_order_reship_direct_cogs_amount,
    product_order_reship_product_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    product_order_exchange_order_count,
    product_order_exchange_unit_count,
    product_order_exchange_direct_cogs_amount,
    product_order_exchange_product_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_order_selling_expenses_amount,
    product_order_payment_processing_cost_amount,
    product_order_variable_gms_cost_amount,
    product_order_variable_warehouse_cost_amount,
    billing_selling_expenses_amount,
    billing_payment_processing_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    product_gross_revenue,
    product_net_revenue,
    product_margin_pre_return,
    product_margin_pre_return_excl_shipping,
    product_gross_profit,
    product_variable_contribution_profit,
    product_order_cash_gross_revenue_amount,
    product_order_cash_net_revenue,
    product_order_cash_margin_pre_return,
    product_order_cash_gross_profit,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    cash_variable_contribution_profit,
    billing_order_transaction_count,
    billed_credit_cash_transaction_count,
    on_retry_billed_credit_cash_transaction_count,
    billing_cash_refund_amount,
    billing_cash_chargeback_amount,
    billed_credit_cash_transaction_amount,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    billed_credit_cash_refund_count,
    billed_credit_cash_refund_chargeback_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_redeemed_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_same_month_amount,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount,
    retail_ship_only_product_order_count,
    retail_ship_only_product_order_unit_count,
    retail_ship_only_product_gross_revenue,
    retail_ship_only_product_gross_revenue_excl_shipping,
    retail_ship_only_product_margin_pre_return,
    retail_ship_only_product_margin_pre_return_excl_shipping,
    retail_ship_only_product_order_cash_margin_pre_return,
    retail_ship_only_product_order_cash_gross_revenue,
    retail_ship_only_product_net_revenue,
    retail_ship_only_product_gross_profit,
    retail_ship_only_product_order_cash_net_revenue,
    retail_ship_only_product_order_cash_gross_profit,
    product_order_reship_exchange_cash_gross_revenue
    ));

INSERT INTO validation.finance_sales_ops_historical_snapshot_comparison
(
    store_brand,
    store_country,
    store_region,
    store_type,
    gender,
    is_retail_vip,
    is_cross_promo,
    finance_specialty_store,
    membership_order_type_l3,
    month_date,
    metric,
    current_snapshot_value,
    previous_snapshot_value,
    variance,
    current_snapshot_datetime,
    previous_snapshot_datetime,
    meta_create_datetime,
    meta_update_datetime
)
WITH _previous_snapshot AS (
SELECT
    snapshot_datetime,
    store_brand,
    store_country,
    store_region,
    store_type,
    gender,
    is_retail_vip,
    is_cross_promo,
    finance_specialty_store,
    membership_order_type_l3,
    month_date,
    metric,
    value
FROM _snapshot_aggregate_pivot
WHERE snapshot_datetime = $previous_snapshot_datetime
)

, _max_snapshot AS (
SELECT
    snapshot_datetime,
    store_brand,
    store_country,
    store_region,
    store_type,
    gender,
    is_retail_vip,
    is_cross_promo,
    finance_specialty_store,
    membership_order_type_l3,
    month_date,
    metric,
    value
FROM _snapshot_aggregate_pivot
WHERE snapshot_datetime = $max_snapshot_datetime
 )

SELECT
    COALESCE(ms.store_brand,ps.store_brand) AS store_brand,
    COALESCE(ms.store_country,ps.store_country) AS store_country,
    COALESCE(ms.store_region,ps.store_region) AS store_region,
    COALESCE(ms.store_type,ps.store_type) AS store_type,
    COALESCE(ms.gender,ps.gender) AS gender,
    COALESCE(ms.is_retail_vip,ps.is_retail_vip) AS is_retail_vip,
    COALESCE(ms.is_cross_promo,ps.is_cross_promo) AS is_cross_promo,
    COALESCE(ms.finance_specialty_store,ps.finance_specialty_store) AS finance_specialty_store,
    COALESCE(ms.membership_order_type_l3,ps.membership_order_type_l3) AS membership_order_type_l3,
    COALESCE(ms.month_date,ps.month_date) AS month_date,
    COALESCE(ms.metric,ps.metric) AS metric,
    COALESCE(ms.value,0) AS current_snapshot_value,
    COALESCE(ps.value,0) AS previous_snapshot_value,
    COALESCE(ms.value,0) - COALESCE(ps.value,0) AS variance,
    $max_snapshot_datetime AS current_snapshot_datetime,
    $previous_snapshot_datetime AS previous_snapshot_datetime,
    $execution_start_time AS meta_create_datetime,
    $execution_start_time AS meta_update_datetime
FROM _max_snapshot AS ms
FULL JOIN _previous_snapshot AS ps
    ON ms.store_brand = ps.store_brand
    AND ms.store_country = ps.store_country
    AND ms.store_region = ps.store_region
    AND ms.store_type = ps.store_type
    AND ms.gender = ps.gender
    AND ms.is_retail_vip = ps.is_retail_vip
    AND ms.is_cross_promo = ps.is_cross_promo
    AND ms.finance_specialty_store = ps.finance_specialty_store
    AND ms.membership_order_type_l3 = ps.membership_order_type_l3
    AND ms.month_date = ps.month_date
    AND ms.metric = ps.metric
WHERE COALESCE(ps.value,0) <> COALESCE(ms.value,0);

SET delete_prior_date = DATEADD(day,-60,current_date);
DELETE FROM validation.finance_sales_ops_historical_snapshot_comparison WHERE meta_create_datetime < $delete_prior_date;
