SET execution_start_time = CURRENT_TIMESTAMP :: TIMESTAMP_LTZ(3);
CREATE OR REPLACE TEMP TABLE _orders AS
SELECT
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') as gender,
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE) AS is_cross_promo,
    IFNULL(dc.finance_specialty_store,'None') as finance_specialty_store,
    omc.membership_order_type_l3,
    fo.order_completion_local_datetime::date AS date,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',1,0)) AS product_order_count,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',unit_count,0)) AS product_order_unit_count,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',loyalty_unit_count,0)) AS product_order_loyalty_unit_count,
    SUM(IFF(LOWER(order_sales_channel_l1) = 'billing order',1,0)) AS billing_order_transaction_count,
    SUM(IFF(LOWER(order_classification_l2) IN ('credit billing', 'token billing'),1,0)) AS billed_credit_cash_transaction_count,
    SUM(IFF(LOWER(order_classification_l2) IN ('credit billing', 'token billing') AND is_credit_billing_on_retry = 1,1,0)) AS on_retry_billed_credit_cash_transaction_count,
    SUM(IFF(LOWER(order_sales_channel_l1) = 'billing order',cash_gross_revenue_local_amount * reporting_usd_conversion_rate ,0)) AS billing_cash_gross_revenue,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',subtotal_excl_tariff_local_amount * reporting_usd_conversion_rate,0)) AS product_order_subtotal_excl_tariff_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',product_subtotal_local_amount * reporting_usd_conversion_rate,0)) AS product_order_product_subtotal_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',tariff_revenue_local_amount * reporting_usd_conversion_rate,0)) AS product_order_tariff_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',product_discount_local_amount * reporting_usd_conversion_rate,0)) AS product_order_product_discount_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',shipping_discount_local_amount * reporting_usd_conversion_rate,0)) AS product_order_shipping_discount_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',shipping_revenue_before_discount_local_amount * reporting_usd_conversion_rate,0)) AS product_order_shipping_revenue_before_discount_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',tax_local_amount * reporting_usd_conversion_rate,0)) AS product_order_tax_amount,
    SUM(IFF(LOWER(order_classification_l1) IN ('product order','reship','exchange'), cash_gross_revenue_local_amount * reporting_usd_conversion_rate,0)) AS product_order_cash_gross_revenue_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',payment_transaction_local_amount * reporting_usd_conversion_rate,0)) AS product_order_cash_transaction_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order' AND foc.order_id IS NOT NULL,foc.cash_credit_redeemed_local_amount * reporting_usd_conversion_rate,0)) AS product_order_cash_credit_redeemed_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order' AND foc.order_id IS NOT NULL,foc.noncash_credit_redeemed_local_amount * reporting_usd_conversion_rate,0)) AS product_order_noncash_credit_redeemed_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',reporting_landed_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_landed_product_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',estimated_shipping_supplies_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_shipping_supplies_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',shipping_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_shipping_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) IN ('product order','reship','exchange'), misc_cogs_local_amount * reporting_usd_conversion_rate,0)) AS product_order_misc_cogs_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order',amount_to_pay * reporting_usd_conversion_rate,0)) AS product_order_amount_to_pay,
    SUM(product_margin_pre_return_local_amount * reporting_usd_conversion_rate) AS product_margin_pre_return,
    SUM(product_margin_pre_return_excl_shipping_local_amount * reporting_usd_conversion_rate) AS product_margin_pre_return_excl_shipping,
    SUM(product_order_cash_margin_pre_return_local_amount * reporting_usd_conversion_rate) AS product_order_cash_margin_pre_return,
    SUM(product_gross_revenue_local_amount * reporting_usd_conversion_rate) AS product_gross_revenue,
    SUM(product_gross_revenue_excl_shipping_local_amount * reporting_usd_conversion_rate) AS product_gross_revenue_excl_shipping,

    SUM(IFF(LOWER(order_classification_l1) = 'exchange',1,0)) AS product_order_exchange_order_count,
    SUM(IFF(LOWER(order_classification_l1) = 'exchange',unit_count,0)) AS product_order_exchange_unit_count,
    SUM(IFF(LOWER(order_classification_l1) = 'exchange',reporting_landed_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_exchange_product_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'exchange',shipping_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_exchange_shipping_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'exchange',estimated_shipping_supplies_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_exchange_shipping_supplies_cost_amount,

    SUM(IFF(LOWER(order_classification_l1) = 'reship',1,0)) AS product_order_reship_order_count,
    SUM(IFF(LOWER(order_classification_l1) = 'reship',unit_count,0)) AS product_order_reship_unit_count,
    SUM(IFF(LOWER(order_classification_l1) = 'reship',reporting_landed_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_reship_product_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'reship',shipping_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_reship_shipping_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'reship',estimated_shipping_supplies_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_reship_shipping_supplies_cost_amount,

    SUM(IFF(LOWER(order_sales_channel_l1) = 'billing order',estimated_variable_gms_cost_local_amount * reporting_usd_conversion_rate,0)) AS billing_variable_gms_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) IN ('product order','reship','exchange'),estimated_variable_gms_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_variable_gms_cost_amount,

    SUM(IFF(LOWER(order_classification_l1) IN ('billing order'),(cash_gross_revenue_local_amount * estimated_variable_payment_processing_pct_cash_revenue * reporting_usd_conversion_rate),0)) AS billing_payment_processing_cost_amount,
    SUM(IFF(LOWER(order_classification_l1) IN ('product order'),(cash_gross_revenue_local_amount * estimated_variable_payment_processing_pct_cash_revenue * reporting_usd_conversion_rate),0)) AS product_order_payment_processing_cost_amount,

    SUM(IFF(LOWER(order_classification_l1) IN ('product order','reship','exchange'),estimated_variable_warehouse_cost_local_amount * reporting_usd_conversion_rate,0)) AS product_order_variable_warehouse_cost_amount,
    SUM(IFF(LOWER(order_classification_l2) in ('credit billing', 'token billing'),cash_gross_revenue_local_amount * reporting_usd_conversion_rate,0)) AS billed_credit_cash_transaction_amount,
    SUM(IFF(LOWER(order_classification_l2) in ('membership fee'),cash_gross_revenue_local_amount * reporting_usd_conversion_rate,0)) AS membership_fee_cash_transaction_amount,
    SUM(IFF(LOWER(order_classification_l2) in ('gift certificate'),cash_gross_revenue_local_amount * reporting_usd_conversion_rate,0)) AS gift_card_transaction_amount,
    SUM(IFF(LOWER(order_classification_l2) in ('legacy credit'),cash_gross_revenue_local_amount * reporting_usd_conversion_rate,0)) AS legacy_credit_cash_transaction_amount,
    SUM(billed_cash_credit_redeemed_local_amount * reporting_usd_conversion_rate) AS billed_cash_credit_redeemed_amount,
    SUM(refund_cash_credit_redeemed_local_amount * reporting_usd_conversion_rate) AS refund_cash_credit_redeemed_amount,
    SUM(other_cash_credit_redeemed_local_amount * reporting_usd_conversion_rate) AS other_cash_credit_redeemed_amount,
    SUM(billed_cash_credit_redeemed_equivalent_count) AS billed_cash_credit_redeemed_equivalent_count,
    SUM(billed_cash_credit_redeemed_same_month_local_amount * reporting_usd_conversion_rate) AS billed_cash_credit_redeemed_same_month_amount,
    SUM(IFF(LOWER(order_classification_l1) = 'product order' AND osc.is_retail_ship_only_order = TRUE,1,0)) AS retail_ship_only_product_order_count,
    SUM(IFF(LOWER(order_classification_l1) = 'product order' AND osc.is_retail_ship_only_order = TRUE, unit_count, 0)) AS retail_ship_only_product_order_unit_count,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE, product_gross_revenue_local_amount * reporting_usd_conversion_rate, 0)) AS retail_ship_only_product_gross_revenue,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE, product_gross_revenue_excl_shipping_local_amount * reporting_usd_conversion_rate, 0)) AS retail_ship_only_product_gross_revenue_excl_shipping,
    SUM(IFF(LOWER(order_classification_l1) = 'product order' AND is_retail_ship_only_order = TRUE, cash_gross_revenue_local_amount * reporting_usd_conversion_rate, 0)) AS retail_ship_only_product_order_cash_gross_revenue,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE, product_margin_pre_return_local_amount * reporting_usd_conversion_rate, 0)) AS retail_ship_only_product_margin_pre_return,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE, product_margin_pre_return_excl_shipping_local_amount * reporting_usd_conversion_rate, 0)) AS retail_ship_only_product_margin_pre_return_excl_shipping,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE, product_order_cash_margin_pre_return_local_amount * reporting_usd_conversion_rate, 0)) AS retail_ship_only_product_order_cash_margin_pre_return,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE AND LOWER(order_classification_l1) IN ('reship','exchange'), reporting_landed_cost_local_amount * reporting_usd_conversion_rate,0)) AS retail_ship_only_reship_exchange_product_cost_amount,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE AND LOWER(order_classification_l1) IN ('reship','exchange'), shipping_cost_local_amount * reporting_usd_conversion_rate,0)) AS retail_ship_only_reship_exchange_shipping_cost_amount,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE AND LOWER(order_classification_l1) IN ('reship','exchange'), estimated_shipping_supplies_cost_local_amount * reporting_usd_conversion_rate,0)) AS retail_ship_only_reship_exchange_shipping_supplies_cost_amount,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE AND LOWER(order_classification_l1) = 'product order',misc_cogs_local_amount * reporting_usd_conversion_rate,0)) AS retail_ship_only_misc_cogs_amount,
    SUM(fo.cash_gross_revenue_local_amount * reporting_usd_conversion_rate) AS cash_gross_revenue
FROM data_model.fact_order AS fo
LEFT JOIN data_model.dim_customer AS dc ON dc.customer_id = fo.customer_id
JOIN data_model.fact_activation AS fa ON fa.activation_key = fo.activation_key
JOIN data_model.dim_store AS st ON st.store_id = fo.store_id
JOIN data_model.dim_order_sales_channel AS osc ON osc.order_sales_channel_key = fo.order_sales_channel_key
JOIN data_model.dim_order_membership_classification AS omc ON omc.order_membership_classification_key = fo.order_membership_classification_key
LEFT JOIN data_model.fact_order_credit AS foc ON foc.order_id = fo.order_id
JOIN data_model.dim_order_status AS os ON os.order_status_key = fo.order_status_key
WHERE os.order_status IN ('Success','Pending')
    AND fo.order_completion_local_datetime IS NOT NULL
    AND st.is_core_store = TRUE
GROUP BY
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F'),
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE),
    IFNULL(dc.finance_specialty_store,'None'),
    omc.membership_order_type_l3,
    fo.order_completion_local_datetime::date;


CREATE OR REPLACE TEMP TABLE _order_line AS
SELECT
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') AS gender,
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE) as is_cross_promo,
    IFNULL(dc.finance_specialty_store,'None') AS finance_specialty_store,
    omc.membership_order_type_l3,
    fo.order_completion_local_datetime::date AS date,
    COUNT(DISTINCT CASE WHEN fol.bundle_order_line_id <> -1 THEN fol.bundle_order_line_id END) AS product_order_outfit_count,
    SUM(IFF(LOWER(pt.product_type_name) = 'bundle component', fol.item_quantity,0)) AS product_order_outfit_component_unit_count,
    SUM(IFF(fol.product_discount_local_amount > 0,fol.item_quantity,0)) AS product_order_discounted_unit_count,
    SUM(IFF(fol.subtotal_excl_tariff_local_amount + fol.tariff_revenue_local_amount - fol.product_discount_local_amount  - fol.non_cash_credit_local_amount <= 0, fol.item_quantity,0)) AS product_order_zero_revenue_unit_count
FROM data_model.fact_order_line AS fol
JOIN data_model.fact_order AS fo ON fo.order_id = fol.order_id
LEFT JOIN data_model.dim_customer AS dc ON dc.customer_id = fol.customer_id
JOIN data_model.fact_activation AS fa ON fa.activation_key = fo.activation_key
JOIN data_model.dim_store AS st ON st.store_id = fol.store_id
JOIN data_model.dim_order_sales_channel AS osc ON osc.order_sales_channel_key = fol.order_sales_channel_key
JOIN data_model.dim_order_membership_classification AS omc ON omc.order_membership_classification_key = fol.order_membership_classification_key
JOIN data_model.dim_order_status AS os ON os.order_status_key = fol.order_status_key
JOIN data_model.dim_order_line_status AS ols ON ols.order_line_status_key = fol.order_line_status_key
JOIN data_model.dim_product_type AS pt ON pt.product_type_key = fol.product_type_key
WHERE os.order_status IN ('Success','Pending')
    AND ols.order_line_status <> 'Cancelled'
    AND osc.order_classification_l1 = 'Product Order'
    AND fo.order_completion_local_datetime IS NOT NULL
    AND pt.is_free = FALSE
    AND st.is_core_store = TRUE
GROUP BY
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F'),
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE),
    IFNULL(dc.finance_specialty_store,'None'),
    omc.membership_order_type_l3,
    fo.order_completion_local_datetime::date;


-- refunds
create or REPLACE temp TABLE _refunds as
SELECT
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') AS gender,
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE) AS is_cross_promo,
    IFNULL(dc.finance_specialty_store,'None') AS finance_specialty_store,
    omc.membership_order_type_l3,
    fr.refund_completion_local_datetime::date AS date,
    SUM(IFF(osc.order_classification_l1 = 'Product Order',fr.cash_refund_local_amount * reporting_usd_conversion_rate,0)) AS product_order_cash_refund_amount,
    SUM(IFF(osc.order_sales_channel_l1 = 'Billing Order',fr.cash_refund_local_amount * reporting_usd_conversion_rate,0)) AS billing_cash_refund_amount,
    SUM(IFF(osc.order_classification_l1 = 'Product Order',fr.store_credit_refund_local_amount * reporting_usd_conversion_rate,0)) AS product_order_credit_refund_amount,
    SUM(IFF(osc.order_classification_l1 = 'Product Order',(fr.cash_store_credit_refund_local_amount + fr.unknown_store_credit_refund_local_amount) * reporting_usd_conversion_rate,0)) AS product_order_cash_credit_refund_amount,
    SUM(IFF(osc.order_classification_l1 = 'Product Order',fr.noncash_store_credit_refund_local_amount * reporting_usd_conversion_rate,0)) AS product_order_noncash_credit_refund_amount,
    SUM(IFF(osc.order_classification_l2 IN ('Credit Billing', 'Token Billing'), fr.cash_refund_local_amount * reporting_usd_conversion_rate,0)) AS billed_credit_cash_refund_amount,
    SUM(IFF(osc.order_classification_l2 IN ('Credit Billing', 'Token Billing'), 1,0)) AS billed_credit_cash_refund_count,
    SUM(IFF(osc.order_classification_l2 = 'Membership Fee', fr.cash_refund_local_amount * reporting_usd_conversion_rate,0)) AS membership_fee_cash_refund_amount,
    SUM(IFF(osc.order_classification_l2 = 'Gift Certificate', fr.cash_refund_local_amount * reporting_usd_conversion_rate,0)) AS gift_card_cash_refund_amount,
    SUM(IFF(osc.order_classification_l2 = 'Legacy Credit', fr.cash_refund_local_amount * reporting_usd_conversion_rate,0)) AS legacy_credit_cash_refund_amount,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE AND osc.order_classification_l1 = 'Product Order',fr.cash_refund_local_amount * reporting_usd_conversion_rate,0)) AS retail_ship_only_cash_refund_amount,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE AND osc.order_classification_l1 = 'Product Order',fr.cash_store_credit_refund_local_amount * reporting_usd_conversion_rate,0)) AS retail_ship_only_cash_credit_refund_amount
FROM data_model.fact_refund AS fr
JOIN data_model.fact_order AS fo ON fo.order_id = fr.order_id
LEFT JOIN data_model.dim_customer AS dc ON dc.customer_id = fr.customer_id
JOIN data_model.fact_activation AS fa ON fa.activation_key = fr.activation_key
JOIN data_model.dim_store AS st ON st.store_id = fr.store_id
JOIN data_model.dim_order_sales_channel AS osc ON osc.order_sales_channel_key = fo.order_sales_channel_key
JOIN data_model.dim_order_membership_classification AS omc ON omc.order_membership_classification_key = fo.order_membership_classification_key
JOIN data_model.dim_refund_status rs ON rs.refund_status_key = fr.refund_status_key
WHERE LOWER(rs.refund_status) = 'refunded'
  AND fr.is_chargeback = 0
  AND fr.refund_completion_local_datetime IS NOT NULL
  AND st.is_core_store = TRUE
GROUP BY
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F'),
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE),
    IFNULL(dc.finance_specialty_store,'None'),
    omc.membership_order_type_l3,
    fr.refund_completion_local_datetime::date;



-- chargebacks
CREATE OR REPLACE TEMP TABLE _chargebacks as
SELECT
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') AS gender,
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE) AS is_cross_promo,
    IFNULL(dc.finance_specialty_store,'None') AS finance_specialty_store,
    omc.membership_order_type_l3,
    fc.chargeback_datetime::date AS date,
    SUM(IFF(osc.order_classification_l1 = 'Product Order',fc.chargeback_local_amount * chargeback_date_usd_conversion_rate,0)) AS product_order_cash_chargeback_amount,
    SUM(IFF(osc.order_sales_channel_l1 = 'Billing Order',fc.chargeback_local_amount * chargeback_date_usd_conversion_rate,0)) AS billing_cash_chargeback_amount,
    SUM(IFF(osc.order_classification_l2 IN ('Credit Billing', 'Token Billing'), fc.chargeback_local_amount * chargeback_date_usd_conversion_rate,0)) AS billed_credit_cash_chargeback_amount,
    SUM(IFF(osc.order_classification_l2 = 'Membership Fee', fc.chargeback_local_amount * chargeback_date_usd_conversion_rate,0)) AS membership_fee_cash_chargeback_amount,
    SUM(IFF(osc.order_classification_l2 = 'Gift Certificate', fc.chargeback_local_amount * chargeback_date_usd_conversion_rate,0)) AS gift_card_cash_chargeback_amount,
    SUM(IFF(osc.order_classification_l2 = 'Legacy Credit', fc.chargeback_local_amount * chargeback_date_usd_conversion_rate,0)) AS legacy_credit_cash_chargeback_amount,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE AND osc.order_classification_l1 = 'Product Order',fc.chargeback_local_amount * chargeback_date_usd_conversion_rate,0)) AS retail_ship_only_cash_chargeback_amount
FROM data_model.fact_chargeback AS fc
JOIN data_model.fact_order AS fo ON fo.order_id = fc.order_id
LEFT JOIN data_model.dim_customer AS dc ON dc.customer_id = fc.customer_id
JOIN data_model.fact_activation AS fa ON fa.activation_key = COALESCE(fc.activation_key,-1)
JOIN data_model.dim_store AS st ON st.store_id = fc.store_id
JOIN data_model.dim_order_sales_channel AS osc ON osc.order_sales_channel_key = fo.order_sales_channel_key
JOIN data_model.dim_order_membership_classification AS omc ON omc.order_membership_classification_key = fo.order_membership_classification_key
WHERE st.is_core_store = TRUE
GROUP BY
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F'),
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE),
    IFNULL(dc.finance_specialty_store,'None'),
    omc.membership_order_type_l3,
    fc.chargeback_datetime::DATE;

-- returns
CREATE OR REPLACE TEMP TABLE _returns AS
SELECT
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') AS gender,
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE) AS is_cross_promo,
    IFNULL(dc.finance_specialty_store,'None') AS finance_specialty_store,
    omc.membership_order_type_l3,
    frl.return_completion_local_datetime::date AS date,
    SUM(frl.return_item_quantity) AS product_order_return_unit_count,
    SUM(frl.estimated_return_shipping_cost_local_amount * reporting_usd_conversion_rate) AS product_order_return_shipping_cost_amount,
    SUM(frl.estimated_returned_product_cost_local_amount_resaleable * reporting_usd_conversion_rate) AS product_order_cost_product_returned_resaleable_amount,
    SUM(frl.estimated_returned_product_cost_local_amount_damaged * reporting_usd_conversion_rate) AS product_order_cost_product_returned_damaged_amount,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE, frl.estimated_return_shipping_cost_local_amount * reporting_usd_conversion_rate, 0)) AS retail_ship_only_return_shipping_cost,
    SUM(IFF(osc.is_retail_ship_only_order = TRUE, frl.estimated_returned_product_cost_local_amount_resaleable * reporting_usd_conversion_rate, 0)) AS retail_ship_only_product_returned_resaleable_amount
FROM data_model.fact_return_line AS frl
JOIN data_model.fact_order AS fo ON fo.order_id = frl.order_id
LEFT JOIN data_model.dim_customer AS dc ON dc.customer_id = frl.customer_id
JOIN data_model.fact_activation AS fa ON fa.activation_key = frl.activation_key
JOIN data_model.dim_store AS st ON st.store_id = frl.store_id
JOIN data_model.dim_order_sales_channel AS osc ON osc.order_sales_channel_key = fo.order_sales_channel_key
JOIN data_model.dim_order_membership_classification AS omc ON omc.order_membership_classification_key = fo.order_membership_classification_key
JOIN data_model.dim_return_status AS rs ON rs.return_status_key = frl.return_status_key
WHERE (rs.return_status = 'Resolved' OR frl.rma_product_id <> -1)
AND st.is_core_store = TRUE
GROUP BY
    st.store_brand,
    st.store_country,
    st.store_type,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F'),
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE),
    IFNULL(dc.finance_specialty_store,'None'),
    omc.membership_order_type_l3,
    frl.return_completion_local_datetime::DATE;


CREATE OR REPLACE TEMP TABLE _credit_base AS
SELECT
    CASE WHEN fce.redemption_store_id = -1 THEN dcr.store_id ELSE fce.redemption_store_id END AS store_id,
    IFF(dc.gender = 'M' AND dc.registration_local_datetime >= '2020-01-01','M','F') AS gender,
    fa.is_retail_vip,
    IFNULL(dc.is_cross_promo,FALSE) AS is_cross_promo,
    IFNULL(dc.finance_specialty_store,'None') AS finance_specialty_store,
    'Repeat VIP' AS membership_order_type_l3,
    fce.credit_activity_local_datetime::DATE AS date,
    fce.credit_activity_type,
    dcr.credit_report_mapping,
    fce.credit_activity_local_amount,
    fce.credit_activity_equivalent_count,
    fce.credit_activity_usd_conversion_rate
FROM data_model.dim_credit AS dcr
JOIN data_model.dim_store AS st ON st.store_id = dcr.store_id
JOIN data_model.fact_credit_event AS fce ON dcr.credit_key = fce.credit_key
LEFT JOIN data_model.dim_customer AS dc ON dc.customer_id = dcr.customer_id
LEFT JOIN data_model.fact_activation AS fa ON fa.activation_key = fce.activation_key
WHERE fce.original_credit_activity_type_action = 'Include'
AND fce.credit_activity_type IN ('Expired','Issued','Cancelled')
AND st.is_core_store = TRUE;

CREATE OR REPLACE TEMP TABLE _credit_activity AS
SELECT
    st.store_brand,
    st.store_country,
    st.store_type,
    cb.gender,
    cb.is_retail_vip,
    cb.is_cross_promo,
    cb.finance_specialty_store,
    cb.membership_order_type_l3,
    cb.date,
    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'billed credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS billed_cash_credit_issued_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'billed credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS billed_cash_credit_cancelled_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'billed credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS billed_cash_credit_expired_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'billed credit',credit_activity_equivalent_count,0)) AS billed_cash_credit_issued_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'billed credit',credit_activity_equivalent_count,0)) AS billed_cash_credit_cancelled_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'billed credit',credit_activity_equivalent_count,0)) AS billed_cash_credit_expired_equivalent_count,

    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'refund credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS refund_cash_credit_issued_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'refund credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS refund_cash_credit_cancelled_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'refund credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS refund_cash_credit_expired_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'refund credit',credit_activity_equivalent_count,0)) AS refund_cash_credit_issued_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'refund credit',credit_activity_equivalent_count,0)) AS refund_cash_credit_cancelled_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'refund credit',credit_activity_equivalent_count,0)) AS refund_cash_credit_expired_equivalent_count,

    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'noncash credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS noncash_credit_issued_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'noncash credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS noncash_credit_cancelled_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'noncash credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS noncash_credit_expired_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'noncash credit',credit_activity_equivalent_count,0)) AS noncash_credit_issued_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'noncash credit',credit_activity_equivalent_count,0)) AS noncash_credit_cancelled_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'noncash credit',credit_activity_equivalent_count,0)) AS noncash_credit_expired_equivalent_count,

    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'other cash credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS other_cash_credit_issued_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'other cash credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS other_cash_credit_cancelled_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'other cash credit',credit_activity_local_amount * credit_activity_usd_conversion_rate,0)) AS other_cash_credit_expired_amount,
    SUM(IFF(LOWER(credit_activity_type) = 'issued' AND LOWER(credit_report_mapping) = 'other cash credit',credit_activity_equivalent_count,0)) AS other_cash_credit_issued_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'cancelled' AND LOWER(credit_report_mapping) = 'other cash credit',credit_activity_equivalent_count,0)) AS other_cash_credit_cancelled_equivalent_count,
    SUM(IFF(LOWER(credit_activity_type) = 'expired' AND LOWER(credit_report_mapping) = 'other cash credit',credit_activity_equivalent_count,0)) AS other_cash_credit_expired_equivalent_count
FROM _credit_base AS cb
JOIN data_model.dim_store AS st ON st.store_id = cb.store_id
GROUP BY
    st.store_brand,
    st.store_country,
    st.store_type,
    cb.gender,
    cb.is_retail_vip,
    cb.is_cross_promo,
    cb.finance_specialty_store,
    cb.membership_order_type_l3,
    cb.date;


CREATE OR REPLACE TEMPORARY TABLE _fact_table_data (
date DATE,
store_brand VARCHAR(30),
store_country VARCHAR(10),
store_type VARCHAR(30),
gender VARCHAR(20),
is_retail_vip BOOLEAN,
is_cross_promo BOOLEAN,
finance_specialty_store VARCHAR(50),
membership_order_type_l3 VARCHAR(50),
product_order_count NUMBER(38,4),
product_order_unit_count NUMBER(38,4),
product_order_loyalty_unit_count NUMBER(38,4),
billing_order_transaction_count NUMBER(38,4),
billed_credit_cash_transaction_count NUMBER(38,4),
on_retry_billed_credit_cash_transaction_count NUMBER(38,4),
billing_cash_gross_revenue NUMBER(38,4),
product_order_subtotal_excl_tariff_amount NUMBER(38,4),
product_order_tariff_amount NUMBER(38,4),
product_order_product_discount_amount NUMBER(38,4),
product_order_shipping_discount_amount NUMBER(38,4),
product_order_shipping_revenue_before_discount_amount NUMBER(38,4),
product_order_tax_amount NUMBER(38,4),
product_order_cash_gross_revenue_amount NUMBER(38,4),
product_order_cash_transaction_amount NUMBER(38,4),
product_order_cash_credit_redeemed_amount NUMBER(38,4),
product_order_noncash_credit_redeemed_amount NUMBER(38,4),
product_order_landed_product_cost_amount NUMBER(38,4),
product_order_shipping_supplies_cost_amount NUMBER(38,4),
product_order_shipping_cost_amount NUMBER(38,4),
product_order_misc_cogs_amount NUMBER(38,4),
product_order_amount_to_pay NUMBER(38,4),
product_margin_pre_return NUMBER(38,4),
product_margin_pre_return_excl_shipping NUMBER(38,4),
product_order_cash_margin_pre_return NUMBER(38,4),
product_gross_revenue NUMBER(38,4),
product_gross_revenue_excl_shipping NUMBER(38,4),
product_order_exchange_order_count NUMBER(38,4),
product_order_exchange_unit_count NUMBER(38,4),
product_order_exchange_product_cost_amount NUMBER(38,4),
product_order_exchange_shipping_cost_amount NUMBER(38,4),
product_order_exchange_shipping_supplies_cost_amount NUMBER(38,4),
product_order_reship_order_count NUMBER(38,4),
product_order_reship_unit_count NUMBER(38,4),
product_order_reship_product_cost_amount NUMBER(38,4),
product_order_reship_shipping_cost_amount NUMBER(38,4),
product_order_reship_shipping_supplies_cost_amount NUMBER(38,4),
billing_variable_gms_cost_amount NUMBER(38,4),
product_order_variable_gms_cost_amount NUMBER(38,4),
billing_payment_processing_cost_amount NUMBER(38,4),
product_order_payment_processing_cost_amount NUMBER(38,4),
product_order_variable_warehouse_cost_amount NUMBER(38,4),
billed_credit_cash_transaction_amount NUMBER(38,4),
membership_fee_cash_transaction_amount NUMBER(38,4),
gift_card_transaction_amount NUMBER(38,4),
legacy_credit_cash_transaction_amount NUMBER(38,4),
billed_cash_credit_redeemed_amount NUMBER(38,4),
refund_cash_credit_redeemed_amount NUMBER(38,4),
other_cash_credit_redeemed_amount NUMBER(38,4),
billed_cash_credit_redeemed_equivalent_count NUMBER(38,4),
billed_cash_credit_redeemed_same_month_amount NUMBER(38,4),
retail_ship_only_product_order_count NUMBER(38,4),
retail_ship_only_product_order_unit_count NUMBER(38,4),
retail_ship_only_product_gross_revenue NUMBER(38,4),
retail_ship_only_product_gross_revenue_excl_shipping NUMBER(38,4),
retail_ship_only_product_order_cash_gross_revenue NUMBER(38,4),
retail_ship_only_product_margin_pre_return NUMBER(38,4),
retail_ship_only_product_margin_pre_return_excl_shipping NUMBER(38,4),
retail_ship_only_product_order_cash_margin_pre_return NUMBER(38,4),
retail_ship_only_product_net_revenue NUMBER(38,4),
retail_ship_only_product_gross_profit NUMBER(38,4),
retail_ship_only_product_order_cash_net_revenue NUMBER(38,4),
retail_ship_only_product_order_cash_gross_profit NUMBER(38,4),
product_order_cash_refund_amount NUMBER(38,4),
product_order_cash_credit_refund_amount NUMBER(38,4),
product_order_noncash_credit_refund_amount NUMBER(38,4),
billing_cash_refund_amount NUMBER(38,4),
billed_credit_cash_refund_count NUMBER(38,4),
billed_credit_cash_refund_chargeback_amount NUMBER(38,4),
membership_fee_cash_refund_chargeback_amount NUMBER(38,4),
gift_card_cash_refund_chargeback_amount NUMBER(38,4),
legacy_credit_cash_refund_chargeback_amount NUMBER(38,4),
product_order_cash_chargeback_amount NUMBER(38,4),
billing_cash_chargeback_amount NUMBER(38,4),
product_order_cost_product_returned_resaleable_amount NUMBER(38,4),
product_order_cost_product_returned_damaged_amount NUMBER(38,4),
product_order_return_shipping_cost_amount NUMBER(38,4),
product_order_return_unit_count NUMBER(38,4),
product_order_outfit_count NUMBER(38,4),
product_order_outfit_component_unit_count NUMBER(38,4),
product_order_discounted_unit_count NUMBER(38,4),
product_order_zero_revenue_unit_count NUMBER(38,4),
billed_cash_credit_issued_amount NUMBER(38,4),
billed_cash_credit_cancelled_amount NUMBER(38,4),
billed_cash_credit_expired_amount NUMBER(38,4),
billed_cash_credit_issued_equivalent_count NUMBER(38,4),
billed_cash_credit_cancelled_equivalent_count NUMBER(38,4),
billed_cash_credit_expired_equivalent_count NUMBER(38,4),
refund_cash_credit_issued_amount NUMBER(38,4),
refund_cash_credit_cancelled_amount NUMBER(38,4),
refund_cash_credit_expired_amount NUMBER(38,4),
noncash_credit_issued_amount NUMBER(38,4),
noncash_credit_cancelled_amount NUMBER(38,4),
noncash_credit_expired_amount NUMBER(38,4),
other_cash_credit_issued_amount NUMBER(38,4),
other_cash_credit_cancelled_amount NUMBER(38,4),
other_cash_credit_expired_amount NUMBER(38,4),
cash_gross_revenue NUMBER(38,4),
product_order_product_subtotal_amount NUMBER(38,4)
);

INSERT INTO _fact_table_data
(
date,
store_brand,
store_country,
store_type,
gender,
is_retail_vip,
is_cross_promo,
finance_specialty_store,
membership_order_type_l3,
product_order_count,
product_order_unit_count,
product_order_loyalty_unit_count,
billing_order_transaction_count,
billed_credit_cash_transaction_count,
on_retry_billed_credit_cash_transaction_count,
billing_cash_gross_revenue,
product_order_subtotal_excl_tariff_amount,
product_order_tariff_amount,
product_order_product_discount_amount,
product_order_shipping_discount_amount,
product_order_shipping_revenue_before_discount_amount,
product_order_tax_amount,
product_order_cash_gross_revenue_amount,
product_order_cash_transaction_amount,
product_order_cash_credit_redeemed_amount,
product_order_noncash_credit_redeemed_amount,
product_order_landed_product_cost_amount,
product_order_shipping_supplies_cost_amount,
product_order_shipping_cost_amount,
product_order_misc_cogs_amount,
product_order_amount_to_pay,
product_margin_pre_return,
product_margin_pre_return_excl_shipping,
product_order_cash_margin_pre_return,
product_gross_revenue,
product_gross_revenue_excl_shipping,
product_order_exchange_order_count,
product_order_exchange_unit_count,
product_order_exchange_product_cost_amount,
product_order_exchange_shipping_cost_amount,
product_order_exchange_shipping_supplies_cost_amount,
product_order_reship_order_count,
product_order_reship_unit_count,
product_order_reship_product_cost_amount,
product_order_reship_shipping_cost_amount,
product_order_reship_shipping_supplies_cost_amount,
billing_variable_gms_cost_amount,
product_order_variable_gms_cost_amount,
billing_payment_processing_cost_amount,
product_order_payment_processing_cost_amount,
product_order_variable_warehouse_cost_amount,
billed_credit_cash_transaction_amount,
membership_fee_cash_transaction_amount,
gift_card_transaction_amount,
legacy_credit_cash_transaction_amount,
billed_cash_credit_redeemed_amount,
refund_cash_credit_redeemed_amount,
other_cash_credit_redeemed_amount,
billed_cash_credit_redeemed_equivalent_count,
billed_cash_credit_redeemed_same_month_amount,
retail_ship_only_product_order_count,
retail_ship_only_product_order_unit_count,
retail_ship_only_product_gross_revenue,
retail_ship_only_product_gross_revenue_excl_shipping,
retail_ship_only_product_order_cash_gross_revenue,
retail_ship_only_product_margin_pre_return,
retail_ship_only_product_margin_pre_return_excl_shipping,
retail_ship_only_product_order_cash_margin_pre_return,
retail_ship_only_product_net_revenue,
retail_ship_only_product_gross_profit,
retail_ship_only_product_order_cash_net_revenue,
retail_ship_only_product_order_cash_gross_profit,
product_order_cash_refund_amount,
product_order_cash_credit_refund_amount,
product_order_noncash_credit_refund_amount,
billing_cash_refund_amount,
billed_credit_cash_refund_count,
billed_credit_cash_refund_chargeback_amount,
membership_fee_cash_refund_chargeback_amount,
gift_card_cash_refund_chargeback_amount,
legacy_credit_cash_refund_chargeback_amount,
product_order_cash_chargeback_amount,
billing_cash_chargeback_amount,
product_order_cost_product_returned_resaleable_amount,
product_order_cost_product_returned_damaged_amount,
product_order_return_shipping_cost_amount,
product_order_return_unit_count,
product_order_outfit_count,
product_order_outfit_component_unit_count,
product_order_discounted_unit_count,
product_order_zero_revenue_unit_count,
billed_cash_credit_issued_amount,
billed_cash_credit_cancelled_amount,
billed_cash_credit_expired_amount,
billed_cash_credit_issued_equivalent_count,
billed_cash_credit_cancelled_equivalent_count,
billed_cash_credit_expired_equivalent_count,
refund_cash_credit_issued_amount,
refund_cash_credit_cancelled_amount,
refund_cash_credit_expired_amount,
noncash_credit_issued_amount,
noncash_credit_cancelled_amount,
noncash_credit_expired_amount,
other_cash_credit_issued_amount,
other_cash_credit_cancelled_amount,
other_cash_credit_expired_amount,
cash_gross_revenue,
product_order_product_subtotal_amount
)

SELECT
   COALESCE(o.date,rd.date,ch.date,rt.date,ca.date,ol.date) AS date,
    COALESCE(o.store_brand,rd.store_brand,ch.store_brand,rt.store_brand,ca.store_brand,ol.store_brand) AS store_brand,
    COALESCE(o.store_country,rd.store_country,ch.store_country,rt.store_country,ca.store_country,ol.store_country) AS store_country,
    COALESCE(o.store_type,rd.store_type,ch.store_type,rt.store_type,ca.store_type,ol.store_type) AS store_type,
    COALESCE(o.gender,rd.gender,ch.gender,rt.gender,ca.gender,ol.gender) AS gender,
    COALESCE(o.is_retail_vip,rd.is_retail_vip,ch.is_retail_vip,rt.is_retail_vip,ca.is_retail_vip,ol.is_retail_vip) AS is_retail_vip,
    COALESCE(o.is_cross_promo,rd.is_cross_promo,ch.is_cross_promo,rt.is_cross_promo,ca.is_cross_promo,ol.is_cross_promo) AS is_cross_promo,
    COALESCE(o.finance_specialty_store,rd.finance_specialty_store,ch.finance_specialty_store,rt.finance_specialty_store,ca.finance_specialty_store) AS finance_specialty_store,
    COALESCE(o.membership_order_type_l3,rd.membership_order_type_l3,ch.membership_order_type_l3,rt.membership_order_type_l3,ca.membership_order_type_l3) AS membership_order_type_l3,
    IFNULL(o.product_order_count,0) AS product_order_count,
    IFNULL(o.product_order_unit_count,0) AS product_order_unit_count,
    IFNULL(o.product_order_loyalty_unit_count,0) AS product_order_loyalty_unit_count,
    IFNULL(o.billing_order_transaction_count,0) AS billing_order_transaction_count,
    IFNULL(o.billed_credit_cash_transaction_count,0) AS billed_credit_cash_transaction_count,
    IFNULL(o.on_retry_billed_credit_cash_transaction_count,0) AS on_retry_billed_credit_cash_transaction_count,
    IFNULL(o.billing_cash_gross_revenue,0) AS billing_cash_gross_revenue,
    IFNULL(o.product_order_subtotal_excl_tariff_amount,0) AS product_order_subtotal_excl_tariff_amount,
    IFNULL(o.product_order_tariff_amount,0) AS product_order_tariff_amount,
    IFNULL(o.product_order_product_discount_amount,0) AS product_order_product_discount_amount,
    IFNULL(o.product_order_shipping_discount_amount,0) AS product_order_shipping_discount_amount,
    IFNULL(o.product_order_shipping_revenue_before_discount_amount,0) AS product_order_shipping_revenue_before_discount_amount,
    IFNULL(o.product_order_tax_amount,0) AS product_order_tax_amount,
    IFNULL(o.product_order_cash_gross_revenue_amount,0) AS product_order_cash_gross_revenue_amount,
    IFNULL(o.product_order_cash_transaction_amount,0) AS product_order_cash_transaction_amount,
    IFNULL(o.product_order_cash_credit_redeemed_amount,0) AS product_order_cash_credit_redeemed_amount,
    IFNULL(o.product_order_noncash_credit_redeemed_amount,0) AS product_order_noncash_credit_redeemed_amount,
    IFNULL(o.product_order_landed_product_cost_amount,0) AS product_order_landed_product_cost_amount,
    IFNULL(o.product_order_shipping_supplies_cost_amount,0) AS product_order_shipping_supplies_cost_amount,
    IFNULL(o.product_order_shipping_cost_amount,0) AS product_order_shipping_cost_amount,
    IFNULL(o.product_order_misc_cogs_amount,0) AS product_order_misc_cogs_amount,
    IFNULL(o.product_order_amount_to_pay,0) AS product_order_amount_to_pay,
    IFNULL(o.product_margin_pre_return,0) AS product_margin_pre_return,
    IFNULL(o.product_margin_pre_return_excl_shipping,0) AS product_margin_pre_return_excl_shipping,
    IFNULL(o.product_order_cash_margin_pre_return,0) AS product_order_cash_margin_pre_return,
    IFNULL(o.product_gross_revenue,0) AS product_gross_revenue,
    IFNULL(o.product_gross_revenue_excl_shipping,0) AS product_gross_revenue_excl_shipping,
    IFNULL(o.product_order_exchange_order_count,0) AS product_order_exchange_order_count,
    IFNULL(o.product_order_exchange_unit_count,0) AS product_order_exchange_unit_count,
    IFNULL(o.product_order_exchange_product_cost_amount,0) AS product_order_exchange_product_cost_amount,
    IFNULL(o.product_order_exchange_shipping_cost_amount,0) AS product_order_exchange_shipping_cost_amount,
    IFNULL(o.product_order_exchange_shipping_supplies_cost_amount,0) AS product_order_exchange_shipping_supplies_cost_amount,
    IFNULL(o.product_order_reship_order_count,0) AS product_order_reship_order_count,
    IFNULL(o.product_order_reship_unit_count,0) AS product_order_reship_unit_count,
    IFNULL(o.product_order_reship_product_cost_amount,0) AS product_order_reship_product_cost_amount,
    IFNULL(o.product_order_reship_shipping_cost_amount,0) AS product_order_reship_shipping_cost_amount,
    IFNULL(o.product_order_reship_shipping_supplies_cost_amount,0) AS product_order_reship_shipping_supplies_cost_amount,
    IFNULL(o.billing_variable_gms_cost_amount,0) AS billing_variable_gms_cost_amount,
    IFNULL(o.product_order_variable_gms_cost_amount,0) AS product_order_variable_gms_cost_amount,
    IFNULL(o.billing_payment_processing_cost_amount,0) AS billing_payment_processing_cost_amount,
    IFNULL(o.product_order_payment_processing_cost_amount,0) AS product_order_payment_processing_cost_amount,
    IFNULL(o.product_order_variable_warehouse_cost_amount,0) AS product_order_variable_warehouse_cost_amount,
    IFNULL(o.billed_credit_cash_transaction_amount,0) AS billed_credit_cash_transaction_amount,
    IFNULL(o.membership_fee_cash_transaction_amount,0) AS membership_fee_cash_transaction_amount,
    IFNULL(o.gift_card_transaction_amount,0) AS gift_card_transaction_amount,
    IFNULL(o.legacy_credit_cash_transaction_amount,0) AS legacy_credit_cash_transaction_amount,
    IFNULL(o.billed_cash_credit_redeemed_amount,0) AS billed_cash_credit_redeemed_amount,
    IFNULL(o.refund_cash_credit_redeemed_amount,0) AS refund_cash_credit_redeemed_amount,
    IFNULL(o.other_cash_credit_redeemed_amount,0) AS other_cash_credit_redeemed_amount,
    IFNULL(o.billed_cash_credit_redeemed_equivalent_count,0) AS billed_cash_credit_redeemed_equivalent_count,
    IFNULL(o.billed_cash_credit_redeemed_same_month_amount,0) AS billed_cash_credit_redeemed_same_month_amount,
    IFNULL(o.retail_ship_only_product_order_count,0) AS retail_ship_only_product_order_count,
    IFNULL(o.retail_ship_only_product_order_unit_count,0) AS retail_ship_only_product_order_unit_count,
    IFNULL(o.retail_ship_only_product_gross_revenue,0) AS retail_ship_only_product_gross_revenue,
    IFNULL(o.retail_ship_only_product_gross_revenue_excl_shipping,0) AS retail_ship_only_product_gross_revenue_excl_shipping,
    IFNULL(o.retail_ship_only_product_order_cash_gross_revenue,0) AS retail_ship_only_product_order_cash_gross_revenue,
    IFNULL(o.retail_ship_only_product_margin_pre_return,0) AS retail_ship_only_product_margin_pre_return,
    IFNULL(o.retail_ship_only_product_margin_pre_return_excl_shipping,0) AS retail_ship_only_product_margin_pre_return_excl_shipping,
    IFNULL(o.retail_ship_only_product_order_cash_margin_pre_return,0) AS retail_ship_only_product_order_cash_margin_pre_return,
    IFNULL(o.retail_ship_only_product_gross_revenue,0)
        - IFNULL(ch.retail_ship_only_cash_chargeback_amount,0)
        - IFNULL(rd.retail_ship_only_cash_refund_amount,0)
        - IFNULL(rd.retail_ship_only_cash_credit_refund_amount,0)
        AS retail_ship_only_product_net_revenue,
    IFNULL(o.retail_ship_only_product_margin_pre_return,0)
        - IFNULL(ch.retail_ship_only_cash_chargeback_amount,0)
        - IFNULL(rd.retail_ship_only_cash_refund_amount,0)
        - IFNULL(rd.retail_ship_only_cash_credit_refund_amount,0)
        - IFNULL(rt.retail_ship_only_return_shipping_cost,0)
        + IFNULL(rt.retail_ship_only_product_returned_resaleable_amount,0)
        - IFNULL(retail_ship_only_reship_exchange_product_cost_amount,0)
        - IFNULL(retail_ship_only_reship_exchange_shipping_cost_amount,0)
        - IFNULL(retail_ship_only_reship_exchange_shipping_supplies_cost_amount,0)
        - IFNULL(retail_ship_only_misc_cogs_amount,0)
        AS retail_ship_only_product_gross_profit,
    IFNULL(o.retail_ship_only_product_order_cash_gross_revenue,0)
        - IFNULL(ch.retail_ship_only_cash_chargeback_amount,0)
        - IFNULL(rd.retail_ship_only_cash_refund_amount,0)
        - IFNULL(rd.retail_ship_only_cash_credit_refund_amount,0)
        AS retail_ship_only_product_order_cash_net_revenue,
    IFNULL(o.retail_ship_only_product_order_cash_margin_pre_return,0)
        - IFNULL(ch.retail_ship_only_cash_chargeback_amount,0)
        - IFNULL(rd.retail_ship_only_cash_refund_amount,0)
        - IFNULL(rd.retail_ship_only_cash_credit_refund_amount,0)
        - IFNULL(rt.retail_ship_only_return_shipping_cost,0)
        + IFNULL(rt.retail_ship_only_product_returned_resaleable_amount,0)
        - IFNULL(o.retail_ship_only_reship_exchange_product_cost_amount,0)
        - IFNULL(o.retail_ship_only_reship_exchange_shipping_cost_amount,0)
        - IFNULL(o.retail_ship_only_reship_exchange_shipping_supplies_cost_amount,0)
        - IFNULL(o.retail_ship_only_misc_cogs_amount,0)
        AS retail_ship_only_product_order_cash_gross_profit,
    IFNULL(rd.product_order_cash_refund_amount,0) AS product_order_cash_refund_amount,
    IFNULL(rd.product_order_cash_credit_refund_amount,0) AS product_order_cash_credit_refund_amount,
    IFNULL(rd.product_order_noncash_credit_refund_amount,0) AS product_order_noncash_credit_refund_amount,
    IFNULL(rd.billing_cash_refund_amount,0) AS billing_cash_refund_amount,
    IFNULL(rd.billed_credit_cash_refund_count,0) AS billed_credit_cash_refund_count,
    IFNULL(rd.billed_credit_cash_refund_amount,0) + IFNULL(ch.billed_credit_cash_chargeback_amount,0) AS billed_credit_cash_refund_chargeback_amount,
    IFNULL(rd.membership_fee_cash_refund_amount,0) + IFNULL(ch.membership_fee_cash_chargeback_amount,0) AS membership_fee_cash_refund_chargeback_amount,
    IFNULL(rd.gift_card_cash_refund_amount,0) + IFNULL(ch.gift_card_cash_chargeback_amount,0) AS gift_card_cash_refund_chargeback_amount,
    IFNULL(rd.legacy_credit_cash_refund_amount,0) + IFNULL(ch.legacy_credit_cash_chargeback_amount,0) AS legacy_credit_cash_refund_chargeback_amount,
    IFNULL(ch.product_order_cash_chargeback_amount,0) AS product_order_cash_chargeback_amount,
    IFNULL(ch.billing_cash_chargeback_amount,0) AS billing_cash_chargeback_amount,
    IFNULL(rt.product_order_cost_product_returned_resaleable_amount,0) AS product_order_cost_product_returned_resaleable_amount,
    IFNULL(rt.product_order_cost_product_returned_damaged_amount,0) AS product_order_cost_product_returned_damaged_amount,
    IFNULL(rt.product_order_return_shipping_cost_amount,0) AS product_order_return_shipping_cost_amount,
    IFNULL(rt.product_order_return_unit_count,0) AS product_order_return_unit_count,
    IFNULL(ol.product_order_outfit_count,0) AS product_order_outfit_count,
    IFNULL(ol.product_order_outfit_component_unit_count,0) AS product_order_outfit_component_unit_count,
    IFNULL(ol.product_order_discounted_unit_count,0) AS product_order_discounted_unit_count,
    IFNULL(ol.product_order_zero_revenue_unit_count,0) AS product_order_zero_revenue_unit_count,
    IFNULL(ca.billed_cash_credit_issued_amount,0) AS billed_cash_credit_issued_amount,
    IFNULL(ca.billed_cash_credit_cancelled_amount,0) AS billed_cash_credit_cancelled_amount,
    IFNULL(ca.billed_cash_credit_expired_amount,0) AS billed_cash_credit_expired_amount,
    IFNULL(ca.billed_cash_credit_issued_equivalent_count,0) AS billed_cash_credit_issued_equivalent_count,
    IFNULL(ca.billed_cash_credit_cancelled_equivalent_count,0) AS billed_cash_credit_cancelled_equivalent_count,
    IFNULL(ca.billed_cash_credit_expired_equivalent_count,0) AS billed_cash_credit_expired_equivalent_count,
    IFNULL(ca.refund_cash_credit_issued_amount,0) AS refund_cash_credit_issued_amount,
    IFNULL(ca.refund_cash_credit_cancelled_amount,0) AS refund_cash_credit_cancelled_amount,
    IFNULL(ca.refund_cash_credit_expired_amount,0) AS refund_cash_credit_expired_amount,
    IFNULL(ca.noncash_credit_issued_amount,0) AS noncash_credit_issued_amount,
    IFNULL(ca.noncash_credit_cancelled_amount,0) AS noncash_credit_cancelled_amount,
    IFNULL(ca.noncash_credit_expired_amount,0) AS noncash_credit_expired_amount,
    IFNULL(ca.other_cash_credit_issued_amount,0) AS other_cash_credit_issued_amount,
    IFNULL(ca.other_cash_credit_cancelled_amount,0) AS other_cash_credit_cancelled_amount,
    IFNULL(ca.other_cash_credit_expired_amount,0) AS other_cash_credit_expired_amount,
    IFNULL(o.cash_gross_revenue,0) AS cash_gross_revenue,
    IFNULL(o.product_order_product_subtotal_amount,0) AS product_order_product_subtotal_amount
FROM _orders AS o
FULL JOIN _refunds rd ON
    o.date = rd.date
    AND o.store_brand = rd.store_brand
    AND o.store_country = rd.store_country
    AND o.store_type = rd.store_type
    AND o.gender = rd.gender
    AND o.is_retail_vip = rd.is_retail_vip
    AND o.is_cross_promo = rd.is_cross_promo
    AND o.finance_specialty_store = rd.finance_specialty_store
    AND o.membership_order_type_l3 = rd.membership_order_type_l3
FULL JOIN _chargebacks ch ON
    ch.date = COALESCE(o.date,rd.date)
    AND ch.store_brand = COALESCE(o.store_brand,rd.store_brand)
    AND ch.store_country = COALESCE(o.store_country,rd.store_country)
    AND ch.store_type = COALESCE(o.store_type,rd.store_type)
    AND ch.gender = COALESCE(o.gender,rd.gender)
    AND ch.is_retail_vip = COALESCE(o.is_retail_vip,rd.is_retail_vip)
    AND ch.is_cross_promo = COALESCE(o.is_cross_promo,rd.is_cross_promo)
    AND ch.finance_specialty_store = COALESCE(o.finance_specialty_store,rd.finance_specialty_store)
    AND ch.membership_order_type_l3 = COALESCE(o.membership_order_type_l3,rd.membership_order_type_l3)
FULL JOIN _returns rt ON
    rt.date = COALESCE(o.date,rd.date,ch.date)
    AND rt.store_brand = COALESCE(o.store_brand,rd.store_brand,ch.store_brand)
    AND rt.store_type = COALESCE(o.store_type,rd.store_type,ch.store_type)
    AND rt.store_country = COALESCE(o.store_country,rd.store_country,ch.store_country)
    AND rt.gender = COALESCE(o.gender,rd.gender,ch.gender)
    AND rt.is_retail_vip = COALESCE(o.is_retail_vip,rd.is_retail_vip,ch.is_retail_vip)
    AND rt.is_cross_promo = COALESCE(o.is_cross_promo,rd.is_cross_promo,ch.is_cross_promo)
    AND rt.finance_specialty_store = COALESCE(o.finance_specialty_store,rd.finance_specialty_store,ch.finance_specialty_store)
    AND rt.membership_order_type_l3 = COALESCE(o.membership_order_type_l3,rd.membership_order_type_l3,ch.membership_order_type_l3)
FULL JOIN _credit_activity ca ON
    ca.date = COALESCE(o.date,rd.date,ch.date,rt.date)
    AND ca.store_brand = COALESCE(o.store_brand,rd.store_brand,ch.store_brand,rt.store_brand)
    AND ca.store_country = COALESCE(o.store_country,rd.store_country,ch.store_country,rt.store_country)
    AND ca.store_type = COALESCE(o.store_type,rd.store_type,ch.store_type,rt.store_type)
    AND ca.gender = COALESCE(o.gender,rd.gender,ch.gender,rt.gender)
    AND ca.is_retail_vip = COALESCE(o.is_retail_vip,rd.is_retail_vip,ch.is_retail_vip,rt.is_retail_vip)
    AND ca.is_cross_promo = COALESCE(o.is_cross_promo,rd.is_cross_promo,ch.is_cross_promo,rt.is_cross_promo)
    AND ca.finance_specialty_store = COALESCE(o.finance_specialty_store,rd.finance_specialty_store,ch.finance_specialty_store,rt.finance_specialty_store)
    AND ca.membership_order_type_l3 = COALESCE(o.membership_order_type_l3,rd.membership_order_type_l3,ch.membership_order_type_l3,rt.membership_order_type_l3)
FULL JOIN _order_line ol ON
   ol.date = COALESCE(o.date,rd.date,ch.date,rt.date,ca.date)
    AND ol.store_brand = COALESCE(o.store_brand,rd.store_brand,ch.store_brand,rt.store_brand,ca.store_brand)
    AND ol.store_country = COALESCE(o.store_country,rd.store_country,ch.store_country,rt.store_country,ca.store_country)
    AND ol.store_type = COALESCE(o.store_type,rd.store_type,ch.store_type,rt.store_type,ca.store_type)
    AND ol.gender = COALESCE(o.gender,rd.gender,ch.gender,rt.gender,ca.gender)
    AND ol.is_retail_vip = COALESCE(o.is_retail_vip,rd.is_retail_vip,ch.is_retail_vip,rt.is_retail_vip,ca.is_retail_vip)
    AND ol.is_cross_promo = COALESCE(o.is_cross_promo,rd.is_cross_promo,ch.is_cross_promo,rt.is_cross_promo,ca.is_cross_promo)
    AND ol.finance_specialty_store = COALESCE(o.finance_specialty_store,rd.finance_specialty_store,ch.finance_specialty_store,rt.finance_specialty_store,ca.finance_specialty_store)
    AND ol.membership_order_type_l3 = COALESCE(o.membership_order_type_l3,rd.membership_order_type_l3,ch.membership_order_type_l3,rt.membership_order_type_l3,ca.membership_order_type_l3);

CREATE OR REPLACE TEMP TABLE _fact_table_data_pivot AS
SELECT * FROM _fact_table_data
    UNPIVOT ( value FOR metric IN (
    product_order_count,
    product_order_unit_count,
    product_order_loyalty_unit_count,
    billing_order_transaction_count,
    billed_credit_cash_transaction_count,
    on_retry_billed_credit_cash_transaction_count,
    billing_cash_gross_revenue,
    product_order_subtotal_excl_tariff_amount,
    product_order_tariff_amount,
    product_order_product_discount_amount,
    product_order_shipping_discount_amount,
    product_order_shipping_revenue_before_discount_amount,
    product_order_tax_amount,
    product_order_cash_gross_revenue_amount,
    product_order_cash_transaction_amount,
    product_order_cash_credit_redeemed_amount,
    product_order_noncash_credit_redeemed_amount,
    product_order_landed_product_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_shipping_cost_amount,
    product_order_misc_cogs_amount,
    product_order_amount_to_pay,
    product_margin_pre_return,
    product_margin_pre_return_excl_shipping,
    product_order_cash_margin_pre_return,
    product_gross_revenue,
    product_gross_revenue_excl_shipping,
    product_order_exchange_order_count,
    product_order_exchange_unit_count,
    product_order_exchange_product_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_order_reship_order_count,
    product_order_reship_unit_count,
    product_order_reship_product_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_variable_gms_cost_amount,
    billing_payment_processing_cost_amount,
    product_order_payment_processing_cost_amount,
    product_order_variable_warehouse_cost_amount,
    billed_credit_cash_transaction_amount,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    billed_cash_credit_redeemed_amount,
    refund_cash_credit_redeemed_amount,
    other_cash_credit_redeemed_amount,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_redeemed_same_month_amount,
    retail_ship_only_product_order_count,
    retail_ship_only_product_order_unit_count,
    retail_ship_only_product_gross_revenue,
    retail_ship_only_product_gross_revenue_excl_shipping,
    retail_ship_only_product_order_cash_gross_revenue,
    retail_ship_only_product_margin_pre_return,
    retail_ship_only_product_margin_pre_return_excl_shipping,
    retail_ship_only_product_order_cash_margin_pre_return,
    retail_ship_only_product_net_revenue,
    retail_ship_only_product_gross_profit,
    retail_ship_only_product_order_cash_net_revenue,
    retail_ship_only_product_order_cash_gross_profit,
    product_order_cash_refund_amount,
    product_order_cash_credit_refund_amount,
    product_order_noncash_credit_refund_amount,
    billing_cash_refund_amount,
    billed_credit_cash_refund_count,
    billed_credit_cash_refund_chargeback_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    product_order_cash_chargeback_amount,
    billing_cash_chargeback_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_cost_product_returned_damaged_amount,
    product_order_return_shipping_cost_amount,
    product_order_return_unit_count,
    product_order_outfit_count,
    product_order_outfit_component_unit_count,
    product_order_discounted_unit_count,
    product_order_zero_revenue_unit_count,
    billed_cash_credit_issued_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    cash_gross_revenue,
    product_order_product_subtotal_amount
));

CREATE OR REPLACE TEMP TABLE _fso
(
date DATE,
store_brand VARCHAR(30),
store_country VARCHAR(10),
store_type VARCHAR(30),
gender VARCHAR(20),
is_retail_vip BOOLEAN,
is_cross_promo BOOLEAN,
finance_specialty_store VARCHAR(50),
membership_order_type_l3 VARCHAR(50),
date_object VARCHAR(30),
product_order_subtotal_excl_tariff_amount NUMBER(38,4),
product_order_tariff_amount NUMBER(38,4),
product_order_product_subtotal_amount NUMBER(38,4),
product_order_product_discount_amount NUMBER(38,4),
product_order_shipping_discount_amount NUMBER(38,4),
product_order_shipping_revenue_before_discount_amount NUMBER(38,4),
product_order_tax_amount NUMBER(38,4),
product_order_cash_transaction_amount NUMBER(38,4),
product_order_cash_credit_redeemed_amount NUMBER(38,4),
product_order_noncash_credit_redeemed_amount NUMBER(38,4),
product_order_count NUMBER(38,4),
product_order_unit_count NUMBER(38,4),
product_order_loyalty_unit_count NUMBER(38,4),
product_order_outfit_component_unit_count NUMBER(38,4),
product_order_outfit_count NUMBER(38,4),
product_order_discounted_unit_count NUMBER(38,4),
product_order_zero_revenue_unit_count NUMBER(38,4),
product_order_landed_product_cost_amount NUMBER(38,4),
product_order_shipping_cost_amount NUMBER(38,4),
product_order_shipping_supplies_cost_amount NUMBER(38,4),
product_order_misc_cogs_amount NUMBER(38,4),
product_order_cash_refund_amount NUMBER(38,4),
product_order_cash_credit_refund_amount NUMBER(38,4),
product_order_noncash_credit_refund_amount NUMBER(38,4),
product_order_cash_chargeback_amount NUMBER(38,4),
product_order_cost_product_returned_resaleable_amount NUMBER(38,4),
product_order_cost_product_returned_damaged_amount NUMBER(38,4),
product_order_return_shipping_cost_amount NUMBER(38,4),
product_order_return_unit_count NUMBER(38,4),
product_order_reship_order_count NUMBER(38,4),
product_order_reship_unit_count NUMBER(38,4),
product_order_reship_product_cost_amount NUMBER(38,4),
product_order_reship_shipping_cost_amount NUMBER(38,4),
product_order_reship_shipping_supplies_cost_amount NUMBER(38,4),
product_order_exchange_order_count NUMBER(38,4),
product_order_exchange_unit_count NUMBER(38,4),
product_order_exchange_product_cost_amount NUMBER(38,4),
product_order_exchange_shipping_cost_amount NUMBER(38,4),
product_order_exchange_shipping_supplies_cost_amount NUMBER(38,4),
product_order_payment_processing_cost_amount NUMBER(38,4),
product_order_variable_gms_cost_amount NUMBER(38,4),
product_order_variable_warehouse_cost_amount NUMBER(38,4),
billing_payment_processing_cost_amount NUMBER(38,4),
billing_variable_gms_cost_amount NUMBER(38,4),
product_order_amount_to_pay NUMBER(38,4),
product_gross_revenue_excl_shipping NUMBER(38,4),
product_gross_revenue NUMBER(38,4),
product_margin_pre_return NUMBER(38,4),
product_margin_pre_return_excl_shipping NUMBER(38,4),
product_order_cash_gross_revenue_amount NUMBER(38,4),
product_order_cash_margin_pre_return NUMBER(38,4),
billing_cash_gross_revenue NUMBER(38,4),
cash_gross_revenue NUMBER(38,4),
billing_order_transaction_count NUMBER(38,4),
billed_credit_cash_transaction_count NUMBER(38,4),
on_retry_billed_credit_cash_transaction_count NUMBER(38,4),
billing_cash_refund_amount NUMBER(38,4),
billing_cash_chargeback_amount NUMBER(38,4),
billed_credit_cash_transaction_amount NUMBER(38,4),
membership_fee_cash_transaction_amount NUMBER(38,4),
gift_card_transaction_amount NUMBER(38,4),
legacy_credit_cash_transaction_amount NUMBER(38,4),
billed_credit_cash_refund_count NUMBER(38,4),
billed_credit_cash_refund_chargeback_amount NUMBER(38,4),
membership_fee_cash_refund_chargeback_amount NUMBER(38,4),
gift_card_cash_refund_chargeback_amount NUMBER(38,4),
legacy_credit_cash_refund_chargeback_amount NUMBER(38,4),
billed_cash_credit_issued_amount NUMBER(38,4),
billed_cash_credit_redeemed_amount NUMBER(38,4),
billed_cash_credit_cancelled_amount NUMBER(38,4),
billed_cash_credit_expired_amount NUMBER(38,4),
billed_cash_credit_issued_equivalent_count NUMBER(38,4),
billed_cash_credit_redeemed_same_month_amount NUMBER(38,4),
billed_cash_credit_redeemed_equivalent_count NUMBER(38,4),
billed_cash_credit_cancelled_equivalent_count NUMBER(38,4),
billed_cash_credit_expired_equivalent_count NUMBER(38,4),
refund_cash_credit_issued_amount NUMBER(38,4),
refund_cash_credit_redeemed_amount NUMBER(38,4),
refund_cash_credit_cancelled_amount NUMBER(38,4),
refund_cash_credit_expired_amount NUMBER(38,4),
other_cash_credit_issued_amount NUMBER(38,4),
other_cash_credit_redeemed_amount NUMBER(38,4),
other_cash_credit_cancelled_amount NUMBER(38,4),
other_cash_credit_expired_amount NUMBER(38,4),
noncash_credit_issued_amount NUMBER(38,4),
noncash_credit_cancelled_amount NUMBER(38,4),
noncash_credit_expired_amount NUMBER(38,4),
retail_ship_only_product_order_count NUMBER(38,4),
retail_ship_only_product_order_unit_count NUMBER(38,4),
retail_ship_only_product_gross_revenue NUMBER(38,4),
retail_ship_only_product_gross_revenue_excl_shipping NUMBER(38,4),
retail_ship_only_product_margin_pre_return NUMBER(38,4),
retail_ship_only_product_margin_pre_return_excl_shipping NUMBER(38,4),
retail_ship_only_product_order_cash_margin_pre_return NUMBER(38,4),
retail_ship_only_product_order_cash_gross_revenue NUMBER(38,4),
retail_ship_only_product_net_revenue NUMBER(38,4),
retail_ship_only_product_gross_profit NUMBER(38,4),
retail_ship_only_product_order_cash_net_revenue NUMBER(38,4),
retail_ship_only_product_order_cash_gross_profit NUMBER(38,4)
);

INSERT INTO _fso
(
store_brand,
store_country,
store_type,
gender,
is_retail_vip,
is_cross_promo,
finance_specialty_store,
membership_order_type_l3,
date_object,
date,
product_order_subtotal_excl_tariff_amount,
product_order_tariff_amount,
product_order_product_subtotal_amount,
product_order_product_discount_amount,
product_order_shipping_discount_amount,
product_order_shipping_revenue_before_discount_amount,
product_order_tax_amount,
product_order_cash_transaction_amount,
product_order_cash_credit_redeemed_amount,
product_order_noncash_credit_redeemed_amount,
product_order_count,
product_order_unit_count,
product_order_loyalty_unit_count,
product_order_outfit_component_unit_count,
product_order_outfit_count,
product_order_discounted_unit_count,
product_order_zero_revenue_unit_count,
product_order_landed_product_cost_amount,
product_order_shipping_cost_amount,
product_order_shipping_supplies_cost_amount,
product_order_misc_cogs_amount,
product_order_cash_refund_amount,
product_order_cash_credit_refund_amount,
product_order_noncash_credit_refund_amount,
product_order_cash_chargeback_amount,
product_order_cost_product_returned_resaleable_amount,
product_order_cost_product_returned_damaged_amount,
product_order_return_shipping_cost_amount,
product_order_return_unit_count,
product_order_reship_order_count,
product_order_reship_unit_count,
product_order_reship_product_cost_amount,
product_order_reship_shipping_cost_amount,
product_order_reship_shipping_supplies_cost_amount,
product_order_exchange_order_count,
product_order_exchange_unit_count,
product_order_exchange_product_cost_amount,
product_order_exchange_shipping_cost_amount,
product_order_exchange_shipping_supplies_cost_amount,
product_order_payment_processing_cost_amount,
product_order_variable_gms_cost_amount,
product_order_variable_warehouse_cost_amount,
billing_payment_processing_cost_amount,
billing_variable_gms_cost_amount,
product_order_amount_to_pay,
product_gross_revenue_excl_shipping,
product_gross_revenue,
product_margin_pre_return,
product_margin_pre_return_excl_shipping,
product_order_cash_gross_revenue_amount,
product_order_cash_margin_pre_return,
billing_cash_gross_revenue,
cash_gross_revenue,
billing_order_transaction_count,
billed_credit_cash_transaction_count,
on_retry_billed_credit_cash_transaction_count,
billing_cash_refund_amount,
billing_cash_chargeback_amount,
billed_credit_cash_transaction_amount,
membership_fee_cash_transaction_amount,
gift_card_transaction_amount,
legacy_credit_cash_transaction_amount,
billed_credit_cash_refund_count,
billed_credit_cash_refund_chargeback_amount,
membership_fee_cash_refund_chargeback_amount,
gift_card_cash_refund_chargeback_amount,
legacy_credit_cash_refund_chargeback_amount,
billed_cash_credit_issued_amount,
billed_cash_credit_redeemed_amount,
billed_cash_credit_cancelled_amount,
billed_cash_credit_expired_amount,
billed_cash_credit_issued_equivalent_count,
billed_cash_credit_redeemed_same_month_amount,
billed_cash_credit_redeemed_equivalent_count,
billed_cash_credit_cancelled_equivalent_count,
billed_cash_credit_expired_equivalent_count,
refund_cash_credit_issued_amount,
refund_cash_credit_redeemed_amount,
refund_cash_credit_cancelled_amount,
refund_cash_credit_expired_amount,
other_cash_credit_issued_amount,
other_cash_credit_redeemed_amount,
other_cash_credit_cancelled_amount,
other_cash_credit_expired_amount,
noncash_credit_issued_amount,
noncash_credit_cancelled_amount,
noncash_credit_expired_amount,
retail_ship_only_product_order_count,
retail_ship_only_product_order_unit_count,
retail_ship_only_product_gross_revenue,
retail_ship_only_product_gross_revenue_excl_shipping,
retail_ship_only_product_margin_pre_return,
retail_ship_only_product_margin_pre_return_excl_shipping,
retail_ship_only_product_order_cash_margin_pre_return,
retail_ship_only_product_order_cash_gross_revenue,
retail_ship_only_product_net_revenue,
retail_ship_only_product_gross_profit,
retail_ship_only_product_order_cash_net_revenue,
retail_ship_only_product_order_cash_gross_profit
)
SELECT
    st.store_brand,
    st.store_country,
    st.store_type,
    IFNULL(fso.gender,'F') AS gender,
    fso.is_retail_vip,
    IFNULL(fso.is_cross_promo,FALSE) AS is_cross_promo,
    IFNULL(fso.finance_specialty_store,'None') AS finance_specialty_store,
    omc.membership_order_type_l3,
    fso.date_object,
    fso.date,
    SUM(product_order_subtotal_excl_tariff_amount) AS product_order_subtotal_excl_tariff_amount,
    SUM(product_order_tariff_amount) AS product_order_tariff_amount,
    SUM(product_order_product_subtotal_amount) AS product_order_product_subtotal_amount,
    SUM(product_order_product_discount_amount) AS product_order_product_discount_amount,
    SUM(product_order_shipping_discount_amount) AS product_order_shipping_discount_amount,
    SUM(product_order_shipping_revenue_before_discount_amount) AS product_order_shipping_revenue_before_discount_amount,
    SUM(product_order_tax_amount) AS product_order_tax_amount,
    SUM(product_order_cash_transaction_amount) AS product_order_cash_transaction_amount,
    SUM(product_order_cash_credit_redeemed_amount) AS product_order_cash_credit_redeemed_amount,
    SUM(product_order_noncash_credit_redeemed_amount) AS product_order_noncash_credit_redeemed_amount,
    SUM(product_order_count) AS product_order_count,
    SUM(product_order_unit_count) AS product_order_unit_count,
    SUM(product_order_loyalty_unit_count) AS product_order_loyalty_unit_count,
    SUM(product_order_outfit_component_unit_count) AS product_order_outfit_component_unit_count,
    SUM(product_order_outfit_count) AS product_order_outfit_count,
    SUM(product_order_discounted_unit_count) AS product_order_discounted_unit_count,
    SUM(product_order_zero_revenue_unit_count) AS product_order_zero_revenue_unit_count,
    SUM(product_order_landed_product_cost_amount) AS product_order_landed_product_cost_amount,
    SUM(product_order_shipping_cost_amount) AS product_order_shipping_cost_amount,
    SUM(product_order_shipping_supplies_cost_amount) AS product_order_shipping_supplies_cost_amount,
    SUM(product_order_misc_cogs_amount) AS product_order_misc_cogs_amount,
    SUM(product_order_cash_refund_amount) AS product_order_cash_refund_amount,
    SUM(product_order_cash_credit_refund_amount) AS product_order_cash_credit_refund_amount,
    SUM(product_order_noncash_credit_refund_amount) AS product_order_noncash_credit_refund_amount,
    SUM(product_order_cash_chargeback_amount) AS product_order_cash_chargeback_amount,
    SUM(product_order_cost_product_returned_resaleable_amount) AS product_order_cost_product_returned_resaleable_amount,
    SUM(product_order_cost_product_returned_damaged_amount) AS product_order_cost_product_returned_damaged_amount,
    SUM(product_order_return_shipping_cost_amount) AS product_order_return_shipping_cost_amount,
    SUM(product_order_return_unit_count) AS product_order_return_unit_count,
    SUM(product_order_reship_order_count) AS product_order_reship_order_count,
    SUM(product_order_reship_unit_count) AS product_order_reship_unit_count,
    SUM(product_order_reship_product_cost_amount) AS product_order_reship_product_cost_amount,
    SUM(product_order_reship_shipping_cost_amount) AS product_order_reship_shipping_cost_amount,
    SUM(product_order_reship_shipping_supplies_cost_amount) AS product_order_reship_shipping_supplies_cost_amount,
    SUM(product_order_exchange_order_count) AS product_order_exchange_order_count,
    SUM(product_order_exchange_unit_count) AS product_order_exchange_unit_count,
    SUM(product_order_exchange_product_cost_amount) AS product_order_exchange_product_cost_amount,
    SUM(product_order_exchange_shipping_cost_amount) AS product_order_exchange_shipping_cost_amount,
    SUM(product_order_exchange_shipping_supplies_cost_amount) AS product_order_exchange_shipping_supplies_cost_amount,
    SUM(product_order_payment_processing_cost_amount) AS product_order_payment_processing_cost_amount,
    SUM(product_order_variable_gms_cost_amount) AS product_order_variable_gms_cost_amount,
    SUM(product_order_variable_warehouse_cost_amount) AS product_order_variable_warehouse_cost_amount,
    SUM(billing_payment_processing_cost_amount) AS billing_payment_processing_cost_amount,
    SUM(billing_variable_gms_cost_amount) AS billing_variable_gms_cost_amount,
    SUM(product_order_amount_to_pay) AS product_order_amount_to_pay,
    SUM(product_gross_revenue_excl_shipping) AS product_gross_revenue_excl_shipping,
    SUM(product_gross_revenue) AS product_gross_revenue,
    SUM(product_margin_pre_return) AS product_margin_pre_return,
    SUM(product_margin_pre_return_excl_shipping) AS product_margin_pre_return_excl_shipping,
    SUM(product_order_cash_gross_revenue_amount) AS product_order_cash_gross_revenue_amount,
    SUM(product_order_cash_margin_pre_return) AS product_order_cash_margin_pre_return,
    SUM(billing_cash_gross_revenue) AS billing_cash_gross_revenue,
    SUM(cash_gross_revenue) AS cash_gross_revenue,
    SUM(billing_order_transaction_count) AS billing_order_transaction_count,
    SUM(billed_credit_cash_transaction_count) AS billed_credit_cash_transaction_count,
    SUM(on_retry_billed_credit_cash_transaction_count) AS on_retry_billed_credit_cash_transaction_count,
    SUM(billing_cash_refund_amount) AS billing_cash_refund_amount,
    SUM(billing_cash_chargeback_amount) AS billing_cash_chargeback_amount,
    SUM(billed_credit_cash_transaction_amount) AS billed_credit_cash_transaction_amount,
    SUM(membership_fee_cash_transaction_amount) AS membership_fee_cash_transaction_amount,
    SUM(gift_card_transaction_amount) AS gift_card_transaction_amount,
    SUM(legacy_credit_cash_transaction_amount) AS legacy_credit_cash_transaction_amount,
    SUM(billed_credit_cash_refund_count) AS billed_credit_cash_refund_count,
    SUM(billed_credit_cash_refund_chargeback_amount) AS billed_credit_cash_refund_chargeback_amount,
    SUM(membership_fee_cash_refund_chargeback_amount) AS membership_fee_cash_refund_chargeback_amount,
    SUM(gift_card_cash_refund_chargeback_amount) AS gift_card_cash_refund_chargeback_amount,
    SUM(legacy_credit_cash_refund_chargeback_amount) AS legacy_credit_cash_refund_chargeback_amount,
    SUM(billed_cash_credit_issued_amount) AS billed_cash_credit_issued_amount,
    SUM(billed_cash_credit_redeemed_amount) AS billed_cash_credit_redeemed_amount,
    SUM(billed_cash_credit_cancelled_amount) AS billed_cash_credit_cancelled_amount,
    SUM(billed_cash_credit_expired_amount) AS billed_cash_credit_expired_amount,
    SUM(billed_cash_credit_issued_equivalent_count) AS billed_cash_credit_issued_equivalent_count,
    SUM(billed_cash_credit_redeemed_same_month_amount) AS billed_cash_credit_redeemed_same_month_amount,
    SUM(billed_cash_credit_redeemed_equivalent_count) AS billed_cash_credit_redeemed_equivalent_count,
    SUM(billed_cash_credit_cancelled_equivalent_count) AS billed_cash_credit_cancelled_equivalent_count,
    SUM(billed_cash_credit_expired_equivalent_count) AS billed_cash_credit_expired_equivalent_count,
    SUM(refund_cash_credit_issued_amount) AS refund_cash_credit_issued_amount,
    SUM(refund_cash_credit_redeemed_amount) AS refund_cash_credit_redeemed_amount,
    SUM(refund_cash_credit_cancelled_amount) AS refund_cash_credit_cancelled_amount,
    SUM(refund_cash_credit_expired_amount) AS refund_cash_credit_expired_amount,
    SUM(other_cash_credit_issued_amount) AS other_cash_credit_issued_amount,
    SUM(other_cash_credit_redeemed_amount) AS other_cash_credit_redeemed_amount,
    SUM(other_cash_credit_cancelled_amount) AS other_cash_credit_cancelled_amount,
    SUM(other_cash_credit_expired_amount) AS other_cash_credit_expired_amount,
    SUM(noncash_credit_issued_amount) AS noncash_credit_issued_amount,
    SUM(noncash_credit_cancelled_amount) AS noncash_credit_cancelled_amount,
    SUM(noncash_credit_expired_amount) AS noncash_credit_expired_amount,
    SUM(retail_ship_only_product_order_count) AS retail_ship_only_product_order_count,
    SUM(retail_ship_only_product_order_unit_count) AS retail_ship_only_product_order_unit_count,
    SUM(retail_ship_only_product_gross_revenue) AS retail_ship_only_product_gross_revenue,
    SUM(retail_ship_only_product_gross_revenue_excl_shipping) AS retail_ship_only_product_gross_revenue_excl_shipping,
    SUM(retail_ship_only_product_margin_pre_return) AS retail_ship_only_product_margin_pre_return,
    SUM(retail_ship_only_product_margin_pre_return_excl_shipping) AS retail_ship_only_product_margin_pre_return_excl_shipping,
    SUM(retail_ship_only_product_order_cash_margin_pre_return) AS retail_ship_only_product_order_cash_margin_pre_return,
    SUM(retail_ship_only_product_order_cash_gross_revenue) AS retail_ship_only_product_order_cash_gross_revenue,
    SUM(retail_ship_only_product_net_revenue) AS retail_ship_only_product_net_revenue,
    SUM(retail_ship_only_product_gross_profit) AS retail_ship_only_product_gross_profit,
    SUM(retail_ship_only_product_order_cash_net_revenue) AS retail_ship_only_product_order_cash_net_revenue,
    SUM(retail_ship_only_product_order_cash_gross_profit) AS retail_ship_only_product_order_cash_gross_profit
FROM analytics_base.finance_sales_ops as fso
join data_model.dim_store as st on st.store_id = fso.store_id
JOIN data_model.dim_order_membership_classification AS omc ON omc.order_membership_classification_key = fso.order_membership_classification_key
WHERE fso.currency_object = 'usd' and date_object = 'shipped'
GROUP BY
    st.store_brand,
    st.store_country,
    st.store_type,
    IFNULL(fso.gender,'F'),
    fso.is_retail_vip,
    IFNULL(fso.is_cross_promo,FALSE),
    IFNULL(fso.finance_specialty_store,'None'),
    omc.membership_order_type_l3,
    fso.date_object,
    fso.date;


CREATE OR REPLACE TEMP TABLE _fso_pivot AS
SELECT * FROM _fso
    UNPIVOT ( value FOR metric IN (
    product_order_subtotal_excl_tariff_amount,
    product_order_tariff_amount,
    product_order_product_subtotal_amount,
    product_order_product_discount_amount,
    product_order_shipping_discount_amount,
    product_order_shipping_revenue_before_discount_amount,
    product_order_tax_amount,
    product_order_cash_transaction_amount,
    product_order_cash_credit_redeemed_amount,
    product_order_noncash_credit_redeemed_amount,
    product_order_count,
    product_order_unit_count,
    product_order_loyalty_unit_count,
    product_order_outfit_component_unit_count,
    product_order_outfit_count,
    product_order_discounted_unit_count,
    product_order_zero_revenue_unit_count,
    product_order_landed_product_cost_amount,
    product_order_shipping_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_misc_cogs_amount,
    product_order_cash_refund_amount,
    product_order_cash_credit_refund_amount,
    product_order_noncash_credit_refund_amount,
    product_order_cash_chargeback_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_cost_product_returned_damaged_amount,
    product_order_return_shipping_cost_amount,
    product_order_return_unit_count,
    product_order_reship_order_count,
    product_order_reship_unit_count,
    product_order_reship_product_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    product_order_exchange_order_count,
    product_order_exchange_unit_count,
    product_order_exchange_product_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_order_payment_processing_cost_amount,
    product_order_variable_gms_cost_amount,
    product_order_variable_warehouse_cost_amount,
    billing_payment_processing_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    product_gross_revenue,
    product_margin_pre_return,
    product_margin_pre_return_excl_shipping,
    product_order_cash_gross_revenue_amount,
    product_order_cash_margin_pre_return,
    billing_cash_gross_revenue,
    cash_gross_revenue,
    billing_order_transaction_count,
    billed_credit_cash_transaction_count,
    on_retry_billed_credit_cash_transaction_count,
    billing_cash_refund_amount,
    billing_cash_chargeback_amount,
    billed_credit_cash_transaction_amount,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    billed_credit_cash_refund_count,
    billed_credit_cash_refund_chargeback_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_redeemed_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_same_month_amount,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount,
    retail_ship_only_product_order_count,
    retail_ship_only_product_order_unit_count,
    retail_ship_only_product_gross_revenue,
    retail_ship_only_product_gross_revenue_excl_shipping,
    retail_ship_only_product_margin_pre_return,
    retail_ship_only_product_margin_pre_return_excl_shipping,
    retail_ship_only_product_order_cash_margin_pre_return,
    retail_ship_only_product_order_cash_gross_revenue,
    retail_ship_only_product_net_revenue,
    retail_ship_only_product_gross_profit,
    retail_ship_only_product_order_cash_net_revenue,
    retail_ship_only_product_order_cash_gross_profit
));

TRUNCATE TABLE validation.finance_sales_ops_edw_comparison;
INSERT INTO validation.finance_sales_ops_edw_comparison
(
    store_brand,
    store_country,
    store_type,
    gender,
    is_retail_vip,
    is_cross_promo,
    finance_specialty_store,
    membership_order_type_l3,
    date,
    metric,
    fso_value,
    fact_value,
    variance,
    meta_create_datetime,
    meta_update_datetime
 )
SELECT
    COALESCE(fso.store_brand,ftp.store_brand) AS store_brand,
    COALESCE(fso.store_country,ftp.store_country) AS store_country,
    COALESCE(fso.store_type,ftp.store_type) AS store_type,
    COALESCE(fso.gender,ftp.gender) AS gender,
    COALESCE(fso.is_retail_vip,ftp.is_retail_vip) AS is_retail_vip,
    COALESCE(fso.is_cross_promo,ftp.is_cross_promo) AS is_cross_promo,
    COALESCE(fso.finance_specialty_store,ftp.finance_specialty_store) AS finance_specialty_store,
    COALESCE(fso.membership_order_type_l3,ftp.membership_order_type_l3) AS membership_order_type_l3,
    coalesce(fso.date,ftp.date) AS date,
    COALESCE(fso.metric,ftp.metric) AS metric,
    IFNULL(fso.value,0) AS fso_value,
    IFNULL(ftp.value,0) AS fact_value,
    IFNULL(fso.value,0) - IFNULL(ftp.value,0) AS variance,
    $execution_start_time AS meta_create_datetime,
    $execution_start_time AS meta_update_datetime
FROM _fso_pivot AS fso
FULL JOIN _fact_table_data_pivot AS ftp ON
    ftp.date = fso.date
    AND ftp.store_brand = fso.store_brand
    AND ftp.store_country = fso.store_country
    AND ftp.store_type = fso.store_type
    AND ftp.gender = fso.gender
    AND ftp.is_retail_vip = fso.is_retail_vip
    AND ftp.is_cross_promo  = fso.is_cross_promo
    AND ftp.finance_specialty_store  = fso.finance_specialty_store
    AND ftp.membership_order_type_l3 = fso.membership_order_type_l3
    AND ftp.metric = fso.metric;
