
ALTER SESSION SET QUERY_TAG ='finance_sales_ops_daily_cash_base_comparison';
SET execution_start_time = CURRENT_TIMESTAMP :: TIMESTAMP_LTZ(3);
CREATE OR REPLACE TEMP TABLE _daily_cash_base (
    date DATE,
    date_object VARCHAR(10),
    currency_object VARCHAR(10),
    report_mapping VARCHAR(50),
    order_membership_classification_key INT,
    product_order_subtotal_excl_tariff_amount NUMBER(38,5),
    product_order_product_discount_amount NUMBER(38,5),
    product_order_shipping_revenue_amount NUMBER(38,5),
    product_order_noncash_credit_redeemed_amount NUMBER(38,5),
    product_order_count NUMBER(38,5),
    product_order_unit_count NUMBER(38,5),
    product_order_landed_product_cost_amount NUMBER(38,5),
    product_order_shipping_cost_amount NUMBER(38,5),
    product_order_shipping_supplies_cost_amount NUMBER(38,5),
    product_order_direct_cogs_amount NUMBER(38,5),
    product_order_cash_refund_amount NUMBER(38,5),
    product_order_cash_chargeback_amount NUMBER(38,5),
    product_order_cost_product_returned_resaleable_amount NUMBER(38,5),
    product_order_cost_product_returned_damaged_amount NUMBER(38,5),
    product_order_return_shipping_cost_amount NUMBER(38,5),
    product_order_reship_order_count NUMBER(38,5),
    product_order_reship_unit_count NUMBER(38,5),
    product_order_reship_direct_cogs_amount NUMBER(38,5),
    product_order_reship_product_cost_amount NUMBER(38,5),
    product_order_reship_shipping_cost_amount NUMBER(38,5),
    product_order_reship_shipping_supplies_cost_amount NUMBER(38,5),
    product_order_exchange_order_count NUMBER(38,5),
    product_order_exchange_unit_count NUMBER(38,5),
    product_order_exchange_product_cost_amount NUMBER(38,5),
    product_order_exchange_shipping_cost_amount NUMBER(38,5),
    product_order_exchange_shipping_supplies_cost_amount NUMBER(38,5),
    product_gross_revenue NUMBER(38,5),
    product_net_revenue NUMBER(38,5),
    product_margin_pre_return NUMBER(38,5),
    product_gross_profit NUMBER(38,5),
    product_order_cash_gross_revenue_amount NUMBER(38,5),
    cash_gross_revenue NUMBER(38,5),
    cash_net_revenue NUMBER(38,5),
    cash_gross_profit NUMBER(38,5),
    billed_credit_cash_transaction_count NUMBER(38,5),
    on_retry_billed_credit_cash_transaction_count NUMBER(38,5),
    billing_cash_refund_amount NUMBER(38,5),
    billing_cash_chargeback_amount NUMBER(38,5),
    billed_credit_cash_transaction_amount NUMBER(38,5),
    billed_credit_cash_refund_chargeback_amount NUMBER(38,5),
    billed_cash_credit_redeemed_amount NUMBER(38,5),
    product_order_misc_cogs_amount NUMBER(38,5),
    product_order_cash_gross_profit NUMBER(38,5),
    billed_cash_credit_redeemed_same_month_amount NUMBER(38,5),
    product_order_tariff_amount NUMBER(38,5),
    product_order_product_subtotal_amount NUMBER(38,5),
    product_order_shipping_discount_amount NUMBER(38,5),
    product_order_shipping_revenue_before_discount_amount NUMBER(38,5),
    product_order_tax_amount NUMBER(38,5),
    product_order_cash_transaction_amount NUMBER(38,5),
    product_order_cash_credit_redeemed_amount NUMBER(38,5),
    product_order_loyalty_unit_count NUMBER(38,5),
    product_order_outfit_component_unit_count NUMBER(38,5),
    product_order_outfit_count NUMBER(38,5),
    product_order_discounted_unit_count NUMBER(38,5),
    product_order_zero_revenue_unit_count NUMBER(38,5),
    product_order_cash_credit_refund_amount NUMBER(38,5),
    product_order_noncash_credit_refund_amount NUMBER(38,5),
    product_order_return_unit_count NUMBER(38,5),
    product_order_exchange_direct_cogs_amount NUMBER(38,5),
    product_order_selling_expenses_amount NUMBER(38,5),
    product_order_payment_processing_cost_amount NUMBER(38,5),
    product_order_variable_gms_cost_amount NUMBER(38,5),
    product_order_variable_warehouse_cost_amount NUMBER(38,5),
    billing_selling_expenses_amount NUMBER(38,5),
    billing_payment_processing_cost_amount NUMBER(38,5),
    billing_variable_gms_cost_amount NUMBER(38,5),
    product_order_amount_to_pay NUMBER(38,5),
    product_gross_revenue_excl_shipping NUMBER(38,5),
    product_margin_pre_return_excl_shipping NUMBER(38,5),
    product_variable_contribution_profit NUMBER(38,5),
    product_order_cash_net_revenue NUMBER(38,5),
    product_order_cash_margin_pre_return NUMBER(38,5),
    billing_cash_gross_revenue NUMBER(38,5),
    billing_cash_net_revenue NUMBER(38,5),
    cash_variable_contribution_profit NUMBER(38,5),
    billing_order_transaction_count NUMBER(38,5),
    membership_fee_cash_transaction_amount NUMBER(38,5),
    gift_card_transaction_amount NUMBER(38,5),
    legacy_credit_cash_transaction_amount NUMBER(38,5),
    membership_fee_cash_refund_chargeback_amount NUMBER(38,5),
    gift_card_cash_refund_chargeback_amount NUMBER(38,5),
    legacy_credit_cash_refund_chargeback_amount NUMBER(38,5),
    billed_cash_credit_issued_amount NUMBER(38,5),
    billed_cash_credit_cancelled_amount NUMBER(38,5),
    billed_cash_credit_expired_amount NUMBER(38,5),
    billed_cash_credit_issued_equivalent_count NUMBER(38,5),
    billed_cash_credit_redeemed_equivalent_count NUMBER(38,5),
    billed_cash_credit_cancelled_equivalent_count NUMBER(38,5),
    billed_cash_credit_expired_equivalent_count NUMBER(38,5),
    refund_cash_credit_issued_amount NUMBER(38,5),
    refund_cash_credit_redeemed_amount NUMBER(38,5),
    refund_cash_credit_cancelled_amount NUMBER(38,5),
    refund_cash_credit_expired_amount NUMBER(38,5),
    other_cash_credit_issued_amount NUMBER(38,5),
    other_cash_credit_redeemed_amount NUMBER(38,5),
    other_cash_credit_cancelled_amount NUMBER(38,5),
    other_cash_credit_expired_amount NUMBER(38,5),
    noncash_credit_issued_amount NUMBER(38,5),
    noncash_credit_cancelled_amount NUMBER(38,5),
    noncash_credit_expired_amount NUMBER(38,5)
);
INSERT INTO  _daily_cash_base
(
   date,
    date_object,
    currency_object,
    report_mapping,
    order_membership_classification_key,
    product_order_subtotal_excl_tariff_amount,
    product_order_product_discount_amount,
    product_order_shipping_revenue_amount,
    product_order_noncash_credit_redeemed_amount,
    product_order_count,
    product_order_unit_count,
    product_order_landed_product_cost_amount,
    product_order_shipping_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_direct_cogs_amount,
    product_order_cash_refund_amount,
    product_order_cash_chargeback_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_cost_product_returned_damaged_amount,
    product_order_return_shipping_cost_amount,
    product_order_reship_order_count,
    product_order_reship_unit_count,
    product_order_reship_direct_cogs_amount,
    product_order_reship_product_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    product_order_exchange_order_count,
    product_order_exchange_unit_count,
    product_order_exchange_product_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_gross_revenue,
    product_net_revenue,
    product_margin_pre_return,
    product_gross_profit,
    product_order_cash_gross_revenue_amount,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    billed_credit_cash_transaction_count,
    on_retry_billed_credit_cash_transaction_count,
    billing_cash_refund_amount,
    billing_cash_chargeback_amount,
    billed_credit_cash_transaction_amount,
    billed_credit_cash_refund_chargeback_amount,
    billed_cash_credit_redeemed_amount,
    product_order_misc_cogs_amount,
    product_order_cash_gross_profit,
    billed_cash_credit_redeemed_same_month_amount,
    product_order_tariff_amount,
    product_order_product_subtotal_amount,
    product_order_shipping_discount_amount,
    product_order_shipping_revenue_before_discount_amount,
    product_order_tax_amount,
    product_order_cash_transaction_amount,
    product_order_cash_credit_redeemed_amount,
    product_order_loyalty_unit_count,
    product_order_outfit_component_unit_count,
    product_order_outfit_count,
    product_order_discounted_unit_count,
    product_order_zero_revenue_unit_count,
    product_order_cash_credit_refund_amount,
    product_order_noncash_credit_refund_amount,
    product_order_return_unit_count,
    product_order_exchange_direct_cogs_amount,
    product_order_selling_expenses_amount,
    product_order_payment_processing_cost_amount,
    product_order_variable_gms_cost_amount,
    product_order_variable_warehouse_cost_amount,
    billing_selling_expenses_amount,
    billing_payment_processing_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    product_margin_pre_return_excl_shipping,
    product_variable_contribution_profit,
    product_order_cash_net_revenue,
    product_order_cash_margin_pre_return,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_variable_contribution_profit,
    billing_order_transaction_count,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount
)
SELECT
    date,
    date_object,
    currency_object,
    report_mapping,
    order_membership_classification_key,
    product_order_subtotal_excl_tariff_amount,
    product_order_product_discount_amount,
    product_order_shipping_revenue_amount,
    product_order_noncash_credit_redeemed_amount,
    product_order_count,
    product_order_unit_count,
    product_order_landed_product_cost_amount,
    product_order_shipping_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_direct_cogs_amount,
    product_order_cash_refund_amount,
    product_order_cash_chargeback_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_cost_product_returned_damaged_amount,
    product_order_return_shipping_cost_amount,
    product_order_reship_order_count,
    product_order_reship_unit_count,
    product_order_reship_direct_cogs_amount,
    product_order_reship_product_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    product_order_exchange_order_count,
    product_order_exchange_unit_count,
    product_order_exchange_product_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_gross_revenue,
    product_net_revenue,
    product_margin_pre_return,
    product_gross_profit,
    product_order_cash_gross_revenue_amount,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    billed_credit_cash_transaction_count,
    on_retry_billed_credit_cash_transaction_count,
    billing_cash_refund_amount,
    billing_cash_chargeback_amount,
    billed_credit_cash_transaction_amount,
    billed_credit_cash_refund_chargeback_amount,
    billed_cash_credit_redeemed_amount,
    product_order_misc_cogs_amount,
    product_order_cash_gross_profit,
    billed_cash_credit_redeemed_same_month_amount,
    product_order_tariff_amount,
    product_order_product_subtotal_amount,
    product_order_shipping_discount_amount,
    product_order_shipping_revenue_before_discount_amount,
    product_order_tax_amount,
    product_order_cash_transaction_amount,
    product_order_cash_credit_redeemed_amount,
    product_order_loyalty_unit_count,
    product_order_outfit_component_unit_count,
    product_order_outfit_count,
    product_order_discounted_unit_count,
    product_order_zero_revenue_unit_count,
    product_order_cash_credit_refund_amount,
    product_order_noncash_credit_refund_amount,
    product_order_return_unit_count,
    product_order_exchange_direct_cogs_amount,
    product_order_selling_expenses_amount,
    product_order_payment_processing_cost_amount,
    product_order_variable_gms_cost_amount,
    product_order_variable_warehouse_cost_amount,
    billing_selling_expenses_amount,
    billing_payment_processing_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    product_margin_pre_return_excl_shipping,
    product_variable_contribution_profit,
    product_order_cash_net_revenue,
    product_order_cash_margin_pre_return,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_variable_contribution_profit,
    billing_order_transaction_count,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount
FROM reporting.daily_cash_base_calc
WHERE currency_object = 'usd' and date_object = 'shipped';

CREATE OR REPLACE TEMP TABLE _daily_cash_pivot AS
SELECT * FROM _daily_cash_base
    UNPIVOT (value FOR metric IN (
                product_order_subtotal_excl_tariff_amount,
                product_order_product_discount_amount,
                product_order_shipping_revenue_amount,
                product_order_noncash_credit_redeemed_amount,
                product_order_count,
                product_order_unit_count,
                product_order_landed_product_cost_amount,
                product_order_shipping_cost_amount,
                product_order_shipping_supplies_cost_amount,
                product_order_direct_cogs_amount,
                product_order_cash_refund_amount,
                product_order_cash_chargeback_amount,
                product_order_cost_product_returned_resaleable_amount,
                product_order_cost_product_returned_damaged_amount,
                product_order_return_shipping_cost_amount,
                product_order_reship_order_count,
                product_order_reship_unit_count,
                product_order_reship_direct_cogs_amount,
                product_order_reship_product_cost_amount,
                product_order_reship_shipping_cost_amount,
                product_order_reship_shipping_supplies_cost_amount,
                product_order_exchange_order_count,
                product_order_exchange_unit_count,
                product_order_exchange_product_cost_amount,
                product_order_exchange_shipping_cost_amount,
                product_order_exchange_shipping_supplies_cost_amount,
                product_gross_revenue,
                product_net_revenue,
                product_margin_pre_return,
                product_gross_profit,
                product_order_cash_gross_revenue_amount,
                cash_gross_revenue,
                cash_net_revenue,
                cash_gross_profit,
                billed_credit_cash_transaction_count,
                on_retry_billed_credit_cash_transaction_count,
                billing_cash_refund_amount,
                billing_cash_chargeback_amount,
                billed_credit_cash_transaction_amount,
                billed_credit_cash_refund_chargeback_amount,
                billed_cash_credit_redeemed_amount,
                product_order_misc_cogs_amount,
                product_order_cash_gross_profit,
                billed_cash_credit_redeemed_same_month_amount,
                product_order_tariff_amount,
                product_order_product_subtotal_amount,
                product_order_shipping_discount_amount,
                product_order_shipping_revenue_before_discount_amount,
                product_order_tax_amount,
                product_order_cash_transaction_amount,
                product_order_cash_credit_redeemed_amount,
                product_order_loyalty_unit_count,
                product_order_outfit_component_unit_count,
                product_order_outfit_count,
                product_order_discounted_unit_count,
                product_order_zero_revenue_unit_count,
                product_order_cash_credit_refund_amount,
                product_order_noncash_credit_refund_amount,
                product_order_return_unit_count,
                product_order_exchange_direct_cogs_amount,
                product_order_selling_expenses_amount,
                product_order_payment_processing_cost_amount,
                product_order_variable_gms_cost_amount,
                product_order_variable_warehouse_cost_amount,
                billing_selling_expenses_amount,
                billing_payment_processing_cost_amount,
                billing_variable_gms_cost_amount,
                product_order_amount_to_pay,
                product_gross_revenue_excl_shipping,
                product_margin_pre_return_excl_shipping,
                product_variable_contribution_profit,
                product_order_cash_net_revenue,
                product_order_cash_margin_pre_return,
                billing_cash_gross_revenue,
                billing_cash_net_revenue,
                cash_variable_contribution_profit,
                billing_order_transaction_count,
                membership_fee_cash_transaction_amount,
                gift_card_transaction_amount,
                legacy_credit_cash_transaction_amount,
                membership_fee_cash_refund_chargeback_amount,
                gift_card_cash_refund_chargeback_amount,
                legacy_credit_cash_refund_chargeback_amount,
                billed_cash_credit_issued_amount,
                billed_cash_credit_cancelled_amount,
                billed_cash_credit_expired_amount,
                billed_cash_credit_issued_equivalent_count,
                billed_cash_credit_redeemed_equivalent_count,
                billed_cash_credit_cancelled_equivalent_count,
                billed_cash_credit_expired_equivalent_count,
                refund_cash_credit_issued_amount,
                refund_cash_credit_redeemed_amount,
                refund_cash_credit_cancelled_amount,
                refund_cash_credit_expired_amount,
                other_cash_credit_issued_amount,
                other_cash_credit_redeemed_amount,
                other_cash_credit_cancelled_amount,
                other_cash_credit_expired_amount,
                noncash_credit_issued_amount,
                noncash_credit_cancelled_amount,
                noncash_credit_expired_amount
            ));

 CREATE OR REPLACE TEMP TABLE _fso_base (
    date DATE,
    date_object VARCHAR(10),
    currency_object VARCHAR(10),
    report_mapping VARCHAR(50),
    order_membership_classification_key INT,
    product_order_subtotal_excl_tariff_amount NUMBER(38,5),
    product_order_product_discount_amount NUMBER(38,5),
    product_order_shipping_revenue_amount NUMBER(38,5),
    product_order_noncash_credit_redeemed_amount NUMBER(38,5),
    product_order_count NUMBER(38,5),
    product_order_unit_count NUMBER(38,5),
    product_order_landed_product_cost_amount NUMBER(38,5),
    product_order_shipping_cost_amount NUMBER(38,5),
    product_order_shipping_supplies_cost_amount NUMBER(38,5),
    product_order_direct_cogs_amount NUMBER(38,5),
    product_order_cash_refund_amount NUMBER(38,5),
    product_order_cash_chargeback_amount NUMBER(38,5),
    product_order_cost_product_returned_resaleable_amount NUMBER(38,5),
    product_order_cost_product_returned_damaged_amount NUMBER(38,5),
    product_order_return_shipping_cost_amount NUMBER(38,5),
    product_order_reship_order_count NUMBER(38,5),
    product_order_reship_unit_count NUMBER(38,5),
    product_order_reship_direct_cogs_amount NUMBER(38,5),
    product_order_reship_product_cost_amount NUMBER(38,5),
    product_order_reship_shipping_cost_amount NUMBER(38,5),
    product_order_reship_shipping_supplies_cost_amount NUMBER(38,5),
    product_order_exchange_order_count NUMBER(38,5),
    product_order_exchange_unit_count NUMBER(38,5),
    product_order_exchange_product_cost_amount NUMBER(38,5),
    product_order_exchange_shipping_cost_amount NUMBER(38,5),
    product_order_exchange_shipping_supplies_cost_amount NUMBER(38,5),
    product_gross_revenue NUMBER(38,5),
    product_net_revenue NUMBER(38,5),
    product_margin_pre_return NUMBER(38,5),
    product_gross_profit NUMBER(38,5),
    product_order_cash_gross_revenue_amount NUMBER(38,5),
    cash_gross_revenue NUMBER(38,5),
    cash_net_revenue NUMBER(38,5),
    cash_gross_profit NUMBER(38,5),
    billed_credit_cash_transaction_count NUMBER(38,5),
    on_retry_billed_credit_cash_transaction_count NUMBER(38,5),
    billing_cash_refund_amount NUMBER(38,5),
    billing_cash_chargeback_amount NUMBER(38,5),
    billed_credit_cash_transaction_amount NUMBER(38,5),
    billed_credit_cash_refund_chargeback_amount NUMBER(38,5),
    billed_cash_credit_redeemed_amount NUMBER(38,5),
    product_order_misc_cogs_amount NUMBER(38,5),
    product_order_cash_gross_profit NUMBER(38,5),
    billed_cash_credit_redeemed_same_month_amount NUMBER(38,5),
    product_order_tariff_amount NUMBER(38,5),
    product_order_product_subtotal_amount NUMBER(38,5),
    product_order_shipping_discount_amount NUMBER(38,5),
    product_order_shipping_revenue_before_discount_amount NUMBER(38,5),
    product_order_tax_amount NUMBER(38,5),
    product_order_cash_transaction_amount NUMBER(38,5),
    product_order_cash_credit_redeemed_amount NUMBER(38,5),
    product_order_loyalty_unit_count NUMBER(38,5),
    product_order_outfit_component_unit_count NUMBER(38,5),
    product_order_outfit_count NUMBER(38,5),
    product_order_discounted_unit_count NUMBER(38,5),
    product_order_zero_revenue_unit_count NUMBER(38,5),
    product_order_cash_credit_refund_amount NUMBER(38,5),
    product_order_noncash_credit_refund_amount NUMBER(38,5),
    product_order_return_unit_count NUMBER(38,5),
    product_order_exchange_direct_cogs_amount NUMBER(38,5),
    product_order_selling_expenses_amount NUMBER(38,5),
    product_order_payment_processing_cost_amount NUMBER(38,5),
    product_order_variable_gms_cost_amount NUMBER(38,5),
    product_order_variable_warehouse_cost_amount NUMBER(38,5),
    billing_selling_expenses_amount NUMBER(38,5),
    billing_payment_processing_cost_amount NUMBER(38,5),
    billing_variable_gms_cost_amount NUMBER(38,5),
    product_order_amount_to_pay NUMBER(38,5),
    product_gross_revenue_excl_shipping NUMBER(38,5),
    product_margin_pre_return_excl_shipping NUMBER(38,5),
    product_variable_contribution_profit NUMBER(38,5),
    product_order_cash_net_revenue NUMBER(38,5),
    product_order_cash_margin_pre_return NUMBER(38,5),
    billing_cash_gross_revenue NUMBER(38,5),
    billing_cash_net_revenue NUMBER(38,5),
    cash_variable_contribution_profit NUMBER(38,5),
    billing_order_transaction_count NUMBER(38,5),
    membership_fee_cash_transaction_amount NUMBER(38,5),
    gift_card_transaction_amount NUMBER(38,5),
    legacy_credit_cash_transaction_amount NUMBER(38,5),
    membership_fee_cash_refund_chargeback_amount NUMBER(38,5),
    gift_card_cash_refund_chargeback_amount NUMBER(38,5),
    legacy_credit_cash_refund_chargeback_amount NUMBER(38,5),
    billed_cash_credit_issued_amount NUMBER(38,5),
    billed_cash_credit_cancelled_amount NUMBER(38,5),
    billed_cash_credit_expired_amount NUMBER(38,5),
    billed_cash_credit_issued_equivalent_count NUMBER(38,5),
    billed_cash_credit_redeemed_equivalent_count NUMBER(38,5),
    billed_cash_credit_cancelled_equivalent_count NUMBER(38,5),
    billed_cash_credit_expired_equivalent_count NUMBER(38,5),
    refund_cash_credit_issued_amount NUMBER(38,5),
    refund_cash_credit_redeemed_amount NUMBER(38,5),
    refund_cash_credit_cancelled_amount NUMBER(38,5),
    refund_cash_credit_expired_amount NUMBER(38,5),
    other_cash_credit_issued_amount NUMBER(38,5),
    other_cash_credit_redeemed_amount NUMBER(38,5),
    other_cash_credit_cancelled_amount NUMBER(38,5),
    other_cash_credit_expired_amount NUMBER(38,5),
    noncash_credit_issued_amount NUMBER(38,5),
    noncash_credit_cancelled_amount NUMBER(38,5),
    noncash_credit_expired_amount NUMBER(38,5)
);

INSERT INTO _fso_base
(
   date,
    date_object,
    currency_object,
    report_mapping,
    order_membership_classification_key,
    product_order_subtotal_excl_tariff_amount,
    product_order_product_discount_amount,
    product_order_shipping_revenue_amount,
    product_order_noncash_credit_redeemed_amount,
    product_order_count,
    product_order_unit_count,
    product_order_landed_product_cost_amount,
    product_order_shipping_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_direct_cogs_amount,
    product_order_cash_refund_amount,
    product_order_cash_chargeback_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_cost_product_returned_damaged_amount,
    product_order_return_shipping_cost_amount,
    product_order_reship_order_count,
    product_order_reship_unit_count,
    product_order_reship_direct_cogs_amount,
    product_order_reship_product_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    product_order_exchange_order_count,
    product_order_exchange_unit_count,
    product_order_exchange_product_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_gross_revenue,
    product_net_revenue,
    product_margin_pre_return,
    product_gross_profit,
    product_order_cash_gross_revenue_amount,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    billed_credit_cash_transaction_count,
    on_retry_billed_credit_cash_transaction_count,
    billing_cash_refund_amount,
    billing_cash_chargeback_amount,
    billed_credit_cash_transaction_amount,
    billed_credit_cash_refund_chargeback_amount,
    billed_cash_credit_redeemed_amount,
    product_order_misc_cogs_amount,
    product_order_cash_gross_profit,
    billed_cash_credit_redeemed_same_month_amount,
    product_order_tariff_amount,
    product_order_product_subtotal_amount,
    product_order_shipping_discount_amount,
    product_order_shipping_revenue_before_discount_amount,
    product_order_tax_amount,
    product_order_cash_transaction_amount,
    product_order_cash_credit_redeemed_amount,
    product_order_loyalty_unit_count,
    product_order_outfit_component_unit_count,
    product_order_outfit_count,
    product_order_discounted_unit_count,
    product_order_zero_revenue_unit_count,
    product_order_cash_credit_refund_amount,
    product_order_noncash_credit_refund_amount,
    product_order_return_unit_count,
    product_order_exchange_direct_cogs_amount,
    product_order_selling_expenses_amount,
    product_order_payment_processing_cost_amount,
    product_order_variable_gms_cost_amount,
    product_order_variable_warehouse_cost_amount,
    billing_selling_expenses_amount,
    billing_payment_processing_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    product_margin_pre_return_excl_shipping,
    product_variable_contribution_profit,
    product_order_cash_net_revenue,
    product_order_cash_margin_pre_return,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_variable_contribution_profit,
    billing_order_transaction_count,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount
)
WITH _fso_agg AS (
    SELECT
        fso.date
        ,fso.date_object
        ,fso.currency_object
        ,fso.currency_type
        ,fso.store_id
        ,fso.vip_store_id
        ,fso.is_retail_vip
        ,fso.gender
        ,fso.is_cross_promo
        ,fso.is_scrubs_customer
        ,CASE WHEN fso.finance_specialty_store IS NULL THEN 'None' ELSE fso.finance_specialty_store END AS finance_specialty_store
        ,fso.order_membership_classification_key
        ,SUM(fso.product_order_subtotal_excl_tariff_amount) AS product_order_subtotal_excl_tariff_amount
        ,SUM(fso.product_order_product_discount_amount) AS product_order_product_discount_amount
        ,SUM(fso.product_order_shipping_revenue_amount) AS product_order_shipping_revenue_amount
        ,SUM(fso.product_order_noncash_credit_redeemed_amount) AS product_order_noncash_credit_redeemed_amount
        ,SUM(fso.product_order_count) AS product_order_count
        ,SUM(fso.product_order_unit_count) AS product_order_unit_count
        ,SUM(fso.product_order_landed_product_cost_amount) AS product_order_landed_product_cost_amount
        ,SUM(fso.product_order_shipping_cost_amount) AS product_order_shipping_cost_amount
        ,SUM(fso.product_order_shipping_supplies_cost_amount) AS product_order_shipping_supplies_cost_amount
        ,SUM(fso.product_order_direct_cogs_amount) AS product_order_direct_cogs_amount
        ,SUM(fso.product_order_cash_refund_amount) AS product_order_cash_refund_amount
        ,SUM(fso.product_order_cash_chargeback_amount) AS product_order_cash_chargeback_amount
        ,SUM(fso.product_order_cost_product_returned_resaleable_amount) AS product_order_cost_product_returned_resaleable_amount
        ,SUM(fso.product_order_cost_product_returned_damaged_amount) AS product_order_cost_product_returned_damaged_amount
        ,SUM(fso.product_order_return_shipping_cost_amount) AS product_order_return_shipping_cost_amount
        ,SUM(fso.product_order_reship_order_count) AS product_order_reship_order_count
        ,SUM(fso.product_order_reship_unit_count) AS product_order_reship_unit_count
        ,SUM(fso.product_order_reship_direct_cogs_amount) AS product_order_reship_direct_cogs_amount
        ,SUM(fso.product_order_reship_product_cost_amount) AS product_order_reship_product_cost_amount
        ,SUM(fso.product_order_reship_shipping_cost_amount) AS product_order_reship_shipping_cost_amount
        ,SUM(fso.product_order_reship_shipping_supplies_cost_amount) AS product_order_reship_shipping_supplies_cost_amount
        ,SUM(fso.product_order_exchange_order_count) AS product_order_exchange_order_count
        ,SUM(fso.product_order_exchange_unit_count) AS product_order_exchange_unit_count
        ,SUM(fso.product_order_exchange_product_cost_amount) AS product_order_exchange_product_cost_amount
        ,SUM(fso.product_order_exchange_shipping_cost_amount) AS product_order_exchange_shipping_cost_amount
        ,SUM(fso.product_order_exchange_shipping_supplies_cost_amount) AS product_order_exchange_shipping_supplies_cost_amount
        ,SUM(fso.product_gross_revenue) AS product_gross_revenue
        ,SUM(fso.product_net_revenue) AS product_net_revenue
        ,SUM(fso.product_margin_pre_return) AS product_margin_pre_return
        ,SUM(fso.product_gross_profit) AS product_gross_profit
        ,SUM(fso.product_order_cash_gross_revenue_amount) AS product_order_cash_gross_revenue_amount
        ,SUM(fso.cash_gross_revenue) AS cash_gross_revenue
        ,SUM(fso.cash_net_revenue) AS cash_net_revenue
        ,SUM(fso.cash_gross_profit) AS cash_gross_profit
        ,SUM(fso.billed_credit_cash_transaction_count) AS billed_credit_cash_transaction_count
        ,SUM(fso.on_retry_billed_credit_cash_transaction_count) AS on_retry_billed_credit_cash_transaction_count
        ,SUM(fso.billing_cash_refund_amount) AS billing_cash_refund_amount
        ,SUM(fso.billing_cash_chargeback_amount) AS billing_cash_chargeback_amount
        ,SUM(fso.billed_credit_cash_transaction_amount) AS billed_credit_cash_transaction_amount
        ,SUM(fso.billed_credit_cash_refund_chargeback_amount) AS billed_credit_cash_refund_chargeback_amount
        ,SUM(fso.billed_cash_credit_redeemed_amount) AS billed_cash_credit_redeemed_amount
        ,SUM(fso.product_order_misc_cogs_amount) AS product_order_misc_cogs_amount
        ,SUM(fso.product_order_cash_gross_profit) AS product_order_cash_gross_profit
        ,SUM(fso.billed_cash_credit_redeemed_same_month_amount) AS billed_cash_credit_redeemed_same_month_amount
        ,SUM(fso.product_order_tariff_amount) AS product_order_tariff_amount
        ,SUM(fso.product_order_product_subtotal_amount) AS product_order_product_subtotal_amount
        ,SUM(fso.product_order_shipping_discount_amount) AS product_order_shipping_discount_amount
        ,SUM(fso.product_order_shipping_revenue_before_discount_amount) AS product_order_shipping_revenue_before_discount_amount
        ,SUM(fso.product_order_tax_amount) AS product_order_tax_amount
        ,SUM(fso.product_order_cash_transaction_amount) AS product_order_cash_transaction_amount
        ,SUM(fso.product_order_cash_credit_redeemed_amount) AS product_order_cash_credit_redeemed_amount
        ,SUM(fso.product_order_loyalty_unit_count) AS product_order_loyalty_unit_count
        ,SUM(fso.product_order_outfit_component_unit_count) AS product_order_outfit_component_unit_count
        ,SUM(fso.product_order_outfit_count) AS product_order_outfit_count
        ,SUM(fso.product_order_discounted_unit_count) AS product_order_discounted_unit_count
        ,SUM(fso.product_order_zero_revenue_unit_count) AS product_order_zero_revenue_unit_count
        ,SUM(fso.product_order_cash_credit_refund_amount) AS product_order_cash_credit_refund_amount
        ,SUM(fso.product_order_noncash_credit_refund_amount) AS product_order_noncash_credit_refund_amount
        ,SUM(fso.product_order_return_unit_count) AS product_order_return_unit_count
        ,SUM(fso.product_order_exchange_direct_cogs_amount) AS product_order_exchange_direct_cogs_amount
        ,SUM(fso.product_order_selling_expenses_amount) AS product_order_selling_expenses_amount
        ,SUM(fso.product_order_payment_processing_cost_amount) AS product_order_payment_processing_cost_amount
        ,SUM(fso.product_order_variable_gms_cost_amount) AS product_order_variable_gms_cost_amount
        ,SUM(fso.product_order_variable_warehouse_cost_amount) AS product_order_variable_warehouse_cost_amount
        ,SUM(fso.billing_selling_expenses_amount) AS billing_selling_expenses_amount
        ,SUM(fso.billing_payment_processing_cost_amount) AS billing_payment_processing_cost_amount
        ,SUM(fso.billing_variable_gms_cost_amount) AS billing_variable_gms_cost_amount
        ,SUM(fso.product_order_amount_to_pay) AS product_order_amount_to_pay
        ,SUM(fso.product_gross_revenue_excl_shipping) AS product_gross_revenue_excl_shipping
        ,SUM(fso.product_margin_pre_return_excl_shipping) AS product_margin_pre_return_excl_shipping
        ,SUM(fso.product_variable_contribution_profit) AS product_variable_contribution_profit
        ,SUM(fso.product_order_cash_net_revenue) AS product_order_cash_net_revenue
        ,SUM(fso.product_order_cash_margin_pre_return) AS product_order_cash_margin_pre_return
        ,SUM(fso.billing_cash_gross_revenue) AS billing_cash_gross_revenue
        ,SUM(fso.billing_cash_net_revenue) AS billing_cash_net_revenue
        ,SUM(fso.cash_variable_contribution_profit) AS cash_variable_contribution_profit
        ,SUM(fso.billing_order_transaction_count) AS billing_order_transaction_count
        ,SUM(fso.membership_fee_cash_transaction_amount) AS membership_fee_cash_transaction_amount
        ,SUM(fso.gift_card_transaction_amount) AS gift_card_transaction_amount
        ,SUM(fso.legacy_credit_cash_transaction_amount) AS legacy_credit_cash_transaction_amount
        ,SUM(fso.membership_fee_cash_refund_chargeback_amount) AS membership_fee_cash_refund_chargeback_amount
        ,SUM(fso.gift_card_cash_refund_chargeback_amount) AS gift_card_cash_refund_chargeback_amount
        ,SUM(fso.legacy_credit_cash_refund_chargeback_amount) AS legacy_credit_cash_refund_chargeback_amount
        ,SUM(fso.billed_cash_credit_issued_amount) AS billed_cash_credit_issued_amount
        ,SUM(fso.billed_cash_credit_cancelled_amount) AS billed_cash_credit_cancelled_amount
        ,SUM(fso.billed_cash_credit_expired_amount) AS billed_cash_credit_expired_amount
        ,SUM(fso.billed_cash_credit_issued_equivalent_count) AS billed_cash_credit_issued_equivalent_count
        ,SUM(fso.billed_cash_credit_redeemed_equivalent_count) AS billed_cash_credit_redeemed_equivalent_count
        ,SUM(fso.billed_cash_credit_cancelled_equivalent_count) AS billed_cash_credit_cancelled_equivalent_count
        ,SUM(fso.billed_cash_credit_expired_equivalent_count) AS billed_cash_credit_expired_equivalent_count
        ,SUM(fso.refund_cash_credit_issued_amount) AS refund_cash_credit_issued_amount
        ,SUM(fso.refund_cash_credit_redeemed_amount) AS refund_cash_credit_redeemed_amount
        ,SUM(fso.refund_cash_credit_cancelled_amount) AS refund_cash_credit_cancelled_amount
        ,SUM(fso.refund_cash_credit_expired_amount) AS refund_cash_credit_expired_amount
        ,SUM(fso.other_cash_credit_issued_amount) AS other_cash_credit_issued_amount
        ,SUM(fso.other_cash_credit_redeemed_amount) AS other_cash_credit_redeemed_amount
        ,SUM(fso.other_cash_credit_cancelled_amount) AS other_cash_credit_cancelled_amount
        ,SUM(fso.other_cash_credit_expired_amount) AS other_cash_credit_expired_amount
        ,SUM(fso.noncash_credit_issued_amount) AS noncash_credit_issued_amount
        ,SUM(fso.noncash_credit_cancelled_amount) AS noncash_credit_cancelled_amount
        ,SUM(fso.noncash_credit_expired_amount) AS noncash_credit_expired_amount
        ,SUM(fso.billed_credit_cash_refund_count) AS billed_credit_cash_refund_count
    FROM analytics_base.finance_sales_ops AS fso
    WHERE
        fso.date IS NOT NULL
        AND fso.currency_object = 'usd'
        AND fso.date_object = 'shipped'
    GROUP BY
        fso.date,
        fso.date_object,
        fso.currency_object,
        fso.currency_type,
        fso.store_id,
        fso.vip_store_id,
        fso.is_retail_vip,
        fso.gender,
        fso.is_cross_promo,
        fso.finance_specialty_store,
        fso.is_scrubs_customer,
        fso.order_membership_classification_key
)
SELECT
    fso.date,
    fso.date_object,
    fso.currency_object,
    fsm.report_mapping,
    fso.order_membership_classification_key,
    SUM(product_order_subtotal_excl_tariff_amount) AS product_order_subtotal_excl_tariff_amount,
    SUM(product_order_product_discount_amount) AS product_order_product_discount_amount,
    SUM(product_order_shipping_revenue_amount) AS product_order_shipping_revenue_amount,
    SUM(product_order_noncash_credit_redeemed_amount) AS product_order_noncash_credit_redeemed_amount,
    SUM(product_order_count) AS product_order_count,
    SUM(product_order_unit_count) AS product_order_unit_count,
    SUM(product_order_landed_product_cost_amount) AS product_order_landed_product_cost_amount,
    SUM(product_order_shipping_cost_amount) AS product_order_shipping_cost_amount,
    SUM(product_order_shipping_supplies_cost_amount) AS product_order_shipping_supplies_cost_amount,
    SUM(product_order_direct_cogs_amount) AS product_order_direct_cogs_amount,
    SUM(product_order_cash_refund_amount) AS product_order_cash_refund_amount,
    SUM(product_order_cash_chargeback_amount) AS product_order_cash_chargeback_amount,
    SUM(product_order_cost_product_returned_resaleable_amount) AS product_order_cost_product_returned_resaleable_amount,
    SUM(product_order_cost_product_returned_damaged_amount) AS product_order_cost_product_returned_damaged_amount,
    SUM(product_order_return_shipping_cost_amount) AS product_order_return_shipping_cost_amount,
    SUM(product_order_reship_order_count) AS product_order_reship_order_count,
    SUM(product_order_reship_unit_count) AS product_order_reship_unit_count,
    SUM(product_order_reship_direct_cogs_amount) AS product_order_reship_direct_cogs_amount,
    SUM(product_order_reship_product_cost_amount) AS product_order_reship_product_cost_amount,
    SUM(product_order_reship_shipping_cost_amount) AS product_order_reship_shipping_cost_amount,
    SUM(product_order_reship_shipping_supplies_cost_amount) AS product_order_reship_shipping_supplies_cost_amount,
    SUM(product_order_exchange_order_count) AS product_order_exchange_order_count,
    SUM(product_order_exchange_unit_count) AS product_order_exchange_unit_count,
    SUM(product_order_exchange_product_cost_amount) AS product_order_exchange_product_cost_amount,
    SUM(product_order_exchange_shipping_cost_amount) AS product_order_exchange_shipping_cost_amount,
    SUM(product_order_exchange_shipping_supplies_cost_amount) AS product_order_exchange_shipping_supplies_cost_amount,
    SUM(product_gross_revenue) AS product_gross_revenue,
    SUM(product_net_revenue) AS product_net_revenue,
    SUM(product_margin_pre_return) AS product_margin_pre_return,
    SUM(product_gross_profit) AS product_gross_profit,
    SUM(product_order_cash_gross_revenue_amount) AS product_order_cash_gross_revenue_amount,
    SUM(cash_gross_revenue) AS cash_gross_revenue,
    SUM(cash_net_revenue) AS cash_net_revenue,
    SUM(cash_gross_profit) AS cash_gross_profit,
    SUM(billed_credit_cash_transaction_count) AS billed_credit_cash_transaction_count,
    SUM(on_retry_billed_credit_cash_transaction_count) AS on_retry_billed_credit_cash_transaction_count,
    SUM(billing_cash_refund_amount) AS billing_cash_refund_amount,
    SUM(billing_cash_chargeback_amount) AS billing_cash_chargeback_amount,
    SUM(billed_credit_cash_transaction_amount) AS billed_credit_cash_transaction_amount,
    SUM(billed_credit_cash_refund_chargeback_amount) AS billed_credit_cash_refund_chargeback_amount,
    SUM(billed_cash_credit_redeemed_amount) AS billed_cash_credit_redeemed_amount,
    SUM(product_order_misc_cogs_amount) AS product_order_misc_cogs_amount,
    SUM(product_order_cash_gross_profit) AS product_order_cash_gross_profit,
    SUM(billed_cash_credit_redeemed_same_month_amount) AS billed_cash_credit_redeemed_same_month_amount,
    SUM(product_order_tariff_amount) AS product_order_tariff_amount,
    SUM(product_order_product_subtotal_amount) AS product_order_product_subtotal_amount,
    SUM(product_order_shipping_discount_amount) AS product_order_shipping_discount_amount,
    SUM(product_order_shipping_revenue_before_discount_amount) AS product_order_shipping_revenue_before_discount_amount,
    SUM(product_order_tax_amount) AS product_order_tax_amount,
    SUM(product_order_cash_transaction_amount) AS product_order_cash_transaction_amount,
    SUM(product_order_cash_credit_redeemed_amount) AS product_order_cash_credit_redeemed_amount,
    SUM(product_order_loyalty_unit_count) AS product_order_loyalty_unit_count,
    SUM(product_order_outfit_component_unit_count) AS product_order_outfit_component_unit_count,
    SUM(product_order_outfit_count) AS product_order_outfit_count,
    SUM(product_order_discounted_unit_count) AS product_order_discounted_unit_count,
    SUM(product_order_zero_revenue_unit_count) AS product_order_zero_revenue_unit_count,
    SUM(product_order_cash_credit_refund_amount) AS product_order_cash_credit_refund_amount,
    SUM(product_order_noncash_credit_refund_amount) AS product_order_noncash_credit_refund_amount,
    SUM(product_order_return_unit_count) AS product_order_return_unit_count,
    SUM(product_order_exchange_direct_cogs_amount) AS product_order_exchange_direct_cogs_amount,
    SUM(product_order_selling_expenses_amount) AS product_order_selling_expenses_amount,
    SUM(product_order_payment_processing_cost_amount) AS product_order_payment_processing_cost_amount,
    SUM(product_order_variable_gms_cost_amount) AS product_order_variable_gms_cost_amount,
    SUM(product_order_variable_warehouse_cost_amount) AS product_order_variable_warehouse_cost_amount,
    SUM(billing_selling_expenses_amount) AS billing_selling_expenses_amount,
    SUM(billing_payment_processing_cost_amount) AS billing_payment_processing_cost_amount,
    SUM(billing_variable_gms_cost_amount) AS billing_variable_gms_cost_amount,
    SUM(product_order_amount_to_pay) AS product_order_amount_to_pay,
    SUM(product_gross_revenue_excl_shipping) AS product_gross_revenue_excl_shipping,
    SUM(product_margin_pre_return_excl_shipping) AS product_margin_pre_return_excl_shipping,
    SUM(product_variable_contribution_profit) AS product_variable_contribution_profit,
    SUM(product_order_cash_net_revenue) AS product_order_cash_net_revenue,
    SUM(product_order_cash_margin_pre_return) AS product_order_cash_margin_pre_return,
    SUM(billing_cash_gross_revenue) AS billing_cash_gross_revenue,
    SUM(billing_cash_net_revenue) AS billing_cash_net_revenue,
    SUM(cash_variable_contribution_profit) AS cash_variable_contribution_profit,
    SUM(billing_order_transaction_count) AS billing_order_transaction_count,
    SUM(membership_fee_cash_transaction_amount) AS membership_fee_cash_transaction_amount,
    SUM(gift_card_transaction_amount) AS gift_card_transaction_amount,
    SUM(legacy_credit_cash_transaction_amount) AS legacy_credit_cash_transaction_amount,
    SUM(membership_fee_cash_refund_chargeback_amount) AS membership_fee_cash_refund_chargeback_amount,
    SUM(gift_card_cash_refund_chargeback_amount) AS gift_card_cash_refund_chargeback_amount,
    SUM(legacy_credit_cash_refund_chargeback_amount) AS legacy_credit_cash_refund_chargeback_amount,
    SUM(billed_cash_credit_issued_amount) AS billed_cash_credit_issued_amount,
    SUM(billed_cash_credit_cancelled_amount) AS billed_cash_credit_cancelled_amount,
    SUM(billed_cash_credit_expired_amount) AS billed_cash_credit_expired_amount,
    SUM(billed_cash_credit_issued_equivalent_count) AS billed_cash_credit_issued_equivalent_count,
    SUM(billed_cash_credit_redeemed_equivalent_count) AS billed_cash_credit_redeemed_equivalent_count,
    SUM(billed_cash_credit_cancelled_equivalent_count) AS billed_cash_credit_cancelled_equivalent_count,
    SUM(billed_cash_credit_expired_equivalent_count) AS billed_cash_credit_expired_equivalent_count,
    SUM(refund_cash_credit_issued_amount) AS refund_cash_credit_issued_amount,
    SUM(refund_cash_credit_redeemed_amount) AS refund_cash_credit_redeemed_amount,
    SUM(refund_cash_credit_cancelled_amount) AS refund_cash_credit_cancelled_amount,
    SUM(refund_cash_credit_expired_amount) AS refund_cash_credit_expired_amount,
    SUM(other_cash_credit_issued_amount) AS other_cash_credit_issued_amount,
    SUM(other_cash_credit_redeemed_amount) AS other_cash_credit_redeemed_amount,
    SUM(other_cash_credit_cancelled_amount) AS other_cash_credit_cancelled_amount,
    SUM(other_cash_credit_expired_amount) AS other_cash_credit_expired_amount,
    SUM(noncash_credit_issued_amount) AS noncash_credit_issued_amount,
    SUM(noncash_credit_cancelled_amount) AS noncash_credit_cancelled_amount,
    SUM(noncash_credit_expired_amount) AS noncash_credit_expired_amount
FROM _fso_agg AS fso
    LEFT JOIN reference.finance_segment_mapping AS fsm
        ON fso.store_id = fsm.event_store_id
        AND fso.vip_store_id = fsm.vip_store_id
        AND fso.is_retail_vip = fsm.is_retail_vip
        AND fso.gender = fsm.customer_gender
        AND fso.is_cross_promo = fsm.is_cross_promo
        AND fso.finance_specialty_store = fsm.finance_specialty_store
        AND fso.is_scrubs_customer = fsm.is_scrubs_customer
        AND (
                fsm.is_daily_cash_usd = TRUE
                OR fsm.is_daily_cash_eur = TRUE
                OR fsm.report_mapping IN ('FLNA-OREV')
        )
        AND fsm.metric_type = 'Orders'
GROUP BY
    fso.date,
    fso.date_object,
    fso.currency_object,
    fsm.report_mapping,
    fso.order_membership_classification_key;


CREATE OR REPLACE TEMP TABLE _fso_pivot AS
SELECT * FROM _fso_base
    UNPIVOT (value FOR metric IN (
    product_order_subtotal_excl_tariff_amount,
    product_order_product_discount_amount,
    product_order_shipping_revenue_amount,
    product_order_noncash_credit_redeemed_amount,
    product_order_count,
    product_order_unit_count,
    product_order_landed_product_cost_amount,
    product_order_shipping_cost_amount,
    product_order_shipping_supplies_cost_amount,
    product_order_direct_cogs_amount,
    product_order_cash_refund_amount,
    product_order_cash_chargeback_amount,
    product_order_cost_product_returned_resaleable_amount,
    product_order_cost_product_returned_damaged_amount,
    product_order_return_shipping_cost_amount,
    product_order_reship_order_count,
    product_order_reship_unit_count,
    product_order_reship_direct_cogs_amount,
    product_order_reship_product_cost_amount,
    product_order_reship_shipping_cost_amount,
    product_order_reship_shipping_supplies_cost_amount,
    product_order_exchange_order_count,
    product_order_exchange_unit_count,
    product_order_exchange_product_cost_amount,
    product_order_exchange_shipping_cost_amount,
    product_order_exchange_shipping_supplies_cost_amount,
    product_gross_revenue,
    product_net_revenue,
    product_margin_pre_return,
    product_gross_profit,
    product_order_cash_gross_revenue_amount,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    billed_credit_cash_transaction_count,
    on_retry_billed_credit_cash_transaction_count,
    billing_cash_refund_amount,
    billing_cash_chargeback_amount,
    billed_credit_cash_transaction_amount,
    billed_credit_cash_refund_chargeback_amount,
    billed_cash_credit_redeemed_amount,
    product_order_misc_cogs_amount,
    product_order_cash_gross_profit,
    billed_cash_credit_redeemed_same_month_amount,
    product_order_tariff_amount,
    product_order_product_subtotal_amount,
    product_order_shipping_discount_amount,
    product_order_shipping_revenue_before_discount_amount,
    product_order_tax_amount,
    product_order_cash_transaction_amount,
    product_order_cash_credit_redeemed_amount,
    product_order_loyalty_unit_count,
    product_order_outfit_component_unit_count,
    product_order_outfit_count,
    product_order_discounted_unit_count,
    product_order_zero_revenue_unit_count,
    product_order_cash_credit_refund_amount,
    product_order_noncash_credit_refund_amount,
    product_order_return_unit_count,
    product_order_exchange_direct_cogs_amount,
    product_order_selling_expenses_amount,
    product_order_payment_processing_cost_amount,
    product_order_variable_gms_cost_amount,
    product_order_variable_warehouse_cost_amount,
    billing_selling_expenses_amount,
    billing_payment_processing_cost_amount,
    billing_variable_gms_cost_amount,
    product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    product_margin_pre_return_excl_shipping,
    product_variable_contribution_profit,
    product_order_cash_net_revenue,
    product_order_cash_margin_pre_return,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_variable_contribution_profit,
    billing_order_transaction_count,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount
));

TRUNCATE TABLE validation.finance_sales_ops_daily_cash_base_comparison;
INSERT INTO validation.finance_sales_ops_daily_cash_base_comparison
(
    date,
    date_object,
    currency_object,
    report_mapping,
    order_membership_classification_key,
    metric,
    fso_value,
    daily_cash_value,
    variance,
    meta_create_datetime,
    meta_update_datetime
)
SELECT COALESCE(fso.date, dc.date)                                                               AS date,
       COALESCE(fso.date_object, dc.date_object)                                                 AS date_object,
       COALESCE(fso.currency_object, dc.currency_object)                                         AS currency_object,
       COALESCE(fso.report_mapping, dc.report_mapping)                                           AS report_mapping,
       COALESCE(fso.order_membership_classification_key,
                dc.order_membership_classification_key)                                          AS order_membership_classification_key,
       COALESCE(fso.metric, dc.metric)                                                           AS metric,
       IFNULL(fso.value,0)                                                                       AS fso_value,
       IFNULL(dc.value,0)                                                                        AS daily_cash_value,
       fso_value - daily_cash_value                                                              AS variance,
       $execution_start_time                                                                     AS meta_create_datetime,
       $execution_start_time                                                                     AS meta_update_datetime
FROM _fso_pivot AS fso
    FULL JOIN _daily_cash_pivot AS dc
        ON dc.date = fso.date
        AND dc.date_object = fso.date_object
        AND dc.currency_object = fso.currency_object
        AND IFNULL(dc.report_mapping,'NULL') = IFNULL(fso.report_mapping,'NULL')
        AND dc.order_membership_classification_key = fso.order_membership_classification_key
        AND dc.metric = fso.metric
WHERE variance <> 0;
