create or replace view LAKE_VIEW.MICROSOFT_ADS.GOALS_AND_FUNNELS_DAILY_REPORT as
select
ACCOUNT_ID
,CAMPAIGN_ID
,AD_GROUP_ID
,KEYWORD_ID
,GOAL
,ALL_CONVERSIONS
,ALL_CONVERSIONS_QUALIFIED
,ASSISTS
,ALL_REVENUE
,GOAL_ID
,DEVICE_TYPE
,DEVICE_OS
,GOAL_TYPE
,VIEW_THROUGH_CONVERSIONS
,DATE
,Convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
from LAKE_FIVETRAN.MED_MICROSOFT_ADS_V1.GOALS_AND_FUNNELS_DAILY_REPORT;
