create or replace view LAKE_VIEW.MICROSOFT_ADS.CAMPAIGN_HISTORY as
select
ID
,MODIFIED_TIME
,BUDGET
,PRIORITY
,LANGUAGE
,STATUS
,WEBSITE
,ACCOUNT_ID
,BUDGET_ID
,NAME
,TYPE
,BID_ADJUSTMENT
,BID_STRATEGY_MAX_CPC
,BID_STRATEGY_TARGET_CPA
,BID_STRATEGY_TYPE
,COUNTRY_CODE
,DOMAIN_LANGUAGE
,LOCAL_INVENTORY_ADS_ENABLED
,STORE_ID
,SUB_TYPE
,TIME_ZONE
,TRACKING_TEMPLATE
,Convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
from LAKE_FIVETRAN.MED_MICROSOFT_ADS_V1.CAMPAIGN_HISTORY;
