create or replace view LAKE_VIEW.MICROSOFT_ADS.KEYWORD_HISTORY as
select
ID
,MODIFIED_TIME
,BID
,LANGUAGE
,PARAM_1
,PARAM_2
,PARAM_3
,STATUS
,AD_GROUP_ID
,NAME
,BID_STRATEGY_TYPE
,DESTINATION_URL
,EDITORIAL_APPEAL_STATUS
,EDITORIAL_LOCATION
,EDITORIAL_REASON_CODE
,EDITORIAL_STATUS
,EDITORIAL_TERM
,FINAL_URL
,INHERITED_BID_STRATEGY_TYPE
,MATCH_TYPE
,MOBILE_FINAL_URL
,TRACKING_TEMPLATE
,Convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
from LAKE_FIVETRAN.MED_MICROSOFT_ADS_V1.KEYWORD_HISTORY;
