create or replace view LAKE_VIEW.MICROSOFT_ADS.AD_HISTORY as
select
ID
,MODIFIED_TIME
,DOMAIN
,TEXT
,TITLE
,STATUS
,TYPE
,AD_GROUP_ID
,AD_FORMAT_PREFERENCE
,BUSINESS_NAME
,CALL_TO_ACTION
,EDITORIAL_APPEAL_STATUS
,EDITORIAL_LOCATION
,EDITORIAL_REASON_CODE
,EDITORIAL_STATUS
,EDITORIAL_TERM
,DISPLAY_URL
,FINAL_URL
,MOBILE_FINAL_URL
,PATH_1
,PATH_2
,APP_ID
,APP_PLATFORM
,DEVICE_PREFERENCE
,TITLE_PART_1
,TITLE_PART_2
,TITLE_PART_3
,HEAD_LINE
,LONG_HEAD_LINE
,LANDSCAPE_IMAGE_MEDIA_ID
,LANDSCAPE_LOGO_MEDIA_ID
,SQUARE_IMAGE_MEDIA_ID
,SQUARE_LOGO_MEDIA_ID
,TRACKING_TEMPLATE
,Convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
from LAKE_FIVETRAN.MED_MICROSOFT_ADS_V1.AD_HISTORY;
