create or replace view LAKE_VIEW.MICROSOFT_ADS.AD_GROUP_HISTORY as
select
ID
,MODIFIED_TIME
,LANGUAGE
,STATUS
,CAMPAIGN_ID
,NAME
,AD_ROTATION
,BID_ADJUSTMENT
,BID_BOOST_VALUE
,BID_OPTION
,BID_STRATEGY_TYPE
,CPC_BID
,INHERITED_BID_STRATEGY_TYPE
,MAXIMUM_BID
,NETWORK_DISTRIBUTION
,PRIVACY_STATUS
,TARGET_SETTING
,END_DATE
,START_DATE
,TRACKING_TEMPLATE
,Convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
from LAKE_FIVETRAN.MED_MICROSOFT_ADS_V1.AD_GROUP_HISTORY;
