CREATE OR REPLACE VIEW lake_view.sailpoint.access_request_items AS
SELECT
    state,
    reviewer_comment,
    reviewed_by_type,
    reviewed_by_id,
    reviewed_by_name,
    requester_type,
    requester_id,
    requester_name,
    requested_for_type,
    requested_for_id,
    requested_for_name,
    owner_type,
    owner_id,
    owner_name,
    requester_comment_comment,
    requester_comment_author_type,
    requester_comment_author_id,
    requester_comment_author_name,
    convert_timezone('UTC', 'America/Los_Angeles', requester_comment_created) AS requester_comment_created,
    previous_reviewers_comments,
    forward_history,
    convert_timezone('UTC', 'America/Los_Angeles', request_created) AS request_created,
    requested_object_name,
    requested_object_description,
    requested_object_type,
    requested_object_id,
    request_type,
    convert_timezone('UTC', 'America/Los_Angeles', remove_date) AS remove_date,
    current_remove_date,
    remove_date_update_requested,
    comment_required_when_rejected,
    sod_violation_context,
    pre_approval_trigger_result_comment,
    pre_approval_trigger_result_decision,
    pre_approval_trigger_result_reviewer,
    convert_timezone('UTC', 'America/Los_Angeles', pre_approval_trigger_result_date) AS pre_approval_trigger_result_date,
    client_metadata_requested_app_icon,
    client_metadata_requested_app_name,
    client_metadata_requested_app_id,
    requested_accounts,
    assignment_context,
    id,
    name,
    convert_timezone('UTC', 'America/Los_Angeles', created) AS created,
    convert_timezone('UTC', 'America/Los_Angeles', modified) AS modified,
    updated_at,
    meta_create_datetime,
    meta_update_datetime
FROM lake.sailpoint.access_request_items;
