from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='eplmv14prod',
    schema='dbo',
    table='BOMHead',
    watermark_column='ModifiedOn',
    initial_load_value='1899-01-01',
    schema_version_prefix='v2',
    column_list=[
        Column('id_bom', 'INT', uniqueness=True, source_name='id_Bom'),
        Column('season', 'VARCHAR(15)', source_name='Season'),
        Column('style', 'VARCHAR(30)', source_name='Style'),
        Column('version', 'VARCHAR(15)', source_name='Version'),
        Column('revision', 'NUMBER(5, 0)', source_name='Revision'),
        Column('rev_description', 'VARCHAR(100)', source_name='RevDescription'),
        Column('std_calc', 'INT', source_name='Std_Calc'),
        Column('rev_date', 'TIMESTAMP_NTZ(3)', source_name='RevDate'),
        Column('link_parent', 'INT', source_name='Link_Parent'),
        Column('id_style', 'INT'),
        Column('factory', 'VARCHAR(10)', source_name='Factory'),
        Column('approved_bom', 'BOOLEAN', source_name='ApprovedBOM'),
        Column('default_bom', 'BOOLEAN', source_name='DefaultBOM'),
        Column('notes', 'VARCHAR'),
        Column('date_created', 'TIMESTAMP_NTZ(3)', source_name='DateCreated'),
        Column('rh_ready', 'BOOLEAN', source_name='RHReady'),
        Column('last_exported', 'TIMESTAMP_NTZ(3)', source_name='lastexported'),
        Column('last_edited', 'TIMESTAMP_NTZ(3)', source_name='lastedited'),
        Column('batch_no', 'VARCHAR(10)', source_name='batchNo'),
        Column('def_size', 'VARCHAR(15)', source_name='defsize'),
        Column('attachments', 'INT', source_name='Attachments'),
        Column('created_by', 'VARCHAR(25)', source_name='CreatedBy'),
        Column('created_on', 'TIMESTAMP_NTZ(3)', delta_column=1, source_name='CreatedOn'),
        Column('modified_by', 'VARCHAR(25)', source_name='ModifiedBy'),
        Column('modified_on', 'TIMESTAMP_NTZ(3)', delta_column=0, source_name='ModifiedOn'),
        Column('row_version', 'INT', source_name='RowVersion'),
        Column('print_pdf', 'BOOLEAN', source_name='printpdf'),
    ],
)
