from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="eplmv14prod",
    schema="dbo",
    table="BOMDetail",
    watermark_column="ModifiedOn",
    initial_load_value="1899-01-01",
    schema_version_prefix="v2",
    column_list=[
        Column("id_column", "INT", uniqueness=True),
        Column("id_bom", "INT", source_name="id_Bom"),
        Column("style_part", "VARCHAR(100)", source_name="StylePart"),
        Column("item", "VARCHAR(46)", source_name="Item"),
        Column("description", "VARCHAR(100)", source_name="Description"),
        Column("image_url", "VARCHAR(10)", source_name="ImageUrl"),
        Column("unit", "VARCHAR(15)", source_name="Unit"),
        Column("usage", "NUMBER(10, 4)", source_name="Usage"),
        Column("color", "VARCHAR(15)", source_name="Color"),
        Column("size", "VARCHAR(15)", source_name="Size"),
        Column("dimension", "VARCHAR(20)", source_name="Dimension"),
        Column("linked", "BOOLEAN", source_name="Linked"),
        Column("cost_cat", "VARCHAR(25)", source_name="Cost_Cat"),
        Column("cost_sheet", "BOOLEAN", source_name="Cost_Sheet"),
        Column("status_807", "VARCHAR(1)", source_name="Status_807"),
        Column("manual_post", "BOOLEAN", source_name="Manual_POst"),
        Column("id_standard", "INT"),
        Column("comp_color", "VARCHAR(15)", source_name="CompColor"),
        Column("approved", "BOOLEAN", source_name="Approved"),
        Column("color1", "VARCHAR(15)"),
        Column("color2", "VARCHAR(15)"),
        Column("color3", "VARCHAR(15)"),
        Column("color4", "VARCHAR(15)"),
        Column("color5", "VARCHAR(15)"),
        Column("color6", "VARCHAR(15)"),
        Column("color7", "VARCHAR(15)"),
        Column("color8", "VARCHAR(15)"),
        Column("color9", "VARCHAR(15)"),
        Column("color10", "VARCHAR(15)"),
        Column("color11", "VARCHAR(15)"),
        Column("color12", "VARCHAR(15)"),
        Column("color13", "VARCHAR(15)"),
        Column("color14", "VARCHAR(15)"),
        Column("color15", "VARCHAR(15)"),
        Column("color16", "VARCHAR(15)"),
        Column("color17", "VARCHAR(15)"),
        Column("color18", "VARCHAR(15)"),
        Column("color19", "VARCHAR(15)"),
        Column("color20", "VARCHAR(15)"),
        Column("color21", "VARCHAR(15)"),
        Column("color22", "VARCHAR(15)"),
        Column("color23", "VARCHAR(15)"),
        Column("color24", "VARCHAR(15)"),
        Column("edit_order", "VARCHAR(10)", source_name="EditOrder"),
        Column("color25", "VARCHAR(15)"),
        Column("color26", "VARCHAR(15)"),
        Column("color27", "VARCHAR(15)"),
        Column("color28", "VARCHAR(15)"),
        Column("color29", "VARCHAR(15)"),
        Column("color30", "VARCHAR(15)"),
        Column("color31", "VARCHAR(15)"),
        Column("color32", "VARCHAR(15)"),
        Column("color33", "VARCHAR(15)"),
        Column("color34", "VARCHAR(15)"),
        Column("color35", "VARCHAR(15)"),
        Column("color36", "VARCHAR(15)"),
        Column("color37", "VARCHAR(15)"),
        Column("color38", "VARCHAR(15)"),
        Column("color39", "VARCHAR(15)"),
        Column("color40", "VARCHAR(15)"),
        Column("color41", "VARCHAR(15)"),
        Column("color42", "VARCHAR(15)"),
        Column("color43", "VARCHAR(15)"),
        Column("color44", "VARCHAR(15)"),
        Column("color45", "VARCHAR(15)"),
        Column("color46", "VARCHAR(15)"),
        Column("color47", "VARCHAR(15)"),
        Column("color48", "VARCHAR(15)"),
        Column("color49", "VARCHAR(15)"),
        Column("color50", "VARCHAR(15)"),
        Column("color51", "VARCHAR(15)"),
        Column("color52", "VARCHAR(15)"),
        Column("color53", "VARCHAR(15)"),
        Column("color54", "VARCHAR(15)"),
        Column("color55", "VARCHAR(15)"),
        Column("color56", "VARCHAR(15)"),
        Column("color57", "VARCHAR(15)"),
        Column("color58", "VARCHAR(15)"),
        Column("color59", "VARCHAR(15)"),
        Column("color60", "VARCHAR(15)"),
        Column("color61", "VARCHAR(15)"),
        Column("color62", "VARCHAR(15)"),
        Column("color63", "VARCHAR(15)"),
        Column("color64", "VARCHAR(15)"),
        Column("color65", "VARCHAR(15)"),
        Column("color66", "VARCHAR(15)"),
        Column("color67", "VARCHAR(15)"),
        Column("color68", "VARCHAR(15)"),
        Column("color69", "VARCHAR(15)"),
        Column("color70", "VARCHAR(15)"),
        Column("color71", "VARCHAR(15)"),
        Column("color72", "VARCHAR(15)"),
        Column("color73", "VARCHAR(15)"),
        Column("color74", "VARCHAR(15)"),
        Column("color75", "VARCHAR(15)"),
        Column("color76", "VARCHAR(15)"),
        Column("color77", "VARCHAR(15)"),
        Column("color78", "VARCHAR(15)"),
        Column("color79", "VARCHAR(15)"),
        Column("color80", "VARCHAR(15)"),
        Column("color81", "VARCHAR(15)"),
        Column("color82", "VARCHAR(15)"),
        Column("color83", "VARCHAR(15)"),
        Column("color84", "VARCHAR(15)"),
        Column("color85", "VARCHAR(15)"),
        Column("color86", "VARCHAR(15)"),
        Column("color87", "VARCHAR(15)"),
        Column("color88", "VARCHAR(15)"),
        Column("color89", "VARCHAR(15)"),
        Column("color90", "VARCHAR(15)"),
        Column("color91", "VARCHAR(15)"),
        Column("color92", "VARCHAR(15)"),
        Column("color93", "VARCHAR(15)"),
        Column("color94", "VARCHAR(15)"),
        Column("color95", "VARCHAR(15)"),
        Column("color96", "VARCHAR(15)"),
        Column("color97", "VARCHAR(15)"),
        Column("color98", "VARCHAR(15)"),
        Column("color99", "VARCHAR(15)"),
        Column("color100", "VARCHAR(15)"),
        Column("row_number", "INT", source_name="rownumber"),
        Column("vendor", "VARCHAR(20)"),
        Column("recorder", "INT"),
        Column("prod_cat", "VARCHAR(25)", source_name="prodcat"),
        Column("supplied", "BOOLEAN"),
        Column("common", "BOOLEAN"),
        Column("subs_comp", "VARCHAR(25)", source_name="SubsComp"),
        Column("subst_vendor", "VARCHAR(25)", source_name="substVendor"),
        Column("size1", "VARCHAR(10)"),
        Column("size2", "VARCHAR(10)"),
        Column("size3", "VARCHAR(10)"),
        Column("size4", "VARCHAR(10)"),
        Column("size5", "VARCHAR(10)"),
        Column("size6", "VARCHAR(10)"),
        Column("size7", "VARCHAR(10)"),
        Column("size8", "VARCHAR(10)"),
        Column("size9", "VARCHAR(10)"),
        Column("size10", "VARCHAR(10)"),
        Column("size11", "VARCHAR(10)"),
        Column("size12", "VARCHAR(10)"),
        Column("size13", "VARCHAR(10)"),
        Column("size14", "VARCHAR(10)"),
        Column("size15", "VARCHAR(10)"),
        Column("size16", "VARCHAR(10)"),
        Column("size17", "VARCHAR(10)"),
        Column("size18", "VARCHAR(10)"),
        Column("size19", "VARCHAR(10)"),
        Column("size20", "VARCHAR(10)"),
        Column("size21", "VARCHAR(10)"),
        Column("size22", "VARCHAR(10)"),
        Column("size23", "VARCHAR(10)"),
        Column("size24", "VARCHAR(10)"),
        Column("size25", "VARCHAR(10)"),
        Column("size26", "VARCHAR(10)"),
        Column("size27", "VARCHAR(10)"),
        Column("size28", "VARCHAR(10)"),
        Column("size29", "VARCHAR(10)"),
        Column("size30", "VARCHAR(10)"),
        Column("size31", "VARCHAR(10)"),
        Column("size32", "VARCHAR(10)"),
        Column("size33", "VARCHAR(10)"),
        Column("size34", "VARCHAR(10)"),
        Column("size35", "VARCHAR(10)"),
        Column("cost", "NUMBER(10, 4)"),
        Column("comm_usage", "VARCHAR(10)", source_name="commusage"),
        Column("attachments", "INT", source_name="Attachments"),
        Column("is_style", "BOOLEAN", source_name="isStyle"),
        Column("created_by", "VARCHAR(25)", source_name="CreatedBy"),
        Column(
            "created_on", "TIMESTAMP_NTZ(3)", delta_column=1, source_name="CreatedOn"
        ),
        Column("modified_by", "VARCHAR(25)", source_name="ModifiedBy"),
        Column(
            "modified_on", "TIMESTAMP_NTZ(3)", delta_column=0, source_name="ModifiedOn"
        ),
        Column("row_version", "INT", source_name="RowVersion"),
        Column("vendor_name", "VARCHAR(50)"),
        Column("bom_ref", "VARCHAR(6)", source_name="BOM_REF"),
        Column("size36", "VARCHAR(10)", source_name="Size36"),
        Column("size37", "VARCHAR(10)", source_name="Size37"),
        Column("size38", "VARCHAR(10)", source_name="Size38"),
        Column("size39", "VARCHAR(10)", source_name="Size39"),
        Column("size40", "VARCHAR(10)", source_name="Size40"),
        Column("size41", "VARCHAR(10)", source_name="Size41"),
        Column("size42", "VARCHAR(10)", source_name="Size42"),
        Column("size43", "VARCHAR(10)", source_name="Size43"),
        Column("size44", "VARCHAR(10)", source_name="Size44"),
        Column("size45", "VARCHAR(10)", source_name="Size45"),
        Column("size46", "VARCHAR(10)", source_name="Size46"),
        Column("size47", "VARCHAR(10)", source_name="Size47"),
        Column("size48", "VARCHAR(10)", source_name="Size48"),
        Column("size49", "VARCHAR(10)", source_name="Size49"),
        Column("size50", "VARCHAR(10)", source_name="Size50"),
        Column("size51", "VARCHAR(10)", source_name="Size51"),
        Column("size52", "VARCHAR(10)", source_name="Size52"),
        Column("size53", "VARCHAR(10)", source_name="Size53"),
        Column("size54", "VARCHAR(10)", source_name="Size54"),
        Column("size55", "VARCHAR(10)", source_name="Size55"),
        Column("size56", "VARCHAR(10)", source_name="Size56"),
        Column("size57", "VARCHAR(10)", source_name="Size57"),
        Column("size58", "VARCHAR(10)", source_name="Size58"),
        Column("size59", "VARCHAR(10)", source_name="Size59"),
        Column("size60", "VARCHAR(10)", source_name="Size60"),
        Column("size61", "VARCHAR(10)", source_name="Size61"),
        Column("size62", "VARCHAR(10)", source_name="Size62"),
        Column("size63", "VARCHAR(10)", source_name="Size63"),
        Column("size64", "VARCHAR(10)", source_name="Size64"),
        Column("size65", "VARCHAR(10)", source_name="Size65"),
        Column("size66", "VARCHAR(10)", source_name="Size66"),
        Column("size67", "VARCHAR(10)", source_name="Size67"),
        Column("size68", "VARCHAR(10)", source_name="Size68"),
        Column("size69", "VARCHAR(10)", source_name="Size69"),
        Column("size70", "VARCHAR(10)", source_name="Size70"),
        Column("size71", "VARCHAR(10)", source_name="Size71"),
        Column("size72", "VARCHAR(10)", source_name="Size72"),
        Column("size73", "VARCHAR(10)", source_name="Size73"),
        Column("size74", "VARCHAR(10)", source_name="Size74"),
        Column("size75", "VARCHAR(10)", source_name="Size75"),
        Column("size76", "VARCHAR(10)", source_name="Size76"),
        Column("size77", "VARCHAR(10)", source_name="Size77"),
        Column("size78", "VARCHAR(10)", source_name="Size78"),
        Column("size79", "VARCHAR(10)", source_name="Size79"),
        Column("size80", "VARCHAR(10)", source_name="Size80"),
        Column("size81", "VARCHAR(10)", source_name="Size81"),
        Column("size82", "VARCHAR(10)", source_name="Size82"),
        Column("size83", "VARCHAR(10)", source_name="Size83"),
        Column("size84", "VARCHAR(10)", source_name="Size84"),
        Column("size85", "VARCHAR(10)", source_name="Size85"),
        Column("size86", "VARCHAR(10)", source_name="Size86"),
        Column("size87", "VARCHAR(10)", source_name="Size87"),
        Column("size88", "VARCHAR(10)", source_name="Size88"),
        Column("size89", "VARCHAR(10)", source_name="Size89"),
        Column("size90", "VARCHAR(10)", source_name="Size90"),
        Column("size91", "VARCHAR(10)", source_name="Size91"),
        Column("size92", "VARCHAR(10)", source_name="Size92"),
        Column("size93", "VARCHAR(10)", source_name="Size93"),
        Column("size94", "VARCHAR(10)", source_name="Size94"),
        Column("size95", "VARCHAR(10)", source_name="Size95"),
        Column("size96", "VARCHAR(10)", source_name="Size96"),
        Column("size97", "VARCHAR(10)", source_name="Size97"),
        Column("size98", "VARCHAR(10)", source_name="Size98"),
        Column("size99", "VARCHAR(10)", source_name="Size99"),
        Column("size100", "VARCHAR(10)", source_name="Size100"),
    ],
)
