from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="eplmv14prod",
    schema="dbo",
    table="DesCode",
    watermark_column="ModifiedOn",
    initial_load_value="1899-01-01",
    schema_version_prefix="v2",
    column_list=[
        Column("season", "VARCHAR(15)"),
        Column("style", "VARCHAR(30)"),
        Column("design_memo", "VARCHAR", source_name="designmemo"),
        Column("design_img", "VARCHAR(50)", source_name="designimg"),
        Column("id_style", "INT", uniqueness=True),
        Column("exp_date", "TIMESTAMP_NTZ(3)", source_name="expdate"),
        Column("orig_exp_date", "TIMESTAMP_NTZ(3)", source_name="origexpdate"),
        Column("status", "VARCHAR(50)"),
        Column("cycle_days", "INT", source_name="cycledays"),
        Column("last_step", "VARCHAR(50)", source_name="laststep"),
        Column("days_late", "INT", source_name="dayslate"),
        Column("ini_date", "TIMESTAMP_NTZ(3)", source_name="inidate"),
        Column("stgscode", "VARCHAR(50)"),
        Column("completed", "BOOLEAN"),
        Column("date_completed", "TIMESTAMP_NTZ(3)", source_name="datecompleted"),
        Column("revision", "VARCHAR(10)", source_name="Revision"),
        Column("desce", "VARCHAR(50)", source_name="Desce"),
        Column("publish", "BOOLEAN", source_name="Publish"),
        Column("desn_image", "VARCHAR", source_name="DesnImage"),
        Column("dist_specs", "BOOLEAN", source_name="DistSpecs"),
        Column("last_date", "TIMESTAMP_NTZ(3)", source_name="LastDate"),
        Column("was_revised", "BOOLEAN", source_name="WasRevised"),
        Column("misc1", "VARCHAR(30)"),
        Column("misc2", "VARCHAR(30)"),
        Column("misc3", "VARCHAR(30)"),
        Column("misc4", "VARCHAR(30)"),
        Column("misc5", "VARCHAR(30)"),
        Column("misc6", "VARCHAR(30)"),
        Column("misc7", "VARCHAR(30)"),
        Column("misc8", "VARCHAR(30)"),
        Column("misc9", "VARCHAR(30)"),
        Column("misc10", "VARCHAR(30)"),
        Column("misc11", "VARCHAR(30)"),
        Column("misc12", "VARCHAR(30)"),
        Column("misc13", "VARCHAR(30)"),
        Column("misc14", "VARCHAR(30)"),
        Column("misc15", "VARCHAR(30)"),
        Column("misc16", "VARCHAR(30)"),
        Column("misc17", "VARCHAR(30)"),
        Column("misc18", "VARCHAR(30)"),
        Column("misc19", "VARCHAR(30)"),
        Column("misc20", "VARCHAR(30)"),
        Column("prototype", "BOOLEAN"),
        Column("start_date", "TIMESTAMP_NTZ(3)", source_name="startdate"),
        Column("whole_cost", "NUMBER(14, 4)", source_name="wholecost"),
        Column("whole_price", "NUMBER(14, 4)", source_name="WholePrice"),
        Column("main_image", "VARCHAR(10)", source_name="mainimage"),
        Column("scale", "VARCHAR(15)"),
        Column("manuf_price", "NUMBER(14, 4)", source_name="ManufPrice"),
        Column("retail_price", "NUMBER(14, 4)", source_name="RetailPrice"),
        Column("whole_margin", "NUMBER(14, 4)", source_name="WholeMargin"),
        Column("retail_margin", "NUMBER(14, 4)", source_name="RetailMargin"),
        Column("manuf_cost", "NUMBER(14, 4)", source_name="manufcost"),
        Column("manuf_margin", "NUMBER(14, 4)", source_name="manufmargin"),
        Column("retail_cost", "NUMBER(14, 4)", source_name="retailcost"),
        Column("forecast", "NUMBER(10, 0)", source_name="Forecast"),
        Column("unit", "VARCHAR(4)"),
        Column("gar_type", "VARCHAR(5)", source_name="gartype"),
        Column("pd_misc1", "VARCHAR(30)", source_name="PDMisc1"),
        Column("pd_misc2", "VARCHAR(30)", source_name="PDMisc2"),
        Column("pd_misc3", "VARCHAR(30)", source_name="PDMisc3"),
        Column("style_status", "VARCHAR(15)", source_name="stylestatus"),
        Column("has_color_way", "BOOLEAN", source_name="hasColorWay"),
        Column("chart_code", "VARCHAR(10)", source_name="chartcode"),
        Column("chart_description", "VARCHAR(50)", source_name="chartDescription"),
        Column("lab_pack_notes", "VARCHAR", source_name="LabPacknotes"),
        Column("const_notes", "VARCHAR", source_name="Constnotes"),
        Column("colw_notes", "VARCHAR", source_name="colwnotes"),
        Column("lab_notes", "VARCHAR", source_name="labnotes"),
        Column("proto_season", "VARCHAR(15)", source_name="ProtoSeason"),
        Column("proto_style", "VARCHAR(30)", source_name="ProtoStyle"),
        Column("group_name", "VARCHAR(20)", source_name="groupName"),
        Column("size_specs", "VARCHAR", source_name="sizespecs"),
        Column("color_specs", "VARCHAR", source_name="colorspecs"),
        Column("cost", "NUMBER(8, 2)"),
        Column("sale_price", "NUMBER(8, 2)", source_name="saleprice"),
        Column("ldp_cost", "NUMBER(10, 4)", source_name="ldpcost"),
        Column("retail_confirmed", "BOOLEAN", source_name="retailconfirmed"),
        Column("cost_confirmed", "BOOLEAN", source_name="costconfirmed"),
        Column("planned_units", "NUMBER(11, 0)", source_name="plannedunits"),
        Column("id_calendar", "INT"),
        Column("more_fields", "VARCHAR", source_name="morefields"),
        Column("w_board_master", "NUMBER(1, 0)", source_name="wboardMaster"),
        Column("opt_locked", "NUMBER(1, 0)", source_name="optLocked"),
        Column("rh_ready", "BOOLEAN", source_name="RHReady"),
        Column("last_exported", "TIMESTAMP_NTZ(3)", source_name="lastexported"),
        Column("last_edited", "TIMESTAMP_NTZ(3)", source_name="lastedited"),
        Column("img_front", "VARCHAR(10)", source_name="imgfront"),
        Column("img_back", "VARCHAR(10)", source_name="imgBack"),
        Column("img_side", "VARCHAR(10)", source_name="imgSide"),
        Column("img_detail", "VARCHAR(10)", source_name="imgDetail"),
        Column("fron_txt", "VARCHAR(30)", source_name="Frontxt"),
        Column("back_txt", "VARCHAR(30)", source_name="backtxt"),
        Column("side_txt", "VARCHAR(30)", source_name="sidetxt"),
        Column("detail_txt", "VARCHAR(30)", source_name="detailtxt"),
        Column("misc21", "VARCHAR(30)"),
        Column("misc22", "VARCHAR(30)"),
        Column("misc23", "VARCHAR(30)"),
        Column("misc24", "VARCHAR(30)"),
        Column("misc25", "VARCHAR(30)"),
        Column("misc26", "VARCHAR(30)"),
        Column("misc27", "VARCHAR(30)"),
        Column("misc28", "VARCHAR(30)"),
        Column("misc29", "VARCHAR(30)"),
        Column("misc30", "VARCHAR(30)"),
        Column("misc31", "VARCHAR(30)"),
        Column("misc32", "VARCHAR(30)"),
        Column("misc33", "VARCHAR(30)"),
        Column("misc34", "VARCHAR(30)"),
        Column("misc35", "VARCHAR(30)"),
        Column("misc36", "VARCHAR(30)"),
        Column("misc37", "VARCHAR(30)"),
        Column("misc38", "VARCHAR(30)"),
        Column("misc39", "VARCHAR(30)"),
        Column("misc40", "VARCHAR(30)"),
        Column("desc_rev", "VARCHAR(10)", source_name="descrev"),
        Column("batch_no", "VARCHAR(10)", source_name="batchNo"),
        Column("collab_issues", "INT"),
        Column("prob", "VARCHAR(250)"),
        Column("attachments", "INT", source_name="Attachments"),
        Column("created_date", "TIMESTAMP_NTZ(3)", source_name="CreatedDate"),
        Column("created_by", "VARCHAR(25)", source_name="Createdby"),
        Column("edited_by", "VARCHAR(25)", source_name="Editedby"),
        Column("last_tab_edited", "VARCHAR(25)", source_name="LastTabEdited"),
        Column(
            "created_on", "TIMESTAMP_NTZ(3)", delta_column=1, source_name="CreatedOn"
        ),
        Column("modified_by", "VARCHAR(25)", source_name="ModifiedBy"),
        Column(
            "modified_on", "TIMESTAMP_NTZ(3)", delta_column=0, source_name="ModifiedOn"
        ),
        Column("row_version", "INT", source_name="RowVersion"),
        Column("hts", "VARCHAR(20)"),
        Column("target_fob", "NUMBER(19, 4)", source_name="TargetFOB"),
        Column("quoted_fob", "NUMBER(19, 4)", source_name="QuotedFOB"),
        Column("actual_fob", "NUMBER(19, 4)", source_name="ActualFOB"),
        Column("current_fob", "NUMBER(19, 4)", source_name="CurrentFOB"),
        Column("landed_cost", "NUMBER(19, 4)", source_name="LandedCost"),
        Column("x_target_fob", "NUMBER(19, 4)", source_name="xTargetFOB"),
        Column("x_quoted_fob", "NUMBER(19, 4)", source_name="xQuotedFOB"),
        Column("x_actual_fob", "NUMBER(19, 4)", source_name="xActualFOB"),
        Column("x_current_fob", "NUMBER(19, 4)", source_name="xCurrentFOB"),
        Column("x_landed_cost", "NUMBER(19, 4)", source_name="xLandedCost"),
        Column("x_retail_price", "NUMBER(19, 4)", source_name="xRetailPrice"),
        Column("x_whole_price", "NUMBER(19, 4)", source_name="xWholePrice"),
        Column("x_whole_margin", "NUMBER(19, 4)", source_name="xWholeMargin"),
        Column("is_set", "BOOLEAN", source_name="isset"),
        Column("side_measurement", "BOOLEAN", source_name="sidemeasurement"),
        Column("last_season", "VARCHAR(15)", source_name="LastSeason"),
        Column("last_style", "VARCHAR(30)", source_name="LastStyle"),
        Column("line_plan_order", "NUMBER(6, 0)", source_name="lineplanorder"),
    ],
)
