from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='eplmv14prod',
    schema='dbo',
    table='StyleColorw',
    watermark_column='ModifiedOn',
    initial_load_value='1899-01-01',
    schema_version_prefix='v2',
    column_list=[
        Column('id_style', 'INT'),
        Column('colorway', 'VARCHAR(15)'),
        Column('id_colorway', 'INT', uniqueness=True),
        Column('bom_order', 'INT', source_name='bomOrder'),
        Column('color_desc', 'VARCHAR(50)', source_name='colordesc'),
        Column('batch_no', 'VARCHAR(10)', source_name='batchNo'),
        Column('last_exported', 'TIMESTAMP_NTZ(3)', source_name='lastExported'),
        Column('ratio', 'NUMBER(10, 4)', source_name='Ratio'),
        Column('attachments', 'INT', source_name='Attachments'),
        Column('created_by', 'VARCHAR(25)', source_name='CreatedBy'),
        Column('created_on', 'TIMESTAMP_NTZ(3)', delta_column=1, source_name='CreatedOn'),
        Column('modified_by', 'VARCHAR(25)', source_name='ModifiedBy'),
        Column('modified_on', 'TIMESTAMP_NTZ(3)', delta_column=0, source_name='ModifiedOn'),
        Column('row_version', 'INT', source_name='RowVersion'),
        Column('color_forecast', 'INT', source_name='ColorForecast'),
        Column('color_sales', 'INT', source_name='ColorSales'),
        Column('color_discounted', 'INT', source_name='ColorDiscounted'),
        Column('original_qty', 'INT', source_name='OriginalQty'),
        Column('misc1', 'VARCHAR(30)'),
        Column('misc2', 'VARCHAR(30)'),
        Column('misc3', 'VARCHAR(30)'),
        Column('misc4', 'VARCHAR(30)'),
        Column('misc5', 'VARCHAR(30)'),
        Column('misc6', 'VARCHAR(30)'),
        Column('misc7', 'VARCHAR(30)'),
        Column('misc8', 'VARCHAR(30)'),
        Column('misc9', 'VARCHAR(30)'),
        Column('misc10', 'VARCHAR(30)'),
        Column('misc11', 'VARCHAR(30)'),
        Column('misc12', 'VARCHAR(30)'),
        Column('misc13', 'VARCHAR(30)'),
        Column('misc14', 'VARCHAR(30)'),
        Column('misc15', 'VARCHAR(30)'),
        Column('misc16', 'VARCHAR(30)'),
        Column('misc17', 'VARCHAR(30)'),
        Column('misc18', 'VARCHAR(30)'),
        Column('misc19', 'VARCHAR(30)'),
        Column('misc20', 'VARCHAR(30)'),
        Column('misc21', 'VARCHAR(30)'),
        Column('misc22', 'VARCHAR(30)'),
        Column('misc23', 'VARCHAR(30)'),
        Column('misc24', 'VARCHAR(30)'),
        Column('misc25', 'VARCHAR(30)'),
        Column('misc26', 'VARCHAR(30)'),
        Column('misc27', 'VARCHAR(30)'),
        Column('misc28', 'VARCHAR(30)'),
        Column('misc29', 'VARCHAR(30)'),
        Column('misc30', 'VARCHAR(30)'),
        Column('misc31', 'VARCHAR(30)'),
        Column('misc32', 'VARCHAR(30)'),
        Column('misc33', 'VARCHAR(30)'),
        Column('misc34', 'VARCHAR(30)'),
        Column('misc35', 'VARCHAR(30)'),
        Column('misc36', 'VARCHAR(30)'),
        Column('misc37', 'VARCHAR(30)'),
        Column('misc38', 'VARCHAR(30)'),
        Column('misc39', 'VARCHAR(30)'),
        Column('misc40', 'VARCHAR(30)'),
        Column('is_discon', 'BOOLEAN', source_name='isdiscon'),
        Column('is_dropped', 'BOOLEAN', source_name='isdropped'),
        Column('actual_fob', 'NUMBER(19, 4)', source_name='ActualFOB'),
        Column('current_fob', 'NUMBER(19, 4)', source_name='CurrentFOB'),
        Column('target_fob', 'NUMBER(19, 4)', source_name='TargetFOB'),
        Column('quoted_fob', 'NUMBER(19, 4)', source_name='QuotedFOB'),
        Column('landed_cost', 'NUMBER(19, 4)', source_name='LandedCost'),
        Column('x_actual_fob', 'NUMBER(19, 4)', source_name='xActualFOB'),
        Column('x_target_fob', 'NUMBER(19, 4)', source_name='xTargetFOB'),
        Column('x_quoted_fob', 'NUMBER(19, 4)', source_name='xQuotedFOB'),
        Column('x_current_fob', 'NUMBER(19, 4)', source_name='xCurrentFOB'),
        Column('x_landed_cost', 'NUMBER(19, 4)', source_name='xLandedCost'),
        Column('x_retail_price', 'NUMBER(19, 4)', source_name='xRetailPrice'),
        Column('x_whole_price', 'NUMBER(19, 4)', source_name='xWholePrice'),
        Column('x_whole_margin', 'NUMBER(19, 4)', source_name='xWholeMargin'),
        Column('manuf_cost', 'NUMBER(9, 4)', source_name='manufcost'),
        Column('manuf_margin', 'NUMBER(9, 2)', source_name='manufmargin'),
        Column('manuf_price', 'NUMBER(9, 4)', source_name='ManufPrice'),
        Column('retail_price', 'NUMBER(9, 4)', source_name='RetailPrice'),
        Column('retail_margin', 'NUMBER(9, 2)', source_name='RetailMargin'),
        Column('retail_cost', 'NUMBER(9, 4)', source_name='retailcost'),
        Column('whole_cost', 'NUMBER(9, 4)', source_name='wholecost'),
        Column('whole_price', 'NUMBER(9, 4)', source_name='WholePrice'),
        Column('whole_margin', 'NUMBER(9, 2)', source_name='WholeMargin'),
        Column('id_color', 'INT'),
    ],
)
