-- CREATIVE DIMENSIONS CLEANSED TABLE
-- purpose: combine all creative naming generators into one cleansed table
create or replace temporary table _creative_dimensions as
 select
    'Fabletics' as store_brand_name,
    'NA' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    null as body_type,
    gender,
    still_life_angle_shot as image_focus,
    null as still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--     null as background_environment,
    platform_or_creative_format as platform,
   null as merchandise_type,
   merchandise_type as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
     null as partner
from lake_view.sharepoint.med_fl_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Fabletics Men' as store_brand_name,
    'NA' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    null as body_type,
    gender,
    still_life_angle_shot as image_focus,
    null as still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--    null as background_environment,
    platform_or_creative_format as platform,
    null as merchandise_type,
    merchandise_type as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    null as partner
from lake_view.sharepoint.med_flm_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Yitty' as store_brand_name,
    'NA' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    body_type,
    gender,
    still_life_angle_shot as image_focus,
    null as still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--    null as background_environment,
    platform_or_creative_format as platform,
    null as merchandise_type,
    merchandise_type as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    null as partner
from lake_view.sharepoint.med_yty_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Fabletics Scrubs' as store_brand_name,
    'NA' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    null as body_type,
    gender,
    still_life_angle_shot as image_focus,
    null as still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--    null as background_environment,
    platform_or_creative_format as platform,
    null as merchandise_type,
    merchandise_type as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    messaging_theme,
--    null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    null as partner
from lake_view.sharepoint.med_scb_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Savage X' as store_brand_name,
    'NA' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    null as first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    missy_or_curvy as body_type,
    gender,
    null as image_focus,
    still_life_angle_shot,
    influencer_name as influencer,
    null as ugc_talent_name,
    null as egc_talent_name,
    null as trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    null as creative_concept,
    test_name,
--     null as background_texture,
    null as background,
--     null as background_environment,
    platform_or_creative_format as platform,
    merchandise_type,
    null as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    null as offer_timing,
--     null as offer_type,
    offer_placement,
    messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    null as partner
from lake_view.sharepoint.med_sx_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'FabKids' as store_brand_name,
    'NA' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    template,
    null as video_length,
    null as audio,
    first_3_seconds_visual,
    shot_type,
--    null as tiktok_style,
    null as first_3_seconds_text,
    null as font_used,
--    null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    null as model_action,
    null as model_placement,
    null as body_type,
    gender,
    null as image_focus,
    null as still_life_angle_shot,
    influencer_name as influencer,
    null as ugc_talent_name,
    null as egc_talent_name,
    null as trello_id,
    null as asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    null as test_name,
--     null as background_texture,
    background as background,
--     null as background_environment,
    platform_or_creative_format as platform,
    merchandise_type,
    null as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku_1 as sku1,
    sku_2 as sku2,
    sku_3 as sku3,
    sku_4 as sku4,
    sku_5 as sku5,
    null as logo,
    offer_promo as offer,
    null as offer_timing,
--     null as offer_type,
    offer_lockup as offer_placement,
    messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    null as partner
from lake_view.sharepoint.med_fk_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'JFB' as store_brand_name,
    'NA' as region,
    creative_code,
    designer_initials,
    date_created,
    jf_brand,
    null as version,
    ad_type,
    template_type as template,
    video_length,
    audio,
    first_3_seconds_visual,
    product_shot_type as shot_type,
--    null as tiktok_style,
   null as first_3_seconds_text,
   font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    null as model_action,
    null as model_placement,
    null as body_type,
    null as gender,
    null as image_focus,
    null as still_life_angle_shot,
    influencer_name as influencer,
    null as ugc_talent_name,
    null as egc_talent_name,
    null as trello_id,
    null as asset_type,
    asset_size,
--    null as creative_format_template,
    creative_concept,
    null as test_name,
--     null as background_texture,
    null as background,
--     null as background_environment,
    platform_or_creative_format as platform,
    merchandise_type,
    null as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku_1 as sku1,
    sku_2 as sku2,
    sku_3 as sku3,
    sku_4 as sku4,
    sku_5 as sku5,
    null as logo,
    offer_promo as offer,
    offer_timing,
--     offer_type,
    offer_lockup_placement as offer_placement,
    null as messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    null as partner
from lake_view.sharepoint.med_jfb_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Fabletics' as store_brand_name,
    'EU' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    null as body_type,
    gender,
    null as image_focus,
    still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--     null as background_environment,
    platform_or_creative_format as platform,
   null as merchandise_type,
   null as promo_type,
   number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    null as messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    partner_agency as partner
from lake_view.sharepoint.med_fleu_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Fabletics Men' as store_brand_name,
    'EU' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    null as body_type,
    gender,
    null as image_focus,
    still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--     null as background_environment,
    platform_or_creative_format as platform,
   null as merchandise_type,
   null as promo_type,
   number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    null as messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    partner_agency as partner
from lake_view.sharepoint.med_flmeu_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Fabletics Scrubs' as store_brand_name,
    'EU' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    model_action,
    model_placement,
    null as body_type,
    gender,
    null as image_focus,
    still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--     null as background_environment,
    platform_or_creative_format as platform,
   null as merchandise_type,
   null as promo_type,
   number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    null as messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    partner_agency as partner
from lake_view.sharepoint.med_scbeu_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1

union

select
    'Savage X' as store_brand_name,
    'EU' as region,
    creative_code,
    designer_initials,
    date_created,
    null as jf_brand,
    null as version,
    ad_type,
    null as template,
    video_length,
    audio,
    first_3_seconds_visual,
    null as shot_type,
--     null as tiktok_style,
    first_3_seconds_text,
    null as font_used,
--     null as endcard,
--     null as text_animated,
--     null as image_animated,
--     null as graphics_animated,
--     null as carousel_card_count,
--     null as carousel_title_card,
--     null as carousel_end_card,
--     null as carousel_contains_video,
    null as model_action,
    model_placement,
    missy_or_curvy as body_type,
    gender,
    null as image_focus,
    null as still_life_angle_shot,
    influencer_name as influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
--     null as creative_format_template,
    adset_creative_concept as creative_concept,
    test_variants_videos as test_name,
--     null as background_texture,
    null as background,
--     null as background_environment,
    platform_or_creative_format as platform,
    merchandise_type,
    null as promo_type,
    number_of_styles_shown,
--     null as footwear_type,
    sku1,
    sku2,
    sku3,
    sku4,
    sku5,
    logo,
    offer_promo as offer,
    offer_timing,
--     null as offer_type,
    offer_placement,
    messaging_theme,
--     null as messaging_urgency,
--     null as messaging_question,
    null as product_type,
--     null as product_name_called_out,
--     null as price_slash_out,
--     null as cta,
--     null as model_name
    null as partner
from lake_view.sharepoint.med_sxeu_creative_dimensions
QUALIFY row_number() OVER(PARTITION BY creative_code ORDER BY NULL)=1;



-- union -- historical code saved but no longer running / deprecated ingestion of old sheets + code
--
-- select *
-- from reporting_media_base_prod.dbo.creative_dimensions_historical;

create or replace transient table reporting_media_base_prod.dbo.creative_dimensions as
select
    store_brand_name,
    region,
    creative_code,
    designer_initials,
    date_created,
    ifnull(version, 'None') as version,
    ifnull(iff(ad_type in ('DABA','GIF'),ad_type,initcap(rtrim(ad_type))),'None') as ad_type,
    ifnull(video_length,'None') as video_length,
    iff(audio = 'No Audio','None',
        iff(audio = 'Voiceover','Voice Over',(ifnull(initcap(audio),'None')))) as audio,
    iff(contains(lower(first_3_seconds_text),'no'),'None',ifnull(initcap(first_3_seconds_text),'None')) as first_3_seconds_text,
    iff(first_3_seconds_visual='No Text','None',ifnull(initcap(first_3_seconds_visual),'None')) as first_3_seconds_visual,
    ifnull(initcap(model_action),'None') as model_action,
    ifnull(initcap(model_placement),'None') as model_placement,
    ifnull(initcap(body_type),'None') as body_type,
    ifnull(initcap(gender),'None') as gender,
    ifnull(initcap(image_focus),'None') as image_focus,
    ifnull(initcap(still_life_angle_shot),'None') as still_life_angle_shot,
    ifnull(influencer, 'None') as influencer,
    ifnull(initcap(ugc_talent_name),'None') as ugc_talent_name,
    ifnull(initcap(egc_talent_name),'None') as egc_talent_name,
    ifnull(trello_id,'None') as trello_id,
    ifnull(iff(contains(asset_type,'campaign'),'Campaign',initcap(asset_type)),'None') as asset_type,
    ifnull(asset_size,'None') as asset_size,
    ifnull(creative_concept,'None') as creative_concept,
    ifnull(test_name,'None') as test_name,
    ifnull(platform,'None') as platform,
    iff(sku1 = 'x' or lower(sku1)='completeme','None',ifnull(upper(sku1),'None')) as SKU1,
    ifnull(sku2,'None') as SKU2,
    ifnull(sku3,'None') as SKU3,
    ifnull(sku4,'None') as SKU4,
    ifnull(sku5,'None') as SKU5,
    ifnull(initcap(merchandise_type),'None') as merchandise_type,
    ifnull(initcap(promo_type),'None') as promo_type,
    iff(contains(number_of_styles_shown,'10'),'10+',ifnull(number_of_styles_shown,'0')) as number_of_styles_shown,
    ifnull(initcap(rtrim(logo)),'None') as logo,
    ifnull(offer, 'None') as offer,
    ifnull(initcap(offer_timing),'None') as offer_format,
    ifnull(initcap(offer_placement),'None') as offer_placement,
    ifnull(initcap(rtrim(messaging_theme)),'None') as messaging_theme,
    ifnull(initcap(product_type),'None') as product_type,
    ifnull(background,'None') as background,
    ifnull(template,'None') as template,
    ifnull(shot_type,'None') as shot_type,
    ifnull(font_used,'None') as font_used,
    ifnull(initcap(partner),'None') as partner,
    ifnull(jf_brand,'None') as jf_brand,


--     -- historical columns that are no longer tagged
--     tiktok_style,
--     endcard,
--     text_animated,
--     image_animated,
--     graphics_animated,
--     creative_format_template,
--     offer_type,
--     messaging_urgency,
--     messaging_question,
--     product_name_called_out,
--     price_slash_out,
--     cta,
--     -- fk brand creative dimensions that are not used by other brands
--     carousel_card_count,
--     carousel_title_card,
--     carousel_end_card,
--     carousel_contains_video,
--     background_texture,
--     background_environment,
--     footwear_type,
--     model_name,

    current_timestamp() as last_refresh_time
from _creative_dimensions
where creative_code is not null
and lower(creative_code) not ilike '%%use%%'
and lower(creative_code) not ilike '%%generator%%'
and lower(creative_code) not ilike '%%exist%%'
and lower(creative_code) not ilike '%%code%%'
and lower(Creative_code) != '';



