CREATE OR REPLACE VIEW LAKE_VIEW.GOOGLE_ADS.AD_SPEND(
    DATE,
	EXTERNAL_CUSTOMER_ID,
	ACCOUNT_DESCRIPTIVE_NAME,
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	AD_GROUP_ID,
	AD_GROUP_NAME,
	AD_ID,
	COST,
	IMPRESSIONS,
	CLICKS,
	VIDEO_VIEWS,
	VIDEO_QUARTILE_25_RATE,
	VIDEO_QUARTILE_50_RATE,
	VIDEO_QUARTILE_75_RATE,
	VIDEO_QUARTILE_100_RATE,
	CONVERSIONS,
	VIEW_THROUGH_CONVERSIONS,
	ALL_CONVERSIONS,
	AD_ID_UNIQUE,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
select DATE
        ,CUSTOMER_ID AS EXTERNAL_CUSTOMER_ID
        ,CUSTOMER_DESCRIPTIVE_NAME
        ,CAMPAIGN_ID
        ,CAMPAIGN_NAME
        ,AD_GROUP_ID
        ,AD_GROUP_NAME
        ,AD_ID
        ,COST_MICROS AS COST
        ,IMPRESSIONS
        ,CLICKS
        ,VIDEO_VIEWS
        ,VIDEO_QUARTILE_P_25_RATE AS VIDEO_QUARTILE_25_RATE
	    ,VIDEO_QUARTILE_P_50_RATE AS VIDEO_QUARTILE_50_RATE
	    ,VIDEO_QUARTILE_P_75_RATE AS VIDEO_QUARTILE_75_RATE
    	,VIDEO_QUARTILE_P_100_RATE AS VIDEO_QUARTILE_100_RATE
	    ,CONVERSIONS
    	,VIEW_THROUGH_CONVERSIONS
    	,ALL_CONVERSIONS
    	,CONCAT(AD_ID,AD_GROUP_ID) AS AD_ID_UNIQUE
    	,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_CREATE_DATETIME
        ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_UPDATE_DATETIME
from LAKE_FIVETRAN.MED_GOOGLE_ADS_V1.AD_SPEND;
