CREATE OR REPLACE VIEW LAKE_VIEW.GOOGLE_ADS.AD_CONVERSIONS(
    DATE,
	EXTERNAL_CUSTOMER_ID,
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	AD_GROUP_ID,
	AD_GROUP_NAME,
	AD_ID,
	CONVERSIONS,
	VIEW_THROUGH_CONVERSIONS,
	ALL_CONVERSIONS,
	ACCOUNT_DESCRIPTIVE_NAME,
	CONVERSION_TYPE_NAME,
	CONVERSION_TRACKER_ID,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
select DATE
        ,CUSTOMER_ID AS EXTERNAL_CUSTOMER_ID
        ,CAMPAIGN_ID
        ,CAMPAIGN_NAME
        ,AD_GROUP_ID
        ,AD_GROUP_NAME
        ,AD_ID
	    ,CONVERSIONS
    	,VIEW_THROUGH_CONVERSIONS
    	,ALL_CONVERSIONS
    	,CUSTOMER_DESCRIPTIVE_NAME AS ACCOUNT_DESCRIPTIVE_NAME
    	,CONVERSION_ACTION_NAME AS CONVERSION_TYPE_NAME
    	,CONVERSION_ACTION AS CONVERSION_TRACKER_ID
    	,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_CREATE_DATETIME
        ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_UPDATE_DATETIME
from LAKE_FIVETRAN.MED_GOOGLE_ADS_V1.AD_CONVERSIONS;
