CREATE OR REPLACE VIEW LAKE_VIEW.GOOGLE_ADS.ACCOUNT_METADATA(
	EXTERNAL_CUSTOMER_ID,
	ACCOUNTDESCRIPTIVENAME,
	ACCOUNTCURRENCYCODE,
	ACCOUNTTIMEZONE,
	CANMANAGECLIENTS,
	ISAUTOTAGGINGENABLED,
	ISTESTACCOUNT,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT ID AS EXTERNAL_CUSTOMER_ID
            ,DESCRIPTIVE_NAME AS ACCOUNTDESCRIPTIVENAME
            ,CURRENCY_CODE AS ACCOUNTCURRENCYCODE
            ,TIME_ZONE AS ACCOUNTTIMEZONE
            ,MANAGER AS CANMANAGECLIENTS
            ,AUTO_TAGGING_ENABLED AS ISAUTOTAGGINGENABLED
            ,TEST_ACCOUNT AS ISTESTACCOUNT
            ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_CREATE_DATETIME
            ,convert_timezone('America/Los_Angeles',UPDATED_AT) AS META_UPDATE_DATETIME
        FROM LAKE_FIVETRAN.MED_GOOGLE_ADS_V1.ACCOUNT_HISTORY qualify row_number() OVER (
                PARTITION BY id ORDER BY UPDATED_AT DESC
                ) = 1;
