CREATE OR REPLACE VIEW LAKE_VIEW.GOOGLE_ADS.CAMPAIGN_METADATA(
	EXTERNAL_CUSTOMER_ID,
	CAMPAIGN_ID,
	CAMPAIGN_NAME,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT CUSTOMER_ID AS EXTERNAL_CUSTOMER_ID
            ,ID AS CAMPAIGN_ID
            ,NAME AS CAMPAIGN_NAME
            ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_CREATE_DATETIME
            ,convert_timezone('America/Los_Angeles',UPDATED_AT) AS META_UPDATE_DATETIME
        FROM LAKE_FIVETRAN.MED_GOOGLE_ADS_V1.CAMPAIGN_HISTORY qualify row_number() OVER (
                PARTITION BY id ORDER BY UPDATED_AT DESC
                ) = 1;
