CREATE OR REPLACE VIEW LAKE_VIEW.GOOGLE_ADS.AD_GROUP_METADATA(
	AD_GROUP_ID,
	CAMPAIGN_ID,
	AD_GROUP_NAME,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT ID AS AD_GROUP_ID
            ,CAMPAIGN_ID
            ,NAME AS AD_GROUP_NAME
            ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_CREATE_DATETIME
            ,convert_timezone('America/Los_Angeles',UPDATED_AT) AS META_UPDATE_DATETIME
        FROM LAKE_FIVETRAN.MED_GOOGLE_ADS_V1.AD_GROUP_HISTORY qualify row_number() OVER (
                PARTITION BY id ORDER BY UPDATED_AT DESC
                ) = 1;
