CREATE OR REPLACE VIEW LAKE_VIEW.GOOGLE_ADS.AD_METADATA(
    AD_ID,
	AD_GROUP_ID,
	IMAGE_CREATIVE_NAME,
	AD_TYPE,
	STATUS,
	AD_ID_UNIQUE,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT ID AS AD_ID
            ,AD_GROUP_ID
            ,NAME AS IMAGE_CREATIVE_NAME
            ,TYPE AS AD_TYPE
            ,STATUS
            ,CONCAT(AD_ID,AD_GROUP_ID) AS AD_ID_UNIQUE
            ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_CREATE_DATETIME
            ,convert_timezone('America/Los_Angeles',UPDATED_AT) AS META_UPDATE_DATETIME
        FROM LAKE_FIVETRAN.MED_GOOGLE_ADS_V1.AD_HISTORY qualify row_number() OVER (
                PARTITION BY ID,AD_GROUP_ID ORDER BY UPDATED_AT DESC
                ) = 1;
