CREATE OR REPLACE VIEW LAKE_VIEW.GOOGLE_ADS.LABEL(
	ID,
	NAME,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT ID
            ,NAME
            ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_CREATE_DATETIME
            ,convert_timezone('America/Los_Angeles',_FIVETRAN_SYNCED) AS META_UPDATE_DATETIME
        FROM LAKE_FIVETRAN.MED_GOOGLE_ADS_V1.LABEL;
