from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultramerchant',
    schema='dbo',
    table='address',
    watermark_column='datetime_modified',
    initial_load_value='2020-01-14',
    schema_version_prefix='v2',
    column_list=[
        Column('address_id', 'INT', uniqueness=True),
        Column('customer_id', 'INT'),
        Column('firstname', 'VARCHAR(25)'),
        Column('lastname', 'VARCHAR(25)'),
        Column('name', 'VARCHAR(50)'),
        Column('company', 'VARCHAR(100)'),
        Column('address1', 'VARCHAR(50)'),
        Column('address2', 'VARCHAR(35)'),
        Column('city', 'VARCHAR(35)'),
        Column('state', 'VARCHAR(25)'),
        Column('zip', 'VARCHAR(25)'),
        Column('country_code', 'VARCHAR(2)'),
        Column('phone', 'VARCHAR(25)'),
        Column('us_phone_areacode', 'VARCHAR(3)'),
        Column('us_phone_prefix', 'VARCHAR(3)'),
        Column('us_phone_linenumber', 'VARCHAR(4)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('is_validated', 'INT'),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('phone_digits', 'VARCHAR(25)'),
        Column('address_hash', 'BINARY(20)'),
        Column('address3', 'VARCHAR(255)'),
        Column('address4', 'VARCHAR(255)'),
        Column('address5', 'VARCHAR(255)'),
        Column('address6', 'VARCHAR(255)'),
        Column('address7', 'VARCHAR(255)'),
        Column('address8', 'VARCHAR(255)'),
        Column('address_type_id', 'INT'),
        Column('email', 'VARCHAR(75)'),
        Column('is_customer_validated', 'INT'),
    ],
)
