from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultramerchant",
    schema="dbo",
    table="cart_line",
    watermark_column="datetime_modified",
    schema_version_prefix="v3",
    column_list=[
        Column("cart_line_id", "INT", uniqueness=True),
        Column("cart_id", "INT"),
        Column("product_id", "INT"),
        Column("offer_id", "INT"),
        Column("pricing_option_id", "INT"),
        Column("product_type_id", "INT"),
        Column("retail_unit_price", "NUMBER(19, 4)"),
        Column("purchase_unit_price", "NUMBER(19, 4)"),
        Column("unit_price_adjustment", "NUMBER(19, 4)"),
        Column("shipping_price", "NUMBER(19, 4)"),
        Column("unit_discount", "NUMBER(19, 4)"),
        Column("quantity", "INT"),
        Column("extended_shipping_price", "NUMBER(19, 4)"),
        Column("extended_price", "NUMBER(19, 4)"),
        Column("autoship_frequency_id", "INT"),
        Column("autoship_quantity", "INT"),
        Column("is_multipay", "INT"),
        Column("group_key", "VARCHAR(50)"),
        Column("exclude_from_discounts", "INT"),
        Column("lpn_code", "VARCHAR(255)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("normal_unit_price", "NUMBER(19, 4)"),
        Column("tokens_applied", "INT"),
    ],
)
