from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultramerchant',
    schema='dbo',
    table='cash_register_log',
    watermark_column='datetime_modified',
    schema_version_prefix='v2',
    column_list=[
        Column('cash_register_log_id', 'INT', uniqueness=True),
        Column('cash_register_id', 'INT'),
        Column('cash_register_eod_id', 'INT'),
        Column('store_id', 'INT'),
        Column('open_amount', 'NUMBER(19, 4)'),
        Column('open_administrator_id', 'INT'),
        Column('float_amount', 'NUMBER(19, 4)'),
        Column('sales_amount', 'NUMBER(19, 4)'),
        Column('sales_count', 'INT'),
        Column('refund_amount', 'NUMBER(19, 4)'),
        Column('refund_count', 'INT'),
        Column('expected_amount', 'NUMBER(19, 4)'),
        Column('first_count_amount', 'NUMBER(19, 4)'),
        Column('first_count_variance_amount', 'NUMBER(19, 4)'),
        Column('first_count_administrator_id', 'INT'),
        Column('first_count_cash_register_disposition_id', 'INT'),
        Column('second_count_amount', 'NUMBER(19, 4)'),
        Column('second_count_variance_amount', 'NUMBER(19, 4)'),
        Column('second_count_administrator_id', 'INT'),
        Column('second_count_cash_register_disposition_id', 'INT'),
        Column('close_count', 'INT'),
        Column('close_amount', 'NUMBER(19, 4)'),
        Column('close_float_amount', 'NUMBER(19, 4)'),
        Column('close_variance_amount', 'NUMBER(19, 4)'),
        Column('close_administrator_id', 'INT'),
        Column('close_cash_register_disposition_id', 'INT'),
        Column('close_comment', 'VARCHAR(8000)'),
        Column('datetime_opened', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_first_count', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_second_count', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_closed', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('statuscode', 'INT'),
    ],
)
