from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultramerchant",
    schema="dbo",
    table="cdr_smartaction",
    watermark_column="datetime_modified",
    schema_version_prefix="v2",
    column_list=[
        Column("cdr_smartaction_id", "INT", uniqueness=True),
        Column("call_id", "VARCHAR(255)"),
        Column("contact_id", "VARCHAR(255)"),
        Column("customer_id", "VARCHAR(255)"),
        Column("ani", "VARCHAR(255)"),
        Column("dnis", "VARCHAR(255)"),
        Column("auth_type", "VARCHAR(255)"),
        Column("ani_match", "VARCHAR(255)"),
        Column("datetime_start", "TIMESTAMP_NTZ(3)"),
        Column("datetime_end", "TIMESTAMP_NTZ(3)"),
        Column("seconds_total", "INT"),
        Column("date_key", "VARCHAR(255)"),
        Column("time_key", "VARCHAR(255)"),
        Column("call_source_key", "VARCHAR(255)"),
        Column("call_result_key", "VARCHAR(255)"),
        Column("open_intent_key", "VARCHAR(255)"),
        Column("transfer_reason_key", "VARCHAR(255)"),
        Column("lob", "VARCHAR(255)"),
        Column("order_status", "VARCHAR(255)"),
        Column("membership_save_offer", "VARCHAR(255)"),
        Column("transfer_code", "VARCHAR(255)"),
        Column("secondary_intent", "VARCHAR(255)"),
        Column("last_intent", "VARCHAR(255)"),
        Column("order_number", "VARCHAR(255)"),
        Column("allow_cancel_after_save", "VARCHAR(255)"),
        Column("allow_cancel_membership", "VARCHAR(255)"),
        Column("allow_skip", "VARCHAR(255)"),
        Column("can_skip", "VARCHAR(255)"),
        Column("allow_courtesy_refund", "VARCHAR(255)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("ab_test_1", "VARCHAR(255)"),
        Column("account_authenticated", "VARCHAR(255)"),
        Column("overall_intents", "VARCHAR(255)"),
        Column("call_outcome", "VARCHAR(255)"),
    ],
)
