from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultramerchant",
    schema="dbo",
    table="dm_site",
    watermark_column="datetime_modified",
    schema_version_prefix="v3",
    column_list=[
        Column("dm_site_id", "INT", uniqueness=True),
        Column("store_group_id", "INT"),
        Column("store_id", "INT"),
        Column("offer_category_id", "INT"),
        Column("offer_id", "INT"),
        Column("cart_derivative_id", "INT"),
        Column("dm_site_type_id", "INT"),
        Column("label", "VARCHAR(100)"),
        Column("description", "VARCHAR(255)"),
        Column("title", "VARCHAR(255)"),
        Column("css_file", "VARCHAR(255)"),
        Column("js_file", "VARCHAR(255)"),
        Column("html_header", "VARCHAR"),
        Column("html_footer", "VARCHAR"),
        Column("html_home", "VARCHAR"),
        Column("redirect_dm_gateway_id", "INT"),
        Column("redirect_url", "VARCHAR(255)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("statuscode", "INT"),
        Column("site_asset", "VARCHAR(100)"),
        Column("cdn_link", "VARCHAR(255)"),
        Column("cdn_content_datetime", "TIMESTAMP_NTZ(3)"),
    ],
)
