from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultramerchant',
    schema='dbo',
    table='gift_certificate',
    watermark_column='datetime_modified',
    schema_version_prefix='v2',
    column_list=[
        Column('gift_certificate_id', 'INT', uniqueness=True),
        Column('store_group_id', 'INT'),
        Column('gift_certificate_batch_id', 'INT'),
        Column('cross_promo_id', 'INT'),
        Column('membership_plan_id', 'INT'),
        Column('order_id', 'INT'),
        Column('customer_id', 'INT'),
        Column('gift_certificate_type_id', 'INT'),
        Column('recipient_email', 'VARCHAR(75)'),
        Column('recipient_firstname', 'VARCHAR(25)'),
        Column('recipient_lastname', 'VARCHAR(25)'),
        Column('recipient_address_id', 'INT'),
        Column('code', 'VARCHAR(25)'),
        Column('amount', 'NUMBER(19, 4)'),
        Column('balance', 'NUMBER(19, 4)'),
        Column('shipping_allowed', 'INT'),
        Column('single_use', 'INT'),
        Column('min_subtotal', 'NUMBER(19, 4)'),
        Column('comment', 'VARCHAR(255)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('date_expires', 'TIMESTAMP_NTZ(0)'),
        Column('statuscode', 'INT'),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('currency_code', 'VARCHAR(3)'),
    ],
)
