from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultramerchant',
    schema='dbo',
    table='membership_plan',
    watermark_column='datetime_added',
    schema_version_prefix='v3',
    column_list=[
        Column('membership_plan_id', 'INT', uniqueness=True),
        Column('store_group_id', 'INT'),
        Column('store_id', 'INT'),
        Column('membership_type_id', 'INT'),
        Column('product_category_id', 'INT'),
        Column('membership_product_id', 'INT'),
        Column('default_membership_reward_plan_id', 'INT'),
        Column('default_membership_recommendation_method_id', 'INT'),
        Column('default_shipping_option_id', 'INT'),
        Column('default_membership_team_id', 'INT'),
        Column('period_type', 'VARCHAR(25)'),
        Column('label', 'VARCHAR(50)'),
        Column('description', 'VARCHAR(2000)'),
        Column('price', 'NUMBER(19, 4)'),
        Column('max_prepaid_credits', 'INT'),
        Column('recommendation_request_extension_days', 'INT'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('active', 'INT'),
        Column('membership_postreg_type_id', 'INT'),
        Column('default_membership_invitation_incentive_id', 'INT'),
        Column('default_personality_type_tag_id', 'INT'),
        Column('default_billing_day', 'INT'),
        Column('default_trial_period_days', 'INT'),
        Column('allow_credit_for_fee', 'INT'),
        Column('default_membership_brand_id', 'INT'),
    ],
)
