from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultramerchant',
    schema='dbo',
    table='membership',
    watermark_column='datetime_modified',
    initial_load_value='2020-01-12',
    schema_version_prefix='v3',
    column_list=[
        Column('membership_id', 'INT', uniqueness=True),
        Column('customer_id', 'INT'),
        Column('store_id', 'INT'),
        Column('membership_type_id', 'INT'),
        Column('membership_plan_id', 'INT'),
        Column('membership_completion_method_id', 'INT'),
        Column('membership_signup_id', 'INT'),
        Column('membership_reward_plan_id', 'INT'),
        Column('order_id', 'INT'),
        Column('order_tracking_id', 'INT'),
        Column('discount_id', 'INT'),
        Column('shipping_option_id', 'INT'),
        Column('offer_id', 'INT'),
        Column('shipping_address_id', 'INT'),
        Column('payment_method', 'VARCHAR(25)'),
        Column('payment_object_id', 'INT'),
        Column('payment_option_id', 'INT'),
        Column('current_membership_recommendation_id', 'INT'),
        Column('current_period_id', 'INT'),
        Column('next_period_id', 'INT'),
        Column('membership_level_id', 'INT'),
        Column('membership_team_id', 'INT'),
        Column('price', 'NUMBER(19, 4)'),
        Column('max_prepaid_credits', 'INT'),
        Column('date_added', 'TIMESTAMP_NTZ(0)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('date_next_scheduled', 'TIMESTAMP_NTZ(0)'),
        Column('datetime_activated', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_cancelled', 'TIMESTAMP_NTZ(3)'),
        Column('date_expires', 'TIMESTAMP_NTZ(0)'),
        Column('statuscode', 'INT'),
        Column('membership_reward_tier_id', 'INT'),
        Column('date_reward_tier_recalculate', 'TIMESTAMP_NTZ(0)'),
        Column('date_reward_tier_updated', 'TIMESTAMP_NTZ(0)'),
        Column('billing_month', 'INT'),
        Column('billing_day', 'INT'),
        Column('membership_brand_id', 'INT'),
    ],
)
