from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultramerchant',
    schema='dbo',
    table='order_line',
    schema_version_prefix='v6',
    watermark_column='datetime_modified',
    column_list=[
        Column('order_line_id', 'INT', uniqueness=True),
        Column('order_id', 'INT'),
        Column('product_id', 'INT'),
        Column('offer_id', 'INT'),
        Column('pricing_option_id', 'INT'),
        Column('product_type_id', 'INT'),
        Column('item_id', 'INT'),
        Column('retail_unit_price', 'NUMBER(19, 4)'),
        Column('purchase_unit_price', 'NUMBER(19, 4)'),
        Column('unit_price_adjustment', 'NUMBER(19, 4)'),
        Column('shipping_price', 'NUMBER(19, 4)'),
        Column('unit_discount', 'DOUBLE'),
        Column('unit_cost', 'DOUBLE'),
        Column('quantity', 'INT'),
        Column('extended_shipping_price', 'NUMBER(19, 4)'),
        Column('extended_price', 'NUMBER(19, 4)'),
        Column('autoship_frequency_id', 'INT'),
        Column('autoship_quantity', 'INT'),
        Column('is_multipay', 'INT'),
        Column('statuscode', 'INT'),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('group_key', 'VARCHAR(50)'),
        Column('lpn_code', 'VARCHAR(255)'),
        Column('datetime_third_party_subscription_renews', 'TIMESTAMP_NTZ(3)'),
        Column('warehouse_id', 'INT'),
        Column('normal_unit_price', 'NUMBER(19, 4)'),
        Column('tokens_applied', 'INT'),
        Column('token_price_difference', 'NUMBER(19, 4)'),
        Column('custom_text', 'VARCHAR(50)'),
        Column('member_unit_price', 'NUMBER(19, 4)'),
        Column('sub_group_key', 'VARCHAR(50)'),
        Column('parent_order_line_id', 'INT'),
    ],
)
