from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultramerchant',
    schema='dbo',
    table='payment_transaction_creditcard',
    watermark_column='datetime_modified',
    initial_load_value='2020-01-12',
    schema_version_prefix='v2',
    column_list=[
        Column('payment_transaction_id', 'INT', uniqueness=True),
        Column('order_id', 'INT'),
        Column('creditcard_id', 'INT'),
        Column('address_id', 'INT'),
        Column('gateway_id', 'INT'),
        Column('gateway_account_id', 'INT'),
        Column('session_id', 'INT'),
        Column('original_payment_transaction_id', 'INT'),
        Column('transaction_type', 'VARCHAR(25)'),
        Column('gateway_name', 'VARCHAR(25)'),
        Column('gateway_account', 'VARCHAR(25)'),
        Column('gateway_api_version', 'VARCHAR(10)'),
        Column('amount', 'NUMBER(19, 4)'),
        Column('request_transaction_id', 'VARCHAR(50)'),
        Column('request_auth_code', 'VARCHAR(50)'),
        Column('response_transaction_id', 'VARCHAR(50)'),
        Column('response_auth_code', 'VARCHAR(50)'),
        Column('response_result_code', 'VARCHAR(25)'),
        Column('response_result_subcode', 'VARCHAR(25)'),
        Column('response_result_text', 'VARCHAR(50)'),
        Column('response_avs_code', 'VARCHAR(25)'),
        Column('response_card_code', 'VARCHAR(25)'),
        Column('response_cavv', 'VARCHAR(25)'),
        Column('response_reason_code', 'VARCHAR(50)'),
        Column('response_reason_text', 'VARCHAR(255)'),
        Column('response_latency', 'INT'),
        Column('response_data_1', 'VARCHAR(50)'),
        Column('response_data_2', 'VARCHAR(25)'),
        Column('response_data_3', 'VARCHAR(25)'),
        Column('ip', 'VARCHAR(15)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('statuscode', 'INT'),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('order_source', 'VARCHAR(25)'),
        Column('processing_type', 'VARCHAR(25)'),
        Column('request_network_transaction_id', 'VARCHAR(50)'),
        Column('response_network_transaction_id', 'VARCHAR(50)'),
    ],
)
