from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultramerchant",
    schema="dbo",
    schema_version_prefix="v4",
    table="product",
    watermark_column="datetime_modified",
    column_list=[
        Column("product_id", "INT", uniqueness=True),
        Column("master_product_id", "INT"),
        Column("store_group_id", "INT"),
        Column("item_id", "INT"),
        Column("packaging_item_id", "INT"),
        Column("product_type_id", "INT"),
        Column("brand_id", "INT"),
        Column("brand_line_tag_id", "INT"),
        Column("manufacturer_id", "INT"),
        Column("vendor_delivery_type_id", "INT"),
        Column("is_master", "INT"),
        Column("option_signature", "VARCHAR(100)"),
        Column("label", "VARCHAR(100)"),
        Column("alias", "VARCHAR(100)"),
        Column("group_code", "VARCHAR(50)"),
        Column("short_description", "VARCHAR(255)"),
        Column("medium_description", "VARCHAR(2000)"),
        Column("long_description", "VARCHAR"),
        Column("meta_keywords", "VARCHAR(255)"),
        Column("meta_description", "VARCHAR(255)"),
        Column("default_store_id", "INT"),
        Column("default_pricing_id", "INT"),
        Column("default_product_category_id", "INT"),
        Column("default_autoship_frequency_id", "INT"),
        Column("default_warehouse_id", "INT"),
        Column("retail_pricing_id", "INT"),
        Column("sale_pricing_id", "INT"),
        Column("full_image_content_id", "INT"),
        Column("thumbnail_image_content_id", "INT"),
        Column("retail_unit_price", "NUMBER(19, 4)"),
        Column("measurement", "DOUBLE"),
        Column("measurement_unit", "VARCHAR(25)"),
        Column("usage_life_days", "INT"),
        Column("is_taxable", "INT"),
        Column("is_dangerous_goods", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("date_expected", "TIMESTAMP_NTZ(0)"),
        Column("date_sale_expires", "TIMESTAMP_NTZ(0)"),
        Column("statuscode", "INT"),
        Column("product_returnable", "BOOLEAN"),
        Column("active", "INT"),
        Column("vip_variant_pricing_id_1", "INT"),
        Column("vip_variant_pricing_id_2", "INT"),
        Column("vip_variant_pricing_id_3", "INT"),
        Column("datetime_preorder_expires", "TIMESTAMP_NTZ(3)"),
        Column("token_redemption_quantity", "INT"),
        Column("sum_pricing", "INT"),
        Column("membership_brand_id", "INT"),
        Column("is_token", "INT"),
    ],
)
