from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultramerchant",
    schema="dbo",
    table="rma_label",
    watermark_column="datetime_modified",
    initial_load_value="2020-01-14",
    fetch_batch_size=5000,
    schema_version_prefix="v2",
    column_list=[
        Column("rma_label_id", "INT", uniqueness=True),
        Column("rma_id", "INT"),
        Column("rma_label_provider_id", "INT"),
        Column("tracking_number", "VARCHAR(50)"),
        Column("tracking_url", "VARCHAR(255)"),
        Column("carrier_tracking_number", "VARCHAR(50)"),
        Column("image_url", "VARCHAR(255)"),
        Column("image_data", "VARCHAR"),
        Column("carrier", "VARCHAR(25)"),
        Column("billed_weight", "DOUBLE"),
        Column("zone", "INT"),
        Column("base_cost", "NUMBER(19, 4)"),
        Column("total_fees", "NUMBER(19, 4)"),
        Column("fuel_surcharge", "NUMBER(19, 4)"),
        Column("total_cost", "NUMBER(19, 4)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_first_scanned", "TIMESTAMP_NTZ(3)"),
        Column("datetime_last_scanned", "TIMESTAMP_NTZ(3)"),
        Column("date_delivery_expected", "TIMESTAMP_NTZ(0)"),
        Column("date_delivered", "TIMESTAMP_NTZ(0)"),
        Column("statuscode", "INT"),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
    ],
)
