from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultramerchant",
    schema="dbo",
    table="store_group",
    watermark_column="datetime_modified",
    strict_inequality=True,
    schema_version_prefix="v2",
    column_list=[
        Column("store_group_id", "INT", uniqueness=True),
        Column("master_store_group_id", "INT"),
        Column("company_id", "INT"),
        Column("default_autoship_discount_matrix_id", "INT"),
        Column("default_warehouse_id", "INT"),
        Column("label", "VARCHAR(100)"),
        Column("gateway_base_url", "VARCHAR(128)"),
        Column("billing_retry_schedule_id", "INT"),
        Column("free_item_order_shipping_option_id", "INT"),
        Column("trial_grace_period_days", "INT"),
        Column("autoship_min_days_since_last", "INT"),
        Column("autoship_allow_master_products", "INT"),
        Column("defer_gift_certificate_code_allocation", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("hash_passwords", "INT"),
        Column("date_format", "VARCHAR(25)"),
        Column("force_cart_line_quantity_one", "INT"),
        Column("default_ph_method", "VARCHAR(50)"),
        Column("default_language_id", "INT"),
        Column("resource_bundle_id", "INT"),
        Column("timezone_id", "INT"),
        Column("currency_code", "VARCHAR(3)"),
        Column("country_code", "VARCHAR(5)"),
        Column("language_code", "VARCHAR(2)"),
        Column("size_system_code", "VARCHAR(4)"),
        Column("active", "INT"),
    ],
)
