CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_SXF_SAVAGE_SHOWROOM AS
SELECT COLOR_SKU
	,SAVAGE_SHOWROOM::date as SAVAGE_SHOWROOM
	,SAVAGE_SHOWROOM_REASON
	,REORDER_1_BRAND_SHOWROOM::date as REORDER_1_BRAND_SHOWROOM
	,REORDER_1_BRAND_SHOWROOM_REASON
	,REORDER_2_BRAND_SHOWROOM::date as REORDER_2_BRAND_SHOWROOM
	,REORDER_2_BRAND_SHOWROOM_REASON
	,REORDER_3_BRAND_SHOWROOM::date as REORDER_3_BRAND_SHOWROOM
	,REORDER_3_BRAND_SHOWROOM_REASON
	,REORDER_4_BRAND_SHOWROOM::date as REORDER_4_BRAND_SHOWROOM
	,REORDER_4_BRAND_SHOWROOM_REASON
	,REORDER_5_BRAND_SHOWROOM::date as REORDER_5_BRAND_SHOWROOM
	,REORDER_5_BRAND_SHOWROOM_REASON
	,REORDER_6_BRAND_SHOWROOM::date as REORDER_6_BRAND_SHOWROOM
	,REORDER_6_BRAND_SHOWROOM_REASON
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM LAKE_FIVETRAN.MED_SHAREPOINT_ACQUISITION_V1.style_master_merch_inputs_Savage_X_Showroom;
