CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_SELECTOR_PROMO AS
select BUSINESS_UNIT_ABBR
,PROMO
,PROMO_INSERT
,ACTIVE_IN_GENERATOR
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from lake_fivetran.med_sharepoint_admin_V1.naming_convention_selections_selector_promo;
