create or replace view LAKE_VIEW.SHAREPOINT.MED_HDYH_MAPPING(
	HDYH_VALUE,
	CHANNEL,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT HDYH_ANSWER AS HDYH_VALUE
  ,CHANNEL_DROPDOWN_ AS CHANNEL
  ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
  ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM LAKE_FIVETRAN.MED_SHAREPOINT_ADMIN_V1.HDYH_MAPPING_HDYH_MAPPING;
