CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_INFLUENCER_MASTER_ORGANIC_SPEND_DIMENSIONS_SCB AS
SELECT DISTINCT PARTNER_OR_IN_HOUSE as PARTNER_OR_INHOUSE
    ,POST_LINK as LINK_TO_POST
    ,ETHNICITY as POST_ETHNICITY
    ,BUSINESS_UNIT as BUSINESS_UNIT_ABBR
    ,CREATOR_IQ_POST_ID_OR_IMPACT_RADIUS_SHARED_ID as POST_ID
    ,WHITELIST_ACCESS_END_DATE as WHITELIST_DATE_END
    ,CUSTOM_LANDING_PAGE
    ,CONTENT_USAGE_RIGHTS_ as CONTENT_USAGE_RIGHTS
    ,WHITELIST_ACCESS_DATE_GRANTED as WHITELIST_DATE_START
    ,MEDIA_PARTNER_ID_IMPACT_RADIUS_ as MEDIA_PARTNER_ID
    ,PRODUCT_SHIPPING_COST as COGS
    ,STYLE_QUIZ_MENTION as POST_MENTIONS_STYLE_QUIZ
    ,PUBLISHER_ID_CREATOR_IQ_ as PUBLISHER_ID
    ,SPEND_START_DATE::date as SPEND_DATE_START
    ,SPEND_END_DATE::date as SPEND_DATE_END
    ,CREATOR_IQ_CAMPAIGN_ID as CAMPAIGN_ID
    ,IS_PLUS_ as POST_PLUS_SIZE
    ,PRODUCTION_QUALITY as POST_PRODUCTION_QUALITY
    ,MENTIONS_COMPETITOR_COMPARISON as POST_COMPETITOR_COMPARISON
    ,SPEND_COUNTRY
    ,UPFRONT_COST
    ,INFLUENCER_CLASSIFICATION
    ,LENGTH as POST_LENGTH
    ,DEDICATED_VS_INTEGRATED as POST_DEDICATED
    ,CPA_REPORT_INPUT
    ,TYPE_OF_COLLECTION as COLLECTION_TYPE
    ,CREATOR_NAME
    ,PAYMENT_METHOD
    ,ADDITIONAL_MEMBERSHIP_EDUCATION as POST_MEMBERSHIP_EDUCATION
    ,POST_STATUS
    ,POST_PLATFORM
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM LAKE_FIVETRAN.MED_SHAREPOINT_INFLUENCER_V1.INFLUENCER_TRACKER_MASTER_G_Influencer_Tracker_scb_NA
WHERE CREATOR_NAME <> 'Creator Name'
    AND CREATOR_NAME <> 'no spaces'
    AND CREATOR_NAME <> 'Creator, Business Unit & County'
    and SPEND_START_DATE<>'Spend Details';
