CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_fabletics_budget_and_forecast as
select DISTINCT BOM_VIPS
,ACTIVATING_NET_REVENUE
,FABLETICS_BUDGET_AND_FORECAST_KEY
,ACTIVATING_DISCOUNT
,MEDIA_SPEND
,BUSINESS_UNIT
,LEADS
,D1_VIPS
,ACTIVATING_REVENUE
,DATE
,TOTAL_VIPS_ON_DATE
,ACTIVATING_ORDER_COUNT
,AGED_LEAD_CONVERSIONS
,ACTIVATING_SUBTOTAL
,EOM_VIPS
,REQUESTOR_NAME
,CURRENCY
,ACTIVATING_UNITS
,UNIQUENESS
,COUNTRY
,M1_VIPS
,ACTIVATING_GROSS_MARGIN
,VERSION
,CANCELS
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from LAKE_FIVETRAN.MED_SHAREPOINT_ACQUISITION_V1.ACQUISITION_TARGETS_INDIVIDUAL_LOCAL_fabletics_forcast

UNION ALL

select DISTINCT BOM_VIPS
,ACTIVATING_NET_REVENUE
,FABLETICS_BUDGET_AND_FORECAST_KEY
,ACTIVATING_DISCOUNT
,MEDIA_SPEND
,BUSINESS_UNIT
,LEADS
,D1_VIPS
,ACTIVATING_REVENUE
,DATE
,TOTAL_VIPS_ON_DATE
,ACTIVATING_ORDER_COUNT
,AGED_LEAD_CONVERSIONS
,ACTIVATING_SUBTOTAL
,EOM_VIPS
,REQUESTOR_NAME
,CURRENCY
,ACTIVATING_UNITS
,UNIQUENESS
,COUNTRY
,M1_VIPS
,ACTIVATING_GROSS_MARGIN
,VERSION
,CANCELS
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from LAKE_FIVETRAN.MED_SHAREPOINT_ACQUISITION_V1.ACQUISITION_TARGETS_INDIVIDUAL_LOCAL_fabletics_BUDGET;
