CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_SX_CREATIVE_DIMENSIONS AS
select distinct TEST_NAME
    ,AD_TYPE
    ,PLATFORM_OR_CREATIVE_FORMAT
    ,DATE_CREATED_MMYY_ as DATE_CREATED
    ,SKU_5 SKU5
    ,VERSION
    ,ASSET_TYPE
    ,SKU_4 SKU4
    ,NUMBER_OF_STYLES_SHOWN
    ,VIDEO_LENGTH
    ,SKU_1 SKU1
    ,SKU_2 SKU2
    ,MESSAGING_THEME
    ,STILL_LIFE_ANGLE_SHOT
    ,MODEL_ACTION
    ,PRODUCT_TYPE
    ,MERCHANDISE_TYPE
    ,LOGO
    ,OFFER_PROMO
    ,SKU_3 SKU3
    ,CREATIVE_CODE
    ,FIRST_3_SECONDS_VISUAL
    ,DESIGNER_INITIALS
    ,MISSY_CURVY as MISSY_OR_CURVY
    ,OFFER_PLACEMENT
    ,ASSET_SIZE
    ,AUDIO
    ,MODEL_PLACEMENT
    ,INFLUENCER_NAME
    ,GENDER
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from LAKE_FIVETRAN.MED_SHAREPOINT_NAMING_GENERATORS_V1.SXF_CREATIVE_DIMENSIONS_GENERATOR_SXF_CREATIVE_ASSET_GENERATOR
where CREATIVE_CODE <> 'Creative Code' and CREATIVE_CODE not ilike '%SAVAGE X FENTY CREATIVE NAMING GENERATOR%';
