CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_IMPACT_INFL_HDYH_MAPPING AS
select MEDIA_PARTNER_ID
,HDYH
,BRAND
,COUNTRY
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from LAKE_FIVETRAN.MED_SHAREPOINT_INFLUENCER_V1.INFLUENCER_SPREADHSEET_NEW_INFLHDYHMAPPING;
