CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_FL_CREATIVE_DIMENSIONS AS
SELECT creative_code,
       designer_initials,
       date_created_mmyy_ date_created,
       ad_type,
       video_length,
       audio,
       first_3_seconds_visual,
       first_3_seconds_text,
       model_action,
       model_placement,
       gender,
       still_life_angle_shot,
       influencer_name,
       ugc_talent_name,
       egc_talent_name,
       trello_id,
       asset_type,
       asset_size,
       adset_creative_concept,
       test_variants_videos,
       platform_or_creative_format,
       sku_1 sku1,
       sku_2 sku2,
       sku_3 sku3,
       sku_4 sku4,
       sku_5 sku5,
       merchandise_type,
       number_of_styles_shown,
       logo,
       offer_promo,
       offer_timing,
       offer_placement,
       messaging_theme,
       _fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime,
       _fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.med_sharepoint_naming_generators_v1.fl_creative_dimensions_generator_fl_creative_asset_generator
WHERE _line > 1;
