CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_PODCAST_SPEND AS
SELECT MEDIA_VENDOR_NAME
,BUSINESS_UNIT
,COUNTRY
,STORE_ID
,AIR_DATE::date as AIR_DATE
,UPDATED_AIR_DATE::date as UPDATED_AIR_DATE
,PLACEMENT
,SPEND
,IMPRESSIONS
,NEVER_AIRED
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM LAKE_FIVETRAN.MED_SHAREPOINT_SPEND_V1.podcast_spend_sheet_1;
