CREATE VIEW IF NOT EXISTS LAKE_VIEW.SHAREPOINT.MED_INFLUENCER_MASTER_ORGANIC_SPEND_DIMENSIONS_FL AS
SELECT DISTINCT CREATOR_NAME
    ,BUSINESS_UNIT as BUSINESS_UNIT_ABBR
    ,SPEND_COUNTRY
    ,INFLUENCER_CLASSIFICATION
    ,PARTNER_OR_IN_HOUSE as PARTNER_OR_INHOUSE
    ,MEDIA_PARTNER_ID_IMPACT_RADIUS_ as MEDIA_PARTNER_ID
    ,PUBLISHER_ID_CREATOR_IQ_ as PUBLISHER_ID
    ,CREATOR_IQ_POST_ID_OR_IMPACT_RADIUS_SHARED_ID as POST_ID
    ,TYPE_OF_COLLECTION as COLLECTION_TYPE
    ,BUTT_REFERENCE
    ,Content as content_type
    ,POST_VIBE
    ,PRODUCT_CALLOUT
    ,AUDIENCE_BUCKET
    ,PAYMENT_METHOD
    ,CREATOR_IQ_CAMPAIGN_ID as CAMPAIGN_ID
    ,CONTENT_USAGE_RIGHTS_ as CONTENT_USAGE_RIGHTS
    ,WHITELIST_ACCESS_DATE_GRANTED as WHITELIST_DATE_START
    ,WHITELIST_ACCESS_END_DATE as WHITELIST_DATE_END
    ,SPEND_START_DATE::date as SPEND_DATE_START
    ,SPEND_END_DATE::date as SPEND_DATE_END
    ,UPFRONT_COST
    ,PRODUCT_SHIPPING_COST as COGS
    ,CPA_REPORT_INPUT
    ,POST_STATUS
    ,POST_PLATFORM
    ,CUSTOM_LANDING_PAGE
    ,POST_LINK as LINK_TO_POST
    ,LENGTH as POST_LENGTH
    ,PRODUCTION_QUALITY as POST_PRODUCTION_QUALITY
    ,ADDITIONAL_MEMBERSHIP_EDUCATION as POST_MEMBERSHIP_EDUCATION
    ,MENTIONS_COMPETITOR_COMPARISON as POST_COMPETITOR_COMPARISON
    ,STYLE_QUIZ_MENTION as POST_MENTIONS_STYLE_QUIZ
    ,IS_PLUS_ as POST_PLUS_SIZE
    ,ETHNICITY as POST_ETHNICITY
    ,DEDICATED_VS_INTEGRATED as POST_DEDICATED
    ,OFFER
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.med_sharepoint_influencer_v1.influencer_tracker_master_g_influencer_tracker_fl_eu
WHERE CREATOR_NAME <> 'Creator Name'
    AND CREATOR_NAME <> 'no spaces'
    AND CREATOR_NAME <> 'Creator, Business Unit & County'
    AND UPFRONT_COST not ilike '%#REF!%'

UNION ALL

SELECT DISTINCT CREATOR_NAME
    ,BUSINESS_UNIT as BUSINESS_UNIT_ABBR
    ,SPEND_COUNTRY
    ,INFLUENCER_CLASSIFICATION
    ,PARTNER_OR_IN_HOUSE as PARTNER_OR_INHOUSE
    ,IFF(MEDIA_PARTNER_ID_IMPACT_RADIUS_ ilike '%.0%',left(MEDIA_PARTNER_ID_IMPACT_RADIUS_,len(MEDIA_PARTNER_ID_IMPACT_RADIUS_)-2),MEDIA_PARTNER_ID_IMPACT_RADIUS_) as MEDIA_PARTNER_ID
    ,PUBLISHER_ID_CREATOR_IQ_ as PUBLISHER_ID
    ,CREATOR_IQ_POST_ID_OR_IMPACT_RADIUS_SHARED_ID as POST_ID
    ,TYPE_OF_COLLECTION as COLLECTION_TYPE
    ,BUTT_REFERENCE
    ,Content as content_type
    ,POST_VIBE
    ,PRODUCT_CALLOUT
    ,AUDIENCE_BUCKET
    ,PAYMENT_METHOD
    ,CREATOR_IQ_CAMPAIGN_ID as CAMPAIGN_ID
    ,CONTENT_USAGE_RIGHTS_ as CONTENT_USAGE_RIGHTS
    ,WHITELIST_ACCESS_DATE_GRANTED as WHITELIST_DATE_START
    ,WHITELIST_ACCESS_END_DATE as WHITELIST_DATE_END
    ,SPEND_START_DATE::date as SPEND_DATE_START
    ,SPEND_END_DATE::date as SPEND_DATE_END
    ,UPFRONT_COST
    ,PRODUCT_SHIPPING_COST as COGS
    ,CPA_REPORT_INPUT
    ,POST_STATUS
    ,POST_PLATFORM
    ,CUSTOM_LANDING_PAGE
    ,POST_LINK as LINK_TO_POST
    ,LENGTH as POST_LENGTH
    ,PRODUCTION_QUALITY as POST_PRODUCTION_QUALITY
    ,ADDITIONAL_MEMBERSHIP_EDUCATION as POST_MEMBERSHIP_EDUCATION
    ,MENTIONS_COMPETITOR_COMPARISON as POST_COMPETITOR_COMPARISON
    ,STYLE_QUIZ_MENTION as POST_MENTIONS_STYLE_QUIZ
    ,IS_PLUS_ as POST_PLUS_SIZE
    ,ETHNICITY as POST_ETHNICITY
    ,DEDICATED_VS_INTEGRATED as POST_DEDICATED
    ,OFFER
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.med_sharepoint_influencer_v1.influencer_tracker_master_g_influencer_tracker_fl_na
WHERE CREATOR_NAME <> 'Creator Name'
    AND CREATOR_NAME <> 'no spaces'
    AND CREATOR_NAME <> 'Creator, Business Unit & County'
    AND UPFRONT_COST not ilike '%#REF!%'
    ;
