CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.GFB_FK_MERCH_OUTFIT_ATTRIBUTES as (
    select
        TRY_CAST(PRODUCT_ID as NUMBER) as PRODUCT_ID,
        OUTFIT_ALIAS,
        SITE_NAME,
        TRY_CAST(VIP_RETAIL as FLOAT) as VIP_RETAIL,
        TYPE,
        GENDER,
        ACTIVE_INACTIVE,
        OUTFIT_VS_BOX_VS_PACK,
        _COMPONTENTS::VARCHAR as COMPONTENTS_NUMBER,
        ITEM_1 as ITEM1,
        ITEM_2 as ITEM2,
        ITEM_3 as ITEM3,
        ITEM_4 as ITEM4,
        ITEM_5 as ITEM5,
        ITEM_6 as ITEM6,
        ITEM_7 as ITEM7,
        ITEM_8 as ITEM8,
        TRY_CAST(TOTAL_COST_OF_OUTFIT as FLOAT) as TOTAL_COST_OF_OUTFIT,
        TRY_CAST(TOTAL_COST_OF_OUTFIT_TARIFF_ as FLOAT) as TOTAL_COST_OF_OUTFIT_TARIFF,
        TRY_CAST(OUTFIT_IMU_ as FLOAT) as OUTFIT_IMU,
        TRY_CAST(OUTFIT_IMU_TARIFF_ as FLOAT) as OUTFIT_IMU_TARIFF,
        CONTAINS_SHOES_ as CONTAINS_SHOES,
    	_fivetran_synced::TIMESTAMP_LTZ as meta_create_datetime,
        _fivetran_synced::TIMESTAMP_LTZ as meta_update_datetime
    from LAKE_FIVETRAN.JFB_OTHER_SHAREPOINT_V1.GFB_FK_MERCH_ATTRIBUTES_OUTFIT_MASTER
    where _LINE not in (0, 1, 2)
);
