CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.GSC_DHL_INVOICES AS
SELECT 'DHL' as source,
       source_name as invoice_number,
       invoice,
       sold_to_ as account_number,
       inv_posnr_,
       bol_ as bol,
       bill_ref_2_ as bill_ref_2,
       shippoint_,
       pick_up_from_,
       pudate_ as invoice_ingestion_date,
       internal_tracking_num_ as internal_tracking_num,
       customer_confirm_,
       delivery_confirm_ as invoice_tracking_number,
       address_1_ as address_1,
       address_2_ as address_2,
       city_ as city,
       state_ as state,
       zip_ as zip,
       country_ as country,
       material_or_vas_num_,
       material_or_vas_desc_ AS invoice_service_type,
       actweight_/16 as invoice_actual_weight,
       uom_actweight_,
       billweight_/16 as chargeable_weight,
       uom_bill_wgt_,
       quantity_ as quantity,
       pricing_zone_ as invoice_zone,
       charge_ as service_charge,
       zfuel_ as fuel_surcharge,
       original_del_con,
       uom_dims,
       peak_surcharge as peak_season_surcharge,
       total as total_package_cost,
       min_pickup_chg_,
       dim_height as package_height,
       dim_width as package_width,
       uom_dim_wt,
       dim_weight,
       dim_length as package_length,
       ZSC_6_CLIENT_SRD_ as nqd_surcharge,
       EXTRA_LENGTH_SURCHARGE,
       EXTRA_VOLUME_SURCHARGE,
       _modified AS meta_update_datetime,
       _file AS file_name
FROM lake_fivetran.global_apps_gsc_secondary_ingestions.dhl_invoices_v_1
WHERE _file <> 'DHL actual invoice - meta data as csv.csv';
