CREATE OR REPLACE VIEW lake_view.sharepoint.gsc_fedex_return_invoices AS
SELECT account_group,
       payer_account as account_number,
       to_date(to_varchar(invoice_month_yyyymm_),'YYYYMM') as invoice_year_month,
       opco,
       service_type,
       service_description as service_name,
       pay_type,
       to_date(shipment_date_mm_dd_yyyy_) as date_shipped,
       to_date(shipment_delivery_date_mm_dd_yyyy_) as delivery_date,
       to_varchar(shipment_tracking_number) as tracking_number,
       shipper_name,
       shipper_company_name,
       shipper_address,
       shipper_city,
       shipper_state_province,
       shipper_country_territory,
       shipper_postal_code as origin_zip,
       shipment_freight_charge_amount_usd,
       shipment_miscellaneous_charge_usd,
       shipment_duty_and_tax_charge_usd,
       shipment_discount_amount_usd,
       net_charge_amount_usd,
       pieces_in_shipment,
       shipment_rated_weight_pounds_ as billed_weight,
       original_weight_pounds_ as actual_weight,
       proof_of_delivery_recipient,
       recipient_name,
       upper(recipient_company_name) as recipient_company_name,
       upper(recipient_address) as recipient_address,
       upper(recipient_city) as recipient_city,
       recipient_state_province,
       recipient_country_territory,
       left(recipient_postal_code,5) as ship_to_zip,
       reference_notes_line_1,
       reference_notes_line_2,
       reference_notes_line_3,
       pricing_zone as zone,
       shipment_dim_flag_y_or_n_ as shipment_dim_flag,
       dimmed_height_in_ as package_height,
       dimmed_width_in_ as package_width,
       dimmed_length_in_ as package_length,
       recipient_original_address,
       recipient_original_city,
       recipient_original_state_province,
       recipient_original_postal_code,
       recipient_original_country_territory,
       shipment_declared_value_amount,
       customs_value,
       to_date(invoice_date_mm_dd_yyyy_) as invoice_date,
       invoice_number,
       domestic_intl,
       package_type,
       shipment_delivery_time_24_hours_ as shipment_delivery_time_24_hours,
       shipment_freight_charge_billed_currency,
       shipment_miscellaneous_charge_billed_currency,
       shipment_duty_and_tax_charge_billed_currency,
       shipment_discount_billed_currency,
       net_charge_billed_currency as total,
       billed_currency_code,
       exchange_rate_to_usd,
       weight_type_code,
       customer_order_number,
       _file as filename
FROM lake_fivetran.global_apps_gsc_secondary_ingestions.fedex_return_invoices_v_1;

