CREATE OR REPLACE VIEW lake_view.sharepoint.gsc_pitney_bowes_return_invoices AS
-- Old Format
SELECT fp,
       merch_name as business_unit,
       merch_id as account_number,
       invoice_id as invoice_id,
       iss_date as invoice_date,
       barcode as parcel_id,
       to_varchar(trck_id) as tracking_number,
       return_id,
       bol,
       "FROM" as from_facility,
       "TO" as to_facility,
       coalesce(sh_to,sort_code) as sort_code,
       nddate as ingestion_date,
       bil_wt as billed_weight,
       zone,
       slfee as transportation_fee,
       n as nmo_flag,
       non_mach_fee as nmo,
       b as balloon_fee_flag,
       balloon_fee,
       o as oversize_fee_flag,
       oversize_fee,
       p as prepaid_fee_flag,
       prepaid_fee,
       r as priority_fee_flag,
       priority_fee,
       c as non_continental_fee_flag,
       non_cont_fee as non_continental_fee,
       fuel_srge_fee as fuel_surcharge,
       tot_invoiced as total,
       brand_name,
       service_name,
       country_code,
       d as dimensional_surcharge_flag,
       dim_fee as dimensional_surcharge,
       m as miscellaneous_fee_flag,
       misc_fee as miscellaneous_fee,
       v as discount_flag,
       discount,
       null AS internal_tracking_number,
       null as transaction_type,
       null as origin_zip,
       null as ship_to_zip,
       null as actual_weight,
       null as package_length,
       null as package_width,
       null as package_height,
       null as volume_adjustment_amount,
       null as peak_surcharge,
       null as additional_fee_1_amount,
       null as additional_fee_2_amount,
       null as additional_fee_3_amount,
       null as tax_amount,
       _file as filename,
       'OLD FORMAT' as source
FROM LAKE_FIVETRAN.GLOBAL_APPS_GSC_SECONDARY_INGESTIONS.PITNEY_BOWES_OLD_FORMAT_RETURN_INVOICES_V_1

UNION
-- Recent Format
SELECT null as fp,
       parent_merchant_name as business_unit,
       merchant_number as account_number,
       invoice_document_number as invoice_id,
       invoice_document_date as invoice_date,
       parcel_id,
       to_varchar(carrier_parcel_id) AS tracking_number,
       return_identifier return_id,
       null as bol,
       from_facility,
       to_facility,
       sort_code,
       induction_date as ingestion_date,
       billing_weight as billed_weight,
       zone,
       transportation_fee,
       null as nmo_flag,
       non_machinable_fee as nmo,
       null as balloon_fee_flag,
       balloon_fee,
       null as oversize_fee_flag,
       oversize_fee,
       null as oversize_fee,
       prepaid_fee,
       null as priority_fee_flag,
       priority_fee,
       null as non_continental_fee_flag,
       non_continental_fee,
       fuel_surcharge,
       total,
       merchant_name as brand_name,
       service_name,
       country_code,
       null as dimensional_surcharge_flag,
       null as dimensional_surcharge,
       null as miscellaneous_fee_flag,
       miscellaneous_fee,
       null as discount_flag,
       null as discount,
       tracking_number AS internal_tracking_number,
       transaction_type,
       origin_zip,
       ship_to_zip,
       actual_weight,
       parcel_length as package_length,
       parcel_width as package_width,
       parcel_height as package_height,
       volume_adjustment_amount,
       peak_surcharge,
       additional_fee_1_amount,
       additional_fee_2_amount,
       additional_fee_3_amount,
       tax_amount,
       _file as filename,
       'RECENT FORMAT' as source
FROM LAKE_FIVETRAN.GLOBAL_APPS_GSC_SECONDARY_INGESTIONS.PITNEY_BOWES_RECENT_FORMAT_RETURN_INVOICES_V_1;

