CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_HDYH_LEGACY_MAPPING AS
SELECT HOWDIDYOUHEAR AS HDYH_VALUE
  ,REALLOCATE_BRANDSITE
  ,REALLOCATE_GATEWAY
  ,CHANNEL
  ,SUBCHANNEL
  ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
  ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.MED_SHAREPOINT_ADMIN_V1.hdyh_taxonomy_sheet_1;
