CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_YTY_CREATIVE_DIMENSIONS AS
select  PLATFORM_OR_CREATIVE_FORMAT
    ,MERCHANDISE_TYPE
    ,MODEL_PLACEMENT
    ,UGC_TALENT_NAME
    ,ASSET_SIZE
    ,ASSET_TYPE
    ,OFFER_TIMING
    ,TRELLO_ID
    ,STILL_LIFE_ANGLE_SHOT
    ,SKU_2 as SKU2
    ,FIRST_3_SECONDS_VISUAL
    ,EGC_TALENT_NAME
    ,AD_TYPE
    ,AUDIO
    ,VIDEO_LENGTH
    ,DATE_CREATED_MMYY_ as DATE_CREATED
    ,LOGO
    ,TEST_VARIANTS_VIDEOS
    ,NUMBER_OF_STYLES_SHOWN
    ,GENDER
    ,ADSET_CREATIVE_CONCEPT
    ,OFFER_PROMO
    ,SKU_1 as SKU1
    ,MESSAGING_THEME
    ,BODY_TYPE
    ,OFFER_PLACEMENT
    ,SKU_3 as SKU3
    ,FIRST_3_SECONDS_TEXT
    ,CREATIVE_CODE
    ,SKU_4 as SKU4
    ,SKU_5 as SKU5
    ,DESIGNER_INITIALS
    ,MODEL_ACTION
    ,INFLUENCER_NAME
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from LAKE_FIVETRAN.MED_SHAREPOINT_NAMING_GENERATORS_V1.YTY_CREATIVE_DIMENSIONS_GENERATOR_YTY_CREATIVE_ASSET_GENERATOR
where CREATIVE_CODE <> 'Creative Code' and CREATIVE_CODE not ilike '%YITTY CREATIVE NAMING GENERATOR%';
