CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_INFLUENCER_MASTER_ORGANIC_SPEND_DIMENSIONS_FK AS
SELECT DISTINCT PAYMENT_METHOD
,MENTIONS_COMPETITOR_COMPARISON as POST_COMPETITOR_COMPARISON
,PRODUCT_SHIPPING_COST as COGS
,MEDIA_PARTNER_ID_IMPACT_RADIUS_ as MEDIA_PARTNER_ID
,POST_PLATFORM
,TYPE_OF_COLLECTION as COLLECTION_TYPE
,PRODUCTION_QUALITY as POST_PRODUCTION_QUALITY
,CUSTOM_LANDING_PAGE
,CREATOR_IQ_CAMPAIGN_ID as CAMPAIGN_ID
,OFFER
,SPEND_END_DATE::date as spend_date_end
,SPEND_COUNTRY
,CREATOR_NAME
,CONTENT_USAGE_RIGHTS_ as CONTENT_USAGE_RIGHTS
,UPFRONT_COST
,POST_LINK as LINK_TO_POST
,ADDITIONAL_MEMBERSHIP_EDUCATION as POST_MEMBERSHIP_EDUCATION
,LENGTH as POST_LENGTH
,CPA_REPORT_INPUT
,INFLUENCER_CLASSIFICATION
,CREATOR_IQ_POST_ID_OR_IMPACT_RADIUS_SHARED_ID as POST_ID
,WHITELIST_ACCESS_DATE_GRANTED as WHITELIST_DATE_START
,WHITELIST_ACCESS_END_DATE as WHITELIST_DATE_END
,PARTNER_OR_IN_HOUSE as PARTNER_OR_INHOUSE
,ETHNICITY as POST_ETHNICITY
,BUSINESS_UNIT as BUSINESS_UNIT_ABBR
,DEDICATED_VS_INTEGRATED as POST_DEDICATED
,SPEND_START_DATE::date as SPEND_DATE_START
,IS_PLUS_ as POST_PLUS_SIZE
,STYLE_QUIZ_MENTION as POST_MENTIONS_STYLE_QUIZ
,POST_STATUS
,PUBLISHER_ID_CREATOR_IQ_ as PUBLISHER_ID
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from LAKE_FIVETRAN.MED_SHAREPOINT_INFLUENCER_V1.INFLUENCER_TRACKER_MASTER_G_INFLUENCER_TRACKER_FK_NA
WHERE CREATOR_NAME <> 'Creator Name'
        AND CREATOR_NAME <> 'no spaces'
        AND CREATOR_NAME <> 'Creator, Business Unit & County';
