CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_SXF_AD_SKU_MAPPING AS
	SELECT distinct AD_ID
		,PRODUCT_DISPLAYED
		,PRIMARY_SKU
		,SKU_2
		,SKU_3
		,SKU_4
		,SKU_5
		,SKU_6
		,NOT_COMPLETE
        ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
		,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
	FROM LAKE_FIVETRAN.MED_SHAREPOINT_ACQUISITION_V1.SXF_US_AD_SKU_TAGGING_AD_SKU_TAGGING;
