CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_SXEU_CREATIVE_DIMENSIONS(
	CREATIVE_CODE,
    DESIGNER_INITIALS,
    DATE_CREATED,
    AD_TYPE,
    VIDEO_LENGTH,
    AUDIO,
    FIRST_3_SECONDS_VISUAL,
    FIRST_3_SECONDS_TEXT,
    MODEL_PLACEMENT,
    MISSY_OR_CURVY,
    GENDER,
    FONT_TREATMENT,
    INFLUENCER_NAME,
    UGC_TALENT_NAME,
    EGC_TALENT_NAME,
    TRELLO_ID,
    ASSET_TYPE,
    ASSET_SIZE,
    ADSET_CREATIVE_CONCEPT,
    TEST_VARIANTS_VIDEOS,
	PLATFORM_OR_CREATIVE_FORMAT,
	SKU1,
	SKU2,
    SKU3,
    SKU4,
	SKU5,
    MERCHANDISE_TYPE,
	NUMBER_OF_STYLES_SHOWN,
    LOGO,
    OFFER_PROMO,
    OFFER_TIMING,
    OFFER_PLACEMENT,
	MESSAGING_THEME,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT DISTINCT
    CREATIVE_CODE
    ,DESIGNER_INITIALS
    ,DATE_CREATED_MMYY_ DATE_CREATED
    ,AD_TYPE
    ,VIDEO_LENGTH
    ,AUDIO
    ,FIRST_3_SECONDS_VISUAL
    ,FIRST_3_SECONDS_TEXT
    ,MODEL_PLACEMENT
    ,MISSY_CURVY MISSY_OR_CURVY
    ,GENDER
    ,FONT_TREATMENT
    ,INFLUENCER_NAME
    ,UGC_TALENT_NAME
    ,EGC_TALENT_NAME
    ,TRELLO_ID
    ,ASSET_TYPE
    ,ASSET_SIZE
    ,ADSET_CREATIVE_CONCEPT
    ,TEST_VARIANTS_VIDEOS
    ,PLATFORM_OR_CREATIVE_FORMAT
    ,SKU_1 SKU1
    ,SKU_2 SKU2
    ,SKU_3 SKU3
    ,SKU_4 SKU4
    ,SKU_5 SKU5
    ,MERCHANDISE_TYPE
    ,NUMBER_OF_STYLES_SHOWN
    ,LOGO
    ,OFFER_PROMO
    ,OFFER_TIMING
    ,OFFER_PLACEMENT
    ,MESSAGING_THEME
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM LAKE_FIVETRAN.MED_SHAREPOINT_NAMING_GENERATORS_V1.SXEU_CREATIVE_DIMENSIONS_GENERATOR_SXEU_CREATIVE_ASSET_GENERATOR
WHERE CREATIVE_CODE not ilike '%%Creative Code%%' and CREATIVE_CODE not ilike '%SAVAGE X FENTY EU CREATIVE NAMING GENERATOR%';
