CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_FLMEU_CREATIVE_DIMENSIONS(
	CREATIVE_CODE,
	DESIGNER_INITIALS,
	DATE_CREATED,
	AD_TYPE,
	VIDEO_LENGTH,
	AUDIO,
	FIRST_3_SECONDS_VISUAL,
	FIRST_3_SECONDS_TEXT,
	MODEL_ACTION,
	MODEL_PLACEMENT,
	GENDER,
	STILL_LIFE_ANGLE_SHOT,
	INFLUENCER_NAME,
	UGC_TALENT_NAME,
	EGC_TALENT_NAME,
	TRELLO_ID,
	ASSET_TYPE,
	ASSET_SIZE,
	ADSET_CREATIVE_CONCEPT,
	TEST_VARIANTS_VIDEOS,
	PLATFORM_OR_CREATIVE_FORMAT,
	SKU1,
	SKU2,
	SKU3,
	SKU4,
	SKU5,
	MERCHANDISE_TYPE,
	NUMBER_OF_STYLES_SHOWN,
	LOGO,
	OFFER_PROMO,
	OFFER_TIMING,
	OFFER_PLACEMENT,
    PARTNER_AGENCY,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
SELECT creative_code,
       designer_initials,
       date_created_mmyy_ as date_created,
       ad_type,
       video_length,
       audio,
       first_3_seconds_visual,
       first_3_seconds_text,
       model_action,
       model_placement,
       gender,
       still_life_angle_shot,
       influencer_name,
       ugc_talent_name,
       egc_talent_name,
       trello_id,
       asset_type,
       asset_size,
       adset_creative_concept,
       test_variants_videos,
       platform_or_creative_format,
       sku_1 sku1,
       sku_2 sku2,
       sku_3 sku3,
       sku_4 sku4,
       sku_5 sku5,
       merchandise_type,
       number_of_styles_shown,
       logo,
       offer_promo,
       offer_timing,
       offer_placement,
       partner_agency,
       _fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime,
       _fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.med_sharepoint_naming_generators_v1.flmeu_creative_dimensions_generator_flmeu_creative_asset_generator
WHERE _line > 1;
