CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_ACQUISITION_BUDGET_INDIVIDUAL_LOCAL as
SELECT business_unit,
    country,
    date::date as date,
    media_spend,
    activating_order_count,
        activating_units,
        activating_subtotal,
        activating_discount,
        activating_revenue,
        activating_net_revenue,
        activating_gross_margin,
        bom_vips,
        leads,
        d_1_vips as d1_vips,
        m_1_vips as m1_vips,
        total_vips_on_date,
        aged_lead_conversions,
        cancels,
        eom_vips,
        currency,
        version,
        requestor_name,
        uniqueness,
        _fivetran_synced::TIMESTAMP_LTZ as meta_create_datetime,
        _fivetran_synced::TIMESTAMP_LTZ as meta_update_datetime
FROM lake_fivetran.med_sharepoint_acquisition_v1.acquisition_targets_individual_local_budget;
