CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_VENDOR_FEES_MEDIA AS
SELECT STORE_COUNTRY
    ,STORE_BRAND
    ,COUNTRY
    ,STORE_ID::INT AS STORE_ID
    ,SPECIALTY_STORE
    ,IS_MENS_ACCOUNT
    ,IS_SCRUBS_ACCOUNT
    ,CHANNEL
    ,ACCOUNT_NAME
    ,ACCOUNT_ID
    ,VENDOR_NAME
    ,FEE_OF_MEDIA_SPEND AS TFEE_PCT_OF_MEDIA_SPEND
    ,IDENTIFIER
    ,IDENTIFIER_TYPE
    ,IDENTIFIER_VALUE
    ,START_DATE_INCLUDE::DATE AS START_DATE_INCLUDE
    ,END_DATE_EXCLUDE::DATE AS END_DATE_EXCLUDE
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.med_sharepoint_admin_V1.media_vendor_fee_mapping_vendor_fees;
