CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_MICROINFLUENCER_PRODUCT_COST AS
SELECT MONTH_START_DATE::date as MONTH_START_DATE
,brand as BUSINESS_UNIT_ABBR
,COUNTRY as COUNTRY_ABBR
,SUBCHANNEL
,PRODUCT_SHIPPING_COST as COGS
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM LAKE_FIVETRAN.MED_SHAREPOINT_INFLUENCER_V1.INFLUENCER_TRACKER_MASTER_G_MICRO_INFLUENCER_PRODUCT_COST;
