CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_INFLUENCER_MAPPING AS
SELECT INFLUENCER_NAME
	,CIQ_PUBLISHER_NAME
	,MEDIA_PARTNER_ID::varchar MEDIA_PARTNER_ID
	,CIQ_PUBLISHER_ID
	,INFLUENCER_IG_HANDLE
	,INFLUENCER_FB_HANDLE
	,INFLUENCER_YT_HANDLE
	,INFLUENCER_CLEANED_NAME_SHOWN_IN_HDYH_ AS INFLUENCER_CLEANED_NAME
	,STORE_NAME_ABBR
	,EXCLUDE_FROM_HDYH
	,ACTIVE
	,HDYH_ANSWER_CHANGE_1
	,HDYH_ANSWER_CHANGE_2
	,HDYH_ANSWER_CHANGE_3
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.med_sharepoint_influencer_v1.tech_style_influencer_mapping_sxna_final_mapping

UNION

SELECT INFLUENCER_NAME
	,CIQ_PUBLISHER_NAME
	,MEDIA_PARTNER_ID
	,CIQ_PUBLISHER_ID
	,INFLUENCER_IG_HANDLE
	,INFLUENCER_FB_HANDLE
	,INFLUENCER_YT_HANDLE
	,INFLUENCER_CLEANED_NAME_SHOWN_IN_HDYH_ AS INFLUENCER_CLEANED_NAME
	,STORE_NAME_ABBR
	,EXCLUDE_FROM_HDYH
	,ACTIVE
	,HDYH_ANSWER_CHANGE_1
	,HDYH_ANSWER_CHANGE_2
	,HDYH_ANSWER_CHANGE_3
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
    ,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
FROM lake_fivetran.med_sharepoint_influencer_v1.tech_style_influencer_mapping_flna_womens_final_mapping;
