CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_POWERSPACE_SPEND AS
	SELECT DISTINCT DATE::DATE AS DATE
		,CURRENCY
		,BUSINESS_UNIT
		,COUNTRY
		,SPEND
		,IMPRESSIONS
		,CLICKS
		,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
		,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
	FROM LAKE_FIVETRAN.MED_SHAREPOINT_SPEND_V1.POWERSPACE_FLFR

	UNION ALL

	SELECT DISTINCT DATE::DATE AS DATE
		,CURRENCY
		,BUSINESS_UNIT
		,COUNTRY
		,SPEND
		,IMPRESSIONS
		,CLICKS
		,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
		,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
	FROM LAKE_FIVETRAN.MED_SHAREPOINT_SPEND_V1.POWERSPACE_JFFR;
