CREATE OR REPLACE VIEW LAKE_VIEW.SHAREPOINT.MED_SCB_CREATIVE_DIMENSIONS AS
select distinct AD_TYPE
,STILL_LIFE_ANGLE_SHOT
,MERCHANDISE_TYPE
,DATE_CREATED_MMYY_ as DATE_CREATED
,SKU_3 as SKU3
,MODEL_PLACEMENT
,INFLUENCER_NAME
,ADSET_CREATIVE_CONCEPT
,SKU_5 as SKU5
,OFFER_PLACEMENT
,MODEL_ACTION
,GENDER
,ASSET_SIZE
,FIRST_3_SECONDS_TEXT
,FIRST_3_SECONDS_VISUAL
,PLATFORM_OR_CREATIVE_FORMAT
,DESIGNER_INITIALS
,TRELLO_ID
,ASSET_TYPE
,EGC_TALENT_NAME
,AUDIO
,OFFER_TIMING
,UGC_TALENT_NAME
,MESSAGING_THEME
,VIDEO_LENGTH
,NUMBER_OF_STYLES_SHOWN
,OFFER_PROMO
,TEST_VARIANTS_VIDEOS
,CREATIVE_CODE
,SKU_4 as SKU4
,LOGO
,SKU_2 as SKU2
,SKU_1 as SKU1
,_fivetran_synced::TIMESTAMP_LTZ AS meta_create_datetime
,_fivetran_synced::TIMESTAMP_LTZ AS meta_update_datetime
from LAKE_FIVETRAN.MED_SHAREPOINT_NAMING_GENERATORS_V1.SCB_CREATIVE_DIMENSIONS_GENERATOR_SCB_CREATIVE_ASSET_GENERATOR
where CREATIVE_CODE <> 'Creative Code' and CREATIVE_CODE not ilike '%FABLETICS SCRUBS CREATIVE NAMING GENERATOR%';
