CREATE VIEW IF NOT EXISTS daily_cash.vw_comparisons_source AS
SELECT
	 CASE
		WHEN comparison_type = 'Forecast' THEN 'FC'
		WHEN comparison_type = 'Budget' THEN 'BT'
		ELSE NULL
	END AS comparison_type,
	issued_datetime,
	month AS date,
	CASE
			WHEN BU = 'JFNA' THEN 'JF NA'
			WHEN BU = 'JFEU' THEN 'JF EU'
			WHEN BU = 'FLEU' THEN 'FL EU'
			WHEN BU = 'FLNA xRT' AND s.comparison_type = 'Forecast' THEN 'FL NA'
			WHEN BU = 'FLNA' AND s.comparison_type = 'Budget' THEN 'FL NA'
			WHEN BU = 'FLNA xRT' AND s.comparison_type = 'Budget' THEN 'FL NA'
			WHEN BU = 'SXNA' THEN 'SX NA'
			WHEN BU = 'SXEU' THEN 'SX EU'
			WHEN BU = 'SXWW' THEN 'SX WW'
			WHEN BU = 'FLRT' THEN 'FL Retail'
            WHEN BU = 'FLNA-FVIP-OREV' THEN 'FL NA WN (Excludes Retail)'
            WHEN BU = 'FLNA-MVIP-OREV ' THEN 'FL NA MN (Excludes Retail)'
            WHEN BU = 'FLNA-OREV ' THEN 'FL NA ONLINE'
            WHEN BU = 'FLNA-RREV ' THEN 'FL NA RETAIL'
            WHEN BU = 'FLNA WN ' THEN 'FL NA WN'
            WHEN BU = 'FLNA MN' THEN 'FL NA MN'
            WHEN BU = 'FLEU-FVIP-OREV' THEN 'FL EU WN (Excludes Retail)'
            WHEN BU = 'FLEU-MVIP-OREV' THEN 'FL EU MN (Excludes Retail)'
            WHEN BU = 'FKNA' THEN 'FK'
            WHEN BU = 'FLNA+RT' THEN 'FLNA wRT'
            WHEN BU = 'FLNAxRT' THEN 'FLNA xRT'
            WHEN BU = 'SDNA' THEN 'SD'
			ELSE BU
		END AS store,
	total_cash_charged_amount,
	-1 * cash_refunds AS total_cash_refunded_amount,
	-1 * chargebacks AS total_cash_chargeback_amount,
	net_cash_revenue,
--	refund_cb_gross_cash_pct,
	cash_gross_margin_amount,
	cash_gross_margin_percent,
---------------------------------------------------------------------
-- Activating orders
---------------------------------------------------------------------
	activating_shipped_order_revenue,
	activating_shipped_order_net_revenue,
	activating_shipped_order_count,
	first_msrp_revenue AS activating_shipped_order_subtotal,
	-1 * first_discounts AS activating_shipped_order_discount,
--	activating_shipped_AOV_incl_shipping = Activating AOV (incl# shipping rev) ,
--	activating_shipped_order_upt,
	activating_shipped_order_upt * activating_shipped_order_count AS activating_shipped_order_units,
--	activating_shipped_discount_pct,
	activating_shipped_gross_margin,
--	activating_shipped_gm_pct = Activating Gross Margin %
---------------------------------------------------------------------
-- Nonctivating orders
---------------------------------------------------------------------
	nonactivating_shipped_order_cash,
	nonactivating_shipped_order_revenue,
	nonactivating_shipped_order_net_revenue,
	nonactivating_shipped_order_count,
	nonactivating_shipped_order_subtotal,
	-1 * repeat_discounts AS nonactivating_shipped_order_discount,
--	nonactivating_shipped_AOV_incl_shipping = Repeat AOV (incl# shipping rev) ,
--	nonactivating_shipped_order_upt,
	nonactivating_shipped_order_upt * nonactivating_shipped_order_count AS nonactivating_shipped_order_units,
--	nonactivating_shipped_discount_pct,
	nonactivating_shipped_gross_margin,
--	nonactivating_shipped_gm_pct = Repeat Gross Margin % ,
	nonactivating_net_cash_revenue,
	nonactivating_cash_gross_margin,
--	nonactivating_cash_gross_margin_percent,
	membership_credit_charged_amount,
	membership_credit_redeemed_amount,
	membership_credit_refunds_chargebacks,
	net_membership_credit_charged_amount,
	net_membership_credit_percent,
	total_store_credit_refunded_amount,
	-1 * refund_credit_redeemed AS refund_credit_redeemed_amount,
--	repeat_net_unredeemed_credit_billings, -- not in my table
	-1 * repeat_refund_credits AS nonactivating_shipped_credit_refunded_amount,
--	Repeat Other (Ad Rev/Adaptive Adj) , -- not in my table
--	net_unredeemed_refund_credit , -- not in my table
--	deferred_revenue, -- not in my table
--	vip_billed_percent * bom_vips AS membership_credit_charged_count,
	membership_credit_charged_count,
	--credit_redeemed_percent = Credit Redeemed % ,
	membership_credit_redeemed_count,
	--credit_canceled_percent,
	membership_credit_canceled_count,
---------------------------------------------------------------------
-- Acquisitons
---------------------------------------------------------------------
	bom_vips AS vips_entering_period_daily,
	bom_vips AS vips_entering_period_monthly,
	--vip_billed_percent,
	media_spend,
	--Cash Contribution after Media ,
--	Media Spend1 ,
--	CPL ,
--	VIP CPA ,
--	M1 Lead to VIP ,
	leads,
	m1_vips,
	aged_lead_conversions,
	total_vips_on_date,
	cancels AS total_cancels,
	net_vips_gained,
	eom_vips,
--	growth_rate = Growth % ,
	total_units_shipped,
	total_outbound_cost_product,
	total_outbound_cost_freight,
	total_outbound_cost_shipping_supplies,
	returns_cost_shipping,
	total_outbound_cost_product_markdown,
	total_cogs,
	cash_purchase_rate * bom_vips AS cash_purchase_count,
------ New metrics
	NULL AS membership_fees_charged,
	NULL AS membership_fees_refunded,
	NULL AS net_membership_fees,
	NULL AS online_retail_gaap_gross_revenue,
	NULL AS online_retail_gaap_net_revenue,
	NULL AS online_retail_shipping_revenue,
	NULL AS online_retail_shipped_order_count,
	NULL AS online_retail_aov_incl_shipping,
	NULL AS online_retail_shipped_order_units,
	NULL AS online_retail_upt,
	NULL AS online_retail_orders_as_pct_of_repeat_orders,
	NULL AS online_retail_aur,
	NULL AS online_retail_discount_pct,
	NULL AS online_retail_gross_margin_,
	NULL AS online_retail_gaap_gross_margin_pct,
	NULL AS first_online_retail_gaap_gross_revenue,
	NULL AS first_online_retail_gaap_net_revenue,
	NULL AS first_online_retail_shipping_revenue,
	NULL AS first_online_retail_shipped_order_count,
	NULL AS first_online_retail_aov_incl_shipping,
	NULL AS first_online_retail_shipped_order_units,
	NULL AS first_online_retail_upt,
	NULL AS first_online_retail_orders_as_pct_of_repeat_orders,
	NULL AS first_online_retail_aur,
	NULL AS first_online_retail_discount_pct,
	NULL AS first_online_retail_gross_margin_,
	NULL AS first_online_retail_gaap_gross_margin_pct,
	NULL AS repeat_online_retail_gaap_gross_revenue,
	NULL AS repeat_online_retail_gaap_net_revenue,
	NULL AS repeat_online_retail_shipping_revenue,
	NULL AS repeat_online_retail_shipped_order_count,
	NULL AS repeat_online_retail_aov_incl_shipping,
	NULL AS repeat_online_retail_shipped_order_units,
	NULL AS repeat_online_retail_upt,
	NULL AS repeat_online_retail_orders_as_pct_of_repeat_orders,
	NULL AS repeat_online_retail_aur,
	NULL AS repeat_online_retail_discount_pct,
	NULL AS repeat_online_retail_gross_margin_,
	NULL AS repeat_online_retail_gaap_gross_margin_pct,
	NULL AS total_customer_merch_purchase_rate_pct,
	NULL AS merch_purchase_rate_pct_vip,
	NULL AS merch_purchase_rate_pct_online_retail,
	NULL AS bop_total_customers,
	NULL AS new_total_customers,
	NULL AS cancels_total_customers,
	NULL AS eop_total_customers,
	NULL AS bop_xtra_members,
	NULL AS new_xtra_members,
	NULL AS cancels_xtra_members,
	NULL AS eop_xtra_members,
	NULL AS bop_online_retail_customers,
	NULL AS new_online_retail_customers,
	NULL AS cancels_online_retail_customers,
	NULL AS eop_online_retail_customers,
	NULL AS total_sessions,
	NULL AS sessions,
	NULL AS revenue_per_session,
	NULL AS cost_per_session,
	NULL AS total_leads,
	NULL AS total_customers,
	NULL AS total_orders,
	NULL AS total_lead_to_total_customer_same_session_pct,
	NULL AS total_lead_to_total_customer_m1_pct,
	NULL AS product_revenue,
	NULL AS membership_revenue,
	NULL AS total_revenue,
	NULL AS product_revenue_aov,
	NULL AS total_revenue_aov,
	NULL AS product_aur,
	NULL AS product_auc,
	NULL AS product_upt,
	NULL AS product_gm,
	NULL AS product_gm_per_order,
	NULL AS product_gm_pct,
	NULL AS total_conversion_pct,
	NULL AS product_revenue_roas,
	NULL AS product_margin_roas,
	NULL AS total_revenue_roas,
	NULL AS total_cpo,
	NULL AS membership_new_vips,
	NULL AS membership_activating_orders,
	NULL AS membership_product_revenue,
	NULL AS membership_membership_revenue,
	NULL AS membership_total_revenue,
	NULL AS membership_product_revenue_aov,
	NULL AS membership_total_revenue_aov,
	NULL AS membership_product_aur,
	NULL AS membership_product_auc,
	NULL AS membership_product_upt,
	NULL AS membership_product_gm,
	NULL AS membership_product_gm_per_order,
	NULL AS membership_product_gm_pct,
	NULL AS membership_conversion_pct,
	NULL AS membership_product_revenue_roas,
	NULL AS membership_product_margin_roas,
	NULL AS membership_new_vips_same_session,
	NULL AS membership_new_m1_vips,
	NULL AS membership_new_m2_vips,
	NULL AS membership_new_vips_converting_from_online_retail,
	NULL AS onlne_retail_new_online_retail_members,
	NULL AS online_retail_1st_time_online_retail_orders,
	NULL AS online_retail_product_revenue,
	NULL AS online_retail_product_revenue_aov,
	NULL AS online_retail_product_aur,
	NULL AS online_retail_product_auc,
	NULL AS online_retail_product_upt,
	NULL AS online_retail_product_gm,
	NULL AS online_retail_product_gm_per_order,
	NULL AS online_retail_product_gm_pct,
	NULL AS online_retail_conversion_pct,
	NULL AS online_retail_product_revenue_roas,
	NULL AS online_retail_product_margin_roas,
	NULL AS online_retail_new_online_retail_same_session,
	NULL AS online_retail_new_online_retail_m1,
	NULL AS online_retail_new_online_retail_m2,
	NULL AS vip_cash_gross_revenue,
	NULL AS vip_cash_net_revenue,
	NULL AS repeat_gaap_gross_revenue,
	NULL AS repeat_gaap_net_revenue,
	NULL AS repeat_shipping_revenue,
	NULL AS repeat_shipped_order_count,
	NULL AS repeat_aov_incl_shipping,
	NULL AS repeat_aov_excl_shipping,
	NULL AS repeat_shipped_order_units,
	NULL AS repeat_upt,
	NULL AS repeat_aur,
	NULL AS repeat_gaap_gross_margin,
	NULL AS repeat_gaap_gross_margin_pct,
	NULL AS gross_product_revenue_pct_of_total,
	NULL AS gross_membership_fee_revenue_pct_of_total,
	NULL AS repeat_gaap_gross_margin_per_order,
	NULL AS first_online_retail_gaap_gross_margin_per_order,
	NULL AS first_online_retail_shipped_order_cash_collected,
	NULL AS repeat_online_retail_aov_excl_shipping,
	NULL AS repeat_online_retail_gaap_gross_margin_per_order,
	NULL AS repeat_online_retail_shipped_order_cash_collected,
	COALESCE(s.activating_acquisition_margin,0) AS activating_acquisition_margin,
	COALESCE(s.activating_acquisition_margin_percent,0) AS activating_acquisition_margin_percent,
	COALESCE(s.activating_acquisition_margin_per_order,0) AS activating_acquisition_margin_per_order
FROM lake.excel.daily_cash_comparisons s
WHERE comparison_type IN ('Forecast', 'Budget');
