CREATE OR REPLACE VIEW reporting.merch.vw_planning_sales_and_returns AS
SELECT COALESCE(ps.store_id, pr.store_id) AS store_id,
    ds.STORE_NAME,
    ds.STORE_TYPE,
    ds.store_brand_name AS business_unit,
    ds.store_country_abbr AS country,
    ds.store_region_abbr AS region,
    COALESCE(ps.period, pr.period) AS period,
    COALESCE(ps.product_sku, pr.product_sku) AS product_sku,
    COALESCE(ps.source, pr.source) AS source,
    COALESCE(ps.date_type, pr.date_type) AS date_type,
    COALESCE(ps.datetime_added, pr.datetime_added) AS datetime_added,
    COALESCE(ps.week_month_year, pr.week_month_year) AS week_month_year,
    COALESCE(ps.year, pr.year) AS year,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_qty_sold, 0), 0)) AS tw_total_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_qty_sold, 0), 0)) AS tw_first_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_qty_sold, 0), 0)) AS tw_repeat_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_gross_sales, 0), 0)) AS tw_total_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_gross_sales, 0), 0)) AS tw_first_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_gross_sales, 0), 0)) AS tw_repeat_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_discount, 0), 0)) AS tw_total_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_discount, 0), 0)) AS tw_first_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_discount, 0), 0)) AS tw_repeat_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_product_revenue, 0), 0)) AS tw_total_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_product_revenue, 0), 0)) AS tw_first_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_product_revenue, 0), 0)) AS tw_repeat_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_cogs, 0), 0)) AS tw_total_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_cogs, 0), 0)) AS tw_first_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_cogs, 0), 0)) AS tw_repeat_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_gross_sales_local, 0), 0)) AS tw_total_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_gross_sales_local, 0), 0)) AS tw_first_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_gross_sales_local, 0), 0)) AS tw_repeat_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_discount_local, 0), 0)) AS tw_total_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_discount_local, 0), 0)) AS tw_first_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_discount_local, 0), 0)) AS tw_repeat_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_product_revenue_local, 0), 0)) AS tw_total_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_product_revenue_local, 0), 0)) AS tw_first_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_product_revenue_local, 0), 0)) AS tw_repeat_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_cogs_local, 0), 0)) AS tw_total_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_cogs_local, 0), 0)) AS tw_first_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_cogs_local, 0), 0)) AS tw_repeat_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_qty_reships, 0), 0)) AS tw_total_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_qty_reships, 0), 0)) AS tw_first_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_qty_reships, 0), 0)) AS tw_repeat_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.total_non_reduced_vip_price, 0), 0)) AS tw_total_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.first_non_reduced_vip_price, 0), 0)) AS tw_first_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(ps.repeat_non_reduced_vip_price, 0), 0)) AS tw_repeat_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_qty_sold, 0), 0)) AS lw_total_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_qty_sold, 0), 0)) AS lw_first_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_qty_sold, 0), 0)) AS lw_repeat_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_gross_sales, 0), 0)) AS lw_total_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_gross_sales, 0), 0)) AS lw_first_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_gross_sales, 0), 0)) AS lw_repeat_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_discount, 0), 0)) AS lw_total_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_discount, 0), 0)) AS lw_first_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_discount, 0), 0)) AS lw_repeat_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_product_revenue, 0), 0)) AS lw_total_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_product_revenue, 0), 0)) AS lw_first_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_product_revenue, 0), 0)) AS lw_repeat_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_cogs, 0), 0)) AS lw_total_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_cogs, 0), 0)) AS lw_first_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_cogs, 0), 0)) AS lw_repeat_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_gross_sales_local, 0), 0)) AS lw_total_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_gross_sales_local, 0), 0)) AS lw_first_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_gross_sales_local, 0), 0)) AS lw_repeat_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_discount_local, 0), 0)) AS lw_total_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_discount_local, 0), 0)) AS lw_first_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_discount_local, 0), 0)) AS lw_repeat_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_product_revenue_local, 0), 0)) AS lw_total_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_product_revenue_local, 0), 0)) AS lw_first_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_product_revenue_local, 0), 0)) AS lw_repeat_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_cogs_local, 0), 0)) AS lw_total_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_cogs_local, 0), 0)) AS lw_first_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_cogs_local, 0), 0)) AS lw_repeat_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_qty_reships, 0), 0)) AS lw_total_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_qty_reships, 0), 0)) AS lw_first_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_qty_reships, 0), 0)) AS lw_repeat_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.total_non_reduced_vip_price, 0), 0)) AS lw_total_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.first_non_reduced_vip_price, 0), 0)) AS lw_first_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(ps.repeat_non_reduced_vip_price, 0), 0)) AS lw_repeat_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_qty_sold, 0), 0)) AS mtd_total_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_qty_sold, 0), 0)) AS mtd_first_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_qty_sold, 0), 0)) AS mtd_repeat_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_gross_sales, 0), 0)) AS mtd_total_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_gross_sales, 0), 0)) AS mtd_first_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_gross_sales, 0), 0)) AS mtd_repeat_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_discount, 0), 0)) AS mtd_total_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_discount, 0), 0)) AS mtd_first_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_discount, 0), 0)) AS mtd_repeat_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_product_revenue, 0), 0)) AS mtd_total_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_product_revenue, 0), 0)) AS mtd_first_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_product_revenue, 0), 0)) AS mtd_repeat_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_cogs, 0), 0)) AS mtd_total_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_cogs, 0), 0)) AS mtd_first_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_cogs, 0), 0)) AS mtd_repeat_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_gross_sales_local, 0), 0)) AS mtd_total_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_gross_sales_local, 0), 0)) AS mtd_first_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_gross_sales_local, 0), 0)) AS mtd_repeat_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_discount_local, 0), 0)) AS mtd_total_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_discount_local, 0), 0)) AS mtd_first_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_discount_local, 0), 0)) AS mtd_repeat_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_product_revenue_local, 0), 0)) AS mtd_total_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_product_revenue_local, 0), 0)) AS mtd_first_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_product_revenue_local, 0), 0)) AS mtd_repeat_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_cogs_local, 0), 0)) AS mtd_total_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_cogs_local, 0), 0)) AS mtd_first_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_cogs_local, 0), 0)) AS mtd_repeat_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_qty_reships, 0), 0)) AS mtd_total_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_qty_reships, 0), 0)) AS mtd_first_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_qty_reships, 0), 0)) AS mtd_repeat_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.total_non_reduced_vip_price, 0), 0)) AS mtd_total_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.first_non_reduced_vip_price, 0), 0)) AS mtd_first_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(ps.repeat_non_reduced_vip_price, 0), 0)) AS mtd_repeat_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_qty_sold, 0), 0)) AS ly_total_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_qty_sold, 0), 0)) AS ly_first_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_qty_sold, 0), 0)) AS ly_repeat_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_gross_sales, 0), 0)) AS ly_total_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_gross_sales, 0), 0)) AS ly_first_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_gross_sales, 0), 0)) AS ly_repeat_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_discount, 0), 0)) AS ly_total_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_discount, 0), 0)) AS ly_first_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_discount, 0), 0)) AS ly_repeat_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_product_revenue, 0), 0)) AS ly_total_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_product_revenue, 0), 0)) AS ly_first_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_product_revenue, 0), 0)) AS ly_repeat_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_cogs, 0), 0)) AS ly_total_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_cogs, 0), 0)) AS ly_first_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_cogs, 0), 0)) AS ly_repeat_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_gross_sales_local, 0), 0)) AS ly_total_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_gross_sales_local, 0), 0)) AS ly_first_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_gross_sales_local, 0), 0)) AS ly_repeat_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_discount_local, 0), 0)) AS ly_total_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_discount_local, 0), 0)) AS ly_first_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_discount_local, 0), 0)) AS ly_repeat_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_product_revenue_local, 0), 0)) AS ly_total_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_product_revenue_local, 0), 0)) AS ly_first_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_product_revenue_local, 0), 0)) AS ly_repeat_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_cogs_local, 0), 0)) AS ly_total_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_cogs_local, 0), 0)) AS ly_first_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_cogs_local, 0), 0)) AS ly_repeat_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_qty_reships, 0), 0)) AS ly_total_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_qty_reships, 0), 0)) AS ly_first_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_qty_reships, 0), 0)) AS ly_repeat_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.total_non_reduced_vip_price, 0), 0)) AS ly_total_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.first_non_reduced_vip_price, 0), 0)) AS ly_first_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(ps.repeat_non_reduced_vip_price, 0), 0)) AS ly_repeat_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_qty_sold, 0), 0)) AS lymtd_total_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_qty_sold, 0), 0)) AS lymtd_first_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_qty_sold, 0), 0)) AS lymtd_repeat_qty_sold,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_gross_sales, 0), 0)) AS lymtd_total_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_gross_sales, 0), 0)) AS lymtd_first_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_gross_sales, 0), 0)) AS lymtd_repeat_gross_sales,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_discount, 0), 0)) AS lymtd_total_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_discount, 0), 0)) AS lymtd_first_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_discount, 0), 0)) AS lymtd_repeat_discount,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_product_revenue, 0), 0)) AS lymtd_total_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_product_revenue, 0), 0)) AS lymtd_first_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_product_revenue, 0), 0)) AS lymtd_repeat_product_revenue,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_cogs, 0), 0)) AS lymtd_total_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_cogs, 0), 0)) AS lymtd_first_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_cogs, 0), 0)) AS lymtd_repeat_cogs,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_gross_sales_local, 0), 0)) AS lymtd_total_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_gross_sales_local, 0), 0)) AS lymtd_first_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_gross_sales_local, 0), 0)) AS lymtd_repeat_gross_sales_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_discount_local, 0), 0)) AS lymtd_total_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_discount_local, 0), 0)) AS lymtd_first_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_discount_local, 0), 0)) AS lymtd_repeat_discount_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_product_revenue_local, 0), 0)) AS lymtd_total_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_product_revenue_local, 0), 0)) AS lymtd_first_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_product_revenue_local, 0), 0)) AS lymtd_repeat_product_revenue_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_cogs_local, 0), 0)) AS lymtd_total_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_cogs_local, 0), 0)) AS lymtd_first_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_cogs_local, 0), 0)) AS lymtd_repeat_cogs_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_qty_reships, 0), 0)) AS lymtd_total_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_qty_reships, 0), 0)) AS lymtd_first_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_qty_reships, 0), 0)) AS lymtd_repeat_qty_reships,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.total_non_reduced_vip_price, 0), 0)) AS lymtd_total_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.first_non_reduced_vip_price, 0), 0)) AS lymtd_first_non_reduced_vip_price,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(ps.repeat_non_reduced_vip_price, 0), 0)) AS lymtd_repeat_non_reduced_vip_price,

    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.total_return_units, 0), 0)) AS tw_total_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.first_return_units, 0), 0)) AS tw_first_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.repeat_return_units, 0), 0)) AS tw_repeat_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.total_return_dollars, 0), 0)) AS tw_total_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.first_return_dollars, 0), 0)) AS tw_first_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.repeat_return_dollars, 0), 0)) AS tw_repeat_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.total_return_dollars_local, 0), 0)) AS tw_total_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.first_return_dollars_local, 0), 0)) AS tw_first_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'TW', COALESCE(pr.repeat_return_dollars_local, 0), 0)) AS tw_repeat_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.total_return_units, 0), 0)) AS lw_total_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.first_return_units, 0), 0)) AS lw_first_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.repeat_return_units, 0), 0)) AS lw_repeat_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.total_return_dollars, 0), 0)) AS lw_total_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.first_return_dollars, 0), 0)) AS lw_first_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.repeat_return_dollars, 0), 0)) AS lw_repeat_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.total_return_dollars_local, 0), 0)) AS lw_total_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.first_return_dollars_local, 0), 0)) AS lw_first_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LW', COALESCE(pr.repeat_return_dollars_local, 0), 0)) AS lw_repeat_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.total_return_units, 0), 0)) AS mtd_total_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.first_return_units, 0), 0)) AS mtd_first_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.repeat_return_units, 0), 0)) AS mtd_repeat_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.total_return_dollars, 0), 0)) AS mtd_total_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.first_return_dollars, 0), 0)) AS mtd_first_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.repeat_return_dollars, 0), 0)) AS mtd_repeat_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.total_return_dollars_local, 0), 0)) AS mtd_total_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.first_return_dollars_local, 0), 0)) AS mtd_first_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'MTD', COALESCE(pr.repeat_return_dollars_local, 0), 0)) AS mtd_repeat_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.total_return_units, 0), 0)) AS ly_total_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.first_return_units, 0), 0)) AS ly_first_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.repeat_return_units, 0), 0)) AS ly_repeat_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.total_return_dollars, 0), 0)) AS ly_total_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.first_return_dollars, 0), 0)) AS ly_first_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.repeat_return_dollars, 0), 0)) AS ly_repeat_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.total_return_dollars_local, 0), 0)) AS ly_total_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.first_return_dollars_local, 0), 0)) AS ly_first_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LY', COALESCE(pr.repeat_return_dollars_local, 0), 0)) AS ly_repeat_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.total_return_units, 0), 0)) AS lymtd_total_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.first_return_units, 0), 0)) AS lymtd_first_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.repeat_return_units, 0), 0)) AS lymtd_repeat_return_units,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.total_return_dollars, 0), 0)) AS lymtd_total_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.first_return_dollars, 0), 0)) AS lymtd_first_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.repeat_return_dollars, 0), 0)) AS lymtd_repeat_return_dollars,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.total_return_dollars_local, 0), 0)) AS lymtd_total_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.first_return_dollars_local, 0), 0)) AS lymtd_first_return_dollars_local,
    SUM(IFF(COALESCE(ps.period, pr.period) = 'LYMTD', COALESCE(pr.repeat_return_dollars_local, 0), 0)) AS lymtd_repeat_return_dollars_local
FROM reporting.merch.planning_sales ps
FULL JOIN reporting.merch.planning_returns pr ON pr.store_id = ps.store_id
    AND pr.period = ps.period
    AND pr.product_sku = ps.product_sku
    AND pr.source = ps.source
    AND pr.date_type = ps.date_type
    AND pr.datetime_added = ps.datetime_added
    AND pr.week_month_year = ps.week_month_year
    AND pr.year = ps.year
JOIN edm_db_edw01_edw_view.dbo.dim_store ds ON ds.store_id = CASE COALESCE(ps.store_id, pr.store_id) WHEN 46001 THEN 4601
                                                                                                    WHEN 52001 THEN 5201
                                                                                                    WHEN 55001 THEN 5501
                                                                                                    ELSE COALESCE(ps.store_id, pr.store_id)
                                                                                                    END
    AND ds.meta_is_current = 1
    AND ds.store_name NOT ILIKE '%(DM)%'
    AND ds.store_name NOT ILIKE '%Wholesale%'
    AND ds.store_name NOT ILIKE '%Heels.com%'
    AND ds.store_name NOT ILIKE '%Retail%'
    AND ds.store_name NOT ILIKE '%Sample%'
    AND ds.store_name NOT ILIKE '%SWAG%'
    AND ds.store_name NOT ILIKE '%PS%'
GROUP BY COALESCE(ps.store_id, pr.store_id),
    ds.STORE_NAME,
    ds.STORE_TYPE,
    ds.store_brand_name,
    ds.store_country_abbr,
    ds.store_region_abbr,
    COALESCE(ps.period, pr.period),
    COALESCE(ps.product_sku, pr.product_sku),
    COALESCE(ps.source, pr.source),
    COALESCE(ps.date_type, pr.date_type),
    COALESCE(ps.datetime_added, pr.datetime_added),
    COALESCE(ps.week_month_year, pr.week_month_year),
    COALESCE(ps.year, pr.year);
