CREATE OR REPLACE VIEW breakage.fabletics_breakage_report_ssrs_base AS
-- token
SELECT CONCAT(brand, ' ', country)                                   business_unit,
       region,
       country,
       IFF(brand = 'Yitty', CONCAT('YT', country, '-F'),
           CONCAT('FL', country, '-',
                  IFF(CONTAINS(business_unit, 'Womens'), 'F', 'M'))) display_store,
       IFF(brand = 'Yitty', CONCAT('YT', country, '-F-', original_credit_type),
           CONCAT('FL', country, '-',
                  IFF(CONTAINS(business_unit, 'Womens'), CONCAT('F', '-', original_credit_type),
                      CONCAT('M', '-', 'Combined'))))                store_credit_type,
       currency,
       'Recognize'                                                   deferred_recognition_label,
       original_credit_reason                                        store_credit_reason,
       IFF(country IN ('US', 'CA', 'UK'), '13x12', '24X12')          assumption_months_baseline,
       original_issued_month                                         issued_month,
       activity_month::DATE                                          recognition_booking_month,
       credit_tenure                                                 months_of_activity_from_issuance,
       DATEADD(MONTH, -23, activity_month)::DATE                     credit_cohort_start_blend,
       activity_month::DATE                                          credit_cohort_end_blend,
       24                                                            blended_credit_cohorts,
       'Clean Blended Cohorts'                                       blended_credit_cohorts_type,
       issued_to_date                                                issued_amount,
       NULL                                                          redeemed_m10,
       NULL                                                          cancelled_m10,
       NULL                                                          unredeemed_m10,
       redeemed_to_date                                              redeemed_to_date,
       cancelled_to_date                                             cancelled_to_date,
       expired_to_date                                               expired_to_date,
       unredeemed_to_date                                            unredeemed_to_date,
       NULL                                                          redeemed_m11plus,
       NULL                                                          cancelled_m11plus,
       0                                                             unredeemed_cant_recognize,

       redeemed_rate_to_date                                         redeemed_to_date_pct,
       cancelled_to_date / NULLIF(issued_amount, 0)                  cancelled_to_date_pct,
       unredeemed_to_date / NULLIF(issued_amount, 0)                 unredeemed_to_date_pct,

       expected_redeemed_rate                                        assumption_cumulative_redeemed_pct,
       NULL                                                          assumption_cumulative_redeemed_m10_pct,
       NULL                                                          assumption_cumulative_redeemed_m11plus_pct,
       expected_redeemed_rate_max                                    assumption_cumulative_redeemed_m19or24_pct,

       1 - expected_redeemed_rate_max - expected_unredeemed_rate     assumption_cumulative_cancelled_pct,
       NULL                                                          assumption_cumulative_cancelled_m10_pct,
       NULL                                                          assumption_cumulative_cancelled_m11plus_pct,
       NULL                                                          assumption_cumulative_unredeemed_m10_pct,
       expected_unredeemed_rate                                      assumption_cumulative_unredeemed_pct,


       issued_amount * expected_redeemed_rate                        expected_redeemed,
       NULL                                                          expected_redeemed_m10,
       NULL                                                          expected_redeemed_m11plus,
       expected_additional_redeemed                                  expected_additional_redeemed,
       issued_amount * assumption_cumulative_cancelled_pct           expected_cancelled,
       NULL                                                          expected_cancelled_m10,
       NULL                                                          expected_cancelled_m11plus,

       expected_additional_cancelled                                 expected_additional_cancelled,
       expected_additional_activity_amount_m14to19,

       NULL                                                          expected_unredeemed_m10,
       issued_amount * assumption_cumulative_unredeemed_pct          expected_unredeemed,
       NULL                                                          redeemed_to_date_vs_expected_redeemed_m10,
       expected_breakage_to_record                                   expected_breakage,
       0                                                             expected_cannot_recognize,
       breakage_recorded                                             breakage_to_record,
       IFF(RANK() OVER (PARTITION BY brand,region,country, currency,original_credit_tender,
           original_credit_type,original_issued_month
           ORDER BY activity_month) = 1, breakage_to_record,
           (breakage_to_record - LAG(breakage_to_record) OVER (PARTITION BY brand,region,country,currency,original_credit_tender,original_credit_type,
               original_issued_month
               ORDER BY activity_month)))                            change_in_breakage_to_record,
       0                                                             reporting_cannot_recognize,
       breakage_to_record                                            reporting_expected_breakage
FROM breakage.fabletics_token_breakage_report

UNION ALL
--converted
SELECT CONCAT(brand, ' ', country)                                         business_unit,
       region,
       country,
       CONCAT('FL', country, '-',
              IFF(CONTAINS(business_unit, 'Womens'), 'F', 'M'))            display_store,
       CONCAT('FL', country, '-',
              IFF(CONTAINS(business_unit, 'Womens'), CONCAT('F', '-', original_credit_type),
                  CONCAT('M', '-', 'Combined')))                           store_credit_type,
       currency,
       'Recognize'                                                         deferred_recognition_label,
       original_credit_reason                                              store_credit_reason,
       '24X12'                                                             assumption_months_baseline,
       original_issued_month                                               issued_month,
       activity_month::DATE                                                recognition_booking_month,
       credit_tenure                                                       months_of_activity_from_issuance,
       DECODE(country, 'US', '2018-12-01'::DATE, 'CA', '2017-08-01'::DATE,
              '2017-10-01'::DATE)                                          credit_cohort_start_blend,
       DECODE(country, 'US', '2021-09-01'::DATE, 'CA', '2021-07-01'::DATE,
              '2021-09-01'::DATE)                                          credit_cohort_end_blend,
       DATEDIFF(MONTH, credit_cohort_start_blend, credit_cohort_end_blend) blended_credit_cohorts,
       'Clean Blended Cohorts'                                             blended_credit_cohorts_type,
       issued_to_date                                                      issued_amount,
       NULL                                                                redeemed_m10,
       NULL                                                                cancelled_m10,
       NULL                                                                unredeemed_m10,
       redeemed_to_date                                                    redeemed_to_date,
       cancelled_to_date                                                   cancelled_to_date,
       expired_to_date                                                     expired_to_date,
       unredeemed_to_date                                                  unredeemed_to_date,
       NULL                                                                redeemed_m11plus,
       NULL                                                                cancelled_m11plus,
       0                                                                   unredeemed_cant_recognize,

       redeemed_rate_to_date                                               redeemed_to_date_pct,
       cancelled_to_date / NULLIF(issued_amount, 0)                        cancelled_to_date_pct,
       unredeemed_to_date / NULLIF(issued_amount, 0)                       unredeemed_to_date_pct,
       expected_redeemed_rate                                              assumption_cumulative_redeemed_pct,
       NULL                                                                assumption_cumulative_redeemed_m10_pct,
       NULL                                                                assumption_cumulative_redeemed_m11plus_pct,
       expected_redeemed_rate_m24                                          assumption_cumulative_redeemed_m19or24_pct,
       1 - expected_redeemed_rate_m24 - expected_unredeemed_rate           assumption_cumulative_cancelled_pct,
       NULL                                                                assumption_cumulative_cancelled_m10_pct,
       NULL                                                                assumption_cumulative_cancelled_m11plus_pct,
       NULL                                                                assumption_cumulative_unredeemed_m10_pct,
       expected_unredeemed_rate                                            assumption_cumulative_unredeemed_pct,
       issued_amount * expected_redeemed_rate                              expected_redeemed,
       NULL                                                                expected_redeemed_m10,
       NULL                                                                expected_redeemed_m11plus,
       expected_additional_redeemed                                        expected_additional_redeemed,
       issued_amount * assumption_cumulative_cancelled_pct                 expected_cancelled,
       NULL                                                                expected_cancelled_m10,
       NULL                                                                expected_cancelled_m11plus,
       expected_additional_cancelled                                       expected_additional_cancelled,
       0                                                                   expected_additional_activity_amount_m14to19,
       NULL                                                                expected_unredeemed_m10,
       issued_amount * assumption_cumulative_unredeemed_pct                expected_unredeemed,
       NULL                                                                redeemed_to_date_vs_expected_redeemed_m10,
       expected_breakage_to_record                                         expected_breakage,
       0                                                                   expected_cannot_recognize,
       breakage_recorded                                                   breakage_to_record,
       IFF(RANK() OVER (PARTITION BY brand,region,country,currency,original_credit_tender,
           original_credit_type,original_issued_month
           ORDER BY activity_month) = 1, breakage_to_record,
           (breakage_to_record - LAG(breakage_to_record) OVER (PARTITION BY brand,region,country,currency,original_credit_tender,original_credit_type,
               original_issued_month
               ORDER BY activity_month)))                                  change_in_breakage_to_record,
       0                                                                   reporting_cannot_recognize,
       breakage_to_record                                                  reporting_expected_breakage
FROM breakage.fabletics_converted_credits_breakage_report

UNION ALL

---Refund Variable Credits
SELECT CONCAT(brand, ' ', country)                                         business_unit,
       region,
       country,

       IFF(brand = 'Yitty', CONCAT('YT', country, '-F'),
       CONCAT('FL', country, '-',
              IFF(CONTAINS(business_unit, 'Womens'), 'F', 'M'))  )          display_store,

        IFF(brand='Yitty',CONCAT('YT', country, '-F-',original_credit_type),
        CONCAT('FL', country, '-',
              IFF(CONTAINS(business_unit, 'Womens'), CONCAT('F', '-', original_credit_type),
                  CONCAT('M', '-', original_credit_type)))  )               store_credit_type,

       currency,
       deferred_recognition_label,
       store_credit_reason                                                 store_credit_reason,
       '24X10'                                                             assumption_months_baseline,
       issued_month                                                        issued_month,
       recognition_booking_month::DATE                                     recognition_booking_month,
       credit_tenure                                                       months_of_activity_from_issuance,
       DATEADD(MONTH, -23, recognition_booking_month::DATE)                credit_cohort_start_blend,
       recognition_booking_month::DATE                                     credit_cohort_end_blend,
       24                                                                  blended_credit_cohorts,
       IFF(credit_tenure <= 24, 'Clean Blended Cohorts', 'Actual Rates')   blended_credit_cohorts_type,
       issued_to_date                                                      issued_amount,
       NULL                                                                redeemed_m10,
       NULL                                                                cancelled_m10,
       NULL                                                                unredeemed_m10,
       redeemed_to_date                                                    redeemed_to_date,
       cancelled_to_date                                                   cancelled_to_date,
       expired_to_date                                                     expired_to_date,
       unredeemed_to_date                                                  unredeemed_to_date,
       NULL                                                                redeemed_m11plus,
       NULL                                                                cancelled_m11plus,
       unredeemed_cant_recognize                                           unredeemed_cant_recognize,
       redeemed_rate_to_date                                               redeemed_to_date_pct,
       cancelled_to_date / NULLIF(issued_amount, 0)                        cancelled_to_date_pct,
       unredeemed_to_date / NULLIF(issued_amount, 0)                       unredeemed_to_date_pct,
       expected_redeemed_rate                                              assumption_cumulative_redeemed_pct,
       NULL                                                                assumption_cumulative_redeemed_m10_pct,
       NULL                                                                assumption_cumulative_redeemed_m11plus_pct,
       expected_redeemed_rate_max                                          assumption_cumulative_redeemed_m19or24_pct,
       1 - expected_redeemed_rate_max - expected_unredeemed_rate           assumption_cumulative_cancelled_pct,
       NULL                                                                assumption_cumulative_cancelled_m10_pct,
       NULL                                                                assumption_cumulative_cancelled_m11plus_pct,
       NULL                                                                assumption_cumulative_unredeemed_m10_pct,
       expected_unredeemed_rate                                            assumption_cumulative_unredeemed_pct,
       issued_amount * expected_redeemed_rate                              expected_redeemed,
       NULL                                                                expected_redeemed_m10,
       NULL                                                                expected_redeemed_m11plus,
       expected_additional_redeemed                                        expected_additional_redeemed,
       issued_amount * assumption_cumulative_cancelled_pct                 expected_cancelled,
       NULL                                                                expected_cancelled_m10,
       NULL                                                                expected_cancelled_m11plus,
       expected_additional_cancelled                                       expected_additional_cancelled,
       0                                                                   expected_additional_activity_amount_m14to19,
       NULL                                                                expected_unredeemed_m10,
       issued_amount * assumption_cumulative_unredeemed_pct                expected_unredeemed,
       NULL                                                                redeemed_to_date_vs_expected_redeemed_m10,
       expected_breakage                                                   expected_breakage,
       expected_cannot_recognize                                           expected_cannot_recognize,
       breakage_to_record                                                  breakage_to_record,
       IFF(RANK() OVER (PARTITION BY brand,region,country,currency,deferred_recognition_label,original_credit_tender,
           original_credit_type,issued_month
           ORDER BY recognition_booking_month) = 1, breakage_to_record,
           (breakage_to_record - LAG(breakage_to_record) OVER (PARTITION BY brand,region,country,currency,deferred_recognition_label,original_credit_tender,original_credit_type,
               issued_month
               ORDER BY recognition_booking_month)))                       change_in_breakage_to_record,
       IFF(blended_credit_cohorts_type = 'Actual Rates', unredeemed_cant_recognize,
           expected_cannot_recognize)                                      reporting_cannot_recognize,
       breakage_to_record                                                  reporting_expected_breakage
FROM breakage.jfb_sxf_membership_credit_breakage_report
where 1=1
and recognition_booking_month >= '2024-12-01'
and brand in ('Fabletics Mens','Fabletics Womens','Yitty')
and ((original_credit_type = 'Variable Credit' and store_credit_reason = 'Refund') OR
     (original_credit_type = 'Giftcard' AND store_credit_reason = 'Gift Card - Paid'))
order by issued_month, deferred_recognition_label
;




