use reporting_prod;
-- Add LAST_EVALUATION_BATCH_ID,LAST_EVALUATION_MESSAGE to IMAGE_TESTING_IMAGE_TESTS
create or replace temporary TABLE _IMAGE_TESTING_IMAGE_TESTS_EXTRACT0 AS
(   WITH ranked_rows AS (
        SELECT
            MASTER_TEST_NUMBER,
            EVALUATION_BATCH_ID,
            EVALUATION_MESSAGE,
            ROW_NUMBER() OVER (PARTITION BY MASTER_TEST_NUMBER ORDER BY EVALUATION_BATCH_ID DESC) AS row_num
        FROM
            REPORTING_BASE_PROD.SHARED.PRODUCT_IMAGE_TEST_CONFIG_EXPORT
    )
    SELECT
        it.*,
        rr.EVALUATION_BATCH_ID AS LAST_EVALUATION_BATCH_ID,
        rr.EVALUATION_MESSAGE AS LAST_EVALUATION_MESSAGE
    FROM
        REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_IMAGE_TESTS  IT
    LEFT JOIN ranked_rows rr
    WHERE
        row_num = 1
    AND
        RR.MASTER_TEST_NUMBER=IT.MASTER_TEST_NUMBER
    ORDER BY IT.MASTER_TEST_NUMBER
);
-- From that, select latest PRODUCT_SKU if repeated
create or replace temporary TABLE _IMAGE_TESTING_IMAGE_TESTS_EXTRACT1 AS
   (WITH ranked_rows AS (
        SELECT
        MASTER_TEST_NUMBER,
        CONTEXT,
        REQUESTED_TEST_ID,
        MASTER_PRODUCT_ID,
        PRODUCT_SKU,
        MASTER_STORE_GROUP_ID,
        MEMBERSHIP_BRAND_ID,
        SAM_ID_CURRENT,
        SAM_ID_TEST,
        SORT_CURRENT,
        SORT_TEST,
        AEM_UUID_CURRENT,
        AEM_UUID_TEST,
        DATETIME_ADDED_SAM_CURRENT,
        DATETIME_ADDED_SAM_TEST,
        DATETIME_MODIFIED_SAM_CURRENT,
        DATETIME_MODIFIED_SAM_TEST,
        URL_LIST_CURRENT,
        URL_LIST_TEST,
        URL_CORE_CURRENT,
        URL_CORE_TEST,
        CONFIG_JSON,
        IMAGE_ID_CURRENT,
        IMAGE_ID_TEST,
        DATETIME_ADDED,
        LAST_EVALUATION_BATCH_ID,
        LAST_EVALUATION_MESSAGE,
        ROW_NUMBER() OVER (PARTITION BY PRODUCT_SKU ORDER BY MASTER_TEST_NUMBER DESC) AS row_num
    FROM _IMAGE_TESTING_IMAGE_TESTS_EXTRACT0)
        SELECT
            MASTER_TEST_NUMBER,
            CONTEXT,
            REQUESTED_TEST_ID,
            MASTER_PRODUCT_ID,
            PRODUCT_SKU,
            MASTER_STORE_GROUP_ID,
            MEMBERSHIP_BRAND_ID,
            SAM_ID_CURRENT,
            SAM_ID_TEST,
            SORT_CURRENT,
            SORT_TEST,
            AEM_UUID_CURRENT,
            AEM_UUID_TEST,
            DATETIME_ADDED_SAM_CURRENT,
            DATETIME_ADDED_SAM_TEST,
            DATETIME_MODIFIED_SAM_CURRENT,
            DATETIME_MODIFIED_SAM_TEST,
            URL_LIST_CURRENT,
            URL_LIST_TEST,
            URL_CORE_CURRENT,
            URL_CORE_TEST,
            CONFIG_JSON,
            IMAGE_ID_CURRENT,
            IMAGE_ID_TEST,
            DATETIME_ADDED,
            LAST_EVALUATION_BATCH_ID,
            LAST_EVALUATION_MESSAGE,
            ROW_NUM
FROM ranked_rows WHERE row_num = 1 ORDER BY MASTER_TEST_NUMBER);

alter table _IMAGE_TESTING_IMAGE_TESTS_EXTRACT1 drop column row_num;

create or replace transient table REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_IMAGE_TESTS_EXTRACT
as select
MASTER_TEST_NUMBER,
CONTEXT,
REQUESTED_TEST_ID,
MASTER_PRODUCT_ID,
PRODUCT_SKU,
MASTER_STORE_GROUP_ID,
MEMBERSHIP_BRAND_ID,
SAM_ID_CURRENT,
SAM_ID_TEST,
SORT_CURRENT,
SORT_TEST,
AEM_UUID_CURRENT,
AEM_UUID_TEST,
DATETIME_ADDED_SAM_CURRENT,
DATETIME_ADDED_SAM_TEST,
DATETIME_MODIFIED_SAM_CURRENT,
DATETIME_MODIFIED_SAM_TEST,
URL_LIST_CURRENT,
URL_LIST_TEST,
URL_CORE_CURRENT,
URL_CORE_TEST,
CONFIG_JSON,
IMAGE_ID_CURRENT,
IMAGE_ID_TEST,
DATETIME_ADDED,
LAST_EVALUATION_BATCH_ID,
LAST_EVALUATION_MESSAGE
from _IMAGE_TESTING_IMAGE_TESTS_EXTRACT1;
