use reporting_prod;
create or replace transient table REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_SAM_TESTABLE_SPI AS
SELECT DISTINCT
SORT1,
SAM_ID1,
IMAGE_ID1,
AEM_UUID1,
DATETIME_ADDED_SAM1,
URL_LIST1,
URL_CORE1,
DATETIME_MODIFIED_SAM1,
IMAGE_ID,
SAM_ID,
AEM_UUID,
MEMBERSHIP_BRAND_ID,
MASTER_STORE_GROUP_ID,
PRODUCT_NAME,
IS_ECAT,
IS_PLUS,
SORT,
DATETIME_ADDED_SAM,
DATETIME_MODIFIED_SAM,
JSON_BLOB,
_EFFECTIVE_FROM_DATE,
_EFFECTIVE_TO_DATE,
_IS_CURRENT,
_IS_DELETED,
META_CREATE_DATETIME,
META_UPDATE_DATETIME,
URL_LIST,
MPID,
STORE_ID,
PRODUCT_TYPE,
CURRENT_SHOWROOM_DATE,
URL_CORE,
TOTAL_IMPRESSIONS,
TOTAL_SALES
FROM (
SELECT T1.SORT as SORT1, T1.SAM_ID as SAM_ID1, T1.IMAGE_ID as IMAGE_ID1, T1.AEM_UUID as AEM_UUID1, T1.DATETIME_ADDED_SAM as DATETIME_ADDED_SAM1,
T1.url_list as url_list1,
T1.url_core as url_core1,
T1.DATETIME_MODIFIED_SAM as DATETIME_MODIFIED_SAM1,T2.*
    FROM REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_SAM_SPI T1
    JOIN REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_SAM_SPI T2
        ON T1.master_store_group_id = T2.master_store_group_id
        AND t1.membership_brand_id = t2.membership_brand_id
        AND T1.PRODUCT_NAME = T2.PRODUCT_NAME
        AND T1.MPID = T2.MPID
        AND T1.SORT < T2.SORT
        AND COALESCE(not TRIM(T1.JSON_BLOB:_source.exclude_from_image_test::TEXT),'true')='true'
        --AND T1.IS_TESTABLE = TRUE
        --AND T1.SORT = 1
        and T2.json_blob like '%uuid%'
        AND COALESCE(not TRIM(T2.JSON_BLOB:_source.exclude_from_image_test::TEXT),'true')= 'true'
        --AND T2.IS_TESTABLE = TRUE
);
