use reporting_prod;
CREATE OR REPLACE TEMPORARY TABLE _IMAGE_TESTING_NEW_FL_REQUESTS AS (
WITH max_values AS (
    SELECT
        COALESCE(MAX(PRODUCT_IMAGE_REQUEST_TEST_ID), 0) AS MAX_PRODUCT_IMAGE_REQUEST_TEST_ID,
        MAX(REQUESTED_TEST_ID) AS MAX_REQUESTED_TEST_ID
    FROM REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_REQUEST_IMAGE_TEST
)
    SELECT
        (max_values.MAX_REQUESTED_TEST_ID + flrq.PRODUCT_IMAGE_REQUEST_TEST_ID - max_values.MAX_PRODUCT_IMAGE_REQUEST_TEST_ID) AS REQUESTED_TEST_ID,
        TRUE AS NEW_REQUEST,
        flrq.SAM_ID_CURRENT,
        flrq.SAM_ID_TEST,
        flrq.SORT_CURRENT,
        flrq.SORT_TEST,
        flrq.DATETIME_ADDED,
        flrq.DATETIME_MODIFIED,
        flrq.STORE_GROUP_ID AS MASTER_STORE_GROUP_ID,
        flrq.SKU AS PRODUCT_SKU,
        flrq.MASTER_PRODUCT_ID,
        flrq.MEMBERSHIP_BRAND_ID,
        flrq.PRODUCT_IMAGE_REQUEST_TEST_ID
    FROM LAKE_FL.ULTRA_ROLLUP.PRODUCT_IMAGE_REQUEST_TEST flrq,
         max_values
    where flrq.PRODUCT_IMAGE_REQUEST_TEST_ID>MAX_PRODUCT_IMAGE_REQUEST_TEST_ID
);

--mark old records
UPDATE REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_REQUEST_IMAGE_TEST
SET NEW_REQUEST = False
WHERE REQUESTED_TEST_ID <= (
    SELECT MAX(REQUESTED_TEST_ID)
    FROM REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_REQUEST_IMAGE_TEST
)
AND NEW_REQUEST = True
AND REQUESTED_TEST_ID IN (
    SELECT REQUESTED_TEST_ID
    FROM REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_IMAGE_TESTS
);
--select count(*) from REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_REQUEST_IMAGE_TEST where NEW_REQUEST = True
INSERT INTO REPORTING_PROD.DATA_SCIENCE.IMAGE_TESTING_REQUEST_IMAGE_TEST
(
REQUESTED_TEST_ID,
NEW_REQUEST,
SAM_ID_CURRENT,
SAM_ID_TEST,
SORT_CURRENT,
SORT_TEST,
DATETIME_ADDED,
DATETIME_MODIFIED,
MASTER_STORE_GROUP_ID,
PRODUCT_SKU,
MASTER_PRODUCT_ID,
MEMBERSHIP_BRAND_ID,
PRODUCT_IMAGE_REQUEST_TEST_ID
)
select
REQUESTED_TEST_ID,
NEW_REQUEST,
SAM_ID_CURRENT,
SAM_ID_TEST,
SORT_CURRENT,
SORT_TEST,
DATETIME_ADDED,
DATETIME_MODIFIED,
MASTER_STORE_GROUP_ID,
PRODUCT_SKU,
MASTER_PRODUCT_ID,
MEMBERSHIP_BRAND_ID,
PRODUCT_IMAGE_REQUEST_TEST_ID
from _IMAGE_TESTING_NEW_FL_REQUESTS;
