CREATE OR REPLACE TEMPORARY TABLE _order_promo AS
SELECT a.business_unit,
       a.sub_brand,
       a.country,
       a.region,
       a.order_date,
       a.promo_code,
       a.promo_name,
       a.order_type,
       a.activating_offers,
       a.promo_goal,
       a.promo_group,
       a.promo_offer,
       a.credit_allowed,
       a.free_shipping_offer,
       a.free_trial_offer,
       a.ppcc,
       a.final_sale,
       a.promo_mini_cart_value,
       'Promo Orders'                      AS promo_order_flag,
       a.order_with_clearance_flag,
       a.order_with_markdown_flag,
       a.order_free_shipping_flag,
       a.promo_mapping,
       a.current_month_credit_billing_status,
       COUNT(DISTINCT a.order_id)          AS orders,
       SUM(b.total_qty_sold)               AS total_qty_sold,
       SUM(b.total_product_revenue)        AS total_product_revenue,
       SUM(b.total_cogs)                   AS total_cogs,
       SUM(b.total_cash_collected)         AS total_cash_collected,
       SUM(b.total_credit_redeemed_amount) AS total_credit_redeemed_amount,
       SUM(b.tokens_applied)               AS tokens_applied,
       SUM(b.total_subtotal_amount)        AS total_subtotal_amount,
       SUM(b.total_shipping_revenue)       AS total_shipping_revenue,
       SUM(b.total_discount)               AS total_discount,
       SUM(b.total_shipping_cost)          AS total_shipping_cost
FROM gfb.gfb011_promo_data_set b
     JOIN
     (SELECT DISTINCT a.order_id,
                      a.business_unit,
                      a.sub_brand,
                      a.country,
                      a.region,
                      a.order_date,
                      a.promo_code_1                     AS promo_code,
                      a.promo_1_promotion_name           AS promo_name,
                      a.order_type,
                      a.activating_offers,
                      a.promo_1_goal                     AS promo_goal,
                      a.promo_1_group                    AS promo_group,
                      a.promo_1_offer                    AS promo_offer,
                      a.promo_1_allow_membership_credits AS credit_allowed,
                      (CASE
                           WHEN a.promo_1_shipping_discount_percentage = 1 THEN 'Free Shipping'
                           ELSE 'No Free Shipping' END)  AS free_shipping_offer,
                      (CASE
                           WHEN a.promo_1_child_promo_classification = 'Free Trial' THEN 'Free Trial'
                           ELSE 'Not Free Trial' END)    AS free_trial_offer,
                      (CASE
                           WHEN a.promo_1_allow_prepaid_creditcard = 1 THEN 'PPCC Allowed'
                           ELSE 'PPCC Not Allowed' END)  AS ppcc,
                      (CASE
                           WHEN a.promo_1_exchanges_allowed = 1 OR a.promo_1_refunds_allowed = 1 THEN 'Not Final Sale'
                           ELSE 'Final Sale' END)        AS final_sale,
                      a.promo_1_min_cart_value           AS promo_mini_cart_value,
                      'Promo Orders'                     AS promo_order_flag,
                      a.order_with_clearance_flag,
                      a.order_with_markdown_flag,
                      a.order_free_shipping_flag,
                      a.promo_1_promo_mapping            AS promo_mapping,
                      a.current_month_credit_billing_status
      FROM gfb.gfb011_promo_data_set a
      WHERE a.promo_code_1 IS NOT NULL) a
     ON a.order_id = b.order_id
GROUP BY a.business_unit,
         a.sub_brand,
         a.country,
         a.region,
         a.order_date,
         a.promo_code,
         a.promo_name,
         a.order_type,
         a.activating_offers,
         a.promo_goal,
         a.promo_group,
         a.promo_offer,
         a.credit_allowed,
         a.free_shipping_offer,
         a.free_trial_offer,
         a.ppcc,
         a.final_sale,
         a.promo_mini_cart_value,
         a.order_with_clearance_flag,
         a.order_with_markdown_flag,
         a.order_free_shipping_flag,
         a.promo_mapping,
         a.current_month_credit_billing_status

UNION

SELECT a.business_unit,
       a.sub_brand,
       a.country,
       a.region,
       a.order_date,
       a.promo_code,
       a.promo_name,
       a.order_type,
       a.activating_offers,
       a.promo_goal,
       a.promo_group,
       a.promo_offer,
       a.credit_allowed,
       a.free_shipping_offer,
       a.free_trial_offer,
       a.ppcc,
       a.final_sale,
       a.promo_mini_cart_value,
       'Promo Orders'                      AS promo_order_flag,
       a.order_with_clearance_flag,
       a.order_with_markdown_flag,
       a.order_free_shipping_flag,
       a.promo_mapping,
       a.current_month_credit_billing_status,
       COUNT(DISTINCT a.order_id)          AS orders,
       SUM(b.total_qty_sold)               AS total_qty_sold,
       SUM(b.total_product_revenue)        AS total_product_revenue,
       SUM(b.total_cogs)                   AS total_cogs,
       SUM(b.total_cash_collected)         AS total_cash_collected,
       SUM(b.total_credit_redeemed_amount) AS total_credit_redeemed_amount,
       SUM(b.tokens_applied)               AS tokens_applied,
       SUM(b.total_subtotal_amount)        AS total_subtotal_amount,
       SUM(b.total_shipping_revenue)       AS total_shipping_revenue,
       SUM(b.total_discount)               AS total_discount,
       SUM(b.total_shipping_cost)          AS total_shipping_cost
FROM gfb.gfb011_promo_data_set b
     JOIN
     (SELECT DISTINCT a.order_id,
                      a.business_unit,
                      a.sub_brand,
                      a.country,
                      a.region,
                      a.order_date,
                      a.promo_code_2                     AS promo_code,
                      a.promo_2_promotion_name           AS promo_name,
                      a.order_type,
                      a.activating_offers,
                      a.promo_2_goal                     AS promo_goal,
                      a.promo_2_group                    AS promo_group,
                      a.promo_2_offer                    AS promo_offer,
                      a.promo_2_allow_membership_credits AS credit_allowed,
                      (CASE
                           WHEN a.promo_2_shipping_discount_percentage = 1 THEN 'Free Shipping'
                           ELSE 'No Free Shipping' END)  AS free_shipping_offer,
                      (CASE
                           WHEN a.promo_2_child_promo_classification = 'Free Trial' THEN 'Free Trial'
                           ELSE 'Not Free Trial' END)    AS free_trial_offer,
                      (CASE
                           WHEN a.promo_2_allow_prepaid_creditcard = 1 THEN 'PPCC Allowed'
                           ELSE 'PPCC Not Allowed' END)  AS ppcc,
                      (CASE
                           WHEN a.promo_2_exchanges_allowed = 1 OR a.promo_2_refunds_allowed = 1 THEN 'Not Final Sale'
                           ELSE 'Final Sale' END)        AS final_sale,
                      a.promo_2_min_cart_value           AS promo_mini_cart_value,
                      'Promo Orders'                     AS promo_order_flag,
                      a.order_with_clearance_flag,
                      a.order_with_markdown_flag,
                      a.order_free_shipping_flag,
                      a.promo_2_promo_mapping            AS promo_mapping,
                      a.current_month_credit_billing_status
      FROM gfb.gfb011_promo_data_set a
      WHERE a.promo_code_2 IS NOT NULL) a
     ON a.order_id = b.order_id
GROUP BY a.business_unit,
         a.sub_brand,
         a.country,
         a.region,
         a.order_date,
         a.promo_code,
         a.promo_name,
         a.order_type,
         a.activating_offers,
         a.promo_goal,
         a.promo_group,
         a.promo_offer,
         a.credit_allowed,
         a.free_shipping_offer,
         a.free_trial_offer,
         a.ppcc,
         a.final_sale,
         a.promo_mini_cart_value,
         a.order_with_clearance_flag,
         a.order_with_markdown_flag,
         a.order_free_shipping_flag,
         a.promo_mapping,
         a.current_month_credit_billing_status

UNION

SELECT a.business_unit,
       a.sub_brand,
       a.country,
       a.region,
       a.order_date,
       NULL                                AS promo_code,
       NULL                                AS promo_name,
       a.order_type,
       NULL,
       NULL                                AS promo_goal,
       NULL                                AS promo_group,
       NULL                                AS promo_offer,
       NULL                                AS credit_allowed,
       NULL                                AS free_shipping_offer,
       NULL                                AS free_trial_offer,
       NULL                                AS ppcc,
       NULL                                AS final_sale,
       NULL                                AS promo_mini_cart_value,
       'Non-Promo Orders'                  AS promo_order_flag,
       a.order_with_clearance_flag,
       a.order_with_markdown_flag,
       a.order_free_shipping_flag,
       NULL                                AS promo_mapping,
       a.current_month_credit_billing_status,
       COUNT(DISTINCT a.order_id)          AS orders,
       SUM(a.total_qty_sold)               AS total_qty_sold,
       SUM(a.total_product_revenue)        AS total_product_revenue,
       SUM(a.total_cogs)                   AS total_cogs,
       SUM(a.total_cash_collected)         AS total_cash_collected,
       SUM(a.total_credit_redeemed_amount) AS total_credit_redeemed_amount,
       SUM(a.tokens_applied)               AS tokens_applied,
       SUM(a.total_subtotal_amount)        AS total_subtotal_amount,
       SUM(a.total_shipping_revenue)       AS total_shipping_revenue,
       SUM(a.total_discount)               AS total_discount,
       SUM(a.total_shipping_cost)          AS total_shipping_cost
FROM gfb.gfb011_promo_data_set a
WHERE a.promo_code_by_order IS NULL
GROUP BY a.business_unit,
         a.sub_brand,
         a.country,
         a.region,
         a.order_date,
         a.order_type,
         a.order_with_clearance_flag,
         a.order_with_markdown_flag,
         a.order_free_shipping_flag,
         a.current_month_credit_billing_status;


CREATE OR REPLACE TRANSIENT TABLE gfb.gfb011_01_promo_code_order_data_set AS
SELECT opm.business_unit,
       opm.sub_brand,
       opm.country,
       opm.region,
       opm.order_date,
       opm.promo_code,
       opm.promo_name,
       opm.order_type,
       opm.activating_offers,
       opm.promo_goal,
       opm.promo_group,
       opm.promo_offer,
       opm.credit_allowed,
       opm.free_shipping_offer,
       opm.free_trial_offer,
       opm.ppcc,
       opm.final_sale,
       opm.promo_mini_cart_value,
       opm.order_with_clearance_flag,
       opm.order_with_markdown_flag,
       opm.order_free_shipping_flag,
       opm.promo_mapping,
       opm.current_month_credit_billing_status,
       opm.orders,
       opm.total_qty_sold               AS total_qty_sold,
       opm.total_product_revenue        AS total_product_revenue,
       opm.total_cogs                   AS total_cogs,
       opm.total_cash_collected         AS total_cash_collected,
       opm.total_credit_redeemed_amount AS total_credit_redeemed_amount,
       opm.tokens_applied,
       opm.total_subtotal_amount        AS total_subtotal_amount,
       opm.total_shipping_revenue       AS total_shipping_revenue,
       opm.total_discount               AS total_discount,
       opm.total_shipping_cost          AS total_shipping_cost
FROM _order_promo opm;
