CREATE OR REPLACE TRANSIENT TABLE gfb.pcvr_product_psource AS
SELECT session_start_date,
       store_brand,
       platform,
       psource,
       country,
       IFF(LOWER(country) IN ('us', 'ca'), 'North America', 'Europe') AS region,
       product_type,
       ses.product_id,
       is_activating,
       registration_session,
       registration_source,
       INITCAP(membership_status)                                     AS membership_status,
       SUM(ses.list_view_total)                                       AS list_view_total,
       SUM(ses.pdp_view_total)                                        AS pdp_view_total,
       SUM(ses.pa_total)                                              AS pa_total,
       SUM(ses.oc_total)                                              AS oc_total,
       SUM(ses.ss_pdp_view)                                           AS ss_pdp_view,
       SUM(ses.ss_product_added)                                      AS ss_product_added,
       SUM(ses.ss_product_ordered)                                    AS ss_product_ordered,
       CURRENT_TIMESTAMP::DATETIME                                    AS refresh_datetime,
       MAX(ses.max_received)                                          AS max_received,
       MAX(ses.max_received_app)                                      AS max_received_app
FROM gfb.pcvr_session_historical AS ses
WHERE ses.product_id IS NOT NULL
  AND ses.product_id <> ''
GROUP BY session_start_date,
         store_brand,
         platform,
         psource,
         country,
         product_type,
         ses.product_id,
         is_activating,
         registration_session,
         registration_source,
         INITCAP(membership_status);
