SET low_watermark_datetime = %(low_watermark)s :: TIMESTAMP_LTZ;


CREATE OR REPLACE TEMP TABLE _input_data as
select
    id,
    project_id,
    project_name,
    input_id,
    session_id,
    contact_id,
    organisation,
    input_text,
    type,
    source,
    reference,
    timestamp,
    flow_name,
    flow_parent_id,
    channel,
    in_handover_request,
    in_handover_conversation,
    output_id,
    locale_reference_id,
    locale_name,
    endpoint_url_token,
    endpoint_name,
    snapshot_id,
    snapshot_name,
    rating,
    rating_comment,
    input_data,
    input_data:numberMetaData:number::VARCHAR number_MetaDatanumber,
    input_data:numberMetaData:type::VARCHAR number_metadata_type,
    input_data:_cognigy:_voiceGateway2:json:cognigyConfig:disableTtsCache::VARCHAR disableTtsCache,
    input_data:_cognigy:_voiceGateway2:json:cognigyConfig:dtmf::VARCHAR dtmf,
    input_data:_cognigy:_voiceGateway2:json:cognigyConfig:user:noInputMode::VARCHAR noInputMode,
    input_data:_cognigy:_voiceGateway2:json:cognigyConfig:user:noInputRetries::VARCHAR noInputRetries,
    input_data:_cognigy:_voiceGateway2:json:cognigyConfig:user:noInputTimeout::VARCHAR noInputTimeout,
    input_data:_cognigy:_voiceGateway2:json:voiceGateway2Config:bargeIn:actionHook::VARCHAR voiceGateway2Config_actionHook,
    input_data:_cognigy:_voiceGateway2:json:voiceGateway2Config:bargeIn:dtmfBargein::VARCHAR dtmfBargein,
    input_data:_cognigy:_voiceGateway2:json:voiceGateway2Config:bargeIn:enable::VARCHAR enable,
    input_data:_cognigy:_voiceGateway2:json:voiceGateway2Config:recognizer:model::VARCHAR recognizer_model,
    input_data:_cognigy:_voiceGateway2:json:voiceGateway2Config:recognizer:punctuation::VARCHAR recognizer_punctuation,
    input_data:_cognigy:_voiceGateway2:json:voiceGateway2Config:recognizer:vad:enable::VARCHAR recognizer_enable,
    input_data:_cognigy:_voiceGateway2:json:voiceGateway2Config:sessionParams::VARCHAR sessionParams,
    input_data:_cognigy:_voiceGateway2:json:hangup:headers:"X-Reason"::VARCHAR hangup_x_Reason,
    input_data:_cognigy:_voiceGateway2:json:"sip:refer":actionHook::VARCHAR sip_refer_actionHook,
    input_data:_cognigy:_voiceGateway2:json:"sip:refer":headers:"X-Reason"::VARCHAR sip_refer_x_reason,
    input_data:_cognigy:_voiceGateway2:json:"sip:refer":referTo::VARCHAR referto,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:ttsVoice::VARCHAR ttsVoice,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:dtmfInterDigitTimeout::VARCHAR dtmfInterDigitTimeout,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:setActivityParams::VARCHAR setActivityParams,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:sttLanguage::VARCHAR sttLanguage,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:ttsLanguage::VARCHAR ttsLanguage,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:userNoInputRetries::VARCHAR userNoInputRetries,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:dtmfEnable::VARCHAR dtmfEnable,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:userNoInputTimeout::VARCHAR userNoInputTimeout,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:ttsVendor::VARCHAR ttsVendor,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:sttHints::VARCHAR sttHints,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:sttHintsDynamicHints::VARCHAR sttHintsDynamicHints, --
    input_data:_cognigy:_voiceGateway2:json.channelConfig:sttVendor::VARCHAR sttVendor,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:text::VARCHAR text,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:asrEnabled::VARCHAR asrEnabled,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:asrTimeout::VARCHAR asrTimeout,
    input_data:_cognigy:_voiceGateway2:json.channelConfig:ttsModel::VARCHAR ttsModel,
    input_data:response:result:result:customer_compensation_primary::VARCHAR customer_compensation_primary,
    input_data:response:result:result:membershipBrandID::VARCHAR membershipBrandID,
    input_data:response:result:result:membershipID::VARCHAR membershipID,
    input_data:response:result:result:storeID::VARCHAR storeID,
    input_data:response:result:result:credits::VARCHAR credits,
    input_data:response:result:result:customerID::VARCHAR customerID,
    input_data:response:result:result:lastname::VARCHAR lastname,
    input_data:response:result:result:allowCourtesyRefund::VARCHAR allowCourtesyRefund,
    input_data:response:result:result:cannotSkipReason::VARCHAR cannotSkipReason,
    input_data:response:result:result:saveMembershipOffer::VARCHAR saveMembershipOffer,
    input_data:response:result:result:customerLTVDecile::VARCHAR customerLTVDecile,
    input_data:response:result:result:membershipLoyalty::VARCHAR membershipLoyalty,
    input_data:response:result:result:email::VARCHAR email,
    input_data:response:result:result:firstname::VARCHAR response_firstname,
    input_data:response:result:result:isShippingDelay::VARCHAR isShippingDelay,
    input_data:response:result:result:membershipLevel::VARCHAR membershipLevel,
    input_data:response:result:result:saveSkipOffer::VARCHAR saveSkipOffer,
    input_data:response:result:result:daysSinceFirstActivation::VARCHAR daysSinceFirstActivation,
    input_data:response:result:result:allowCancelAfterSave::VARCHAR allowCancelAfterSave,
    input_data:response:result:result:membershipTypeID::VARCHAR membershipTypeID,
    input_data:response:result:result:membershipSince::VARCHAR membershipSince,
    input_data:response:result:result:cancel_segments_gms::VARCHAR cancel_segments_gms,
    input_data:response:result:result:rewardPoints::VARCHAR rewardPoints,
    input_data:response:result:result:membershipPrice::VARCHAR membershipPrice,
    input_data:response:result:result:membershipLastSkipped::VARCHAR membershipLastSkipped,
    input_data:response:result:result:customer_compensation_segment_primary::VARCHAR customer_compensation_segment_primary,
    input_data:response:result:result:eligible_save_offer::VARCHAR eligible_save_offer,
    input_data:response:result:result:customer_compensation_segment_secondary::VARCHAR customer_compensation_segment_secondary,
    input_data:response:result:result:membershipCollectionPreference::VARCHAR membershipCollectionPreference,
    input_data:response:result:result:allowCancelMembership::VARCHAR allowCancelMembership,
    input_data:response:result:result:allowCancelOrder::VARCHAR allowCancelOrder,
    input_data:response:result:result:canSkip::VARCHAR canSkip,
    input_data:response:result:result:customer_compensation_secondary::VARCHAR customer_compensation_secondary,
    input_data:response:result:result:allowSkip::VARCHAR allowSkip
FROM lake.cognigy.conversations
    WHERE meta_update_datetime > $low_watermark_datetime;


CREATE OR REPLACE TEMP TABLE _orders as
SELECT
    id,
    p.value::VARCHAR phone,
    o.value:datetimePlaced::VARCHAR datetimePlaced,
    o.value:orderID::VARCHAR orderID,
    o.value:type::VARCHAR order_type,
    o.value:paymentMethod::VARCHAR paymentMethod,
    o.value:paymentStatusCode::VARCHAR paymentStatusCode,
    o.value:subTotal::VARCHAR subTotal,
    o.value:tax::VARCHAR tax,
    o.value:shipping::VARCHAR shipping,
    o.value:tracking:carrier::VARCHAR carrier,
    o.value:tracking:number::VARCHAR tracking_number,
    o.value:tracking:status::VARCHAR status,
    o.value:firstname::VARCHAR order_firstname,
    o.value:membershipBrandID::VARCHAR order_membershipBrandID,
    o.value:total::VARCHAR total,
    o.value:processingStatusCode::VARCHAR processingStatusCode,
    o.value:currency::VARCHAR currency,
    o.value:datetimeEstimatedDelivery::VARCHAR datetimeEstimatedDelivery,
    o.value:shippingAddress:address1::VARCHAR address1,
    o.value:shippingAddress:address2::VARCHAR address2,
    o.value:shippingAddress:address3::VARCHAR address3,
    o.value:shippingAddress:address4::VARCHAR address4,
    o.value:shippingAddress:address5::VARCHAR address5,
    o.value:shippingAddress:address6::VARCHAR address6,
    o.value:shippingAddress:address7::VARCHAR address7,
    o.value:shippingAddress:address8::VARCHAR address8,
    o.value:shippingAddress:city::VARCHAR city,
    o.value:shippingAddress:country::VARCHAR shippingAddresscountry,
    o.value:shippingAddress:state::VARCHAR state,
    o.value:shippingAddress:zip::VARCHAR zip,
    o.value:canCancel::VARCHAR canCancel,
    o.value:itemCount::VARCHAR itemCount,
    o.value:credits::VARCHAR order_credits,
    o.value:datetimeShipped::VARCHAR datetimeShipped,
    o.value:discount::VARCHAR discount,
    o.value:lastname::VARCHAR order_lastname,
    o.value:refund:product::VARCHAR refund_product,
    o.value:refund:shipping::VARCHAR refund_shipping,
    o.value:refund:tax::VARCHAR refund_tax,
    o.value:refund:total::VARCHAR refund_total,
    i.value:item::VARCHAR item,
    i.value:orderLineID::VARCHAR orderLineID,
    i.value:price::VARCHAR price,
    i.value:product::VARCHAR product,
    i.value:quantity::VARCHAR quantity
from _input_data c
    ,lateral flatten(input=>parse_json(input_data), path=>'response.result.result:orders') o
    ,lateral flatten(input=>parse_json(input_data), path=>'response.result.result:phone') p
    ,lateral flatten(input=>o.value, path=>'items') i;


CREATE OR REPLACE TEMP TABLE _final AS
select
    coalesce(i.id, o.id) id,
    i.* exclude (id, input_data),
    o.* exclude (id)
from _input_data i
    LEFT JOIN _orders o ON i.id=o.id;


MERGE INTO reporting_prod.gms.cognigy_conversations t
    USING (
        SELECT *,
               hash(*) meta_row_hash,
               current_timestamp() meta_create_datetime,
               current_timestamp() meta_update_datetime
        FROM _final
        ) s ON equal_null(s.id, t.id)
            AND equal_null(s.phone, t.phone)
            AND equal_null(s.orderlineid, t.orderlineid)
WHEN NOT MATCHED
THEN INSERT (ID,PROJECT_ID,PROJECT_NAME,INPUT_ID,SESSION_ID,CONTACT_ID,ORGANISATION,INPUT_TEXT,TYPE,
    SOURCE,REFERENCE,TIMESTAMP,FLOW_NAME,FLOW_PARENT_ID,CHANNEL,IN_HANDOVER_REQUEST,IN_HANDOVER_CONVERSATION,OUTPUT_ID,
    LOCALE_REFERENCE_ID,LOCALE_NAME,ENDPOINT_URL_TOKEN,ENDPOINT_NAME,SNAPSHOT_ID,SNAPSHOT_NAME,RATING,RATING_COMMENT,
    NUMBER_METADATANUMBER,NUMBER_METADATA_TYPE,DISABLETTSCACHE,DTMF,NOINPUTMODE,NOINPUTRETRIES,NOINPUTTIMEOUT,
    VOICEGATEWAY2CONFIG_ACTIONHOOK,DTMFBARGEIN,ENABLE,RECOGNIZER_MODEL,RECOGNIZER_PUNCTUATION,RECOGNIZER_ENABLE,
    SESSIONPARAMS,HANGUP_X_REASON,SIP_REFER_ACTIONHOOK,SIP_REFER_X_REASON,REFERTO,TTSVOICE,
    DTMFINTERDIGITTIMEOUT,SETACTIVITYPARAMS,STTLANGUAGE,TTSLANGUAGE,USERNOINPUTRETRIES,DTMFENABLE,USERNOINPUTTIMEOUT,
    TTSVENDOR,STTHINTS,STTHINTSDYNAMICHINTS,STTVENDOR,TEXT,ASRENABLED,ASRTIMEOUT,TTSMODEL,CUSTOMER_COMPENSATION_PRIMARY,
    MEMBERSHIPBRANDID,MEMBERSHIPID,STOREID,CREDITS,CUSTOMERID,LASTNAME,ALLOWCOURTESYREFUND,CANNOTSKIPREASON,
    SAVEMEMBERSHIPOFFER,CUSTOMERLTVDECILE,MEMBERSHIPLOYALTY,EMAIL,RESPONSE_FIRSTNAME,ISSHIPPINGDELAY,MEMBERSHIPLEVEL,
    SAVESKIPOFFER,DAYSSINCEFIRSTACTIVATION,ALLOWCANCELAFTERSAVE,MEMBERSHIPTYPEID,MEMBERSHIPSINCE,CANCEL_SEGMENTS_GMS,
    REWARDPOINTS,MEMBERSHIPPRICE,MEMBERSHIPLASTSKIPPED,CUSTOMER_COMPENSATION_SEGMENT_PRIMARY,ELIGIBLE_SAVE_OFFER,
    CUSTOMER_COMPENSATION_SEGMENT_SECONDARY,MEMBERSHIPCOLLECTIONPREFERENCE,ALLOWCANCELMEMBERSHIP,ALLOWCANCELORDER,
    CANSKIP,CUSTOMER_COMPENSATION_SECONDARY,ALLOWSKIP,PHONE,DATETIMEPLACED,ORDERID,ORDER_TYPE,PAYMENTMETHOD,
    PAYMENTSTATUSCODE,SUBTOTAL,TAX,SHIPPING,CARRIER,TRACKING_NUMBER,STATUS,ORDER_FIRSTNAME,ORDER_MEMBERSHIPBRANDID,
    TOTAL,PROCESSINGSTATUSCODE,CURRENCY,DATETIMEESTIMATEDDELIVERY,ADDRESS1,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,
    ADDRESS7,ADDRESS8,CITY,SHIPPINGADDRESSCOUNTRY,STATE,ZIP,CANCANCEL,ITEMCOUNT,ORDER_CREDITS,DATETIMESHIPPED,DISCOUNT,
    ORDER_LASTNAME,REFUND_PRODUCT,REFUND_SHIPPING,REFUND_TAX,REFUND_TOTAL,ITEM,ORDERLINEID,PRICE,PRODUCT,QUANTITY,
    meta_row_hash,meta_create_datetime,meta_update_datetime)
VALUES (ID,PROJECT_ID,PROJECT_NAME,INPUT_ID,SESSION_ID,CONTACT_ID,ORGANISATION,INPUT_TEXT,TYPE,
    SOURCE,REFERENCE,TIMESTAMP,FLOW_NAME,FLOW_PARENT_ID,CHANNEL,IN_HANDOVER_REQUEST,IN_HANDOVER_CONVERSATION,OUTPUT_ID,
    LOCALE_REFERENCE_ID,LOCALE_NAME,ENDPOINT_URL_TOKEN,ENDPOINT_NAME,SNAPSHOT_ID,SNAPSHOT_NAME,RATING,RATING_COMMENT,
    NUMBER_METADATANUMBER,NUMBER_METADATA_TYPE,DISABLETTSCACHE,DTMF,NOINPUTMODE,NOINPUTRETRIES,NOINPUTTIMEOUT,
    VOICEGATEWAY2CONFIG_ACTIONHOOK,DTMFBARGEIN,ENABLE,RECOGNIZER_MODEL,RECOGNIZER_PUNCTUATION,RECOGNIZER_ENABLE,
    SESSIONPARAMS,HANGUP_X_REASON,SIP_REFER_ACTIONHOOK,SIP_REFER_X_REASON,REFERTO,TTSVOICE,
    DTMFINTERDIGITTIMEOUT,SETACTIVITYPARAMS,STTLANGUAGE,TTSLANGUAGE,USERNOINPUTRETRIES,DTMFENABLE,USERNOINPUTTIMEOUT,
    TTSVENDOR,STTHINTS,STTHINTSDYNAMICHINTS,STTVENDOR,TEXT,ASRENABLED,ASRTIMEOUT,TTSMODEL,CUSTOMER_COMPENSATION_PRIMARY,
    MEMBERSHIPBRANDID,MEMBERSHIPID,STOREID,CREDITS,CUSTOMERID,LASTNAME,ALLOWCOURTESYREFUND,CANNOTSKIPREASON,
    SAVEMEMBERSHIPOFFER,CUSTOMERLTVDECILE,MEMBERSHIPLOYALTY,EMAIL,RESPONSE_FIRSTNAME,ISSHIPPINGDELAY,MEMBERSHIPLEVEL,
    SAVESKIPOFFER,DAYSSINCEFIRSTACTIVATION,ALLOWCANCELAFTERSAVE,MEMBERSHIPTYPEID,MEMBERSHIPSINCE,CANCEL_SEGMENTS_GMS,
    REWARDPOINTS,MEMBERSHIPPRICE,MEMBERSHIPLASTSKIPPED,CUSTOMER_COMPENSATION_SEGMENT_PRIMARY,ELIGIBLE_SAVE_OFFER,
    CUSTOMER_COMPENSATION_SEGMENT_SECONDARY,MEMBERSHIPCOLLECTIONPREFERENCE,ALLOWCANCELMEMBERSHIP,ALLOWCANCELORDER,
    CANSKIP,CUSTOMER_COMPENSATION_SECONDARY,ALLOWSKIP,PHONE,DATETIMEPLACED,ORDERID,ORDER_TYPE,PAYMENTMETHOD,
    PAYMENTSTATUSCODE,SUBTOTAL,TAX,SHIPPING,CARRIER,TRACKING_NUMBER,STATUS,ORDER_FIRSTNAME,ORDER_MEMBERSHIPBRANDID,
    TOTAL,PROCESSINGSTATUSCODE,CURRENCY,DATETIMEESTIMATEDDELIVERY,ADDRESS1,ADDRESS2,ADDRESS3,ADDRESS4,ADDRESS5,ADDRESS6,
    ADDRESS7,ADDRESS8,CITY,SHIPPINGADDRESSCOUNTRY,STATE,ZIP,CANCANCEL,ITEMCOUNT,ORDER_CREDITS,DATETIMESHIPPED,DISCOUNT,
    ORDER_LASTNAME,REFUND_PRODUCT,REFUND_SHIPPING,REFUND_TAX,REFUND_TOTAL,ITEM,ORDERLINEID,PRICE,PRODUCT,QUANTITY,
    META_ROW_HASH,META_CREATE_DATETIME,META_UPDATE_DATETIME)
WHEN MATCHED AND t.meta_row_hash != s.meta_row_hash
    THEN UPDATE SET t.project_id=s.project_id,
                    t.project_name=s.project_name,
                    t.input_id=s.input_id,
                    t.session_id=s.session_id,
                    t.contact_id=s.contact_id,
                    t.organisation=s.organisation,
                    t.input_text=s.input_text,
                    t.type=s.type,
                    t.source=s.source,
                    t.reference=s.reference,
                    t.timestamp=s.timestamp,
                    t.flow_name=s.flow_name,
                    t.flow_parent_id=s.flow_parent_id,
                    t.channel=s.channel,
                    t.in_handover_request=s.in_handover_request,
                    t.in_handover_conversation=s.in_handover_conversation,
                    t.output_id=s.output_id,
                    t.locale_reference_id=s.locale_reference_id,
                    t.locale_name=s.locale_name,
                    t.endpoint_url_token=s.endpoint_url_token,
                    t.endpoint_name=s.endpoint_name,
                    t.snapshot_id=s.snapshot_id,
                    t.snapshot_name=s.snapshot_name,
                    t.rating=s.rating,
                    t.rating_comment=s.rating_comment,
                    t.number_metadatanumber=s.number_metadatanumber,
                    t.number_metadata_type=s.number_metadata_type,
                    t.disablettscache=s.disablettscache,
                    t.dtmf=s.dtmf,
                    t.noinputmode=s.noinputmode,
                    t.noinputretries=s.noinputretries,
                    t.noinputtimeout=s.noinputtimeout,
                    t.voicegateway2config_actionhook=s.voicegateway2config_actionhook,
                    t.dtmfbargein=s.dtmfbargein,
                    t.enable=s.enable,
                    t.recognizer_model=s.recognizer_model,
                    t.recognizer_punctuation=s.recognizer_punctuation,
                    t.recognizer_enable=s.recognizer_enable,
                    t.sessionparams=s.sessionparams,
                    t.hangup_x_reason=s.hangup_x_reason,
                    t.sip_refer_actionhook=s.sip_refer_actionhook,
                    t.sip_refer_x_reason=s.sip_refer_x_reason,
                    t.referto=s.referto,
                    t.ttsvoice=s.ttsvoice,
                    t.dtmfinterdigittimeout=s.dtmfinterdigittimeout,
                    t.setactivityparams=s.setactivityparams,
                    t.sttlanguage=s.sttlanguage,
                    t.ttslanguage=s.ttslanguage,
                    t.usernoinputretries=s.usernoinputretries,
                    t.dtmfenable=s.dtmfenable,
                    t.usernoinputtimeout=s.usernoinputtimeout,
                    t.ttsvendor=s.ttsvendor,
                    t.stthints=s.stthints,
                    t.stthintsdynamichints=s.stthintsdynamichints,
                    t.sttvendor=s.sttvendor,
                    t.text=s.text,
                    t.asrenabled=s.asrenabled,
                    t.asrtimeout=s.asrtimeout,
                    t.ttsmodel=s.ttsmodel,
                    t.customer_compensation_primary=s.customer_compensation_primary,
                    t.membershipbrandid=s.membershipbrandid,
                    t.membershipid=s.membershipid,
                    t.storeid=s.storeid,
                    t.credits=s.credits,
                    t.customerid=s.customerid,
                    t.lastname=s.lastname,
                    t.allowcourtesyrefund=s.allowcourtesyrefund,
                    t.cannotskipreason=s.cannotskipreason,
                    t.savemembershipoffer=s.savemembershipoffer,
                    t.customerltvdecile=s.customerltvdecile,
                    t.membershiployalty=s.membershiployalty,
                    t.email=s.email,
                    t.response_firstname=s.response_firstname,
                    t.isshippingdelay=s.isshippingdelay,
                    t.membershiplevel=s.membershiplevel,
                    t.saveskipoffer=s.saveskipoffer,
                    t.dayssincefirstactivation=s.dayssincefirstactivation,
                    t.allowcancelaftersave=s.allowcancelaftersave,
                    t.membershiptypeid=s.membershiptypeid,
                    t.membershipsince=s.membershipsince,
                    t.cancel_segments_gms=s.cancel_segments_gms,
                    t.rewardpoints=s.rewardpoints,
                    t.membershipprice=s.membershipprice,
                    t.membershiplastskipped=s.membershiplastskipped,
                    t.customer_compensation_segment_primary=s.customer_compensation_segment_primary,
                    t.eligible_save_offer=s.eligible_save_offer,
                    t.customer_compensation_segment_secondary=s.customer_compensation_segment_secondary,
                    t.membershipcollectionpreference=s.membershipcollectionpreference,
                    t.allowcancelmembership=s.allowcancelmembership,
                    t.allowcancelorder=s.allowcancelorder,
                    t.canskip=s.canskip,
                    t.customer_compensation_secondary=s.customer_compensation_secondary,
                    t.allowskip=s.allowskip,
                    t.datetimeplaced=s.datetimeplaced,
                    t.orderid=s.orderid,
                    t.order_type=s.order_type,
                    t.paymentmethod=s.paymentmethod,
                    t.paymentstatuscode=s.paymentstatuscode,
                    t.subtotal=s.subtotal,
                    t.tax=s.tax,
                    t.shipping=s.shipping,
                    t.carrier=s.carrier,
                    t.tracking_number=s.tracking_number,
                    t.status=s.status,
                    t.order_firstname=s.order_firstname,
                    t.order_membershipbrandid=s.order_membershipbrandid,
                    t.total=s.total,
                    t.processingstatuscode=s.processingstatuscode,
                    t.currency=s.currency,
                    t.datetimeestimateddelivery=s.datetimeestimateddelivery,
                    t.address1=s.address1,
                    t.address2=s.address2,
                    t.address3=s.address3,
                    t.address4=s.address4,
                    t.address5=s.address5,
                    t.address6=s.address6,
                    t.address7=s.address7,
                    t.address8=s.address8,
                    t.city=s.city,
                    t.shippingaddresscountry=s.shippingaddresscountry,
                    t.state=s.state,
                    t.zip=s.zip,
                    t.cancancel=s.cancancel,
                    t.itemcount=s.itemcount,
                    t.order_credits=s.order_credits,
                    t.datetimeshipped=s.datetimeshipped,
                    t.discount=s.discount,
                    t.order_lastname=s.order_lastname,
                    t.refund_product=s.refund_product,
                    t.refund_shipping=s.refund_shipping,
                    t.refund_tax=s.refund_tax,
                    t.refund_total=s.refund_total,
                    t.item=s.item,
                    t.price=s.price,
                    t.product=s.product,
                    t.quantity=s.quantity,
                    t.meta_row_hash=s.meta_row_hash,
                    t.meta_update_datetime=s.meta_update_datetime;
