CREATE TABLE IF NOT EXISTS reporting_prod.gsc.air_dsr
(
    origin                         STRING,
    destination                    STRING,
    vendor                         STRING,
    booking_request_number         STRING,
    cargo_ready_date               DATE,
    cargo_received_date            DATE,
    document_received_date         DATE,
    po_number                      STRING,
    destination_city               STRING,
    flight_number                  STRING,
    mawb_mbl_number                STRING,
    hawb_hbl_number                STRING,
    outer_pieces                   STRING,
    inner_pieces                   STRING,
    gross_weight_kg                STRING,
    chargeable_weight_kg           STRING,
    cmb                            STRING,
    vessel_depart_at_port_estimate DATE,
    vessel_depart_at_port_actual   DATE,
    vessel_arrive_at_port_estimate DATE,
    vessel_arrive_at_port_actual   DATE,
    planned_delivery_date          DATE,
    pod_date                       DATE,
    pod_name                       STRING,
    comments                       STRING,
    edi_origin                     STRING,
    edi_destination                STRING,
    invoiced                       STRING,
    meta_create_datetime           TIMESTAMP_LTZ(3) DEFAULT current_timestamp(3),
    meta_update_datetime           TIMESTAMP_LTZ(3) DEFAULT current_timestamp(3),
    PRIMARY KEY (po_number)
);

CREATE TABLE IF NOT EXISTS reporting_prod.gsc.air_dsr_stg
(
    origin                  STRING,
    destination             STRING,
    vendor                  STRING,
    booking_request_number  STRING,
    cargo_ready_date        STRING,
    cargo_received_date     STRING,
    document_received_date  STRING,
    po_number               STRING,
    destination_city        STRING,
    flight_number           STRING,
    mawb_mbl_number         STRING,
    hawb_hbl_number         STRING,
    outer_pieces            STRING,
    inner_pieces            STRING,
    gross_weight_kg         STRING,
    chargeable_weight_kg    STRING,
    cmb                     STRING,
    etd_origin_airport_date STRING,
    atd_origin_airport_date STRING,
    eta_destination_airport STRING,
    ata_destination_airport STRING,
    planned_delivery_date   STRING,
    pod_date                STRING,
    pod_name                STRING,
    comments                STRING,
    edi_origin              STRING,
    edi_destination         STRING,
    invoiced                STRING,
    file_name               STRING,
    file_date               DATE
);

DELETE
FROM reporting_prod.gsc.air_dsr_stg;

COPY INTO reporting_prod.gsc.air_dsr_stg
    FROM (SELECT DISTINCT $1                                                            AS origin,
                          $2                                                            AS destination,
                          $3                                                            AS vendor,
                          $4                                                            AS booking_request_number,
                          $5                                                            AS cargo_ready_date,
                          $6                                                            AS cargo_received_date,
                          $7                                                            AS document_received_date,
                          $8                                                            AS po_number,
                          $9                                                            AS destination_city,
                          $10                                                           AS flight_number,
                          $11                                                           AS mawb_mbl_number,
                          $12                                                           AS hawb_hbl_number,
                          $13                                                           AS outer_pieces,
                          $14                                                           AS inner_pieces,
                          $15                                                           AS gross_weight_kg,
                          $16                                                           AS chargeable_weight_kg,
                          $17                                                           AS cmb,
                          $18                                                           AS etd_origin_airport_date,
                          $19                                                           AS atd_origin_airport_date,
                          $20                                                           AS eta_destination_airport,
                          $21                                                           AS ata_destination_airport,
                          $22                                                           AS planned_delivery_date,
                          $23                                                           AS pod_date,
                          $24                                                           AS pod_name,
                          $25                                                           AS comments,
                          $26                                                           AS edi_origin,
                          $27                                                           AS edi_destination,
                          $28                                                           AS invoiced,
                          metadata$filename                                             AS file_name,
                          TRY_TO_DATE(split_part(split_part(metadata$filename, '/', -1), '_', 5),'yyyymmdd') AS file_date
          FROM '@lake_stg.public.tsos_da_int_inbound/lake/gsc.air_dsr/v2/')
    FILE_FORMAT = (
        TYPE = CSV,
        FIELD_DELIMITER = ',',
        RECORD_DELIMITER = '\n',
        FIELD_OPTIONALLY_ENCLOSED_BY = '"',
        SKIP_HEADER = 1,
        ESCAPE_UNENCLOSED_FIELD = NONE,
        REPLACE_INVALID_CHARACTERS = TRUE,
        NULL_IF = ('')
        )
    ON_ERROR = 'SKIP_FILE_1%';

CREATE OR REPLACE TEMP TABLE _reporting_air_dsr_stg AS
SELECT TRIM(origin)                                                                                         AS origin,
       TRIM(destination)                                                                                    AS destination,
       TRIM(vendor)                                                                                         AS vendor,
       ltrim(replace(replace(booking_request_number, '�'), '\''), 0) AS booking_request_number,
       COALESCE(TRY_TO_DATE(cargo_ready_date, 'mm/dd/yyyy'), '1900-01-01')                                  AS cargo_ready_date,
       COALESCE(TRY_TO_DATE(cargo_received_date, 'mm/dd/yyyy'),
                '1900-01-01')                                                                               AS cargo_received_date,
       COALESCE(TRY_TO_DATE(document_received_date, 'mm/dd/yyyy'),
                '1900-01-01')                                                                               AS document_received_date,
       TRIM(po_number)                                                                                      AS po_number,
       TRIM(destination_city)                                                                               AS destination_city,
       TRIM(flight_number)                                                                                  AS flight_number,
       TRIM(mawb_mbl_number)                                                                                AS mawb_mbl_number,
       TRIM(hawb_hbl_number)                                                                                AS hawb_hbl_number,
       outer_pieces,
       inner_pieces,
       gross_weight_kg,
       chargeable_weight_kg,
       cmb,
       COALESCE(TRY_TO_DATE(etd_origin_airport_date, 'mm/dd/yy hh:mi'),
                TRY_TO_DATE(etd_origin_airport_date, 'mm/dd/yyyy'),
                '1900-01-01')                                                                               AS vessel_depart_at_port_estimate,
       COALESCE(TRY_TO_DATE(atd_origin_airport_date, 'mm/dd/yy hh:mi'),
                TRY_TO_DATE(atd_origin_airport_date, 'mm/dd/yyyy'),
                '1900-01-01')                                                                               AS vessel_depart_at_port_actual,
       COALESCE(TRY_TO_DATE(eta_destination_airport, 'mm/dd/yyyy'),
                TRY_TO_DATE(eta_destination_airport, 'mm/dd/yy hh:mi'),
                '1900-01-01')                                                                               AS vessel_arrive_at_port_estimate,
       COALESCE(TRY_TO_DATE(ata_destination_airport, 'mm/dd/yyyy'),
                TRY_TO_DATE(ata_destination_airport, 'mm/dd/yy hh:mi'),
                '1900-01-01')                                                                               AS vessel_arrive_at_port_actual,
       COALESCE(TRY_TO_DATE(planned_delivery_date, 'mm/dd/yyyy'), TRY_TO_DATE(planned_delivery_date, 'mm/dd/yy hh:mi'),
                TRY_TO_DATE(planned_delivery_date, 'mm/dd/yyyy hhmi'),
                '1900-01-01')                                                                               AS planned_delivery_date,
       COALESCE(TRY_TO_DATE(pod_date, 'mm/dd/yyyy'), TRY_TO_DATE(pod_date, 'mm/dd/yy hh:mi'), '1900-01-01') AS pod_date,
       TRIM(pod_name)                                                                                       AS pod_name,
       TRIM(comments)                                                                                       AS comments,
       TRIM(edi_origin)                                                                                     AS edi_origin,
       TRIM(edi_destination)                                                                                AS edi_destination,
       TRIM(invoiced)                                                                                       AS invoiced,
       file_name,
       file_date
FROM reporting_prod.gsc.air_dsr_stg
WHERE po_number IS NOT NULL;

MERGE INTO reporting_prod.gsc.air_dsr t
    USING (
        SELECT a.*
        FROM (
                 SELECT *,
                        current_timestamp                                                                           AS meta_create_datetime,
                        current_timestamp                                                                           AS meta_update_datetime,
                        row_number()
                                OVER (PARTITION BY po_number ORDER BY COALESCE(file_date, '1900-01-01') DESC )      AS rn
                 FROM _reporting_air_dsr_stg
             ) a
        WHERE a.rn = 1
    ) s ON equal_null(t.po_number, s.po_number)
    WHEN NOT MATCHED THEN INSERT (
                                  origin, destination, vendor, booking_request_number, cargo_ready_date,
                                  cargo_received_date, document_received_date, po_number, destination_city,
                                  flight_number, mawb_mbl_number, hawb_hbl_number, outer_pieces, inner_pieces,
                                  gross_weight_kg, chargeable_weight_kg, cmb, vessel_depart_at_port_estimate,
                                  vessel_depart_at_port_actual, vessel_arrive_at_port_estimate,
                                  vessel_arrive_at_port_actual, planned_delivery_date, pod_date, pod_name, comments,
                                  edi_origin, edi_destination, invoiced, meta_create_datetime, meta_update_datetime
        )
        VALUES (origin, destination, vendor, booking_request_number, cargo_ready_date, cargo_received_date,
                document_received_date, po_number, destination_city, flight_number, mawb_mbl_number, hawb_hbl_number,
                outer_pieces, inner_pieces, gross_weight_kg, chargeable_weight_kg, cmb, vessel_depart_at_port_estimate,
                vessel_depart_at_port_actual, vessel_arrive_at_port_estimate, vessel_arrive_at_port_actual,
                planned_delivery_date, pod_date, pod_name, comments, edi_origin, edi_destination, invoiced,
                meta_create_datetime, meta_update_datetime)
    WHEN MATCHED THEN UPDATE
        SET t.origin = s.origin,
            t.destination = s.destination,
            t.vendor = s.vendor,
            t.booking_request_number = s.booking_request_number,
            t.cargo_ready_date = s.cargo_ready_date,
            t.cargo_received_date = s.cargo_received_date,
            t.document_received_date = s.document_received_date,
            t.po_number = s.po_number,
            t.destination_city = s.destination_city,
            t.flight_number = s.flight_number,
            t.mawb_mbl_number = s.mawb_mbl_number,
            t.hawb_hbl_number = s.hawb_hbl_number,
            t.outer_pieces = s.outer_pieces,
            t.inner_pieces = s.inner_pieces,
            t.gross_weight_kg = s.gross_weight_kg,
            t.chargeable_weight_kg = s.chargeable_weight_kg,
            t.cmb = s.cmb,
            t.vessel_depart_at_port_estimate = s.vessel_depart_at_port_estimate,
            t.vessel_depart_at_port_actual = s.vessel_depart_at_port_actual,
            t.vessel_arrive_at_port_estimate = s.vessel_arrive_at_port_estimate,
            t.vessel_arrive_at_port_actual = s.vessel_arrive_at_port_actual,
            t.planned_delivery_date = s.planned_delivery_date,
            t.pod_date = s.pod_date,
            t.pod_name = s.pod_name,
            t.comments = s.comments,
            t.edi_origin = s.edi_origin,
            t.edi_destination = s.edi_destination,
            t.invoiced = s.invoiced,
            t.meta_update_datetime = s.meta_update_datetime;
