CREATE TABLE IF NOT EXISTS reporting_prod.retail.fl_pos_snapshot
(
    STORE_CODE VARCHAR(50),
    DATE VARCHAR(50),
    SLOT VARCHAR(50),
    ORDER_COUNT NUMBER(19,0),
    PRODUCT_GROSS_REVENUE NUMBER(38,10),
    UNIT_COUNT NUMBER(38,0),
    REFUND_ORDERS NUMBER(18,0),
    PRODUCT_REFUND NUMBER(38,10),
    REFUND_UNITS NUMBER(38,0),
    ACTIVATING_VIP_ORDER_COUNT NUMBER(18,0),
    GUEST_ORDER_COUNT NUMBER(19,0),
    REPEAT_VIP_ORDER_COUNT NUMBER(18,0),
    GROSS_MARGIN NUMBER(38,12),
    SNAPSHOT_DATETIME TIMESTAMP_LTZ(9)
);

INSERT INTO reporting_prod.retail.fl_pos_snapshot 
(STORE_CODE,DATE,SLOT,ORDER_COUNT,PRODUCT_GROSS_REVENUE,UNIT_COUNT,REFUND_ORDERS,
PRODUCT_REFUND,REFUND_UNITS,ACTIVATING_VIP_ORDER_COUNT,GUEST_ORDER_COUNT,REPEAT_VIP_ORDER_COUNT,
GROSS_MARGIN,SNAPSHOT_DATETIME)
select
    STORE_CODE,
    TO_CHAR(DATE,'DD/MM/YYYY') AS DATE,
    TO_CHAR(SLOT,'HH24:MI') AS SLOT,
    SUM(ORDER_COUNT) AS ORDER_COUNT,
    SUM(PRODUCT_GROSS_REVENUE)::NUMBER(19,2) AS PRODUCT_GROSS_REVENUE,
    SUM(UNIT_COUNT) AS UNIT_COUNT,
    SUM(REFUND_ORDERS) AS REFUND_ORDERS,
    SUM(PRODUCT_REFUND)::NUMBER(19,2) AS PRODUCT_REFUND,
    SUM(REFUND_UNITS) AS REFUND_UNITS,
    SUM(ACTIVATING_ORDER_COUNT) AS ACTIVATING_VIP_ORDER_COUNT,
    SUM(GUEST_ORDER_COUNT) AS GUEST_ORDER_COUNT,
    SUM(REPEAT_VIP_ORDER_COUNT) AS REPEAT_VIP_ORDER_COUNT,
    SUM(GROSS_MARGIN) AS GROSS_MARGIN,
    CURRENT_TIMESTAMP AS 	SNAPSHOT_DATETIME
from reporting_prod.retail.realtime_edw
WHERE EVENT_STORE_BRAND='Fabletics' AND EVENT_STORE_LOCATION='Retail'
group by STORE_CODE,
        DATE,
        SLOT
ORDER BY STORE_CODE,
        DATE,
        SLOT;

delete from reporting_prod.retail.fl_pos_snapshot
where  SNAPSHOT_DATETIME < DATEADD(month, -3, TO_DATE(SNAPSHOT_DATETIME));        