CREATE TABLE IF NOT EXISTS reporting_prod.retail.sxf_employeesales_snapshot
(
    STORE_CODE VARCHAR(50),
    EMPLOYEE_NUMBER VARCHAR(50),
    DATE VARCHAR(50),
    ORDER_COUNT NUMBER(19,0),
    PRODUCT_GROSS_REVENUE NUMBER(38,10),
    UNIT_COUNT NUMBER(38,0),
    REFUND_ORDERS NUMBER(18,0),
    PRODUCT_REFUND NUMBER(38,10),
    REFUND_UNITS NUMBER(38,0),
    ACTIVATING_VIP_ORDER_COUNT NUMBER(18,0),
    GUEST_ORDER_COUNT NUMBER(19,0),
    REPEAT_VIP_ORDER_COUNT NUMBER(18,0),
    SNAPSHOT_DATETIME TIMESTAMP_LTZ(9)
);

INSERT INTO reporting_prod.retail.sxf_employeesales_snapshot 
(STORE_CODE,EMPLOYEE_NUMBER,DATE,ORDER_COUNT,PRODUCT_GROSS_REVENUE,UNIT_COUNT,REFUND_ORDERS,
PRODUCT_REFUND,REFUND_UNITS,ACTIVATING_VIP_ORDER_COUNT,GUEST_ORDER_COUNT,REPEAT_VIP_ORDER_COUNT
,SNAPSHOT_DATETIME)
select
    CONCAT('SXF-',STORE_CODE) as STORE_CODE,
    EMPLOYEE_NUMBER,
    TO_CHAR(DATE,'DD/MM/YYYY') AS DATE,
    SUM(ORDER_COUNT) AS ORDER_COUNT,
    SUM(PRODUCT_GROSS_REVENUE)::NUMBER(19,2) AS PRODUCT_GROSS_REVENUE,
    SUM(UNIT_COUNT) AS UNIT_COUNT,
    SUM(REFUND_ORDERS) AS REFUND_ORDERS,
    SUM(PRODUCT_REFUND)::NUMBER(19,2) AS PRODUCT_REFUND,
    SUM(REFUND_UNITS) AS REFUND_UNITS,
    SUM(ACTIVATING_ORDER_COUNT) AS ACTIVATING_VIP_ORDER_COUNT,
    SUM(GUEST_ORDER_COUNT) AS GUEST_ORDER_COUNT,
    SUM(REPEAT_VIP_ORDER_COUNT) AS REPEAT_VIP_ORDER_COUNT,
    CURRENT_TIMESTAMP AS SNAPSHOT_DATETIME
from reporting_prod.retail.realtime_edw
WHERE EVENT_STORE_BRAND='Savage X' AND EVENT_STORE_LOCATION='Retail'
    and EMPLOYEE_NUMBER <> '-1'
group by     CONCAT('SXF-',STORE_CODE),
    EMPLOYEE_NUMBER,
    DATE
ORDER BY     CONCAT('SXF-',STORE_CODE),
    EMPLOYEE_NUMBER,
    DATE;

delete from reporting_prod.retail.sxf_employeesales_snapshot
where  SNAPSHOT_DATETIME < DATEADD(month, -3, TO_DATE(SNAPSHOT_DATETIME));       