ALTER SESSION SET TIMEZONE = 'America/Los_Angeles';
SET months_back = dateadd(month, -4, date_trunc(month, current_timestamp));

INSERT OVERWRITE INTO shared.ab_test_ds_image_testing
SELECT 'INDIV COUNTRY + INDIV PLATFORM'            AS version,
       'WITH COLOR'                                AS product_report_version,
       'GRID - DIRECT'                             AS funnel_report_version,
       test_key,
       test_framework_id,
       test_label,
       test_framework_description,
       a.master_test_number,
       test_framework_ticket,
       campaign_code,
       test_type,
       test_activated_datetime,
       test_effective_end_datetime_pst,
       test_group,
       test_group_description,
       ab_test_start_local_date,
       store_brand,
       store_region,
       store_country,
       test_start_membership_state,
       is_male_customer,
       platform,
       a.master_product_id                            product_id,
       rnk_mpid_status_changed,
       a.product_effective_start_date_pst,
       a.product_effective_end_date_pst,
       product_name,
       base_sku,
       a.product_sku,
       color,
       sub_brand,
       gender,
       segment,
       image_url,
       evaluation_message,
       evaluation_batch_id,
       COALESCE(CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku,
                       '-', CAST(SPLIT_PART(image_pairs, ':', 1) AS NUMBER(38, 0)), '_271x407.jpg'),
                image_url)                         AS image_sort_url_control,
       CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku, '-',
              CAST(SPLIT_PART(image_pairs, ':', 2) AS NUMBER(38, 0)),
              '_271x407.jpg')                      AS image_sort_url_variant,
       COUNT(DISTINCT session_id)                  AS sessions,
       COUNT(DISTINCT customer_id)                 AS distinct_customers,
       COUNT(DISTINCT CASE
                          WHEN test_type IN
                               ('membership', 'Sorting Hat, Persistent', 'Membership Detail', 'Customer Detail')
                              THEN customer_id
                          WHEN test_type IN ('session', 'Session Detail', 'Sorting Hat, Non Persistent', 'Builder')
                              THEN session_id END) AS test_starts_actual,
       SUM(grid_views)                             AS grid_views,
       SUM(pdp_views)                              AS pdp_views,
       SUM(atb)                                    AS atb,
       SUM(units_activating)                       AS units_activating,
       SUM(units_nonactivating)                    AS units_nonactivating,
       SUM(revenue)                                AS revenue,
       MAX(max_record_pst)                         AS max_record_pst
FROM reporting_base_prod.shared.session_ab_test_ds_image_test AS a
WHERE ab_test_start_pst_datetime::DATE >= $months_back
GROUP BY ALL

UNION ALL

SELECT 'INDIV COUNTRY + TOTAL PLATFORM'            AS version,
       'WITH COLOR'                                AS product_report_version,
       'GRID - DIRECT'                             AS funnel_report_version,
       test_key,
       test_framework_id,
       test_label,
       test_framework_description,
       a.master_test_number,
       test_framework_ticket,
       campaign_code,
       test_type,
       test_activated_datetime,
       test_effective_end_datetime_pst,
       test_group,
       test_group_description,
       ab_test_start_local_date,
       store_brand,
       store_region,
       store_country,
       test_start_membership_state,
       is_male_customer,
       'Total'                                     AS platform,
       a.master_product_id                            product_id,
       rnk_mpid_status_changed,
       a.product_effective_start_date_pst,
       a.product_effective_end_date_pst,
       product_name,
       base_sku,
       a.product_sku,
       color,
       sub_brand,
       gender,
       segment,
       image_url,
       evaluation_message,
       evaluation_batch_id,
       COALESCE(CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku,
                       '-', CAST(SPLIT_PART(image_pairs, ':', 1) AS NUMBER(38, 0)), '_271x407.jpg'),
                image_url)                         AS image_sort_url_control,
       CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku, '-',
              CAST(SPLIT_PART(image_pairs, ':', 2) AS NUMBER(38, 0)),
              '_271x407.jpg')                      AS image_sort_url_variant,
       COUNT(DISTINCT session_id)                  AS sessions,
       COUNT(DISTINCT customer_id)                 AS distinct_customers,
       COUNT(DISTINCT CASE
                          WHEN test_type IN
                               ('membership', 'Sorting Hat, Persistent', 'Membership Detail', 'Customer Detail')
                              THEN customer_id
                          WHEN test_type IN ('session', 'Session Detail', 'Sorting Hat, Non Persistent', 'Builder')
                              THEN session_id END) AS test_starts_actual,
       SUM(grid_views)                             AS grid_views,
       SUM(pdp_views)                              AS pdp_views,
       SUM(atb)                                    AS atb,
       SUM(units_activating)                       AS units_activating,
       SUM(units_nonactivating)                    AS units_nonactivating,
       SUM(revenue)                                AS revenue,
       MAX(max_record_pst)                         AS max_record_pst
FROM reporting_base_prod.shared.session_ab_test_ds_image_test AS a
where ab_test_start_pst_datetime >= $months_back
GROUP BY ALL


UNION ALL

SELECT 'INDIV REGION + INDIV PLATFORM'             AS version,
       'WITH COLOR'                                AS product_report_version,
       'GRID - DIRECT'                             AS funnel_report_version,
       test_key,
       test_framework_id,
       test_label,
       test_framework_description,
       a.master_test_number,
       test_framework_ticket,
       campaign_code,
       test_type,
       test_activated_datetime,
       test_effective_end_datetime_pst,
       test_group,
       test_group_description,
       ab_test_start_local_date,
       store_brand,
       store_region,
       store_region                                AS store_country,
       test_start_membership_state,
       is_male_customer,
       platform,
       a.master_product_id                            product_id,
       rnk_mpid_status_changed,
       a.product_effective_start_date_pst,
       a.product_effective_end_date_pst,
       product_name,
       base_sku,
       a.product_sku,
       color,
       sub_brand,
       gender,
       segment,
       image_url,
       evaluation_message,
       evaluation_batch_id,
       COALESCE(CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku,
                       '-', CAST(SPLIT_PART(image_pairs, ':', 1) AS NUMBER(38, 0)), '_271x407.jpg'),
                image_url)                         AS image_sort_url_control,
       CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku, '-',
              CAST(SPLIT_PART(image_pairs, ':', 2) AS NUMBER(38, 0)),
              '_271x407.jpg')                      AS image_sort_url_variant,
       COUNT(DISTINCT session_id)                  AS sessions,
       COUNT(DISTINCT customer_id)                 AS distinct_customers,
       COUNT(DISTINCT CASE
                          WHEN test_type IN
                               ('membership', 'Sorting Hat, Persistent', 'Membership Detail', 'Customer Detail')
                              THEN customer_id
                          WHEN test_type IN ('session', 'Session Detail', 'Sorting Hat, Non Persistent', 'Builder')
                              THEN session_id END) AS test_starts_actual,
       SUM(grid_views)                             AS grid_views,
       SUM(pdp_views)                              AS pdp_views,
       SUM(atb)                                    AS atb,
       SUM(units_activating)                       AS units_activating,
       SUM(units_nonactivating)                    AS units_nonactivating,
       SUM(revenue)                                AS revenue,
       MAX(max_record_pst)                         AS max_record_pst
FROM reporting_base_prod.shared.session_ab_test_ds_image_test AS a
GROUP BY ALL

UNION ALL

SELECT 'INDIV REGION + TOTAL PLATFORM'             AS version,
       'WITH COLOR'                                AS product_report_version,
       'GRID - DIRECT'                             AS funnel_report_version,
       test_key,
       test_framework_id,
       test_label,
       test_framework_description,
       a.master_test_number,
       test_framework_ticket,
       campaign_code,
       test_type,
       test_activated_datetime,
       test_effective_end_datetime_pst,
       test_group,
       test_group_description,
       ab_test_start_local_date,
       store_brand,
       store_region,
       store_region                                AS store_country,
       test_start_membership_state,
       is_male_customer,
       'Total'                                     AS platform,
       a.master_product_id                            product_id,
       rnk_mpid_status_changed,
       a.product_effective_start_date_pst,
       a.product_effective_end_date_pst,
       product_name,
       base_sku,
       a.product_sku,
       color,
       sub_brand,
       gender,
       segment,
       image_url,
       evaluation_message,
       evaluation_batch_id,
       COALESCE(CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku,
                       '-', CAST(SPLIT_PART(image_pairs, ':', 1) AS NUMBER(38, 0)), '_271x407.jpg'),
                image_url)                         AS image_sort_url_control,
       CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku, '-',
              CAST(SPLIT_PART(image_pairs, ':', 2) AS NUMBER(38, 0)),
              '_271x407.jpg')                      AS image_sort_url_variant,
       COUNT(DISTINCT session_id)                  AS sessions,
       COUNT(DISTINCT customer_id)                 AS distinct_customers,
       COUNT(DISTINCT CASE
                          WHEN test_type IN
                               ('membership', 'Sorting Hat, Persistent', 'Membership Detail', 'Customer Detail')
                              THEN customer_id
                          WHEN test_type IN ('session', 'Session Detail', 'Sorting Hat, Non Persistent', 'Builder')
                              THEN session_id END) AS test_starts_actual,
       SUM(grid_views)                             AS grid_views,
       SUM(pdp_views)                              AS pdp_views,
       SUM(atb)                                    AS atb,
       SUM(units_activating)                       AS units_activating,
       SUM(units_nonactivating)                    AS units_nonactivating,
       SUM(revenue)                                AS revenue,
       MAX(max_record_pst)                         AS max_record_pst
FROM reporting_base_prod.shared.session_ab_test_ds_image_test AS a
GROUP BY ALL


UNION ALL

SELECT 'GLOBAL + INDIV PLATFORM'                   AS version,
       'WITH COLOR'                                AS product_report_version,
       'GRID - DIRECT'                             AS funnel_report_version,
       test_key,
       test_framework_id,
       test_label,
       test_framework_description,
       a.master_test_number,
       test_framework_ticket,
       campaign_code,
       test_type,
       test_activated_datetime,
       test_effective_end_datetime_pst,
       test_group,
       test_group_description,
       ab_test_start_local_date,
       store_brand,
       'GLOBAL'                                       store_region,
       'GLOBAL'                                       store_country,
       test_start_membership_state,
       is_male_customer,
       platform,
       a.master_product_id                            product_id,
       rnk_mpid_status_changed,
       a.product_effective_start_date_pst,
       a.product_effective_end_date_pst,
       product_name,
       base_sku,
       a.product_sku,
       color,
       sub_brand,
       gender,
       segment,
       image_url,
       evaluation_message,
       evaluation_batch_id,
       COALESCE(CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku,
                       '-', CAST(SPLIT_PART(image_pairs, ':', 1) AS NUMBER(38, 0)), '_271x407.jpg'),
                image_url)                         AS image_sort_url_control,
       CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku, '-',
              CAST(SPLIT_PART(image_pairs, ':', 2) AS NUMBER(38, 0)),
              '_271x407.jpg')                      AS image_sort_url_variant,
       COUNT(DISTINCT session_id)                  AS sessions,
       COUNT(DISTINCT customer_id)                 AS distinct_customers,
       COUNT(DISTINCT CASE
                          WHEN test_type IN
                               ('membership', 'Sorting Hat, Persistent', 'Membership Detail', 'Customer Detail')
                              THEN customer_id
                          WHEN test_type IN ('session', 'Session Detail', 'Sorting Hat, Non Persistent', 'Builder')
                              THEN session_id END) AS test_starts_actual,
       SUM(grid_views)                             AS grid_views,
       SUM(pdp_views)                              AS pdp_views,
       SUM(atb)                                    AS atb,
       SUM(units_activating)                       AS units_activating,
       SUM(units_nonactivating)                    AS units_nonactivating,
       SUM(revenue)                                AS revenue,
       MAX(max_record_pst)                         AS max_record_pst
FROM reporting_base_prod.shared.session_ab_test_ds_image_test AS a
GROUP BY ALL

UNION ALL

SELECT 'GLOBAL + TOTAL PLATFORM'                   AS version,
       'WITH COLOR'                                AS product_report_version,
       'GRID - DIRECT'                             AS funnel_report_version,
       test_key,
       test_framework_id,
       test_label,
       test_framework_description,
       a.master_test_number,
       test_framework_ticket,
       campaign_code,
       test_type,
       test_activated_datetime,
       test_effective_end_datetime_pst,
       test_group,
       test_group_description,
       ab_test_start_local_date,
       store_brand,
       'GLOBAL'                                       store_region,
       'GLOBAL'                                       store_country,
       test_start_membership_state,
       is_male_customer,
       'Total'                                     AS platform,
       a.master_product_id                            product_id,
       rnk_mpid_status_changed,
       a.product_effective_start_date_pst,
       a.product_effective_end_date_pst,
       product_name,
       base_sku,
       a.product_sku,
       color,
       sub_brand,
       gender,
       segment,
       image_url,
       evaluation_message,
       evaluation_batch_id,
       COALESCE(CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku,
                       '-', CAST(SPLIT_PART(image_pairs, ':', 1) AS NUMBER(38, 0)), '_271x407.jpg'),
                image_url)                         AS image_sort_url_control,
       CONCAT('https://fabletics-us-cdn.justfab.com/media/images/products/', a.product_sku, '/', a.product_sku, '-',
              CAST(SPLIT_PART(image_pairs, ':', 2) AS NUMBER(38, 0)),
              '_271x407.jpg')                      AS image_sort_url_variant,
       COUNT(DISTINCT session_id)                  AS sessions,
       COUNT(DISTINCT customer_id)                 AS distinct_customers,
       COUNT(DISTINCT CASE
                          WHEN test_type IN
                               ('membership', 'Sorting Hat, Persistent', 'Membership Detail', 'Customer Detail')
                              THEN customer_id
                          WHEN test_type IN ('session', 'Session Detail', 'Sorting Hat, Non Persistent', 'Builder')
                              THEN session_id END) AS test_starts_actual,
       SUM(grid_views)                             AS grid_views,
       SUM(pdp_views)                              AS pdp_views,
       SUM(atb)                                    AS atb,
       SUM(units_activating)                       AS units_activating,
       SUM(units_nonactivating)                    AS units_nonactivating,
       SUM(revenue)                                AS revenue,
       MAX(max_record_pst)                         AS max_record_pst
FROM reporting_base_prod.shared.session_ab_test_ds_image_test AS a
GROUP BY ALL;

