CREATE OR REPLACE VIEW LAKE_VIEW.FIVETRAN_LOG.USAGE_COST as
SELECT MEASURED_MONTH,
        DESTINATION_ID,
        AMOUNT,
        _fivetran_synced::TIMESTAMP_LTZ as meta_update_datetime
    FROM LAKE_FIVETRAN.FIVETRAN_LOG_V1.USAGE_COST;
