CREATE OR REPLACE VIEW LAKE_VIEW.FIVETRAN_LOG.LOG as
SELECT ID,
        TIME_STAMP,
        CONNECTOR_ID,
        TRANSFORMATION_ID,
        EVENT,
        MESSAGE_EVENT,
        SYNC_ID,
        MESSAGE_DATA,
        _fivetran_synced::TIMESTAMP_LTZ as meta_update_datetime
    FROM LAKE_FIVETRAN.FIVETRAN_LOG_V1.LOG;
