CREATE OR REPLACE VIEW LAKE_VIEW.FIVETRAN_LOG.CONNECTOR_TYPE as
SELECT ID,
        OFFICIAL_CONNECTOR_NAME,
        TYPE,
        AVAILABILITY,
        CREATED_AT,
        PUBLIC_BETA_AT,
        RELEASE_AT,
        DELETED,
        BROKEN,
        _fivetran_synced::TIMESTAMP_LTZ as meta_update_datetime
    FROM LAKE_FIVETRAN.FIVETRAN_LOG_V1.CONNECTOR_TYPE;
