CREATE OR REPLACE VIEW LAKE_VIEW.FIVETRAN_LOG.INCREMENTAL_MAR as
SELECT CONNECTOR_ID,
        DESTINATION_ID,
        FREE_TYPE,
        MEASURED_DATE,
        SCHEMA_NAME,
        SYNC_TYPE,
        TABLE_NAME,
        UPDATED_AT,
        INCREMENTAL_ROWS,
        _fivetran_synced::TIMESTAMP_LTZ as meta_update_datetime
    FROM LAKE_FIVETRAN.FIVETRAN_LOG_V1.INCREMENTAL_MAR;
