from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrarollup",
    schema="dbo",
    table="products_in_stock",
    watermark_column="rollup_datetime_modified",
    schema_version_prefix="v1",
    enable_archive=False,
    column_list=[
        Column("product_id", "INT", uniqueness=True),
        Column("master_product_id", "INT"),
        Column("product_type_id", "INT"),
        Column("master_store_group_id", "INT"),
        Column("store_group_id", "INT"),
        Column("item_number", "VARCHAR(30)"),
        Column("item_id", "INT"),
        Column("alias", "VARCHAR(100)"),
        Column("style", "VARCHAR(255)"),
        Column("heel_type", "VARCHAR(4)"),
        Column("heel_tag_id", "INT"),
        Column("master_statuscode", "INT"),
        Column("statuscode", "INT"),
        Column("is_active", "BOOLEAN"),
        Column("is_master", "BOOLEAN"),
        Column("in_season_period_current", "INT"),
        Column("current_period_id", "INT"),
        Column("in_season_period_next", "INT"),
        Column("next_period_id", "INT"),
        Column("available_quantity", "INT"),
        Column("available_quantity_default", "INT"),
        Column("available_quantity_ca", "INT"),
        Column("available_quantity_master", "INT"),
        Column("available_quantity_master_default", "INT"),
        Column("available_quantity_master_ca", "INT"),
        Column("available_quantity_group", "INT"),
        Column("available_quantity_group_default", "INT"),
        Column("available_quantity_group_ca", "INT"),
        Column("available_quantity_preorder", "INT"),
        Column("available_quantity_preorder_default", "INT"),
        Column("available_quantity_preorder_ca", "INT"),
        Column("available_quantity_preorder_master", "INT"),
        Column("available_quantity_preorder_master_default", "INT"),
        Column("available_quantity_preorder_master_ca", "INT"),
        Column("date_available_preorder", "TIMESTAMP_NTZ(3)"),
        Column("date_available_preorder_default", "TIMESTAMP_NTZ(3)"),
        Column("date_available_preorder_ca", "TIMESTAMP_NTZ(3)"),
        Column("date_inventory_available", "TIMESTAMP_NTZ(3)"),
        Column("date_inventory_available_default", "TIMESTAMP_NTZ(3)"),
        Column("date_inventory_available_ca", "TIMESTAMP_NTZ(3)"),
        Column("option_signature", "VARCHAR(100)"),
        Column("option_signature_prefix", "VARCHAR(100)"),
        Column("group_code", "VARCHAR(50)"),
        Column("label", "VARCHAR(100)"),
        Column("label_instance", "VARCHAR(100)"),
        Column("short_description", "VARCHAR(1000)"),
        Column("medium_description", "VARCHAR(2000)"),
        Column("long_description", "VARCHAR"),
        Column("default_product_category_id", "INT"),
        Column("default_product_category_label", "VARCHAR(50)"),
        Column("retail_unit_price", "NUMBER(19, 4)"),
        Column("default_unit_price", "NUMBER(19, 4)"),
        Column("sale_unit_price", "NUMBER(19, 4)"),
        Column("brand_id", "INT"),
        Column("brand_label", "VARCHAR(100)"),
        Column("post_reg_only", "INT"),
        Column("style_major", "VARCHAR(100)"),
        Column("style_minor", "VARCHAR(100)"),
        Column("style_major_tag_id", "INT"),
        Column("style_minor_tag_id", "INT"),
        Column("sales_rank_1_day", "INT"),
        Column("sales_count_1_day", "INT"),
        Column("sales_rank_conversions_5_days", "INT"),
        Column("sales_count_conversions_5_days", "INT"),
        Column("sales_rank_conversions_10_days", "INT"),
        Column("sales_count_conversions_10_days", "INT"),
        Column("sales_rank_10_days", "INT"),
        Column("sales_count_10_days", "INT"),
        Column("rating_rank", "INT"),
        Column("latest_rank", "INT"),
        Column("review_rank", "INT"),
        Column("date_expected", "TIMESTAMP_NTZ(3)"),
        Column("date_expected_group_code", "TIMESTAMP_NTZ(3)"),
        Column("date_sale_expires", "TIMESTAMP_NTZ(3)"),
        Column("related_product_count", "INT"),
        Column("permissions_flag", "INT"),
        Column("product_category_id_list", "VARCHAR"),
        Column("featured_product_location_id_list", "VARCHAR"),
        Column("product_option_id_list", "VARCHAR"),
        Column("permalink", "VARCHAR(255)"),
        Column("daily_fix_active", "BOOLEAN"),
        Column("date_sale_rank", "INT"),
        Column("review_group", "VARCHAR(100)"),
        Column("average_review", "DOUBLE"),
        Column("review_count", "DOUBLE"),
        Column("recommended_count", "DOUBLE"),
        Column("recommended_percentage", "DOUBLE"),
        Column("group_code_rating_rank", "INT"),
        Column("group_code_latest_rank", "INT"),
        Column("group_code_sales_rank", "INT"),
        Column("include_in_site_search", "BOOLEAN"),
        Column("image_count", "INT"),
        Column("default_warehouse_id", "INT"),
        Column("available_quantity_any_profile", "INT"),
        Column("retail_pricing_id", "INT"),
        Column("retail_store_unit_price", "NUMBER(19, 4)"),
        Column("current_cost", "NUMBER(19, 4)"),
        Column("profit_margin", "NUMBER(19, 4)"),
        Column("margin_percentage", "DOUBLE"),
        Column("markup_percentage", "DOUBLE"),
        Column("sku", "VARCHAR(100)"),
        Column("plus_size_sku", "VARCHAR(100)"),
        Column("rollup_datetime_added", "TIMESTAMP_NTZ(3)"),
        Column("rollup_datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("rollup_datetime_verified", "TIMESTAMP_NTZ(3)"),
        Column("row_checksum", "BINARY"),
        Column("color", "VARCHAR(100)"),
        Column("average_review_all_stores", "DOUBLE"),
        Column("coo", "VARCHAR(2)"),
        Column("is_bundle_product", "BOOLEAN"),
        Column("is_plus_size", "BOOLEAN"),
        Column("regular_size_sku", "VARCHAR(100)"),
        Column("gender", "VARCHAR(50)"),
        Column("age_group", "VARCHAR(50)"),
        Column("size", "VARCHAR(100)"),
        Column("size_type", "VARCHAR(10)"),
        Column("size_system_code", "VARCHAR(4)"),
        Column("availability", "VARCHAR(50)"),
        Column("brand_name", "VARCHAR(100)"),
        Column("product_type_label", "VARCHAR(50)"),
        Column("base_sku", "VARCHAR(100)"),
        Column("store_region", "VARCHAR(10)"),
        Column("store_region_group", "VARCHAR(10)"),
        Column("pdp_url", "VARCHAR"),
        Column("has_plus_size", "BOOLEAN"),
        Column("is_component_product", "BOOLEAN"),
        Column("bundle_separate_retail_unit_price", "NUMBER(19, 4)"),
        Column("bundle_separate_default_unit_price", "NUMBER(19, 4)"),
        Column("pricing_option_id", "INT"),
        Column("shipping_price", "NUMBER(19, 4)"),
        Column("is_market", "BOOLEAN"),
        Column("date_preorder_expires", "TIMESTAMP_NTZ(3)"),
        Column("date_inventory_available_preorder", "TIMESTAMP_NTZ(3)"),
        Column("product_option_count", "INT"),
        Column("sales_count_5_days", "INT"),
        Column("sales_count_conversions_1_day", "INT"),
        Column("average_overall_review", "DOUBLE"),
        Column("average_overall_review_all_stores", "DOUBLE"),
        Column("token_redemption_quantity", "INT"),
        Column("sales_rank_5_days", "INT"),
        Column("sales_rank_conversions_1_day", "INT"),
        Column("sale_pricing_id", "INT"),
        Column("default_pricing_id", "INT"),
        Column("average_overall_review_filtered_stores", "DOUBLE"),
        Column("image_main_link", "VARCHAR"),
        Column("image_hover_link", "VARCHAR"),
        Column("sum_pricing", "INT"),
        Column("membership_brand_id", "INT"),
        Column("bundle_available_quantity_accessory", "INT"),
        Column("bundle_available_quantity_accessory_preorder", "INT"),
        Column("is_token", "INT"),
        Column("customization_configuration_id", "INT"),
        Column("company_id", "INT"),
        Column("available_quantity_accessory", "INT"),
        Column("review_count_filtered_stores", "INT"),
        Column("image_test_flag", "BOOLEAN"),
        Column("reward_point_price", "INT"),
        Column("subco_image_name", "VARCHAR(50)"),
        Column("is_warehouse_product", "INT"),
        Column("warehouse_unit_price", "NUMBER(19, 4)"),
        Column("retail_outlet_unit_price", "NUMBER(19, 4)"),
        Column("fulfillment_partner_id", "INT"),
    ],
)
