from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultrarollup',
    schema='dbo',
    table='products_in_stock_ranking',
    watermark_column='rollup_datetime_modified',
    schema_version_prefix='v2',
    column_list=[
        Column('master_product_id', 'INT', uniqueness=True),
        Column('store_group_id', 'INT'),
        Column('master_store_group_id', 'INT'),
        Column('product_type_id', 'INT'),
        Column('default_warehouse_id', 'INT'),
        Column('default_product_category_id', 'INT'),
        Column('group_code', 'VARCHAR(50)'),
        Column('group_code_rating_rank', 'INT'),
        Column('group_code_latest_rank', 'INT'),
        Column('group_code_sales_rank', 'INT'),
        Column('sales_rank_1_day', 'INT'),
        Column('sales_rank_conversions_1_day', 'INT'),
        Column('sales_rank_5_days', 'INT'),
        Column('sales_rank_conversions_5_days', 'INT'),
        Column('sales_rank_10_days', 'INT'),
        Column('sales_rank_conversions_10_days', 'INT'),
        Column('rating_rank', 'INT'),
        Column('latest_rank', 'INT'),
        Column('review_rank', 'INT'),
        Column('date_sale_rank', 'INT'),
        Column('total_sold', 'INT'),
        Column('total_sold_conversions', 'INT'),
        Column('total_impressions', 'INT'),
        Column('total_sold_1_day', 'INT'),
        Column('total_sold_conversions_1_day', 'INT'),
        Column('total_impressions_1_day', 'INT'),
        Column('sales_per_impression_1_day', 'NUMBER(18, 9)'),
        Column('sales_per_impression_conversion_1_day', 'NUMBER(18, 9)'),
        Column('total_sold_5_days', 'INT'),
        Column('total_sold_conversions_5_days', 'INT'),
        Column('total_impressions_5_days', 'INT'),
        Column('sales_per_impression_5_days', 'NUMBER(18, 9)'),
        Column('sales_per_impression_conversion_5_days', 'NUMBER(18, 9)'),
        Column('total_sold_10_days', 'INT'),
        Column('total_sold_conversions_10_days', 'INT'),
        Column('total_impressions_10_days', 'INT'),
        Column('sales_per_impression_10_days', 'NUMBER(18, 9)'),
        Column('sales_per_impression_conversion_10_days', 'NUMBER(18, 9)'),
        Column('rollup_datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('rollup_datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('rollup_datetime_verified', 'TIMESTAMP_NTZ(3)'),
        Column('row_checksum', 'BINARY(32)'),
    ],
)
