

TRUNCATE TABLE documentation.ddd_metric_definition;

INSERT INTO documentation.ddd_metric_definition
    (
         metric,
         metric_breakouts,
         metric_definition,
         metric_group
     )
VALUES
('Cash Contribution Profit', 'Total', 'Cash Gross Revenue - Refunds - Chargebacks - Product Order Landed Cost - Shipping Supplies Cost - Shipping Cost + Product Cost Returned Resaleable - Reship/Exchange Product Cost Amount - Variable GMS Cost - Payment Processing Cost - Product Order Misc COGS', 'Cash Metrics'),
('Cash Gross Profit', 'Total', 'Cash Net Revenue - Direct COGS - Return Shipping Cost Amount + Product Cost Returned Resaleable', 'Cash Metrics'),
('Cash Gross Revenue', 'Total, Act, NonAct', 'Payment Transaction - Tax', 'Cash Metrics'),
('Cash Gross Revenue Excl. Shipping', 'Total, Act, NonAct', 'Payment Transaction - Tax - Shipping Revenue', 'Cash Metrics'),
('Cash Refund', 'Act, NonAct', 'Amount refunded in cash from a product or billing order', 'Refunds and Chargebacks'),
('Cash Refund - Credit Billing', 'NonAct', 'Amount refunded in cash from a billing order', 'Refunds and Chargebacks'),
('Cash Refund - Product Order', 'Act, NonAct', 'Amount refunded in cash from a product order', 'Refunds and Chargebacks'),
('Chargebacks', 'Total, NonAct', 'Chargeback amount the customer was compensated for their product or billing order. Excludes tax. Chargeback is when a customer claims the transaction is fraudulent', 'Refunds and Chargebacks'),
('Chargebacks - Credit Billings', 'Total', 'Chargeback amount the customer was compensated for their billing order. Excludes tax.  Chargeback is when a customer claims the transaction to be fraud', 'Refunds and Chargebacks'),
('Gift Card - Cash Refund and Chargeback Amount', 'Total', 'Refund or chargeback amount in cash for a giftcard', 'Refunds and Chargebacks'),
('Legacy Credit - Cash Refund and Chargeback Amount', 'Total', 'Refund or chargeback amount in cash for a billed credit as reported in legacy systems', 'Refunds and Chargebacks'),
('Legacy Credit - Cash Transaction Amount', 'Total', 'The cash amount collect for a billed credit as reported in legacy systems', 'Refunds and Chargebacks'),
('Membership Fee - Cash Refund Amount', 'Total', 'Refund or chargeback amount in cash for a membership fee', 'Refunds and Chargebacks'),
('Membership Fee - Cash Transaction Amount', 'Total', 'The cash amount collected for a customer membership fee', 'Refunds and Chargebacks'),
('Product Order Chargebacks', 'Act, NonAct', 'Chargeback amount the customer was compensated for their product order. Excludes tax. Chargeback is when a customer claims the transaction is fraudulent', 'Refunds and Chargebacks'),
('Billed Cash Credit - Cancelled Amount', 'Total', 'The amount of credits cancelled for billing orders', 'Credit Billings'),
('Billed Cash Credit - Cancelled Equivalent Count', 'Total', 'Billed cash credit (e.g. Membership credits, gift certificates) cancelled equivalent count where an equivalent count is the ratio of a credit''s cancelled amount to the billed amount', 'Credit Billings'),
('Billed Cash Credit - Expired Amount', 'Total', 'The amount of credits that have expired for billing orders', 'Credit Billings'),
('Billed Cash Credit - Issued Amount', 'Total', 'The amount of credits purchased for billing orders', 'Credit Billings'),
('Billed Cash Credit - Issued Equivalent Count', 'Total', 'Billed cash credit (e.g. Membership credits, gift certificates) issued equivalent count where an equivalent count is the ratio of a credit''s issued amount to the billed amount', 'Credit Billings'),
('Billed Cash Credit - Net Amount', 'Total', 'Issued Credits net redeemed, cancelled, and expired credits', 'Credit Billings'),
('Billed Cash Credit - Redeemed Amount', 'Total', 'The amount of credits redeemed for billing orders', 'Credit Billings'),
('Billed Cash Credit - Redeemed Equivalent Count', 'Total', 'Billed cash credit (e.g. Membership credits, gift certificates) redeemed equivalent count where an equivalent count is the ratio of a credit''s redeemed amount to the billed amount', 'Credit Billings'),
('Billed Credit - Cash Transaction Amount', 'Total', 'The cash amount collected for a billed credit', 'Credit Billings'),
('NonCash Credit - Cancelled Amount', 'Total', 'The amount of non cash credits refunded for billing orders', 'Credit Billings'),
('NonCash Credit - Issued Amount', 'Total', 'The amount of non cash credits issued for billing orders', 'Credit Billings'),
('NonCash Credit - Redeemed Amount', 'Total', 'The amount of non-cash credit redeemed in a product order. Non-cash credit is store credit that was never paid for with cash (e.g. endowments, ambassador credit etc.)', 'Credit Billings'),
('Other Cash Credit - Cancelled Amount', 'Total', 'The amount of other cash credits cancelled for billing orders', 'Credit Billings'),
('Other Cash Credit - Issued Amount', 'Total', 'The amount of other cash credits refunded for billing orders', 'Credit Billings'),
('Other Cash Credit - Redeemed Amount', 'Total', 'The amount of other cash credits redeemed for billing orders', 'Credit Billings'),
('Refund Cash Credit - Cancelled Amount', 'Total', 'The amount of credits cancelled for billing orders', 'Credit Billings'),
('Refund Cash Credit - Issued Amount', 'Total', 'The amount of credits issued for billing orders', 'Credit Billings'),
('Refund Cash Credit - Redeemed Amount', 'Total', 'The amount of credits redeemed for billing orders', 'Credit Billings'),
('Store Credit Refund Cash', 'Act, NonAct', 'Amount of cash credit refunded from a product order', 'Credit Billings'),
('AOV', 'Total, Act, NonAct', 'Average Order Value; Product Revenue Including Shipping/Product Order Count Excluding Reship Exch', 'Product Orders'),
('AOV Excl Shipping', 'Total, Act, NonAct', 'Average Order Value excluding Shipping; (Product Revenue Including Shipping - Shipping Revenue)/Product Order Count Excluding Reship Exch', 'Product Orders'),
('AUC - Reship/Exch', 'Total, Act, NonAct', 'Average Unit Count for Reships and Exchanges only; ﻿Order Product Cost Reship Exch/Unit Count Reship Exch', 'Product Orders'),
('AUC Incl. Reship/Exch', 'Total, Act, NonAct', 'Average Unit Count including Reships and Exchanges; ﻿Order Product Cost/Unit Count Including Reship Exch', 'Product Orders'),
('AUC Excluding Reship/Exch', 'Total, Act, NonAct', 'Average Unit Count excluding Reships and Exchanges; ﻿Order Product Cost/Unit Count Excl Reship Exch', 'Product Orders'),
('Discount Rate', 'Act, NonAct', 'Discount Amount/(Product Order Subtotal Amount - Product Order NonCash Credit Redeemed Amount)', 'Product Orders'),
('Gift Card - Cash Transaction Amount', 'Total', 'The gift card amount collected for a product order', 'Product Orders'),
('Product Discount', 'Total, Act, NonAct', 'The discount amount applied only to the product purchased in the order (e.g. BOGO, $25 leggings, etc.) ', 'Product Orders'),
('Product Gross Profit', 'Total, First Guest', 'Product Net Revenue - Direct COGS - Return Shipping Cost Amount + Product Cost Returned Resaleable', 'Product Orders'),
('Product Gross Revenue', 'Total, Act, NonAct', 'Product Order Subtotal + Tariff Amount - Discount + Shipping Revenue - NonCash Credit Redeemed Amount', 'Product Orders'),
('Product Gross Revenue Excl. Shipping', 'Total, Act, NonAct', 'Product Order Subtotal + Tariff Amount - Discount - NonCash Credit Redeemed Amount', 'Product Orders'),
('Product Margin Pre Return', 'Total, First Guest', 'Product Order Subtotal + Tariff Amount - Discount + Shipping Revenue - NonCash Credit Redeemed Amount - Landed Product Cost - Shipping Cost - Shipping Supplies Cost', 'Product Orders'),
('Product Order Count', 'Total, Act, NonAct, First Guest', 'The count of product order transactions excluding reships and exchanges', 'Product Orders'),
('Product Order Count Incl. Reship/Exch', 'Total', 'The count of product order transactions including reships and exchanges', 'Product Orders'),
('Product Order Count Reship/Exch', 'Total', 'The count of reship and exchange product order transactions', 'Product Orders'),
('Return Shipping Cost Incl. Reship/Exch', 'Total, Act, NonAct', 'Cost of shipping back the item back to the FC. This is a unit based assumption provided by FP&A', 'Product Orders'),
('Return Unit Count', 'Total, Act, NonAct', 'The total count of units that were returned back the FC', 'Product Orders'),
('Shipping Revenue', 'Total, Act, NonAct', 'The shipping revenue amount gained in a product order gross of shipping discount ', 'Product Orders'),
('UPT', 'Total, Act, NonAct', 'Units Per Transaction excluding Reships and Exchanges; ﻿Unit Count Excluding Reship Exch/Product Order Count Excluding Reship Exch', 'Product Orders'),
('UPT Incl. Reship/Exch', 'Total', 'Units Per Transaction excluding Reships and Exchanges; ﻿Unit Count Including Reship Exch/Product Order Count Including Reship Exch', 'Product Orders'),
('Unit Count', 'Total, Act, NonAct', 'The count of product order units.  Includes loyalty units and excludes reships and exchanges.', 'Product Orders'),
('Unit Count Incl. Reship/Exch', 'Total', 'The count of product order units.  Includes both loyalty units and reships and exchanges.', 'Product Orders'),
('Unit Count Reship/Exch', 'Total, Act, NonAct', 'Count of customers that activated as a VIP that are cross promo.', 'Product Orders'),
('BOP VIPs', 'Total', 'Count of VIPs at the beginning of the month', 'Acquisition'),
('Cancels', 'Total', 'Count of VIPs that cancelled membership', 'Acquisition'),
('EOP VIPs', 'Total', 'Count of VIPs at the end of the month', 'Acquisition'),
('New Leads', 'Total', 'Count of customers that registered', 'Acquisition'),
('New Online Leads', 'Total', 'Count of customers that registered on the website or mobile app', 'Acquisition'),
('New Retail Leads', 'Total', 'Count of customers that registered in a retail store', 'Acquisition'),
('New Leads - Cumulative', 'Total', 'Historical cumulative count of registered customers', 'Acquisition'),
('New Vips', 'Total', 'Count of customers that activated as a VIP', 'Acquisition'),
('New VIPs - M1', 'Total', 'Count of customers that activated as a VIP the same month they registered', 'Acquisition'),
('Paid Vips', 'Total', 'Count of customers that activated as a VIP that are not cross promo.', 'Acquisition'),
('Paid VIPs - M1', 'Total', 'Count of customers that activated as a VIP in the same month they registered that are not cross promo.', 'Acquisition'),
('Unpaid Vips', 'Total', 'Count of customers that activated as a VIP in the same month they registered that are cross promo.', 'Acquisition'),
('Media Spend', 'Total', 'Total amount spent on media advertisements across channels (e.g. Facebook, Instagram, etc.)', 'Acquisition'),
('Misc COGS Amount Incl. Reship/Exch', 'Total', 'The amount is associated with product markdown cost, based on assumptions provided by the FP&A, as a percentage of product landed cost', 'COGS'),
('Outbound Product Cost Incl. Reship/Exch', 'Total, Act, NonAct', 'Blended landed cost of the product. Includes product, freight and CMT cost. Initial cost estimates are sourced from Oracle EBS, PO SKU and EDW01 (prior to 2018); Landed costs reflect actuals as they become available.', 'COGS'),
('Outbound Product Cost Excl. Reship/Exch', 'Total, Act, NonAct', 'Blended landed cost of the product excluding reships and exchanges. Includes product, freight and CMT cost. Initial cost estimates are sourced from Oracle EBS, PO SKU and EDW01 (prior to 2018); Landed costs reflect actuals as they become available.', 'COGS'),
('Outbound Product Cost Reship - Activating', 'Act', 'Blended landed cost of the product for reship orders. Includes product, freight and CMT cost. Initial cost estimates are sourced from Oracle EBS, PO SKU and EDW01 (prior to 2018); Landed costs reflect actuals as they become available.', 'COGS'),
('Outbound Product Cost Reship/Exch', 'Total, Act, NonAct', 'Blended landed cost of the product for reships and exchanges. Includes product, freight and CMT cost. Initial cost estimates are sourced from Oracle EBS, PO SKU and EDW01 (prior to 2018); Landed costs reflect actuals as they become available.', 'COGS'),
('Outbound Shipping Cost - Reship/Exch', 'Total, Act, NonAct', 'Shipping cost of reships and exchanges orders.  If the order hasn''t shipped, we use an estimate provided by FP&A', 'COGS'),
('Outbound Shipping Cost Excl. Reship/Exch', 'Total, Act, NonAct', 'Shipping cost of the product order excluding reships and exchanges.  If the order hasn''t shipped, we use an estimate provided by FP&A', 'COGS'),
('Outbound Shipping Cost Incl. Reship/Exch', 'Total, Act, NonAct', 'Shipping cost of the product order including reships and exchanges.  If the order hasn''t shipped, we use an estimate provided by FP&A', 'COGS'),
('Product Cost Net of Returns Incl. Reship/Exch', 'Total', 'Product Order Landed Cost Amount + product_order_reship_product_cost_amount +product_order_exchange_product_cost_amount -product_order_cost_product_returned_resaleable_amount', 'COGS'),
('Product Cost Returned Damaged Incl. Reship/Exch', 'Total', 'The unit cost for the returned items that may not be resold and distributed due to return condition.', 'COGS'),
('Product Cost Returned Resaleable Incl. Reship/Exch', 'Total, Act, NonAct', 'The adjusted unit cost for the returned items that may be resold and distributed.  The percent resaleable is an assumption provided by FP&A - (Returned Item Quantity * Estimated Landed Product Cost * Markdown Adjustment Factor * Percent Resaleable)/Item Quantity in the Original Order', 'COGS'),
('Shipping Cost Reship Exch', 'Total', 'Shipping cost of the and exchange reship orders. If the order hasn''t shipped, we use an estimate provided by FP&A', 'COGS'),
('Shipping Supplies Cost Incl. Reship/Exch', 'Total, Act, NonAct', 'Estimated cost of preparing the product to be shipped to the customer (e.g. cartons, tape, shrink wrap, etc). This cost is an assumption provided by the FP&A department ', 'COGS'),
('Shipping Supplies Cost Reship/Exch', 'Total, Act, NonAct', 'Estimated cost of preparing the product to be shipped to the customer (e.g. cartons, tape, shrink wrap, etc) for reship and exchange orders. This cost is an assumption provided by the FP&A department ', 'COGS'),
('Total COGS Incl. Reship/Exch', 'Total', 'Product Order Landed Cost + Reship/Exch Product Cost + Shipping Cost+ Shipping Supplies Cost + Misc COGS - Product Cost Returned Resaleable', 'COGS'),
('Variable GMS Labor Cost Incl. Reship/Exch', 'Total, Act', 'Estimated variable cost of Global Member services applied to billing orders. This is an assumption provided by the FP&A department', 'COGS'),
('Variable Payment Processing Cost Incl. Reship/Exch', 'Total, Act', 'The fee paid to the credit card processor for a product order. This is an assumption provided by the FP&A department', 'COGS'),
('Variable Warehouse Labor Cost Incl. Reship/Exch', 'Total, Act', 'Fulfillment cost associated with receiving and storing products along with processing orders from handling to shipping. This is an assumption provided by the FP&A department', 'COGS')
