TRUNCATE TABLE reference.credit_state_mapping;


INSERT INTO reference.credit_state_mapping
(
    state_abbreviation,
    state_name,
    giftco_recognition,
    region
)
VALUES ('AK', 'Alaska', 'Cant Recognize', 'Pacific'),
       ('AL', 'Alabama', 'Recognize', 'East South Central'),
       ('AR', 'Arkansas', 'Recognize', 'West South Central'),
       ('AZ', 'Arizona', 'Recognize', 'Mountain'),
       ('CA', 'California', 'Recognize', 'Pacific'),
       ('CO', 'Colorado', 'Cant Recognize', 'Mountain'),
       ('CT', 'Conneticut', 'Recognize', 'New England'),
       ('DC', 'District of Columbia', 'Cant Recognize', 'N/A'),
       ('DE', 'Delaware', 'Cant Recognize', 'South Atlantic'),
       ('FL', 'Florida', 'Recognize', 'South Atlantic'),
       ('GA', 'Georgia', 'Cant Recognize', 'South Atlantic'),
       ('HI', 'Hawaii', 'Recognize', 'Pacific'),
       ('IA', 'Iowa', 'Recognize', 'West North Central'),
       ('ID', 'Idaho', 'Recognize', 'Mountain'),
       ('IL', 'Illinois', 'Recognize', 'East North Central'),
       ('IN', 'Indiana', 'Recognize', 'East North Central'),
       ('KS', 'Kansas', 'Recognize', 'West North Central'),
       ('KY', 'Kentucky', 'Cant Recognize', 'East South Central'),
       ('LA', 'Louisiana', 'Cant Recognize', 'West South Central'),
       ('MA', 'Massachusetts', 'Recognize', 'New England'),
       ('MD', 'Maryland', 'Recognize', 'South Atlantic'),
       ('ME', 'Maine', 'Cant Recognize', 'New England'),
       ('MI', 'Michigan', 'Recognize', 'East North Central'),
       ('MN', 'Minnesota', 'Recognize', 'West North Central'),
       ('MO', 'Missouri', 'Recognize 40%', 'West North Central'),
       ('MS', 'Mississippi', 'Cant Recognize', 'East South Central'),
       ('MT', 'Montana', 'Recognize 40%', 'Mountain'),
       ('NC', 'North Carolina', 'Recognize', 'South Atlantic'),
       ('ND', 'North Dakota', 'Recognize', 'West North Central'),
       ('NE', 'Nebraska', 'Recognize', 'West North Central'),
       ('NH', 'New Hampshire', 'Recognize', 'New England'),
       ('NJ', 'New Jersey', 'Recognize 40%', 'Middle Atlantic'),
       ('NM', 'New Mexico', 'Recognize 40%', 'Mountain'),
       ('NV', 'Nevada', 'Recognize', 'Mountain'),
       ('NY', 'New York', 'Cant Recognize', 'Middle Atlantic'),
       ('OH', 'Ohio', 'Recognize', 'East North Central'),
       ('OK', 'Oklahoma', 'Cant Recognize', 'West South Central'),
       ('OR', 'Oregon', 'Recognize', 'Pacific'),
       ('PA', 'Pennsylvania', 'Recognize', 'Middle Atlantic'),
       ('PR', 'Puerto Rico', 'Recognize', 'N/A'),
       ('RI', 'Rhode Island', 'Recognize', 'New England'),
       ('SC', 'South Carolina', 'Recognize', 'South Atlantic'),
       ('SD', 'South Dakota', 'Recognize', 'West North Central'),
       ('TN', 'Tennessee', 'Recognize', 'East South Central'),
       ('TX', 'Texas', 'Recognize', 'West South Central'),
       ('UT', 'Utah', 'Recognize', 'Mountain'),
       ('VA', 'Virginia', 'Recognize', 'South Atlantic'),
       ('VI', 'Invalid State', 'Recognize', 'N/A'),
       ('VT', 'Vermont', 'Recognize', 'New England'),
       ('WA', 'Washington', 'Recognize', 'Pacific'),
       ('WI', 'Wisconisn', 'Recognize', 'East North Central'),
       ('WV', 'West Virginia', 'Recognize 40%', 'South Atlantic'),
       ('WY', 'Wyoming', 'Recognize', 'Mountain'),
       ('AA', 'Armed Forces Americas', 'Recognize', 'N/A'),
       ('MH', 'Marshall Islands', 'Recognize', 'N/A'),
       ('MP', 'Northern Mariana Islands', 'Recognize', 'N/A'),
       ('PW', 'Palau', 'Recognize', 'N/A'),
       ('AP', 'Armed Forces Pacific', 'Recognize', 'N/A'),
       ('AS', 'America Samoa', 'Recognize', 'N/A'),
       ('FM', 'Federated States of Micronesia', 'Recognize', 'N/A'),
       ('GU', 'Guam', 'Recognize', 'N/A'),
       ('AE', 'US Armed Forces - Europe', 'Recognize', 'N/A');
