
TRUNCATE TABLE reference.config_ssrs_subscription_adhoc;

INSERT INTO reference.config_ssrs_subscription_adhoc (
    report_version,
    report_name,
    param_name,
    param_value
)
VALUES ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'file_name', 'Daily Cash Revenue - EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'file_name', 'Daily Cash Revenue - EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'file_name', 'Daily Cash Revenue - EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'file_name', 'Daily Cash Revenue - EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'file_name', 'Daily Cash Revenue - EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'file_name', 'Daily Cash Revenue - EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'file_name', 'Daily Cash Revenue - EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'file_name', 'Daily Cash Revenue - EU USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'file_name', 'Daily Cash Revenue - Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'file_name', 'Daily Cash Revenue - Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'file_name', 'Daily Cash Revenue - Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'file_name', 'Daily Cash Revenue - Global USD - Shipped Date'),
    ('Weekly KPI', 'Weekly KPI - SXEU-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - SXEU-TREV', 'report_mapping', 'SXEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - SXEU-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SXNA-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - SXNA-TREV', 'report_mapping', 'SXNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - SXNA-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SXWW-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXWW-TREV'),
    ('Weekly KPI', 'Weekly KPI - SXWW-TREV', 'report_mapping', 'SXWW-TREV'),
    ('Weekly KPI', 'Weekly KPI - SXWW-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SXUS - Retail Total Revenue and Retail VIP Acquisition', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXUS - Retail Total Revenue and Retail VIP Acquisition'),
    ('Weekly KPI', 'Weekly KPI - SXUS - Retail Total Revenue and Retail VIP Acquisition', 'report_mapping', 'SXUS-RREV'),
    ('Weekly KPI', 'Weekly KPI - SXUS - Retail Total Revenue and Retail VIP Acquisition', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SXUS-RREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXUS-RREV'),
    ('Weekly KPI', 'Weekly KPI - SXUS-RREV', 'report_mapping', 'SXUS-RREV'),
    ('Weekly KPI', 'Weekly KPI - SXUS-RREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FKNA-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - FKNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - FKNA-TREV', 'report_mapping', 'FKNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - FKNA-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLEU-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-TREV', 'report_mapping', 'FLEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLEU-FVIP-OREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-FVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-FVIP-OREV', 'report_mapping', 'FLEU-FVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-FVIP-OREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLEU-MVIP-OREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-MVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-MVIP-OREV', 'report_mapping', 'FLEU-MVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-MVIP-OREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLNA-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-TREV', 'report_mapping', 'FLNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLNA-OREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-OREV', 'report_mapping', 'FLNA-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-OREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLNA-FVIP-OREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-FVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-FVIP-OREV', 'report_mapping', 'FLNA-FVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-FVIP-OREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLNA-MVIP-OREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-MVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-MVIP-OREV', 'report_mapping', 'FLNA-MVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-MVIP-OREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLNA - Retail Total Revenue and Retail VIP Acquisition', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA - Retail Total Revenue and Retail VIP Acquisition'),
    ('Weekly KPI', 'Weekly KPI - FLNA - Retail Total Revenue and Retail VIP Acquisition', 'report_mapping', 'FLNA-RREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA - Retail Total Revenue and Retail VIP Acquisition', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLNA-RREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-RREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-RREV', 'report_mapping', 'FLNA-RREV'),
    ('Weekly KPI', 'Weekly KPI - FLNA-RREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - YTNA-OREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - YTNA-OREV'),
    ('Weekly KPI', 'Weekly KPI - YTNA-OREV', 'report_mapping', 'YTNA-OREV'),
    ('Weekly KPI', 'Weekly KPI - YTNA-OREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLEU - Retail Total Revenue and Retail VIP Acquisition', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU - Retail Total Revenue and Retail VIP Acquisition'),
    ('Weekly KPI', 'Weekly KPI - FLEU - Retail Total Revenue and Retail VIP Acquisition', 'report_mapping', 'FLEU-RREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU - Retail Total Revenue and Retail VIP Acquisition', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLEU-RREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-RREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-RREV', 'report_mapping', 'FLEU-RREV'),
    ('Weekly KPI', 'Weekly KPI - FLEU-RREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - JFEU-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - JFEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - JFEU-TREV', 'report_mapping', 'JFEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - JFEU-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - JFNA-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - JFNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - JFNA-TREV', 'report_mapping', 'JFNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - JFNA-TREV', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SDNA-TREV', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - SDNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - SDNA-TREV', 'report_mapping', 'SDNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - SDNA-TREV', 'noofmonths', '13'),
    ('CPA by Lead Channel NA', 'CPA by Lead Channel - USD-exclSXF', 'currency', 'USD'),
    ('CPA by Lead Channel NA', 'CPA by Lead Channel - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('CPA by Lead Channel NA', 'CPA by Lead Channel - USD-exclSXF', 'email', 'CPA-BY-LEAD-NA-SSRS-REPORT-USERS@JustFab.com'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - USD-exclSXF', 'currency', 'USD'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - USD-exclSXF', 'email', 'CPA-BY-LEAD-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - Local-exclSXF', 'currency', 'Local'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - Local-exclSXF', 'report_version', 'Local-exclSXF'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - Local-exclSXF', 'email', 'CPA-BY-LEAD-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('Total CPA Report NA', 'Total CPA Report - USD-exclSXF', 'currency', 'USD'),
    ('Total CPA Report NA', 'Total CPA Report - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('Total CPA Report NA', 'Total CPA Report - USD-exclSXF', 'email', 'TOTAL-CPA-NA-SSRS-REPORT-USERS@JustFab.com'),
    ('Total CPA Report EU', 'Total CPA Report - USD-exclSXF', 'currency', 'USD'),
    ('Total CPA Report EU', 'Total CPA Report - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('Total CPA Report EU', 'Total CPA Report - USD-exclSXF', 'email', 'TOTAL-CPA-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('Total CPA Report EU', 'Total CPA Report - Local-exclSXF', 'currency', 'Local'),
    ('Total CPA Report EU', 'Total CPA Report - Local-exclSXF', 'report_version', 'Local-exclSXF'),
    ('Total CPA Report EU', 'Total CPA Report - Local-exclSXF', 'email', 'TOTAL-CPA-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - FL USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - FL USD', 'report_version', 'FL-USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - FL USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\CAC by Lead\\All Brands - USD'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - FL Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - FL Local', 'report_version', 'FL-Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - FL Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\CAC by Lead\\EU Brands - Local'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - SX USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - SX USD', 'report_version', 'SXF-USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - SX USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\CAC by Lead\\All Brands - USD'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - SX Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - SX Local', 'report_version', 'SXF-Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - SX Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\CAC by Lead\\EU Brands - Local'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - JFB USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - JFB USD', 'report_version', 'JFB-USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - JFB USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\CAC by Lead\\All Brands - USD'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - JFB Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - JFB Local', 'report_version', 'JFB-Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - JFB Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\CAC by Lead\\EU Brands - Local'),
    ('Total CAC Report NA', 'Total CAC - FL USD', 'currency', 'USD'),
    ('Total CAC Report NA', 'Total CAC - FL USD', 'report_version', 'FL-USD'),
    ('Total CAC Report EU', 'Total CAC - FL Local', 'currency', 'Local'),
    ('Total CAC Report EU', 'Total CAC - FL Local', 'report_version', 'FL-Local'),
    ('Total CAC Report NA', 'Total CAC - SX USD', 'currency', 'USD'),
    ('Total CAC Report NA', 'Total CAC - SX USD', 'report_version', 'SXF-USD'),
    ('Total CAC Report NA', 'Total CAC - SX USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\Total CAC\\All Brands - USD'),
    ('Total CAC Report EU', 'Total CAC - SX Local', 'currency', 'Local'),
    ('Total CAC Report EU', 'Total CAC - SX Local', 'report_version', 'SXF-Local'),
    ('Total CAC Report EU', 'Total CAC - SX Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\Total CAC\\EU Brands - Local'),
    ('Total CAC Report NA', 'Total CAC - JFB USD', 'currency', 'USD'),
    ('Total CAC Report NA', 'Total CAC - JFB USD', 'report_version', 'JFB-USD'),
    ('Total CAC Report NA', 'Total CAC - JFB USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\Total CAC\\All Brands - USD'),
    ('Total CAC Report EU', 'Total CAC - JFB Local', 'currency', 'Local'),
    ('Total CAC Report EU', 'Total CAC - JFB Local', 'report_version', 'JFB-Local'),
    ('Total CAC Report EU', 'Total CAC - JFB Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\Total CAC\\EU Brands - Local'),
    ('Total CAC Report NA', 'Total CAC - FL USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\Total CAC\\All Brands - USD'),
    ('Total CAC Report EU', 'Total CAC - FL Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\Total CAC\\EU Brands - Local'),
    ('Lead to VIP Waterfall', 'FL Lead to VIP Waterfall', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Fabletics\\Lead to VIP Waterfall'),
    ('Lead to VIP Waterfall', 'FL Lead to VIP Waterfall', 'brand_mapping', 'Fabletics'),
    ('Lead to VIP Waterfall', 'JFB Lead to VIP Waterfall', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\JFB\\Lead to VIP Waterfall'),
    ('Lead to VIP Waterfall', 'JFB Lead to VIP Waterfall', 'brand_mapping', 'JFB'),
    ('Lead to VIP Waterfall', 'SX Lead to VIP Waterfall', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Savage X\\Lead to VIP Waterfall'),
    ('Lead to VIP Waterfall', 'SX Lead to VIP Waterfall', 'brand_mapping', 'Savage X');
