
TRUNCATE TABLE reference.config_ssrs_subscription;

INSERT INTO reference.config_ssrs_subscription (
    report_version,
    report_name,
    param_name,
    param_value
)
VALUES ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date JFB', 'file_name', 'Daily Cash Revenue - EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Placed Date Savage X', 'file_name', 'Daily Cash Revenue - EU Local - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date JFB', 'file_name', 'Daily Cash Revenue - EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'currency_object', 'local'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU Local - Shipped Date Savage X', 'file_name', 'Daily Cash Revenue - EU Local - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date JFB', 'file_name', 'Daily Cash Revenue - EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'date_object', 'placed'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Placed Date Savage X', 'file_name', 'Daily Cash Revenue - EU USD - Placed Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date JFB', 'file_name', 'Daily Cash Revenue - EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash EU USD - Shipped Date'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'date_object', 'shipped'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash EU', 'Daily Cash Revenue - EU USD - Shipped Date Savage X', 'file_name', 'Daily Cash Revenue - EU USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date JFB', 'file_name', 'Daily Cash Revenue - Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Placed Date Savage X', 'file_name', 'Daily Cash Revenue - Global USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date JFB', 'file_name', 'Daily Cash Revenue - Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global USD - Shipped Date Savage X', 'file_name', 'Daily Cash Revenue - Global USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash Global By Country USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - Global by Country USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash Global By Country USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date JFB', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date JFB', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date JFB', 'file_name', 'Daily Cash Revenue - Global by Country USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash Global By Country USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Savage X', 'date_object', 'placed'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Placed Date Savage X', 'file_name', 'Daily Cash Revenue - Global by Country USD - Placed Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Daily Cash\\Daily Cash Global By Country USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - Global by Country USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date JFB', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Daily Cash\\Daily Cash Global By Country USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date JFB', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date JFB', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date JFB', 'store_brand', 'JFB'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date JFB', 'file_name', 'Daily Cash Revenue - Global by Country USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Savage X', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Daily Cash\\Daily Cash Global By Country USD - Shipped Date'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Savage X', 'currency_object', 'usd'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Savage X', 'date_object', 'shipped'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Savage X', 'store_brand', 'Savage X'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Placed Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Capital Plan\\Daily Cash Global USD - Placed Date - Capital Raise'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Placed Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Placed Date Fabletics', 'date_object', 'placed'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Placed Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Placed Date Fabletics', 'file_name', 'Daily Cash Revenue - Global USD - Placed Date - Capital Raise'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Capital Plan\\Daily Cash Global USD - Shipped Date - Capital Raise'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'currency_object', 'usd'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'date_object', 'shipped'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'store_brand', 'Fabletics'),
    ('Daily Cash CapRaise', 'CapRaise Daily Cash Revenue - Global USD - Shipped Date Fabletics', 'file_name', 'Daily Cash Revenue - Global USD - Shipped Date - Capital Raise'),
    ('Daily Cash NA', 'Daily Cash Revenue - Global by Country USD - Shipped Date Savage X', 'file_name', 'Daily Cash Revenue - Global by Country USD - Shipped Date'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-EU', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-EU', 'report_mapping', 'SX-TREV-EU'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-EU', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-NA', 'report_mapping', 'SX-TREV-NA'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SX-OREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SX-OREV-NA'),
    ('Weekly KPI', 'Weekly KPI - SX-OREV-NA', 'report_mapping', 'SX-OREV-NA'),
    ('Weekly KPI', 'Weekly KPI - SX-OREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-Global', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXWW-TREV'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-Global', 'report_mapping', 'SX-TREV-Global'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-Global', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SX-US - Retail Total Revenue and Retail VIP Acquisition', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXUS - Retail Total Revenue and Retail VIP Acquisition'),
    ('Weekly KPI', 'Weekly KPI - SX-US - Retail Total Revenue and Retail VIP Acquisition', 'report_mapping', 'SX-RREV-US'),
    ('Weekly KPI', 'Weekly KPI - SX-US - Retail Total Revenue and Retail VIP Acquisition', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SX-RREV-US', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SXUS-RREV'),
    ('Weekly KPI', 'Weekly KPI - SX-RREV-US', 'report_mapping', 'SX-RREV-US'),
    ('Weekly KPI', 'Weekly KPI - SX-RREV-US', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-CA-US', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\Weekly KPI\\Weekly KPI - SX-TREV-CA-US'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-CA-US', 'report_mapping', 'SX-TREV-CA-US'),
    ('Weekly KPI', 'Weekly KPI - SX-TREV-CA-US', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FK-TREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - FKNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - FK-TREV-NA', 'report_mapping', 'FK-TREV-NA'),
    ('Weekly KPI', 'Weekly KPI - FK-TREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FL-TREV-EU', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - FL-TREV-EU', 'report_mapping', 'FL-TREV-EU'),
    ('Weekly KPI', 'Weekly KPI - FL-TREV-EU', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FL-W-OREV-EU', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-FVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FL-W-OREV-EU', 'report_mapping', 'FL-W-OREV-EU'),
    ('Weekly KPI', 'Weekly KPI - FL-W-OREV-EU', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FL-M-OREV-EU', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-MVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FL-M-OREV-EU', 'report_mapping', 'FL-M-OREV-EU'),
    ('Weekly KPI', 'Weekly KPI - FL-M-OREV-EU', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLSC-TREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - FLSC-TREV-NA', 'report_mapping', 'FL+SC-TREV-NA'),
    ('Weekly KPI', 'Weekly KPI - FLSC-TREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLSC-OREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLSC-OREV-NA', 'report_mapping', 'FL+SC-OREV-NA'),
    ('Weekly KPI', 'Weekly KPI - FLSC-OREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLSC-W-OREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-FVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLSC-W-OREV-NA', 'report_mapping', 'FL+SC-W-OREV-NA'),
    ('Weekly KPI', 'Weekly KPI - FLSC-W-OREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLSC-M-OREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-MVIP-OREV'),
    ('Weekly KPI', 'Weekly KPI - FLSC-M-OREV-NA', 'report_mapping', 'FL+SC-M-OREV-NA'),
    ('Weekly KPI', 'Weekly KPI - FLSC-M-OREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FL-NA - Retail Total Revenue and Retail VIP Acquisition', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA - Retail Total Revenue and Retail VIP Acquisition'),
    ('Weekly KPI', 'Weekly KPI - FL-NA - Retail Total Revenue and Retail VIP Acquisition', 'report_mapping', 'FL+SC-RREV-NA'),
    ('Weekly KPI', 'Weekly KPI - FL-NA - Retail Total Revenue and Retail VIP Acquisition', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FLSC-RREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLNA-RREV'),
    ('Weekly KPI', 'Weekly KPI - FLSC-RREV-NA', 'report_mapping', 'FL+SC-RREV-NA'),
    ('Weekly KPI', 'Weekly KPI - FLSC-RREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - YT-OREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - YTNA-OREV'),
    ('Weekly KPI', 'Weekly KPI - YT-OREV-NA', 'report_mapping', 'YT-OREV-NA'),
    ('Weekly KPI', 'Weekly KPI - YT-OREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FL-EU - Retail Total Revenue and Retail VIP Acquisition', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU - Retail Total Revenue and Retail VIP Acquisition'),
    ('Weekly KPI', 'Weekly KPI - FL-EU - Retail Total Revenue and Retail VIP Acquisition', 'report_mapping', 'FL-RREV-EU'),
    ('Weekly KPI', 'Weekly KPI - FL-EU - Retail Total Revenue and Retail VIP Acquisition', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - FL-RREV-EU', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\Weekly KPI\\Weekly KPI - FLEU-RREV'),
    ('Weekly KPI', 'Weekly KPI - FL-RREV-EU', 'report_mapping', 'FL-RREV-EU'),
    ('Weekly KPI', 'Weekly KPI - FL-RREV-EU', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - JF-TREV-EU', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - JFEU-TREV'),
    ('Weekly KPI', 'Weekly KPI - JF-TREV-EU', 'report_mapping', 'JF-TREV-EU'),
    ('Weekly KPI', 'Weekly KPI - JF-TREV-EU', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - JF-TREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - JFNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - JF-TREV-NA', 'report_mapping', 'JF-TREV-NA'),
    ('Weekly KPI', 'Weekly KPI - JF-TREV-NA', 'noofmonths', '13'),
    ('Weekly KPI', 'Weekly KPI - SD-TREV-NA', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\Weekly KPI\\Weekly KPI - SDNA-TREV'),
    ('Weekly KPI', 'Weekly KPI - SD-TREV-NA', 'report_mapping', 'SD-TREV-NA'),
    ('Weekly KPI', 'Weekly KPI - SD-TREV-NA', 'noofmonths', '13'),
    ('CPA by Lead Channel NA', 'CPA by Lead Channel - USD-exclSXF', 'currency', 'USD'),
    ('CPA by Lead Channel NA', 'CPA by Lead Channel - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('CPA by Lead Channel NA', 'CPA by Lead Channel - USD-exclSXF', 'email', 'CPA-BY-LEAD-NA-SSRS-REPORT-USERS@JustFab.com'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - USD-exclSXF', 'currency', 'USD'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - USD-exclSXF', 'email', 'CPA-BY-LEAD-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - Local-exclSXF', 'currency', 'Local'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - Local-exclSXF', 'report_version', 'Local-exclSXF'),
    ('CPA by Lead Channel EU', 'CPA by Lead Channel - Local-exclSXF', 'email', 'CPA-BY-LEAD-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('Total CPA Report NA', 'Total CPA Report - USD-exclSXF', 'currency', 'USD'),
    ('Total CPA Report NA', 'Total CPA Report - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('Total CPA Report NA', 'Total CPA Report - USD-exclSXF', 'email', 'TOTAL-CPA-NA-SSRS-REPORT-USERS@JustFab.com'),
    ('Total CPA Report EU', 'Total CPA Report - USD-exclSXF', 'currency', 'USD'),
    ('Total CPA Report EU', 'Total CPA Report - USD-exclSXF', 'report_version', 'USD-exclSXF'),
    ('Total CPA Report EU', 'Total CPA Report - USD-exclSXF', 'email', 'TOTAL-CPA-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('Total CPA Report EU', 'Total CPA Report - Local-exclSXF', 'currency', 'Local'),
    ('Total CPA Report EU', 'Total CPA Report - Local-exclSXF', 'report_version', 'Local-exclSXF'),
    ('Total CPA Report EU', 'Total CPA Report - Local-exclSXF', 'email', 'TOTAL-CPA-EU-SSRS-REPORT-USERS@JustFab.com'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - FL USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - FL USD', 'report_version', 'FL-USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - FL USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\CAC by Lead\\All Brands - USD'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - FL Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - FL Local', 'report_version', 'FL-Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - FL Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\CAC by Lead\\EU Brands - Local'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - SX USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - SX USD', 'report_version', 'SXF-USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - SX USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\CAC by Lead\\All Brands - USD'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - SX Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - SX Local', 'report_version', 'SXF-Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - SX Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\CAC by Lead\\EU Brands - Local'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - JFB USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - JFB USD', 'report_version', 'JFB-USD'),
    ('CAC by Lead Channel NA', 'CAC By Lead Channel - JFB USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\CAC by Lead\\All Brands - USD'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - JFB Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - JFB Local', 'report_version', 'JFB-Local'),
    ('CAC by Lead Channel EU', 'CAC By Lead Channel - JFB Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\CAC by Lead\\EU Brands - Local'),
    ('Total CAC Report NA', 'Total CAC - FL USD', 'currency', 'USD'),
    ('Total CAC Report NA', 'Total CAC - FL USD', 'report_version', 'FL-USD'),
    ('Total CAC Report EU', 'Total CAC - FL Local', 'currency', 'Local'),
    ('Total CAC Report EU', 'Total CAC - FL Local', 'report_version', 'FL-Local'),
    ('Total CAC Report NA', 'Total CAC - SX USD', 'currency', 'USD'),
    ('Total CAC Report NA', 'Total CAC - SX USD', 'report_version', 'SXF-USD'),
    ('Total CAC Report NA', 'Total CAC - SX USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\Total CAC\\All Brands - USD'),
    ('Total CAC Report EU', 'Total CAC - SX Local', 'currency', 'Local'),
    ('Total CAC Report EU', 'Total CAC - SX Local', 'report_version', 'SXF-Local'),
    ('Total CAC Report EU', 'Total CAC - SX Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\CAC Reports\\Total CAC\\EU Brands - Local'),
    ('Total CAC Report NA', 'Total CAC - JFB USD', 'currency', 'USD'),
    ('Total CAC Report NA', 'Total CAC - JFB USD', 'report_version', 'JFB-USD'),
    ('Total CAC Report NA', 'Total CAC - JFB USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\Total CAC\\All Brands - USD'),
    ('Total CAC Report EU', 'Total CAC - JFB Local', 'currency', 'Local'),
    ('Total CAC Report EU', 'Total CAC - JFB Local', 'report_version', 'JFB-Local'),
    ('Total CAC Report EU', 'Total CAC - JFB Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\CAC Reports\\Total CAC\\EU Brands - Local'),
    ('Total CAC Report NA', 'Total CAC - FL USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\Total CAC\\All Brands - USD'),
    ('Total CAC Report EU', 'Total CAC - FL Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\CAC Reports\\Total CAC\\EU Brands - Local'),
    ('Lead to VIP Waterfall', 'FL Lead to VIP Waterfall', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Fabletics\\Lead to VIP Waterfall'),
    ('Lead to VIP Waterfall', 'FL Lead to VIP Waterfall', 'brand_mapping', 'Fabletics'),
    ('Lead to VIP Waterfall', 'JFB Lead to VIP Waterfall', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\JFB\\Lead to VIP Waterfall'),
    ('Lead to VIP Waterfall', 'JFB Lead to VIP Waterfall', 'brand_mapping', 'JFB'),
    ('Lead to VIP Waterfall', 'SX Lead to VIP Waterfall', 'file_path', '\\\\tfgelsvm12nas01\\data analytics$\\Sharepoint Root\\Savage X\\Lead to VIP Waterfall'),
    ('Lead to VIP Waterfall', 'SX Lead to VIP Waterfall', 'brand_mapping', 'Savage X'),

    ('CAC by Lead Channel EU New', 'FLEU - Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\NEW CAC Reports\\CAC by Lead\\FLEU - Local'),
    ('CAC by Lead Channel EU New', 'FLEU - Local', 'currency', 'USD'),
    ('CAC by Lead Channel EU New', 'FLEU - Local', 'report_version', 'FLEU - Local'),
    ('CAC by Lead Channel EU New', 'JFEU - Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU New', 'JFEU - Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\NEW CAC Reports\\CAC by Lead\\JFEU - Local'),
    ('CAC by Lead Channel EU New', 'JFEU - Local', 'report_version', 'JFEU - Local'),
    ('CAC by Lead Channel EU New', 'SXEU - Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\NEW CAC Reports\\CAC by Lead\\SXEU - Local'),
    ('CAC by Lead Channel EU New', 'SXEU - Local', 'currency', 'Local'),
    ('CAC by Lead Channel EU New', 'SXEU - Local', 'report_version', 'SXEU - Local'),
    ('CAC by Lead Channel NA New', 'FL GLOBAL by Country - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\NEW CAC Reports\\CAC by Lead\\FL GLOBAL by Country - USD'),
    ('CAC by Lead Channel NA New', 'FL GLOBAL by Country - USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA New', 'FL GLOBAL by Country - USD', 'report_version', 'FL GLOBAL by Country - USD'),
    ('CAC by Lead Channel NA New', 'FL GLOBAL by Region - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\NEW CAC Reports\\CAC by Lead\\FL GLOBAL by Region - USD'),
    ('CAC by Lead Channel NA New', 'FL GLOBAL by Region - USD', 'report_version', 'FL GLOBAL by Region - USD'),
    ('CAC by Lead Channel NA New', 'FL GLOBAL by Region - USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA New', 'JFB GLOBAL - USD', 'report_version', 'JFB GLOBAL - USD'),
    ('CAC by Lead Channel NA New', 'JFB GLOBAL - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\NEW CAC Reports\\CAC by Lead\\JFB GLOBAL - USD'),
    ('CAC by Lead Channel NA New', 'JFB GLOBAL - USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA New', 'SXF GLOBAL - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\NEW CAC Reports\\CAC by Lead\\SXF GLOBAL - USD'),
    ('CAC by Lead Channel NA New', 'SXF GLOBAL - USD', 'currency', 'USD'),
    ('CAC by Lead Channel NA New', 'SXF GLOBAL - USD', 'report_version', 'SXF GLOBAL - USD'),

    ('Total CAC Report EU New', 'FLEU - Local', 'currency', 'Local'),
    ('Total CAC Report EU New', 'FLEU - Local', 'report_version', 'FLEU - Local'),
    ('Total CAC Report EU New', 'FLEU - Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\NEW CAC Reports\\Total CAC\\FLEU - Local'),
    ('Total CAC Report EU New', 'JFEU - Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\NEW CAC Reports\\Total CAC\\JFEU - Local'),
    ('Total CAC Report EU New', 'JFEU - Local', 'currency ', 'Local'),
    ('Total CAC Report EU New', 'JFEU - Local', 'report_version', 'JFEU - Local'),
    ('Total CAC Report EU New', 'SXEU - Local', 'report_version', 'SXEU - Local'),
    ('Total CAC Report EU New', 'SXEU - Local', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\NEW CAC Reports\\Total CAC\\SXEU - Local'),
    ('Total CAC Report EU New', 'SXEU - Local', 'currency', 'Local'),
    ('Total CAC Report NA New', 'FL GLOBAL by Country - USD', 'report_version', 'FL GLOBAL by Country - USD'),
    ('Total CAC Report NA New', 'FL GLOBAL by Country - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\NEW CAC Reports\\Total CAC\\FL GLOBAL by Country - USD'),
    ('Total CAC Report NA New', 'FL GLOBAL by Country - USD', 'currency', 'USD'),
    ('Total CAC Report NA New', 'FL GLOBAL by Region - USD', 'report_version', 'FL GLOBAL by Region - USD'),
    ('Total CAC Report NA New', 'FL GLOBAL by Region - USD', 'currency', 'USD'),
    ('Total CAC Report NA New', 'FL GLOBAL by Region - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Fabletics\\NEW CAC Reports\\Total CAC\\FL GLOBAL by Region - USD'),
    ('Total CAC Report NA New', 'JFB GLOBAL - USD', 'report_version', 'JFB GLOBAL - USD'),
    ('Total CAC Report NA New', 'JFB GLOBAL - USD', 'currency', 'USD'),
    ('Total CAC Report NA New', 'JFB GLOBAL - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\JFB\\NEW CAC Reports\\Total CAC\\JFB GLOBAL - USD'),
    ('Total CAC Report NA New', 'SXF GLOBAL - USD', 'report_version', 'SXF GLOBAL - USD'),
    ('Total CAC Report NA New', 'SXF GLOBAL - USD', 'currency', 'USD'),
    ('Total CAC Report NA New', 'SXF GLOBAL - USD', 'path', '\\\\itbtsnnas01\\Data Analytics$\\Sharepoint Root\\Daily Cash & Weekly KPI\\Daily Cash\\Savage X\\NEW CAC Reports\\Total CAC\\SXF GLOBAL - USD');
