INSERT INTO reference.validation_tables_info(schema_name, table_name, subject, body) VALUES
('validation', 'finance_currency_conversion_missing_currency', ' EDW - Finance Currency Conversion', ' list of local currencies in reference.finance_currency_conversion that are either missing or about to expire '),
('validation', 'exchange_rate_check_for_duplicates', ' EDW - Duplicate Records in Exchange Rate Tables', ' list of duplicate records in EDW exchange rate table(s): '),
('validation', 'new_store_in_dim_store', ' EDW - New store added in EDW', ' list of new stores that are added to EDW recently'),
('validation', 'finance_assumptions_fact_order_mismatch', ' EDW - Finance Assumptions in Fact Order', ' list of BUs with incorrect assumptions metrics in stg.fact_order:'),
('validation', 'finance_assumptions_fact_return_line_mismatch', ' EDW - Finance Assumptions in Fact Return Line', ' list of BUs with incorrect assumptions metrics in stg.fact_return_line:'),
('validation', 'fact_order_and_fact_return_line_missing_assumptions', ' EDW - Finance Assumptions Missing ', 'Finance assumptions for the below BUs needs to be added to reference.finance_assumption table immediately :'),
('validation', 'edw_exception_count', ' EDW - Exception Counts', ' list of exception tables with records:'),
('validation', 'fact_order_test_orders', ' Fact_Order Test Order Variance', ' fact_order test order variances:'),
('validation', 'membership_level_mismatch', ' EDW - Membership Level Discrepancies in Dim Customer', ' membership_level discrepancies between dim_customer and source:'),
('validation', 'fact_credit_event_comparison', ' EDW - Discrepancies between EDW and Reporting Base Fact Credit Event', ' credit level discrepancies between reporting_base.shared.fact_credit_event and edw.stg.fact_credit_event:'),
('validation', 'dim_credit_comparison', ' EDW - Discrepancies between EDW and Reporting Base Dim Credit', ' credit level discrepancies between reporting_base.shared.dim_credit and edw.stg.dim_credit:'),
('validation', 'fact_credit_event_orphan_records_count', ' EDW - Orphan Records in Fact Credit Event', ' orphan credit count in stg.fact_credit_event. These credits do not join to stg.dim_credit:'),
('validation', 'landed_cost_zero', ' SKU\'s with zero landed cost ', ' sku\'s in fact_inventory has zero landed cost:'),
('validation', 'actual_landed_cost_changes','Actual landed cost changed', 'The list of skus\'s for the given PO number, PO line number, and year month received, where the actual landed cost has changed compared to yesterday\'s data, despite being fully landed:'),
('validation', 'dim_credit_unknown_report_mappings', ' Dim Credit Unknown Credit Report Mappings', ' combinations of dependent columns for which the credit report mapping and credit report sub mapping are unknown:'),
('validation', 'edw_credit_equivalent_count', ' Credit Tables with NULL Equivalent Counts', ' you can find the number of the credit records with NULL credit equivalent counts:'),
('validation', 'fl_scrubs_product_taxonomy', ' FL Scrubs Product Taxonomy', ' are a list of unexpected FL Scrubs department values in dim_product:'),
('validation', 'fact_credit_event_historical_snapshot_comparison_count', ' EDW - Day over day changes in Fact Credit Event', ' day over day credit event level discrepancies for fact_credit_event:'),
('validation', 'fake_retail_leads_with_activations', ' Fake retail leads with Activations ', ' list of customers with fake retail leads with activations They are added to the reference.fake_retail_leads_with_activations.The is_fake_retail_registration flag for these customers in fact registration will be updated to FALSE on the next run:'),
('validation', 'receivables_trx_name', ' New receivables_trx_name', ' new receivables_trx_name in chargeback data.Please make sure to add it to reference.gl_trx_store:'),
('validation', 'new_vendor_in_oracle_ebs', ' New Vendor in Oracle ebs', ' new source in chargeback_eu/us'),
('validation', 'chargeback_lake_edw_comparison', 'Chargeback Data comparsion between Lake vs EDW ', 'Chargeback Data comparsion between Lake vs EDW:'),
('validation', 'new_membership_brand', ' New Membership brand Id', ' new membership_brand_id added into lake ultra merchant membership brand:'),
('validation', 'fact_order_missing_fx_rates', ' Fact Order Missing fx Rates', ' count of null order date conversion rate or reporting conversion rate:'),
('validation', 'warehouse_outlet_order_alert', ' Warehouse Outlet Order Alert', ' count of warehouse outlet orders with token redemption or promo discount:'),
('validation', 'return_and_rma_duplicates', 'Third party return and rma duplicates alert', ' count of return and rma duplicates:'),
('validation', 'utm_medium_and_utm_source_duplicates', 'UTM Medium and UTM Source duplicates alert', ' count of utm medium and utm source duplicates:');
