TRUNCATE TABLE reference.credit_report_mapping;

INSERT INTO reference.credit_report_mapping
(original_credit_tender,
 original_credit_type,
 original_credit_reason,
 report_mapping,
 original_credit_match_reason,
 report_sub_mapping)
VALUES ('Cash', 'Fixed Credit', 'Membership Credit', 'Billed Credit', 'Converted To Variable To Token',
        'Billed Credit - Credit Converted To Token'),
       ('Cash', 'Fixed Credit', 'Refund', 'Billed Credit', 'Converted To Variable To Token',
        'Refund Credit - Credit Converted To Token'),
       ('Cash', 'Fixed Credit', 'Membership Credit', 'Billed Credit', 'Already Original', 'Billed Credit - Credit'),
       ('Cash', 'Fixed Credit', 'Membership Credit', 'Billed Credit', 'Converted To Token',
        'Billed Credit - Credit Converted To Token'),
       ('Cash', 'Fixed Credit', 'Membership Credit', 'Billed Credit', 'Converted To Variable',
        'Billed Credit - Credit Converted To Variable'),
       ('Cash', 'Token', 'Token Billing', 'Billed Credit', 'Already Original', 'Billed Credit - Token'),
       ('NonCash', 'Fixed Credit', 'Brand Ambassador Credit', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Brand Ambassador Credit', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Employee Credit', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Employee Credit', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Endowment', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Endowment', 'NonCash Credit', 'Converted To Variable', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Endowment - VIP Only', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Endowment - VIP Only', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Gift Card - Promotional', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Gift Card'),
       ('NonCash', 'Fixed Credit', 'Gift Card - Promotional', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Gift Card'),
       ('NonCash', 'Fixed Credit', 'Internal Use Credit', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Internal Use Credit', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Loyalty Credit', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Loyalty Credit', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Manager Discretion', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Manager Discretion', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Other', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Other', 'NonCash Credit', 'Converted To Variable', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Promotional', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Promotional', 'NonCash Credit', 'Converted To Variable', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Refund - NonCash', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Fixed Credit', 'Refund - NonCash', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('NonCash', 'Token', 'Manager Discretion', 'NonCash Credit', 'Already Original', 'NonCash Credit - Token'),
       ('NonCash', 'Token', 'Refund - NonCash', 'NonCash Credit', 'Already Original', 'NonCash Credit - Token'),
       ('NonCash', 'Variable Credit', 'Brand Ambassador Credit', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Employee Credit', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Endowment', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Endowment - VIP Only', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Gift Card - Promotional', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Gift Card'),
       ('NonCash', 'Variable Credit', 'Internal Use Credit', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Loyalty Credit', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Manager Discretion', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Other', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Promotional', 'NonCash Credit', 'Already Original', 'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Refund - NonCash', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Gift Certificate', 'Gift Certificate', 'NonCash Credit', 'None',
        'NonCash Credit - Direct Gift Card'),
       ('Cash', 'Fixed Credit', 'Gift Card - Paid', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Gift Card'),
       ('Cash', 'Fixed Credit', 'ShoeDazzle Classic Credit', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Fixed Credit', 'ShoeDazzle Classic Credit', 'Other Cash Credit', 'Converted To Variable',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Variable Credit', 'Gift Card - Paid', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Gift Card'),
       ('Cash', 'Variable Credit', 'Legacy Credit', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Variable Credit', 'Other Membership Credit', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Other Credit'),
       ('Cash', 'Variable Credit', 'Gift Card Redemption (Gift Certificate)', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Gift Card'),
       ('Cash', 'Variable Credit', 'ShoeDazzle Classic Credit', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Gift Certificate', 'Gift Certificate', 'Other Cash Credit', 'None',
        'Other Cash Credit - Direct Gift Card'),
       ('Cash', 'Giftcard', 'Gift Card - Paid', 'Other Cash Credit', 'Gift Card Converted to Store Credit',
        'Other Cash Credit - Gift Card'),
       ('Cash', 'Giftcard', 'Gift Card - Paid', 'Other Cash Credit', 'Already Original',
        'Other Cash Credit - Direct Gift Card'),
       ('Cash', 'Fixed Credit', 'Refund', 'Refund Credit', 'Already Original', 'Refund Credit - Credit'),
       ('Cash', 'Fixed Credit', 'Refund', 'Refund Credit', 'Converted To Token', 'Refund Credit - Credit'),
       ('Cash', 'Fixed Credit', 'Refund', 'Refund Credit', 'Converted To Variable', 'Refund Credit - Credit'),
       ('Cash', 'Fixed Credit', 'Membership Credit', 'Billed Credit', 'Converted To Variable And Giftco Roundtrip',
        'Billed Credit - Credit Giftco Roundtrip'),
       ('Cash', 'Fixed Credit', 'Refund', 'Refund Credit', 'Converted To Variable And Giftco Roundtrip',
        'Refund Credit - Credit'),
       ('Cash', 'Token', 'Refund', 'Refund Credit', 'Already Original', 'Refund Credit - Token'),
       ('Cash', 'Variable Credit', 'Refund', 'Refund Credit', 'Already Original', 'Refund Credit - Credit'),
       ('Cash', 'Variable Credit', 'Refund - Partial Shipment', 'Refund Credit', 'Already Original',
        'Refund Credit - Credit'),
       ('Cash', 'Variable Credit', 'Refund - Partial Shipment', 'Refund Credit', 'Converted To Token',
        'Refund Credit - Credit'),
       ('Cash', 'Variable Credit', 'Refund - Partial Shipment', 'Refund Credit', 'Converted To Variable',
        'Refund Credit - Credit'),
       ('Cash', 'Fixed Credit', 'Membership Credit', 'Billed Credit', 'Giftco Roundtrip',
        'Billed Credit - Credit Giftco Roundtrip'),
       ('NonCash', 'Fixed Credit', 'Gift Card - Promotional', 'NonCash Credit', 'Giftco Roundtrip',
        'NonCash Credit - Gift Card'),
       ('NonCash', 'Variable Credit', 'Endowment', 'NonCash Credit', 'Giftco Roundtrip', 'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Gift Card - Promotional', 'NonCash Credit', 'Giftco Roundtrip',
        'NonCash Credit - Gift Card'),
       ('NonCash', 'Variable Credit', 'Other', 'NonCash Credit', 'Giftco Roundtrip', 'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Refund - NonCash', 'NonCash Credit', 'Giftco Roundtrip',
        'NonCash Credit - Credit'),
       ('NonCash', 'Giftcard', 'Bounceback Endowment', 'NonCash Credit', 'Already Original', 'NonCash Credit - Gift Card'),
       ('NonCash', 'Giftcard', 'Bounceback Endowment', 'NonCash Credit', 'Gift Card Converted to Store Credit', 'NonCash Credit - Gift Card'),
       ('Cash', 'Fixed Credit', 'Gift Card - Paid', 'Other Cash Credit', 'Giftco Roundtrip',
        'Other Cash Credit - Gift Card'),
       ('Cash', 'Fixed Credit', 'ShoeDazzle Classic Credit', 'Other Cash Credit', 'Giftco Roundtrip',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Variable Credit', 'Gift Card - Paid', 'Other Cash Credit', 'Giftco Roundtrip',
        'Other Cash Credit - Gift Card'),
        ('Cash', 'Giftcard', 'Gift Card - Paid', 'Other Cash Credit', 'Giftco Roundtrip',
        'Other Cash Credit - Gift Card'),
        ('Cash', 'Variable Credit', 'Legacy Credit', 'Other Cash Credit', 'Giftco Roundtrip',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Variable Credit', 'Other Membership Credit', 'Other Cash Credit', 'Giftco Roundtrip',
        'Other Cash Credit - Other Credit'),
       ('Cash', 'Variable Credit', 'ShoeDazzle Classic Credit', 'Other Cash Credit', 'Giftco Roundtrip',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Fixed Credit', 'Refund', 'Refund Credit', 'Giftco Roundtrip', 'Refund Credit - Credit'),
       ('Cash', 'Variable Credit', 'Refund', 'Refund Credit', 'Giftco Roundtrip', 'Refund Credit - Credit'),
       ('Cash', 'Variable Credit', 'Refund - Partial Shipment', 'Refund Credit', 'Giftco Roundtrip',
        'Refund Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Endowment - ThredUp', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('NonCash', 'Variable Credit', 'Manager Discretion', 'NonCash Credit', 'Converted To Variable',
        'NonCash Credit - Credit'),
       ('Cash', 'Fixed Credit', 'Gift Card - Paid', 'Other Cash Credit', 'Converted To Token',
        'Billed Credit - Credit Converted To Token'),
       ('Cash', 'Fixed Credit', 'ShoeDazzle Classic Credit', 'Other Cash Credit', 'Converted To Token',
        'Billed Credit - Credit Converted To Token'),
       ('Cash', 'Fixed Credit', 'Membership Credit', 'Billed Credit', 'Converted To Token And Giftco Roundtrip',
        'Billed Credit - Credit Giftco Roundtrip'),
       ('Cash', 'Fixed Credit', 'ShoeDazzle Classic Credit', 'Other Cash Credit',
        'Converted To Token And Giftco Roundtrip',
        'Other Cash Credit - Legacy Credit'),
       ('Cash', 'Variable Credit', 'Other Membership Credit', 'Other Cash Credit',
        'Converted To Token',
        'Other Cash Credit - Credit Converted To Token'),
       ('Cash', 'Token', 'Token Billing', 'Billed Credit', 'Converted To Credit',
        'Billed Credit - Token Converted to Credit'),
       ('Cash', 'Token', 'Converted Membership Credit', 'Billed Credit', 'Converted To Credit',
        'Billed Credit - Token Converted to Credit'),
       ('Cash', 'Token', 'Refund', 'Refund Credit', 'Converted To Credit', 'Refund Credit - Token Converted to Credit'),
       ('NonCash', 'Token', 'Manager Discretion', 'NonCash Credit', 'Converted To Credit',
        'NonCash Credit - Token Converted to Credit'),
       ('NonCash', 'Token', 'Refund - NonCash', 'NonCash Credit', 'Converted To Credit',
        'NonCash Credit - Token Converted to Credit'),
       ('NonCash', 'Fixed Credit', 'Converted Membership Token - Promotional Credit', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Expired Token to Credit'),
       ('Cash', 'Token', 'Refund - Converted Credit', 'Refund Credit', 'Converted To Credit',
        'Refund Credit - Token Converted to Credit'),
       ('NonCash', 'Variable Credit', 'Endowment - Winback', 'NonCash Credit', 'Already Original',
        'NonCash Credit - Credit'),
       ('Cash', 'Fixed Credit', 'Converted Membership Token', 'Billed Credit', 'Converted To Variable',
        'Billed Credit - Credit Converted To Variable')
    ;
