TRUNCATE TABLE reference.payment_method_mapping;

INSERT INTO reference.payment_method_mapping (
    payment_method,
    raw_creditcard_type,
    creditcard_type,
    is_prepaid_creditcard
    )
VALUES ('Cash', 'Not Applicable', 'Not Applicable', FALSE),
       ('Credit Card', 'Amex', 'American Express', FALSE),
       ('Credit Card', 'Amex', 'American Express', TRUE),
       ('Credit Card', 'Ap_Amex', 'American Express', FALSE),
       ('Credit Card', 'Ap_Amex', 'American Express', TRUE),
       ('Credit Card', 'Ap_Discover', 'Discover', FALSE),
       ('Credit Card', 'Ap_Mastercard', 'Mastercard', TRUE),
       ('Credit Card', 'Ap_Visa', 'Visa', FALSE),
       ('Credit Card', 'Ap_Visa', 'Visa', TRUE),
       ('Credit Card', 'Discover', 'Discover', FALSE),
       ('Credit Card', 'Discover', 'Discover', TRUE),
       ('Credit Card', 'Master Card', 'Mastercard', FALSE),
       ('Credit Card', 'Not Applicable', 'Not Applicable', FALSE),
       ('Credit Card', 'Unknown', 'Unknown', FALSE),
       ('Credit Card', 'Visa', 'Visa', FALSE),
       ('Psp', 'Amex', 'American Express', FALSE),
       ('Psp', 'Master Card', 'Mastercard', FALSE),
       ('Psp', 'Not Applicable', 'Not Applicable', FALSE),
       ('Psp', 'Paypal', 'Paypal', FALSE),
       ('Psp', 'Vpay', 'Vpay', FALSE),
       ('Credit Card', 'Visa', 'Visa', TRUE),
       ('Credit Card', 'Ap_Mastercard', 'Mastercard', FALSE),
       ('Credit Card', 'Master Card', 'Mastercard', TRUE),
       ('None', 'Not Applicable', 'Not Applicable', FALSE),
       ('Psp', 'Braintreepaypal', 'Paypal', FALSE),
       ('Psp', 'Other', 'Other', FALSE),
       ('Psp', 'Unknown', 'Unknown', FALSE),
       ('Psp', 'Visa', 'Visa', FALSE),
       ('Psp', 'Afterpay', 'Afterpay', FALSE),
       ('Psp', 'Visastandarddebit', 'Visastandarddebit', FALSE),
       ('Psp', 'Electron', 'Electron', FALSE),
       ('None', 'Electron', 'Electron', FALSE),
       ('None', 'Amex', 'American Express', FALSE),
       ('None', 'Master Card', 'Mastercard', FALSE),
       ('None', 'Visa', 'Visa', FALSE),
       ('None', 'Other', 'Other', FALSE),
       ('Check', 'Visa', 'Visa', FALSE),
       ('Credit Card', 'Credit', 'Credit', FALSE),
       ('Credit Card', 'Other', 'Other', FALSE),
       ('Credit Card', 'Visa_Electron', 'Visa_Electron', FALSE),
       ('None', 'Discover', 'Discover', FALSE),
       ('None', 'Mccommercialcredit', 'Mccommercialcredit', FALSE),
       ('None', 'Mccommercialdebit', 'Mccommercialdebit', FALSE),
       ('None', 'Mcdebit', 'Mcdebit', FALSE),
       ('None', 'Mcpremiumcredit', 'Mcpremiumcredit', FALSE),
       ('None', 'Mcpremiumdebit', 'Mcpremiumdebit', FALSE),
       ('None', 'Mcstandardcredit', 'Mcstandardcredit', FALSE),
       ('None', 'Mcstandarddebit', 'Mcstandarddebit', FALSE),
       ('None', 'Mcsuperpremiumcredit', 'Mcsuperpremiumcredit', FALSE),
       ('None', 'Mcsuperpremiumdebit', 'Mcsuperpremiumdebit', FALSE),
       ('None', 'Paypal', 'Paypal', FALSE),
       ('None', 'Visacommercialcredit', 'Visacommercialcredit', FALSE),
       ('None', 'Visacommercialdebit', 'Visacommercialdebit', FALSE),
       ('None', 'Visapremiumcredit', 'Visapremiumcredit', FALSE),
       ('None', 'Visapremiumdebit', 'Visapremiumdebit', FALSE),
       ('None', 'Visastandardcredit', 'Visastandardcredit', FALSE),
       ('None', 'Visastandarddebit', 'Visastandarddebit', FALSE),
       ('None', 'Visasuperpremiumdebit', 'Visasuperpremiumdebit', FALSE),
       ('None', 'Vpay', 'Vpay', FALSE),
       ('Psp', 'Discover', 'Discover', FALSE),
       ('Psp', 'Maestro', 'Maestro', FALSE),
       ('Psp', 'Mccommercialcredit', 'Mccommercialcredit', FALSE),
       ('Psp', 'Mccommercialdebit', 'Mccommercialdebit', FALSE),
       ('Psp', 'Mccredit', 'Mccredit', FALSE),
       ('Psp', 'Mcdebit', 'Mcdebit', FALSE),
       ('Psp', 'Mcfleetcredit', 'Mcfleetcredit', FALSE),
       ('Psp', 'Mcpremiumcredit', 'Mcpremiumcredit', FALSE),
       ('Psp', 'Mcpremiumdebit', 'Mcpremiumdebit', FALSE),
       ('Psp', 'Mcstandardcredit', 'Mcstandardcredit', FALSE),
       ('Psp', 'Mcstandarddebit', 'Mcstandarddebit', FALSE),
       ('Psp', 'Mcsuperpremiumcredit', 'Mcsuperpremiumcredit', FALSE),
       ('Psp', 'Mcsuperpremiumdebit', 'Mcsuperpremiumdebit', FALSE),
       ('Psp', 'Sepaadyenapi', 'Sepaadyenapi', FALSE),
       ('Psp', 'Visacommercialcredit', 'Visacommercialcredit', FALSE),
       ('Psp', 'Visacommercialdebit', 'Visacommercialdebit', FALSE),
       ('Psp', 'Visacommercialpremiumdebit', 'Visacommercialpremiumdebit', FALSE),
       ('Psp', 'Visacorporatecredit', 'Visacorporatecredit', FALSE),
       ('Psp', 'Visacorporatedebit', 'Visacorporatedebit', FALSE),
       ('Psp', 'Visapremiumcredit', 'Visapremiumcredit', FALSE),
       ('Psp', 'Visapremiumdebit', 'Visapremiumdebit', FALSE),
       ('Psp', 'Visastandardcredit', 'Visastandardcredit', FALSE),
       ('Psp', 'Visasuperpremiumcredit', 'Visasuperpremiumcredit', FALSE),
       ('Psp', 'Visasuperpremiumdebit', 'Visasuperpremiumdebit', FALSE);
