TRUNCATE TABLE reference.dummy_customer;

INSERT INTO  reference.dummy_customer (
    customer_id,
	meta_original_customer_id,
	first_name,
	last_name,
	email,
	store_id,
    default_address_id,
	default_address1,
	default_address2,
	default_city,
	default_state_province,
	default_postal_code,
	default_country_code,
    detail_country_code,
	specialty_country_code,
    finance_specialty_store,
    birth_day,
	birth_year,
	birth_month,
	quiz_zip,
	top_size,
	bottom_size,
	bra_size,
    onepiece_size,
	denim_size,
	dress_size,
	shoe_size,
	gender,
	first_gender,
    is_friend_referral,
	membership_level,
	how_did_you_hear,
	registration_local_datetime,
	secondary_registration_local_datetime,
	primary_registration_store_id,
	secondary_registration_store_id,
	is_secondary_registration_after_vip,
	is_blacklisted,
	blacklist_reason,
	is_free_trial,
    is_free_trial_promo,
    is_free_trial_gift_order,
	is_cross_promo,
	is_metanav,
	is_scrubs_customer,
	is_test_customer,
    is_opt_out,
	bralette_size,
	undie_size,
    lingerie_sleep_size,
    emp_optin_datetime,
    first_mobile_app_session_local_datetime,
    first_mobile_app_session_id,
    first_mobile_app_order_local_datetime,
    first_mobile_app_order_id,
    mobile_app_cohort_month_date,
    mobile_app_cohort_os,
	onetrust_consent_strictlynecessary,
    onetrust_consent_performance,
    onetrust_consent_functional,
    onetrust_consent_targeting,
    onetrust_consent_social,
    onetrust_update_datetime,
    registration_type,
    is_deleted,
    current_membership_type,
    membership_price,
    membership_plan_id,
    email_opt_in_datetime,
    sms_opt_in_datetime,
    membership_state,
    customer_bucket_group
    )
SELECT
    -1 * store_id AS customer_id,
	-1 * store_id AS meta_original_customer_id,
	'Chargeback' AS first_name,
	 store_name AS last_name,
	'Unknown' AS email,
	 store_id,
    -1 AS default_address_id,
	'Unknown' AS default_address1,
	'Unknown' AS default_address2,
	'Unknown' AS default_city,
	'Unknown' AS default_state_province,
	'Unknown' AS default_postal_code,
	'Unknown' AS default_country_code,
    'Unknown' AS detail_country_code,
	'Unknown' AS specialty_country_code,
    'Unknown' AS finance_specialty_store,
    -1 AS birth_day,
	-1 AS birth_year,
	-1 AS birth_month,
	'Unknown' AS quiz_zip,
	'Unknown' AS top_size,
	'Unknown' AS bottom_size,
	'Unknown' AS bra_size,
    'Unknown' AS onepiece_size,
	'Unknown' AS denim_size,
	'Unknown' AS dress_size,
	'Unknown' AS shoe_size,
	'Unknown' AS gender,
	'Unknown' AS first_gender,
    NULL AS is_friend_referral,
	'Unknown' AS membership_level,
	'Unknown' AS how_did_you_hear,
	'1900-01-01 00:00:00.000' AS registration_local_datetime,
	'1900-01-01 00:00:00.000' AS secondary_registration_local_datetime,
	-1 AS primary_registration_store_id,
	-1 AS secondary_registration_store_id,
	NULL AS is_secondary_registration_after_vip,
	NULL AS is_blacklisted,
	NULL AS blacklist_reason,
	NULL AS is_free_trial,
    NULL AS is_free_trial_promo,
    NULL AS is_free_trial_gift_order,
	NULL AS is_cross_promo,
	NULL AS is_metanav,
	NULL AS is_scrubs_customer,
	NULL AS is_test_customer,
    NULL AS is_opt_out,
	'Unknown' AS bralette_size,
	'Unknown' AS undie_size,
    'Unknown' AS lingerie_sleep_size,
    NULL AS emp_optin_datetime,
    NULL AS first_mobile_app_session_local_datetime,
    NULL AS first_mobile_app_session_id,
    NULL AS first_mobile_app_order_local_datetime,
    NULL AS first_mobile_app_order_id,
    NULL AS mobile_app_cohort_month_date,
    NULL AS mobile_app_cohort_os,
	NULL AS onetrust_consent_strictlynecessary,
    NULL AS onetrust_consent_performance,
    NULL AS onetrust_consent_functional,
    NULL AS onetrust_consent_targeting,
    NULL AS onetrust_consent_social,
    NULL AS onetrust_update_datetime,
    NULL AS registration_type,
    FALSE AS is_deleted,
    NULL AS current_membership_type,
    NULL AS membership_price,
    NULL AS membership_plan_id,
    NULL AS email_opt_in_datetime,
    NULL AS sms_opt_in_datetime,
    NULL AS membership_state,
    NULL AS customer_bucket_group
FROM stg.dim_Store
WHERE store_sub_type = 'Chargeback'
    OR
    (
        is_core_store
        AND store_type = 'Online'
        AND store_country IS NOT NULL -- excluding dummy FL stores
        AND store_id NOT IN (116, 44, 315) -- excluding JF PS and JF Wholesale
    );
