CREATE OR REPLACE FUNCTION REPORTING_PROD.BLUE_YONDER.UDF_CLEANUP_FIELD("column_name" VARCHAR(50))
RETURNS VARCHAR(50)
LANGUAGE SQL
AS '
  SELECT REGEXP_REPLACE(TRIM(column_name), ''[\\?~\\%/<>&"”\\n\\r\\|\ \''']'', ''_'') ';
