CREATE TABLE IF NOT EXISTS WORK.DBO.AUDIT_LAKE_DATA (
	ID_VALUE VARCHAR,
	IS_EDW_SOURCE BOOLEAN,
	TABLE_NAME VARCHAR,
	DATETIME_ADDED TIMESTAMP_NTZ(9),
	DATETIME_MODIFIED TIMESTAMP_NTZ(9),
    ROW_ADDED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
