CREATE TABLE IF NOT EXISTS WORK.DBO.AUDIT_SOURCE_DATA_ARCHIVE (
	ID_VALUE VARCHAR(16777216),
	IS_EDW_SOURCE BOOLEAN,
	TABLE_NAME VARCHAR(16777216),
	DATETIME_ADDED TIMESTAMP_NTZ(9),
	DATETIME_MODIFIED TIMESTAMP_NTZ(9),
	ROW_ADDED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	SNAPSHOT_DATETIME TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);
