create or replace temporary table _pp_data AS
    SELECT
        ad_id,
        date,
        CASE
            WHEN PLATFORM_POSITION ILIKE '%reels%' THEN 'reels'
            WHEN PLATFORM_POSITION ILIKE '%stories%' THEN 'stories'
            WHEN PLATFORM_POSITION ILIKE '%feed%' THEN 'feed'
            ELSE 'other'
        END placement,
        SUM(spend_usd) AS spend_usd_pp,
        SUM(spend_with_vendor_fees_usd) AS spend_with_vendor_fees_usd_pp,
        SUM(spend_account_currency) AS spend_account_currency_pp,
        SUM(spend_with_vendor_fees_account_currency) AS spend_with_vendor_fees_account_currency_pp,
        SUM(impressions)AS impressions_pp,
        SUM(clicks) AS clicks_pp,
        SUM(pixel_lead_view_1d) AS pixel_lead_view_1d_pp,
        SUM(pixel_lead_view_7d) AS pixel_lead_view_7d_pp,
        SUM(pixel_lead_click_1d) AS pixel_lead_click_1d_pp,
        SUM(pixel_lead_click_7d) AS pixel_lead_click_7d_pp,
        SUM(pixel_vip_view_1d) AS pixel_vip_view_1d_pp,
        SUM(pixel_vip_view_7d) AS pixel_vip_view_7d_pp,
        SUM(pixel_vip_click_1d) AS pixel_vip_click_1d_pp,
        SUM(pixel_vip_click_7d) AS pixel_vip_click_7d_pp
    FROM reporting_media_prod.facebook.facebook_optimization_dataset_platform
    WHERE ad_id IS NOT NULL
    GROUP BY ad_id, date, placement;

create or replace temporary table _platform_placement as
SELECT
    ad_id,
    date,
    placement,

   SUM(spend_usd_pp) OVER (PARTITION BY ad_id, date) AS total_spend_usd,
    ifnull(DIV0(spend_usd_pp , total_spend_usd),0) AS pct_spend_usd,

    SUM(spend_with_vendor_fees_usd_pp) OVER (PARTITION BY ad_id, date) AS total_spend_with_vendor_fees_usd,
    ifnull(DIV0(spend_with_vendor_fees_usd_pp , total_spend_with_vendor_fees_usd),0) AS pct_spend_with_vendor_fees_usd,

    SUM(spend_account_currency_pp) OVER (PARTITION BY ad_id, date) AS total_spend_account_currency,
    ifnull(DIV0(spend_account_currency_pp , total_spend_account_currency),0) AS pct_spend_account_currency,

    SUM(spend_with_vendor_fees_account_currency_pp) OVER (PARTITION BY ad_id, date) AS total_spend_with_vendor_fees_account_currency,
    ifnull(DIV0(spend_with_vendor_fees_account_currency_pp , total_spend_with_vendor_fees_account_currency),0) AS pct_spend_with_vendor_fees_account_currency,

    SUM(impressions_pp) OVER (PARTITION BY ad_id, date) AS total_impressions,
    ifnull(DIV0(impressions_pp, total_impressions),0) AS pct_impressions,

    SUM(clicks_pp) OVER (PARTITION BY ad_id, date) AS total_clicks,
    ifnull(DIV0(clicks_pp , total_clicks),0) AS pct_clicks,

    SUM(pixel_lead_view_1d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_lead_view_1d,
    ifnull(DIV0(pixel_lead_view_1d_pp , total_pixel_lead_view_1d),0) AS pct_pixel_lead_view_1d,

    SUM(pixel_lead_view_7d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_lead_view_7d,
    ifnull(DIV0(pixel_lead_view_7d_pp , total_pixel_lead_view_7d),0) AS pct_pixel_lead_view_7d,

    SUM(pixel_lead_click_1d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_lead_click_1d,
    ifnull(DIV0(pixel_lead_click_1d_pp , total_pixel_lead_click_1d),0) AS pct_pixel_lead_click_1d,

    SUM(pixel_lead_click_7d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_lead_click_7d,
    ifnull(DIV0(pixel_lead_click_7d_pp , total_pixel_lead_click_7d),0) AS pct_pixel_lead_click_7d,

    SUM(pixel_vip_view_1d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_vip_view_1d,
    ifnull(DIV0(pixel_vip_view_1d_pp , total_pixel_vip_view_1d),0) AS pct_pixel_vip_view_1d,

    SUM(pixel_vip_view_7d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_vip_view_7d,
    ifnull(DIV0(pixel_vip_view_7d_pp , total_pixel_vip_view_7d),0) AS pct_pixel_vip_view_7d,

    SUM(pixel_vip_click_1d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_vip_click_1d,
    ifnull(DIV0(pixel_vip_click_1d_pp , total_pixel_vip_click_1d),0) AS pct_pixel_vip_click_1d,

    SUM(pixel_vip_click_7d_pp) OVER (PARTITION BY ad_id, date) AS total_pixel_vip_click_7d,
    ifnull(DIV0(pixel_vip_click_7d_pp , total_pixel_vip_click_7d),0) AS pct_pixel_vip_click_7d

FROM _pp_data;

create or replace temporary table _creative_dims as
select
    store_id,
    op.store_brand_name,
    store_brand_abbr,
    country,
    op.region,
    channel,
    subchannel,
    vendor,
    member_segment,
    bidding_objective,
    account_id,
    account_name,
    campaign_id,
    campaign_name,
    adgroup_name,
    adgroup_id,
    ad_name,
    ad_id,
    ad_is_active_flag,
    adgroup_is_active_flag,
    link_to_post,
    image_url,
    date,
    op.creative_code,
    iff(cd.sku1 = 'None', 'Unclassified',ifnull(cd.sku1,'Unclassified')) as sku1,
    iff(cd.sku2 = 'None', 'Unclassified',ifnull(cd.sku2,'Unclassified')) as sku2,
    iff(cd.sku3 = 'None', 'Unclassified',ifnull(cd.sku3,'Unclassified')) as sku3,
    iff(cd.sku4 = 'None', 'Unclassified',ifnull(cd.sku4,'Unclassified')) as sku4,
    iff(cd.sku5 = 'None', 'Unclassified',ifnull(cd.sku5,'Unclassified')) as sku5,
    op.offer,
    influencer_name,
    cd.designer_initials,
    cd.date_created,
    cd.jf_brand,
    cd.version,
    cd.ad_type,
    cd.video_length,
    cd.audio,
    cd.first_3_seconds_text,
    cd.first_3_seconds_visual,
    cd.model_action,
    cd.model_placement,
    cd.body_type,
    cd.gender,
    cd.image_focus,
    cd.still_life_angle_shot,
    cd.influencer,
    cd.ugc_talent_name,
    cd.egc_talent_name,
    cd.trello_id,
    cd.asset_type,
    cd.asset_size,
    cd.creative_concept,
    cd.test_name,
    cd.platform,
    cd.promo_type,
    cd.number_of_styles_shown,
    cd.logo,
    cd.offer_format,
    cd.offer_placement,
    cd.messaging_theme,
    cd.font_used,
    cd.partner,
    shot_type,
    template,
    background,
    spend_usd,
    spend_with_vendor_fees_usd,
    spend_account_currency,
    spend_with_vendor_fees_account_currency,
    impressions,
    clicks,
    video_views,
    ui_optimization_window,
    pixel_lead_view_1d,
    pixel_lead_view_7d,
    pixel_lead_click_1d,
    pixel_lead_click_7d,
    ui_optimization_pixel_lead,
    pixel_vip_view_1d,
    pixel_vip_view_7d,
    pixel_vip_click_1d,
    pixel_vip_click_7d,
    ui_optimization_pixel_vip
from reporting_media_prod.dbo.all_channel_optimization op
left join reporting_media_base_prod.dbo.creative_dimensions cd on op.creative_code = cd.creative_code
where op.creative_code is not null
and ad_id is not null;

create or replace temporary table _placement_final as
select
    store_id,
    store_brand_name,
    store_brand_abbr,
    country,
    region,
    channel,
    subchannel,
    vendor,
    member_segment,
    bidding_objective,
    account_id,
    account_name,
    campaign_id,
    campaign_name,
    adgroup_name,
    adgroup_id,
    ad_name,
    cd.ad_id,
    ad_is_active_flag,
    adgroup_is_active_flag,
    link_to_post,
    image_url,
    cd.date,
    creative_code,
    iff(cd.sku1 = 'None', 'Unclassified',ifnull(cd.sku1,'Unclassified')) as sku1,
    iff(cd.sku2 = 'None', 'Unclassified',ifnull(cd.sku2,'Unclassified')) as sku2,
    iff(cd.sku3 = 'None', 'Unclassified',ifnull(cd.sku3,'Unclassified')) as sku3,
    iff(cd.sku4 = 'None', 'Unclassified',ifnull(cd.sku4,'Unclassified')) as sku4,
    iff(cd.sku5 = 'None', 'Unclassified',ifnull(cd.sku5,'Unclassified')) as sku5,
    offer,
    influencer_name,
    designer_initials,
    date_created,
    jf_brand,
    version,
    ad_type,
    video_length,
    audio,
    first_3_seconds_text,
    first_3_seconds_visual,
    model_action,
    model_placement,
    body_type,
    gender,
    image_focus,
    still_life_angle_shot,
    influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
    creative_concept,
    test_name,
    platform,
    ifnull(p.placement,channel) as placement_x,
    iff(placement_x = 'fb+ig','other',placement_x) as placement,
    promo_type,
    number_of_styles_shown,
    logo,
    offer_format,
    offer_placement,
    messaging_theme,
    font_used,
    partner,
    shot_type,
    template,
    background,
    spend_usd * ifnull(p.pct_spend_usd,1) as spend_usd,
    spend_with_vendor_fees_usd * ifnull(p.pct_spend_with_vendor_fees_usd,1) as spend_with_vendor_fees_usd,
    spend_account_currency * ifnull(p.pct_spend_account_currency, 1) as spend_acct_currency,
    spend_with_vendor_fees_account_currency * ifnull(p.pct_spend_with_vendor_fees_account_currency,1) as spend_with_vendor_fees_account_currency,
    impressions * ifnull(p.pct_impressions,1) as impressions,
    clicks * ifnull(p.pct_clicks,1) as clicks,
    video_views,
    ui_optimization_window,
    pixel_lead_view_1d * ifnull(p.pct_pixel_lead_view_1d,1) as pixel_lead_view_1d,
    pixel_lead_view_7d * ifnull(p.pct_pixel_lead_view_7d,1) as pixel_lead_view_7d,
    pixel_lead_click_1d * ifnull(p.pct_pixel_lead_click_1d,1) as pixel_lead_click_1d,
    pixel_lead_click_7d * ifnull(p.pct_pixel_lead_click_7d,1) as pixel_lead_click_7d,
    ui_optimization_pixel_lead,
    pixel_vip_view_1d * ifnull(p.pct_pixel_vip_view_1d,1) as pixel_vip_view_1d,
    pixel_vip_view_7d * ifnull(p.pct_pixel_vip_view_7d,1) as pixel_vip_view_7d,
    pixel_vip_click_1d * ifnull(p.pct_pixel_vip_click_1d,1) as pixel_vip_click_1d,
    pixel_vip_click_7d * ifnull(p.pct_pixel_vip_click_7d,1) as pixel_vip_click_7d,
    ui_optimization_pixel_vip

from _creative_dims cd
left join _platform_placement p on cd.ad_id = p.ad_id and cd.date = p.date;

create or replace temporary table _sku_pivot as
select *
from _placement_final
unpivot (creative_product_sku for sku_number in (sku1, sku2, sku3, sku4, sku5));

create or replace temporary table _product_data_raw as
select distinct
                p.store_brand_abbr,
                ds.store_country,
                dp.product_sku,
                current_showroom_date,
                replace(dp.product_name,'* ','') as product_name,
                product_category,
                merch_category,
                merch_subcategory,
                case when p.store_brand_abbr in ('FL','YTY') then merch_class
                    when p.store_brand_abbr in ('SX') then merch_subcategory
                else merch_subcategory end as product_class,
                case when p.store_brand_abbr in ('FL','YTY') then merch_subclass
                    when p.store_brand_abbr in ('SX') then merch_sub_department
                else merch_subclass end as product_subclass,
                dp.department,
                dp.category,
                dp.color,
                p.merch_color_family,
                p.site_color,
                cm.parent_color,
                dp.image_url as product_image_url,
                dp.is_active,
                dp.meta_update_datetime
from edw_prod.data_model.dim_product dp
join edw_prod.data_model.dim_store ds on ds.store_id = dp.store_id and lower(ds.store_brand_abbr) in ('fl','yty','sx','sd','jf','fk')
join reporting_media_base_prod.dbo.product_sku_color_mapping cm on dp.product_sku = cm.product_sku and dp.store_id = cm.store_id
left join reporting_base_prod.data_science.product_recommendation_tags_pivoted p on mpid = edw_prod.stg.udf_unconcat_brand(iff(master_product_id=-1, product_id, master_product_id))
where dp.is_active = true
qualify row_number() over (partition by dp.product_sku, ds.store_country order by dp.meta_update_datetime desc) = 1;


create or replace transient table reporting_media_prod.dbo.all_channel_creative_performance_by_sku as
select
    store_id,
    s.store_brand_name,
    s.store_brand_abbr,
    country,
    region,
    channel,
    subchannel,
    vendor,
    member_segment,
    bidding_objective,
    account_id,
    account_name,
    campaign_id,
    campaign_name,
    adgroup_name,
    adgroup_id,
    ad_name,
    s.ad_id,
    ad_is_active_flag,
    adgroup_is_active_flag,
    link_to_post,
    image_url,
    date,
    creative_code,
    sku_number,
    creative_product_sku,
    product_image_url,
    ifnull(product_sku,'Unclassified') as product_sku,
    current_showroom_date,
    ifnull(product_name,'Unclassified') as product_name,
    ifnull(product_category,'Unclassified') as product_category,
    ifnull(department,'Unclassified') as department,
    ifnull(category,'Unclassified') as category,
    ifnull(color,'Unclassified') as color,
    ifnull(merch_color_family,'Unclassified') as merch_color_family,
    ifnull(site_color,'Unclassified') as site_color,
    ifnull(parent_color,'Unclassified') as parent_color,
    ifnull(merch_category,'Unclassified') as merch_category,
    ifnull(merch_subcategory,'Unclassified') as merch_subcategory,
    ifnull(product_class,'Unclassified') as product_class,
    ifnull(product_subclass,'Unclassified') as product_subclass,
    offer,
    influencer_name,
    designer_initials,
    date_created,
    jf_brand,
    version,
    ad_type,
    video_length,
    audio,
    first_3_seconds_text,
    first_3_seconds_visual,
    model_action,
    model_placement,
    body_type,
    gender,
    image_focus,
    still_life_angle_shot,
    influencer,
    ugc_talent_name,
    egc_talent_name,
    trello_id,
    asset_type,
    asset_size,
    creative_concept,
    test_name,
    platform,
    placement,
    promo_type,
    number_of_styles_shown,
    logo,
    offer_format,
    offer_placement,
    messaging_theme,
    font_used,
    partner,
    shot_type,
    template,
    background,
    spend_usd  / count(*) over (partition by s.ad_id, placement, date) as spend_usd,
    spend_with_vendor_fees_usd / count(*) over (partition by s.ad_id, placement, date) as spend_with_vendor_fees_usd,
    spend_acct_currency / count(*) over (partition by s.ad_id, placement, date) as spend_account_currency,
    spend_with_vendor_fees_account_currency / count(*) over (partition by s.ad_id, placement, date) as spend_with_vendor_fees_account_currency,
    impressions / count(*) over (partition by s.ad_id, placement, date) as impressions,
    clicks / count(*) over (partition by s.ad_id, placement, date) as clicks,
    video_views / count(*) over (partition by s.ad_id, placement, date) as video_views,
    ui_optimization_window,
    pixel_lead_view_1d / count(*) over (partition by s.ad_id, placement, date) as pixel_lead_view_1d,
    pixel_lead_view_7d / count(*) over (partition by s.ad_id, placement, date) as pixel_lead_view_7d,
    pixel_lead_click_1d / count(*) over (partition by s.ad_id, placement, date) as pixel_lead_click_1d,
    pixel_lead_click_7d / count(*) over (partition by s.ad_id, placement, date) as pixel_lead_click_7d,
    ui_optimization_pixel_lead / count(*) over (partition by s.ad_id, placement, date) as ui_optimization_pixel_lead,
    pixel_vip_view_1d / count(*) over (partition by s.ad_id, placement, date) as pixel_vip_view_1d,
    pixel_vip_view_7d / count(*) over (partition by s.ad_id, placement, date) as pixel_vip_view_7d,
    pixel_vip_click_1d / count(*) over (partition by s.ad_id, placement, date) as pixel_vip_click_1d,
    pixel_vip_click_7d / count(*) over (partition by s.ad_id, placement, date) as pixel_vip_click_7d,
    ui_optimization_pixel_vip / count(*) over (partition by s.ad_id, placement, date) as ui_optimization_pixel_vip,
    current_timestamp() as latest_refresh_datetime
from _sku_pivot s
left join _product_data_raw p on s.creative_product_sku = p.product_sku and s.country = p.store_country
where product_sku is not null or lower(sku_number) = 'sku1';




