
CREATE OR REPLACE TEMP table _fmc AS
SELECT DISTINCT
    (CASE WHEN IS_MENS_FLAG = 1
        THEN 'Fabletics Men' ELSE STORE_BRAND END
        ) || ' ' || STORE_REGION
        AS store_region,
    CAST(MEDIA_COST_DATE AS DATE) AS date,
    SUM(COST) AS spend
FROM REPORTING_MEDIA_PROD.DBO.VW_FACT_MEDIA_COST AS fmc
JOIN EDW_PROD.DATA_MODEL.DIM_STORE AS ds
    ON ds.STORE_ID = fmc.STORE_ID
WHERE STORE_REGION = 'NA'
    AND MEDIA_COST_DATE >= '2019-01-01'
    AND MEDIA_COST_DATE < CAST(CURRENT_TIMESTAMP() AS DATE)
GROUP BY 1,2;

CREATE OR REPLACE TEMP TABLE _date AS
SELECT
    CALENDAR_YEAR,
    MONTH_DATE,
    FULL_DATE,
    DAY_NAME_OF_WEEK,
    WEEK_OF_YEAR,
    MONTH(MONTH_DATE) AS MONTH_OF_YEAR,
    DATEDIFF(MONTH, MONTH_DATE, CURRENT_TIMESTAMP()) AS months_ago
FROM EDW_PROD.DATA_MODEL.DIM_DATE
WHERE FULL_DATE >= '2019-01-01'
    AND FULL_DATE < CAST(CURRENT_TIMESTAMP() AS DATE)
ORDER BY 1,4;

CREATE OR REPLACE TEMP TABLE _weekly_spend AS
SELECT
    d.*,
    store_region,
    spend,
    SUM(spend) OVER(PARTITION BY store_region, CALENDAR_YEAR, WEEK_OF_YEAR) AS total_spend_week,
    SPEND / SUM(IFF(spend = 0, NULL, spend)) OVER(PARTITION BY store_region, CALENDAR_YEAR, WEEK_OF_YEAR)
        AS pct_total_spend_week
FROM _date AS d
LEFT JOIN _fmc AS f
    ON f.date = d.FULL_DATE
ORDER BY FULL_DATE ASC;

CREATE OR REPLACE TRANSIENT TABLE REPORTING_MEDIA_PROD.DBO.MEDIA_FORECASTING_REPORT_WEEKLY_SPEND AS
SELECT *
FROM _weekly_spend;
