from include.airflow.operators.mssql_acquisition import HighWatermarkMaxRowVersion
from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='um_replicated',
    schema='dbo',
    table='ultramerchant__order__all',
    watermark_column='repl_timestamp',
    initial_load_value='0x0',
    high_watermark_cls=HighWatermarkMaxRowVersion,
    schema_version_prefix='v2',
    column_list=[
        Column('order_id', 'INT'),
        Column('store_id', 'INT'),
        Column('customer_id', 'INT'),
        Column('order_source_id', 'INT'),
        Column('order_tracking_id', 'INT'),
        Column('shipping_address_id', 'INT'),
        Column('billing_address_id', 'INT'),
        Column('payment_method', 'VARCHAR(25)'),
        Column('auth_payment_transaction_id', 'INT'),
        Column('capture_payment_transaction_id', 'INT'),
        Column('master_order_id', 'INT'),
        Column('session_id', 'INT'),
        Column('payment_option_id', 'INT'),
        Column('reserved_id', 'INT'),
        Column('code', 'VARCHAR(36)'),
        Column('subtotal', 'NUMBER(19, 4)'),
        Column('shipping', 'NUMBER(19, 4)'),
        Column('tax', 'NUMBER(19, 4)'),
        Column('discount', 'NUMBER(19, 4)'),
        Column('credit', 'NUMBER(19, 4)'),
        Column('estimated_weight', 'DOUBLE'),
        Column('ip', 'VARCHAR(15)'),
        Column('date_added', 'TIMESTAMP_NTZ(0)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('date_placed', 'TIMESTAMP_NTZ(0)'),
        Column('datetime_processing_modified', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_payment_modified', 'TIMESTAMP_NTZ(3)'),
        Column('date_shipped', 'TIMESTAMP_NTZ(0)'),
        Column('processing_statuscode', 'INT'),
        Column('payment_statuscode', 'INT'),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('store_domain_id', 'INT'),
        Column('membership_level_id', 'INT'),
        Column('datetime_transaction', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_local_transaction', 'TIMESTAMP_NTZ(3)'),
        Column('currency_code', 'VARCHAR(3)'),
        Column('store_group_id', 'INT'),
        Column('repl_action', 'VARCHAR(1)'),
        Column('repl_timestamp', 'BINARY(8)', uniqueness=True),
    ],
)
