CREATE OR
REPLACE  TRANSIENT TABLE
GSC.YARD_CONTAINER_DATA (
	YARD_CONTAINER_ID NUMBER(38,0),
	TRAILER_ID VARCHAR(255),
	WAREHOUSE_ID NUMBER(38,0),
	FROM_WAREHOUSE_LABEL VARCHAR(255),
	TO_WAREHOUSE_LABEL VARCHAR(255),
	LOAD_DATE TIMESTAMP_NTZ(3),
	DEPARTURE_DATE TIMESTAMP_NTZ(3),
	ARRIVAL_DATE TIMESTAMP_NTZ(3),
	CARRIER_DEPARTURE_DATE TIMESTAMP_NTZ(3),
	CARRIER_ARRIVAL_DATE TIMESTAMP_NTZ(3),
	PO_NUMBER VARCHAR(255),
	ITEM_ID NUMBER(38,0),
	QUANTITY NUMBER(38,0),
	ORDER_NUMBER VARCHAR(255),
	ITEM_NUMBER VARCHAR(255),
	TOTAL_UNIT_VOLUME FLOAT,
	CARRIER VARCHAR(255),
	META_CREATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9)),
	META_UPDATE_DATETIME TIMESTAMP_NTZ(9) DEFAULT CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ(9))
);
