CREATE TRANSIENT TABLE IF NOT EXISTS history.bot_user_agent
(
    USER_AGENT VARCHAR,
    MONTH_ADDED DATE,
    SESSIONS NUMBER,
    LEAD_REGISTRATIONS NUMBER,
    SUCCESSFUL_ORDERS NUMBER,
    SESSION_TO_LEAD_PCT DECIMAL(18, 6),
    SESSION_TO_ORDER_PCT DECIMAL(18, 6),
    META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
);
