CREATE TABLE if not exists shared.bot_user_agent_detail (
	USER_AGENT VARCHAR(512),
	SESSION_DATE_HQ DATE,
	STORE_ID NUMBER(38,0),
	BOT_DEFINITION VARCHAR(16777216),
	BOT_TYPE VARCHAR(16777216),
	IS_KNOWN_BOT BOOLEAN,
	SESSIONS NUMBER(18,0),
	NO_CID_SESSIONS NUMBER(13,0),
	CID_SESSIONS NUMBER(13,0),
	TEST_SESSIONS NUMBER(13,0),
	ROLLING_SESSIONS NUMBER(30,0),
	ROLLING_NO_CID NUMBER(25,0),
	ROLLING_CID_SESSIONS NUMBER(25,0),
	ROLLING_TEST_SESSIONS NUMBER(25,0),
	UA_SESSIONS_PCT NUMBER(38,6),
	UA_SESSIONS_PCT_SID NUMBER(38,6)
);
