
CREATE TABLE if not exists reporting_base.shared.mobile_app_session_os_updated (
    SESSION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
	CUSTOMER_ID NUMBER(38,0),
    BROWSER VARCHAR,
    OS VARCHAR,
    SESSION_LOCAL_DATETIME TIMESTAMP_TZ(9),
    META_ORIGINAL_SESSION_ID NUMBER(38,0),
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
) CLUSTER BY (TRUNC(session_id, -7));
