CREATE TRANSIENT TABLE if not exists staging.site_visit_metrics (
    SESSION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
	IS_QUIZ_START_ACTION BOOLEAN,
	IS_QUIZ_COMPLETE_ACTION  BOOLEAN,
	IS_LEAD_REGISTRATION_ACTION  BOOLEAN,
	IS_SPEEDY_REGISTRATION_ACTION  BOOLEAN,
    IS_SKIP_QUIZ_REGISTRATION_ACTION BOOLEAN,
    IS_QUIZ_REGISTRATION_ACTION  BOOLEAN,
    META_ORIGINAL_SESSION_ID NUMBER(38,0),
    META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
);
