CREATE TRANSIENT TABLE if not exists staging.session_ga (
	SESSION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
	GA_UTM_MEDIUM VARCHAR,
    GA_UTM_SOURCE VARCHAR,
    GA_UTM_CAMPAIGN VARCHAR,
    GA_UTM_TERM VARCHAR,
    GA_UTM_CONTENT VARCHAR,
    GA_DEVICE VARCHAR,
    GA_BROWSER VARCHAR,
    GA_REFERRAL_PATH VARCHAR,
    GA_IS_LEAD BOOLEAN,
    GA_IS_VIP BOOLEAN,
    GA_CUSTOMER_ID NUMBER(38,0),
    META_ORIGINAL_SESSION_ID NUMBER(38,0),
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
);
