CREATE TRANSIENT TABLE if not exists staging.session_add_to_cart (
    SESSION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    ADD_TO_CART_COUNT NUMBER(38,0),
    ECHO_ADD_TO_CART_COUNT NUMBER(38,0),
    META_ORIGINAL_SESSION_ID NUMBER(38,0),
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
);
