
CREATE TRANSIENT TABLE if not exists staging.membership_state (
    session_id NUMBER(38,0) NOT NULL PRIMARY KEY,
	membership_state VARCHAR,
	daily_lead_tenure NUMBER(38,0),
	monthly_vip_tenure NUMBER(38,0),
	META_ORIGINAL_SESSION_ID NUMBER(38,0),
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
);
