CREATE TRANSIENT TABLE if not exists staging.migrated_session (
    SESSION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    MIGRATION_PREVIOUS_SESSION_ID NUMBER(38,0),
    META_ORIGINAL_SESSION_ID NUMBER(38,0),
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
);
