CREATE TRANSIENT TABLE if not exists staging.visitor_session (
    SESSION_ID NUMBER(38,0) NOT NULL PRIMARY KEY,
    VISITOR_ID NUMBER(38,0),
    PREVIOUS_VISITOR_SESSION_ID NUMBER(38,0),
    PREVIOUS_VISITOR_SESSION_DATETIME TIMESTAMP_NTZ(9),
    NEXT_VISITOR_SESSION_ID NUMBER(38,0),
    NEXT_VISITOR_SESSION_DATETIME TIMESTAMP_NTZ(9),
    META_ORIGINAL_SESSION_ID NUMBER(38,0),
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP,
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP
);
