from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='merlin',
    schema='dbo',
    table='StyleColor',
    watermark_column='DateUpdate',
    schema_version_prefix='v2',
    column_list=[
        Column('oid', 'INT', uniqueness=True, source_name='OID'),
        Column('style', 'INT', source_name='Style'),
        Column('color', 'INT', source_name='Color'),
        Column('material_content', 'VARCHAR(500)', source_name='MaterialContent'),
        Column('color_serialized_sku', 'INT', source_name='ColorSerializedSku'),
        Column('city', 'INT', source_name='City'),
        Column('optimistic_lock_field', 'INT', source_name='OptimisticLockField'),
        Column('gc_record', 'INT', source_name='GCRecord'),
        Column('wash_code', 'INT', source_name='WashCode'),
        Column('type_of_upper', 'INT', source_name='TypeOfUpper'),
        Column('flocked', 'INT', source_name='Flocked'),
        Column('upper_height', 'INT', source_name='UpperHeight'),
        Column('foxing_band', 'INT', source_name='FoxingBand'),
        Column('closures', 'INT', source_name='Closures'),
        Column('molded_construction', 'INT', source_name='MoldedConstruction'),
        Column('pvc', 'INT', source_name='PVC'),
        Column('upper_90_percent', 'INT', source_name='Upper90Percent'),
        Column('waterproof', 'INT', source_name='Waterproof'),
        Column('lined_fur', 'INT', source_name='LinedFur'),
        Column('thick_padding', 'INT', source_name='ThickPadding'),
        Column('protective_in_nature', 'INT', source_name='ProtectiveInNature'),
        Column('footwear_construction_type', 'VARCHAR', source_name='FootwearConstructionType'),
        Column('footwear_construction_type2', 'VARCHAR', source_name='FootwearConstructionType2'),
        Column('upper_50_leather', 'INT', source_name='Upper50Leather'),
        Column('constructed_jute', 'INT', source_name='ConstructedJute'),
        Column('type_of_sole', 'INT', source_name='TypeOfSole'),
        Column('sample_passed_date', 'TIMESTAMP_NTZ(3)', source_name='SamplePassedDate'),
        Column('color_sample_passed_date', 'TIMESTAMP_NTZ(3)', source_name='ColorSamplePassedDate'),
        Column('fabric_code', 'INT', source_name='FabricCode'),
        Column('sku', 'VARCHAR(50)', source_name='Sku'),
        Column('rank', 'INT', source_name='Rank'),
        Column('eu_rank', 'INT', source_name='EURank'),
        Column('sports_footwear', 'INT', source_name='SportsFootwear'),
        Column('protective_toe_cap', 'INT', source_name='ProtectiveToeCap'),
        Column('other_material', 'VARCHAR(100)', source_name='OtherMaterial'),
        Column('external_surfaces', 'INT', source_name='ExternalSurfaces'),
        Column('non_molded_construction', 'INT', source_name='NonMoldedConstruction'),
        Column('footwear_construction_type3', 'VARCHAR', source_name='FootwearConstructionType3'),
        Column('footwear_weight', 'INT', source_name='FootwearWeight'),
        Column('footwear_overlap', 'INT', source_name='FootwearOverlap'),
        Column('uppers_and_soles', 'INT', source_name='UppersandSoles'),
        Column('footwear_material', 'INT', source_name='FootwearMaterial'),
        Column('upper', 'VARCHAR(100)', source_name='Upper'),
        Column('footwear_construction_type4', 'INT', source_name='FootwearConstructionType4'),
        Column('date_create', 'TIMESTAMP_NTZ(3)', delta_column=1, source_name='DateCreate'),
        Column('date_update', 'TIMESTAMP_NTZ(3)', delta_column=0, source_name='DateUpdate'),
    ],
)
