
CREATE OR REPLACE VIEW LAKE_CONSOLIDATED.REFERENCE.HVR_LAKE_STATUS AS
SELECT
    DATABASE,
    SCHEMA,
    TABLE_GROUP,
    CASE
        WHEN
            TABLE_GROUP = 'HIGH FREQ'
            AND DATEADD(MINUTE, -45, CURRENT_TIMESTAMP()) <= CAST(COALESCE(UPDATED_TO, '1900-01-01') AS TIMESTAMP_LTZ)
        THEN 'YES'
        WHEN
            DATEADD(MINUTE, -120, CURRENT_TIMESTAMP()) <= CAST(COALESCE(UPDATED_TO, '1900-01-01') AS TIMESTAMP_LTZ)
        THEN 'YES'
        ELSE 'NO' END
    AS SLA_MET,
    CAST(COALESCE(UPDATED_TO, '1900-01-01') AS TIMESTAMP_LTZ) AS UPDATED_TO,
    CAST(COALESCE(COMPLETED_AT, '1900-01-01') AS TIMESTAMP_LTZ) AS COMPLETED_AT
FROM (

    SELECT
        'EV' AS DATABASE,
        'ULTRA_WAREHOUSE' AS SCHEMA,
        'CARRIER & CASE' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE.HVR_INTERNAL_ULTRA_WAREHOUSE.HVR_ISEV_UW_SD_T_EV_UW_CA

    UNION ALL
    SELECT
        'EV' AS DATABASE,
        'ULTRA_WAREHOUSE' AS SCHEMA,
        'CYCLE_COUNT' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE.HVR_INTERNAL_ULTRA_WAREHOUSE.HVR_ISEV_UW_SD_T_EV_UW_CC

    UNION ALL
    SELECT
        'EV' AS DATABASE,
        'ULTRA_WAREHOUSE' AS SCHEMA,
        'INVENTORY' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE.HVR_INTERNAL_ULTRA_WAREHOUSE.HVR_ISEV_UW_SD_T_EV_UW_IN

    UNION ALL
    SELECT
        'EV' AS DATABASE,
        'ULTRA_WAREHOUSE' AS SCHEMA,
        'ITEM' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE.HVR_INTERNAL_ULTRA_WAREHOUSE.HVR_ISEV_UW_SD_T_EV_UW_IT

    UNION ALL
    SELECT
        'EV' AS DATABASE,
        'ULTRA_WAREHOUSE' AS SCHEMA,
        'LPN' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE.HVR_INTERNAL_ULTRA_WAREHOUSE.HVR_ISEV_UW_SD_T_EV_UW_LP

    UNION ALL
    SELECT
        'EV' AS DATABASE,
        'ULTRA_WAREHOUSE' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE.HVR_INTERNAL_ULTRA_WAREHOUSE.HVR_ISEV_UW_SD_T_EV_UW_RT

    UNION ALL
    SELECT
        'EV' AS DATABASE,
        'ULTRA_WAREHOUSE_HISTORY' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_HISTORY.HVR_INTERNAL_HISTORY_ULTRA_WAREHOUSE.HVR_ISEV_UW_H_T_EV_UW_RT_H

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'GDPR' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_GDPR.HVR_ISFL_GDPR_SD_T_FL_GDPR_RT

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_CART' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_CART.HVR_ISFL_UCRT_SD_T_FL_UCRT_RT

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_CMS' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_CMS.HVR_ISFL_UCMS_SD_T_FL_UCMS_RT

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISFL_UM_SD_T_FL_UM_RT

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'CUSTOMER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISFL_UM_SD_T_FUM_CU

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'HIGH FREQ' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISFL_UM_SD_T_FUM_HF

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'SESSION' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISFL_UM_SD_T_FUM_LT

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'MEMBERSHIP' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISFL_UM_SD_T_FUM_MM
    UNION ALL

    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'UI PROMO' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISFL_UM_SD_T_FUM_UI

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_ROLLUP' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_ULTRA_ROLLUP.HVR_ISFL_UR_SD_T_FL_UR_RT

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_CMS_HISTORY' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_HISTORY_ULTRA_CMS.HVR_ISFL_UCMS_H_T_FUCMS_RT_H

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'CUSTOMER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISFL_UM_H_T_FUM_CU_H

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'HIGH FREQ' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISFL_UM_H_T_FUM_HF_H

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'MEMBERSHIP' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISFL_UM_H_T_FUM_MM_H

    UNION ALL
    SELECT
        'FL' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_FL.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISFL_UM_H_T_FUM_RT_H

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'GDPR' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_GDPR.HVR_ISJF_GDPR_SD_T_JF_GDPR_RT

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_CART' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_CART.HVR_ISJF_UCRT_SD_T_JF_UCRT_RT

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISJF_UM_SD_T_JF_UM_RT

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'CUSTOMER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISJF_UM_SD_T_JUM_CU

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'HIGH FREQ' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISJF_UM_SD_T_JUM_HF

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'SESSION' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISJF_UM_SD_T_JUM_LT

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'MEMBERSHIP' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISJF_UM_SD_T_JUM_MM
    UNION ALL

    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'UI PROMO' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISJF_UM_SD_T_JUM_UI

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'CUSTOMER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISJF_UM_H_T_JUM_CU_H

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'HIGH FREQ' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISJF_UM_H_T_JUM_HF_H

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'MEMBERSHIP' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISJF_UM_H_T_JUM_MM_H

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISJF_UM_H_T_JUM_RT_H

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_CMS_HISTORY' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_HISTORY_ULTRA_CMS.HVR_ISJF_UCMS_H_T_JUCMS_RT_H

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_CMS' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_CMS.HVR_ISJF_UCMS_SD_T_JF_UCMS_RT

    UNION ALL
    SELECT
        'JFB' AS DATABASE,
        'ULTRA_ROLLUP' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_JFB.HVR_INTERNAL_ULTRA_ROLLUP.HVR_ISJF_UR_SD_T_JF_UR_RT

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'GDPR' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_GDPR.HVR_ISSX_GDPR_SD_T_SX_GDPR_RT

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_CART' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_CART.HVR_ISSX_UCRT_SD_T_SX_UCRT_RT

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_CMS' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_CMS.HVR_ISSX_UCMS_SD_T_SX_UCMS_RT

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISSX_UM_SD_T_SX_UM_RT

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'CUSTOMER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISSX_UM_SD_T_SUM_CU

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'HIGH FREQ' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISSX_UM_SD_T_SUM_HF

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'SESSION' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISSX_UM_SD_T_SUM_LT

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'MEMBERSHIP' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISSX_UM_SD_T_SUM_MM
    UNION ALL

    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT' AS SCHEMA,
        'UI PROMO' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_MERCHANT.HVR_ISSX_UM_SD_T_SUM_UI

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_ROLLUP' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_ULTRA_ROLLUP.HVR_ISSX_UR_SD_T_SX_UR_RT

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_CMS_HISTORY' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_HISTORY_ULTRA_CMS.HVR_ISSX_UCMS_H_T_SUCMS_RT_H

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'CUSTOMER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISSX_UM_H_T_SUM_CU_H

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'HIGH FREQ' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISSX_UM_H_T_SUM_HF_H

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'MEMBERSHIP' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISSX_UM_H_T_SUM_MM_H

    UNION ALL
    SELECT
        'SXF' AS DATABASE,
        'ULTRA_MERCHANT_HISTORY' AS SCHEMA,
        'OTHER' AS TABLE_GROUP,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', TRAILER_CAP_BEGIN) AS UPDATED_TO,
        CONVERT_TIMEZONE('UTC', 'US/Pacific', LAST_INTEG_END) AS COMPLETED_AT
    FROM LAKE_SXF.HVR_INTERNAL_HISTORY_ULTRA_MERCHANT.HVR_ISSX_UM_H_T_SUM_RT_H
) AS A;
GRANT OWNERSHIP ON VIEW LAKE_CONSOLIDATED.REFERENCE.HVR_LAKE_STATUS TO ROLE ACCOUNTADMIN COPY CURRENT GRANTS;