CREATE OR REPLACE VIEW  reporting_media_prod.dbo.vw_media_dim_store as
    select store_id,
            store_group_id,
            store_group,
            store_name,
            store_name_region,
            store_full_name,
            store_brand,
            store_brand_abbr,
            store_type,
            store_sub_type,
            is_core_store,
            store_country,
            store_region,
            store_division,
            store_division_abbr,
            store_currency,
            store_time_zone,
            store_retail_state,
            store_retail_city,
            store_retail_location,
            store_retail_zip_code,
            store_retail_location_code,
            0 as speciality_store,
            meta_create_datetime,
            meta_update_datetime
    from edw_prod.data_model.dim_store

    union all

    select store_id,
            store_group_id,
            store_group,
            store_name,
            store_name_region,
            store_full_name,
            store_brand,
            store_brand_abbr,
            store_type,
            store_sub_type,
            is_core_store,
            store_country,
            store_region,
            store_division,
            store_division_abbr,
            store_currency,
            store_time_zone,
            store_retail_state,
            store_retail_city,
            store_retail_location,
            store_retail_zip_code,
            store_retail_location_code,
            1 as speciality_store,
            meta_create_datetime,
            meta_update_datetime
    from reporting_media_prod.dbo.dim_speciality_store
;
