from include.utils.acquisition.lake_consolidated_table_config import (
    LakeConsolidatedTableConfig as TableConfig,
)
from include.utils.snowflake import Column

table_config = TableConfig(
    table="ml_gms_export_customer_save_data_sel",
    company_join_sql="""
        SELECT DISTINCT
            L.ML_GMS_EXPORT_CUSTOMER_SAVE_DATA_SEL_ID,
            DS.COMPANY_ID
        FROM {database}.REFERENCE.DIM_STORE AS DS
        INNER JOIN {database}.{schema}.CUSTOMER AS C
            ON DS.STORE_GROUP_ID = C.STORE_GROUP_ID
        INNER JOIN {database}.{source_schema}.ml_gms_export_customer_save_data_sel AS L
            ON L.CUSTOMER_ID = C.CUSTOMER_ID """,
    column_list=[
        Column(
            "ml_gms_export_customer_save_data_sel_id", "INT", uniqueness=True, key=True
        ),
        Column("customer_id", "INT", key=True),
        Column("store_label", "VARCHAR(13)"),
        Column("median_income", "VARCHAR(50)"),
        Column("cancel_call_count", "INT"),
        Column("days_last_cancel_call", "INT"),
        Column("number_of_vip_cancelled_accounts", "INT"),
        Column("last_cancelled_account_days", "INT"),
        Column("total_number_of_accounts", "INT"),
        Column("total_number_of_vip_accounts", "INT"),
        Column("store_credit_balance", "NUMBER(19, 4)"),
        Column("active_credits", "INT"),
        Column("active_credits_amount", "NUMBER(19, 4)"),
        Column("fraud_customer_statuscode", "INT"),
        Column("total_credits", "INT"),
        Column("total_credits_amount", "NUMBER(19, 4)"),
        Column("total_credits_refunded", "INT"),
        Column("total_credits_refunded_amount", "NUMBER(19, 4)"),
        Column("skips", "INT"),
        Column("grace_skips", "INT"),
        Column("grace_skips_this_year", "INT"),
        Column("current_period_skip", "INT"),
        Column("saves", "INT"),
        Column("last_order_amount", "NUMBER(19, 4)"),
        Column("last_order_date", "TIMESTAMP_NTZ(3)"),
        Column("last_order_type", "INT"),
        Column("first_order_total", "NUMBER(19, 4)"),
        Column("member_purchased_amount", "NUMBER(19, 4)"),
        Column("refund_total", "NUMBER(19, 4)"),
        Column("total_order_amount", "NUMBER(19, 4)"),
        Column("order_count", "INT"),
        Column("failed_auth_total", "NUMBER(19, 4)"),
        Column("reward_points", "INT"),
        Column("ct", "VARCHAR(1)"),
        Column("last_login_hours_count", "INT"),
        Column("days_member_start", "INT"),
        Column("days_member_first_start", "INT"),
        Column("last_order_days", "INT"),
        Column("days_since_last_credit_billing", "INT"),
        Column("gaming_total_score", "DOUBLE"),
        Column("days_to_ship_last_order", "INT"),
        Column("cancel_call_day_of_month", "INT"),
        Column("cancel_call_time_of_day", "DOUBLE"),
        Column("skip_datetime_m_minus_1", "DOUBLE"),
        Column("skip_datetime_m_minus_2", "DOUBLE"),
        Column("login_count_last_60_days", "INT"),
        Column("login_count_last_30_days", "INT"),
        Column("login_count_last_10_days", "INT"),
        Column("login_count_last_5_days", "INT"),
        Column("first_of_month_login_count_last_60_days", "INT"),
        Column("order_count_last_60_days", "INT"),
        Column("order_count_last_30_days", "INT"),
        Column("order_amount_last_60_days", "NUMBER(19, 4)"),
        Column("order_amount_last_30_days", "NUMBER(19, 4)"),
        Column("order_count_last_10_days", "INT"),
        Column("order_count_last_5_days", "INT"),
        Column("order_amount_last_10_days", "NUMBER(19, 4)"),
        Column("order_amount_last_5_days", "NUMBER(19, 4)"),
        Column("session_time_to_cart_last_60_days", "INT"),
        Column("session_to_cart_count_last_60_days", "INT"),
        Column("session_time_to_cart_last_30_days", "INT"),
        Column("session_to_cart_count_last_30_days", "INT"),
        Column("session_time_to_cart_last_10_days", "INT"),
        Column("session_to_cart_count_last_10_days", "INT"),
        Column("session_time_to_cart_last_5_days", "INT"),
        Column("session_to_cart_count_last_5_days", "INT"),
        Column("total_save_credit_issued", "NUMBER(19, 4)"),
        Column("total_save_credit_balance", "NUMBER(19, 4)"),
        Column("total_review", "INT"),
        Column("total_recommended_count", "INT"),
        Column("last_review_days", "INT"),
        Column("last_review_recommended", "VARCHAR(3)"),
        Column(
            "datetime_added",
            "TIMESTAMP_NTZ(3)",
        ),
    ],
    watermark_column="datetime_added",
)
