from include.utils.acquisition.lake_consolidated_table_config import (
    LakeConsolidatedTableConfig as TableConfig,
)
from include.utils.snowflake import Column

table_config = TableConfig(
    table="promo",
    company_join_sql="""SELECT DISTINCT L.promo_id, DS.company_id
    from {database}.REFERENCE.dim_store ds
    join {database}.{source_schema}.promo L
            on ds.store_group_id=L.store_group_id""",
    column_list=[
        Column("promo_id", "INT", uniqueness=True, key=True),
        Column("store_group_id", "INT"),
        Column("promo_type_id", "INT"),
        Column("subtotal_discount_id", "INT", key=True),
        Column("shipping_discount_id", "INT", key=True),
        Column("product_id", "INT", key=True),
        Column("product_category_id", "INT", key=True),
        Column("membership_plan_id", "INT", key=True),
        Column("required_product_id", "INT", key=True),
        Column("required_product_category_id", "INT", key=True),
        Column("required_membership_plan_id", "INT", key=True),
        Column("shipping_option_id", "INT"),
        Column("required_promo_id", "INT", key=True),
        Column("code", "VARCHAR(50)"),
        Column("label", "VARCHAR(50)"),
        Column("description", "VARCHAR(255)"),
        Column("min_subtotal", "NUMBER(19, 4)"),
        Column("min_purchase_unit_price", "NUMBER(19, 4)"),
        Column("min_required_purchase_unit_price", "NUMBER(19, 4)"),
        Column("max_product_quantity", "INT"),
        Column("min_product_quantity", "INT"),
        Column("required_product_quantity", "INT"),
        Column("max_uses_per_customer", "INT"),
        Column("max_discount_sets_per_use", "INT"),
        Column("rush_shipping_discount_allowed", "INT"),
        Column("apply_automatically", "INT"),
        Column("add_product_automatically", "INT"),
        Column("remove_product_automatically", "INT"),
        Column("membership_promo_expiration_days", "INT"),
        Column("membership_promo_current_period_only", "INT"),
        Column("allow_membership_credits", "INT"),
        Column("allow_like_promos", "INT"),
        Column("date_start", "TIMESTAMP_NTZ(0)"),
        Column("date_end", "TIMESTAMP_NTZ(0)"),
        Column(
            "datetime_added",
            "TIMESTAMP_NTZ(3)",
        ),
        Column("statuscode", "INT"),
        Column("max_purchase_unit_price", "NUMBER(19, 4)"),
        Column("max_required_purchase_unit_price", "NUMBER(19, 4)"),
        Column("allow_prepaid_creditcard", "INT"),
        Column(
            "datetime_modified",
            "TIMESTAMP_NTZ(3)",
        ),
        Column("featured_product_location_id", "INT", key=True),
        Column("required_featured_product_location_id", "INT", key=True),
        Column("restrict_code_access_to_specific_memberships", "INT"),
        Column("terms", "VARCHAR"),
        Column("time_start", "TIME"),
        Column("time_end", "TIME"),
        Column("long_label", "VARCHAR(2550)"),
        Column("refunds_allowed", "INT"),
        Column("exchanges_allowed", "INT"),
        Column("membership_reward_multiplier", "NUMBER(18, 1)"),
        Column("group_code", "VARCHAR(50)"),
        Column("filtered_featured_product_location_id", "INT", key=True),
        Column("filtered_product_category_id", "INT", key=True),
        Column("filtered_benefit_featured_product_location_id", "INT"),
        Column("filtered_benefit_product_category_id", "INT"),
        Column("display_on_pdp", "INT"),
        Column("pdp_label", "VARCHAR(255)"),
        Column("max_uses_per_day", "INT"),
        Column("store_domain_type_id_list", "VARCHAR(50)"),
        Column("membership_brand_id_list", "VARCHAR(50)"),
        Column("qualification_product_include_membership_brand_id_list", "VARCHAR(50)"),
        Column("qualification_product_exclude_membership_brand_id_list", "VARCHAR(50)"),
        Column("benefit_product_include_membership_brand_id_list", "VARCHAR(50)"),
        Column("benefit_product_exclude_membership_brand_id_list", "VARCHAR(50)"),
        Column("rush_shipping_discount_id", "NUMBER(38,0)"),
    ],
    watermark_column="datetime_modified",
)
