from dataclasses import dataclass
from include.utils.snowflake import Column
from typing import List


@dataclass
class Config:
    """
    This class will compare snowflake view definition available in source control with
    snowflake and sends email alert with list of mismatch views.  If the view doesnt exist in repo
    code will raise an exception.

    Args:
        name: name of the interface
        remote_dir: SFTP path to which the csv files of the interface to be written
        append: Should the snashot be maintainted, True if snapshot to be maintained, else False
        generate_empty_file: if set to True, then if no records available, then an empty file
        will be generated.
        column_list: List of columns in the interface along with datatypes
    """

    name: str
    file_name: str
    append: bool
    generate_empty_file: bool
    column_list: List[Column]


config_list = {
    "transportload": Config(
        name='transportload',
        append=True,
        file_name='transportLoads',
        generate_empty_file=True,
        column_list=[
            Column('LOADID', 'VARCHAR'),
            Column('ARRIVDATE', 'DATE'),
            Column('SHIPDATE', 'DATE'),
            Column('TRANSMODE', 'VARCHAR'),
            Column('SOURCE', 'VARCHAR'),
            Column('DEST', 'VARCHAR'),
            Column('ITEM', 'VARCHAR'),
            Column('SOURCING', 'VARCHAR'),
            Column('UNITS', 'NUMBER(38,0)'),
            Column('U_STATUS', 'VARCHAR'),
        ],
    ),
    "schedrcpts": Config(
        name='schedrcpts',
        append=True,
        file_name='scheduledReceipts',
        generate_empty_file=True,
        column_list=[
            Column('ITEM', 'VARCHAR'),
            Column('LOC', 'VARCHAR'),
            Column('SCHEDDATE', 'DATE'),
            Column('UNITS', 'NUMBER(38,0)'),
            Column('COST', 'NUMBER(38,12)'),
            Column('RETAIL', 'VARCHAR'),
            Column('PO_TYPE', 'VARCHAR'),
            Column('PO_NUMBER', 'VARCHAR'),
            Column('VENDOR', 'VARCHAR'),
            Column('ORIG_UNITS', 'NUMBER(38,0)'),
            Column('ORIG_SHOWROOM_DATE', 'VARCHAR'),
            Column('SEQNUM', 'NUMBER(18,0)'),
        ],
    ),
    "inventory": Config(
        name='inventory',
        append=True,
        file_name='inventoryOnHands',
        generate_empty_file=True,
        column_list=[
            Column('ITEM', 'VARCHAR'),
            Column('LOC', 'VARCHAR'),
            Column('AVAILDATE', 'DATE'),
            Column('UNITS', 'NUMBER(38,0)'),
            Column('OTB_UNITS', 'NUMBER(38,0)'),
            Column('OTB_COST', 'NUMBER(38,10)'),
            Column('INTRANSIT_UNITS', 'NUMBER(38,10)'),
            Column('ORDER_UNITS', 'NUMBER(38,10)'),
        ],
    ),
    "inventory_transaction": Config(
        name='inventory_transaction',
        append=True,
        file_name='inventoryTransactions',
        generate_empty_file=True,
        column_list=[
            Column('ITEM', 'VARCHAR'),
            Column('LOC', 'VARCHAR'),
            Column('STARTDATE', 'DATE'),
            Column('TRANSACTIONCODE', 'NUMBER(2,0)'),
            Column('UNITS', 'NUMBER(38,0)'),
            Column('COST', 'NUMBER(38,12)'),
            Column('RETAIL', 'NUMBER(38,12)'),
        ],
    ),
    "network": Config(
        name='network',
        append=True,
        file_name='networks',
        generate_empty_file=True,
        column_list=[
            Column('SOURCE', 'VARCHAR'),
            Column('DEST', 'VARCHAR'),
            Column('TRANSMODE', 'VARCHAR'),
            Column('ITEM', 'VARCHAR'),
            Column('SOURCING', 'VARCHAR'),
            Column('TRANSLEADTIME', 'NUMBER(22,5)'),
        ],
    ),
    "dfu": Config(
        name='dfu',
        append=True,
        file_name='itemLocationCustomers',
        generate_empty_file=True,
        column_list=[
            Column('DMDUNIT', 'VARCHAR'),
            Column('DMDGROUP', 'VARCHAR'),
            Column('LOC', 'VARCHAR'),
            Column('MARKET', 'VARCHAR'),
            Column('BUS_SEGMENT', 'VARCHAR'),
            Column('HIST_STREAM', 'VARCHAR'),
            Column('LEAD_ONLY', 'NUMBER(1,0)'),
        ],
    ),
    "history": Config(
        name='history',
        append=True,
        file_name='histShipments',
        generate_empty_file=True,
        column_list=[
            Column('SKU', 'VARCHAR'),
            Column('CC', 'VARCHAR'),
            Column('DMDGROUP', 'VARCHAR'),
            Column('LOC', 'VARCHAR'),
            Column('STARTDATE', 'DATE'),
            Column('HISTSTREAM', 'VARCHAR'),
            Column('DUR', 'NUMBER(4,0)'),
            Column('UNITS_NONACT', 'NUMBER(38,0)'),
            Column('UNITS_ACT', 'NUMBER(38,0)'),
            Column('COST_NONACT', 'NUMBER(38,10)'),
            Column('COST_ACT', 'NUMBER(38,10)'),
            Column('RETAIL_NONACT', 'NUMBER(38,10)'),
            Column('RETAIL_ACT', 'NUMBER(38,10)'),
            Column('DISC_NONACT', 'NUMBER(38,10)'),
            Column('DISC_ACT', 'NUMBER(38,10)'),
            Column('RET_UNITS', 'NUMBER(38,0)'),
            Column('RET_COST', 'NUMBER(38,10)'),
            Column('DMD_FLAG', 'NUMBER(1,0)'),
            Column('ALLOC_FLAG', 'NUMBER(1,0)'),
            Column('EP_FLAG', 'NUMBER(1,0)'),
            Column('SS_FLAG', 'NUMBER(1,0)'),
        ],
    ),
    "worklist": Config(
        name='worklist',
        append=True,
        file_name='workLists',
        generate_empty_file=True,
        column_list=[
            Column('OPERATION_CODE', 'NUMBER(1,0)'),
            Column('DEFAULT_WAREHOUSE', 'VARCHAR'),
            Column('QUANTITY_PER_PACK', 'NUMBER(1,0)'),
            Column('PACK_SKU', 'VARCHAR'),
            Column('VENDOR_PACK', 'VARCHAR'),
            Column('AVAILABLE_PACKS', 'NUMBER(38,0)'),
            Column('ON_ORDER_PACKS', 'NUMBER(38,0)'),
            Column('PO_DST_NUMBER', 'VARCHAR'),
            Column('PRODUCT_NUMBER', 'VARCHAR'),
            Column('MERCHANDISE_SOURCE', 'NUMBER(1,0)'),
            Column('ASN_NUMBER', 'VARCHAR'),
            Column('RECEIPT_DATE', 'VARCHAR'),
            Column('EXP_RECEIPT_DATE', 'VARCHAR'),
            Column('SKU', 'VARCHAR'),
            Column('LINE_SEQUENCE', 'NUMBER(38,0)'),
            Column('PRODUCT_IMAGE', 'VARCHAR'),
        ],
    ),
    "sku": Config(
        name='sku',
        append=True,
        file_name='itemLocations',
        generate_empty_file=True,
        column_list=[
            Column('ITEM', 'VARCHAR'),
            Column('LOC', 'VARCHAR'),
            Column('REPLENTYPE', 'NUMBER(1,0)'),
        ],
    ),
    "calendar": Config(
        name='calendar',
        append=True,
        file_name='extCalendarses01',
        generate_empty_file=True,
        column_list=[
            Column('day', 'DATE'),
            Column('week', 'VARCHAR(30)'),
            Column('month', 'VARCHAR(30)'),
            Column('month_desc', 'VARCHAR'),
            Column('month_startdate', 'DATE'),
            Column('quarter', 'VARCHAR(30)'),
            Column('quarter_desc', 'VARCHAR(30)'),
            Column('quarter_startdate', 'DATE'),
            Column('half', 'VARCHAR(30)'),
            Column('half_desc', 'VARCHAR(30)'),
            Column('half_startdate', 'DATE'),
            Column('year', 'VARCHAR(30)'),
            Column('year_desc', 'VARCHAR(30)'),
            Column('year_startdate', 'DATE'),
        ],
    ),
    "loc": Config(
        name='loc',
        append=True,
        file_name='locations',
        generate_empty_file=True,
        column_list=[
            Column('LOCATION', 'VARCHAR'),
            Column('DESCR', 'VARCHAR'),
            Column('TYPE', 'NUMBER(1,0)'),
            Column('TOTAL_COMPANY', 'VARCHAR'),
            Column('TOTAL_COMPANY_DESC', 'VARCHAR'),
            Column('COMPANY', 'VARCHAR'),
            Column('COMPANY_DESC', 'VARCHAR'),
            Column('BUS_SEG', 'VARCHAR'),
            Column('LOC_H_LVL_1', 'VARCHAR'),
            Column('LOC_H_LVL_1_DSC', 'VARCHAR'),
            Column('LOC_H_LVL_2', 'VARCHAR'),
            Column('LOC_H_LVL_2_DSC', 'VARCHAR'),
            Column('CITY', 'VARCHAR'),
            Column('STATE', 'VARCHAR'),
            Column('STATE_NAME', 'VARCHAR'),
            Column('CHANNEL', 'VARCHAR'),
            Column('CHANNEL_NAME', 'VARCHAR'),
            Column('REGION', 'VARCHAR'),
            Column('REGION_NAME', 'VARCHAR'),
            Column('DISTRICT', 'VARCHAR'),
            Column('DISTRICT_NAME', 'VARCHAR'),
            Column('ADDRESS_1', 'VARCHAR'),
            Column('ADDRESS_2', 'VARCHAR'),
            Column('ZIP_CODE', 'VARCHAR'),
            Column('COUNTRY_ID', 'NUMBER(5,0)'),
            Column('COUNTRY_NAME', 'VARCHAR'),
            Column('TELEPHONE', 'VARCHAR'),
            Column('ACTIVE_YN', 'VARCHAR'),
            Column('DATE_OPENED', 'VARCHAR'),
            Column('DATE_CLOSED', 'VARCHAR'),
            Column('FORMAT', 'VARCHAR'),
            Column('REMODEL_DATE', 'VARCHAR'),
            Column('ANNUAL_SALES', 'NUMBER(1,0)'),
            Column('RETAIL_SQUARE_FEET', 'NUMBER(38,0)'),
            Column('WHSE_FLAG', 'VARCHAR'),
            Column('OUTLET_FLAG', 'VARCHAR'),
            Column('STORE_NUMBER', 'VARCHAR'),
            Column('STORE_ID', 'NUMBER'),
            Column('DMD_FLAG', 'NUMBER(1,0)'),
            Column('FF_FLAG', 'NUMBER(1,0)'),
            Column('ALLOC_FLAG', 'NUMBER(1,0)'),
            Column('EP_FLAG', 'NUMBER(1,0)'),
            Column('SS_FLAG', 'NUMBER(1,0)'),
        ],
    ),
    "item": Config(
        name='item',
        append=True,
        file_name='items',
        generate_empty_file=True,
        column_list=[
            Column('item', 'VARCHAR'),
            Column('descr', 'VARCHAR'),
            Column('total_company', 'VARCHAR'),
            Column('total_company_desc', 'VARCHAR'),
            Column('company', 'VARCHAR'),
            Column('company_desc', 'VARCHAR'),
            Column('division', 'VARCHAR'),
            Column('division_desc', 'VARCHAR'),
            Column('product_segment', 'VARCHAR'),
            Column('product_segment_desc', 'VARCHAR'),
            Column('gender', 'VARCHAR'),
            Column('gender_desc', 'VARCHAR'),
            Column('sub_dept', 'VARCHAR'),
            Column('sub_dept_desc', 'VARCHAR'),
            Column('class', 'VARCHAR'),
            Column('class_desc', 'VARCHAR'),
            Column('sub_class', 'VARCHAR'),
            Column('sub_class_desc', 'VARCHAR'),
            Column('style', 'VARCHAR'),
            Column('style_desc', 'VARCHAR'),
            Column('cc', 'VARCHAR'),
            Column('cc_desc', 'VARCHAR'),
            Column('color', 'VARCHAR'),
            Column('color_desc', 'VARCHAR'),
            Column('size', 'VARCHAR'),
            Column('size_desc', 'VARCHAR'),
            Column('size_seq', 'VARCHAR'),
            Column('ecosystem', 'VARCHAR'),
            Column('fit_block', 'VARCHAR'),
            Column('lined_unlined', 'VARCHAR'),
            Column('fabric', 'VARCHAR'),
            Column('fabric_desc', 'VARCHAR'),
            Column('collection', 'VARCHAR'),
            Column('collection_desc', 'VARCHAR'),
            Column('color_family', 'VARCHAR'),
            Column('color_family_desc', 'VARCHAR'),
            Column('core_item', 'NUMBER(38,0)'),
            Column('core_vs_fashion', 'VARCHAR'),
            Column('dmd_flag', 'VARCHAR'),
            Column('ff_flag', 'VARCHAR'),
            Column('alloc_flag', 'VARCHAR'),
            Column('ep_flag', 'VARCHAR'),
            Column('ss_flag', 'VARCHAR'),
            Column('vip_price', 'NUMBER(19,4)'),
            Column('retail_price', 'NUMBER(19,4)'),
            Column('msp_price', 'NUMBER(19,4)'),
        ],
    ),
    "itemhierarchy": Config(
        name='itemhierarchy',
        append=True,
        file_name='itemHierarchyLevelMembers',
        generate_empty_file=True,
        column_list=[
            Column('PRODUCTGROUPID', 'varchar'),
            Column('PRODUCTGROUPNAME', 'varchar'),
            Column('LEVELID', 'varchar'),
            Column('PARENTACTIONCODE', 'number(2,0)'),
            Column('PARENTGROUPID', 'varchar'),
            Column('PARENTLEVELID', 'varchar'),
        ],
    ),
    "lochierarchy": Config(
        name='lochierarchy',
        append=True,
        file_name='locationHierarchyLevelMembers',
        generate_empty_file=True,
        column_list=[
            Column('MEMBERID', 'varchar'),
            Column('MEMBERNAME', 'varchar'),
            Column('LEVELID', 'varchar'),
            Column('PARENTACTIONCODE', 'number(5,0)'),
            Column('PARENTMEMBERID', 'varchar'),
            Column('PARENTLEVELID', 'varchar'),
        ],
    ),
}
