CREATE VIEW IF NOT EXISTS LAKE_VIEW.EMARSYS.SMS_CAMPAIGNS AS
SELECT  csm.store_group,
    s.NAME,
	s.SENDER_NAME,
	s.MESSAGE,
	s.INCLUDE_UNSUBSCRIBE_LINK,
	s.TRIGGER_TYPE,
	s.CAMPAIGN_ID,
	s.EVENT_TIME,
	s.CUSTOMER_ID,
	s.LOADED_AT,
	s.BUSINESS_UNIT,
	s.META_CREATE_DATETIME
FROM LAKE.EMARSYS.SMS_CAMPAIGNS s
JOIN lake.emarsys.customer_store_mapping csm on csm.customer_id = s.customer_id;
