CREATE VIEW IF NOT EXISTS LAKE_VIEW.EMARSYS.WEBCHANNEL_EVENTS_ENHANCED AS
SELECT csm.store_group,
    s.PLATFORM,
	s.MD5,
	s.IS_MOBILE,
	s.IS_ANONYMIZED,
	s.CAMPAIGN_ID,
	s.AD_ID,
	s.CUSTOMER_ID,
	s.CONTACT_ID,
	s.EVENT_TYPE,
	s.USER_AGENT,
	s.EVENT_TIME,
	s.LOADED_AT,
	s.META_CREATE_DATETIME
FROM LAKE.EMARSYS.WEBCHANNEL_EVENTS_ENHANCED s
JOIN lake.emarsys.customer_store_mapping csm on csm.customer_id = s.customer_id;
