CREATE VIEW IF NOT EXISTS LAKE_VIEW.EMARSYS.EMAIL_CAMPAIGNS_V2 AS
SELECT csm.store_group,
    s.CAMPAIGN_ID,
	s.CAMPAIGN_TYPE,
	s.CATEGORY_NAME,
	s.CUSTOMER_ID,
	s.DEFINED_TYPE,
	s.EVENT_TIME,
	s.IS_RECURRING,
	s.LANGUAGE,
	s.LOADED_AT,
	s.NAME,
	s.ORIGIN_CAMPAIGN_ID,
	s.PROGRAM_ID,
	s.PROGRAM_VERSION_ID,
	s.SUBJECT,
	s.SUITE_EVENT,
	s.SUITE_TYPE,
	s.TIMEZONE,
	s.VERSION_NAME,
	s.META_CREATE_DATETIME
FROM LAKE.EMARSYS.EMAIL_CAMPAIGNS_V2 s
JOIN lake.emarsys.customer_store_mapping csm on csm.customer_id = s.customer_id;
