CREATE VIEW IF NOT EXISTS LAKE_VIEW.EMARSYS.SESSION_TAGS AS
SELECT csm.store_group,
    s.USER_ID,
	s.USER_ID_TYPE,
	s.USER_ID_FIELD_ID,
	s.CONTACT_ID,
	s.TAG,
	s.ATTRIBUTES,
	s.ATTRIBUTES_NAME,
	s.ATTRIBUTES_STRING_VALUE,
	s.ATTRIBUTES_NUMBER_VALUE,
	s.ATTRIBUTES_BOOLEAN_VALUE,
	s.EVENT_TIME,
	s.CUSTOMER_ID,
	s.LOADED_AT,
	s.META_CREATE_DATETIME
FROM LAKE.EMARSYS.SESSION_TAGS s
JOIN lake.emarsys.customer_store_mapping csm on csm.customer_id = s.customer_id;
