CREATE VIEW IF NOT EXISTS LAKE_VIEW.EMARSYS.EMAIL_UNSUBSCRIBES AS
SELECT
    csm.store_group,
    s.CAMPAIGN_ID,
	s.CAMPAIGN_TYPE,
	s.CONTACT_ID,
	s.CUSTOMER_ID,
	s.DOMAIN,
	s.EMAIL_SENT_AT,
	s.EVENT_TIME,
	s.LAUNCH_ID,
	s.LOADED_AT,
	s.MESSAGE_ID,
	s.SOURCE,
	s.META_CREATE_DATETIME
FROM LAKE.EMARSYS.EMAIL_UNSUBSCRIBES s
JOIN lake.emarsys.customer_store_mapping csm on csm.customer_id = s.customer_id;
