create or replace view lake_view.gms.cognigy_analytics(
  id,
  organisation,
  project_id,
  flow_reference_id,
  entrypoint,
  ip,
  contact_id,
  session_id,
  input_id,
  input_text,
  state,
  mode,
  user_type,
  channel,
  flow_language,
  intent,
  intent_flow,
  intent_score,
  completed_goals_list,
  found_slots,
  found_slot_details,
  understood,
  timestamp,
  execution_time,
  execution,
  custom1,
  custom2,
  custom3,
  custom4,
  custom5,
  custom6,
  custom7,
  custom8,
  custom9,
  custom10,
  locale_reference_id,
  locale_name,
  endpoint_url_token,
  endpoint_name,
  rating,
  rating_comment,
  snapshot_name,
  event,
  country,
  country_calling_code,
  national_number,
  phone_number,
  call_termination_by,
  event_type,
  browser,
  browser_version,
  geolocation_city,
  geolocation_country,
  language,
  languages,
  origin,
  os,
  platform,
  meta_create_datetime,
  meta_update_datetime
) as
select id,
       organisation,
       project_id,
       flow_reference_id,
       entrypoint,
       ip,
       contact_id,
       session_id,
       input_id,
       input_text,
       state,
       mode,
       user_type,
       channel,
       flow_language,
       intent,
       intent_flow,
       intent_score,
       completed_goals_list,
       found_slots,
       found_slot_details,
       understood,
       timestamp,
       execution_time,
       execution,
       custom1,
       custom2,
       custom3,
       custom4,
       custom5,
       custom6,
       custom7,
       custom8,
       custom9,
       custom10,
       locale_reference_id,
       locale_name,
       endpoint_url_token,
       endpoint_name,
       rating,
       rating_comment,
       snapshot_name,
       input_data:event::varchar                                 event,
       input_data:numbermetadata:country::varchar                country,
       input_data:numbermetadata:countrycallingcode::int         country_calling_code,
       input_data:numbermetadata:nationalnumber::int             national_number,
       input_data:numbermetadata:number::varchar                 phone_number,
       input_data:payload:call_termination_by::varchar           call_termination_by,
       input_data:_cognigy:event:type::varchar                   event_type,
       input_data:_webchat3Metadata:browser::varchar             browser,
       input_data:_webchat3Metadata:browser_version::varchar     browser_version,
       input_data:_webchat3Metadata:geolocation:city::varchar    geolocation_city,
       input_data:_webchat3Metadata:geolocation:country::varchar geolocation_country,
       input_data:_webchat3Metadata:language::varchar            language,
       input_data:_webchat3Metadata:languages::variant           languages,
       input_data:_webchat3Metadata:origin::varchar              origin,
       input_data:_webchat3Metadata:os::varchar                  os,
       input_data:_webchat3Metadata:platform::varchar            platform,
       meta_create_datetime,
       meta_update_datetime
from lake.cognigy.analytics;
