CREATE OR REPLACE VIEW lake_view.gsc.broker_duty_tariff AS
SELECT
    'OOCL' As customer_broker,
    pstadv_num AS reference_number,
    entry_num AS entry_number,
    pod_eta AS po_eta_number,
    fnd_country AS fnd_country,
    NULL AS entry_port,
    business_unit AS business_unit,
    upper(trim(po_num)) AS po_number,
    sku_num AS sku_number,
    hts_num AS hts_code,
    por_country AS origin_country,
    unit AS units,
    unit_cost AS unit_cost,
    sku_value AS value,
    est_duty AS estimated_duty,
    est_duty_rate AS advalorem_rate,
    duty_fee AS duty_fee,
    NULL AS tariff_fee,
    est_broker_fee AS broker_fee,
    receive_date AS received_date,
    bl_num AS bol_number,
    fw_bl_num AS fw_bol_number,
    cntr_num AS container_number,
    pol_etd AS pol_etd_date,
    oll_billing_invoice_num AS invoice_number,
    advance_fee AS advance_fee,
    NULL AS hmf_fee,
    NULL AS mpf_fee,
    NULL AS non_dutiable_fee,
    NULL AS cotton_fee,
    NULL AS other_fees,
    meta_create_datetime,
    meta_update_datetime
FROM lake.excel.broker_data_oocl

UNION ALL

SELECT
    'CARMICHAEL' AS customer_broker,
    broker_ref_num ,
    entry_num,
    eta,
    'US' AS fnd_country,
    entry_port,
    NULL AS business_unit,
    upper(trim(po_num)) as po_number,
    sku_num,
    hts_num,
    origin_country,
    pieces,
    unit_price,
    po_value,
    NULL AS estimated_duty,
    advalorem_rate,
    duty,
    us_tariffs,
    broker_fee,
    NULL AS received_date,
    NULL AS bol_number,
    NULL AS fw_bol_number,
    NULL AS container_number,
    NULL AS pol_etd_date,
    statement_num,
    NULL AS advance_fee,
    hmf AS hmf_fee,
    mpf AS mpf_fee,
    non_dutiable AS non_dutiable_fee,
    cotton_fee AS cotton_fee,
    nvl(other_fee, 0) + nvl(other_charge, 0) AS other_fees,
    meta_create_datetime,
    meta_update_datetime
FROM lake.excel.broker_data_carmichael;
