CREATE VIEW IF NOT EXISTS lake_view.gsc.pivot88_inspections
AS SELECT
    i.date_inspection,
    i.inspector:name::VARCHAR as inspector_name,
    i.inspector:username::VARCHAR as inspector_username,
    i.inspector:email::VARCHAR as inspector_email,
    i.inspector:title::VARCHAR as inspector_title,
    i.inspector:code::VARCHAR as inspector_code,
    i.inspector:id::NUMBER as inspector_id,
    i.inspection_location,
    i.report_type:name::VARCHAR as report_type_name,
    i.report_type:allow_submit_urgent::BOOLEAN as report_type_allow_submit_urgent,
    i.report_type:id::NUMBER as report_type_id,
    i.date_created,
    i.date_modified,
    i.recycled,
    i.factory_name,
    i.contact_name,
    i.contact_number,
    i.inspection_company,
    i.approved_by,
    i.id,
    i.assignment_group:id::VARCHAR as assignment_group_id,
    i.inspection_method:name::VARCHAR as inspection_method_name,
    i.inspection_level:name::VARCHAR as inspection_level_name,
    report_url,
    i.travel_tag_number,
    i.shift,
    i.line,
    i.supervisor,
    i.comment,
    i.cutter,
    i.next_pqa_date,
    i.staff_id,
    i.assignments_reviewers,
    i.reviewer_user,
    i.spudi_lab_address,
    i.spudi_date,
    f.value:inspection_status_text::VARCHAR as inspection_status_text,
    f.value:inspection_result_text::VARCHAR as inspection_result_text,
    f.value:sampling_size::NUMBER as sampling_size,
    f.value:notes::VARCHAR as notes,
    f.value:inspection_status_id::NUMBER as inspection_status_id,
    f.value:inspection_status_msg::VARCHAR as inspection_status_msg,
    f.value:fabric_description::VARCHAR as fabric_description,
    f.value:inspection_sequence::VARCHAR as inspection_sequence,
    f.value:inspection_result_id::NUMBER as inspection_result_id,
    f.value:inspection_completed_date::TIMESTAMP as inspection_completed_date,
    f.value:client_msg::VARCHAR as client_msg,
    f.value:manager_msg::VARCHAR as manager_msg,
    f.value:recycled::NUMBER as assignments_items_recycled,
    f.value:qty_to_inspect::VARCHAR as qty_to_inspect,
    f.value:qty_inspected::VARCHAR as qty_inspected,
    f.value:inspection_total_critical_defect_count::VARCHAR as inspection_total_critical_defect_count,
    f.value:inspection_total_minor_defect_count::VARCHAR as inspection_total_minor_defect_count,
    f.value:auditor_msg::VARCHAR as auditor_msg,
    f.value:booking_msg::VARCHAR as booking_msg,
    f.value:supplier_booking_msg::VARCHAR as supplier_booking_msg,
    f.value:id::NUMBER as assignments_items_id,
    f.value:unlinked_assignment::VARCHAR as unlinked_assignment,
    f.value:aql_minor:aql::NUMBER as aql_minor,
    f.value:aql_major_b:aql::NUMBER as aql_major_b,
    f.value:aql_major_a:aql::NUMBER as aql_major_a,
    f.value:aql_critical:aql::NUMBER as aql_critical,
    f.value:aql_major:aql::NUMBER as aql_major,
    f.value:po_line:pol_attribute1::VARCHAR as pol_attribute1,
    f.value:po_line:pol_attribute2::VARCHAR as pol_attribute2,
    f.value:po_line:pol_attribute3::VARCHAR as pol_attribute3,
    f.value:po_line:pol_attribute4::VARCHAR as pol_attribute4,
    f.value:po_line:pol_attribute5::VARCHAR as pol_attribute5,
    f.value:po_line:recycled::VARCHAR as po_line_recycled,
    f.value:po_line:qty::NUMBER as qty,
    f.value:po_line:cost::NUMBER as cost,
    f.value:po_line:etd::VARCHAR as etd,
    f.value:po_line:eta::VARCHAR as eta,
    f.value:po_line:color::VARCHAR as color,
    f.value:po_line:size::VARCHAR as size,
    f.value:po_line:style::VARCHAR as style,
    f.value:po_line:banner::VARCHAR as banner,
    f.value:po_line:fob_price::VARCHAR as fob_price,
    f.value:po_line:id::NUMBER as po_line_id,
    f.value:po_line:po:importer_id::NUMBER as po_importer_id,
    f.value:po_line:po:exporter_id::NUMBER as po_exporter_id,
    f.value:po_line:po:suppliers:name::VARCHAR as po_suppliers_name,
    f.value:po_line:po:suppliers:description::VARCHAR as po_suppliers_description,
    f.value:po_line:po:suppliers:address_line1::VARCHAR as po_suppliers_address_line1,
    f.value:po_line:po:suppliers:address_line2::VARCHAR as po_suppliers_address_line2,
    f.value:po_line:po:suppliers:zipcode::VARCHAR as po_suppliers_zipcode,
    f.value:po_line:po:suppliers:banner::VARCHAR as po_suppliers_banner,
    f.value:po_line:po:suppliers:erp_business_id::VARCHAR as po_suppliers_erp_business_id,
    f.value:po_line:po:suppliers:auto_inspect::VARCHAR as po_suppliers_auto_inspect,
    f.value:po_line:po:suppliers:city::VARCHAR as po_suppliers_city,
    f.value:po_line:po:suppliers:state::VARCHAR as po_suppliers_state,
    f.value:po_line:po:suppliers:country::VARCHAR as po_suppliers_country,
    f.value:po_line:po:suppliers:unit_number::VARCHAR as po_suppliers_unit_number,
    f.value:po_line:po:suppliers:contact_name::VARCHAR as po_suppliers_contact_name,
    f.value:po_line:po:suppliers:contact_number::VARCHAR as po_suppliers_contact_number,
    f.value:po_line:po:suppliers:id::NUMBER as po_suppliers_id,
    f.value:po_line:po:suppliers:other_codes::VARCHAR as po_suppliers_other_codes,
    f.value:po_line:po:suppliers:un_locode::VARCHAR as po_suppliers_un_locode,
    f.value:po_line:po:po_number::VARCHAR as po_number,
    f.value:po_line:po:order_date::TIMESTAMP as order_date,
    f.value:po_line:po:origin::VARCHAR as origin,
    f.value:po_line:po:destination::VARCHAR as destination,
    f.value:po_line:po:recycled_at::VARCHAR as recycled_at,
    f.value:po_line:po:customer_po::VARCHAR as customer_po,
    f.value:po_line:po:id::NUMBER as po_line_po_id,
    f.value:po_line:po:project:name::VARCHAR as po_line_po_project_name,
    f.value:po_line:po:project:project_code::VARCHAR as po_line_po_project_code,
    f.value:po_line:po:project:id::VARCHAR as po_line_po_project_id,
    f.value:po_line:po:client::VARCHAR as po_line_po_client,
    f.value:po_line:po:terms::VARCHAR as po_line_po_terms,
    f.value:po_line:po:buyer:name::VARCHAR as po_line_po_buyer_name,
    f.value:po_line:po:buyer:description::VARCHAR as po_line_po_buyer_description,
    f.value:po_line:po:buyer:address_line1::VARCHAR as po_buyer_address_line1,
    f.value:po_line:po:buyer:address_line2::VARCHAR as po_buyer_address_line2,
    f.value:po_line:po:buyer:zipcode::VARCHAR as po_buyer_zipcode,
    f.value:po_line:po:buyer:banner::VARCHAR as po_buyer_banner,
    f.value:po_line:po:buyer:erp_business_id::VARCHAR as po_buyer_erp_business_id,
    f.value:po_line:po:buyer:auto_inspect::VARCHAR as po_buyer_auto_inspect,
    f.value:po_line:po:buyer:city::VARCHAR as po_buyer_city,
    f.value:po_line:po:buyer:state::VARCHAR as po_buyer_state,
    f.value:po_line:po:buyer:country::VARCHAR as po_buyer_country,
    f.value:po_line:po:buyer:unit_number::VARCHAR as po_buyer_unit_number,
    f.value:po_line:po:buyer:contact_name::VARCHAR as po_buyer_contact_name,
    f.value:po_line:po:buyer:contact_number::VARCHAR as po_buyer_contact_number,
    f.value:po_line:po:buyer:id::NUMBER as po_buyer_id,
    f.value:po_line:po:buyer:other_codes::VARCHAR as po_buyer_other_codes,
    f.value:po_line:po:buyer:un_locode::VARCHAR as po_buyer_un_locode,
    f.value:po_line:po:store::VARCHAR as po_store,
    f.value:po_line:po:tier2::VARCHAR as po_tier2,
    f.value:po_line:po:merchandiser_user::VARCHAR as po_merchandiser_user,
    f.value:po_line:po:type::VARCHAR as po_type,
    f.value:po_line:po:factory:name::VARCHAR as po_line_po_factory_name,
    f.value:po_line:po:factory:description::VARCHAR as po_line_po_factory_description,
    f.value:po_line:po:factory:address_line1::VARCHAR as po_factory_address_line1,
    f.value:po_line:po:factory:address_line2::VARCHAR as po_factory_address_line2,
    f.value:po_line:po:factory:zipcode::VARCHAR as po_factory_zipcode,
    f.value:po_line:po:factory:banner::VARCHAR as po_factory_banner,
    f.value:po_line:po:factory:erp_business_id::VARCHAR as po_factory_erp_business_id,
    f.value:po_line:po:factory:auto_inspect::VARCHAR as po_factory_auto_inspect,
    f.value:po_line:po:factory:city::VARCHAR as po_factory_city,
    f.value:po_line:po:factory:state::VARCHAR as po_factory_state,
    f.value:po_line:po:factory:country::VARCHAR as po_factory_country,
    f.value:po_line:po:factory:unit_number::VARCHAR as po_factory_unit_number,
    f.value:po_line:po:factory:contact_name::VARCHAR as po_factory_contact_name,
    f.value:po_line:po:factory:contact_number::VARCHAR as po_factory_contact_number,
    f.value:po_line:po:factory:id::NUMBER as po_factory_id,
    f.value:po_line:po:factory:other_codes::VARCHAR as po_factory_other_codes,
    f.value:po_line:po:factory:un_locode::VARCHAR as po_factory_un_locode,
    f.value:po_line:po:distribution_center::VARCHAR as po_distribution_center,
    f.value:po_line:po:po_status::VARCHAR as po_status,
    f.value:po_line:sku:sku_attribute1::VARCHAR as po_sku_attribute1,
    f.value:po_line:sku:sku_attribute2::VARCHAR as po_sku_attribute2,
    f.value:po_line:sku:sku_attribute3::VARCHAR as po_sku_attribute3,
    f.value:po_line:sku:sku_attribute4::VARCHAR as po_sku_attribute4,
    f.value:po_line:sku:sku_attribute5::VARCHAR as po_sku_attribute5,
    f.value:po_line:sku:item_name::VARCHAR as po_item_name,
    f.value:po_line:sku:sku_number::VARCHAR as po_sku_number,
    f.value:po_line:sku:serial_number::VARCHAR as po_sku_serial_number,
    f.value:po_line:sku:cost::VARCHAR as po_sku_cost,
    f.value:po_line:sku:price::VARCHAR as po_sku_price,
    f.value:po_line:sku:product_family::VARCHAR as po_sku_product_family,
    f.value:po_line:sku:other_codes::VARCHAR as po_sku_other_codes,
    f.value:po_line:sku:item_description::VARCHAR as po_sku_item_description,
    f.value:po_line:sku:material_types::VARCHAR as po_sku_material_types,
    f.value:po_line:sku:recycled::VARCHAR as po_sku_recycled,
    f.value:po_line:sku:id::NUMBER as po_sku_id,
    f.value:po_line:sku:sku_ref_sheet::VARCHAR as po_sku_sku_ref_sheet,
    f.value:po_line:sku:retail_price::VARCHAR as po_sku_retail_price,
    f.value:po_line:sku:model_number::VARCHAR as po_sku_model_number,
    f.value:po_line:unit::VARCHAR as po_unit,
    f.value:po_line:merchandiser::VARCHAR as po_merchandiser,
    f.value:po_line:manager::VARCHAR as po_manager,
    f.value:po_line:season::VARCHAR as po_season,
    f.value:po_line:packaging_type::VARCHAR as po_packaging_type,
    f.value:po_line:master_carton_qty::NUMBER as po_master_carton_qty,
    f.value:po_line:inner_pack_qty::NUMBER as po_inner_pack_qty,
    f.value:po_line:lot_number::VARCHAR as po_lot_number,
    f.value:po_line:bom_version::VARCHAR as po_bom_version,
    f.value:po_line:date_code::VARCHAR as po_date_code,
    f.value:po_line:port_of_loading::VARCHAR as po_port_of_loading,
    f.value:po_line:port_of_arrival::VARCHAR as po_port_of_arrival,
    f.value:po_line:ship_mode::VARCHAR as po_ship_mode,
    f.value:po_line:currency::VARCHAR as po_currency,
    f.value:po_line:department::VARCHAR as po_department,
    f.value:po_line:child_po_lines::VARIANT as po_child_po_lines,
    f.value:po_line:business_unit::VARCHAR as po_business_unit,
    f.value:po_line:coalition::VARCHAR as po_coalition,
    f.value:po_line:region::VARCHAR as po_region,
    f.value:po_line:sourcing_office::VARCHAR as po_sourcing_office,
    f.value:po_line:sbu::VARCHAR as po_sbu,
    f.value:po_line:sub_sbu::VARCHAR as po_sub_sbu,
    f.value:po_line:source_system::VARCHAR as po_source_system,
    f.value:po_line:product_line::VARCHAR as po_product_line,
    f.value:po_line:purchasing_group::VARCHAR as po_purchasing_group,
    f.value:po_line:buy_season::VARCHAR as po_buy_season,
    f.value:po_line:disabled::BOOLEAN as po_disabled,
    f.value:po_line:no_inspection_required::BOOLEAN as po_no_inspection_required,
    f.value:po_line:date_no_inspection_required_modified::VARCHAR as po_date_no_inspection_required_modified,
    f.value:po_line:no_inspection_required_modified_by_id::VARCHAR as po_no_inspection_required_modified_by_id,
    f.value:po_line:unique_key::VARCHAR as po_unique_key
FROM lake.pivot88.inspections i,
    lateral flatten(input => i.assignments_items) f;
