CREATE OR REPLACE VIEW reporting_prod.shared.sessions_by_platform_new AS
SELECT session_local_datetime,
       session_date,
       session_month_date,
       session_store_id,
       store_type,
       store_brand_name,
       store_brand_abbr,
       store_region_abbr,
       store_country_abbr,
       store_name,
       store_group,
       is_mobile_app_store,
       customer_id,
       visitor_id,
       session_id,
       session_platform,
       raw_device,
       operating_system,
       browser,
       membership_state,
       customer_gender,
       is_atb_action,
       monthly_vip_tenure,
       daily_lead_tenure,
       is_lead_registration_action,
       registration_local_datetime,
       is_skip_month_action,
       channel,
       subchannel,
       channel_adj,
       subchannel_adj,
       is_bot,
       is_test_customer_account,
       is_scrubs_gateway,
       is_scrubs_customer,
       is_scrubs_action,
       is_scrubs_session,
       is_in_segment,
       referrer,
       is_paid_media,
       user_segment,
       meta_create_datetime,
       meta_update_datetime
FROM reporting_prod.shared.sessions_by_platform_stg
WHERE store_type <> 'Retail'
  AND is_test_customer_account = FALSE
  AND is_in_segment = TRUE
  AND is_bot = FALSE;
