from include.airflow.operators.mssql_acquisition import HighWatermarkMaxRowVersion
from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='um_replicated',
    schema='dbo',
    table='ultracms__test_framework__all',
    watermark_column='repl_timestamp',
    initial_load_value='0x0',
    high_watermark_cls=HighWatermarkMaxRowVersion,
    schema_version_prefix='v2',
    column_list=[
        Column('test_framework_id', 'INT'),
        Column('store_group_id', 'INT'),
        Column('label', 'VARCHAR(200)'),
        Column('start_date', 'DATE'),
        Column('end_date', 'DATE'),
        Column('start_time', 'TIME'),
        Column('end_time', 'TIME'),
        Column('type', 'VARCHAR(25)'),
        Column('campaign_code', 'VARCHAR(100)'),
        Column('code', 'VARCHAR(100)'),
        Column('code_mobile', 'VARCHAR(100)'),
        Column('statuscode', 'INT'),
        Column('customer_bucket_group_from', 'INT'),
        Column('customer_bucket_group_to', 'INT'),
        Column('always_on', 'INT'),
        Column('test_framework_group_id', 'INT'),
        Column('test_framework_group_id_mobile', 'INT'),
        Column('locale', 'VARCHAR(100)'),
        Column('membership_level', 'VARCHAR(100)'),
        Column('test_framework_xfa_id', 'INT'),
        Column('test_framework_xfa_other', 'VARCHAR(50)'),
        Column('persistent', 'BOOLEAN'),
        Column('cohort_split', 'VARCHAR(50)'),
        Column('weight', 'INT'),
        Column('membership_detail', 'VARCHAR(50)'),
        Column('session_detail', 'VARCHAR(50)'),
        Column('detail_value', 'VARCHAR(50)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('test_framework_desktopgroup_other', 'VARCHAR(100)'),
        Column('test_framework_mobilegroup_other', 'VARCHAR(100)'),
        Column('test_framework_ticket_url', 'VARCHAR(200)'),
        Column('test_framework_description', 'VARCHAR(200)'),
        Column('developer_defined', 'VARCHAR(50)'),
        Column('funnel', 'VARCHAR(100)'),
        Column('lead_day', 'VARCHAR(20)'),
        Column('administrator_id', 'INT'),
        Column('last_modified_administrator_id', 'INT'),
        Column('"GROUP"', 'VARCHAR(100)', source_name='[group]'),
        Column('membership_trial_status', 'VARCHAR(100)'),
        Column('membership_renewal_status', 'VARCHAR(100)'),
        Column('membership_type_id_list', 'VARCHAR(50)'),
        Column('is_fields_updated', 'INT'),
        Column('code_mobileapp', 'VARCHAR(100)'),
        Column('test_framework_group_id_mobileapp', 'INT'),
        Column('test_framework_mobileappgroup_other', 'VARCHAR(100)'),
        Column('repl_action', 'VARCHAR(1)'),
        Column('repl_timestamp', 'BINARY(8)', uniqueness=True),
    ],
)
