INSERT INTO lake_history.workday.employee_history_last6months (
    employee_id,
    first_name,
    last_name,
    preferred_first_name,
    preferred_last_name,
    business_title,
    worker_title,
    status,
    manager,
    company,
    brand,
    cost_center,
    email,
    start_date,
    termination_date,
    location,
    mgmlevel01,
    mgmlevel02,
    mgmlevel03,
    mgmlevel04,
    mgmlevel05,
    mgmlevel06,
    mgmlevel07,
    updated_at,
    source_meta_create_datetime,
    source_meta_update_datetime,
    source_meta_row_hash,
    meta_create_datetime,
    meta_update_datetime
)
SELECT
    employee_id,
    first_name,
    last_name,
    preferred_first_name,
    preferred_last_name,
    business_title,
    worker_title,
    status,
    manager,
    company,
    brand,
    cost_center,
    email,
    start_date,
    termination_date,
    location,
    mgmlevel01,
    mgmlevel02,
    mgmlevel03,
    mgmlevel04,
    mgmlevel05,
    mgmlevel06,
    mgmlevel07,
    updated_at,
    meta_create_datetime AS source_meta_create_datetime,
    meta_update_datetime AS source_meta_update_datetime,
    meta_row_hash AS source_meta_row_hash,
    CURRENT_TIMESTAMP() AS meta_create_datetime,
    CURRENT_TIMESTAMP() AS meta_update_datetime
FROM lake.workday.employees;

DELETE FROM lake_history.workday.employee_history_last6months
WHERE meta_update_datetime < CURRENT_DATE() - 182;
