CREATE TABLE EDW.META_TABLE_DEPENDENCY_WATERMARK_PROC_LOG(
TABLE_NAME VARCHAR(255),
WATERMARK_VALUE TIMESTAMP_LTZ(9),
USER_NAME VARCHAR(255),
META_CREATE_DATETIME TIMESTAMP_LTZ(9),
META_UPDATE_DATETIME TIMESTAMP_LTZ(9)
);
