from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultracms',
    schema='dbo',
    schema_version_prefix='v3',
    table='ui_promo_management_promos',
    watermark_column='datetime_modified',
    column_list=[
        Column('ui_promo_management_promo_id', 'INT', uniqueness=True),
        Column('promo_name', 'VARCHAR(200)'),
        Column('ui_promo_management_campaign_id', 'INT'),
        Column('promo_type_id', 'INT'),
        Column('store_group_id', 'INT'),
        Column('short_label', 'VARCHAR(50)'),
        Column('long_label', 'VARCHAR(255)'),
        Column('start_date', 'DATE'),
        Column('start_time', 'TIME'),
        Column('end_date', 'DATE'),
        Column('end_time', 'TIME'),
        Column('ongoing_promotion', 'INT'),
        Column('code', 'VARCHAR(255)'),
        Column('statuscode', 'INT'),
        Column('administrator_id', 'INT'),
        Column('promo_id', 'INT'),
        Column('is_active', 'INT', source_name='IsActive'),
        Column('setup_json', 'VARCHAR', source_name='setup_JSON'),
        Column('target_user_json', 'VARCHAR', source_name='target_user_JSON'),
        Column('qualifications_json', 'VARCHAR', source_name='qualifications_JSON'),
        Column('benefits_json', 'VARCHAR', source_name='benefits_JSON'),
        Column('additional_settings_json', 'VARCHAR', source_name='additional_settings_JSON'),
        Column('delivery_method_json', 'VARCHAR', source_name='delivery_method_JSON'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('display_settings_json', 'VARCHAR', source_name='display_settings_JSON'),
    ],
)
