from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='jf_portal',
    schema='dbo',
    table='PoHdr',
    is_full_upsert=True,
    enable_archive=True,
    schema_version_prefix='v6',
    column_list=[
        Column('po_id', 'INT', uniqueness=True, source_name='PoId'),
        Column('pr_id', 'INT', source_name='PrId'),
        Column('po_number', 'VARCHAR(17)', source_name='PoNumber'),
        Column('division_id', 'VARCHAR(15)', source_name='DivisionId'),
        Column('region_id', 'VARCHAR(2)', source_name='RegionId'),
        Column('shipping_port_id', 'INT', source_name='ShippingPortId'),
        Column('freight_method_id', 'INT', source_name='FreightMethodId'),
        Column('warehouse_id', 'INT', source_name='WarehouseId'),
        Column('date_launch', 'DATE', source_name='DateLaunch'),
        Column('date_start', 'DATE', source_name='DateStart'),
        Column('date_end', 'DATE', source_name='DateEnd'),
        Column('show_room', 'VARCHAR(20)', source_name='ShowRoom'),
        Column('vend_name', 'VARCHAR(65)', source_name='VendName'),
        Column('plm_vendor_id', 'VARCHAR(15)', source_name='PlmVendorId'),
        Column('vendor_id', 'VARCHAR(15)', source_name='VendorId'),
        Column('vendor_email', 'VARCHAR(500)', source_name='VendorEmail'),
        Column('qty_req', 'INT', source_name='QtyReq'),
        Column('priority', 'INT', source_name='Priority'),
        Column('vendor_comments', 'VARCHAR', source_name='VendorComments'),
        Column('cancel_reason', 'VARCHAR(500)', source_name='CancelReason'),
        Column('po_status_id', 'INT', source_name='PoStatusId'),
        Column('user_create', 'VARCHAR(100)', source_name='UserCreate'),
        Column('user_update', 'VARCHAR(100)', source_name='UserUpdate'),
        Column('date_create', 'TIMESTAMP_NTZ(3)', delta_column=1, source_name='DateCreate'),
        Column('date_update', 'TIMESTAMP_NTZ(3)', delta_column=0, source_name='DateUpdate'),
        Column('legacy', 'BOOLEAN'),
        Column('doc_date', 'TIMESTAMP_NTZ(3)', source_name='DocDate'),
        Column('curncyid', 'VARCHAR(15)', source_name='CURNCYID'),
        Column('inter_id', 'VARCHAR(15)', source_name='InterID'),
        Column('country_origin', 'VARCHAR(2)', source_name='CountryOrigin'),
        Column('state_origin', 'VARCHAR(2)', source_name='StateOrigin'),
        Column('gender', 'VARCHAR(7)', source_name='Gender'),
        Column('inco_term_id', 'INT', source_name='IncoTermId'),
        Column('pr_series_id', 'INT', source_name='PrSeriesId'),
        Column('version', 'INT', source_name='Version'),
        Column('executive_chg_appr', 'VARCHAR(100)', source_name='ExecutiveChgAppr'),
        Column('date_executive_chg_appr', 'TIMESTAMP_NTZ(3)', source_name='DateExecutiveChgAppr'),
        Column('executive_chg_reject', 'VARCHAR(100)', source_name='ExecutiveChgReject'),
        Column(
            'date_executive_chg_reject', 'TIMESTAMP_NTZ(3)', source_name='DateExecutiveChgReject'
        ),
        Column('gp_status', 'INT', source_name='GpStatus'),
        Column('buyer', 'VARCHAR(30)', source_name='Buyer'),
        Column('plm_id_style', 'INT', source_name='PLM_id_style'),
        Column('po_source_id', 'INT', source_name='PoSourceId'),
        Column('re_order_po_id', 'INT', source_name='ReOrderPoId'),
        Column('department', 'VARCHAR(50)', source_name='Department'),
        Column('vendor_confirm', 'BOOLEAN', source_name='VendorConfirm'),
        Column('guid', 'VARCHAR(36)', source_name='GUID'),
        Column('re_order_po_num', 'VARCHAR(17)', source_name='ReOrderPoNum'),
        Column('direct', 'VARCHAR(50)', source_name='Direct'),
        Column('mv2_planstyleoid', 'INT', source_name='MV2_PlanStyleOid'),
        Column('is_cmt', 'BOOLEAN', source_name='IsCMT'),
        Column('oracle_po_number', 'VARCHAR(17)', source_name='OraclePONumber'),
        Column('vendor_factory', 'INT', source_name='VendorFactory'),
        Column('split_from_po_id', 'INT', source_name='SplitFromPoID'),
        Column('is_retail', 'BOOLEAN', source_name='IsRetail'),
        Column('warehouse_origin', 'INT', source_name='WarehouseOrigin'),
        Column('mv2_vendoroid', 'INT', source_name='Mv2_VendorOid'),
        Column('warehouse_origin_overwriten', 'BOOLEAN', source_name='WarehouseOriginOverwriten'),
        Column('detail_date_update', 'TIMESTAMP_NTZ(3)', source_name='DetailDateUpdate'),
        Column('wholesaler_id', 'INT', source_name='WholesalerId'),
        Column('req_num', 'VARCHAR(100)', source_name='ReqNum'),
        Column('pay_term_id', 'INT', source_name='PayTermId'),
        Column('source_vend_name', 'VARCHAR(65)', source_name='SourceVendName'),
        Column('source_vendor_id', 'VARCHAR(15)', source_name='SourceVendorId'),
        Column('plm_id_devstyle', 'INT', source_name='PLM_id_devstyle'),
        Column('plm_andromeda_poid', 'INT', source_name='PLMAndromedaPOID'),
        Column('has_unbreakable_sets', 'BOOLEAN', source_name='HasUnbreakableSets'),
        Column('buying_rank', 'VARCHAR(2)', source_name='BuyingRank'),
        Column('po_type_id', 'INT', source_name='PoTypeId'),
        Column('po_vendor_type_id', 'INT', source_name='PoVendorTypeId'),
        Column('sub_department', 'VARCHAR(100)', source_name='SubDepartment'),
        Column('is_freight_cost_overwritten', 'BOOLEAN', source_name='IsFreightCostOverwritten'),
        Column('carrier', 'VARCHAR(255)', source_name='Carrier'),
        Column('tracking_no', 'VARCHAR(80)', source_name='TrackingNo'),
        Column('centric_style_id', 'VARCHAR(50)', source_name='CentricStyleId'),
        Column(
            'centric_price_list_revision_id',
            'VARCHAR(50)',
            source_name='CentricPriceListRevisionId',
        ),
        Column('initial_show_room', 'VARCHAR(20)', source_name='InitialShowRoom'),
        Column('initial_show_room_locked', 'BOOLEAN', source_name='InitialShowRoomLocked'),
    ],
)
