USE ROLE DA_TASKADMIN_WH;
USE DATABASE UTIL;
USE SCHEMA PUBLIC;
CREATE OR REPLACE TASK TASK_SCALE_UP_DA_WH_ETL
  SCHEDULE = 'USING CRON 30 3 * * * America/Los_Angeles'
  WAREHOUSE = 'DA_WH_ETL'
  TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD HH24'
AS
ALTER WAREHOUSE DA_WH_ETL SET WAREHOUSE_SIZE=Small, MAX_CLUSTER_COUNT=5;
ALTER TASK TASK_SCALE_UP_DA_WH_ETL RESUME;
