-- Disabled as per request from Leadership team just before Cyber Week
USE ROLE DA_TASKADMIN_WH;
USE DATABASE UTIL;
USE SCHEMA PUBLIC;
CREATE OR REPLACE TASK TASK_SCALE_DOWN_DA_WH_ANALYTICS
  SCHEDULE = 'USING CRON 0 17 * * * America/Los_Angeles'
  WAREHOUSE = 'DA_WH_ANALYTICS'
  TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD HH24'
AS
ALTER WAREHOUSE DA_WH_ANALYTICS SET WAREHOUSE_SIZE=XSMALL, MAX_CLUSTER_COUNT=2;
ALTER TASK TASK_SCALE_DOWN_DA_WH_ANALYTICS RESUME;
