-- Disabled as per request from Leadership team just before Cyber Week
USE ROLE DA_TASKADMIN_WH;
USE DATABASE UTIL;
USE SCHEMA PUBLIC;
CREATE OR REPLACE TASK TASK_SCALE_UP_DA_WH_ANALYTICS
  SCHEDULE = 'USING CRON 0 6 * * 1,2,3,4,5 America/Los_Angeles'
  WAREHOUSE = 'DA_WH_ANALYTICS'
  TIMESTAMP_INPUT_FORMAT = 'YYYY-MM-DD HH24'
AS
ALTER WAREHOUSE DA_WH_ANALYTICS SET WAREHOUSE_SIZE=Small, MAX_CLUSTER_COUNT=3;
ALTER TASK TASK_SCALE_UP_DA_WH_ANALYTICS RESUME;
