CREATE OR REPLACE VIEW analytics_base.customer_lifetime_value_monthly (
    month_date,
    customer_id,
    meta_original_customer_id,
    activation_key,
    vip_store_id,
    first_activation_key,
    gender,
    store_id,
    finance_specialty_store,
    guest_cohort_month_date,
    vip_cohort_month_date,
    membership_type,
    membership_type_entering_month,
    is_bop_vip,
    is_reactivated_vip,
    is_cancel,
    is_cancel_before_6th,
    is_passive_cancel,
    is_skip,
    is_snooze,
    is_login,
    segment_activity,
    is_merch_purchaser,
    is_successful_billing,
    is_pending_billing,
    is_failed_billing,
    is_cross_promo,
    is_retail_vip,
    is_scrubs_customer,
    customer_action_category,
    product_order_count,
    online_product_order_count,
    retail_product_order_count,
    mobile_app_product_order_count,
    product_order_unit_count,
    online_product_order_unit_count,
    retail_product_order_unit_count,
    mobile_app_product_order_unit_count,
    product_order_subtotal_excl_tariff_amount,
    product_order_product_subtotal_amount,
    online_product_order_subtotal_excl_tariff_amount,
    retail_product_order_subtotal_excl_tariff_amount,
    mobile_app_product_order_subtotal_excl_tariff_amount,
    product_order_product_discount_amount,
    online_product_order_product_discount_amount,
    retail_product_order_product_discount_amount,
    mobile_app_product_order_product_discount_amount,
    product_order_shipping_revenue_amount,
    online_product_order_shipping_revenue_amount,
    retail_product_order_shipping_revenue_amount,
    mobile_app_product_order_shipping_revenue_amount,
    product_order_direct_cogs_amount,
    online_product_order_direct_cogs_amount,
    retail_product_order_direct_cogs_amount,
    mobile_app_product_order_direct_cogs_amount,
    product_order_selling_expenses_amount,
    online_product_order_selling_expenses_amount,
    retail_product_order_selling_expenses_amount,
    mobile_app_product_order_selling_expenses_amount,
    product_order_cash_refund_amount_and_chargeback_amount,
    online_product_order_cash_refund_chargeback_amount,
    retail_product_order_cash_refund_chargeback_amount,
    mobile_app_product_order_cash_refund_chargeback_amount,
    product_order_cash_credit_refund_amount,
    online_product_order_cash_credit_refund_amount,
    retail_product_order_cash_credit_refund_amount,
    mobile_app_product_order_cash_credit_refund_amount,
    product_order_reship_exchange_order_count,
    online_product_order_reship_exchange_order_count,
    retail_product_order_reship_exchange_order_count,
    mobile_app_product_order_reship_exchange_order_count,
    product_order_reship_exchange_unit_count,
    online_product_order_reship_exchange_unit_count,
    retail_product_order_reship_exchange_unit_count,
    mobile_app_product_order_reship_exchange_unit_count,
    product_order_reship_exchange_direct_cogs_amount,
    online_product_order_reship_exchange_direct_cogs_amount,
    retail_product_order_reship_exchange_direct_cogs_amount,
    mobile_app_product_order_reship_exchange_direct_cogs_amount,
    product_order_return_cogs_amount,
    online_product_order_return_cogs_amount,
    retail_product_order_return_cogs_amount,
    mobile_app_product_order_return_cogs_amount,
    product_order_return_unit_count,
    online_product_order_return_unit_count,
    retail_product_order_return_unit_count,
    mobile_app_product_order_return_unit_count,
    product_order_amount_to_pay,
    online_product_order_amount_to_pay,
    retail_product_order_amount_to_pay,
    mobile_app_product_order_amount_to_pay,
    product_gross_revenue_excl_shipping,
    online_product_gross_revenue_excl_shipping,
    retail_product_gross_revenue_excl_shipping,
    mobile_app_product_gross_revenue_excl_shipping,
    product_gross_revenue,
    online_product_gross_revenue,
    retail_product_gross_revenue,
    mobile_app_product_gross_revenue,
    product_net_revenue,
    online_product_net_revenue,
    retail_product_net_revenue,
    mobile_app_product_net_revenue,
    product_margin_pre_return,
    online_product_margin_pre_return,
    retail_product_margin_pre_return,
    mobile_app_product_margin_pre_return,
    product_margin_pre_return_excl_shipping,
    online_product_margin_pre_return_excl_shipping,
    retail_product_margin_pre_return_excl_shipping,
    mobile_app_product_margin_pre_return_excl_shipping,
    product_gross_profit,
    online_product_gross_profit,
    retail_product_gross_profit,
    mobile_app_product_gross_profit,
    product_variable_contribution_profit,
    online_product_variable_contribution_profit,
    retail_product_variable_contribution_profit,
    mobile_app_product_variable_contribution_profit,
    product_order_cash_gross_revenue_amount,
    online_product_order_cash_gross_revenue_amount,
    retail_product_order_cash_gross_revenue_amount,
    mobile_app_product_order_cash_gross_revenue_amount,
    product_order_cash_net_revenue,
    online_product_order_cash_net_revenue,
    retail_product_order_cash_net_revenue,
    mobile_app_product_order_cash_net_revenue,
    product_order_landed_product_cost_amount,
    online_product_order_landed_product_cost_amount,
    retail_product_order_landed_product_cost_amount,
    mobile_app_product_order_landed_product_cost_amount,
    product_order_cash_margin_pre_return,
    online_product_order_cash_margin_pre_return,
    retail_product_order_cash_margin_pre_return,
    mobile_app_product_order_cash_margin_pre_return,
    product_order_cash_gross_profit,
    online_product_order_cash_gross_profit,
    retail_product_order_cash_gross_profit,
    mobile_app_product_order_cash_gross_profit,
    billing_cash_gross_revenue,
    billing_cash_net_revenue,
    cash_gross_revenue,
    cash_net_revenue,
    cash_gross_profit,
    cash_variable_contribution_profit,
    monthly_billed_credit_cash_transaction_amount,
    membership_fee_cash_transaction_amount,
    gift_card_transaction_amount,
    legacy_credit_cash_transaction_amount,
    monthly_billed_credit_cash_refund_count,
    monthly_billed_credit_cash_refund_chargeback_amount,
    membership_fee_cash_refund_chargeback_amount,
    gift_card_cash_refund_chargeback_amount,
    legacy_credit_cash_refund_chargeback_amount,
    billed_cash_credit_issued_amount,
    billed_cash_credit_redeemed_amount,
    online_billed_cash_credit_redeemed_amount,
    retail_billed_cash_credit_redeemed_amount,
    mobile_billed_cash_credit_redeemed_amount,
    billed_cash_credit_cancelled_amount,
    billed_cash_credit_expired_amount,
    billed_cash_credit_issued_equivalent_count,
    billed_cash_credit_redeemed_same_month_amount,
    billed_cash_credit_redeemed_equivalent_count,
    billed_cash_credit_cancelled_equivalent_count,
    billed_cash_credit_expired_equivalent_count,
    refund_cash_credit_issued_amount,
    refund_cash_credit_redeemed_amount,
    refund_cash_credit_cancelled_amount,
    refund_cash_credit_expired_amount,
    other_cash_credit_issued_amount,
    other_cash_credit_redeemed_amount,
    other_cash_credit_cancelled_amount,
    other_cash_credit_expired_amount,
    noncash_credit_issued_amount,
    noncash_credit_cancelled_amount,
    noncash_credit_expired_amount,
    first_guest_product_margin_pre_return,
    cumulative_cash_gross_profit,
    cumulative_product_gross_profit,
    cumulative_cash_gross_profit_decile,
    cumulative_product_gross_profit_decile,
    product_order_count_with_credit_redemption,
    entering_month_unredeemed_credits_per_customer,
    meta_create_datetime,
    meta_update_datetime
    ) AS
SELECT
    c.month_date,
    c.customer_id,
    c.meta_original_customer_id,
    c.activation_key,
    c.vip_store_id,
    c.first_activation_key,
    c.gender,
    c.store_id,
    c.finance_specialty_store,
    c.guest_cohort_month_date,
    c.vip_cohort_month_date,
    c.membership_type,
    c.membership_type_entering_month,
    c.is_bop_vip,
    c.is_reactivated_vip,
    c.is_cancel,
    c.is_cancel_before_6th,
    c.is_passive_cancel,
    c.is_skip,
    c.is_snooze,
    c.is_login,
    c.segment_activity,
    c.is_merch_purchaser,
    c.is_successful_billing,
    c.is_pending_billing,
    c.is_failed_billing,
    c.is_cross_promo,
    c.is_retail_vip,
    c.is_scrubs_customer,
    c.customer_action_category,
    IFNULL(a.product_order_count, 0) AS product_order_count,
    IFNULL(a.online_product_order_count, 0) AS online_product_order_count,
    IFNULL(a.retail_product_order_count, 0) AS retail_product_order_count,
    IFNULL(a.mobile_app_product_order_count, 0) AS mobile_app_product_order_count,
    IFNULL(a.product_order_unit_count, 0) AS product_order_unit_count,
    IFNULL(a.online_product_order_unit_count, 0) AS online_product_order_unit_count,
    IFNULL(a.retail_product_order_unit_count, 0) AS retail_product_order_unit_count,
    IFNULL(a.mobile_app_product_order_unit_count, 0) AS mobile_app_product_order_unit_count,
    IFNULL(a.product_order_subtotal_excl_tariff_amount, 0) AS product_order_subtotal_excl_tariff_amount,
    IFNULL(a.product_order_product_subtotal_amount, 0) AS product_order_product_subtotal_amount,
    IFNULL(a.online_product_order_subtotal_excl_tariff_amount, 0) AS online_product_order_subtotal_excl_tariff_amount,
    IFNULL(a.retail_product_order_subtotal_excl_tariff_amount, 0) AS retail_product_order_subtotal_excl_tariff_amount,
    IFNULL(a.mobile_app_product_order_subtotal_excl_tariff_amount, 0) AS mobile_app_product_order_subtotal_excl_tariff_amount,
    IFNULL(a.product_order_product_discount_amount, 0) AS product_order_product_discount_amount,
    IFNULL(a.online_product_order_product_discount_amount, 0) AS online_product_order_product_discount_amount,
    IFNULL(a.retail_product_order_product_discount_amount, 0) AS retail_product_order_product_discount_amount,
    IFNULL(a.mobile_app_product_order_product_discount_amount, 0) AS mobile_app_product_order_product_discount_amount,
    IFNULL(a.product_order_shipping_revenue_amount, 0) AS product_order_shipping_revenue_amount,
    IFNULL(a.online_product_order_shipping_revenue_amount, 0) AS online_product_order_shipping_revenue_amount,
    IFNULL(a.retail_product_order_shipping_revenue_amount, 0) AS retail_product_order_shipping_revenue_amount,
    IFNULL(a.mobile_app_product_order_shipping_revenue_amount, 0) AS mobile_app_product_order_shipping_revenue_amount,
    IFNULL(a.product_order_direct_cogs_amount, 0) AS product_order_direct_cogs_amount,
    IFNULL(a.online_product_order_direct_cogs_amount, 0) AS online_product_order_direct_cogs_amount,
    IFNULL(a.retail_product_order_direct_cogs_amount, 0) AS retail_product_order_direct_cogs_amount,
    IFNULL(a.mobile_app_product_order_direct_cogs_amount, 0) AS mobile_app_product_order_direct_cogs_amount,
    IFNULL(a.product_order_selling_expenses_amount, 0) AS product_order_selling_expenses_amount,
    IFNULL(a.online_product_order_selling_expenses_amount, 0) AS online_product_order_selling_expenses_amount,
    IFNULL(a.retail_product_order_selling_expenses_amount, 0) AS retail_product_order_selling_expenses_amount,
    IFNULL(a.mobile_app_product_order_selling_expenses_amount, 0) AS mobile_app_product_order_selling_expenses_amount,
    IFNULL(a.product_order_cash_refund_amount_and_chargeback_amount, 0) AS product_order_cash_refund_amount_and_chargeback_amount,
    IFNULL(a.online_product_order_cash_refund_chargeback_amount, 0) AS online_product_order_cash_refund_chargeback_amount,
    IFNULL(a.retail_product_order_cash_refund_chargeback_amount, 0) AS retail_product_order_cash_refund_chargeback_amount,
    IFNULL(a.mobile_app_product_order_cash_refund_chargeback_amount, 0) AS mobile_app_product_order_cash_refund_chargeback_amount,
    IFNULL(a.product_order_cash_credit_refund_amount, 0) AS product_order_cash_credit_refund_amount,
    IFNULL(a.online_product_order_cash_credit_refund_amount, 0) AS online_product_order_cash_credit_refund_amount,
    IFNULL(a.retail_product_order_cash_credit_refund_amount, 0) AS retail_product_order_cash_credit_refund_amount,
    IFNULL(a.mobile_app_product_order_cash_credit_refund_amount, 0) AS mobile_app_product_order_cash_credit_refund_amount,
    IFNULL(a.product_order_reship_exchange_order_count, 0) AS product_order_reship_exchange_order_count,
    IFNULL(a.online_product_order_reship_exchange_order_count, 0) AS online_product_order_reship_exchange_order_count,
    IFNULL(a.retail_product_order_reship_exchange_order_count, 0) AS retail_product_order_reship_exchange_order_count,
    IFNULL(a.mobile_app_product_order_reship_exchange_order_count, 0) AS mobile_app_product_order_reship_exchange_order_count,
    IFNULL(a.product_order_reship_exchange_unit_count, 0) AS product_order_reship_exchange_unit_count,
    IFNULL(a.online_product_order_reship_exchange_unit_count, 0) AS online_product_order_reship_exchange_unit_count,
    IFNULL(a.retail_product_order_reship_exchange_unit_count, 0) AS retail_product_order_reship_exchange_unit_count,
    IFNULL(a.mobile_app_product_order_reship_exchange_unit_count, 0) AS mobile_app_product_order_reship_exchange_unit_count,
    IFNULL(a.product_order_reship_exchange_direct_cogs_amount, 0) AS product_order_reship_exchange_direct_cogs_amount,
    IFNULL(a.online_product_order_reship_exchange_direct_cogs_amount, 0) AS online_product_order_reship_exchange_direct_cogs_amount,
    IFNULL(a.retail_product_order_reship_exchange_direct_cogs_amount, 0) AS retail_product_order_reship_exchange_direct_cogs_amount,
    IFNULL(a.mobile_app_product_order_reship_exchange_direct_cogs_amount, 0) AS mobile_app_product_order_reship_exchange_direct_cogs_amount,
    IFNULL(a.product_order_return_cogs_amount, 0) AS product_order_return_cogs_amount,
    IFNULL(a.online_product_order_return_cogs_amount, 0) AS online_product_order_return_cogs_amount,
    IFNULL(a.retail_product_order_return_cogs_amount, 0) AS retail_product_order_return_cogs_amount,
    IFNULL(a.mobile_app_product_order_return_cogs_amount, 0) AS mobile_app_product_order_return_cogs_amount,
    IFNULL(a.product_order_return_unit_count, 0) AS product_order_return_unit_count,
    IFNULL(a.online_product_order_return_unit_count, 0) AS online_product_order_return_unit_count,
    IFNULL(a.retail_product_order_return_unit_count, 0) AS retail_product_order_return_unit_count,
    IFNULL(a.mobile_app_product_order_return_unit_count, 0) AS mobile_app_product_order_return_unit_count,
    IFNULL(a.product_order_amount_to_pay, 0) AS product_order_amount_to_pay,
    IFNULL(a.online_product_order_amount_to_pay, 0) AS online_product_order_amount_to_pay,
    IFNULL(a.retail_product_order_amount_to_pay, 0) AS retail_product_order_amount_to_pay,
    IFNULL(a.mobile_app_product_order_amount_to_pay, 0) AS mobile_app_product_order_amount_to_pay,
    IFNULL(a.product_gross_revenue_excl_shipping, 0) AS product_gross_revenue_excl_shipping,
    IFNULL(a.online_product_gross_revenue_excl_shipping, 0) AS online_product_gross_revenue_excl_shipping,
    IFNULL(a.retail_product_gross_revenue_excl_shipping, 0) AS retail_product_gross_revenue_excl_shipping,
    IFNULL(a.mobile_app_product_gross_revenue_excl_shipping, 0) AS mobile_app_product_gross_revenue_excl_shipping,
    IFNULL(a.product_gross_revenue, 0) AS product_gross_revenue,
    IFNULL(a.online_product_gross_revenue, 0) AS online_product_gross_revenue,
    IFNULL(a.retail_product_gross_revenue, 0) AS retail_product_gross_revenue,
    IFNULL(a.mobile_app_product_gross_revenue, 0) AS mobile_app_product_gross_revenue,
    IFNULL(a.product_net_revenue, 0) AS product_net_revenue,
    IFNULL(a.online_product_net_revenue, 0) AS online_product_net_revenue,
    IFNULL(a.retail_product_net_revenue, 0) AS retail_product_net_revenue,
    IFNULL(a.mobile_app_product_net_revenue, 0) AS mobile_app_product_net_revenue,
    IFNULL(a.product_margin_pre_return, 0) AS product_margin_pre_return,
    IFNULL(a.online_product_margin_pre_return, 0) AS online_product_margin_pre_return,
    IFNULL(a.retail_product_margin_pre_return, 0) AS retail_product_margin_pre_return,
    IFNULL(a.mobile_app_product_margin_pre_return, 0) AS mobile_app_product_margin_pre_return,
    IFNULL(a.product_margin_pre_return_excl_shipping, 0) AS product_margin_pre_return_excl_shipping,
    IFNULL(a.online_product_margin_pre_return_excl_shipping, 0) AS online_product_margin_pre_return_excl_shipping,
    IFNULL(a.retail_product_margin_pre_return_excl_shipping, 0) AS retail_product_margin_pre_return_excl_shipping,
    IFNULL(a.mobile_app_product_margin_pre_return_excl_shipping, 0) AS mobile_app_product_margin_pre_return_excl_shipping,
    IFNULL(a.product_gross_profit, 0) AS product_gross_profit,
    IFNULL(a.online_product_gross_profit, 0) AS online_product_gross_profit,
    IFNULL(a.retail_product_gross_profit, 0) AS retail_product_gross_profit,
    IFNULL(a.mobile_app_product_gross_profit, 0) AS mobile_app_product_gross_profit,
    IFNULL(a.product_variable_contribution_profit, 0) AS product_variable_contribution_profit,
    IFNULL(a.online_product_variable_contribution_profit, 0) AS online_product_variable_contribution_profit,
    IFNULL(a.retail_product_variable_contribution_profit, 0) AS retail_product_variable_contribution_profit,
    IFNULL(a.mobile_app_product_variable_contribution_profit, 0) AS mobile_app_product_variable_contribution_profit,
    IFNULL(a.product_order_cash_gross_revenue_amount, 0) AS product_order_cash_gross_revenue_amount,
    IFNULL(a.online_product_order_cash_gross_revenue_amount, 0) AS online_product_order_cash_gross_revenue_amount,
    IFNULL(a.retail_product_order_cash_gross_revenue_amount, 0) AS retail_product_order_cash_gross_revenue_amount,
    IFNULL(a.mobile_app_product_order_cash_gross_revenue_amount, 0) AS mobile_app_product_order_cash_gross_revenue_amount,
    IFNULL(a.product_order_cash_net_revenue, 0) AS product_order_cash_net_revenue,
    IFNULL(a.online_product_order_cash_net_revenue, 0) AS online_product_order_cash_net_revenue,
    IFNULL(a.retail_product_order_cash_net_revenue, 0) AS retail_product_order_cash_net_revenue,
    IFNULL(a.mobile_app_product_order_cash_net_revenue, 0) AS mobile_app_product_order_cash_net_revenue,
    IFNULL(a.product_order_landed_product_cost_amount, 0) AS product_order_landed_product_cost_amount,
    IFNULL(a.online_product_order_landed_product_cost_amount, 0) AS online_product_order_landed_product_cost_amount,
    IFNULL(a.retail_product_order_landed_product_cost_amount, 0) AS retail_product_order_landed_product_cost_amount,
    IFNULL(a.mobile_app_product_order_landed_product_cost_amount, 0) AS mobile_app_product_order_landed_product_cost_amount,
    IFNULL(a.product_order_cash_margin_pre_return, 0) AS product_order_cash_margin_pre_return,
    IFNULL(a.online_product_order_cash_margin_pre_return, 0) AS online_product_order_cash_margin_pre_return,
    IFNULL(a.retail_product_order_cash_margin_pre_return, 0) AS retail_product_order_cash_margin_pre_return,
    IFNULL(a.mobile_app_product_order_cash_margin_pre_return, 0) AS mobile_app_product_order_cash_margin_pre_return,
    IFNULL(a.product_order_cash_gross_profit, 0) AS product_order_cash_gross_profit,
    IFNULL(a.online_product_order_cash_gross_profit, 0) AS online_product_order_cash_gross_profit,
    IFNULL(a.retail_product_order_cash_gross_profit, 0) AS retail_product_order_cash_gross_profit,
    IFNULL(a.mobile_app_product_order_cash_gross_profit, 0) AS mobile_app_product_order_cash_gross_profit,
    IFNULL(a.billing_cash_gross_revenue, 0) AS billing_cash_gross_revenue,
    IFNULL(a.billing_cash_net_revenue, 0) AS billing_cash_net_revenue,
    IFNULL(a.cash_gross_revenue, 0) AS cash_gross_revenue,
    IFNULL(a.cash_net_revenue, 0) AS cash_net_revenue,
    IFNULL(a.cash_gross_profit, 0) AS cash_gross_profit,
    IFNULL(a.cash_variable_contribution_profit, 0) AS cash_variable_contribution_profit,
    IFNULL(a.monthly_billed_credit_cash_transaction_amount, 0) AS monthly_billed_credit_cash_transaction_amount,
    IFNULL(a.membership_fee_cash_transaction_amount, 0) AS membership_fee_cash_transaction_amount,
    IFNULL(a.gift_card_transaction_amount, 0) AS gift_card_transaction_amount,
    IFNULL(a.legacy_credit_cash_transaction_amount, 0) AS legacy_credit_cash_transaction_amount,
    IFNULL(a.monthly_billed_credit_cash_refund_count, 0) AS monthly_billed_credit_cash_refund_count,
    IFNULL(a.monthly_billed_credit_cash_refund_chargeback_amount, 0) AS monthly_billed_credit_cash_refund_chargeback_amount,
    IFNULL(a.membership_fee_cash_refund_chargeback_amount, 0) AS membership_fee_cash_refund_chargeback_amount,
    IFNULL(a.gift_card_cash_refund_chargeback_amount, 0) AS gift_card_cash_refund_chargeback_amount,
    IFNULL(a.legacy_credit_cash_refund_chargeback_amount, 0) AS legacy_credit_cash_refund_chargeback_amount,
    IFNULL(a.billed_cash_credit_issued_amount, 0) AS billed_cash_credit_issued_amount,
    IFNULL(a.billed_cash_credit_redeemed_amount, 0) AS billed_cash_credit_redeemed_amount,
    IFNULL(a.online_billed_cash_credit_redeemed_amount, 0) AS online_billed_cash_credit_redeemed_amount,
    IFNULL(a.retail_billed_cash_credit_redeemed_amount, 0) AS retail_billed_cash_credit_redeemed_amount,
    IFNULL(a.mobile_billed_cash_credit_redeemed_amount, 0) AS mobile_billed_cash_credit_redeemed_amount,
    IFNULL(a.billed_cash_credit_cancelled_amount, 0) AS billed_cash_credit_cancelled_amount,
    IFNULL(a.billed_cash_credit_expired_amount, 0) AS billed_cash_credit_expired_amount,
    IFNULL(a.billed_cash_credit_issued_equivalent_count, 0) AS billed_cash_credit_issued_equivalent_count,
    IFNULL(a.billed_cash_credit_redeemed_same_month_amount, 0) AS billed_cash_credit_redeemed_same_month_amount,
    IFNULL(a.billed_cash_credit_redeemed_equivalent_count, 0) AS billed_cash_credit_redeemed_equivalent_count,
    IFNULL(a.billed_cash_credit_cancelled_equivalent_count, 0) AS billed_cash_credit_cancelled_equivalent_count,
    IFNULL(a.billed_cash_credit_expired_equivalent_count, 0) AS billed_cash_credit_expired_equivalent_count,
    IFNULL(a.refund_cash_credit_issued_amount, 0) AS refund_cash_credit_issued_amount,
    IFNULL(a.refund_cash_credit_redeemed_amount, 0) AS refund_cash_credit_redeemed_amount,
    IFNULL(a.refund_cash_credit_cancelled_amount, 0) AS refund_cash_credit_cancelled_amount,
    IFNULL(a.refund_cash_credit_expired_amount, 0) AS refund_cash_credit_expired_amount,
    IFNULL(a.other_cash_credit_issued_amount, 0) AS other_cash_credit_issued_amount,
    IFNULL(a.other_cash_credit_redeemed_amount, 0) AS other_cash_credit_redeemed_amount,
    IFNULL(a.other_cash_credit_cancelled_amount, 0) AS other_cash_credit_cancelled_amount,
    IFNULL(a.other_cash_credit_expired_amount, 0) AS other_cash_credit_expired_amount,
    IFNULL(a.noncash_credit_issued_amount, 0) AS noncash_credit_issued_amount,
    IFNULL(a.noncash_credit_cancelled_amount, 0) AS noncash_credit_cancelled_amount,
    IFNULL(a.noncash_credit_expired_amount, 0) AS noncash_credit_expired_amount,
    IFNULL(a.first_guest_product_margin_pre_return, 0) AS first_guest_product_margin_pre_return,
    IFNULL(c.cumulative_cash_gross_profit, 0) AS cumulative_cash_gross_profit,
    IFNULL(c.cumulative_product_gross_profit, 0) AS cumulative_product_gross_profit,
    IFNULL(c.cumulative_cash_gross_profit_decile, 0) AS cumulative_cash_gross_profit_decile,
    IFNULL(c.cumulative_product_gross_profit_decile, 0) AS cumulative_product_gross_profit_decile,
    IFNULL(a.product_order_count_with_credit_redemption,0) AS product_order_count_with_credit_redemption,
    IFNULL(c.entering_month_unredeemed_credits_per_customer,0) AS entering_month_unredeemed_credits_per_customer,
    LEAST(COALESCE(c.meta_create_datetime, '9999-12-31'), COALESCE(a.meta_create_datetime, '9999-12-31')) AS meta_create_datetime,
    GREATEST(COALESCE(c.meta_update_datetime, '1900-01-01'), COALESCE(a.meta_update_datetime, '1900-01-01')) AS meta_update_datetime
FROM analytics_base.customer_lifetime_value_monthly_cust AS c
    LEFT JOIN analytics_base.customer_lifetime_value_monthly_agg AS a
        ON a.month_date = c.month_date
        AND a.customer_id = c.customer_id
        AND a.activation_key = c.activation_key
        AND a.vip_store_id = c.vip_store_id;
