CREATE OR REPLACE VIEW analytics_base.finance_sales_ops_dim_detail AS
SELECT fso.date
     , fso.date_object
     , fso.store_id
     , fso.customer_id
     , fso.activation_key
     , fso.first_activation_key
     , fso.associate_id
     , fso.order_membership_classification_key
     , fso.is_bop_vip
     , fso.currency_object
     , fso.currency_type
     , fso.vip_store_id
     , fso.is_cross_promo
     , fso.gender
     , fso.is_retail_vip
     , fso.is_reactivated_vip
     , fso.activation_local_datetime
     , fso.vip_cohort_month_date
     , fso.cancellation_local_datetime
     , fso.first_activation_local_datetime
     , fso.first_vip_cohort_month_date
     , fso.first_cancellation_local_datetime
     , fso.finance_specialty_store
     , fso.reporting_landed_cost_local_amount
     , fso.product_order_subtotal_excl_tariff_amount
     , fso.product_order_tariff_amount
     , fso.product_order_product_subtotal_amount
     , fso.product_order_product_discount_amount
     , fso.product_order_shipping_discount_amount
     , fso.product_order_shipping_revenue_before_discount_amount
     , fso.product_order_shipping_revenue_amount
     , fso.product_order_tax_amount
     , fso.product_order_cash_transaction_amount
     , fso.product_order_cash_credit_redeemed_amount
     , fso.product_order_noncash_credit_redeemed_amount
     , fso.product_order_count
     , fso.product_order_unit_count
     , fso.product_order_loyalty_unit_count
     , fso.product_order_outfit_component_unit_count
     , fso.product_order_outfit_count
     , fso.product_order_discounted_unit_count
     , fso.product_order_zero_revenue_unit_count
     , fso.product_order_landed_product_cost_amount
     , fso.product_order_shipping_cost_amount
     , fso.product_order_shipping_supplies_cost_amount
     , fso.product_order_misc_cogs_amount
     , fso.product_order_direct_cogs_amount
     , fso.product_order_cash_refund_amount
     , fso.product_order_cash_credit_refund_amount
     , fso.product_order_noncash_credit_refund_amount
     , fso.product_order_cash_chargeback_amount
     , fso.product_order_cost_product_returned_resaleable_amount
     , fso.product_order_cost_product_returned_damaged_amount
     , fso.product_order_return_shipping_cost_amount
     , fso.product_order_return_unit_count
     , fso.product_order_reship_order_count
     , fso.product_order_reship_unit_count
     , fso.product_order_reship_direct_cogs_amount
     , fso.product_order_reship_product_cost_amount
     , fso.product_order_reship_shipping_cost_amount
     , fso.product_order_reship_shipping_supplies_cost_amount
     , fso.product_order_exchange_order_count
     , fso.product_order_exchange_unit_count
     , fso.product_order_exchange_direct_cogs_amount
     , fso.product_order_exchange_product_cost_amount
     , fso.product_order_exchange_shipping_cost_amount
     , fso.product_order_exchange_shipping_supplies_cost_amount
     , fso.product_order_selling_expenses_amount
     , fso.product_order_payment_processing_cost_amount
     , fso.product_order_variable_gms_cost_amount
     , fso.product_order_variable_warehouse_cost_amount
     , fso.billing_selling_expenses_amount
     , fso.billing_payment_processing_cost_amount
     , fso.billing_variable_gms_cost_amount
     , fso.product_order_amount_to_pay
     , fso.product_gross_revenue_excl_shipping
     , fso.product_gross_revenue
     , fso.product_net_revenue
     , fso.product_margin_pre_return
     , fso.product_margin_pre_return_excl_shipping
     , fso.product_gross_profit
     , fso.product_variable_contribution_profit
     , fso.product_order_cash_gross_revenue_amount
     , fso.product_order_cash_net_revenue
     , fso.product_order_cash_margin_pre_return
     , fso.product_order_cash_gross_profit
     , fso.billing_cash_gross_revenue
     , fso.billing_cash_net_revenue
     , fso.cash_gross_revenue
     , fso.cash_net_revenue
     , fso.cash_gross_profit
     , fso.cash_variable_contribution_profit
     , fso.billing_order_transaction_count
     , fso.billed_credit_cash_transaction_count
     , fso.on_retry_billed_credit_cash_transaction_count
     , fso.billing_cash_refund_amount
     , fso.billing_cash_chargeback_amount
     , fso.billed_credit_cash_transaction_amount
     , fso.membership_fee_cash_transaction_amount
     , fso.gift_card_transaction_amount
     , fso.legacy_credit_cash_transaction_amount
     , fso.billed_credit_cash_refund_count
     , fso.billed_credit_cash_refund_chargeback_amount
     , fso.membership_fee_cash_refund_chargeback_amount
     , fso.gift_card_cash_refund_chargeback_amount
     , fso.legacy_credit_cash_refund_chargeback_amount
     , fso.billed_cash_credit_issued_amount
     , fso.billed_cash_credit_redeemed_amount
     , fso.billed_cash_credit_cancelled_amount
     , fso.billed_cash_credit_expired_amount
     , fso.billed_cash_credit_issued_equivalent_count
     , fso.billed_cash_credit_redeemed_same_month_amount
     , fso.billed_cash_credit_redeemed_equivalent_count
     , fso.billed_cash_credit_cancelled_equivalent_count
     , fso.billed_cash_credit_expired_equivalent_count
     , fso.refund_cash_credit_issued_amount
     , fso.refund_cash_credit_redeemed_amount
     , fso.refund_cash_credit_cancelled_amount
     , fso.refund_cash_credit_expired_amount
     , fso.other_cash_credit_issued_amount
     , fso.other_cash_credit_redeemed_amount
     , fso.other_cash_credit_cancelled_amount
     , fso.other_cash_credit_expired_amount
     , fso.noncash_credit_issued_amount
     , fso.noncash_credit_cancelled_amount
     , fso.noncash_credit_expired_amount
     , fso.cash_gift_card_redeemed_amount
     , fso.retail_ship_only_product_order_count
     , fso.retail_ship_only_product_order_unit_count
     , fso.retail_ship_only_product_gross_revenue
     , fso.retail_ship_only_product_gross_revenue_excl_shipping
     , fso.retail_ship_only_product_margin_pre_return
     , fso.retail_ship_only_product_margin_pre_return_excl_shipping
     , fso.retail_ship_only_product_order_cash_margin_pre_return
     , fso.retail_ship_only_product_order_cash_gross_revenue
     , fso.retail_ship_only_product_net_revenue
     , fso.retail_ship_only_product_gross_profit
     , fso.retail_ship_only_product_order_cash_net_revenue
     , fso.retail_ship_only_product_order_cash_gross_profit
     , fso.product_order_reship_exchange_cash_gross_revenue
     , fso.meta_row_hash
     , fso.meta_create_datetime
     , fso.meta_update_datetime
     , mc.membership_order_type_l1
     , mc.membership_order_type_l2
     , mc.membership_order_type_l3
     , mc.is_vip
     , ds.store_group
     , ds.store_name
     , ds.store_name_region
     , ds.store_full_name
     , ds.store_brand
     , ds.store_brand_abbr
     , ds.store_type
     , ds.store_sub_type
     , ds.store_country
     , ds.store_region
     , ds.store_division
     , ds.store_division_abbr
     , ds.store_currency
     , ds.store_time_zone
     , ds.store_retail_state
     , ds.store_retail_city
     , ds.store_retail_location
     , ds.store_retail_zip_code
FROM analytics_base.finance_sales_ops fso
         LEFT JOIN data_model.dim_order_membership_classification mc
                   ON fso.order_membership_classification_key = mc.order_membership_classification_key
         LEFT JOIN data_model.dim_store ds ON fso.store_id = ds.store_id;
