CREATE OR REPLACE VIEW data_model_sxf.fact_activation (
    activation_key,
    membership_event_key,
    store_id,
    customer_id,
    activation_local_datetime,
    next_activation_local_datetime,
    source_activation_local_datetime,
    source_next_activation_local_datetime,
    cancellation_local_datetime,
    is_reactivated_vip,
    order_id,
    session_id,
    activation_channel_type,
    activation_channel,
    activation_subchannel,
    vip_cohort_month_date,
    source_vip_cohort_month_date,
    membership_event_type,
    membership_type,
    is_vip_activation_from_reactivated_lead,
    dm_gateway_id,
    device,
    browser,
    operating_system,
    utm_medium,
    utm_source,
    utm_campaign,
    utm_content,
    utm_term,
    pcode,
    ccode,
    acode,
    scode,
    sub_store_id,
    store_type,
    store_sub_type,
    is_retail_vip,
    is_retail_varsity_vip,
    is_retail_legging_bar_vip,
    is_mobile_app_vip,
    is_legging_bar_vip,
    is_kiosk_vip,
    is_scrubs_vip,
    order_discount_percent,
    is_current,
    cancel_type,
    cancel_method,
    cancel_reason,
    activation_sequence_number,
    meta_create_datetime,
    meta_update_datetime
    )
AS
SELECT
    fa.activation_key,
    fa.membership_event_key,
    fa.store_id,
    stg.udf_unconcat_brand(fa.customer_id) AS customer_id,
    fa.activation_local_datetime,
    fa.next_activation_local_datetime,
    fa.source_activation_local_datetime,
    fa.source_next_activation_local_datetime,
    fa.cancellation_local_datetime,
    fa.is_reactivated_vip,
    stg.udf_unconcat_brand(fa.order_id) AS order_id,
    stg.udf_unconcat_brand(fa.session_id) AS session_id,
    fa.activation_channel_type,
    fa.activation_channel,
    fa.activation_subchannel,
    fa.vip_cohort_month_date,
    fa.source_vip_cohort_month_date,
    fa.membership_event_type,
    fa.membership_type,
    fa.is_vip_activation_from_reactivated_lead,
    fa.dm_gateway_id,
    fa.device,
    fa.browser,
    fa.operating_system,
    fa.utm_medium,
    fa.utm_source,
    fa.utm_campaign,
    fa.utm_content,
    fa.utm_term,
    fa.pcode,
    fa.ccode,
    fa.acode,
    fa.scode,
    fa.sub_store_id,
    dss.store_type,
    dss.store_sub_type,
    IFF(dss.store_brand IN ('Fabletics','Savage X') AND dss.store_type = 'Retail', TRUE, FALSE) AS is_retail_vip,
    IFF(dss.store_brand = 'Fabletics' AND dss.store_sub_type = 'Varsity', TRUE, FALSE) AS is_retail_varsity_vip,
    IFF(dss.store_brand = 'Fabletics' AND dss.store_type = 'Legging Bar', TRUE, FALSE) AS is_retail_legging_bar_vip,
    IFF(dss.store_type = 'Mobile App', TRUE, FALSE) AS is_mobile_app_vip,
    fa.is_legging_bar_vip,
    fa.is_kiosk_vip,
    fa.is_scrubs_vip,
    fa.order_discount_percent,
    fa.is_current,
    fa.cancel_type,
    fa.cancel_method,
    fa.cancel_reason,
    fa.activation_sequence_number,
    fa.meta_create_datetime,
    fa.meta_update_datetime
FROM stg.fact_activation AS fa
    LEFT JOIN stg.dim_store AS ds
        ON ds.store_id = fa.store_id
    LEFT JOIN stg.dim_store AS dss
        ON dss.store_id = fa.sub_store_id
WHERE NOT fa.is_deleted
    AND NOT NVL(fa.is_test_customer, FALSE)
    AND ds.store_brand NOT IN ('Legacy')
    AND (substring(fa.customer_id, -2) = '30'  OR fa.customer_id = -1);
