CREATE OR REPLACE VIEW data_model_fl.dim_credit AS
SELECT credit_key,
       store_id,
       stg.udf_unconcat_brand(credit_id) as credit_id,
       source_credit_id_type,
       administrator_id,
       stg.udf_unconcat_brand(customer_id) as customer_id,
       credit_report_mapping,
       credit_report_sub_mapping,
       credit_type,
       credit_tender,
       credit_reason,
       credit_issuance_reason,
       stg.udf_unconcat_brand(credit_order_id) as credit_order_id,
       credit_issued_hq_datetime,
       credit_issued_local_datetime,
       credit_expiration_local_datetime,
       original_credit_key,
       original_credit_tender,
       original_credit_type,
       original_credit_issued_local_datetime,
       original_credit_expiration_local_datetime,
       original_credit_reason,
       original_credit_match_reason,
       deferred_recognition_label_token,
       credit_issued_usd_conversion_rate,
       credit_issued_local_gross_vat_amount,
       credit_issued_equivalent_count,
       credit_issued_local_amount,
       is_bill_me_now_online,
       is_bill_me_now_gms,
       is_test_customer,
       meta_create_datetime,
       meta_update_datetime
FROM stg.dim_credit
WHERE is_test_customer = FALSE
    AND substring(credit_id, -2) = '20';
