CREATE OR REPLACE VIEW data_model_jfb.fact_credit_event
(
    credit_event_key,
    credit_key,
    credit_id,
    source_credit_id,
    customer_id,
    activation_key,
    first_activation_key,
    is_bop_vip,
    administrator_id,
    credit_activity_type,
    original_credit_activity_type_action,
    credit_activity_type_reason,
    credit_activity_local_datetime,
    credit_activity_source,
    credit_activity_source_reason,
    redemption_order_id,
    redemption_store_id,
    vat_rate_ship_to_country,
    credit_activity_vat_rate,
    credit_activity_usd_conversion_rate,
    credit_activity_equivalent_count,
    credit_activity_gross_vat_local_amount,
    credit_activity_local_amount,
    activity_amount_local_amount_issuance_date,
    is_current,
    meta_create_datetime,
    meta_update_datetime
) AS
SELECT
    credit_event_key,
    credit_key,
    stg.udf_unconcat_brand(credit_id) AS credit_id,
    stg.udf_unconcat_brand(source_credit_id) AS source_credit_id,
    stg.udf_unconcat_brand(customer_id) AS customer_id,
    activation_key,
    first_activation_key,
    is_bop_vip,
    administrator_id,
    credit_activity_type,
    original_credit_activity_type_action,
    credit_activity_type_reason,
    credit_activity_local_datetime,
    credit_activity_source,
    credit_activity_source_reason,
    stg.udf_unconcat_brand(redemption_order_id),
    redemption_store_id,
    vat_rate_ship_to_country,
    credit_activity_vat_rate,
    credit_activity_usd_conversion_rate,
    credit_activity_equivalent_count,
    credit_activity_gross_vat_local_amount,
    credit_activity_local_amount,
    activity_amount_local_amount_issuance_date,
    is_current,
    meta_create_datetime,
    meta_update_datetime
FROM stg.fact_credit_event
WHERE NOT is_deleted AND
      NOT NVL(is_test_customer,False)
        AND substring(credit_id, -2) = '10';
