CREATE OR REPLACE VIEW data_model_fl.fact_order_line_embroidery (
    order_line_id,
    embroidery_order_line_id,
    order_id,
    product_id,
    order_line_status_key,
    order_status_key,
    item_quantity,
    payment_transaction_local_amount,
    subtotal_excl_tariff_local_amount,
    tax_local_amount,
    tax_cash_local_amount,
    tax_credit_local_amount,
    product_discount_local_amount,
    cash_credit_local_amount,
    cash_membership_credit_local_amount,
    cash_refund_credit_local_amount,
    cash_giftco_credit_local_amount,
    cash_giftcard_credit_local_amount,
    non_cash_credit_local_amount,
    estimated_landed_cost_local_amount,
    reporting_landed_cost_local_amount,
    actual_landed_cost_local_amount,
    oracle_cost_local_amount,
    tariff_revenue_local_amount,
    price_offered_local_amount,
    bounceback_endowment_local_amount,
    vip_endowment_local_amount,
    air_vip_price,
    retail_unit_price,
    product_price_history_key,
    sub_group_key,
    meta_create_datetime,
    meta_update_datetime
) AS
SELECT
    stg.udf_unconcat_brand(order_line_id) AS order_line_id,
    stg.udf_unconcat_brand(embroidery_order_line_id) AS embroidery_order_line_id,
    stg.udf_unconcat_brand(order_id) AS order_id,
    stg.udf_unconcat_brand(product_id) AS product_id,
    order_line_status_key,
    order_status_key,
    item_quantity,
    payment_transaction_local_amount,
    subtotal_excl_tariff_local_amount,
    tax_local_amount,
    tax_cash_local_amount,
    tax_credit_local_amount,
    product_discount_local_amount,
    cash_credit_local_amount,
    cash_membership_credit_local_amount,
    cash_refund_credit_local_amount,
    cash_giftco_credit_local_amount,
    cash_giftcard_credit_local_amount,
    non_cash_credit_local_amount,
    estimated_landed_cost_local_amount,
    reporting_landed_cost_local_amount,
    actual_landed_cost_local_amount,
    oracle_cost_local_amount,
    tariff_revenue_local_amount,
    price_offered_local_amount,
    bounceback_endowment_local_amount,
    vip_endowment_local_amount,
    air_vip_price,
    retail_unit_price,
    product_price_history_key,
    sub_group_key,
    meta_create_datetime,
    meta_update_datetime
FROM stg.fact_order_line_embroidery
WHERE NOT is_deleted
  and not is_test_customer
  AND substring(order_id, -2) = '20';
