CREATE OR REPLACE VIEW reporting.failed_billings_final_output AS
SELECT month_date,
    CASE WHEN store_brand = 'Fabletics' AND gender = 'M' THEN 'Fabletics Men'
        WHEN store_brand = 'Fabletics' THEN 'Fabletics Women'
        ELSE store_brand END AS store_brand,
    store_region,
    store_country,
    store_full_name,
    vip_tenure,
    is_login,
    is_first_failed_billing,
    is_failed_prior_month,
    opened_an_email,
    clicked_an_email,
    consecutive_failed_billings,
    months_since_last_successful_billing,
    number_of_failed_billings_in_last_12_months,
    months_since_last_skip,
    number_of_skips_in_last_12_months,
    months_since_last_login,
    number_of_visits_in_last_12_months,
    months_since_last_email_open,
    months_since_last_email_click,
    months_since_last_successful_order,
    COUNT(DISTINCT customer_id) AS customer_count,
    SUM(number_of_email_opens) AS number_of_email_opens,
    SUM(number_of_email_clicks) AS number_of_email_clicks,
    MAX(meta_create_datetime) AS meta_create_datetime,
    MAX(meta_update_datetime) AS meta_update_datetime
FROM analytics_base.customer_failed_billings_monthly
GROUP BY month_date,
    CASE WHEN store_brand = 'Fabletics' AND gender = 'M' THEN 'Fabletics Men'
        WHEN store_brand = 'Fabletics' THEN 'Fabletics Women'
        ELSE store_brand END,
    store_region,
    store_country,
    store_full_name,
    vip_tenure,
    is_login,
    is_first_failed_billing,
    is_failed_prior_month,
    opened_an_email,
    clicked_an_email,
    consecutive_failed_billings,
    months_since_last_successful_billing,
    number_of_failed_billings_in_last_12_months,
    months_since_last_skip,
    number_of_skips_in_last_12_months,
    months_since_last_login,
    number_of_visits_in_last_12_months,
    months_since_last_email_open,
    months_since_last_email_click,
    months_since_last_successful_order;
