CREATE OR REPLACE VIEW reporting.amz_settlement(
    settlement_id,
    settlement_start_pst_datetime,
    settlement_end_pst_datetime,
    deposit_local_datetime,
    settlement_total_amount,
    currency,
    transaction_type,
    order_id,
    shipment_id,
    marketplace_name,
    posted_local_date,
    posted_local_datetime,
    posted_pst_date,
    posted_pst_datetime,
    sku,
    quantity_purchased,
    order_line_id,
    item_price,
    item_witheld_tax,
    promotion,
    item_fees,
    cost_of_advertising,
    other_transaction,
    total_amount,
    tfg_reporting_landed_cost,
    tfg_po_cost,
    tfg_cmt_cost,
    tfg_commission_inspection_cost,
    tfg_duty_tariff_cost,
    tfg_freight_cost,
    tfg_cross_border_duty_cost,
    tfg_cross_border_other_cost,
    meta_create_datetime,
    meta_update_datetime
)
AS
(
SELECT settlement_id,
       CONVERT_TIMEZONE('America/Los_Angeles', 'UTC',
                        settlement_start_local_datetime::TIMESTAMP_NTZ) AS settlement_start_pst_datetime,
       CONVERT_TIMEZONE('America/Los_Angeles', 'UTC',
                        settlement_end_local_datetime::TIMESTAMP_NTZ)   AS settlement_end_pst_datetime,
       deposit_local_datetime,
       settlement_total_amount,
       currency,
       transaction_type,
       order_id,
       shipment_id,
       marketplace_name,
       posted_local_date,
       posted_local_datetime,
       posted_pst_date,
       posted_pst_datetime,
       sku,
       quantity_purchased,
       order_line_id,
       item_price,
       item_witheld_tax,
       promotion,
       item_fees,
       cost_of_advertising,
       other_transaction,
       total_amount,
       tfg_reporting_landed_cost,
       tfg_po_cost,
       tfg_cmt_cost,
       tfg_commission_inspection_cost,
       tfg_duty_tariff_cost,
       tfg_freight_cost,
       tfg_cross_border_duty_cost,
       tfg_cross_border_other_cost,
       meta_create_datetime,
       meta_update_datetime
FROM dbt_edw_prod.reporting.amz_settlement
    );
