CREATE
OR REPLACE VIEW reporting.daily_cash_tableau_comparison AS
WITH _metric_name_lookup AS (
    SELECT *
    FROM (VALUES ('cash_gross_revenue', 'Cash Gross Revenue'),
                 ('cash_net_revenue', 'Cash Net Revenue'),
                 ('cash_gross_profit', 'Cash Gross Profit'),
                 ('cash_gross_profit_percent_of_net_cash', 'Cash Gross Profit % of Net Cash'),
                 ('cash_net_revenue_with_budgeted_fx_rates', 'Cash Net Revenue with Budgeted FX Rates'),
                 ('activating_cash_gross_revenue', 'Activating Cash Gross Revenue'),
                 ('activating_cash_net_revenue', 'Activating Cash Net Revenue'),
                 ('nonactivating_cash_gross_revenue', 'NonActivating Cash Gross Revenue'),
                 ('nonactivating_cash_net_revenue', 'NonActivating Cash Net Revenue'),
                 ('product_order_and_billing_cash_refund', 'Product Order And Billing Cash Refund'),
                 ('product_order_and_billing_chargebacks', 'Product Order And Billing Chargebacks'),
                 ('refund_chargebacks_as_percent_of_cash_gross_rev', 'Refunds + Chargebacks as % of Cash Gross Rev'),
                 ('activating_product_gross_revenue', 'Activating Product Gross Revenue'),
                 ('activating_product_net_revenue', 'Activating Product Net Revenue'),
                 ('activating_shipping_revenue', 'Activating Shipping Revenue'),
                 ('activating_product_order_count', 'Activating Product Order Count'),
                 ('activating_product_order_count_excl_seeding', 'Activating Product Order Count Excl Seeding'),
                 ('activating_product_margin_pre_return_excl_seeding', 'Activating Product Margin Pre Return Excl Seeding'),
                 ('activating_aov', 'Activating AOV'),
                 ('activating_unit_count', 'Activating Unit Count'),
                 ('activating_upt', 'Activating UPT'),
                 ('activating_aur', 'Activating AUR'),
                 ('activating_auc_incl_reship_exch', 'Activating AUC Incl. Reship/Exch'),
                 ('activating_discount_percent', 'Activating Discount %'),
                 ('planning_activating_discount_percent', 'Planning Activating Discount %'),
                 ('activating_product_gross_profit', 'Activating Product Gross Profit'),
                 ('activating_product_gross_profit_per_order', 'Activating Product Gross Profit Per Order'),
                 ('activating_product_gross_profit_percent', 'Activating Product Gross Profit %'),
                 ('activating_product_order_cash_gross_revenue', 'Activating Product Order Cash Gross Revenue'),
                 ('activating_product_margin_pre_return', 'Activating Product Margin Pre Return'),
                 ('activating_product_margin_pre_return_per_order', 'Activating Product Margin Pre Return Per Order'),
                 ('activating_product_margin_pre_return_percent', 'Activating Product Margin Pre Return %'),
                 ('nonactivating_product_gross_revenue', 'NonActivating Product Gross Revenue'),
                 ('nonactivating_product_net_revenue', 'NonActivating Product Net Revenue'),
                 ('nonactivating_cash_revenue_as_percent_of_product_gross_revenue',
                  'NonActivating Cash Revenue as % of Product Gross Revenue'),
                 ('nonactivating_shipping_revenue', 'NonActivating Shipping Revenue'),
                 ('nonactivating_product_order_count', 'NonActivating Product Order Count'),
                 ('nonactivating_product_order_count_excl_seeding', 'NonActivating Product Order Count Excl Seeding'),
                 ('nonactivating_product_margin_pre_return_excl_seeding', 'NonActivating Product Margin Pre Return Excl Seeding'),
                 ('nonactivating_aov', 'NonActivating AOV'),
                 ('nonactivating_unit_count', 'NonActivating Unit Count'),
                 ('nononactivating_upt', 'NonActivating UPT'),
                 ('nonactivating_aur', 'NonActivating AUR'),
                 ('nonactivating_auc_incl_reship_exch', 'NonActivating AUC Incl. Reship/Exch'),
                 ('nonactivating_discount_percent', 'NonActivating Discount %'),
                 ('planning_nonactivating_discount_percent', 'Planning NonActivating Discount %'),
                 ('nonactivating_product_gross_profit', 'NonActivating Product Gross Profit'),
                 ('nonactivating_product_gross_profit_percent', 'NonActivating Product Gross Profit %'),
                 ('nonactivating_product_order_cash_gross_profit', 'NonActivating Product Order Cash Gross Profit'),
                 ('nonactivating_product_order_cash_gross_profit_per_order',
                  'NonActivating Product Order Cash Gross Profit Per Order'),
                 ('nonactivating_product_order_cash_gross_revenue', 'NonActivating Product Order Cash Gross Revenue'),
                 ('guest_orders_as_percent_of_non_activating', 'Guest Orders As % Of NonActivating'),
                 ('guest_product_net_revenue', 'Guest Product Net Revenue'),
                 ('guest_product_order_count', 'Guest Product Order Count'),
                 ('guest_product_order_count_excl_seeding', 'Guest Product Order Count Excl Seeding'),
                 ('guest_product_margin_pre_return_excl_seeding', 'Guest Product Margin Pre Return Excl Seeding'),
                 ('guest_aov', 'Guest AOV'),
                 ('guest_product_gross_profit', 'Guest Product Gross Profit'),
                 ('guest_product_gross_revenue', 'Guest Product Gross Revenue'),
                 ('guest_shipping_revenue', 'Guest Shipping Revenue'),
                 ('guest_unit_count', 'Guest Unit Count'),
                 ('guest_upt', 'Guest UPT'),
                 ('guest_aur', 'Guest AUR'),
                 ('guest_discount_percent', 'Guest Discount %'),
                 ('planning_guest_discount_percent', 'Planning Guest Discount %'),
                 ('guest_product_gross_profit_percent', 'Guest Product Gross Profit %'),
                 ('planning_repeat_vip_discount_percent', 'Planning Repeat VIP Discount %'),
                 ('billed_credit_cash_transaction_amount', 'Billed Credit Cash Transaction Amount'),
                 ('billed_credit_cash_refund_chargeback_amount', 'Billed Credit Cash Refund & Chargeback Amount'),
                 ('billed_cash_credit_redeemed_amount', 'Billed Credit Cash Redeemed Amount'),
                 ('same_month_billed_credit_redeemed', 'Same Month Billed Credit Redeemed'),
                 ('billed_credit_net_billings', 'Billed Credit Net Billings'),
                 ('net_credit_billings_as_percent_of_cash_net_revenue', 'Net Credit Billings As % Of Cash Net Revenue'),
                 ('billed_credits_successful_on_first_try', 'Billed Credits Successful On 1st Try'),
                 ('billed_credits_successful_on_retry', 'Billed Credits Successful On Retry'),
                 ('billed_credit_cash_transaction_count', 'Billed Credit Count'),
                 ('membership_fee_cash_transaction_amount', 'Membership Fee Cash Transaction Amount'),
                 ('gift_card_transaction_amount', 'Gift Card Transaction Amount'),
                 ('legacy_credit_cash_transaction_amount', 'Legacy Credit Cash Transaction Amount'),
                 ('other_billing_cash_transaction_amount',
                  'Giftcard/Membership Fee/Legacy Credits Billing Transaction Amount'),
                 ('membership_fee_cash_refund_chargeback_amount', 'Membership Fee Cash Refund & Chargeback Amount'),
                 ('membership_fee_net_cash_transaction_amount', 'Membership Fee Net Cash Transaction Amount'),
                 ('outbound_product_cost_incl_reship_exch', 'Outbound Product Cost Incl. Reship/Exch'),
                 ('oracle_outbound_product_cost_incl_reship_exch', 'Oracle Outbound Product Cost Incl. Reship/Exch'),
                 ('product_order_count_incl_reship_exch', 'Product Order Count Incl. Reship/Exch'),
                 ('unit_count_incl_reship_exch', 'Unit Count Incl. Reship/Exch'),
                 ('auc_incl_reship_exch', 'AUC Incl. Reship/Exch'),
                 ('product_cost_returned_resaleable_incl_reship_exch',
                  'Product Cost Returned - Resaleable Incl. Reship/Exch'),
                 ('product_cost_returned_damaged_incl_reship_exch',
                  'Product Cost Returned - Damaged Incl. Reship/Exch'),
                 ('product_cost_net_of_returns_incl_reship_exch', 'Product Cost Net Of Returns Incl. Reship/Exch'),
                 ('shipped_cost_incl_reship_exch', 'Shipping Cost Incl. Reship/Exch'),
                 ('shipping_supplies_cost_incl_reship_exch', 'Shipping Supplies Costs Incl. Reship/Exch'),
                 ('return_shipping_costs_incl_reship_exch', 'Return Shipping Costs Incl. Reship/Exch'),
                 ('misc_cogs_amount', 'Misc Cogs Amount'),
                 ('total_cogs', 'Total Cogs'),
                 ('oracle_total_cogs', 'Oracle Total Cogs'),
                 ('pending_product_order_count', 'Pending Product Order Count'),
                 ('eop_vips', 'EOP VIPs'),
                 ('product_order_return_unit_count', 'Product Order Return Unit Count'),
                 ('pending_order_cash_transaction_amount', 'Pending Order Cash Transaction Amount'),
                 ('pending_order_cash_margin_pre_return_amount', 'Pending Order Cash Margin Pre Return Amount'),
                 ('product_order_cash_credit_refund_amount', 'Product Order Credit Refund'),
                 ('product_order_cash_credit_refund_net_billings', 'Product Order Cash Credit Refund - Net Billings'),
                 ('gift_cash_membership_fee_legacy_credit_net_billings',
                  'Giftcard/Membership Fee/Legacy Credit - Net Billings'),
                 ('noncash_credit_issued_amount', 'NonCash Credit Issued Amount'),
                 ('product_order_noncash_credit_redeemed_amount', 'NonCash Credit Redeemed Amount'),
                 ('shipping_cost_per_order','Shipping Cost Per Order'),
                 ('reactivated_vip_product_order_percent', 'Reactivated VIP Product Order %'),
                 ('nonactivating_cash_discount_percent', 'NonActivating Cash Discount %'),
                 ('nonactivating_non_token_unit_percent', 'NonActivating Non Token Unit %'),
                 ('nonactivating_guest_product_order_percent', 'NonActivating Guest Product Order %'),
                 ('nonactivating_product_gross_profit_per_order', 'NonActivating Product Gross Profit Per Order'),
                 ('nonactivating_product_margin_pre_return_per_order', 'NonActivating Product Margin Pre Return Per Order')
             )
),
     _relevant_rows AS (
         SELECT dcso.*,
                CASE
                    WHEN dcso.data_source = 'RR' THEN 'Run Rate'
                    WHEN dcso.data_source = 'MTD' THEN 'MTD'
                    WHEN dcso.data_source = 'EOM' THEN 'Month Totals'
                    ELSE NULL
                    END AS calculation_type
         FROM reporting.daily_cash_ssrs_output AS dcso
         WHERE currency_object <> 'hyperion'
     ),
     _pre_pivot AS (
         SELECT date,
                date_object,
                currency_object,
                currency_type,
                store_brand,
                business_unit,
                report_mapping,
                calculation_type,
                ZEROIFNULL(cash_gross_revenue) :: NUMBER(38, 12)                                             AS cash_gross_revenue,
                ZEROIFNULL(cash_net_revenue) :: NUMBER(38, 12)                                               AS cash_net_revenue,
                ZEROIFNULL(cash_gross_profit) :: NUMBER(38, 12)                                              AS cash_gross_profit,
                ZEROIFNULL(cash_gross_profit_percent_of_net_cash) :: NUMBER(38, 12)                          AS cash_gross_profit_percent_of_net_cash,
                ZEROIFNULL(cash_net_revenue_with_budgeted_fx_rates) :: NUMBER(38, 12)                        AS cash_net_revenue_with_budgeted_fx_rates,
                ZEROIFNULL(activating_cash_gross_revenue) :: NUMBER(38, 12)                                  AS activating_cash_gross_revenue,
                ZEROIFNULL(activating_cash_net_revenue) :: NUMBER(38, 12)                                    AS activating_cash_net_revenue,
                ZEROIFNULL(nonactivating_cash_gross_revenue) :: NUMBER(38, 12)                               AS nonactivating_cash_gross_revenue,
                ZEROIFNULL(nonactivating_cash_net_revenue) :: NUMBER(38, 12)                                 AS nonactivating_cash_net_revenue,
                ZEROIFNULL(product_order_and_billing_cash_refund) :: NUMBER(38, 12)                          AS product_order_and_billing_cash_refund,
                ZEROIFNULL(product_order_and_billing_chargebacks) :: NUMBER(38, 12)                          AS product_order_and_billing_chargebacks,
                ZEROIFNULL(refund_chargebacks_as_percent_of_cash_gross_rev) :: NUMBER(38, 12)                AS refund_chargebacks_as_percent_of_cash_gross_rev,
                ZEROIFNULL(activating_product_gross_revenue) :: NUMBER(38, 12)                               AS activating_product_gross_revenue,
                ZEROIFNULL(activating_product_net_revenue) :: NUMBER(38, 12)                                 AS activating_product_net_revenue,
                ZEROIFNULL(activating_shipping_revenue) :: NUMBER(38, 12)                                    AS activating_shipping_revenue,
                ZEROIFNULL(activating_product_order_count) :: NUMBER(38, 12)                                 AS activating_product_order_count,
                ZEROIFNULL(activating_product_order_count_excl_seeding) :: NUMBER(38, 12)                    AS activating_product_order_count_excl_seeding,
                ZEROIFNULL(activating_product_margin_pre_return_excl_seeding) :: NUMBER(38, 12)              AS activating_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(activating_aov) :: NUMBER(38, 12)                                                 AS activating_aov,
                ZEROIFNULL(activating_unit_count) :: NUMBER(38, 12)                                          AS activating_unit_count,
                ZEROIFNULL(activating_upt) :: NUMBER(38, 12)                                                 AS activating_upt,
                ZEROIFNULL(activating_aur) :: NUMBER(38, 12)                                                 AS activating_aur,
                ZEROIFNULL(activating_auc_incl_reship_exch) :: NUMBER(38, 12)                                AS activating_auc_incl_reship_exch,
                ZEROIFNULL(activating_discount_percent) :: NUMBER(38, 12)                                    AS activating_discount_percent,
                ZEROIFNULL(planning_activating_discount_percent) :: NUMBER(38, 12)                           AS planning_activating_discount_percent,
                ZEROIFNULL(activating_product_gross_profit) :: NUMBER(38, 12)                                AS activating_product_gross_profit,
                ZEROIFNULL(activating_product_gross_profit_per_order) :: NUMBER(38, 12)                      AS activating_product_gross_profit_per_order,
                ZEROIFNULL(nonactivating_product_gross_profit_per_order) :: NUMBER(38, 12)                   AS nonactivating_product_gross_profit_per_order,
                ZEROIFNULL(activating_product_gross_profit_percent) :: NUMBER(38, 12)                        AS activating_product_gross_profit_percent,
                ZEROIFNULL(activating_product_order_cash_gross_revenue) :: NUMBER(38, 12)                    AS activating_product_order_cash_gross_revenue,
                ZEROIFNULL(activating_product_margin_pre_return) :: NUMBER(38, 12)                           AS activating_product_margin_pre_return,
                ZEROIFNULL(activating_product_margin_pre_return_per_order) :: NUMBER(38, 12)                 AS activating_product_margin_pre_return_per_order,
                ZEROIFNULL(nonactivating_product_margin_pre_return_per_order) :: NUMBER(38, 12)              AS nonactivating_product_margin_pre_return_per_order,
                ZEROIFNULL(activating_product_margin_pre_return_percent) :: NUMBER(38, 12)                   AS activating_product_margin_pre_return_percent,
                ZEROIFNULL(nonactivating_product_gross_revenue) :: NUMBER(38, 12)                            AS nonactivating_product_gross_revenue,
                ZEROIFNULL(nonactivating_product_net_revenue) :: NUMBER(38, 12)                              AS nonactivating_product_net_revenue,
                ZEROIFNULL(
                        nonactivating_cash_revenue_as_percent_of_product_gross_revenue) :: NUMBER(38, 12)    AS nonactivating_cash_revenue_as_percent_of_product_gross_revenue,
                ZEROIFNULL(nonactivating_shipping_revenue) :: NUMBER(38, 12)                                 AS nonactivating_shipping_revenue,
                ZEROIFNULL(nonactivating_product_order_count) :: NUMBER(38, 12)                              AS nonactivating_product_order_count,
                ZEROIFNULL(nonactivating_product_order_count_excl_seeding) :: NUMBER(38, 12)                 AS nonactivating_product_order_count_excl_seeding,
                ZEROIFNULL(nonactivating_product_margin_pre_return_excl_seeding) :: NUMBER(38, 12)           AS nonactivating_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(nonactivating_aov) :: NUMBER(38, 12)                                              AS nonactivating_aov,
                ZEROIFNULL(nonactivating_unit_count) :: NUMBER(38, 12)                                       AS nonactivating_unit_count,
                ZEROIFNULL(nononactivating_upt) :: NUMBER(38, 12)                                            AS nononactivating_upt,
                ZEROIFNULL(nonactivating_aur) :: NUMBER(38, 12)                                              AS nonactivating_aur,
                ZEROIFNULL(nonactivating_auc_incl_reship_exch) :: NUMBER(38, 12)                             AS nonactivating_auc_incl_reship_exch,
                ZEROIFNULL(nonactivating_discount_percent) :: NUMBER(38, 12)                                 AS nonactivating_discount_percent,
                ZEROIFNULL(planning_nonactivating_discount_percent) :: NUMBER(38, 12)                        AS planning_nonactivating_discount_percent,
                ZEROIFNULL(nonactivating_product_gross_profit) :: NUMBER(38, 12)                             AS nonactivating_product_gross_profit,
                ZEROIFNULL(nonactivating_product_gross_profit_percent) :: NUMBER(38, 12)                     AS nonactivating_product_gross_profit_percent,
                ZEROIFNULL(nonactivating_product_order_cash_gross_profit) :: NUMBER(38, 12)                  AS nonactivating_product_order_cash_gross_profit,
                ZEROIFNULL(nonactivating_product_order_cash_gross_profit_per_order) :: NUMBER(38, 12)        AS nonactivating_product_order_cash_gross_profit_per_order,
                ZEROIFNULL(nonactivating_product_order_cash_gross_revenue) :: NUMBER(38, 12)                 AS nonactivating_product_order_cash_gross_revenue,
                ZEROIFNULL(guest_orders_as_percent_of_non_activating) :: NUMBER(38, 12)                      AS guest_orders_as_percent_of_non_activating,
                ZEROIFNULL(guest_product_net_revenue) :: NUMBER(38, 12)                                      AS guest_product_net_revenue,
                ZEROIFNULL(guest_product_order_count) :: NUMBER(38, 12)                                      AS guest_product_order_count,
                ZEROIFNULL(guest_product_order_count_excl_seeding) :: NUMBER(38, 12)                         AS guest_product_order_count_excl_seeding,
                ZEROIFNULL(guest_product_margin_pre_return_excl_seeding) :: NUMBER(38, 12)                   AS guest_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(guest_aov) :: NUMBER(38, 12)                                                      AS guest_aov,
                ZEROIFNULL(guest_product_gross_profit) :: NUMBER(38, 12)                                     AS guest_product_gross_profit,
                ZEROIFNULL(guest_product_gross_revenue) :: NUMBER(38, 12)                                    AS guest_product_gross_revenue,
                ZEROIFNULL(guest_shipping_revenue) :: NUMBER(38, 12)                                         AS guest_shipping_revenue,
                ZEROIFNULL(guest_unit_count) :: NUMBER(38, 12)                                               AS guest_unit_count,
                ZEROIFNULL(guest_upt) :: NUMBER(38, 12)                                                      AS guest_upt,
                ZEROIFNULL(guest_aur) :: NUMBER(38, 12)                                                      AS guest_aur,
                ZEROIFNULL(guest_discount_percent) :: NUMBER(38, 12)                                         AS guest_discount_percent,
                ZEROIFNULL(planning_guest_discount_percent) :: NUMBER(38, 12)                                AS planning_guest_discount_percent,
                ZEROIFNULL(guest_product_gross_profit_percent) :: NUMBER(38, 12)                             AS guest_product_gross_profit_percent,
                ZEROIFNULL(planning_repeat_vip_discount_percent) :: NUMBER(38, 12)                           AS planning_repeat_vip_discount_percent,
                ZEROIFNULL(billed_credit_cash_transaction_amount) :: NUMBER(38, 12)                          AS billed_credit_cash_transaction_amount,
                ZEROIFNULL(billed_credit_cash_refund_chargeback_amount) :: NUMBER(38, 12)                    AS billed_credit_cash_refund_chargeback_amount,
                ZEROIFNULL(billed_cash_credit_redeemed_amount) :: NUMBER(38, 12)                             AS billed_cash_credit_redeemed_amount,
                ZEROIFNULL(same_month_billed_credit_redeemed) :: NUMBER(38, 12)                              AS same_month_billed_credit_redeemed,
                ZEROIFNULL(billed_credit_net_billings) :: NUMBER(38, 12)                                     AS billed_credit_net_billings,
                ZEROIFNULL(net_credit_billings_as_percent_of_cash_net_revenue) :: NUMBER(38, 12)             AS net_credit_billings_as_percent_of_cash_net_revenue,
                ZEROIFNULL(billed_credits_successful_on_first_try) :: NUMBER(38, 12)                         AS billed_credits_successful_on_first_try,
                ZEROIFNULL(billed_credits_successful_on_retry) :: NUMBER(38, 12)                             AS billed_credits_successful_on_retry,
                ZEROIFNULL(billed_credit_cash_transaction_count) :: NUMBER(38, 12)                           AS billed_credit_cash_transaction_count,
                ZEROIFNULL(membership_fee_cash_transaction_amount) :: NUMBER(38, 12)                         AS membership_fee_cash_transaction_amount,
                ZEROIFNULL(gift_card_transaction_amount) :: NUMBER(38, 12)                                   AS gift_card_transaction_amount,
                ZEROIFNULL(legacy_credit_cash_transaction_amount) :: NUMBER(38, 12)                          AS legacy_credit_cash_transaction_amount,
                ZEROIFNULL(other_billing_cash_transaction_amount) :: NUMBER(38, 12)                          AS other_billing_cash_transaction_amount,
                ZEROIFNULL(membership_fee_cash_refund_chargeback_amount) :: NUMBER(38, 12)                   AS membership_fee_cash_refund_chargeback_amount,
                ZEROIFNULL(membership_fee_net_cash_transaction_amount) :: NUMBER(38, 12)                     AS membership_fee_net_cash_transaction_amount,
                ZEROIFNULL(outbound_product_cost_incl_reship_exch) :: NUMBER(38, 12)                         AS outbound_product_cost_incl_reship_exch,
                ZEROIFNULL(oracle_outbound_product_cost_incl_reship_exch) :: NUMBER(38, 12)                  AS oracle_outbound_product_cost_incl_reship_exch,
                ZEROIFNULL(product_order_count_incl_reship_exch) :: NUMBER(38, 12)                           AS product_order_count_incl_reship_exch,
                ZEROIFNULL(unit_count_incl_reship_exch) :: NUMBER(38, 12)                                    AS unit_count_incl_reship_exch,
                ZEROIFNULL(auc_incl_reship_exch) :: NUMBER(38, 12)                                           AS auc_incl_reship_exch,
                ZEROIFNULL(product_cost_returned_resaleable_incl_reship_exch) :: NUMBER(38, 12)              AS product_cost_returned_resaleable_incl_reship_exch,
                ZEROIFNULL(product_cost_returned_damaged_incl_reship_exch) :: NUMBER(38, 12)                 AS product_cost_returned_damaged_incl_reship_exch,
                ZEROIFNULL(product_cost_net_of_returns_incl_reship_exch) :: NUMBER(38, 12)                   AS product_cost_net_of_returns_incl_reship_exch,
                ZEROIFNULL(shipped_cost_incl_reship_exch) :: NUMBER(38, 12)                                  AS shipped_cost_incl_reship_exch,
                ZEROIFNULL(shipping_supplies_cost_incl_reship_exch) :: NUMBER(38, 12)                        AS shipping_supplies_cost_incl_reship_exch,
                ZEROIFNULL(return_shipping_costs_incl_reship_exch) :: NUMBER(38, 12)                         AS return_shipping_costs_incl_reship_exch,
                ZEROIFNULL(misc_cogs_amount) :: NUMBER(38, 12)                                               AS misc_cogs_amount,
                ZEROIFNULL(total_cogs) :: NUMBER(38, 12)                                                     AS total_cogs,
                ZEROIFNULL(oracle_total_cogs) :: NUMBER(38, 12)                                              AS oracle_total_cogs,
                ZEROIFNULL(eop_vips) :: NUMBER(38, 12)                                                       AS eop_vips,
                ZEROIFNULL(product_order_return_unit_count) :: NUMBER(38, 12)                                AS product_order_return_unit_count,
                ZEROIFNULL(product_order_cash_credit_refund_amount) :: NUMBER(38, 12)                        AS product_order_cash_credit_refund_amount,
                ZEROIFNULL(product_order_cash_credit_refund_net_billings) :: NUMBER(38, 12)                  AS product_order_cash_credit_refund_net_billings,
                ZEROIFNULL(gift_card_membership_fee_legacy_credit_net_billings) :: NUMBER(38, 12)            AS gift_card_membership_fee_legacy_credit_net_billings,
                ZEROIFNULL(noncash_credit_issued_amount) :: NUMBER(38, 12)                                   AS noncash_credit_issued_amount,
                ZEROIFNULL(product_order_noncash_credit_redeemed_amount) :: NUMBER(38, 12)                   AS product_order_noncash_credit_redeemed_amount,
                ZEROIFNULL(shipped_cost_incl_reship_exch/NULLIFZERO(COALESCE(activating_product_order_count,0)+COALESCE(nonactivating_product_order_count,0))) :: NUMBER(38, 12)                                  AS shipping_cost_per_order,
                ZEROIFNULL(reactivated_vip_product_order_count/NULLIFZERO(COALESCE(activating_product_order_count,0))) :: NUMBER(38, 12) AS reactivated_vip_product_order_percent,
                ZEROIFNULL(nonactivating_cash_discount_percent) :: NUMBER(38, 12)                             AS nonactivating_cash_discount_percent,
                ZEROIFNULL(nonactivating_non_token_unit_percent) :: NUMBER(38, 12)                            AS nonactivating_non_token_unit_percent,
                ZEROIFNULL(nonactivating_guest_product_order_percent) :: NUMBER(38, 12)                       AS nonactivating_guest_product_order_percent
       FROM _relevant_rows
     ),
     _pre_pivot_forecast AS (
         SELECT date,
                date_object,
                currency_object,
                currency_type,
                store_brand,
                business_unit,
                report_mapping,
                'Forecast'                                                                                AS calculation_type,
                ZEROIFNULL(cash_gross_revenue_forecast) :: NUMBER(38, 12)                                 AS cash_gross_revenue,
                ZEROIFNULL(cash_net_revenue_forecast) :: NUMBER(38, 12)                                   AS cash_net_revenue,
                ZEROIFNULL(cash_gross_profit_forecast) :: NUMBER(38, 12)                                  AS cash_gross_profit,
                ZEROIFNULL(cash_gross_profit_percent_of_net_cash_forecast) :: NUMBER(38, 12)              AS cash_gross_profit_percent_of_net_cash,
                ZEROIFNULL(cash_net_revenue_forecast) :: NUMBER(38, 12)                                   AS cash_net_revenue_with_budgeted_fx_rates,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS activating_cash_gross_revenue,
                ZEROIFNULL(activating_cash_net_revenue_forecast) :: NUMBER(38, 12)                        AS activating_cash_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_cash_gross_revenue,
                ZEROIFNULL(nonactivating_cash_net_revenue_forecast) :: NUMBER(38, 12)                     AS nonactivating_cash_net_revenue,
                ZEROIFNULL(product_order_and_billing_cash_refund_forecast) :: NUMBER(38, 12)              AS product_order_and_billing_cash_refund,
                ZEROIFNULL(product_order_and_billing_chargebacks_forecast) :: NUMBER(38, 12)              AS product_order_and_billing_chargebacks,
                ZEROIFNULL((COALESCE(product_order_and_billing_cash_refund_forecast, 0) +
                            COALESCE(product_order_and_billing_chargebacks_forecast, 0))
                    /
                           NULLIFZERO(cash_gross_revenue_forecast)) :: NUMBER(38, 12)                     AS refund_chargebacks_as_percent_of_cash_gross_rev,

                ZEROIFNULL(activating_product_gross_revenue_forecast) :: NUMBER(38, 12)                   AS activating_product_gross_revenue,
                ZEROIFNULL(activating_product_net_revenue_forecast) :: NUMBER(38, 12)                     AS activating_product_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS activating_shipping_revenue,
                ZEROIFNULL(activating_product_order_count_forecast) :: NUMBER(38, 12)                     AS activating_product_order_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS activating_product_order_count_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS activating_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(activating_aov_forecast) :: NUMBER(38, 12)                                     AS activating_aov,
                ZEROIFNULL(activating_unit_count_forecast) :: NUMBER(38, 12)                              AS activating_unit_count,
                ZEROIFNULL(activating_upt_forecast) :: NUMBER(38, 12)                                     AS activating_upt,
                ZEROIFNULL(activating_product_gross_revenue_forecast /
                           NULLIFZERO(activating_unit_count_forecast)) :: NUMBER(38, 12)                  AS activating_aur,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS activating_auc_incl_reship_exch,
                ZEROIFNULL(activating_discount_percent_forecast) :: NUMBER(38, 12)                        AS activating_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS planning_activating_discount_percent,
                ZEROIFNULL(activating_product_gross_profit_forecast) :: NUMBER(38, 12)                    AS activating_product_gross_profit,
                ZEROIFNULL(activating_product_gross_profit_forecast /
                           NULLIFZERO(activating_product_order_count_forecast)) :: NUMBER(38, 12)         AS activating_product_gross_profit_per_order,
                ZEROIFNULL(nonactivating_product_gross_profit_forecast /
                           NULLIFZERO(nonactivating_product_order_count_forecast)) :: NUMBER(38, 12)      AS nonactivating_product_gross_profit_per_order,
                ZEROIFNULL(activating_product_gross_profit_percent_forecast) :: NUMBER(38, 12)            AS activating_product_gross_profit_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS activating_product_order_cash_gross_revenue,
                ZEROIFNULL(activating_product_margin_pre_return_forecast) :: NUMBER(38, 12)               AS activating_product_margin_pre_return,
                ZEROIFNULL(activating_product_margin_pre_return_per_order_forecast) :: NUMBER(38, 12)     AS activating_product_margin_pre_return_per_order,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_product_margin_pre_return_per_order,
                ZEROIFNULL(activating_product_margin_pre_return_percent_forecast) :: NUMBER(38, 12)       AS activating_product_margin_pre_return_percent,
                ZEROIFNULL(nonactivating_product_gross_revenue_forecast) :: NUMBER(38, 12)                AS nonactivating_product_gross_revenue,
                ZEROIFNULL(nonactivating_product_net_revenue_forecast) :: NUMBER(38, 12)                  AS nonactivating_product_net_revenue,
                ZEROIFNULL(nonactivating_product_order_cash_gross_revenue_forecast /
                           NULLIFZERO(nonactivating_product_gross_revenue_forecast)) :: NUMBER(38, 12)    AS nonactivating_cash_revenue_as_percent_of_product_gross_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_shipping_revenue,
                ZEROIFNULL(nonactivating_product_order_count_forecast) :: NUMBER(38, 12)                  AS nonactivating_product_order_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_product_order_count_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(nonactivating_aov_forecast) :: NUMBER(38, 12)                                  AS nonactivating_aov,
                ZEROIFNULL(nonactivating_unit_count_forecast) :: NUMBER(38, 12)                           AS nonactivating_unit_count,
                ZEROIFNULL(nonactivating_unit_count_forecast /
                           NULLIFZERO(nonactivating_product_order_count_forecast)) :: NUMBER(38, 12)      AS nononactivating_upt,
                ZEROIFNULL(nonactivating_product_gross_revenue_forecast /
                           NULLIFZERO(nonactivating_unit_count_forecast)) :: NUMBER(38, 12)               AS nonactivating_aur,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_auc_incl_reship_exch,
                ZEROIFNULL(nonactivating_discount_percent_forecast) :: NUMBER(38, 12)                     AS nonactivating_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS planning_nonactivating_discount_percent,
                ZEROIFNULL(nonactivating_product_gross_profit_forecast) :: NUMBER(38, 12)                 AS nonactivating_product_gross_profit,
                ZEROIFNULL(nonactivating_product_gross_profit_percent_forecast) :: NUMBER(38, 12)         AS nonactivating_product_gross_profit_percent,
                ZEROIFNULL(nonactivating_product_order_cash_gross_profit_forecast) :: NUMBER(38, 12)      AS nonactivating_product_order_cash_gross_profit,
                ZEROIFNULL(nonactivating_product_order_cash_gross_profit_forecast /
                           NULLIFZERO(nonactivating_product_order_count_forecast)) :: NUMBER(38, 12)      AS nonactivating_product_order_cash_gross_profit_per_order,
                ZEROIFNULL(nonactivating_product_order_cash_gross_revenue_forecast) :: NUMBER(38, 12)     AS nonactivating_product_order_cash_gross_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_orders_as_percent_of_non_activating,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_product_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_product_order_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_product_order_count_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_aov,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_product_gross_profit,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_product_gross_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_shipping_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_unit_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_upt,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_aur,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS planning_guest_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS guest_product_gross_profit_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS planning_repeat_vip_discount_percent,
                ZEROIFNULL(billed_credit_cash_transaction_amount_forecast) :: NUMBER(38, 12)              AS billed_credit_cash_transaction_amount,
                ZEROIFNULL(billed_credit_cash_refund_chargeback_amount_forecast) :: NUMBER(38, 12)        AS billed_credit_cash_refund_chargeback_amount,
                ZEROIFNULL(billed_cash_credit_redeemed_amount_forecast) :: NUMBER(38, 12)                 AS billed_cash_credit_redeemed_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS same_month_billed_credit_redeemed,
                ZEROIFNULL(COALESCE(billed_credit_cash_transaction_amount_forecast, 0) -
                           COALESCE(billed_credit_cash_refund_chargeback_amount_forecast, 0) -
                           COALESCE(billed_cash_credit_redeemed_amount_forecast, 0)) :: NUMBER(38, 12)    AS billed_credit_net_billings,
                ZEROIFNULL((COALESCE(billed_credit_cash_transaction_amount_forecast, 0) -
                            COALESCE(billed_credit_cash_refund_chargeback_amount_forecast, 0) -
                            COALESCE(billed_cash_credit_redeemed_amount_forecast, 0)) /
                           NULLIFZERO(cash_net_revenue_forecast)) :: NUMBER(38, 12)                       AS net_credit_billings_as_percent_of_cash_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS billed_credits_successful_on_first_try,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS billed_credits_successful_on_retry,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS billed_credit_cash_transaction_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS membership_fee_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS gift_card_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS legacy_credit_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS other_billing_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS membership_fee_cash_refund_chargeback_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS membership_fee_net_cash_transaction_amount,
                ZEROIFNULL(product_cost_calc_forecast) :: NUMBER(38, 12)                                  AS outbound_product_cost_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS oracle_outbound_product_cost_incl_reship_exch,
                ZEROIFNULL(COALESCE(activating_product_order_count_forecast, 0) +
                           COALESCE(nonactivating_product_order_count_forecast, 0) +
                           COALESCE(product_order_reship_exch_order_count_forecast, 0)) :: NUMBER(38, 12) AS product_order_count_incl_reship_exch,
                ZEROIFNULL(unit_count_forecast) :: NUMBER(38, 12)                                         AS unit_count_incl_reship_exch,
                ZEROIFNULL(
                        product_cost_calc_forecast / NULLIFZERO(unit_count_forecast)) :: NUMBER(38, 12)   AS auc_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS product_cost_returned_resaleable_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS product_cost_returned_damaged_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS product_cost_net_of_returns_incl_reship_exch,
                ZEROIFNULL(shipping_cost_incl_reship_exch_forecast) :: NUMBER(38, 12)                     AS shipped_cost_incl_reship_exch,
                ZEROIFNULL(shipping_supplies_cost_incl_reship_exch_forecast) :: NUMBER(38, 12)            AS shipping_supplies_cost_incl_reship_exch,
                ZEROIFNULL(return_shipping_costs_incl_reship_exch_forecast) :: NUMBER(38, 12)             AS return_shipping_costs_incl_reship_exch,
                ZEROIFNULL(misc_cogs_amount_forecast) :: NUMBER(38, 12)                                   AS misc_cogs_amount,
                ZEROIFNULL(total_cogs_forecast) :: NUMBER(38, 12)                                         AS total_cogs,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS oracle_total_cogs,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS pending_product_order_count,
                ZEROIFNULL(COALESCE(bop_vips_forecast, 0) + COALESCE(new_vips_forecast, 0) -
                           COALESCE(cancels_forecast, 0)) :: NUMBER(38, 12)                               AS eop_vips,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS product_order_return_unit_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS pending_order_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS pending_order_cash_margin_pre_return_amount,
                ZEROIFNULL(product_order_cash_credit_refund_amount_forecast) :: NUMBER(38, 12)            AS product_order_cash_credit_refund_amount,
                ZEROIFNULL(COALESCE(product_order_cash_credit_refund_amount_forecast, 0) -
                           COALESCE(refund_cash_credit_redeemed_amount_forecast, 0)) :: NUMBER(38, 12)    AS product_order_cash_credit_refund_net_billings,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS noncash_credit_issued_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS product_order_noncash_credit_redeemed_amount,
                ZEROIFNULL(shipping_cost_incl_reship_exch_forecast/NULLIFZERO(COALESCE(activating_product_order_count_forecast,0)+COALESCE(nonactivating_product_order_count_forecast,0))) :: NUMBER(38, 12)                                  AS shipping_cost_per_order,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS reactivated_vip_product_order_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_cash_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_non_token_unit_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                           AS nonactivating_guest_product_order_percent
         FROM reporting.daily_cash_final_output
         WHERE day(date) = 1
         AND report_date_type = 'To Date'
     ),
     _pre_pivot_budget AS (
         SELECT date,
                date_object,
                currency_object,
                currency_type,
                store_brand,
                business_unit,
                report_mapping,
                'Budget'                                                                                AS calculation_type,
                ZEROIFNULL(cash_gross_revenue_budget) :: NUMBER(38, 12)                                 AS cash_gross_revenue,
                ZEROIFNULL(cash_net_revenue_budget) :: NUMBER(38, 12)                                   AS cash_net_revenue,
                ZEROIFNULL(cash_gross_profit_budget) :: NUMBER(38, 12)                                  AS cash_gross_profit,
                ZEROIFNULL(cash_gross_profit_percent_of_net_cash_budget) :: NUMBER(38, 12)              AS cash_gross_profit_percent_of_net_cash,
                ZEROIFNULL(cash_net_revenue_budget) :: NUMBER(38, 12)                                   AS cash_net_revenue_with_budgeted_fx_rates,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS activating_cash_gross_revenue,
                ZEROIFNULL(activating_cash_net_revenue_budget) :: NUMBER(38, 12)                        AS activating_cash_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_cash_gross_revenue,
                ZEROIFNULL(nonactivating_cash_net_revenue_budget) :: NUMBER(38, 12)                     AS nonactivating_cash_net_revenue,
                ZEROIFNULL(product_order_and_billing_cash_refund_budget) :: NUMBER(38, 12)              AS product_order_and_billing_cash_refund,
                ZEROIFNULL(product_order_and_billing_chargebacks_budget) :: NUMBER(38, 12)              AS product_order_and_billing_chargebacks,
                ZEROIFNULL((COALESCE(product_order_and_billing_cash_refund_budget, 0) +
                            COALESCE(product_order_and_billing_chargebacks_budget, 0))
                    /
                           NULLIFZERO(cash_gross_revenue_budget)) :: NUMBER(38, 12)                     AS refund_chargebacks_as_percent_of_cash_gross_rev,

                ZEROIFNULL(activating_product_gross_revenue_budget) :: NUMBER(38, 12)                   AS activating_product_gross_revenue,
                ZEROIFNULL(activating_product_net_revenue_budget) :: NUMBER(38, 12)                     AS activating_product_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS activating_shipping_revenue,
                ZEROIFNULL(activating_product_order_count_budget) :: NUMBER(38, 12)                     AS activating_product_order_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS activating_product_order_count_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS activating_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(activating_aov_budget) :: NUMBER(38, 12)                                     AS activating_aov,
                ZEROIFNULL(activating_unit_count_budget) :: NUMBER(38, 12)                              AS activating_unit_count,
                ZEROIFNULL(activating_upt_budget) :: NUMBER(38, 12)                                     AS activating_upt,
                ZEROIFNULL(activating_product_gross_revenue_budget /
                           NULLIFZERO(activating_unit_count_budget)) :: NUMBER(38, 12)                  AS activating_aur,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS activating_auc_incl_reship_exch,
                ZEROIFNULL(activating_discount_percent_budget) :: NUMBER(38, 12)                        AS activating_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS planning_activating_discount_percent,
                ZEROIFNULL(activating_product_gross_profit_budget) :: NUMBER(38, 12)                    AS activating_product_gross_profit,
                ZEROIFNULL(activating_product_gross_profit_budget /
                           NULLIFZERO(activating_product_order_count_budget)) :: NUMBER(38, 12)         AS activating_product_gross_profit_per_order,
                ZEROIFNULL(nonactivating_product_gross_profit_budget /
                           NULLIFZERO(nonactivating_product_order_count_budget)) :: NUMBER(38, 12)      AS nonactivating_product_gross_profit_per_order,
                ZEROIFNULL(activating_product_gross_profit_percent_budget) :: NUMBER(38, 12)            AS activating_product_gross_profit_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS activating_product_order_cash_gross_revenue,
                ZEROIFNULL(activating_product_margin_pre_return_budget) :: NUMBER(38, 12)               AS activating_product_margin_pre_return,
                ZEROIFNULL(activating_product_margin_pre_return_per_order_budget) :: NUMBER(38, 12)     AS activating_product_margin_pre_return_per_order,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_product_margin_pre_return_per_order,
                ZEROIFNULL(activating_product_margin_pre_return_percent_budget) :: NUMBER(38, 12)       AS activating_product_margin_pre_return_percent,
                ZEROIFNULL(nonactivating_product_gross_revenue_budget) :: NUMBER(38, 12)                AS nonactivating_product_gross_revenue,
                ZEROIFNULL(nonactivating_product_net_revenue_budget) :: NUMBER(38, 12)                  AS nonactivating_product_net_revenue,
                ZEROIFNULL(nonactivating_product_order_cash_gross_revenue_budget /
                           NULLIFZERO(nonactivating_product_gross_revenue_budget)) :: NUMBER(38, 12)    AS nonactivating_cash_revenue_as_percent_of_product_gross_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_shipping_revenue,
                ZEROIFNULL(nonactivating_product_order_count_budget) :: NUMBER(38, 12)                  AS nonactivating_product_order_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_product_order_count_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(nonactivating_aov_budget) :: NUMBER(38, 12)                                  AS nonactivating_aov,
                ZEROIFNULL(nonactivating_unit_count_budget) :: NUMBER(38, 12)                           AS nonactivating_unit_count,
                ZEROIFNULL(nonactivating_unit_count_budget /
                           NULLIFZERO(nonactivating_product_order_count_budget)) :: NUMBER(38, 12)      AS nononactivating_upt,
                ZEROIFNULL(nonactivating_product_gross_revenue_budget /
                           NULLIFZERO(nonactivating_unit_count_budget)) :: NUMBER(38, 12)               AS nonactivating_aur,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_auc_incl_reship_exch,
                ZEROIFNULL(nonactivating_discount_percent_budget) :: NUMBER(38, 12)                     AS nonactivating_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS planning_nonactivating_discount_percent,
                ZEROIFNULL(nonactivating_product_gross_profit_budget) :: NUMBER(38, 12)                 AS nonactivating_product_gross_profit,
                ZEROIFNULL(nonactivating_product_gross_profit_percent_budget) :: NUMBER(38, 12)         AS nonactivating_product_gross_profit_percent,
                ZEROIFNULL(nonactivating_product_order_cash_gross_profit_budget) :: NUMBER(38, 12)      AS nonactivating_product_order_cash_gross_profit,
                ZEROIFNULL(nonactivating_product_order_cash_gross_profit_budget /
                           NULLIFZERO(nonactivating_product_order_count_budget)) :: NUMBER(38, 12)      AS nonactivating_product_order_cash_gross_profit_per_order,
                ZEROIFNULL(nonactivating_product_order_cash_gross_revenue_budget) :: NUMBER(38, 12)     AS nonactivating_product_order_cash_gross_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_orders_as_percent_of_non_activating,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_product_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_product_order_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_product_order_count_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_product_margin_pre_return_excl_seeding,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_aov,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_product_gross_profit,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_product_gross_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_shipping_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_unit_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_upt,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_aur,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS planning_guest_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS guest_product_gross_profit_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS planning_repeat_vip_discount_percent,
                ZEROIFNULL(billed_credit_cash_transaction_amount_budget) :: NUMBER(38, 12)              AS billed_credit_cash_transaction_amount,
                ZEROIFNULL(billed_credit_cash_refund_chargeback_amount_budget) :: NUMBER(38, 12)        AS billed_credit_cash_refund_chargeback_amount,
                ZEROIFNULL(billed_cash_credit_redeemed_amount_budget) :: NUMBER(38, 12)                 AS billed_cash_credit_redeemed_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS same_month_billed_credit_redeemed,
                ZEROIFNULL(COALESCE(billed_credit_cash_transaction_amount_budget, 0) -
                           COALESCE(billed_credit_cash_refund_chargeback_amount_budget, 0) -
                           COALESCE(billed_cash_credit_redeemed_amount_budget, 0)) :: NUMBER(38, 12)    AS billed_credit_net_billings,
                ZEROIFNULL((COALESCE(billed_credit_cash_transaction_amount_budget, 0) -
                            COALESCE(billed_credit_cash_refund_chargeback_amount_budget, 0) -
                            COALESCE(billed_cash_credit_redeemed_amount_budget, 0)) /
                           NULLIFZERO(cash_net_revenue_budget)) :: NUMBER(38, 12)                       AS net_credit_billings_as_percent_of_cash_net_revenue,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS billed_credits_successful_on_first_try,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS billed_credits_successful_on_retry,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS billed_credit_cash_transaction_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS membership_fee_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS gift_card_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS legacy_credit_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS other_billing_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS membership_fee_cash_refund_chargeback_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS membership_fee_net_cash_transaction_amount,
                ZEROIFNULL(product_cost_calc_budget) :: NUMBER(38, 12)                                  AS outbound_product_cost_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS oracle_outbound_product_cost_incl_reship_exch,
                ZEROIFNULL(COALESCE(activating_product_order_count_budget, 0) +
                           COALESCE(nonactivating_product_order_count_budget, 0) +
                           COALESCE(product_order_reship_exch_order_count_budget, 0)) :: NUMBER(38, 12) AS product_order_count_incl_reship_exch,
                ZEROIFNULL(unit_count_budget) :: NUMBER(38, 12)                                         AS unit_count_incl_reship_exch,
                ZEROIFNULL(
                        product_cost_calc_budget / NULLIFZERO(unit_count_budget)) :: NUMBER(38, 12)     AS auc_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS product_cost_returned_resaleable_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS product_cost_returned_damaged_incl_reship_exch,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS product_cost_net_of_returns_incl_reship_exch,
                ZEROIFNULL(shipping_cost_incl_reship_exch_budget) :: NUMBER(38, 12)                     AS shipped_cost_incl_reship_exch,
                ZEROIFNULL(shipping_supplies_cost_incl_reship_exch_budget) :: NUMBER(38, 12)            AS shipping_supplies_cost_incl_reship_exch,
                ZEROIFNULL(return_shipping_costs_incl_reship_exch_budget) :: NUMBER(38, 12)             AS return_shipping_costs_incl_reship_exch,
                ZEROIFNULL(misc_cogs_amount_budget) :: NUMBER(38, 12)                                   AS misc_cogs_amount,
                ZEROIFNULL(total_cogs_budget) :: NUMBER(38, 12)                                         AS total_cogs,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS oracle_total_cogs,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS pending_product_order_count,
                ZEROIFNULL(COALESCE(bop_vips_budget, 0) + COALESCE(new_vips_budget, 0) -
                           COALESCE(cancels_budget, 0)) :: NUMBER(38, 12)                               AS eop_vips,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS product_order_return_unit_count,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS pending_order_cash_transaction_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS pending_order_cash_margin_pre_return_amount,
                ZEROIFNULL(product_order_cash_credit_refund_amount_budget) :: NUMBER(38, 12)            AS product_order_cash_credit_refund_amount,
                ZEROIFNULL(COALESCE(product_order_cash_credit_refund_amount_budget, 0) -
                           COALESCE(refund_cash_credit_redeemed_amount_budget, 0)) :: NUMBER(38, 12)    AS product_order_cash_credit_refund_net_billings,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS noncash_credit_issued_amount,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS product_order_noncash_credit_redeemed_amount,
                ZEROIFNULL(shipping_cost_incl_reship_exch_budget/NULLIFZERO(COALESCE(activating_product_order_count_budget,0)+COALESCE(nonactivating_product_order_count_budget,0))) :: NUMBER(38, 12)                                  AS shipping_cost_per_order,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS reactivated_vip_product_order_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_cash_discount_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_non_token_unit_percent,
                ZEROIFNULL(0) :: NUMBER(38, 12)                                                         AS nonactivating_guest_product_order_percent
         FROM reporting.daily_cash_final_output
         WHERE day(date) = 1
         AND report_date_type = 'To Date'
     ),
     _pivoted_table AS (
         SELECT pp.date,
                pp.date_object,
                pp.currency_object,
                pp.currency_type,
                pp.store_brand,
                pp.business_unit,
                pp.report_mapping,
                pp.calculation_type,
                LOWER("metric_name") AS metric_name,
                "value"
         FROM _pre_pivot AS pp
             UNPIVOT (
             "value" FOR "metric_name" IN (
                 cash_gross_revenue,
                 cash_net_revenue,
                 cash_gross_profit,
                 cash_gross_profit_percent_of_net_cash,
                 cash_net_revenue_with_budgeted_fx_rates,
                 activating_cash_gross_revenue,
                 activating_cash_net_revenue,
                 nonactivating_cash_gross_revenue,
                 nonactivating_cash_net_revenue,
                 product_order_and_billing_cash_refund,
                 product_order_and_billing_chargebacks,
                 refund_chargebacks_as_percent_of_cash_gross_rev,
                 activating_product_gross_revenue,
                 activating_product_net_revenue,
                 activating_shipping_revenue,
                 activating_product_order_count,
                 activating_product_order_count_excl_seeding,
                 activating_product_margin_pre_return_excl_seeding,
                 activating_aov,
                 activating_unit_count,
                 activating_upt,
                 activating_aur,
                 activating_auc_incl_reship_exch,
                 activating_discount_percent,
                 planning_activating_discount_percent,
                 activating_product_gross_profit,
                 activating_product_gross_profit_per_order,
                 nonactivating_product_gross_profit_per_order,
                 activating_product_gross_profit_percent,
                 activating_product_order_cash_gross_revenue,
                 activating_product_margin_pre_return,
                 activating_product_margin_pre_return_per_order,
                 nonactivating_product_margin_pre_return_per_order,
                 activating_product_margin_pre_return_percent,
                 nonactivating_product_gross_revenue,
                 nonactivating_product_net_revenue,
                 nonactivating_cash_revenue_as_percent_of_product_gross_revenue,
                 nonactivating_shipping_revenue,
                 nonactivating_product_order_count,
                 nonactivating_product_order_count_excl_seeding,
                 nonactivating_product_margin_pre_return_excl_seeding,
                 nonactivating_aov,
                 nonactivating_unit_count,
                 nononactivating_upt,
                 nonactivating_aur,
                 nonactivating_auc_incl_reship_exch,
                 nonactivating_discount_percent,
                 planning_nonactivating_discount_percent,
                 nonactivating_product_gross_profit,
                 nonactivating_product_gross_profit_percent,
                 nonactivating_product_order_cash_gross_profit,
                 nonactivating_product_order_cash_gross_profit_per_order,
                 nonactivating_product_order_cash_gross_revenue,
                 guest_orders_as_percent_of_non_activating,
                 guest_product_net_revenue,
                 guest_product_order_count,
                 guest_product_order_count_excl_seeding,
                 guest_product_margin_pre_return_excl_seeding,
                 guest_aov,
                 guest_product_gross_profit,
                 guest_product_gross_revenue,
                 guest_shipping_revenue,
                 guest_unit_count,
                 guest_upt,
                 guest_aur,
                 guest_discount_percent,
                 planning_guest_discount_percent,
                 guest_product_gross_profit_percent,
                 planning_repeat_vip_discount_percent,
                 billed_credit_cash_transaction_amount,
                 billed_credit_cash_refund_chargeback_amount,
                 billed_cash_credit_redeemed_amount,
                 same_month_billed_credit_redeemed,
                 billed_credit_net_billings,
                 net_credit_billings_as_percent_of_cash_net_revenue,
                 billed_credits_successful_on_first_try,
                 billed_credits_successful_on_retry,
                 billed_credit_cash_transaction_count,
                 membership_fee_cash_transaction_amount,
                 gift_card_transaction_amount,
                 legacy_credit_cash_transaction_amount,
                 other_billing_cash_transaction_amount,
                 membership_fee_cash_refund_chargeback_amount,
                 membership_fee_net_cash_transaction_amount,
                 outbound_product_cost_incl_reship_exch,
                 oracle_outbound_product_cost_incl_reship_exch,
                 product_order_count_incl_reship_exch,
                 unit_count_incl_reship_exch,
                 auc_incl_reship_exch,
                 product_cost_returned_resaleable_incl_reship_exch,
                 product_cost_returned_damaged_incl_reship_exch,
                 product_cost_net_of_returns_incl_reship_exch,
                 shipped_cost_incl_reship_exch,
                 shipping_supplies_cost_incl_reship_exch,
                 return_shipping_costs_incl_reship_exch,
                 misc_cogs_amount,
                 total_cogs,
                 oracle_total_cogs,
                 eop_vips,
                 product_order_return_unit_count,
                 product_order_cash_credit_refund_amount,
                 product_order_cash_credit_refund_net_billings,
                 gift_card_membership_fee_legacy_credit_net_billings,
                 noncash_credit_issued_amount,
                 product_order_noncash_credit_redeemed_amount,
                 shipping_cost_per_order,
                 reactivated_vip_product_order_percent,
                 nonactivating_cash_discount_percent,
                 nonactivating_non_token_unit_percent,
                 nonactivating_guest_product_order_percent
                 )
             )
         UNION ALL
         SELECT ppf.date,
                ppf.date_object,
                ppf.currency_object,
                ppf.currency_type,
                ppf.store_brand,
                ppf.business_unit,
                ppf.report_mapping,
                ppf.calculation_type,
                LOWER("metric_name") AS metric_name,
                "value"
         FROM _pre_pivot_forecast AS ppf
             UNPIVOT (
             "value" FOR "metric_name" IN (
                 cash_gross_revenue,
                 cash_net_revenue,
                 cash_gross_profit,
                 cash_gross_profit_percent_of_net_cash,
                 cash_net_revenue_with_budgeted_fx_rates,
                 activating_cash_gross_revenue,
                 activating_cash_net_revenue,
                 nonactivating_cash_gross_revenue,
                 nonactivating_cash_net_revenue,
                 product_order_and_billing_cash_refund,
                 product_order_and_billing_chargebacks,
                 refund_chargebacks_as_percent_of_cash_gross_rev,
                 activating_product_gross_revenue,
                 activating_product_net_revenue,
                 activating_shipping_revenue,
                 activating_product_order_count,
                 activating_product_order_count_excl_seeding,
                 activating_product_margin_pre_return_excl_seeding,
                 activating_aov,
                 activating_unit_count,
                 activating_upt,
                 activating_aur,
                 activating_auc_incl_reship_exch,
                 activating_discount_percent,
                 planning_activating_discount_percent,
                 activating_product_gross_profit,
                 activating_product_gross_profit_per_order,
                 nonactivating_product_gross_profit_per_order,
                 activating_product_gross_profit_percent,
                 activating_product_order_cash_gross_revenue,
                 activating_product_margin_pre_return,
                 activating_product_margin_pre_return_per_order,
                 nonactivating_product_margin_pre_return_per_order,
                 activating_product_margin_pre_return_percent,
                 nonactivating_product_gross_revenue,
                 nonactivating_product_net_revenue,
                 nonactivating_cash_revenue_as_percent_of_product_gross_revenue,
                 nonactivating_shipping_revenue,
                 nonactivating_product_order_count,
                 nonactivating_product_order_count_excl_seeding,
                 nonactivating_product_margin_pre_return_excl_seeding,
                 nonactivating_aov,
                 nonactivating_unit_count,
                 nononactivating_upt,
                 nonactivating_aur,
                 nonactivating_auc_incl_reship_exch,
                 nonactivating_discount_percent,
                 planning_nonactivating_discount_percent,
                 nonactivating_product_gross_profit,
                 nonactivating_product_gross_profit_percent,
                 nonactivating_product_order_cash_gross_profit,
                 nonactivating_product_order_cash_gross_profit_per_order,
                 nonactivating_product_order_cash_gross_revenue,
                 guest_orders_as_percent_of_non_activating,
                 guest_product_net_revenue,
                 guest_product_order_count,
                 guest_product_order_count_excl_seeding,
                 guest_product_margin_pre_return_excl_seeding,
                 guest_aov,
                 guest_product_gross_profit,
                 guest_product_gross_revenue,
                 guest_shipping_revenue,
                 guest_unit_count,
                 guest_upt,
                 guest_aur,
                 guest_discount_percent,
                 planning_guest_discount_percent,
                 guest_product_gross_profit_percent,
                 planning_repeat_vip_discount_percent,
                 billed_credit_cash_transaction_amount,
                 billed_credit_cash_refund_chargeback_amount,
                 billed_cash_credit_redeemed_amount,
                 same_month_billed_credit_redeemed,
                 billed_credit_net_billings,
                 net_credit_billings_as_percent_of_cash_net_revenue,
                 billed_credits_successful_on_first_try,
                 billed_credits_successful_on_retry,
                 billed_credit_cash_transaction_count,
                 membership_fee_cash_transaction_amount,
                 gift_card_transaction_amount,
                 legacy_credit_cash_transaction_amount,
                 other_billing_cash_transaction_amount,
                 membership_fee_cash_refund_chargeback_amount,
                 membership_fee_net_cash_transaction_amount,
                 outbound_product_cost_incl_reship_exch,
                 oracle_outbound_product_cost_incl_reship_exch,
                 product_order_count_incl_reship_exch,
                 unit_count_incl_reship_exch,
                 auc_incl_reship_exch,
                 product_cost_returned_resaleable_incl_reship_exch,
                 product_cost_returned_damaged_incl_reship_exch,
                 product_cost_net_of_returns_incl_reship_exch,
                 shipped_cost_incl_reship_exch,
                 shipping_supplies_cost_incl_reship_exch,
                 return_shipping_costs_incl_reship_exch,
                 misc_cogs_amount,
                 total_cogs,
                 oracle_total_cogs,
                 pending_product_order_count,
                 eop_vips,
                 product_order_return_unit_count,
                 pending_order_cash_transaction_amount,
                 pending_order_cash_margin_pre_return_amount,
                 product_order_cash_credit_refund_amount,
                 product_order_cash_credit_refund_net_billings,
                 noncash_credit_issued_amount,
                 product_order_noncash_credit_redeemed_amount,
                 shipping_cost_per_order,
                 reactivated_vip_product_order_percent,
                 nonactivating_cash_discount_percent,
                 nonactivating_non_token_unit_percent,
                 nonactivating_guest_product_order_percent
                 ))

         UNION ALL

         SELECT ppb.date,
                ppb.date_object,
                ppb.currency_object,
                ppb.currency_type,
                ppb.store_brand,
                ppb.business_unit,
                ppb.report_mapping,
                ppb.calculation_type,
                LOWER("metric_name") AS metric_name,
                "value"
         FROM _pre_pivot_budget AS ppb
             UNPIVOT (
             "value" FOR "metric_name" IN (
                 cash_gross_revenue,
                 cash_net_revenue,
                 cash_gross_profit,
                 cash_gross_profit_percent_of_net_cash,
                 cash_net_revenue_with_budgeted_fx_rates,
                 activating_cash_gross_revenue,
                 activating_cash_net_revenue,
                 nonactivating_cash_gross_revenue,
                 nonactivating_cash_net_revenue,
                 product_order_and_billing_cash_refund,
                 product_order_and_billing_chargebacks,
                 refund_chargebacks_as_percent_of_cash_gross_rev,
                 activating_product_gross_revenue,
                 activating_product_net_revenue,
                 activating_shipping_revenue,
                 activating_product_order_count,
                 activating_product_order_count_excl_seeding,
                 activating_product_margin_pre_return_excl_seeding,
                 activating_aov,
                 activating_unit_count,
                 activating_upt,
                 activating_aur,
                 activating_auc_incl_reship_exch,
                 activating_discount_percent,
                 planning_activating_discount_percent,
                 activating_product_gross_profit,
                 activating_product_gross_profit_per_order,
                 nonactivating_product_gross_profit_per_order,
                 activating_product_gross_profit_percent,
                 activating_product_order_cash_gross_revenue,
                 activating_product_margin_pre_return,
                 activating_product_margin_pre_return_per_order,
                 nonactivating_product_margin_pre_return_per_order,
                 activating_product_margin_pre_return_percent,
                 nonactivating_product_gross_revenue,
                 nonactivating_product_net_revenue,
                 nonactivating_cash_revenue_as_percent_of_product_gross_revenue,
                 nonactivating_shipping_revenue,
                 nonactivating_product_order_count,
                 nonactivating_product_order_count_excl_seeding,
                 nonactivating_product_margin_pre_return_excl_seeding,
                 nonactivating_aov,
                 nonactivating_unit_count,
                 nononactivating_upt,
                 nonactivating_aur,
                 nonactivating_auc_incl_reship_exch,
                 nonactivating_discount_percent,
                 planning_nonactivating_discount_percent,
                 nonactivating_product_gross_profit,
                 nonactivating_product_gross_profit_percent,
                 nonactivating_product_order_cash_gross_profit,
                 nonactivating_product_order_cash_gross_profit_per_order,
                 nonactivating_product_order_cash_gross_revenue,
                 guest_orders_as_percent_of_non_activating,
                 guest_product_net_revenue,
                 guest_product_order_count,
                 guest_product_order_count_excl_seeding,
                 guest_product_margin_pre_return_excl_seeding,
                 guest_aov,
                 guest_product_gross_profit,
                 guest_product_gross_revenue,
                 guest_shipping_revenue,
                 guest_unit_count,
                 guest_upt,
                 guest_aur,
                 guest_discount_percent,
                 planning_guest_discount_percent,
                 guest_product_gross_profit_percent,
                 planning_repeat_vip_discount_percent,
                 billed_credit_cash_transaction_amount,
                 billed_credit_cash_refund_chargeback_amount,
                 billed_cash_credit_redeemed_amount,
                 same_month_billed_credit_redeemed,
                 billed_credit_net_billings,
                 net_credit_billings_as_percent_of_cash_net_revenue,
                 billed_credits_successful_on_first_try,
                 billed_credits_successful_on_retry,
                 billed_credit_cash_transaction_count,
                 membership_fee_cash_transaction_amount,
                 gift_card_transaction_amount,
                 legacy_credit_cash_transaction_amount,
                 other_billing_cash_transaction_amount,
                 membership_fee_cash_refund_chargeback_amount,
                 membership_fee_net_cash_transaction_amount,
                 outbound_product_cost_incl_reship_exch,
                 oracle_outbound_product_cost_incl_reship_exch,
                 product_order_count_incl_reship_exch,
                 unit_count_incl_reship_exch,
                 auc_incl_reship_exch,
                 product_cost_returned_resaleable_incl_reship_exch,
                 product_cost_returned_damaged_incl_reship_exch,
                 product_cost_net_of_returns_incl_reship_exch,
                 shipped_cost_incl_reship_exch,
                 shipping_supplies_cost_incl_reship_exch,
                 return_shipping_costs_incl_reship_exch,
                 misc_cogs_amount,
                 total_cogs,
                 oracle_total_cogs,
                 pending_product_order_count,
                 eop_vips,
                 product_order_return_unit_count,
                 pending_order_cash_transaction_amount,
                 pending_order_cash_margin_pre_return_amount,
                 product_order_cash_credit_refund_amount,
                 product_order_cash_credit_refund_net_billings,
                 noncash_credit_issued_amount,
                 product_order_noncash_credit_redeemed_amount,
                 shipping_cost_per_order,
                 reactivated_vip_product_order_percent,
                 nonactivating_cash_discount_percent,
                 nonactivating_non_token_unit_percent,
                 nonactivating_guest_product_order_percent
                 ))
     ),
     percentage_metrics AS (
         SELECT *
         FROM (VALUES ('cash_gross_profit_percent_of_net_cash'),
                      ('refund_chargebacks_as_percent_of_cash_gross_rev'),
                      ('activating_discount_percent'),
                      ('planning_activating_discount_percent'),
                      ('activating_product_gross_profit_percent'),
                      ('activating_product_margin_pre_return_percent'),
                      ('nonactivating_cash_revenue_as_percent_of_product_gross_revenue'),
                      ('nonactivating_discount_percent'),
                      ('planning_nonactivating_discount_percent'),
                      ('nonactivating_product_gross_profit_percent'),
                      ('guest_orders_as_percent_of_non_activating'),
                      ('guest_discount_percent'),
                      ('planning_guest_discount_percent'),
                      ('guest_product_gross_profit_percent'),
                      ('planning_repeat_vip_discount_percent'),
                      ('net_credit_billings_as_percent_of_cash_net_revenue'),
                      ('nonactivating_cash_discount_percent'),
                      ('nonactivating_non_token_unit_percent'),
                      ('nonactivating_guest_product_order_percent')
                  )
     ),
     _pivot_output AS (
         SELECT pt.date,
                pt.date_object,
                pt.currency_object,
                pt.currency_type,
                pt.store_brand,
                pt.business_unit,
                pt.report_mapping,
                pt.calculation_type,
                mnl.column2                                             AS metric_name,
                CASE
                    WHEN pt.metric_name IN (SELECT * FROM percentage_metrics) THEN pt."value" * 100
                    ELSE pt."value"
                    END                                                 AS value_num,
                trim(to_varchar(round(value_num, 2), '999,999,999.00')) AS value_str,
                (rr."value" - pt."value") / nullifzero(pt."value")      AS variance
         FROM _pivoted_table AS pt
                  LEFT JOIN _pivoted_table AS rr
                            ON pt.date_object = rr.date_object
                                AND pt.currency_object = rr.currency_object
                                AND pt.currency_type = rr.currency_type
                                AND pt.store_brand = rr.store_brand
                                AND pt.business_unit = rr.business_unit
                                AND pt.report_mapping = rr.report_mapping
                                AND pt.metric_name = rr.metric_name
                                AND rr.calculation_type = 'Run Rate'
                  LEFT JOIN _metric_name_lookup AS mnl
                            ON pt.metric_name = mnl.column1
     ),
     _missing_mappings AS (
         SELECT DISTINCT date_object,
                         currency_object,
                         currency_type,
                         store_brand,
                         business_unit,
                         report_mapping,
                         metric_name
         FROM _pivot_output
         WHERE calculation_type IS NULL
           AND report_mapping IS NOT NULL
     )
SELECT po.date,
       date_trunc(MONTH, po.date) AS associated_date,
       po.date_object,
       po.currency_object,
       po.currency_type,
       po.store_brand,
       po.business_unit,
       po.report_mapping,
       po.calculation_type,
       po.calculation_type        AS calculation_type_associated,
       po.metric_name,
       po.value_num,
       po.value_str,
       CASE
           WHEN po.calculation_type = 'Month Totals' THEN 0
           WHEN po.calculation_type IN ('Forecast', 'Budget')
               AND date_trunc(MONTH, po.date) < date_trunc(MONTH, getdate()::DATE)
               THEN (ifnull(v.value_num,mtd.value_num) - po.value_num) / abs(nullifzero(po.value_num))
           ELSE po.variance END   AS variance
FROM _pivot_output po
         LEFT JOIN _pivot_output v
                   ON date_trunc(MONTH, po.date) = v.date
                       AND po.date_object = v.date_object
                       AND po.currency_object = v.currency_object
                       AND po.currency_type = v.currency_type
                       AND po.store_brand = v.store_brand
                       AND po.business_unit = v.business_unit
                       AND po.report_mapping = v.report_mapping
                       AND po.metric_name = v.metric_name
                       AND v.calculation_type = 'Month Totals'
         LEFT JOIN _pivot_output mtd
                   ON po.date = date_trunc(month,mtd.date)
                       AND po.date_object = mtd.date_object
                       AND po.currency_object = mtd.currency_object
                       AND po.currency_type = mtd.currency_type
                       AND po.store_brand = mtd.store_brand
                       AND po.business_unit = mtd.business_unit
                       AND po.report_mapping = mtd.report_mapping
                       AND po.metric_name = mtd.metric_name
                       AND mtd.calculation_type = 'MTD'
WHERE po.calculation_type IS NOT NULL

UNION ALL

SELECT po.date,
       dateadd('month', 1, po.date) AS associated_date,
       po.date_object,
       po.currency_object,
       po.currency_type,
       po.store_brand,
       po.business_unit,
       po.report_mapping,
       po.calculation_type,
       'Last Month'                 AS calculation_type_associated,
       po.metric_name,
       po.value_num,
       po.value_str,
       CASE
           WHEN dateadd('month', 1, po.date) < date_trunc(MONTH, getdate()::DATE)
               THEN (ifnull(v.value_num,mtd.value_num) - po.value_num) / abs(nullifzero(po.value_num))
           ELSE po.variance END     AS variance
FROM _pivot_output po
         LEFT JOIN _pivot_output v
                   ON dateadd('month', 1, po.date) = v.date
                       AND po.date_object = v.date_object
                       AND po.currency_object = v.currency_object
                       AND po.currency_type = v.currency_type
                       AND po.store_brand = v.store_brand
                       AND po.business_unit = v.business_unit
                       AND po.report_mapping = v.report_mapping
                       AND po.metric_name = v.metric_name
                       AND v.calculation_type = 'Month Totals'
         LEFT JOIN _pivot_output mtd
                   ON  dateadd('month', 1, po.date) = date_trunc(month,mtd.date)
                       AND po.date_object = mtd.date_object
                       AND po.currency_object = mtd.currency_object
                       AND po.currency_type = mtd.currency_type
                       AND po.store_brand = mtd.store_brand
                       AND po.business_unit = mtd.business_unit
                       AND po.report_mapping = mtd.report_mapping
                       AND po.metric_name = mtd.metric_name
                       AND mtd.calculation_type = 'MTD'
WHERE po.calculation_type = 'Month Totals'
  AND associated_date < getdate()::DATE

UNION ALL

SELECT po.date,
       dateadd('year', 1, po.date) AS associated_date,
       po.date_object,
       po.currency_object,
       po.currency_type,
       po.store_brand,
       po.business_unit,
       po.report_mapping,
       po.calculation_type,
       'Last Year'                 AS calculation_type_associated,
       po.metric_name,
       po.value_num,
       po.value_str,
       CASE
           WHEN dateadd('year', 1, po.date) < date_trunc(MONTH, getdate()::DATE)
               THEN (ifnull(v.value_num,mtd.value_num) - po.value_num) / abs(nullifzero(po.value_num))
           ELSE po.variance END    AS variance
FROM _pivot_output po
         LEFT JOIN _pivot_output v
                   ON dateadd('year', 1, po.date) = v.date
                       AND po.date_object = v.date_object
                       AND po.currency_object = v.currency_object
                       AND po.currency_type = v.currency_type
                       AND po.store_brand = v.store_brand
                       AND po.business_unit = v.business_unit
                       AND po.report_mapping = v.report_mapping
                       AND po.metric_name = v.metric_name
                       AND v.calculation_type = 'Month Totals'
         LEFT JOIN _pivot_output mtd
                   ON  dateadd('year', 1, po.date) = date_trunc(month,mtd.date)
                       AND po.date_object = mtd.date_object
                       AND po.currency_object = mtd.currency_object
                       AND po.currency_type = mtd.currency_type
                       AND po.store_brand = mtd.store_brand
                       AND po.business_unit = mtd.business_unit
                       AND po.report_mapping = mtd.report_mapping
                       AND po.metric_name = mtd.metric_name
                       AND mtd.calculation_type = 'MTD'
WHERE po.calculation_type = 'Month Totals'
  AND associated_date < getdate()::DATE


UNION ALL

SELECT (SELECT MAX(date) FROM _pivot_output) AS date,
       (SELECT MAX(date) FROM _pivot_output) AS associated_date,
       mm.date_object,
       mm.currency_object,
       mm.currency_type,
       mm.store_brand,
       mm.business_unit,
       mm.report_mapping,
       ''                                    AS calculation_type,
       ''                                    AS calculation_type_associated,
       mm.metric_name,
       NULL                                  AS value_num,
       NULL                                  AS value_str,
       NULL                                  AS variance
FROM _missing_mappings mm
    LEFT JOIN _pivot_output po
ON po.date_object = mm.date_object
    AND po.currency_object = mm.currency_object
    AND po.currency_type = mm.currency_type
    AND po.store_brand = mm.store_brand
    AND po.business_unit = mm.business_unit
    AND po.report_mapping = mm.report_mapping
    AND po.metric_name = mm.metric_name
    AND po.calculation_type IS NOT NULL
WHERE po.date_object IS NULL;
