from include.utils.acquisition.lake_consolidated_table_config import (
    LakeConsolidatedTableConfig as TableConfig,
)
from include.utils.snowflake import Column

table_config = TableConfig(
    schema="ultra_rollup",
    table="products_in_stock_product_feed",
    company_join_sql="""
    SELECT DISTINCT
        L.product_id,
        DS.company_id
    FROM {database}.REFERENCE.DIM_STORE AS DS
    INNER JOIN {database}.{source_schema}.products_in_stock_product_feed AS L
        ON L.MASTER_STORE_GROUP_ID = DS.STORE_GROUP_ID
    """,
    column_list=[
        Column("product_id", "INT", uniqueness=True, key=True),
        Column("master_product_id", "INT", key=True),
        Column("master_store_group_id", "INT"),
        Column("store_group_id", "INT"),
        Column("item_number", "VARCHAR(30)"),
        Column("item_id", "INT", key=True),
        Column("item_group_id", "INT"),
        Column("alias", "VARCHAR(100)"),
        Column("style", "VARCHAR(255)"),
        Column("product_color", "VARCHAR(255)"),
        Column("product_colors", "VARCHAR"),
        Column("google_product_colors", "VARCHAR"),
        Column("bundle_color_tag_id_list", "VARCHAR(255)"),
        Column("bundle_color_tag_list", "VARCHAR"),
        Column("related_color_tag_id_list", "VARCHAR(255)"),
        Column("related_color_tag_list", "VARCHAR"),
        Column("master_statuscode", "INT"),
        Column("statuscode", "INT"),
        Column("is_active", "BOOLEAN"),
        Column("brand_name", "VARCHAR(100)"),
        Column("has_plus_size", "BOOLEAN"),
        Column("is_plus_size", "BOOLEAN"),
        Column("product_sku", "VARCHAR(100)"),
        Column("regular_size_sku", "VARCHAR(100)"),
        Column("plus_size_sku", "VARCHAR(100)"),
        Column("label", "VARCHAR(100)"),
        Column("label_instance", "VARCHAR(100)"),
        Column("group_code", "VARCHAR(50)"),
        Column("short_description", "VARCHAR(1000)"),
        Column("medium_description", "VARCHAR(2000)"),
        Column("long_description", "VARCHAR"),
        Column("condition", "VARCHAR(10)"),
        Column("language_id", "INT"),
        Column("resource_bundle_id", "INT"),
        Column("inseam", "VARCHAR(50)"),
        Column("gender", "VARCHAR(50)"),
        Column("age_group", "VARCHAR(50)"),
        Column("default_product_category_id", "INT", key=True),
        Column("default_product_category_label", "VARCHAR(50)"),
        Column("default_product_category_hierarchy", "VARCHAR"),
        Column("product_type", "VARCHAR(50)"),
        Column("product_type_hierarchy", "VARCHAR"),
        Column("retail_unit_price", "NUMBER(19, 4)"),
        Column("default_unit_price", "NUMBER(19, 4)"),
        Column("sale_unit_price", "NUMBER(19, 4)"),
        Column("availability", "VARCHAR(50)"),
        Column("available_quantity", "INT"),
        Column("available_quantity_default", "INT"),
        Column("available_quantity_ca", "INT"),
        Column("available_quantity_preorder", "INT"),
        Column("available_quantity_preorder_default", "INT"),
        Column("available_quantity_preorder_ca", "INT"),
        Column("date_inventory_available", "TIMESTAMP_NTZ(3)"),
        Column("date_inventory_available_default", "TIMESTAMP_NTZ(3)"),
        Column("date_inventory_available_ca", "TIMESTAMP_NTZ(3)"),
        Column('"RELEASE_DATE_DD/MM/YYYY"', "VARCHAR(10)"),
        Column("sales_count_10_days", "INT"),
        Column("sales_count_conversions_10_days", "INT"),
        Column("coo", "VARCHAR(2)"),
        Column("permalink", "VARCHAR(255)"),
        Column("image_count", "INT"),
        Column("catwalk_video", "VARCHAR"),
        Column("is_bundle_product", "BOOLEAN"),
        Column("is_outfit", "BOOLEAN"),
        Column("product_type_id", "INT"),
        Column("product_type_label", "VARCHAR(100)"),
        Column("google_product_id", "INT"),
        Column("size", "VARCHAR(100)"),
        Column("size_type", "VARCHAR(10)"),
        Column("size_system_code", "VARCHAR(4)"),
        Column("is_sheer", "BOOLEAN"),
        Column("is_use_laydown", "BOOLEAN"),
        Column("is_membership_exclusive", "BOOLEAN"),
        Column("is_wide_width", "BOOLEAN"),
        Column("is_wide_calf", "BOOLEAN"),
        Column("season", "VARCHAR"),
        Column("occasion", "VARCHAR"),
        Column("activity", "VARCHAR"),
        Column("weather", "VARCHAR"),
        Column("shoe_style", "VARCHAR"),
        Column("product_detail", "VARCHAR"),
        Column("inventory_classification", "VARCHAR"),
        Column("silhouette", "VARCHAR"),
        Column("collection", "VARCHAR"),
        Column("personality_type", "VARCHAR"),
        Column("material", "VARCHAR"),
        Column("pattern", "VARCHAR"),
        Column("currency_code", "VARCHAR(3)"),
        Column("component_product_id_list", "VARCHAR"),
        Column("image_link", "VARCHAR"),
        Column("additional_image_link_1", "VARCHAR"),
        Column("additional_image_link_2", "VARCHAR"),
        Column("additional_image_link_3", "VARCHAR"),
        Column("additional_image_link_4", "VARCHAR"),
        Column("additional_image_link_5", "VARCHAR"),
        Column("laydown_image_link", "VARCHAR"),
        Column("product_link", "VARCHAR"),
        Column("mobile_link", "VARCHAR"),
        Column("rollup_datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("rollup_datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("rollup_datetime_verified", "TIMESTAMP_NTZ(3)"),
        Column("rollup_datetime_last_active_status", "TIMESTAMP_NTZ(3)"),
        Column("row_checksum", "BINARY"),
        Column("date_expected", "TIMESTAMP_NTZ(3)"),
        Column("featured_product_location_id_list", "VARCHAR"),
        Column("master_item_number", "VARCHAR(30)"),
        Column("vimeo_video", "VARCHAR"),
        Column("average_review", "DOUBLE"),
        Column("review_count", "INT"),
        Column("product_tag_id_list", "VARCHAR"),
        Column("product_category_id_list", "VARCHAR"),
        Column("inventory", "VARCHAR"),
        Column("sales_count_1_day", "INT"),
        Column("sales_count_5_days", "INT"),
        Column("sales_count_conversions_1_day", "INT"),
        Column("sales_count_conversions_5_days", "INT"),
        Column("token_redemption_quantity", "INT"),
        Column("vimeo_video2", "VARCHAR"),
        Column("membership_brand_id", "INT"),
        Column("product_tag_label_list", "VARCHAR"),
        Column("product_category_label_list", "VARCHAR"),
        Column("vimeo_video_live_shopping_id", "VARCHAR"),
        Column("social_media_image", "VARCHAR"),
        Column("meta_description_override", "VARCHAR"),
        Column("is_warehouse_product", "INT"),
        Column("warehouse_unit_price", "NUMBER(19,4)"),
        Column("retail_outlet_unit_price", "NUMBER(19,4)"),
        Column("fulfillment_partner_id", "INT"),
        Column("product_permalink", "VARCHAR"),
    ],
    watermark_column="rollup_datetime_modified",
)
