from include.utils.acquisition.lake_consolidated_table_config import (
    LakeConsolidatedTableConfig as TableConfig,
)
from include.utils.snowflake import Column

table_config = TableConfig(
    table='products_in_stock_master',
    schema='ultra_rollup',
    company_join_sql="""
    SELECT DISTINCT
         L.master_product_id,
         DS.company_id
     FROM {database}.REFERENCE.DIM_STORE AS DS
     INNER JOIN {database}.{source_schema}.products_in_stock_master AS L
         ON DS.STORE_GROUP_ID = L.MASTER_STORE_GROUP_ID
    """,
    column_list=[
        Column('master_product_id', 'INT', uniqueness=True, key=True),
        Column('product_type_id', 'INT'),
        Column('master_store_group_id', 'INT'),
        Column('store_group_id', 'INT'),
        Column('item_number', 'VARCHAR(30)'),
        Column('alias', 'VARCHAR(100)'),
        Column('master_statuscode', 'INT'),
        Column('is_active', 'BOOLEAN'),
        Column('is_master', 'BOOLEAN'),
        Column('available_quantity_master', 'INT'),
        Column('available_quantity_master_default', 'INT'),
        Column('available_quantity_master_ca', 'INT'),
        Column('available_quantity_group', 'INT'),
        Column('available_quantity_group_default', 'INT'),
        Column('available_quantity_group_ca', 'INT'),
        Column('available_quantity_preorder_master', 'INT'),
        Column('available_quantity_preorder_master_default', 'INT'),
        Column('available_quantity_preorder_master_ca', 'INT'),
        Column('group_code', 'VARCHAR(50)'),
        Column('label', 'VARCHAR(100)'),
        Column('short_description', 'VARCHAR(1000)'),
        Column('medium_description', 'VARCHAR(2000)'),
        Column('long_description', 'VARCHAR'),
        Column('default_product_category_id', 'INT'),
        Column('default_product_category_label', 'VARCHAR(50)'),
        Column('retail_unit_price', 'NUMBER(19, 4)'),
        Column('default_unit_price', 'NUMBER(19, 4)'),
        Column('sale_unit_price', 'NUMBER(19, 4)'),
        Column('brand_id', 'INT', key=True),
        Column('brand_label', 'VARCHAR(100)'),
        Column('post_reg_only', 'INT'),
        Column('sales_rank_1_day', 'INT'),
        Column('sales_count_1_day', 'INT'),
        Column('sales_count_conversions_5_days', 'INT'),
        Column('sales_count_conversions_10_days', 'INT'),
        Column('sales_rank_10_days', 'INT'),
        Column('sales_count_10_days', 'INT'),
        Column('rating_rank', 'INT'),
        Column('latest_rank', 'INT'),
        Column('review_rank', 'INT'),
        Column('date_expected', 'TIMESTAMP_NTZ(3)'),
        Column('date_expected_group_code', 'TIMESTAMP_NTZ(3)'),
        Column('date_sale_expires', 'TIMESTAMP_NTZ(3)'),
        Column('related_product_count', 'INT'),
        Column('permissions_flag', 'INT'),
        Column('product_category_id_list', 'VARCHAR'),
        Column('featured_product_location_id_list', 'VARCHAR'),
        Column('product_option_id_list', 'VARCHAR'),
        Column('permalink', 'VARCHAR(255)'),
        Column('daily_fix_active', 'BOOLEAN'),
        Column('date_sale_rank', 'INT'),
        Column('review_group', 'VARCHAR(100)'),
        Column('average_review', 'DOUBLE'),
        Column('review_count', 'DOUBLE'),
        Column('recommended_count', 'DOUBLE'),
        Column('recommended_percentage', 'DOUBLE'),
        Column('group_code_rating_rank', 'INT'),
        Column('group_code_latest_rank', 'INT'),
        Column('group_code_sales_rank', 'INT'),
        Column('include_in_site_search', 'BOOLEAN'),
        Column('image_count', 'INT'),
        Column('has_plus_size', 'BOOLEAN'),
        Column('default_warehouse_id', 'INT'),
        Column('available_quantity_any_profile', 'INT'),
        Column('retail_pricing_id', 'INT'),
        Column('retail_store_unit_price', 'NUMBER(19, 4)'),
        Column('current_cost', 'NUMBER(19, 4)'),
        Column('profit_margin', 'NUMBER(19, 4)'),
        Column('margin_percentage', 'DOUBLE'),
        Column('markup_percentage', 'DOUBLE'),
        Column('sku', 'VARCHAR(100)'),
        Column('plus_size_sku', 'VARCHAR(100)'),
        Column('rollup_datetime_added', 'TIMESTAMP_NTZ(3)'),
        Column('rollup_datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('rollup_datetime_verified', 'TIMESTAMP_NTZ(3)'),
        Column('row_checksum', 'BINARY'),
        Column('color', 'VARCHAR(100)'),
        Column('average_review_all_stores', 'DOUBLE'),
        Column('is_bundle_product', 'BOOLEAN'),
        Column('regular_size_sku', 'VARCHAR(100)'),
        Column('gender', 'VARCHAR(50)'),
        Column('brand_name', 'VARCHAR(100)'),
        Column('product_type_label', 'VARCHAR(50)'),
        Column('base_sku', 'VARCHAR(100)'),
        Column('store_region', 'VARCHAR(10)'),
        Column('store_region_group', 'VARCHAR(10)'),
        Column('pdp_url', 'VARCHAR'),
        Column('is_component_product', 'BOOLEAN'),
        Column('bundle_separate_retail_unit_price', 'NUMBER(19, 4)'),
        Column('bundle_separate_default_unit_price', 'NUMBER(19, 4)'),
        Column('pricing_option_id', 'INT'),
        Column('shipping_price', 'NUMBER(19, 4)'),
        Column('date_preorder_expires', 'TIMESTAMP_NTZ(3)'),
        Column('product_option_count', 'INT'),
        Column('sales_count_5_days', 'INT'),
        Column('sales_count_conversions_1_day', 'INT'),
        Column('average_overall_review', 'DOUBLE'),
        Column('average_overall_review_all_stores', 'DOUBLE'),
        Column('token_redemption_quantity', 'INT'),
        Column('sales_rank_5_days', 'INT'),
        Column('sale_pricing_id', 'INT'),
        Column('default_pricing_id', 'INT'),
        Column('average_overall_review_filtered_stores', 'DOUBLE'),
        Column('image_main_link', 'VARCHAR'),
        Column('image_hover_link', 'VARCHAR'),
        Column('sum_pricing', 'INT'),
        Column('membership_brand_id', 'INT'),
        Column('bundle_available_quantity_accessory', 'INT'),
        Column('bundle_available_quantity_accessory_preorder', 'INT'),
        Column('is_token', 'INT'),
        Column('customization_configuration_id', 'INT'),
        Column('company_id', 'INT'),
        Column('available_quantity_accessory', 'INT'),
        Column('review_count_filtered_stores', 'INT'),
        Column('image_test_flag', 'BOOLEAN'),
        Column('reward_point_price', 'INT'),
        Column('fulfillment_partner_id', 'INT'),
        Column('inventory_breakage_percentage', 'INT'),
    ],
    watermark_column='rollup_datetime_modified',
)
