CREATE OR REPLACE VIEW engineering.segment.vw_segmentqa_sxf_us_qa_order_completed AS
SELECT DISTINCT
    to_timestamp(RECORD_METADATA:CreateTime::string) AS create_time,
    RECORD_METADATA:key::string AS key,
    RECORD_METADATA:offset::NUMBER(38,0) AS offset,
    RECORD_METADATA:partition::NUMBER(38,0) AS partition,
    RECORD_METADATA:topic::string AS topic,
    RECORD_CONTENT:correlationid::string AS correlation_id,
    parse_json(RECORD_CONTENT:data):automated_test::STRING AS automated_test,
    parse_json(RECORD_CONTENT:data):correlation_id::STRING AS data_correlation_id,
    parse_json(RECORD_CONTENT:data):credit::NUMBER(38,2) AS credit,
    parse_json(RECORD_CONTENT:data):currency::STRING AS currency,
    parse_json(RECORD_CONTENT:data):customer_bucket_group::NUMBER(38,0) AS customer_bucket_group,
    parse_json(RECORD_CONTENT:data):customer_gender::STRING AS customer_gender,
    parse_json(RECORD_CONTENT:data):customer_id::NUMBER(38,0) AS customer_id,
    parse_json(RECORD_CONTENT:data):customer_ip::STRING AS customer_ip,
    parse_json(RECORD_CONTENT:data):discount::NUMBER(38,2) AS discount,
    parse_json(RECORD_CONTENT:data):dmg_code::STRING AS dmg_code,
    parse_json(RECORD_CONTENT:data):error::STRING AS error,
    parse_json(RECORD_CONTENT:data):feature::STRING AS feature,
    parse_json(RECORD_CONTENT:data):is_activating::STRING AS is_activating,
    parse_json(RECORD_CONTENT:data):loggedin_status::STRING AS loggedin_status,
    parse_json(RECORD_CONTENT:data):membership_status::STRING AS membership_status,
    parse_json(RECORD_CONTENT:data):order_id::STRING AS order_id,
    parse_json(RECORD_CONTENT:data):page_hostname::STRING AS page_hostname,
    parse_json(RECORD_CONTENT:data):products::STRING AS products,
    parse_json(RECORD_CONTENT:data):revenue::NUMBER(38,2) AS revenue,
    parse_json(RECORD_CONTENT:data):session_id::NUMBER(38,0) AS session_id,
    parse_json(RECORD_CONTENT:data):sha_email::STRING AS sha_email,
    parse_json(RECORD_CONTENT:data):shipping::NUMBER(38,2) AS shipping,
    parse_json(RECORD_CONTENT:data):store_group_id::NUMBER(38,0) AS store_group_id,
    parse_json(RECORD_CONTENT:data):store_id::NUMBER(38,0) AS store_id,
    parse_json(RECORD_CONTENT:data):subtotal::NUMBER(38,2) AS subtotal,
    parse_json(RECORD_CONTENT:data):tax::NUMBER(38,2) AS tax,
    parse_json(RECORD_CONTENT:data):total::NUMBER(38,2) AS total,
    parse_json(RECORD_CONTENT:data):visitor_group::STRING AS visitor_group,
    parse_json(RECORD_CONTENT:data):visitor_id::STRING AS visitor_id,
    RECORD_CONTENT:datacontenttype::string AS data_content_type,
    RECORD_CONTENT:date::date AS date,
    RECORD_CONTENT:id::string AS id,
    RECORD_CONTENT:ip::string AS ip,
    RECORD_CONTENT:source::string AS source,
    RECORD_CONTENT:specversion::NUMBER(38,0) AS spec_version,
    RECORD_CONTENT:status::string AS status,
    RECORD_CONTENT:subject::string AS subject,
    RECORD_CONTENT:success::string AS success,
    RECORD_CONTENT:time::timestamp AS time,
    RECORD_CONTENT:type::string AS type
FROM engineering.segment.segmentqa_sxf_us_qa_order_completed
  , LATERAL FLATTEN (input => RECORD_METADATA) a
  , LATERAL FLATTEN (input => RECORD_CONTENT) b;
