TRUNCATE TABLE reporting_media_base_prod.lkp.channel_display_name;
INSERT INTO reporting_media_base_prod.lkp.channel_display_name
SELECT
    $1 AS channel_key,
    $2 AS channel_name,
    $3 as channel_type,
    seq4() AS sequence
FROM
VALUES
    ('ALL','ALL','Paid+Organic'),
    ('affiliate', 'Affiliate','Paid'),
    ('applovin', 'AppLovin','Paid'),
    ('branded search', 'Branded Search','Paid'),
    ('celebrity', 'Celebrity','Organic'),
    ('crm', 'CRM','Organic'),
    ('direct traffic', 'Direct Traffic','Organic'),
    ('friend', 'Friend','Organic'),
    ('google other', 'Google Other','Paid'),
    ('influencers', 'Influencers','Paid'),
    ('linkedin', 'LinkedIn','Paid'),
    ('meta', 'Meta','Paid'),
    ('metanav', 'Metanav','Organic'),
    ('nift', 'NIFT','Paid'),
    ('non branded search', 'Non Branded Search','Paid'),
    ('ooh', 'OOH','Paid'),
    ('organic', 'Organic', 'Organic'),
    ('organic press', 'Organic Press', 'Organic'),
    ('organic search', 'Organic Search','Organic'),
    ('organic social', 'Organic Social','Organic'),
    ('physical partnerships', 'Physical Partnerships', 'Paid'),
    ('pinterest', 'Pinterest','Paid'),
    ('print', 'Print','Paid'),
    ('programmatic', 'Programmatic','Paid'),
    ('radio/podcast', 'Radio/Podcast','Paid'),
    ('reddit','Reddit','Paid'),
    ('referral', 'Referral','Organic'),
    ('retail', 'Retail','Paid'),
    ('rokt', 'ROKT','Paid'),
    ('shopping', 'Shopping','Paid'),
    ('snapchat', 'Snapchat','Paid'),
    ('testing','Testing','Paid'),
    ('tiktok','TikTok','Paid'),
    ('tv+streaming', 'TV+Streaming','Paid'),
    ('twitch', 'Twitch','Paid'),
    ('twitter','Twitter','Paid'),
    ('unclassified', 'Unclassified','Organic'),
    ('youtube', 'Youtube','Paid');
