TRUNCATE TABLE reporting_media_base_prod.lkp.subchannel_display_name;
INSERT INTO reporting_media_base_prod.lkp.subchannel_display_name
VALUES
    ('agencywithin', 'Agency WITHIN'),
    ('ambassador', 'Ambassador'),
    ('attentive', 'Attentive'),
    ('baidu', 'Baidu'),
    ('billboard', 'Billboard'),
    ('bing', 'Bing'),
    ('blog', 'Blog'),
    ('browser', 'Browser'),
    ('catalog', 'Catalog'),
    ('collaborator', 'Collaborator'),
    ('content/native', 'Content/Native'),
    ('criteo', 'Criteo'),
    ('crosspromo', 'Crosspromo'),
    ('cse', 'CSE'),
    ('directmail', 'DirectMail'),
    ('discovery', 'Discovery'),
    ('display', 'Display'),
    ('dqna', 'DQNA'),
    ('ebg', 'EBG'),
    ('emailing', 'Emailing'),
    ('event', 'Event'),
    ('fabkids', 'Fabkids'),
    ('fabletics', 'Fabletics'),
    ('facebook', 'Facebook'),
    ('fb+ig', 'FB+IG'),
    ('fl2', 'FL2'),
    ('friend', 'Friend'),
    ('gdn', 'GDN'),
    ('geistm', 'GeistM'),
    ('google', 'Google'),
    ('ignore', 'Ignore'),
    ('influencer','Influencer'),
    ('instagram', 'Instagram'),
    ('jetblue', 'JetBlue'),
    ('justfab', 'JustFab'),
    ('like2buy', 'Like2buy'),
    ('local', 'Local'),
    ('magazine', 'Magazine'),
    ('microinfluencers', 'MicroInfluencers'),
    ('narrative', 'Narrative'),
    ('national', 'National'),
    ('nationallocal', 'NationalLocal'),
    ('networks', 'Networks'),
    ('ooh', 'OOH'),
    ('organic press', 'Organic Press'),
    ('other', 'Other'),
    ('outbrain', 'Outbrain'),
    ('paidinfluencers', 'Paid Influencers'),
    ('peoplehype', 'PeopleHype'),
    ('phoenixsuns', 'Phoenix Suns'),
    ('pinterest', 'Pinterest'),
    ('pinterestshopping', 'PinterestShopping'),
    ('pinteresttmp', 'PinterestTmp'),
    ('powerspace', 'Powerspace'),
    ('privalia/veepee', 'Privalia/Veepee'),
    ('reddit', 'Reddit'),
    ('rokt', 'ROKT'),
    ('rokuctvstreaming', 'RokuCTVStreaming'),
    ('rokufepstreaming', 'RokuFEPStreaming'),
    ('sailthru', 'Sailthru'),
    ('shoedazzle', 'Shoedazzle'),
    ('snapchat', 'Snapchat'),
    ('streaming', 'Streaming'),
    ('taboola', 'Taboola'),
    ('tiktok', 'TikTok'),
    ('tradedesk', 'Tradedesk'),
    ('ttdaudio', 'TTDAudio'),
    ('ttddisplay', 'TTDDisplay'),
    ('ttdnative', 'TTDNative'),
    ('ttdonlinevideo', 'TTDOnlineVideo'),
    ('ttdctvstreaming', 'TTDCTVStreaming'),
    ('ttdfepstreaming', 'TTDFEPStreaming'),
    ('tubescience', 'TubeScience'),
    ('twitter', 'Twitter'),
    ('unclassified', 'Unclassified'),
    ('varsity', 'Varsity'),
    ('venga', 'Venga'),
    ('website', 'Website'),
    ('wunderkind','Wunderkind'),
    ('yahoo', 'Yahoo'),
    ('youtube', 'YouTube');
