history_table_list = {
    'lake_consolidated.ultra_cms.ui_promo_management_promos',
    'lake_consolidated.ultra_merchant."ORDER"',
    'lake_consolidated.ultra_merchant.customer',
    'lake_consolidated.ultra_merchant.discount',
    'lake_consolidated.ultra_merchant.membership',
    'lake_consolidated.ultra_merchant.membership_token_transaction',
    'lake_consolidated.ultra_merchant.payment_transaction_cash',
    'lake_consolidated.ultra_merchant.payment_transaction_creditcard',
    'lake_consolidated.ultra_merchant.payment_transaction_psp',
    'lake_consolidated.ultra_merchant.pricing_option',
    'lake_consolidated.ultra_merchant.product',
    'lake_consolidated.ultra_merchant.product_bundle_component',
    'lake_consolidated.ultra_merchant.product_category',
    'lake_consolidated.ultra_merchant.promo',
    'lake_consolidated.ultra_merchant.refund',
}
