from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="address",
    watermark_column="datetime_modified",
    schema_version_prefix="v2",
    column_list=[
        Column("address_id", "INT", uniqueness=True),
        Column("firstname", "VARCHAR(25)"),
        Column("lastname", "VARCHAR(25)"),
        Column("address1", "VARCHAR(255)"),
        Column("address2", "VARCHAR(255)"),
        Column("city", "VARCHAR(35)"),
        Column("state", "VARCHAR(25)"),
        Column("zip", "VARCHAR(25)"),
        Column("country_code", "VARCHAR(2)"),
        Column("phone", "VARCHAR(25)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("company", "VARCHAR(100)"),
        Column("address3", "VARCHAR(255)"),
        Column("address4", "VARCHAR(255)"),
        Column("address5", "VARCHAR(255)"),
        Column("address6", "VARCHAR(255)"),
        Column("address7", "VARCHAR(255)"),
        Column("address8", "VARCHAR(255)"),
        Column("address_type_id", "INT"),
        Column("misc1", "VARCHAR(255)"),
        Column("misc2", "VARCHAR(255)"),
        Column("misc3", "VARCHAR(255)"),
        Column("address_hash", "BINARY(20)"),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
    ],
)
