from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultrawarehouse',
    schema='dbo',
    table='chargeback_customer_return',
    watermark_column='datetime_modified',
    strict_inequality=True,
    schema_version_prefix='v2',
    column_list=[
        Column('chargeback_customer_return_id', 'INT', uniqueness=True),
        Column('return_id', 'INT'),
        Column('return_date', 'TIMESTAMP_NTZ(3)'),
        Column('erp_db_name', 'VARCHAR(255)'),
        Column('region_id', 'VARCHAR(255)'),
        Column('department', 'VARCHAR(255)'),
        Column('business_unit', 'VARCHAR(255)'),
        Column('warehouse_code', 'VARCHAR(255)'),
        Column('po_number', 'VARCHAR(255)'),
        Column('vendor_id', 'VARCHAR(255)'),
        Column('vendor_name', 'VARCHAR(255)'),
        Column('incoterm_name', 'VARCHAR(255)'),
        Column('multi_vendor', 'BOOLEAN'),
        Column('lpn_code', 'VARCHAR(255)'),
        Column('item_number', 'VARCHAR(255)'),
        Column('return_dispostion_label', 'VARCHAR(255)'),
        Column('item_cost', 'NUMBER(19, 4)'),
        Column('freight', 'NUMBER(19, 4)'),
        Column('duty', 'NUMBER(19, 4)'),
        Column('return_cost', 'NUMBER(19, 4)'),
        Column('fc_processing_cost', 'NUMBER(19, 4)'),
        Column('defect_rate', 'DOUBLE'),
        Column('chargeback_id', 'INT'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('outbound_cost', 'NUMBER(19, 4)'),
        Column('shipped_units', 'INT'),
        Column('country_of_origin', 'VARCHAR(255)'),
        Column('wms_class', 'VARCHAR(255)'),
    ],
)
