from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="chargeback",
    watermark_column="datetime_modified",
    strict_inequality=True,
    schema_version_prefix="v2",
    column_list=[
        Column("chargeback_id", "INT", uniqueness=True),
        Column("chargeback_external_reference_id", "INT"),
        Column("source_type", "INT"),
        Column("source_reference", "VARCHAR(255)"),
        Column("po_reference", "VARCHAR(255)"),
        Column("date_placed", "TIMESTAMP_NTZ(3)"),
        Column("chargeback_type_id", "INT"),
        Column("erp_db_name", "VARCHAR(255)"),
        Column("business_unit", "VARCHAR(255)"),
        Column("interid", "VARCHAR(255)"),
        Column("market", "VARCHAR(255)"),
        Column("vendor_id", "VARCHAR(255)"),
        Column("category_reference", "VARCHAR(255)"),
        Column("chargeback_vendor_id", "INT"),
        Column("incoterm", "VARCHAR(255)"),
        Column("version", "VARCHAR(255)"),
        Column("company_id", "INT"),
        Column("source_id", "INT"),
        Column("reason_id", "INT"),
        Column("status_id", "INT"),
        Column("sent_to_vendor", "TIMESTAMP_NTZ(3)"),
        Column("confirmed_by_vendor", "TIMESTAMP_NTZ(3)"),
        Column("confirmed_chargeback_amount", "NUMBER(19, 4)"),
        Column("total_chargeback_quantity", "INT"),
        Column("waived_chargeback_amount", "NUMBER(19, 4)"),
        Column("total_chargeback_amount", "NUMBER(19, 4)"),
        Column("waived_reason", "VARCHAR"),
        Column("waived_by_id", "INT"),
        Column("comments", "VARCHAR"),
        Column("statement_period", "VARCHAR(255)"),
        Column("closed", "BOOLEAN"),
        Column("vendor_name", "VARCHAR(255)"),
        Column("vendor_contact", "VARCHAR(255)"),
        Column("vendor_email", "VARCHAR"),
        Column("wire_issued_date", "TIMESTAMP_NTZ(3)"),
        Column("credit_issued_amount", "NUMBER(19, 4)"),
        Column("credit_issuance_date", "TIMESTAMP_NTZ(3)"),
        Column("wire_sent_date", "TIMESTAMP_NTZ(3)"),
        Column("wire_no", "VARCHAR(255)"),
        Column("wire_amount", "NUMBER(19, 4)"),
        Column("package_no", "INT"),
        Column("bank_wire_confirmation", "INT"),
        Column("wire_comment", "VARCHAR(255)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("object", "VARCHAR(255)"),
        Column("object_id", "VARCHAR(255)"),
    ],
)
