from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="cycle_count_location",
    watermark_column="datetime_modified",
    schema_version_prefix="v2",
    column_list=[
        Column("cycle_count_location_id", "INT", uniqueness=True),
        Column("location_id", "INT"),
        Column("sequence", "INT"),
        Column("sequence_1_administrator_id", "INT"),
        Column("sequence_1_is_accurate", "INT"),
        Column("sequence_1_skipped", "INT"),
        Column("sequence_1_datetime_submitted", "TIMESTAMP_NTZ(3)"),
        Column("sequence_1_datetime_completed", "TIMESTAMP_NTZ(3)"),
        Column("sequence_2_administrator_id", "INT"),
        Column("sequence_2_is_accurate", "INT"),
        Column("sequence_2_skipped", "INT"),
        Column("sequence_2_datetime_submitted", "TIMESTAMP_NTZ(3)"),
        Column("sequence_2_datetime_completed", "TIMESTAMP_NTZ(3)"),
        Column("sequence_3_administrator_id", "INT"),
        Column("sequence_3_is_accurate", "INT"),
        Column("sequence_3_skipped", "INT"),
        Column("sequence_3_datetime_submitted", "TIMESTAMP_NTZ(3)"),
        Column("sequence_3_datetime_completed", "TIMESTAMP_NTZ(3)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("status_code_id", "INT"),
        Column("assigned_administrator_id", "INT"),
        Column("datetime_assigned", "TIMESTAMP_NTZ(3)"),
        Column("sort", "INT"),
    ],
)
