from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultrawarehouse',
    schema='dbo',
    table='fulfillment_item',
    watermark_column='datetime_modified',
    schema_version_prefix='v2',
    column_list=[
        Column('fulfillment_item_id', 'INT', uniqueness=True),
        Column('fulfillment_id', 'INT'),
        Column('foreign_order_line_id', 'INT'),
        Column('foreign_product_id', 'INT'),
        Column('item_id', 'INT'),
        Column('component_item_id', 'INT'),
        Column('component_uom', 'VARCHAR(25)'),
        Column('component_count', 'INT'),
        Column('quantity', 'INT'),
        Column('quantity_allocated', 'INT'),
        Column('quantity_backordered', 'INT'),
        Column('quantity_invoiced', 'INT'),
        Column('quantity_cancelled', 'INT'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('foreign_product_type_id', 'INT'),
        Column('purchase_unit_price', 'NUMBER(19, 4)'),
        Column('unit_discount', 'NUMBER(19, 4)'),
        Column('extended_price', 'NUMBER(19, 4)'),
        Column('foreign_group_key', 'VARCHAR(255)'),
        Column('inventory_reserve_code', 'VARCHAR(255)'),
        Column('item_reference_type_code_id', 'INT'),
        Column('currency_code', 'VARCHAR(3)'),
        Column('ship_set', 'INT'),
        Column('min_ship_qty', 'INT'),
    ],
)
