from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="fulfillment",
    watermark_column="datetime_modified",
    schema_version_prefix="v3",
    column_list=[
        Column("fulfillment_id", "INT", uniqueness=True),
        Column("company_id", "INT"),
        Column("warehouse_id", "INT"),
        Column("foreign_order_id", "INT"),
        Column("foreign_erp_reference_number", "VARCHAR(75)"),
        Column("line_count", "INT"),
        Column("priority", "INT"),
        Column("bin_zone_id", "INT"),
        Column("bin_location_id", "INT"),
        Column("datetime_placed", "TIMESTAMP_NTZ(3)"),
        Column("datetime_allocated", "TIMESTAMP_NTZ(3)"),
        Column("datetime_process", "TIMESTAMP_NTZ(3)"),
        Column("source", "VARCHAR(25)"),
        Column("last_message", "VARCHAR(512)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("status_code_id", "INT"),
        Column("foreign_customer_id", "INT"),
        Column("foreign_store_id", "INT"),
        Column("foreign_store_group_id", "INT"),
        Column("order_total", "NUMBER(19, 4)"),
        Column("fulfillment_batch_id", "INT"),
        Column("picked_count", "INT"),
        Column("sorted_count", "INT"),
        Column("packed_count", "INT"),
        Column("shipped_count", "INT"),
        Column("pick_count", "INT"),
        Column("subtotal", "NUMBER(19, 4)"),
        Column("shipping", "NUMBER(19, 4)"),
        Column("tax", "NUMBER(19, 4)"),
        Column("discount", "NUMBER(19, 4)"),
        Column("credit", "NUMBER(19, 4)"),
        Column("original_foreign_order_id", "INT"),
        Column("is_available_to_batch", "INT"),
        Column("pick_method", "VARCHAR(255)"),
        Column("pack_method", "VARCHAR(255)"),
        Column("pack_packing_slip", "BOOLEAN"),
        Column("datetime_estimated_shipment", "TIMESTAMP_NTZ(3)"),
        Column("datetime_estimated_shipment_original", "TIMESTAMP_NTZ(3)"),
        Column("datetime_sla", "TIMESTAMP_NTZ(3)"),
        Column("wcs_path_type_code_id", "INT"),
        Column("wholesaler_id", "INT"),
        Column("release_datetime", "TIMESTAMP_NTZ(3)"),
        Column("min_ship_datetime", "TIMESTAMP_NTZ(3)"),
        Column("max_ship_datetime", "TIMESTAMP_NTZ(3)"),
        Column("outbound_plan_id", "INT"),
        Column("outbound_plan_log_id", "INT"),
        Column("fifo_sort", "INT"),
    ],
)
