from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="inventory_rollup",
    watermark_column="date",
    schema_version_prefix="v3",
    table_hints=["index(IX_inventory_rollup_2)"],
    column_list=[
        Column("warehouse_id", "INT", uniqueness=True),
        Column("date", "TIMESTAMP_NTZ(3)", uniqueness=True),
        Column("item_id", "INT", uniqueness=True),
        Column("unit_cost", "NUMBER(19, 4)"),
        Column("qty_onhand", "INT"),
        Column("qty_lost", "INT"),
        Column("qty_replen", "INT"),
        Column("qty_ri", "INT"),
        Column("qty_return", "INT"),
        Column("qty_intransit", "INT"),
        Column("qty_staging", "INT"),
        Column("qty_pick_staging", "INT"),
        Column("qty_mrb", "INT"),
        Column("qty_mrb_returns", "INT"),
        Column("qty_adjusted", "INT"),
        Column("qty_adjusted_cyclecount", "INT"),
        Column("qty_adjusted_other", "INT"),
        Column("qty_adjusted_receipt", "INT"),
        Column("qty_adjusted_sales", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("qty_putaway", "INT"),
        Column("inventory_rollup_id", "INT"),
        Column("qty_sub_fg", "INT"),
        Column("qty_sub_qa", "INT"),
        Column("qty_sub_lost", "INT"),
        Column("qty_sub_ri", "INT"),
        Column("qty_sub_return", "INT"),
        Column("qty_sub_intransit", "INT"),
        Column("qty_sub_mrb_return", "INT"),
        Column("qty_sub_mrb_receiving", "INT"),
        Column("qty_sub_mrb_warehouse", "INT"),
        Column("local_date", "TIMESTAMP_NTZ(3)"),
        Column("qty_adjusted_bulk_shipment", "INT"),
        Column("qty_adjusted_oms", "INT"),
        Column("qty_adjusted_damaged", "INT"),
        Column("qty_adjusted_return", "INT"),
        Column("qty_adjusted_transfer", "INT"),
        Column("qty_allocated", "INT"),
        Column("qty_order_reserve", "INT"),
        Column("qty_wholesale_reserve", "INT"),
        Column("qty_misc3_reserve", "INT"),
        Column("qty_ghost", "INT"),
    ],
)
