from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="inventory_adjustment_rollup",
    watermark_column="datetime_modified",
    strict_inequality=True,
    schema_version_prefix="v2",
    column_list=[
        Column("date", "DATE", uniqueness=True),
        Column("hour", "INT", uniqueness=True),
        Column("warehouse_id", "INT", uniqueness=True),
        Column("company_id", "INT", uniqueness=True),
        Column("item_id", "INT", uniqueness=True),
        Column("return_restock_adjustments", "INT"),
        Column("kitting_adjustments", "INT"),
        Column("sample_request_office_adjustments", "INT"),
        Column("sample_request_merchandise_adjustments", "INT"),
        Column("sample_request_marketing_adjustments", "INT"),
        Column("sample_request_pr_adjustments", "INT"),
        Column("scrap_adjustments", "INT"),
        Column("heels_pick_adjustments", "INT"),
        Column("cycle_count_adjustments", "INT"),
        Column("correction_receipt_adjustments", "INT"),
        Column("bulk_shipments", "INT"),
        Column("in_transit_units", "INT"),
        Column("units_shipped", "INT"),
        Column("units_received", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("inventory_adjustment_rollup_id", "INT"),
        Column("unknown_adjustments", "INT"),
    ],
)
