from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="invoice_box",
    watermark_column="datetime_modified",
    schema_version_prefix="v2",
    column_list=[
        Column("invoice_box_id", "INT", uniqueness=True),
        Column("invoice_id", "INT"),
        Column("work_location_id", "INT"),
        Column("box_id", "INT"),
        Column("company_carrier_service_id", "INT"),
        Column("tracking_number", "VARCHAR(50)"),
        Column("partial_tracking_number", "VARCHAR(50)"),
        Column("date_shipped", "TIMESTAMP_NTZ(3)"),
        Column("weight", "DOUBLE"),
        Column("zone", "INT"),
        Column("postage", "NUMBER(19, 4)"),
        Column("surcharge", "NUMBER(19, 4)"),
        Column("status_code_id", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("datetime_carrier_confirmed", "TIMESTAMP_NTZ(3)"),
        Column("datetime_carrier_delivered", "TIMESTAMP_NTZ(3)"),
        Column("datetime_carrier_status_update", "TIMESTAMP_NTZ(3)"),
        Column("carrier_status", "VARCHAR(75)"),
        Column("carrier_weight", "DOUBLE"),
        Column("carrier_postage", "NUMBER(19, 4)"),
        Column("carrier_surcharge", "NUMBER(19, 4)"),
        Column("carrier_discount", "NUMBER(19, 4)"),
        Column("carrier_transportation", "NUMBER(19, 4)"),
        Column("package_id", "INT"),
        Column("pack_administrator_id", "INT"),
        Column("ship_administrator_id", "INT"),
        Column("company_carrier_manifest_id", "INT"),
        Column("datetime_transaction", "TIMESTAMP_NTZ(3)"),
        Column("datetime_local_transaction", "TIMESTAMP_NTZ(3)"),
        Column("net_rate", "NUMBER(19, 4)"),
        Column("discount_rate", "NUMBER(19, 4)"),
        Column("gross_rate", "NUMBER(19, 4)"),
        Column("fuel_surcharge", "NUMBER(19, 4)"),
        Column("residential_surcharge", "NUMBER(19, 4)"),
    ],
)
