from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="invoice",
    watermark_column="datetime_modified",
    schema_version_prefix="v2",
    column_list=[
        Column("invoice_id", "INT", uniqueness=True),
        Column("company_id", "INT"),
        Column("batch_id", "INT"),
        Column("warehouse_id", "INT"),
        Column("foreign_order_id", "INT"),
        Column("foreign_erp_reference_number", "VARCHAR(75)"),
        Column("foreign_store_id", "INT"),
        Column("foreign_company_id", "INT"),
        Column("shipping_address_id", "INT"),
        Column("carrier_service_id", "INT"),
        Column("item_quantity_total", "INT"),
        Column("item_combination_id", "INT"),
        Column("batch_filter_id", "INT"),
        Column("print_material_sequence_id", "INT"),
        Column("batch_hash_code", "VARCHAR(255)"),
        Column("date_placed", "TIMESTAMP_NTZ(3)"),
        Column("datetime_batched", "TIMESTAMP_NTZ(3)"),
        Column("archive_filename", "VARCHAR(255)"),
        Column("archive_directory", "VARCHAR(255)"),
        Column("source_code_id", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("status_code_id", "INT"),
        Column("foreign_customer_id", "INT"),
        Column("foreign_store_group_id", "INT"),
        Column("retail_point_address_id", "INT"),
        Column("email", "VARCHAR(255)"),
        Column("datetime_transaction", "TIMESTAMP_NTZ(3)"),
        Column("datetime_local_transaction", "TIMESTAMP_NTZ(3)"),
        Column("wholesaler_id", "INT"),
    ],
)
