from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultrawarehouse',
    schema='dbo',
    table='item',
    watermark_column='datetime_modified',
    schema_version_prefix='v2',
    column_list=[
        Column('item_id', 'INT', uniqueness=True),
        Column('item_number', 'VARCHAR(30)'),
        Column('description', 'VARCHAR(512)'),
        Column('short_description', 'VARCHAR(255)'),
        Column('generic_description', 'VARCHAR(255)'),
        Column('class', 'VARCHAR(30)'),
        Column('wms_class', 'VARCHAR(30)'),
        Column('consumable_item_number', 'VARCHAR(30)'),
        Column('type_code_id', 'INT'),
        Column('class_type_code_id', 'INT'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('company_id', 'INT'),
        Column('is_hazardous', 'INT'),
        Column('plm_maps_to_item_number', 'VARCHAR(255)'),
        Column('plm_category', 'VARCHAR(255)'),
        Column('plm_sub_category', 'VARCHAR(255)'),
        Column('plm_gender', 'VARCHAR(255)'),
        Column('division', 'VARCHAR(255)'),
        Column('department', 'VARCHAR(255)'),
        Column('sub_department', 'VARCHAR(255)'),
        Column('category', 'VARCHAR(255)'),
        Column('sub_category', 'VARCHAR(255)'),
        Column('color', 'VARCHAR(255)'),
        Column('color_code', 'VARCHAR(255)'),
        Column('size', 'VARCHAR(255)'),
        Column('gender', 'VARCHAR(255)'),
        Column('hash', 'BINARY(20)'),
        Column('date_launch', 'TIMESTAMP_NTZ(3)'),
    ],
)
