from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultrawarehouse',
    schema='dbo',
    table='item_warehouse',
    watermark_column='datetime_modified',
    schema_version_prefix='v2',
    column_list=[
        Column('item_id', 'INT', uniqueness=True),
        Column('warehouse_id', 'INT', uniqueness=True),
        Column('qty_onhand', 'INT'),
        Column('qty_allocated', 'INT'),
        Column('qty_order_reserve', 'INT'),
        Column('qty_wholesale_reserve', 'INT'),
        Column('qty_transfer_reserve', 'INT'),
        Column('qty_misc1_reserve', 'INT'),
        Column('qty_misc2_reserve', 'INT'),
        Column('qty_misc3_reserve', 'INT'),
        Column('datetime_process', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('qty_intransit', 'INT'),
        Column('qty_lost', 'INT'),
        Column('qty_mrb', 'INT'),
        Column('qty_mrb_returns', 'INT'),
        Column('qty_pick_staging', 'INT'),
        Column('qty_replen', 'INT'),
        Column('qty_return', 'INT'),
        Column('qty_ri', 'INT'),
        Column('qty_staging', 'INT'),
        Column('qty_ghost', 'INT'),
        Column('datetime_pick_process', 'TIMESTAMP_NTZ(3)'),
        Column('item_warehouse_id', 'INT'),
        Column('row_value', 'BINARY(20)'),
    ],
)
