from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="pick_log",
    watermark_column="datetime_modified",
    schema_version_prefix="v2",
    column_list=[
        Column("pick_log_id", "INT", uniqueness=True),
        Column("type_code_id", "INT"),
        Column("parent_id", "INT"),
        Column("location_id", "INT"),
        Column("parent_container_id", "INT"),
        Column("case_id", "INT"),
        Column("lpn_id", "INT"),
        Column("item_id", "INT"),
        Column("quantity", "INT"),
        Column("pick_assigned_administrator_id", "INT"),
        Column("pick_administrator_id", "INT"),
        Column("initialscan_administrator_id", "INT"),
        Column("singulate_administrator_id", "INT"),
        Column("presort_administrator_id", "INT"),
        Column("sort_administrator_id", "INT"),
        Column("pack_administrator_id", "INT"),
        Column("ship_administrator_id", "INT"),
        Column("cancel_administrator_id", "INT"),
        Column("datetime_pick_assigned", "TIMESTAMP_NTZ(3)"),
        Column("datetime_picked", "TIMESTAMP_NTZ(3)"),
        Column("datetime_initialscanned", "TIMESTAMP_NTZ(3)"),
        Column("datetime_singulated", "TIMESTAMP_NTZ(3)"),
        Column("datetime_presorted", "TIMESTAMP_NTZ(3)"),
        Column("datetime_sorted", "TIMESTAMP_NTZ(3)"),
        Column("datetime_packed", "TIMESTAMP_NTZ(3)"),
        Column("datetime_shipped", "TIMESTAMP_NTZ(3)"),
        Column("datetime_cancelled", "TIMESTAMP_NTZ(3)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("status_code_id", "INT"),
        Column("cancel_type_code_id", "INT"),
        Column("cycle_count_location_id", "INT"),
        Column("did_cycle_count_recover_unit", "INT"),
        Column("inventory_log_id", "INT"),
        Column("case_has_lpn", "BOOLEAN"),
        Column("wcs_path_type_code_id", "INT"),
        Column("pick_id", "INT"),
    ],
)
