from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultrawarehouse',
    schema='dbo',
    table='po_inventory_rollup',
    watermark_column='datetime_modified',
    schema_version_prefix='v2',
    column_list=[
        Column('warehouse_id', 'INT'),
        Column('date', 'TIMESTAMP_NTZ(3)'),
        Column('po_number', 'VARCHAR(255)'),
        Column('item_id', 'INT'),
        Column('qty_onhand', 'INT'),
        Column('qty_lost', 'INT'),
        Column('qty_replen', 'INT'),
        Column('qty_ri', 'INT'),
        Column('qty_return', 'INT'),
        Column('qty_intransit', 'INT'),
        Column('qty_staging', 'INT'),
        Column('qty_pick_staging', 'INT'),
        Column('qty_putaway', 'INT'),
        Column('qty_mrb', 'INT'),
        Column('qty_mrb_returns', 'INT'),
        Column('qty_sub_fg', 'INT'),
        Column('qty_sub_lost', 'INT'),
        Column('qty_sub_ri', 'INT'),
        Column('qty_sub_return', 'INT'),
        Column('qty_sub_intransit', 'INT'),
        Column('qty_sub_qa', 'INT'),
        Column('qty_sub_mrb_return', 'INT'),
        Column('qty_sub_mrb_receiving', 'INT'),
        Column('qty_sub_mrb_warehouse', 'INT'),
        Column('local_date', 'TIMESTAMP_NTZ(3)'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('po_inventory_rollup_id', 'INT', uniqueness=True),
    ],
)
