from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="retail_location",
    watermark_column="datetime_modified",
    strict_inequality=True,
    schema_version_prefix="v2",
    column_list=[
        Column("retail_location_id", "INT", uniqueness=True),
        Column("retail_location_code", "VARCHAR(255)"),
        Column("label", "VARCHAR(255)"),
        Column("description", "VARCHAR(512)"),
        Column("demographic", "VARCHAR(512)"),
        Column("address1", "VARCHAR(255)"),
        Column("address2", "VARCHAR(255)"),
        Column("city", "VARCHAR(255)"),
        Column("state", "VARCHAR(255)"),
        Column("zip", "VARCHAR(255)"),
        Column("country_code", "VARCHAR(255)"),
        Column("phone", "VARCHAR(255)"),
        Column("open_date", "DATE"),
        Column("store_id", "INT"),
        Column("warehouse_id", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("ga_account", "VARCHAR(100)"),
        Column("ship_from_store", "INT"),
        Column("pickup_in_store", "INT"),
        Column("dressing_rooms", "INT"),
        Column("firstname", "VARCHAR(100)"),
        Column("lastname", "VARCHAR(100)"),
        Column("short_name", "VARCHAR(100)"),
        Column("blind_receiving", "INT"),
        Column("store_mode", "VARCHAR(35)"),
        Column("sunday_open", "VARCHAR(35)"),
        Column("sunday_close", "VARCHAR(35)"),
        Column("monday_open", "VARCHAR(35)"),
        Column("monday_close", "VARCHAR(35)"),
        Column("tuesday_open", "VARCHAR(35)"),
        Column("tuesday_close", "VARCHAR(35)"),
        Column("wednesday_open", "VARCHAR(35)"),
        Column("wednesday_close", "VARCHAR(35)"),
        Column("thursday_open", "VARCHAR(35)"),
        Column("thursday_close", "VARCHAR(35)"),
        Column("friday_open", "VARCHAR(35)"),
        Column("friday_close", "VARCHAR(35)"),
        Column("saturday_open", "VARCHAR(35)"),
        Column("saturday_close", "VARCHAR(35)"),
        Column("carrier_service_id", "INT"),
        Column("address_id", "INT"),
        Column("email_address", "VARCHAR(50)"),
        Column("selling_sq_ft", "INT"),
        Column("backroom_sq_ft", "INT"),
        Column("total_sq_ft", "INT"),
        Column("grand_open_date", "DATE"),
        Column("landlord", "VARCHAR(35)"),
        Column("shipment_delivery_notes", "VARCHAR(255)"),
        Column("code", "INT"),
        Column("latitude", "VARCHAR(25)"),
        Column("longitude", "VARCHAR(25)"),
        Column("store_group_id", "INT"),
    ],
)
