from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="rpt",
    table="transload_manifest_file_for_ca",
    watermark_column="datetime_modified",
    schema_version_prefix="v4",
    column_list=[
        Column("transload_manifest_file_for_ca_id", "INT", uniqueness=True),
        Column("transload_manifest_file_id", "INT"),
        Column("manifest_filename", "VARCHAR(255)"),
        Column("yard_container_id", "INT"),
        Column("container_label", "VARCHAR(255)"),
        Column("transload_manifest_id", "INT"),
        Column("control_number", "VARCHAR(255)"),
        Column("shipment_type", "VARCHAR(255)"),
        Column("shipper_name", "VARCHAR(255)"),
        Column("shipper_address", "VARCHAR(255)"),
        Column("shipper_city", "VARCHAR(255)"),
        Column("shipper_country_code", "VARCHAR(255)"),
        Column("shipper_state", "VARCHAR(255)"),
        Column("shipper_zip", "VARCHAR(255)"),
        Column("shipper_pol", "VARCHAR(255)"),
        Column("name", "VARCHAR(255)"),
        Column("address1", "VARCHAR(50)"),
        Column("city", "VARCHAR(35)"),
        Column("country_code", "VARCHAR(2)"),
        Column("state", "VARCHAR(25)"),
        Column("zip", "VARCHAR(25)"),
        Column("wms_class_category", "VARCHAR(255)"),
        Column("quantity", "INT"),
        Column("unit_of_measurement", "VARCHAR(255)"),
        Column("weight", "DOUBLE"),
        Column("unit_of_weight", "VARCHAR(255)"),
        Column("product_value", "NUMBER(19, 4)"),
        Column("foreign_order_id", "INT"),
        Column("port_arrival", "VARCHAR(255)"),
        Column("port_loading", "VARCHAR(255)"),
        Column("port_receipt", "VARCHAR(255)"),
        Column("port_origin", "VARCHAR(255)"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("po_cost", "NUMBER(19, 4)"),
        Column("po_cost_profit_margin", "NUMBER(19, 4)"),
        Column("customer_paid_value", "NUMBER(19, 4)"),
        Column("sku", "VARCHAR(30)"),
        Column("msrp", "NUMBER(19, 4)"),
    ],
)
