from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="vw_inventory",
    watermark_column="max_datetime_added",
    initial_load_value="2024-06-11",
    schema_version_prefix="v2",
    column_list=[
        Column("warehouse_id", "INT", uniqueness=True),
        Column("location_id", "INT", uniqueness=True),
        Column("location_label", "VARCHAR(255)"),
        Column("location_status_code_id", "INT"),
        Column("allow_multiple_item", "INT"),
        Column("zone_id", "INT"),
        Column("zone_label", "VARCHAR(255)"),
        Column("zone_type_code_id", "INT"),
        Column("zone_type_code_label", "VARCHAR(255)"),
        Column("pick_zone_id", "INT"),
        Column("pick_zone_label", "VARCHAR(255)"),
        Column("pick_zone_type_code_id", "INT"),
        Column("pick_zone_type_code_label", "VARCHAR(255)"),
        Column("parent_container_id", "INT"),
        Column("parent_container_label", "VARCHAR(255)"),
        Column("parent_container_type_code_id", "INT"),
        Column("parent_container_type_code_label", "VARCHAR(255)"),
        Column("container_id", "INT"),
        Column("container_label", "VARCHAR(255)"),
        Column("container_type_code_id", "INT"),
        Column("container_type_code_label", "VARCHAR(255)"),
        Column("case_id", "INT", uniqueness=True),
        Column("case_code", "VARCHAR(255)"),
        Column("case_status_code_id", "INT"),
        Column("lpn_id", "INT", uniqueness=True),
        Column("lpn_code", "VARCHAR(255)"),
        Column("lpn_status_code_id", "INT"),
        Column("item_id", "INT", uniqueness=True),
        Column("item_number", "VARCHAR(30)"),
        Column("item_class", "VARCHAR(30)"),
        Column("item_description", "VARCHAR(512)"),
        Column("wms_class", "VARCHAR(30)"),
        Column("qty_onhand", "INT"),
        Column("qty_allocated", "INT"),
        Column("qty_incoming", "INT"),
        Column("qty_hold", "INT"),
        Column("min_datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("max_datetime_added", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("administrator_id", "INT"),
        Column("administrator_firstname", "VARCHAR(25)"),
        Column("administrator_lastname", "VARCHAR(25)"),
        Column("administrator_login", "VARCHAR(25)"),
    ],
)
