from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ultrawarehouse",
    schema="dbo",
    table="vw_inventory_log",
    watermark_column="datetime_modified",
    column_list=[
        Column("inventory_log_id", "INT", uniqueness=True),
        Column("parent_inventory_log_id", "INT"),
        Column("warehouse_id", "INT"),
        Column("type_code_id", "INT"),
        Column("type_code_label", "VARCHAR(255)"),
        Column("location_id", "INT"),
        Column("location_label", "VARCHAR(255)"),
        Column("zone_id", "INT"),
        Column("zone_label", "VARCHAR(255)"),
        Column("zone_type_code_id", "INT"),
        Column("pick_zone_id", "INT"),
        Column("pick_zone_label", "VARCHAR(255)"),
        Column("pick_zone_type_code_id", "INT"),
        Column("parent_container_id", "INT"),
        Column("parent_container_label", "VARCHAR(255)"),
        Column("parent_container_type_code_id", "INT"),
        Column("parent_container_type_code_label", "VARCHAR(255)"),
        Column("container_id", "INT"),
        Column("container_label", "VARCHAR(255)"),
        Column("container_type_code_id", "INT"),
        Column("container_type_code_label", "VARCHAR(255)"),
        Column("case_id", "INT"),
        Column("case_code", "VARCHAR(255)"),
        Column("lpn_id", "INT"),
        Column("lpn_code", "VARCHAR(255)"),
        Column("item_id", "INT"),
        Column("item_number", "VARCHAR(30)"),
        Column("item_description", "VARCHAR(512)"),
        Column("wms_class", "VARCHAR(30)"),
        Column("quantity", "INT"),
        Column("object", "VARCHAR(75)"),
        Column("object_id", "INT"),
        Column("datetime_added", "TIMESTAMP_NTZ(3)", delta_column=1),
        Column("datetime_modified", "TIMESTAMP_NTZ(3)", delta_column=0),
        Column("administrator_id", "INT"),
        Column("administrator_firstname", "VARCHAR(25)"),
        Column("administrator_lastname", "VARCHAR(25)"),
    ],
)
