from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database='ultrawarehouse',
    schema='dbo',
    table='warehouse',
    watermark_column='datetime_modified',
    strict_inequality=True,
    schema_version_prefix='v4',
    column_list=[
        Column('warehouse_id', 'INT', uniqueness=True),
        Column('code', 'VARCHAR(30)'),
        Column('label', 'VARCHAR(255)'),
        Column('description', 'VARCHAR(512)'),
        Column('name', 'VARCHAR(255)'),
        Column('type_code_id', 'INT'),
        Column('transfer_type_code_id', 'INT'),
        Column('zip_shipping_from', 'VARCHAR(25)'),
        Column('label_print_spooler_url', 'VARCHAR(255)'),
        Column('cups_url', 'VARCHAR(255)'),
        Column('wms_type_code_id', 'INT'),
        Column('status_code_id', 'INT'),
        Column('datetime_added', 'TIMESTAMP_NTZ(3)', delta_column=1),
        Column('datetime_modified', 'TIMESTAMP_NTZ(3)', delta_column=0),
        Column('region_id', 'INT'),
        Column('address_id', 'INT'),
        Column('carrier_service_id', 'INT'),
        Column('timezone', 'VARCHAR(25)'),
        Column('airport_code', 'VARCHAR(5)'),
        Column('parent_warehouse_id', 'INT'),
        Column('foreign_warehouse_id', 'VARCHAR(32)'),
        Column('consignment', 'BOOLEAN'),
        Column('allow_external', 'BOOLEAN'),
    ],
)
