SELECT ASN_ID                                as ship_label,
       'OOCL'                                as ship_carrier,
       PORT_OF_LOAD                          as ship_from,
       PORT_OF_DISCHARGE                     as ship_pod,
       FINAL_DESTINATION                     as ship_to,
       cast(SHIPMENT_VOLUME as float)        as ship_volume,
       cast(SHIPMENT_CARTON_QUANTITY as int) as ship_carton,
       BILL_OF_LADING                        as ship_bol,
       VESSEL_NAME                           as ship_vessel,
       VOYAGE_NUMBER                         as ship_voyage,
       TRANSPORT_MODE                        as ship_transport_mode,
       CONTAINER_ID                          as container_label,
       SEAL_NUMBER                           as container_seal,
       DEPARTURE_DATE                        as container_shipped_date,
       EST_DELIVERY_DATE                     as container_est_delivery,
       null                                  as container_tracking,
       cast(container_weight as float)       as container_weight,
       EQUIPMENT_TYPE                        as container_equipment,
       traffic_mode                          as container_traffic_mode,
       PO_NUMBER                             as document_label,
       610                                   as document_type,
       null                                  as case_label,
       CAST(null AS bigint)                  as case_id,
       ITEM_NUMBER                           as line_item_number,
       CAST(SHIPPED_QUANTITY AS INT)         as line_quantity,
       CAST(null AS INT)                     as line_quantity_added,
       CARTON_QUANTITY                       as line_carton_qty,
       cast(VOLUME as float)                 as line_volume,
       cast(WEIGHT as float)                 as line_weight,
       cast(po_line_number as INT)              as line_number
FROM REPORTING_PROD.SPS.ASN l
where l.meta_create_datetime > %(low_watermark)s
