from include.utils.snowflake import Column

column_list = [
    Column('survey_id', 'NUMBER', uniqueness=True),
    Column('survey_title', 'VARCHAR'),
    Column('respondent_id', 'NUMBER', uniqueness=True),
    Column('session_id', 'VARCHAR'),
    Column('customer_id', 'VARCHAR'),
    Column('customer_id_type', 'VARCHAR'),
    Column('contact_id', 'VARCHAR'),
    Column('question_id', 'VARCHAR', uniqueness=True),
    Column('question_label', 'VARCHAR'),
    Column('l1_question_id', 'VARCHAR'),
    Column('l1_question_label', 'VARCHAR'),
    Column('l2_question_id', 'VARCHAR'),
    Column('l2_question_label', 'VARCHAR'),
    Column('l3_question_id', 'VARCHAR'),
    Column('l3_question_label', 'VARCHAR'),
    Column('question_type', 'VARCHAR'),
    Column('response', 'VARCHAR'),
    Column('response_text', 'VARCHAR'),
    Column('response_numeric', 'NUMBER'),
    Column('response_alt', 'VARCHAR'),
    Column('answer_id', 'VARCHAR'),
    Column('updated_at', 'TIMESTAMP_LTZ(3)', delta_column=True),
    Column('date_submitted', 'TIMESTAMP_LTZ(3)'),
]
