from include.utils.copy_paste_helper import TableConfig
from include.utils.snowflake import Column

tables = [
    TableConfig(
        database="edw_prod",
        schema="data_model",
        target_database="analytic",
        target_schema="dbo",
        table="dim_store",
        initial_load_value="1900-01-01",
        watermark_column="meta_update_datetime",
        column_list=[
            Column("store_id", "INT", uniqueness=True),
            Column("store_group_id", "INT"),
            Column("store_group", "VARCHAR(10)"),
            Column("store_name", "VARCHAR(50)"),
            Column("store_name_region", "VARCHAR(50)"),
            Column("store_full_name", "VARCHAR(50)"),
            Column("store_brand", "VARCHAR(20)"),
            Column("store_brand_abbr", "VARCHAR(10)"),
            Column("store_type", "VARCHAR(10)"),
            Column("store_sub_type", "VARCHAR(50)"),
            Column("is_core_store", "VARCHAR(50)"),
            Column("store_country", "VARCHAR(50)"),
            Column("store_region", "VARCHAR(32)"),
            Column("store_division", "VARCHAR(32)"),
            Column("store_division_abbr", "VARCHAR(10)"),
            Column("store_currency", "VARCHAR(10)"),
            Column("store_time_zone", "VARCHAR(100)"),
            Column("store_retail_state", "VARCHAR(50)"),
            Column("store_retail_city", "VARCHAR(50)"),
            Column("store_retail_location", "VARCHAR(50)"),
            Column("store_retail_zip_code", "VARCHAR(10)"),
            Column("store_retail_location_code", "VARCHAR(50)"),
            Column("store_retail_status", "VARCHAR(50)"),
            Column("store_retail_region", "VARCHAR(50)"),
            Column("store_retail_district", "VARCHAR(50)"),
            Column(
                "src_meta_create_datetime",
                "DATETIME",
                delta_column=0,
                source_name="meta_create_datetime",
            ),
            Column(
                "src_meta_update_datetime",
                "DATETIME",
                delta_column=0,
                source_name="meta_update_datetime",
            ),
        ],
    ),
    TableConfig(
        database="edw_prod",
        schema="reference",
        target_database="analytic",
        target_schema="dbo",
        table="currency_exchange_rate",
        initial_load_value="1900-01-01",
        watermark_column="meta_update_datetime",
        column_list=[
            Column("SRC_CURRENCY", "VARCHAR(10)", uniqueness=True),
            Column("DEST_CURRENCY", "VARCHAR(10)", uniqueness=True),
            Column(
                "RATE_DATETIME",
                "DATETIME",
                uniqueness=True,
                source_name="RATE_DATETIME::DATETIME",
            ),
            Column("EXCHANGE_RATE", "DECIMAL(19,4)"),
            Column(
                "EFFECTIVE_START_DATETIME",
                "DATETIME",
                source_name="EFFECTIVE_START_DATETIME::DATETIME",
            ),
            Column(
                "EFFECTIVE_END_DATETIME",
                "DATETIME",
                source_name="EFFECTIVE_END_DATETIME::DATETIME",
            ),
            Column(
                "src_meta_create_datetime",
                "DATETIME",
                delta_column=1,
                source_name="meta_create_datetime::DATETIME",
            ),
            Column(
                "src_meta_update_datetime",
                "DATETIME",
                delta_column=0,
                source_name="meta_update_datetime::DATETIME",
            ),
        ],
    ),
    TableConfig(
        database="edw_prod",
        schema="reference",
        target_database="analytic",
        target_schema="dbo",
        table="vat_rate_history",
        initial_load_value="1900-01-01",
        watermark_column="meta_update_datetime",
        column_list=[
            Column("COUNTRY_CODE", "VARCHAR(10)", uniqueness=True),
            Column("RATE", "DECIMAL(18,6)", uniqueness=True),
            Column(
                "START_DATE",
                "DATETIME",
                source_name="START_DATE::DATETIME",
                uniqueness=True,
            ),
            Column(
                "EXPIRES_DATE",
                "DATETIME",
                source_name="EXPIRES_DATE::DATETIME",
                uniqueness=True,
            ),
            Column(
                "src_meta_create_datetime",
                "DATETIME",
                delta_column=1,
                source_name="meta_create_datetime::DATETIME",
            ),
            Column(
                "src_meta_update_datetime",
                "DATETIME",
                delta_column=0,
                source_name="meta_update_datetime::DATETIME",
            ),
        ],
    ),
    TableConfig(
        database="lake",
        schema="workday",
        target_database="analytic",
        target_schema="dbo",
        table="employees",
        initial_load_value="1900-01-01",
        watermark_column="meta_update_datetime",
        column_list=[
            Column("EMPLOYEE_ID", "VARCHAR(10)", uniqueness=True),
            Column("FIRST_NAME", "VARCHAR(200)"),
            Column("LAST_NAME", "VARCHAR(200)"),
            Column("BUSINESS_TITLE", "VARCHAR(200)"),
            Column("WORKER_TITLE", "VARCHAR(200)"),
            Column("STATUS", "VARCHAR(200)"),
            Column("MANAGER", "VARCHAR(200)"),
            Column("COMPANY", "VARCHAR(200)"),
            Column("BRAND", "VARCHAR(200)"),
            Column("COST_CENTER", "VARCHAR(200)"),
            Column("EMAIL", "VARCHAR(200)", uniqueness=True),
            Column(
                "START_DATE",
                "DATETIME",
                source_name="START_DATE::DATETIME",
                uniqueness=True,
            ),
            Column(
                "TERMINATION_DATE", "DATETIME", source_name="TERMINATION_DATE::DATETIME"
            ),
            Column("UPDATED_AT", "DATETIME", source_name="UPDATED_AT::DATETIME"),
            Column(
                "src_meta_create_datetime",
                "DATETIME",
                delta_column=1,
                source_name="meta_create_datetime::DATETIME",
            ),
            Column(
                "src_meta_update_datetime",
                "DATETIME",
                delta_column=0,
                source_name="meta_update_datetime::DATETIME",
            ),
        ],
    ),
]
