from include.utils.snowflake import Column
from task_configs.dag_config.base_config import Config

contacts_config = Config(
    schema='callminer',
    table='contacts',
    version='v1',
    column_list=[
        Column('contact_id', 'NUMBER', source_name='Contact_Id', uniqueness=True),
        Column('contact_type', 'VARCHAR', source_name='Contact_Type'),
        Column('contact_wav_path', 'VARCHAR', source_name='Contact_WavPath'),
        Column('last_modified', 'TIMESTAMP_LTZ(3)', source_name='LastModified', delta_column=True),
        Column('attributes_customer_account', 'VARCHAR', source_name='Attributes_CustomerAccount'),
        Column('attributes_location', 'VARCHAR', source_name='Attributes_Location'),
        Column('attributes_subject', 'VARCHAR', source_name='Attributes_Subject'),
        Column('attributes_comment', 'VARCHAR', source_name='Attributes_Comment'),
        Column('attributes_dnis', 'VARCHAR', source_name='Attributes_DNIS'),
        Column(
            'attributes_source_document_type', 'NUMBER', source_name='Attributes_SourceDocumentType'
        ),
        Column('attributes_udf_text_09', 'VARCHAR', source_name='Attributes_UDF_text_09'),
        Column('attributes_message_total', 'NUMBER', source_name='Attributes_MessageTotal'),
        Column('attributes_audio_source_name', 'VARCHAR', source_name='Attributes_AudioSourceName'),
        Column('attributes_udf_text_02', 'VARCHAR', source_name='Attributes_UDF_text_02'),
        Column('attributes_udf_text_03', 'VARCHAR', source_name='Attributes_UDF_text_03'),
        Column('attributes_udf_text_06', 'VARCHAR', source_name='Attributes_UDF_text_06'),
        Column('attributes_udf_text_23', 'VARCHAR', source_name='Attributes_UDF_text_23'),
        Column('attributes_id', 'NUMBER', source_name='Attributes_ID'),
        Column('attributes_udf_text_21', 'VARCHAR', source_name='Attributes_UDF_text_21'),
        Column('attributes_dept', 'VARCHAR', source_name='Attributes_Dept'),
        Column('attributes_direction', 'VARCHAR', source_name='Attributes_Direction'),
        Column('attributes_agent', 'VARCHAR', source_name='Attributes_Agent'),
        Column('attributes_agent_group', 'VARCHAR', source_name='Attributes_AgentGroup'),
        Column('attributes_description', 'VARCHAR', source_name='Attributes_Description'),
        Column(
            'attributes_source_document_type_name',
            'VARCHAR',
            source_name='Attributes_SourceDocumentTypeName',
        ),
        Column('measures_udf_num_04', 'VARCHAR', source_name='Measures_UDF_num_04'),
        Column('measures_udf_num_07', 'VARCHAR', source_name='Measures_UDF_num_07'),
        Column(
            'measures_silence_duration_max_seconds',
            'FLOAT',
            source_name='Measures_SilenceDurationMaxSeconds',
        ),
        Column('measures_average_delay', 'FLOAT', source_name='Measures_AverageDelay'),
        Column('measures_sentiment_compound', 'FLOAT', source_name='Measures_SentimentCompound'),
        Column('measures_silence_percent', 'FLOAT', source_name='Measures_Silence_percent'),
        Column('measures_word_count', 'NUMBER', source_name='Measures_WordCount'),
        Column('measures_udf_num_05', 'NUMBER', source_name='Measures_UDF_num_05'),
        Column('measures_id_1', 'NUMBER', source_name='Measures_ID1'),
        Column('measures_id', 'NUMBER', source_name='Measures_ID'),
        Column('measures_udf_num_03', 'VARCHAR', source_name='Measures_UDF_num_03'),
        Column('measures_sentiment_positive', 'FLOAT', source_name='Measures_SentimentPositive'),
        Column('measures_max_delay', 'FLOAT', source_name='Measures_MaxDelay'),
        Column('measures_sentiment_negative', 'FLOAT', source_name='Measures_SentimentNegative'),
        Column('measures_udf_num_02', 'NUMBER', source_name='Measures_UDF_num_02'),
        Column('measures_udf_num_01', 'NUMBER', source_name='Measures_UDF_num_01'),
        Column('measures_text_length', 'FLOAT', source_name='Measures_TextLength'),
        Column('measures_total_hold_seconds', 'FLOAT', source_name='Measures_TotalHoldSeconds'),
        Column('measures_wavlength', 'NUMBER', source_name='Measures_WAVLength'),
        Column(
            'measures_tempo_average_words_per_minute',
            'FLOAT',
            source_name='Measures_TempoAverageWordsPerMinute',
        ),
        Column('measures_agitation', 'FLOAT', source_name='Measures_Agitation'),
        Column('others_udf_text_29', 'VARCHAR', source_name='Others_UDF_text_29'),
        Column(
            'others_silence_duration_average_seconds',
            'FLOAT',
            source_name='Others_SilenceDurationAverageSeconds',
        ),
        Column('others_index_length', 'NUMBER', source_name='Others_IndexLength'),
        Column(
            'others_silence_duration_total_seconds',
            'FLOAT',
            source_name='Others_SilenceDurationTotalSeconds',
        ),
        Column('others_source_sqlserver', 'VARCHAR', source_name='Others_SourceSQLServer'),
        Column('others_create_date', 'TIMESTAMP_LTZ(3)', source_name='Others_CreateDate'),
        Column('others_processing_hold', 'NUMBER', source_name='Others_ProcessingHold'),
        Column('others_id', 'NUMBER', source_name='Others_ID'),
        Column(
            'others_silence_location_weighted_average_seconds',
            'FLOAT',
            source_name='Others_SilenceLocationWeightedAverageSeconds',
        ),
        Column('others_location_call_id', 'NUMBER', source_name='Others_LocationCallID'),
        Column('others_exit_status', 'VARCHAR', source_name='Others_ExitStatus'),
        Column('others_call_date', 'TIMESTAMP_LTZ(3)', source_name='Others_CallDate'),
        Column('others_tenant_apikey', 'VARCHAR', source_name='Others_TenantAPIKey'),
        Column(
            'others_entered_queue_date', 'TIMESTAMP_LTZ(3)', source_name='Others_EnteredQueueDate'
        ),
        Column('others_ani', 'VARCHAR', source_name='Others_ANI'),
        Column('others_parent_id', 'NUMBER', source_name='Others_ParentID'),
        Column('others_udf_text_04', 'VARCHAR', source_name='Others_UDF_text_04'),
        Column('others_is_sample', 'VARCHAR', source_name='Others_IsSample'),
        Column('others_udf_text_30', 'VARCHAR', source_name='Others_UDF_text_30'),
        Column('others_udf_date_01', 'TIMESTAMP_LTZ(3)', source_name='Others_UDF_Date_01'),
        Column('others_sequence_id', 'NUMBER', source_name='Others_SequenceID'),
        Column('others_noise_percent', 'FLOAT', source_name='Others_Noise_percent'),
        Column('others_path_mode', 'NUMBER', source_name='Others_PathMode'),
        Column(
            'others_noise_location_weighted_average_seconds',
            'FLOAT',
            source_name='Others_NoiseLocationWeightedAverageSeconds',
        ),
        Column(
            'others_silence_duration_min_seconds',
            'FLOAT',
            source_name='Others_SilenceDurationMinSeconds',
        ),
        Column('others_stress_min', 'FLOAT', source_name='Others_StressMin'),
        Column(
            'others_stress_standard_deviation',
            'FLOAT',
            source_name='Others_StressStandardDeviation',
        ),
        Column('others_site_name', 'VARCHAR', source_name='Others_SiteName'),
        Column('others_udf_date_02', 'TIMESTAMP_LTZ(3)', source_name='Others_UDF_Date_02'),
        Column(
            'others_noise_duration_total_seconds',
            'FLOAT',
            source_name='Others_NoiseDurationTotalSeconds',
        ),
        Column('others_udf_text_01', 'VARCHAR', source_name='Others_UDF_text_01'),
        Column('others_wavpath', 'VARCHAR', source_name='Others_WAVPath'),
        Column(
            'others_noise_duration_max_seconds',
            'FLOAT',
            source_name='Others_NoiseDurationMaxSeconds',
        ),
        Column('others_total_silence_seconds', 'NUMBER', source_name='Others_TotalSilenceSeconds'),
        Column('others_udf_text_05', 'VARCHAR', source_name='Others_UDF_text_05'),
        Column(
            'others_use_default_credentials', 'VARCHAR', source_name='Others_UseDefaultCredentials'
        ),
        Column('others_stress_max', 'FLOAT', source_name='Others_StressMax'),
        Column(
            'others_silence_total_segments', 'NUMBER', source_name='Others_SilenceTotalSegments'
        ),
        Column('others_content_id', 'VARCHAR', source_name='Others_ContentID'),
        Column('others_client_id', 'VARCHAR', source_name='Others_ClientID'),
        Column(
            'others_noise_duration_min_seconds',
            'FLOAT',
            source_name='Others_NoiseDurationMinSeconds',
        ),
        Column('others_ctievent_list', 'VARCHAR', source_name='Others_CTIEventList'),
        Column('others_confidence_average', 'NUMBER', source_name='Others_ConfidenceAverage'),
        Column(
            'others_client_capture_date_ut',
            'TIMESTAMP_LTZ(3)',
            source_name='Others_ClientCaptureDateUT',
        ),
        Column('others_request_id', 'VARCHAR', source_name='Others_RequestID'),
        Column('others_bucket_count', 'NUMBER', source_name='Others_BucketCount'),
        Column('others_content_group', 'VARCHAR', source_name='Others_ContentGroup'),
        Column('others_audio_profile', 'NUMBER', source_name='Others_AudioProfile'),
        Column('others_sequence_position', 'VARCHAR', source_name='Others_SequencePosition'),
        Column(
            'others_confidence_standard_deviation',
            'VARCHAR',
            source_name='Others_ConfidenceStandardDeviation',
        ),
        Column('others_total_hold_count', 'VARCHAR', source_name='Others_TotalHoldCount'),
        Column('others_client_capture_time', 'VARCHAR', source_name='Others_ClientCaptureTime'),
        Column(
            'others_silence_location_percent', 'FLOAT', source_name='Others_Silence_LocationPercent'
        ),
        Column('others_noise_total_segments', 'NUMBER', source_name='Others_NoiseTotalSegments'),
        Column('others_referrer_url', 'VARCHAR', source_name='Others_ReferrerURL'),
        Column(
            'others_noise_duration_average_seconds',
            'FLOAT',
            source_name='Others_NoiseDurationAverageSeconds',
        ),
        Column('others_stress_average', 'FLOAT', source_name='Others_StressAverage'),
        Column('others_wait_time_seconds', 'NUMBER', source_name='Others_WaitTimeSeconds'),
        Column('others_client_capture_date', 'VARCHAR', source_name='Others_ClientCaptureDate'),
        Column('others_correlation_id', 'VARCHAR', source_name='Others_CorrelationID'),
        Column('others_segment_information', 'VARIANT', source_name='Others_SegmentInformation'),
        Column('sections', 'VARIANT', source_name='Sections'),
        Column('categories', 'VARIANT', source_name='Categories'),
        Column('scores', 'VARIANT', source_name='Scores'),
        Column('score_components', 'VARIANT', source_name='ScoreComponents'),
    ],
)

transcripts_config = Config(
    schema='callminer',
    table='transcripts',
    version='v1',
    column_list=[
        Column('contact_id', 'NUMBER', source_name='ContactID', uniqueness=True),
        Column('word', 'VARCHAR', source_name='Word'),
        Column('start_time', 'VARCHAR', source_name='StartTime', uniqueness=True),
        Column('speaker_id', 'NUMBER', source_name='SpeakerID'),
        Column('speaker_name', 'VARCHAR', source_name='SpeakerName'),
        Column('confidence', 'NUMBER', source_name='Confidence'),
        Column('is_new_line', 'BOOLEAN', source_name='IsNewLine'),
    ],
)

contacts_bulk_config = [
    Config(
        schema='callminer',
        table='contacts_new',
        version='v1',
        column_list=[
            Column('contact_id', 'NUMBER', source_name='ID', uniqueness=True),
            Column('attributes_location', 'VARCHAR', source_name='Location'),
            Column('contact_type', 'VARCHAR', source_name='SourceDocumentTypeName'),
            # Column('contact_wav_path', 'VARCHAR', source_name='Contact_WavPath'),
            Column(
                'last_modified', 'TIMESTAMP_LTZ(3)', source_name='LastModified', delta_column=True
            ),
            Column('attributes_customer_account', 'VARCHAR', source_name='CustomerAccount'),
            Column('attributes_subject', 'VARCHAR', source_name='Subject'),
            # Column('attributes_comment', 'VARCHAR', source_name='Comment'),
            Column('attributes_dnis', 'VARCHAR', source_name='DNIS'),
            Column('attributes_source_document_type', 'NUMBER', source_name='SourceDocumentType'),
            Column('attributes_udf_text_09', 'VARCHAR', source_name='UDF_text_09'),
            Column('attributes_message_total', 'NUMBER', source_name='MessageTotal'),
            Column('attributes_audio_source_name', 'VARCHAR', source_name='AudioSourceName'),
            Column('attributes_udf_text_02', 'VARCHAR', source_name='UDF_text_02'),
            Column('attributes_udf_text_03', 'VARCHAR', source_name='UDF_text_03'),
            Column('attributes_udf_text_06', 'VARCHAR', source_name='UDF_text_06'),
            Column('attributes_udf_text_23', 'VARCHAR', source_name='UDF_text_23'),
            Column('attributes_id', 'NUMBER', source_name='ID'),
            Column('attributes_udf_text_21', 'VARCHAR', source_name='UDF_text_21'),
            Column('attributes_dept', 'VARCHAR', source_name='Dept'),
            Column('attributes_direction', 'VARCHAR', source_name='Direction'),
            Column('attributes_agent', 'VARCHAR', source_name='Agent'),
            Column('attributes_agent_group', 'VARCHAR', source_name='AgentGroup'),
            Column('attributes_description', 'VARCHAR', source_name='Description'),
            Column(
                'attributes_source_document_type_name',
                'VARCHAR',
                source_name='SourceDocumentTypeName',
            ),
            Column('measures_udf_num_04', 'VARCHAR', source_name='UDF_num_04'),
            Column('measures_udf_num_07', 'VARCHAR', source_name='UDF_num_07'),
            Column(
                'measures_silence_duration_max_seconds',
                'FLOAT',
                source_name='SilenceDurationMaxSeconds',
            ),
            Column('measures_average_delay', 'FLOAT', source_name='AverageDelay'),
            Column('measures_sentiment_compound', 'FLOAT', source_name='SentimentCompound'),
            Column('measures_silence_percent', 'FLOAT', source_name='Silence_percent'),
            Column('measures_word_count', 'NUMBER', source_name='WordCount'),
            Column('measures_udf_num_05', 'NUMBER', source_name='UDF_num_05'),
            Column('measures_id_1', 'NUMBER', source_name='ID'),
            Column('measures_id', 'NUMBER', source_name='ID'),
            Column('measures_udf_num_03', 'VARCHAR', source_name='UDF_num_03'),
            Column('measures_sentiment_positive', 'FLOAT', source_name='SentimentPositive'),
            Column('measures_max_delay', 'FLOAT', source_name='MaxDelay'),
            Column('measures_sentiment_negative', 'FLOAT', source_name='SentimentNegative'),
            Column('measures_udf_num_02', 'NUMBER', source_name='UDF_num_02'),
            Column('measures_udf_num_01', 'NUMBER', source_name='UDF_num_01'),
            Column('measures_text_length', 'FLOAT', source_name='TextLength'),
            Column('measures_total_hold_seconds', 'FLOAT', source_name='TotalHoldSeconds'),
            Column('measures_wavlength', 'NUMBER', source_name='WAVLength'),
            Column(
                'measures_tempo_average_words_per_minute',
                'FLOAT',
                source_name='TempoAverageWordsPerMinute',
            ),
            Column('measures_agitation', 'FLOAT', source_name='Agitation'),
            Column('others_udf_text_29', 'VARCHAR', source_name='UDF_text_29'),
            Column(
                'others_silence_duration_average_seconds',
                'FLOAT',
                source_name='SilenceDurationAverageSeconds',
            ),
            # Column('others_index_length', 'NUMBER', source_name='WAVLength'),
            Column(
                'others_silence_duration_total_seconds',
                'FLOAT',
                source_name='SilenceDurationTotalSeconds',
            ),
            # Column('others_source_sqlserver', 'VARCHAR', source_name='Others_SourceSQLServer'),
            Column('others_create_date', 'TIMESTAMP_LTZ(3)', source_name='CreateDate'),
            # Column('others_processing_hold', 'NUMBER', source_name='Others_ProcessingHold'),
            Column('others_id', 'NUMBER', source_name='ID'),
            Column(
                'others_silence_location_weighted_average_seconds',
                'FLOAT',
                source_name='SilenceLocationWeightedAverageSeconds',
            ),
            Column('others_location_call_id', 'NUMBER', source_name='LocationCallID'),
            Column('others_exit_status', 'VARCHAR', source_name='ExitStatus'),
            Column('others_call_date', 'TIMESTAMP_LTZ(3)', source_name='CallDate'),
            Column('others_tenant_apikey', 'VARCHAR', source_name='TenantAPIKey'),
            Column('others_entered_queue_date', 'TIMESTAMP_LTZ(3)', source_name='EnteredQueueDate'),
            Column('others_ani', 'VARCHAR', source_name='ANI'),
            # Column('others_parent_id', 'NUMBER', source_name='Others_ParentID'),
            Column('others_udf_text_04', 'VARCHAR', source_name='UDF_text_04'),
            # Column('others_is_sample', 'VARCHAR', source_name='Others_IsSample'),
            Column('others_udf_text_30', 'VARCHAR', source_name='UDF_text_30'),
            Column('others_udf_date_01', 'TIMESTAMP_LTZ(3)', source_name='UDF_Date_01'),
            Column('others_sequence_id', 'NUMBER', source_name='SequenceID'),
            Column('others_noise_percent', 'FLOAT', source_name='Noise_percent'),
            # Column('others_path_mode', 'NUMBER', source_name='Others_PathMode'),
            Column(
                'others_noise_location_weighted_average_seconds',
                'FLOAT',
                source_name='NoiseLocationWeightedAverageSeconds',
            ),
            Column(
                'others_silence_duration_min_seconds',
                'FLOAT',
                source_name='SilenceDurationMinSeconds',
            ),
            Column('others_stress_min', 'FLOAT', source_name='StressMin'),
            Column(
                'others_stress_standard_deviation',
                'FLOAT',
                source_name='StressStandardDeviation',
            ),
            Column('others_site_name', 'VARCHAR', source_name='SiteName'),
            Column('others_udf_date_02', 'TIMESTAMP_LTZ(3)', source_name='UDF_Date_02'),
            Column(
                'others_noise_duration_total_seconds',
                'FLOAT',
                source_name='NoiseDurationTotalSeconds',
            ),
            Column('others_udf_text_01', 'VARCHAR', source_name='UDF_text_01'),
            # Column('others_wavpath', 'VARCHAR', source_name='Others_WAVPath'),
            Column(
                'others_noise_duration_max_seconds',
                'FLOAT',
                source_name='NoiseDurationMaxSeconds',
            ),
            Column('others_total_silence_seconds', 'NUMBER', source_name='TotalSilenceSeconds'),
            Column('others_udf_text_05', 'VARCHAR', source_name='UDF_text_05'),
            # Column(
            #     'others_use_default_credentials', 'VARCHAR', source_name='Others_UseDefaultCredentials'
            # ),
            Column('others_stress_max', 'FLOAT', source_name='StressMax'),
            Column('others_silence_total_segments', 'NUMBER', source_name='SilenceTotalSegments'),
            Column('others_content_id', 'VARCHAR', source_name='ContentID'),
            Column('others_client_id', 'VARCHAR', source_name='ClientID'),
            Column(
                'others_noise_duration_min_seconds',
                'FLOAT',
                source_name='NoiseDurationMinSeconds',
            ),
            Column('others_ctievent_list', 'VARCHAR', source_name='CTIEventList'),
            Column('others_confidence_average', 'NUMBER', source_name='ConfidenceAverage'),
            Column(
                'others_client_capture_date_ut',
                'TIMESTAMP_LTZ(3)',
                source_name='ClientCaptureDateUT',
            ),
            Column('others_request_id', 'VARCHAR', source_name='RequestID'),
            # Column('others_bucket_count', 'NUMBER', source_name='Others_BucketCount'),
            Column('others_content_group', 'VARCHAR', source_name='ContentGroup'),
            # Column('others_audio_profile', 'NUMBER', source_name='Others_AudioProfile'),
            Column('others_sequence_position', 'VARCHAR', source_name='SequencePosition'),
            Column(
                'others_confidence_standard_deviation',
                'VARCHAR',
                source_name='ConfidenceStandardDeviation',
            ),
            Column('others_total_hold_count', 'VARCHAR', source_name='TotalHoldCount'),
            Column('others_client_capture_time', 'VARCHAR', source_name='ClientCaptureTime'),
            Column(
                'others_silence_location_percent', 'FLOAT', source_name='Silence_LocationPercent'
            ),
            Column('others_noise_total_segments', 'NUMBER', source_name='NoiseTotalSegments'),
            Column('others_referrer_url', 'VARCHAR', source_name='ReferrerURL'),
            Column(
                'others_noise_duration_average_seconds',
                'FLOAT',
                source_name='NoiseDurationAverageSeconds',
            ),
            Column('others_stress_average', 'FLOAT', source_name='StressAverage'),
            Column('others_wait_time_seconds', 'NUMBER', source_name='WaitTimeSeconds'),
            Column('others_client_capture_date', 'VARCHAR', source_name='ClientCaptureDate'),
            Column('others_correlation_id', 'VARCHAR', source_name='CorrelationID'),
            # Column('others_segment_information', 'VARIANT', source_name='Others_SegmentInformation'),
            # Column('sections', 'VARIANT', source_name='Sections'),
        ],
    ),
    Config(
        schema='callminer',
        table='categories_new',
        version='v1',
        column_list=[
            Column('ContactID', 'NUMBER', source_name='ContactID', uniqueness=True),
            Column('CategoryID', 'NUMBER', source_name='CategoryID', uniqueness=True),
            Column('CategoryFullName', 'VARCHAR', source_name='CategoryFullName'),
            Column('CategoryName', 'VARCHAR', source_name='CategoryName'),
            Column('SectionID', 'NUMBER', source_name='SectionID', uniqueness=True),
            Column('SectionName', 'VARCHAR', source_name='SectionName'),
        ],
    ),
    Config(
        schema='callminer',
        table='categories_components_new',
        version='v1',
        column_list=[
            Column('ContactID', 'NUMBER', source_name='ContactID', uniqueness=True),
            Column('ComponentID', 'NUMBER', source_name='ComponentID', uniqueness=True),
            Column('ComponentName', 'VARCHAR', source_name='ComponentName'),
            Column('CategoryID', 'NUMBER', source_name='CategoryID', uniqueness=True),
            Column('CategoryFullName', 'VARCHAR', source_name='CategoryFullName'),
            Column('CategoryDescription', 'VARCHAR', source_name='CategoryDescription'),
            Column('CategoryName', 'VARCHAR', source_name='CategoryName'),
            Column('SectionName', 'VARCHAR', source_name='SectionName'),
            Column('StartTime', 'NUMBER(38,16)', source_name='StartTime', uniqueness=True),
            Column('EndTime', 'NUMBER(38,16)', source_name='EndTime'),
            Column('Weight', 'NUMBER(38,16)', source_name='Weight'),
            Column('SimilarityScore', 'NUMBER', source_name='SimilarityScore'),
        ],
    ),
    Config(
        schema='callminer',
        table='scores_new',
        version='v1',
        column_list=[
            Column('ContactID', 'NUMBER', source_name='ContactID', uniqueness=True),
            Column('ScoreID', 'NUMBER', source_name='ScoreID', uniqueness=True),
            Column('ScoreName', 'VARCHAR', source_name='ScoreName'),
            Column('Score', 'VARCHAR', source_name='Score'),
        ],
    ),
    Config(
        schema='callminer',
        table='score_indicators_new',
        version='v1',
        column_list=[
            Column('ContactID', 'NUMBER', source_name='ContactID', uniqueness=True),
            Column('ScoreID', 'NUMBER', source_name='ScoreID', uniqueness=True),
            Column('ScoreComponentID', 'NUMBER', source_name='ScoreComponentID', uniqueness=True),
            Column('ComponentFullName', 'VARCHAR', source_name='ComponentFullName'),
            Column('DisplayDescription', 'BOOLEAN', source_name='DisplayDescription'),
            Column('CurrentlyActive', 'BOOLEAN', source_name='CurrentlyActive'),
            Column('DisplayFormat', 'NUMBER(1,0)', source_name='DisplayFormat'),
            Column('DisplayOrder', 'NUMBER', source_name='DisplayOrder'),
            Column('Value', 'NUMBER(38,16)', source_name='Value'),
        ],
    ),
]
