from dataclasses import dataclass

from include.utils.snowflake import Column


@dataclass
class Config:
    table: str
    column_list: list
    version: str
    database: str = 'lake'
    schema: str = 'centric'
    watermark_column: str = 'COALESCE(patch_time, modified_at)'
    db_conn_id: str = 'centric_postgres_prod'


watermark_table_list = [
    Config(
        table='ed_category1',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('calendar_level', 'NUMBER'),
            Column('crew', 'NUMBER'),
            Column('crew_type', 'NUMBER'),
            Column('defaults_001', 'NUMBER'),
            Column('issue_category1', 'NUMBER'),
            Column('issue_category2', 'NUMBER'),
            Column('issue_collection', 'NUMBER'),
            Column('issue_product', 'NUMBER'),
            Column('issue_season', 'NUMBER'),
            Column('master_container', 'NUMBER'),
            Column('material_schedule', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('parent_season', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('cnt_colorway', 'NUMBER'),
            Column('cnt_documents', 'NUMBER'),
            Column('cnt_style', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('expr', 'NUMBER'),
            Column('last_child_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('material_schedule_allowed', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('tfg_division_ref', 'VARCHAR'),
            Column('wbs_reports_enabled', 'BOOLEAN'),
        ],
        version='v1',
    ),
    Config(
        table='ed_category2',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('calendar_level', 'NUMBER'),
            Column('category1', 'NUMBER'),
            Column('crew', 'NUMBER'),
            Column('crew_type', 'NUMBER'),
            Column('defaults_001', 'NUMBER'),
            Column('issue_category1', 'NUMBER'),
            Column('issue_category2', 'NUMBER'),
            Column('issue_collection', 'NUMBER'),
            Column('issue_product', 'NUMBER'),
            Column('issue_season', 'NUMBER'),
            Column('master_container', 'NUMBER'),
            Column('material_schedule', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('parent_season', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('cnt_colorway', 'NUMBER'),
            Column('cnt_documents', 'NUMBER'),
            Column('cnt_style', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('expr', 'NUMBER'),
            Column('last_child_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('material_schedule_allowed', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('tfg_division_ref', 'VARCHAR'),
            Column('tfg_num_bank_prefix1', 'VARCHAR'),
            Column('tfg_style_prefix1', 'VARCHAR'),
            Column('wbs_reports_enabled', 'BOOLEAN'),
        ],
        version='v1',
    ),
    Config(
        table='ed_classifier0',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('modified_by', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('tfg_plm_department', 'VARCHAR'),
        ],
        version='v3',
    ),
    Config(
        table='ed_classifier1',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'VARCHAR'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('tfg_gender', 'VARCHAR'),
            Column('tfg_uniqu_id', 'VARCHAR'),
        ],
        version='v1',
    ),
    Config(
        table='ed_classifier2',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('tfg_sc_category', 'VARCHAR'),
            Column('tfg_unique_id', 'VARCHAR'),
            Column('tfg_master_class', 'VARCHAR'),
            Column('tfg_case_pack', 'NUMBER'),
            Column('tfg_us_split', 'FLOAT'),
            Column('tfg_ca_split', 'FLOAT'),
            Column('tfg_round_to_case', 'BOOLEAN'),
        ],
        version='v1',
    ),
    Config(
        table='ed_classifier3',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('tfg_dept_sub_dept_class', 'VARCHAR'),
            Column('tfg_sub_department_ref', 'VARCHAR'),
            Column('tfg_division', 'VARCHAR'),
        ],
        version='v1',
    ),
    Config(
        table='ed_color_specification',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'VARCHAR'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('color_specification', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('print_specification', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('cmyk', 'VARCHAR'),
            Column('cnt_documents', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('color_model', 'VARCHAR'),
            Column('color_type', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('last_child_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('ok_for_material', 'BOOLEAN'),
            Column('ok_for_style', 'BOOLEAN'),
            Column('pantone', 'VARCHAR'),
            Column('pantone_tc', 'VARCHAR'),
            Column('rgb', 'NUMBER'),
            Column('rgb_hex', 'VARCHAR'),
            Column('rgb_triple', 'VARCHAR'),
            Column('special', 'BOOLEAN'),
            Column('sys_id', 'VARCHAR'),
            Column('tfg_color_family', 'VARCHAR'),
            Column('tfg_color_luminance_pct', 'FLOAT'),
            Column('tfg_color_std', 'VARCHAR'),
            Column('tfg_freeze_status', 'BOOLEAN'),
            Column('tfg_hue', 'FLOAT'),
            Column('tfg_is_pantone', 'BOOLEAN'),
            Column('tfg_luminosity', 'FLOAT'),
            Column('tfg_rgb_double', 'FLOAT'),
            Column('tfg_saturation', 'FLOAT'),
            Column('tfg_color_service', 'VARCHAR'),
            Column('tfg_solid_print', 'VARCHAR'),
        ],
        version='v2',
    ),
    Config(
        table='ed_colorway',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('calendar_level', 'NUMBER'),
            Column('category1', 'NUMBER'),
            Column('category2', 'NUMBER'),
            Column('class_config', 'NUMBER'),
            Column('collection', 'NUMBER'),
            Column('color_specification', 'NUMBER'),
            Column('colorway_mov', 'NUMBER'),
            Column('copied_from', 'NUMBER'),
            Column('master_container', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('parent_season', 'NUMBER'),
            Column('style_001', 'NUMBER'),
            Column('tfg_blank_colorway', 'NUMBER'),
            Column('tfg_color_sup_quote', 'NUMBER'),
            Column('tfg_first_main_material', 'NUMBER'),
            Column('tfg_parent_season', 'NUMBER'),
            Column('tfg_style_attributes_ref', 'NUMBER'),
            Column('tfg_style_attr_ref', 'NUMBER'),
            Column('tfg_style_ref', 'NUMBER'),
            Column('wbs', 'NUMBER'),
            Column('wbs_request', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('carry_over', 'BOOLEAN'),
            Column('cnt_customer_purchase_order', 'NUMBER'),
            Column('cnt_order', 'NUMBER'),
            Column('cnt_purchased_order', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('customer_earliest_target_date', 'TIMESTAMP_LTZ(3)'),
            Column('customer_total_order_volume', 'FLOAT'),
            Column('description', 'VARCHAR'),
            Column('development_type', 'VARCHAR'),
            Column('earliest_target_date', 'TIMESTAMP_LTZ(3)'),
            Column('final_inspection_relevant', 'BOOLEAN'),
            Column('inline_002', 'BOOLEAN'),
            Column('intro_date', 'TIMESTAMP_LTZ(3)'),
            Column('mass_copy', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('production_min', 'NUMBER'),
            Column('sales_volume', 'NUMBER'),
            Column('sys_id', 'VARCHAR'),
            Column('tfg_adopted', 'BOOLEAN'),
            Column('tfg_authority_bom', 'NUMBER'),
            Column('tfg_blank_colorway_sku', 'VARCHAR'),
            Column('tfg_bom_main_material_count', 'NUMBER'),
            Column('tfg_buy_category', 'VARCHAR'),
            Column('tfg_chase_category', 'VARCHAR'),
            Column('tfg_color1', 'VARCHAR'),
            Column('tfg_color2', 'VARCHAR'),
            Column('tfg_color3', 'VARCHAR'),
            Column('tfg_color_family', 'VARCHAR'),
            Column('tfg_color_sku_number', 'VARCHAR'),
            Column('tfg_color_sku_segment', 'VARCHAR'),
            Column('tfg_color_standard', 'VARCHAR'),
            Column('tfg_colorway_spec_match', 'BOOLEAN'),
            Column('tfg_colorway_suffix', 'VARCHAR'),
            Column('tfg_composition_list', 'VARCHAR'),
            Column('tfg_design_notes', 'VARCHAR'),
            Column('tfg_division', 'VARCHAR'),
            Column('tfg_fabric_category', 'VARCHAR'),
            Column('tfg_final_composition', 'VARCHAR'),
            Column('tfg_first_composition', 'VARCHAR'),
            Column('tfg_first_fabric_category', 'VARCHAR'),
            Column('tfg_forecasted_units', 'NUMBER'),
            Column('tfg_forecasted_units_sr1', 'NUMBER'),
            Column('tfg_forecasted_units_sr2', 'NUMBER'),
            Column('tfg_forecasted_units_sr3', 'NUMBER'),
            Column('tfg_ifi_flocked', 'VARCHAR'),
            Column('tfg_ifi_heightof_upper', 'VARCHAR'),
            Column('tfg_ifi_is_sport_fw', 'VARCHAR'),
            Column('tfg_ifi_majority_material_upper', 'VARCHAR'),
            Column('tfg_ifi_protective_metal_toe_cap', 'VARCHAR'),
            Column('tfg_in_sr1', 'BOOLEAN'),
            Column('tfg_in_sr2', 'BOOLEAN'),
            Column('tfg_in_sr3', 'BOOLEAN'),
            Column('tfg_last_active_status', 'BOOLEAN'),
            Column('tfg_lining', 'VARCHAR'),
            Column('tfg_main_material', 'NUMBER'),
            Column('tfg_marketing_color_name', 'VARCHAR'),
            Column('tfg_marketing_color_status', 'VARCHAR'),
            Column('tfg_marketing_story', 'VARCHAR'),
            Column('tfg_msrp_price', 'FLOAT'),
            Column('tfg_noded_url', 'VARCHAR'),
            Column('tfg_parent_season_ref', 'VARCHAR'),
            Column('tfg_rank', 'VARCHAR'),
            Column('tfg_re_color', 'BOOLEAN'),
            Column('tfg_re_order', 'BOOLEAN'),
            Column('tfg_showroom1', 'VARCHAR'),
            Column('tfg_showroom2', 'VARCHAR'),
            Column('tfg_showroom3', 'VARCHAR'),
            Column('tfg_showroom_earliest', 'VARCHAR'),
            Column('tfg_solid_print', 'VARCHAR'),
            Column('tfg_sr1', 'VARCHAR'),
            Column('tfg_sr2', 'VARCHAR'),
            Column('tfg_sr3_003', 'VARCHAR'),
            Column('tfg_target_ddp', 'FLOAT'),
            Column('tfg_target_fob', 'FLOAT'),
            Column('tfg_vipimu_pct', 'FLOAT'),
            Column('tfg_vip_price', 'FLOAT'),
            Column('total_order_volume', 'FLOAT'),
            Column('total_sample_volume', 'FLOAT'),
            Column('tst_code_backup', 'VARCHAR'),
            Column('tst_code_backup_2023_02_01', 'VARCHAR'),
            Column('wbs_enabled', 'BOOLEAN'),
            Column('tfg_vendor_color_sku', 'VARCHAR'),
        ],
        version='v3',
    ),
    Config(
        table='ed_lookup_item',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('class_config', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('subtype', 'NUMBER'),
            Column('tfg_carton_sub_class', 'NUMBER'),
            Column('tfg_country', 'NUMBER'),
            Column('tfg_destination_country', 'NUMBER'),
            Column('tfg_origin_country', 'NUMBER'),
            Column('tfg_port_of_destination', 'NUMBER'),
            Column('tfg_port_of_origin', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('final_inspection_relevant', 'VARCHAR'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('special', 'BOOLEAN'),
            Column('sys_id', 'VARCHAR'),
            Column('tfg_address', 'VARCHAR'),
            Column('tfg_carton_depth_cm', 'FLOAT'),
            Column('tfg_carton_height_cm', 'FLOAT'),
            Column('tfg_carton_volume_cubic_inches', 'FLOAT'),
            Column('tfg_carton_volume_cubic_meters', 'FLOAT'),
            Column('tfg_carton_weight_lb', 'FLOAT'),
            Column('tfg_carton_width_cm', 'FLOAT'),
            Column('tfg_div_string', 'VARCHAR'),
            Column('tfg_est_freight_destination', 'VARCHAR'),
            Column('tfg_est_freight_mode_air_def', 'FLOAT'),
            Column('tfg_est_freight_mode_air_expr', 'FLOAT'),
            Column('tfg_est_freight_mode_air_std', 'FLOAT'),
            Column('tfg_est_freight_mode_ocean_np', 'FLOAT'),
            Column('tfg_est_freight_mode_ocean_ps', 'FLOAT'),
            Column('tfg_est_freight_mode_truck', 'FLOAT'),
            Column('tfg_estimated_duty_pct', 'FLOAT'),
            Column('tfg_estimated_freight_air', 'FLOAT'),
            Column('tfg_estimated_freight_ocean', 'FLOAT'),
            Column('tfg_estimated_freight_rate', 'FLOAT'),
            Column('tfg_fulfillment_center', 'VARCHAR'),
            Column('tfg_incoterms', 'VARCHAR'),
            Column('tfg_sc_category', 'VARCHAR'),
            Column('tfg_shipping_mode', 'VARCHAR'),
            Column('tfg_style_type', 'VARCHAR'),
            Column('tfg_tarrif', 'FLOAT'),
            Column('tfg_tracking_url_prefix', 'VARCHAR'),
            Column('tfg_num_bank_div_prefix', 'VARCHAR'),
            Column('tfg_style_code_div_prefix', 'VARCHAR'),
        ],
        version='v1',
    ),
    Config(
        table='ed_material',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('a_material', 'NUMBER'),
            Column('the_parent_id', 'NUMBER'),
            Column('actual_size_range', 'NUMBER'),
            Column('authority_bom', 'NUMBER'),
            Column('calendar_level', 'NUMBER'),
            Column('calendar_msg', 'NUMBER'),
            Column('copied_from', 'NUMBER'),
            Column('crew', 'NUMBER'),
            Column('crew_type', 'NUMBER'),
            Column('default3_d_material', 'NUMBER'),
            Column('default_color', 'NUMBER'),
            Column('default_quote', 'NUMBER'),
            Column('default_size', 'NUMBER'),
            Column('designated_product_source', 'NUMBER'),
            Column('designated_product_source_supplier', 'NUMBER'),
            Column('drape_file', 'NUMBER'),
            Column('issue_category1', 'NUMBER'),
            Column('issue_category2', 'NUMBER'),
            Column('issue_collection', 'NUMBER'),
            Column('issue_product', 'NUMBER'),
            Column('issue_season', 'NUMBER'),
            Column('master_container', 'NUMBER'),
            Column('material_original_category1', 'NUMBER'),
            Column('material_original_season', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('product_type', 'NUMBER'),
            Column('selected_blended_cost', 'NUMBER'),
            Column('selected_cost_scenario', 'NUMBER'),
            Column('tfg_supplier_requests', 'NUMBER'),
            Column('tooling_size_range', 'NUMBER'),
            Column('wbs', 'NUMBER'),
            Column('wbs_request', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('bom_main_material_count', 'NUMBER'),
            Column('cnt_documents', 'NUMBER'),
            Column('cnt_order', 'NUMBER'),
            Column('cnt_purchased_order', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('composition', 'VARCHAR'),
            Column('construction', 'VARCHAR'),
            Column('default_color_size_availability', 'BOOLEAN'),
            Column('default_material_family', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('diameter', 'VARCHAR'),
            Column('dimension', 'VARCHAR'),
            Column('distributor_price_act', 'FLOAT'),
            Column('earliest_target_date', 'TIMESTAMP_LTZ(3)'),
            Column('finish', 'VARCHAR'),
            Column('fob_act', 'FLOAT'),
            Column('fob_calc', 'FLOAT'),
            Column('fob_negotiated', 'FLOAT'),
            Column('has_season_availability', 'BOOLEAN'),
            Column('hidden', 'BOOLEAN'),
            Column('insurance_markup', 'FLOAT'),
            Column('insurance_premium', 'FLOAT'),
            Column('is_size_owner', 'BOOLEAN'),
            Column('is_stock_managed', 'BOOLEAN'),
            Column('last_child_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('length_001', 'VARCHAR'),
            Column('main_material', 'BOOLEAN'),
            Column('main_materials', 'VARCHAR'),
            Column('managed', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('ok_color_specs', 'BOOLEAN'),
            Column('ok_for_material_bom', 'BOOLEAN'),
            Column('ok_for_style_bom', 'BOOLEAN'),
            Column('ok_variation_by_bom_size', 'BOOLEAN'),
            Column('qty_per_container', 'FLOAT'),
            Column('sample_cost', 'FLOAT'),
            Column('sourcing_model', 'VARCHAR'),
            Column('special', 'BOOLEAN'),
            Column('status', 'VARCHAR'),
            Column('status_time', 'TIMESTAMP_LTZ(3)'),
            Column('sys_id', 'VARCHAR'),
            Column('texture_emboss_ref', 'VARCHAR'),
            Column('tfg_composition_list', 'VARCHAR'),
            Column('tfg_core_fashion', 'VARCHAR'),
            Column('tfg_cuttable_width', 'VARCHAR'),
            Column('tfg_denier', 'VARCHAR'),
            Column('tfg_dye_print_method', 'VARCHAR'),
            Column('tfg_end_use', 'VARCHAR'),
            Column('tfg_estimated_cost_currency', 'VARCHAR'),
            Column('tfg_est_uom', 'VARCHAR'),
            Column('tfg_exclusive', 'BOOLEAN'),
            Column('tfg_fabric_category', 'VARCHAR'),
            Column('tfg_footwear', 'BOOLEAN'),
            Column('tfg_greige_inventory_yardage', 'FLOAT'),
            Column('tfg_legacy_content', 'VARCHAR'),
            Column('tfg_material_auto_code', 'VARCHAR'),
            Column('tfg_material_legacy_code', 'VARCHAR'),
            Column('tfg_material_opacity', 'VARCHAR'),
            Column('tfg_material_sourced', 'BOOLEAN'),
            Column('tfg_material_sub_types', 'VARCHAR'),
            Column('tfg_nominated', 'BOOLEAN'),
            Column('tfg_notes', 'VARCHAR'),
            Column('tfg_product_supplier_list', 'VARCHAR'),
            Column('tfg_vendor_article_number', 'VARCHAR'),
            Column('tfg_warp_shrinkage_pct', 'FLOAT'),
            Column('tfg_weave_shrinkage_pct', 'FLOAT'),
            Column('tfg_yarn_size_knit_face', 'VARCHAR'),
            Column('thickness', 'VARCHAR'),
            Column('total_order_volume', 'FLOAT'),
            Column('total_shipment_qty', 'FLOAT'),
            Column('usable', 'BOOLEAN'),
            Column('usable_for_material_bom', 'BOOLEAN'),
            Column('usable_for_style_bom', 'BOOLEAN'),
            Column('usable_for_supplier_request', 'BOOLEAN'),
            Column('usage_002', 'VARCHAR'),
            Column('wbs_enabled', 'BOOLEAN'),
            Column('weight', 'VARCHAR'),
            Column('width', 'VARCHAR'),
            Column('tfg_eco_style', 'BOOLEAN'),
            Column('tfg_comments', 'VARCHAR'),
            Column('tfg_technical_callouts', 'VARCHAR'),
            Column('tfg_ld_exempt', 'BOOLEAN'),
            Column('tfg_material_marketing_name', 'VARCHAR'),
        ],
        version='v1',
    ),
    Config(
        table='ed_print_design_color',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('color_specification', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('cnt_documents', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('last_child_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('ok_for_material', 'BOOLEAN'),
            Column('ok_for_style', 'BOOLEAN'),
            Column('special', 'BOOLEAN'),
            Column('sys_id', 'VARCHAR'),
            Column('tfg_color_std', 'VARCHAR'),
            Column('tfg_color_family', 'VARCHAR'),
        ],
        version='v1',
    ),
    Config(
        table='ed_size_range',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('base_size', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('description', 'VARCHAR'),
            Column('dimension1_type', 'VARCHAR'),
            Column('dimension2_type', 'VARCHAR'),
            Column('is_two_dim', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('ok_for_material', 'BOOLEAN'),
            Column('ok_for_size_chart', 'BOOLEAN'),
            Column('ok_for_style', 'BOOLEAN'),
            Column('tfg_plus', 'BOOLEAN'),
            Column('type_001', 'VARCHAR'),
            Column('tfg_regular', 'BOOLEAN'),
            Column('tfg_division_enum', 'VARCHAR'),
            Column('tfg_ok_for_po', 'BOOLEAN'),
        ],
        version='v1',
    ),
    Config(
        table='ed_style',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('actual_size_range', 'NUMBER'),
            Column('adopted_from_inspiration_style', 'NUMBER'),
            Column('assortment_bom', 'NUMBER'),
            Column('authority_bom', 'NUMBER'),
            Column('calendar_level', 'NUMBER'),
            Column('category1', 'NUMBER'),
            Column('category2', 'NUMBER'),
            Column('classifier3', 'NUMBER'),
            Column('collection', 'NUMBER'),
            Column('copied_from', 'NUMBER'),
            Column('created_from_sample', 'NUMBER'),
            Column('crew', 'NUMBER'),
            Column('crew_type', 'NUMBER'),
            Column('default_color', 'NUMBER'),
            Column('default_size', 'NUMBER'),
            Column('designated_product_source', 'NUMBER'),
            Column('designated_product_source_supplier', 'NUMBER'),
            Column('inspiration_sr', 'NUMBER'),
            Column('inspiration_theme', 'NUMBER'),
            Column('issue_category1', 'NUMBER'),
            Column('issue_category2', 'NUMBER'),
            Column('issue_collection', 'NUMBER'),
            Column('issue_product', 'NUMBER'),
            Column('issue_season', 'NUMBER'),
            Column('marketing_main_material', 'NUMBER'),
            Column('master_container', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('parent_season', 'NUMBER'),
            Column('production_quote', 'NUMBER'),
            Column('product_structure', 'NUMBER'),
            Column('product_type', 'NUMBER'),
            Column('sample_quote', 'NUMBER'),
            Column('selected_blended_cost', 'NUMBER'),
            Column('selected_cost_scenario', 'NUMBER'),
            Column('shape', 'NUMBER'),
            Column('style_mpv', 'NUMBER'),
            Column('style_supplier_attributes', 'NUMBER'),
            Column('tfg_blank_style', 'NUMBER'),
            Column('tfg_brand_lookup', 'NUMBER'),
            Column('tfg_brand_lookup_ref', 'NUMBER'),
            Column('tfg_capsule', 'NUMBER'),
            Column('tfg_classifier0', 'NUMBER'),
            Column('tfg_classifier1', 'NUMBER'),
            Column('tfg_classifier2', 'NUMBER'),
            Column('tfg_collection', 'NUMBER'),
            Column('tfg_final_suppliers', 'NUMBER'),
            Column('tfg_first_main_material', 'NUMBER'),
            Column('tfg_fit_block', 'NUMBER'),
            Column('tfg_parent_season_ref', 'NUMBER'),
            Column('tfg_po_size_range', 'NUMBER'),
            Column('tfg_related_style', 'NUMBER'),
            Column('tfg_related_style_attributes', 'NUMBER'),
            Column('tfg_size_range', 'NUMBER'),
            Column('tfg_style_ref', 'NUMBER'),
            Column('tfg_style_type_ref', 'NUMBER'),
            Column('tfg_supplier_requests', 'NUMBER'),
            Column('theme', 'NUMBER'),
            Column('tool', 'NUMBER'),
            Column('tst_brand_check', 'NUMBER'),
            Column('wbs', 'NUMBER'),
            Column('wbs_request', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('bom_main_material_count', 'NUMBER'),
            Column('carry_over', 'BOOLEAN'),
            Column('cnt_colorway', 'NUMBER'),
            Column('cnt_customer_purchase_order', 'NUMBER'),
            Column('cnt_documents', 'NUMBER'),
            Column('cnt_order', 'NUMBER'),
            Column('cnt_purchased_order', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('customer_earliest_target_date', 'TIMESTAMP_LTZ(3)'),
            Column('customer_total_order_volume', 'FLOAT'),
            Column('default_color_size_availability', 'BOOLEAN'),
            Column('description', 'VARCHAR'),
            Column('development_type', 'VARCHAR'),
            Column('distributor_price_act', 'FLOAT'),
            Column('earliest_target_date', 'TIMESTAMP_LTZ(3)'),
            Column('fob_act', 'FLOAT'),
            Column('fob_calc', 'FLOAT'),
            Column('fob_negotiated', 'FLOAT'),
            Column('gt_volume', 'NUMBER'),
            Column('inline_001', 'BOOLEAN'),
            Column('insurance_markup', 'FLOAT'),
            Column('insurance_premium', 'FLOAT'),
            Column('is_inspiration', 'BOOLEAN'),
            Column('is_size_owner', 'BOOLEAN'),
            Column('is_template', 'BOOLEAN'),
            Column('last_child_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('main_materials', 'VARCHAR'),
            Column('marketing_segment', 'VARCHAR'),
            Column('mass_copy', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('ok_variation_by_bom_size', 'BOOLEAN'),
            Column('original_season', 'VARCHAR'),
            Column('sales_volume', 'NUMBER'),
            Column('sample_cost', 'FLOAT'),
            Column('special', 'BOOLEAN'),
            Column('tfg_accessory', 'BOOLEAN'),
            Column('tfg_accessory_composition', 'VARCHAR'),
            Column('tfg_adopted', 'BOOLEAN'),
            Column('tfg_adopted_value', 'VARCHAR'),
            Column('tfg_blank_candidate', 'BOOLEAN'),
            Column('tfg_blank_style_sku', 'VARCHAR'),
            Column('tfg_block_reference', 'VARCHAR'),
            Column('tfg_body_length', 'VARCHAR'),
            Column('tfg_bom_count', 'FLOAT'),
            Column('tfg_bottoms_compression', 'VARCHAR'),
            Column('tfg_bottoms_rise', 'VARCHAR'),
            Column('tfg_bottoms_silhouette', 'VARCHAR'),
            Column('tfg_brand_name', 'VARCHAR'),
            Column('tfg_bra_support', 'VARCHAR'),
            Column('tfg_buy_category', 'VARCHAR'),
            Column('tfg_buyer', 'VARCHAR'),
            Column('tfg_buy_type', 'VARCHAR'),
            Column('tfg_chase_category', 'VARCHAR'),
            Column('tfg_closure', 'VARCHAR'),
            Column('tfg_cnt_style', 'VARCHAR'),
            Column('tfg_code_num_generated', 'VARCHAR'),
            Column('tfg_c_ofrom_style_season', 'VARCHAR'),
            Column('tfg_colors', 'VARCHAR'),
            Column('tfg_composition_list', 'VARCHAR'),
            Column('tfg_core_fashion', 'VARCHAR'),
            Column('tfg_courses_density', 'VARCHAR'),
            Column('tfg_coverage', 'VARCHAR'),
            Column('tfg_designer', 'VARCHAR'),
            Column('tfg_design_notes', 'VARCHAR'),
            Column('tfg_division', 'VARCHAR'),
            Column('tfg_division_ref', 'VARCHAR'),
            Column('tfg_dressy_vs_casual', 'VARCHAR'),
            Column('tfg_earliest_intro_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_earliest_showroom', 'VARCHAR'),
            Column('tfg_eco_style', 'BOOLEAN'),
            Column('tfg_estimated_cost_currency', 'VARCHAR'),
            Column('tfg_est_uom', 'VARCHAR'),
            Column('tfg_eu_core_fashion', 'VARCHAR'),
            Column('tfg_exclusive', 'BOOLEAN'),
            Column('tfg_first_composition', 'VARCHAR'),
            Column('tfg_first_fabric_category', 'VARCHAR'),
            Column('tfg_fit_comments', 'VARCHAR'),
            Column('tfg_fit_type', 'VARCHAR'),
            Column('tfg_flat_lay', 'VARCHAR'),
            Column('tfg_fw_all_over_padding', 'NUMBER'),
            Column('tfg_fw_antibacterial', 'VARCHAR'),
            Column('tfg_fw_arch_support', 'VARCHAR'),
            Column('tfg_fw_breathing_holes', 'VARCHAR'),
            Column('tfg_fw_comfort_sock', 'VARCHAR'),
            Column('tfg_fw_construction', 'VARCHAR'),
            Column('tfg_fw_cushioned_footbed', 'VARCHAR'),
            Column('tfg_fw_cushioned_heel', 'VARCHAR'),
            Column('tfg_fw_footbed_material', 'VARCHAR'),
            Column('tfg_fw_heel_height', 'VARCHAR'),
            Column('tfg_fw_heel_height_in', 'FLOAT'),
            Column('tfg_fw_heel_height_mm', 'FLOAT'),
            Column('tfg_fw_heel_type', 'VARCHAR'),
            Column('tfg_fw_last_code', 'VARCHAR'),
            Column('tfg_fw_leg_opening_in', 'FLOAT'),
            Column('tfg_fw_leg_opening_mm', 'FLOAT'),
            Column('tfg_fw_lining_material', 'VARCHAR'),
            Column('tfg_fw_memory_foam', 'VARCHAR'),
            Column('tfg_fw_midsole_material', 'VARCHAR'),
            Column('tfg_fw_outsole_material', 'VARCHAR'),
            Column('tfg_fw_platform_height', 'VARCHAR'),
            Column('tfg_fw_platform_height_in', 'FLOAT'),
            Column('tfg_fw_platform_height_mm', 'FLOAT'),
            Column('tfg_fw_shaft_height_in', 'FLOAT'),
            Column('tfg_fw_shaft_height_mm', 'FLOAT'),
            Column('tfg_fw_shaft_height_string', 'VARCHAR'),
            Column('tfg_fw_shaft_info', 'VARCHAR'),
            Column('tfg_fw_sweat_wicking', 'VARCHAR'),
            Column('tfg_fw_toe_character', 'VARCHAR'),
            Column('tfg_fw_upper_material', 'VARCHAR'),
            Column('tfg_fw_water_resistant', 'VARCHAR'),
            Column('tfg_fw_width_type', 'VARCHAR'),
            Column('tfg_gender', 'VARCHAR'),
            Column('tfg_graphic', 'BOOLEAN'),
            Column('tfg_group_name', 'VARCHAR'),
            Column('tfg_gusset', 'VARCHAR'),
            Column('tfg_handle_drop', 'VARCHAR'),
            Column('tfg_handle_width', 'VARCHAR'),
            Column('tfg_has_approved_size_chart', 'BOOLEAN'),
            Column('tfg_has_plus_size', 'BOOLEAN'),
            Column('tfg_has_price_list', 'BOOLEAN'),
            Column('tfg_has_production_bom', 'BOOLEAN'),
            Column('tfg_has_regular_size', 'BOOLEAN'),
            Column('tfg_height', 'VARCHAR'),
            Column('tfg_initial_vip_price', 'FLOAT'),
            Column('tfg_inseam', 'VARCHAR'),
            Column('tfg_inseam_length', 'VARCHAR'),
            Column('tfg_in_sr1', 'BOOLEAN'),
            Column('tfg_in_sr2', 'BOOLEAN'),
            Column('tfg_in_sr3', 'BOOLEAN'),
            Column('tfg_is_legacy', 'BOOLEAN'),
            Column('tfg_jss_due_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_legacy_collection', 'VARCHAR'),
            Column('tfg_legacy_content', 'VARCHAR'),
            Column('tfg_legacy_coo', 'VARCHAR'),
            Column('tfg_legacy_eco_system', 'VARCHAR'),
            Column('tfg_legacy_fabric_category', 'VARCHAR'),
            Column('tfg_legacy_fabric_code', 'VARCHAR'),
            Column('tfg_legacy_fabric_coo', 'VARCHAR'),
            Column('tfg_legacy_fabric_description', 'VARCHAR'),
            Column('tfg_legacy_fabric_sub_category', 'VARCHAR'),
            Column('tfg_legacy_po_size_scale', 'VARCHAR'),
            Column('tfg_legacy_showroom', 'VARCHAR'),
            Column('tfg_legacy_source_style', 'VARCHAR'),
            Column('tfg_legacy_style_code', 'VARCHAR'),
            Column('tfg_legacy_wash_instructions', 'VARCHAR'),
            Column('tfg_length', 'VARCHAR'),
            Column('tfg_lining', 'VARCHAR'),
            Column('tfg_long_strap_width', 'VARCHAR'),
            Column('tfg_marketing', 'BOOLEAN'),
            Column('tfg_master_code', 'VARCHAR'),
            Column('tfg_msrp_price', 'FLOAT'),
            Column('tfg_new_carryover', 'VARCHAR'),
            Column('tfg_noded_url', 'VARCHAR'),
            Column('tfg_notes', 'VARCHAR'),
            Column('tfg_opacity', 'VARCHAR'),
            Column('tfg_original_style_name', 'VARCHAR'),
            Column('tfg_parent_season_name', 'VARCHAR'),
            Column('tfg_plus', 'BOOLEAN'),
            Column('tfg_po_entry_status', 'BOOLEAN'),
            Column('tfg_po_readiness_status', 'VARCHAR'),
            Column('tfg_po_ready', 'BOOLEAN'),
            Column('tfg_po_size_range_valid', 'BOOLEAN'),
            Column('tfg_pp_due_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_product_category', 'VARCHAR'),
            Column('tfg_product_developer', 'VARCHAR'),
            Column('tfg_product_supplier_list', 'VARCHAR'),
            Column('tfg_proto_due_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_purchase_priority', 'VARCHAR'),
            Column('tfg_rank', 'VARCHAR'),
            Column('tfg_recycled', 'BOOLEAN'),
            Column('tfg_samples_due_in_house', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_shoe_type', 'VARCHAR'),
            Column('tfg_short_tall', 'VARCHAR'),
            Column('tfg_showroom1', 'VARCHAR'),
            Column('tfg_showroom2', 'VARCHAR'),
            Column('tfg_showroom3', 'VARCHAR'),
            Column('tfg_showroom_month1', 'VARCHAR'),
            Column('tfg_showroom_month2', 'VARCHAR'),
            Column('tfg_showroom_month3', 'VARCHAR'),
            Column('tfg_size_range_valid', 'BOOLEAN'),
            Column('tfg_sleeve_length', 'VARCHAR'),
            Column('tfg_sms_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_sourcing_comment', 'VARCHAR'),
            Column('tfg_sr1_color_report', 'VARCHAR'),
            Column('tfg_sr2_color_report', 'VARCHAR'),
            Column('tfg_sr3_color_report', 'VARCHAR'),
            Column('tfg_stage', 'VARCHAR'),
            Column('tfg_stock', 'VARCHAR'),
            Column('tfg_strap_standard', 'VARCHAR'),
            Column('tfg_stretch', 'VARCHAR'),
            Column('tfg_style_num_bank', 'VARCHAR'),
            Column('tfg_style_prefix', 'VARCHAR'),
            Column('tfg_style_sku_number', 'VARCHAR'),
            Column('tfg_suffix', 'VARCHAR'),
            Column('tfg_sync_sr_month', 'BOOLEAN'),
            Column('tfg_tech_designer', 'VARCHAR'),
            Column('tfg_tech_spec_block', 'VARCHAR'),
            Column('tfgtfg_composition_backup_230307', 'VARCHAR'),
            Column('tfg_tops_length', 'VARCHAR'),
            Column('tfg_total_forecasted_units', 'NUMBER'),
            Column('tfg_total_forecasted_units_sr1', 'NUMBER'),
            Column('tfg_total_forecasted_units_sr2', 'NUMBER'),
            Column('tfg_total_forecasted_units_sr3', 'NUMBER'),
            Column('tfg_tp_due_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_tp_handoff_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_tp_ready_date', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_wales_density', 'VARCHAR'),
            Column('tfg_web_name', 'VARCHAR'),
            Column('tfg_weight', 'VARCHAR'),
            Column('tool_status', 'VARCHAR'),
            Column('total_order_volume', 'FLOAT'),
            Column('total_shipment_qty', 'FLOAT'),
            Column('tst_code_backup', 'VARCHAR'),
            Column('tst_code_backup_2023_02_01', 'VARCHAR'),
            Column('tst_design_notes2', 'VARCHAR'),
            Column('valid_structures', 'BOOLEAN'),
            Column('wbs_enabled', 'BOOLEAN'),
            Column('wbs_reports_enabled', 'BOOLEAN'),
            Column('tfg_cad_designer', 'VARCHAR'),
            Column('tfg_vendor_style_number', 'VARCHAR'),
        ],
        version='v5',
    ),
    Config(
        table='ed_price',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('actual', 'NUMBER'),
            Column('colorway', 'NUMBER'),
            Column('comment_row', 'NUMBER'),
            Column('copy_001', 'NUMBER'),
            Column('country', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('original', 'NUMBER'),
            Column('product_sales_region', 'NUMBER'),
            Column('sku', 'NUMBER'),
            Column('tfg_colorway_attributes_ref', 'NUMBER'),
            Column('tfg_factory', 'NUMBER'),
            Column('tfg_freight_forwarder', 'NUMBER'),
            Column('tfg_port_of_origin', 'NUMBER'),
            Column('tfg_po_size_range', 'NUMBER'),
            Column('tfg_quote_factory', 'NUMBER'),
            Column('tfg_quote_ref', 'NUMBER'),
            Column('tfg_quote_ref_rev', 'NUMBER'),
            Column('tfg_quote_shipping_port', 'NUMBER'),
            Column('tfg_quote_supplier', 'NUMBER'),
            Column('tfg_shipping_port_sr1', 'NUMBER'),
            Column('tfg_shipping_port_sr2', 'NUMBER'),
            Column('tfg_shipping_port_sr3', 'NUMBER'),
            Column('tfg_style_attr_ref', 'NUMBER'),
            Column('tfg_style_ref', 'NUMBER'),
            Column('tfg_supplier', 'NUMBER'),
            Column('tfg_supplier_quote_or', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('comment_002', 'VARCHAR'),
            Column('freeze_status', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('tfg_actual_po_qty', 'NUMBER'),
            Column('tfg_actual_po_qty_sr1', 'NUMBER'),
            Column('tfg_actual_po_qty_sr2', 'NUMBER'),
            Column('tfg_actual_po_qty_sr3', 'NUMBER'),
            Column('tfg_cmt_cost', 'FLOAT'),
            Column('tfg_forecasted_units_sr1', 'NUMBER'),
            Column('tfg_forecasted_units_sr2', 'NUMBER'),
            Column('tfg_forecasted_units_sr3', 'NUMBER'),
            Column('tfg_incoterms', 'VARCHAR'),
            Column('tfg_msrp', 'FLOAT'),
            Column('tfg_msrpimu_pct', 'FLOAT'),
            Column('tfg_po_entry_requirement_status', 'VARCHAR'),
            Column('tfg_po_entry_status', 'BOOLEAN'),
            Column('tfg_po_style_number', 'VARCHAR'),
            Column('tfg_po_type', 'VARCHAR'),
            Column('tfg_po_vendor_type', 'VARCHAR'),
            Column('tfg_price', 'FLOAT'),
            Column('tfg_quote_incoterms', 'VARCHAR'),
            Column('tfg_quote_shipping_method', 'VARCHAR'),
            Column('tfg_shipping_method_sr1', 'VARCHAR'),
            Column('tfg_shipping_method_sr2', 'VARCHAR'),
            Column('tfg_shipping_method_sr3', 'VARCHAR'),
            Column('tfg_style_number', 'VARCHAR'),
            Column('tfg_total_landed_cost', 'FLOAT'),
            Column('tfg_vipimu_pct', 'FLOAT'),
            Column('tfg_vip_price', 'FLOAT'),
            Column('tfg_xfd_sr1', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_xfd_sr2', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_xfd_sr3', 'TIMESTAMP_LTZ(3)'),
            Column('tfg_coo', 'NUMBER'),
        ],
        version='v1',
    ),
    Config(
        table='ed_factory',
        column_list=[
            Column('id', 'NUMBER', source_name='id', uniqueness=True),
            Column('the_cnl', 'VARCHAR', source_name='the_cnl'),
            Column('the_deleted', 'BOOLEAN', source_name='the_deleted'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)', source_name='patch_time'),
            Column('the_created_by', 'NUMBER', source_name='the_created_by'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)', source_name='the_created_at'),
            Column('class_config', 'NUMBER', source_name='class_config'),
            Column('country', 'NUMBER', source_name='country'),
            Column('issue_category1', 'NUMBER', source_name='issue_category1'),
            Column('issue_category2', 'NUMBER', source_name='issue_category2'),
            Column('issue_collection', 'NUMBER', source_name='issue_collection'),
            Column('issue_product', 'NUMBER', source_name='issue_product'),
            Column('issue_season', 'NUMBER', source_name='issue_season'),
            Column('last_review', 'NUMBER', source_name='last_review'),
            Column('modified_by', 'NUMBER', source_name='modified_by'),
            Column(
                'next_scheduled_review_event', 'NUMBER', source_name='next_scheduled_review_event'
            ),
            Column('port_of_origin', 'NUMBER', source_name='port_of_origin'),
            Column('province_state', 'NUMBER', source_name='province_state'),
            Column('subtype', 'NUMBER', source_name='subtype'),
            Column('tfg_port_of_origin_air', 'NUMBER', source_name='tfg_port_of_origin_air'),
            Column('tfg_primary_contact', 'NUMBER', source_name='tfg_primary_contact'),
            Column('address', 'VARCHAR', source_name='address'),
            Column('address1', 'VARCHAR', source_name='address1'),
            Column('address2', 'VARCHAR', source_name='address2'),
            Column('city', 'VARCHAR', source_name='city'),
            Column('cnt_documents', 'NUMBER', source_name='cnt_documents'),
            Column('commission_pct', 'FLOAT', source_name='commission_pct'),
            Column('company', 'VARCHAR', source_name='company'),
            Column('compliant', 'BOOLEAN', source_name='compliant'),
            Column('email', 'VARCHAR', source_name='email'),
            Column('fax', 'VARCHAR', source_name='fax'),
            Column('fixed_oh_rate', 'FLOAT', source_name='fixed_oh_rate'),
            Column('job_title', 'VARCHAR', source_name='job_title'),
            Column('labor_rate', 'FLOAT', source_name='labor_rate'),
            Column('language_001', 'VARCHAR', source_name='language_001'),
            Column(
                'last_child_comment_date', 'TIMESTAMP_LTZ(3)', source_name='last_child_comment_date'
            ),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)', source_name='last_comment_date'),
            Column('lead_time', 'VARCHAR', source_name='lead_time'),
            Column('localized_address', 'VARCHAR', source_name='localized_address'),
            Column('material_burden_pct', 'FLOAT', source_name='material_burden_pct'),
            Column('min_order_amt', 'FLOAT', source_name='min_order_amt'),
            Column('min_order_surcharge', 'FLOAT', source_name='min_order_surcharge'),
            Column('mobile', 'VARCHAR', source_name='mobile'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)', source_name='modified_at'),
            Column('moq_initial', 'NUMBER', source_name='moq_initial'),
            Column('moq_reorder', 'NUMBER', source_name='moq_reorder'),
            Column('node_name', 'VARCHAR', source_name='node_name'),
            Column('payment_term', 'VARCHAR', source_name='payment_term'),
            Column('payment_terms', 'VARCHAR', source_name='payment_terms'),
            Column('phone_number', 'VARCHAR', source_name='phone_number'),
            Column('photocopy_number', 'VARCHAR', source_name='photocopy_number'),
            Column('postal_code', 'VARCHAR', source_name='postal_code'),
            Column('purpose', 'VARCHAR', source_name='purpose'),
            Column('raw_material_freight_pct', 'FLOAT', source_name='raw_material_freight_pct'),
            Column('state_002', 'VARCHAR', source_name='state_002'),
            Column('supplier_number', 'VARCHAR', source_name='supplier_number'),
            Column('tfg_active', 'BOOLEAN', source_name='tfg_active'),
            Column('tfg_address3', 'VARCHAR', source_name='tfg_address3'),
            Column('tfg_c_doc_count', 'NUMBER', source_name='tfg_c_doc_count'),
            Column('tfg_data_load', 'BOOLEAN', source_name='tfg_data_load'),
            Column('tfg_factory_upper_name', 'VARCHAR', source_name='tfg_factory_upper_name'),
            Column('tfg_fem', 'BOOLEAN', source_name='tfg_fem'),
            Column('tfg_fem_active_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_fem_active_date'),
            Column('tfg_fem_expired', 'BOOLEAN', source_name='tfg_fem_expired'),
            Column('tfg_fem_expiry_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_fem_expiry_date'),
            Column('tfg_fem_verification', 'BOOLEAN', source_name='tfg_fem_verification'),
            Column('tfg_fslm', 'BOOLEAN', source_name='tfg_fslm'),
            Column('tfg_fslm_expiry_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_fslm_expiry_date'),
            Column('tfg_fslm_expiry_duration', 'NUMBER', source_name='tfg_fslm_expiry_duration'),
            Column('tfg_fslm_set_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_fslm_set_date'),
            Column('tfg_fslm_verification', 'BOOLEAN', source_name='tfg_fslm_verification'),
            Column('tfg_higg_expiry_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_higg_expiry_date'),
            Column('tfg_higg_expiry_duration', 'NUMBER', source_name='tfg_higg_expiry_duration'),
            Column('tfg_higg_id', 'VARCHAR', source_name='tfg_higg_id'),
            Column('tfg_higg_index', 'BOOLEAN', source_name='tfg_higg_index'),
            Column('tfg_inactive', 'BOOLEAN', source_name='tfg_inactive'),
            Column('tfg_integration_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_integration_date'),
            Column('tfg_integration_status', 'VARCHAR', source_name='tfg_integration_status'),
            Column('tfg_lingerie', 'BOOLEAN', source_name='tfg_lingerie'),
            Column('tfg_merlin_confirmed', 'BOOLEAN', source_name='tfg_merlin_confirmed'),
            Column('tfg_merlin_fty_status', 'VARCHAR', source_name='tfg_merlin_fty_status'),
            Column('tfg_oid', 'VARCHAR', source_name='tfg_oid'),
            Column('tfg_requirements_ok', 'BOOLEAN', source_name='tfg_requirements_ok'),
            Column('tfg_requirements_status', 'VARCHAR', source_name='tfg_requirements_status'),
            Column('tfg_second_tier', 'BOOLEAN', source_name='tfg_second_tier'),
            Column('tfg_send_to_merlin', 'BOOLEAN', source_name='tfg_send_to_merlin'),
            Column('tfg_vendor_address_type', 'VARCHAR', source_name='tfg_vendor_address_type'),
            Column('trade_term', 'VARCHAR', source_name='trade_term'),
            Column('variable_oh_rate', 'FLOAT', source_name='variable_oh_rate'),
            Column('volume_capacity', 'NUMBER', source_name='volume_capacity'),
            Column('website', 'VARCHAR', source_name='website'),
        ],
        version='v1',
    ),
    Config(
        table='ed_product_size',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('the_parent_id', 'NUMBER'),
            Column('dimension1_size', 'NUMBER'),
            Column('dimension2_size', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('dimension_type', 'VARCHAR'),
            Column('is_two_dim', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('size_code', 'NUMBER'),
            Column('sys_id', 'VARCHAR'),
            Column('tfg_plus', 'BOOLEAN'),
            Column('tfg_size_sku_segment', 'VARCHAR'),
            Column('us_label', 'VARCHAR'),
        ],
        version='v1',
    ),
    Config(
        table='tfg_datachanges',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('table_name', 'VARCHAR'),
            Column('operation', 'VARCHAR'),
            Column('table_id', 'NUMBER'),
            Column('the_cnl', 'VARCHAR'),
            Column('date_modified', 'TIMESTAMP_LTZ(3)'),
            Column('date_da_integrated', 'TIMESTAMP_LTZ(3)'),
        ],
        version='v1',
        watermark_column='date_modified',
    ),
    Config(
        table='ed_sku',
        version='v2',
        column_list=[
            Column('id', 'NUMBER', source_name='id', uniqueness=True),
            Column('the_cnl', 'VARCHAR', source_name='the_cnl'),
            Column('the_deleted', 'BOOLEAN', source_name='the_deleted'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)', source_name='patch_time'),
            Column('the_created_by', 'NUMBER', source_name='the_created_by'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)', source_name='the_created_at'),
            Column('the_parent_id', 'NUMBER', source_name='the_parent_id'),
            Column('calendar_level', 'NUMBER', source_name='calendar_level'),
            Column('category1', 'NUMBER', source_name='category1'),
            Column('category2', 'NUMBER', source_name='category2'),
            Column('collection', 'NUMBER', source_name='collection'),
            Column('master_container', 'NUMBER', source_name='master_container'),
            Column('modified_by', 'NUMBER', source_name='modified_by'),
            Column('parent_season', 'NUMBER', source_name='parent_season'),
            Column('realized_color', 'NUMBER', source_name='realized_color'),
            Column('realized_size', 'NUMBER', source_name='realized_size'),
            Column('sku_quote', 'NUMBER', source_name='sku_quote'),
            Column('style_001', 'NUMBER', source_name='style_001'),
            Column('tfg_blank_sku', 'NUMBER', source_name='tfg_blank_sku'),
            Column('wbs', 'NUMBER', source_name='wbs'),
            Column('wbs_request', 'NUMBER', source_name='wbs_request'),
            Column('active', 'BOOLEAN', source_name='active'),
            Column('carry_over', 'BOOLEAN', source_name='carry_over'),
            Column('cnt_documents', 'NUMBER', source_name='cnt_documents'),
            Column(
                'customer_earliest_target_date',
                'TIMESTAMP_LTZ(3)',
                source_name='customer_earliest_target_date',
            ),
            Column('customer_total_order_qty', 'FLOAT', source_name='customer_total_order_qty'),
            Column('earliest_target_date', 'TIMESTAMP_LTZ(3)', source_name='earliest_target_date'),
            Column('gtin', 'VARCHAR', source_name='gtin'),
            Column('gtin_checksum', 'VARCHAR', source_name='gtin_checksum'),
            Column('gtin_manufacturer_code', 'VARCHAR', source_name='gtin_manufacturer_code'),
            Column('gtin_product_code', 'VARCHAR', source_name='gtin_product_code'),
            Column(
                'last_child_comment_date', 'TIMESTAMP_LTZ(3)', source_name='last_child_comment_date'
            ),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)', source_name='last_comment_date'),
            Column('master_carton_i2_of5', 'VARCHAR', source_name='master_carton_i2_of5'),
            Column(
                'master_carton_i2_of5_checksum',
                'VARCHAR',
                source_name='master_carton_i2_of5_checksum',
            ),
            Column(
                'master_carton_i2_of5_leading_digit',
                'VARCHAR',
                source_name='master_carton_i2_of5_leading_digit',
            ),
            Column(
                'master_carton_i2_of5_pack_code',
                'VARCHAR',
                source_name='master_carton_i2_of5_pack_code',
            ),
            Column('modified_at', 'TIMESTAMP_LTZ(3)', source_name='modified_at'),
            Column('node_name', 'VARCHAR', source_name='node_name'),
            Column('pallet_i2_of5', 'VARCHAR', source_name='pallet_i2_of5'),
            Column('pallet_i2_of5_checksum', 'VARCHAR', source_name='pallet_i2_of5_checksum'),
            Column(
                'pallet_i2_of5_leading_digit', 'VARCHAR', source_name='pallet_i2_of5_leading_digit'
            ),
            Column('pallet_i2_of5_pack_code', 'VARCHAR', source_name='pallet_i2_of5_pack_code'),
            Column('sku_status', 'VARCHAR', source_name='sku_status'),
            Column('tfg_code', 'VARCHAR', source_name='tfg_code'),
            Column('tfg_color_sku_segment', 'VARCHAR', source_name='tfg_color_sku_segment'),
            Column('tfg_colorway_sku', 'VARCHAR', source_name='tfg_colorway_sku'),
            Column('tfg_division', 'VARCHAR', source_name='tfg_division'),
            Column(
                'tfg_imported_date_time', 'TIMESTAMP_LTZ(3)', source_name='tfg_imported_date_time'
            ),
            Column('tfg_size_sku_segment', 'VARCHAR', source_name='tfg_size_sku_segment'),
            Column('tfg_style_sku_segment', 'VARCHAR', source_name='tfg_style_sku_segment'),
            Column('tfg_upc_code', 'VARCHAR', source_name='tfg_upc_code'),
            Column('total_order_qty', 'FLOAT', source_name='total_order_qty'),
            Column('wbs_enabled', 'BOOLEAN', source_name='wbs_enabled'),
            Column('tfg_vendor_sku', 'VARCHAR', source_name='tfg_vendor_sku'),
        ],
    ),
    Config(
        table='ed_season',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('the_cnl', 'VARCHAR'),
            Column('the_deleted', 'BOOLEAN'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('the_created_by', 'NUMBER'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('crew', 'NUMBER'),
            Column('crew_type', 'NUMBER'),
            Column('defaults_001', 'NUMBER'),
            Column('issue_category1', 'NUMBER'),
            Column('issue_category2', 'NUMBER'),
            Column('issue_collection', 'NUMBER'),
            Column('issue_product', 'NUMBER'),
            Column('issue_season', 'NUMBER'),
            Column('master_calendar_level', 'NUMBER'),
            Column('material_schedule', 'NUMBER'),
            Column('modified_by', 'NUMBER'),
            Column('parent_season', 'NUMBER'),
            Column('tfg_division_header', 'NUMBER'),
            Column('active', 'BOOLEAN'),
            Column('cnt_colorway', 'NUMBER'),
            Column('cnt_documents', 'NUMBER'),
            Column('cnt_style', 'NUMBER'),
            Column('code', 'VARCHAR'),
            Column('description', 'VARCHAR'),
            Column('expr', 'NUMBER'),
            Column('freeze_status', 'BOOLEAN'),
            Column('last_child_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_comment_date', 'TIMESTAMP_LTZ(3)'),
            Column('last_pruned', 'TIMESTAMP_LTZ(3)'),
            Column('mass_copy_status', 'VARCHAR'),
            Column('material_schedule_allowed', 'BOOLEAN'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('node_name', 'VARCHAR'),
            Column('status', 'VARCHAR'),
            Column('tfg_div_code', 'VARCHAR'),
            Column('tfg_division', 'VARCHAR'),
            Column('tfg_division_name', 'VARCHAR'),
            Column('tfg_division_ref', 'VARCHAR'),
            Column('tfg_season_div_code', 'VARCHAR'),
            Column('tfg_season_name', 'VARCHAR'),
            Column('tfg_season_sort', 'VARCHAR'),
            Column('tfg_season_year', 'VARCHAR'),
            Column('tfg_showroom1', 'VARCHAR'),
            Column('tfg_showroom2', 'VARCHAR'),
            Column('tfg_showroom3', 'VARCHAR'),
            Column('wbs_reports_enabled', 'BOOLEAN'),
        ],
        version='v1',
    ),
    Config(
        table='ed_product_sales_region',
        column_list=[
            Column('id', 'NUMBER', source_name='id', uniqueness=True),
            Column('the_cnl', 'VARCHAR', source_name='the_cnl'),
            Column('the_deleted', 'BOOLEAN', source_name='the_deleted'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)', source_name='patch_time'),
            Column('the_created_by', 'NUMBER', source_name='the_created_by'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)', source_name='the_created_at'),
            Column('the_parent_id', 'NUMBER', source_name='the_parent_id'),
            Column('modified_by', 'NUMBER', source_name='modified_by'),
            Column('product_sales_region_spec', 'NUMBER', source_name='product_sales_region_spec'),
            Column('sales_region_agent', 'NUMBER', source_name='sales_region_agent'),
            Column('sales_region_factory', 'NUMBER', source_name='sales_region_factory'),
            Column('active', 'BOOLEAN', source_name='active'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)', source_name='modified_at'),
            Column('node_name', 'VARCHAR', source_name='node_name'),
        ],
        version='v1',
    ),
]

no_watermark_table_list = [
    Config(
        table='er_style',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('attr_id', 'VARCHAR', uniqueness=True),
            Column('map_key', 'VARCHAR', uniqueness=True),
            Column('ref_id', 'NUMBER'),
        ],
        version='v1',
    ),
    Config(
        table='et_style',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('attr_id', 'VARCHAR', uniqueness=True),
            Column('map_key', 'VARCHAR', uniqueness=True),
            Column('text_value', 'VARCHAR'),
        ],
        version='v1',
    ),
    Config(
        table='er_size_range',
        column_list=[
            Column('id', 'NUMBER', uniqueness=True),
            Column('attr_id', 'VARCHAR', uniqueness=True),
            Column('map_key', 'VARCHAR', uniqueness=True),
            Column('ref_id', 'NUMBER'),
        ],
        version='v1',
    ),
]

truncate_load_table_list = [
    Config(
        table='tfg_drayage',
        column_list=[
            Column('id', 'NUMBER', source_name='id', uniqueness=True),
            Column('the_cnl', 'VARCHAR', source_name='the_cnl'),
            Column('node_name', 'VARCHAR', source_name='node_name'),
            Column('active', 'BOOLEAN', source_name='active'),
            Column('code', 'VARCHAR', source_name='code'),
            Column('description', 'VARCHAR', source_name='description'),
            Column('subtype', 'NUMBER', source_name='subtype'),
            Column('subtype_node_name', 'VARCHAR', source_name='subtype_node_name'),
            Column('tfg_effective_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_effective_date'),
            Column('tfg_port_of_destination', 'NUMBER', source_name='tfg_port_of_destination'),
            Column('port_of_destination_name', 'VARCHAR', source_name='port_of_destination_name'),
            Column('port_of_destination_city', 'VARCHAR', source_name='port_of_destination_city'),
            Column('tfg_origin_warehouse_ref', 'NUMBER', source_name='tfg_origin_warehouse_ref'),
            Column('origin_warehouse_name', 'VARCHAR', source_name='origin_warehouse_name'),
            Column('origin_warehouse_code', 'VARCHAR', source_name='origin_warehouse_code'),
            Column(
                'origin_warehouse_merlin_name',
                'VARCHAR',
                source_name='origin_warehouse_merlin_name',
            ),
            Column('tfg_cost', 'FLOAT', source_name='tfg_cost'),
            Column('tfg_freight_cost_per', 'VARCHAR', source_name='tfg_freight_cost_per'),
            Column('the_deleted', 'BOOLEAN', source_name='the_deleted'),
            Column('the_created_by', 'NUMBER', source_name='the_created_by'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)', source_name='the_created_at'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)', source_name='modified_at'),
            Column('modified_by', 'NUMBER', source_name='modified_by'),
        ],
        version='v2',
    ),
    Config(
        table='tfg_shipping_rates',
        column_list=[
            Column('id', 'NUMBER', source_name='id', uniqueness=True),
            Column('the_cnl', 'VARCHAR', source_name='the_cnl'),
            Column('node_name', 'VARCHAR', source_name='node_name'),
            Column('effective_date', 'TIMESTAMP_LTZ(3)', source_name='effective_date'),
            Column('port_of_origin', 'NUMBER', source_name='port_of_origin'),
            Column('port_of_origin_city', 'VARCHAR', source_name='port_of_origin_city'),
            Column(
                'tfg_port_of_origin_country', 'NUMBER', source_name='tfg_port_of_origin_country'
            ),
            Column('origin_country_name', 'VARCHAR', source_name='origin_country_name'),
            Column('port_of_destination', 'NUMBER', source_name='port_of_destination'),
            Column('port_of_destination_city', 'VARCHAR', source_name='port_of_destination_city'),
            Column(
                'tfg_port_of_destination_country',
                'NUMBER',
                source_name='tfg_port_of_destination_country',
            ),
            Column('destination_country_name', 'VARCHAR', source_name='destination_country_name'),
            Column('tfg_first_warehouse', 'NUMBER', source_name='tfg_first_warehouse'),
            Column('first_warehouse_name', 'VARCHAR', source_name='first_warehouse_name'),
            Column('first_warehouse_dba_name', 'VARCHAR', source_name='first_warehouse_dba_name'),
            Column(
                'first_warehouse_airport_code',
                'VARCHAR',
                source_name='first_warehouse_airport_code',
            ),
            Column('first_warehouse_id', 'VARCHAR', source_name='first_warehouse_id'),
            Column('first_warehouse_code', 'VARCHAR', source_name='first_warehouse_code'),
            Column(
                'first_warehouse_merlin_name', 'VARCHAR', source_name='first_warehouse_merlin_name'
            ),
            Column('tfg_final_warehouse', 'NUMBER', source_name='tfg_final_warehouse'),
            Column('final_warehouse_name', 'VARCHAR', source_name='final_warehouse_name'),
            Column('final_warehouse_dba_name', 'VARCHAR', source_name='final_warehouse_dba_name'),
            Column(
                'final_warehouse_airport_code',
                'VARCHAR',
                source_name='final_warehouse_airport_code',
            ),
            Column('final_warehouse_id', 'VARCHAR', source_name='final_warehouse_id'),
            Column('final_warehouse_code', 'VARCHAR', source_name='final_warehouse_code'),
            Column(
                'final_warehouse_merlin_name', 'VARCHAR', source_name='final_warehouse_merlin_name'
            ),
            Column('shipment_type', 'VARCHAR', source_name='shipment_type'),
            Column('tfg_freight_method', 'VARCHAR', source_name='tfg_freight_method'),
            Column('container', 'NUMBER', source_name='container'),
            Column('container_name', 'VARCHAR', source_name='container_name'),
            Column('container_max_cbm', 'FLOAT', source_name='container_max_cbm'),
            Column('container_utilization_pct', 'FLOAT', source_name='container_utilization_pct'),
            Column('container_utilization_cbm', 'FLOAT', source_name='container_utilization_cbm'),
            Column('dimensional_weight_factor', 'FLOAT', source_name='dimensional_weight_factor'),
            Column('rate', 'FLOAT', source_name='rate'),
            Column('tfg_has_drayage', 'BOOLEAN', source_name='tfg_has_drayage'),
            Column('tfg_has_transload', 'BOOLEAN', source_name='tfg_has_transload'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)', source_name='the_created_at'),
            Column('the_created_by', 'NUMBER', source_name='the_created_by'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)', source_name='modified_at'),
            Column('modified_by', 'NUMBER', source_name='modified_by'),
            Column('the_deleted', 'BOOLEAN', source_name='the_deleted'),
            Column('tfg_active', 'BOOLEAN', source_name='tfg_active'),
        ],
        version='v4',
    ),
    Config(
        table='tfg_transload',
        column_list=[
            Column('id', 'NUMBER', source_name='id', uniqueness=True),
            Column('the_cnl', 'VARCHAR', source_name='the_cnl'),
            Column('node_name', 'VARCHAR', source_name='node_name'),
            Column('active', 'BOOLEAN', source_name='active'),
            Column('code', 'VARCHAR', source_name='code'),
            Column('description', 'VARCHAR', source_name='description'),
            Column('subtype', 'NUMBER', source_name='subtype'),
            Column('subtype_node_name', 'VARCHAR', source_name='subtype_node_name'),
            Column('tfg_effective_date', 'TIMESTAMP_LTZ(3)', source_name='tfg_effective_date'),
            Column(
                'tfg_destination_warehouse_ref',
                'NUMBER',
                source_name='tfg_destination_warehouse_ref',
            ),
            Column(
                'destination_warehouse_name', 'VARCHAR', source_name='destination_warehouse_name'
            ),
            Column(
                'destination_warehouse_code', 'VARCHAR', source_name='destination_warehouse_code'
            ),
            Column(
                'destination_warehouse_merlin_name',
                'VARCHAR',
                source_name='destination_warehouse_merlin_name',
            ),
            Column('tfg_origin_warehouse_ref', 'NUMBER', source_name='tfg_origin_warehouse_ref'),
            Column('origin_warehouse_name', 'VARCHAR', source_name='origin_warehouse_name'),
            Column('origin_warehouse_code', 'VARCHAR', source_name='origin_warehouse_code'),
            Column(
                'origin_warehouse_merlin_name',
                'VARCHAR',
                source_name='origin_warehouse_merlin_name',
            ),
            Column('tfg_cost', 'FLOAT', source_name='tfg_cost'),
            Column('tfg_freight_cost_per', 'VARCHAR', source_name='tfg_freight_cost_per'),
            Column('container', 'NUMBER', source_name='container'),
            Column('container_name', 'VARCHAR', source_name='container_name'),
            Column('container_max_cbm', 'FLOAT', source_name='container_max_cbm'),
            Column('container_utilization_pct', 'FLOAT', source_name='container_utilization_pct'),
            Column('container_utilization_cbm', 'FLOAT', source_name='container_utilization_cbm'),
            Column('the_deleted', 'BOOLEAN', source_name='the_deleted'),
            Column('the_created_by', 'NUMBER', source_name='the_created_by'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)', source_name='the_created_at'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)', source_name='modified_at'),
            Column('modified_by', 'NUMBER', source_name='modified_by'),
        ],
        version='v3',
    ),
    Config(
        table='tfg_cbm_kg_class',
        column_list=[
            Column('division', 'VARCHAR', source_name='division'),
            Column('department', 'VARCHAR', source_name='department'),
            Column('subdept', 'VARCHAR', source_name='subdept'),
            Column('gender', 'VARCHAR', source_name='gender'),
            Column('sccategory', 'VARCHAR', source_name='sccategory'),
            Column('class', 'VARCHAR', source_name='"Class"'),
            Column('cbm', 'FLOAT', source_name='cbm'),
            Column('kg', 'FLOAT', source_name='kg'),
        ],
        version='v2',
    ),
    Config(
        table='tfg_ifi_form',
        column_list=[
            Column('style_number', 'VARCHAR', source_name='style_number'),
            Column('style_name', 'VARCHAR', source_name='style_name'),
            Column('color', 'VARCHAR', source_name='color'),
            Column('color_sku_segment', 'VARCHAR', source_name='color_sku_segment'),
            Column('q3', 'VARCHAR', source_name='q3'),
            Column('q4', 'VARCHAR', source_name='q4'),
            Column('q5', 'VARCHAR', source_name='q5'),
            Column('q6', 'VARCHAR', source_name='q6'),
            Column('q7', 'VARCHAR', source_name='q7'),
            Column('q8', 'VARCHAR', source_name='q8'),
            Column('q9', 'VARCHAR', source_name='q9'),
            Column('q10', 'VARCHAR', source_name='q10'),
            Column('q11', 'VARCHAR', source_name='q11'),
            Column('q12', 'VARCHAR', source_name='q12'),
            Column('q13', 'VARCHAR', source_name='q13'),
            Column('q14', 'VARCHAR', source_name='q14'),
            Column('q15', 'VARCHAR', source_name='q15'),
            Column('q16', 'VARCHAR', source_name='q16'),
            Column('q17', 'VARCHAR', source_name='q17'),
            Column('q18', 'VARCHAR', source_name='q18'),
            Column('q19', 'VARCHAR', source_name='q19'),
            Column('q20', 'VARCHAR', source_name='q20'),
            Column('q21', 'VARCHAR', source_name='q21'),
            Column('q22', 'VARCHAR', source_name='q22'),
            Column('q23', 'VARCHAR', source_name='q23'),
            Column('q24', 'VARCHAR', source_name='q24'),
            Column('q25', 'VARCHAR', source_name='q25'),
        ],
        version='v2',
    ),
    Config(
        table='tfg_marketplace_costs',
        column_list=[
            Column('style_cnl', 'VARCHAR', source_name='style_cnl'),
            Column('sir_cnl', 'VARCHAR', source_name='sir_cnl'),
            Column('season_cnl', 'VARCHAR', source_name='season_cnl'),
            Column('colorway_cnl', 'VARCHAR', source_name='colorway_cnl'),
            Column('tfg_division', 'VARCHAR', source_name='tfg_division'),
            Column('style', 'VARCHAR', source_name='style'),
            Column('colorway', 'VARCHAR', source_name='colorway'),
            Column('supplier', 'VARCHAR', source_name='supplier'),
            Column('size_type', 'VARCHAR', source_name='size_type'),
            Column('fob_full_price', 'FLOAT', source_name='fob_full_price'),
            Column('fob_price', 'FLOAT', source_name='fob_price'),
            Column('landed_cost', 'FLOAT', source_name='landed_cost'),
            Column('revision_state', 'VARCHAR', source_name='revision_state'),
            Column('season', 'VARCHAR', source_name='season'),
        ],
        version='v2',
    ),
    Config(
        table='tfg_buy_plan',
        column_list=[
            Column('channel', 'VARCHAR', source_name='channel'),
            Column('region', 'VARCHAR', source_name='region'),
            Column('showroom', 'VARCHAR', source_name='showroom'),
            Column('department', 'VARCHAR', source_name='department'),
            Column('gender', 'VARCHAR', source_name='gender'),
            Column('product_category', 'VARCHAR', source_name='product_category'),
            Column('product_version', 'VARCHAR', source_name='product_version'),
            Column('style_number', 'VARCHAR', source_name='style_number'),
            Column('style_name', 'VARCHAR', source_name='style_name'),
            Column('class', 'VARCHAR', source_name='class'),
            Column('sub_class', 'VARCHAR', source_name='sub_class'),
            Column('colorway', 'VARCHAR', source_name='colorway'),
            Column('base_sku', 'VARCHAR', source_name='base_sku'),
            Column('ldp_blend', 'NUMBER', source_name='ldp_blend'),
            Column('ldp_reg', 'NUMBER', source_name='ldp_reg'),
            Column('ldp_ext', 'NUMBER', source_name='ldp_ext'),
            Column('units_total', 'NUMBER', source_name='units_total'),
            Column('units_reg', 'NUMBER', source_name='units_reg'),
            Column('units_ext', 'NUMBER', source_name='units_ext'),
            Column('vip', 'NUMBER', source_name='vip'),
            Column('msrp', 'NUMBER', source_name='msrp'),
            Column('bottoms_silhouette', 'VARCHAR', source_name='bottoms_silhouette'),
            Column('sub_department', 'VARCHAR', source_name='sub_department'),
            Column('end_use', 'VARCHAR', source_name='end_use'),
            Column('silhouette', 'VARCHAR', source_name='silhouette'),
        ],
        version='v4',
    ),
    Config(
        table='tfg_marketplace_costs_history',
        column_list=[
            Column('style_cnl', 'VARCHAR'),
            Column('sir_cnl', 'VARCHAR'),
            Column('season_cnl', 'VARCHAR'),
            Column('colorway_cnl', 'VARCHAR'),
            Column('tfg_division', 'VARCHAR'),
            Column('style', 'VARCHAR'),
            Column('colorway', 'VARCHAR'),
            Column('supplier', 'VARCHAR'),
            Column('size_type', 'VARCHAR'),
            Column('fob_full_price', 'FLOAT'),
            Column('fob_price', 'FLOAT'),
            Column('landed_cost', 'FLOAT'),
            Column('revision_state', 'VARCHAR'),
            Column('is_current', 'BOOLEAN'),
            Column('season', 'VARCHAR'),
            Column('the_created_at', 'TIMESTAMP_LTZ(3)'),
            Column('modified_at', 'TIMESTAMP_LTZ(3)'),
            Column('patch_time', 'TIMESTAMP_LTZ(3)'),
            Column('supplier_item_id', 'NUMBER'),
            Column('current_revision_id', 'NUMBER'),
            Column('supplier_item_revision_id', 'NUMBER'),
            Column('style_id', 'NUMBER'),
            Column('colorway_id', 'NUMBER'),
        ],
        version='v1',
    ),
]
