from include.utils.snowflake import Column

column_list = [
    Column('assessment_id', 'VARCHAR', source_name='Assessment #'),
    Column('audit_firm', 'VARCHAR', source_name='Audit Company name'),
    Column('vendor_name', 'VARCHAR', source_name='Vendor Name'),
    Column('facility_name', 'VARCHAR', source_name='Facility Name'),
    Column('facility_address', 'VARCHAR', source_name='Facility Address'),
    Column('city', 'VARCHAR', source_name='Facility City'),
    Column('state', 'VARCHAR', source_name='Facility State'),
    Column('country', 'VARCHAR', source_name='Facility Country'),
    Column('facility_status', 'VARCHAR', source_name='Facility Status'),
    Column('industry', 'VARCHAR', source_name='Facility Industry'),
    Column('business_unit', 'VARCHAR', source_name='Facility Business unit'),
    Column('report_type', 'VARCHAR', source_name='Assessment Type'),
    Column('assessment_stage', 'VARCHAR', source_name='Assessment Stage'),
    Column('assessment_status', 'VARCHAR', source_name='Assessment Status'),
    Column('assessment_sub_status', 'VARCHAR', source_name='Assessment Sub Status'),
    Column('overall_facility_score', 'FLOAT', source_name='Score/Result'),
    Column('audit_date', 'DATE', source_name='Assessment Date'),
    Column('section', 'VARCHAR', source_name='Section '),
    Column('subsection', 'VARCHAR', source_name='Subsection '),
    Column('finding_id', 'VARCHAR', source_name='Finding ID'),
    Column('rating', 'VARCHAR', source_name='Rating '),
    Column('finding_details', 'VARCHAR', source_name='Finding details '),
    Column('num_major_nc', 'NUMBER', source_name='# Major NC '),
    Column('num_critical_nc', 'NUMBER', source_name='# Critical NC'),
]
