#!/usr/bin/env python

"""
This hook scans all transform scripts for the edw and identifies all lake tables referenced.

It is meant to be called any time an edw script is changed.

It updates a text file with the list of tables.

This file will be read by the acquisition dag generator, so that the tables that the edw does not
depend on can be run on a slower schedule and de-prioritized.
"""

import re
from pathlib import Path

from include import DAGS_DIR, SQL_DIR

reserved_words = {'order', 'group'}


def update_file():
    char_class = r'[a-zA-Z0-9_"]'
    folder = SQL_DIR / 'edw_prod/procedures'
    tables = set()
    for file in Path(folder).rglob('*.sql'):
        content = file.read_text()
        matches = re.findall(
            pattern=rf'{char_class}+\.{char_class}+\.{char_class}+',
            string=content,
            flags=re.MULTILINE,
        )
        matches = {
            x.lower()
            .replace('"', '')
            .replace('lake_view.', 'lake.')
            .replace("lake_consolidated_view", "lake_consolidated")
            for x in matches
        }
        matches = {x for x in matches if 'lake' in x}
        tables.update(matches)

    acq_config_file = DAGS_DIR / 'edm/acquisition/configs/edw_source_tables.py'

    schema_exclusion_list = [
        "gdpr",
        "ultra_cart",
        "ultra_cms",
        "ultra_merchant",
        "ultra_rollup",
    ]

    with open(acq_config_file, 'wt') as f:
        f.write('"""AUTOGENERATED -- DO NOT MODIFY MANUALLY!!!"""\n')
        f.write('edw_source_list = {\n')
        for table in sorted(tables):
            db, schema, tbl = table.split('.')
            if db.lower() not in ["lake_consolidated", "lake_consolidated_view"]:
                if not any(i in schema.lower() for i in schema_exclusion_list):
                    if tbl in reserved_words:
                        tbl = f'"{tbl.upper()}"'
                    f.write(f"    '{db}.{schema}.{tbl}',\n")
        f.write('}\n')


def main(argv=None):
    update_file()
    retv = 0
    return retv


if __name__ == '__main__':
    exit(main())
