from include.utils.acquisition.table_config import TableConfig
from include.utils.snowflake import Column

table_config = TableConfig(
    database="ssrs_reports",
    schema="wms",
    table="jfportal_poskus",
    watermark_column="DW_Datetime_modified",
    schema_version_prefix="v2",
    column_list=[
        Column("sku", "VARCHAR(31)", uniqueness=True, source_name="SKU"),
        Column("division_id", "VARCHAR(15)", source_name="DivisionID"),
        Column("showroom", "VARCHAR(20)", source_name="Showroom"),
        Column("date_launch", "DATE", source_name="DateLaunch"),
        Column("po_number", "VARCHAR(17)", uniqueness=True, source_name="PONumber"),
        Column("color", "VARCHAR(30)", source_name="Color"),
        Column("gp_description", "VARCHAR(100)", source_name="GPDescription"),
        Column("qty", "INT", source_name="Qty"),
        Column("vendor_id", "VARCHAR(15)", source_name="VendorId"),
        Column("xfd", "DATE", source_name="XFD"),
        Column("fc_delivery", "DATE", source_name="FCDelivery"),
        Column("delivery", "DATE", source_name="Delivery"),
        Column("department", "VARCHAR(50)", source_name="Department"),
        Column("inco_term", "VARCHAR(50)", source_name="IncoTerm"),
        Column("freight", "NUMBER(19, 4)", source_name="Freight"),
        Column("duty", "NUMBER(19, 4)", source_name="Duty"),
        Column("date_create", "TIMESTAMP_NTZ(3)", source_name="DateCreate"),
        Column("date_update", "TIMESTAMP_NTZ(3)", source_name="DateUpdate"),
        Column("cost", "NUMBER(19, 4)", source_name="Cost"),
        Column("region_id", "VARCHAR(2)", uniqueness=True, source_name="RegionId"),
        Column("freight_method", "VARCHAR(50)", source_name="FreightMethod"),
        Column("shipping_port", "VARCHAR(53)", source_name="ShippingPort"),
        Column("gender", "VARCHAR(7)", source_name="Gender"),
        Column("wms_code", "VARCHAR(15)", source_name="WMScode"),
        Column("style_name", "VARCHAR(100)", source_name="StyleName"),
        Column("style_type", "VARCHAR(50)", source_name="StyleType"),
        Column("vendor_name", "VARCHAR(30)", source_name="VendorName"),
        Column("brand", "VARCHAR(50)", source_name="Brand"),
        Column("po_status_id", "INT", source_name="POStatusId"),
        Column("po_status_text", "VARCHAR(50)", source_name="POStatusText"),
        Column("sub_department", "VARCHAR(30)", source_name="SubDepartment"),
        Column("line_status", "VARCHAR(25)", source_name="LineStatus"),
        Column("country_origin", "VARCHAR(2)", source_name="CountryOrigin"),
        Column("cmt", "NUMBER(19, 4)", source_name="CMT"),
        Column(
            "dw_datetime_modified",
            "TIMESTAMP_NTZ(3)",
            source_name="DW_Datetime_modified",
            delta_column=True,
        ),
        Column("check_sum_data", "INT", source_name="CheckSumData"),
        Column("hts_code", "VARCHAR(30)", source_name="HTS_Code"),
        Column("duty_percentage", "NUMBER(4, 4)", source_name="DutyPercentage"),
        Column("plm_style", "VARCHAR(30)", source_name="PLMStyle"),
        Column("material", "VARCHAR(100)", source_name="Material"),
        Column("material_content", "VARCHAR(255)", source_name="MaterialContent"),
        Column("fabric_category", "VARCHAR(30)", source_name="FabricCategory"),
        Column("hts_update", "VARCHAR(25)", source_name="HTSUpdate"),
        Column("buyer", "VARCHAR(30)", source_name="Buyer"),
        Column("style_part", "VARCHAR(100)", source_name="StylePart"),
        Column("component", "VARCHAR(46)", source_name="Component"),
        Column("bom_description", "VARCHAR(100)", source_name="BOMDescription"),
        Column("warehouse_id", "INT"),
        Column("dimension", "VARCHAR(100)", source_name="Dimension"),
        Column("subclass", "VARCHAR(255)"),
        Column("warehouse_id_origin", "INT"),
        Column(
            "hts_code_type", "VARCHAR(25)", uniqueness=True, source_name="HTS_Code_type"
        ),
        Column("style_rank", "VARCHAR(10)", source_name="Style_Rank"),
        Column("tariff", "NUMBER(4, 4)"),
        Column("avg_volume", "DOUBLE"),
        Column("source_vendor_name", "STRING"),
        Column("source_vendor_id", "STRING"),
    ],
)
