CREATE OR REPLACE TRANSIENT TABLE reporting_base_prod.data_science.product_recommendation_tags_pivoted AS
(WITH inventory_and_permalink AS (SELECT master_product_id                                              AS mpid,
                                         permalink,
                                         product_type_id,
                                         sum(available_quantity)                                        AS sum_available_quantity,
                                         sum(CASE WHEN core_sized_product
                                                      THEN CASE WHEN core_size THEN available_quantity ELSE 0 END
                                                  ELSE available_quantity END)                          AS sum_core_size_available_quantity,
                                         listagg(label_instance || ':' || available_quantity, ', ')
                                                 WITHIN GROUP (ORDER BY label_instance DESC, base_size) AS size_quantity_list
                                  FROM (SELECT master_product_id,
                                               label_instance,
                                               size,
                                               available_quantity,
                                               permalink,
                                               product_type_id,
                                               rollup_datetime_modified,
                                               trim(split_part(size, ' / ', 1))                                    AS base_size,
                                               base_size IN ('S', 'S/M', 'M', 'M/L', 'L')                          AS core_size,
                                               CASE WHEN max(CASE WHEN base_size IN ('S', 'S/M', 'M', 'M/L', 'L') THEN 1
                                                                  ELSE 0 END) OVER (PARTITION BY master_product_id) = 1
                                                        THEN TRUE
                                                    ELSE FALSE END                                                 AS core_sized_product,
                                               max(rollup_datetime_modified) OVER (PARTITION BY master_product_id) AS max_datetime_modified
                                        FROM lake_consolidated_view.ultra_rollup.products_in_stock)
                                  WHERE rollup_datetime_modified = max_datetime_modified
                                  GROUP BY mpid, permalink, product_type_id)
    , spi                     AS (SELECT mpid, sum(total_impressions) AS impressions
                                  FROM reporting_prod.data_science.export_postreg_segment_spi_ranking
                                  WHERE grid_name = 'pdp_view_add'
                                    AND impressions_date >= dateadd(DAY, -30, current_date())
                                  GROUP BY mpid)
    , fpls                    AS (SELECT DISTINCT edw_prod.stg.udf_unconcat_brand(product_id)      AS mpid,
                                                  array_agg(DISTINCT featured_product_location_id) AS fpl_ids,
                                  FROM lake_consolidated_view.ultra_merchant.featured_product
                                  WHERE hvr_is_deleted = 0
                                    AND active = 1
                                    AND current_date() BETWEEN ifnull(datetime_start, current_date()) AND ifnull(datetime_end, '2079-06-06')
                                  GROUP BY mpid)
    , _double_listed          AS (SELECT DISTINCT edw_prod.stg.udf_unconcat_brand(p.product_id) AS mpid,
                                                  max(iff(s.store_group = 'Fabletics' AND p.department = 'Mens' AND
                                                          pc.label = 'Womens', TRUE, FALSE))    AS double_listed
                                  FROM edw_prod.data_model.dim_product p
                                       JOIN      edw_prod.data_model.dim_store s ON p.store_id = s.store_id
                                       LEFT JOIN lake_consolidated_view.ultra_merchant.product_product_category ppc
                                                 ON p.product_id = ppc.product_id
                                       LEFT JOIN lake_consolidated_view.ultra_merchant.product_category pc
                                                 ON pc.product_category_id = ppc.product_category_id
                                  GROUP BY mpid)

    , pivoted_tags            AS (SELECT *
                                  FROM (SELECT t.mpid                             AS mpid_from_tags,
                                               to_date(t.date_expected)           AS site_date_expected,
                                               concat(tag_type, '_', lower(name)) AS tag_col,
                                               listagg(lower(value), ', ')        AS val -- turns tags with multi-select into a list
                                        FROM reporting_base_prod.data_science.product_recommendation_tags t
                                        GROUP BY mpid_from_tags, site_date_expected, tag_col) PIVOT (max(val) FOR tag_col IN ('dimproduct_category','dimproduct_class','dimproduct_department','dimproduct_full_color','dimproduct_primary_color', 'dimproduct_product_category','dimproduct_product_name','dimproduct_secondary_color','dimproduct_subcategory', 'dimproduct_tertiary_color','merch_additional_launch_other', 'merch_antibacterial_flag', 'merch_arch_support_flag', 'merch_breathing_holes_flag', 'merch_bright', 'merch_buy_timing', 'merch_category', 'merch_category_type', 'merch_channel', 'merch_class', 'merch_classification', 'merch_collection', 'merch_color', 'merch_color_application', 'merch_color_family', 'merch_color_roll_up', 'merch_color_tone', 'merch_color_value', 'merch_comfort_flag', 'merch_core_fashion', 'merch_coresb_reorder_fashion', 'merch_coverage', 'merch_current_name', 'merch_current_price', 'merch_current_showroom', 'merch_current_vip_retail', 'merch_cushioned_footbed_flag', 'merch_cushioned_heel_flag', 'merch_department', 'merch_department_detail', 'merch_design_style_number', 'merch_eco_style', 'merch_eco_system', 'merch_editorial_features', 'merch_end_use', 'merch_fabric', 'merch_fabric_grouping', 'merch_factory', 'merch_fit_block', 'merch_fit_style', 'merch_fk_attribute', 'merch_fk_new_season_code', 'merch_fk_site_name', 'merch_gender', 'merch_go_live_date', 'merch_heat', 'merch_heel_height', 'merch_heel_type', 'merch_img_model_plus', 'merch_img_model_reg', 'merch_inseams_construction', 'merch_is_plussize', 'merch_item_rank', 'merch_item_status', 'merch_lined_unlined', 'merch_list_of_all_showrooms', 'merch_marketing_capsule_name', 'merch_marketing_story', 'merch_master_color', 'merch_memory_foam_flag', 'merch_opacity', 'merch_original_showroom_month', 'merch_pattern', 'merch_persona', 'merch_product_color_from_label', 'merch_product_segment', 'merch_short_inseam', 'merch_site_color', 'merch_size_13_15', 'merch_size_range', 'merch_size_scale', 'merch_size_scale_production', 'merch_sku_status', 'merch_style_color', 'merch_style_name', 'merch_style_parent', 'merch_style_rank', 'merch_style_status', 'merch_style_type', 'merch_sub_brand', 'merch_sub_department', 'merch_subcategory', 'merch_subclass', 'merch_sweat_wicking_flag', 'merch_tall_inseam', 'merch_ww_wc', 'site__vip_exclusive_style','site_a-score','site_accents','site_accessories', 'site_accessories_sub_class','site_accessory','site_accessory_type','site_activity','site_all', 'site_b-score','site_badge_callout','site_bag_detail','site_bag_size','site_bag_style', 'site_body_type_edit','site_boot_cut','site_boot_shaft_height','site_boots','site_bottom_style', 'site_bottom_type','site_bottoms','site_bottoms_length','site_bottoms_rise','site_bottoms_sub_class', 'site_boys_fashion','site_boys_outfits','site_bra_support','site_bra_type','site_brand','site_bras', 'site_buyer','site_c-score','site_call_outs','site_category','site_cigarette','site_clothing_detail', 'site_collection','site_color','site_color_family','site_color_for_dresses/rompers', 'site_color_for_swim_bottoms','site_color_for_swim_cover-ups','site_color_for_swim_one-pieces', 'site_color_for_swim_tops','site_color_preference','site_colors_for_shoes','site_compression', 'site_cover-up_coverage','site_cover-up_type','site_denim_style','site_designer_collaboration', 'site_detail','site_dg_bottoms','site_dg_bras','site_dg_bras_impact_level','site_dg_leggings', 'site_dg_men','site_dg_pants','site_dg_polo_shirts','site_dg_scrubs','site_dg_scrubs_women', 'site_dg_short_sleeve_tees','site_dg_shorts','site_dg_shorts_lined','site_dg_shorts_unlined', 'site_dg_sweatshirts','site_dg_tank_tops','site_dg_tops','site_dg_underwear','site_dg_women', 'site_dg_womens_bottoms','site_dg_womens_tops','site_discovery_guide','site_dress_style', 'site_dress_type_for_dresses/rompers','site_eco-system','site_ecosystem','site_embellishment_type', 'site_fabric','site_fabric_edit','site_fabric_features','site_fashion','site_fashion_attribute', 'site_feature','site_featured','site_fit','site_fit_edit','site_flats','site_gender','site_girls_fashion', 'site_girls_outfits','site_grid_callouts','site_heel_height','site_heel_preference','site_heel_shape', 'site_heel_size_(deprecated)','site_heel_type','site_height','site_hoodies_and_sweatshirts', 'site_img_model_-_plus','site_img_model_-_reg','site_img_type','site_inseam_category', 'site_inventory_classification','site_jacket_&_vest_style','site_jacket_type','site_jackets', 'site_jewelry_type','site_launch_year','site_leggings_sub_class','site_length', 'site_length_for_dresses/rompers','site_lined_type','site_lingerie','site_material_type', 'site_mens_accessories_type','site_mens_bottom_type','site_mens_fashion','site_mens_top_type', 'site_mens_underwear_type','site_month','site_occasion','site_occasion_type','site_outerwear_sub_class', 'site_outfit','site_outfit_type','site_outfits_/_wardrobes','site_pants_style','site_pattern', 'site_pdp_color_swatch_category','site_personality_type','site_platform_style','site_presentation', 'site_print','site_product_class','site_product_detail','site_product_personality_type', 'site_product_subclass','site_promo_restrictions','site_retail','site_rise','site_seamless_size_scale', 'site_search','site_season','site_season_edit','site_shirt','site_shoe_detail','site_shoe_style', 'site_shoe_type','site_shoes','site_shop_category','site_shorts','site_shorts_style', 'site_signature_style_type','site_silhouette','site_size_type','site_skirt_style','site_sleepwear', 'site_sleeve_length','site_sleeves','site_sleeves_for_dresses/rompers','site_strap_type','site_style', 'site_style_features','site_style_profile','site_support_for_dresses/rompers','site_swatch_category', 'site_sweater_style','site_swim_bottom_coverage','site_swim_bottom_level','site_swim_bottom_type', 'site_swim_coverage','site_swim_cups','site_swim_liner','site_swim_support_level','site_swim_top_coverage', 'site_swim_top_type','site_swimwear_sub_class','site_target_area','site_toe_type','site_top_support', 'site_top_type','site_tops','site_tops_fit','site_tops_length','site_tops_style','site_tops_sub_class', 'site_trend','site_trend/detail','site_trend_edit','site_underwear','site_vip_exclusive','site_weather', 'site_womens_fashion','site_year')))

    , cleansed_pivoted_tags   AS (SELECT mpid_from_tags,
                                         site_date_expected,
                                         "'dimproduct_category'"                 AS dimproduct_category,
                                         "'dimproduct_class'"                    AS dimproduct_class,
                                         "'dimproduct_department'"               AS dimproduct_department,
                                         "'dimproduct_full_color'"               AS dimproduct_full_color,
                                         "'dimproduct_primary_color'"            AS dimproduct_primary_color,
                                         "'dimproduct_product_category'"         AS dimproduct_product_category,
                                         "'dimproduct_product_name'"             AS dimproduct_product_name,
                                         "'dimproduct_secondary_color'"          AS dimproduct_secondary_color,
                                         "'dimproduct_subcategory'"              AS dimproduct_subcategory,
                                         "'dimproduct_tertiary_color'"           AS dimproduct_tertiary_color,

                                         "'merch_antibacterial_flag'"            AS merch_antibacterial_flag,
                                         "'merch_arch_support_flag'"             AS merch_arch_support_flag,
                                         "'merch_breathing_holes_flag'"          AS merch_breathing_holes_flag,
                                         "'merch_bright'"                        AS merch_bright,
                                         "'merch_buy_timing'"                    AS merch_buy_timing,
                                         CASE WHEN "'merch_category'" = 'tops' THEN 'top'
                                              WHEN "'merch_category'" = 'bottoms' THEN 'bottom'
                                              WHEN "'merch_category'" = 'jackets' THEN 'jacket'
                                              ELSE "'merch_category'" END        AS merch_category,
                                         "'merch_category_type'"                 AS merch_category_type,
                                         "'merch_channel'"                       AS merch_channel,
                                         "'merch_class'"                         AS merch_class,
                                         "'merch_classification'"                AS merch_classification,
                                         "'merch_collection'"                    AS merch_collection,
                                         "'merch_color'"                         AS merch_color,
                                         "'merch_color_application'"             AS merch_color_application,
                                         "'merch_color_family'"                  AS merch_color_family,
                                         "'merch_color_roll_up'"                 AS merch_color_roll_up,
                                         "'merch_color_tone'"                    AS merch_color_tone,
                                         "'merch_color_value'"                   AS merch_color_value,
                                         "'merch_comfort_flag'"                  AS merch_comfort_flag,
                                         "'merch_core_fashion'"                  AS merch_core_fashion,
                                         "'merch_coresb_reorder_fashion'"        AS merch_coresb_reorder_fashion,
                                         "'merch_coverage'"                      AS merch_coverage,
                                         "'merch_current_name'"                  AS merch_current_name,
                                         "'merch_current_price'"                 AS merch_current_price,
                                         "'merch_current_showroom'"              AS merch_current_showroom,
                                         "'merch_current_vip_retail'"            AS merch_current_vip_retail,
                                         "'merch_cushioned_footbed_flag'"        AS merch_cushioned_footbed_flag,
                                         "'merch_cushioned_heel_flag'"           AS merch_cushioned_heel_flag,
                                         "'merch_department'"                    AS merch_department,
                                         "'merch_department_detail'"             AS merch_department_detail,
                                         "'merch_design_style_number'"           AS merch_design_style_number,
                                         "'merch_eco_style'"                     AS merch_eco_style,
                                         "'merch_eco_system'"                    AS merch_eco_system,
                                         "'merch_editorial_features'"            AS merch_editorial_features,
                                         "'merch_end_use'"                       AS merch_end_use,
                                         "'merch_fabric'"                        AS merch_fabric,
                                         "'merch_fabric_grouping'"               AS merch_fabric_grouping,
                                         "'merch_factory'"                       AS merch_factory,
                                         "'merch_fit_block'"                     AS merch_fit_block,
                                         "'merch_fit_style'"                     AS merch_fit_style,
                                         "'merch_fk_attribute'"                  AS merch_fk_attribute,
                                         "'merch_fk_new_season_code'"            AS merch_fk_new_season_code,
                                         "'merch_fk_site_name'"                  AS merch_fk_site_name,
                                         "'merch_gender'"                        AS merch_gender,
                                         "'merch_go_live_date'"                  AS merch_go_live_date,
                                         "'merch_heat'"                          AS merch_heat,
                                         "'merch_heel_height'"                   AS merch_heel_height,
                                         "'merch_heel_type'"                     AS merch_heel_type,
                                         "'merch_img_model_plus'"                AS merch_img_model_plus,
                                         "'merch_img_model_reg'"                 AS merch_img_model_reg,
                                         "'merch_inseams_construction'"          AS merch_inseams_construction,
                                         "'merch_is_plussize'"                   AS merch_is_plussize,
                                         "'merch_item_rank'"                     AS merch_item_rank,
                                         "'merch_item_status'"                   AS merch_item_status,
                                         "'merch_lined_unlined'"                 AS merch_lined_unlined,
                                         "'merch_list_of_all_showrooms'"         AS merch_list_of_all_showrooms,
                                         "'merch_marketing_capsule_name'"        AS merch_marketing_capsule_name,
                                         "'merch_marketing_story'"               AS merch_marketing_story,
                                         "'merch_master_color'"                  AS merch_master_color,
                                         "'merch_memory_foam_flag'"              AS merch_memory_foam_flag,
                                         "'merch_opacity'"                       AS merch_opacity,
                                         "'merch_original_showroom_month'"       AS merch_original_showroom_month,
                                         "'merch_pattern'"                       AS merch_pattern,
                                         "'merch_persona'"                       AS merch_persona,
                                         "'merch_product_color_from_label'"      AS merch_product_color_from_label,
                                         "'merch_product_segment'"               AS merch_product_segment,
                                         "'merch_short_inseam'"                  AS merch_short_inseam,
                                         "'merch_site_color'"                    AS merch_site_color,
                                         "'merch_size_13_15'"                    AS merch_size_13_15,
                                         "'merch_size_range'"                    AS merch_size_range,
                                         "'merch_size_scale'"                    AS merch_size_scale,
                                         "'merch_size_scale_production'"         AS merch_size_scale_production,
                                         "'merch_sku_status'"                    AS merch_sku_status,
                                         "'merch_style_color'"                   AS merch_style_color,
                                         "'merch_style_name'"                    AS merch_style_name,
                                         "'merch_style_parent'"                  AS merch_style_parent,
                                         "'merch_style_rank'"                    AS merch_style_rank,
                                         "'merch_style_status'"                  AS merch_style_status,
                                         "'merch_style_type'"                    AS merch_style_type,
                                         "'merch_sub_brand'"                     AS merch_sub_brand,
                                         "'merch_sub_department'"                AS merch_sub_department,
                                         "'merch_subcategory'"                   AS merch_subcategory,
                                         "'merch_subclass'"                      AS merch_subclass,
                                         "'merch_sweat_wicking_flag'"            AS merch_sweat_wicking_flag,
                                         "'merch_tall_inseam'"                   AS merch_tall_inseam,
                                         "'merch_ww_wc'"                         AS merch_ww_wc,

                                         "'site__vip_exclusive_style'"           AS site__vip_exclusive_style,
                                         "'site_a-score'"                        AS site_a_score,
                                         "'site_accents'"                        AS site_accents,
                                         "'site_accessories'"                    AS site_accessories,
                                         "'site_accessories_sub_class'"          AS site_accessories_sub_class,
                                         "'site_accessory'"                      AS site_accessory,
                                         "'site_accessory_type'"                 AS site_accessory_type,
                                         "'site_activity'"                       AS site_activity,
                                         "'site_all'"                            AS site_all,
                                         "'site_b-score'"                        AS site_b_score,
                                         "'site_badge_callout'"                  AS site_badge_callout,
                                         "'site_bag_detail'"                     AS site_bag_detail,
                                         "'site_bag_size'"                       AS site_bag_size,
                                         "'site_bag_style'"                      AS site_bag_style,
                                         "'site_body_type_edit'"                 AS site_body_type_edit,
                                         "'site_boot_cut'"                       AS site_boot_cut,
                                         "'site_boot_shaft_height'"              AS site_boot_shaft_height,
                                         "'site_boots'"                          AS site_boots,
                                         "'site_bottom_style'"                   AS site_bottom_style,
                                         "'site_bottom_type'"                    AS site_bottom_type,
                                         "'site_bottoms'"                        AS site_bottoms,
                                         "'site_bottoms_length'"                 AS site_bottoms_length,
                                         "'site_bottoms_rise'"                   AS site_bottoms_rise,
                                         "'site_bottoms_sub_class'"              AS site_bottoms_sub_class,
                                         "'site_boys_fashion'"                   AS site_boys_fashion,
                                         "'site_boys_outfits'"                   AS site_boys_outfits,
                                         "'site_bra_support'"                    AS site_bra_support,
                                         "'site_bra_type'"                       AS site_bra_type,
                                         "'site_brand'"                          AS site_brand,
                                         "'site_bras'"                           AS site_bras,
                                         "'site_buyer'"                          AS site_buyer,
                                         "'site_c-score'"                        AS site_c_score,
                                         "'site_call_outs'"                      AS site_call_outs,
                                         "'site_category'"                       AS site_category,
                                         "'site_cigarette'"                      AS site_cigarette,
                                         "'site_clothing_detail'"                AS site_clothing_detail,
                                         "'site_collection'"                     AS site_collection,
                                         "'site_color'"                          AS site_color,
                                         "'site_color_family'"                   AS site_color_family,
                                         "'site_color_for_dresses/rompers'"      AS site_color_for_dresses_rompers,
                                         "'site_color_for_swim_bottoms'"         AS site_color_for_swim_bottoms,
                                         "'site_color_for_swim_cover-ups'"       AS site_color_for_swim_cover_ups,
                                         "'site_color_for_swim_one-pieces'"      AS site_color_for_swim_one_pieces,
                                         "'site_color_for_swim_tops'"            AS site_color_for_swim_tops,
                                         "'site_color_preference'"               AS site_color_preference,
                                         "'site_colors_for_shoes'"               AS site_colors_for_shoes,
                                         "'site_compression'"                    AS site_compression,
                                         "'site_cover-up_coverage'"              AS site_cover_up_coverage,
                                         "'site_cover-up_type'"                  AS site_cover_up_type,
                                         "'site_denim_style'"                    AS site_denim_style,
                                         "'site_designer_collaboration'"         AS site_designer_collaboration,
                                         "'site_detail'"                         AS site_detail,
                                         "'site_dg_bottoms'"                     AS site_dg_bottoms,
                                         "'site_dg_bras'"                        AS site_dg_bras,
                                         "'site_dg_bras_impact_level'"           AS site_dg_bras_impact_level,
                                         "'site_dg_leggings'"                    AS site_dg_leggings,
                                         "'site_dg_men'"                         AS site_dg_men,
                                         "'site_dg_pants'"                       AS site_dg_pants,
                                         "'site_dg_polo_shirts'"                 AS site_dg_polo_shirts,
                                         "'site_dg_scrubs'"                      AS site_dg_scrubs,
                                         "'site_dg_scrubs_women'"                AS site_dg_scrubs_women,
                                         "'site_dg_short_sleeve_tees'"           AS site_dg_short_sleeve_tees,
                                         "'site_dg_shorts'"                      AS site_dg_shorts,
                                         "'site_dg_shorts_lined'"                AS site_dg_shorts_lined,
                                         "'site_dg_shorts_unlined'"              AS site_dg_shorts_unlined,
                                         "'site_dg_sweatshirts'"                 AS site_dg_sweatshirts,
                                         "'site_dg_tank_tops'"                   AS site_dg_tank_tops,
                                         "'site_dg_tops'"                        AS site_dg_tops,
                                         "'site_dg_underwear'"                   AS site_dg_underwear,
                                         "'site_dg_women'"                       AS site_dg_women,
                                         "'site_dg_womens_bottoms'"              AS site_dg_womens_bottoms,
                                         "'site_dg_womens_tops'"                 AS site_dg_womens_tops,
                                         "'site_discovery_guide'"                AS site_discovery_guide,
                                         "'site_dress_style'"                    AS site_dress_style,
                                         "'site_dress_type_for_dresses/rompers'" AS site_dress_type_for_dresses_rompers,
                                         "'site_eco-system'"                     AS site_eco_system,
                                         "'site_ecosystem'"                      AS site_ecosystem,
                                         "'site_embellishment_type'"             AS site_embellishment_type,
                                         "'site_fabric'"                         AS site_fabric,
                                         "'site_fabric_edit'"                    AS site_fabric_edit,
                                         "'site_fabric_features'"                AS site_fabric_features,
                                         "'site_fashion'"                        AS site_fashion,
                                         "'site_fashion_attribute'"              AS site_fashion_attribute,
                                         "'site_feature'"                        AS site_feature,
                                         "'site_featured'"                       AS site_featured,
                                         "'site_fit'"                            AS site_fit,
                                         "'site_fit_edit'"                       AS site_fit_edit,
                                         "'site_flats'"                          AS site_flats,
                                         "'site_gender'"                         AS site_gender,
                                         "'site_girls_fashion'"                  AS site_girls_fashion,
                                         "'site_girls_outfits'"                  AS site_girls_outfits,
                                         "'site_grid_callouts'"                  AS site_grid_callouts,
                                         "'site_heel_height'"                    AS site_heel_height,
                                         "'site_heel_preference'"                AS site_heel_preference,
                                         "'site_heel_shape'"                     AS site_heel_shape,
                                         "'site_heel_size_(deprecated)'"         AS site_heel_size_deprecated,
                                         "'site_heel_type'"                      AS site_heel_type,
                                         "'site_height'"                         AS site_height,
                                         "'site_hoodies_and_sweatshirts'"        AS site_hoodies_and_sweatshirts,
                                         "'site_img_model_-_plus'"               AS site_img_model_plus,
                                         "'site_img_model_-_reg'"                AS site_img_model_reg,
                                         "'site_img_type'"                       AS site_img_type,
                                         "'site_inseam_category'"                AS site_inseam_category,
                                         "'site_inventory_classification'"       AS site_inventory_classification,
                                         "'site_jacket_&_vest_style'"            AS site_jacket_vest_style,
                                         "'site_jacket_type'"                    AS site_jacket_type,
                                         "'site_jackets'"                        AS site_jackets,
                                         "'site_jewelry_type'"                   AS site_jewelry_type,
                                         "'site_launch_year'"                    AS site_launch_year,
                                         "'site_leggings_sub_class'"             AS site_leggings_sub_class,
                                         "'site_length'"                         AS site_length,
                                         "'site_length_for_dresses/rompers'"     AS site_length_for_dresses_rompers,
                                         "'site_lined_type'"                     AS site_lined_type,
                                         "'site_lingerie'"                       AS site_lingerie,
                                         "'site_material_type'"                  AS site_material_type,
                                         "'site_mens_accessories_type'"          AS site_mens_accessories_type,
                                         "'site_mens_bottom_type'"               AS site_mens_bottom_type,
                                         "'site_mens_fashion'"                   AS site_mens_fashion,
                                         "'site_mens_top_type'"                  AS site_mens_top_type,
                                         "'site_mens_underwear_type'"            AS site_mens_underwear_type,
                                         "'site_month'"                          AS site_month,
                                         "'site_occasion'"                       AS site_occasion,
                                         "'site_occasion_type'"                  AS site_occasion_type,
                                         "'site_outerwear_sub_class'"            AS site_outerwear_sub_class,
                                         "'site_outfit'"                         AS site_outfit,
                                         "'site_outfit_type'"                    AS site_outfit_type,
                                         "'site_outfits_/_wardrobes'"            AS site_outfits___wardrobes,
                                         "'site_pants_style'"                    AS site_pants_style,
                                         "'site_pattern'"                        AS site_pattern,
                                         "'site_pdp_color_swatch_category'"      AS site_pdp_color_swatch_category,
                                         "'site_personality_type'"               AS site_personality_type,
                                         "'site_platform_style'"                 AS site_platform_style,
                                         "'site_presentation'"                   AS site_presentation,
                                         "'site_print'"                          AS site_print,
                                         "'site_product_class'"                  AS site_product_class,
                                         "'site_product_detail'"                 AS site_product_detail,
                                         "'site_product_personality_type'"       AS site_product_personality_type,
                                         "'site_product_subclass'"               AS site_product_subclass,
                                         "'site_promo_restrictions'"             AS site_promo_restrictions,
                                         "'site_retail'"                         AS site_retail,
                                         "'site_rise'"                           AS site_rise,
                                         "'site_seamless_size_scale'"            AS site_seamless_size_scale,
                                         "'site_search'"                         AS site_search,
                                         "'site_season'"                         AS site_season,
                                         "'site_season_edit'"                    AS site_season_edit,
                                         "'site_shirt'"                          AS site_shirt,
                                         "'site_shoe_detail'"                    AS site_shoe_detail,
                                         "'site_shoe_style'"                     AS site_shoe_style,
                                         "'site_shoe_type'"                      AS site_shoe_type,
                                         "'site_shoes'"                          AS site_shoes,
                                         "'site_shop_category'"                  AS site_shop_category,
                                         "'site_shorts'"                         AS site_shorts,
                                         "'site_shorts_style'"                   AS site_shorts_style,
                                         "'site_signature_style_type'"           AS site_signature_style_type,
                                         "'site_silhouette'"                     AS site_silhouette,
                                         "'site_size_type'"                      AS site_size_type,
                                         "'site_skirt_style'"                    AS site_skirt_style,
                                         "'site_sleepwear'"                      AS site_sleepwear,
                                         "'site_sleeve_length'"                  AS site_sleeve_length,
                                         "'site_sleeves'"                        AS site_sleeves,
                                         "'site_sleeves_for_dresses/rompers'"    AS site_sleeves_for_dresses_rompers,
                                         "'site_strap_type'"                     AS site_strap_type,
                                         "'site_style'"                          AS site_style,
                                         "'site_style_features'"                 AS site_style_features,
                                         "'site_style_profile'"                  AS site_style_profile,
                                         "'site_support_for_dresses/rompers'"    AS site_support_for_dresses_rompers,
                                         "'site_swatch_category'"                AS site_swatch_category,
                                         "'site_sweater_style'"                  AS site_sweater_style,
                                         "'site_swim_bottom_coverage'"           AS site_swim_bottom_coverage,
                                         "'site_swim_bottom_level'"              AS site_swim_bottom_level,
                                         "'site_swim_bottom_type'"               AS site_swim_bottom_type,
                                         "'site_swim_coverage'"                  AS site_swim_coverage,
                                         "'site_swim_cups'"                      AS site_swim_cups,
                                         "'site_swim_liner'"                     AS site_swim_liner,
                                         "'site_swim_support_level'"             AS site_swim_support_level,
                                         "'site_swim_top_coverage'"              AS site_swim_top_coverage,
                                         "'site_swim_top_type'"                  AS site_swim_top_type,
                                         "'site_swimwear_sub_class'"             AS site_swimwear_sub_class,
                                         "'site_target_area'"                    AS site_target_area,
                                         "'site_toe_type'"                       AS site_toe_type,
                                         "'site_top_support'"                    AS site_top_support,
                                         "'site_top_type'"                       AS site_top_type,
                                         "'site_tops'"                           AS site_tops,
                                         "'site_tops_fit'"                       AS site_tops_fit,
                                         "'site_tops_length'"                    AS site_tops_length,
                                         "'site_tops_style'"                     AS site_tops_style,
                                         "'site_tops_sub_class'"                 AS site_tops_sub_class,
                                         "'site_trend'"                          AS site_trend,
                                         "'site_trend/detail'"                   AS site_trend_detail,
                                         "'site_trend_edit'"                     AS site_trend_edit,
                                         "'site_underwear'"                      AS site_underwear,
                                         "'site_vip_exclusive'"                  AS site_vip_exclusive,
                                         "'site_weather'"                        AS site_weather,
                                         "'site_womens_fashion'"                 AS site_womens_fashion,
                                         "'site_year'"                           AS site_year
                                  FROM pivoted_tags)
    --get distinct tags for each brand since some ubts have different columns -- we dont need them all

    , mpids                   AS (SELECT s.store_group,
                                         s.store_brand_abbr,
                                         p.department,
                                         edw_prod.stg.udf_unconcat_brand(p.product_id) AS mpid,
                                         p.is_active,
                                         p.product_status,
                                         p.category,
                                         p.product_name,
                                         p.product_type,
                                         p.group_code,
                                         p.image_url,
                                         p.current_showroom_date                       AS date_expected,
                                         i.product_type_id,
                                         i.permalink,
                                         i.size_quantity_list,
                                         i.sum_available_quantity,
                                         i.sum_core_size_available_quantity,
                                         spi.impressions,
                                         d.double_listed,
                                         fpls.fpl_ids,
                                         ifnull(to_boolean(pt.tag_id), FALSE)          AS last_chance,
                                         CASE WHEN p.product_type != 'Bundle' AND
                                                   p.current_showroom_date <= current_date() AND
                                                   i.sum_available_quantity <= 0 THEN TRUE
                                              ELSE FALSE END                           AS sold_out_on_site -- gives all bundles not sold out. Outfits always have zero inventory
                                  FROM edw_prod.data_model.dim_product p
                                       JOIN      edw_prod.data_model.dim_store s ON p.store_id = s.store_id
                                       LEFT JOIN inventory_and_permalink i ON i.mpid = p.product_id
                                       LEFT JOIN spi ON spi.mpid = edw_prod.stg.udf_unconcat_brand(p.product_id)
                                       LEFT JOIN fpls ON fpls.mpid = edw_prod.stg.udf_unconcat_brand(p.product_id)
                                       LEFT JOIN _double_listed d
                                                 ON d.mpid = edw_prod.stg.udf_unconcat_brand(p.product_id)
                                       LEFT JOIN lake_consolidated_view.ultra_merchant.product_tag pt
                                                 ON p.product_id = pt.product_id AND pt.tag_id = 600220 -- last_chance tag
                                  WHERE p.master_product_id = -1
                                    AND p.product_type != 'Bundle')

 SELECT DISTINCT m.store_group,
                 m.store_brand_abbr,
                 m.department,
                 m.category,
                 m.mpid,
                 m.group_code,
                 m.image_url,
                 m.is_active,
                 m.product_status,
                 m.product_name,
                 m.product_type,
                 m.date_expected,
                 m.product_type_id,
                 m.permalink,
                 m.size_quantity_list,
                 m.sum_available_quantity,
                 m.sum_core_size_available_quantity,
                 m.impressions,
                 m.last_chance,
                 m.double_listed,
                 m.fpl_ids,
                 p.*,
                 trim(regexp_replace(dimproduct_product_name,
                                     '( lined 5in| unlined 5in| lined 7in| unlined 7in| 5in| 7in| \\(classic fit\\)| \\(slim fit\\))',
                                     ''))                                                  AS cleaned_dimproduct_product_name,
                 concat(cleaned_dimproduct_product_name, '_', dimproduct_full_color)       AS cleaned_dimproduct_product_name_with_color,
                 CASE WHEN replace(dimproduct_full_color, ' recycled active knit', '') IN
                           ('black', 'white', 'classic white', 'white/black', 'black caviar', 'angel white', 'onyx')
                          THEN TRUE
                      ELSE FALSE END                                                       AS black_or_white,
                 CASE WHEN contains(dimproduct_product_name, 'swim') OR contains(merch_category, 'swim') THEN TRUE
                      ELSE FALSE END                                                       AS is_swimwear,
                 CASE WHEN merch_end_use IN ('lounge') OR contains((site_activity), 'lounge') THEN TRUE
                      ELSE FALSE END                                                       AS is_lounge,
                 CASE WHEN merch_end_use IN ('sleep') OR contains(site_activity, 'sleep') OR
                           contains(dimproduct_product_name, 'sleep') THEN TRUE
                      ELSE FALSE END                                                       AS is_sleep,

                 CASE WHEN contains(merch_category, 'underwear') AND contains(merch_color_family, 'brown') AND
                           contains(dimproduct_product_name, 'thong') AND NOT contains(dimproduct_product_name, 'lace')
                          THEN TRUE
                      ELSE FALSE END                                                       AS is_nude_thong,

                 contains(site_activity, 'running')                                        AS site_activity_running,
                 contains(site_activity, 'performance')                                    AS site_activity_performance,
                 contains(site_activity, 'everyday')                                       AS site_activity_everyday,
                 contains(site_activity, 'golf')                                           AS site_activity_golf,
                 contains(site_activity, 'tennis')                                         AS site_activity_tennis,
                 contains(site_activity, 'lounge')                                         AS site_activity_lounge,
                 contains(site_activity, 'swim')                                           AS site_activity_swim,
                 contains(site_activity, 'sleep')                                          AS site_activity_sleep,
                 contains(site_activity, 'cycle')                                          AS site_activity_cycle,
                 contains(site_activity, 'relax and renew')                                AS site_activity_relax_and_renew,
                 contains(site_activity, 'lifestyle')                                      AS site_activity_lifestyle,
                 contains(site_activity, 'yoga and studio')                                AS site_activity_yoga_and_studio,
                 contains(site_activity, 'gym and train')                                  AS site_activity_gym_and_train,
                 contains(site_activity, 'gym')                                            AS site_activity_gym,
                 contains(site_activity, 'fashion and function')                           AS site_activity_fashion_and_function,
                 contains(site_activity, 'training')                                       AS site_activity_training,

                 (contains(site_print, 'print') AND NOT contains(site_print, 'non-print')) AS site_print_print,
                 contains(site_print, 'solid')                                             AS site_print_solid,
                 contains(site_print, 'heather')                                           AS site_print_heather,
                 contains(site_print, 'non-print')                                         AS site_print_non_print,
                 contains(site_print, 'metallic')                                          AS site_print_metallic,

                 CASE WHEN merch_category ILIKE '%bra%' THEN 'bra'
                      WHEN merch_category ILIKE 'sleepwear' THEN concat(merch_category, '_', merch_category_type)
                      ELSE merch_category END                                              AS merch_category_consolidated
 --      LOWER(merch_category_type) = 'all over'                                       AS is_allover,
--      LOWER(merch_size_range) = 'youniveral'                                        AS is_youniversal,
--      LOWER(merch_size_range) = 'one size'                                          AS is_onesize,
--      CONCAT(merch_sub_department, '_', merch_collection)                           AS concat_subd_coll,
--      CONCAT(merch_sub_department, '_', merch_collection, '_', site_color)          AS subd_coll_wcolor,
--      CONCAT(merch_collection, '_', site_color)                                     AS coll_wcolor,
--      CONCAT(merch_sub_department, '_', site_color)                                 AS sub_wcolor

 FROM mpids m
      LEFT JOIN cleansed_pivoted_tags p ON p.mpid_from_tags = m.mpid
 ORDER BY m.mpid, site_date_expected);
