-- INSERT INTO REPORTING_BASE_PROD.FABLETICS.TASK_CONTROL_TABLE
-- VALUES
--     ('FACT_ORDER_LINE_EXTENDED_DAILY_REFRESH_NEW', NULL)

--USE WAREHOUSE DA_WH_ADHOC_LARGE;

-- update refresh date from the datetime_modified in the table
UPDATE REPORTING_BASE_PROD.FABLETICS.TASK_CONTROL_TABLE
--     SET refresh_from_date = '2013-08-30'
SET refresh_from_date = (SELECT IFF(DAY(CURRENT_DATE())=1,
                                DATEADD(MONTH, -24, CURRENT_DATE()),
                                COALESCE(DATEADD(MONTH,-6,MAX(order_local_datetime::DATE)),'2013-08-30'))
                         FROM REPORTING_BASE_PROD.FABLETICS.FACT_ORDER_LINE_EXTENDED_NEW)
WHERE process_name = 'FACT_ORDER_LINE_EXTENDED_DAILY_REFRESH_NEW';

-- start business logic

CREATE OR REPLACE TEMP TABLE _orders_with_customer_segment AS
SELECT --top 10
        STORE_BRAND,
        STORE_REGION,
        STORE_COUNTRY,
        fol.ORDER_LOCAL_DATETIME::DATE                          AS order_date,
        DATE_TRUNC('hour', fol.ORDER_LOCAL_DATETIME)            AS order_date_hour,
        CASE
            WHEN fa.SUB_STORE_ID = 241 AND ds.store_type = 'Retail' THEN 'YT-CUST'
            WHEN STORE_BRAND = 'Fabletics' AND IS_SCRUBS_CUSTOMER = TRUE AND dc.GENDER = 'M' THEN 'SC-M-CUST'
            WHEN STORE_BRAND = 'Fabletics' AND IS_SCRUBS_CUSTOMER = TRUE And dc.GENDER != 'M' THEN 'SC-W-CUST'
            WHEN STORE_BRAND = 'Fabletics' AND dc.GENDER = 'M' THEN 'FL-M-CUST'
            WHEN STORE_BRAND = 'Fabletics' AND dc.GENDER != 'M' THEN 'FL-W-CUST'
            WHEN STORE_BRAND = 'Yitty' THEN 'YT-CUST' END       AS customer_segment,
        ds.store_type                                           AS sales_channel,
        iff(BUNDLE_PRODUCT_ID = -1, 'Item', 'Outfit')           AS item_type,
        dpt.IS_FREE                                             AS IS_FREE,
        doc.IS_PRODUCT_SEEDING_ORDER,
        doc.IS_BOPS_ORDER,
        doc.IS_RETAIL_SHIP_ONLY_ORDER, -- 10.29.24 Christina added
        doc.IS_MEMBERSHIP_GIFT,
        doc.IS_WAREHOUSE_OUTLET_ORDER, -- 8.21.24 Christina added for warehouse site sales


        fa.VIP_COHORT_MONTH_DATE,
        IFF(fa.sub_store_id = -1, fo.store_id, fa.SUB_STORE_ID) AS vip_store_id,
        fol.ORDER_LINE_ID,
        fol.ORDER_ID,
        fol.STORE_ID,
        fol.CUSTOMER_ID,
        fol.PRODUCT_ID,
        fol.MASTER_PRODUCT_ID,
        fol.BUNDLE_PRODUCT_ID,
        fol.BUNDLE_COMPONENT_PRODUCT_ID,
        fol.GROUP_CODE,
        fol.BUNDLE_COMPONENT_HISTORY_KEY,
        fol.PRODUCT_TYPE_KEY,
        fol.BUNDLE_ORDER_LINE_ID,
        fol.ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
        fol.ORDER_SALES_CHANNEL_KEY,
        fol.ORDER_LINE_STATUS_KEY,
        fol.ORDER_STATUS_KEY,
        fol.ORDER_PRODUCT_SOURCE_KEY,
        fol.CURRENCY_KEY,
        fol.ADMINISTRATOR_ID,
        fol.WAREHOUSE_ID,
        fol.SHIPPING_ADDRESS_ID,
        fol.BILLING_ADDRESS_ID,
        fol.BOUNCEBACK_ENDOWMENT_ID,
        fol.COST_SOURCE_ID,
        fol.COST_SOURCE,
        fol.ORDER_LOCAL_DATETIME,
        fol.PAYMENT_TRANSACTION_LOCAL_DATETIME,
        fol.SHIPPED_LOCAL_DATETIME,
        fol.ORDER_COMPLETION_LOCAL_DATETIME,
        fol.ORDER_DATE_USD_CONVERSION_RATE,
        fol.ORDER_DATE_EUR_CONVERSION_RATE,
        fol.PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
        fol.PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
        fol.SHIPPED_DATE_USD_CONVERSION_RATE,
        fol.SHIPPED_DATE_EUR_CONVERSION_RATE,
        fol.REPORTING_USD_CONVERSION_RATE,
        fol.REPORTING_EUR_CONVERSION_RATE,
        fol.EFFECTIVE_VAT_RATE,
        fol.ITEM_QUANTITY,
        fol.PAYMENT_TRANSACTION_LOCAL_AMOUNT,
        fol.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
        fol.TARIFF_REVENUE_LOCAL_AMOUNT,
        fol.PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
        fol.TAX_LOCAL_AMOUNT,
        fol.PRODUCT_DISCOUNT_LOCAL_AMOUNT,
        fol.SHIPPING_COST_LOCAL_AMOUNT,
        fol.SHIPPING_DISCOUNT_LOCAL_AMOUNT,
        fol.SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
        fol.SHIPPING_REVENUE_LOCAL_AMOUNT,
        fol.CASH_CREDIT_LOCAL_AMOUNT,
        fol.CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
        fol.CASH_REFUND_CREDIT_LOCAL_AMOUNT,
        fol.CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
        fol.CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
        fol.TOKEN_COUNT,
        fol.TOKEN_LOCAL_AMOUNT,
        fol.CASH_TOKEN_COUNT,
        fol.CASH_TOKEN_LOCAL_AMOUNT,
        fol.NON_CASH_TOKEN_COUNT,
        fol.NON_CASH_TOKEN_LOCAL_AMOUNT,
        fol.NON_CASH_CREDIT_LOCAL_AMOUNT,
        fol.ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
        fol.ORACLE_COST_LOCAL_AMOUNT,
        fol.LPN_PO_COST_LOCAL_AMOUNT,
        fol.PO_COST_LOCAL_AMOUNT,
        fol.MISC_COGS_LOCAL_AMOUNT,
        fol.ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
        fol.ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
        fol.ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
        fol.ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
        fol.ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
        fol.PRICE_OFFERED_LOCAL_AMOUNT,
        fol.AIR_VIP_PRICE,
        fol.RETAIL_UNIT_PRICE,
        fol.BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
        fol.PRODUCT_PRICE_HISTORY_KEY,
        fol.BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
        fol.ITEM_PRICE_KEY,
        fol.AMOUNT_TO_PAY,
        fol.CASH_GROSS_REVENUE_LOCAL_AMOUNT,
        fol.PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
        fol.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
        fol.PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
        fol.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
        fol.GROUP_KEY,
        fol.LPN_CODE,
        fol.CUSTOM_PRINTED_TEXT,
        fol.REPORTING_LANDED_COST_LOCAL_AMOUNT,
        fol.IS_ACTUAL_LANDED_COST,
        fol.IS_FULLY_LANDED,
        fol.FULLY_LANDED_CONVERSION_DATE,
        fol.ACTUAL_LANDED_COST_LOCAL_AMOUNT,
        fol.ACTUAL_PO_COST_LOCAL_AMOUNT,
        fol.ACTUAL_CMT_COST_LOCAL_AMOUNT,
        fol.ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
        fol.ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
        fol.ACTUAL_OTHER_COST_LOCAL_AMOUNT,
        fol.META_CREATE_DATETIME,
        fol.META_UPDATE_DATETIME,
        fol.product_discount_local_amount * fol.reporting_usd_conversion_rate AS product_discount_amount,
        fol.product_subtotal_local_amount * fol.reporting_usd_conversion_rate AS product_subtotal_amount,
        fol.product_gross_revenue_local_amount * fol.reporting_usd_conversion_rate AS product_gross_revenue_amount,
        fol.product_gross_revenue_excl_shipping_local_amount * fol.reporting_usd_conversion_rate AS product_gross_revenue_excl_shipping_amount,
        fol.product_margin_pre_return_local_amount * fol.reporting_usd_conversion_rate AS product_margin_pre_return_amount,
        fol.product_margin_pre_return_excl_shipping_local_amount * fol.reporting_usd_conversion_rate AS product_margin_pre_return_excl_shipping_amount,
        fol.token_local_amount * fol.reporting_usd_conversion_rate AS token_amount,
        fol.reporting_landed_cost_local_amount * fol.reporting_usd_conversion_rate AS reporting_landed_cost_amount,
        fol.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT * fol.reporting_usd_conversion_rate AS SUBTOTAL_EXCL_TARIFF,
        fol.TARIFF_REVENUE_LOCAL_AMOUNT * fol.reporting_usd_conversion_rate AS TARIFF_REVENUE,
        ((fol.AIR_VIP_PRICE * fol.reporting_usd_conversion_rate)
             - (fol.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT
                    + fol.TARIFF_REVENUE_LOCAL_AMOUNT)* fol.reporting_usd_conversion_rate)  AS VIP_DISCOUNT, --8.6.24 Christina added conversion rate calc to VIP Price
        fol.non_cash_credit_local_amount* fol.reporting_usd_conversion_rate AS NON_CASH_CREDIT_DISCOUNT,
        fol.bounceback_endowment_local_amount * fol.reporting_usd_conversion_rate AS bounceback_endowment_amount,
        fol.vip_endowment_local_amount * fol.reporting_usd_conversion_rate AS vip_endowment_amount,
        PRODUCT_DISCOUNT_AMOUNT AS PRODUCT_DISCOUNT,
        PRODUCT_DISCOUNT + VIP_DISCOUNT + NON_CASH_CREDIT_DISCOUNT AS BLENDED_DISCOUNT,
        dp.sku,
        dpt.product_type_name,
        CASE
            WHEN UPPER(TRIM(I.SIZE)) ilike '%OS%' THEN 'OS'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%2XL%' THEN 'XXL/1X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%3XL%' THEN 'XXXL'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%XXXL%' THEN 'XXXL'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%3X/4X%' THEN '3X/4X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%XS/S%' THEN 'XS/S'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%XL/XXL%' THEN 'XL/XXL'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%1X/2X%' THEN '1X/2X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%XXL%' THEN 'XXL/1X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%L/XL%' THEN 'L/XL'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%XL%' THEN 'XL'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%XXS%' THEN 'XXS'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%XS%' THEN 'XS'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%S/M%' THEN 'S/M'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%M/L%' THEN 'M/L'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%SM%' THEN 'S'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%M%' THEN 'M'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%L%' THEN 'L'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%S%' THEN 'S'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%X3%' THEN i.size
            WHEN UPPER(TRIM(I.SIZE)) ilike '%1X%' THEN 'XXL/1X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%2X%' THEN '2X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%3X%' THEN '3X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%4X%' THEN '4X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%5X%' THEN '5X'
            WHEN UPPER(TRIM(I.SIZE)) ilike '%6X%' THEN '6X'
            WHEN UPPER(TRIM(I.SIZE)) ilike 'Unknown' THEN 'OS'
            WHEN UPPER(TRIM(I.SIZE)) in ('2T', '3T') THEN 'OTHER'
            ELSE UPPER(TRIM(I.SIZE)) END AS cleansed_size,
        product_sku,
        IFF(dpt.PRODUCT_TYPE_ID = 15, 'Part of an Outfit', 'Pieced Good') AS OUTFIT_PIECED_GOOD,

        -- fields from membership_order_type
        mc.MEMBERSHIP_ORDER_TYPE_L1,
        mc.MEMBERSHIP_ORDER_TYPE_L2,
        mc.MEMBERSHIP_ORDER_TYPE_L3,
        mc.MEMBERSHIP_ORDER_TYPE_L4,

        --key data from fact_order added 9.3.24 | BOPs data from fact_order added 10.29.24
        fo.ACTIVATION_KEY,
        fo.MEMBERSHIP_EVENT_KEY,
        fo.BOPS_PICKUP_LOCAL_DATETIME,
        fo.BOPS_STORE_ID
    FROM edw_prod.DATA_MODEL_FL.fact_order_line fol
        JOIN edw_prod.DATA_MODEL_FL.DIM_CUSTOMER dc ON dc.CUSTOMER_ID = fol.CUSTOMER_ID
        JOIN edw_prod.DATA_MODEL_FL.fact_order fo ON fol.order_id = fo.order_id
        JOIN edw_prod.DATA_MODEL_FL.FACT_ACTIVATION fa ON fa.ACTIVATION_KEY = fo.ACTIVATION_KEY
        JOIN edw_prod.DATA_MODEL_FL.DIM_ITEM_PRICE dp ON dp.ITEM_PRICE_KEY = fol.ITEM_PRICE_KEY --Christina swapped from dim_product 12.12.24
        LEFT JOIN lake_view.ultra_warehouse.item i ON i.item_number = dp.sku
        JOIN edw_prod.DATA_MODEL_FL.dim_store ds ON fol.store_id = ds.store_id
        JOIN edw_prod.DATA_MODEL_FL.dim_product_type dpt ON fol.product_type_key = dpt.product_type_key
        JOIN edw_prod.DATA_MODEL_FL.dim_order_membership_classification mc
            ON mc.order_membership_classification_key = fol.order_membership_classification_key
        JOIN edw_prod.DATA_MODEL_FL.dim_order_sales_channel doc
            ON fol.order_sales_channel_key = doc.order_sales_channel_key
        JOIN edw_prod.DATA_MODEL_FL.dim_order_status dos ON fol.order_status_key = dos.order_status_key
        JOIN edw_prod.DATA_MODEL_FL.dim_order_processing_status ops
            ON ops.order_processing_status_key = fo.order_processing_status_key
        JOIN edw_prod.DATA_MODEL_FL.dim_order_line_status ols  ON fol.order_line_status_key = ols.order_line_status_key
    WHERE ds.store_brand IN ('Fabletics', 'Yitty')
    AND dpt.product_type_name NOT IN
       ('Offer Gift', 'Autoship Gift', 'Free Sample', 'Gift Certificate', 'Flyer', 'Candidate Product',
        'Membership Gift', 'Directed Insert', 'Free Third Party Subscription')
    AND doc.order_classification_l1 IN ('Product Order')
    AND doc.is_ps_order = 'FALSE'
    AND dos.order_status IN ('Success', 'Pending')
    AND ols.order_line_status <> 'Cancelled'
    AND fol.order_local_datetime::DATE >= (SELECT refresh_from_date
                                           FROM REPORTING_BASE_PROD.FABLETICS.TASK_CONTROL_TABLE
                                           WHERE process_name ='FACT_ORDER_LINE_EXTENDED_DAILY_REFRESH_NEW');


---------------------------------------------------------------------------------
-- add in order line level promo dimensions

CREATE OR REPLACE TEMP TABLE _promo_dimensions AS
SELECT
    ocs.order_line_id,
    CASE WHEN promo_type = 'Item Level Discount: Buy X Products Get Y Off'
        THEN COALESCE(dph.min_product_quantity,dph.REQUIRED_PRODUCT_QUANTITY) || ' for ' || subtotal_discount
    WHEN SHIPPING_DISCOUNT = '100% off' THEN 'Free shipping'
    WHEN promo_code = 'TEAM50' THEN 'Employee discount'
    WHEN PROMO_TYPE = 'Item Level Discount: Membership Normal'
        THEN 'Item level: ' || dph.subtotal_discount || ' discount.'
    WHEN promo_classification IN ('Courtesy', 'Employee') THEN promo_classification || ': ' || dph.subtotal_discount

    WHEN promo_type = 'Order Level Discount: Required Min Subtotal After Discounts Subtracted'
        THEN 'Order level: ' || subtotal_discount
    WHEN PROMO_TYPE = 'Item Level Discount: Required Min Subtotal After Discounts Subtracted'
        THEN 'Item level: ' || subtotal_discount
    WHEN PROMO_TYPE IS NULL THEN 'No promo applied'
    WHEN PROMO_TYPE = 'Item Level Discount: Bogo' THEN 'BOGO'
    WHEN PROMO_TYPE = 'Loyalty Point Multiplier' THEN 'Loyalty points: ' || dph.MEMBERSHIP_REWARD_MULTIPLIER
    WHEN promo_type = 'Item Level Discount: Discountable Required Product Before Discount Applies'
        THEN 'Buy from: ' || COALESCE(dph.category_required, dph.fpl_required) || ' . Get one with ' || dph.subtotal_discount
    WHEN promo_type = 'Item Level Discount: Buy X or More For Y Each'
        THEN COALESCE(dph.MIN_PRODUCT_QUANTITY,dph.REQUIRED_PRODUCT_QUANTITY) || ' for ' || dph.subtotal_discount || ' each'
    ELSE 'No promo'
    END AS promo_offer_rule_based,
    CATEGORY_INCLUDED,
    PROMO_TYPE,
    first_promo_code,
    dph.promo_id,
    CASE WHEN CONTAINS(PROMO_TYPE, 'Order Level Discount:') THEN CONCAT('Order Level: ', LISTAGG(DISTINCT TRIM(UPPER(REGEXP_REPLACE(dph.promo_name, '!', '')))))
        WHEN CONTAINS(PROMO_TYPE, 'Item Level Discount:')THEN CONCAT('Item Level: ', LISTAGG(DISTINCT TRIM(UPPER(REGEXP_REPLACE(dph.promo_name, '!', '')))))
        ELSE dph.promo_name END AS promo_name, --Christina added 1.8.25
    fpl.FEATURED_PRODUCT_LOCATION_ID,
    product_discount_amount,
    product_subtotal_amount,
    product_gross_revenue_amount,
    product_gross_revenue_excl_shipping_amount,
    product_margin_pre_return_amount,
    product_margin_pre_return_excl_shipping_amount,
    token_amount,
    reporting_landed_cost_amount,
    bounceback_endowment_amount,
    vip_endowment_amount,
    fold.ORDER_LINE_DISCOUNT_LOCAL_AMOUNT AS promo_discount
FROM _orders_with_customer_segment ocs
JOIN EDW_PROD.DATA_MODEL_FL.fact_order_line_DISCOUNT folD ON FOLD.ORDER_LINE_ID = ocs.ORDER_LINE_ID
LEFT JOIN EDW_PROD.DATA_MODEL_FL.dim_promo_history dph ON dph.promo_history_key = folD.promo_history_key
LEFT JOIN LAKE_FL_VIEW.ULTRA_MERCHANT.PROMO p ON p.PROMO_ID = dph.PROMO_ID
LEFT JOIN LAKE_FL_VIEW.ULTRA_MERCHANT.FEATURED_PRODUCT_LOCATION fpl ON fpl.FEATURED_PRODUCT_LOCATION_ID = p.FEATURED_PRODUCT_LOCATION_ID
GROUP BY ocs.ORDER_LINE_ID,
    CASE WHEN promo_type = 'Item Level Discount: Buy X Products Get Y Off'
            THEN COALESCE(dph.min_product_quantity,dph.REQUIRED_PRODUCT_QUANTITY) || ' for ' || subtotal_discount
        WHEN SHIPPING_DISCOUNT = '100% off' THEN 'Free shipping'
        WHEN promo_code = 'TEAM50' THEN 'Employee discount'
        WHEN PROMO_TYPE = 'Item Level Discount: Membership Normal'
            THEN 'Item level: ' || dph.subtotal_discount || ' discount.'
        WHEN promo_classification IN ('Courtesy', 'Employee') THEN promo_classification || ': ' || dph.subtotal_discount

        WHEN promo_type = 'Order Level Discount: Required Min Subtotal After Discounts Subtracted'
            THEN 'Order level: ' || subtotal_discount
        WHEN PROMO_TYPE = 'Item Level Discount: Required Min Subtotal After Discounts Subtracted'
            THEN 'Item level: ' || subtotal_discount
        WHEN PROMO_TYPE IS NULL THEN 'No promo applied'
        WHEN PROMO_TYPE = 'Item Level Discount: Bogo' THEN 'BOGO'
        WHEN PROMO_TYPE = 'Loyalty Point Multiplier' THEN 'Loyalty points: ' || dph.MEMBERSHIP_REWARD_MULTIPLIER
        WHEN promo_type = 'Item Level Discount: Discountable Required Product Before Discount Applies'
            THEN 'Buy from: ' || COALESCE(dph.category_required, dph.fpl_required) || ' . Get one with ' || dph.subtotal_discount
        WHEN promo_type = 'Item Level Discount: Buy X or More For Y Each'
            THEN COALESCE(dph.MIN_PRODUCT_QUANTITY,dph.REQUIRED_PRODUCT_QUANTITY) || ' for ' || dph.subtotal_discount || ' each'
        ELSE 'No promo'
        END, CATEGORY_INCLUDED, PROMO_TYPE, FIRST_PROMO_CODE, dph.promo_id, promo_name, fpl.FEATURED_PRODUCT_LOCATION_ID, product_discount_amount, product_subtotal_amount, product_gross_revenue_amount, product_gross_revenue_excl_shipping_amount, product_margin_pre_return_amount, product_margin_pre_return_excl_shipping_amount, token_amount,
         bounceback_endowment_amount, vip_endowment_amount, reporting_landed_cost_amount, promo_discount;


--------------------------------------------------------------------------------
-- combining promo dimensions & order line data

CREATE OR REPLACE TEMP TABLE _order_line_data AS
SELECT
    fol.STORE_BRAND,
    fol.STORE_REGION,
    fol.STORE_COUNTRY,
    fol.ORDER_DATE,
    fol.ORDER_DATE_HOUR,
    fol.CUSTOMER_SEGMENT,
    fol.SALES_CHANNEL,
    fol.ITEM_TYPE,
    fol.IS_FREE,
    fol.IS_PRODUCT_SEEDING_ORDER,
    fol.IS_BOPS_ORDER,
    fol.IS_RETAIL_SHIP_ONLY_ORDER,
    fol.IS_MEMBERSHIP_GIFT,
    fol.IS_WAREHOUSE_OUTLET_ORDER,
    fol.VIP_COHORT_MONTH_DATE,
    fol.VIP_STORE_ID,
    fol.ORDER_LINE_ID,
    fol.ORDER_ID,
    fol.STORE_ID,
    fol.CUSTOMER_ID,
    fol.PRODUCT_ID,
    fol.MASTER_PRODUCT_ID,
    fol.BUNDLE_PRODUCT_ID,
    fol.BUNDLE_COMPONENT_PRODUCT_ID,
    fol.GROUP_CODE,
    fol.BUNDLE_COMPONENT_HISTORY_KEY,
    fol.PRODUCT_TYPE_KEY,
    fol.BUNDLE_ORDER_LINE_ID,
    fol.ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
    fol.ORDER_SALES_CHANNEL_KEY,
    fol.ORDER_LINE_STATUS_KEY,
    fol.ORDER_STATUS_KEY,
    fol.ORDER_PRODUCT_SOURCE_KEY,
    fol.CURRENCY_KEY,
    fol.ADMINISTRATOR_ID,
    fol.WAREHOUSE_ID,
    fol.SHIPPING_ADDRESS_ID,
    fol.BILLING_ADDRESS_ID,
    fol.BOUNCEBACK_ENDOWMENT_ID,
    fol.COST_SOURCE_ID,
    fol.COST_SOURCE,
    fol.ORDER_LOCAL_DATETIME,
    fol.PAYMENT_TRANSACTION_LOCAL_DATETIME,
    fol.SHIPPED_LOCAL_DATETIME,
    fol.ORDER_COMPLETION_LOCAL_DATETIME,
    fol.ORDER_DATE_USD_CONVERSION_RATE,
    fol.ORDER_DATE_EUR_CONVERSION_RATE,
    fol.PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
    fol.PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
    fol.SHIPPED_DATE_USD_CONVERSION_RATE,
    fol.SHIPPED_DATE_EUR_CONVERSION_RATE,
    fol.REPORTING_USD_CONVERSION_RATE,
    fol.REPORTING_EUR_CONVERSION_RATE,
    fol.EFFECTIVE_VAT_RATE,
    fol.ITEM_QUANTITY,
    fol.PAYMENT_TRANSACTION_LOCAL_AMOUNT,
    fol.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
    fol.TARIFF_REVENUE_LOCAL_AMOUNT,
    fol.PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
    fol.TAX_LOCAL_AMOUNT,
    fol.PRODUCT_DISCOUNT_LOCAL_AMOUNT,
    fol.SHIPPING_COST_LOCAL_AMOUNT,
    fol.SHIPPING_DISCOUNT_LOCAL_AMOUNT,
    fol.SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
    fol.SHIPPING_REVENUE_LOCAL_AMOUNT,
    fol.CASH_CREDIT_LOCAL_AMOUNT,
    fol.CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
    fol.CASH_REFUND_CREDIT_LOCAL_AMOUNT,
    fol.CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
    fol.CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
    fol.TOKEN_COUNT,
    fol.TOKEN_LOCAL_AMOUNT,
    fol.CASH_TOKEN_COUNT,
    fol.CASH_TOKEN_LOCAL_AMOUNT,
    fol.NON_CASH_TOKEN_COUNT,
    fol.NON_CASH_TOKEN_LOCAL_AMOUNT,
    fol.NON_CASH_CREDIT_LOCAL_AMOUNT,
    fol.ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
    fol.ORACLE_COST_LOCAL_AMOUNT,
    fol.LPN_PO_COST_LOCAL_AMOUNT,
    fol.PO_COST_LOCAL_AMOUNT,
    fol.MISC_COGS_LOCAL_AMOUNT,
    fol.ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
    fol.ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
    fol.ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
    fol.ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
    fol.ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
    fol.PRICE_OFFERED_LOCAL_AMOUNT,
    fol.AIR_VIP_PRICE,
    fol.RETAIL_UNIT_PRICE,
    fol.BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
    fol.PRODUCT_PRICE_HISTORY_KEY,
    fol.BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
    fol.ITEM_PRICE_KEY,
    fol.AMOUNT_TO_PAY,
    fol.CASH_GROSS_REVENUE_LOCAL_AMOUNT,
    fol.PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
    fol.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
    fol.PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
    fol.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
    fol.GROUP_KEY,
    fol.LPN_CODE,
    fol.CUSTOM_PRINTED_TEXT,
    fol.REPORTING_LANDED_COST_LOCAL_AMOUNT,
    fol.IS_ACTUAL_LANDED_COST,
    fol.IS_FULLY_LANDED,
    fol.FULLY_LANDED_CONVERSION_DATE,
    fol.ACTUAL_LANDED_COST_LOCAL_AMOUNT,
    fol.ACTUAL_PO_COST_LOCAL_AMOUNT,
    fol.ACTUAL_CMT_COST_LOCAL_AMOUNT,
    fol.ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
    fol.ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
    fol.ACTUAL_OTHER_COST_LOCAL_AMOUNT,
    fol.META_CREATE_DATETIME,
    fol.META_UPDATE_DATETIME,
    fol.PRODUCT_DISCOUNT_AMOUNT,
    fol.PRODUCT_SUBTOTAL_AMOUNT,
    fol.PRODUCT_GROSS_REVENUE_AMOUNT,
    fol.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT,
    fol.PRODUCT_MARGIN_PRE_RETURN_AMOUNT,
    fol.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT,
    fol.TOKEN_AMOUNT,
    fol.REPORTING_LANDED_COST_AMOUNT,
    fol.SUBTOTAL_EXCL_TARIFF,
    fol.TARIFF_REVENUE,
    fol.VIP_DISCOUNT,
    fol.NON_CASH_CREDIT_DISCOUNT,
    fol.PRODUCT_DISCOUNT,
    fol.BLENDED_DISCOUNT,
    fol.SKU,
    fol.PRODUCT_TYPE_NAME,
    fol.CLEANSED_SIZE,
    fol.PRODUCT_SKU,
    fol.OUTFIT_PIECED_GOOD,
    fol.MEMBERSHIP_ORDER_TYPE_L1,
    fol.MEMBERSHIP_ORDER_TYPE_L2,
    fol.MEMBERSHIP_ORDER_TYPE_L3,
    fol.MEMBERSHIP_ORDER_TYPE_L4,
    fol.ACTIVATION_KEY,
    fol.MEMBERSHIP_EVENT_KEY,
    fol.BOPS_PICKUP_LOCAL_DATETIME,
    fol.BOPS_STORE_ID,
    -- order level promo dimensions
    COALESCE(pd_o.promo_offer_rule_based,'No Promo') AS promo_order_offer,
    COALESCE(pd_o.CATEGORY_INCLUDED,'No Promo') AS promo_order_category,
    COALESCE(pd_o.first_promo_code,'No Promo') AS promo_order_promocode,
    pd_o.FEATURED_PRODUCT_LOCATION_ID AS promo_order_fpl,
    COALESCE(pd_o.promo_discount,0) AS promo_order_discount,
    pd_o.promo_id promo_order_promoid,
    COALESCE(pd_o.promo_name, 'No Promo') AS promo_order_name, --Christina added 1.8.25

    -- item level promo dimensions
    COALESCE(pd_i.promo_offer_rule_based,'No Promo') AS promo_item_offer,
    COALESCE(pd_i.CATEGORY_INCLUDED,'No Promo') AS promo_item_category,
    COALESCE(pd_i.first_promo_code,'No Promo') AS promo_item_promocode,
    pd_i.FEATURED_PRODUCT_LOCATION_ID AS promo_item_fpl,
    COALESCE(pd_i.promo_discount,0) AS promo_item_discount,
    pd_i.promo_id promo_item_promoid,
    COALESCE(pd_i.promo_name, 'No Promo') AS promo_item_name, --Christina added 1.8.25
    fol.BOUNCEBACK_ENDOWMENT_AMOUNT,
    fol.VIP_ENDOWMENT_AMOUNT

    --IFF(COALESCE(pd_o.FEATURED_PRODUCT_LOCATION_ID,pd_i.featured_product_location_id) in (23821,23720,23719,24034),TRUE,FALSE) as is_yitty_sale_section_product
FROM _orders_with_customer_segment fol
LEFT JOIN _promo_dimensions pd_o ON pd_o.order_line_id = fol.ORDER_LINE_ID
    AND pd_o.PROMO_TYPE ilike '%order level discount%'
LEFT JOIN _promo_dimensions pd_i ON pd_i.order_line_id = fol.ORDER_LINE_ID
    AND pd_i.PROMO_TYPE ilike '%item level discount%';

--------------------------------------------------------------------------------
-- get history table of product tags for when they were on or off @ time of sale
-- tags include Platinum Exclusive, Lead Only and Last Chance

CREATE OR REPLACE TEMP TABLE _historical_product_tags AS
SELECT
    lower(tg.label) AS tag_name,
    edw_prod.stg.udf_unconcat_brand(pt.product_id) AS master_product_id,
    pt.effective_start_datetime,
    pt.effective_end_datetime
FROM LAKE_CONSOLIDATED.ultra_merchant_history.product_tag pt
JOIN LAKE_CONSOLIDATED.ultra_merchant.product p ON pt.product_id = p.product_id
JOIN LAKE_CONSOLIDATED.ultra_merchant.tag tg ON tg.tag_id = pt.tag_id
WHERE lower(tg.label) IN ('platinum exclusive','lead only','last chance','sale fit finds')
AND pt.hvr_change_op = 1
AND pt.meta_company_id = 20
AND pt.effective_end_datetime >= (SELECT refresh_from_date
                                  FROM REPORTING_BASE_PROD.FABLETICS.TASK_CONTROL_TABLE
                                  WHERE process_name ='FACT_ORDER_LINE_EXTENDED_DAILY_REFRESH_NEW');


CREATE OR REPLACE TEMP TABLE _order_line_with_tags AS
SELECT DISTINCT
    ocs.STORE_BRAND,
    ocs.STORE_REGION,
    ocs.STORE_COUNTRY,
    ocs.ORDER_DATE,
    ocs.ORDER_DATE_HOUR,
    ocs.CUSTOMER_SEGMENT,
    ocs.SALES_CHANNEL,
    ocs.ITEM_TYPE,
    ocs.IS_FREE,
    ocs.IS_PRODUCT_SEEDING_ORDER,
    ocs.IS_BOPS_ORDER,
    ocs.IS_RETAIL_SHIP_ONLY_ORDER,
    ocs.IS_MEMBERSHIP_GIFT,
    ocs.IS_WAREHOUSE_OUTLET_ORDER,
    ocs.VIP_COHORT_MONTH_DATE,
    ocs.VIP_STORE_ID,
    ocs.ORDER_LINE_ID,
    ocs.ORDER_ID,
    ocs.STORE_ID,
    ocs.CUSTOMER_ID,
    ocs.PRODUCT_ID,
    ocs.MASTER_PRODUCT_ID,
    ocs.BUNDLE_PRODUCT_ID,
    ocs.BUNDLE_COMPONENT_PRODUCT_ID,
    ocs.GROUP_CODE,
    ocs.BUNDLE_COMPONENT_HISTORY_KEY,
    ocs.PRODUCT_TYPE_KEY,
    ocs.BUNDLE_ORDER_LINE_ID,
    ocs.ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
    ocs.ORDER_SALES_CHANNEL_KEY,
    ocs.ORDER_LINE_STATUS_KEY,
    ocs.ORDER_STATUS_KEY,
    ocs.ORDER_PRODUCT_SOURCE_KEY,
    ocs.CURRENCY_KEY,
    ocs.ADMINISTRATOR_ID,
    ocs.WAREHOUSE_ID,
    ocs.SHIPPING_ADDRESS_ID,
    ocs.BILLING_ADDRESS_ID,
    ocs.BOUNCEBACK_ENDOWMENT_ID,
    ocs.COST_SOURCE_ID,
    ocs.COST_SOURCE,
    ocs.ORDER_LOCAL_DATETIME,
    ocs.PAYMENT_TRANSACTION_LOCAL_DATETIME,
    ocs.SHIPPED_LOCAL_DATETIME,
    ocs.ORDER_COMPLETION_LOCAL_DATETIME,
    ocs.ORDER_DATE_USD_CONVERSION_RATE,
    ocs.ORDER_DATE_EUR_CONVERSION_RATE,
    ocs.PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
    ocs.PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
    ocs.SHIPPED_DATE_USD_CONVERSION_RATE,
    ocs.SHIPPED_DATE_EUR_CONVERSION_RATE,
    ocs.REPORTING_USD_CONVERSION_RATE,
    ocs.REPORTING_EUR_CONVERSION_RATE,
    ocs.EFFECTIVE_VAT_RATE,
    ocs.ITEM_QUANTITY,
    ocs.PAYMENT_TRANSACTION_LOCAL_AMOUNT,
    ocs.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
    ocs.TARIFF_REVENUE_LOCAL_AMOUNT,
    ocs.PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
    ocs.TAX_LOCAL_AMOUNT,
    ocs.PRODUCT_DISCOUNT_LOCAL_AMOUNT,
    ocs.SHIPPING_COST_LOCAL_AMOUNT,
    ocs.SHIPPING_DISCOUNT_LOCAL_AMOUNT,
    ocs.SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
    ocs.SHIPPING_REVENUE_LOCAL_AMOUNT,
    ocs.CASH_CREDIT_LOCAL_AMOUNT,
    ocs.CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
    ocs.CASH_REFUND_CREDIT_LOCAL_AMOUNT,
    ocs.CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
    ocs.CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
    ocs.TOKEN_COUNT,
    ocs.TOKEN_LOCAL_AMOUNT,
    ocs.CASH_TOKEN_COUNT,
    ocs.CASH_TOKEN_LOCAL_AMOUNT,
    ocs.NON_CASH_TOKEN_COUNT,
    ocs.NON_CASH_TOKEN_LOCAL_AMOUNT,
    ocs.NON_CASH_CREDIT_LOCAL_AMOUNT,
    ocs.ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
    ocs.ORACLE_COST_LOCAL_AMOUNT,
    ocs.LPN_PO_COST_LOCAL_AMOUNT,
    ocs.PO_COST_LOCAL_AMOUNT,
    ocs.MISC_COGS_LOCAL_AMOUNT,
    ocs.ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
    ocs.ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
    ocs.ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
    ocs.ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
    ocs.ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
    ocs.PRICE_OFFERED_LOCAL_AMOUNT,
    ocs.AIR_VIP_PRICE,
    ocs.RETAIL_UNIT_PRICE,
    ocs.BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
    ocs.PRODUCT_PRICE_HISTORY_KEY,
    ocs.BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
    ocs.ITEM_PRICE_KEY,
    ocs.AMOUNT_TO_PAY,
    ocs.CASH_GROSS_REVENUE_LOCAL_AMOUNT,
    ocs.PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
    ocs.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
    ocs.PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
    ocs.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
    ocs.GROUP_KEY,
    ocs.LPN_CODE,
    ocs.CUSTOM_PRINTED_TEXT,
    ocs.REPORTING_LANDED_COST_LOCAL_AMOUNT,
    ocs.IS_ACTUAL_LANDED_COST,
    ocs.IS_FULLY_LANDED,
    ocs.FULLY_LANDED_CONVERSION_DATE,
    ocs.ACTUAL_LANDED_COST_LOCAL_AMOUNT,
    ocs.ACTUAL_PO_COST_LOCAL_AMOUNT,
    ocs.ACTUAL_CMT_COST_LOCAL_AMOUNT,
    ocs.ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
    ocs.ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
    ocs.ACTUAL_OTHER_COST_LOCAL_AMOUNT,
    ocs.META_CREATE_DATETIME,
    ocs.META_UPDATE_DATETIME,
    ocs.PRODUCT_DISCOUNT_AMOUNT,
    ocs.PRODUCT_SUBTOTAL_AMOUNT,
    ocs.PRODUCT_GROSS_REVENUE_AMOUNT,
    ocs.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT,
    ocs.PRODUCT_MARGIN_PRE_RETURN_AMOUNT,
    ocs.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT,
    ocs.TOKEN_AMOUNT,
    ocs.REPORTING_LANDED_COST_AMOUNT,
    ocs.SUBTOTAL_EXCL_TARIFF,
    ocs.TARIFF_REVENUE,
    ocs.VIP_DISCOUNT,
    ocs.NON_CASH_CREDIT_DISCOUNT,
    ocs.PRODUCT_DISCOUNT,
    ocs.BLENDED_DISCOUNT,
    ocs.SKU,
    ocs.PRODUCT_TYPE_NAME,
    ocs.CLEANSED_SIZE,
    ocs.PRODUCT_SKU,
    ocs.OUTFIT_PIECED_GOOD,
    ocs.MEMBERSHIP_ORDER_TYPE_L1,
    ocs.MEMBERSHIP_ORDER_TYPE_L2,
    ocs.MEMBERSHIP_ORDER_TYPE_L3,
    ocs.MEMBERSHIP_ORDER_TYPE_L4,
    ocs.ACTIVATION_KEY,
    ocs.MEMBERSHIP_EVENT_KEY,
    ocs.BOPS_PICKUP_LOCAL_DATETIME,
    ocs.BOPS_STORE_ID,
    ocs.PROMO_ORDER_OFFER,
    ocs.PROMO_ORDER_CATEGORY,
    ocs.PROMO_ORDER_PROMOCODE,
    ocs.PROMO_ORDER_FPL,
    ocs.PROMO_ORDER_DISCOUNT,
    ocs.PROMO_ORDER_PROMOID,
    ocs.PROMO_ORDER_NAME,
    ocs.PROMO_ITEM_OFFER,
    ocs.PROMO_ITEM_CATEGORY,
    ocs.PROMO_ITEM_PROMOCODE,
    ocs.PROMO_ITEM_FPL,
    ocs.PROMO_ITEM_DISCOUNT,
    ocs.PROMO_ITEM_PROMOID,
    ocs.PROMO_ITEM_NAME,
    ocs.BOUNCEBACK_ENDOWMENT_AMOUNT,
    ocs.VIP_ENDOWMENT_AMOUNT,
    IFF(ep.master_product_id is not null, TRUE, FALSE) AS is_exclusive_product,
    IFF(lo.master_product_id is not null, TRUE, FALSE) AS is_lead_only_product,
    IFF(lc.master_product_id is not null, TRUE, FALSE) AS is_last_chance_product,
    IFF(lc.master_product_id is not null, TRUE, FALSE) AS is_sale_section_product
FROM _order_line_data ocs
LEFT JOIN (SELECT * FROM _historical_product_tags WHERE tag_name = 'platinum exclusive') ep
    ON ep.master_product_id = IFF(ocs.master_product_id = -1, ocs.product_id, ocs.master_product_id)
        AND ep.effective_start_datetime < ocs.ORDER_LOCAL_DATETIME
        AND ep.effective_end_datetime >= ORDER_LOCAL_DATETIME
LEFT JOIN (SELECT * FROM _historical_product_tags WHERE tag_name = 'lead only') lo
    ON lo.master_product_id = IFF(ocs.master_product_id = -1, ocs.product_id, ocs.master_product_id)
        AND lo.effective_start_datetime < ocs.ORDER_LOCAL_DATETIME
        AND lo.effective_end_datetime >= ORDER_LOCAL_DATETIME
LEFT JOIN (SELECT * FROM _historical_product_tags WHERE tag_name = 'last chance') lc
    ON lc.master_product_id = IFF(ocs.master_product_id = -1, ocs.product_id, ocs.master_product_id)
        AND lc.effective_start_datetime < ocs.ORDER_LOCAL_DATETIME
        AND lc.effective_end_datetime >= ORDER_LOCAL_DATETIME
LEFT JOIN (SELECT * FROM _historical_product_tags WHERE tag_name = 'sale fit finds') sale
    ON sale.master_product_id = IFF(ocs.master_product_id = -1, ocs.product_id, ocs.master_product_id)
        AND sale.effective_start_datetime < ocs.ORDER_LOCAL_DATETIME
        AND sale.effective_end_datetime >= ORDER_LOCAL_DATETIME;


-- join to get loyalty tier of customer @ time of purchase
CREATE OR REPLACE TEMP TABLE _add_in_loyalty_tier AS
SELECT
    olt.STORE_BRAND,
    olt.STORE_REGION,
    olt.STORE_COUNTRY,
    olt.ORDER_DATE,
    olt.ORDER_DATE_HOUR,
    olt.CUSTOMER_SEGMENT,
    olt.SALES_CHANNEL,
    olt.ITEM_TYPE,
    olt.IS_FREE,
    olt.IS_PRODUCT_SEEDING_ORDER,
    olt.IS_BOPS_ORDER,
    olt.IS_RETAIL_SHIP_ONLY_ORDER,
    olt.IS_MEMBERSHIP_GIFT,
    olt.IS_WAREHOUSE_OUTLET_ORDER,
    olt.VIP_COHORT_MONTH_DATE,
    olt.VIP_STORE_ID,
    olt.ORDER_LINE_ID,
    olt.ORDER_ID,
    olt.STORE_ID,
    olt.CUSTOMER_ID,
    olt.PRODUCT_ID,
    olt.MASTER_PRODUCT_ID,
    olt.BUNDLE_PRODUCT_ID,
    olt.BUNDLE_COMPONENT_PRODUCT_ID,
    olt.GROUP_CODE,
    olt.BUNDLE_COMPONENT_HISTORY_KEY,
    olt.PRODUCT_TYPE_KEY,
    olt.BUNDLE_ORDER_LINE_ID,
    olt.ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
    olt.ORDER_SALES_CHANNEL_KEY,
    olt.ORDER_LINE_STATUS_KEY,
    olt.ORDER_STATUS_KEY,
    olt.ORDER_PRODUCT_SOURCE_KEY,
    olt.CURRENCY_KEY,
    olt.ADMINISTRATOR_ID,
    olt.WAREHOUSE_ID,
    olt.SHIPPING_ADDRESS_ID,
    olt.BILLING_ADDRESS_ID,
    olt.BOUNCEBACK_ENDOWMENT_ID,
    olt.COST_SOURCE_ID,
    olt.COST_SOURCE,
    olt.ORDER_LOCAL_DATETIME,
    olt.PAYMENT_TRANSACTION_LOCAL_DATETIME,
    olt.SHIPPED_LOCAL_DATETIME,
    olt.ORDER_COMPLETION_LOCAL_DATETIME,
    olt.ORDER_DATE_USD_CONVERSION_RATE,
    olt.ORDER_DATE_EUR_CONVERSION_RATE,
    olt.PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
    olt.PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
    olt.SHIPPED_DATE_USD_CONVERSION_RATE,
    olt.SHIPPED_DATE_EUR_CONVERSION_RATE,
    olt.REPORTING_USD_CONVERSION_RATE,
    olt.REPORTING_EUR_CONVERSION_RATE,
    olt.EFFECTIVE_VAT_RATE,
    olt.ITEM_QUANTITY,
    olt.PAYMENT_TRANSACTION_LOCAL_AMOUNT,
    olt.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
    olt.TARIFF_REVENUE_LOCAL_AMOUNT,
    olt.PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
    olt.TAX_LOCAL_AMOUNT,
    olt.PRODUCT_DISCOUNT_LOCAL_AMOUNT,
    olt.SHIPPING_COST_LOCAL_AMOUNT,
    olt.SHIPPING_DISCOUNT_LOCAL_AMOUNT,
    olt.SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
    olt.SHIPPING_REVENUE_LOCAL_AMOUNT,
    olt.CASH_CREDIT_LOCAL_AMOUNT,
    olt.CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
    olt.CASH_REFUND_CREDIT_LOCAL_AMOUNT,
    olt.CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
    olt.CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
    olt.TOKEN_COUNT,
    olt.TOKEN_LOCAL_AMOUNT,
    olt.CASH_TOKEN_COUNT,
    olt.CASH_TOKEN_LOCAL_AMOUNT,
    olt.NON_CASH_TOKEN_COUNT,
    olt.NON_CASH_TOKEN_LOCAL_AMOUNT,
    olt.NON_CASH_CREDIT_LOCAL_AMOUNT,
    olt.ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
    olt.ORACLE_COST_LOCAL_AMOUNT,
    olt.LPN_PO_COST_LOCAL_AMOUNT,
    olt.PO_COST_LOCAL_AMOUNT,
    olt.MISC_COGS_LOCAL_AMOUNT,
    olt.ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
    olt.ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
    olt.ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
    olt.ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
    olt.ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
    olt.PRICE_OFFERED_LOCAL_AMOUNT,
    olt.AIR_VIP_PRICE,
    olt.RETAIL_UNIT_PRICE,
    olt.BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
    olt.PRODUCT_PRICE_HISTORY_KEY,
    olt.BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
    olt.ITEM_PRICE_KEY,
    olt.AMOUNT_TO_PAY,
    olt.CASH_GROSS_REVENUE_LOCAL_AMOUNT,
    olt.PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
    olt.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
    olt.PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
    olt.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
    olt.GROUP_KEY,
    olt.LPN_CODE,
    olt.CUSTOM_PRINTED_TEXT,
    olt.REPORTING_LANDED_COST_LOCAL_AMOUNT,
    olt.IS_ACTUAL_LANDED_COST,
    olt.IS_FULLY_LANDED,
    olt.FULLY_LANDED_CONVERSION_DATE,
    olt.ACTUAL_LANDED_COST_LOCAL_AMOUNT,
    olt.ACTUAL_PO_COST_LOCAL_AMOUNT,
    olt.ACTUAL_CMT_COST_LOCAL_AMOUNT,
    olt.ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
    olt.ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
    olt.ACTUAL_OTHER_COST_LOCAL_AMOUNT,
    olt.META_CREATE_DATETIME,
    olt.META_UPDATE_DATETIME,
    olt.PRODUCT_DISCOUNT_AMOUNT,
    olt.PRODUCT_SUBTOTAL_AMOUNT,
    olt.PRODUCT_GROSS_REVENUE_AMOUNT,
    olt.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT,
    olt.PRODUCT_MARGIN_PRE_RETURN_AMOUNT,
    olt.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT,
    olt.TOKEN_AMOUNT,
    olt.REPORTING_LANDED_COST_AMOUNT,
    olt.SUBTOTAL_EXCL_TARIFF,
    olt.TARIFF_REVENUE,
    olt.VIP_DISCOUNT,
    olt.NON_CASH_CREDIT_DISCOUNT,
    olt.PRODUCT_DISCOUNT,
    olt.BLENDED_DISCOUNT,
    olt.SKU,
    olt.PRODUCT_TYPE_NAME,
    olt.CLEANSED_SIZE,
    olt.PRODUCT_SKU,
    olt.OUTFIT_PIECED_GOOD,
    olt.MEMBERSHIP_ORDER_TYPE_L1,
    olt.MEMBERSHIP_ORDER_TYPE_L2,
    olt.MEMBERSHIP_ORDER_TYPE_L3,
    olt.MEMBERSHIP_ORDER_TYPE_L4,
    olt.ACTIVATION_KEY,
    olt.MEMBERSHIP_EVENT_KEY,
    olt.BOPS_PICKUP_LOCAL_DATETIME,
    olt.BOPS_STORE_ID,
    olt.PROMO_ORDER_OFFER,
    olt.PROMO_ORDER_CATEGORY,
    olt.PROMO_ORDER_PROMOCODE,
    olt.PROMO_ORDER_FPL,
    olt.PROMO_ORDER_DISCOUNT,
    olt.PROMO_ORDER_PROMOID,
    olt.PROMO_ORDER_NAME,
    olt.PROMO_ITEM_OFFER,
    olt.PROMO_ITEM_CATEGORY,
    olt.PROMO_ITEM_PROMOCODE,
    olt.PROMO_ITEM_FPL,
    olt.PROMO_ITEM_DISCOUNT,
    olt.PROMO_ITEM_PROMOID,
    olt.PROMO_ITEM_NAME,
    olt.IS_EXCLUSIVE_PRODUCT,
    olt.IS_LEAD_ONLY_PRODUCT,
    olt.IS_LAST_CHANCE_PRODUCT,
    olt.IS_SALE_SECTION_PRODUCT,
    CASE WHEN olt.MEMBERSHIP_ORDER_TYPE_L2 = 'Activating VIP' THEN 'Gold'
        ELSE MEMBERSHIP_REWARD_TIER END AS MEMBERSHIP_REWARD_TIER,
    olt.BOUNCEBACK_ENDOWMENT_AMOUNT,
    olt.VIP_ENDOWMENT_AMOUNT

FROM _order_line_with_tags olt
LEFT JOIN edw_prod.DATA_MODEL_FL.FACT_ACTIVATION_LOYALTY_TIER falt ON falt.CUSTOMER_ID = olt.CUSTOMER_ID
    AND falt.EVENT_START_LOCAL_DATETIME <= olt.ORDER_LOCAL_DATETIME
    AND falt.EVENT_END_LOCAL_DATETIME > olt.ORDER_LOCAL_DATETIME;


MERGE INTO REPORTING_BASE_PROD.FABLETICS.FACT_ORDER_LINE_EXTENDED_NEW as t
USING
(
    SELECT
        STORE_BRAND,
        STORE_REGION,
        STORE_COUNTRY,
        ORDER_DATE,
        ORDER_DATE_HOUR,
        CUSTOMER_SEGMENT,
        SALES_CHANNEL,
        ITEM_TYPE,
        IS_FREE,
        IS_PRODUCT_SEEDING_ORDER,
        IS_BOPS_ORDER,
        IS_RETAIL_SHIP_ONLY_ORDER,
        IS_MEMBERSHIP_GIFT,
        IS_WAREHOUSE_OUTLET_ORDER,
        VIP_COHORT_MONTH_DATE,
        VIP_STORE_ID,
        ORDER_LINE_ID,
        ORDER_ID,
        STORE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        MASTER_PRODUCT_ID,
        BUNDLE_PRODUCT_ID,
        BUNDLE_COMPONENT_PRODUCT_ID,
        GROUP_CODE,
        BUNDLE_COMPONENT_HISTORY_KEY,
        PRODUCT_TYPE_KEY,
        BUNDLE_ORDER_LINE_ID,
        ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
        ORDER_SALES_CHANNEL_KEY,
        ORDER_LINE_STATUS_KEY,
        ORDER_STATUS_KEY,
        ORDER_PRODUCT_SOURCE_KEY,
        CURRENCY_KEY,
        ADMINISTRATOR_ID,
        WAREHOUSE_ID,
        SHIPPING_ADDRESS_ID,
        BILLING_ADDRESS_ID,
        BOUNCEBACK_ENDOWMENT_ID,
        COST_SOURCE_ID,
        COST_SOURCE,
        ORDER_LOCAL_DATETIME,
        PAYMENT_TRANSACTION_LOCAL_DATETIME,
        SHIPPED_LOCAL_DATETIME,
        ORDER_COMPLETION_LOCAL_DATETIME,
        ORDER_DATE_USD_CONVERSION_RATE,
        ORDER_DATE_EUR_CONVERSION_RATE,
        PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
        PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
        SHIPPED_DATE_USD_CONVERSION_RATE,
        SHIPPED_DATE_EUR_CONVERSION_RATE,
        REPORTING_USD_CONVERSION_RATE,
        REPORTING_EUR_CONVERSION_RATE,
        EFFECTIVE_VAT_RATE,
        ITEM_QUANTITY,
        PAYMENT_TRANSACTION_LOCAL_AMOUNT,
        SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
        TARIFF_REVENUE_LOCAL_AMOUNT,
        PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
        TAX_LOCAL_AMOUNT,
        PRODUCT_DISCOUNT_LOCAL_AMOUNT,
        SHIPPING_COST_LOCAL_AMOUNT,
        SHIPPING_DISCOUNT_LOCAL_AMOUNT,
        SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
        SHIPPING_REVENUE_LOCAL_AMOUNT,
        CASH_CREDIT_LOCAL_AMOUNT,
        CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
        CASH_REFUND_CREDIT_LOCAL_AMOUNT,
        CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
        CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
        TOKEN_COUNT,
        TOKEN_LOCAL_AMOUNT,
        CASH_TOKEN_COUNT,
        CASH_TOKEN_LOCAL_AMOUNT,
        NON_CASH_TOKEN_COUNT,
        NON_CASH_TOKEN_LOCAL_AMOUNT,
        NON_CASH_CREDIT_LOCAL_AMOUNT,
        ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
        ORACLE_COST_LOCAL_AMOUNT,
        LPN_PO_COST_LOCAL_AMOUNT,
        PO_COST_LOCAL_AMOUNT,
        MISC_COGS_LOCAL_AMOUNT,
        ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
        ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
        ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
        ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
        ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
        PRICE_OFFERED_LOCAL_AMOUNT,
        AIR_VIP_PRICE,
        RETAIL_UNIT_PRICE,
        BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
        PRODUCT_PRICE_HISTORY_KEY,
        BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
        ITEM_PRICE_KEY,
        AMOUNT_TO_PAY,
        CASH_GROSS_REVENUE_LOCAL_AMOUNT,
        PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
        PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
        GROUP_KEY,
        LPN_CODE,
        CUSTOM_PRINTED_TEXT,
        REPORTING_LANDED_COST_LOCAL_AMOUNT,
        IS_ACTUAL_LANDED_COST,
        IS_FULLY_LANDED,
        FULLY_LANDED_CONVERSION_DATE,
        ACTUAL_LANDED_COST_LOCAL_AMOUNT,
        ACTUAL_PO_COST_LOCAL_AMOUNT,
        ACTUAL_CMT_COST_LOCAL_AMOUNT,
        ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
        ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
        ACTUAL_OTHER_COST_LOCAL_AMOUNT,
        META_CREATE_DATETIME,
        META_UPDATE_DATETIME,
        PRODUCT_DISCOUNT_AMOUNT,
        PRODUCT_SUBTOTAL_AMOUNT,
        PRODUCT_GROSS_REVENUE_AMOUNT,
        PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT,
        TOKEN_AMOUNT,
        REPORTING_LANDED_COST_AMOUNT,
        SKU,
        PRODUCT_TYPE_NAME,
        CLEANSED_SIZE,
        PRODUCT_SKU,
        OUTFIT_PIECED_GOOD,
        MEMBERSHIP_ORDER_TYPE_L1,
        MEMBERSHIP_ORDER_TYPE_L2,
        MEMBERSHIP_ORDER_TYPE_L3,
        MEMBERSHIP_ORDER_TYPE_L4,
        ACTIVATION_KEY,
        MEMBERSHIP_EVENT_KEY,
        BOPS_PICKUP_LOCAL_DATETIME,
        BOPS_STORE_ID,
        PROMO_ORDER_OFFER,
        PROMO_ORDER_CATEGORY,
        PROMO_ORDER_PROMOCODE,
        PROMO_ORDER_FPL,
        PROMO_ORDER_DISCOUNT,
        PROMO_ORDER_PROMOID,
        PROMO_ORDER_NAME,
        PROMO_ITEM_OFFER,
        PROMO_ITEM_CATEGORY,
        PROMO_ITEM_PROMOCODE,
        PROMO_ITEM_FPL,
        PROMO_ITEM_DISCOUNT,
        PROMO_ITEM_PROMOID,
        PROMO_ITEM_NAME,
        IS_EXCLUSIVE_PRODUCT,
        IS_LEAD_ONLY_PRODUCT,
        IS_LAST_CHANCE_PRODUCT,
        IS_SALE_SECTION_PRODUCT,
        MEMBERSHIP_REWARD_TIER,
        VIP_DISCOUNT,
        NON_CASH_CREDIT_DISCOUNT,
        PRODUCT_DISCOUNT,
        BLENDED_DISCOUNT,
        SUBTOTAL_EXCL_TARIFF,
        TARIFF_REVENUE,
        BOUNCEBACK_ENDOWMENT_AMOUNT,
        VIP_ENDOWMENT_AMOUNT,
        CURRENT_TIMESTAMP() AS DATETIME_MODIFIED
    FROM _add_in_loyalty_tier
    ) AS s
    ON t.ORDER_LINE_ID = s.ORDER_LINE_ID
    WHEN MATCHED THEN
    UPDATE
    SET
        t.STORE_BRAND = s.STORE_BRAND,
        t.STORE_REGION = s.STORE_REGION,
        t.STORE_COUNTRY = s.STORE_COUNTRY,
        t.ORDER_DATE = s.ORDER_DATE,
        t.ORDER_DATE_HOUR = s.ORDER_DATE_HOUR,
        t.CUSTOMER_SEGMENT = s.CUSTOMER_SEGMENT,
        t.SALES_CHANNEL = s.SALES_CHANNEL,
        t.ITEM_TYPE = s.ITEM_TYPE,
        t.IS_FREE = s.IS_FREE,
        t.IS_PRODUCT_SEEDING_ORDER = s.IS_PRODUCT_SEEDING_ORDER,
        t.IS_BOPS_ORDER = s.IS_BOPS_ORDER,
        t.IS_RETAIL_SHIP_ONLY_ORDER = s.IS_RETAIL_SHIP_ONLY_ORDER,
        t.IS_MEMBERSHIP_GIFT = s.IS_MEMBERSHIP_GIFT,
        t.IS_WAREHOUSE_OUTLET_ORDER = s.IS_WAREHOUSE_OUTLET_ORDER,
        t.VIP_COHORT_MONTH_DATE = s.VIP_COHORT_MONTH_DATE,
        t.VIP_STORE_ID = s.VIP_STORE_ID,
        t.ORDER_ID = s.ORDER_ID,
        t.STORE_ID = s.STORE_ID,
        t.CUSTOMER_ID = s.CUSTOMER_ID,
        t.PRODUCT_ID = s.PRODUCT_ID,
        t.MASTER_PRODUCT_ID = s.MASTER_PRODUCT_ID,
        t.BUNDLE_PRODUCT_ID = s.BUNDLE_PRODUCT_ID,
        t.BUNDLE_COMPONENT_PRODUCT_ID = s.BUNDLE_COMPONENT_PRODUCT_ID,
        t.GROUP_CODE = s.GROUP_CODE,
        t.BUNDLE_COMPONENT_HISTORY_KEY = s.BUNDLE_COMPONENT_HISTORY_KEY,
        t.PRODUCT_TYPE_KEY = s.PRODUCT_TYPE_KEY,
        t.BUNDLE_ORDER_LINE_ID = s.BUNDLE_ORDER_LINE_ID,
        t.ORDER_MEMBERSHIP_CLASSIFICATION_KEY = s.ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
        t.ORDER_SALES_CHANNEL_KEY = s.ORDER_SALES_CHANNEL_KEY,
        t.ORDER_LINE_STATUS_KEY = s.ORDER_LINE_STATUS_KEY,
        t.ORDER_STATUS_KEY = s.ORDER_STATUS_KEY,
        t.ORDER_PRODUCT_SOURCE_KEY = s.ORDER_PRODUCT_SOURCE_KEY,
        t.CURRENCY_KEY = s.CURRENCY_KEY,
        t.ADMINISTRATOR_ID = s.ADMINISTRATOR_ID,
        t.WAREHOUSE_ID = s.WAREHOUSE_ID,
        t.SHIPPING_ADDRESS_ID = s.SHIPPING_ADDRESS_ID,
        t.BILLING_ADDRESS_ID = s.BILLING_ADDRESS_ID,
        t.BOUNCEBACK_ENDOWMENT_ID = s.BOUNCEBACK_ENDOWMENT_ID,
        t.COST_SOURCE_ID = s.COST_SOURCE_ID,
        t.COST_SOURCE = s.COST_SOURCE,
        t.ORDER_LOCAL_DATETIME = s.ORDER_LOCAL_DATETIME,
        t.PAYMENT_TRANSACTION_LOCAL_DATETIME = s.PAYMENT_TRANSACTION_LOCAL_DATETIME,
        t.SHIPPED_LOCAL_DATETIME = s.SHIPPED_LOCAL_DATETIME,
        t.ORDER_COMPLETION_LOCAL_DATETIME = s.ORDER_COMPLETION_LOCAL_DATETIME,
        t.ORDER_DATE_USD_CONVERSION_RATE = s.ORDER_DATE_USD_CONVERSION_RATE,
        t.ORDER_DATE_EUR_CONVERSION_RATE = s.ORDER_DATE_EUR_CONVERSION_RATE,
        t.PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE = s.PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
        t.PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE = s.PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
        t.SHIPPED_DATE_USD_CONVERSION_RATE = s.SHIPPED_DATE_USD_CONVERSION_RATE,
        t.SHIPPED_DATE_EUR_CONVERSION_RATE = s.SHIPPED_DATE_EUR_CONVERSION_RATE,
        t.REPORTING_USD_CONVERSION_RATE = s.REPORTING_USD_CONVERSION_RATE,
        t.REPORTING_EUR_CONVERSION_RATE = s.REPORTING_EUR_CONVERSION_RATE,
        t.EFFECTIVE_VAT_RATE = s.EFFECTIVE_VAT_RATE,
        t.ITEM_QUANTITY = s.ITEM_QUANTITY,
        t.PAYMENT_TRANSACTION_LOCAL_AMOUNT = s.PAYMENT_TRANSACTION_LOCAL_AMOUNT,
        t.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT = s.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
        t.TARIFF_REVENUE_LOCAL_AMOUNT = s.TARIFF_REVENUE_LOCAL_AMOUNT,
        t.PRODUCT_SUBTOTAL_LOCAL_AMOUNT = s.PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
        t.TAX_LOCAL_AMOUNT = s.TAX_LOCAL_AMOUNT,
        t.PRODUCT_DISCOUNT_LOCAL_AMOUNT = s.PRODUCT_DISCOUNT_LOCAL_AMOUNT,
        t.SHIPPING_COST_LOCAL_AMOUNT = s.SHIPPING_COST_LOCAL_AMOUNT,
        t.SHIPPING_DISCOUNT_LOCAL_AMOUNT = s.SHIPPING_DISCOUNT_LOCAL_AMOUNT,
        t.SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT = s.SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
        t.SHIPPING_REVENUE_LOCAL_AMOUNT = s.SHIPPING_REVENUE_LOCAL_AMOUNT,
        t.CASH_CREDIT_LOCAL_AMOUNT = s.CASH_CREDIT_LOCAL_AMOUNT,
        t.CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT = s.CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
        t.CASH_REFUND_CREDIT_LOCAL_AMOUNT = s.CASH_REFUND_CREDIT_LOCAL_AMOUNT,
        t.CASH_GIFTCO_CREDIT_LOCAL_AMOUNT = s.CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
        t.CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT = s.CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
        t.TOKEN_COUNT = s.TOKEN_COUNT,
        t.TOKEN_LOCAL_AMOUNT = s.TOKEN_LOCAL_AMOUNT,
        t.CASH_TOKEN_COUNT = s.CASH_TOKEN_COUNT,
        t.CASH_TOKEN_LOCAL_AMOUNT = s.CASH_TOKEN_LOCAL_AMOUNT,
        t.NON_CASH_TOKEN_COUNT = s.NON_CASH_TOKEN_COUNT,
        t.NON_CASH_TOKEN_LOCAL_AMOUNT = s.NON_CASH_TOKEN_LOCAL_AMOUNT,
        t.NON_CASH_CREDIT_LOCAL_AMOUNT = s.NON_CASH_CREDIT_LOCAL_AMOUNT,
        t.ESTIMATED_LANDED_COST_LOCAL_AMOUNT = s.ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
        t.ORACLE_COST_LOCAL_AMOUNT = s.ORACLE_COST_LOCAL_AMOUNT,
        t.LPN_PO_COST_LOCAL_AMOUNT = s.LPN_PO_COST_LOCAL_AMOUNT,
        t.PO_COST_LOCAL_AMOUNT = s.PO_COST_LOCAL_AMOUNT,
        t.MISC_COGS_LOCAL_AMOUNT = s.MISC_COGS_LOCAL_AMOUNT,
        t.ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT = s.ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
        t.ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT = s.ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
        t.ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT = s.ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
        t.ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT = s.ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
        t.ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE = s.ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
        t.PRICE_OFFERED_LOCAL_AMOUNT = s.PRICE_OFFERED_LOCAL_AMOUNT,
        t.AIR_VIP_PRICE = s.AIR_VIP_PRICE,
        t.RETAIL_UNIT_PRICE = s.RETAIL_UNIT_PRICE,
        t.BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT = s.BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
        t.PRODUCT_PRICE_HISTORY_KEY = s.PRODUCT_PRICE_HISTORY_KEY,
        t.BUNDLE_PRODUCT_PRICE_HISTORY_KEY = s.BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
        t.ITEM_PRICE_KEY = s.ITEM_PRICE_KEY,
        t.AMOUNT_TO_PAY = s.AMOUNT_TO_PAY,
        t.CASH_GROSS_REVENUE_LOCAL_AMOUNT = s.CASH_GROSS_REVENUE_LOCAL_AMOUNT,
        t.PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT = s.PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
        t.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT = s.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
        t.PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT = s.PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
        t.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT = s.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
        t.GROUP_KEY = s.GROUP_KEY,
        t.LPN_CODE = s.LPN_CODE,
        t.CUSTOM_PRINTED_TEXT = s.CUSTOM_PRINTED_TEXT,
        t.REPORTING_LANDED_COST_LOCAL_AMOUNT = s.REPORTING_LANDED_COST_LOCAL_AMOUNT,
        t.IS_ACTUAL_LANDED_COST = s.IS_ACTUAL_LANDED_COST,
        t.IS_FULLY_LANDED = s.IS_FULLY_LANDED,
        t.FULLY_LANDED_CONVERSION_DATE = s.FULLY_LANDED_CONVERSION_DATE,
        t.ACTUAL_LANDED_COST_LOCAL_AMOUNT = s.ACTUAL_LANDED_COST_LOCAL_AMOUNT,
        t.ACTUAL_PO_COST_LOCAL_AMOUNT = s.ACTUAL_PO_COST_LOCAL_AMOUNT,
        t.ACTUAL_CMT_COST_LOCAL_AMOUNT = s.ACTUAL_CMT_COST_LOCAL_AMOUNT,
        t.ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT = s.ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
        t.ACTUAL_FREIGHT_COST_LOCAL_AMOUNT = s.ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
        t.ACTUAL_OTHER_COST_LOCAL_AMOUNT = s.ACTUAL_OTHER_COST_LOCAL_AMOUNT,
        t.META_CREATE_DATETIME = s.META_CREATE_DATETIME,
        t.META_UPDATE_DATETIME = s.META_UPDATE_DATETIME,
        t.PRODUCT_DISCOUNT_AMOUNT = s.PRODUCT_DISCOUNT_AMOUNT,
        t.PRODUCT_SUBTOTAL_AMOUNT = s.PRODUCT_SUBTOTAL_AMOUNT,
        t.PRODUCT_GROSS_REVENUE_AMOUNT = s.PRODUCT_GROSS_REVENUE_AMOUNT,
        t.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT = s.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT,
        t.PRODUCT_MARGIN_PRE_RETURN_AMOUNT = s.PRODUCT_MARGIN_PRE_RETURN_AMOUNT,
        t.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT = s.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT,
        t.TOKEN_AMOUNT = s.TOKEN_AMOUNT,
        t.REPORTING_LANDED_COST_AMOUNT = s.REPORTING_LANDED_COST_AMOUNT,
        t.SKU = s.SKU,
        t.PRODUCT_TYPE_NAME = s.PRODUCT_TYPE_NAME,
        t.CLEANSED_SIZE = s.CLEANSED_SIZE,
        t.PRODUCT_SKU = s.PRODUCT_SKU,
        t.OUTFIT_PIECED_GOOD = s.OUTFIT_PIECED_GOOD,
        t.MEMBERSHIP_ORDER_TYPE_L1 = s.MEMBERSHIP_ORDER_TYPE_L1,
        t.MEMBERSHIP_ORDER_TYPE_L2 = s.MEMBERSHIP_ORDER_TYPE_L2,
        t.MEMBERSHIP_ORDER_TYPE_L3 = s.MEMBERSHIP_ORDER_TYPE_L3,
        t.MEMBERSHIP_ORDER_TYPE_L4 = s.MEMBERSHIP_ORDER_TYPE_L4,
        t.ACTIVATION_KEY = s.ACTIVATION_KEY,
        t.MEMBERSHIP_EVENT_KEY = s.MEMBERSHIP_EVENT_KEY,
        t.BOPS_PICKUP_LOCAL_DATETIME = s.BOPS_PICKUP_LOCAL_DATETIME,
        t.BOPS_STORE_ID = s.BOPS_STORE_ID,
        t.PROMO_ORDER_OFFER = s.PROMO_ORDER_OFFER,
        t.PROMO_ORDER_CATEGORY = s.PROMO_ORDER_CATEGORY,
        t.PROMO_ORDER_PROMOCODE = s.PROMO_ORDER_PROMOCODE,
        t.PROMO_ORDER_FPL = s.PROMO_ORDER_FPL,
        t.PROMO_ORDER_DISCOUNT = s.PROMO_ORDER_DISCOUNT,
        t.PROMO_ORDER_PROMOID = s.PROMO_ORDER_PROMOID,
        t.PROMO_ORDER_NAME = s.PROMO_ORDER_NAME,
        t.PROMO_ITEM_OFFER = s.PROMO_ITEM_OFFER,
        t.PROMO_ITEM_CATEGORY = s.PROMO_ITEM_CATEGORY,
        t.PROMO_ITEM_PROMOCODE = s.PROMO_ITEM_PROMOCODE,
        t.PROMO_ITEM_FPL = s.PROMO_ITEM_FPL,
        t.PROMO_ITEM_DISCOUNT = s.PROMO_ITEM_DISCOUNT,
        t.PROMO_ITEM_PROMOID = s.PROMO_ITEM_PROMOID,
        t.PROMO_ITEM_NAME = s.PROMO_ITEM_NAME,
        t.IS_EXCLUSIVE_PRODUCT = s.IS_EXCLUSIVE_PRODUCT,
        t.IS_LEAD_ONLY_PRODUCT = s.IS_LEAD_ONLY_PRODUCT,
        t.IS_LAST_CHANCE_PRODUCT = s.IS_LAST_CHANCE_PRODUCT,
        t.IS_SALE_SECTION_PRODUCT = s.IS_SALE_SECTION_PRODUCT,
        t.MEMBERSHIP_REWARD_TIER = s.MEMBERSHIP_REWARD_TIER,
        t.VIP_DISCOUNT = s.VIP_DISCOUNT,
        t.NON_CASH_CREDIT_DISCOUNT = s.NON_CASH_CREDIT_DISCOUNT,
        t.PRODUCT_DISCOUNT = s.PRODUCT_DISCOUNT,
        t.BLENDED_DISCOUNT = s.BLENDED_DISCOUNT,
        t.SUBTOTAL_EXCL_TARIFF = s.SUBTOTAL_EXCL_TARIFF,
        t.TARIFF_REVENUE = s.TARIFF_REVENUE,
        t.BOUNCEBACK_ENDOWMENT_AMOUNT = s.BOUNCEBACK_ENDOWMENT_AMOUNT,
        t.VIP_ENDOWMENT_AMOUNT = s.VIP_ENDOWMENT_AMOUNT,
        t.DATETIME_MODIFIED = s.DATETIME_MODIFIED
    WHEN NOT MATCHED THEN
    INSERT
    (
        STORE_BRAND,
        STORE_REGION,
        STORE_COUNTRY,
        ORDER_DATE,
        ORDER_DATE_HOUR,
        CUSTOMER_SEGMENT,
        SALES_CHANNEL,
        ITEM_TYPE,
        IS_FREE,
        IS_PRODUCT_SEEDING_ORDER,
        IS_BOPS_ORDER,
        IS_RETAIL_SHIP_ONLY_ORDER,
        IS_MEMBERSHIP_GIFT,
        IS_WAREHOUSE_OUTLET_ORDER,
        VIP_COHORT_MONTH_DATE,
        VIP_STORE_ID,
        ORDER_LINE_ID,
        ORDER_ID,
        STORE_ID,
        CUSTOMER_ID,
        PRODUCT_ID,
        MASTER_PRODUCT_ID,
        BUNDLE_PRODUCT_ID,
        BUNDLE_COMPONENT_PRODUCT_ID,
        GROUP_CODE,
        BUNDLE_COMPONENT_HISTORY_KEY,
        PRODUCT_TYPE_KEY,
        BUNDLE_ORDER_LINE_ID,
        ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
        ORDER_SALES_CHANNEL_KEY,
        ORDER_LINE_STATUS_KEY,
        ORDER_STATUS_KEY,
        ORDER_PRODUCT_SOURCE_KEY,
        CURRENCY_KEY,
        ADMINISTRATOR_ID,
        WAREHOUSE_ID,
        SHIPPING_ADDRESS_ID,
        BILLING_ADDRESS_ID,
        BOUNCEBACK_ENDOWMENT_ID,
        COST_SOURCE_ID,
        COST_SOURCE,
        ORDER_LOCAL_DATETIME,
        PAYMENT_TRANSACTION_LOCAL_DATETIME,
        SHIPPED_LOCAL_DATETIME,
        ORDER_COMPLETION_LOCAL_DATETIME,
        ORDER_DATE_USD_CONVERSION_RATE,
        ORDER_DATE_EUR_CONVERSION_RATE,
        PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
        PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
        SHIPPED_DATE_USD_CONVERSION_RATE,
        SHIPPED_DATE_EUR_CONVERSION_RATE,
        REPORTING_USD_CONVERSION_RATE,
        REPORTING_EUR_CONVERSION_RATE,
        EFFECTIVE_VAT_RATE,
        ITEM_QUANTITY,
        PAYMENT_TRANSACTION_LOCAL_AMOUNT,
        SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
        TARIFF_REVENUE_LOCAL_AMOUNT,
        PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
        TAX_LOCAL_AMOUNT,
        PRODUCT_DISCOUNT_LOCAL_AMOUNT,
        SHIPPING_COST_LOCAL_AMOUNT,
        SHIPPING_DISCOUNT_LOCAL_AMOUNT,
        SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
        SHIPPING_REVENUE_LOCAL_AMOUNT,
        CASH_CREDIT_LOCAL_AMOUNT,
        CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
        CASH_REFUND_CREDIT_LOCAL_AMOUNT,
        CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
        CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
        TOKEN_COUNT,
        TOKEN_LOCAL_AMOUNT,
        CASH_TOKEN_COUNT,
        CASH_TOKEN_LOCAL_AMOUNT,
        NON_CASH_TOKEN_COUNT,
        NON_CASH_TOKEN_LOCAL_AMOUNT,
        NON_CASH_CREDIT_LOCAL_AMOUNT,
        ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
        ORACLE_COST_LOCAL_AMOUNT,
        LPN_PO_COST_LOCAL_AMOUNT,
        PO_COST_LOCAL_AMOUNT,
        MISC_COGS_LOCAL_AMOUNT,
        ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
        ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
        ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
        ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
        ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
        PRICE_OFFERED_LOCAL_AMOUNT,
        AIR_VIP_PRICE,
        RETAIL_UNIT_PRICE,
        BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
        PRODUCT_PRICE_HISTORY_KEY,
        BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
        ITEM_PRICE_KEY,
        AMOUNT_TO_PAY,
        CASH_GROSS_REVENUE_LOCAL_AMOUNT,
        PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
        PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
        GROUP_KEY,
        LPN_CODE,
        CUSTOM_PRINTED_TEXT,
        REPORTING_LANDED_COST_LOCAL_AMOUNT,
        IS_ACTUAL_LANDED_COST,
        IS_FULLY_LANDED,
        FULLY_LANDED_CONVERSION_DATE,
        ACTUAL_LANDED_COST_LOCAL_AMOUNT,
        ACTUAL_PO_COST_LOCAL_AMOUNT,
        ACTUAL_CMT_COST_LOCAL_AMOUNT,
        ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
        ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
        ACTUAL_OTHER_COST_LOCAL_AMOUNT,
        META_CREATE_DATETIME,
        META_UPDATE_DATETIME,
        PRODUCT_DISCOUNT_AMOUNT,
        PRODUCT_SUBTOTAL_AMOUNT,
        PRODUCT_GROSS_REVENUE_AMOUNT,
        PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_AMOUNT,
        PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT,
        TOKEN_AMOUNT,
        REPORTING_LANDED_COST_AMOUNT,
        SKU,
        PRODUCT_TYPE_NAME,
        CLEANSED_SIZE,
        PRODUCT_SKU,
        OUTFIT_PIECED_GOOD,
        MEMBERSHIP_ORDER_TYPE_L1,
        MEMBERSHIP_ORDER_TYPE_L2,
        MEMBERSHIP_ORDER_TYPE_L3,
        MEMBERSHIP_ORDER_TYPE_L4,
        ACTIVATION_KEY,
        MEMBERSHIP_EVENT_KEY,
        BOPS_PICKUP_LOCAL_DATETIME,
        BOPS_STORE_ID,
        PROMO_ORDER_OFFER,
        PROMO_ORDER_CATEGORY,
        PROMO_ORDER_PROMOCODE,
        PROMO_ORDER_FPL,
        PROMO_ORDER_DISCOUNT,
        PROMO_ORDER_PROMOID,
        PROMO_ORDER_NAME,
        PROMO_ITEM_OFFER,
        PROMO_ITEM_CATEGORY,
        PROMO_ITEM_PROMOCODE,
        PROMO_ITEM_FPL,
        PROMO_ITEM_DISCOUNT,
        PROMO_ITEM_PROMOID,
        PROMO_ITEM_NAME,
        IS_EXCLUSIVE_PRODUCT,
        IS_LEAD_ONLY_PRODUCT,
        IS_LAST_CHANCE_PRODUCT,
        IS_SALE_SECTION_PRODUCT,
        MEMBERSHIP_REWARD_TIER,
        VIP_DISCOUNT,
        NON_CASH_CREDIT_DISCOUNT,
        PRODUCT_DISCOUNT,
        BLENDED_DISCOUNT,
        SUBTOTAL_EXCL_TARIFF,
        TARIFF_REVENUE,
        BOUNCEBACK_ENDOWMENT_AMOUNT,
        VIP_ENDOWMENT_AMOUNT,
        DATETIME_MODIFIED
    )
    VALUES
    (
        s.STORE_BRAND,
        s.STORE_REGION,
        s.STORE_COUNTRY,
        s.ORDER_DATE,
        s.ORDER_DATE_HOUR,
        s.CUSTOMER_SEGMENT,
        s.SALES_CHANNEL,
        s.ITEM_TYPE,
        s.IS_FREE,
        s.IS_PRODUCT_SEEDING_ORDER,
        s.IS_BOPS_ORDER,
        s.IS_RETAIL_SHIP_ONLY_ORDER,
        s.IS_MEMBERSHIP_GIFT,
        s.IS_WAREHOUSE_OUTLET_ORDER,
        s.VIP_COHORT_MONTH_DATE,
        s.VIP_STORE_ID,
        s.ORDER_LINE_ID,
        s.ORDER_ID,
        s.STORE_ID,
        s.CUSTOMER_ID,
        s.PRODUCT_ID,
        s.MASTER_PRODUCT_ID,
        s.BUNDLE_PRODUCT_ID,
        s.BUNDLE_COMPONENT_PRODUCT_ID,
        s.GROUP_CODE,
        s.BUNDLE_COMPONENT_HISTORY_KEY,
        s.PRODUCT_TYPE_KEY,
        s.BUNDLE_ORDER_LINE_ID,
        s.ORDER_MEMBERSHIP_CLASSIFICATION_KEY,
        s.ORDER_SALES_CHANNEL_KEY,
        s.ORDER_LINE_STATUS_KEY,
        s.ORDER_STATUS_KEY,
        s.ORDER_PRODUCT_SOURCE_KEY,
        s.CURRENCY_KEY,
        s.ADMINISTRATOR_ID,
        s.WAREHOUSE_ID,
        s.SHIPPING_ADDRESS_ID,
        s.BILLING_ADDRESS_ID,
        s.BOUNCEBACK_ENDOWMENT_ID,
        s.COST_SOURCE_ID,
        s.COST_SOURCE,
        s.ORDER_LOCAL_DATETIME,
        s.PAYMENT_TRANSACTION_LOCAL_DATETIME,
        s.SHIPPED_LOCAL_DATETIME,
        s.ORDER_COMPLETION_LOCAL_DATETIME,
        s.ORDER_DATE_USD_CONVERSION_RATE,
        s.ORDER_DATE_EUR_CONVERSION_RATE,
        s.PAYMENT_TRANSACTION_DATE_USD_CONVERSION_RATE,
        s.PAYMENT_TRANSACTION_DATE_EUR_CONVERSION_RATE,
        s.SHIPPED_DATE_USD_CONVERSION_RATE,
        s.SHIPPED_DATE_EUR_CONVERSION_RATE,
        s.REPORTING_USD_CONVERSION_RATE,
        s.REPORTING_EUR_CONVERSION_RATE,
        s.EFFECTIVE_VAT_RATE,
        s.ITEM_QUANTITY,
        s.PAYMENT_TRANSACTION_LOCAL_AMOUNT,
        s.SUBTOTAL_EXCL_TARIFF_LOCAL_AMOUNT,
        s.TARIFF_REVENUE_LOCAL_AMOUNT,
        s.PRODUCT_SUBTOTAL_LOCAL_AMOUNT,
        s.TAX_LOCAL_AMOUNT,
        s.PRODUCT_DISCOUNT_LOCAL_AMOUNT,
        s.SHIPPING_COST_LOCAL_AMOUNT,
        s.SHIPPING_DISCOUNT_LOCAL_AMOUNT,
        s.SHIPPING_REVENUE_BEFORE_DISCOUNT_LOCAL_AMOUNT,
        s.SHIPPING_REVENUE_LOCAL_AMOUNT,
        s.CASH_CREDIT_LOCAL_AMOUNT,
        s.CASH_MEMBERSHIP_CREDIT_LOCAL_AMOUNT,
        s.CASH_REFUND_CREDIT_LOCAL_AMOUNT,
        s.CASH_GIFTCO_CREDIT_LOCAL_AMOUNT,
        s.CASH_GIFTCARD_CREDIT_LOCAL_AMOUNT,
        s.TOKEN_COUNT,
        s.TOKEN_LOCAL_AMOUNT,
        s.CASH_TOKEN_COUNT,
        s.CASH_TOKEN_LOCAL_AMOUNT,
        s.NON_CASH_TOKEN_COUNT,
        s.NON_CASH_TOKEN_LOCAL_AMOUNT,
        s.NON_CASH_CREDIT_LOCAL_AMOUNT,
        s.ESTIMATED_LANDED_COST_LOCAL_AMOUNT,
        s.ORACLE_COST_LOCAL_AMOUNT,
        s.LPN_PO_COST_LOCAL_AMOUNT,
        s.PO_COST_LOCAL_AMOUNT,
        s.MISC_COGS_LOCAL_AMOUNT,
        s.ESTIMATED_SHIPPING_SUPPLIES_COST_LOCAL_AMOUNT,
        s.ESTIMATED_SHIPPING_COST_LOCAL_AMOUNT,
        s.ESTIMATED_VARIABLE_WAREHOUSE_COST_LOCAL_AMOUNT,
        s.ESTIMATED_VARIABLE_GMS_COST_LOCAL_AMOUNT,
        s.ESTIMATED_VARIABLE_PAYMENT_PROCESSING_PCT_CASH_REVENUE,
        s.PRICE_OFFERED_LOCAL_AMOUNT,
        s.AIR_VIP_PRICE,
        s.RETAIL_UNIT_PRICE,
        s.BUNDLE_PRICE_OFFERED_LOCAL_AMOUNT,
        s.PRODUCT_PRICE_HISTORY_KEY,
        s.BUNDLE_PRODUCT_PRICE_HISTORY_KEY,
        s.ITEM_PRICE_KEY,
        s.AMOUNT_TO_PAY,
        s.CASH_GROSS_REVENUE_LOCAL_AMOUNT,
        s.PRODUCT_GROSS_REVENUE_LOCAL_AMOUNT,
        s.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_LOCAL_AMOUNT,
        s.PRODUCT_MARGIN_PRE_RETURN_LOCAL_AMOUNT,
        s.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_LOCAL_AMOUNT,
        s.GROUP_KEY,
        s.LPN_CODE,
        s.CUSTOM_PRINTED_TEXT,
        s.REPORTING_LANDED_COST_LOCAL_AMOUNT,
        s.IS_ACTUAL_LANDED_COST,
        s.IS_FULLY_LANDED,
        s.FULLY_LANDED_CONVERSION_DATE,
        s.ACTUAL_LANDED_COST_LOCAL_AMOUNT,
        s.ACTUAL_PO_COST_LOCAL_AMOUNT,
        s.ACTUAL_CMT_COST_LOCAL_AMOUNT,
        s.ACTUAL_TARIFF_DUTY_COST_LOCAL_AMOUNT,
        s.ACTUAL_FREIGHT_COST_LOCAL_AMOUNT,
        s.ACTUAL_OTHER_COST_LOCAL_AMOUNT,
        s.META_CREATE_DATETIME,
        s.META_UPDATE_DATETIME,
        s.PRODUCT_DISCOUNT_AMOUNT,
        s.PRODUCT_SUBTOTAL_AMOUNT,
        s.PRODUCT_GROSS_REVENUE_AMOUNT,
        s.PRODUCT_GROSS_REVENUE_EXCL_SHIPPING_AMOUNT,
        s.PRODUCT_MARGIN_PRE_RETURN_AMOUNT,
        s.PRODUCT_MARGIN_PRE_RETURN_EXCL_SHIPPING_AMOUNT,
        s.TOKEN_AMOUNT,
        s.REPORTING_LANDED_COST_AMOUNT,
        s.SKU,
        s.PRODUCT_TYPE_NAME,
        s.CLEANSED_SIZE,
        s.PRODUCT_SKU,
        s.OUTFIT_PIECED_GOOD,
        s.MEMBERSHIP_ORDER_TYPE_L1,
        s.MEMBERSHIP_ORDER_TYPE_L2,
        s.MEMBERSHIP_ORDER_TYPE_L3,
        s.MEMBERSHIP_ORDER_TYPE_L4,
        s.ACTIVATION_KEY,
        s.MEMBERSHIP_EVENT_KEY,
        s.BOPS_PICKUP_LOCAL_DATETIME,
        s.BOPS_STORE_ID,
        s.PROMO_ORDER_OFFER,
        s.PROMO_ORDER_CATEGORY,
        s.PROMO_ORDER_PROMOCODE,
        s.PROMO_ORDER_FPL,
        s.PROMO_ORDER_DISCOUNT,
        s.PROMO_ORDER_PROMOID,
        s.PROMO_ORDER_NAME,
        s.PROMO_ITEM_OFFER,
        s.PROMO_ITEM_CATEGORY,
        s.PROMO_ITEM_PROMOCODE,
        s.PROMO_ITEM_FPL,
        s.PROMO_ITEM_DISCOUNT,
        s.PROMO_ITEM_PROMOID,
        s.PROMO_ITEM_NAME,
        s.IS_EXCLUSIVE_PRODUCT,
        s.IS_LEAD_ONLY_PRODUCT,
        s.IS_LAST_CHANCE_PRODUCT,
        s.IS_SALE_SECTION_PRODUCT,
        s.MEMBERSHIP_REWARD_TIER,
        s.VIP_DISCOUNT,
        s.NON_CASH_CREDIT_DISCOUNT,
        s.PRODUCT_DISCOUNT,
        s.BLENDED_DISCOUNT,
        s.SUBTOTAL_EXCL_TARIFF,
        s.TARIFF_REVENUE,
        s.BOUNCEBACK_ENDOWMENT_AMOUNT,
        s.VIP_ENDOWMENT_AMOUNT,
        s.DATETIME_MODIFIED
    );
