
SET end_date = CONVERT_TIMEZONE('America/Los_Angeles', CURRENT_TIMESTAMP)::DATE;
SET report_date = DATEADD(DAY, -1, $end_date);
SET report_month = DATE_TRUNC(MONTH,$report_date);
SET run_rate_multiplier = (
    SELECT DAY(LAST_DAY($report_date)) / DAY($report_date));
set data_refresh_datetime = CURRENT_TIMESTAMP();

CREATE OR REPLACE TRANSIENT TABLE REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST AS
SELECT
    CASE
        WHEN BU = 'FLNA-MVIP-OREV' THEN 'FLNA-MOVIP'
        WHEN BU = 'FLNA-FVIP-OREV' THEN 'FLNA-FOVIP'
        WHEN BU = 'FLNA-RREV' THEN 'FLNA-RVIP'
        WHEN BU = 'FLEU-FVIP-OREV' THEN 'FLEU-FVIP'
        WHEN BU = 'FLEU-MVIP-OREV' THEN 'FLEU-MVIP'
        WHEN BU = 'FLNA+RT' THEN 'FLNA'
        WHEN BU = 'YTNA-OREV' THEN 'YTNA'
        ELSE BU END as STORE,
    VERSION AS SEGMENT,
    FINANCIAL_DATE AS MONTH_DATE,
    MEDIA_SPEND,
    leads,
    M1_VIPS,
    TOTAL_NEW_VIPS AS VIPS,
    TOTAL_NEW_VIPS-M1_VIPS AS M2PLUS_VIPs,
    $data_refresh_datetime AS data_refresh_datetime
FROM EDW_PROD.REFERENCE.FINANCE_BUDGET_FORECAST
WHERE VERSION IN ('Forecast','Budget')
    AND BU IN ('SDNA', 'JFNA', 'FKNA', 'FLNA-MVIP-OREV', 'FLNA+RT', 'FLNA-FVIP-OREV', 'FLNA-RREV', 'FLEU-FVIP-OREV',
               'FLEU-MVIP-OREV', 'SXNA', 'SXEU', 'JFEU', 'YTNA-OREV')
    AND CURRENCY_TYPE = 'USDCurrFX'
    AND FINANCIAL_DATE >= '2020-11-01'
    AND FINANCIAL_DATE <= DATE_TRUNC(MONTH, CURRENT_DATE()::TIMESTAMP_LTZ)

UNION ALL

SELECT
    CASE
        WHEN STORE_BRAND = 'ShoeDazzle' THEN 'SDNA'
        WHEN STORE_BRAND = 'FabKids' THEN 'FKNA'
        WHEN STORE_BRAND = 'JustFab' AND STORE_REGION = 'NA' THEN 'JFNA'
        WHEN STORE_BRAND = 'JustFab' AND STORE_REGION = 'EU' THEN 'JFEU'
        WHEN STORE_BRAND = 'Savage X' AND STORE_REGION = 'NA' THEN 'SXNA'
        WHEN STORE_BRAND = 'Savage X' AND STORE_REGION = 'EU' THEN 'SXEU'
        WHEN STORE_BRAND = 'Yitty' AND STORE_REGION = 'NA' THEN 'YTNA'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='EU' AND IS_FL_MENS_FLAG = 1 THEN 'FLEU-MVIP'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='EU' AND IS_FL_MENS_FLAG = 0 THEN 'FLEU-FVIP'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='NA' AND IS_FL_MENS_FLAG = 0
            AND RETAIL_VIP = 0 THEN 'FLNA-FOVIP'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='NA' AND IS_FL_MENS_FLAG = 1
            AND RETAIL_VIP = 0 THEN 'FLNA-MOVIP'
        ELSE 'FLNA-RVIP' END AS STORE,
    'Actuals MTD' AS SEGMENT,
    DATE_TRUNC(MONTH, date) AS MONTH,
    SUM(TOTAL_SPEND) AS SPEND,
    SUM(primary_leads) AS LEADS,
    SUM(VIPS_FROM_LEADS_M1) AS M1VIPS,
    SUM(TOTAL_VIPS_ON_DATE) AS VIPS_ON_DATE,
    SUM(TOTAL_VIPS_ON_DATE - VIPS_FROM_LEADS_M1) AS M2PLUS_VIPS,
    $data_refresh_datetime AS data_refresh_datetime
from reporting_media_prod.attribution.daily_acquisition_metrics_cac
WHERE 1=1
    AND CURRENCY = 'USD'
    AND date >= '2018-11-01'
    AND date < $end_date
GROUP BY 1,2,3

UNION ALL

SELECT
    CASE
        WHEN STORE_BRAND = 'ShoeDazzle' THEN 'SDNA'
        WHEN STORE_BRAND = 'FabKids' THEN 'FKNA'
        WHEN STORE_BRAND = 'JustFab' AND STORE_REGION = 'NA' THEN 'JFNA'
        WHEN STORE_BRAND = 'JustFab' AND STORE_REGION = 'EU' THEN 'JFEU'
        WHEN STORE_BRAND = 'Savage X' AND STORE_REGION = 'NA' THEN 'SXNA'
        WHEN STORE_BRAND = 'Savage X' AND STORE_REGION = 'EU' THEN 'SXEU'
        WHEN STORE_BRAND = 'Yitty' AND STORE_REGION = 'NA' THEN 'YTNA'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='EU' AND IS_FL_MENS_FLAG = 1 THEN 'FLEU-MVIP'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='EU' AND IS_FL_MENS_FLAG = 0 THEN 'FLEU-FVIP'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='NA' AND IS_FL_MENS_FLAG = 0
            AND RETAIL_VIP = 0 THEN 'FLNA-FOVIP'
        WHEN STORE_BRAND = 'Fabletics' AND STORE_REGION ='NA' AND IS_FL_MENS_FLAG = 1
            AND RETAIL_VIP = 0 THEN 'FLNA-MOVIP'
        ELSE 'FLNA-RVIP' END AS STORE,
    'Actuals RunRate' AS SEGMENT,
    DATE_TRUNC(MONTH ,date) as MONTH,
    SUM(IFF(DATE_TRUNC(MONTH, date) = $report_month,
        TOTAL_SPEND * $run_rate_multiplier, TOTAL_SPEND)) AS SPEND,
    SUM(IFF(DATE_TRUNC(MONTH, date) = $report_month,
        primary_leads * $run_rate_multiplier, primary_leads)) AS LEADS,
    SUM(IFF(DATE_TRUNC(MONTH, date) = $report_month,
        VIPS_FROM_LEADS_M1 * $run_rate_multiplier, VIPS_FROM_LEADS_M1)) AS M1VIPS,
    SUM(IFF(DATE_TRUNC(MONTH, date) = $report_month,
        TOTAL_VIPS_ON_DATE * $run_rate_multiplier, TOTAL_VIPS_ON_DATE)) AS VIPS_ON_DATE,
    SUM(IFF(DATE_TRUNC(MONTH, date) = $report_month,
        (TOTAL_VIPS_ON_DATE - VIPS_FROM_LEADS_M1) * $run_rate_multiplier, TOTAL_VIPS_ON_DATE-VIPS_FROM_LEADS_M1)
        ) as AGED_CONVERSIOS,
    $data_refresh_datetime as data_refresh_datetime
from reporting_media_prod.attribution.daily_acquisition_metrics_cac
WHERE 1=1
    AND CURRENCY = 'USD'
    AND date >= '2018-11-01'
    AND date < $end_date
GROUP BY 1,2,3;

ALTER TABLE REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST SET DATA_RETENTION_TIME_IN_DAYS = 0;
INSERT INTO REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
SELECT
    'FLNA' AS store,
    segment,
    MONTH_DATE,
    SUM(MEDIA_SPEND) AS SPEND,
    SUM(LEADS) AS LEADS,
    SUM(M1_VIPS) AS M1_VIPS,
    SUM(VIPS) AS VIPS,
    SUM(M2PLUS_VIPs) AS M2PLUS_VIPS,
    MAX(data_refresh_datetime)
FROM REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
WHERE segment ILIKE '%actuals%'
    AND store IN ('FLNA-FOVIP', 'FLNA-MOVIP', 'FLNA-RVIP')
GROUP BY 1,2,3;

INSERT INTO REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
SELECT
    'FLEU' AS store,
    segment,
    MONTH_DATE,
    SUM(MEDIA_SPEND) AS SPEND,
    SUM(LEADS) AS LEADS,
    SUM(M1_VIPS) AS M1_VIPS,
    SUM(VIPS) AS VIPS,
    SUM(M2PLUS_VIPs) AS M2PLUS_VIPS,
    MAX(data_refresh_datetime)
FROM REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
WHERE segment ILIKE '%actuals%'
    AND store IN ('FLEU-FVIP', 'FLEU-MVIP')
GROUP BY 1,2,3;

/* insert in same month last year values */
INSERT INTO REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
SELECT
    bfly.store,
    'Same Month 1YR' AS segment,
    bf.MONTH_DATE, /* this year month date */
    SUM(bfly.MEDIA_SPEND) AS SPEND,
    SUM(bfly.LEADS) AS LEADS,
    SUM(bfly.M1_VIPS) AS M1_VIPS,
    SUM(bfly.VIPS) AS VIPS,
    SUM(bfly.M2PLUS_VIPs) AS M2PLUS_VIPS,
    MAX(bf.data_refresh_datetime)
FROM REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST AS bf
JOIN REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST AS bfly
    ON DATEADD(MONTH, -12, bf.MONTH_DATE) = bfly.MONTH_DATE
    AND bf.SEGMENT = bfly.SEGMENT
WHERE bf.segment = 'Actuals MTD'
GROUP BY 1,2,3;

/* insert in same month last year values */
INSERT INTO REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
SELECT
    bfly.store,
    'Same Month 2YR' as segment,
    bf.MONTH_DATE, -- this year month date
    SUM(bfly.MEDIA_SPEND) AS SPEND,
    SUM(bfly.LEADS) as LEADS,
    SUM(bfly.M1_VIPS) AS M1_VIPS,
    SUM(bfly.VIPS) AS VIPS,
    SUM(bfly.M2PLUS_VIPs) as M2PLUS_VIPS,
    max(bf.data_refresh_datetime)
FROM REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST AS bf
JOIN REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST AS bfly
    ON DATEADD(MONTH, -24, bf.MONTH_DATE) = bfly.MONTH_DATE
    AND bf.SEGMENT = bfly.SEGMENT
WHERE bf.segment = 'Actuals MTD'
GROUP BY 1,2,3;


DELETE FROM REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
WHERE MONTH_DATE < '2021-01-01';

/*
-- calculate:
-- Actuals MTD/RunRate - Budget/Forecast/Same Month 1Y/Same Month 2Y difference calculations
*/
INSERT INTO REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST
SELECT
    act.STORE,
    act.SEGMENT::STRING || ' - ' || bf.segment::STRING AS segment,
    bf.MONTH_DATE,
    COALESCE(act.MEDIA_SPEND, 0) - COALESCE(bf.MEDIA_SPEND, 0) AS SPEND,
    COALESCE(act.leads, 0) - COALESCE(bf.leads, 0) AS LEADS,
    COALESCE(act.M1_VIPs, 0) - COALESCE(bf.M1_VIPs, 0) AS  M1_VIPS,
    COALESCE(act.VIPS, 0) - COALESCE(bf.VIPS, 0) AS VIPS,
    COALESCE(act.M2PLUS_VIPs, 0) - COALESCE(bf.M2PLUS_VIPs, 0) AS M2PLUS_VIPS,
    act.data_refresh_datetime
FROM REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST AS act
LEFT JOIN REPORTING_BASE_PROD.SHARED.ACQ01_ACQUISITION_BUDGET_FORECAST AS bf
    ON bf.MONTH_DATE = act.MONTH_DATE
    AND act.STORE = bf.STORE
    AND bf.SEGMENT NOT ILIKE '%actuals%'
WHERE act.segment ILIKE '%actuals%';
