
CREATE OR REPLACE TEMP TABLE _session_refresh_base_stg AS
SELECT
    s.session_local_datetime,
    s.session_id,
    s.customer_id,
    visitor_id,
    s.store_id,
    store_brand,
    t.store_region,
    t.store_country,
    s.membership_state,
    daily_lead_tenure,
    monthly_vip_tenure,
    platform,
    browser,
    os,
    m.channel_type,
    m.channel,
    m.subchannel,
    smc.last_non_direct_media_channel,
    smc.last_non_direct_media_subchannel,
    m.utm_medium,
    m.utm_source,
    m.utm_campaign,
    utm_content,
    utm_term,
    ccode,
    s.dm_gateway_id,
    s.dm_site_id,
    s.dm_gateway_test_site_id,
    dg.gateway_code,
    dg.gateway_type,
    dg.gateway_sub_type,
    dg.gateway_name,
    dg.offer,
    dg.gender_featured,
    dg.ftv_or_rtv,
    dg.influencer_name,
    dg.experience_description,
    gateway_test_name,
    gateway_test_id,
    g.datetime_start AS gateway_test_start_local_datetime,
    g.datetime_end AS gateway_test_end_local_datetime,
    gateway_test_description,
    gateway_test_hypothesis,
    gateway_test_results,
    dgg.gateway_test_lp_traffic_split,
    gateway_test_lp_type,
    gateway_test_lp_class,
    gateway_test_lp_location,
    dms.label,
    is_yitty_gateway,
    is_scrubs_gateway,
    is_male_gateway,
    is_male_session_action,
    is_male_session,
    is_male_customer,
    is_skip_quiz_action,
    is_quiz_start_action,
    is_quiz_complete_action,
    is_quiz_registration_action,
    is_speedy_registration_action,
    is_skip_quiz_registration_action,
    is_lead_registration_action,
    is_atb_action,
    dc.how_did_you_hear AS hdyh,
    is_test_customer,
    is_bot,
    si.refresh_time AS refreshtime,
    s.is_scrubs_customer,
    s.is_scrubs_action,
    s.is_scrubs_session,
    NVL(s.is_in_segment, TRUE) as is_in_segment,
    s.user_segment
FROM shared.session AS s
JOIN shared.svm_session_ids_stg si
    ON si.session_id = s.session_id
JOIN edw_prod.data_model.dim_store AS t
    ON t.store_id = s.store_id
JOIN shared.media_source_channel_mapping AS m
    ON m.media_source_hash = s.media_source_hash
LEFT JOIN edw_prod.data_model.dim_customer AS dc
    ON dc.customer_id = s.customer_id
LEFT JOIN shared.dim_gateway dg
    ON dg.dm_gateway_id = s.dm_gateway_id
    AND dg.effective_start_datetime <= s.session_local_datetime
    AND dg.effective_end_datetime > s.session_local_datetime
LEFT JOIN lake_consolidated_view.ultra_merchant.dm_site dms
    ON dms.dm_site_id = s.dm_site_id --get start AND end date FROM here
LEFT JOIN lake_consolidated_view.ultra_merchant.dm_site_type dmst
    ON dmst.dm_site_type_id = dms.dm_site_type_id
LEFT JOIN shared.dim_gateway_test_site dgg
    ON dgg.dm_gateway_test_site_id = s.dm_gateway_test_site_id
    AND dgg.effective_start_datetime <= s.session_local_datetime
    AND dgg.effective_end_datetime > s.session_local_datetime
LEFT JOIN lake_consolidated_view.ultra_merchant.dm_gateway_test AS g
    ON g.dm_gateway_test_id = dgg.gateway_test_id
LEFT JOIN staging.session_media_channel smc
    ON s.session_id = smc.session_id
WHERE store_type <> 'Retail'
    AND is_test_customer_account = FALSE
    AND NVL(is_in_segment, TRUE) != FALSE
ORDER BY session_id ASC;

MERGE INTO shared.session_refresh_base AS T
    USING (
        SELECT
            session_local_datetime,
            session_id,
            customer_id,
            visitor_id,
            store_id,
            store_brand,
            store_region,
            store_country,
            membership_state,
            daily_lead_tenure,
            monthly_vip_tenure,
            platform,
            browser,
            os,
            channel_type,
            channel,
            subchannel,
            last_non_direct_media_channel,
            last_non_direct_media_subchannel,
            utm_medium,
            utm_source,
            utm_campaign,
            utm_content,
            utm_term,
            ccode,
            dm_gateway_id,
            dm_site_id,
            dm_gateway_test_site_id,
            gateway_code,
            gateway_type,
            gateway_sub_type,
            gateway_name,
            offer,
            gender_featured,
            ftv_or_rtv,
            influencer_name,
            experience_description,
            gateway_test_name,
            gateway_test_id,
            gateway_test_start_local_datetime,
            gateway_test_end_local_datetime,
            gateway_test_description,
            gateway_test_hypothesis,
            gateway_test_results,
            gateway_test_lp_traffic_split,
            gateway_test_lp_type,
            gateway_test_lp_class,
            gateway_test_lp_location,
            label,
            is_yitty_gateway,
            is_scrubs_gateway,
            is_male_gateway,
            is_male_session_action,
            is_male_session,
            is_male_customer,
            is_skip_quiz_action,
            is_quiz_start_action,
            is_quiz_complete_action,
            is_quiz_registration_action,
            is_speedy_registration_action,
            is_skip_quiz_registration_action,
            is_lead_registration_action,
            is_atb_action,
            hdyh,
            is_test_customer,
            is_bot,
            refreshtime,
            is_scrubs_customer,
            is_scrubs_action,
            is_scrubs_session,
            is_in_segment,
            user_segment
        FROM _session_refresh_base_stg
    ) AS SRC
    ON SRC.session_id = T.session_id
    WHEN MATCHED
        AND t.refreshtime < src.refreshtime THEN
        UPDATE SET
            t.session_local_datetime = src.session_local_datetime,
            t.customer_id = src.customer_id,
            t.visitor_id = src.visitor_id,
            t.store_id = src.store_id,
            t.store_brand = src.store_brand,
            t.store_region = src.store_region,
            t.store_country = src.store_country,
            t.membership_state = src.membership_state,
            t.daily_lead_tenure = src.daily_lead_tenure,
            t.monthly_vip_tenure = src.monthly_vip_tenure,
            t.platform = src.platform,
            t.browser = src.browser,
            t.os = src.os,
            t.channel_type = src.channel_type,
            t.channel = src.channel,
            t.subchannel = src.subchannel,
            t.last_non_direct_media_channel = src.last_non_direct_media_channel,
            t.last_non_direct_media_subchannel = src.last_non_direct_media_subchannel,
            t.utm_medium = src.utm_medium,
            t.utm_source = src.utm_source,
            t.utm_campaign = src.utm_campaign,
            t.utm_content = src.utm_content,
            t.utm_term = src.utm_term,
            t.ccode = src.ccode,
            t.dm_gateway_id = src.dm_gateway_id,
            t.dm_site_id = src.dm_site_id,
            t.dm_gateway_test_site_id = src.dm_gateway_test_site_id,
            t.gateway_code = src.gateway_code,
            t.gateway_type = src.gateway_type,
            t.gateway_sub_type = src.gateway_sub_type,
            t.gateway_name = src.gateway_name,
            t.offer = src.offer,
            t.gender_featured = src.gender_featured,
            t.ftv_or_rtv = src.ftv_or_rtv,
            t.influencer_name = src.influencer_name,
            t.experience_description = src.experience_description,
            t.gateway_test_name = src.gateway_test_name,
            t.gateway_test_id = src.gateway_test_id,
            t.gateway_test_start_local_datetime = src.gateway_test_start_local_datetime,
            t.gateway_test_end_local_datetime = src.gateway_test_end_local_datetime,
            t.gateway_test_description = src.gateway_test_description,
            t.gateway_test_hypothesis = src.gateway_test_hypothesis,
            t.gateway_test_results = src.gateway_test_results,
            t.gateway_test_lp_traffic_split = src.gateway_test_lp_traffic_split,
            t.gateway_test_lp_type = src.gateway_test_lp_type,
            t.gateway_test_lp_class = src.gateway_test_lp_class,
            t.gateway_test_lp_location = src.gateway_test_lp_location,
            t.label = src.label,
            t.is_yitty_gateway = src.is_yitty_gateway,
            t.is_scrubs_gateway = src.is_scrubs_gateway,
            t.is_male_gateway = src.is_male_gateway,
            t.is_male_session_action = src.is_male_session_action,
            t.is_male_session = src.is_male_session,
            t.is_male_customer = src.is_male_customer,
            t.is_skip_quiz_action = src.is_skip_quiz_action,
            t.is_quiz_start_action = src.is_quiz_start_action,
            t.is_quiz_complete_action = src.is_quiz_complete_action,
            t.is_quiz_registration_action = src.is_quiz_registration_action,
            t.is_speedy_registration_action = src.is_speedy_registration_action,
            t.is_skip_quiz_registration_action = src.is_skip_quiz_registration_action,
            t.is_lead_registration_action = src.is_lead_registration_action,
            t.is_atb_action = src.is_atb_action,
            t.hdyh = src.hdyh,
            t.is_test_customer = src.is_test_customer,
            t.is_bot = src.is_bot,
            t.refreshtime = src.refreshtime,
            t.is_scrubs_customer = src.is_scrubs_customer,
            t.is_scrubs_action = src.is_scrubs_action,
            t.is_scrubs_session = src.is_scrubs_session,
            t.is_in_segment = src.is_in_segment,
            t.user_segment = src.user_segment
        WHEN NOT MATCHED
            AND NOT (
                src.is_bot = TRUE
                OR NVL(src.is_in_segment, TRUE) = FALSE
                )
            THEN
        INSERT (
            session_local_datetime,
            session_id,
            customer_id,
            visitor_id,
            store_id,
            store_brand,
            store_region,
            store_country,
            membership_state,
            daily_lead_tenure,
            monthly_vip_tenure,
            platform,
            browser,
            os,
            channel_type,
            channel,
            subchannel,
            last_non_direct_media_channel,
            last_non_direct_media_subchannel,
            utm_medium,
            utm_source,
            utm_campaign,
            utm_content,
            utm_term,
            ccode,
            dm_gateway_id,
            dm_site_id,
            dm_gateway_test_site_id,
            gateway_code,
            gateway_type,
            gateway_sub_type,
            gateway_name,
            offer,
            gender_featured,
            ftv_or_rtv,
            influencer_name,
            experience_description,
            gateway_test_name,
            gateway_test_id,
            gateway_test_start_local_datetime,
            gateway_test_end_local_datetime,
            gateway_test_description,
            gateway_test_hypothesis,
            gateway_test_results,
            gateway_test_lp_traffic_split,
            gateway_test_lp_type,
            gateway_test_lp_class,
            gateway_test_lp_location,
            label,
            is_yitty_gateway,
            is_scrubs_gateway,
            is_male_gateway,
            is_male_session_action,
            is_male_session,
            is_male_customer,
            is_skip_quiz_action,
            is_quiz_start_action,
            is_quiz_complete_action,
            is_quiz_registration_action,
            is_speedy_registration_action,
            is_skip_quiz_registration_action,
            is_lead_registration_action,
            is_atb_action,
            hdyh,
            is_test_customer,
            is_bot,
            refreshtime,
            is_scrubs_customer,
            is_scrubs_action,
            is_scrubs_session,
            is_in_segment,
            user_segment
            )
        VALUES(
            src.session_local_datetime,
            src.session_id,
            src.customer_id,
            src.visitor_id,
            src.store_id,
            src.store_brand,
            src.store_region,
            src.store_country,
            src.membership_state,
            src.daily_lead_tenure,
            src.monthly_vip_tenure,
            src.platform,
            src.browser,
            src.os,
            src.channel_type,
            src.channel,
            src.subchannel,
            src.last_non_direct_media_channel,
            src.last_non_direct_media_subchannel,
            src.utm_medium,
            src.utm_source,
            src.utm_campaign,
            src.utm_content,
            src.utm_term,
            src.ccode,
            src.dm_gateway_id,
            src.dm_site_id,
            src.dm_gateway_test_site_id,
            src.gateway_code,
            src.gateway_type,
            src.gateway_sub_type,
            src.gateway_name,
            src.offer,
            src.gender_featured,
            src.ftv_or_rtv,
            src.influencer_name,
            src.experience_description,
            src.gateway_test_name,
            src.gateway_test_id,
            src.gateway_test_start_local_datetime,
            src.gateway_test_end_local_datetime,
            src.gateway_test_description,
            src.gateway_test_hypothesis,
            src.gateway_test_results,
            src.gateway_test_lp_traffic_split,
            src.gateway_test_lp_type,
            src.gateway_test_lp_class,
            src.gateway_test_lp_location,
            src.label,
            src.is_yitty_gateway,
            src.is_scrubs_gateway,
            src.is_male_gateway,
            src.is_male_session_action,
            src.is_male_session,
            src.is_male_customer,
            src.is_skip_quiz_action,
            src.is_quiz_start_action,
            src.is_quiz_complete_action,
            src.is_quiz_registration_action,
            src.is_speedy_registration_action,
            src.is_skip_quiz_registration_action,
            src.is_lead_registration_action,
            src.is_atb_action,
            src.hdyh,
            src.is_test_customer,
            src.is_bot,
            src.refreshtime,
            src.is_scrubs_customer,
            src.is_scrubs_action,
            src.is_scrubs_session,
            src.is_in_segment,
            src.user_segment
        );

/* Bot Cleanup */
DELETE FROM shared.session_refresh_base
WHERE is_bot = TRUE
    OR NVL(is_in_segment, TRUE) = FALSE;
