CREATE TRANSIENT TABLE IF NOT EXISTS shared.product_reviews
(
    store_brand VARCHAR,
    store_region VARCHAR,
    store_country VARCHAR,
    review_id NUMBER(38,0),
    customer_id NUMBER(38,0),
    review_template_name VARCHAR,
    review_hq_datetime TIMESTAMP_TZ(9),
    review_status VARCHAR,
    order_id NUMBER(38,0),
    order_line_id NUMBER(38,0),
    product_id NUMBER(38,0),
    review_text VARCHAR,
    comfort_review_text VARCHAR,
    plan_to_return_reason_review_text VARCHAR,
    style_review_text VARCHAR,
    size_fit_review_text VARCHAR,
    quality_value_review_text VARCHAR,
    shopping_experience_review_text VARCHAR,
    cs_experience_review_text VARCHAR,
    recommended_score NUMBER(38,0),
    return_score NUMBER(38,0),
    shopping_experience_score NUMBER(38,0),
    cs_shopping_experience_score NUMBER(38,0),
    nps_score NUMBER(38,0),
    style_score NUMBER(38,0),
    comfort_score NUMBER(38,0),
    quality_value_score NUMBER(38,0),
    size_fit_score NUMBER(38,0),
    overall_score NUMBER(38,0)
);
