CREATE OR REPLACE TABLE lake.amazon.selling_partner_merchant_listings (
    selling_partner_merchant_listings_key INT IDENTITY,
    market_place_id VARCHAR,
    item_name VARCHAR,
    item_description VARCHAR,
    listing_id VARCHAR,
    seller_sku VARCHAR,
    price NUMBER(19,4)   ,
    quantity INT,
    open_date VARCHAR,
    image_url VARCHAR,
    item_is_marketplace VARCHAR,
    product_id_type INT,
    zshop_shipping_fee NUMBER(19,4),
    item_note VARCHAR,
    item_condition VARCHAR,
    zshop_category1 VARCHAR,
    zshop_browse_path VARCHAR,
    zshop_storefront_feature VARCHAR,
    asin1 VARCHAR,
    asin2 VARCHAR,
    asin3 VARCHAR,
    will_ship_internationally VARCHAR,
    expedited_shipping VARCHAR,
    zshop_boldface VARCHAR,
    product_id VARCHAR,
    bid_for_featured_placement VARCHAR,
    add_delete VARCHAR,
    pending_quantity VARCHAR,
    fulfillment_channel VARCHAR,
    merchant_shipping_group VARCHAR,
    status VARCHAR,
    meta_type_1_hash INT,
    meta_type_2_hash INT,
    meta_from_datetime TIMESTAMP_LTZ,
    meta_to_datetime TIMESTAMP_LTZ,
    meta_is_current BOOLEAN,
    meta_create_datetime TIMESTAMP_LTZ,
    meta_update_datetime TIMESTAMP_LTZ,
    PRIMARY KEY (market_place_id, seller_sku, meta_from_datetime)
);
