CREATE or replace table lake.excel.landed_cost_budget (
    business_unit VARCHAR,
    gender VARCHAR,
    category VARCHAR,
    class VARCHAR,
    origin_country VARCHAR,
    destination_country VARCHAR,
    fc VARCHAR,
    po_incoterms VARCHAR,
    shipping_mode VARCHAR,
    budget_date DATE,
    primary_freight NUMBER(38,8),
    first_cost_rate NUMBER(38,8),
    duty_rate NUMBER(38,8),
    tariff_rate NUMBER(38,8),
    unit_volume NUMBER(38,8),
    total_budget_first_cost NUMBER(38,8),
    total_budget_primary_cost NUMBER(38,8),
    total_budget_duty_cost NUMBER(38,8),
    total_budget_tariff_cost NUMBER(38,8),
    meta_row_hash INT,
    meta_create_datetime TIMESTAMP_LTZ(3),
    meta_update_datetime TIMESTAMP_LTZ(3)
);
