CREATE TABLE IF NOT EXISTS lake_stg.gsc.booking_data_stg (
    so VARCHAR(255),
    po VARCHAR(255),
    style_color VARCHAR(255),
    vendor_booking_received_date DATE,
    cargo_ready_date DATE,
    cargo_receive_date DATE,
    fnd_eta DATE,
    revised_fnd_date DATE,
    dc_appointment_date DATE,
    gate_in_date DATE,
    pol_etd DATE,
    pod_eta DATE,
    pol VARCHAR(255),
    pod VARCHAR(255),
    fnd VARCHAR(255),
    traffic_mode VARCHAR(255),
    vol NUMBER(38,10),
    gwt NUMBER(38,10),
    units INT,
    pack INT,
    carrier_bkg_place_date DATE,
    carrier_bkg_confirm_date DATE,
    file_name VARCHAR(255),
    mixcarton_flag BOOLEAN,
    line_item_num INT
);


CREATE TABLE IF NOT EXISTS lake.gsc.booking_data (
    so VARCHAR(255),
    po VARCHAR(255),
    style_color VARCHAR(255),
    vendor_booking_received_date DATE,
    cargo_ready_date DATE,
    cargo_receive_date DATE,
    fnd_eta DATE,
    revised_fnd_date DATE,
    dc_appointment_date DATE,
    gate_in_date DATE,
    pol_etd DATE,
    pod_eta DATE,
    pol VARCHAR(255),
    pod VARCHAR(255),
    fnd VARCHAR(255),
    traffic_mode VARCHAR(255),
    vol NUMBER(38,10),
    gwt NUMBER(38,10),
    units INT,
    pack INT,
    carrier_bkg_place_date DATE,
    carrier_bkg_confirm_date DATE,
    file_name VARCHAR(255),
    meta_row_hash INT,
    meta_create_datetime TIMESTAMP_LTZ(3),
    meta_update_datetime TIMESTAMP_LTZ(3),
    mixcarton_flag BOOLEAN,
    line_item_num INT,
    PRIMARY KEY (so, po, style_color)
);
