CREATE TABLE IF NOT EXISTS lake.oracle_ebs.chargeback_us (
    source VARCHAR,
    gl_period VARCHAR,
    gl_account VARCHAR,
    settlement_date TIMESTAMP_NTZ,
    merchant_id VARCHAR,
    chargeback_amt NUMBER(38,2),
    order_id INT,
    order_date_placed TIMESTAMP_NTZ,
    shipping_country_code VARCHAR,
    store_id INT,
    store_credit_id INT,
    membership_token_id INT,
    membership_brand VARCHAR,
    receipt_number VARCHAR,
    receivables_trx_name VARCHAR,
    creation_date TIMESTAMP_NTZ,
    activity VARCHAR,
    reason_code VARCHAR,
    reason_description VARCHAR,
    cycle VARCHAR,
    merchant_grouping_id VARCHAR,
    issuing_bank VARCHAR,
    payment_type VARCHAR,
    meta_row_hash INT,
    meta_create_datetime TIMESTAMP_LTZ(3),
    meta_update_datetime TIMESTAMP_LTZ(3)
);
