CREATE TABLE IF NOT EXISTS lake.tiktok_shop.order_report
(
    shop_name                      VARCHAR,
    order_id                       VARCHAR,
    order_status                   VARCHAR,
    cancellation_or_return_type    VARCHAR,
    sku_quantity_of_return         NUMBER(1, 0),
    currency                       VARCHAR,
    original_shipping_fee          NUMBER(38, 4),
    original_total_product_price   NUMBER(38, 4),
    platform_discount              NUMBER(38, 4),
    product_tax                    NUMBER(38, 4),
    seller_discount                NUMBER(38, 4),
    shipping_fee                   NUMBER(38, 4),
    shipping_fee_platform_discount NUMBER(38, 4),
    shipping_fee_seller_discount   NUMBER(38, 4),
    shipping_fee_tax               NUMBER(38, 4),
    sub_total                      NUMBER(38, 4),
    tax                            NUMBER(38, 4),
    total_amount                   NUMBER(38, 4),
    order_refund_amount            NUMBER(38, 4),
    created_time_pst               TIMESTAMP_LTZ,
    paid_time_pst                  TIMESTAMP_LTZ,
    rts_time_pst                   TIMESTAMP_LTZ,
    shipped_time_pst               TIMESTAMP_LTZ,
    delivered_time_pst             TIMESTAMP_LTZ,
    cancelled_time_pst             TIMESTAMP_LTZ,
    cancel_by                      VARCHAR,
    cancel_reason                  VARCHAR,
    fulfillment_type               VARCHAR,
    tracking_id                    VARCHAR,
    delivery_option_type           VARCHAR,
    shipping_provider_name         VARCHAR,
    buyer_message                  VARCHAR,
    user_id                        VARCHAR,
    is_on_hold_order               BOOLEAN,
    is_replacement_order           BOOLEAN,
    is_sample_order                BOOLEAN,
    recipient                      VARCHAR,
    phone_number                   VARCHAR,
    country                        VARCHAR,
    state                          VARCHAR,
    city                           VARCHAR,
    zipcode                        VARCHAR,
    address_line1                  VARCHAR,
    address_line2                  VARCHAR,
    delivery_instruction           VARCHAR,
    payment_method                 VARCHAR,
    package_id                     VARCHAR,
    seller_note                    VARCHAR,
    shipping_information           VARCHAR,
    order_item_ids                 ARRAY,
    sku_ids                        ARRAY,
    seller_skus                    ARRAY,
    product_ids                    ARRAY,
    product_names                  ARRAY,
    variations                     ARRAY,
    quantity                       NUMBER(38, 0),
    meta_row_hash                  NUMBER(38, 0),
    meta_create_datetime           TIMESTAMP_LTZ,
    meta_update_datetime           TIMESTAMP_LTZ
);
