CREATE TABLE IF NOT EXISTS lake.tiktok_shop.order_line (
    shop_name                      VARCHAR,
	order_id                       VARCHAR,
    order_item_id                  VARCHAR,
	order_status                   VARCHAR,
	order_substatus                VARCHAR,
	cancellation_or_return_type    VARCHAR,
	normal_or_pre_order            VARCHAR,
	sku_id                         VARCHAR,
	seller_sku                     VARCHAR,
    product_id                     VARCHAR,
	product_name                   VARCHAR,
	variation                      VARCHAR,
	quantity                       NUMBER(1,0),
	sku_quantity_of_return         NUMBER(1,0),
	sku_unit_original_price        NUMBER(38, 4),
	sku_subtotal_before_discount   NUMBER(38, 4),
	sku_platform_discount          NUMBER(38, 4),
	sku_seller_discount            NUMBER(38, 4),
	sku_subtotal_after_discount    NUMBER(38, 4),
	taxes                          NUMBER(38, 4),
	created_time_pst               TIMESTAMP_LTZ,
	paid_time_pst                  TIMESTAMP_LTZ,
	rts_time_pst                   TIMESTAMP_LTZ,
	shipped_time_pst               TIMESTAMP_LTZ,
	delivered_time_pst             TIMESTAMP_LTZ,
	cancelled_time_pst             TIMESTAMP_LTZ,
	cancel_by                      VARCHAR,
	cancel_reason                  VARCHAR,
	fulfillment_type               VARCHAR,
	tracking_id                    VARCHAR,
	delivery_option_type           VARCHAR,
	shipping_provider_name         VARCHAR,
	buyer_message                  VARCHAR,
    user_id                        VARCHAR,
	recipient                      VARCHAR,
	phone_number                   VARCHAR,
	country                        VARCHAR,
	state                          VARCHAR,
	city                           VARCHAR,
	zipcode                        VARCHAR,
	address_line1                  VARCHAR,
	address_line2                  VARCHAR,
	delivery_instruction           VARCHAR,
	payment_method                 VARCHAR,
	package_id                     VARCHAR,
	seller_note                    VARCHAR,
	shipping_information           VARCHAR,
    meta_row_hash                  NUMBER(38, 0),
    meta_create_datetime           TIMESTAMP_LTZ,
    meta_update_datetime           TIMESTAMP_LTZ
);
