CREATE TABLE IF NOT EXISTS lake.tiktok_shop.refund_events_report (
    shop_name                     VARCHAR,
	return_order_id               VARCHAR,
    return_line_item_id           VARCHAR,
	order_id                      VARCHAR,
    order_line_item_id            VARCHAR,
	refund_total                  NUMBER(38, 4),
	sku_id                        VARCHAR,
	seller_sku                    VARCHAR,
	product_name                  VARCHAR,
	sku_name                      VARCHAR,
	return_type                   VARCHAR,
	created_time_pst              TIMESTAMP_LTZ,
    updated_time_pst              TIMESTAMP_LTZ,
	return_reason                 VARCHAR,
    return_reason_text            VARCHAR,
    refund_shipping_fee           NUMBER(38, 4),
    refund_tax                    NUMBER(38, 4),
    refund_subtotal               NUMBER(38, 4),
	return_quantity               NUMBER(1,0),
    return_status                 VARCHAR,
	return_logistics_tracking_id  VARCHAR,
    meta_row_hash                 NUMBER(38, 0),
    meta_create_datetime          TIMESTAMP_LTZ,
    meta_update_datetime          TIMESTAMP_LTZ
);
