CREATE OR REPLACE VIEW lake_view.jira.issue AS
SELECT id,
       key,
       parent_id,
       resolution,
       last_viewed,
       _original_estimate,
       issue_type,
       environment,
       remaining_estimate,
       _time_spent,
       work_ratio,
       reporter,
       updated,
       original_estimate,
       description,
       priority,
       created,
       assignee,
       due_date,
       status,
       _remaining_estimate,
       creator,
       time_spent,
       project,
       resolved,
       summary,
       _fivetran_deleted,
       CONVERT_TIMEZONE('America/Los_Angeles', _fivetran_synced) AS meta_create_datetime
FROM lake_fivetran.central_jira_cloud_v1.issue;
