CREATE OR REPLACE NOTIFICATION INTEGRATION EMAIL_NOTIFICATION_WH_QUEUEING
    TYPE=EMAIL
    ENABLED=TRUE
    ALLOWED_RECIPIENTS=('RPOORNIMA@TECHSTYLE.com','SAVANGALA@FABLETICS.com', 'RTANNEERU@TECHSTYLE.com');
