SET PROCESS_TO_DATE = DATE_TRUNC(MONTH, CURRENT_DATE);

CREATE OR REPLACE TEMPORARY TABLE _STORE AS
SELECT *
FROM EDW_PROD.DATA_MODEL.DIM_STORE ST
WHERE STORE_FULL_NAME NOT LIKE '%SWAG%'
  AND STORE_FULL_NAME NOT LIKE '%DM%'
  AND STORE_FULL_NAME NOT LIKE '%Sample Request%'
  AND STORE_FULL_NAME NOT LIKE '%Heels%'
  AND STORE_FULL_NAME NOT LIKE '%Wholesale%'
  AND STORE_FULL_NAME NOT LIKE '%Retail Replen%'
  AND STORE_BRAND NOT IN ('Not Applicable', 'Unknown');

CREATE OR REPLACE TRANSIENT TABLE _PS_ORDERS AS
SELECT ORDER_ID
FROM LAKE_CONSOLIDATED_VIEW.ULTRA_MERCHANT.ORDER_CLASSIFICATION
WHERE ORDER_TYPE_ID IN (25, 26); -- box subscription & box exchange)

ALTER TABLE _PS_ORDERS SET DATA_RETENTION_TIME_IN_DAYS = 0;

INSERT INTO _PS_ORDERS
SELECT O.RESHIP_ORDER_ID
FROM LAKE_CONSOLIDATED_VIEW.ULTRA_MERCHANT.RESHIP O
WHERE EXISTS(SELECT 1 FROM _PS_ORDERS PS WHERE PS.ORDER_ID = O.ORIGINAL_ORDER_ID);

CREATE OR REPLACE TRANSIENT TABLE month_end.shipping_revenue_detail AS
SELECT ST.STORE_BRAND || ' ' || ST.STORE_COUNTRY AS STORE,
       D.MONTH_DATE                              AS SHIPPED_MONTH,
       O.ORDER_ID,
       O.SHIPPING                                AS SHIPPING_AMT
FROM LAKE_CONSOLIDATED_VIEW.ULTRA_MERCHANT."ORDER" O
         JOIN _STORE ST ON ST.STORE_ID = O.STORE_ID
         JOIN EDW_PROD.DATA_MODEL.DIM_DATE D ON D.FULL_DATE = CAST(O.DATE_SHIPPED AS DATE)
    AND D.MONTH_DATE < $PROCESS_TO_DATE
WHERE NOT EXISTS(SELECT 1 FROM _PS_ORDERS PS WHERE PS.ORDER_ID = O.ORDER_ID)
  AND ST.STORE_NAME <> 'PS by JustFab';

ALTER TABLE month_end.shipping_revenue_detail SET DATA_RETENTION_TIME_IN_DAYS = 0;

INSERT INTO month_end.shipping_revenue_detail_SNAPSHOT
SELECT STORE
     , SHIPPED_MONTH
     , ORDER_ID
     , SHIPPING_AMT
     , CURRENT_TIMESTAMP AS SNAPSHOT_TIMESTAMP
FROM month_end.shipping_revenue_detail;

DELETE
FROM month_end.shipping_revenue_detail_snapshot
WHERE snapshot_timestamp < DATEADD(MONTH, -12, getdate());
