create or replace view lake_view.excel.FL_MERCH_OUTFITS_UBT_HIERARCHY(
            PRODUCT_SEGMENT,
            GENDER,
            OUTFIT_NUMBER,
            SHOWROOM_MONTH,
            GO_LIVE_DATE,
            NUMBER_OF_OUTFIT_COMPONENTS,
            US_OUTFIT_VIP_DOLLAR,
            EU_UK_VIPDOLLAR,
            INITIAL_LAUNCH,
            ADDITIONAL_INFORMATION,
            OUTFIT_COMPLEXION,
            SKU_NUMBER_1,
            DESCRIPTION_1_CURRENT_NAME,
            STYLE_COLOR_1,
            SKU_NUMBER_2,
            DESCRIPTION_2_CURRENT_NAME,
            STYLE_COLOR_2,
            SKU_NUMBER_3_REG_INSEAM,
            SKU_NUMBER_3_SHORT_INSEAM,
            SKU_NUMBER_3_TALL_INSEAM,
            INSEAM,
            DESCRIPTION_3_CURRENT_NAME,
            STYLE_COLOR_3,
            SKU_NUMBER_4,
            DESCRIPTION_4_CURRENT_NAME,
            STYLE_COLOR_4,
            SKU_NUMBER_5,
            DESCRIPTION_5_CURRENT_NAME,
            STYLE_COLOR_5,
            SKU_NUMBER_6,
            DESCRIPTION_6_CURRENT_NAME,
            STYLE_COLOR_6,
            SKU_NUMBER_7,
            DESCRIPTION_7_CURRENT_NAME,
            STYLE_COLOR_7,
            SKU_NUMBER_8,
            DESCRIPTION_8_CURRENT_NAME,
            STYLE_COLOR_8,
            OUTFIT_MSRP_DOLLAR,
            COMP_NUMBER_1_MSRP,
            COMP_NUMBER_2_MSRP,
            COMP_NUMBER_3_MSRP,
            COMP_NUMBER_4_MSRP,
            COMP_NUMBER_5_MSRP,
            COMP_NUMBER_6_MSRP,
            COMP_NUMBER_7_MSRP,
            COMP_NUMBER_8_MSRP,
            US_IMU,
            US_OUTFIT_COST_DOLLAR,
            US_TOP_COST_DOLLAR,
            US_BRA_JACKET_COST_DOLLAR,
            US_BOTTOM_COST_DOLLAR,
            US_COST_COMP_NUMBER_4,
            US_COST_COMP_NUMBER_5,
            US_COST_COMP_NUMBER_6,
            US_COST_COMP_NUMBER_7,
            US_COST_COMP_NUMBER_8,
            MX_IMU,
            MX_OUTFIT_COST_DOLLAR,
            MX_TOP_COST_DOLLAR,
            MX_BRA_JACKET_COST_DOLLAR,
            MX_BOTTOM_COST_DOLLAR,
            MX_COST_COMP_NUMBER_4,
            MX_COST_COMP_NUMBER_5,
            MX_COST_COMP_NUMBER_6,
            MX_COST_COMP_NUMBER_7,
            MX_COST_COMP_NUMBER_8,
            EU_IMU,
            EU_OUTFIT_COST_DOLLAR,
            EU_TOP_COST_DOLLAR,
            EU_BRA_JACKET_COST_DOLLAR,
            EU_BOTTOM_COST_DOLLAR,
            EU_COST_COMP_NUMBER_4,
            EU_COST_COMP_NUMBER_5,
            EU_COST_COMP_NUMBER_6,
            EU_COST_COMP_NUMBER_7,
            EU_COST_COMP_NUMBER_8,
            UK_IMU,
            UK_OUTFIT_COST_DOLLAR,
            UK_TOP_COST_DOLLAR,
            UK_BRA_JACKET_COST_DOLLAR,
            UK_BOTTOM_COST_DOLLAR,
            UK_COST_COMP_NUMBER_4,
            UK_COST_COMP_NUMBER_5,
            UK_COST_COMP_NUMBER_6,
            UK_COST_COMP_NUMBER_7,
            UK_COST_COMP_NUMBER_8,
            RTL_IMU,
            RTL_OUTFIT_COST_DOLLAR,
            RTL_TOP_COST_DOLLAR,
            RTL_BRA_JACKET_COST_DOLLAR,
            RTL_BOTTOM_COST_DOLLAR,
            RTL_COST_COMP_NUMBER_4,
            RTL_COST_COMP_NUMBER_5,
            RTL_COST_COMP_NUMBER_6,
            RTL_COST_COMP_NUMBER_7,
            RTL_COST_COMP_NUMBER_8,
            OUTFIT_IMAGE,
            SUB_BRAND,
            META_ROW_HASH,
            META_CREATE_DATETIME,
            META_UPDATE_DATETIME
) as
SELECT
            UPPER(product_segment) AS product_segment,
            UPPER(gender) AS gender,
            UPPER(outfit_number) AS outfit_number,
            UPPER(showroom_month) AS showroom_month,
            UPPER(go_live_date) AS go_live_date,
            number_of_outfit_components,
            us_outfit_vip_dollar,
            eu_uk_vipdollar,
            UPPER(initial_launch) AS initial_launch,
            UPPER(additional_information) AS additional_information,
            UPPER(outfit_complexion) AS outfit_complexion,
            UPPER(sku_number_1) AS sku_number_1,
            UPPER(description_1_current_name) AS description_1_current_name,
            UPPER(style_color_1) AS style_color_1,
            UPPER(sku_number_2) AS sku_number_2,
            UPPER(description_2_current_name) AS description_2_current_name,
            UPPER(style_color_2) AS style_color_2,
            UPPER(sku_number_3_reg_inseam) AS sku_number_3_reg_inseam,
            UPPER(sku_number_3_short_inseam) AS sku_number_3_short_inseam,
            UPPER(sku_number_3_tall_inseam) AS sku_number_3_tall_inseam,
            UPPER(inseam) AS inseam,
            UPPER(description_3_current_name) AS description_3_current_name,
            UPPER(style_color_3) AS style_color_3,
            UPPER(sku_number_4) AS sku_number_4,
            UPPER(description_4_current_name) AS description_4_current_name,
            UPPER(style_color_4) AS style_color_4,
            UPPER(sku_number_5) AS sku_number_5,
            UPPER(description_5_current_name) AS description_5_current_name,
            UPPER(style_color_5) AS style_color_5,
            UPPER(sku_number_6) AS sku_number_6,
            UPPER(description_6_current_name) AS description_6_current_name,
            UPPER(style_color_6) AS style_color_6,
            UPPER(sku_number_7) AS sku_number_7,
            UPPER(description_7_current_name) AS description_7_current_name,
            UPPER(style_color_7) AS style_color_7,
            UPPER(sku_number_8) AS sku_number_8,
            UPPER(description_8_current_name) AS description_8_current_name,
            UPPER(style_color_8) AS style_color_8,
            outfit_msrp_dollar,
            comp_number_1_msrp,
            comp_number_2_msrp,
            comp_number_3_msrp,
            comp_number_4_msrp,
            comp_number_5_msrp,
            comp_number_6_msrp,
            comp_number_7_msrp,
            comp_number_8_msrp,
            us_imu,
            us_outfit_cost_dollar,
            us_top_cost_dollar,
            us_bra_jacket_cost_dollar,
            us_bottom_cost_dollar,
            us_cost_comp_number_4,
            us_cost_comp_number_5,
            us_cost_comp_number_6,
            us_cost_comp_number_7,
            us_cost_comp_number_8,
            mx_imu,
            mx_outfit_cost_dollar,
            mx_top_cost_dollar,
            mx_bra_jacket_cost_dollar,
            mx_bottom_cost_dollar,
            mx_cost_comp_number_4,
            mx_cost_comp_number_5,
            mx_cost_comp_number_6,
            mx_cost_comp_number_7,
            mx_cost_comp_number_8,
            eu_imu,
            eu_outfit_cost_dollar,
            eu_top_cost_dollar,
            eu_bra_jacket_cost_dollar,
            eu_bottom_cost_dollar,
            eu_cost_comp_number_4,
            eu_cost_comp_number_5,
            eu_cost_comp_number_6,
            eu_cost_comp_number_7,
            eu_cost_comp_number_8,
            uk_imu,
            uk_outfit_cost_dollar,
            uk_top_cost_dollar,
            uk_bra_jacket_cost_dollar,
            uk_bottom_cost_dollar,
            uk_cost_comp_number_4,
            uk_cost_comp_number_5,
            uk_cost_comp_number_6,
            uk_cost_comp_number_7,
            uk_cost_comp_number_8,
            rtl_imu,
            rtl_outfit_cost_dollar,
            rtl_top_cost_dollar,
            rtl_bra_jacket_cost_dollar,
            rtl_bottom_cost_dollar,
            rtl_cost_comp_number_4,
            rtl_cost_comp_number_5,
            rtl_cost_comp_number_6,
            rtl_cost_comp_number_7,
            rtl_cost_comp_number_8,
            outfit_image,
            UPPER(sub_brand) AS sub_brand,
            meta_row_hash,
            meta_create_datetime,
            meta_update_datetime
FROM lake.excel.fl_merch_outfits_ubt_hierarchy;
