create or replace view lake_view.excel.FL_MERCH_ITEMS_UBT(
            PRODUCT_SEGMENT,
            STYLE_SKU,
            SKU,
            GENDER WITH TAG (UTIL.PUBLIC.PII_INFO_TAG='PII'),
            CATEGORY,
            CLASS,
            SUBCLASS,
            ORIGINAL_SHOWROOM_MONTH,
            CURRENT_SHOWROOM,
            MARKETING_STORY,
            GO_LIVE_DATE,
            ITEM_RANK,
            DESIGN_STYLE_NUMBER,
            CURRENT_NAME,
            COLOR,
            COLOR_FAMILY,
            BUY_TIMING,
            ITEM_STATUS,
            STYLE_STATUS,
            SKU_STATUS,
            INSEAMS_CONSTRUCTION,
            END_USE,
            ECO_SYSTEM,
            FIT_BLOCK,
            COLOR_APPLICATION,
            ECO_STYLE,
            FABRIC,
            FIT_STYLE,
            LINED_UNLINED,
            STYLE_PARENT,
            SIZE_SCALE,
            SIZE_RANGE,
            FACTORY,
            EDITORIAL_FEATURES,
            US_MSRP_DOLLAR,
            US_VIP_DOLLAR,
            US_TTL_BUY_UNITS,
            US_TTL_BLENDED_LDP_DOLLAR,
            US_BLENDED_VIP_IMU_PERCENT,
            US_BLENDED_LDP_DOLLAR,
            US_TTL_MSRP_DOLLAR,
            US_TTL_VIP_DOLLAR,
            MX_MSRP_DOLLAR,
            MX_VIP_DOLLAR,
            MX_TTL_BUY_UNITS,
            MX_TTL_BLENDED_LDP_DOLLAR,
            MX_BLENDED_VIP_IMU_PERCENT,
            MX_BLENDED_LDP_DOLLAR,
            MX_TTL_MSRP_DOLLAR,
            MX_TTL_VIP_DOLLAR,
            EU_MSRP_DOLLAR,
            EU_VIP_DOLLAR,
            EU_TTL_BUY_UNITS,
            EU_TTL_BLENDED_LDP_DOLLAR,
            EU_BLENDED_VIP_IMU_PERCENT,
            EU_BLENDED_LDP_DOLLAR,
            EU_TTL_MSRP_DOLLAR,
            EU_TTL_VIP_DOLLAR,
            UK_MSRP_DOLLAR,
            UK_VIP_DOLLAR,
            UK_TTL_BUY_UNITS,
            UK_TTL_BLENDED_LDP_DOLLAR,
            UK_BLENDED_VIP_IMU_PERCENT,
            UK_BLENDED_LDP_DOLLAR,
            UK_TTL_MSRP_DOLLAR,
            UK_TTL_VIP_DOLLAR,
            RTL_MSRP_DOLLAR,
            RTL_VIP_DOLLAR,
            RTL_TTL_BUY_UNITS,
            RTL_TTL_BLENDED_LDP_DOLLAR,
            RTL_BLENDED_VIP_IMU_PERCENT,
            RTL_BLENDED_LDP_DOLLAR,
            RTL_TTL_MSRP_DOLLAR,
            RTL_TTL_VIP_DOLLAR,
            CHANNEL,
            GLOBAL_TOTAL_UNITS,
            NA_TOTAL_UNITS,
            NA_BLENDED_LDP,
            EU_PLUS_UK_TOTAL_UNITS,
            EU_PLUS_UK_BLENDED_LDP,
            STYLE_COLOR,
            TALL_INSEAM,
            SHORT_INSEAM,
            IMAGE_URL,
            SUB_BRAND,
            META_ROW_HASH,
            META_CREATE_DATETIME,
            META_UPDATE_DATETIME
) as
SELECT
            UPPER(product_segment) AS product_segment,
            UPPER(style_sku) AS STYLE_SKU,
            UPPER(sku) AS sku,
            UPPER(gender) AS gender,
            UPPER(category) AS category,
            UPPER(class) AS class,
            UPPER(subclass) AS subclass,
            UPPER(original_showroom_month) AS original_showroom_month,
            current_showroom,
            UPPER(marketing_story) AS marketing_story,
            go_live_date,
            UPPER(item_rank) AS item_rank,
            UPPER(design_style_number) AS design_style_number,
            UPPER(current_name) AS current_name,
            UPPER(color) AS color,
            UPPER(color_family) AS color_family,
            UPPER(buy_timing) AS buy_timing,
            UPPER(item_status) AS item_status,
            UPPER(style_status) AS style_status,
            UPPER(sku_status) AS sku_status,
            UPPER(inseams_construction) AS inseams_construction,
            UPPER(end_use) AS end_use,
            UPPER(eco_system) AS eco_system,
            UPPER(fit_block) AS fit_block,
            UPPER(color_application) AS color_application,
            UPPER(eco_style) AS eco_style,
            UPPER(fabric) AS fabric,
            UPPER(fit_style) AS fit_style,
            UPPER(lined_unlined) AS lined_unlined,
            UPPER(style_parent) AS style_parent,
            UPPER(size_scale) AS size_scale,
            UPPER(size_range) AS size_range,
            UPPER(factory) AS factory,
            UPPER(editorial_features) AS editorial_features,
            us_msrp_dollar,
            us_vip_dollar,
            us_ttl_buy_units,
            us_ttl_blended_ldp_dollar,
            us_blended_vip_imu_percent,
            us_blended_ldp_dollar,
            us_ttl_msrp_dollar,
            us_ttl_vip_dollar,
            mx_msrp_dollar,
            mx_vip_dollar,
            mx_ttl_buy_units,
            mx_ttl_blended_ldp_dollar,
            mx_blended_vip_imu_percent,
            mx_blended_ldp_dollar,
            mx_ttl_msrp_dollar,
            mx_ttl_vip_dollar,
            eu_msrp_dollar,
            eu_vip_dollar,
            eu_ttl_buy_units,
            eu_ttl_blended_ldp_dollar,
            eu_blended_vip_imu_percent,
            eu_blended_ldp_dollar,
            eu_ttl_msrp_dollar,
            eu_ttl_vip_dollar,
            uk_msrp_dollar,
            uk_vip_dollar,
            uk_ttl_buy_units,
            uk_ttl_blended_ldp_dollar,
            uk_blended_vip_imu_percent,
            uk_blended_ldp_dollar,
            uk_ttl_msrp_dollar,
            uk_ttl_vip_dollar,
            rtl_msrp_dollar,
            rtl_vip_dollar,
            rtl_ttl_buy_units,
            rtl_ttl_blended_ldp_dollar,
            rtl_blended_vip_imu_percent,
            rtl_blended_ldp_dollar,
            rtl_ttl_msrp_dollar,
            rtl_ttl_vip_dollar,
            UPPER(channel) AS channel,
            global_total_units,
            na_total_units,
            na_blended_ldp,
            eu_plus_uk_total_units,
            eu_plus_uk_blended_ldp,
            UPPER(style_color) AS style_color,
            UPPER(tall_inseam) AS tall_inseam,
            UPPER(short_inseam) AS short_inseam,
            image_url,
            UPPER(sub_brand) AS sub_brand,
            meta_row_hash,
            meta_create_datetime,
            meta_update_datetime
FROM lake.excel.fl_merch_items_ubt;
