CREATE VIEW IF NOT EXISTS LAKE_VIEW.TIKTOK.DAILY_SPEND(
    AD_ID
    , AD_NAME
    , ADGROUP_ID
    , ADGROUP_NAME
    , CAMPAIGN_ID
    , ADVERTISER_ID
    , CAMPAIGN_NAME
    , CLICKS
    , PURCHASE_CLICK_1D
    , CTA_CONVERSION
    , IMPRESSIONS
    , VIP_CLICK_1D
    , ON_WEB_SUBSCRIBE
    , MEDIA_COST
    , LEAD_CLICK_1D
    , VIDEO_PLAY_ACTIONS
    , VIDEO_WATCHED_2S
    , VIDEO_WATCHED_6S
    , VTA_CONVERSION
    , DATE
    ,META_CREATE_DATETIME
	,META_UPDATE_DATETIME
) AS
	SELECT AD_ID
		,AD_NAME
		,ADGROUP_ID
		,ADGROUP_NAME
		,ds.CAMPAIGN_ID
		,ch.advertiser_id
		,CAMPAIGN_NAME
		,CLICKS
	    ,ON_WEB_ORDER
		,CTA_CONVERSION
		,IMPRESSIONS
		,COMPLETE_PAYMENT
		,ON_WEB_SUBSCRIBE
		,SPEND
		,USER_REGISTRATION
		,VIDEO_PLAY_ACTIONS
		,VIDEO_WATCHED_2_S
		,VIDEO_WATCHED_6_S
		,VTA_CONVERSION
		,STAT_TIME_DAY::date
	    ,convert_timezone('America/Los_Angeles',ds._FIVETRAN_SYNCED) AS META_CREATE_DATETIME
        ,convert_timezone('America/Los_Angeles',ds._FIVETRAN_SYNCED) AS META_UPDATE_DATETIME
	FROM lake_fivetran.MED_TIKTOK_V1.DAILY_SPEND ds
	LEFT JOIN (
		SELECT DISTINCT campaign_id
			,advertiser_id
		FROM lake_fivetran.MED_TIKTOK_V1.CAMPAIGN_History
		) ch ON ds.campaign_id = ch.campaign_id;
