CREATE OR REPLACE VIEW lake_view.amazon_selling_partner.competitive_price_type
            (
                        asin,
                        id,
                        landed_currency_code,
                        landed_amount,
                        listing_currency_code,
                        listing_amount,
                        shipping_currency_code,
                        shipping_amount,
                        points_number,
                        points_monetary_value_currency_code,
                        points_monetary_value_amount,
                        CONDITION,
                        subcondition,
                        offer_type,
                        quantity_tier,
                        quantity_discount_type,
                        seller_id,
                        belongs_to_requester,
                        meta_update_datetime
            )
            AS
SELECT asin,
       id,
       landed_currency_code,
       landed_amount,
       listing_currency_code,
       listing_amount,
       shipping_currency_code,
       shipping_amount,
       points_number,
       points_monetary_value_currency_code,
       points_monetary_value_amount,
       CONDITION,
       subcondition,
       offer_type,
       quantity_tier,
       quantity_discount_type,
       seller_id,
       belongs_to_requester,
       convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
FROM lake_fivetran.central_amazon_selling_partner_v1.competitive_price_type;
