CREATE OR REPLACE VIEW lake_view.amazon_selling_partner.item_dimension
            (
                        asin,
                        marketplace_id,
                        item_height_unit,
                        item_height_value,
                        item_length_unit,
                        item_length_value,
                        item_weight_unit,
                        item_weight_value,
                        item_width_unit,
                        item_width_value,
                        package_height_unit,
                        package_height_value,
                        package_length_unit,
                        package_length_value,
                        package_weight_unit,
                        package_weight_value,
                        package_width_unit,
                        package_width_value,
                        meta_update_datetime
            )
            AS
SELECT asin,
       marketplace_id,
       item_height_unit,
       item_height_value,
       item_length_unit,
       item_length_value,
       item_weight_unit,
       item_weight_value,
       item_width_unit,
       item_width_value,
       package_height_unit,
       package_height_value,
       package_length_unit,
       package_length_value,
       package_weight_unit,
       package_weight_value,
       package_width_unit,
       package_width_value,
       convert_timezone('America/Los_Angeles', _fivetran_synced) AS meta_update_datetime
FROM lake_fivetran.central_amazon_selling_partner_v1.item_dimension;
