import pendulum
from airflow.models import DAG

from include.airflow.callbacks.slack import slack_failure_gsc
from include.airflow.operators.excel_smb import ExcelSMBToS3Operator, SheetConfig
from include.airflow.operators.snowflake_load import SnowflakeTruncateAndLoadOperator
from include.config import conn_ids, email_lists, owners, s3_buckets, stages
from include.utils.snowflake import Column, CopyConfigCsv

main_sheets = [
    SheetConfig(
        sheet_name='Full Summary',
        schema='excel',
        table='gsc_factory_audit',
        header_rows=1,
        column_list=[
            Column("scheduled_audit_date", "DATE", uniqueness=True),
            Column("vendor", "STRING", uniqueness=True),
            Column("bu", "STRING", uniqueness=True),
            Column("country", "STRING", uniqueness=True),
            Column("official_factory_name", "STRING", uniqueness=True),
            Column("address", "STRING"),
            Column("phone_number", "STRING"),
            Column("auditor", "STRING"),
            Column("report_date", "DATE"),
            Column("report_number", "STRING"),
            Column("audit_number", "STRING"),
            Column("final_score", "NUMBER(38,0)"),
            Column("cap_issued", "STRING"),
            Column("cap_returned_date", "STRING"),
            Column("score_range", "STRING"),
            Column("supplier_factories_laws_and_regulations", "NUMBER(38,0)"),
            Column("child_labor", "NUMBER(38,0)"),
            Column("forced_labor", "NUMBER(38,0)"),
            Column("wages_and_benefits", "NUMBER(38,0)"),
            Column("working_hours", "NUMBER(38,0)"),
            Column("discrimination_and_womens_rights", "NUMBER(38,0)"),
            Column("disciplinary_practices", "NUMBER(38,0)"),
            Column("free_association", "NUMBER(38,0)"),
            Column("health_and_safety", "NUMBER(38,0)"),
            Column("environmental_safekeeping", "NUMBER(38,0)"),
            Column("factory_social_audit_document_review", "NUMBER(38,0)"),
            Column("factory_facilities_and_environment", "NUMBER(38,0)"),
            Column("quality_management_system", "NUMBER(38,0)"),
            Column("production_control", "NUMBER(38,0)"),
            Column("final_inspection", "NUMBER(38,0)"),
            Column("testing", "NUMBER(38,0)"),
            Column("factory_production_audit_document_review", "NUMBER(38,0)"),
            Column("audit_month", "INT"),
            Column("audit_quarter", "INT"),
            Column("audit_year", "INT"),
            Column("cap_month", "INT"),
            Column("cap_quarter", "INT"),
            Column("cap_year", "INT"),
            Column("cap_return_month", "INT"),
            Column("cap_return_quarter", "INT"),
            Column("cap_return_year", "INT"),
            Column("cap_status", "STRING"),
            Column("cap_severity", "STRING"),
            Column("primary_area_of_concern", "STRING"),
        ],
    ),
    SheetConfig(
        sheet_name='3rd Party Full Summary',
        schema='excel',
        table='gsc_factory_audit_3rd_party',
        header_rows=1,
        column_list=[
            Column("scheduled_audit_date", "DATE"),
            Column("vendor", "STRING"),
            Column("bu", "STRING"),
            Column("country", "STRING"),
            Column("factory_name", "STRING"),
            Column("address", "STRING"),
            Column("phone_number", "STRING"),
            Column("auditor", "STRING"),
            Column("report_number", "STRING"),
            Column("type", "STRING"),
            Column("audit_number", "STRING"),
            Column("final_score", "STRING"),
            Column("cap_issued", "DATE"),
            Column("cap_returned_date", "STRING"),
            Column("score_range", "STRING"),
            Column("supplier_factories_laws_and_regulations", "NUMBER(38,0)"),
            Column("child_labor", "NUMBER(38,0)"),
            Column("forced_labor", "NUMBER(38,0)"),
            Column("wages_and_benefits", "NUMBER(38,0)"),
            Column("working_hours", "NUMBER(38,0)"),
            Column("discrimination_and_womens_rights", "NUMBER(38,0)"),
            Column("disciplinary_practices", "NUMBER(38,0)"),
            Column("free_association", "NUMBER(38,0)"),
            Column("health_and_safety", "NUMBER(38,0)"),
            Column("environmental_safekeeping", "NUMBER(38,0)"),
            Column("audit_month", "INT"),
            Column("audit_quarter", "INT"),
            Column("audit_year", "INT"),
            Column("cap_month", "INT"),
            Column("cap_quarter", "INT"),
            Column("cap_year", "INT"),
            Column("cap_return_month", "INT"),
            Column("cap_return_quarter", "INT"),
            Column("cap_return_year", "INT"),
            Column("cap_status", "STRING"),
            Column("cap_severity", "STRING"),
            Column("primary_area_of_concern", "STRING"),
        ],
    ),
]

combo_sheet = SheetConfig(
    sheet_name='Full Summary',
    schema='excel',
    table='gsc_factory_audit_combined',
    header_rows=1,
    column_list=[
        Column("scheduled_audit_date", "DATE"),
        Column("vendor", "STRING"),
        Column("bu", "STRING"),
        Column("country", "STRING"),
        Column("official_factory_name", "STRING"),
        Column("address", "STRING"),
        Column("contact_info", "STRING"),
        Column("auditor", "STRING"),
        Column("report_number", "STRING"),
        Column("classification", "STRING"),
        Column("report_type", "STRING"),
        Column("final_score_org", "STRING"),
        Column("final_score", "NUMBER(38,2)"),
        Column("cap_issued", "DATE"),
        Column("cap_returned_date", "DATE"),
        Column("score_range", "STRING"),
        Column("supplier_factories_laws_and_regulations", "NUMBER(38,4)"),
        Column("child_labor", "NUMBER(38,4)"),
        Column("forced_labor", "NUMBER(38,4)"),
        Column("wages_and_benefits", "NUMBER(38,4)"),
        Column("working_hours", "NUMBER(38,4)"),
        Column("discrimination_and_womens_rights", "NUMBER(38,4)"),
        Column("disciplinary_practices", "NUMBER(38,4)"),
        Column("free_association", "NUMBER(38,4)"),
        Column("health_and_safety", "NUMBER(38,4)"),
        Column("environmental_safekeeping", "NUMBER(38,4)"),
        Column("factory_social_audit_document_review", "NUMBER(38,4)"),
        Column("factory_facilities_and_environment", "NUMBER(38,2)"),
        Column("quality_management_system", "NUMBER(38,2)"),
        Column("production_control", "NUMBER(38,2)"),
        Column("final_inspection", "NUMBER(38,2)"),
        Column("testing", "NUMBER(38,2)"),
        Column("factory_production_audit_document_review", "NUMBER(38,4)"),
        Column("audit_month", "INT"),
        Column("audit_quarter", "INT"),
        Column("audit_year", "INT"),
        Column("cap_month", "INT"),
        Column("cap_quarter", "INT"),
        Column("cap_year", "INT"),
        Column("cap_return_month", "INT"),
        Column("cap_return_quarter", "INT"),
        Column("cap_return_year", "INT"),
        Column("cap_status", "STRING"),
        Column("cap_severity", "STRING"),
        Column("primary_area_of_concern", "STRING"),
    ],
)

default_args = {
    'start_date': pendulum.datetime(2020, 3, 1, tz='America/Los_Angeles'),
    'retries': 1,
    'owner': owners.data_integrations,
    'email': email_lists.data_integration_support,
    'on_failure_callback': slack_failure_gsc,
}


dag = DAG(
    dag_id="global_apps_inbound_vendor_profile_factory_audit",
    default_args=default_args,
    schedule="0 1 * * *",
    catchup=False,
    max_active_tasks=10,
    max_active_runs=1,
)
with dag:
    to_s3 = ExcelSMBToS3Operator(
        task_id='excel_to_s3_new',
        smb_path='Inbound/airflow.vendor_compliance/Factory Audit/Vendor Data Source/'
        'New/SE_FactoryAudit_Dashboard_Main_Combo V2.xlsx',
        share_name='BI',
        bucket=s3_buckets.tsos_da_int_inbound,
        s3_conn_id=conn_ids.S3.tsos_da_int_prod,
        smb_conn_id=conn_ids.SMB.nas01,
        sheet_configs=[combo_sheet],
        default_schema_version='v2',
    )

    to_snowflake = SnowflakeTruncateAndLoadOperator(
        task_id=f"{combo_sheet.schema}.{combo_sheet.table}.load_to_snowflake",
        files_path=f"{stages.tsos_da_int_inbound}/lake/{combo_sheet.schema}.{combo_sheet.table}/v2/"
        f"se_factoryaudit_dashboard_main_combo v2-{str(combo_sheet.sheet_name).lower()}.csv.gz",
        database='lake',
        staging_database='lake_stg',
        schema=combo_sheet.schema,
        table=combo_sheet.table,
        column_list=combo_sheet.column_list,
        initial_load=True,
        copy_config=CopyConfigCsv(
            field_delimiter='|',
            record_delimiter='\n',
            header_rows=combo_sheet.header_rows,
            null_if="'',' '",
        ),
    )
    to_s3 >> to_snowflake
