create or replace view LAKE_VIEW.SNAPCHAT.PIXEL_DATA_1DAY(
	START_TIME,
	END_TIME,
	SWIPE_UP_ATTRIBUTION_WINDOW,
	VIEW_ATTRIBUTION_WINDOW,
	AD_ID,
	IMPRESSIONS,
	SWIPES,
	QUARTILE_1,
	QUARTILE_2,
	QUARTILE_3,
	VIEW_COMPLETION,
	SPEND,
	VIEW_TIME_MILLS,
	VIDEO_VIEWS,
	CONVERSION_PURCHASES_SWIPE_UP,
	CONVERSION_PURCHASES_VIEW,
	CONVERSION_SIGN_UPS_SWIPE_UP,
	CONVERSION_SIGN_UPS_VIEW,
	SCREEN_TIME_MILLIS,
	META_CREATE_DATETIME,
	META_UPDATE_DATETIME
) as
select convert_timezone('America/Los_Angeles',date) AS START_TIME
,dateadd('day',1,convert_timezone('America/Los_Angeles',date)) AS END_TIME
,'1_DAY' as SWIPE_UP_ATTRIBUTION_WINDOW
,'1_DAY' as VIEW_ATTRIBUTION_WINDOW
, adp.ad_id
,IMPRESSIONS
,SWIPES
,QUARTILE_1
,QUARTILE_2
,QUARTILE_3
,VIEW_COMPLETION
,SPEND
,VIEW_TIME_MILLIS as VIEW_TIME_MILLS
,VIDEO_VIEWS
,CONVERSION_PURCHASES_SWIPE_UP
,CONVERSION_PURCHASES_VIEW
,CONVERSION_SIGN_UPS_SWIPE_UP
,CONVERSION_SIGN_UPS_VIEW
,SCREEN_TIME_MILLIS
,convert_timezone('America/Los_Angeles',adp._FIVETRAN_SYNCED) AS META_CREATE_DATETIME
,convert_timezone('America/Los_Angeles',adp._FIVETRAN_SYNCED) AS META_UPDATE_DATETIME
from lake_fivetran.MED_SNAPCHAT_AD1_V1.AD_DAILY_REPORT adp;
