CREATE OR REPLACE TABLE lake_history.workday.employee_history_last6months (
    employee_id VARCHAR NOT NULL,
    first_name VARCHAR WITH MASKING POLICY LAKE.PUBLIC.DEFAULT_MASK,
    last_name VARCHAR WITH MASKING POLICY LAKE.PUBLIC.DEFAULT_MASK,
    preferred_first_name VARCHAR WITH MASKING POLICY LAKE.PUBLIC.DEFAULT_MASK,
    preferred_last_name VARCHAR WITH MASKING POLICY LAKE.PUBLIC.DEFAULT_MASK,
    business_title VARCHAR,
    worker_title VARCHAR,
    status VARCHAR,
    manager VARCHAR WITH MASKING POLICY LAKE.PUBLIC.DEFAULT_MASK,
    company VARCHAR,
    brand VARCHAR,
    cost_center VARCHAR,
    email VARCHAR NOT NULL WITH MASKING POLICY LAKE.PUBLIC.DEFAULT_MASK,
    start_date DATE NOT NULL,
    termination_date DATE,
    location VARCHAR,
    mgmlevel01 VARCHAR,
    mgmlevel02 VARCHAR,
    mgmlevel03 VARCHAR,
    mgmlevel04 VARCHAR,
    mgmlevel05 VARCHAR,
    mgmlevel06 VARCHAR,
    mgmlevel07 VARCHAR,
    created_at TIMESTAMP_LTZ(3),
    updated_at TIMESTAMP_LTZ(3),
    source_meta_create_datetime TIMESTAMP_LTZ(3),
    source_meta_update_datetime TIMESTAMP_LTZ(3),
	source_meta_row_hash NUMBER(38,0),
    meta_create_datetime TIMESTAMP_LTZ(3),
    meta_update_datetime TIMESTAMP_LTZ(3)
);
