CREATE TABLE IF NOT EXISTS analytics_base.acquisition_media_spend_daily_agg
(
    date_object                        VARCHAR(6),
    date                               DATE,
    currency_object                    VARCHAR(16777216),
    currency_type                      VARCHAR(16777216),
    event_store_id                     NUMBER(38, 0),
    vip_store_id                       NUMBER(38, 0),
    is_retail_vip                      BOOLEAN,
    customer_gender                    VARCHAR(10),
    is_cross_promo                     BOOLEAN,
    finance_specialty_store            VARCHAR(20),
    membership_order_type_l1           VARCHAR(14),
    membership_order_type_l2           VARCHAR(14),
    membership_order_type_l3           VARCHAR(14),
    leads                              NUMBER(18, 0),
    reactivated_leads                  NUMBER(18, 0),
    new_vips                           NUMBER(18, 0),
    reactivated_vips                   NUMBER(18, 0),
    vips_from_reactivated_leads_m1     NUMBER(18, 0),
    paid_vips                          NUMBER(18, 0),
    unpaid_vips                        NUMBER(18, 0),
    new_vips_m1                        NUMBER(18, 0),
    paid_vips_m1                       NUMBER(18, 0),
    cancels                            NUMBER(18, 0),
    m1_cancels                         NUMBER(18, 0),
    bop_vips                           NUMBER(18, 0),
    media_spend                        NUMBER(38, 10),
    meta_create_datetime               TIMESTAMP_LTZ(3),
    meta_update_datetime               TIMESTAMP_LTZ(3),
    meta_row_hash                      NUMBER(19, 0),
    primary_leads                      NUMBER(18, 0),
    vip_from_leads_30min               NUMBER(18, 0),
    vip_from_leads_2h                  NUMBER(18, 0),
    vip_from_leads_24h                 NUMBER(18, 0),
    vip_from_reactivated_leads_30min   NUMBER(18, 0),
    vip_from_reactivated_leads_2h      NUMBER(18, 0),
    vip_from_reactivated_leads_24h     NUMBER(18, 0),
    vip_from_leads_d1                  NUMBER(18, 0),
    vip_from_leads_d2                  NUMBER(18, 0),
    vip_from_leads_d3                  NUMBER(18, 0),
    vip_from_leads_d4                  NUMBER(18, 0),
    vip_from_leads_d5                  NUMBER(18, 0),
    vip_from_leads_d6                  NUMBER(18, 0),
    vip_from_leads_d7                  NUMBER(18, 0),
    vip_from_leads_d8_d30              NUMBER(18, 0),
    vip_from_leads_m1                  NUMBER(18, 0),
    vip_from_leads_m2                  NUMBER(18, 0),
    vip_from_leads_m3                  NUMBER(18, 0),
    vip_from_leads_m4                  NUMBER(18, 0),
    vip_from_leads_m5                  NUMBER(18, 0),
    vip_from_leads_m6                  NUMBER(18, 0),
    vip_from_leads_m7                  NUMBER(18, 0),
    vip_from_leads_m8                  NUMBER(18, 0),
    vip_from_leads_m9                  NUMBER(18, 0),
    vip_from_leads_m10                 NUMBER(18, 0),
    vip_from_leads_m11                 NUMBER(18, 0),
    vip_from_leads_m12                 NUMBER(18, 0),
    retail_vips                        NUMBER(18, 0),
    varsity_vips                       NUMBER(18, 0),
    vips_from_reactivated_leads        NUMBER(18, 0),
    new_vips_d1                        NUMBER(18, 0),
    new_vips_d2                        NUMBER(18, 0),
    new_vips_d3                        NUMBER(18, 0),
    new_vips_d4                        NUMBER(18, 0),
    new_vips_d5                        NUMBER(18, 0),
    new_vips_d6                        NUMBER(18, 0),
    new_vips_d7                        NUMBER(18, 0),
    new_vips_d2_d7                     NUMBER(18, 0),
    new_vips_d1_d7                     NUMBER(18, 0),
    new_vips_d8_d30                    NUMBER(18, 0),
    new_vips_d31_d89                   NUMBER(18, 0),
    new_vips_d8_d90                    NUMBER(18, 0),
    new_vips_d90plus                   NUMBER(18, 0),
    new_vips_m2                        NUMBER(18, 0),
    new_vips_m3                        NUMBER(18, 0),
    new_vips_m4                        NUMBER(18, 0),
    new_vips_m5                        NUMBER(18, 0),
    new_vips_m6                        NUMBER(18, 0),
    new_vips_m7                        NUMBER(18, 0),
    new_vips_m8                        NUMBER(18, 0),
    new_vips_m9                        NUMBER(18, 0),
    new_vips_m10                       NUMBER(18, 0),
    new_vips_m11                       NUMBER(18, 0),
    new_vips_m12                       NUMBER(18, 0),
    new_vips_m13plus                   NUMBER(18, 0),
    passive_cancel                     NUMBER(18, 0),
    d1_cancels                         NUMBER(18, 0),
    m2_cancels                         NUMBER(18, 0),
    m3_cancels                         NUMBER(18, 0),
    m4_m12_cancels                     NUMBER(18, 0),
    m13plus_cancels                    NUMBER(18, 0),
    secondary_leads                    NUMBER(18, 0),
    is_retail_registration             BOOLEAN,
    is_scrubs_customer                 BOOLEAN,
    registration_channel               VARCHAR(16777216),
    how_did_you_hear                   VARCHAR(16777216),
    registration_subchannel            VARCHAR(16777216),
    vip_from_reactivated_leads_d1      NUMBER(18, 0),
    vip_from_reactivated_leads_d2      NUMBER(18, 0),
    vip_from_reactivated_leads_d3      NUMBER(18, 0),
    vip_from_reactivated_leads_d4      NUMBER(18, 0),
    vip_from_reactivated_leads_d5      NUMBER(18, 0),
    vip_from_reactivated_leads_d6      NUMBER(18, 0),
    vip_from_reactivated_leads_d7      NUMBER(18, 0),
    vip_from_reactivated_leads_d8_d30  NUMBER(18, 0),
    vip_from_reactivated_leads_m1      NUMBER(18, 0),
    vip_from_reactivated_leads_m2      NUMBER(18, 0),
    vip_from_reactivated_leads_m3      NUMBER(18, 0),
    vip_from_reactivated_leads_m4      NUMBER(18, 0),
    vip_from_reactivated_leads_m5      NUMBER(18, 0),
    vip_from_reactivated_leads_m6      NUMBER(18, 0),
    vip_from_reactivated_leads_m7      NUMBER(18, 0),
    vip_from_reactivated_leads_m8      NUMBER(18, 0),
    vip_from_reactivated_leads_m9      NUMBER(18, 0),
    vip_from_reactivated_leads_m10     NUMBER(18, 0),
    vip_from_reactivated_leads_m11     NUMBER(18, 0),
    vip_from_reactivated_leads_m12     NUMBER(18, 0),
    new_vips_m1_reactivated_leads      NUMBER(18, 0),
    new_vips_d1_reactivated_leads      NUMBER(18, 0),
    new_vips_d2_reactivated_leads      NUMBER(18, 0),
    new_vips_d3_reactivated_leads      NUMBER(18, 0),
    new_vips_d4_reactivated_leads      NUMBER(18, 0),
    new_vips_d5_reactivated_leads      NUMBER(18, 0),
    new_vips_d6_reactivated_leads      NUMBER(18, 0),
    new_vips_d7_reactivated_leads      NUMBER(18, 0),
    new_vips_d2_d7_reactivated_leads   NUMBER(18, 0),
    new_vips_d1_d7_reactivated_leads   NUMBER(18, 0),
    new_vips_d8_d30_reactivated_leads  NUMBER(18, 0),
    new_vips_d31_d89_reactivated_leads NUMBER(18, 0),
    new_vips_d8_d90_reactivated_leads  NUMBER(18, 0),
    new_vips_d90plus_reactivated_leads NUMBER(18, 0),
    new_vips_m2_reactivated_leads      NUMBER(18, 0),
    new_vips_m3_reactivated_leads      NUMBER(18, 0),
    new_vips_m4_reactivated_leads      NUMBER(18, 0),
    new_vips_m5_reactivated_leads      NUMBER(18, 0),
    new_vips_m6_reactivated_leads      NUMBER(18, 0),
    new_vips_m7_reactivated_leads      NUMBER(18, 0),
    new_vips_m8_reactivated_leads      NUMBER(18, 0),
    new_vips_m9_reactivated_leads      NUMBER(18, 0),
    new_vips_m10_reactivated_leads     NUMBER(18, 0),
    new_vips_m11_reactivated_leads     NUMBER(18, 0),
    new_vips_m12_reactivated_leads     NUMBER(18, 0),
    new_vips_m13plus_reactivated_leads NUMBER(18, 0)
);
