-- DROP TABLE IF EXISTS analytics_base.customer_lifetime_value_monthly_agg;

CREATE TABLE analytics_base.customer_lifetime_value_monthly_agg (
    month_date DATE,
    customer_id NUMBER(38,0),
    activation_key NUMBER(38,0),
    vip_store_id NUMBER(38,0),
    product_order_count NUMBER(38,0),
    online_product_order_count NUMBER(38,0),
    retail_product_order_count NUMBER(38,0),
    mobile_app_product_order_count NUMBER(38,0),
    product_order_unit_count NUMBER(38,0),
    online_product_order_unit_count NUMBER(38,0),
    retail_product_order_unit_count NUMBER(38,0),
    mobile_app_product_order_unit_count NUMBER(38,0),
    product_order_subtotal_excl_tariff_amount NUMBER(38,10),
    product_order_product_subtotal_amount NUMBER(38,10),
    online_product_order_subtotal_excl_tariff_amount NUMBER(38,10),
    retail_product_order_subtotal_excl_tariff_amount NUMBER(38,10),
    mobile_app_product_order_subtotal_excl_tariff_amount NUMBER(38,10),
    product_order_product_discount_amount NUMBER(38,10),
    online_product_order_product_discount_amount NUMBER(38,10),
    retail_product_order_product_discount_amount NUMBER(38,10),
    mobile_app_product_order_product_discount_amount NUMBER(38,10),
    product_order_shipping_revenue_amount NUMBER(38,10),
    online_product_order_shipping_revenue_amount NUMBER(38,10),
    retail_product_order_shipping_revenue_amount NUMBER(38,10),
    mobile_app_product_order_shipping_revenue_amount NUMBER(38,10),
    product_order_direct_cogs_amount NUMBER(38,10),
    online_product_order_direct_cogs_amount NUMBER(38,10),
    retail_product_order_direct_cogs_amount NUMBER(38,10),
    mobile_app_product_order_direct_cogs_amount NUMBER(38,10),
    product_order_selling_expenses_amount NUMBER(38,10),
    online_product_order_selling_expenses_amount NUMBER(38,10),
    retail_product_order_selling_expenses_amount NUMBER(38,10),
    mobile_app_product_order_selling_expenses_amount NUMBER(38,10),
    product_order_cash_refund_amount_and_chargeback_amount NUMBER(38,10),
    online_product_order_cash_refund_chargeback_amount NUMBER(38,10),
    retail_product_order_cash_refund_chargeback_amount NUMBER(38,10),
    mobile_app_product_order_cash_refund_chargeback_amount NUMBER(38,10),
    product_order_cash_credit_refund_amount NUMBER(38,10),
    online_product_order_cash_credit_refund_amount NUMBER(38,10),
    retail_product_order_cash_credit_refund_amount NUMBER(38,10),
    mobile_app_product_order_cash_credit_refund_amount NUMBER(38,10),
    product_order_reship_exchange_order_count NUMBER(38,0),
    online_product_order_reship_exchange_order_count NUMBER(38,0),
    retail_product_order_reship_exchange_order_count NUMBER(38,0),
    mobile_app_product_order_reship_exchange_order_count NUMBER(38,0),
    product_order_reship_exchange_unit_count NUMBER(38,0),
    online_product_order_reship_exchange_unit_count NUMBER(38,0),
    retail_product_order_reship_exchange_unit_count NUMBER(38,0),
    mobile_app_product_order_reship_exchange_unit_count NUMBER(38,0),
    product_order_reship_exchange_direct_cogs_amount NUMBER(38,10),
    online_product_order_reship_exchange_direct_cogs_amount NUMBER(38,10),
    retail_product_order_reship_exchange_direct_cogs_amount NUMBER(38,10),
    mobile_app_product_order_reship_exchange_direct_cogs_amount NUMBER(38,10),
    product_order_return_cogs_amount NUMBER(38,10),
    online_product_order_return_cogs_amount NUMBER(38,10),
    retail_product_order_return_cogs_amount NUMBER(38,10),
    mobile_app_product_order_return_cogs_amount NUMBER(38,10),
    product_order_return_unit_count NUMBER(38,0),
    online_product_order_return_unit_count NUMBER(38,0),
    retail_product_order_return_unit_count NUMBER(38,0),
    mobile_app_product_order_return_unit_count NUMBER(38,0),
    product_order_amount_to_pay NUMBER(38,10),
    online_product_order_amount_to_pay NUMBER(38,10),
    retail_product_order_amount_to_pay NUMBER(38,10),
    mobile_app_product_order_amount_to_pay NUMBER(38,10),
    product_gross_revenue_excl_shipping NUMBER(38,10),
    online_product_gross_revenue_excl_shipping NUMBER(38,10),
    retail_product_gross_revenue_excl_shipping NUMBER(38,10),
    mobile_app_product_gross_revenue_excl_shipping NUMBER(38,10),
    product_gross_revenue NUMBER(38,10),
    online_product_gross_revenue NUMBER(38,10),
    retail_product_gross_revenue NUMBER(38,10),
    mobile_app_product_gross_revenue NUMBER(38,10),
    product_net_revenue NUMBER(38,10),
    online_product_net_revenue NUMBER(38,10),
    retail_product_net_revenue NUMBER(38,10),
    mobile_app_product_net_revenue NUMBER(38,10),
    product_margin_pre_return NUMBER(38,10),
    online_product_margin_pre_return NUMBER(38,10),
    retail_product_margin_pre_return NUMBER(38,10),
    mobile_app_product_margin_pre_return NUMBER(38,10),
    product_margin_pre_return_excl_shipping NUMBER(38,10),
    online_product_margin_pre_return_excl_shipping NUMBER(38,10),
    retail_product_margin_pre_return_excl_shipping NUMBER(38,10),
    mobile_app_product_margin_pre_return_excl_shipping NUMBER(38,10),
    product_gross_profit NUMBER(38,10),
    online_product_gross_profit NUMBER(38,10),
    retail_product_gross_profit NUMBER(38,10),
    mobile_app_product_gross_profit NUMBER(38,10),
    product_variable_contribution_profit NUMBER(38,10),
    online_product_variable_contribution_profit NUMBER(38,10),
    retail_product_variable_contribution_profit NUMBER(38,10),
    mobile_app_product_variable_contribution_profit NUMBER(38,10),
    product_order_cash_gross_revenue_amount NUMBER(38,10),
    online_product_order_cash_gross_revenue_amount NUMBER(38,10),
    retail_product_order_cash_gross_revenue_amount NUMBER(38,10),
    mobile_app_product_order_cash_gross_revenue_amount NUMBER(38,10),
    product_order_cash_net_revenue NUMBER(38,10),
    online_product_order_cash_net_revenue NUMBER(38,10),
    retail_product_order_cash_net_revenue NUMBER(38,10),
    mobile_app_product_order_cash_net_revenue NUMBER(38,10),
    product_order_landed_product_cost_amount NUMBER(38,10),
    online_product_order_landed_product_cost_amount NUMBER(38,10),
    retail_product_order_landed_product_cost_amount NUMBER(38,10),
    mobile_app_product_order_landed_product_cost_amount NUMBER(38,10),
    product_order_cash_margin_pre_return NUMBER(38,10),
    online_product_order_cash_margin_pre_return NUMBER(38,10),
    retail_product_order_cash_margin_pre_return NUMBER(38,10),
    mobile_app_product_order_cash_margin_pre_return NUMBER(38,10),
    product_order_cash_gross_profit NUMBER(38,10),
    online_product_order_cash_gross_profit NUMBER(38,10),
    retail_product_order_cash_gross_profit NUMBER(38,10),
    mobile_app_product_order_cash_gross_profit NUMBER(38,10),
    billing_cash_gross_revenue NUMBER(38,10),
    billing_cash_net_revenue NUMBER(38,10),
    cash_gross_revenue NUMBER(38,10),
    cash_net_revenue NUMBER(38,10),
    cash_gross_profit NUMBER(38,10),
    cash_variable_contribution_profit NUMBER(38,10),
    monthly_billed_credit_cash_transaction_amount NUMBER(38,10),
    membership_fee_cash_transaction_amount NUMBER(38,10),
    gift_card_transaction_amount NUMBER(38,10),
    legacy_credit_cash_transaction_amount NUMBER(38,10),
    monthly_billed_credit_cash_refund_count NUMBER(38,0),
    monthly_billed_credit_cash_refund_chargeback_amount NUMBER(38,10),
    membership_fee_cash_refund_chargeback_amount NUMBER(38,10),
    gift_card_cash_refund_chargeback_amount NUMBER(38,10),
    legacy_credit_cash_refund_chargeback_amount NUMBER(38,10),
    billed_cash_credit_issued_amount NUMBER(38,10),
    billed_cash_credit_redeemed_amount NUMBER(38,10),
    online_billed_cash_credit_redeemed_amount NUMBER(38,10),
    retail_billed_cash_credit_redeemed_amount NUMBER(38,10),
    mobile_billed_cash_credit_redeemed_amount NUMBER(38,10),
    billed_cash_credit_cancelled_amount NUMBER(38,10),
    billed_cash_credit_expired_amount NUMBER(38,10),
    billed_cash_credit_issued_equivalent_count NUMBER(38,10),
    billed_cash_credit_redeemed_same_month_amount NUMBER(38,10),
    billed_cash_credit_redeemed_equivalent_count NUMBER(38,10),
    billed_cash_credit_cancelled_equivalent_count NUMBER(38,10),
    billed_cash_credit_expired_equivalent_count NUMBER(38,10),
    refund_cash_credit_issued_amount NUMBER(38,10),
    refund_cash_credit_redeemed_amount NUMBER(38,10),
    refund_cash_credit_cancelled_amount NUMBER(38,10),
    refund_cash_credit_expired_amount NUMBER(38,10),
    other_cash_credit_issued_amount NUMBER(38,10),
    other_cash_credit_redeemed_amount NUMBER(38,10),
    other_cash_credit_cancelled_amount NUMBER(38,10),
    other_cash_credit_expired_amount NUMBER(38,10),
    noncash_credit_issued_amount NUMBER(38,10),
    noncash_credit_cancelled_amount NUMBER(38,10),
    noncash_credit_expired_amount NUMBER(38,10),
    first_guest_product_margin_pre_return NUMBER(38,10),
    meta_row_hash NUMBER(19,0),
    meta_create_datetime TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(3),
    meta_update_datetime TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (month_date, customer_id, activation_key,vip_store_id),
    FOREIGN KEY (customer_id) REFERENCES stg.dim_customer (customer_id),
    FOREIGN KEY (vip_store_id) REFERENCES stg.dim_store (store_id)
) CLUSTER BY (month_date);

GRANT OWNERSHIP ON TABLE analytics_base.customer_lifetime_value_monthly_agg TO ROLE __EDW_ANALYTICS_BASE_RWC COPY CURRENT GRANTS;

-- ALTER TABLE analytics_base.customer_lifetime_value_monthly_agg ADD COLUMN guest_cohort_month_date DATE;

/*
-- Insert unknown record
INSERT INTO analytics_base.customer_lifetime_value_monthly_agg (month_date, customer_id, activation_key, meta_create_datetime, meta_update_datetime)
SELECT '1900-01-01' AS month_date, -1 AS customer_id, -1 AS activation_key, CURRENT_TIMESTAMP AS meta_create_datetime, CURRENT_TIMESTAMP AS meta_update_datetime
WHERE NOT EXISTS (SELECT TRUE AS is_exists FROM analytics_base.customer_lifetime_value_monthly_agg WHERE month_date = '1900-01-01' AND customer_id = -1 AND activation_key = -1);

-- Update unknown record
UPDATE analytics_base.customer_lifetime_value_monthly_agg
SET
    --month_date = '1900-01-01',
    --customer_id = -1,
    --activation_key = -1,
    product_order_count = 0,
    online_product_order_count = 0,
    retail_product_order_count = 0,
    mobile_app_product_order_count = 0,
    product_order_unit_count = 0,
    online_product_order_unit_count = 0,
    retail_product_order_unit_count = 0,
    mobile_app_product_order_unit_count = 0,
    product_order_subtotal_excl_tariff_amount = 0,
    product_order_product_subtotal_amount = 0,
    online_product_order_subtotal_excl_tariff_amount = 0,
    retail_product_order_subtotal_excl_tariff_amount = 0,
    mobile_app_product_order_subtotal_excl_tariff_amount = 0,
    product_order_product_discount_amount = 0,
    online_product_order_product_discount_amount = 0,
    retail_product_order_product_discount_amount = 0,
    mobile_app_product_order_product_discount_amount = 0,
    product_order_shipping_revenue_amount = 0,
    online_product_order_shipping_revenue_amount = 0,
    retail_product_order_shipping_revenue_amount = 0,
    mobile_app_product_order_shipping_revenue_amount = 0,
    product_order_direct_cogs_amount = 0,
    online_product_order_direct_cogs_amount = 0,
    retail_product_order_direct_cogs_amount = 0,
    mobile_app_product_order_direct_cogs_amount = 0,
    product_order_selling_expenses_amount = 0,
    online_product_order_selling_expenses_amount = 0,
    retail_product_order_selling_expenses_amount = 0,
    mobile_app_product_order_selling_expenses_amount = 0,
    product_order_cash_refund_amount_and_chargeback_amount = 0,
    online_product_order_cash_refund_chargeback_amount = 0,
    retail_product_order_cash_refund_chargeback_amount = 0,
    mobile_app_product_order_cash_refund_chargeback_amount = 0,
    product_order_cash_credit_refund_amount = 0,
    online_product_order_cash_credit_refund_amount = 0,
    retail_product_order_cash_credit_refund_amount = 0,
    mobile_app_product_order_cash_credit_refund_amount = 0,
    product_order_reship_exchange_order_count = 0,
    online_product_order_reship_exchange_order_count = 0,
    retail_product_order_reship_exchange_order_count = 0,
    mobile_app_product_order_reship_exchange_order_count = 0,
    product_order_reship_exchange_unit_count = 0,
    online_product_order_reship_exchange_unit_count = 0,
    retail_product_order_reship_exchange_unit_count = 0,
    mobile_app_product_order_reship_exchange_unit_count = 0,
    product_order_reship_exchange_direct_cogs_amount = 0,
    online_product_order_reship_exchange_direct_cogs_amount = 0,
    retail_product_order_reship_exchange_direct_cogs_amount = 0,
    mobile_app_product_order_reship_exchange_direct_cogs_amount = 0,
    product_order_return_cogs_amount = 0,
    online_product_order_return_cogs_amount = 0,
    retail_product_order_return_cogs_amount = 0,
    mobile_app_product_order_return_cogs_amount = 0,
    product_order_return_unit_count = 0,
    online_product_order_return_unit_count = 0,
    retail_product_order_return_unit_count = 0,
    mobile_app_product_order_return_unit_count = 0,
    product_order_amount_to_pay = 0,
    online_product_order_amount_to_pay = 0,
    retail_product_order_amount_to_pay = 0,
    mobile_app_product_order_amount_to_pay = 0,
    product_gross_revenue_excl_shipping = 0,
    online_product_gross_revenue_excl_shipping = 0,
    retail_product_gross_revenue_excl_shipping = 0,
    mobile_app_product_gross_revenue_excl_shipping = 0,
    product_gross_revenue = 0,
    online_product_gross_revenue = 0,
    retail_product_gross_revenue = 0,
    mobile_app_product_gross_revenue = 0,
    product_net_revenue = 0,
    online_product_net_revenue = 0,
    retail_product_net_revenue = 0,
    mobile_app_product_net_revenue = 0,
    product_margin_pre_return = 0,
    online_product_margin_pre_return = 0,
    retail_product_margin_pre_return = 0,
    mobile_app_product_margin_pre_return = 0,
    product_margin_pre_return_excl_shipping = 0,
    online_product_margin_pre_return_excl_shipping = 0,
    retail_product_margin_pre_return_excl_shipping = 0,
    mobile_app_product_margin_pre_return_excl_shipping = 0,
    product_gross_profit = 0,
    online_product_gross_profit = 0,
    retail_product_gross_profit = 0,
    mobile_app_product_gross_profit = 0,
    product_variable_contribution_profit = 0,
    online_product_variable_contribution_profit = 0,
    retail_product_variable_contribution_profit = 0,
    mobile_app_product_variable_contribution_profit = 0,
    product_order_cash_gross_revenue_amount = 0,
    online_product_order_cash_gross_revenue_amount = 0,
    retail_product_order_cash_gross_revenue_amount = 0,
    mobile_app_product_order_cash_gross_revenue_amount = 0,
    product_order_cash_net_revenue = 0,
    online_product_order_cash_net_revenue = 0,
    retail_product_order_cash_net_revenue = 0,
    mobile_app_product_order_cash_net_revenue = 0,
    product_order_landed_product_cost_amount = 0,
    online_product_order_landed_product_cost_amount = 0,
    retail_product_order_landed_product_cost_amount = 0,
    mobile_app_product_order_landed_product_cost_amount = 0,
    product_order_cash_margin_pre_return = 0,
    online_product_order_cash_margin_pre_return = 0,
    retail_product_order_cash_margin_pre_return = 0,
    mobile_app_product_order_cash_margin_pre_return = 0,
    product_order_cash_gross_profit = 0,
    online_product_order_cash_gross_profit = 0,
    retail_product_order_cash_gross_profit = 0,
    mobile_app_product_order_cash_gross_profit = 0,
    billing_cash_gross_revenue = 0,
    billing_cash_net_revenue = 0,
    cash_gross_revenue = 0,
    cash_net_revenue = 0,
    cash_gross_profit = 0,
    cash_variable_contribution_profit = 0,
    monthly_billed_credit_cash_transaction_amount = 0,
    membership_fee_cash_transaction_amount = 0,
    gift_card_transaction_amount = 0,
    legacy_credit_cash_transaction_amount = 0,
    monthly_billed_credit_cash_refund_count = 0,
    monthly_billed_credit_cash_refund_chargeback_amount = 0,
    membership_fee_cash_refund_chargeback_amount = 0,
    gift_card_cash_refund_chargeback_amount = 0,
    legacy_credit_cash_refund_chargeback_amount = 0,
    billed_cash_credit_issued_amount = 0,
    billed_cash_credit_redeemed_amount = 0,
    online_billed_cash_credit_redeemed_amount = 0,
    retail_billed_cash_credit_redeemed_amount = 0,
    mobile_billed_cash_credit_redeemed_amount = 0,
    billed_cash_credit_cancelled_amount = 0,
    billed_cash_credit_expired_amount = 0,
    billed_cash_credit_issued_equivalent_count = 0,
    billed_cash_credit_redeemed_same_month_amount = 0,
    billed_cash_credit_redeemed_equivalent_count = 0,
    billed_cash_credit_cancelled_equivalent_count = 0,
    billed_cash_credit_expired_equivalent_count = 0,
    refund_cash_credit_issued_amount = 0,
    refund_cash_credit_redeemed_amount = 0,
    refund_cash_credit_cancelled_amount = 0,
    refund_cash_credit_expired_amount = 0,
    other_cash_credit_issued_amount = 0,
    other_cash_credit_redeemed_amount = 0,
    other_cash_credit_cancelled_amount = 0,
    other_cash_credit_expired_amount = 0,
    noncash_credit_issued_amount = 0,
    noncash_credit_cancelled_amount = 0,
    noncash_credit_expired_amount = 0,
    first_guest_product_margin_pre_return = 0
WHERE month_date = '1900-01-01' AND customer_id = -1 AND activation_key = -1;
*/
