CREATE TABLE IF NOT EXISTS analytics_base.order_line_ext_stg (
    object_type VARCHAR(100),
    order_line_id NUMBER(38, 0),
    meta_original_order_line_id NUMBER(38,0),
    order_id NUMBER(38, 0),
    original_order_id NUMBER(38, 0),
    placed_date DATE,
    order_completion_date DATE,
    order_shipped_date DATE,
    reship_placed_date DATE,
    exchange_placed_date DATE,
    return_date DATE,
    order_status VARCHAR(100),
    order_line_status VARCHAR(100),
    store_id NUMBER(38, 0),
    store_name VARCHAR(500),
    store_full_name VARCHAR(1000),
    store_brand VARCHAR(500),
    store_type VARCHAR(100),
    store_region VARCHAR(100),
    store_country VARCHAR(100),
    fulfillment_warehouse_id NUMBER(38, 0),
    warehouse_code VARCHAR(100),
    warehouse_name VARCHAR(100),
    warehouse_type VARCHAR(100),
    carrier_service VARCHAR(500),
    pickup_store_id NUMBER(38, 0),
    product_id NUMBER(38, 0),
    master_product_id NUMBER(38, 0),
    sku VARCHAR(100),
    product_sku VARCHAR(100),
    base_sku VARCHAR(100),
    product_name VARCHAR(500),
    bundle_product_id NUMBER(38, 0),
    bundle_alias VARCHAR(100),
    is_byo_component BOOLEAN,
    is_bundle_component BOOLEAN,
    is_pre_made_set BOOLEAN,
    is_vip_box BOOLEAN,
    is_free BOOLEAN,
    color VARCHAR(100),
    size VARCHAR(100),
    product_gender VARCHAR(50),
    membership_order_type_l1 VARCHAR(100),
    membership_order_type_l2 VARCHAR(100),
    membership_order_type_l3 VARCHAR(100),
    order_sales_channel_l1 VARCHAR(100),
    order_sales_channel_l2 VARCHAR(100),
    order_classification_l1 VARCHAR(100),
    is_retail_ship_only_order BOOLEAN,
    is_bops_order BOOLEAN,
    customer_id NUMBER(38, 0),
    customer_gender VARCHAR(50),
    is_cross_promo BOOLEAN,
    finance_specialty_store VARCHAR(100),
    price_sold_as_type VARCHAR(100),
    first_item_vip_price NUMBER(38, 4),
    current_item_vip_price NUMBER(38, 4),
    item_vip_price NUMBER(38, 4),
    item_retail_price NUMBER(38, 4),
    non_reduced_vip_price NUMBER(38, 4),
    unit_count NUMBER(38, 0),
    reship_unit_count NUMBER(38, 0),
    exchange_unit_count NUMBER(38, 0),
    finalsales_quantity NUMBER(38, 0),
    token_count NUMBER(38, 0),
    subtotal_excl_tariff NUMBER(38, 4),
    tariff_revenue NUMBER(38, 4),
    token_subtotal NUMBER(38, 4),
    product_gross_revenue_excl_shipping NUMBER(38, 4),
    product_margin_pre_return_excl_shipping NUMBER(38, 4),
    product_cost NUMBER(38, 4),
    reship_product_cost NUMBER(38, 4),
    exchange_product_cost NUMBER(38, 4),
    token_product_cost NUMBER(38, 4),
    product_discount NUMBER(38, 4),
    token_discount NUMBER(38, 4),
    return_unit_count NUMBER(38, 0),
    return_product_gross_revenue_excl_shipping NUMBER(38, 4),
    return_product_cost_returned_resalable NUMBER(38, 4),
    meta_row_hash NUMBER(38, 0),
    meta_create_datetime TIMESTAMP_LTZ(3),
    meta_update_datetime TIMESTAMP_LTZ(3),
    is_deleted boolean DEFAULT FALSE
    );

ALTER TABLE analytics_base.order_line_ext ADD PRIMARY KEY (object_type, order_line_id);

ALTER TABLE analytics_base.order_line_ext ADD COLUMN order_processing_status VARCHAR(100);

