CREATE TABLE IF NOT EXISTS analytics_base.sales_returns_agg(
	date DATE,
	date_type VARCHAR(30),
	store_id NUMBER(38,0),
	store_name VARCHAR(250),
	store_brand VARCHAR(100),
	store_type VARCHAR(30),
	region VARCHAR(50),
	country VARCHAR(100),
    finance_specialty_store VARCHAR(20),
	sku VARCHAR(100),
	product_sku VARCHAR(50),
	base_sku VARCHAR(50),
	is_retail BOOLEAN,
	is_sold_as_part_of_bundle BOOLEAN,
	bundle_name VARCHAR(200),
	bundle_alias VARCHAR(200),
	membership_order_type_l2 VARCHAR(100),
	unit_count NUMBER(38,0),
	product_order_subtotal NUMBER(38,4),
	product_order_discount NUMBER(38,4),
	product_order_gross_revenue_excl_shipping NUMBER(38,4),
	product_order_margin_pre_return_excl_shipping NUMBER(38,4),
	product_cost NUMBER(38,4),
    product_cost_c NUMBER(38,4),
	non_reduced_vip_price NUMBER(38, 4),
	return_unit_count NUMBER(38,0),
	returned_product_gross_rev_excluding_shipping NUMBER(38,4),
	meta_create_datetime TIMESTAMP_LTZ(3),
	meta_update_datetime TIMESTAMP_LTZ(3)
);
