-- DROP TABLE IF EXISTS analytics_base.customer_lifetime_value_ltd;

CREATE TABLE analytics_base.customer_lifetime_value_ltd (
    customer_id NUMBER(38),
    meta_original_customer_id NUMBER(38,0),
    store_id NUMBER(38),
    vip_store_id NUMBER(38),
    vip_cohort_month_date DATE,
    guest_cohort_month_date DATE,
    activation_key NUMBER(38),
    first_activation_key NUMBER(38),
    is_reactivated_vip BOOLEAN,
    membership_type VARCHAR(75),
    gender VARCHAR(16),
    is_scrubs_customer BOOLEAN,
    product_order_count NUMBER(38),
    online_product_order_count NUMBER(38),
    retail_product_order_count NUMBER(38),
    mobile_app_product_order_count NUMBER(38),
    product_order_unit_count NUMBER(38),
    online_product_order_unit_count NUMBER(38),
    retail_product_order_unit_count NUMBER(38),
    mobile_app_product_order_unit_count NUMBER(38),
    product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    online_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    retail_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    mobile_app_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    product_order_product_discount_amount NUMBER(38, 10),
    online_product_order_product_discount_amount NUMBER(38, 10),
    retail_product_order_product_discount_amount NUMBER(38, 10),
    mobile_app_product_order_product_discount_amount NUMBER(38, 10),
    product_order_shipping_revenue_amount NUMBER(38, 10),
    online_product_order_shipping_revenue_amount NUMBER(38, 10),
    retail_product_order_shipping_revenue_amount NUMBER(38, 10),
    mobile_app_product_order_shipping_revenue_amount NUMBER(38, 10),
    product_order_direct_cogs_amount NUMBER(38, 10),
    online_product_order_direct_cogs_amount NUMBER(38, 10),
    retail_product_order_direct_cogs_amount NUMBER(38, 10),
    mobile_app_product_order_direct_cogs_amount NUMBER(38, 10),
    product_order_selling_expenses_amount NUMBER(38, 10),
    online_product_order_selling_expenses_amount NUMBER(38, 10),
    retail_product_order_selling_expenses_amount NUMBER(38, 10),
    mobile_app_product_order_selling_expenses_amount NUMBER(38, 10),
    product_order_cash_refund_amount_and_chargeback_amount NUMBER(38, 10),
    online_product_order_cash_refund_chargeback_amount NUMBER(38, 10),
    retail_product_order_cash_refund_chargeback_amount NUMBER(38, 10),
    mobile_app_product_order_cash_refund_chargeback_amount NUMBER(38, 10),
    product_order_cash_credit_refund_amount NUMBER(38, 10),
    online_product_order_cash_credit_refund_amount NUMBER(38, 10),
    retail_product_order_cash_credit_refund_amount NUMBER(38, 10),
    mobile_app_product_order_cash_credit_refund_amount NUMBER(38, 10),
    product_order_reship_exchange_order_count NUMBER(38),
    online_product_order_reship_exchange_order_count NUMBER(38),
    retail_product_order_reship_exchange_order_count NUMBER(38),
    mobile_app_product_order_reship_exchange_order_count NUMBER(38),
    product_order_reship_exchange_unit_count NUMBER(38),
    online_product_order_reship_exchange_unit_count NUMBER(38),
    retail_product_order_reship_exchange_unit_count NUMBER(38),
    mobile_app_product_order_reship_exchange_unit_count NUMBER(38),
    product_order_reship_exchange_direct_cogs_amount NUMBER(38, 10),
    online_product_order_reship_exchange_direct_cogs_amount NUMBER(38, 10),
    retail_product_order_reship_exchange_direct_cogs_amount NUMBER(38, 10),
    mobile_app_product_order_reship_exchange_direct_cogs_amount NUMBER(38, 10),
    product_order_return_cogs_amount NUMBER(38, 10),
    online_product_order_return_cogs_amount NUMBER(38, 10),
    retail_product_order_return_cogs_amount NUMBER(38, 10),
    mobile_app_product_order_return_cogs_amount NUMBER(38, 10),
    product_order_return_unit_count NUMBER(38),
    online_product_order_return_unit_count NUMBER(38),
    retail_product_order_return_unit_count NUMBER(38),
    mobile_app_product_order_return_unit_count NUMBER(38),
    product_order_amount_to_pay NUMBER(38, 10),
    online_product_order_amount_to_pay NUMBER(38, 10),
    retail_product_order_amount_to_pay NUMBER(38, 10),
    mobile_app_product_order_amount_to_pay NUMBER(38, 10),
    product_gross_revenue_excl_shipping NUMBER(38, 10),
    online_product_gross_revenue_excl_shipping NUMBER(38, 10),
    retail_product_gross_revenue_excl_shipping NUMBER(38, 10),
    mobile_app_product_gross_revenue_excl_shipping NUMBER(38, 10),
    product_gross_revenue NUMBER(38, 10),
    online_product_gross_revenue NUMBER(38, 10),
    retail_product_gross_revenue NUMBER(38, 10),
    mobile_app_product_gross_revenue NUMBER(38, 10),
    product_net_revenue NUMBER(38, 10),
    online_product_net_revenue NUMBER(38, 10),
    retail_product_net_revenue NUMBER(38, 10),
    mobile_app_product_net_revenue NUMBER(38, 10),
    product_margin_pre_return NUMBER(38, 10),
    first_guest_product_margin_pre_return NUMBER(38, 10),
    online_product_margin_pre_return NUMBER(38, 10),
    retail_product_margin_pre_return NUMBER(38, 10),
    mobile_app_product_margin_pre_return NUMBER(38, 10),
    product_margin_pre_return_excl_shipping NUMBER(38, 10),
    online_product_margin_pre_return_excl_shipping NUMBER(38, 10),
    retail_product_margin_pre_return_excl_shipping NUMBER(38, 10),
    mobile_app_product_margin_pre_return_excl_shipping NUMBER(38, 10),
    product_gross_profit NUMBER(38, 10),
    online_product_gross_profit NUMBER(38, 10),
    retail_product_gross_profit NUMBER(38, 10),
    mobile_app_product_gross_profit NUMBER(38, 10),
    product_variable_contribution_profit NUMBER(38, 10),
    online_product_variable_contribution_profit NUMBER(38, 10),
    retail_product_variable_contribution_profit NUMBER(38, 10),
    mobile_app_product_variable_contribution_profit NUMBER(38, 10),
    product_order_cash_gross_revenue_amount NUMBER(38, 10),
    online_product_order_cash_gross_revenue_amount NUMBER(38, 10),
    retail_product_order_cash_gross_revenue_amount NUMBER(38, 10),
    mobile_app_product_order_cash_gross_revenue_amount NUMBER(38, 10),
    product_order_cash_net_revenue NUMBER(38, 10),
    online_product_order_cash_net_revenue NUMBER(38, 10),
    retail_product_order_cash_net_revenue NUMBER(38, 10),
    mobile_app_product_order_cash_net_revenue NUMBER(38, 10),
    billing_cash_gross_revenue NUMBER(38, 10),
    billing_cash_net_revenue NUMBER(38, 10),
    cash_gross_revenue NUMBER(38, 10),
    cash_net_revenue NUMBER(38, 10),
    cash_gross_profit NUMBER(38, 10),
    cash_variable_contribution_profit NUMBER(38, 10),
    monthly_billed_credit_cash_transaction_amount NUMBER(38, 10),
    membership_fee_cash_transaction_amount NUMBER(38, 10),
    gift_card_transaction_amount NUMBER(38, 10),
    legacy_credit_cash_transaction_amount NUMBER(38, 10),
    monthly_billed_credit_cash_refund_chargeback_amount NUMBER(38, 10),
    membership_fee_cash_refund_chargeback_amount NUMBER(38, 10),
    gift_card_cash_refund_chargeback_amount NUMBER(38, 10),
    legacy_credit_cash_refund_chargeback_amount NUMBER(38, 10),
    billed_cash_credit_issued_amount NUMBER(38, 10),
    billed_cash_credit_redeemed_amount NUMBER(38, 10),
    online_billed_cash_credit_redeemed_amount NUMBER(38, 10),
    retail_billed_cash_credit_redeemed_amount NUMBER(38, 10),
    mobile_billed_cash_credit_redeemed_amount NUMBER(38, 10),
    billed_cash_credit_cancelled_amount NUMBER(38, 10),
    billed_cash_credit_expired_amount NUMBER(38, 10),
    billed_cash_credit_issued_equivalent_count NUMBER(38, 10),
    billed_cash_credit_redeemed_same_month_amount NUMBER(38, 10),
    billed_cash_credit_redeemed_equivalent_count NUMBER(38, 10),
    billed_cash_credit_cancelled_equivalent_count NUMBER(38, 10),
    billed_cash_credit_expired_equivalent_count NUMBER(38, 10),
    refund_cash_credit_issued_amount NUMBER(38, 10),
    refund_cash_credit_redeemed_amount NUMBER(38, 10),
    refund_cash_credit_cancelled_amount NUMBER(38, 10),
    refund_cash_credit_expired_amount NUMBER(38, 10),
    other_cash_credit_issued_amount NUMBER(38, 10),
    other_cash_credit_redeemed_amount NUMBER(38, 10),
    other_cash_credit_cancelled_amount NUMBER(38, 10),
    other_cash_credit_expired_amount NUMBER(38, 10),
    noncash_credit_issued_amount NUMBER(38, 10),
    noncash_credit_cancelled_amount NUMBER(38, 10),
    noncash_credit_expired_amount NUMBER(38, 10),
    cumulative_cash_gross_profit_decile NUMBER(38),
    cumulative_product_gross_profit_decile NUMBER(38),
    activating_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    activating_product_order_tariff_amount NUMBER(38, 10),
    activating_product_order_product_subtotal_amount NUMBER(38, 10),
    activating_product_order_product_discount_amount NUMBER(38, 10),
    activating_product_order_shipping_discount_amount NUMBER(38, 10),
    activating_product_order_shipping_revenue_before_discount_amount NUMBER(38, 10),
    activating_product_order_shipping_revenue_amount NUMBER(38, 10),
    activating_product_order_tax_amount NUMBER(38, 10),
    activating_product_order_cash_transaction_amount NUMBER(38, 10),
    activating_product_order_count NUMBER(38),
    activating_product_order_unit_count NUMBER(38),
    activating_product_order_outfit_component_unit_count NUMBER(38),
    activating_product_order_outfit_count NUMBER(38),
    activating_product_order_discounted_unit_count NUMBER(38),
    activating_product_order_zero_revenue_unit_count NUMBER(38),
    activating_product_order_landed_product_cost_amount NUMBER(38, 10),
    activating_product_order_shipping_cost_amount NUMBER(38, 10),
    activating_product_order_shipping_supplies_cost_amount NUMBER(38, 10),
    activating_product_order_misc_cogs_amount NUMBER(38, 10),
    activating_product_order_direct_cogs_amount NUMBER(38, 10),
    activating_product_order_payment_processing_cost_amount NUMBER(38, 10),
    activating_product_order_variable_gms_cost_amount NUMBER(38, 10),
    activating_product_order_variable_warehouse_cost_amount NUMBER(38, 10),
    activating_product_order_amount_to_pay NUMBER(38, 10),
    activating_product_gross_revenue_excl_shipping NUMBER(38, 10),
    activating_product_gross_revenue NUMBER(38, 10),
    activating_product_margin_pre_return NUMBER(38, 10),
    activating_product_margin_pre_return_excl_shipping NUMBER(38, 10),
    m3_cumulative_cash_gross_profit NUMBER(38, 10),
    m3_cumulative_product_gross_profit NUMBER(38, 10),
    m6_cumulative_cash_gross_profit NUMBER(38, 10),
    m6_cumulative_product_gross_profit NUMBER(38, 10),
    m9_cumulative_cash_gross_profit NUMBER(38, 10),
    m9_cumulative_product_gross_profit NUMBER(38, 10),
    m12_cumulative_cash_gross_profit NUMBER(38, 10),
    m12_cumulative_product_gross_profit NUMBER(38, 10),
    m18_cumulative_cash_gross_profit NUMBER(38, 10),
    m18_cumulative_product_gross_profit NUMBER(38, 10),
    m24_cumulative_cash_gross_profit NUMBER(38, 10),
    m24_cumulative_product_gross_profit NUMBER(38, 10),
    m36_cumulative_cash_gross_profit NUMBER(38, 10),
    m36_cumulative_product_gross_profit NUMBER(38, 10),
    customer_acquisition_cost NUMBER(38, 10),
    x_customer_acquisition_cost NUMBER(38, 10),
    meta_row_hash INT,
    meta_create_datetime TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(3),
    meta_update_datetime TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (customer_id, store_id, vip_store_id, vip_cohort_month_date, guest_cohort_month_date,
        activation_key, first_activation_key, is_reactivated_vip, membership_type, gender),
    FOREIGN KEY (customer_id) references stg.dim_customer (customer_id),
    FOREIGN KEY (store_id) references stg.dim_store (store_id),
    FOREIGN KEY (vip_store_id) references stg.dim_store (store_id)
);

GRANT OWNERSHIP ON TABLE analytics_base.customer_lifetime_value_ltd TO ROLE __EDW_ANALYTICS_BASE_RWC COPY CURRENT GRANTS;

-- ALTER TABLE analytics_base.customer_lifetime_value_ltd ADD COLUMN new_column INT;
