CREATE TABLE IF NOT EXISTS analytics_base.customer_failed_billings_monthly (
    month_date DATE,
    customer_id NUMBER(38, 0),
    store_id NUMBER(38, 0),
    store_brand VARCHAR(50),
    store_region VARCHAR(50),
    store_full_name VARCHAR(100),
    store_country VARCHAR(75),
    vip_tenure NUMBER(38, 0),
    is_first_failed_billing BOOLEAN,
    is_failed_prior_month BOOLEAN,
    consecutive_failed_billings NUMBER(38, 0),
    months_since_last_successful_billing NUMBER(38, 0),
    number_of_failed_billings_in_last_12_months NUMBER(38, 0),
    months_since_last_skip NUMBER(38, 0),
    number_of_skips_in_last_12_months NUMBER(38, 0),
    months_since_last_login NUMBER(38, 0),
    is_login BOOLEAN,
    number_of_visits_in_last_12_months NUMBER(38, 0),
    opened_an_email BOOLEAN,
    clicked_an_email BOOLEAN,
    months_since_last_email_open NUMBER(38, 0),
    months_since_last_email_click NUMBER(38, 0),
    months_since_last_successful_order NUMBER(38, 0),
    number_of_email_opens NUMBER(38, 0),
    number_of_email_clicks NUMBER(38, 0),
	meta_create_datetime TIMESTAMP_LTZ(3),
	meta_update_datetime TIMESTAMP_LTZ(3)
);
