CREATE OR REPLACE TABLE reference.gsc_landed_cost
(
    po_number VARCHAR,
    year_month_received DATE,
    sku VARCHAR,
    po_line_number NUMBER(38,0),
    plm_style VARCHAR,
    fully_landed VARCHAR,
    units_received NUMBER(38,0),
    actual_landed_cost_per_unit NUMBER(38,6),
    po_cost_without_commission NUMBER(38,6),
    cmt_cost NUMBER(38,6),
    actual_duty_cost_per_unit NUMBER(38,6),
    actual_tariff_cost_per_unit NUMBER(38,6),
    cpu_freight NUMBER(38,6),
    cpu_ocean NUMBER(38,6),
    cpu_air NUMBER(38,6),
    cpu_transload NUMBER(38,6),
    cpu_otr NUMBER(38,6),
    cpu_domestic NUMBER(38,6),
    cpu_pierpass NUMBER(38,6),
    agency_cost_and_po_cost NUMBER(38,6),
    history VARCHAR,
    total_actual_landed_cost NUMBER(38,6),
    meta_row_hash INT,
    is_deleted BOOLEAN,
    meta_create_datetime TIMESTAMP_LTZ,
    meta_update_datetime TIMESTAMP_LTZ
);
