CREATE OR REPLACE TABLE reference.finance_monthly_budget_forecast_actual
(
    version                                                       VARCHAR(255),
    version_date                                                  DATE,
    financial_date                                                DATE,
    hyperion_store_rg                                             VARCHAR(255),
    bu                                                            VARCHAR(255),
    membership_credits_charged_count                              NUMBER(19, 7),
    membership_credits_redeemed_count                             NUMBER(19, 7),
    membership_credits_cancelled_count                            NUMBER(19, 7),
    first_msrp_revenue                                            NUMBER(19, 7),
    first_discounts                                               NUMBER(19, 7),
    repeat_msrp_revenue                                           NUMBER(19, 7),
    repeat_discounts                                              NUMBER(19, 7),
    leads                                                         NUMBER(19, 7),
    gross_cash_revenue                                            NUMBER(19, 7),
    cash_refunds                                                  NUMBER(19, 7),
    chargebacks                                                   NUMBER(19, 7),
    net_cash_revenue_total                                        NUMBER(19, 7),
    refunds_and_chargebacks_as_percent_of_gross_cash              NUMBER(19, 7),
    cash_gross_margin                                             NUMBER(19, 7),
    cash_gross_margin_percent_total                               NUMBER(19, 7),
    media_spend                                                   NUMBER(19, 7),
    cash_contribution_after_media                                 NUMBER(19, 7),
    cpl                                                           NUMBER(19, 7),
    vip_cpa                                                       NUMBER(19, 7),
    m1_lead_to_vip                                                NUMBER(19, 7),
    m1_vips                                                       NUMBER(19, 7),
    aged_lead_conversions                                         NUMBER(19, 7),
    total_new_vips                                                NUMBER(19, 7),
    cancels                                                       NUMBER(19, 7),
    net_change_in_vips                                            NUMBER(19, 7),
    ending_vips                                                   NUMBER(19, 7),
    vip_growth_percent                                            NUMBER(19, 7),
    activating_gaap_gross_revenue                                 NUMBER(19, 7),
    activating_gaap_net_revenue                                   NUMBER(19, 7),
    activating_order_count                                        NUMBER(19, 7),
    activating_aov_incl_shipping_rev                              NUMBER(19, 7),
    activating_units_per_transaction                              NUMBER(19, 7),
    activating_discount_percent                                   NUMBER(19, 7),
    activating_gross_margin_$                                     NUMBER(19, 7),
    activating_gross_margin_percent                               NUMBER(19, 7),
    repeat_gaap_gross_revenue                                     NUMBER(19, 7),
    repeat_gaap_net_revenue                                       NUMBER(19, 7),
    repeat_order_count                                            NUMBER(19, 7),
    repeat_aov_incl_shipping_rev                                  NUMBER(19, 7),
    repeat_units_per_transaction                                  NUMBER(19, 7),
    repeat_discount_percent                                       NUMBER(19, 7),
    repeat_gaap_gross_margin_$                                    NUMBER(19, 7),
    repeat_gaap_gross_margin_percent                              NUMBER(19, 7),
    repeat_net_unredeemed_credit_billings                         NUMBER(19, 7),
    repeat_refund_credits                                         NUMBER(19, 7),
    repeat_other_ad_rev_div_adaptive_adj                          NUMBER(19, 7),
    repeat_net_cash_revenue                                       NUMBER(19, 7),
    repeat_cash_gross_margin                                      NUMBER(19, 7),
    repeat_cash_gross_margin_percent                              NUMBER(19, 7),
    membership_credits_charged                                    NUMBER(19, 7),
    membership_credits_redeemed                                   NUMBER(19, 7),
    membership_credits_refunded_plus_chargebacks                  NUMBER(19, 7),
    net_unredeemed_credit_billings                                NUMBER(19, 7),
    net_unredeemed_credit_billings_as_percent_of_net_cash_revenue NUMBER(19, 7),
    refunded_as_credit                                            NUMBER(19, 7),
    refund_credit_redeemed                                        NUMBER(19, 7),
    net_unredeemed_refund_credit                                  NUMBER(19, 7),
    deferred_revenue                                              NUMBER(19, 7),
    bom_vips                                                      NUMBER(19, 7),
    credit_billed_percent                                         NUMBER(19, 7),
    credit_redeemed_percent                                       NUMBER(19, 7),
    credit_canceled_percent                                       NUMBER(19, 7),
    total_units_shipped                                           NUMBER(19, 7),
    repeat_cash_purchasers                                        NUMBER(19, 7),
    cash_purchase_rate                                            NUMBER(19, 7),
    o_div_vip                                                     NUMBER(19, 7),
    ebitda_minus_cash                                             NUMBER(19, 7),
    repeatplusbizdev                                              NUMBER(19, 7),
    activating_units                                              NUMBER(19, 7),
    repeat_units                                                  NUMBER(19, 7),
    repeat_product_revenue_incl_shipping                          NUMBER(19, 7),
    product_cost_calc                                             NUMBER(19, 7),
    inventory_writedown                                           NUMBER(19, 7),
    total_cogs_minus_cash                                         NUMBER(19, 7),
    merchant_fees                                                 NUMBER(19, 7),
    gms_variable                                                  NUMBER(19, 7),
    fc_variable                                                   NUMBER(19, 7),
    freight_revenue                                               NUMBER(19, 7),
    freight_out_cost                                              NUMBER(19, 7),
    outbound_shipping_supplies                                    NUMBER(19, 7),
    returns_shipping_cost                                         NUMBER(19, 7),
    product_cost_markdown                                         NUMBER(19, 7),
    repeat_shipped_order_cash_collected                           NUMBER(19, 7),
    acquisition_margin_$                                          NUMBER(19, 7),
    acquisition_margin_percent                                    NUMBER(19, 7),
    acquisition_margin_$__div__order                              NUMBER(19, 7),
    product_cost_cust_returns_calc                                NUMBER(19, 7),
    reship_exch_orders_shipped                                    NUMBER(19, 7),
    reship_exch_units_shipped                                     NUMBER(19, 7),
    cash_net_revenue                                              NUMBER(19, 7),
    activating_product_gross_revenue                              NUMBER(19, 7),
    repeat_product_gross_revenue                                  NUMBER(19, 7),
    cash_gross_margin_percent                                     NUMBER(19, 7),
    repeat_units_shipped                                          NUMBER(19, 7),
    repeat_orders_shipped                                         NUMBER(19, 7),
    advertising_expenses                                          NUMBER(19, 7),
    merchant_fee                                                  NUMBER(19, 7),
    selling_expenses                                              NUMBER(19, 7),
    marketing_expenses                                            NUMBER(19, 7),
    direct_general_and_administrative                             NUMBER(19, 7),
    total_opex                                                    NUMBER(19, 7),
    product_revenue                                               NUMBER(19, 7),
    product_gross_margin                                          NUMBER(19, 7),
    cash_gross_profit                                             NUMBER(19, 7),
    retail_redemption_revenue                                     NUMBER(19, 7),
    meta_row_hash                                                 INT,
    meta_create_datetime                                          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(3),
    meta_update_datetime                                          TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(3)
);
