CREATE OR REPLACE TABLE reference.order_customer_change (
	ORDER_ID NUMBER(38,0),
	ORIGINAL_CUSTOMER_ID NUMBER(38,0),
	NEW_CUSTOMER_ID NUMBER(38,0),
	CUSTOMER_ID_CHANGE_SEQUENCE NUMBER(38,0),
	IS_GIFT_ORDER BOOLEAN DEFAULT FALSE,
	META_CREATE_DATETIME TIMESTAMP_LTZ(9),
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9)
);
