CREATE OR REPLACE TABLE reference.specialty_store_ids
    (
        store_id NUMBER(38,0),
        store_full_name VARCHAR(50),
        store_group_id NUMBER(38,0),
        store_group VARCHAR(50),
        store_type VARCHAR(10),
        store_sub_type VARCHAR(50),
        is_core_store BOOLEAN,
        store_division VARCHAR(32),
        store_division_abbr VARCHAR(10),
        store_brand VARCHAR(20),
        store_brand_abbr VARCHAR(10),
        store_region VARCHAR(32),
        store_country VARCHAR(10),
        store_currency VARCHAR(10),
        store_time_zone VARCHAR(50),
        store_retail_state VARCHAR(50),
        store_retail_city VARCHAR(50),
        store_retail_location VARCHAR(50),
        store_retail_zip_code VARCHAR(10),
        retail_location_code VARCHAR(50),
        retail_status VARCHAR(50),
        retail_region VARCHAR(50),
        retail_district VARCHAR(50),
        meta_create_datetime TIMESTAMP_LTZ(9),
        meta_update_datetime TIMESTAMP_LTZ(9),
        PRIMARY KEY (store_id)
    );
