CREATE TABLE IF NOT EXISTS reference.zip_code
(
	zipcode varchar,
	primaryrecord varchar,
	population varchar,
	householdsperzipcode varchar,
	whitepopulation varchar,
	blackpopulation varchar,
	hispanicpopulation varchar,
	asianpopulation varchar,
	hawaiianpopulation varchar,
	indianpopulation varchar,
	otherpopulation varchar,
	malepopulation varchar,
	femalepopulation varchar,
	personsperhousehold varchar,
	averagehousevalue varchar,
	incomeperhousehold varchar,
	medianage varchar,
	medianagemale varchar,
	medianagefemale varchar,
	latitude varchar,
	longitude varchar,
	elevation varchar,
	state varchar,
	statefullname varchar,
	citytype varchar,
	cityaliasabbreviation varchar,
	areacode varchar,
	city varchar,
	cityaliasname varchar,
	county varchar,
	countyfips varchar,
	statefips varchar,
	timezone varchar,
	daylightsaving varchar,
	msa varchar,
	pmsa varchar,
	csa varchar,
	cbsa varchar,
	cbsa_div varchar,
	cbsa_type varchar,
	cbsa_name varchar,
	msa_name varchar,
	pmsa_name varchar,
	region varchar,
	division varchar,
	mailingname varchar,
	numberofbusinesses varchar,
	numberofemployees varchar,
	businessfirstquarterpayroll varchar,
	businessannualpayroll varchar,
	businessemploymentflag varchar,
	growthrank varchar,
	growingcountiesa varchar,
	growingcountiesb varchar,
	growthincreasenumber varchar,
	growthincreasepercentage varchar,
	cbsapopulation varchar,
	cbsadivisionpopulation varchar,
	congressionaldistrict varchar,
	congressionallandarea varchar,
	deliveryresidential varchar,
	deliverybusiness varchar,
	deliverytotal varchar,
	preferredlastlinekey varchar,
	classificationcode varchar,
	multicounty varchar,
	csaname varchar,
	cbsa_div_name varchar,
	citystatekey varchar,
	populationestimate varchar,
	landarea varchar,
	waterarea varchar,
	cityaliascode varchar,
	citymixedcase varchar,
	cityaliasmixedcase varchar,
	boxcount varchar,
	sfdu varchar,
	mfdu varchar,
	stateansi varchar,
	countyansi varchar,
	zipintrodate varchar,
	aliasintrodate varchar,
	facilitycode varchar,
	citydeliveryindicator varchar,
	carrierrouteratesortation varchar,
	financenumber varchar,
	uniquezipname varchar,
	ssastatecountycode varchar,
	medicarecbsacode varchar,
	medicarecbsaname varchar,
	medicarecbsatype varchar,
	marketratingareaid varchar,
	countymixedcase varchar
);

/*
CREATE OR REPLACE TABLE reference.zip_code AS
SELECT * FROM ds_work.public.zip_codes_database_deluxe_business ORDER BY zipcode;
*/

ALTER TABLE reference.zip_code ADD PRIMARY KEY (zipcode);
