CREATE TABLE IF NOT EXISTS reporting.merch_planning_outfit (
    date DATE,
    date_type VARCHAR(100),
    store_id NUMBER(38, 0),
    store_name VARCHAR(500),
    store_brand VARCHAR(200),
    store_type VARCHAR(60),
    country VARCHAR(200),
    region VARCHAR(200),
    finance_specialty_store VARCHAR(20),
    is_retail BOOLEAN,
    bundle_name VARCHAR(2000),
    bundle_alias VARCHAR(100),
    ty_total_bundle_count NUMBER(38, 0),
    ty_bundle_count_activating NUMBER(38, 0),
    ty_bundle_count_repeat NUMBER(38, 0),
    ty_bundle_count_guest NUMBER(38, 0),
    ty_total_product_subtotal NUMBER(38, 4),
    ty_product_subtotal_activating NUMBER(38, 4),
    ty_product_subtotal_repeat NUMBER(38, 4),
    ty_product_subtotal_guest NUMBER(38, 4),
    ty_total_product_discount NUMBER(38, 4),
    ty_product_discount_activating NUMBER(38, 4),
    ty_product_discount_repeat NUMBER(38, 4),
    ty_product_discount_guest NUMBER(38, 4),
    ty_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    ty_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    ty_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    ty_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    ty_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    ty_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    ty_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    ty_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    ty_total_product_cost NUMBER(38, 4),
    ty_product_cost_activating NUMBER(38, 4),
    ty_product_cost_repeat NUMBER(38, 4),
    ty_product_cost_guest NUMBER(38, 4),

    ty_total_product_cost_c NUMBER(38, 4),
    ty_product_cost_activating_c NUMBER(38, 4),
    ty_product_cost_repeat_c NUMBER(38, 4),
    ty_product_cost_guest_c NUMBER(38, 4),

    ty_total_non_reduced_vip_price NUMBER(38, 4),
    ty_non_reduced_vip_price_activating NUMBER(38, 4),
    ty_non_reduced_vip_price_repeat NUMBER(38, 4),
    ty_non_reduced_vip_price_guest NUMBER(38, 4),
    ltd_total_bundle_count NUMBER(38, 0),
    ltd_bundle_count_activating NUMBER(38, 0),
    ltd_bundle_count_repeat NUMBER(38, 0),
    ltd_bundle_count_guest NUMBER(38, 0),
    mtd_total_bundle_count NUMBER(38, 0),
    mtd_bundle_count_activating NUMBER(38, 0),
    mtd_bundle_count_repeat NUMBER(38, 0),
    mtd_bundle_count_guest NUMBER(38, 0),
    mtd_total_product_subtotal NUMBER(38, 4),
    mtd_product_subtotal_activating NUMBER(38, 4),
    mtd_product_subtotal_repeat NUMBER(38, 4),
    mtd_product_subtotal_guest NUMBER(38, 4),
    mtd_total_product_discount NUMBER(38, 4),
    mtd_product_discount_activating NUMBER(38, 4),
    mtd_product_discount_repeat NUMBER(38, 4),
    mtd_product_discount_guest NUMBER(38, 4),
    mtd_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    mtd_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    mtd_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    mtd_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    mtd_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    mtd_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    mtd_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    mtd_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    mtd_total_product_cost NUMBER(38, 4),
    mtd_product_cost_activating NUMBER(38, 4),
    mtd_product_cost_repeat NUMBER(38, 4),
    mtd_product_cost_guest NUMBER(38, 4),

    mtd_total_product_cost_c NUMBER(38, 4),
    mtd_product_cost_activating_c NUMBER(38, 4),
    mtd_product_cost_repeat_c NUMBER(38, 4),
    mtd_product_cost_guest_c NUMBER(38, 4),

    mtd_total_non_reduced_vip_price NUMBER(38, 4),
    mtd_non_reduced_vip_price_activating NUMBER(38, 4),
    mtd_non_reduced_vip_price_repeat NUMBER(38, 4),
    mtd_non_reduced_vip_price_guest NUMBER(38, 4),
    ly_day_total_bundle_count NUMBER(38, 0),
    ly_day_bundle_count_activating NUMBER(38, 0),
    ly_day_bundle_count_repeat NUMBER(38, 0),
    ly_day_bundle_count_guest NUMBER(38, 0),
    ly_day_total_product_subtotal NUMBER(38, 4),
    ly_day_product_subtotal_activating NUMBER(38, 4),
    ly_day_product_subtotal_repeat NUMBER(38, 4),
    ly_day_product_subtotal_guest NUMBER(38, 4),
    ly_day_total_product_discount NUMBER(38, 4),
    ly_day_product_discount_activating NUMBER(38, 4),
    ly_day_product_discount_repeat NUMBER(38, 4),
    ly_day_product_discount_guest NUMBER(38, 4),
    ly_day_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    ly_day_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    ly_day_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    ly_day_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    ly_day_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    ly_day_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    ly_day_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    ly_day_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    ly_day_total_product_cost NUMBER(38, 4),
    ly_day_product_cost_activating NUMBER(38, 4),
    ly_day_product_cost_repeat NUMBER(38, 4),
    ly_day_product_cost_guest NUMBER(38, 4),

    ly_day_total_product_cost_c NUMBER(38, 4),
    ly_day_product_cost_activating_c NUMBER(38, 4),
    ly_day_product_cost_repeat_c NUMBER(38, 4),
    ly_day_product_cost_guest_c NUMBER(38, 4),

    ly_day_total_non_reduced_vip_price NUMBER(38, 4),
    ly_day_non_reduced_vip_price_activating NUMBER(38, 4),
    ly_day_non_reduced_vip_price_repeat NUMBER(38, 4),
    ly_day_non_reduced_vip_price_guest NUMBER(38, 4),
    lymtd_day_total_bundle_count NUMBER(38, 0),
    lymtd_day_bundle_count_activating NUMBER(38, 0),
    lymtd_day_bundle_count_repeat NUMBER(38, 0),
    lymtd_day_bundle_count_guest NUMBER(38, 0),
    lymtd_day_total_product_subtotal NUMBER(38, 4),
    lymtd_day_product_subtotal_activating NUMBER(38, 4),
    lymtd_day_product_subtotal_repeat NUMBER(38, 4),
    lymtd_day_product_subtotal_guest NUMBER(38, 4),
    lymtd_day_total_product_discount NUMBER(38, 4),
    lymtd_day_product_discount_activating NUMBER(38, 4),
    lymtd_day_product_discount_repeat NUMBER(38, 4),
    lymtd_day_product_discount_guest NUMBER(38, 4),
    lymtd_day_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    lymtd_day_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    lymtd_day_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    lymtd_day_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    lymtd_day_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    lymtd_day_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    lymtd_day_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    lymtd_day_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    lymtd_day_total_product_cost NUMBER(38, 4),
    lymtd_day_product_cost_activating NUMBER(38, 4),
    lymtd_day_product_cost_repeat NUMBER(38, 4),
    lymtd_day_product_cost_guest NUMBER(38, 4),

    lymtd_day_total_product_cost_c NUMBER(38, 4),
    lymtd_day_product_cost_activating_c NUMBER(38, 4),
    lymtd_day_product_cost_repeat_c NUMBER(38, 4),
    lymtd_day_product_cost_guest_c NUMBER(38, 4),

    lymtd_day_total_non_reduced_vip_price NUMBER(38, 4),
    lymtd_day_non_reduced_vip_price_activating NUMBER(38, 4),
    lymtd_day_non_reduced_vip_price_repeat NUMBER(38, 4),
    lymtd_day_non_reduced_vip_price_guest NUMBER(38, 4),
    ly_date_total_bundle_count NUMBER(38, 0),
    ly_date_bundle_count_activating NUMBER(38, 0),
    ly_date_bundle_count_repeat NUMBER(38, 0),
    ly_date_bundle_count_guest NUMBER(38, 0),
    ly_date_total_product_subtotal NUMBER(38, 4),
    ly_date_product_subtotal_activating NUMBER(38, 4),
    ly_date_product_subtotal_repeat NUMBER(38, 4),
    ly_date_product_subtotal_guest NUMBER(38, 4),
    ly_date_total_product_discount NUMBER(38, 4),
    ly_date_product_discount_activating NUMBER(38, 4),
    ly_date_product_discount_repeat NUMBER(38, 4),
    ly_date_product_discount_guest NUMBER(38, 4),
    ly_date_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    ly_date_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    ly_date_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    ly_date_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    ly_date_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    ly_date_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    ly_date_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    ly_date_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    ly_date_total_product_cost NUMBER(38, 4),
    ly_date_product_cost_activating NUMBER(38, 4),
    ly_date_product_cost_repeat NUMBER(38, 4),
    ly_date_product_cost_guest NUMBER(38, 4),

    ly_date_total_product_cost_c NUMBER(38, 4),
    ly_date_product_cost_activating_c NUMBER(38, 4),
    ly_date_product_cost_repeat_c NUMBER(38, 4),
    ly_date_product_cost_guest_c NUMBER(38, 4),

    ly_date_total_non_reduced_vip_price NUMBER(38, 4),
    ly_date_non_reduced_vip_price_activating NUMBER(38, 4),
    ly_date_non_reduced_vip_price_repeat NUMBER(38, 4),
    ly_date_non_reduced_vip_price_guest NUMBER(38, 4),
    meta_create_datetime TIMESTAMP_LTZ(3),
    meta_update_datetime TIMESTAMP_LTZ(3)
);
