CREATE TABLE IF NOT EXISTS reporting.order_transactions_by_reason (
    month_date DATE,
    order_date DATE,
    transaction_date DATE,
    payment_date DATE,
    store_region VARCHAR(50),
    store_country VARCHAR(75),
    store_type VARCHAR(20),
    store_brand VARCHAR(50),
    store_full_name VARCHAR(100),
    payment_method VARCHAR(75),
    creditcard_type VARCHAR(75),
    order_classification_l1 VARCHAR(75),
    order_classification_l2 VARCHAR(75),
    order_status VARCHAR(50),
    membership_order_type_l1 VARCHAR(50),
    membership_order_type_l2 VARCHAR(50),
    membership_order_type_l3 VARCHAR(50),
    transaction_type VARCHAR(100),
    platform VARCHAR(250),
    browser VARCHAR(250),
    attempt_status VARCHAR(255),
    response_result_text VARCHAR(255),
    response_reason_text VARCHAR(255),
    attempts NUMBER(38, 0),
    customers NUMBER(38, 0),
    orders NUMBER(38, 0),
	meta_create_datetime TIMESTAMP_LTZ(3),
	meta_update_datetime TIMESTAMP_LTZ(3)
);
