CREATE OR REPLACE TABLE reporting.merch_planning_item_final_output(
    date DATE,
    period VARCHAR(50),
    date_type VARCHAR(100),
    store_id NUMBER(38, 0),
    store_name VARCHAR(500),
    store_brand VARCHAR(200),
    store_type VARCHAR(60),
    country VARCHAR(200),
    finance_specialty_store VARCHAR(20),
    region VARCHAR(100),
    product_sku VARCHAR(100),
    base_sku VARCHAR(100),
    is_retail BOOLEAN,
    wms_class VARCHAR(100),
    ty_total_unit_count NUMBER(38, 0),
    ty_unit_count_activating NUMBER(38, 0),
    ty_unit_count_repeat NUMBER(38, 0),
    ty_unit_count_guest NUMBER(38, 0),
    ty_total_product_subtotal NUMBER(38, 4),
    ty_product_subtotal_activating NUMBER(38, 4),
    ty_product_subtotal_repeat NUMBER(38, 4),
    ty_product_subtotal_guest NUMBER(38, 4),
    ty_total_product_discount NUMBER(38, 4),
    ty_product_discount_activating NUMBER(38, 4),
    ty_product_discount_repeat NUMBER(38, 4),
    ty_product_discount_guest NUMBER(38, 4),
    ty_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    ty_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    ty_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    ty_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    ty_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    ty_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    ty_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    ty_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    ty_total_product_cost NUMBER(38, 4),
    ty_product_cost_activating NUMBER(38, 4),
    ty_product_cost_repeat NUMBER(38, 4),
    ty_product_cost_guest NUMBER(38, 4),

    ty_total_product_cost_c NUMBER(38, 4),
    ty_product_cost_activating_c NUMBER(38, 4),
    ty_product_cost_repeat_c NUMBER(38, 4),
    ty_product_cost_guest_c NUMBER(38, 4),

    ty_total_non_reduced_vip_price NUMBER(38, 4),
    ty_non_reduced_vip_price_activating NUMBER(38, 4),
    ty_non_reduced_vip_price_repeat NUMBER(38, 4),
    ty_non_reduced_vip_price_guest NUMBER(38, 4),
    ty_total_return_unit_count NUMBER(38, 0),
    ty_return_unit_count_activating NUMBER(38, 0),
    ty_return_unit_count_repeat NUMBER(38, 0),
    ty_return_unit_count_guest NUMBER(38, 0),
    ty_total_returned_product_gross_rev_excluding_shipping NUMBER(38, 4),
    ty_returned_product_gross_rev_excluding_shipping_activating NUMBER(38, 4),
    ty_returned_product_gross_rev_excluding_shipping_repeat NUMBER(38, 4),
    ty_returned_product_gross_rev_excluding_shipping_guest NUMBER(38, 4),
    ty_bop_onhand_qty NUMBER(38, 0),
    ty_bop_available_to_sell_qty NUMBER(38, 0),
    ty_bop_open_to_buy_qty NUMBER(38, 0),
    ty_bop_open_to_buy_qty_incl_in_transit NUMBER(38, 0),
    ty_bop_retail_reserve NUMBER(38, 0),
    ty_eop_onhand_qty NUMBER(38, 0),
    ty_eop_available_to_sell_qty NUMBER(38, 0),
    ty_eop_open_to_buy_qty NUMBER(38, 0),
    ty_eop_open_to_buy_qty_incl_in_transit NUMBER(38, 0),
    ty_eop_retail_reserve NUMBER(38, 0),
    mtd_total_unit_count NUMBER(38, 0),
    mtd_unit_count_activating NUMBER(38, 0),
    mtd_unit_count_repeat NUMBER(38, 0),
    mtd_unit_count_guest NUMBER(38, 0),
    mtd_total_product_subtotal NUMBER(38, 4),
    mtd_product_subtotal_activating NUMBER(38, 4),
    mtd_product_subtotal_repeat NUMBER(38, 4),
    mtd_product_subtotal_guest NUMBER(38, 4),
    mtd_total_product_discount NUMBER(38, 4),
    mtd_product_discount_activating NUMBER(38, 4),
    mtd_product_discount_repeat NUMBER(38, 4),
    mtd_product_discount_guest NUMBER(38, 4),
    mtd_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    mtd_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    mtd_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    mtd_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    mtd_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    mtd_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    mtd_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    mtd_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    mtd_total_product_cost NUMBER(38, 4),
    mtd_product_cost_activating NUMBER(38, 4),
    mtd_product_cost_repeat NUMBER(38, 4),
    mtd_product_cost_guest NUMBER(38, 4),

    mtd_total_product_cost_c NUMBER(38, 4),
    mtd_product_cost_activating_c NUMBER(38, 4),
    mtd_product_cost_repeat_c NUMBER(38, 4),
    mtd_product_cost_guest_c NUMBER(38, 4),

    mtd_total_non_reduced_vip_price NUMBER(38, 4),
    mtd_non_reduced_vip_price_activating NUMBER(38, 4),
    mtd_non_reduced_vip_price_repeat NUMBER(38, 4),
    mtd_non_reduced_vip_price_guest NUMBER(38, 4),
    mtd_total_return_unit_count NUMBER(38, 0),
    mtd_return_unit_count_activating NUMBER(38, 0),
    mtd_return_unit_count_repeat NUMBER(38, 0),
    mtd_return_unit_count_guest NUMBER(38, 0),
    mtd_total_returned_product_gross_rev_excluding_shipping NUMBER(38, 4),
    mtd_returned_product_gross_rev_excluding_shipping_activating NUMBER(38, 4),
    mtd_returned_product_gross_rev_excluding_shipping_repeat NUMBER(38, 4),
    mtd_returned_product_gross_rev_excluding_shipping_guest NUMBER(38, 4),
    ly_total_unit_count NUMBER(38, 0),
    ly_unit_count_activating NUMBER(38, 0),
    ly_unit_count_repeat NUMBER(38, 0),
    ly_unit_count_guest NUMBER(38, 0),
    ly_total_product_subtotal NUMBER(38, 4),
    ly_product_subtotal_activating NUMBER(38, 4),
    ly_product_subtotal_repeat NUMBER(38, 4),
    ly_product_subtotal_guest NUMBER(38, 4),
    ly_total_product_discount NUMBER(38, 4),
    ly_product_discount_activating NUMBER(38, 4),
    ly_product_discount_repeat NUMBER(38, 4),
    ly_product_discount_guest NUMBER(38, 4),
    ly_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    ly_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    ly_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    ly_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    ly_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    ly_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    ly_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    ly_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    ly_total_product_cost NUMBER(38, 4),
    ly_product_cost_activating NUMBER(38, 4),
    ly_product_cost_repeat NUMBER(38, 4),
    ly_product_cost_guest NUMBER(38, 4),

    ly_total_product_cost_c NUMBER(38, 4),
    ly_product_cost_activating_c NUMBER(38, 4),
    ly_product_cost_repeat_c NUMBER(38, 4),
    ly_product_cost_guest_c NUMBER(38, 4),

    ly_total_non_reduced_vip_price NUMBER(38, 4),
    ly_non_reduced_vip_price_activating NUMBER(38, 4),
    ly_non_reduced_vip_price_repeat NUMBER(38, 4),
    ly_non_reduced_vip_price_guest NUMBER(38, 4),
    ly_total_return_unit_count NUMBER(38, 0),
    ly_return_unit_count_activating NUMBER(38, 0),
    ly_return_unit_count_repeat NUMBER(38, 0),
    ly_return_unit_count_guest NUMBER(38, 0),
    ly_total_returned_product_gross_rev_excluding_shipping NUMBER(38, 4),
    ly_returned_product_gross_rev_excluding_shipping_activating NUMBER(38, 4),
    ly_returned_product_gross_rev_excluding_shipping_repeat NUMBER(38, 4),
    ly_returned_product_gross_rev_excluding_shipping_guest NUMBER(38, 4),
    ly_bop_onhand_qty NUMBER(38, 0),
    ly_bop_available_to_sell_qty NUMBER(38, 0),
    ly_bop_open_to_buy_qty NUMBER(38, 0),
    ly_bop_open_to_buy_qty_incl_in_transit NUMBER(38, 0),
    ly_bop_retail_reserve NUMBER(38, 0),
    ly_eop_onhand_qty NUMBER(38, 0),
    ly_eop_available_to_sell_qty NUMBER(38, 0),
    ly_eop_open_to_buy_qty NUMBER(38, 0),
    ly_eop_open_to_buy_qty_incl_in_transit NUMBER(38, 0),
    ly_eop_retail_reserve NUMBER(38, 0),
    lymtd_total_unit_count NUMBER(38, 0),
    lymtd_unit_count_activating NUMBER(38, 0),
    lymtd_unit_count_repeat NUMBER(38, 0),
    lymtd_unit_count_guest NUMBER(38, 0),
    lymtd_total_product_subtotal NUMBER(38, 4),
    lymtd_product_subtotal_activating NUMBER(38, 4),
    lymtd_product_subtotal_repeat NUMBER(38, 4),
    lymtd_product_subtotal_guest NUMBER(38, 4),
    lymtd_total_product_discount NUMBER(38, 4),
    lymtd_product_discount_activating NUMBER(38, 4),
    lymtd_product_discount_repeat NUMBER(38, 4),
    lymtd_product_discount_guest NUMBER(38, 4),
    lymtd_total_product_gross_revenue_excl_shipping NUMBER(38, 4),
    lymtd_product_gross_revenue_excl_shipping_activating NUMBER(38, 4),
    lymtd_product_gross_revenue_excl_shipping_repeat NUMBER(38, 4),
    lymtd_product_gross_revenue_excl_shipping_guest NUMBER(38, 4),
    lymtd_total_product_margin_pre_return_excl_shipping NUMBER(38, 4),
    lymtd_product_margin_pre_return_excl_shipping_activating NUMBER(38, 4),
    lymtd_product_margin_pre_return_excl_shipping_repeat NUMBER(38, 4),
    lymtd_product_margin_pre_return_excl_shipping_guest NUMBER(38, 4),
    lymtd_total_product_cost NUMBER(38, 4),
    lymtd_product_cost_activating NUMBER(38, 4),
    lymtd_product_cost_repeat NUMBER(38, 4),
    lymtd_product_cost_guest NUMBER(38, 4),

    lymtd_total_product_cost_c NUMBER(38, 4),
    lymtd_product_cost_activating_c NUMBER(38, 4),
    lymtd_product_cost_repeat_c NUMBER(38, 4),
    lymtd_product_cost_guest_c NUMBER(38, 4),

    lymtd_total_non_reduced_vip_price NUMBER(38, 4),
    lymtd_non_reduced_vip_price_activating NUMBER(38, 4),
    lymtd_non_reduced_vip_price_repeat NUMBER(38, 4),
    lymtd_non_reduced_vip_price_guest NUMBER(38, 4),
    lymtd_total_return_unit_count NUMBER(38, 0),
    lymtd_return_unit_count_activating NUMBER(38, 0),
    lymtd_return_unit_count_repeat NUMBER(38, 0),
    lymtd_return_unit_count_guest NUMBER(38, 0),
    lymtd_total_returned_product_gross_rev_excluding_shipping NUMBER(38, 4),
    lymtd_returned_product_gross_rev_excluding_shipping_activating NUMBER(38, 4),
    lymtd_returned_product_gross_rev_excluding_shipping_repeat NUMBER(38, 4),
    lymtd_returned_product_gross_rev_excluding_shipping_guest NUMBER(38, 4),
    ty_bop_inventory_cost NUMBER(38, 4),
    ty_eop_inventory_cost NUMBER(38, 4),
    ly_bop_inventory_cost NUMBER(38, 4),
    ly_eop_inventory_cost NUMBER(38, 4),
    meta_create_datetime TIMESTAMP_LTZ(3),
    meta_update_datetime TIMESTAMP_LTZ(3)
);
