CREATE OR REPLACE TABLE reporting.daily_cash_final_output (
    date DATE,
    date_object VARCHAR(20),
    currency_object VARCHAR(8),
    currency_type VARCHAR(50),
    store_brand VARCHAR(100),
    business_unit VARCHAR(100),
    report_mapping VARCHAR(250),
    is_daily_cash_usd BOOLEAN,
    is_daily_cash_eur BOOLEAN,
    product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    product_order_subtotal_excl_tariff_amount_mtd NUMBER(38, 10),
    product_order_subtotal_excl_tariff_amount_mtd_ly NUMBER(38, 10),
    product_order_subtotal_excl_tariff_amount_month_tot_lm NUMBER(38, 10),
    product_order_subtotal_excl_tariff_amount_month_tot_ly NUMBER(38, 10),
    activating_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    activating_product_order_subtotal_excl_tariff_amount_mtd NUMBER(38, 10),
    activating_product_order_subtotal_excl_tariff_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_subtotal_excl_tariff_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_subtotal_excl_tariff_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    nonactivating_product_order_subtotal_excl_tariff_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_subtotal_excl_tariff_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_subtotal_excl_tariff_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_subtotal_excl_tariff_amount_month_tot_ly NUMBER(38, 10),
    guest_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    guest_product_order_subtotal_excl_tariff_amount_mtd NUMBER(38, 10),
    guest_product_order_subtotal_excl_tariff_amount_mtd_ly NUMBER(38, 10),
    guest_product_order_subtotal_excl_tariff_amount_month_tot_lm NUMBER(38, 10),
    guest_product_order_subtotal_excl_tariff_amount_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_order_subtotal_excl_tariff_amount NUMBER(38, 10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_mtd NUMBER(38, 10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_mtd_ly NUMBER(38, 10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_month_tot_lm NUMBER(38, 10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_month_tot_ly NUMBER(38, 10),
    product_order_product_subtotal_amount NUMBER(38, 10),
    product_order_product_subtotal_amount_mtd NUMBER(38, 10),
    product_order_product_subtotal_amount_mtd_ly NUMBER(38, 10),
    product_order_product_subtotal_amount_month_tot_lm NUMBER(38, 10),
    product_order_product_subtotal_amount_month_tot_ly NUMBER(38, 10),
    activating_product_order_product_subtotal_amount NUMBER(38, 10),
    activating_product_order_product_subtotal_amount_mtd NUMBER(38, 10),
    activating_product_order_product_subtotal_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_product_subtotal_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_product_subtotal_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_product_subtotal_amount NUMBER(38, 10),
    nonactivating_product_order_product_subtotal_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_product_subtotal_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_product_subtotal_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_product_subtotal_amount_month_tot_ly NUMBER(38, 10),
    product_order_product_discount_amount NUMBER(38, 10),
    product_order_product_discount_amount_mtd NUMBER(38, 10),
    product_order_product_discount_amount_mtd_ly NUMBER(38, 10),
    product_order_product_discount_amount_month_tot_lm NUMBER(38, 10),
    product_order_product_discount_amount_month_tot_ly NUMBER(38, 10),
    activating_product_order_product_discount_amount NUMBER(38, 10),
    activating_product_order_product_discount_amount_mtd NUMBER(38, 10),
    activating_product_order_product_discount_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_product_discount_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_product_discount_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_product_discount_amount NUMBER(38, 10),
    nonactivating_product_order_product_discount_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_product_discount_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_product_discount_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_product_discount_amount_month_tot_ly NUMBER(38, 10),
    guest_product_order_product_discount_amount NUMBER(38, 10),
    guest_product_order_product_discount_amount_mtd NUMBER(38, 10),
    guest_product_order_product_discount_amount_mtd_ly NUMBER(38, 10),
    guest_product_order_product_discount_amount_month_tot_lm NUMBER(38, 10),
    guest_product_order_product_discount_amount_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_order_product_discount_amount NUMBER(38, 10),
    repeat_vip_product_order_product_discount_amount_mtd NUMBER(38, 10),
    repeat_vip_product_order_product_discount_amount_mtd_ly NUMBER(38, 10),
    repeat_vip_product_order_product_discount_amount_month_tot_lm NUMBER(38, 10),
    repeat_vip_product_order_product_discount_amount_month_tot_ly NUMBER(38, 10),
    shipping_revenue NUMBER(38, 10),
    shipping_revenue_mtd NUMBER(38, 10),
    shipping_revenue_mtd_ly NUMBER(38, 10),
    shipping_revenue_month_tot_lm NUMBER(38, 10),
    shipping_revenue_month_tot_ly NUMBER(38, 10),
    activating_shipping_revenue NUMBER(38, 10),
    activating_shipping_revenue_mtd NUMBER(38, 10),
    activating_shipping_revenue_mtd_ly NUMBER(38, 10),
    activating_shipping_revenue_month_tot_lm NUMBER(38, 10),
    activating_shipping_revenue_month_tot_ly NUMBER(38, 10),
    nonactivating_shipping_revenue NUMBER(38, 10),
    nonactivating_shipping_revenue_mtd NUMBER(38, 10),
    nonactivating_shipping_revenue_mtd_ly NUMBER(38, 10),
    nonactivating_shipping_revenue_month_tot_lm NUMBER(38, 10),
    nonactivating_shipping_revenue_month_tot_ly NUMBER(38, 10),
    guest_shipping_revenue NUMBER(38, 10),
    guest_shipping_revenue_mtd NUMBER(38, 10),
    guest_shipping_revenue_mtd_ly NUMBER(38, 10),
    guest_shipping_revenue_month_tot_lm NUMBER(38, 10),
    guest_shipping_revenue_month_tot_ly NUMBER(38, 10),
    product_order_noncash_credit_redeemed_amount NUMBER(38, 10),
    product_order_noncash_credit_redeemed_amount_mtd NUMBER(38, 10),
    product_order_noncash_credit_redeemed_amount_mtd_ly NUMBER(38, 10),
    product_order_noncash_credit_redeemed_amount_month_tot_lm NUMBER(38, 10),
    product_order_noncash_credit_redeemed_amount_month_tot_ly NUMBER(38, 10),
    activating_product_order_noncash_credit_redeemed_amount NUMBER(38, 10),
    activating_product_order_noncash_credit_redeemed_amount_mtd NUMBER(38, 10),
    activating_product_order_noncash_credit_redeemed_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_noncash_credit_redeemed_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_noncash_credit_redeemed_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_noncash_credit_redeemed_amount NUMBER(38, 10),
    nonactivating_product_order_noncash_credit_redeemed_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_noncash_credit_redeemed_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_noncash_credit_redeemed_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_noncash_credit_redeemed_amount_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_order_noncash_credit_redeemed_amount number(38, 10),
    repeat_vip_product_order_noncash_credit_redeemed_amount_mtd number(38, 10),
    repeat_vip_product_order_noncash_credit_redeemed_amount_mtd_ly number(38, 10),
    repeat_vip_product_order_noncash_credit_redeemed_amount_month_tot_lm number(38, 10),
    repeat_vip_product_order_noncash_credit_redeemed_amount_month_tot_ly number(38, 10),
    product_order_count NUMBER(38),
    product_order_count_mtd NUMBER(38),
    product_order_count_mtd_ly NUMBER(38),
    product_order_count_month_tot_lm NUMBER(38),
    product_order_count_month_tot_ly NUMBER(38),
    activating_product_order_count NUMBER(38),
    activating_product_order_count_mtd NUMBER(38),
    activating_product_order_count_mtd_ly NUMBER(38),
    activating_product_order_count_month_tot_lm NUMBER(38),
    activating_product_order_count_month_tot_ly NUMBER(38),
    activating_product_order_count_budget NUMBER(38),
    activating_product_order_count_budget_alt NUMBER(38),
    activating_product_order_count_forecast NUMBER(38),
    nonactivating_product_order_count NUMBER(38),
    nonactivating_product_order_count_mtd NUMBER(38),
    nonactivating_product_order_count_mtd_ly NUMBER(38),
    nonactivating_product_order_count_month_tot_lm NUMBER(38),
    nonactivating_product_order_count_month_tot_ly NUMBER(38),
    nonactivating_product_order_count_budget NUMBER(38),
    nonactivating_product_order_count_budget_alt NUMBER(38),
    nonactivating_product_order_count_forecast NUMBER(38),
    guest_product_order_count NUMBER(38),
    guest_product_order_count_mtd NUMBER(38),
    guest_product_order_count_mtd_ly NUMBER(38),
    guest_product_order_count_month_tot_lm NUMBER(38),
    guest_product_order_count_month_tot_ly NUMBER(38),
    repeat_vip_product_order_count NUMBER(38),
    repeat_vip_product_order_count_mtd NUMBER(38),
    repeat_vip_product_order_count_mtd_ly NUMBER(38),
    repeat_vip_product_order_count_month_tot_lm NUMBER(38),
    repeat_vip_product_order_count_month_tot_ly NUMBER(38),
    reactivated_vip_product_order_count number(38),
    reactivated_vip_product_order_count_mtd number(38),
    reactivated_vip_product_order_count_mtd_ly number(38),
    reactivated_vip_product_order_count_month_tot_lm number(38),
    reactivated_vip_product_order_count_month_tot_ly number(38),
    product_order_count_excl_seeding number(38),
    product_order_count_excl_seeding_mtd number(38),
    product_order_count_excl_seeding_mtd_ly number(38),
    product_order_count_excl_seeding_month_tot_lm number(38),
    product_order_count_excl_seeding_month_tot_ly number(38),
    activating_product_order_count_excl_seeding number(38),
    activating_product_order_count_excl_seeding_mtd number(38),
    activating_product_order_count_excl_seeding_mtd_ly number(38),
    activating_product_order_count_excl_seeding_month_tot_lm number(38),
    activating_product_order_count_excl_seeding_month_tot_ly number(38),
    nonactivating_product_order_count_excl_seeding number(38),
    nonactivating_product_order_count_excl_seeding_mtd number(38),
    nonactivating_product_order_count_excl_seeding_mtd_ly number(38),
    nonactivating_product_order_count_excl_seeding_month_tot_lm number(38),
    nonactivating_product_order_count_excl_seeding_month_tot_ly number(38),
    guest_product_order_count_excl_seeding number(38),
    guest_product_order_count_excl_seeding_mtd number(38),
    guest_product_order_count_excl_seeding_mtd_ly number(38),
    guest_product_order_count_excl_seeding_month_tot_lm number(38),
    guest_product_order_count_excl_seeding_month_tot_ly number(38),
    repeat_vip_product_order_count_excl_seeding number(38),
    repeat_vip_product_order_count_excl_seeding_mtd number(38),
    repeat_vip_product_order_count_excl_seeding_mtd_ly number(38),
    repeat_vip_product_order_count_excl_seeding_month_tot_lm number(38),
    repeat_vip_product_order_count_excl_seeding_month_tot_ly number(38),
    reactivated_vip_product_order_count_excl_seeding number(38),
    reactivated_vip_product_order_count_excl_seeding_mtd number(38),
    reactivated_vip_product_order_count_excl_seeding_mtd_ly number(38),
    reactivated_vip_product_order_count_excl_seeding_month_tot_lm number(38),
    reactivated_vip_product_order_count_excl_seeding_month_tot_ly number(38),
    product_margin_pre_return_excl_seeding number(38, 12),
    product_margin_pre_return_excl_seeding_mtd number(38, 12),
    product_margin_pre_return_excl_seeding_mtd_ly number(38, 12),
    product_margin_pre_return_excl_seeding_month_tot_lm number(38, 12),
    product_margin_pre_return_excl_seeding_month_tot_ly number(38, 12),
    activating_product_margin_pre_return_excl_seeding number(38, 12),
    activating_product_margin_pre_return_excl_seeding_mtd number(38, 12),
    activating_product_margin_pre_return_excl_seeding_mtd_ly number(38, 12),
    activating_product_margin_pre_return_excl_seeding_month_tot_lm number(38, 12),
    activating_product_margin_pre_return_excl_seeding_month_tot_ly number(38, 12),
    nonactivating_product_margin_pre_return_excl_seeding number(38, 12),
    nonactivating_product_margin_pre_return_excl_seeding_mtd number(38, 12),
    nonactivating_product_margin_pre_return_excl_seeding_mtd_ly number(38, 12),
    nonactivating_product_margin_pre_return_excl_seeding_month_tot_lm number(38, 12),
    nonactivating_product_margin_pre_return_excl_seeding_month_tot_ly number(38, 12),
    guest_product_margin_pre_return_excl_seeding number(38, 12),
    guest_product_margin_pre_return_excl_seeding_mtd number(38, 12),
    guest_product_margin_pre_return_excl_seeding_mtd_ly number(38, 12),
    guest_product_margin_pre_return_excl_seeding_month_tot_lm number(38, 12),
    guest_product_margin_pre_return_excl_seeding_month_tot_ly number(38, 12),
    repeat_vip_product_margin_pre_return_excl_seeding number(38, 12),
    repeat_vip_product_margin_pre_return_excl_seeding_mtd number(38, 12),
    repeat_vip_product_margin_pre_return_excl_seeding_mtd_ly number(38, 12),
    repeat_vip_product_margin_pre_return_excl_seeding_month_tot_lm number(38, 12),
    repeat_vip_product_margin_pre_return_excl_seeding_month_tot_ly number(38, 12),
    reactivated_vip_product_margin_pre_return_excl_seeding number(38, 12),
    reactivated_vip_product_margin_pre_return_excl_seeding_mtd number(38, 12),
    reactivated_vip_product_margin_pre_return_excl_seeding_mtd_ly number(38, 12),
    reactivated_vip_product_margin_pre_return_excl_seeding_month_tot_lm number(38, 12),
    reactivated_vip_product_margin_pre_return_excl_seeding_month_tot_ly number(38, 12),
    unit_count NUMBER(38),
    unit_count_mtd NUMBER(38),
    unit_count_mtd_ly NUMBER(38),
    unit_count_month_tot_lm NUMBER(38),
    unit_count_month_tot_ly NUMBER(38),
    unit_count_budget NUMBER(38),
    unit_count_budget_alt NUMBER(38),
    unit_count_forecast NUMBER(38),
    activating_unit_count NUMBER(38),
    activating_unit_count_mtd NUMBER(38),
    activating_unit_count_mtd_ly NUMBER(38),
    activating_unit_count_month_tot_lm NUMBER(38),
    activating_unit_count_month_tot_ly NUMBER(38),
    activating_unit_count_budget NUMBER(38),
    activating_unit_count_budget_alt NUMBER(38),
    activating_unit_count_forecast NUMBER(38),
    nonactivating_unit_count NUMBER(38),
    nonactivating_unit_count_mtd NUMBER(38),
    nonactivating_unit_count_mtd_ly NUMBER(38),
    nonactivating_unit_count_month_tot_lm NUMBER(38),
    nonactivating_unit_count_month_tot_ly NUMBER(38),
    nonactivating_unit_count_budget NUMBER(38),
    nonactivating_unit_count_budget_alt NUMBER(38),
    nonactivating_unit_count_forecast NUMBER(38),
    guest_unit_count NUMBER(38),
    guest_unit_count_mtd NUMBER(38),
    guest_unit_count_mtd_ly NUMBER(38),
    guest_unit_count_month_tot_lm NUMBER(38),
    guest_unit_count_month_tot_ly NUMBER(38),
    repeat_vip_unit_count NUMBER(38),
    repeat_vip_unit_count_mtd NUMBER(38),
    repeat_vip_unit_count_mtd_ly NUMBER(38),
    repeat_vip_unit_count_month_tot_lm NUMBER(38),
    repeat_vip_unit_count_month_tot_ly NUMBER(38),
    activating_product_order_air_vip_price NUMBER(38, 10),
    activating_product_order_air_vip_price_mtd NUMBER(38, 10),
    activating_product_order_air_vip_price_mtd_ly NUMBER(38, 10),
    activating_product_order_air_vip_price_month_tot_lm NUMBER(38, 10),
    activating_product_order_air_vip_price_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_air_price NUMBER(38, 10),
    nonactivating_product_order_air_price_mtd NUMBER(38, 10),
    nonactivating_product_order_air_price_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_air_price_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_air_price_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_order_air_vip_price NUMBER(38, 10),
    repeat_vip_product_order_air_vip_price_mtd NUMBER(38, 10),
    repeat_vip_product_order_air_vip_price_mtd_ly NUMBER(38, 10),
    repeat_vip_product_order_air_vip_price_month_tot_lm NUMBER(38, 10),
    repeat_vip_product_order_air_vip_price_month_tot_ly NUMBER(38, 10),
    guest_product_order_air_vip_price number(38, 10),
    guest_product_order_air_vip_price_mtd number(38, 10),
    guest_product_order_air_vip_price_mtd_ly number(38, 10),
    guest_product_order_air_vip_price_month_tot_lm number(38, 10),
    guest_product_order_air_vip_price_month_tot_ly number(38, 10),
    guest_product_order_retail_unit_price NUMBER(38, 10),
    guest_product_order_retail_unit_price_mtd NUMBER(38, 10),
    guest_product_order_retail_unit_price_mtd_ly NUMBER(38, 10),
    guest_product_order_retail_unit_price_month_tot_lm NUMBER(38, 10),
    guest_product_order_retail_unit_price_month_tot_ly NUMBER(38, 10),
    activating_product_order_price_offered_amount NUMBER(38, 10),
    activating_product_order_price_offered_amount_mtd NUMBER(38, 10),
    activating_product_order_price_offered_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_price_offered_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_price_offered_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_price_offered_amount NUMBER(38, 10),
    nonactivating_product_order_price_offered_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_price_offered_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_price_offered_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_price_offered_amount_month_tot_ly NUMBER(38, 10),
    guest_product_order_price_offered_amount NUMBER(38, 10),
    guest_product_order_price_offered_amount_mtd NUMBER(38, 10),
    guest_product_order_price_offered_amount_mtd_ly NUMBER(38, 10),
    guest_product_order_price_offered_amount_month_tot_lm NUMBER(38, 10),
    guest_product_order_price_offered_amount_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_order_price_offered_amount NUMBER(38, 10),
    repeat_vip_product_order_price_offered_amount_mtd NUMBER(38, 10),
    repeat_vip_product_order_price_offered_amount_mtd_ly NUMBER(38, 10),
    repeat_vip_product_order_price_offered_amount_month_tot_lm NUMBER(38, 10),
    repeat_vip_product_order_price_offered_amount_month_tot_ly NUMBER(38, 10),
    product_order_landed_product_cost_amount NUMBER(38, 10),
    product_order_landed_product_cost_amount_mtd NUMBER(38, 10),
    product_order_landed_product_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_landed_product_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_landed_product_cost_amount_month_tot_ly NUMBER(38, 10),
    activating_product_order_landed_product_cost_amount NUMBER(38, 10),
    activating_product_order_landed_product_cost_amount_mtd NUMBER(38, 10),
    activating_product_order_landed_product_cost_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_landed_product_cost_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_landed_product_cost_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_landed_product_cost_amount NUMBER(38, 10),
    nonactivating_product_order_landed_product_cost_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_landed_product_cost_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_landed_product_cost_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_landed_product_cost_amount_month_tot_ly NUMBER(38, 10),
    guest_product_order_landed_product_cost_amount number(38, 10),
    guest_product_order_landed_product_cost_amount_mtd number(38, 10),
    guest_product_order_landed_product_cost_amount_mtd_ly number(38, 10),
    guest_product_order_landed_product_cost_amount_month_tot_lm number(38, 10),
    guest_product_order_landed_product_cost_amount_month_tot_ly number(38, 10),
    repeat_vip_product_order_landed_product_cost_amount number(38, 10),
    repeat_vip_product_order_landed_product_cost_amount_mtd number(38, 10),
    repeat_vip_product_order_landed_product_cost_amount_mtd_ly number(38, 10),
    repeat_vip_product_order_landed_product_cost_amount_month_tot_lm number(38, 10),
    repeat_vip_product_order_landed_product_cost_amount_month_tot_ly number(38, 10),
    oracle_product_order_landed_product_cost_amount NUMBER(38, 10),
    oracle_product_order_landed_product_cost_amount_mtd NUMBER(38, 10),
    oracle_product_order_landed_product_cost_amount_mtd_ly NUMBER(38, 10),
    oracle_product_order_landed_product_cost_amount_month_tot_lm NUMBER(38, 10),
    oracle_product_order_landed_product_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_shipping_cost_amount NUMBER(38, 10),
    product_order_shipping_cost_amount_mtd NUMBER(38, 10),
    product_order_shipping_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_shipping_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_shipping_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_shipping_supplies_cost_amount NUMBER(38, 10),
    product_order_shipping_supplies_cost_amount_mtd NUMBER(38, 10),
    product_order_shipping_supplies_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_shipping_supplies_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_shipping_supplies_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_direct_cogs_amount NUMBER(38, 10),
    product_order_direct_cogs_amount_mtd NUMBER(38, 10),
    product_order_direct_cogs_amount_mtd_ly NUMBER(38, 10),
    product_order_direct_cogs_amount_month_tot_lm NUMBER(38, 10),
    product_order_direct_cogs_amount_month_tot_ly NUMBER(38, 10),
    product_order_cash_refund_amount NUMBER(38, 10),
    product_order_cash_refund_amount_mtd NUMBER(38, 10),
    product_order_cash_refund_amount_mtd_ly NUMBER(38, 10),
    product_order_cash_refund_amount_month_tot_lm NUMBER(38, 10),
    product_order_cash_refund_amount_month_tot_ly NUMBER(38, 10),
    product_order_cash_chargeback_amount NUMBER(38, 10),
    product_order_cash_chargeback_amount_mtd NUMBER(38, 10),
    product_order_cash_chargeback_amount_mtd_ly NUMBER(38, 10),
    product_order_cash_chargeback_amount_month_tot_lm NUMBER(38, 10),
    product_order_cash_chargeback_amount_month_tot_ly NUMBER(38, 10),
    product_cost_returned_resaleable_incl_reship_exch NUMBER(38, 10),
    product_cost_returned_resaleable_incl_reship_exch_mtd NUMBER(38, 10),
    product_cost_returned_resaleable_incl_reship_exch_mtd_ly NUMBER(38, 10),
    product_cost_returned_resaleable_incl_reship_exch_month_tot_lm NUMBER(38, 10),
    product_cost_returned_resaleable_incl_reship_exch_month_tot_ly NUMBER(38, 10),
    product_order_cost_product_returned_damaged_amount NUMBER(38, 10),
    product_order_cost_product_returned_damaged_amount_mtd NUMBER(38, 10),
    product_order_cost_product_returned_damaged_amount_mtd_ly NUMBER(38, 10),
    product_order_cost_product_returned_damaged_amount_month_tot_lm NUMBER(38, 10),
    product_order_cost_product_returned_damaged_amount_month_tot_ly NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch_mtd NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch_mtd_ly NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch_month_tot_lm NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch_month_tot_ly NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch_budget NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch_budget_alt NUMBER(38, 10),
    return_shipping_costs_incl_reship_exch_forecast NUMBER(38, 10),
    product_order_reship_order_count NUMBER(38),
    product_order_reship_order_count_mtd NUMBER(38),
    product_order_reship_order_count_mtd_ly NUMBER(38),
    product_order_reship_order_count_month_tot_lm NUMBER(38),
    product_order_reship_order_count_month_tot_ly NUMBER(38),
    product_order_reship_unit_count NUMBER(38),
    product_order_reship_unit_count_mtd NUMBER(38),
    product_order_reship_unit_count_mtd_ly NUMBER(38),
    product_order_reship_unit_count_month_tot_lm NUMBER(38),
    product_order_reship_unit_count_month_tot_ly NUMBER(38),
    activating_product_order_reship_unit_count NUMBER(38),
    activating_product_order_reship_unit_count_mtd NUMBER(38),
    activating_product_order_reship_unit_count_mtd_ly NUMBER(38),
    activating_product_order_reship_unit_count_month_tot_lm NUMBER(38),
    activating_product_order_reship_unit_count_month_tot_ly NUMBER(38),
    nonactivating_product_order_reship_unit_count NUMBER(38),
    nonactivating_product_order_reship_unit_count_mtd NUMBER(38),
    nonactivating_product_order_reship_unit_count_mtd_ly NUMBER(38),
    nonactivating_product_order_reship_unit_count_month_tot_lm NUMBER(38),
    nonactivating_product_order_reship_unit_count_month_tot_ly NUMBER(38),
    guest_product_order_reship_unit_count number(38),
    guest_product_order_reship_unit_count_mtd number(38),
    guest_product_order_reship_unit_count_mtd_ly number(38),
    guest_product_order_reship_unit_count_month_tot_lm number(38),
    guest_product_order_reship_unit_count_month_tot_ly number(38),
    repeat_vip_product_order_reship_unit_count number(38),
    repeat_vip_product_order_reship_unit_count_mtd number(38),
    repeat_vip_product_order_reship_unit_count_mtd_ly number(38),
    repeat_vip_product_order_reship_unit_count_month_tot_lm number(38),
    repeat_vip_product_order_reship_unit_count_month_tot_ly number(38),
    total_cogs_budget NUMBER(38, 10),
    total_cogs_budget_alt NUMBER(38, 10),
    total_cogs_forecast NUMBER(38, 10),
    product_order_reship_product_cost_amount NUMBER(38, 10),
    product_order_reship_product_cost_amount_mtd NUMBER(38, 10),
    product_order_reship_product_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_reship_product_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_reship_product_cost_amount_month_tot_ly NUMBER(38, 10),
    activating_product_order_reship_product_cost_amount NUMBER(38, 10),
    activating_product_order_reship_product_cost_amount_mtd NUMBER(38, 10),
    activating_product_order_reship_product_cost_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_reship_product_cost_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_reship_product_cost_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_reship_product_cost_amount NUMBER(38, 10),
    nonactivating_product_order_reship_product_cost_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_reship_product_cost_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_reship_product_cost_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_reship_product_cost_amount_month_tot_ly NUMBER(38, 10),
    guest_product_order_reship_product_cost_amount number(38, 10),
    guest_product_order_reship_product_cost_amount_mtd number(38, 10),
    guest_product_order_reship_product_cost_amount_mtd_ly number(38, 10),
    guest_product_order_reship_product_cost_amount_month_tot_lm number(38, 10),
    guest_product_order_reship_product_cost_amount_month_tot_ly number(38, 10),
    repeat_vip_product_order_reship_product_cost_amount number(38, 10),
    repeat_vip_product_order_reship_product_cost_amount_mtd number(38, 10),
    repeat_vip_product_order_reship_product_cost_amount_mtd_ly number(38, 10),
    repeat_vip_product_order_reship_product_cost_amount_month_tot_lm number(38, 10),
    repeat_vip_product_order_reship_product_cost_amount_month_tot_ly number(38, 10),
    oracle_product_order_reship_product_cost_amount NUMBER(38, 10),
    oracle_product_order_reship_product_cost_amount_mtd NUMBER(38, 10),
    oracle_product_order_reship_product_cost_amount_mtd_ly NUMBER(38, 10),
    oracle_product_order_reship_product_cost_amount_month_tot_lm NUMBER(38, 10),
    oracle_product_order_reship_product_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_reship_shipping_cost_amount NUMBER(38, 10),
    product_order_reship_shipping_cost_amount_mtd NUMBER(38, 10),
    product_order_reship_shipping_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_reship_shipping_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_reship_shipping_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_reship_shipping_supplies_cost_amount NUMBER(38, 10),
    product_order_reship_shipping_supplies_cost_amount_mtd NUMBER(38, 10),
    product_order_reship_shipping_supplies_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_reship_shipping_supplies_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_reship_shipping_supplies_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_exchange_order_count NUMBER(38),
    product_order_exchange_order_count_mtd NUMBER(38),
    product_order_exchange_order_count_mtd_ly NUMBER(38),
    product_order_exchange_order_count_month_tot_lm NUMBER(38),
    product_order_exchange_order_count_month_tot_ly NUMBER(38),
    product_order_reship_exch_order_count_budget NUMBER(38),
    product_order_reship_exch_order_count_budget_alt NUMBER(38),
    product_order_reship_exch_order_count_forecast NUMBER(38),
    product_order_exchange_unit_count NUMBER(38),
    product_order_exchange_unit_count_mtd NUMBER(38),
    product_order_exchange_unit_count_mtd_ly NUMBER(38),
    product_order_exchange_unit_count_month_tot_lm NUMBER(38),
    product_order_exchange_unit_count_month_tot_ly NUMBER(38),
    activating_product_order_exchange_unit_count NUMBER(38),
    activating_product_order_exchange_unit_count_mtd NUMBER(38),
    activating_product_order_exchange_unit_count_mtd_ly NUMBER(38),
    activating_product_order_exchange_unit_count_month_tot_lm NUMBER(38),
    activating_product_order_exchange_unit_count_month_tot_ly NUMBER(38),
    nonactivating_product_order_exchange_unit_count NUMBER(38),
    nonactivating_product_order_exchange_unit_count_mtd NUMBER(38),
    nonactivating_product_order_exchange_unit_count_mtd_ly NUMBER(38),
    nonactivating_product_order_exchange_unit_count_month_tot_lm NUMBER(38),
    nonactivating_product_order_exchange_unit_count_month_tot_ly NUMBER(38),
    guest_product_order_exchange_unit_count number(38),
    guest_product_order_exchange_unit_count_mtd number(38),
    guest_product_order_exchange_unit_count_mtd_ly number(38),
    guest_product_order_exchange_unit_count_month_tot_lm number(38),
    guest_product_order_exchange_unit_count_month_tot_ly number(38),
    repeat_vip_product_order_exchange_unit_count number(38),
    repeat_vip_product_order_exchange_unit_count_mtd number(38),
    repeat_vip_product_order_exchange_unit_count_mtd_ly number(38),
    repeat_vip_product_order_exchange_unit_count_month_tot_lm number(38),
    repeat_vip_product_order_exchange_unit_count_month_tot_ly number(38),
    product_order_exchange_product_cost_amount NUMBER(38, 10),
    product_order_exchange_product_cost_amount_mtd NUMBER(38, 10),
    product_order_exchange_product_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_exchange_product_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_exchange_product_cost_amount_month_tot_ly NUMBER(38, 10),
    activating_product_order_exchange_product_cost_amount NUMBER(38, 10),
    activating_product_order_exchange_product_cost_amount_mtd NUMBER(38, 10),
    activating_product_order_exchange_product_cost_amount_mtd_ly NUMBER(38, 10),
    activating_product_order_exchange_product_cost_amount_month_tot_lm NUMBER(38, 10),
    activating_product_order_exchange_product_cost_amount_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_exchange_product_cost_amount NUMBER(38, 10),
    nonactivating_product_order_exchange_product_cost_amount_mtd NUMBER(38, 10),
    nonactivating_product_order_exchange_product_cost_amount_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_exchange_product_cost_amount_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_exchange_product_cost_amount_month_tot_ly NUMBER(38, 10),
    guest_product_order_exchange_product_cost_amount number(38, 10),
    guest_product_order_exchange_product_cost_amount_mtd number(38, 10),
    guest_product_order_exchange_product_cost_amount_mtd_ly number(38, 10),
    guest_product_order_exchange_product_cost_amount_month_tot_lm number(38, 10),
    guest_product_order_exchange_product_cost_amount_month_tot_ly number(38, 10),
    repeat_vip_product_order_exchange_product_cost_amount number(38, 10),
    repeat_vip_product_order_exchange_product_cost_amount_mtd number(38, 10),
    repeat_vip_product_order_exchange_product_cost_amount_mtd_ly number(38, 10),
    repeat_vip_product_order_exchange_product_cost_amount_month_tot_lm number(38, 10),
    repeat_vip_product_order_exchange_product_cost_amount_month_tot_ly number(38, 10),
    oracle_product_order_exchange_product_cost_amount NUMBER(38, 10),
    oracle_product_order_exchange_product_cost_amount_mtd NUMBER(38, 10),
    oracle_product_order_exchange_product_cost_amount_mtd_ly NUMBER(38, 10),
    oracle_product_order_exchange_product_cost_amount_month_tot_lm NUMBER(38, 10),
    oracle_product_order_exchange_product_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_exchange_shipping_cost_amount NUMBER(38, 10),
    product_order_exchange_shipping_cost_amount_mtd NUMBER(38, 10),
    product_order_exchange_shipping_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_exchange_shipping_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_exchange_shipping_cost_amount_month_tot_ly NUMBER(38, 10),
    product_order_exchange_shipping_supplies_cost_amount NUMBER(38, 10),
    product_order_exchange_shipping_supplies_cost_amount_mtd NUMBER(38, 10),
    product_order_exchange_shipping_supplies_cost_amount_mtd_ly NUMBER(38, 10),
    product_order_exchange_shipping_supplies_cost_amount_month_tot_lm NUMBER(38, 10),
    product_order_exchange_shipping_supplies_cost_amount_month_tot_ly NUMBER(38, 10),
    product_gross_revenue NUMBER(38, 10),
    product_gross_revenue_mtd NUMBER(38, 10),
    product_gross_revenue_mtd_ly NUMBER(38, 10),
    product_gross_revenue_month_tot_lm NUMBER(38, 10),
    product_gross_revenue_month_tot_ly NUMBER(38, 10),
    activating_product_gross_revenue NUMBER(38, 10),
    activating_product_gross_revenue_mtd NUMBER(38, 10),
    activating_product_gross_revenue_mtd_ly NUMBER(38, 10),
    activating_product_gross_revenue_month_tot_lm NUMBER(38, 10),
    activating_product_gross_revenue_month_tot_ly NUMBER(38, 10),
    activating_product_gross_revenue_budget NUMBER(38, 10),
    activating_product_gross_revenue_budget_alt NUMBER(38, 10),
    activating_product_gross_revenue_forecast NUMBER(38, 10),
    nonactivating_product_gross_revenue NUMBER(38, 10),
    nonactivating_product_gross_revenue_mtd NUMBER(38, 10),
    nonactivating_product_gross_revenue_mtd_ly NUMBER(38, 10),
    nonactivating_product_gross_revenue_month_tot_lm NUMBER(38, 10),
    nonactivating_product_gross_revenue_month_tot_ly NUMBER(38, 10),
    nonactivating_product_gross_revenue_budget NUMBER(38, 10),
    nonactivating_product_gross_revenue_budget_alt NUMBER(38, 10),
    nonactivating_product_gross_revenue_forecast NUMBER(38, 10),
    guest_product_gross_revenue NUMBER(38, 10),
    guest_product_gross_revenue_mtd NUMBER(38, 10),
    guest_product_gross_revenue_mtd_ly NUMBER(38, 10),
    guest_product_gross_revenue_month_tot_lm NUMBER(38, 10),
    guest_product_gross_revenue_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_gross_revenue NUMBER(38, 10),
    repeat_vip_product_gross_revenue_mtd NUMBER(38, 10),
    repeat_vip_product_gross_revenue_mtd_ly NUMBER(38, 10),
    repeat_vip_product_gross_revenue_month_tot_lm NUMBER(38, 10),
    repeat_vip_product_gross_revenue_month_tot_ly NUMBER(38, 10),
    product_net_revenue NUMBER(38, 10),
    product_net_revenue_mtd NUMBER(38, 10),
    product_net_revenue_mtd_ly NUMBER(38, 10),
    product_net_revenue_month_tot_lm NUMBER(38, 10),
    product_net_revenue_month_tot_ly NUMBER(38, 10),
    activating_product_net_revenue NUMBER(38, 10),
    activating_product_net_revenue_mtd NUMBER(38, 10),
    activating_product_net_revenue_mtd_ly NUMBER(38, 10),
    activating_product_net_revenue_month_tot_lm NUMBER(38, 10),
    activating_product_net_revenue_month_tot_ly NUMBER(38, 10),
    activating_product_net_revenue_budget NUMBER(38, 10),
    activating_product_net_revenue_budget_alt NUMBER(38, 10),
    activating_product_net_revenue_forecast NUMBER(38, 10),
    nonactivating_product_net_revenue NUMBER(38, 10),
    nonactivating_product_net_revenue_mtd NUMBER(38, 10),
    nonactivating_product_net_revenue_mtd_ly NUMBER(38, 10),
    nonactivating_product_net_revenue_month_tot_lm NUMBER(38, 10),
    nonactivating_product_net_revenue_month_tot_ly NUMBER(38, 10),
    nonactivating_product_net_revenue_budget NUMBER(38, 10),
    nonactivating_product_net_revenue_budget_alt NUMBER(38, 10),
    nonactivating_product_net_revenue_forecast NUMBER(38, 10),
    guest_product_net_revenue NUMBER(38, 10),
    guest_product_net_revenue_mtd NUMBER(38, 10),
    guest_product_net_revenue_mtd_ly NUMBER(38, 10),
    guest_product_net_revenue_month_tot_lm NUMBER(38, 10),
    guest_product_net_revenue_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_net_revenue NUMBER(38, 10),
    repeat_vip_product_net_revenue_mtd NUMBER(38, 10),
    repeat_vip_product_net_revenue_mtd_ly NUMBER(38, 10),
    repeat_vip_product_net_revenue_month_tot_lm NUMBER(38, 10),
    repeat_vip_product_net_revenue_month_tot_ly NUMBER(38, 10),
    product_margin_pre_return NUMBER(38, 10),
    product_margin_pre_return_mtd NUMBER(38, 10),
    product_margin_pre_return_mtd_ly NUMBER(38, 10),
    product_margin_pre_return_month_tot_lm NUMBER(38, 10),
    product_margin_pre_return_month_tot_ly NUMBER(38, 10),
    activating_product_margin_pre_return NUMBER(38, 10),
    activating_product_margin_pre_return_mtd NUMBER(38, 10),
    activating_product_margin_pre_return_mtd_ly NUMBER(38, 10),
    activating_product_margin_pre_return_month_tot_lm NUMBER(38, 10),
    activating_product_margin_pre_return_month_tot_ly NUMBER(38, 10),
    activating_product_margin_pre_return_budget NUMBER(38, 10),
    activating_product_margin_pre_return_budget_alt NUMBER(38, 10),
    activating_product_margin_pre_return_forecast NUMBER(38, 10),
    first_guest_product_margin_pre_return NUMBER(38, 10),
    first_guest_product_margin_pre_return_mtd NUMBER(38, 10),
    first_guest_product_margin_pre_return_mtd_ly NUMBER(38, 10),
    first_guest_product_margin_pre_return_month_tot_lm NUMBER(38, 10),
    first_guest_product_margin_pre_return_month_tot_ly NUMBER(38, 10),
    product_gross_profit NUMBER(38, 10),
    product_gross_profit_mtd NUMBER(38, 10),
    product_gross_profit_mtd_ly NUMBER(38, 10),
    product_gross_profit_month_tot_lm NUMBER(38, 10),
    product_gross_profit_month_tot_ly NUMBER(38, 10),
    activating_product_gross_profit NUMBER(38, 10),
    activating_product_gross_profit_mtd NUMBER(38, 10),
    activating_product_gross_profit_mtd_ly NUMBER(38, 10),
    activating_product_gross_profit_month_tot_lm NUMBER(38, 10),
    activating_product_gross_profit_month_tot_ly NUMBER(38, 10),
    activating_product_gross_profit_budget NUMBER(38, 10),
    activating_product_gross_profit_budget_alt NUMBER(38, 10),
    activating_product_gross_profit_forecast NUMBER(38, 10),
    nonactivating_product_gross_profit NUMBER(38, 10),
    nonactivating_product_gross_profit_mtd NUMBER(38, 10),
    nonactivating_product_gross_profit_mtd_ly NUMBER(38, 10),
    nonactivating_product_gross_profit_month_tot_lm NUMBER(38, 10),
    nonactivating_product_gross_profit_month_tot_ly NUMBER(38, 10),
    nonactivating_product_gross_profit_budget NUMBER(38, 10),
    nonactivating_product_gross_profit_budget_alt NUMBER(38, 10),
    nonactivating_product_gross_profit_forecast NUMBER(38, 10),
    guest_product_gross_profit NUMBER(38, 10),
    guest_product_gross_profit_mtd NUMBER(38, 10),
    guest_product_gross_profit_mtd_ly NUMBER(38, 10),
    guest_product_gross_profit_month_tot_lm NUMBER(38, 10),
    guest_product_gross_profit_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_gross_profit NUMBER(38, 10),
    repeat_vip_product_gross_profit_mtd NUMBER(38, 10),
    repeat_vip_product_gross_profit_mtd_ly NUMBER(38, 10),
    repeat_vip_product_gross_profit_month_tot_lm NUMBER(38, 10),
    repeat_vip_product_gross_profit_month_tot_ly NUMBER(38, 10),
    product_order_cash_gross_revenue NUMBER(38, 10),
    product_order_cash_gross_revenue_mtd NUMBER(38, 10),
    product_order_cash_gross_revenue_mtd_ly NUMBER(38, 10),
    product_order_cash_gross_revenue_month_tot_lm NUMBER(38, 10),
    product_order_cash_gross_revenue_month_tot_ly NUMBER(38, 10),
    activating_product_order_cash_gross_revenue NUMBER(38, 10),
    activating_product_order_cash_gross_revenue_mtd NUMBER(38, 10),
    activating_product_order_cash_gross_revenue_mtd_ly NUMBER(38, 10),
    activating_product_order_cash_gross_revenue_month_tot_lm NUMBER(38, 10),
    activating_product_order_cash_gross_revenue_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue_mtd NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue_budget NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue_budget_alt NUMBER(38, 10),
    nonactivating_product_order_cash_gross_revenue_forecast NUMBER(38, 10),
    cash_gross_revenue NUMBER(38, 10),
    cash_gross_revenue_mtd NUMBER(38, 10),
    cash_gross_revenue_mtd_ly NUMBER(38, 10),
    cash_gross_revenue_month_tot_lm NUMBER(38, 10),
    cash_gross_revenue_month_tot_ly NUMBER(38, 10),
    cash_gross_revenue_budget NUMBER(38, 10),
    cash_gross_revenue_budget_alt NUMBER(38, 10),
    cash_gross_revenue_forecast NUMBER(38, 10),
    activating_cash_gross_revenue NUMBER(38, 10),
    activating_cash_gross_revenue_mtd NUMBER(38, 10),
    activating_cash_gross_revenue_mtd_ly NUMBER(38, 10),
    activating_cash_gross_revenue_month_tot_lm NUMBER(38, 10),
    activating_cash_gross_revenue_month_tot_ly NUMBER(38, 10),
    nonactivating_cash_gross_revenue NUMBER(38, 10),
    nonactivating_cash_gross_revenue_mtd NUMBER(38, 10),
    nonactivating_cash_gross_revenue_mtd_ly NUMBER(38, 10),
    nonactivating_cash_gross_revenue_month_tot_lm NUMBER(38, 10),
    nonactivating_cash_gross_revenue_month_tot_ly NUMBER(38, 10),
    cash_net_revenue NUMBER(38, 10),
    cash_net_revenue_mtd NUMBER(38, 10),
    cash_net_revenue_mtd_ly NUMBER(38, 10),
    cash_net_revenue_month_tot_lm NUMBER(38, 10),
    cash_net_revenue_month_tot_ly NUMBER(38, 10),
    cash_net_revenue_budget NUMBER(38, 10),
    cash_net_revenue_budget_alt NUMBER(38, 10),
    cash_net_revenue_forecast NUMBER(38, 10),
    activating_cash_net_revenue NUMBER(38, 10),
    activating_cash_net_revenue_mtd NUMBER(38, 10),
    activating_cash_net_revenue_mtd_ly NUMBER(38, 10),
    activating_cash_net_revenue_month_tot_lm NUMBER(38, 10),
    activating_cash_net_revenue_month_tot_ly NUMBER(38, 10),
    activating_cash_net_revenue_budget NUMBER(38, 10),
    activating_cash_net_revenue_budget_alt NUMBER(38, 10),
    activating_cash_net_revenue_forecast NUMBER(38, 10),
    nonactivating_cash_net_revenue NUMBER(38, 10),
    nonactivating_cash_net_revenue_mtd NUMBER(38, 10),
    nonactivating_cash_net_revenue_mtd_ly NUMBER(38, 10),
    nonactivating_cash_net_revenue_month_tot_lm NUMBER(38, 10),
    nonactivating_cash_net_revenue_month_tot_ly NUMBER(38, 10),
    nonactivating_cash_net_revenue_budget NUMBER(38, 10),
    nonactivating_cash_net_revenue_budget_alt NUMBER(38, 10),
    nonactivating_cash_net_revenue_forecast NUMBER(38, 10),
    cash_net_revenue_budgeted_fx NUMBER(38, 10),
    cash_net_revenue_budgeted_fx_mtd NUMBER(38, 10),
    cash_net_revenue_budgeted_fx_mtd_ly NUMBER(38, 10),
    cash_net_revenue_budgeted_fx_month_tot_lm NUMBER(38, 10),
    cash_net_revenue_budgeted_fx_month_tot_ly NUMBER(38, 10),
    cash_gross_profit NUMBER(38, 10),
    cash_gross_profit_mtd NUMBER(38, 10),
    cash_gross_profit_mtd_ly NUMBER(38, 10),
    cash_gross_profit_month_tot_lm NUMBER(38, 10),
    cash_gross_profit_month_tot_ly NUMBER(38, 10),
    cash_gross_profit_budget NUMBER(38, 10),
    cash_gross_profit_budget_alt NUMBER(38, 10),
    cash_gross_profit_forecast NUMBER(38, 10),
    nonactivating_cash_gross_profit NUMBER(38, 10),
    nonactivating_cash_gross_profit_mtd NUMBER(38, 10),
    nonactivating_cash_gross_profit_mtd_ly NUMBER(38, 10),
    nonactivating_cash_gross_profit_month_tot_lm NUMBER(38, 10),
    nonactivating_cash_gross_profit_month_tot_ly NUMBER(38, 10),
    nonactivating_cash_gross_profit_budget NUMBER(38, 10),
    nonactivating_cash_gross_profit_budget_alt NUMBER(38, 10),
    nonactivating_cash_gross_profit_forecast NUMBER(38, 10),
    billed_credit_cash_transaction_count NUMBER(38),
    billed_credit_cash_transaction_count_mtd NUMBER(38),
    billed_credit_cash_transaction_count_mtd_ly NUMBER(38),
    billed_credit_cash_transaction_count_month_tot_lm NUMBER(38),
    billed_credit_cash_transaction_count_month_tot_ly NUMBER(38),
    billed_credits_successful_on_retry NUMBER(38),
    billed_credits_successful_on_retry_mtd NUMBER(38),
    billed_credits_successful_on_retry_mtd_ly NUMBER(38),
    billed_credits_successful_on_retry_month_tot_lm NUMBER(38),
    billed_credits_successful_on_retry_month_tot_ly NUMBER(38),
    billing_cash_refund_amount NUMBER(38, 10),
    billing_cash_refund_amount_mtd NUMBER(38, 10),
    billing_cash_refund_amount_mtd_ly NUMBER(38, 10),
    billing_cash_refund_amount_month_tot_lm NUMBER(38, 10),
    billing_cash_refund_amount_month_tot_ly NUMBER(38, 10),
    billing_cash_chargeback_amount NUMBER(38, 10),
    billing_cash_chargeback_amount_mtd NUMBER(38, 10),
    billing_cash_chargeback_amount_mtd_ly NUMBER(38, 10),
    billing_cash_chargeback_amount_month_tot_lm NUMBER(38, 10),
    billing_cash_chargeback_amount_month_tot_ly NUMBER(38, 10),
    billed_credit_cash_transaction_amount NUMBER(38, 10),
    billed_credit_cash_transaction_amount_mtd NUMBER(38, 10),
    billed_credit_cash_transaction_amount_mtd_ly NUMBER(38, 10),
    billed_credit_cash_transaction_amount_month_tot_lm NUMBER(38, 10),
    billed_credit_cash_transaction_amount_month_tot_ly NUMBER(38, 10),
    billed_credit_cash_transaction_amount_budget NUMBER(38, 10),
    billed_credit_cash_transaction_amount_budget_alt NUMBER(38, 10),
    billed_credit_cash_transaction_amount_forecast NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount_mtd NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount_mtd_ly NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount_month_tot_lm NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount_month_tot_ly NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount_budget NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount_budget_alt NUMBER(38, 10),
    billed_credit_cash_refund_chargeback_amount_forecast NUMBER(38, 10),
    activating_billed_cash_credit_redeemed_amount NUMBER(38,10),
    billed_cash_credit_redeemed_amount NUMBER(38, 10),
    billed_cash_credit_redeemed_amount_mtd NUMBER(38, 10),
    billed_cash_credit_redeemed_amount_mtd_ly NUMBER(38, 10),
    billed_cash_credit_redeemed_amount_month_tot_lm NUMBER(38, 10),
    billed_cash_credit_redeemed_amount_month_tot_ly NUMBER(38, 10),
    billed_cash_credit_redeemed_amount_budget NUMBER(38, 10),
    billed_cash_credit_redeemed_amount_budget_alt NUMBER(38, 10),
    billed_cash_credit_redeemed_amount_forecast NUMBER(38, 10),
    misc_cogs_amount NUMBER(38, 10),
    misc_cogs_amount_mtd NUMBER(38, 10),
    misc_cogs_amount_mtd_ly NUMBER(38, 10),
    misc_cogs_amount_month_tot_lm NUMBER(38, 10),
    misc_cogs_amount_month_tot_ly NUMBER(38, 10),
    misc_cogs_amount_budget NUMBER(38, 10),
    misc_cogs_amount_budget_alt NUMBER(38, 10),
    misc_cogs_amount_forecast NUMBER(38, 10),
    product_order_cash_gross_profit NUMBER(38, 10),
    product_order_cash_gross_profit_mtd NUMBER(38, 10),
    product_order_cash_gross_profit_mtd_ly NUMBER(38, 10),
    product_order_cash_gross_profit_month_tot_lm NUMBER(38, 10),
    product_order_cash_gross_profit_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit_mtd NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit_mtd_ly NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit_month_tot_lm NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit_month_tot_ly NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit_budget NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit_budget_alt NUMBER(38, 10),
    nonactivating_product_order_cash_gross_profit_forecast NUMBER(38, 10),
    same_month_billed_credit_redeemed NUMBER(38, 10),
    same_month_billed_credit_redeemed_mtd NUMBER(38, 10),
    same_month_billed_credit_redeemed_mtd_ly NUMBER(38, 10),
    same_month_billed_credit_redeemed_month_tot_lm NUMBER(38, 10),
    same_month_billed_credit_redeemed_month_tot_ly NUMBER(38, 10),
    billed_credit_cash_refund_count NUMBER(38),
    billed_credit_cash_refund_count_mtd NUMBER(38),
    billed_credit_cash_refund_count_mtd_ly NUMBER(38),
    billed_credit_cash_refund_count_month_tot_lm NUMBER(38),
    billed_credit_cash_refund_count_month_tot_ly NUMBER(38),
    cash_variable_contribution_profit NUMBER(38, 10),
    cash_variable_contribution_profit_mtd NUMBER(38, 10),
    cash_variable_contribution_profit_mtd_ly NUMBER(38, 10),
    cash_variable_contribution_profit_month_tot_lm NUMBER(38, 10),
    cash_variable_contribution_profit_month_tot_ly NUMBER(38, 10),
    cash_contribution_after_media_budget NUMBER(38, 10),
    cash_contribution_after_media_budget_alt NUMBER(38, 10),
    cash_contribution_after_media_forecast NUMBER(38, 10),
    billed_cash_credit_redeemed_equivalent_count NUMBER(38, 10),
    billed_cash_credit_redeemed_equivalent_count_mtd NUMBER(38, 10),
    billed_cash_credit_redeemed_equivalent_count_mtd_ly NUMBER(38, 10),
    billed_cash_credit_redeemed_equivalent_count_month_tot_lm NUMBER(38, 10),
    billed_cash_credit_redeemed_equivalent_count_month_tot_ly NUMBER(38, 10),
    membership_credits_redeemed_count_budget NUMBER(38, 10),
    membership_credits_redeemed_count_budget_alt NUMBER(38, 10),
    membership_credits_redeemed_count_forecast NUMBER(38, 10),
    billed_cash_credit_cancelled_equivalent_count NUMBER(38, 10),
    billed_cash_credit_cancelled_equivalent_count_mtd NUMBER(38, 10),
    billed_cash_credit_cancelled_equivalent_count_mtd_ly NUMBER(38, 10),
    billed_cash_credit_cancelled_equivalent_count_month_tot_lm NUMBER(38, 10),
    billed_cash_credit_cancelled_equivalent_count_month_tot_ly NUMBER(38, 10),
    membership_credits_cancelled_count_budget NUMBER(38, 10),
    membership_credits_cancelled_count_budget_alt NUMBER(38, 10),
    membership_credits_cancelled_count_forecast NUMBER(38, 10),
    cash_gross_profit_percent_of_net_cash_budget NUMBER(38, 10),
    cash_gross_profit_percent_of_net_cash_budget_alt NUMBER(38, 10),
    cash_gross_profit_percent_of_net_cash_forecast NUMBER(38, 10),
    product_order_and_billing_cash_refund_budget NUMBER(38, 10),
    product_order_and_billing_cash_refund_budget_alt NUMBER(38, 10),
    product_order_and_billing_cash_refund_forecast NUMBER(38, 10),
    product_order_and_billing_chargebacks_budget NUMBER(38, 10),
    product_order_and_billing_chargebacks_budget_alt NUMBER(38, 10),
    product_order_and_billing_chargebacks_forecast NUMBER(38, 10),
    refunds_plus_chargebacks_as_percent_of_cash_gross_rev_budget NUMBER(38, 10),
    refunds_plus_chargebacks_as_percent_of_cash_gross_rev_budget_alt NUMBER(38, 10),
    refunds_plus_chargebacks_as_percent_of_cash_gross_rev_forecast NUMBER(38, 10),
    activating_aov_budget NUMBER(38, 10),
    activating_aov_budget_alt NUMBER(38, 10),
    activating_aov_forecast NUMBER(38, 10),
    activating_upt_budget NUMBER(38, 10),
    activating_upt_budget_alt NUMBER(38, 10),
    activating_upt_forecast NUMBER(38, 10),
    activating_discount_percent_budget NUMBER(38, 10),
    activating_discount_percent_budget_alt NUMBER(38, 10),
    activating_discount_percent_forecast NUMBER(38, 10),
    activating_product_gross_profit_percent_budget NUMBER(38, 10),
    activating_product_gross_profit_percent_budget_alt NUMBER(38, 10),
    activating_product_gross_profit_percent_forecast NUMBER(38, 10),
    activating_product_margin_pre_return_per_order_budget NUMBER(38, 10),
    activating_product_margin_pre_return_per_order_budget_alt NUMBER(38, 10),
    activating_product_margin_pre_return_per_order_forecast NUMBER(38, 10),
    activating_product_margin_pre_return_percent_budget NUMBER(38, 10),
    activating_product_margin_pre_return_percent_budget_alt NUMBER(38, 10),
    activating_product_margin_pre_return_percent_forecast NUMBER(38, 10),
    nonactivating_aov_budget NUMBER(38, 10),
    nonactivating_aov_budget_alt NUMBER(38, 10),
    nonactivating_aov_forecast NUMBER(38, 10),
    nonactivating_upt_budget NUMBER(38, 10),
    nonactivating_upt_budget_alt NUMBER(38, 10),
    nonactivating_upt_forecast NUMBER(38, 10),
    nonactivating_discount_percent_budget NUMBER(38, 10),
    nonactivating_discount_percent_budget_alt NUMBER(38, 10),
    nonactivating_discount_percent_forecast NUMBER(38, 10),
    nonactivating_product_gross_profit_percent_budget NUMBER(38, 10),
    nonactivating_product_gross_profit_percent_budget_alt NUMBER(38, 10),
    nonactivating_product_gross_profit_percent_forecast NUMBER(38, 10),
    shipping_cost_incl_reship_exch_budget NUMBER(38, 10),
    shipping_cost_incl_reship_exch_budget_alt NUMBER(38, 10),
    shipping_cost_incl_reship_exch_forecast NUMBER(38, 10),
    shipping_supplies_cost_incl_reship_exch_budget NUMBER(38, 10),
    shipping_supplies_cost_incl_reship_exch_budget_alt NUMBER(38, 10),
    shipping_supplies_cost_incl_reship_exch_forecast NUMBER(38, 10),
    product_cost_calc_budget NUMBER(38, 10),
    product_cost_calc_budget_alt NUMBER(38, 10),
    product_cost_calc_forecast NUMBER(38, 10),
    product_order_tariff_amount NUMBER(38, 10),
    product_order_shipping_discount_amount NUMBER(38, 10),
    product_order_shipping_revenue_before_discount_amount NUMBER(38, 10),
    product_order_tax_amount NUMBER(38, 10),
    product_order_cash_transaction_amount NUMBER(38, 10),
    product_order_cash_credit_redeemed_amount NUMBER(38, 10),
    product_order_loyalty_unit_count NUMBER(38),
    product_order_outfit_component_unit_count NUMBER(38),
    product_order_outfit_count NUMBER(38),
    product_order_discounted_unit_count NUMBER(38),
    product_order_zero_revenue_unit_count NUMBER(38),
    product_order_cash_credit_refund_amount NUMBER(38, 10),
    product_order_cash_credit_refund_amount_mtd NUMBER(38, 10),
    product_order_cash_credit_refund_amount_mtd_ly NUMBER(38, 10),
    product_order_cash_credit_refund_amount_month_tot_lm NUMBER(38, 10),
    product_order_cash_credit_refund_amount_month_tot_ly NUMBER(38, 10),
    product_order_cash_credit_refund_amount_budget NUMBER(38, 10),
    product_order_cash_credit_refund_amount_budget_alt NUMBER(38, 10),
    product_order_cash_credit_refund_amount_forecast NUMBER(38, 10),
    activating_product_order_cash_credit_refund_amount number(38, 10),
    activating_product_order_cash_credit_refund_amount_mtd number(38, 10),
    activating_product_order_cash_credit_refund_amount_mtd_ly number(38, 10),
    activating_product_order_cash_credit_refund_amount_month_tot_lm number(38, 10),
    activating_product_order_cash_credit_refund_amount_month_tot_ly number(38, 10),
    activating_product_order_cash_credit_refund_amount_budget number(38, 10),
    activating_product_order_cash_credit_refund_amount_budget_alt number(38, 10),
    activating_product_order_cash_credit_refund_amount_forecast number(38, 10),
    nonactivating_product_order_cash_credit_refund_amount number(38,10),
    nonactivating_product_order_cash_credit_refund_amount_mtd number(38,10),
    nonactivating_product_order_cash_credit_refund_amount_mtd_ly number(38,10),
    nonactivating_product_order_cash_credit_refund_amount_month_tot_lm number(38,10),
    nonactivating_product_order_cash_credit_refund_amount_month_tot_ly number(38,10),
    nonactivating_product_order_cash_credit_refund_amount_budget number(38, 10),
    nonactivating_product_order_cash_credit_refund_amount_budget_alt number(38, 10),
    nonactivating_product_order_cash_credit_refund_amount_forecast number(38, 10),
    product_order_noncash_credit_refund_amount NUMBER(38, 10),
    product_order_noncash_credit_refund_amount_mtd NUMBER(38, 10),
    product_order_noncash_credit_refund_amount_mtd_ly NUMBER(38, 10),
    product_order_noncash_credit_refund_amount_month_tot_lm NUMBER(38, 10),
    product_order_noncash_credit_refund_amount_month_tot_ly NUMBER(38, 10),
    product_order_noncash_credit_refund_amount_budget NUMBER(38, 10),
    product_order_noncash_credit_refund_amount_budget_alt NUMBER(38, 10),
    product_order_noncash_credit_refund_amount_forecast NUMBER(38, 10),
    product_order_return_unit_count NUMBER(38),
    product_order_return_unit_count_mtd NUMBER(38),
    product_order_return_unit_count_mtd_ly NUMBER(38),
    product_order_return_unit_count_month_tot_lm NUMBER(38),
    product_order_return_unit_count_month_tot_ly NUMBER(38),
    product_order_exchange_direct_cogs_amount NUMBER(38, 10),
    product_order_selling_expenses_amount NUMBER(38, 10),
    product_order_payment_processing_cost_amount NUMBER(38, 10),
    product_order_variable_gms_cost_amount NUMBER(38, 10),
    product_order_variable_warehouse_cost_amount NUMBER(38, 10),
    billing_selling_expenses_amount NUMBER(38, 10),
    billing_payment_processing_cost_amount NUMBER(38, 10),
    billing_variable_gms_cost_amount NUMBER(38, 10),
    product_order_amount_to_pay NUMBER(38, 10),
    product_gross_revenue_excl_shipping NUMBER(38, 10),
    product_gross_revenue_excl_shipping_mtd NUMBER(38, 10),
    product_gross_revenue_excl_shipping_mtd_ly NUMBER(38, 10),
    product_gross_revenue_excl_shipping_month_tot_lm NUMBER(38, 10),
    product_gross_revenue_excl_shipping_month_tot_ly NUMBER(38, 10),
    activating_product_gross_revenue_excl_shipping NUMBER(38, 10),
    activating_product_gross_revenue_excl_shipping_mtd NUMBER(38, 10),
    activating_product_gross_revenue_excl_shipping_mtd_ly NUMBER(38, 10),
    activating_product_gross_revenue_excl_shipping_month_tot_lm NUMBER(38, 10),
    activating_product_gross_revenue_excl_shipping_month_tot_ly NUMBER(38, 10),
    nonactivating_product_gross_revenue_excl_shipping NUMBER(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_mtd NUMBER(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_mtd_ly NUMBER(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_month_tot_lm NUMBER(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_month_tot_ly NUMBER(38, 10),
    guest_product_gross_revenue_excl_shipping NUMBER(38, 10),
    guest_product_gross_revenue_excl_shipping_mtd NUMBER(38, 10),
    guest_product_gross_revenue_excl_shipping_mtd_ly NUMBER(38, 10),
    guest_product_gross_revenue_excl_shipping_month_tot_lm NUMBER(38, 10),
    guest_product_gross_revenue_excl_shipping_month_tot_ly NUMBER(38, 10),
    repeat_vip_product_gross_revenue_excl_shipping number(38, 10),
    repeat_vip_product_gross_revenue_excl_shipping_mtd number(38, 10),
    repeat_vip_product_gross_revenue_excl_shipping_mtd_ly number(38, 10),
    repeat_vip_product_gross_revenue_excl_shipping_month_tot_lm number(38, 10),
    repeat_vip_product_gross_revenue_excl_shipping_month_tot_ly number(38, 10),
    product_margin_pre_return_excl_shipping NUMBER(38, 10),
    activating_product_margin_pre_return_excl_shipping NUMBER(38, 10),
    product_variable_contribution_profit NUMBER(38, 10),
    product_order_cash_net_revenue NUMBER(38, 10),
    product_order_cash_margin_pre_return NUMBER(38, 10),
    billing_cash_gross_revenue NUMBER(38, 10),
    billing_cash_net_revenue NUMBER(38, 10),
    billing_order_transaction_count NUMBER(38),
    billing_order_transaction_count_mtd NUMBER(38),
    billing_order_transaction_count_mtd_ly NUMBER(38),
    billing_order_transaction_count_month_tot_lm NUMBER(38),
    billing_order_transaction_count_month_tot_ly NUMBER(38),
    billing_order_transaction_count_budget NUMBER(38),
    billing_order_transaction_count_budget_alt NUMBER(38),
    billing_order_transaction_count_forecast NUMBER(38),
    membership_fee_cash_transaction_amount NUMBER(38, 10),
    membership_fee_cash_transaction_amount_mtd NUMBER(38, 10),
    membership_fee_cash_transaction_amount_mtd_ly NUMBER(38, 10),
    membership_fee_cash_transaction_amount_month_tot_lm NUMBER(38, 10),
    membership_fee_cash_transaction_amount_month_tot_ly NUMBER(38, 10),
    gift_card_transaction_amount NUMBER(38, 10),
    gift_card_transaction_amount_mtd NUMBER(38, 10),
    gift_card_transaction_amount_mtd_ly NUMBER(38, 10),
    gift_card_transaction_amount_month_tot_lm NUMBER(38, 10),
    gift_card_transaction_amount_month_tot_ly NUMBER(38, 10),
    legacy_credit_cash_transaction_amount NUMBER(38, 10),
    legacy_credit_cash_transaction_amount_mtd NUMBER(38, 10),
    legacy_credit_cash_transaction_amount_mtd_ly NUMBER(38, 10),
    legacy_credit_cash_transaction_amount_month_tot_lm NUMBER(38, 10),
    legacy_credit_cash_transaction_amount_month_tot_ly NUMBER(38, 10),
    membership_fee_cash_refund_chargeback_amount NUMBER(38, 10),
    membership_fee_cash_refund_chargeback_amount_mtd NUMBER(38, 10),
    membership_fee_cash_refund_chargeback_amount_mtd_ly NUMBER(38, 10),
    membership_fee_cash_refund_chargeback_amount_month_tot_lm NUMBER(38, 10),
    membership_fee_cash_refund_chargeback_amount_month_tot_ly NUMBER(38, 10),
    gift_card_cash_refund_chargeback_amount number(38, 10),
    gift_card_cash_refund_chargeback_amount_mtd NUMBER(38,10),
    gift_card_cash_refund_chargeback_amount_mtd_ly NUMBER(38,10),
    gift_card_cash_refund_chargeback_amount_month_tot_lm NUMBER(38,10),
    gift_card_cash_refund_chargeback_amount_month_tot_ly NUMBER(38,10),
    legacy_credit_cash_refund_chargeback_amount number(38, 10),
    legacy_credit_cash_refund_chargeback_amount_mtd NUMBER(38,10),
    legacy_credit_cash_refund_chargeback_amount_mtd_ly NUMBER(38,10),
    legacy_credit_cash_refund_chargeback_amount_month_tot_lm NUMBER(38,10),
    legacy_credit_cash_refund_chargeback_amount_month_tot_ly NUMBER(38,10),
    billed_cash_credit_issued_amount NUMBER(38, 10),
    billed_cash_credit_cancelled_amount NUMBER(38, 10),
    billed_cash_credit_expired_amount NUMBER(38, 10),
    billed_cash_credit_issued_equivalent_count NUMBER(38, 10),
    billed_cash_credit_issued_equivalent_count_mtd NUMBER(38, 10),
    billed_cash_credit_issued_equivalent_count_mtd_ly NUMBER(38, 10),
    billed_cash_credit_issued_equivalent_count_month_tot_lm NUMBER(38, 10),
    billed_cash_credit_issued_equivalent_count_month_tot_ly NUMBER(38, 10),
    billed_cash_credit_expired_equivalent_count NUMBER(38, 10),
    refund_cash_credit_issued_amount NUMBER(38, 10),
    refund_cash_credit_issued_amount_mtd NUMBER(38, 10),
    refund_cash_credit_issued_amount_mtd_ly NUMBER(38, 10),
    refund_cash_credit_issued_amount_month_tot_lm NUMBER(38, 10),
    refund_cash_credit_issued_amount_month_tot_ly NUMBER(38, 10),
    refund_cash_credit_issued_amount_budget NUMBER(38, 10),
    refund_cash_credit_issued_amount_budget_alt NUMBER(38, 10),
    refund_cash_credit_issued_amount_forecast NUMBER(38, 10),
    refund_cash_credit_redeemed_amount NUMBER(38, 10),
    refund_cash_credit_redeemed_amount_mtd NUMBER(38, 10),
    refund_cash_credit_redeemed_amount_mtd_ly NUMBER(38, 10),
    refund_cash_credit_redeemed_amount_month_tot_lm NUMBER(38, 10),
    refund_cash_credit_redeemed_amount_month_tot_ly NUMBER(38, 10),
    refund_cash_credit_redeemed_amount_budget NUMBER(38, 10),
    refund_cash_credit_redeemed_amount_budget_alt NUMBER(38, 10),
    refund_cash_credit_redeemed_amount_forecast NUMBER(38, 10),
    refund_cash_credit_cancelled_amount NUMBER(38, 10),
    refund_cash_credit_cancelled_amount_mtd NUMBER(38, 10),
    refund_cash_credit_cancelled_amount_mtd_ly NUMBER(38, 10),
    refund_cash_credit_cancelled_amount_month_tot_lm NUMBER(38, 10),
    refund_cash_credit_cancelled_amount_month_tot_ly NUMBER(38, 10),
    net_unredeemed_refund_credit_budget NUMBER(38, 10),
    net_unredeemed_refund_credit_budget_alt NUMBER(38, 10),
    net_unredeemed_refund_credit_forecast NUMBER(38, 10),
    refund_cash_credit_expired_amount NUMBER(38, 10),
    other_cash_credit_issued_amount NUMBER(38, 10),
    other_cash_credit_redeemed_amount NUMBER(38, 10),
    other_cash_credit_redeemed_amount_mtd NUMBER(38, 10),
    other_cash_credit_redeemed_amount_mtd_ly NUMBER(38, 10),
    other_cash_credit_redeemed_amount_month_tot_lm NUMBER(38, 10),
    other_cash_credit_redeemed_amount_month_tot_ly NUMBER(38, 10),
    other_cash_credit_cancelled_amount NUMBER(38, 10),
    other_cash_credit_expired_amount NUMBER(38, 10),
    cash_gift_card_redeemed_amount NUMBER(38, 10),
    activating_cash_gift_card_redeemed_amount NUMBER(38, 10),
    nonactivating_cash_gift_card_redeemed_amount NUMBER(38, 10),
    guest_cash_gift_card_redeemed_amount NUMBER(38, 10),
    noncash_credit_issued_amount NUMBER(38, 10),
	noncash_credit_issued_amount_mtd NUMBER(38, 10),
    noncash_credit_issued_amount_mtd_ly NUMBER(38, 10),
    noncash_credit_issued_amount_month_tot_lm NUMBER(38, 10),
    noncash_credit_issued_amount_month_tot_ly NUMBER(38, 10),
    noncash_credit_cancelled_amount NUMBER(38, 10),
    noncash_credit_expired_amount NUMBER(38, 10),
    net_unredeemed_credit_billings_budget NUMBER(38, 10),
    net_unredeemed_credit_billings_budget_alt NUMBER(38, 10),
    net_unredeemed_credit_billings_forecast NUMBER(38, 10),
    product_order_non_token_subtotal_excl_tariff_amount number(38, 10),
    product_order_non_token_subtotal_excl_tariff_amount_mtd number(38, 10),
    product_order_non_token_subtotal_excl_tariff_amount_mtd_ly number(38, 10),
    product_order_non_token_subtotal_excl_tariff_amount_month_tot_lm number(38, 10),
    product_order_non_token_subtotal_excl_tariff_amount_month_tot_ly number(38, 10),
    product_order_non_token_unit_count number(38, 0),
    product_order_non_token_unit_count_mtd number(38, 0),
    product_order_non_token_unit_count_mtd_ly number(38, 0),
    product_order_non_token_unit_count_month_tot_lm number(38, 0),
    product_order_non_token_unit_count_month_tot_ly number(38, 0),
    nonactivating_product_order_non_token_subtotal_excl_tariff_amount number(38, 10),
    nonactivating_product_order_non_token_subtotal_excl_tariff_amount_mtd number(38, 10),
    nonactivating_product_order_non_token_subtotal_excl_tariff_amount_mtd_ly number(38, 10),
    nonactivating_product_order_non_token_subtotal_excl_tariff_amount_month_tot_lm number(38, 10),
    nonactivating_product_order_non_token_subtotal_excl_tariff_amount_month_tot_ly number(38, 10),
    nonactivating_product_order_non_token_unit_count number(38, 0),
    nonactivating_product_order_non_token_unit_count_mtd number(38, 0),
    nonactivating_product_order_non_token_unit_count_mtd_ly number(38, 0),
    nonactivating_product_order_non_token_unit_count_month_tot_lm number(38, 0),
    nonactivating_product_order_non_token_unit_count_month_tot_ly number(38, 0),
    pending_order_count NUMBER(38),
    pending_order_local_amount NUMBER(38, 10),
    pending_order_usd_amount NUMBER(38, 10),
    pending_order_eur_amount NUMBER(38, 10),
    pending_order_cash_margin_pre_return_local_amount NUMBER(38, 10),
    pending_order_cash_margin_pre_return_usd_amount NUMBER(38, 10),
    pending_order_cash_margin_pre_return_eur_amount NUMBER(38, 10),
    leads NUMBER(38),
    leads_mtd NUMBER(38),
    leads_mtd_ly NUMBER(38),
    leads_month_tot_lm NUMBER(38),
    leads_month_tot_ly NUMBER(38),
    leads_budget NUMBER(38, 10),
    leads_budget_alt NUMBER(38, 10),
    leads_forecast NUMBER(38, 10),
    primary_leads number(38, 0),
    primary_leads_mtd number(38, 0),
    primary_leads_mtd_ly number(38, 0),
    primary_leads_month_tot_lm number(38, 0),
    primary_leads_month_tot_ly number(38, 0),
    reactivated_leads NUMBER(38),
    reactivated_leads_mtd NUMBER(38),
    reactivated_leads_mtd_ly NUMBER(38),
    reactivated_leads_month_tot_lm NUMBER(38),
    reactivated_leads_month_tot_ly NUMBER(38),
    new_vips NUMBER(38),
    new_vips_mtd NUMBER(38),
    new_vips_mtd_ly NUMBER(38),
    new_vips_month_tot_lm NUMBER(38),
    new_vips_month_tot_ly NUMBER(38),
    new_vips_budget NUMBER(38),
    new_vips_budget_alt NUMBER(38),
    new_vips_forecast NUMBER(38),
    reactivated_vips NUMBER(38),
    reactivated_vips_mtd NUMBER(38),
    reactivated_vips_mtd_ly NUMBER(38),
    reactivated_vips_month_tot_lm NUMBER(38),
    reactivated_vips_month_tot_ly NUMBER(38),
    vips_from_reactivated_leads_m1 NUMBER(38),
    vips_from_reactivated_leads_m1_mtd NUMBER(38),
    vips_from_reactivated_leads_m1_mtd_ly NUMBER(38),
    vips_from_reactivated_leads_m1_month_tot_lm NUMBER(38),
    vips_from_reactivated_leads_m1_month_tot_ly NUMBER(38),
    paid_vips NUMBER(38),
    paid_vips_mtd NUMBER(38),
    paid_vips_mtd_ly NUMBER(38),
    paid_vips_month_tot_lm NUMBER(38),
    paid_vips_month_tot_ly NUMBER(38),
    unpaid_vips NUMBER(38),
    unpaid_vips_mtd NUMBER(38),
    unpaid_vips_mtd_ly NUMBER(38),
    unpaid_vips_month_tot_lm NUMBER(38),
    unpaid_vips_month_tot_ly NUMBER(38),
    new_vips_m1 NUMBER(38),
    new_vips_m1_mtd NUMBER(38),
    new_vips_m1_mtd_ly NUMBER(38),
    new_vips_m1_month_tot_lm NUMBER(38),
    new_vips_m1_month_tot_ly NUMBER(38),
    new_vips_m1_budget NUMBER(38),
    new_vips_m1_budget_alt NUMBER(38),
    new_vips_m1_forecast NUMBER(38),
    paid_vips_m1 NUMBER(38),
    paid_vips_m1_mtd NUMBER(38),
    paid_vips_m1_mtd_ly NUMBER(38),
    paid_vips_m1_month_tot_lm NUMBER(38),
    paid_vips_m1_month_tot_ly NUMBER(38),
    cancels NUMBER(38),
    cancels_mtd NUMBER(38),
    cancels_mtd_ly NUMBER(38),
    cancels_month_tot_lm NUMBER(38),
    cancels_month_tot_ly NUMBER(38),
    cancels_budget NUMBER(38),
    cancels_budget_alt NUMBER(38),
    cancels_forecast NUMBER(38),
    m1_cancels NUMBER(38),
    m1_cancels_mtd NUMBER(38),
    m1_cancels_mtd_ly NUMBER(38),
    m1_cancels_month_tot_lm NUMBER(38),
    m1_cancels_month_tot_ly NUMBER(38),
    bop_vips NUMBER(38),
    bop_vips_mtd NUMBER(38),
    bop_vips_mtd_ly NUMBER(38),
    bop_vips_month_tot_lm NUMBER(38),
    bop_vips_month_tot_ly NUMBER(38),
    bop_vips_budget NUMBER(38),
    bop_vips_budget_alt NUMBER(38),
    bop_vips_forecast NUMBER(38),
    media_spend NUMBER(38, 10),
    media_spend_mtd NUMBER(38, 10),
    media_spend_mtd_ly NUMBER(38, 10),
    media_spend_month_tot_lm NUMBER(38, 10),
    media_spend_month_tot_ly NUMBER(38, 10),
    media_spend_budget NUMBER(38, 10),
    media_spend_budget_alt NUMBER(38, 10),
    media_spend_forecast NUMBER(38, 10),
    merch_purchase_count NUMBER(38),
    merch_purchase_count_mtd NUMBER(38),
    merch_purchase_count_mtd_ly NUMBER(38),
    merch_purchase_count_month_tot_lm NUMBER(38),
    merch_purchase_count_month_tot_ly NUMBER(38),
    merch_purchase_hyperion_count NUMBER(38),
    merch_purchase_hyperion_count_mtd NUMBER(38),
    merch_purchase_hyperion_count_mtd_ly NUMBER(38),
    merch_purchase_hyperion_count_month_tot_lm NUMBER(38),
    merch_purchase_hyperion_count_month_tot_ly NUMBER(38),
    bom_vips NUMBER(38),
    skip_count NUMBER(38),
    report_date_type varchar(8),
    snapshot_datetime_budget TIMESTAMPLTZ,
    snapshot_datetime_forecast TIMESTAMPLTZ,
    meta_update_datetime TIMESTAMPLTZ(3),
    meta_create_datetime TIMESTAMPLTZ(3)
);
