CREATE OR REPLACE TABLE snapshot.finance_sales_ops
(
    store_brand                                              VARCHAR(20),
    store_country                                            VARCHAR(50),
    store_region                                             VARCHAR(32),
    store_type                                               VARCHAR(20),
    gender                                                   VARCHAR(10),
    is_retail_vip                                            BOOLEAN,
    is_cross_promo                                           BOOLEAN,
    finance_specialty_store                                  VARCHAR(20),
    membership_order_type_l3                                 VARCHAR(50),
    date                                                     DATE,
    date_object                                              VARCHAR(20),
    currency_object                                          VARCHAR(8),
    currency_type                                            VARCHAR(50),
    product_order_subtotal_excl_tariff_amount                NUMBER(38, 10),
    product_order_tariff_amount                              NUMBER(38, 10),
    product_order_product_subtotal_amount                    NUMBER(38, 10),
    product_order_product_discount_amount                    NUMBER(38, 10),
    product_order_shipping_discount_amount                   NUMBER(38, 10),
    product_order_shipping_revenue_before_discount_amount    NUMBER(38, 10),
    product_order_shipping_revenue_amount                    NUMBER(38, 10),
    product_order_tax_amount                                 NUMBER(38, 10),
    product_order_cash_transaction_amount                    NUMBER(38, 10),
    product_order_cash_credit_redeemed_amount                NUMBER(38, 10),
    product_order_noncash_credit_redeemed_amount             NUMBER(38, 10),
    product_order_count                                      NUMBER(25, 0),
    product_order_count_excl_seeding                         NUMBER(25, 0),
    product_order_unit_count                                 NUMBER(38, 0),
    product_order_loyalty_unit_count                         NUMBER(38, 0),
    product_order_outfit_component_unit_count                NUMBER(38, 0),
    product_order_outfit_count                               NUMBER(38, 0),
    product_order_discounted_unit_count                      NUMBER(38, 0),
    product_order_zero_revenue_unit_count                    NUMBER(38, 0),
    product_order_landed_product_cost_amount                 NUMBER(38, 10),
    product_order_shipping_cost_amount                       NUMBER(38, 12),
    product_order_shipping_supplies_cost_amount              NUMBER(38, 12),
    product_order_misc_cogs_amount                           NUMBER(38, 12),
    product_order_direct_cogs_amount                         NUMBER(38, 12),
    product_order_cash_refund_amount                         NUMBER(38, 10),
    product_order_cash_credit_refund_amount                  NUMBER(38, 10),
    product_order_noncash_credit_refund_amount               NUMBER(38, 10),
    product_order_cash_chargeback_amount                     NUMBER(38, 10),
    product_order_cost_product_returned_resaleable_amount    NUMBER(38, 12),
    product_order_cost_product_returned_damaged_amount       NUMBER(38, 12),
    product_order_return_shipping_cost_amount                NUMBER(38, 10),
    product_order_return_unit_count                          NUMBER(38, 0),
    product_order_reship_order_count                         NUMBER(25, 0),
    product_order_reship_unit_count                          NUMBER(38, 0),
    product_order_reship_direct_cogs_amount                  NUMBER(38, 12),
    product_order_reship_product_cost_amount                 NUMBER(38, 10),
    product_order_reship_shipping_cost_amount                NUMBER(38, 12),
    product_order_reship_shipping_supplies_cost_amount       NUMBER(38, 12),
    product_order_exchange_order_count                       NUMBER(25, 0),
    product_order_exchange_unit_count                        NUMBER(38, 0),
    product_order_exchange_direct_cogs_amount                NUMBER(38, 12),
    product_order_exchange_product_cost_amount               NUMBER(38, 10),
    product_order_exchange_shipping_cost_amount              NUMBER(38, 12),
    product_order_exchange_shipping_supplies_cost_amount     NUMBER(38, 12),
    product_order_selling_expenses_amount                    NUMBER(38, 12),
    product_order_payment_processing_cost_amount             NUMBER(38, 12),
    product_order_variable_gms_cost_amount                   NUMBER(38, 12),
    product_order_variable_warehouse_cost_amount             NUMBER(38, 12),
    billing_selling_expenses_amount                          NUMBER(38, 12),
    billing_payment_processing_cost_amount                   NUMBER(38, 12),
    billing_variable_gms_cost_amount                         NUMBER(38, 12),
    product_order_amount_to_pay                              NUMBER(38, 10),
    product_gross_revenue_excl_shipping                      NUMBER(38, 10),
    product_gross_revenue                                    NUMBER(38, 10),
    product_net_revenue                                      NUMBER(38, 10),
    product_margin_pre_return                                NUMBER(38, 12),
    product_margin_pre_return_excl_shipping                  NUMBER(38, 10),
    product_margin_pre_return_excl_seeding                   NUMBER(38, 10),
    product_gross_profit                                     NUMBER(38, 12),
    product_variable_contribution_profit                     NUMBER(38, 12),
    product_order_cash_gross_revenue_amount                  NUMBER(38, 10),
    product_order_cash_net_revenue                           NUMBER(38, 10),
    product_order_cash_margin_pre_return                     NUMBER(38, 10),
    product_order_cash_gross_profit                          NUMBER(38, 10),
    billing_cash_gross_revenue                               NUMBER(38, 10),
    billing_cash_net_revenue                                 NUMBER(38, 10),
    cash_gross_revenue                                       NUMBER(38, 10),
    cash_net_revenue                                         NUMBER(38, 10),
    cash_gross_profit                                        NUMBER(38, 12),
    cash_variable_contribution_profit                        NUMBER(38, 12),
    billing_order_transaction_count                          NUMBER(25, 0),
    billed_credit_cash_transaction_count                     NUMBER(25, 0),
    on_retry_billed_credit_cash_transaction_count            NUMBER(25, 0),
    billing_cash_refund_amount                               NUMBER(38, 10),
    billing_cash_chargeback_amount                           NUMBER(38, 10),
    billed_credit_cash_transaction_amount                    NUMBER(38, 10),
    membership_fee_cash_transaction_amount                   NUMBER(38, 10),
    gift_card_transaction_amount                             NUMBER(38, 10),
    legacy_credit_cash_transaction_amount                    NUMBER(38, 10),
    billed_credit_cash_refund_count                          NUMBER(25, 0),
    billed_credit_cash_refund_chargeback_amount              NUMBER(38, 10),
    membership_fee_cash_refund_chargeback_amount             NUMBER(38, 10),
    gift_card_cash_refund_chargeback_amount                  NUMBER(38, 10),
    legacy_credit_cash_refund_chargeback_amount              NUMBER(38, 10),
    billed_cash_credit_issued_amount                         NUMBER(38, 12),
    billed_cash_credit_redeemed_amount                       NUMBER(38, 12),
    billed_cash_credit_cancelled_amount                      NUMBER(38, 12),
    billed_cash_credit_expired_amount                        NUMBER(38, 12),
    billed_cash_credit_issued_equivalent_count               NUMBER(30, 0),
    billed_cash_credit_redeemed_same_month_amount            NUMBER(30, 0),
    billed_cash_credit_redeemed_equivalent_count             NUMBER(38, 10),
    billed_cash_credit_cancelled_equivalent_count            NUMBER(38, 10),
    billed_cash_credit_expired_equivalent_count              NUMBER(38, 10),
    refund_cash_credit_issued_amount                         NUMBER(38, 12),
    refund_cash_credit_redeemed_amount                       NUMBER(38, 12),
    refund_cash_credit_cancelled_amount                      NUMBER(38, 12),
    refund_cash_credit_expired_amount                        NUMBER(38, 12),
    other_cash_credit_issued_amount                          NUMBER(38, 12),
    other_cash_credit_redeemed_amount                        NUMBER(38, 12),
    other_cash_credit_cancelled_amount                       NUMBER(38, 12),
    other_cash_credit_expired_amount                         NUMBER(38, 12),
    noncash_credit_issued_amount                             NUMBER(38, 12),
    noncash_credit_cancelled_amount                          NUMBER(38, 12),
    noncash_credit_expired_amount                            NUMBER(38, 12),
    retail_ship_only_product_order_count                     NUMBER(38, 0),
    retail_ship_only_product_order_unit_count                NUMBER(38, 0),
    retail_ship_only_product_gross_revenue                   NUMBER(31, 4),
    retail_ship_only_product_gross_revenue_excl_shipping     NUMBER(31, 4),
    retail_ship_only_product_margin_pre_return               NUMBER(31, 4),
    retail_ship_only_product_margin_pre_return_excl_shipping NUMBER(31, 4),
    retail_ship_only_product_order_cash_margin_pre_return    NUMBER(31, 4),
    retail_ship_only_product_order_cash_gross_revenue        NUMBER(31, 4),
    retail_ship_only_product_net_revenue                     NUMBER(31, 4),
    retail_ship_only_product_gross_profit                    NUMBER(31, 4),
    retail_ship_only_product_order_cash_net_revenue          NUMBER(31, 4),
    retail_ship_only_product_order_cash_gross_profit         NUMBER(31, 4),
    product_order_reship_exchange_cash_gross_revenue         NUMBER(38, 10),
    cash_gift_card_redeemed_amount                           NUMBER(38, 10),
    snapshot_datetime                                        TIMESTAMP_LTZ(3)
);
