CREATE OR REPLACE TABLE snapshot.daily_cash_final_output (
	date date,
	date_object varchar(20),
	currency_object varchar(8),
	currency_type varchar(50),
    store_brand VARCHAR(100),
    business_unit varchar(100),
	report_mapping varchar(250),
	is_daily_cash_usd boolean,
	is_daily_cash_eur boolean,
	product_order_subtotal_excl_tariff_amount number(38,10),
	product_order_subtotal_excl_tariff_amount_mtd number(38,10),
	product_order_subtotal_excl_tariff_amount_mtd_ly number(38,10),
	product_order_subtotal_excl_tariff_amount_month_tot_lm number(38,10),
	product_order_subtotal_excl_tariff_amount_month_tot_ly number(38,10),
	activating_product_order_subtotal_excl_tariff_amount number(38,10),
	activating_product_order_subtotal_excl_tariff_amount_mtd number(38,10),
	activating_product_order_subtotal_excl_tariff_amount_mtd_ly number(38,10),
	activating_product_order_subtotal_excl_tariff_amount_month_tot_lm number(38,10),
	activating_product_order_subtotal_excl_tariff_amount_month_tot_ly number(38,10),
	nonactivating_product_order_subtotal_excl_tariff_amount number(38,10),
	nonactivating_product_order_subtotal_excl_tariff_amount_mtd number(38,10),
	nonactivating_product_order_subtotal_excl_tariff_amount_mtd_ly number(38,10),
	nonactivating_product_order_subtotal_excl_tariff_amount_month_tot_lm number(38,10),
	nonactivating_product_order_subtotal_excl_tariff_amount_month_tot_ly number(38,10),
    guest_product_order_subtotal_excl_tariff_amount number(38,10),
    guest_product_order_subtotal_excl_tariff_amount_mtd number(38,10),
    guest_product_order_subtotal_excl_tariff_amount_mtd_ly number(38,10),
    guest_product_order_subtotal_excl_tariff_amount_month_tot_lm number(38,10),
    guest_product_order_subtotal_excl_tariff_amount_month_tot_ly number(38,10),
    repeat_vip_product_order_subtotal_excl_tariff_amount number(38,10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_mtd number(38,10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_mtd_ly number(38,10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_month_tot_lm number(38,10),
    repeat_vip_product_order_subtotal_excl_tariff_amount_month_tot_ly number(38,10),
	product_order_product_discount_amount number(38,10),
	product_order_product_discount_amount_mtd number(38,10),
	product_order_product_discount_amount_mtd_ly number(38,10),
	product_order_product_discount_amount_month_tot_lm number(38,10),
	product_order_product_discount_amount_month_tot_ly number(38,10),
	activating_product_order_product_discount_amount number(38,10),
	activating_product_order_product_discount_amount_mtd number(38,10),
	activating_product_order_product_discount_amount_mtd_ly number(38,10),
	activating_product_order_product_discount_amount_month_tot_lm number(38,10),
	activating_product_order_product_discount_amount_month_tot_ly number(38,10),
	nonactivating_product_order_product_discount_amount number(38,10),
	nonactivating_product_order_product_discount_amount_mtd number(38,10),
	nonactivating_product_order_product_discount_amount_mtd_ly number(38,10),
	nonactivating_product_order_product_discount_amount_month_tot_lm number(38,10),
	nonactivating_product_order_product_discount_amount_month_tot_ly number(38,10),
	shipping_revenue number(38,10),
	shipping_revenue_mtd number(38,10),
	shipping_revenue_mtd_ly number(38,10),
	shipping_revenue_month_tot_lm number(38,10),
	shipping_revenue_month_tot_ly number(38,10),
	activating_shipping_revenue number(38,10),
	activating_shipping_revenue_mtd number(38,10),
	activating_shipping_revenue_mtd_ly number(38,10),
	activating_shipping_revenue_month_tot_lm number(38,10),
	activating_shipping_revenue_month_tot_ly number(38,10),
	nonactivating_shipping_revenue number(38,10),
	nonactivating_shipping_revenue_mtd number(38,10),
	nonactivating_shipping_revenue_mtd_ly number(38,10),
	nonactivating_shipping_revenue_month_tot_lm number(38,10),
	nonactivating_shipping_revenue_month_tot_ly number(38,10),
	product_order_noncash_credit_redeemed_amount number(38,10),
	product_order_noncash_credit_redeemed_amount_mtd number(38,10),
	product_order_noncash_credit_redeemed_amount_mtd_ly number(38,10),
	product_order_noncash_credit_redeemed_amount_month_tot_lm number(38,10),
	product_order_noncash_credit_redeemed_amount_month_tot_ly number(38,10),
	activating_product_order_noncash_credit_redeemed_amount number(38,10),
	activating_product_order_noncash_credit_redeemed_amount_mtd number(38,10),
	activating_product_order_noncash_credit_redeemed_amount_mtd_ly number(38,10),
	activating_product_order_noncash_credit_redeemed_amount_month_tot_lm number(38,10),
	activating_product_order_noncash_credit_redeemed_amount_month_tot_ly number(38,10),
	nonactivating_product_order_noncash_credit_redeemed_amount number(38,10),
	nonactivating_product_order_noncash_credit_redeemed_amount_mtd number(38,10),
	nonactivating_product_order_noncash_credit_redeemed_amount_mtd_ly number(38,10),
	nonactivating_product_order_noncash_credit_redeemed_amount_month_tot_lm number(38,10),
	nonactivating_product_order_noncash_credit_redeemed_amount_month_tot_ly number(38,10),
	product_order_count number(38,0),
	product_order_count_mtd number(38,0),
	product_order_count_mtd_ly number(38,0),
	product_order_count_month_tot_lm number(38,0),
	product_order_count_month_tot_ly number(38,0),
	activating_product_order_count number(38,0),
	activating_product_order_count_mtd number(38,0),
	activating_product_order_count_mtd_ly number(38,0),
	activating_product_order_count_month_tot_lm number(38,0),
	activating_product_order_count_month_tot_ly number(38,0),
	activating_product_order_count_budget number(19,7),
	activating_product_order_count_forecast number(19,7),
	nonactivating_product_order_count number(38,0),
	nonactivating_product_order_count_mtd number(38,0),
	nonactivating_product_order_count_mtd_ly number(38,0),
	nonactivating_product_order_count_month_tot_lm number(38,0),
	nonactivating_product_order_count_month_tot_ly number(38,0),
	nonactivating_product_order_count_budget number(19,7),
	nonactivating_product_order_count_forecast number(19,7),
	guest_product_order_count number(38,0),
	guest_product_order_count_mtd number(38,0),
	guest_product_order_count_mtd_ly number(38,0),
	guest_product_order_count_month_tot_lm number(38,0),
	guest_product_order_count_month_tot_ly number(38,0),
	unit_count number(38,0),
	unit_count_mtd number(38,0),
	unit_count_mtd_ly number(38,0),
	unit_count_month_tot_lm number(38,0),
	unit_count_month_tot_ly number(38,0),
	unit_count_budget number(19,7),
	unit_count_forecast number(19,7),
	activating_unit_count number(38,0),
	activating_unit_count_mtd number(38,0),
	activating_unit_count_mtd_ly number(38,0),
	activating_unit_count_month_tot_lm number(38,0),
	activating_unit_count_month_tot_ly number(38,0),
	activating_unit_count_budget number(19,7),
	activating_unit_count_forecast number(19,7),
	nonactivating_unit_count number(38,0),
	nonactivating_unit_count_mtd number(38,0),
	nonactivating_unit_count_mtd_ly number(38,0),
	nonactivating_unit_count_month_tot_lm number(38,0),
	nonactivating_unit_count_month_tot_ly number(38,0),
	nonactivating_unit_count_budget number(19,7),
	nonactivating_unit_count_forecast number(19,7),
    activating_product_order_air_vip_price number(38,10),
    activating_product_order_air_vip_price_mtd number(38,10),
    activating_product_order_air_vip_price_mtd_ly number(38,10),
    activating_product_order_air_vip_price_month_tot_lm number(38,10),
    activating_product_order_air_vip_price_month_tot_ly number(38,10),
    nonactivating_product_order_air_price number(38,10),
    nonactivating_product_order_air_price_mtd number(38,10),
    nonactivating_product_order_air_price_mtd_ly number(38,10),
    nonactivating_product_order_air_price_month_tot_lm number(38,10),
    nonactivating_product_order_air_price_month_tot_ly number(38,10),
    repeat_vip_product_order_air_vip_price number(38,10),
    repeat_vip_product_order_air_vip_price_mtd number(38,10),
    repeat_vip_product_order_air_vip_price_mtd_ly number(38,10),
    repeat_vip_product_order_air_vip_price_month_tot_lm number(38,10),
    repeat_vip_product_order_air_vip_price_month_tot_ly number(38,10),
    guest_product_order_retail_unit_price number(38,10),
    guest_product_order_retail_unit_price_mtd number(38,10),
    guest_product_order_retail_unit_price_mtd_ly number(38,10),
    guest_product_order_retail_unit_price_month_tot_lm number(38,10),
    guest_product_order_retail_unit_price_month_tot_ly number(38,10),
    activating_product_order_price_offered_amount number(38,10),
    activating_product_order_price_offered_amount_mtd number(38,10),
    activating_product_order_price_offered_amount_mtd_ly number(38,10),
    activating_product_order_price_offered_amount_month_tot_lm number(38,10),
    activating_product_order_price_offered_amount_month_tot_ly number(38,10),
    nonactivating_product_order_price_offered_amount number(38,10),
    nonactivating_product_order_price_offered_amount_mtd number(38,10),
    nonactivating_product_order_price_offered_amount_mtd_ly number(38,10),
    nonactivating_product_order_price_offered_amount_month_tot_lm number(38,10),
    nonactivating_product_order_price_offered_amount_month_tot_ly number(38,10),
    guest_product_order_price_offered_amount number(38,10),
    guest_product_order_price_offered_amount_mtd number(38,10),
    guest_product_order_price_offered_amount_mtd_ly number(38,10),
    guest_product_order_price_offered_amount_month_tot_lm number(38,10),
    guest_product_order_price_offered_amount_month_tot_ly number(38,10),
    repeat_vip_product_order_price_offered_amount number(38,10),
    repeat_vip_product_order_price_offered_amount_mtd number(38,10),
    repeat_vip_product_order_price_offered_amount_mtd_ly number(38,10),
    repeat_vip_product_order_price_offered_amount_month_tot_lm number(38,10),
    repeat_vip_product_order_price_offered_amount_month_tot_ly number(38,10),
    product_order_landed_product_cost_amount number(38,10),
	product_order_landed_product_cost_amount_mtd number(38,10),
	product_order_landed_product_cost_amount_mtd_ly number(38,10),
	product_order_landed_product_cost_amount_month_tot_lm number(38,10),
	product_order_landed_product_cost_amount_month_tot_ly number(38,10),
	activating_product_order_landed_product_cost_amount number(38,10),
	activating_product_order_landed_product_cost_amount_mtd number(38,10),
	activating_product_order_landed_product_cost_amount_mtd_ly number(38,10),
	activating_product_order_landed_product_cost_amount_month_tot_lm number(38,10),
	activating_product_order_landed_product_cost_amount_month_tot_ly number(38,10),
	nonactivating_product_order_landed_product_cost_amount number(38,10),
	nonactivating_product_order_landed_product_cost_amount_mtd number(38,10),
	nonactivating_product_order_landed_product_cost_amount_mtd_ly number(38,10),
	nonactivating_product_order_landed_product_cost_amount_month_tot_lm number(38,10),
	nonactivating_product_order_landed_product_cost_amount_month_tot_ly number(38,10),
	product_order_shipping_cost_amount number(38,12),
	product_order_shipping_cost_amount_mtd number(38,12),
	product_order_shipping_cost_amount_mtd_ly number(38,12),
	product_order_shipping_cost_amount_month_tot_lm number(38,12),
	product_order_shipping_cost_amount_month_tot_ly number(38,12),
	product_order_shipping_supplies_cost_amount number(38,12),
	product_order_shipping_supplies_cost_amount_mtd number(38,12),
	product_order_shipping_supplies_cost_amount_mtd_ly number(38,12),
	product_order_shipping_supplies_cost_amount_month_tot_lm number(38,12),
	product_order_shipping_supplies_cost_amount_month_tot_ly number(38,12),
	product_order_direct_cogs_amount number(38,12),
	product_order_direct_cogs_amount_mtd number(38,12),
	product_order_direct_cogs_amount_mtd_ly number(38,12),
	product_order_direct_cogs_amount_month_tot_lm number(38,12),
	product_order_direct_cogs_amount_month_tot_ly number(38,12),
	product_order_cash_refund_amount number(38,10),
	product_order_cash_refund_amount_mtd number(38,10),
	product_order_cash_refund_amount_mtd_ly number(38,10),
	product_order_cash_refund_amount_month_tot_lm number(38,10),
	product_order_cash_refund_amount_month_tot_ly number(38,10),
	product_order_cash_chargeback_amount number(38,10),
	product_order_cash_chargeback_amount_mtd number(38,10),
	product_order_cash_chargeback_amount_mtd_ly number(38,10),
	product_order_cash_chargeback_amount_month_tot_lm number(38,10),
	product_order_cash_chargeback_amount_month_tot_ly number(38,10),
	product_cost_returned_resaleable_incl_reship_exch number(38,12),
	product_cost_returned_resaleable_incl_reship_exch_mtd number(38,12),
	product_cost_returned_resaleable_incl_reship_exch_mtd_ly number(38,12),
	product_cost_returned_resaleable_incl_reship_exch_month_tot_lm number(38,12),
	product_cost_returned_resaleable_incl_reship_exch_month_tot_ly number(38,12),
	product_order_cost_product_returned_damaged_amount number(38,12),
	product_order_cost_product_returned_damaged_amount_mtd number(38,12),
	product_order_cost_product_returned_damaged_amount_mtd_ly number(38,12),
	product_order_cost_product_returned_damaged_amount_month_tot_lm number(38,12),
	product_order_cost_product_returned_damaged_amount_month_tot_ly number(38,12),
	return_shipping_costs_incl_reship_exch number(38,10),
	return_shipping_costs_incl_reship_exch_mtd number(38,10),
	return_shipping_costs_incl_reship_exch_mtd_ly number(38,10),
	return_shipping_costs_incl_reship_exch_month_tot_lm number(38,10),
	return_shipping_costs_incl_reship_exch_month_tot_ly number(38,10),
	return_shipping_costs_incl_reship_exch_budget number(38,12),
	return_shipping_costs_incl_reship_exch_forecast number(38,12),
	product_order_reship_order_count number(38,0),
	product_order_reship_order_count_mtd number(38,0),
	product_order_reship_order_count_mtd_ly number(38,0),
	product_order_reship_order_count_month_tot_lm number(38,0),
	product_order_reship_order_count_month_tot_ly number(38,0),
	product_order_reship_unit_count number(38,0),
	product_order_reship_unit_count_mtd number(38,0),
	product_order_reship_unit_count_mtd_ly number(38,0),
	product_order_reship_unit_count_month_tot_lm number(38,0),
	product_order_reship_unit_count_month_tot_ly number(38,0),
	activating_product_order_reship_unit_count number(38,0),
	activating_product_order_reship_unit_count_mtd number(38,0),
	activating_product_order_reship_unit_count_mtd_ly number(38,0),
	activating_product_order_reship_unit_count_month_tot_lm number(38,0),
	activating_product_order_reship_unit_count_month_tot_ly number(38,0),
	nonactivating_product_order_reship_unit_count number(38,0),
	nonactivating_product_order_reship_unit_count_mtd number(38,0),
	nonactivating_product_order_reship_unit_count_mtd_ly number(38,0),
	nonactivating_product_order_reship_unit_count_month_tot_lm number(38,0),
	nonactivating_product_order_reship_unit_count_month_tot_ly number(38,0),
	product_order_reship_product_cost_amount number(38,10),
	product_order_reship_product_cost_amount_mtd number(38,10),
	product_order_reship_product_cost_amount_mtd_ly number(38,10),
	product_order_reship_product_cost_amount_month_tot_lm number(38,10),
	product_order_reship_product_cost_amount_month_tot_ly number(38,10),
	activating_product_order_reship_product_cost_amount number(38,10),
	activating_product_order_reship_product_cost_amount_mtd number(38,10),
	activating_product_order_reship_product_cost_amount_mtd_ly number(38,10),
	activating_product_order_reship_product_cost_amount_month_tot_lm number(38,10),
	activating_product_order_reship_product_cost_amount_month_tot_ly number(38,10),
	nonactivating_product_order_reship_product_cost_amount number(38,10),
	nonactivating_product_order_reship_product_cost_amount_mtd number(38,10),
	nonactivating_product_order_reship_product_cost_amount_mtd_ly number(38,10),
	nonactivating_product_order_reship_product_cost_amount_month_tot_lm number(38,10),
	nonactivating_product_order_reship_product_cost_amount_month_tot_ly number(38,10),
	product_order_reship_shipping_cost_amount number(38,12),
	product_order_reship_shipping_cost_amount_mtd number(38,12),
	product_order_reship_shipping_cost_amount_mtd_ly number(38,12),
	product_order_reship_shipping_cost_amount_month_tot_lm number(38,12),
	product_order_reship_shipping_cost_amount_month_tot_ly number(38,12),
	product_order_reship_shipping_supplies_cost_amount number(38,12),
	product_order_reship_shipping_supplies_cost_amount_mtd number(38,12),
	product_order_reship_shipping_supplies_cost_amount_mtd_ly number(38,12),
	product_order_reship_shipping_supplies_cost_amount_month_tot_lm number(38,12),
	product_order_reship_shipping_supplies_cost_amount_month_tot_ly number(38,12),
	product_order_exchange_order_count number(38,0),
	product_order_exchange_order_count_mtd number(38,0),
	product_order_exchange_order_count_mtd_ly number(38,0),
	product_order_exchange_order_count_month_tot_lm number(38,0),
	product_order_exchange_order_count_month_tot_ly number(38,0),
	product_order_exchange_unit_count number(38,0),
	product_order_exchange_unit_count_mtd number(38,0),
	product_order_exchange_unit_count_mtd_ly number(38,0),
	product_order_exchange_unit_count_month_tot_lm number(38,0),
	product_order_exchange_unit_count_month_tot_ly number(38,0),
	activating_product_order_exchange_unit_count number(38,0),
	activating_product_order_exchange_unit_count_mtd number(38,0),
	activating_product_order_exchange_unit_count_mtd_ly number(38,0),
	activating_product_order_exchange_unit_count_month_tot_lm number(38,0),
	activating_product_order_exchange_unit_count_month_tot_ly number(38,0),
	nonactivating_product_order_exchange_unit_count number(38,0),
	nonactivating_product_order_exchange_unit_count_mtd number(38,0),
	nonactivating_product_order_exchange_unit_count_mtd_ly number(38,0),
	nonactivating_product_order_exchange_unit_count_month_tot_lm number(38,0),
	nonactivating_product_order_exchange_unit_count_month_tot_ly number(38,0),
	product_order_exchange_product_cost_amount number(38,10),
	product_order_exchange_product_cost_amount_mtd number(38,10),
	product_order_exchange_product_cost_amount_mtd_ly number(38,10),
	product_order_exchange_product_cost_amount_month_tot_lm number(38,10),
	product_order_exchange_product_cost_amount_month_tot_ly number(38,10),
	activating_product_order_exchange_product_cost_amount number(38,10),
	activating_product_order_exchange_product_cost_amount_mtd number(38,10),
	activating_product_order_exchange_product_cost_amount_mtd_ly number(38,10),
	activating_product_order_exchange_product_cost_amount_month_tot_lm number(38,10),
	activating_product_order_exchange_product_cost_amount_month_tot_ly number(38,10),
	nonactivating_product_order_exchange_product_cost_amount number(38,10),
	nonactivating_product_order_exchange_product_cost_amount_mtd number(38,10),
	nonactivating_product_order_exchange_product_cost_amount_mtd_ly number(38,10),
	nonactivating_product_order_exchange_product_cost_amount_month_tot_lm number(38,10),
	nonactivating_product_order_exchange_product_cost_amount_month_tot_ly number(38,10),
	product_order_exchange_shipping_cost_amount number(38,12),
	product_order_exchange_shipping_cost_amount_mtd number(38,12),
	product_order_exchange_shipping_cost_amount_mtd_ly number(38,12),
	product_order_exchange_shipping_cost_amount_month_tot_lm number(38,12),
	product_order_exchange_shipping_cost_amount_month_tot_ly number(38,12),
	product_order_exchange_shipping_supplies_cost_amount number(38,12),
	product_order_exchange_shipping_supplies_cost_amount_mtd number(38,12),
	product_order_exchange_shipping_supplies_cost_amount_mtd_ly number(38,12),
	product_order_exchange_shipping_supplies_cost_amount_month_tot_lm number(38,12),
	product_order_exchange_shipping_supplies_cost_amount_month_tot_ly number(38,12),
	product_gross_revenue number(38,10),
	product_gross_revenue_mtd number(38,10),
	product_gross_revenue_mtd_ly number(38,10),
	product_gross_revenue_month_tot_lm number(38,10),
	product_gross_revenue_month_tot_ly number(38,10),
	activating_product_gross_revenue number(38,10),
	activating_product_gross_revenue_mtd number(38,10),
	activating_product_gross_revenue_mtd_ly number(38,10),
	activating_product_gross_revenue_month_tot_lm number(38,10),
	activating_product_gross_revenue_month_tot_ly number(38,10),
	activating_product_gross_revenue_budget number(38,12),
	activating_product_gross_revenue_forecast number(38,12),
	nonactivating_product_gross_revenue number(38,10),
	nonactivating_product_gross_revenue_mtd number(38,10),
	nonactivating_product_gross_revenue_mtd_ly number(38,10),
	nonactivating_product_gross_revenue_month_tot_lm number(38,10),
	nonactivating_product_gross_revenue_month_tot_ly number(38,10),
	nonactivating_product_gross_revenue_budget number(38,12),
	nonactivating_product_gross_revenue_forecast number(38,12),
	guest_product_gross_revenue number(38,10),
	guest_product_gross_revenue_mtd number(38,10),
	guest_product_gross_revenue_mtd_ly number(38,10),
	guest_product_gross_revenue_month_tot_lm number(38,10),
	guest_product_gross_revenue_month_tot_ly number(38,10),
	product_net_revenue number(38,10),
	product_net_revenue_mtd number(38,10),
	product_net_revenue_mtd_ly number(38,10),
	product_net_revenue_month_tot_lm number(38,10),
	product_net_revenue_month_tot_ly number(38,10),
	activating_product_net_revenue number(38,10),
	activating_product_net_revenue_mtd number(38,10),
	activating_product_net_revenue_mtd_ly number(38,10),
	activating_product_net_revenue_month_tot_lm number(38,10),
	activating_product_net_revenue_month_tot_ly number(38,10),
	activating_product_net_revenue_budget number(38,12),
	activating_product_net_revenue_forecast number(38,12),
	nonactivating_product_net_revenue number(38,10),
	nonactivating_product_net_revenue_mtd number(38,10),
	nonactivating_product_net_revenue_mtd_ly number(38,10),
	nonactivating_product_net_revenue_month_tot_lm number(38,10),
	nonactivating_product_net_revenue_month_tot_ly number(38,10),
	nonactivating_product_net_revenue_budget number(38,12),
	nonactivating_product_net_revenue_forecast number(38,12),
	guest_product_net_revenue number(38,10),
	guest_product_net_revenue_mtd number(38,10),
	guest_product_net_revenue_mtd_ly number(38,10),
	guest_product_net_revenue_month_tot_lm number(38,10),
	guest_product_net_revenue_month_tot_ly number(38,10),
	product_margin_pre_return number(38,12),
	product_margin_pre_return_mtd number(38,12),
	product_margin_pre_return_mtd_ly number(38,12),
	product_margin_pre_return_month_tot_lm number(38,12),
	product_margin_pre_return_month_tot_ly number(38,12),
	activating_product_margin_pre_return number(38,12),
	activating_product_margin_pre_return_mtd number(38,12),
	activating_product_margin_pre_return_mtd_ly number(38,12),
	activating_product_margin_pre_return_month_tot_lm number(38,12),
	activating_product_margin_pre_return_month_tot_ly number(38,12),
	activating_product_margin_pre_return_budget number(38,12),
	activating_product_margin_pre_return_forecast number(38,12),
	product_gross_profit number(38,12),
	product_gross_profit_mtd number(38,12),
	product_gross_profit_mtd_ly number(38,12),
	product_gross_profit_month_tot_lm number(38,12),
	product_gross_profit_month_tot_ly number(38,12),
	activating_product_gross_profit number(38,12),
	activating_product_gross_profit_mtd number(38,12),
	activating_product_gross_profit_mtd_ly number(38,12),
	activating_product_gross_profit_month_tot_lm number(38,12),
	activating_product_gross_profit_month_tot_ly number(38,12),
	activating_product_gross_profit_budget number(38,12),
	activating_product_gross_profit_forecast number(38,12),
	nonactivating_product_gross_profit number(38,12),
	nonactivating_product_gross_profit_mtd number(38,12),
	nonactivating_product_gross_profit_mtd_ly number(38,12),
	nonactivating_product_gross_profit_month_tot_lm number(38,12),
	nonactivating_product_gross_profit_month_tot_ly number(38,12),
	nonactivating_product_gross_profit_budget number(38,12),
	nonactivating_product_gross_profit_forecast number(38,12),
	guest_product_gross_profit number(38,12),
	guest_product_gross_profit_mtd number(38,12),
	guest_product_gross_profit_mtd_ly number(38,12),
	guest_product_gross_profit_month_tot_lm number(38,12),
	guest_product_gross_profit_month_tot_ly number(38,12),
	product_order_cash_gross_revenue number(38,10),
	product_order_cash_gross_revenue_mtd number(38,10),
	product_order_cash_gross_revenue_mtd_ly number(38,10),
	product_order_cash_gross_revenue_month_tot_lm number(38,10),
	product_order_cash_gross_revenue_month_tot_ly number(38,10),
	activating_product_order_cash_gross_revenue number(38,10),
	activating_product_order_cash_gross_revenue_mtd number(38,10),
	activating_product_order_cash_gross_revenue_mtd_ly number(38,10),
	activating_product_order_cash_gross_revenue_month_tot_lm number(38,10),
	activating_product_order_cash_gross_revenue_month_tot_ly number(38,10),
	nonactivating_product_order_cash_gross_revenue number(38,10),
	nonactivating_product_order_cash_gross_revenue_mtd number(38,10),
	nonactivating_product_order_cash_gross_revenue_mtd_ly number(38,10),
	nonactivating_product_order_cash_gross_revenue_month_tot_lm number(38,10),
	nonactivating_product_order_cash_gross_revenue_month_tot_ly number(38,10),
	nonactivating_product_order_cash_gross_revenue_budget number(38,12),
	nonactivating_product_order_cash_gross_revenue_forecast number(38,12),
	cash_gross_revenue number(38,10),
	cash_gross_revenue_mtd number(38,10),
	cash_gross_revenue_mtd_ly number(38,10),
	cash_gross_revenue_month_tot_lm number(38,10),
	cash_gross_revenue_month_tot_ly number(38,10),
	cash_gross_revenue_budget number(38,12),
	cash_gross_revenue_forecast number(38,12),
	activating_cash_gross_revenue number(38,10),
	activating_cash_gross_revenue_mtd number(38,10),
	activating_cash_gross_revenue_mtd_ly number(38,10),
	activating_cash_gross_revenue_month_tot_lm number(38,10),
	activating_cash_gross_revenue_month_tot_ly number(38,10),
	nonactivating_cash_gross_revenue number(38,10),
	nonactivating_cash_gross_revenue_mtd number(38,10),
	nonactivating_cash_gross_revenue_mtd_ly number(38,10),
	nonactivating_cash_gross_revenue_month_tot_lm number(38,10),
	nonactivating_cash_gross_revenue_month_tot_ly number(38,10),
	cash_net_revenue number(38,10),
	cash_net_revenue_mtd number(38,10),
	cash_net_revenue_mtd_ly number(38,10),
	cash_net_revenue_month_tot_lm number(38,10),
	cash_net_revenue_month_tot_ly number(38,10),
	cash_net_revenue_budget number(38,12),
	cash_net_revenue_forecast number(38,12),
	activating_cash_net_revenue number(38,10),
	activating_cash_net_revenue_mtd number(38,10),
	activating_cash_net_revenue_mtd_ly number(38,10),
	activating_cash_net_revenue_month_tot_lm number(38,10),
	activating_cash_net_revenue_month_tot_ly number(38,10),
	activating_cash_net_revenue_budget number(38,12),
	activating_cash_net_revenue_forecast number(38,12),
	nonactivating_cash_net_revenue number(38,10),
	nonactivating_cash_net_revenue_mtd number(38,10),
	nonactivating_cash_net_revenue_mtd_ly number(38,10),
	nonactivating_cash_net_revenue_month_tot_lm number(38,10),
	nonactivating_cash_net_revenue_month_tot_ly number(38,10),
	nonactivating_cash_net_revenue_budget number(38,12),
	nonactivating_cash_net_revenue_forecast number(38,12),
	cash_gross_profit number(38,12),
	cash_gross_profit_mtd number(38,12),
	cash_gross_profit_mtd_ly number(38,12),
	cash_gross_profit_month_tot_lm number(38,12),
	cash_gross_profit_month_tot_ly number(38,12),
	cash_gross_profit_budget number(38,12),
	cash_gross_profit_forecast number(38,12),
	billed_credit_cash_transaction_count number(38,0),
	billed_credit_cash_transaction_count_mtd number(38,0),
	billed_credit_cash_transaction_count_mtd_ly number(38,0),
	billed_credit_cash_transaction_count_month_tot_lm number(38,0),
	billed_credit_cash_transaction_count_month_tot_ly number(38,0),
	billed_credits_successful_on_retry number(38,0),
	billed_credits_successful_on_retry_mtd number(38,0),
	billed_credits_successful_on_retry_mtd_ly number(38,0),
	billed_credits_successful_on_retry_month_tot_lm number(38,0),
	billed_credits_successful_on_retry_month_tot_ly number(38,0),
	billing_cash_refund_amount number(38,10),
	billing_cash_refund_amount_mtd number(38,10),
	billing_cash_refund_amount_mtd_ly number(38,10),
	billing_cash_refund_amount_month_tot_lm number(38,10),
	billing_cash_refund_amount_month_tot_ly number(38,10),
	billing_cash_chargeback_amount number(38,10),
	billing_cash_chargeback_amount_mtd number(38,10),
	billing_cash_chargeback_amount_mtd_ly number(38,10),
	billing_cash_chargeback_amount_month_tot_lm number(38,10),
	billing_cash_chargeback_amount_month_tot_ly number(38,10),
	billed_credit_cash_transaction_amount number(38,10),
	billed_credit_cash_transaction_amount_mtd number(38,10),
	billed_credit_cash_transaction_amount_mtd_ly number(38,10),
	billed_credit_cash_transaction_amount_month_tot_lm number(38,10),
	billed_credit_cash_transaction_amount_month_tot_ly number(38,10),
	billed_credit_cash_transaction_amount_budget number(38,12),
	billed_credit_cash_transaction_amount_forecast number(38,12),
	billed_credit_cash_refund_chargeback_amount number(38,10),
	billed_credit_cash_refund_chargeback_amount_mtd number(38,10),
	billed_credit_cash_refund_chargeback_amount_mtd_ly number(38,10),
	billed_credit_cash_refund_chargeback_amount_month_tot_lm number(38,10),
	billed_credit_cash_refund_chargeback_amount_month_tot_ly number(38,10),
	billed_credit_cash_refund_chargeback_amount_budget number(38,12),
	billed_credit_cash_refund_chargeback_amount_forecast number(38,12),
    activating_billed_cash_credit_redeemed_amount number(38,10),
	billed_cash_credit_redeemed_amount number(38,12),
	billed_cash_credit_redeemed_amount_mtd number(38,12),
	billed_cash_credit_redeemed_amount_mtd_ly number(38,12),
	billed_cash_credit_redeemed_amount_month_tot_lm number(38,12),
	billed_cash_credit_redeemed_amount_month_tot_ly number(38,12),
	billed_cash_credit_redeemed_amount_budget number(38,12),
	billed_cash_credit_redeemed_amount_forecast number(38,12),
	misc_cogs_amount number(38,12),
	misc_cogs_amount_mtd number(38,12),
	misc_cogs_amount_mtd_ly number(38,12),
	misc_cogs_amount_month_tot_lm number(38,12),
	misc_cogs_amount_month_tot_ly number(38,12),
	misc_cogs_amount_budget number(38,12),
	misc_cogs_amount_forecast number(38,12),
	product_order_cash_gross_profit number(38,10),
	product_order_cash_gross_profit_mtd number(38,10),
	product_order_cash_gross_profit_mtd_ly number(38,10),
	product_order_cash_gross_profit_month_tot_lm number(38,10),
	product_order_cash_gross_profit_month_tot_ly number(38,10),
	nonactivating_product_order_cash_gross_profit number(38,10),
	nonactivating_product_order_cash_gross_profit_mtd number(38,10),
	nonactivating_product_order_cash_gross_profit_mtd_ly number(38,10),
	nonactivating_product_order_cash_gross_profit_month_tot_lm number(38,10),
	nonactivating_product_order_cash_gross_profit_month_tot_ly number(38,10),
	nonactivating_product_order_cash_gross_profit_budget number(19,7),
	nonactivating_product_order_cash_gross_profit_forecast number(19,7),
	same_month_billed_credit_redeemed number(38,0),
	same_month_billed_credit_redeemed_mtd number(38,0),
	same_month_billed_credit_redeemed_mtd_ly number(38,0),
	same_month_billed_credit_redeemed_month_tot_lm number(38,0),
	same_month_billed_credit_redeemed_month_tot_ly number(38,0),
	billed_credit_cash_refund_count number(38,0),
	billed_credit_cash_refund_count_mtd number(38,0),
	billed_credit_cash_refund_count_mtd_ly number(38,0),
	billed_credit_cash_refund_count_month_tot_lm number(38,0),
	billed_credit_cash_refund_count_month_tot_ly number(38,0),
	cash_variable_contribution_profit number(38,12),
	cash_variable_contribution_profit_mtd number(38,12),
	cash_variable_contribution_profit_mtd_ly number(38,12),
	cash_variable_contribution_profit_month_tot_lm number(38,12),
	cash_variable_contribution_profit_month_tot_ly number(38,12),
	billed_cash_credit_redeemed_equivalent_count number(38,10),
	billed_cash_credit_redeemed_equivalent_count_mtd number(38,10),
	billed_cash_credit_redeemed_equivalent_count_mtd_ly number(38,10),
	billed_cash_credit_redeemed_equivalent_count_month_tot_lm number(38,10),
	billed_cash_credit_redeemed_equivalent_count_month_tot_ly number(38,10),
	billed_cash_credit_cancelled_equivalent_count number(38,10),
	billed_cash_credit_cancelled_equivalent_count_mtd number(38,10),
	billed_cash_credit_cancelled_equivalent_count_mtd_ly number(38,10),
	billed_cash_credit_cancelled_equivalent_count_month_tot_lm number(38,10),
	billed_cash_credit_cancelled_equivalent_count_month_tot_ly number(38,10),
	cash_gross_profit_percent_of_net_cash_budget number(19,7),
	cash_gross_profit_percent_of_net_cash_forecast number(19,7),
	product_order_and_billing_cash_refund_budget number(38,12),
	product_order_and_billing_cash_refund_forecast number(38,12),
	product_order_and_billing_chargebacks_budget number(38,12),
	product_order_and_billing_chargebacks_forecast number(38,12),
	refunds_plus_chargebacks_as_percent_of_cash_gross_rev_budget number(19,7),
	refunds_plus_chargebacks_as_percent_of_cash_gross_rev_forecast number(19,7),
	activating_aov_budget number(19,7),
	activating_aov_forecast number(19,7),
	activating_upt_budget number(19,7),
	activating_upt_forecast number(19,7),
	activating_discount_percent_budget number(19,7),
	activating_discount_percent_forecast number(19,7),
	activating_product_gross_profit_percent_budget number(19,7),
	activating_product_gross_profit_percent_forecast number(19,7),
	activating_product_margin_pre_return_per_order_budget number(19,7),
	activating_product_margin_pre_return_per_order_forecast number(19,7),
	activating_product_margin_pre_return_percent_budget number(19,7),
	activating_product_margin_pre_return_percent_forecast number(19,7),
	nonactivating_aov_budget number(38,12),
	nonactivating_aov_forecast number(38,12),
	nonactivating_upt_budget number(19,7),
	nonactivating_upt_forecast number(19,7),
	nonactivating_discount_percent_budget number(19,7),
	nonactivating_discount_percent_forecast number(19,7),
	nonactivating_product_gross_profit_percent_budget number(19,7),
	nonactivating_product_gross_profit_percent_forecast number(19,7),
	shipping_cost_incl_reship_exch_budget number(38,12),
	shipping_cost_incl_reship_exch_forecast number(38,12),
	shipping_supplies_cost_incl_reship_exch_budget number(38,12),
	shipping_supplies_cost_incl_reship_exch_forecast number(38,12),
	product_cost_calc_budget number(38,12),
	product_cost_calc_forecast number(38,12),
	product_order_tariff_amount number(38,10),
	product_order_product_subtotal_amount number(38,10),
	product_order_shipping_discount_amount number(38,10),
	product_order_shipping_revenue_before_discount_amount number(38,10),
	product_order_tax_amount number(38,10),
	product_order_cash_transaction_amount number(38,10),
	product_order_cash_credit_redeemed_amount number(38,10),
	product_order_loyalty_unit_count number(38,0),
	product_order_outfit_component_unit_count number(38,0),
	product_order_outfit_count number(38,0),
	product_order_discounted_unit_count number(38,0),
	product_order_zero_revenue_unit_count number(38,0),
	product_order_cash_credit_refund_amount number(38,10),
	product_order_cash_credit_refund_amount_mtd varchar(16777216),
	product_order_cash_credit_refund_amount_mtd_ly varchar(16777216),
	product_order_cash_credit_refund_amount_month_tot_lm varchar(16777216),
	product_order_cash_credit_refund_amount_month_tot_ly varchar(16777216),
	product_order_cash_credit_refund_amount_budget varchar(16777216),
	product_order_cash_credit_refund_amount_forecast varchar(16777216),
	product_order_noncash_credit_refund_amount number(38,10),
	product_order_noncash_credit_refund_amount_mtd varchar(16777216),
	product_order_noncash_credit_refund_amount_mtd_ly varchar(16777216),
	product_order_noncash_credit_refund_amount_month_tot_lm varchar(16777216),
	product_order_noncash_credit_refund_amount_month_tot_ly varchar(16777216),
	product_order_noncash_credit_refund_amount_budget varchar(16777216),
	product_order_noncash_credit_refund_amount_forecast varchar(16777216),
	product_order_return_unit_count number(38,0),
    product_order_return_unit_count_mtd NUMBER(38),
    product_order_return_unit_count_mtd_ly NUMBER(38),
    product_order_return_unit_count_month_tot_lm NUMBER(38),
    product_order_return_unit_count_month_tot_ly NUMBER(38),
	product_order_exchange_direct_cogs_amount number(38,12),
	product_order_selling_expenses_amount number(38,12),
	product_order_payment_processing_cost_amount number(38,12),
	product_order_variable_gms_cost_amount number(38,12),
	product_order_variable_warehouse_cost_amount number(38,12),
	billing_selling_expenses_amount number(38,12),
	billing_payment_processing_cost_amount number(38,12),
	billing_variable_gms_cost_amount number(38,12),
	product_order_amount_to_pay number(38,10),
	product_gross_revenue_excl_shipping number(38,10),
	product_margin_pre_return_excl_shipping number(38,10),
    activating_product_margin_pre_return_excl_shipping number(38,10),
	product_variable_contribution_profit number(38,12),
	product_order_cash_net_revenue number(38,10),
	product_order_cash_margin_pre_return number(38,10),
	billing_cash_gross_revenue number(38,10),
	billing_cash_net_revenue number(38,10),
	billing_order_transaction_count number(38,0),
	billing_order_transaction_count_mtd number(38,0),
	billing_order_transaction_count_mtd_ly number(38,0),
	billing_order_transaction_count_month_tot_lm number(38,0),
	billing_order_transaction_count_month_tot_ly number(38,0),
	billing_order_transaction_count_budget number(19,7),
	billing_order_transaction_count_forecast number(19,7),
	membership_fee_cash_transaction_amount number(38,10),
	gift_card_transaction_amount number(38,10),
    gift_card_transaction_amount_mtd NUMBER(38, 10),
    gift_card_transaction_amount_mtd_ly NUMBER(38, 10),
    gift_card_transaction_amount_month_tot_lm NUMBER(38, 10),
    gift_card_transaction_amount_month_tot_ly NUMBER(38, 10),
	legacy_credit_cash_transaction_amount number(38,10),
    legacy_credit_cash_transaction_amount_mtd NUMBER(38, 10),
    legacy_credit_cash_transaction_amount_mtd_ly NUMBER(38, 10),
    legacy_credit_cash_transaction_amount_month_tot_lm NUMBER(38, 10),
    legacy_credit_cash_transaction_amount_month_tot_ly NUMBER(38, 10),
	membership_fee_cash_refund_chargeback_amount number(38,10),
    gift_card_cash_refund_chargeback_amount_mtd number(38,10),
    gift_card_cash_refund_chargeback_amount_mtd_ly number(38,10),
    gift_card_cash_refund_chargeback_amount_month_tot_lm number(38,10),
    gift_card_cash_refund_chargeback_amount_month_tot_ly number(38,10),
    legacy_credit_cash_refund_chargeback_amount_mtd number(38,10),
    legacy_credit_cash_refund_chargeback_amount_mtd_ly number(38,10),
    legacy_credit_cash_refund_chargeback_amount_month_tot_lm number(38,10),
    legacy_credit_cash_refund_chargeback_amount_month_tot_ly number(38,10),
	billed_cash_credit_issued_amount number(38,12),
	billed_cash_credit_cancelled_amount number(38,12),
	billed_cash_credit_expired_amount number(38,12),
	billed_cash_credit_issued_equivalent_count number(38,0),
	billed_cash_credit_expired_equivalent_count number(38,10),
	refund_cash_credit_issued_amount number(38,12),
	refund_cash_credit_redeemed_amount number(38,12),
	refund_cash_credit_redeemed_amount_mtd number(38,12),
	refund_cash_credit_redeemed_amount_mtd_ly number(38,12),
	refund_cash_credit_redeemed_amount_month_tot_lm number(38,12),
	refund_cash_credit_redeemed_amount_month_tot_ly number(38,12),
	refund_cash_credit_redeemed_amount_budget number(38,12),
	refund_cash_credit_redeemed_amount_forecast number(38,12),
	refund_cash_credit_cancelled_amount number(38,12),
	refund_cash_credit_expired_amount number(38,12),
	other_cash_credit_issued_amount number(38,12),
	other_cash_credit_redeemed_amount number(38,12),
    other_cash_credit_redeemed_amount_mtd number(38,12),
    other_cash_credit_redeemed_amount_mtd_ly number(38,12),
    other_cash_credit_redeemed_amount_month_tot_lm number(38,12),
    other_cash_credit_redeemed_amount_month_tot_ly number(38,12),
	other_cash_credit_cancelled_amount number(38,12),
	other_cash_credit_expired_amount number(38,12),
	noncash_credit_issued_amount number(38,12),
	noncash_credit_issued_amount_mtd number(38,12),
    noncash_credit_issued_amount_mtd_ly number(38,12),
    noncash_credit_issued_amount_month_tot_lm number(38,12),
    noncash_credit_issued_amount_month_tot_ly number(38,12),
	noncash_credit_cancelled_amount number(38,12),
	noncash_credit_expired_amount number(38,12),
	net_unredeemed_credit_billings_budget number(38,12),
	net_unredeemed_credit_billings_forecast number(38,12),
	budgeted_fx_rate number(9,6),
	pending_order_count number(18,0),
	pending_order_local_amount number(36,4),
	pending_order_usd_amount number(38,10),
	pending_order_eur_amount number(38,10),
    pending_order_cash_margin_pre_return_local_amount NUMBER(38, 10),
    pending_order_cash_margin_pre_return_usd_amount NUMBER(38, 10),
    pending_order_cash_margin_pre_return_eur_amount NUMBER(38, 10),
	leads number(38,0),
	leads_mtd number(38,0),
	leads_mtd_ly number(38,0),
	leads_month_tot_lm number(38,0),
	leads_month_tot_ly number(38,0),
	leads_budget number(19,7),
	leads_forecast number(19,7),
	reactivated_leads number(38,0),
	reactivated_leads_mtd number(38,0),
	reactivated_leads_mtd_ly number(38,0),
	reactivated_leads_month_tot_lm number(38,0),
	reactivated_leads_month_tot_ly number(38,0),
	new_vips number(38,0),
	new_vips_mtd number(38,0),
	new_vips_mtd_ly number(38,0),
	new_vips_month_tot_lm number(38,0),
	new_vips_month_tot_ly number(38,0),
	new_vips_budget number(19,7),
	new_vips_forecast number(19,7),
	reactivated_vips number(38,0),
	reactivated_vips_mtd number(38,0),
	reactivated_vips_mtd_ly number(38,0),
	reactivated_vips_month_tot_lm number(38,0),
	reactivated_vips_month_tot_ly number(38,0),
	vips_from_reactivated_leads_m1 number(38,0),
	vips_from_reactivated_leads_m1_mtd number(38,0),
	vips_from_reactivated_leads_m1_mtd_ly number(38,0),
	vips_from_reactivated_leads_m1_month_tot_lm number(38,0),
	vips_from_reactivated_leads_m1_month_tot_ly number(38,0),
	paid_vips number(38,0),
	paid_vips_mtd number(38,0),
	paid_vips_mtd_ly number(38,0),
	paid_vips_month_tot_lm number(38,0),
	paid_vips_month_tot_ly number(38,0),
	unpaid_vips number(38,0),
	unpaid_vips_mtd number(38,0),
	unpaid_vips_mtd_ly number(38,0),
	unpaid_vips_month_tot_lm number(38,0),
	unpaid_vips_month_tot_ly number(38,0),
	new_vips_m1 number(38,0),
	new_vips_m1_mtd number(38,0),
	new_vips_m1_mtd_ly number(38,0),
	new_vips_m1_month_tot_lm number(38,0),
	new_vips_m1_month_tot_ly number(38,0),
	new_vips_m1_budget number(19,7),
	new_vips_m1_forecast number(19,7),
	paid_vips_m1 number(38,0),
	paid_vips_m1_mtd number(38,0),
	paid_vips_m1_mtd_ly number(38,0),
	paid_vips_m1_month_tot_lm number(38,0),
	paid_vips_m1_month_tot_ly number(38,0),
	cancels number(38,0),
	cancels_mtd number(38,0),
	cancels_mtd_ly number(38,0),
	cancels_month_tot_lm number(38,0),
	cancels_month_tot_ly number(38,0),
	cancels_budget number(19,7),
	cancels_forecast number(19,7),
	m1_cancels number(38,0),
	m1_cancels_mtd number(38,0),
	m1_cancels_mtd_ly number(38,0),
	m1_cancels_month_tot_lm number(38,0),
	m1_cancels_month_tot_ly number(38,0),
	bop_vips number(38,0),
	bop_vips_mtd number(38,0),
	bop_vips_mtd_ly number(38,0),
	bop_vips_month_tot_lm number(38,0),
	bop_vips_month_tot_ly number(38,0),
	bop_vips_budget number(19,7),
	bop_vips_forecast number(19,7),
	media_spend number(38,10),
	media_spend_mtd number(38,10),
	media_spend_mtd_ly number(38,10),
	media_spend_month_tot_lm number(38,10),
	media_spend_month_tot_ly number(38,10),
	media_spend_budget number(38,12),
	media_spend_forecast number(38,12),
	meta_update_datetime timestamp_ltz(3),
	meta_create_datetime timestamp_ltz(3),
	snapshot_datetime timestamp_ltz(3),
	nonactivating_cash_gross_profit number(38,12),
	nonactivating_cash_gross_profit_mtd number(38,12),
	nonactivating_cash_gross_profit_mtd_ly number(38,12),
	nonactivating_cash_gross_profit_month_tot_lm number(38,12),
	nonactivating_cash_gross_profit_month_tot_ly number(38,12),
	nonactivating_cash_gross_profit_budget number(38,12),
	nonactivating_cash_gross_profit_forecast number(38,12),
	product_order_product_subtotal_amount_mtd number(38,12),
	product_order_product_subtotal_amount_mtd_ly number(38,12),
	product_order_product_subtotal_amount_month_tot_lm number(38,12),
	product_order_product_subtotal_amount_month_tot_ly number(38,12),
	activating_product_order_product_subtotal_amount number(38,12),
	activating_product_order_product_subtotal_amount_mtd number(38,12),
	activating_product_order_product_subtotal_amount_mtd_ly number(38,12),
	activating_product_order_product_subtotal_amount_month_tot_lm number(38,12),
	activating_product_order_product_subtotal_amount_month_tot_ly number(38,12),
	nonactivating_product_order_product_subtotal_amount number(38,12),
	nonactivating_product_order_product_subtotal_amount_mtd number(38,12),
	nonactivating_product_order_product_subtotal_amount_mtd_ly number(38,12),
	nonactivating_product_order_product_subtotal_amount_month_tot_lm number(38,12),
	nonactivating_product_order_product_subtotal_amount_month_tot_ly number(38,12),
	cash_contribution_after_media_budget number(38,10),
	cash_contribution_after_media_forecast number(38,10),
	refund_cash_credit_issued_amount_mtd number(38,10),
	refund_cash_credit_issued_amount_mtd_ly number(38,10),
	refund_cash_credit_issued_amount_month_tot_lm number(38,10),
	refund_cash_credit_issued_amount_month_tot_ly number(38,10),
	refund_cash_credit_issued_amount_budget number(38,10),
	refund_cash_credit_issued_amount_forecast number(38,10),
	refund_cash_credit_cancelled_amount_mtd number(38,10),
	refund_cash_credit_cancelled_amount_mtd_ly number(38,10),
	refund_cash_credit_cancelled_amount_month_tot_lm number(38,10),
	refund_cash_credit_cancelled_amount_month_tot_ly number(38,10),
	net_unredeemed_refund_credit_budget number(38,10),
	net_unredeemed_refund_credit_forecast number(38,10),
	billed_cash_credit_issued_equivalent_count_mtd number(38,0),
	billed_cash_credit_issued_equivalent_count_mtd_ly number(38,0),
	billed_cash_credit_issued_equivalent_count_month_tot_lm number(38,0),
	billed_cash_credit_issued_equivalent_count_month_tot_ly number(38,0),
	membership_credits_redeemed_count_budget number(38,0),
	membership_credits_redeemed_count_forecast number(38,0),
	membership_credits_cancelled_count_budget number(38,0),
	membership_credits_cancelled_count_forecast number(38,0),
	snapshot_datetime_budget timestamp_ltz(3),
	snapshot_datetime_forecast timestamp_ltz(3),
    guest_product_order_product_discount_amount number(38, 10),
    guest_product_order_product_discount_amount_mtd number(38, 10),
    guest_product_order_product_discount_amount_mtd_ly number(38, 10),
    guest_product_order_product_discount_amount_month_tot_lm number(38, 10),
    guest_product_order_product_discount_amount_month_tot_ly number(38, 10),
    guest_shipping_revenue number(38, 10),
    guest_shipping_revenue_mtd number(38, 10),
    guest_shipping_revenue_mtd_ly number(38, 10),
    guest_shipping_revenue_month_tot_lm number(38, 10),
    guest_shipping_revenue_month_tot_ly number(38, 10),
    guest_unit_count number(38, 0),
    guest_unit_count_mtd number(38, 0),
    guest_unit_count_mtd_ly number(38, 0),
    guest_unit_count_month_tot_lm number(38, 0),
    guest_unit_count_month_tot_ly number(38, 0),
    product_order_reship_exch_order_count_budget number(38, 0),
    product_order_reship_exch_order_count_forecast number(38, 0),
    product_gross_revenue_excl_shipping_mtd number(38, 10),
    product_gross_revenue_excl_shipping_mtd_ly number(38, 10),
    product_gross_revenue_excl_shipping_month_tot_lm number(38, 10),
    product_gross_revenue_excl_shipping_month_tot_ly number(38, 10),
    activating_product_gross_revenue_excl_shipping number(38, 10),
    activating_product_gross_revenue_excl_shipping_mtd number(38, 10),
    activating_product_gross_revenue_excl_shipping_mtd_ly number(38, 10),
    activating_product_gross_revenue_excl_shipping_month_tot_lm number(38, 10),
    activating_product_gross_revenue_excl_shipping_month_tot_ly number(38, 10),
    nonactivating_product_gross_revenue_excl_shipping number(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_mtd number(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_mtd_ly number(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_month_tot_lm number(38, 10),
    nonactivating_product_gross_revenue_excl_shipping_month_tot_ly number(38, 10),
    guest_product_gross_revenue_excl_shipping number(38, 10),
    guest_product_gross_revenue_excl_shipping_mtd number(38, 10),
    guest_product_gross_revenue_excl_shipping_mtd_ly number(38, 10),
    guest_product_gross_revenue_excl_shipping_month_tot_lm number(38, 10),
    guest_product_gross_revenue_excl_shipping_month_tot_ly number(38, 10),
    membership_fee_cash_transaction_amount_mtd number(38, 10),
    membership_fee_cash_transaction_amount_mtd_ly number(38, 10),
    membership_fee_cash_transaction_amount_month_tot_lm number(38, 10),
    membership_fee_cash_transaction_amount_month_tot_ly number(38, 10),
    membership_fee_cash_refund_chargeback_amount_mtd number(38, 10),
    membership_fee_cash_refund_chargeback_amount_mtd_ly number(38, 10),
    membership_fee_cash_refund_chargeback_amount_month_tot_lm number(38, 10),
    membership_fee_cash_refund_chargeback_amount_month_tot_ly number(38, 10),
    repeat_vip_product_order_product_discount_amount number(38, 10),
    repeat_vip_product_order_product_discount_amount_mtd number(38, 10),
    repeat_vip_product_order_product_discount_amount_mtd_ly number(38, 10),
    repeat_vip_product_order_product_discount_amount_month_tot_lm number(38, 10),
    repeat_vip_product_order_product_discount_amount_month_tot_ly number(38, 10),
    repeat_vip_product_order_count number(38, 0),
    repeat_vip_product_order_count_mtd number(38, 0),
    repeat_vip_product_order_count_mtd_ly number(38, 0),
    repeat_vip_product_order_count_month_tot_lm number(38, 0),
    repeat_vip_product_order_count_month_tot_ly number(38, 0),
    repeat_vip_unit_count number(38, 0),
    repeat_vip_unit_count_mtd number(38, 0),
    repeat_vip_unit_count_mtd_ly number(38, 0),
    repeat_vip_unit_count_month_tot_lm number(38, 0),
    repeat_vip_unit_count_month_tot_ly number(38, 0),
    repeat_vip_product_gross_revenue number(38, 10),
    repeat_vip_product_gross_revenue_mtd number(38, 10),
    repeat_vip_product_gross_revenue_mtd_ly number(38, 10),
    repeat_vip_product_gross_revenue_month_tot_lm number(38, 10),
    repeat_vip_product_gross_revenue_month_tot_ly number(38, 10),
    repeat_vip_product_net_revenue number(38, 10),
    repeat_vip_product_net_revenue_mtd number(38, 10),
    repeat_vip_product_net_revenue_mtd_ly number(38, 10),
    repeat_vip_product_net_revenue_month_tot_lm number(38, 10),
    repeat_vip_product_net_revenue_month_tot_ly number(38, 10),
    repeat_vip_product_gross_profit number(38, 10),
    repeat_vip_product_gross_profit_mtd number(38, 10),
    repeat_vip_product_gross_profit_mtd_ly number(38, 10),
    repeat_vip_product_gross_profit_month_tot_lm number(38, 10),
    repeat_vip_product_gross_profit_month_tot_ly number(38, 10),
    first_guest_product_margin_pre_return number(38, 10),
    first_guest_product_margin_pre_return_mtd number(38, 10),
    first_guest_product_margin_pre_return_mtd_ly number(38, 10),
    first_guest_product_margin_pre_return_month_tot_lm number(38, 10),
    first_guest_product_margin_pre_return_month_tot_ly number(38, 10),
    merch_purchase_count number(38, 0),
    merch_purchase_count_mtd number(38, 0),
    merch_purchase_count_mtd_ly number(38, 0),
    merch_purchase_count_month_tot_lm number(38, 0),
    merch_purchase_count_month_tot_ly number(38, 0),
    merch_purchase_hyperion_count NUMBER(38),
    merch_purchase_hyperion_count_mtd NUMBER(38),
    merch_purchase_hyperion_count_mtd_ly NUMBER(38),
    merch_purchase_hyperion_count_month_tot_lm NUMBER(38),
    merch_purchase_hyperion_count_month_tot_ly NUMBER(38),
    bom_vips number(38, 0),
    skip_count number(38, 0),
    cash_net_revenue_budgeted_fx number(38, 10),
    cash_net_revenue_budgeted_fx_mtd number(38, 10),
    cash_net_revenue_budgeted_fx_mtd_ly number(38, 10),
    cash_net_revenue_budgeted_fx_month_tot_lm number(38, 10),
    cash_net_revenue_budgeted_fx_month_tot_ly number(38, 10),
    product_order_count_excl_seeding number(38,0),
    product_order_count_excl_seeding_mtd number(38,0),
    product_order_count_excl_seeding_mtd_ly number(38,0),
    product_order_count_excl_seeding_month_tot_lm number(38,0),
    product_order_count_excl_seeding_month_tot_ly number(38,0),
    activating_product_order_count_excl_seeding number(38,0),
    activating_product_order_count_excl_seeding_mtd number(38,0),
    activating_product_order_count_excl_seeding_mtd_ly number(38,0),
    activating_product_order_count_excl_seeding_month_tot_lm number(38,0),
    activating_product_order_count_excl_seeding_month_tot_ly number(38,0),
    nonactivating_product_order_count_excl_seeding number(38,0),
    nonactivating_product_order_count_excl_seeding_mtd number(38,0),
    nonactivating_product_order_count_excl_seeding_mtd_ly number(38,0),
    nonactivating_product_order_count_excl_seeding_month_tot_lm number(38,0),
    nonactivating_product_order_count_excl_seeding_month_tot_ly number(38,0),
    guest_product_order_count_excl_seeding number(38,0),
    guest_product_order_count_excl_seeding_mtd number(38,0),
    guest_product_order_count_excl_seeding_mtd_ly number(38,0),
    guest_product_order_count_excl_seeding_month_tot_lm number(38,0),
    guest_product_order_count_excl_seeding_month_tot_ly number(38,0),
    repeat_vip_product_order_count_excl_seeding number(38,0),
    repeat_vip_product_order_count_excl_seeding_mtd number(38,0),
    repeat_vip_product_order_count_excl_seeding_mtd_ly number(38,0),
    repeat_vip_product_order_count_excl_seeding_month_tot_lm number(38,0),
    repeat_vip_product_order_count_excl_seeding_month_tot_ly number(38,0),
    reactivated_vip_product_order_count_excl_seeding number(38,0),
    reactivated_vip_product_order_count_excl_seeding_mtd number(38,0),
    reactivated_vip_product_order_count_excl_seeding_mtd_ly number(38,0),
    reactivated_vip_product_order_count_excl_seeding_month_tot_lm number(38,0),
    reactivated_vip_product_order_count_excl_seeding_month_tot_ly number(38,0),
    product_margin_pre_return_excl_seeding number(38,12),
    product_margin_pre_return_excl_seeding_mtd number(38,12),
    product_margin_pre_return_excl_seeding_mtd_ly number(38,12),
    product_margin_pre_return_excl_seeding_month_tot_lm number(38,12),
    product_margin_pre_return_excl_seeding_month_tot_ly number(38,12),
    activating_product_margin_pre_return_excl_seeding number(38,12),
    activating_product_margin_pre_return_excl_seeding_mtd number(38,12),
    activating_product_margin_pre_return_excl_seeding_mtd_ly number(38,12),
    activating_product_margin_pre_return_excl_seeding_month_tot_lm number(38,12),
    activating_product_margin_pre_return_excl_seeding_month_tot_ly number(38,12),
    nonactivating_product_margin_pre_return_excl_seeding number(38,12),
    nonactivating_product_margin_pre_return_excl_seeding_mtd number(38,12),
    nonactivating_product_margin_pre_return_excl_seeding_mtd_ly number(38,12),
    nonactivating_product_margin_pre_return_excl_seeding_month_tot_lm number(38,12),
    nonactivating_product_margin_pre_return_excl_seeding_month_tot_ly number(38,12),
    guest_product_margin_pre_return_excl_seeding number(38,12),
    guest_product_margin_pre_return_excl_seeding_mtd number(38,12),
    guest_product_margin_pre_return_excl_seeding_mtd_ly number(38,12),
    guest_product_margin_pre_return_excl_seeding_month_tot_lm number(38,12),
    guest_product_margin_pre_return_excl_seeding_month_tot_ly number(38,12),
    repeat_vip_product_margin_pre_return_excl_seeding number(38,12),
    repeat_vip_product_margin_pre_return_excl_seeding_mtd number(38,12),
    repeat_vip_product_margin_pre_return_excl_seeding_mtd_ly number(38,12),
    repeat_vip_product_margin_pre_return_excl_seeding_month_tot_lm number(38,12),
    repeat_vip_product_margin_pre_return_excl_seeding_month_tot_ly number(38,12),
    reactivated_vip_product_margin_pre_return_excl_seeding number(38,12),
    reactivated_vip_product_margin_pre_return_excl_seeding_mtd number(38,12),
    reactivated_vip_product_margin_pre_return_excl_seeding_mtd_ly number(38,12),
    reactivated_vip_product_margin_pre_return_excl_seeding_month_tot_lm number(38,12),
    reactivated_vip_product_margin_pre_return_excl_seeding_month_tot_ly number(38,12),
    activating_product_order_count_budget_alt number(19,7),
	nonactivating_product_order_count_budget_alt number(19,7),
	unit_count_budget_alt number(19,7),
	activating_unit_count_budget_alt number(19,7),
	nonactivating_unit_count_budget_alt number(19,7),
	return_shipping_costs_incl_reship_exch_budget_alt number(38,12),
	activating_product_gross_revenue_budget_alt number(38,12),
	nonactivating_product_gross_revenue_budget_alt number(38,12),
	activating_product_net_revenue_budget_alt number(38,12),
	nonactivating_product_net_revenue_budget_alt number(38,12),
	activating_product_margin_pre_return_budget_alt number(38,12),
	activating_product_gross_profit_budget_alt number(38,12),
	nonactivating_product_gross_profit_budget_alt number(38,12),
	nonactivating_product_order_cash_gross_revenue_budget_alt number(38,12),
	cash_gross_revenue_budget_alt number(38,12),
	cash_net_revenue_budget_alt number(38,12),
	activating_cash_net_revenue_budget_alt number(38,12),
	nonactivating_cash_net_revenue_budget_alt number(38,12),
	cash_gross_profit_budget_alt number(38,12),
	billed_credit_cash_transaction_amount_budget_alt number(38,12),
	billed_credit_cash_refund_chargeback_amount_budget_alt number(38,12),
	billed_cash_credit_redeemed_amount_budget_alt number(38,12),
	misc_cogs_amount_budget_alt number(38,12),
	nonactivating_product_order_cash_gross_profit_budget_alt number(19,7),
	cash_gross_profit_percent_of_net_cash_budget_alt number(19,7),
	product_order_and_billing_cash_refund_budget_alt number(38,12),
	product_order_and_billing_chargebacks_budget_alt number(38,12),
	refunds_plus_chargebacks_as_percent_of_cash_gross_rev_budget_alt number(19,7),
	activating_aov_budget_alt number(19,7),
	activating_upt_budget_alt number(19,7),
	activating_discount_percent_budget_alt number(19,7),
	activating_product_gross_profit_percent_budget_alt number(19,7),
	activating_product_margin_pre_return_per_order_budget_alt number(19,7),
	activating_product_margin_pre_return_percent_budget_alt number(19,7),
	nonactivating_aov_budget_alt number(38,12),
	nonactivating_upt_budget_alt number(19,7),
	nonactivating_discount_percent_budget_alt number(19,7),
	nonactivating_product_gross_profit_percent_budget_alt number(19,7),
	shipping_cost_incl_reship_exch_budget_alt number(38,12),
	shipping_supplies_cost_incl_reship_exch_budget_alt number(38,12),
	product_cost_calc_budget_alt number(38,12),
	product_order_cash_credit_refund_amount_budget_alt varchar(16777216),
	product_order_noncash_credit_refund_amount_budget_alt varchar(16777216),
	billing_order_transaction_count_budget_alt number(19,7),
	refund_cash_credit_redeemed_amount_budget_alt number(38,12),
	net_unredeemed_credit_billings_budget_alt number(38,12),
	leads_budget_alt number(19,7),
	new_vips_budget_alt number(19,7),
	new_vips_m1_budget_alt number(19,7),
	cancels_budget_alt number(19,7),
	bop_vips_budget_alt number(19,7),
	media_spend_budget_alt number(38,12),
	nonactivating_cash_gross_profit_budget_alt number(38,12),
	cash_contribution_after_media_budget_alt number(38,10),
	refund_cash_credit_issued_amount_budget_alt number(38,10),
	net_unredeemed_refund_credit_budget_alt number(38,10),
	membership_credits_redeemed_count_budget_alt number(38,0),
	membership_credits_cancelled_count_budget_alt number(38,0),
	product_order_reship_exch_order_count_budget_alt number(38, 0),
    cash_gift_card_redeemed_amount NUMBER(38, 10),
    activating_cash_gift_card_redeemed_amount NUMBER(38, 10),
    nonactivating_cash_gift_card_redeemed_amount NUMBER(38, 10),
    guest_cash_gift_card_redeemed_amount NUMBER(38, 10)
);
