CREATE TABLE snapshot.finance_sales_ops_comparison
(
	STORE_BRAND VARCHAR(20),
	STORE_COUNTRY VARCHAR(50),
	STORE_REGION VARCHAR(32),
	STORE_TYPE VARCHAR(20),
	GENDER VARCHAR(10),
	IS_RETAIL_VIP BOOLEAN,
	IS_CROSS_PROMO BOOLEAN,
	FINANCE_SPECIALTY_STORE VARCHAR(20),
	MEMBERSHIP_ORDER_TYPE_L3 VARCHAR(50),
	MONTH_DATE DATE,
	METRIC VARCHAR(80),
	CURRENT_SNAPSHOT_VALUE NUMBER(38,10),
	PREVIOUS_SNAPSHOT_VALUE NUMBER(38,10),
	VARIANCE NUMBER(38,10),
	CURRENT_SNAPSHOT_DATETIME TIMESTAMP_LTZ(9),
	PREVIOUS_SNAPSHOT_DATETIME TIMESTAMP_LTZ(9),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9),
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9),
	PRIMARY KEY (store_brand,store_country,store_region,store_type,gender,
	is_retail_vip,is_cross_promo,finance_specialty_store,membership_order_type_l3,month_date,metric)
);
