CREATE TABLE IF NOT EXISTS stg.lkp_order_classification (
	order_id NUMBER(38,0) NOT NULL,
	meta_original_order_id NUMBER(38,0),
	customer_id NUMBER(38,0),
	session_id NUMBER(38,0),
	order_local_datetime TIMESTAMP_TZ(3),
	order_status VARCHAR(50),
	is_activating BOOLEAN,
	is_guest BOOLEAN,
	is_billing_order BOOLEAN,
	is_membership_fee BOOLEAN,
	is_exchange BOOLEAN,
	is_reship BOOLEAN,
	is_retail_order BOOLEAN,
	is_border_free_order BOOLEAN,
	is_ps_order BOOLEAN,
	is_retail_ship_only_order BOOLEAN,
	is_test_order BOOLEAN,
	is_preorder BOOLEAN,
	is_product_seeding_order BOOLEAN,
	is_selected_order_type BOOLEAN,
	order_sales_channel VARCHAR(50),
	order_classification_name VARCHAR(50),
	is_bops_order BOOLEAN,
	original_order_id NUMBER(38,0),
	is_custom_order BOOLEAN,
	is_discreet_packaging BOOLEAN,
    is_amazon_order BOOLEAN,
    is_bill_me_now_online BOOLEAN DEFAULT FALSE,
	is_bill_me_now_gms BOOLEAN DEFAULT FALSE,
    is_membership_gift BOOLEAN DEFAULT FALSE,
    is_dropship BOOLEAN,
    is_warehouse_outlet_order BOOLEAN,
    is_third_party BOOLEAN,
    is_vip_membership_trial BOOLEAN DEFAULT FALSE,
    meta_row_hash NUMBER(38,0),
	meta_create_datetime TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(3),
	meta_update_datetime TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(3),
	primary key (ORDER_ID)
);
