CREATE TABLE IF NOT EXISTS stg.dim_order_sales_channel (
    order_sales_channel_key INT IDENTITY (1,1) NOT NULL,
    order_sales_channel_l1 VARCHAR(50) NOT NULL,
    order_sales_channel_l2 VARCHAR(50) NOT NULL,
    order_classification_l1 VARCHAR(50) NOT NULL,
    order_classification_l2 VARCHAR(50) NOT NULL,
    is_border_free_order BOOLEAN,
    is_ps_order BOOLEAN,
    is_retail_ship_only_order BOOLEAN,
    is_test_order BOOLEAN,
    is_preorder BOOLEAN,
    is_product_seeding_order BOOLEAN,
    is_bops_order BOOLEAN,
    is_custom_order BOOLEAN,
    is_discreet_packaging BOOLEAN,
    is_bill_me_now_online BOOLEAN,
    is_bill_me_now_gms BOOLEAN,
    is_membership_gift BOOLEAN,
    is_dropship BOOLEAN,
    is_warehouse_outlet_order BOOLEAN,
    is_third_party BOOLEAN,
    effective_start_datetime TIMESTAMP_LTZ,
    effective_end_datetime TIMESTAMP_LTZ,
    is_current BOOLEAN,
    meta_create_datetime TIMESTAMP_LTZ,
    meta_update_datetime TIMESTAMP_LTZ,
    PRIMARY KEY (order_sales_channel_key)
);
