create or replace TABLE STG.DIM_PRODUCT_TYPE (
	PRODUCT_TYPE_KEY NUMBER(38,0) autoincrement,
	PRODUCT_TYPE_ID NUMBER(38,0),
	PRODUCT_TYPE_NAME VARCHAR(50),
	IS_FREE BOOLEAN,
	SOURCE_IS_FREE BOOLEAN,
	EFFECTIVE_START_DATETIME TIMESTAMP_LTZ(9),
	EFFECTIVE_END_DATETIME TIMESTAMP_LTZ(9),
	IS_CURRENT BOOLEAN,
	META_ROW_HASH NUMBER(38,0),
	META_CREATE_DATETIME TIMESTAMP_LTZ(9),
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9),
	unique (PRODUCT_TYPE_KEY),
	primary key (PRODUCT_TYPE_ID)
);
