CREATE OR REPLACE TRANSIENT TABLE validation.dim_credit_comparison
(
    credit_id                             NUMBER(38, 0),
    store_id                              NUMBER(38, 0),
    customer_id                           NUMBER(38, 0),
    administrator_id                      NUMBER(38, 0),
    credit_order_id                       NUMBER(38, 0),
    source_credit_id_type                 VARCHAR(50),
    credit_report_mapping                 VARCHAR,
    credit_report_sub_mapping             VARCHAR,
    credit_type                           VARCHAR(50),
    credit_tender                         VARCHAR(50),
    credit_reason                         VARCHAR(50),
    credit_issuance_reason                VARCHAR(50),
    credit_issued_hq_datetime             TIMESTAMP_TZ(9),
    credit_issued_local_datetime          TIMESTAMP_TZ(9),
    original_credit_tender                VARCHAR(25),
    original_credit_type                  VARCHAR(25),
    original_credit_issued_local_datetime TIMESTAMP_TZ(9),
    original_credit_reason                VARCHAR(50),
    original_credit_match_reason          VARCHAR(50),
    deferred_recognition_label_token      VARCHAR(55),
    credit_issued_usd_conversion_rate     NUMBER(18, 6),
    credit_issued_local_gross_vat_amount  NUMBER(19, 4),
    credit_issued_equivalent_count        NUMBER(30, 4),
    credit_issued_local_amount            NUMBER(19, 4),
    meta_create_datetime                  TIMESTAMP_LTZ(3),
    meta_update_datetime                  TIMESTAMP_LTZ(3)
);
