CREATE OR REPLACE TRANSIENT TABLE validation.fl_scrubs_product_taxonomy
(
    PRODUCT_ID NUMBER(38,0),
    META_ORIGINAL_PRODUCT_ID NUMBER(38,0),
    MASTER_PRODUCT_ID NUMBER(38,0),
    STORE_ID NUMBER(38,0),
    PRODUCT_ALIAS VARCHAR(100),
    PRODUCT_SKU VARCHAR(30),
    SKU VARCHAR(30),
    PRODUCT_NAME VARCHAR(100),
    DEPARTMENT VARCHAR(100),
    CATEGORY VARCHAR(3000),
    CURRENT_SHOWROOM_DATE DATE,
	META_CREATE_DATETIME TIMESTAMP_LTZ(9),
	META_UPDATE_DATETIME TIMESTAMP_LTZ(9)
);
