CREATE TABLE IF NOT EXISTS VALIDATION.FACT_CREDIT_EVENT_HISTORICAL_SNAPSHOT_COMPARISON (
	CREDIT_STORE_ID NUMBER(38,0),
	REDEMPTION_STORE_ID NUMBER(38,0),
	CREDIT_ACTIVITY_LOCAL_DATE DATE,
	METRIC VARCHAR(16777216),
	CURRENT_SNAPSHOT_VALUE NUMBER(38,10),
	PREVIOUS_SNAPSHOT_VALUE NUMBER(38,10),
	VARIANCE NUMBER(38,10),
	CURRENT_SNAPSHOT_DATETIME TIMESTAMP_NTZ(9),
	PREVIOUS_SNAPSHOT_DATETIME VARCHAR(16777216),
	META_CREATE_DATETIME TIMESTAMP_LTZ(3),
	META_UPDATE_DATETIME TIMESTAMP_LTZ(3),
	CREDIT_ACTIVITY_TYPE VARCHAR(60)
);
