CREATE TABLE REPORTING.SEGMENT_API_VOLUME(
REPORT_DATE DATE,
SOURCE VARCHAR(50),
STORE_BRAND VARCHAR(50),
STORE_COUNTRY VARCHAR(10),
ENVIRONMENT VARCHAR(10),
API_CALL  VARCHAR(100),
VOLUME NUMBER(38,0),
META_ROW_HASH NUMBER(23,0),
META_CREATE_DATETIME	TIMESTAMP_LTZ(9),
META_UPDATE_DATETIME	TIMESTAMP_LTZ(9)
);
